### PR TITLE
[BugFix]Fix starrocks can not query hive external table when hive decimal type change

### LINKED ISSUE #19803: when hive schema change, starrocks can not query hive external table
### Steps to reproduce the behavior (Required)
1. hive
   create table t_decimal(id int, score decimal(18,4)) stored as orc;
   insert into test.t_decimal values (1, 18.0012);
   alter table test.t_decimal change column score score decimal(18,5);
   insert into test.t_decimal values (1, 17.00122);
2. starrocks
  select * from  hive_catalog.test.t_decimal;
### Expected behavior (Required)
return correct result
### Real behavior (Required)
ERROR 1064 (HY000): Type mismatch: orc DECIMAL64(18, 4) to native DECIMAL64(18, 5). file = part-00000-c7e950a3-112e-4d24-997d-dd8b7a083583-c000.snappy.orc
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19803

## Problem Summary(Required) ：

when hive decimal schema change, select return result
image

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/runtime/types.h [hunk 1]
```diff
@@ -225,7 +225,7 @@ struct TypeDescriptor {
 
     bool is_implicit_castable(const TypeDescriptor& from) const {
         if (is_decimal_type()) {
-            return precision == from.precision && scale == from.scale;
+            return true;
```
Comment (dirtysalt) [inline be/src/runtime/types.h:228]: I suggest to remove this function and just put this implementation at orc level.

Because that castable only works in orc scenario.

**Review by dirtysalt — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-2.5
