### PR TITLE
[BugFix] Fix set statement miss user define variable and system variable syntax bug

### LINKED ISSUE #9383: Set statement report syntax error
### Steps to reproduce the behavior (Required)
 set @@query_timeout = 10;

### Expected behavior (Required)
success
### Real behavior (Required)
syntax error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9383

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 27 / 30 (90.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|27|30|90.00%|[2327, 2334, 2338]|

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java [hunk 1]
```diff
@@ -2296,19 +2296,49 @@ public ParseNode visitAdminSetConfig(StarRocksParser.AdminSetConfigContext conte
...
+        if (context.AT().isEmpty()) {
+            Expr expr = (Expr) visit(context.setExprOrDefault());
+            String variable = ((Identifier) visit(context.identifier())).getValue();
+            if (context.varType() != null) {
+                return new SetVar(getVariableType(context.varType()), variable, expr);
+            } else {
+                return new SetVar(variable, expr);
+            }
+        } else if (context.AT().size() == 1) {
+            Expr expr = (Expr) visit(context.expression());
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:2315]: I'm not familiar with it, could you explain why one `@` calling `context.expression()` while zero or two `@` calling `context.setExprOrDefault()`

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
