### PR TITLE
[BugFix] Fix invalid max column unique id introduced by version compatibility for cloud-native table

### LINKED ISSUE #57850: 3.3.8 cloud-native cluster CN crashed with local pk index
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)

```sh
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/starrocks/be/lib/starrocks_be --cn'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000810800d in google::protobuf::Message::SpaceUsedLong() const ()
Missing separate debuginfos, use: debuginfo-install glibc-2.17-317.el7.x86_64 java-1.8.0-openjdk-headless-1.8.0.412.b08-1.el7_9.x86_64 libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64 numactl-libs-2.0.12-5.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x000000000810800d in google::protobuf::Message::SpaceUsedLong() const ()
#1  0x00000000067e8420 in starrocks::ColumnReader::_init(starrocks::ColumnMetaPB*, starrocks::TabletColumn const*) ()
#2  0x00000000067e9d8b in starrocks::ColumnReader::create(starrocks::ColumnMetaPB*, starrocks::Segment*, starrocks::TabletColumn const*) ()
#3  0x000000000618473b in starrocks::Segment::_create_column_readers(starrocks::SegmentFooterPB*) ()
#4  0x0000000006185e04 in starrocks::Segment::_open(unsigned long*, starrocks::FooterPointerPB const*, starrocks::LakeIOOptions const&) ()
#5  0x0000000006186581 in starrocks::Segment::open(unsigned long*, starrocks::FooterPointerPB const*, starrocks::LakeIOOptions const&) ()
#6  0x000000000632a239 in starrocks::lake::TabletManager::load_segment(starrocks::FileInfo const&, int, unsigned long*, starrocks::LakeIOOptions const&, bool, std::shared_ptr<starrocks::TabletSchema const>) ()
#7  0x00000000063182e4 in starrocks::lake::Rowset::load_segments(std::vector<std::shared_ptr<starrocks::Segment>, std::allocator<std::shared_ptr<starrocks::Segment> > >*, starrocks::LakeIOOptions const&, bool, std::pair<std::vector<std::shared_ptr<starrocks::Segment>, std::allocator<std::shared_ptr<starrocks::Segment> > >, std::vector<std::shared_ptr<starrocks::Segment>, std::allocator<std::shared_ptr<starrocks::Segment> > > >*) ()
#8  0x000000000631d6e5 in starrocks::lake::Rowset::get_each_segment_iterator_with_delvec(starrocks::Schema const&, long, starrocks::lake::MetaFileBuilder const*, starrocks::OlapReaderStatistics*) ()
#9  0x00000000063a2427 in starrocks::lake::LakeLocalPersistentIndexTabletLoader::rowset_iterator(starrocks::Schema const&, std::function<starrocks::Status (std::vector<std::shared_ptr<starrocks::ChunkIterator>, std::allocator<std::shared_ptr<starrocks::ChunkIterator> > > const&, unsigned int)> const&) ()
#10 0x000000000647898a in starrocks::PersistentIndex::_insert_rowsets(starrocks::TabletLoader*, starrocks::Schema const&, std::unique_ptr<starrocks::Column, std::default_delete<starrocks::Column> >) ()
#11 0x00000000064877a8 in starrocks::PersistentIndex::_load_by_loader(starrocks::TabletLoader*) ()
#12 0x000000000639ef60 in starrocks::lake::LakeLocalPersistentIndex::load_from_lake_tablet(starrocks::lake::TabletManager*, std::shared_ptr<starrocks::TabletMetadataPB const> const&, long, starrocks::lake::MetaFileBuilder const*) ()
#13 0x0000000006375757 in starrocks::lake::LakePrimaryIndex::_do_lake_load(starrocks::lake::TabletManager*, std::shared_ptr<starrocks::TabletMetadataPB const> const&, long, starrocks::lake::MetaFileBuilder const*) ()
#14 0x0000000006375eaf in starrocks::lake::LakePrimaryIndex::lake_load(starrocks::lake::TabletManager*, std::shared_ptr<starrocks::TabletMetadataPB const> const&, long, starrocks::lake::MetaFileBuilder const*) ()
#15 0x0000000006353c84 in starrocks::lake::UpdateManager::prepare_primary_index(std::shared_ptr<starrocks::TabletMetadataPB const> const&, starrocks::lake::MetaFileBuilder*, long, long, std::unique_ptr<std::lock_guard<std::shared_timed_mutex>, std::default_delete<std::lock_guard<std::shared_timed_mutex> > >&) ()
#16 0x00000000063988dc in starrocks::lake::PrimaryKeyTxnLogApplier::apply_write_log(starrocks::TxnLogPB_OpWrite const&, long) ()
#17 0x0000000006398a60 in std::_Function_handler<starrocks::Status (), starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#18 0x0000000006398d05 in starrocks::lake::PrimaryKeyTxnLogApplier::check_and_recover(std::function<starrocks::Status ()> const&) ()
#19 0x000000000639b63e in starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&) ()
#20 0x0000000006344fa2 in starrocks::lake::publish_version(starrocks::lake::TabletManager*, long, long, long, std::span<starrocks::TxnInfoPB const, 18446744073709551615ul>) ()
#21 0x00000000037eaccb in starrocks::LakeServiceImpl::publish_version(google::protobuf::RpcController*, starrocks::PublishVersionRequest const*, starrocks::PublishVersionResponse*, google::protobuf::Closure*)::{lambda()#1}::operator()() const ()
#22 0x00000000037edbaa in std::_Function_handler<void (), starrocks::ConcurrencyLimitedThreadPoolToken::submit_func(std::function<void ()>, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#23 0x000000000388cc83 in starrocks::ThreadPool::dispatch_thread() ()
#24 0x00000000038856e6 in starrocks::Thread::supervise_thread(void*) ()
#25 0x00007f4748407ea5 in start_thread () from /lib64/libpthread.so.0
#26 0x00007f47470fe96d in clone () from /lib64/libc.so.6
```

### StarRocks version (Required)
 - 3.3.8

### PR DESCRIPTION
**Pull request by wxl24life**
## Why I'm doing:

When upgrade and downgrade between  v3.2 and v3.3, there are chances column unique id has unexpected values. Some efforts have been tried to solve those problems, such as #48628 #47826 #58164 .

Bad luck, there are still other bad cases relative to column unique id. Issue #57850 mentioned a CN crash issue.

The direct reason for that crash is duplicate unique id found in tablet meta, looks like this one (omitted unrelated properties here).
```json
 {
         [
           {
                "unique_id": 5,
                "name": "t_col_329",
                "type": "BIGINT"
            },
            {
                "unique_id": 6,
                "name": "t_col_329_1",
                "type": "BIGINT"
            },
            {
                "unique_id": 6,
                "name": "t_col_329_2",
                "type": "BIGINT"
            }
        ],
        "next_column_unique_id": 8,
    },
```

We can see that last two columns have same unique ids. 

Further investigation revealed that the cause of the duplicate unique ID issue is related to version upgrades and downgrades. And The problem can be reproduced in the following way:

1. Create a table on v3.3 cluster
```sql
create database test;
use test;
CREATE TABLE `t_user` (
  `id` bigint(20) NOT NULL COMMENT "",
  `name` varchar(765) NULL COMMENT "",
  `age` tinyint(4) NULL COMMENT "",
  `create_time` datetime NULL COMMENT "",
  `update_time` datetime NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
"compression" = "LZ4",
"datacache.enable" = "true",
"enable_async_write_back" = "false",
"enable_persistent_index" = "true",
"persistent_index_type" = "CLOUD_NATIVE",
"replication_num" = "1",
"fast_schema_evolution"="false",
"storage_volume" = "builtin_storage_volume"
);
```

2. Downgrade the cluster from v3.3 to v3.2, then do alter statement.
```sql
alter table t_user add column (`t_col` bigint(20));
```
3. Upgrade from v3.2 to v3.3 again, the max unique id is wrong
4. Do alter statement again, then table meta will have duplicate unique ids.

## What I'm doing:

Fixes #57850

1. Prevent CN crash by adding tablet meta column uniqueness check in BE, if duplicate id found, we will stop user from query this tablet.
```sql
select * from t_user;
ERROR 1064 (HY000): load_segments failed tablet:15023 rowset:1 segid:0: Duplicate column id found in tablet schema: BE:10001`
```

2. Try to restore column unique id while upgrading and downgrading version happend.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 1]
```diff
@@ -206,6 +206,57 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
...
+    /**
+     * For tables created in the old version of StarRocks cluster, such as v3.2, the column unique id in FE might
+     * have default value -1. When upgrading from old version to v3.3 upwards, the unique id of columns might introduce
+     * compatibility issues. This method is used to check if the table needs to restore the column unique id.
+     */
+    private static boolean needRestoreColumnUniqueId(OlapTable table) {
+        boolean needRestore = false;
+        for (MaterializedIndexMeta indexMeta : table.getIndexIdToMeta().values()) {
+            List<Column> columns = indexMeta.getSchema();
+            needRestore = hasNegativeUniqueId(columns);
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:246]: needRestore will be overwrite

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:246]: 👍 ok, here we can `break`

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 2]
```diff
@@ -206,6 +206,57 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
...
+            LOG.info("Table {}'s column unique id has been restored, maxColUniqueId is: {}", table.getName(), maxId);
+        }
+    }
+
+    /**
+     * For tables created in the old version of StarRocks cluster, such as v3.2, the column unique id in FE might
+     * have default value -1. When upgrading from old version to v3.3 upwards, the unique id of columns might introduce
+     * compatibility issues. This method is used to check if the column list need to restore their column unique id.
+     */
+    public static void restoreColumnUniqueId(String tableName, long indexId, List<Column> columns) {
```
[the remark this answers is not in the document]
Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:225]: Yes

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 3]
```diff
@@ -206,6 +206,57 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
...
+    private static boolean needRestoreColumnUniqueId(OlapTable table) {
+        boolean needRestore = false;
+        for (MaterializedIndexMeta indexMeta : table.getIndexIdToMeta().values()) {
+            List<Column> columns = indexMeta.getSchema();
+            needRestore = hasNegativeUniqueId(columns);
+        }
+        return needRestore;
+    }
+
+    private static boolean hasNegativeUniqueId(List<Column> columns) {
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:251]:
```suggestion
    private static boolean hasInvalidUniqueId(List<Column> columns) {
```

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (xiangguangyxg) [reply fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:225]: not a good style, you can add a return value and print logs in the caller code.

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 4]
```diff
@@ -206,6 +206,57 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
         return !path.endsWith(String.format("/%d", physicalPartitionId));
     }
 
+    /**
+     * For version compatibility reason, we should restore column unique id and table's max unique id if needed.
+     */
+    public static void restoreColumnUniqueIdPostLoadImage(OlapTable table) {
+        if (needRestoreColumnUniqueId(table)) {
+            int maxId = LakeTableHelper.restoreColumnUniqueId(table);
+            table.setMaxColUniqueId(maxId);
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:215]: this max unique id assignment should be removed, because it will be assigned in OlapTable.gsonPostProcess()

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 5]
```diff
@@ -206,6 +206,57 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
         return !path.endsWith(String.format("/%d", physicalPartitionId));
     }
 
+    /**
+     * For version compatibility reason, we should restore column unique id and table's max unique id if needed.
+     */
+    public static void restoreColumnUniqueIdPostLoadImage(OlapTable table) {
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:212]:
```suggestion
    public static boolean restoreColumnUniqueId(OlapTable table) {
```

Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:212]:
```suggestion
    public static boolean restoreColumnUniqueId(OlapTable table) {
```

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java (hunk 2 above)
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:225]:
```suggestion
    public static boolean restoreColumnUniqueId(List<Column> columns) {
```

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 6]
```diff
@@ -206,6 +206,52 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
...
 
+    /**
+     * For tables created in the old version of StarRocks cluster, such as v3.2, the column unique id in FE might
+     * have default value -1. When upgrading from old version to v3.3 upwards, the unique id of columns might introduce
+     * compatibility issues. This method is used to check if the table needs to restore the column unique id.
+     */
+    public static void restoreColumnUniqueIdIfNeeded(OlapTable table) {
+        boolean needRestore = false;
+        for (MaterializedIndexMeta indexMeta : table.getIndexIdToMeta().values()) {
+            List<Column> columns = indexMeta.getSchema();
```
Comment (smartlxh) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:217]: Just call `restoreColumnUniqueIdIfNeeded(columns)` directly? Is there necessary to call  `LakeTableHelper.restoreColumnUniqueId(table);`?

File: fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java [hunk 7]
```diff
@@ -206,6 +206,52 @@ public static boolean isSharedDirectory(String path, long physicalPartitionId) {
...
+            if (hasInvalidUniqueId(columns)) {
+                needRestore = true;
+                break;
+            }
+        }
+        if (needRestore) {
+            restoreColumnUniqueId(table);
+            LOG.info("Column unique ids in table {} have been restored", table.getName());
+        }
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:226]: the variable `needRestore` could be removed, move this code to line 220 (`break;`)

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/lake/LakeTableHelper.java:226]: but i think the current manner might be more clear?

**Review by xiangguangyxg — APPROVED** [review]

**Review by smartlxh — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by luohaha — APPROVED** [review]
