### PR TITLE
[BugFix] string_to_float_internal may lose some precision

### LINKED ISSUE #9633: BrokerLoad will lose some precision when loading double data
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `table1` ( `k1` date, `v6` float, `v7` double) ENGINE=OLAP DUPLICATE KEY(`k1`) 
COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`) BUCKETS 1 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
2. prepare csv
2020-06-23      -1.4    -2.97
3. broker load
4. SELECT  * from table1

### Expected behavior (Required)
+------------+------+---------------------+
| k1         | v6   | v7                  |
+------------+------+---------------------+
| 2020-06-23 | -1.4 |               -2.97 |
+------------+------+---------------------+
### Real behavior (Required)
+------------+------+---------------------+
| k1         | v6   | v7                  |
+------------+------+---------------------+
| 2020-06-23 | -1.4 | -2.9699999999999998 |
+------------+------+---------------------+
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
5454a8c

### PR DESCRIPTION
**Pull request by xiaoyong-z**
For 2.97, string_to_float_internal will calculated by 2 + 97 / 100, which is 2.9699999999999998,
acutulay it should be calculated by by 297 / 100, which is 2.970000000002

Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9633

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

File: be/src/util/string_parser.hpp [hunk 1]
```diff
@@ -463,11 +464,23 @@ inline T StringParser::string_to_float_internal(const char* s, int len, ParseRes
                 // overflowing 'remainder' (we stop after 18 instead of 17 to get the rounding
                 // right).
                 if (sig_figs <= 18) {
-                    remainder = remainder * 10 + s[i] - '0';
-                    divide *= 10;
+                    if (LIKELY(acc_num < 63)) {
```
Comment (chaoyli) [inline be/src/util/string_parser.hpp:467]: The modification will change the logic in cast_expr.cpp. I think we should be more test.

**Comment by stdpain** [comment]
how about using std::from_chars instead of this ? https://en.cppreference.com/w/cpp/utility/from_chars

**Comment by stdpain** [comment]
It seems only GCC11 implements from_chars to float. 

we can try ryu_parse to parse string to float. https://github.com/ulfjack/ryu/blob/master/ryu/ryu_parse.h 
we had Introduced this lib

**Comment by xiaoyong-z** [comment]
> It seems only GCC11 implements from_chars to float.
> 
> we can try ryu_parse to parse string to float. https://github.com/ulfjack/ryu/blob/master/ryu/ryu_parse.h we had Introduced this lib

ryu_parser seems to be only an experimental implementation, it doesn't support -E, -i etc...
```cpp
// This is an experimental implementation of parsing strings to 64-bit floats
// using a Ryu-like algorithm. At this time, it only support up to 17 non-zero
// digits in the input, and also does not support all formats. Use at your own
// risk.
//
// This implementation does not currently support -DRYU_OPTIMIZE_SIZE and always
// compiles against the large lookup tables.

enum Status s2d_n(const char * buffer, const int len, double * result);
enum Status s2d(const char * buffer, double * result);

enum Status s2f_n(const char * buffer, const int len, float * result);
enum Status s2f(const char * buffer, float * result);
```

**Comment by xiaoyong-z** [comment]
a comment in our string_to_float_internal
```txt
    // This is considerably faster than glibc's implementation (>100x why???)
    // No special case handling needs to be done for overflows, the floating point spec
    // already does it and will cap the values to -inf/inf
    // To avoid inaccurate conversions this function falls back to strtod for
    // scientific notation.
    // Return PARSE_FAILURE on leading whitespace. Trailing whitespace is allowed.
    // TODO: Investigate using intrinsics to speed up the slow strtod path.
    template <typename T>
    static inline T string_to_float_internal(const char* s, int len, ParseResult* result);
```

**Comment by stdpain** [comment]
The current implementation seems to have too much duplicated code. Not very easy to maintain

**Comment by xiaoyong-z** [comment]
speed test
```txt

[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark 
# parsing random numbers
available models (-m): uniform one_over_rand32 simple_uniform32 simple_int32 int_e_int simple_int64 bigint_int_dot_int big_ints 
model: generate random numbers uniformly in the interval [0.0,1.0]
volume: 100000 floats
volume = 0.0524521 MB 
netlib                                  :   182.96 MB/s (+/- 1.0 %)     8.72 Mfloat/s      30.10 i/B   662.09 i/f (+/- 0.0 %)      0.17 bm/B     3.72 bm/f (+/- 1.3 %)     16.62 c/B   365.62 c/f (+/- 1.0 %)      1.81 i/c      3.19 GHz 
doubleconversion                        :   182.01 MB/s (+/- 1.2 %)     8.67 Mfloat/s      48.42 i/B  1065.14 i/f (+/- 0.0 %)      0.07 bm/B     1.60 bm/f (+/- 0.6 %)     16.72 c/B   367.76 c/f (+/- 1.1 %)      2.90 i/c      3.19 GHz 
strtod                                  :   123.12 MB/s (+/- 1.4 %)     5.87 Mfloat/s      54.92 i/B  1208.30 i/f (+/- 0.0 %)      0.13 bm/B     2.86 bm/f (+/- 0.4 %)     24.70 c/B   543.41 c/f (+/- 1.0 %)      2.22 i/c      3.19 GHz 
starrocks                               :    98.31 MB/s (+/- 0.9 %)     4.69 Mfloat/s      74.08 i/B  1629.80 i/f (+/- 0.0 %)      0.14 bm/B     3.12 bm/f (+/- 0.4 %)     30.98 c/B   681.66 c/f (+/- 0.7 %)      2.39 i/c      3.19 GHz 
clickhouse                              :   596.78 MB/s (+/- 3.9 %)    28.44 Mfloat/s      17.38 i/B   382.34 i/f (+/- 0.0 %)      0.01 bm/B     0.20 bm/f (+/- 7.9 %)      5.09 c/B   111.93 c/f (+/- 3.9 %)      3.42 i/c      3.18 GHz 
fastfloat                               :   723.33 MB/s (+/- 2.7 %)    34.48 Mfloat/s      14.09 i/B   310.05 i/f (+/- 0.0 %)      0.00 bm/B     0.01 bm/f (+/- 18.3 %)      4.20 c/B    92.43 c/f (+/- 2.7 %)      3.35 i/c      3.19 GHz 
# You can also provide a filename (with the -f flag): it should contain one string per line corresponding to a number
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -c
# parsing random numbers
available models (-m): uniform one_over_rand32 simple_uniform32 simple_int32 int_e_int simple_int64 bigint_int_dot_int big_ints 
model: generate random numbers uniformly in the interval [0.0,1.0]
concise (using as few digits as possible)
volume: 100000 floats
volume = 0.0435523 MB 
netlib                                  :   167.00 MB/s (+/- 0.5 %)     9.59 Mfloat/s      32.67 i/B   596.85 i/f (+/- 0.0 %)      0.20 bm/B     3.71 bm/f (+/- 0.4 %)     18.18 c/B   332.18 c/f (+/- 0.5 %)      1.80 i/c      3.18 GHz 
doubleconversion                        :   164.71 MB/s (+/- 1.1 %)     9.45 Mfloat/s      51.95 i/B   948.98 i/f (+/- 0.0 %)      0.09 bm/B     1.65 bm/f (+/- 2.1 %)     18.44 c/B   336.78 c/f (+/- 0.6 %)      2.82 i/c      3.18 GHz 
strtod                                  :   105.42 MB/s (+/- 0.9 %)     6.05 Mfloat/s      60.28 i/B  1101.13 i/f (+/- 0.0 %)      0.20 bm/B     3.57 bm/f (+/- 0.9 %)     28.82 c/B   526.46 c/f (+/- 0.8 %)      2.09 i/c      3.19 GHz 
starrocks                               :   419.16 MB/s (+/- 10.6 %)    24.06 Mfloat/s      21.48 i/B   392.47 i/f (+/- 0.0 %)      0.02 bm/B     0.46 bm/f (+/- 18.1 %)      7.26 c/B   132.56 c/f (+/- 10.2 %)      2.96 i/c      3.19 GHz 
clickhouse                              :   481.75 MB/s (+/- 1.5 %)    27.65 Mfloat/s      18.48 i/B   337.54 i/f (+/- 0.0 %)      0.05 bm/B     0.96 bm/f (+/- 5.8 %)      6.31 c/B   115.27 c/f (+/- 1.5 %)      2.93 i/c      3.19 GHz 
fastfloat                               :   666.01 MB/s (+/- 3.0 %)    38.23 Mfloat/s      13.28 i/B   242.64 i/f (+/- 0.0 %)      0.03 bm/B     0.62 bm/f (+/- 0.5 %)      4.57 c/B    83.46 c/f (+/- 2.8 %)      2.91 i/c      3.19 GHz 
# You can also provide a filename (with the -f flag): it should contain one string per line corresponding to a number
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/canada.txt 
# read 111126 lines 
volume = 0.0483436 MB 
netlib                                  :   190.23 MB/s (+/- 1.7 %)    10.93 Mfloat/s      31.91 i/B   582.25 i/f (+/- 0.0 %)      0.13 bm/B     2.31 bm/f (+/- 0.5 %)     15.99 c/B   291.83 c/f (+/- 1.6 %)      2.00 i/c      3.19 GHz 
doubleconversion                        :   173.05 MB/s (+/- 0.7 %)     9.94 Mfloat/s      53.96 i/B   984.52 i/f (+/- 0.0 %)      0.05 bm/B     1.00 bm/f (+/- 1.1 %)     17.58 c/B   320.74 c/f (+/- 0.6 %)      3.07 i/c      3.19 GHz 
strtod                                  :    95.94 MB/s (+/- 0.9 %)     5.51 Mfloat/s      72.59 i/B  1324.55 i/f (+/- 0.0 %)      0.12 bm/B     2.19 bm/f (+/- 1.2 %)     31.69 c/B   578.24 c/f (+/- 0.9 %)      2.29 i/c      3.19 GHz 
starrocks                               :   457.37 MB/s (+/- 0.3 %)    26.28 Mfloat/s      20.81 i/B   379.79 i/f (+/- 0.0 %)      0.01 bm/B     0.18 bm/f (+/- 2.0 %)      6.65 c/B   121.33 c/f (+/- 0.2 %)      3.13 i/c      3.19 GHz 
clickhouse                              :   579.82 MB/s (+/- 1.1 %)    33.32 Mfloat/s      18.29 i/B   333.75 i/f (+/- 0.0 %)      0.02 bm/B     0.29 bm/f (+/- 2.3 %)      5.24 c/B    95.70 c/f (+/- 1.0 %)      3.49 i/c      3.19 GHz 
fastfloat                               :   590.34 MB/s (+/- 2.1 %)    33.92 Mfloat/s      17.50 i/B   319.24 i/f (+/- 0.0 %)      0.01 bm/B     0.11 bm/f (+/- 4.8 %)      5.15 c/B    93.95 c/f (+/- 2.0 %)      3.40 i/c      3.19 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/mesh.txt 
# read 73019 lines 
volume = 0.0134002 MB 
netlib                                  :   222.24 MB/s (+/- 2.0 %)    30.28 Mfloat/s      32.66 i/B   251.39 i/f (+/- 0.0 %)      0.08 bm/B     0.64 bm/f (+/- 1.1 %)     13.66 c/B   105.15 c/f (+/- 2.0 %)      2.39 i/c      3.18 GHz 
doubleconversion                        :   185.63 MB/s (+/- 0.6 %)    25.29 Mfloat/s      53.89 i/B   414.83 i/f (+/- 0.0 %)      0.03 bm/B     0.21 bm/f (+/- 2.2 %)     16.39 c/B   126.13 c/f (+/- 0.5 %)      3.29 i/c      3.19 GHz 
strtod                                  :    90.08 MB/s (+/- 0.7 %)    12.27 Mfloat/s      87.88 i/B   676.47 i/f (+/- 0.0 %)      0.10 bm/B     0.78 bm/f (+/- 0.9 %)     33.76 c/B   259.85 c/f (+/- 0.6 %)      2.60 i/c      3.19 GHz 
starrocks                               :   391.65 MB/s (+/- 2.3 %)    53.35 Mfloat/s      23.70 i/B   182.40 i/f (+/- 0.0 %)      0.02 bm/B     0.15 bm/f (+/- 11.8 %)      7.77 c/B    59.78 c/f (+/- 2.2 %)      3.05 i/c      3.19 GHz 
clickhouse                              :   457.31 MB/s (+/- 84.7 %)    62.30 Mfloat/s      23.57 i/B   181.42 i/f (+/- 0.0 %)      0.02 bm/B     0.13 bm/f (+/- 6.1 %)      6.65 c/B    51.20 c/f (+/- 83.8 %)      3.54 i/c      3.19 GHz 
fastfloat                               :   421.63 MB/s (+/- 53.7 %)    57.44 Mfloat/s      24.51 i/B   188.67 i/f (+/- 0.0 %)      0.01 bm/B     0.10 bm/f (+/- 1.8 %)      7.20 c/B    55.41 c/f (+/- 52.9 %)      3.41 i/c      3.18 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ 
```

**Comment by xiaoyong-z** [comment]
choose fastfloat here, it is precise, no precision loss

**Comment by xiaoyong-z** [comment]
https://github.com/lemire/simple_fastfloat_benchmark

**Comment by xiaoyong-z** [comment]
https://github.com/fastfloat/fast_float

**Comment by xiaoyong-z** [comment]
some discussions in clickhouse: https://github.com/ClickHouse/ClickHouse/pull/16787

**Comment by xiaoyong-z** [comment]
extension test:
```txt
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers1.tsv 
# read 10000 lines 
volume = 0.00092721 MB 
netlib                                  :   275.44 MB/s (+/- 0.7 %)    74.27 Mfloat/s      39.63 i/B   154.13 i/f (+/- 0.0 %)      0.03 bm/B     0.11 bm/f (+/- 1.9 %)     11.08 c/B    43.10 c/f (+/- 0.4 %)      3.58 i/c      3.20 GHz 
doubleconversion                        :   132.50 MB/s (+/- 1.3 %)    35.73 Mfloat/s      81.78 i/B   318.05 i/f (+/- 0.0 %)      0.03 bm/B     0.12 bm/f (+/- 2.2 %)     23.03 c/B    89.58 c/f (+/- 0.9 %)      3.55 i/c      3.20 GHz 
strtod                                  :    87.06 MB/s (+/- 0.6 %)    23.47 Mfloat/s     120.43 i/B   468.33 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 25.6 %)     35.06 c/B   136.33 c/f (+/- 0.3 %)      3.44 i/c      3.20 GHz 
starrocks                               :   355.75 MB/s (+/- 0.4 %)    95.92 Mfloat/s      27.75 i/B   107.91 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 26.2 %)      8.58 c/B    33.38 c/f (+/- 0.1 %)      3.23 i/c      3.20 GHz 
clickhouse                              :   411.96 MB/s (+/- 0.5 %)   111.08 Mfloat/s      29.75 i/B   115.69 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 9.5 %)      7.41 c/B    28.83 c/f (+/- 0.1 %)      4.01 i/c      3.20 GHz 
fastfloat                               :   265.41 MB/s (+/- 1.0 %)    71.56 Mfloat/s      42.12 i/B   163.80 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 24.7 %)     11.50 c/B    44.73 c/f (+/- 0.6 %)      3.66 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers2.tsv 
# read 10000 lines 
volume = 0.000238419 MB 
netlib                                  :   110.48 MB/s (+/- 1.5 %)   115.84 Mfloat/s     108.22 i/B   108.22 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 17.9 %)     27.64 c/B    27.64 c/f (+/- 0.9 %)      3.92 i/c      3.20 GHz 
doubleconversion                        :    49.59 MB/s (+/- 1.9 %)    52.00 Mfloat/s     221.52 i/B   221.52 i/f (+/- 0.0 %)      0.10 bm/B     0.10 bm/f (+/- 1.4 %)     61.56 c/B    61.56 c/f (+/- 1.4 %)      3.60 i/c      3.20 GHz 
strtod                                  :    27.55 MB/s (+/- 1.5 %)    28.89 Mfloat/s     376.12 i/B   376.12 i/f (+/- 0.0 %)      0.10 bm/B     0.10 bm/f (+/- 8.7 %)    110.79 c/B   110.79 c/f (+/- 1.2 %)      3.39 i/c      3.20 GHz 
starrocks                               :   201.84 MB/s (+/- 0.5 %)   211.64 Mfloat/s      53.02 i/B    53.02 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 22.8 %)     15.13 c/B    15.13 c/f (+/- 0.1 %)      3.50 i/c      3.20 GHz 
clickhouse                              :   132.55 MB/s (+/- 0.7 %)   138.99 Mfloat/s      81.02 i/B    81.02 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 23.3 %)     23.04 c/B    23.04 c/f (+/- 0.2 %)      3.52 i/c      3.20 GHz 
fastfloat                               :    80.25 MB/s (+/- 0.9 %)    84.14 Mfloat/s     132.02 i/B   132.02 i/f (+/- 0.0 %)      0.00 bm/B     0.00 bm/f (+/- 26.3 %)     38.05 c/B    38.05 c/f (+/- 0.4 %)      3.47 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers3.tsv 
# read 10000 lines 
volume = 0.00116539 MB 
netlib                                  :   202.35 MB/s (+/- 2.7 %)    43.41 Mfloat/s      42.02 i/B   205.38 i/f (+/- 0.0 %)      0.03 bm/B     0.14 bm/f (+/- 16.9 %)     15.09 c/B    73.74 c/f (+/- 2.2 %)      2.79 i/c      3.20 GHz 
doubleconversion                        :   149.23 MB/s (+/- 3.5 %)    32.01 Mfloat/s      73.11 i/B   357.37 i/f (+/- 0.0 %)      0.02 bm/B     0.10 bm/f (+/- 0.8 %)     20.45 c/B    99.97 c/f (+/- 3.1 %)      3.57 i/c      3.20 GHz 
strtod                                  :    42.14 MB/s (+/- 1.4 %)     9.04 Mfloat/s     162.44 i/B   794.03 i/f (+/- 0.0 %)      0.14 bm/B     0.68 bm/f (+/- 4.4 %)     72.22 c/B   353.04 c/f (+/- 1.3 %)      2.25 i/c      3.19 GHz 
starrocks                               :   370.06 MB/s (+/- 1.8 %)    79.39 Mfloat/s      25.16 i/B   122.99 i/f (+/- 0.0 %)      0.03 bm/B     0.14 bm/f (+/- 7.3 %)      8.25 c/B    40.33 c/f (+/- 1.3 %)      3.05 i/c      3.20 GHz 
clickhouse                              :   294.50 MB/s (+/- 1.9 %)    63.18 Mfloat/s      36.21 i/B   176.98 i/f (+/- 0.0 %)      0.02 bm/B     0.10 bm/f (+/- 0.4 %)     10.37 c/B    50.67 c/f (+/- 1.4 %)      3.49 i/c      3.20 GHz 
fastfloat                               :   275.38 MB/s (+/- 2.8 %)    59.07 Mfloat/s      37.42 i/B   182.89 i/f (+/- 0.0 %)      0.02 bm/B     0.10 bm/f (+/- 14.9 %)     11.09 c/B    54.19 c/f (+/- 2.4 %)      3.38 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers4.tsv 
# read 10000 lines 
volume = 0.0039917 MB 
netlib                                  :   271.96 MB/s (+/- 0.8 %)    17.03 Mfloat/s      31.69 i/B   530.57 i/f (+/- 0.0 %)      0.08 bm/B     1.32 bm/f (+/- 1.1 %)     11.22 c/B   187.89 c/f (+/- 0.5 %)      2.82 i/c      3.20 GHz 
doubleconversion                        :   169.13 MB/s (+/- 2.8 %)    10.59 Mfloat/s      55.44 i/B   928.18 i/f (+/- 0.0 %)      0.07 bm/B     1.15 bm/f (+/- 5.0 %)     18.01 c/B   301.61 c/f (+/- 2.5 %)      3.08 i/c      3.19 GHz 
strtod                                  :   175.64 MB/s (+/- 0.8 %)    11.00 Mfloat/s      47.80 i/B   800.33 i/f (+/- 0.0 %)      0.05 bm/B     0.88 bm/f (+/- 0.7 %)     17.38 c/B   290.90 c/f (+/- 0.5 %)      2.75 i/c      3.20 GHz 
starrocks                               :   366.71 MB/s (+/- 0.4 %)    22.97 Mfloat/s      20.98 i/B   351.18 i/f (+/- 0.0 %)      0.04 bm/B     0.74 bm/f (+/- 0.3 %)      8.32 c/B   139.35 c/f (+/- 0.1 %)      2.52 i/c      3.20 GHz 
clickhouse                              :   611.97 MB/s (+/- 0.7 %)    38.33 Mfloat/s      16.60 i/B   277.97 i/f (+/- 0.0 %)      0.04 bm/B     0.66 bm/f (+/- 1.4 %)      4.99 c/B    83.51 c/f (+/- 0.4 %)      3.33 i/c      3.20 GHz 
fastfloat                               :   638.89 MB/s (+/- 0.8 %)    40.01 Mfloat/s      12.99 i/B   217.54 i/f (+/- 0.0 %)      0.04 bm/B     0.68 bm/f (+/- 1.7 %)      4.78 c/B    79.99 c/f (+/- 0.5 %)      2.72 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers5.tsv 
# read 10000 lines 
volume = 0.0041662 MB 
netlib                                  :   207.73 MB/s (+/- 3.8 %)    12.47 Mfloat/s      28.48 i/B   497.71 i/f (+/- 0.0 %)      0.18 bm/B     3.12 bm/f (+/- 1.7 %)     14.69 c/B   256.61 c/f (+/- 3.3 %)      1.94 i/c      3.20 GHz 
doubleconversion                        :   153.95 MB/s (+/- 39.7 %)     9.24 Mfloat/s      55.25 i/B   965.52 i/f (+/- 0.0 %)      0.10 bm/B     1.76 bm/f (+/- 3.0 %)     19.77 c/B   345.54 c/f (+/- 36.7 %)      2.79 i/c      3.19 GHz 
strtod                                  :    67.07 MB/s (+/- 5.7 %)     4.02 Mfloat/s      67.09 i/B  1172.38 i/f (+/- 0.0 %)      0.11 bm/B     1.87 bm/f (+/- 0.9 %)     45.22 c/B   790.21 c/f (+/- 4.6 %)      1.48 i/c      3.18 GHz 
starrocks                               :   235.09 MB/s (+/- 61.5 %)    14.11 Mfloat/s      20.93 i/B   365.76 i/f (+/- 0.0 %)      0.04 bm/B     0.65 bm/f (+/- 5.3 %)     12.65 c/B   221.08 c/f (+/- 32.0 %)      1.65 i/c      3.12 GHz 
clickhouse                              :   316.09 MB/s (+/- 16.2 %)    18.97 Mfloat/s      18.77 i/B   328.08 i/f (+/- 0.0 %)      0.04 bm/B     0.78 bm/f (+/- 1.6 %)      9.66 c/B   168.74 c/f (+/- 14.9 %)      1.94 i/c      3.20 GHz 
fastfloat                               :   327.20 MB/s (+/- 19.7 %)    19.63 Mfloat/s      16.16 i/B   282.44 i/f (+/- 0.0 %)      0.04 bm/B     0.68 bm/f (+/- 1.6 %)      9.19 c/B   160.56 c/f (+/- 19.7 %)      1.76 i/c      3.15 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers6.tsv 
# read 10000 lines 
volume = 0.00410221 MB 
netlib                                  :   168.99 MB/s (+/- 1.3 %)    10.30 Mfloat/s      33.57 i/B   577.56 i/f (+/- 0.0 %)      0.17 bm/B     2.90 bm/f (+/- 0.6 %)     18.01 c/B   309.95 c/f (+/- 1.0 %)      1.86 i/c      3.19 GHz 
doubleconversion                        :   171.65 MB/s (+/- 1.2 %)    10.46 Mfloat/s      54.67 i/B   940.65 i/f (+/- 0.0 %)      0.05 bm/B     0.85 bm/f (+/- 10.2 %)     17.71 c/B   304.65 c/f (+/- 1.3 %)      3.09 i/c      3.19 GHz 
strtod                                  :    94.06 MB/s (+/- 1.5 %)     5.73 Mfloat/s      74.16 i/B  1276.07 i/f (+/- 0.0 %)      0.16 bm/B     2.71 bm/f (+/- 1.0 %)     32.38 c/B   557.08 c/f (+/- 1.4 %)      2.29 i/c      3.19 GHz 
starrocks                               :   434.39 MB/s (+/- 2.8 %)    26.47 Mfloat/s      21.40 i/B   368.14 i/f (+/- 0.0 %)      0.02 bm/B     0.36 bm/f (+/- 6.9 %)      7.03 c/B   120.89 c/f (+/- 2.4 %)      3.05 i/c      3.20 GHz 
clickhouse                              :   512.99 MB/s (+/- 3.2 %)    31.26 Mfloat/s      18.87 i/B   324.69 i/f (+/- 0.0 %)      0.03 bm/B     0.60 bm/f (+/- 19.6 %)      5.95 c/B   102.37 c/f (+/- 2.9 %)      3.17 i/c      3.20 GHz 
fastfloat                               :   593.00 MB/s (+/- 3.6 %)    36.14 Mfloat/s      16.36 i/B   281.55 i/f (+/- 0.0 %)      0.02 bm/B     0.36 bm/f (+/- 0.9 %)      5.15 c/B    88.56 c/f (+/- 3.3 %)      3.18 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers7.tsv 
# read 10000 lines 
volume = 0.00505977 MB 
netlib                                  :   179.57 MB/s (+/- 2.5 %)     8.87 Mfloat/s      30.79 i/B   653.42 i/f (+/- 0.0 %)      0.18 bm/B     3.79 bm/f (+/- 0.8 %)     16.95 c/B   359.62 c/f (+/- 2.3 %)      1.82 i/c      3.19 GHz 
doubleconversion                        :   178.70 MB/s (+/- 1.7 %)     8.83 Mfloat/s      48.87 i/B  1037.02 i/f (+/- 0.0 %)      0.08 bm/B     1.61 bm/f (+/- 0.8 %)     17.03 c/B   361.32 c/f (+/- 1.5 %)      2.87 i/c      3.19 GHz 
strtod                                  :    95.50 MB/s (+/- 1.2 %)     4.72 Mfloat/s      62.89 i/B  1334.68 i/f (+/- 0.0 %)      0.19 bm/B     3.96 bm/f (+/- 0.9 %)     31.86 c/B   676.09 c/f (+/- 1.0 %)      1.97 i/c      3.19 GHz 
starrocks                               :    76.97 MB/s (+/- 0.7 %)     3.80 Mfloat/s      81.97 i/B  1739.62 i/f (+/- 0.0 %)      0.23 bm/B     4.79 bm/f (+/- 0.5 %)     39.54 c/B   839.13 c/f (+/- 0.5 %)      2.07 i/c      3.19 GHz 
clickhouse                              :   538.74 MB/s (+/- 2.3 %)    26.62 Mfloat/s      17.57 i/B   372.83 i/f (+/- 0.0 %)      0.03 bm/B     0.62 bm/f (+/- 3.3 %)      5.67 c/B   120.23 c/f (+/- 1.8 %)      3.10 i/c      3.20 GHz 
fastfloat                               :   574.00 MB/s (+/- 5.2 %)    28.36 Mfloat/s      16.48 i/B   349.82 i/f (+/- 0.0 %)      0.02 bm/B     0.42 bm/f (+/- 11.9 %)      5.32 c/B   112.84 c/f (+/- 4.8 %)      3.10 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers8.tsv 
# read 10000 lines 
volume = 0.00476062 MB 
netlib                                  :   164.45 MB/s (+/- 0.7 %)     8.64 Mfloat/s      31.42 i/B   627.37 i/f (+/- 0.0 %)      0.24 bm/B     4.76 bm/f (+/- 0.5 %)     18.49 c/B   369.29 c/f (+/- 0.6 %)      1.70 i/c      3.19 GHz 
doubleconversion                        :   142.32 MB/s (+/- 2.2 %)     7.47 Mfloat/s      50.94 i/B  1017.06 i/f (+/- 0.0 %)      0.17 bm/B     3.44 bm/f (+/- 0.5 %)     21.39 c/B   427.06 c/f (+/- 2.0 %)      2.38 i/c      3.19 GHz 
strtod                                  :   102.47 MB/s (+/- 0.4 %)     5.38 Mfloat/s      65.37 i/B  1305.27 i/f (+/- 0.0 %)      0.35 bm/B     6.93 bm/f (+/- 0.7 %)     29.73 c/B   593.60 c/f (+/- 0.2 %)      2.20 i/c      3.19 GHz 
starrocks                               :    91.51 MB/s (+/- 0.5 %)     4.81 Mfloat/s      75.38 i/B  1505.17 i/f (+/- 0.0 %)      0.37 bm/B     7.37 bm/f (+/- 0.6 %)     33.24 c/B   663.74 c/f (+/- 0.4 %)      2.27 i/c      3.19 GHz 
clickhouse                              :   470.55 MB/s (+/- 1.3 %)    24.71 Mfloat/s      18.25 i/B   364.45 i/f (+/- 0.0 %)      0.06 bm/B     1.18 bm/f (+/- 1.6 %)      6.48 c/B   129.47 c/f (+/- 1.0 %)      2.81 i/c      3.20 GHz 
fastfloat                               :   483.53 MB/s (+/- 1.2 %)    25.39 Mfloat/s      16.58 i/B   331.09 i/f (+/- 0.0 %)      0.06 bm/B     1.26 bm/f (+/- 0.9 %)      6.31 c/B   126.03 c/f (+/- 0.8 %)      2.63 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers9.tsv 
# read 10000 lines 
volume = 0.0184972 MB 
netlib                                  :   515.17 MB/s (+/- 0.9 %)     6.96 Mfloat/s      14.94 i/B  1159.00 i/f (+/- 0.0 %)      0.04 bm/B     2.72 bm/f (+/- 1.6 %)      5.91 c/B   458.22 c/f (+/- 0.7 %)      2.53 i/c      3.19 GHz 
doubleconversion                        :   311.46 MB/s (+/- 0.5 %)     4.21 Mfloat/s      27.59 i/B  2140.85 i/f (+/- 0.0 %)      0.04 bm/B     3.37 bm/f (+/- 0.5 %)      9.77 c/B   758.01 c/f (+/- 0.5 %)      2.82 i/c      3.19 GHz 
strtod                                  :   266.00 MB/s (+/- 0.4 %)     3.60 Mfloat/s      31.53 i/B  2445.88 i/f (+/- 0.0 %)      0.04 bm/B     3.15 bm/f (+/- 0.6 %)     11.45 c/B   887.95 c/f (+/- 0.4 %)      2.75 i/c      3.19 GHz 
starrocks                               :   289.07 MB/s (+/- 0.3 %)     3.91 Mfloat/s      19.44 i/B  1508.10 i/f (+/- 0.0 %)      0.01 bm/B     1.00 bm/f (+/- 1.1 %)     10.54 c/B   817.61 c/f (+/- 0.1 %)      1.84 i/c      3.19 GHz 
clickhouse                              :  1102.97 MB/s (+/- 0.8 %)    14.91 Mfloat/s       9.39 i/B   728.15 i/f (+/- 0.0 %)      0.01 bm/B     0.93 bm/f (+/- 1.7 %)      2.77 c/B   214.68 c/f (+/- 0.4 %)      3.39 i/c      3.20 GHz 
fastfloat                               :   896.92 MB/s (+/- 2.5 %)    12.12 Mfloat/s       9.72 i/B   754.32 i/f (+/- 0.0 %)      0.02 bm/B     1.59 bm/f (+/- 2.4 %)      3.39 c/B   263.31 c/f (+/- 2.3 %)      2.86 i/c      3.19 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ ./benchmarks/benchmark -f ../data/numbers10.tsv 
# read 10000 lines 
volume = 0.0187369 MB 
netlib                                  :   298.85 MB/s (+/- 1.4 %)     3.99 Mfloat/s      20.47 i/B  1608.57 i/f (+/- 0.0 %)      0.09 bm/B     7.46 bm/f (+/- 2.2 %)     10.19 c/B   800.73 c/f (+/- 1.3 %)      2.01 i/c      3.19 GHz 
doubleconversion                        :   294.63 MB/s (+/- 0.5 %)     3.93 Mfloat/s      27.11 i/B  2130.82 i/f (+/- 0.0 %)      0.06 bm/B     4.44 bm/f (+/- 0.7 %)     10.33 c/B   811.83 c/f (+/- 0.4 %)      2.62 i/c      3.19 GHz 
strtod                                  :   283.11 MB/s (+/- 0.4 %)     3.78 Mfloat/s      24.59 i/B  1932.80 i/f (+/- 0.0 %)      0.10 bm/B     8.03 bm/f (+/- 0.3 %)     10.76 c/B   845.41 c/f (+/- 0.2 %)      2.29 i/c      3.19 GHz 
starrocks                               :   381.20 MB/s (+/- 0.9 %)     5.09 Mfloat/s      17.37 i/B  1365.06 i/f (+/- 0.0 %)      0.02 bm/B     1.76 bm/f (+/- 0.5 %)      7.99 c/B   628.19 c/f (+/- 0.7 %)      2.17 i/c      3.20 GHz 
clickhouse                              :   869.50 MB/s (+/- 2.6 %)    11.60 Mfloat/s      11.38 i/B   894.02 i/f (+/- 0.0 %)      0.02 bm/B     1.51 bm/f (+/- 0.9 %)      3.51 c/B   275.84 c/f (+/- 2.2 %)      3.24 i/c      3.20 GHz 
fastfloat                               :   859.86 MB/s (+/- 1.6 %)    11.47 Mfloat/s      10.48 i/B   823.93 i/f (+/- 0.0 %)      0.02 bm/B     1.69 bm/f (+/- 3.2 %)      3.55 c/B   278.93 c/f (+/- 1.2 %)      2.95 i/c      3.20 GHz 
[zhaoxiaoyong@starrocks-sandbox04 build]$ 
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_build images

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_unittest images

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by wangruin** [comment]
run starrocks_admit_test image

**Comment by wangruin** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest images

**Comment by xiaoyong-z** [comment]
run starrocks_be_build images

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test images

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest images

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_be_unittest image

**Comment by wangruin** [comment]
run starrocks_admit_test image

**Comment by wangruin** [comment]
run starrocks_be_build image

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest image

**Comment by xiaoyong-z** [comment]
run starrocks_be_build image

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

File: be/src/util/string_parser.hpp [hunk 2]
```diff
@@ -429,114 +418,95 @@ inline T StringParser::string_to_float_internal(const char* s, int len, ParseRes
...
         }
     }
 
-    // Determine if it is an overflow case and update the result
-    if (UNLIKELY(val == std::numeric_limits<T>::infinity())) {
-        *result = PARSE_OVERFLOW;
-    } else {
-        *result = PARSE_SUCCESS;
+    double val;
+    auto res = fast_float::from_chars(s + i, s + j + 1, val);
```
Comment (chaoyli) [inline be/src/util/string_parser.hpp:497]: If you import the fast_float library, is there necessary to change the string_parser.hpp?

Comment (xiaoyong-z) [reply be/src/util/string_parser.hpp:497]: i think it is necessary, original string_parser.hpp use heristic method to convert string to double(val = val + remainder / divide), it will lose some precision, we need to discard this implementation.

**Comment by xiaoyong-z** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest image

**Comment by xiaoyong-z** [comment]
run starrocks_be_build image

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
run starrocks_be_build image

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest image

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest image

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
@mergify rebase

**Comment by xiaoyong-z** [comment]
run starrocks_be_unittest image

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by chaoyli — APPROVED** [review]

**Comment by xiaoyong-z** [comment]
Update commit msg: 
[BugFix] string_to_float_internal may lose some precision
For 2.97, string_to_float_internal will calculated by 2 + 97 / 100, which is 2.9699999999999998,
acutulay it should be calculated by by 297 / 100, which is 2.970000000002
In this pr, we use fast_float library to transfer string to float, in most cases, its speed is faster
than the original string_to_float_internal, except that the double number is very simple(such as 0, 2, 2,..9).
Also the fast float's string to float conversion is without precision loss

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test image

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.4

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by fzhedu** [comment]
backport branch-2.3

**Comment by fzhedu** [comment]
@mergify backport branch-2.3
