### PR TITLE
Fix date cast to datetime bug when datetime is null

### LINKED ISSUE #3783: query sql error: Invalid date value
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS w1;
CREATE DATABASE w1;
USE w1;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL(29, 3)  NULL ,c_0_1 BOOLEAN NOT NULL ,c_0_2 SMALLINT NULL ,c_0_3 VARCHAR(1) NULL ,c_0_4 BOOLEAN NULL ,c_0_5 FLOAT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) DISTRIBUTED BY HASH (c_0_4,c_0_0,c_0_3) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ,c_1_1 PERCENTILE PERCENTILE_UNION NOT NULL ,c_1_2 DECIMAL(7, 0)  SUM NULL ,c_1_3 BITMAP BITMAP_UNION NULL ,c_1_4 BOOLEAN REPLACE NULL ,c_1_5 HLL HLL_UNION NULL ,c_1_6 DATETIME REPLACE_IF_NOT_NULL NULL ,c_1_7 FLOAT MIN NULL ,c_1_8 FLOAT REPLACE_IF_NOT_NULL NULL ,c_1_9 DATE REPLACE NOT NULL ,c_1_10 BITMAP BITMAP_UNION NOT NULL ,c_1_11 DOUBLE SUM NULL ,c_1_12 LARGEINT SUM NOT NULL ) AGGREGATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 BOOLEAN NULL ,c_2_1 DECIMAL(6, 3)  NULL ,c_2_2 VARCHAR(11) NULL ,c_2_3 DATETIME NULL ,c_2_4 LARGEINT NULL ,c_2_5 BIGINT NOT NULL ,c_2_6 VARCHAR(11) NOT NULL ,c_2_7 DECIMAL(1, 0)  NULL ,c_2_8 BOOLEAN NULL ,c_2_9 DECIMAL(27, 1)  NOT NULL ,c_2_10 CHAR(21) NULL ,c_2_11 BOOLEAN NULL ,c_2_12 HLL HLL_UNION NULL ,c_2_13 BOOLEAN REPLACE NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11) DISTRIBUTED BY HASH (c_2_0,c_2_4,c_2_5) properties("replication_num"="3") ;
CREATE TABLE t3 (c_3_0 BOOLEAN NOT NULL ,c_3_1 BOOLEAN NOT NULL ,c_3_2 BOOLEAN NOT NULL ,c_3_3 TINYINT NULL ,c_3_4 INT NULL ,c_3_5 DATETIME NOT NULL ,c_3_6 DATETIME NOT NULL ,c_3_7 DATETIME NOT NULL ,c_3_8 VARCHAR(11) REPLACE NOT NULL ,c_3_9 HLL HLL_UNION NULL ,c_3_10 DECIMAL(24, 3)  SUM NULL ,c_3_11 BOOLEAN REPLACE NOT NULL ,c_3_12 BOOLEAN REPLACE NULL ,c_3_13 DECIMAL(31, 1)  REPLACE NOT NULL ,c_3_14 BITMAP BITMAP_UNION NOT NULL ) AGGREGATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7) DISTRIBUTED BY HASH (c_3_1) properties("replication_num"="3") ;
INSERT INTO t1 VALUES (NULL, percentile_hash("-77407879"), 4432560, bitmap_hash("9H"), true, hll_hash(""), "1970-01-01 08:00:00", -7.7407879E7, 0.8705922226681327, "1970-01-01", bitmap_hash("Ke"), NULL, -77407879), ("1970-01-01 08:00:00", percentile_hash("479938424"), NULL, bitmap_hash("qV"), true, hll_hash("j"), "1970-01-01 08:00:00", 0.6947607253815146, 0.9608773320409817, "1970-01-01", bitmap_hash("psJzfxeW"), 0.03143778979490108, 97306175);
TRUNCATE TABLE t0;
```
2. mysql> SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_10, t2.c_2_11, t2.c_2_13 FROM t2) subt2 RIGHT JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5 FROM t0) subt0 ON subt2.c_2_11 = subt0.c_0_2 AND subt2.c_2_11 <= ((1809077112)*(257082716)) AND subt2.c_2_7 >= subt0.c_0_2 AND subt2.c_2_7 >= subt0.c_0_2,  (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6, t3.c_3_7, t3.c_3_8, t3.c_3_10, t3.c_3_11, t3.c_3_12, t3.c_3_13 FROM t3 WHERE ((t3.c_3_7) IS NULL)) subt3 LEFT SEMI JOIN (SELECT t1.c_1_0, t1.c_1_2, t1.c_1_4, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_11, t1.c_1_12 FROM t1) subt1 ON subt3.c_3_13 = subt1.c_1_0 AND subt3.c_3_13 < subt1.c_1_0 WHERE  ( CAST(subt0.c_0_2 AS DATE )  ) >= ( subt2.c_2_3 )  UNION ALL SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_10, t2.c_2_11, t2.c_2_13 FROM t2) subt2 RIGHT JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5 FROM t0) subt0 ON subt2.c_2_11 = subt0.c_0_2 AND subt2.c_2_11 <= ((1809077112)*(257082716)) AND subt2.c_2_7 >= subt0.c_0_2 AND subt2.c_2_7 >= subt0.c_0_2,  (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6, t3.c_3_7, t3.c_3_8, t3.c_3_10, t3.c_3_11, t3.c_3_12, t3.c_3_13 FROM t3 WHERE ((t3.c_3_7) IS NULL)) subt3 LEFT SEMI JOIN (SELECT t1.c_1_0, t1.c_1_2, t1.c_1_4, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_11, t1.c_1_12 FROM t1) subt1 ON subt3.c_3_13 = subt1.c_1_0 AND subt3.c_3_13 < subt1.c_1_0 WHERE (NOT ( ( CAST(subt0.c_0_2 AS DATE )  ) >= ( subt2.c_2_3 ) )) UNION ALL SELECT subt2.c_2_0 FROM  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_10, t2.c_2_11, t2.c_2_13 FROM t2) subt2 RIGHT OUTER JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5 FROM t0) subt0 ON subt2.c_2_11 = subt0.c_0_2 AND subt2.c_2_11 <= ((1809077112)*(257082716)) AND subt2.c_2_7 >= subt0.c_0_2 AND subt2.c_2_7 >= subt0.c_0_2,  (SELECT t3.c_3_0, t3.c_3_1, t3.c_3_2, t3.c_3_3, t3.c_3_4, t3.c_3_5, t3.c_3_6, t3.c_3_7, t3.c_3_8, t3.c_3_10, t3.c_3_11, t3.c_3_12, t3.c_3_13 FROM t3 WHERE ((t3.c_3_7) IS NULL)) subt3 LEFT SEMI JOIN (SELECT t1.c_1_0, t1.c_1_2, t1.c_1_4, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_11, t1.c_1_12 FROM t1) subt1 ON subt3.c_3_13 = subt1.c_1_0 AND subt3.c_3_13 < subt1.c_1_0 WHERE (( ( CAST(subt0.c_0_2 AS DATE )  ) >= ( subt2.c_2_3 ) ) IS NULL);
ERROR 1064 (HY000): Invalid date value
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_01_RELEASE d25e286 |
+---------------------------------+

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3783

## Problem Summary(Required) ：

Will throw exception
```
select * from t1 where cast(v1 as datetime) < NULL;
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 48 / 54 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/CompoundPredicateOperator.java|1|4|25.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java|38|38|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java [hunk 1]
```diff
@@ -154,4 +154,28 @@ public int hashCode() {
     public boolean isNullable() {
         return !this.type.equals(BinaryType.EQ_FOR_NULL) && super.isNullable();
     }
+
+    public static BinaryPredicateOperator eq(ScalarOperator... arguments) {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java:158]: BinaryPredicateOperator Since it is limited to a binary operator here, why do we set a variable length parameter? Is it better to change to fixed parameters instead of relying on Preconditions.checkState(arguments.size() == 2);
Throws an Unknow Error to the user at runtime.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java [hunk 2]
```diff
@@ -146,59 +147,46 @@ public ScalarOperator reduceDateToDatetimeCast(BinaryPredicateOperator operator)
...
             case EQ:
                 // when the BinaryType is = ,cast dateTime to equivalent date type；
                 // Eg:cast dateTime(2021-12-28 00:00:00.0) to date(2021-12-28)
                 if (!originalDateTime.isEqual(bottomDateTime)) {
                     resultBinaryPredicateOperator = operator;
                 } else {
-                    newDate = ConstantOperator.createDate(bottomDateTime.truncatedTo(ChronoUnit.DAYS));
-                    resultBinaryPredicateOperator =
-                            new BinaryPredicateOperator(BinaryPredicateOperator.BinaryType.EQ, castChild, newDate);
+                    newDate = ConstantOperator.createDate(bottomDateTime);
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:188]: Why bottomDateTime.truncatedTo(ChronoUnit.DAYS) was originally needed

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java [hunk 3]
```diff
@@ -209,11 +197,14 @@ public ScalarOperator reduceDateToDatetimeCast(BinaryPredicateOperator operator)
...
-        ScalarOperator castChild = child1.getChild(0);
-        LocalDateTime originalDate = ((ConstantOperator) child2).getDate();
+    private ScalarOperator reduceDatetimeToDateCast(BinaryPredicateOperator operator) {
+        ScalarOperator castChild = operator.getChild(0).getChild(0);
+        ConstantOperator child2 = (ConstantOperator) operator.getChild(1);
+        if (child2.isNull()) {
+            return operator;
+        }
+
+        LocalDateTime originalDate = child2.getDate().truncatedTo(ChronoUnit.DAYS);
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:207]: Why is bottomDateTime.truncatedTo(ChronoUnit.DAYS) needed here, and when we need to call this function

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java [hunk 4]
```diff
@@ -1105,8 +1105,15 @@ public void testTimestampPartitionPruneOptimize() throws Exception {
                 "select * from test_partition_prune_optimize_by_date where dt >= timestamp('2021-12-27 00:00:00.123456') " +
                         "and dt <= timestamp('2021-12-29 00:00:00.123456')";
         String plan = getFragmentPlan(sql);
+        System.out.println(plan);
```
Comment (HangyuanLiu) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/DistributedEnvPlanWithCostTest.java:1108]: Forgot to delete?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java [hunk 5]
```diff
@@ -130,12 +126,17 @@ public boolean checkCastTypeReduceAble(Type parent, Type child, Type grandChild)
...
-        ScalarOperator child2 = operator.getChild(1);
-        ScalarOperator castChild = child1.getChild(0);
-        LocalDateTime originalDateTime = ((ConstantOperator) child2).getDatetime();
-        LocalDateTime bottomDateTime = ((ConstantOperator) child2).getDatetime().toLocalDate().atTime(0, 0, 0, 0);
+    private ScalarOperator reduceDateToDatetimeCast(BinaryPredicateOperator operator) {
+        ScalarOperator castChild = operator.getChild(0).getChild(0);
+        ConstantOperator child2 = (ConstantOperator) operator.getChild(1);
+
+        if (child2.isNull()) {
+            return operator;
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:134]: Does returning null here mean giving up optimization? If yes, then why can't you modify the type of null and then proceed with the optimization

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java:158]: You are right

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java (hunk 5 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:134]: Null meanings the child is non-value and the rule depend on the value, it's should optimize by other rule, not here

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java (hunk 2 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:188]: I think you should read the comment about the rule

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java (hunk 3 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java:207]: I think you should read the comment about the rule

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRuleTest.java [hunk 6]
```diff
@@ -297,6 +297,17 @@ public void testReduceDateToDatetimeCast() {
 
             Assert.assertSame(beforeOptimize, afterOptimize);
         }
+        {
+            CastOperator castOperator =
+                    new CastOperator(Type.DATETIME, new ColumnRefOperator(0, Type.DATE, "id_date", false));
+            ConstantOperator constantOperator = ConstantOperator.createNull(Type.DATETIME);
+            BinaryPredicateOperator beforeOptimize =
+                    new BinaryPredicateOperator(BinaryPredicateOperator.BinaryType.GE, castOperator, constantOperator);
+            ScalarOperator afterOptimize = reduceCastRule.apply(
```
Comment (liuyehcf) [inline fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRuleTest.java:306]: Replace it with BinaryPredicateOperator.ge?

File: fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRuleTest.java [hunk 7]
```diff
@@ -410,5 +421,14 @@ public void testReduceDatetimeToDateCast() {
...
                     ((ConstantOperator) right.getChild(1)).getDatetime().format(formatter));
         }
+        {
+            CastOperator castOperator =
+                    new CastOperator(Type.DATE, new ColumnRefOperator(0, Type.DATETIME, "id_datetime", false));
+            ConstantOperator constantOperator = ConstantOperator.createNull(Type.DATE);
+            BinaryPredicateOperator beforeOptimize =
+                    new BinaryPredicateOperator(BinaryPredicateOperator.BinaryType.LT, castOperator, constantOperator);
+            ScalarOperator afterOptimize = reduceCastRule.apply(beforeOptimize, null);
+            Assert.assertSame(beforeOptimize, afterOptimize);
```
Comment (liuyehcf) [inline fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRuleTest.java:431]: Same as above

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 48 / 54 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/CompoundPredicateOperator.java|1|4|25.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/BinaryPredicateOperator.java|4|6|66.67%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/ReduceCastRule.java|38|38|100.00%|

**Review by liuyehcf — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
