### PR TITLE
[BugFix] Limit the maximum number of reorders

### LINKED ISSUE #6515: [sqlancer] JoinReorderGreedy  unknow error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS v13;
CREATE DATABASE v13;
USE v13;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NULL ,c_0_1 TINYINT NULL ,c_0_2 INT NOT NULL ,c_0_3 CHAR(31) NULL ,c_0_4 DECIMAL(13, 5)  NULL ,c_0_5 DATETIME NOT NULL ,c_0_6 SMALLINT NULL ,c_0_7 CHAR(21) NULL ,c_0_8 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_9 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_10 DATETIME REPLACE_IF_NOT_NULL NOT NULL ,c_0_11 VARCHAR(1) REPLACE_IF_NOT_NULL NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 101 day)) DISTRIBUTED BY HASH (c_0_2,c_0_5,c_0_1,c_0_0,c_0_7,c_0_4,c_0_3,c_0_6) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATETIME NULL ,c_1_1 BOOLEAN NOT NULL ,c_1_2 DATE NULL ,c_1_3 INT REPLACE_IF_NOT_NULL NULL ,c_1_4 BOOLEAN REPLACE NULL ,c_1_5 FLOAT SUM NOT NULL ,c_1_6 HLL HLL_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_1_0,c_1_1,c_1_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 BIGINT NULL ,c_2_1 DATE NOT NULL ,c_2_2 HLL HLL_UNION NULL ,c_2_3 DECIMAL(31, 2)  SUM NOT NULL ,c_2_4 BOOLEAN REPLACE NULL ,c_2_5 BOOLEAN REPLACE NULL ,c_2_6 VARCHAR(31) REPLACE_IF_NOT_NULL NOT NULL ,c_2_7 SMALLINT SUM NULL ,c_2_8 HLL HLL_UNION NULL ,c_2_9 DATE REPLACE NOT NULL ,c_2_10 PERCENTILE PERCENTILE_UNION NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_0,c_2_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DATE NOT NULL ,c_3_1 CHAR(11) MAX NULL ,c_3_2 BOOLEAN REPLACE NULL ) AGGREGATE KEY (c_3_0) PARTITION BY RANGE(c_3_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 199 day)) DISTRIBUTED BY HASH (c_3_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t4 (c_4_0 BOOLEAN NOT NULL ,c_4_1 CHAR(31) NULL ,c_4_2 DATETIME NOT NULL ,c_4_3 DATE NULL ,c_4_4 DATE NULL , INDEX index1_c_4_3(`c_4_3`) USING BITMAP) DUPLICATE KEY (c_4_0,c_4_1,c_4_2,c_4_3) PARTITION BY RANGE(c_4_3) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_4_1,c_4_3) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2010-01-06 08:00:14', 4, 5, '', 503.10966, '2010-01-22 08:00:14', 7, 'VW9', percentile_hash('554717221'), percentile_hash('1066154514'), '2009-12-31 08:00:14', ''), ('2010-01-08 08:00:14', 0, 7, '', 454.08947, '2010-01-05 08:00:14', 10, 'b3pUT', percentile_hash('1066154514'), percentile_hash('2083686536'), NULL, '');
INSERT INTO t4 VALUES (false, '9', '2010-01-17 08:00:14', '2010-01-20', '2010-01-30'), (true, 'O', '2010-01-06 08:00:14', '2010-01-31', '2010-01-14');
INSERT INTO t2 VALUES (-776219113, '2010-01-24', hll_hash('loAQ0u'), 494291879843290520614162986.13, true, false, '', 9, hll_hash('k4OwOzCXD'), '2010-01-03', percentile_hash('-1288522024')), (1066154514, '2010-01-30', hll_hash('DBIoi'), 436414372788672404673393501.18, NULL, false, 'ia', 11, hll_hash('EvI'), '2010-01-29', percentile_hash('1066154514'));
INSERT INTO t0 VALUES ('2010-01-12 08:00:14', 3, 21, 'so9OwFS', 493.36129, '2010-01-27 08:00:14', 3, 'H', percentile_hash('-1941869041'), percentile_hash('1823480810'), '2010-01-08 08:00:14', NULL);
INSERT INTO t3 VALUES ('2010-01-27', '', false), ('2010-01-29', '', false);
INSERT INTO t2 VALUES (-1941869041, '2010-01-21', hll_hash('Bu78qYpmH'), 250857499641809770464240259.00, true, false, 'R', 8, hll_hash('0'), '2009-12-31', percentile_hash('1479700299'));
INSERT INTO t0 VALUES ('2010-01-08 08:00:14', 1, 15, 'BxC', 325.27301, '2010-01-03 08:00:14', 1, '', percentile_hash('-1987498097'), percentile_hash('1479700299'), NULL, ''), ('2010-01-17 08:00:14', 5, 20, '9lx9fF', 783.05483, '2010-01-22 08:00:14', 9, '', percentile_hash('-1288522024'), percentile_hash('-20354353'), '2010-01-02 08:00:14', '');
INSERT INTO t0 VALUES ('2010-01-07 08:00:14', 5, 19, '4', 303.19892, '2010-01-15 08:00:14', 15, 'cTyOO9fq', percentile_hash('1418550958'), percentile_hash('1066154514'), NULL, ''), ('2010-01-01 08:00:14', NULL, 7, NULL, 266.70495, '2010-01-22 08:00:14', 0, '', percentile_hash('1066154514'), percentile_hash('-156509323'), '2010-01-01 08:00:14', '');
INSERT INTO t1 VALUES ('2010-01-03 08:00:14', false, '2010-01-10', 0, false, 0.7428362737675623, hll_hash('DAi'));
INSERT INTO t1 VALUES ('2010-01-21 08:00:14', true, '2010-01-23', 10, true, 0.8735155550464849, hll_hash('ZB'));
INSERT INTO t2 VALUES (90041710, '2010-01-07', hll_hash(''), 414648206845130858874126644.76, false, false, '2OoM', 15, hll_hash(''), '2010-01-06', percentile_hash('1055193809'));
INSERT INTO t0 VALUES ('2010-01-19 08:00:14', NULL, 4, 'klzkQe47O', 402.45102, '2010-01-02 08:00:14', 2, '', percentile_hash('90041710'), percentile_hash('-20354353'), '2010-01-17 08:00:14', '');
INSERT INTO t0 VALUES ('2010-01-27 08:00:14', 4, 2, '', 884.58758, '2010-01-25 08:00:14', 15, '', percentile_hash('-1941869041'), percentile_hash('1055193809'), '2010-01-12 08:00:14', ''), ('2010-01-31 08:00:14', 1, 15, 'D', 558.97043, '2010-01-13 08:00:14', 7, 'c9tsefaO', percentile_hash('404125897'), percentile_hash('1066154514'), '2010-01-02 08:00:14', ''), ('2010-01-30 08:00:14', 5, 10, 'kz', 599.94437, '2010-01-28 08:00:14', 8, NULL, percentile_hash('90041710'), percentile_hash('2083686536'), '2010-01-16 08:00:14', NULL);
INSERT INTO t0 VALUES ('2009-12-31 08:00:14', 3, 12, 'yr', 93.85232, '2010-01-05 08:00:14', 13, 'Kj5', percentile_hash('-221652293'), percentile_hash('-1807604816'), '2010-01-01 08:00:14', '');
INSERT INTO t2 VALUES (-652079575, '2010-01-09', hll_hash('aJ'), 953983255411400498575469342.19, false, false, 'zjF', 5, hll_hash(''), '2010-01-12', percentile_hash('-1288522024'));
INSERT INTO t4 VALUES (false, 'YNr', '2010-01-29 08:00:14', '2010-01-12', '2010-01-11');
CREATE VIEW v0 AS SELECT t2_1141.c_2_0 FROM t2 AS t2_1141;
CREATE VIEW v1 AS SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE ( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) ) ;
CREATE VIEW v49 AS SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE (NOT (( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) ) ));
CREATE VIEW v2 AS SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE ((( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) ) ) IS NULL);
CREATE VIEW v3 AS SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE ( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) )  UNION ALL SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE (NOT (( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) ) )) UNION ALL SELECT t2_1141.c_2_0 FROM t2 AS t2_1141 WHERE ((( ( CHAR_LENGTH('h0')  ) != ( t2_1141.c_2_0 ) )  BETWEEN (t2_1141.c_2_5) AND (CAST(((NULL)+(((-221652293)+(-927244214)))) AS BOOLEAN ) ) ) IS NULL);
CREATE VIEW v4 AS SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183;
CREATE VIEW v5 AS SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END;
CREATE VIEW v6 AS SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE (NOT (CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END));
CREATE VIEW v7 AS SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE ((CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END) IS NULL);
CREATE VIEW v8 AS SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END UNION ALL SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE (NOT (CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END)) UNION ALL SELECT t2_1176.c_2_0 FROM t2 AS t2_1176, v49 AS v49_1183 WHERE ((CASE  WHEN false THEN false  WHEN (NOT (true)) THEN true END) IS NULL);
CREATE VIEW v9 AS SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0;
CREATE VIEW v10 AS SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE true;
CREATE VIEW v11 AS SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE (NOT (true));
CREATE VIEW v12 AS SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE ((true) IS NULL);
CREATE VIEW v13 AS SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE true UNION ALL SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE (NOT (true)) UNION ALL SELECT v2_1241.c_2_0 FROM v7 AS v7_1247,  v2 AS v2_1241  LEFT JOIN v3 AS v3_1242 ON v2_1241.c_2_0 = v3_1242.c_2_0 AND v2_1241.c_2_0 <= v3_1242.c_2_0,  v6 AS v6_1246 LEFT ANTI JOIN (SELECT v8_1248.c_2_0 FROM v8 AS v8_1248) subv8 ON v6_1246.c_2_0 = subv8.c_2_0 AND -776219113 >= subv8.c_2_0,  (SELECT t3_1237.c_3_0, t3_1237.c_3_1, t3_1237.c_3_2 FROM t3 AS t3_1237 WHERE NULL) subt3 LEFT SEMI JOIN (SELECT t0_1234.c_0_0, t0_1234.c_0_1, t0_1234.c_0_2, t0_1234.c_0_3, t0_1234.c_0_4, t0_1234.c_0_5, t0_1234.c_0_6, t0_1234.c_0_7, t0_1234.c_0_10, t0_1234.c_0_11 FROM t0 AS t0_1234) subt0 ON subt3.c_3_0 = subt0.c_0_2 AND TO_DATE('1970-01-05')  <= ((1923380642)+(-20354353)) AND subt3.c_3_1 != subt0.c_0_3 AND subt3.c_3_1 >= subt0.c_0_3 AND subt3.c_3_1 != subt0.c_0_6 AND (('')||('')) != subt0.c_0_6 AND subt3.c_3_2 >= subt0.c_0_11 AND subt3.c_3_2 > subt0.c_0_11,  v4 AS v4_1243 LEFT ANTI JOIN v1 AS v1_1240 ON v4_1243.c_2_0 = v1_1240.c_2_0 AND v4_1243.c_2_0 <= v1_1240.c_2_0 WHERE ((true) IS NULL);
CREATE VIEW v14 AS WITH with_t_0 as (SELECT t3_1322.c_3_0, t3_1322.c_3_1, t3_1322.c_3_2 FROM t3 AS t3_1322) SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0;
CREATE VIEW v15 AS WITH with_t_0 as (SELECT t3_1322.c_3_0, t3_1322.c_3_1, t3_1322.c_3_2 FROM t3 AS t3_1322) SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE false;
CREATE VIEW v16 AS WITH with_t_0 as (SELECT t3_1322.c_3_0, t3_1322.c_3_1, t3_1322.c_3_2 FROM t3 AS t3_1322) SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE (NOT (false));
CREATE VIEW v17 AS WITH with_t_0 as (SELECT t3_1322.c_3_0, t3_1322.c_3_1, t3_1322.c_3_2 FROM t3 AS t3_1322) SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE ((false) IS NULL);
CREATE VIEW v18 AS WITH with_t_0 as (SELECT t3_1322.c_3_0, t3_1322.c_3_1, t3_1322.c_3_2 FROM t3 AS t3_1322) SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE false UNION ALL SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE (NOT (false)) UNION ALL SELECT CASE  WHEN false THEN v9_1338.c_2_0  WHEN NULL THEN v9_1338.c_2_0 ELSE v9_1338.c_2_0 END FROM v10 AS v10_1326, v0 AS v0_1324, v5 AS v5_1334, t3 AS t3_1322, v3 AS v3_1331, t0 AS t0_1319, v12 AS v12_1328, v1 AS v1_1325, v8 AS v8_1337, v4 AS v4_1332, t4 AS t4_1323, v13 AS v13_1329, t1 AS t1_1320, with_t_0 AS with_t_0,  v9 AS v9_1338  LEFT JOIN v2 AS v2_1330 ON v9_1338.c_2_0 = v2_1330.c_2_0 AND v9_1338.c_2_0 < v2_1330.c_2_0 WHERE ((false) IS NULL);
CREATE VIEW v99 AS SELECT t2_1431.c_2_0 FROM t2 AS t2_1431, v49 AS v49_1448, v10 AS v10_1436, v1 AS v1_1435, v18 AS v18_1444, v2 AS v2_1445, v14 AS v14_1440, v13 AS v13_1439, t3 AS t3_1432, v12 AS v12_1438, v9 AS v9_1453, v3 AS v3_1446, v15 AS v15_1441, v6 AS v6_1450, v0 AS v0_1434, v17 AS v17_1443, v5 AS v5_1449, v16 AS v16_1442, t4 AS t4_1433, v7 AS v7_1451, v8 AS v8_1452, v4 AS v4_1447;
SELECT * FROM v99;
```

```
fe.log:
java.lang.NullPointerException: null
        at com.starrocks.sql.optimizer.rule.join.JoinReorderGreedy.getBestExpr(JoinReorderGreedy.java:91) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinReorderGreedy.searchJoinOrders(JoinReorderGreedy.java:45) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinReorderGreedy.enumerate(JoinReorderGreedy.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.JoinOrder.reorder(JoinOrder.java:169) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.enumerate(ReorderJoinRule.java:69) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.join.ReorderJoinRule.transform(ReorderJoinRule.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:134) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:103) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:117) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:288) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:436) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:672) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN 1e841c7 |
+-------------------+
- cluster: sqlancer_02_asan

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6515

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java [hunk 1]
```diff
@@ -188,6 +188,7 @@ public class SessionVariable implements Serializable, Writable, Cloneable {
     public static final String CBO_CTE_REUSE = "cbo_cte_reuse";
     public static final String CBO_CTE_REUSE_RATE = "cbo_cte_reuse_rate";
     public static final String ENABLE_SQL_DIGEST = "enable_sql_digest";
+    public static final String CBO_MAX_REORDER_NODE = "max_reorder_node";
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:191]: please user prefix cbo_

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|2|100.00%|

**Review by kangkaisen — APPROVED** [review]
