### PR TITLE
[Enhancement] Modify the ttl semantics to start counting from the current time

### LINKED ISSUE #20669: Automatic partition table is easy for users to misuse and delete data
### Steps to reproduce the behavior (Required)
1. CREATE TABLE site_access(
    event_day datetime,
    site_id INT DEFAULT '10',
    city_code VARCHAR(100),
    user_name VARCHAR(32) DEFAULT '',
    pv BIGINT DEFAULT '0'
)
DUPLICATE KEY(event_day, site_id, city_code, user_name)
PARTITION BY time_slice(event_day, interval 1 day)
DISTRIBUTED BY HASH(event_day, site_id) BUCKETS 32
PROPERTIES(
    "partition_live_number" = "3",
    "replication_num" = "1"
);
2.
INSERT INTO site_access (event_day, site_id, city_code, user_name, pv)
VALUES
('2023-03-27', 1, 'city_code', 'user_name', 1);

INSERT INTO site_access (event_day, site_id, city_code, user_name, pv)
VALUES
('2023-03-28', 1, 'city_code', 'user_name', 1);

INSERT INTO site_access (event_day, site_id, city_code, user_name, pv)
VALUES
('2023-03-29', 1, 'city_code', 'user_name', 1);

INSERT INTO site_access (event_day, site_id, city_code, user_name, pv)
VALUES
('2023-03-30', 1, 'city_code', 'user_name', 1);

INSERT INTO site_access (event_day, site_id, city_code, user_name, pv)
VALUES
('9999-12-31', 1, 'city_code', 'user_name', 1);
### Expected behavior (Required)
Keep the last 3 days of partitions at the current time
### Real behavior (Required)
2023-03-28 partition is deleted.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.0

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20669

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java [hunk 1]
```diff
@@ -458,7 +464,16 @@ private void executePartitionTimeToLive() {
                 continue;
             }
 
-            ArrayList<DropPartitionClause> dropPartitionClauses = getDropPartitionClauseByTTL(olapTable, ttlNumber);
+            ArrayList<DropPartitionClause> dropPartitionClauses = null;
+            try {
+                dropPartitionClauses = getDropPartitionClauseByTTL(olapTable, ttlNumber);
+            } catch (AnalysisException e) {
+                LOG.warn("database={}, table={} Failed to generate drop statement.", dbId, tableId, e);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:471]: is it necessary to throw exception?

File: fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java [hunk 2]
```diff
@@ -475,20 +490,61 @@ private void executePartitionTimeToLive() {
...
+                // The current time is within the range of this partition.
+                if (lowerPartitionKey.compareTo(currentPartitionKey) <= 0
+                        && upperPartitionKey.compareTo(currentPartitionKey) > 0) {
+                    candidatePartitionList.add(partitionRange);
+                }
+            }
+        } else if (partitionType.isNumericType()) {
+            candidatePartitionList = new ArrayList<>(rangePartitionInfo.getIdToRange(false).entrySet());
+        } else {
+            throw new AnalysisException("Partition ttl does not support:" + partitionType);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:536]:
```suggestion
            throw new AnalysisException("Partition ttl does not support type:" + partitionType);
```

File: fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java (hunk 1 above)
Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:471]: This is because PartitionKey.createPartitionKey throws this exception, so it has to be handled.

File: fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java [hunk 3]
```diff
@@ -475,20 +490,61 @@ private void executePartitionTimeToLive() {
...
+                // The current time is greater than the extent of the partition
+                if (lowerPartitionKey.compareTo(currentPartitionKey) < 0
+                        && upperPartitionKey.compareTo(currentPartitionKey) <= 0) {
+                    candidatePartitionList.add(partitionRange);
+                }
+                // The current time is within the range of this partition.
+                if (lowerPartitionKey.compareTo(currentPartitionKey) <= 0
+                        && upperPartitionKey.compareTo(currentPartitionKey) > 0) {
+                    candidatePartitionList.add(partitionRange);
+                }
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:531]: if (lowerPartitionKey.compareTo(currentPartitionKey) <= 0) {
candidatePartitionList.add(partitionRange);
}

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:531]: you are right

**Review by wyb — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
