### PR TITLE
[BugFix] Unexpected exception: failed to init view stmt

### LINKED ISSUE #33841: [sqlancer] Unexpected exception: failed to init view stmt
### Steps to reproduce the behavior (Required)
1. Prepare Data:

```sql
-- Time: 2023/08/10 00:22:54
-- Database: v3
-- Database version: 5.1.0
-- seed value: 1691598037413
DROP DATABASE IF EXISTS v3;
CREATE DATABASE v3;
USE v3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 BOOLEAN NULL ,c_0_2 DECIMAL(30, 0)  NULL ,c_0_3 DATETIME NOT NULL ,c_0_4 DECIMAL(7, 0)  NOT NULL ,c_0_5 DECIMAL(25, 14)  NULL ,c_0_6 DECIMAL(4, 2)  NULL ,c_0_7 TINYINT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 339 day)) DISTRIBUTED BY HASH (c_0_2,c_0_0) BUCKETS 3 properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 VARCHAR(1) NOT NULL,c_1_1 VARCHAR(11) NOT NULL,c_1_2 DATE NOT NULL,c_1_3 DATETIME NOT NULL,c_1_4 BOOLEAN NOT NULL,c_1_5 VARCHAR(21) NOT NULL,c_1_6 BOOLEAN NOT NULL,c_1_7 DATETIME NOT NULL,c_1_8 INT NOT NULL,c_1_9 BOOLEAN NOT NULL,c_1_10 LARGEINT NOT NULL,c_1_11 DOUBLE NOT NULL,c_1_12 LARGEINT NOT NULL,c_1_13 DATETIME NOT NULL,c_1_14 DATETIME NOT NULL,c_1_15 BOOLEAN NOT NULL,c_1_16 INT NOT NULL,c_1_17 FLOAT NOT NULL,c_1_18 ARRAY<STRING> NOT NULL, INDEX index1_c_1_4(`c_1_4`) USING BITMAP) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10) PARTITION BY RANGE(c_1_2) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 98 day)) DISTRIBUTED BY HASH (c_1_1,c_1_4,c_1_6,c_1_10) BUCKETS 3 properties("replication_num"="1") ;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_1154.c_1_0, t1_1154.c_1_1, t1_1154.c_1_2, t1_1154.c_1_3, t1_1154.c_1_4, t1_1154.c_1_5, t1_1154.c_1_6, t1_1154.c_1_7, t1_1154.c_1_8, t1_1154.c_1_9, t1_1154.c_1_10, t1_1154.c_1_11, t1_1154.c_1_12, t1_1154.c_1_13, t1_1154.c_1_14, t1_1154.c_1_16, t1_1154.c_1_17, MIN(t1_1154.c_1_15)  FROM t1 AS t1_1154 GROUP BY t1_1154.c_1_0, t1_1154.c_1_1, t1_1154.c_1_2, t1_1154.c_1_3, t1_1154.c_1_4, t1_1154.c_1_5, t1_1154.c_1_6, t1_1154.c_1_7, t1_1154.c_1_8, t1_1154.c_1_9, t1_1154.c_1_10, t1_1154.c_1_11, t1_1154.c_1_12, t1_1154.c_1_13, t1_1154.c_1_14, t1_1154.c_1_16, t1_1154.c_1_17 ORDER BY t1_1154.c_1_0, t1_1154.c_1_1 ASC, t1_1154.c_1_2 ASC, t1_1154.c_1_3, t1_1154.c_1_4 DESC, t1_1154.c_1_5 ASC, t1_1154.c_1_6, t1_1154.c_1_7, t1_1154.c_1_8 DESC, t1_1154.c_1_9 DESC, t1_1154.c_1_10 DESC, t1_1154.c_1_11, t1_1154.c_1_12 ASC, t1_1154.c_1_13 ASC, t1_1154.c_1_14 ASC, t1_1154.c_1_16, t1_1154.c_1_17;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_1156.c_1_1, t1_1156.c_1_5, t1_1156.c_1_6, t1_1156.c_1_8, t1_1156.c_1_10, t1_1156.c_1_11, t1_1156.c_1_12, t1_1156.c_1_13, t1_1156.c_1_16, MAX(t1_1156.c_1_0) , MAX(t1_1156.c_1_2) , MIN(t1_1156.c_1_3) , MIN(t1_1156.c_1_4) , MIN(t1_1156.c_1_7) , MIN(t1_1156.c_1_9) , MIN(t1_1156.c_1_14) , MAX(t1_1156.c_1_15) , MAX(t1_1156.c_1_17)  FROM t1 AS t1_1156 GROUP BY t1_1156.c_1_1, t1_1156.c_1_5, t1_1156.c_1_6, t1_1156.c_1_8, t1_1156.c_1_10, t1_1156.c_1_11, t1_1156.c_1_12, t1_1156.c_1_13, t1_1156.c_1_16 ORDER BY t1_1156.c_1_1, t1_1156.c_1_5 ASC, t1_1156.c_1_6 DESC, t1_1156.c_1_8 DESC, t1_1156.c_1_10 ASC, t1_1156.c_1_11 ASC, t1_1156.c_1_12, t1_1156.c_1_13 ASC, t1_1156.c_1_16;
TRUNCATE TABLE t0;
CREATE VIEW v29 AS WITH with_t_0 as (SELECT t0_1159.c_0_0, t0_1159.c_0_1, t0_1159.c_0_2, t0_1159.c_0_3, t0_1159.c_0_4, t0_1159.c_0_5, t0_1159.c_0_6, t0_1159.c_0_7 FROM t0 AS t0_1159) SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0;
CREATE VIEW v0 AS WITH with_t_0 as (SELECT t0_1159.c_0_0, t0_1159.c_0_1, t0_1159.c_0_2, t0_1159.c_0_3, t0_1159.c_0_4, t0_1159.c_0_5, t0_1159.c_0_6, t0_1159.c_0_7 FROM t0 AS t0_1159) SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE true;
CREATE VIEW v1 AS WITH with_t_0 as (SELECT t0_1159.c_0_0, t0_1159.c_0_1, t0_1159.c_0_2, t0_1159.c_0_3, t0_1159.c_0_4, t0_1159.c_0_5, t0_1159.c_0_6, t0_1159.c_0_7 FROM t0 AS t0_1159) SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE (NOT (true));
CREATE VIEW v2 AS WITH with_t_0 as (SELECT t0_1159.c_0_0, t0_1159.c_0_1, t0_1159.c_0_2, t0_1159.c_0_3, t0_1159.c_0_4, t0_1159.c_0_5, t0_1159.c_0_6, t0_1159.c_0_7 FROM t0 AS t0_1159) SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE ((true) IS NULL);
CREATE VIEW v78 AS (WITH with_t_0 as (SELECT t0_1159.c_0_0, t0_1159.c_0_1, t0_1159.c_0_2, t0_1159.c_0_3, t0_1159.c_0_4, t0_1159.c_0_5, t0_1159.c_0_6, t0_1159.c_0_7 FROM t0 AS t0_1159) (SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE true) UNION ALL (SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE (NOT (true))) UNION ALL (SELECT t0_1159.c_0_0 FROM t0 AS t0_1159, t1 AS t1_1160, with_t_0 AS with_t_0 WHERE ((true) IS NULL)) );
CREATE VIEW v3 AS SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181;
CREATE VIEW v4 AS SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE NULL;
CREATE VIEW v5 AS SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE (NOT (NULL));
CREATE VIEW v6 AS SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE ((NULL) IS NULL);
CREATE VIEW v95 AS ((SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE NULL) UNION ALL (SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE (NOT (NULL))) UNION ALL (SELECT v78_1185.c_0_0 FROM v78 AS v78_1185, t1 AS t1_1180, v29 AS v29_1184, v1 AS v1_1182, t0 AS t0_1179, v0 AS v0_1181 WHERE ((NULL) IS NULL)) );
CREATE VIEW v7 AS SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0;
CREATE VIEW v8 AS SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE false;
CREATE VIEW v9 AS SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE (NOT (false));
CREATE VIEW v10 AS SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE ((false) IS NULL);
CREATE VIEW v11 AS ((SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE false) UNION ALL (SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE (NOT (false))) UNION ALL (SELECT (('')||(NULL)) FROM  (SELECT t1_1225.c_1_0, t1_1225.c_1_1, t1_1225.c_1_2, t1_1225.c_1_3, t1_1225.c_1_4, t1_1225.c_1_5, t1_1225.c_1_6, t1_1225.c_1_7, t1_1225.c_1_8, t1_1225.c_1_9, t1_1225.c_1_10, t1_1225.c_1_11, t1_1225.c_1_12, t1_1225.c_1_13, t1_1225.c_1_14, t1_1225.c_1_15, t1_1225.c_1_16, t1_1225.c_1_17 FROM t1 AS t1_1225 WHERE false) subt1 LEFT SEMI JOIN (SELECT v0_1226.c_0_0 FROM v0 AS v0_1226 WHERE CASE  WHEN NULL THEN (NOT (true))  WHEN false THEN  ( v0_1226.c_0_0 ) <= ( v0_1226.c_0_0 )   WHEN ((v0_1226.c_0_0) IS NULL) THEN ((v0_1226.c_0_0) IS NULL) ELSE ((v0_1226.c_0_0) IS NULL) END) subv0 ON subt1.c_1_1 = subv0.c_0_0 AND subt1.c_1_1 < subv0.c_0_0 AND subt1.c_1_17 < subv0.c_0_0 AND subt1.c_1_17 = subv0.c_0_0 WHERE ((false) IS NULL)) );
CREATE VIEW v12 AS SELECT v10_1298.concat('', NULL) FROM v10 AS v10_1298, v2 AS v2_1300, v1 AS v1_1297, v29 AS v29_1301, v7 AS v7_1306, v8 AS v8_1308, v6 AS v6_1305, t0 AS t0_1294, v11 AS v11_1299, v4 AS v4_1303, v0 AS v0_1296, v3 AS v3_1302, v95 AS v95_1310, t1 AS t1_1295;

```

2. Query

```sql
CREATE VIEW v12 AS SELECT v10_1298.concat('', NULL) FROM v10 AS v10_1298, v2 AS v2_1300, v1 AS v1_1297, v29 AS v29_1301, v7 AS v7_1306, v8 AS v8_1308, v6 AS v6_1305, t0 AS t0_1294, v11 AS v11_1299, v4 AS v4_1303, v0 AS v0_1296, v3 AS v3_1302, v95 AS v95_1310, t1 AS t1_1295;
```
### Expected behavior (Required)
NO Error

### Real behavior (Required)
Error as follows
```
--java.lang.AssertionError: CREATE VIEW v12 AS SELECT v10_1298.concat('', NULL) FROM v10 AS v10_1298, v2 AS v2_1300, v1 AS v1_1297, v29 AS v29_1301, v7 AS v7_1306, v8 AS v8_1308, v6 AS v6_1305, t0 AS t0_1294, v11 AS v11_1299, v4 AS v4_1303, v0 AS v0_1296, v3 AS v3_1302, v95 AS v95_1310, t1 AS t1_1295;
--	at sqlancer.common.query.QueryAdapter.checkException(QueryAdapter.java:98)
--	at sqlancer.common.query.QueryAdapter.execute(QueryAdapter.java:91)
--	at sqlancer.Main$QueryManager.execute(Main.java:257)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:131)
--	at sqlancer.starrocks.oracle.tlp.StarRocksTLPViewOracle.createView(StarRocksTLPViewOracle.java:108)
--	at sqlancer.starrocks.oracle.tlp.StarRocksTLPViewOracle.check(StarRocksTLPViewOracle.java:33)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:55)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:342)
--	at sqlancer.Main$2.run(Main.java:557)
--	at sqlancer.Main$2.runThread(Main.java:533)
--	at sqlancer.Main$2.run(Main.java:523)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unexpected exception: failed to init view stmt
--	at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:839)
--	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:739)
--	at sqlancer.common.query.QueryAdapter.execute(QueryAdapter.java:85)
--	... 12 more
--
```
### StarRocks version (Required)
- main(b0cfdcf)

### PR DESCRIPTION
**Pull request by liubotao**
Fixes [#issue](https://github.com/StarRocks/starrocks/issues/33841)

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java [hunk 1]
```diff
@@ -161,10 +161,10 @@ public String visitSelect(SelectRelation stmt, Void context) {
                                     columnName));
                         }
                     } else {
+                        String aliasColumn = stmt.getSelectList().getItems().get(i).getAlias();
                         selectListString.add(
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java:165]: outputExpressions may have a different size with selectList.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java [hunk 2]
```diff
@@ -142,6 +140,17 @@ public String visitSelect(SelectRelation stmt, Void context) {
                 sqlBuilder.append("DISTINCT ");
             }
 
+            Map<FunctionCallExpr, String> selectFuncCallExprAliasMap = new HashMap<>();
+            for (SelectListItem selectListItem : selectList.getItems()) {
+                if (selectListItem.getExpr() != null
+                        && !(selectListItem.getExpr() instanceof FieldReference)
+                        && !(selectListItem.getExpr() instanceof SlotRef)
+                ) {
+                    selectFuncCallExprAliasMap.put((FunctionCallExpr)selectListItem.getExpr(),
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AstToSQLBuilder.java:149]: Use `Expr`as key becauee it may not a functionCallExpr.

**Review by packy92 — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by packy92 — APPROVED** [review]
