### PR TITLE
[BugFix] Fix broker load ssl_enable does not take effect

### LINKED ISSUE #57325: broker load ssl_enable does not take effect
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What I'm doing:

Fixes #57325

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: be/src/fs/fs_s3.cpp [hunk 1]
```diff
@@ -289,6 +289,8 @@ static std::shared_ptr<Aws::S3::S3Client> new_s3client(
         }
         if (hdfs_properties->__isset.ssl_enable && hdfs_properties->ssl_enable) {
             config.scheme = Aws::Http::Scheme::HTTPS;
+        } else if (hdfs_properties->__isset.ssl_enable && !hdfs_properties->ssl_enable) {
```
Comment (kevincai) [inline be/src/fs/fs_s3.cpp:292]:
```suggestion
        if (hdfs_properties->__isset.ssl_enable) {
            config.scheme = hdfs_properties->ssl_enable ? Aws::Http::Scheme::HTTPS : Aws::Http::Scheme::HTTP;
        }
```

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]
