### PR TITLE
[BugFix] ESDataSource to use uninitialized variable

### LINKED ISSUE #6413: [sqlsmith] es query sql oom
### Steps to reproduce the behavior (Required)

```
sql:
select distinct 
  cast(nullif(subq_0.c0,
    subq_0.c1) as VARCHAR) as c0
from 
  (select  
        ref_0.s_city as c0, 
        ref_0.s_nation as c1, 
        ref_0.s_address as c2, 
        ref_0.s_region as c3, 
        ref_0.s_region as c4, 
        ref_0.s_suppkey as c5
      from 
        sqlsmith.es_ssb_10g_supplier as ref_0
      where (cast(coalesce(cast(null as DOUBLE),
            cast(null as DOUBLE)) as DOUBLE) <> cast(coalesce(cast(null as DOUBLE),
            cast(null as DOUBLE)) as DOUBLE)) 
        or (e() is NULL)
      limit 92) as subq_0
where true
limit 143;
```

```
crash.log:
tcmalloc: large alloc 2134007808 bytes == 0x7553de000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x35002e6 0x350095e 0x3500cbb 0x316fbcc 0x2c1931c 0x283ec62 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
tcmalloc: large alloc 2137710592 bytes == 0x698eec000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x35002e6 0x350095e 0x3500cbb 0x316fbcc 0x2c1931c 0x283ec62 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
tcmalloc: large alloc 1795170304 bytes == 0x61b126000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x32b2482 0x2934d8d 0x2936d3a 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
tcmalloc: large alloc 1816166400 bytes == 0x7d4704000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x32b2482 0x2934d8d 0x2936d3a 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
tcmalloc: large alloc 1802207232 bytes == 0x84130c000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x1ac9c5a 0x2934ad3 0x2936d3a 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
tcmalloc: large alloc 2131058688 bytes == 0x7553de000 @  0x5758faf 0x59ea61c 0x204a45a 0x593aa95 0x35002e6 0x350095e 0x3500cbb 0x316fbcc 0x2c1931c 0x283ec62 0x286b387 0x28608c4 0x20ec749 0x20e82fa 0x7fcd6833ae65
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE ebb36c3 |
+----------------------+
- cluster:sqlsmith_branch_release
- path: /home/disk1/sr/sqlsmith_branch_release/be/log

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [X] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6413,  #6408

## Problem Summary(Required) ：

`_read_timer` and `_es_reader` are not initailized if `_no_data = true`

### CODE REVIEW

**Review by DorianZheng — DISMISSED** [review]
LGTM

File: be/src/connector/es_connector.h [hunk 1]
```diff
@@ -75,7 +75,7 @@ class ESDataSource final : public DataSource {
     int64_t _rows_read_number = 0;
     int64_t _rows_return_number = 0;
 
-    ESScanReader* _es_reader;
+    ESScanReader* _es_reader = nullptr;
     std::unique_ptr<vectorized::ScrollParser> _es_scroll_parser;
 
     RuntimeProfile::Counter* _read_counter;
```
Comment (imay) [inline be/src/connector/es_connector.h:81]: why not give this counter initialization value.

File: be/src/connector/es_connector.cpp [hunk 2]
```diff
@@ -201,11 +201,11 @@ void ESDataSource::_init_counter() {
 }
 
 Status ESDataSource::get_next(RuntimeState* state, vectorized::ChunkPtr* chunk) {
-    SCOPED_TIMER(_read_timer);
     if (_no_data || (_line_eof && _batch_eof)) {
         return Status::EndOfFile("");
     }
 
+    SCOPED_TIMER(_read_timer);
```
Comment (imay) [inline be/src/connector/es_connector.cpp:208]: Could you leave a notice ?

**Review by imay — APPROVED** [review]
