### PR TITLE
fix: make json type support case-when expression

### LINKED ISSUE #4518: query crash
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS w36;
CREATE DATABASE w36;
USE w36;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NOT NULL ,c_0_1 SMALLINT NOT NULL ,c_0_2 BIGINT NULL ,c_0_3 SMALLINT NULL ,c_0_4 DATETIME NULL ,c_0_5 DECIMAL(20, 1)  NOT NULL ,c_0_6 TINYINT NOT NULL ,c_0_7 BOOLEAN NOT NULL ,c_0_8 DATE NULL ,c_0_9 BOOLEAN NOT NULL ,c_0_10 TINYINT NOT NULL ,c_0_11 VARCHAR(1) NOT NULL ,c_0_12 FLOAT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) PARTITION BY RANGE(c_0_0) (START ("2000-01-01") END ("2021-12-31") EVERY (INTERVAL 8035 day)) DISTRIBUTED BY HASH (c_0_7,c_0_9,c_0_2,c_0_6,c_0_1,c_0_4,c_0_3,c_0_10,c_0_8) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NULL ,c_1_1 DATE NOT NULL ,c_1_2 DATE NULL ,c_1_3 DATE NULL ,c_1_4 INT NOT NULL ,c_1_5 CHAR(21) NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3) PARTITION BY RANGE(c_1_0) (START ("2000-01-01") END ("2021-12-31") EVERY (INTERVAL 502 day)) DISTRIBUTED BY HASH (c_1_2,c_1_0) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 VARCHAR(21) NOT NULL ,c_2_1 DATE NULL ,c_2_2 CHAR(11) NOT NULL ,c_2_3 JSON NULL ,c_2_4 LARGEINT NOT NULL ,c_2_5 BOOLEAN NOT NULL ,c_2_6 TINYINT NULL ,c_2_7 VARCHAR(1) NOT NULL ,c_2_8 DOUBLE NULL ,c_2_9 DATETIME NULL ,c_2_10 BOOLEAN NOT NULL ,c_2_11 JSON NOT NULL ,c_2_12 ARRAY<STRING> NULL ,c_2_13 DECIMAL(34, 1)  NULL ) DUPLICATE KEY (c_2_0,c_2_1,c_2_2) PARTITION BY RANGE(c_2_1) (START ("2000-01-01") END ("2021-12-31") EVERY (INTERVAL 104 day)) DISTRIBUTED BY HASH (c_2_2,c_2_1,c_2_0) properties("replication_num"="3") ;
DELETE FROM t0 WHERE c_0_3=-1313484988 AND c_0_7=false AND c_0_2=1356098846 AND c_0_9=false AND c_0_5=680000979293077246.5 AND c_0_10=-714478025;
DELETE FROM t0 WHERE c_0_7=true AND c_0_9=false AND c_0_0="1970-01-19" AND c_0_8="1969-12-28" AND c_0_6=1591128601 AND c_0_10=-85932833 AND c_0_2=-747825157 AND c_0_1=-1271960122 AND c_0_3=388907815;
INSERT INTO t1 VALUES ("2000-01-30", "2000-01-16", "2000-01-28", "2000-01-14", 1, "");
INSERT INTO t1 VALUES ("2000-01-21", "2000-01-31", "2000-01-02", "2000-01-11", 6, "7wZCqz");
INSERT INTO t1 VALUES ("2000-01-28", "2000-01-12", "2000-01-03", "2000-01-13", 31, "");
INSERT INTO t0 VALUES ("2000-01-25", 10, -1873066077, NULL, "2000-01-30 08:00:10", 651900468424753478.1, 0, true, "2000-01-10", false, 5, "", 1.356098846E9);
SELECT t1.c_1_0 FROM t1, t0, t2 WHERE (((CAST(CASE  WHEN (t2.c_2_8)  BETWEEN (t2.c_2_8) AND (t2.c_2_8)  THEN JSON_OBJECT("X", parse_json('{"wo": null}'), "", parse_json('{"tw": null, "fl": 1819653634, "h": "QOUM5sL", "pRsFVi5": 0.4508441053531339, "ZBy": "", "rb": -1104769900, "q": [-1851555724, true, 0.434228840916847, "MuYwbOc", false, 0.8287057652676189, "", null, 0.583247200314665, null, 1897205482], "5ulQSzf": [null], "s": false, "RVHnQf": -1.7976931348623157E308, "u": {"p": true, "sgBVM": "vFnA", "ohI": true, "juZJynPW": 1594768606, "C": false, "t": -1295805940, "gdH0": -622554692, "3L": null, "o": null}, "uww8": [0.9076995700094375, 0.5503495082528196, "", null], "y": [""]}'))  ELSE t2.c_2_3 END AS STRING ) )||((("")||("y")))))  BETWEEN (t1.c_1_5) AND (t1.c_1_5)  UNION ALL SELECT t1.c_1_0 FROM t1, t0, t2 WHERE (NOT ((((CAST(CASE  WHEN (t2.c_2_8)  BETWEEN (t2.c_2_8) AND (t2.c_2_8)  THEN JSON_OBJECT("X", parse_json('{"wo": null}'), "", parse_json('{"tw": null, "fl": 1819653634, "h": "QOUM5sL", "pRsFVi5": 0.4508441053531339, "ZBy": "", "rb": -1104769900, "q": [-1851555724, true, 0.434228840916847, "MuYwbOc", false, 0.8287057652676189, "", null, 0.583247200314665, null, 1897205482], "5ulQSzf": [null], "s": false, "RVHnQf": -1.7976931348623157E308, "u": {"p": true, "sgBVM": "vFnA", "ohI": true, "juZJynPW": 1594768606, "C": false, "t": -1295805940, "gdH0": -622554692, "3L": null, "o": null}, "uww8": [0.9076995700094375, 0.5503495082528196, "", null], "y": [""]}'))  ELSE t2.c_2_3 END AS STRING ) )||((("")||("y")))))  BETWEEN (t1.c_1_5) AND (t1.c_1_5) )) UNION ALL SELECT t1.c_1_0 FROM t1, t0, t2 WHERE (((((CAST(CASE  WHEN (t2.c_2_8)  BETWEEN (t2.c_2_8) AND (t2.c_2_8)  THEN JSON_OBJECT("X", parse_json('{"wo": null}'), "", parse_json('{"tw": null, "fl": 1819653634, "h": "QOUM5sL", "pRsFVi5": 0.4508441053531339, "ZBy": "", "rb": -1104769900, "q": [-1851555724, true, 0.434228840916847, "MuYwbOc", false, 0.8287057652676189, "", null, 0.583247200314665, null, 1897205482], "5ulQSzf": [null], "s": false, "RVHnQf": -1.7976931348623157E308, "u": {"p": true, "sgBVM": "vFnA", "ohI": true, "juZJynPW": 1594768606, "C": false, "t": -1295805940, "gdH0": -622554692, "3L": null, "o": null}, "uww8": [0.9076995700094375, 0.5503495082528196, "", null], "y": [""]}'))  ELSE t2.c_2_3 END AS STRING ) )||((("")||("y")))))  BETWEEN (t1.c_1_5) AND (t1.c_1_5) ) IS NULL);
```

```
crash.log:
==10209==ERROR: AddressSanitizer: heap-use-after-free on address 0x61d00056d680 at pc 0x000006d4404d bp 0x7f90b7a786d0 sp 0x7f90b7a786c8
READ of size 8 at 0x61d00056d680 thread T379
    #0 0x6d4404c in starrocks::vectorized::CrossJoinNode::close(starrocks::RuntimeState*) /root/starrocks/be/src/exec/vectorized/cross_join_node.cpp:441
    #1 0x62812b2 in starrocks::vectorized::CrossJoinNode::~CrossJoinNode() /root/starrocks/be/src/exec/vectorized/cross_join_node.h:16
    #2 0x62813b3 in starrocks::vectorized::CrossJoinNode::~CrossJoinNode() /root/starrocks/be/src/exec/vectorized/cross_join_node.h:18
    #3 0x6287052 in starrocks::ObjectPool::add<starrocks::vectorized::CrossJoinNode>(starrocks::vectorized::CrossJoinNode*)::{lambda(void*)#1}::operator()(void*) const (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x6287052)
    #4 0x6287072 in starrocks::ObjectPool::add<starrocks::vectorized::CrossJoinNode>(starrocks::vectorized::CrossJoinNode*)::{lambda(void*)#1}::_FUN(void*) (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x6287072)
    #5 0x452a14f in starrocks::ObjectPool::clear() /root/starrocks/be/src/common/object_pool.h:56
    #6 0x4529f61 in starrocks::ObjectPool::~ObjectPool() /root/starrocks/be/src/common/object_pool.h:38
    #7 0x56c5cbe in std::_Sp_counted_ptr<starrocks::ObjectPool*, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x56c5cbe)
    #8 0x42eacac in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #9 0x42e7c19 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #10 0x56ba177 in std::__shared_ptr<starrocks::ObjectPool, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #11 0x56ba193 in std::shared_ptr<starrocks::ObjectPool>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #12 0x56b3028 in starrocks::RuntimeState::~RuntimeState() /root/starrocks/be/src/runtime/runtime_state.cpp:102
    #13 0x6eb978d in std::default_delete<starrocks::RuntimeState>::operator()(starrocks::RuntimeState*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #14 0x6ed6d18 in std::_Sp_counted_deleter<starrocks::RuntimeState*, std::default_delete<starrocks::RuntimeState>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:474
    #15 0x42eacac in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #16 0x42e7c19 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #17 0x4539737 in std::__shared_ptr<starrocks::RuntimeState, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #18 0x4539753 in std::shared_ptr<starrocks::RuntimeState>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #19 0x453a091 in starrocks::pipeline::FragmentContext::~FragmentContext() (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x453a091)
    #20 0x453ed4b in std::default_delete<starrocks::pipeline::FragmentContext>::operator()(starrocks::pipeline::FragmentContext*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #21 0x453d0b2 in std::unique_ptr<starrocks::pipeline::FragmentContext, std::default_delete<starrocks::pipeline::FragmentContext> >::~unique_ptr() /usr/include/c++/10.3.0/bits/unique_ptr.h:361
    #22 0x6ea3e2f in starrocks::pipeline::FragmentExecutor::prepare(starrocks::ExecEnv*, starrocks::TExecPlanFragmentParams const&) /root/starrocks/be/src/exec/pipeline/fragment_executor.cpp:100
    #23 0x5722c89 in starrocks::PInternalServiceImpl<doris::PBackendService>::_exec_plan_fragment(brpc::Controller*) (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x5722c89)
    #24 0x571e26f in starrocks::PInternalServiceImpl<doris::PBackendService>::exec_plan_fragment(google::protobuf::RpcController*, starrocks::PExecPlanFragmentRequest const*, starrocks::PExecPlanFragmentResult*, google::protobuf::Closure*) (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0x571e26f)
    #25 0x608c84d in doris::PBackendService::CallMethod(google::protobuf::MethodDescriptor const*, google::protobuf::RpcController*, google::protobuf::Message const*, google::protobuf::Message*, google::protobuf::Closure*) /root/starrocks/gensrc/build/gen_cpp/doris_internal_service.pb.cc:201
    #26 0x9fc411d in brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/policy/baidu_rpc_protocol.cpp:496
    #27 0x9fbab86 in brpc::ProcessInputMessage(void*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:135
    #28 0x9fbba32 in brpc::RunLastMessage::operator()(brpc::InputMessageBase*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:141
    #29 0x9fbba32 in std::unique_ptr<brpc::InputMessageBase, brpc::RunLastMessage>::~unique_ptr() /usr/include/c++/10.3.0/bits/unique_ptr.h:361
    #30 0x9fbba32 in brpc::InputMessenger::OnNewMessages(brpc::Socket*) /usr/include/c++/10.3.0/bits/unique_ptr.h:355
    #31 0xa06202d in brpc::Socket::ProcessEvent(void*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/socket.cpp:1017
    #32 0x9f7087e in bthread::TaskGroup::task_runner(long) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/task_group.cpp:296
    #33 0xa0f87b0 in bthread_make_fcontext (/home/disk1/sr/sqlancer_01_asan/be/lib/starrocks_be+0xa0f87b0)

0x61d00056d680 is located 0 bytes inside of 2056-byte region [0x61d00056d680,0x61d00056de88)
freed by thread T379 here:
    #0 0x429d897 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172

previously allocated by thread T379 here:
    #0 0x429ca77 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99

Thread T379 created by T0 here:
    #0 0x4246772 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x9f6bd5b in bthread::TaskControl::add_workers(int) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/task_control.cpp:199
    #2 0x9f6204c in bthread_setconcurrency /var/local/thirdparty/src/incubator-brpc-0.9.7/src/bthread/bthread.cpp:310
    #3 0xa0536a1 in brpc::Server::StartInternal(in_addr const&, brpc::PortRange const&, brpc::ServerOptions const*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/server.cpp:915
    #4 0xa05510c in brpc::Server::Start(butil::EndPoint const&, brpc::ServerOptions const*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/server.cpp:1061
    #5 0xa05522b in brpc::Server::Start(int, brpc::ServerOptions const*) /var/local/thirdparty/src/incubator-brpc-0.9.7/src/brpc/server.cpp:1080
    #6 0x56fe547 in starrocks::BRpcService::start(int) /root/starrocks/be/src/service/brpc_service.cpp:58
    #7 0x42dd310 in main /root/starrocks/be/src/service/starrocks_main.cpp:236
    #8 0x7f9130c83554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: heap-use-after-free /root/starrocks/be/src/exec/vectorized/cross_join_node.cpp:441 in starrocks::vectorized::CrossJoinNode::close(starrocks::RuntimeState*)
Shadow bytes around the buggy address:
  0x0c3a800a5a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800a5a90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800a5aa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800a5ab0: 00 fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800a5ac0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3a800a5ad0:[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3a800a5ae0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3a800a5af0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3a800a5b00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3a800a5b10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3a800a5b20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==10209==ABORTING

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.2 asan
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN 470b7d9 |
+------------------------------+

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4518 

## Problem Summary(Required) ：

Make JSON type support case-when expression.

### CODE REVIEW

**Review by kangkaisen — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

File: be/src/exec/vectorized/cross_join_node.cpp [hunk 1]
```diff
@@ -438,7 +440,6 @@ Status CrossJoinNode::close(RuntimeState* state) {
         _probe_chunk->reset();
     }
 
-    child(0)->close(state);
```
Comment (Seaven) [inline be/src/exec/vectorized/cross_join_node.cpp:441]: Why remove it?

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
