### PR TITLE
[Enhancement] avoid duplicated local shuffle of lake table

### LINKED ISSUE #18388: [StarOS] some failure from shuffle join cases
### Steps to reproduce the behavior (Required)
```
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_aggregate
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_aggregate_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_aggregate_on_others
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_broadcast_join_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_broadcast_join_on_others
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_colocate_join_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_colocate_join_on_others
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_distinct_aggregate_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_distinct_aggregate_on_others
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_hash_join ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_hash_join
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_local_bucket_shuffle_join_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_local_bucket_shuffle_join_on_others
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_window_function ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_window_function
FAILED (failures=1)
test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_window_function_on_others ... FAIL
FAIL: test_dql.test_pipeline_local_shuffle.TestPipelineLocalShuffle.test_window_function_on_others
FAILED (failures=1)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 800b5477f |
+-------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18388 

## Problem Summary(Required) ：

Optimization of duplicated local shuffle removal has been done in https://github.com/StarRocks/starrocks/pull/15268, while the `ConnectorScanOperator` has not. In this PR, this optimization is also done in lake table.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|0|2|00.00%|[776, 777]|

**Comment by TszKitLo40** [comment]
run starrocks_be_unittest

**Comment by TszKitLo40** [comment]
run starrocks_admit_test

File: be/src/exec/pipeline/scan/connector_scan_operator.cpp [hunk 1]
```diff
@@ -48,6 +48,12 @@ OperatorPtr ConnectorScanOperatorFactory::do_create(int32_t dop, int32_t driver_
     return std::make_shared<ConnectorScanOperator>(this, _id, driver_sequence, dop, _scan_node);
 }
 
+const std::vector<ExprContext*>& ConnectorScanOperatorFactory::partition_exprs() const {
```
Comment (dirtysalt) [inline be/src/exec/pipeline/scan/connector_scan_operator.cpp:51]: Where you use `partition_exprs` this function?

File: be/src/connector/connector.h [hunk 2]
```diff
@@ -110,6 +110,13 @@ class DataSourceProvider {
     virtual bool accept_empty_scan_ranges() const { return true; }
 
     virtual bool stream_data_source() const { return false; }
+
+    virtual Status init(ObjectPool* pool, RuntimeState* state) { return Status::OK(); }
+
+    const std::vector<ExprContext*>& bucket_exprs() const { return _bucket_exprs; }
```
Comment (dirtysalt) [inline be/src/connector/connector.h:116]: empty function named as `partition_exprs()`

File: be/src/connector/connector.h [hunk 3]
```diff
@@ -110,6 +110,13 @@ class DataSourceProvider {
...
+
+protected:
+    std::vector<ExprContext*> _bucket_exprs;
```
Comment (dirtysalt) [inline be/src/connector/connector.h:119]: moved to `LakeDataSourceProvider`

File: be/src/exec/pipeline/scan/connector_scan_operator.cpp (hunk 1 above)
Comment (TszKitLo40) [reply be/src/exec/pipeline/scan/connector_scan_operator.cpp:51]: It is override from `SourceOperatorFactory`.

**Comment by TszKitLo40** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by TszKitLo40** [comment]
run starrocks_fe_unittest

**Comment by TszKitLo40** [comment]
run starrocks_fe_unittest

**Comment by TszKitLo40** [comment]
run starrocks_admit_test

**Comment by TszKitLo40** [comment]
run starrocks_be_unittest

**Comment by TszKitLo40** [comment]
run starrocks_fe_unittest

**Comment by TszKitLo40** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|0|2|00.00%|[776, 777]|
