### PR TITLE
[BugFix]Can not see the loaded data when the state of broker load turn into finished from follower node

### LINKED ISSUE #6220: Can not see the loaded data when the state of `broker load` turn into `finished`.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #6220

## Problem Summary(Required) ：

Show Load & Show Routine do not use FORWARD_WITH_SYNC. If the metadata of the imported data results are not synchronized to followers, querying these data will report an error. Using FORWARD_WITH_SYNC will keep the metadata consistent for these queries

### CODE REVIEW

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowLoadStmt.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/analysis/ShowRoutineLoadTaskStmt.java|0|1|00.00%|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowLoadStmt.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/analysis/ShowRoutineLoadTaskStmt.java|1|1|100.00%|

**Review by gengjun-git — APPROVED** [review]
LGTM

File: fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadTaskStmt.java [hunk 1]
```diff
@@ -150,7 +150,7 @@ public ShowResultSetMetaData getMetaData() {
 
     @Override
     public RedirectStatus getRedirectStatus() {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadTaskStmt.java:152]: How to handle the query when the follower is lagging from the master?
If you are all forward the request to the master, we should not make the user use the follower.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/analysis/ShowRoutineLoadTaskStmt.java:152]: SHOW LOAD/SHOW ROUTINE LOAD is load related meta. The current process of these two stmts is forward to master. This change is to make sure that the connected follower has replicated the latest data from master before returning to user, so that the newly loaded data can be queried right after the load state is finished.

**Review by chaoyli — APPROVED** [review]
