### PR TITLE
[BugFix] Fix un-processed NULL_TYPE

### LINKED ISSUE #21972: Sqlaner Error "NULL_TYPE is illegal in thrift stage"
### Steps to reproduce the behavior (Required)
1. prepare data
```sql
DROP DATABASE IF EXISTS d7;
CREATE DATABASE d7;
USE d7;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NOT NULL ,c_0_1 SMALLINT MAX NULL ,c_0_2 CHAR(21) MIN NULL ,c_0_3 SMALLINT REPLACE NULL ,c_0_4 DOUBLE MIN NULL ) AGGREGATE KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 115 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ,c_1_1 DATETIME NULL ,c_1_2 DECIMAL(14, 2)  NULL ,c_1_3 CHAR(1) NOT NULL ,c_1_4 DECIMAL(1, 0)  NOT NULL ,c_1_5 BOOLEAN NOT NULL ,c_1_6 BOOLEAN NOT NULL ,c_1_7 DATE NOT NULL ,c_1_8 INT NOT NULL ,c_1_9 BOOLEAN NOT NULL ,c_1_10 SMALLINT NOT NULL ,c_1_11 DECIMAL(1, 0)  NULL ,c_1_12 DECIMAL(22, 9)  NULL , INDEX index1_c_1_7(`c_1_7`) USING BITMAP) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 189 day)) DISTRIBUTED BY HASH (c_1_11,c_1_8,c_1_10,c_1_0,c_1_6,c_1_5,c_1_1,c_1_2) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_3") ;
INSERT INTO t1 VALUES ('2010-01-01 08:00:14', '2010-01-26 08:00:14', NULL, '', 2, true, false, '2010-01-19', 20, false, 3, 8, 6192.758257631), ('2010-01-19 08:00:14', '2010-01-10 08:00:14', 5319117516.63, '', 5, true, false, '2010-01-19', 19, true, 1, 1, 971.393309088);
INSERT INTO t0 VALUES ('2010-01-27 08:00:14', 1, 'ZZq8vLerj', 1, 0.2936273522796976);
DELETE FROM t0 WHERE c_0_0='1969-12-20 06:48:25';
INSERT INTO t0 VALUES ('2010-01-12 08:00:14', 15, 'b', 12, 0.2936273522796976), ('2010-01-27 08:00:14', 4, '', 2, 0.841342676952513);
INSERT INTO t0 VALUES ('2010-01-29 08:00:14', 12, 'AW2sGAI', 13, 0.9733227055445478), ('2010-01-18 08:00:14', 14, 'A', 14, -1.041094952E9);
INSERT INTO t1 VALUES ('2010-01-23 08:00:14', '2010-01-20 08:00:14', 378554168.22, '', 0, true, true, '2010-01-05', 23, false, 8, 0, 4204.242449469);
INSERT INTO t1 VALUES ('2010-01-18 08:00:14', '2010-01-31 08:00:14', 2228380427.28, '', 8, false, true, '2010-01-11', 29, true, 8, 6, 3073.473382929);
INSERT INTO t0 VALUES ('2010-01-26 08:00:14', 1, '4n8', 6, NULL), ('2010-01-27 08:00:14', 8, NULL, 2, 0.9430070523121846);
INSERT INTO t1 VALUES ('2010-01-15 08:00:14', '2010-01-30 08:00:14', 6495038508.11, '', 1, true, false, '2010-01-30', 8, true, 10, 4, 5796.051379658);
INSERT INTO t1 VALUES ('2009-12-31 08:00:14', '2010-01-31 08:00:14', 4578845300.42, '', 1, false, false, '2010-01-10', 20, false, 9, 6, 4400.950067720), ('2010-01-29 08:00:14', '2010-01-11 08:00:14', NULL, '', 1, true, false, '2010-01-07', 1, true, 13, 8, 6263.032768170), ('2010-01-20 08:00:14', '2010-01-13 08:00:14', NULL, '', 0, true, false, '2010-01-29', 4, true, 9, 2, 615.177587787), ('2010-01-19 08:00:14', NULL, 3076309094.25, '', 1, false, false, '2010-01-14', 8, true, 14, 5, 9162.715913154);
```
2. query
```sql
SELECT DISTINCT * FROM (SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE NULL UNION ALL SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE (NOT (NULL)) UNION ALL SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE ((NULL) IS NULL)) t;

```

### Expected behavior (Required)
NO ERROR

### Real behavior (Required)
```
--java.lang.AssertionError: SELECT DISTINCT * FROM (SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE NULL UNION ALL SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE (NOT (NULL)) UNION ALL SELECT DISTINCT NULL FROM  t1 AS t1_88 FULL JOIN (SELECT t0_87.c_0_0, t0_87.c_0_1, t0_87.c_0_2, t0_87.c_0_3, t0_87.c_0_4 FROM t0 AS t0_87) subt0 ON t1_88.c_1_5 = subt0.c_0_2 AND CASE  WHEN false THEN t1_88.c_1_5  WHEN true THEN t1_88.c_1_5 ELSE t1_88.c_1_5 END < subt0.c_0_2 WHERE ((NULL) IS NULL)) t;
--	at sqlancer.common.query.QueryAdapter.checkException(QueryAdapter.java:98)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:128)
--	at sqlancer.ComparatorHelper.getResultSetFirstColumnAsString(ComparatorHelper.java:54)
--	at sqlancer.ComparatorHelper.getCombinedResultSetNoDuplicates(ComparatorHelper.java:164)
--	at sqlancer.starrocks.oracle.tlp.StarRocksTLPDistinctOracle.check(StarRocksTLPDistinctOracle.java:43)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:55)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:326)
--	at sqlancer.Main$2.run(Main.java:521)
--	at sqlancer.Main$2.runThread(Main.java:498)
--	at sqlancer.Main$2.run(Main.java:488)
--	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
--	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
--	at java.lang.Thread.run(Thread.java:748)
--Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: NULL_TYPE is illegal in thrift stage
--	at sun.reflect.GeneratedConstructorAccessor5.newInstance(Unknown Source)
--	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
--	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
--	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
--	at com.mysql.jdbc.Util.getInstance(Util.java:408)
--	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
--	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
--	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
--	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2497)
--	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2455)
--	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1369)
--	at sqlancer.common.query.QueryAdapter.executeAndGet(QueryAdapter.java:118)
--	... 11 more
---- Time: 2023/04/18 17:42:35
-- Database: d7
-- Database version: 5.1.0
-- seed value: 1681800583237
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main (05b45b531b)

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #21972

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|3|3|100.00%|[]|

**Review by Seaven — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java [hunk 1]
```diff
@@ -1602,8 +1602,8 @@ private AggregateExprInfo buildAggregateTuple(
                 intermediateSlotDesc.setType(intermediateType);
                 intermediateSlotDesc.setIsNullable(aggrFn.isNullable());
                 intermediateSlotDesc.setIsMaterialized(true);
-                SlotRef intermediateSlotRef = new SlotRef(aggregation.getKey().toString(), intermediateSlotDesc);
-                intermediateAggrExprs.add(intermediateSlotRef);
+                intermediateAggrExprs.add(ScalarOperatorToExpr.buildExecExpression(aggregation.getKey(),
+                        new ScalarOperatorToExpr.FormatterContext(context.getColRefToExpr())));
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:1606]: Is the above lines about `intermediateSlotDesc` is unnecessary? 
 line 1605 
```
ScalarOperatorToExpr.buildExecExpression(aggregation.getKey(),
new ScalarOperatorToExpr.FormatterContext(context.getColRefToExpr()))
```
 seems just retrun the SlotRef created in line 1595 
```
context.getColRefToExpr().put(aggregation.getKey(), new SlotRef(aggregation.getKey().toString(), slotDesc));
```
. Is it OK?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:1606]: yes, it will return the SlotRef added in 1595, but it will go through the hack process inside the ScalarOperatorToExpr

Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:1606]: 「Is the above lines about intermediateSlotDesc is unnecessary?
line 1605」
Seems unnecessary, I'll remove it and see what happens.

Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:1606]: What happens if `intermediateType` is not equal with `aggregation.getValue().getType()`?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|5|5|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:1598]: intermediateType has been removed now.

**Review by kangkaisen — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java]: It's query cache related logic, I'll revert the change.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|3|3|100.00%|[]|

**Review by packy92 — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3
