### PR TITLE
[BugFix] Use sort key to process predicates to get scan range while sort key is assigned.

### LINKED ISSUE #14441: Should not use primary key to process WHERE predicates like before, it will get wrong result.
in old usage, in some case segment iterator use primary key as the filter when `WHERE` predicate be used, just scan a smaller range to speed up, it related to some range algorithm.
if sort key assigned, 
1. should not use primary key as like before, it will result in wrong range to scan.
2. should use sort key to process these predicates

### StarRocks version (Required)
main

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/14441

## Problem Summary(Required) ：

Under previous cases,  segment iterator use primary key as the filter when `WHERE` predicate be used, just scan a smaller range to speed up, it related to some range algorithm.
If sort key assigned, we should use sort key instead of primary key to process the predicates.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 14 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|8|14|57.14%|[637, 638, 639, 640, 641, 657]|

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
@mergify rebase

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 8 / 14 (57.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|8|14|57.14%|[653, 654, 655, 656, 657, 673]|

File: be/src/connector/lake_connector.cpp [hunk 1]
```diff
@@ -185,7 +185,7 @@ Status LakeDataSource::open(RuntimeState* state) {
     cm.conjunct_ctxs_ptr = &_conjunct_ctxs;
     cm.tuple_desc = tuple_desc;
     cm.obj_pool = &_obj_pool;
-    cm.key_column_names = &thrift_lake_scan_node.key_column_name;
+    cm.key_column_names = &thrift_lake_scan_node.sort_key_column_names;
```
Comment (chaoyli) [inline be/src/connector/lake_connector.cpp:188]: How about the performance improvement?

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
