### PR TITLE
Bugfix: copy the last row in array column replace aggregator

### LINKED ISSUE #4705: BE crashes when doing replace aggregation on array column
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `t2` (
  `c_1_0` date NOT NULL COMMENT "",
  `c_1_1` date NULL COMMENT "",
  `c_1_2` ARRAY<varchar(65533)> NOT NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`c_1_0`, `c_1_1`)
DISTRIBUTED BY HASH(`c_1_0`) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);
2. insert into t2 values ("2000-01-19", "2000-01-07", ["", "pZI1", "HI", "Y", "v", "K", "k", "Ev7w9", "W", "YE", "XT", "xttzhi1", "3ci4J", "dq"]);
insert into t2 values ("2000-01-19", "2000-01-18", ["a", "fI", "K2", "g", "Cv7a0", "a7iuR", "", "Z", "911"]), ("2000-01-19", "2000-01-10", ["T5ykNYmvN", "8n", "lGO", "", "", "", "CQSlQ6az", "", "", "", "Z", "", "", "9cJAl0cK", "2"]); 
insert into t2 values ("2000-01-18", "2000-01-05", ["3", "A3ewNppkL", "HuZ", "", "ZjQ", "Bwlc44EL", ""]);
insert into t2 values ("2000-01-27", "2000-01-07", ["gbLs", "v3J2B7", "l", "kWng", "y", "9", "", "buYQ", "U", "hp", "F2ojHqEBC", "he8", ""]), ("2000-01-13", "2000-01-04", ["VMQPqSmuq", "", "mvLu3", "c8Jd", "C", "QTs", "S", "B", "", "B"]); 
3. SELECT * from t2 
or compaction

### Expected behavior (Required)
query or compaction success

### Real behavior (Required)
be crash
```
*** Check failure stack trace: ***
    @          0xa23c50d  google::LogMessage::Fail()
    @          0xa23e7e9  google::LogMessage::SendToLog()
    @          0xa23c089  google::LogMessage::Flush()
    @          0xa23ede9  google::LogMessageFatal::~LogMessageFatal()
    @          0x460826d  starrocks::vectorized::BinaryColumnBase<>::check_or_die()
    @          0x6347048  starrocks::vectorized::NullableColumn::check_or_die()
    @          0x63027e3  starrocks::vectorized::ArrayColumn::check_or_die()
    @          0x6323cb8  starrocks::vectorized::Chunk::check_or_die()
    @          0x4889583  starrocks::vectorized::ChunkIterator::get_next()
    @          0x4bdc64a  starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x4889570  starrocks::vectorized::ChunkIterator::get_next()
    @          0x4bd2a21  starrocks::vectorized::TabletReader::do_get_next()
    @          0x4889570  starrocks::vectorized::ChunkIterator::get_next()
    @          0x76be68c  starrocks::vectorized::TabletScanner::get_chunk()
    @          0x687f383  starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x6885ee0  _ZZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS0_13TabletScannerEbENKUlvE_clEv
    @          0x688b7a4  _ZSt13__invoke_implIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x688b644  _ZSt10__invoke_rIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @          0x688b4ac  _ZNSt17_Function_handlerIFvvEZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS2_13TabletScannerEbEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x4433f7c  std::function<>::operator()()
    @          0x554ce10  starrocks::PriorityThreadPool::work_thread()
    @          0x5576031  std::__invoke_impl<>()
    @          0x5575e71  std::__invoke<>()
    @          0x5575e1b  _ZNKSt12_Mem_fn_baseIMN9starrocks18PriorityThreadPoolEFviELb1EEclIJRPS1_RiEEEDTcl8__invokedtdefpT6_M_pmfspcl7forwardIT_Efp_EEEDpOS9_
    @          0x5575dcc  std::__invoke_impl<>()
    @          0x5575d23  _ZSt10__invoke_rIvRSt7_Mem_fnIMN9starrocks18PriorityThreadPoolEFviEEJRPS2_RiEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESB_E4typeEOSC_DpOSD_
    @          0x5574afc  _ZNSt12_Bind_resultIvFSt7_Mem_fnIMN9starrocks18PriorityThreadPoolEFviEEPS2_iEE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x5571c26  std::_Bind_result<>::operator()<>()
    @          0x557063a  boost::detail::thread_data<>::run()
    @          0xa1ea4f7  thread_proxy
    @     0x7f9c8fecdea5  start_thread
    @     0x7f9c8e993b0d  __clone
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 
2.2 and main

### PR DESCRIPTION
**Pull request by wyb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4705

## Problem Summary(Required) ：

Currently, the column in replace aggregator ArrayState is the same as the column in aggregate iterator.
When processing the next chunk in aggregate iterator, the previous column will be overwritten or reset 
and its memory may be wrong.

So copy it when processing the last row in array column replace aggregator.

### CODE REVIEW

**Review by sduzh — APPROVED** [review]

File: be/src/storage/vectorized/column_aggregate_func.cpp [hunk 1]
```diff
@@ -231,8 +231,15 @@ class ReplaceAggregator<ArrayColumn, ArrayState> final : public ValueColumnAggre
     void reset() override { this->data().reset(); }
 
     void aggregate_impl(int row, const ColumnPtr& src) override {
-        this->data().column = src;
-        this->data().row = row;
```
Comment (kangkaisen) [inline be/src/storage/vectorized/column_aggregate_func.cpp:235]: Why only array column is special?

Comment (wyb) [reply be/src/storage/vectorized/column_aggregate_func.cpp:235]: Good question. I think it is because the child type of the array column is uncertain, and this can reduce the overhead of memory copy in the replace aggregation.

**Review by chaoyli — APPROVED** [review]
