### PR TITLE
[BugFix] Fix the bug of empty table after recover table (#13797)

### LINKED ISSUE #13797: Table does not exist after recover database
### Steps to reproduce the behavior (Required)
```
create database db1;
use db1;
CREATE TABLE t1 (
    k1 INT,
    k2 INT,
    k3 INT SUM)
AGGREGATE KEY(k1,k2)
DISTRIBUTED BY HASH(k1);
show tables;
drop database db1;
recover database db1;
use db1;
show tables;

```

### Expected behavior (Required)
```
+---------------+
| Tables_in_db1 |
+---------------+
| t1            |
+---------------+
```
### Real behavior (Required)
`Empty set (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 0057ace |
+----------------------+
```

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：
Fixes #13797
Problem:
This Problem was introduced by commit #12868. This commit use Collections.unmodifiableSet instead of HashSet to reduce the memory usage of FE. But the problem here is that Collections.unmodifiableSet just returns the view of nameToTable.keySet(). Before using the TableNames in recycle database, nameToTable had been dropped, and also the view of it would become empty, which caused this problem.

Solution:
We copy the nameToTable.keySet() only when dropping the database.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

- [x] I have checked the version labels which the pr will be auto backported to target branch

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|6|50.00%|[482, 483, 2815]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|3|3|100.00%|[]|

**Review by decster — DISMISSED** [review]

**Review by waittttting — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by decster — DISMISSED** [review]

**Review by waittttting — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by srlch** [comment]
run #39455

**Comment by srlch** [comment]
run 39455

**Comment by srlch** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 9 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|6|50.00%|[482, 483, 2815]|
|:large_blue_circle:|com/starrocks/catalog/Database.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java [hunk 1]
```diff
@@ -423,8 +423,8 @@ public void dropDb(String dbName, boolean isForceDrop) throws DdlException, Meta
                 }
 
                 // save table names for recycling
-                Set<String> tableNames = db.getTableNamesWithLock();
-                runnableList = unprotectDropDb(db, isForceDrop, false);
+                Set<String> tableNames = new HashSet<String>();
+                runnableList = unprotectDropDb(db, isForceDrop, false, tableNames);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java:427]: You can copy the name to a new set here, instead of add a param in unprotectDropDb.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java:427]: Besides, better to change the getTableNamesWithLock to a name that reminds the caller that this is just a view of the tablet map.

Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java]: ok,i have fixed it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|2|00.00%|[260, 716]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|1|2|50.00%|[482]|

**Review by gengjun-git — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
