### PR TITLE
[BugFix] fix persistent index compatibility issue when migrate between different cpu arch

### LINKED ISSUE #57952: Crash of starrocks BE on ARM
### Steps to reproduce the behavior (Required)
Waiting about 10 minutes, no query required to reproduce the crash

### Expected behavior (Required)
It does not crash

### Real behavior (Required)
It crashes

### StarRocks version (Required)
3.3.9, 3.4.1

### Description of the bug

Tested on both versions 3.3.9 and 3.4.1, in a setup with a single FE and single BE, nothing shared mode, about 160GB of database data, zstd compressed.

This setup is running on x86 architecture with no particular issue. Now, moving to an ARM machine, I observe the BE is regularly crashing with this stack trace :

```
W20250406 17:07:33.542100 281456209117312 stack_util.cpp:347] 2025-04-06 17:07:33.227865, query_id=00000000-0000-0000-0000-000000000000, fragment_instance_id=00000000-0000-0000-
0000-000000000000 throws exception: std::bad_alloc, trace:
     @          0x6549740  __wrap___cxa_throw
    @          0xd7d7298  operator new(unsigned long)
    @          0x6d5ae2c  starrocks::FixedMutableIndex<20ul>::load_snapshot(phmap::BinaryInputArchive&)
    @          0x6d17698  starrocks::ShardByLengthMutableIndex::load_snapshot(phmap::BinaryInputArchive&, std::set<unsigned int, std::less<unsigned int>, std::allocator<unsigned
 int> > const&)
    @          0x6d2f948  starrocks::ShardByLengthMutableIndex::load(starrocks::MutableIndexMetaPB const&)
    @          0x6d3a4c4  starrocks::PersistentIndex::_load(starrocks::PersistentIndexMetaPB const&, bool)
    @          0x6d3b06c  starrocks::PersistentIndex::load(starrocks::PersistentIndexMetaPB const&)
    @          0x6d42acc  starrocks::PersistentIndex::_load_by_loader(starrocks::TabletLoader*)
    @          0x6d441f0  starrocks::PersistentIndex::load_from_tablet(starrocks::Tablet*)
    @          0x6867f2c  starrocks::PrimaryIndex::_do_load(starrocks::Tablet*)
    @          0x6868bd8  starrocks::PrimaryIndex::load(starrocks::Tablet*)
    @          0x69373a8  starrocks::UpdateManager::on_rowset_finished(starrocks::Tablet*, starrocks::Rowset*)
    @          0x71ca5b8  starrocks::DeltaWriter::commit()
    @          0x8136388  starrocks::AsyncDeltaWriter::_execute(void*, bthread::TaskIterator<starrocks::AsyncDeltaWriter::Task>&)
    @          0x989e6ac  bthread::ExecutionQueueBase::_execute(bthread::TaskNode*, bool, int*)
    @          0x989f638  bthread::ExecutionQueueBase::_execute_tasks(void*)
    @          0x83236a4  starrocks::ThreadPool::dispatch_thread()
    @          0x831b69c  starrocks::Thread::supervise_thread(void*)
    @     0xffff9455d5c8  (/usr/lib/aarch64-linux-gnu/libc.so.6+0x7d5c7)
    @     0xffff945c5edc  (/usr/lib/aarch64-linux-gnu/libc.so.6+0xe5edb)
```
Before it crashes, I can access all the data, and there is no visible corruption. But after 10 minutes about it crashes like this.

One thing to note, the data volume of the BE was copied from the X86 machine to the ARM machine as is. Are the data architecture specific ? Maybe I should rebuild from scratch the data instead ?

### PR DESCRIPTION
**Pull request by luohaha**
## Why I'm doing:
In the current implementation, the FixedMutableIndex of the persistent index uses two different data structures depending on whether the CPU supports SSE instructions (https://github.com/StarRocks/starrocks/blob/0d19cb4f9bc58d0cab5237a469b9e4bd30c0eb31/be/src/util/phmap/phmap.h#L447). 
Since ARM architecture CPUs do not support SSE instructions, when migrating from x86 to ARM, the differing implementations cause the loaded FixedMutableIndex to become corrupted.

## What I'm doing:
1. For the subsequent generation of snapshots in the persistent index, all snapshots will be converted to the new format to support cross-CPU architectures.
2. For snapshots generated by older versions of StarRocks, a completeness_check will be performed to verify whether the snapshot file is complete and compatible with the current CPU architecture. If it passes the check, the old format will be used for loading.
3. If the completeness_check fails, it indicates that the file is either corrupted or was generated on a different CPU architecture. In this case, compatibility loading will be skipped, and the snapshot will be rebuilt.

Fix #57952

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: be/src/storage/persistent_index.cpp [hunk 1]
```diff
@@ -60,6 +60,12 @@ constexpr size_t kPackSize = 16;
 constexpr size_t kBucketSizeMax = 256;
 constexpr size_t kFixedMaxKeySize = 128;
 constexpr size_t kBatchBloomFilterReadSize = 4ULL << 20;
+/*
+The introduction of this magic number serves two purposes:
+1. To detect endianness mismatches in cross-platform scenarios
+2. To identify the new snapshot encoding format
+*/
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:67]:
```suggestion
// The introduction of this magic number serves two purposes:
// 1. To detect endianness mismatches in cross-platform scenarios
// 2. To identify the new snapshot encoding format
```
Prefer comment starts with`//`

File: be/test/storage/persistent_index_snapshot_load_test.cpp [hunk 2]
```diff
@@ -0,0 +1,135 @@
...
+        vector<IndexValue> values;
+        vector<size_t> idxes;
+        key_slices.reserve(N);
+        idxes.reserve(N);
+        for (int i = 0; i < N; i++) {
+            if constexpr (std::is_same_v<Key, uint32_t>) {
+                ASSERT_TRUE(GetParam().fixed_key_size)
+                        << "KeyType is uint32_t, but GetParam().fixed_key_size is false.";
+                keys[i] = i;
+                values.emplace_back(i * 2); // 假设 IndexValue 可以这样构造
```
Comment (alvin-celerdata) [inline be/test/storage/persistent_index_snapshot_load_test.cpp:64]: please use English

**Review by dengliu — APPROVED** [review]

File: be/src/storage/persistent_index.cpp [hunk 3]
```diff
@@ -1006,7 +1027,26 @@ class FixedMutableIndex : public MutableIndex {
     // will use `sizeof(size_t)` as return value.
     size_t dump_bound() override { return _map.empty() ? sizeof(size_t) : _map.dump_bound(); }
 
-    bool dump(phmap::BinaryOutputArchive& ar) override { return _map.dump(ar); }
+    bool dump(phmap::BinaryOutputArchive& ar) override {
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:1030]: As far as I know, this dump should be compatible with phmap dump behavior in X86 platform.
You should add comments in the codebase to let others know why you implemented similar logic in this function, rather than just calling _map.dump() directly.

Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:1030]: Can you change the function return type from bool to Status, which can have more meaningful information.

File: be/src/storage/persistent_index.cpp [hunk 4]
```diff
@@ -1964,6 +2004,13 @@ Status ShardByLengthMutableIndex::append_wal(const Slice* keys, const IndexValue
 }
 
 Status ShardByLengthMutableIndex::load_snapshot(phmap::BinaryInputArchive& ar, const std::set<uint32_t>& idxes) {
+    uint32_t magic_num = 0;
+    RETURN_IF(!ar.load(&magic_num), Status::Corruption("ShardByLengthMutableIndex load snapshot magic num failed"));
+    if (magic_num != kSnapshotMagicNum) {
+        return Status::Corruption(
+                fmt::format("ShardByLengthMutableIndex load snapshot magic num failed, expect {}, but got {}",
+                            kSnapshotMagicNum, magic_num));
+    }
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:2013]: Will this new check cause all persistent index corruption? Because the previously generated snapshot has no magic number.

File: be/src/storage/persistent_index.cpp [hunk 5]
```diff
@@ -1978,6 +2025,9 @@ size_t ShardByLengthMutableIndex::dump_bound() {
 }
 
 bool ShardByLengthMutableIndex::dump(phmap::BinaryOutputArchive& ar_out, std::set<uint32_t>& dumped_shard_idxes) {
+    if (!ar_out.dump(kSnapshotMagicNum)) {
+        return false;
+    }
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:2030]: prefer Status return type

File: be/test/storage/persistent_index_snapshot_load_test.cpp (hunk 2 above)
Comment (luohaha) [reply be/test/storage/persistent_index_snapshot_load_test.cpp:64]: Ok, this is generared by AI...

File: be/src/storage/persistent_index.cpp (hunk 4 above)
Comment (luohaha) [reply be/src/storage/persistent_index.cpp:2013]: Persistent index will be rebuilt

**Review by alvin-phoenix-ai — CHANGES_REQUESTED** [review]
sorry, I leave a request changes because of behavior changes.

File: be/src/storage/persistent_index.cpp (hunk 3 above)
Comment (luohaha) [reply be/src/storage/persistent_index.cpp]: done

File: be/src/util/phmap/phmap.h [hunk 6]
```diff
@@ -1541,6 +1541,9 @@ class raw_hash_set {
 
     template <typename InputArchive>
     bool load(InputArchive&);
+
+    template <typename InputArchive>
+    bool completeness_check(InputArchive& ar);
```
Comment (alvin-celerdata) [inline be/src/util/phmap/phmap.h:1546]:
```suggestion
    Status completeness_check(const InputArchive& ar);
```

File: be/src/util/phmap/phmap_dump.h [hunk 7]
```diff
@@ -143,6 +143,39 @@ bool raw_hash_set<Policy, Hash, Eq, Alloc>::load(InputArchive& ar) {
...
+template <class Policy, class Hash, class Eq, class Alloc>
+template <typename InputArchive>
+bool raw_hash_set<Policy, Hash, Eq, Alloc>::completeness_check(InputArchive& ar) {
+    static_assert(type_traits_internal::IsTriviallyCopyable<value_type>::value,
+                  "value_type should be trivially copyable");
+    raw_hash_set<Policy, Hash, Eq, Alloc>().swap(*this); // clear any existing content
+    size_t size = 0;
+    if (!ar.load(&size)) {
+        std::cerr << "Failed to load size" << std::endl;
+        return false;
```
Comment (alvin-celerdata) [inline be/src/util/phmap/phmap_dump.h:155]: 1. std::cerr/std::cout is not allowed in our codebase. Only LOG is allowed.
2. It is not a good design choice to print logs in a basic structure class. Image that std::vector will print log, it will make it difficult to handle it.
2. Considering returning Status with detail information.

File: be/src/storage/persistent_index.h [hunk 8]
```diff
@@ -281,6 +281,10 @@ class MutableIndex {
 
     virtual Status pk_dump(PrimaryKeyDump* dump, PrimaryIndexDumpPB* dump_pb) = 0;
 
+    virtual void set_format_version(uint32_t ver) = 0;
+
+    virtual Status completeness_check(phmap::BinaryInputArchive& ar) = 0;
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.h:286]:
```suggestion
    virtual Status completeness_check(const phmap::BinaryInputArchive& ar) = 0;
```
use `const` as much as possible

File: be/src/storage/persistent_index.cpp [hunk 9]
```diff
@@ -1977,17 +2098,22 @@ size_t ShardByLengthMutableIndex::dump_bound() {
                            [](size_t s, const auto& e) { return e->size() > 0 ? s + e->dump_bound() : s; });
 }
 
-bool ShardByLengthMutableIndex::dump(phmap::BinaryOutputArchive& ar_out, std::set<uint32_t>& dumped_shard_idxes) {
+Status ShardByLengthMutableIndex::dump(phmap::BinaryOutputArchive& ar_out, std::set<uint32_t>& dumped_shard_idxes) {
+    bool use_old_format = false;
+    TEST_SYNC_POINT_CALLBACK("ShardByLengthMutableIndex::dump::1", &use_old_format);
+    if (LIKELY(!use_old_format)) {
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:2104]: Please add more comments here to explain the reason why you do it this way.

Comment (alvin-celerdata) [reply be/src/storage/persistent_index.cpp:2104]: What will happen if a new version snapshot is generated? However, the image is rolled back due to other reasons. Will it cause the old version image to crash forever?

File: be/src/storage/persistent_index.cpp [hunk 10]
```diff
@@ -1058,8 +1120,11 @@ class FixedMutableIndex : public MutableIndex {
 
     size_t memory_usage() override { return _map.capacity() * (1 + (KeySize + 3) / 4 * 4 + kIndexValueSize); }
 
+    void set_format_version(uint32_t ver) override { format_version = ver; }
+
 private:
     phmap::flat_hash_map<KeyType, IndexValue, FixedKeyHash<KeySize>> _map;
+    uint32_t format_version = kMutableIndexFormatVersion2;
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:1127]: Should follow the naming rules.
```suggestion
    uint32_t _format_version = kMutableIndexFormatVersion2;
```

**Review by chaoyli — DISMISSED** [review]

File: be/src/storage/persistent_index.h (hunk 8 above)
Comment (luohaha) [reply be/src/storage/persistent_index.h:286]: It can't be const, there is `ifstream` in `BinaryInputArchive`, and `completeness_check` will lead to state change in `ifstream`.

File: be/src/util/phmap/phmap.h (hunk 6 above)
Comment (luohaha) [reply be/src/util/phmap/phmap.h]: done

File: be/src/storage/persistent_index.cpp (hunk 9 above)
Comment (luohaha) [reply be/src/storage/persistent_index.cpp:2107]: If BE rollback, then old BE can't recognize new format snapshot. So I increase the persistent index format version to `PERSISTENT_INDEX_VERSION_7`, so when rollback happen, it will be rebuilt.

File: be/src/storage/persistent_index.h [hunk 11]
```diff
@@ -74,7 +74,8 @@ enum PersistentIndexFileVersion {
     PERSISTENT_INDEX_VERSION_3,
     PERSISTENT_INDEX_VERSION_4,
     PERSISTENT_INDEX_VERSION_5,
-    PERSISTENT_INDEX_VERSION_6
+    PERSISTENT_INDEX_VERSION_6,
+    PERSISTENT_INDEX_VERSION_7
```
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/storage/persistent_index.h:78]: his is a legacy issue, and we will refactor it in subsequent PRs.

File: be/src/storage/persistent_index.cpp [hunk 12]
```diff
@@ -1060,8 +1120,11 @@ class FixedMutableIndex : public MutableIndex {
 
     size_t memory_usage() override { return _map.capacity() * (1 + (KeySize + 3) / 4 * 4 + kIndexValueSize); }
 
+    void set_format_version(uint32_t ver) override { _format_version = ver; }
+
 private:
     phmap::flat_hash_map<KeyType, IndexValue, FixedKeyHash<KeySize>> _map;
+    uint32_t _format_version = kMutableIndexFormatVersion2;
```
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/storage/persistent_index.cpp:1127]: There is not format version in `MutableIndex`, previous version is in `ImmutableIndex`

File: be/src/storage/persistent_index.h [hunk 13]
```diff
@@ -281,6 +282,10 @@ class MutableIndex {
 
     virtual Status pk_dump(PrimaryKeyDump* dump, PrimaryIndexDumpPB* dump_pb) = 0;
 
+    virtual void set_format_version(uint32_t ver) = 0;
```
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/storage/persistent_index.h:285]: The new ​​PERSISTENT_INDEX_VERSION_xx​​ and the old ​​kMutableIndexFormatVersion1​​ may coexist because:

1. Each time the ​​persistent index​​ is updated, we record the latest ​​PERSISTENT_INDEX_VERSION_xx​​ in RocksDB's metadata.
2. However, not every write triggers a ​​dump​​, so the snapshot file may still be in the old format.
3. Therefore, an additional ​​format version​​ identifier is needed to distinguish between versions.

File: be/src/storage/persistent_index.cpp [hunk 14]
```diff
@@ -1348,34 +1411,50 @@ class SliceMutableIndex : public MutableIndex {
     //  |total num|| data size ||  data    | ... | data size ||  data    |
     size_t dump_bound() override { return sizeof(size_t) * (1 + size()) + _total_kv_pairs_usage; }
 
-    bool dump(phmap::BinaryOutputArchive& ar) override {
+    Status dump(phmap::BinaryOutputArchive& ar) override {
```
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/storage/persistent_index.cpp:1414]: This is a legacy issue too, they were introduced from day one. We can submit a refactor PR later.

File: be/src/storage/persistent_index.h (hunk 13 above)
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/storage/persistent_index.h]: changed. done.

File: be/src/util/phmap/phmap_dump.h [hunk 15]
```diff
@@ -143,6 +143,35 @@ bool raw_hash_set<Policy, Hash, Eq, Alloc>::load(InputArchive& ar) {
...
+template <class Policy, class Hash, class Eq, class Alloc>
+template <typename InputArchive>
+starrocks::Status raw_hash_set<Policy, Hash, Eq, Alloc>::completeness_check(InputArchive& ar) {
+    static_assert(type_traits_internal::IsTriviallyCopyable<value_type>::value,
+                  "value_type should be trivially copyable");
+    raw_hash_set<Policy, Hash, Eq, Alloc>().swap(*this); // clear any existing content
+    size_t size = 0;
+    if (!ar.load(&size)) {
+        return starrocks::Status::InternalError("Failed to load size");
+    }
```
[the remark this answers is not in the document]
Comment (luohaha) [reply be/src/util/phmap/phmap_dump.h]: done

**Review by decster — DISMISSED** [review]

File: be/src/exprs/agg/distinct.h [hunk 16]
```diff
@@ -72,18 +72,18 @@ struct DistinctAggregateState<LT, SumLT, FixedLengthLTGuard<LT>> {
 
     void serialize(uint8_t* dst) const {
         phmap::InMemoryOutput output(reinterpret_cast<char*>(dst));
-        set.dump(output);
+        (void)set.dump(output);
```
Comment (alvin-celerdata) [inline be/src/exprs/agg/distinct.h:75]:
``` suggestion
        [[maybe_unused]] set.dump(output);
```

Comment (alvin-celerdata) [reply be/src/exprs/agg/distinct.h:75]: It will make compilation fail in CentOS. https://github.com/StarRocks/starrocks/pull/58419

File: be/src/exprs/agg/distinct.h [hunk 17]
```diff
@@ -72,18 +72,18 @@ struct DistinctAggregateState<LT, SumLT, FixedLengthLTGuard<LT>> {
...
         DCHECK(output.length() == set.dump_bound());
     }
 
     void deserialize_and_merge(const uint8_t* src, size_t len) {
         phmap::InMemoryInput input(reinterpret_cast<const char*>(src));
         auto old_size = set.size();
         if (old_size == 0) {
-            set.load(input);
+            (void)set.load(input);
```
Comment (alvin-celerdata) [inline be/src/exprs/agg/distinct.h:83]: ditto

File: be/src/exprs/agg/distinct.h [hunk 18]
```diff
@@ -72,18 +72,18 @@ struct DistinctAggregateState<LT, SumLT, FixedLengthLTGuard<LT>> {
...
         } else {
             MyHashSet set_src;
-            set_src.load(input);
+            (void)set_src.load(input);
```
Comment (alvin-celerdata) [inline be/src/exprs/agg/distinct.h:86]: ditto

File: be/src/storage/persistent_index.cpp [hunk 19]
```diff
@@ -1965,7 +2040,45 @@ Status ShardByLengthMutableIndex::append_wal(const Slice* keys, const IndexValue
...
+    auto check_arch_fn = [&]() {
+        ar.reset();
+        for (const auto idx : idxes) {
+            if (!_shards[idx]->completeness_check(ar).ok()) {
+                return false;
+            }
+        }
+        // Must reach the end of the file.
+        return ar.eof();
+    };
```
Comment (alvin-celerdata) [inline be/src/storage/persistent_index.cpp:2056]: Better to use Status as the return type to pass along the error message

**Review by alvin-phoenix-ai — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-3.3
