### PR TITLE
[BugFix] Fix FE host redundant bug when restart FE node in k8s cluster

### LINKED ISSUE #18834: [BUG] FE host redundant when restart FE node in k8s cluster
### Steps to reproduce the behavior (Required)
1. Build a k8s cluster with 3 FE node.
2. delete a pod continuously.

### Expected behavior (Required)
The FE node should be recovered successfully.

### Real behavior (Required)
The FE node restart failed, and another FE node with the same host is added to cluster.
```
mysql> show frontends\G
*************************** 1. row ***************************
             Name: test-fe-0.test-fe-search.gengjun.svc.cluster.local_9010_1677487245671
               IP: test-fe-0.test-fe-search.gengjun.svc.cluster.local
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: FOLLOWER
        ClusterId: 1732864776
             Join: false
            Alive: false
ReplayedJournalId: 30550
    LastHeartbeat: 2023-02-28 13:18:48
         IsHelper: true
           ErrMsg: got exception
        StartTime: NULL
          Version: UNKNOWN-1e222c2
*************************** 2. row ***************************
             Name: test-fe-2.test-fe-search.gengjun.svc.cluster.local_9010_1677487405443
               IP: test-fe-2.test-fe-search.gengjun.svc.cluster.local
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: FOLLOWER
        ClusterId: 1732864776
             Join: true
            Alive: true
ReplayedJournalId: 80609
    LastHeartbeat: 2023-03-02 11:49:02
         IsHelper: true
           ErrMsg:
        StartTime: 2023-02-28 13:18:47
          Version: UNKNOWN-1e222c2
*************************** 3. row ***************************
             Name: test-fe-1.test-fe-search.gengjun.svc.cluster.local_9010_1677487358479
               IP: test-fe-1.test-fe-search.gengjun.svc.cluster.local
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 9030
          RpcPort: 9020
             Role: LEADER
        ClusterId: 1732864776
             Join: true
            Alive: true
ReplayedJournalId: 80610
    LastHeartbeat: 2023-03-02 11:49:02
         IsHelper: true
           ErrMsg:
        StartTime: 2023-02-28 13:18:14
          Version: UNKNOWN-1e222c2
*************************** 4. row ***************************
             Name: test-fe-0.test-fe-search.gengjun.svc.cluster.local_9010_1677590336633
               IP: test-fe-0.test-fe-search.gengjun.svc.cluster.local
      EditLogPort: 9010
         HttpPort: 8030
        QueryPort: 0
          RpcPort: 0
             Role: FOLLOWER
        ClusterId: 1732864776
             Join: false
            Alive: false
ReplayedJournalId: 0
    LastHeartbeat: NULL
         IsHelper: true
           ErrMsg: got exception
        StartTime: NULL
          Version: NULL
4 rows in set (0.01 sec)
```

### StarRocks version (Required)
 - After 2.4

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18834
If a pod in k8s is deleted, a new pod with the same FQDN will be added to the cluster and the manager will call `Alter system add Follower/Observer ...` to StarRocks(The manager cannot judge whether the node is restarted or newly added, so it call this command every time. But for the restart, this command will fail because the node is already in the cluster). But the function getFeByHost() will return null when the specified FQDN cannot be resolved to ip, in this case, the FE with the same FQDN will be added to cluster.
To fix this bug, I write a new function to judge whether the specified FQDN is already in the cluster, if the FQDN cannot be resolved, an exception will be thrown.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java [hunk 1]
```diff
@@ -741,9 +741,13 @@ public void addFrontend(FrontendNodeType role, String host, int editLogPort) thr
...
         }
         try {
-            Frontend fe = getFeByHost(host);
-            if (null != fe) {
-                throw new DdlException("frontend use host [" + host + "] already exists ");
+            try {
+                if (checkFeExistByIpOrFqdn(host)) {
+                    throw new DdlException("FE with the same host: " + host + " already exists");
+                }
+            } catch (UnknownHostException e) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java:748]: If throwing the exception, how to add the new POD?

File: fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java [hunk 2]
```diff
@@ -931,6 +935,34 @@ public Frontend unprotectCheckFeExist(String host, int port) {
...
+    protected boolean checkFeExistByIpOrFqdn(String ipOrFqdn) throws UnknownHostException {
+        Pair<String, String> targetIpAndFqdn = NetUtils.getIpAndFqdnByHost(ipOrFqdn);
+
+        for (Frontend fe : frontends.values()) {
+            Pair<String, String> curIpAndFqdn;
+            try {
+                curIpAndFqdn = NetUtils.getIpAndFqdnByHost(fe.getHost());
+            } catch (UnknownHostException e) {
+                LOG.warn("failed to get right ip by fqdn {}", fe.getHost(), e);
+                if (targetIpAndFqdn.second.equals(fe.getHost())) {
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java:947]: why don't check `!Strings.isNullOrEmpty(targetIpAndFqdn.second)` here?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java]: If the code reaches here, it means the targetIpAndFqdn.second cannot be null, but for code robust, add this check will be better. 
done

File: fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/server/NodeMgr.java:748]: Adding POD is not effected by the `Add Follower/Observer ` command, it is controlled by k8s manager. The exception must be thrown if the specified host already in the cluster.

**Review by nshangyiming — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 15 / 25 (60.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/NodeMgr.java|13|23|56.52%|[748, 749, 750, 945, 946, 947, 948, 949, 951, 960]|
|:large_blue_circle:|com/starrocks/common/util/NetUtils.java|2|2|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
