### PR TITLE
[BugFix] In a concurrency scenario, after a tablet is deleted, its corresponding data directory still exists.

### LINKED ISSUE #50383: After tablet is deleted, its corresponding data directory still exists
### Steps to reproduce the behavior (Required)
```
BE log: I0826 11:32:01.586261 892877 storage_engine.cpp:994] start to sweep trash(first sweep)
BE log: I0826 11:32:18.161396 268541 agent_task.cpp:358] local tablet migration succeeded. status: OK, signature: 47036351 (put tabletId through_add_ shutdown_tablet_unlocked to _shutdown_tablets)
FE log: 2024-08-26 11:35:07.393+08:00 INFO (ReportHandler|190) [ReportHandler.addDropReplicaTask():964] delete tablet[47036351] from backend[ 10007] because not found in meta
BE log: I0826 11:35:07.392313 273802 agent_task.cpp:155] Remove task success. type=DROP, signature=47036351, task_count_in_queue=20 (put tabletId to _shutdown_tablets via _add_shutdown_tablet_unlocked, overwriting the previous record)
BE log: I0826 11:35:07.761147 892877 storage_engine.cpp:994] start to sweep trash (second sweep)
```
https://forum.mirrorship.cn/t/topic/14447

### Expected behavior (Required)
The data directory should be deleted
### Real behavior (Required)
The data directory should not be deleted

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhangheihei**
## What I'm doing:

Fixes #50383

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by meegoo — DISMISSED** [review]

File: be/src/storage/tablet_manager.cpp [hunk 1]
```diff
@@ -1028,83 +1091,53 @@ Status TabletManager::start_trash_sweep() {
     }
 
     std::vector<DroppedTabletInfo> tablets_to_check;
+    std::vector<DroppedTabletInfo> tablets_redundant_to_check;
```
Comment (wyb) [inline be/src/storage/tablet_manager.cpp:1094]: use `map`？

Comment (zhangheihei) [reply be/src/storage/tablet_manager.cpp:1094]: I has been optimized here

Comment (zhangheihei) [reply be/src/storage/tablet_manager.cpp:1094]: hi @wyb @meegoo @sevev 
please reveiw the code

**Review by sevev — APPROVED** [review]

**Review by wyb — APPROVED** [review]
