### PR TITLE
[Enhancement] Return the error message of the publish version task to the FE

### LINKED ISSUE #34768: In shared data mode, return the error message of the publish version task to the FE
## Problem
In shared data mode, when the publish version task fails, BE will only return the list of failed Tablet ids, but will not return the error reason for the task failure to FE, returning the error information to FE can make the problem troubleshooting more convenient.

## Solution
Add a [status](https://github.com/StarRocks/starrocks/blob/309f3dccae87b554015e70bd2f9262e0f8c95140/gensrc/proto/status.proto#L23) field in the [response](https://github.com/StarRocks/starrocks/blob/309f3dccae87b554015e70bd2f9262e0f8c95140/gensrc/proto/lake_service.proto#L38) to return error message to FE.

### PR DESCRIPTION
**Pull request by silly-carbon**
return the error message of the publish version task to the FE

Fixes #34768

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/service/service_be/lake_service.cpp [hunk 1]
```diff
@@ -182,12 +182,14 @@ void LakeServiceImpl::publish_version(::google::protobuf::RpcController* control
                 auto score = compaction_score(metadata);
                 std::lock_guard l(response_mtx);
                 response->mutable_compaction_scores()->insert({tablet_id, score});
+                Status::OK().to_protobuf(response->mutable_status());
```
Comment (sduzh) [inline be/src/service/service_be/lake_service.cpp:185]: Initialize the response status to ok before entering the for loop. This prevents later success from overwriting and dropping the error status, since currently any error will be overridden by a subsequent success assignment.

File: be/src/service/service_be/lake_service.cpp [hunk 2]
```diff
@@ -200,6 +202,7 @@ void LakeServiceImpl::publish_version(::google::protobuf::RpcController* control
                          << " txn_id=" << request->txn_ids()[0];
             std::lock_guard l(response_mtx);
             response->add_failed_tablets(tablet_id);
+            st.status().to_protobuf(response->mutable_status());
```
Comment (sduzh) [inline be/src/service/service_be/lake_service.cpp:205]:
```suggestion
            st.to_protobuf(response->mutable_status());
```

Comment (silly-carbon) [reply be/src/service/service_be/lake_service.cpp]: Thanks, sorry for the mistake, my local docker just also encountered this error, I've fixed.

**Review by sduzh — APPROVED** [review]

**Comment by sduzh** [comment]
LGTM, @wyb PTAL

**Review by wyb — APPROVED** [review]

**Comment by sduzh** [comment]
@silly-carbon Thanks for your contribution!

**Comment by silly-carbon** [comment]
> @silly-carbon Thanks for your contribution!

You are welcome. Thanks for you guys' great work on reviewing this.
