### PR TITLE
[Enhancement] bump up breakpad to 2024.02.16 to fix crash in dump_syms

### LINKED ISSUE #60004: [BUG] gen_minidump_symbols.sh crash in dump_syms
$ bash thirdparty/minidump/gen_minidump_symbols.sh
thirdparty/minidump/gen_minidump_symbols.sh: line 13: 27305 Aborted                 (core dumped) $(dirname $curdir)/installed/bin/dump_syms $starrocks_home/output/be/lib/starrocks_be > $starrocks_home/output/be/starrocks_be.sym

Starting program: /opensource/deploystarrocks/be/lib/temp/dump_syms starrocks_be
BFD: /lib64/ld-linux-x86-64.so.2: unknown type [0x13] section `.relr.dyn'
warning: `/lib64/ld-linux-x86-64.so.2': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
warning: `/lib64/ld-linux-x86-64.so.2': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
BFD: /lib/x86_64-linux-gnu/libc.so.6: unknown type [0x13] section `.relr.dyn'
warning: `/lib/x86_64-linux-gnu/libc.so.6': Shared library architecture unknown is not compatible with target architecture i386:x86-64.
BFD: /lib/x86_64-linux-gnu/libm.so.6: unknown type [0x13] section `.relr.dyn'
warning: `/lib/x86_64-linux-gnu/libm.so.6': Shared library architecture unknown is not compatible with target architecture i386:x86-64.

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff784527e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff78288ff in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff782881b in __assert_fail_base (fmt=<optimized out>, assertion=<optimized out>, file=<optimized out>, line=<optimized out>, function=<optimized out>) at ./assert/assert.c:96
#6  0x00007ffff783b517 in __assert_fail (assertion=0x5555555a40a2 "size == 4 || size == 8", file=0x5555555a3ee8 "src/common/dwarf/bytereader.cc", line=58, 
    function=0x5555555a3f08 "void google_breakpad::ByteReader::SetAddressSize(uint8_t)") at ./assert/assert.c:105
#7  0x000055555557b3a7 in google_breakpad::ByteReader::SetAddressSize (this=<optimized out>, size=<optimized out>) at src/common/dwarf/bytereader.cc:58

#8  0x000055555557ebdc in google_breakpad::CompilationUnit::ReadAddressSize (this=<optimized out>, headerptr=<optimized out>) at src/common/dwarf/dwarf2reader.cc:306
#9  0x000055555557ee6b in google_breakpad::CompilationUnit::ReadHeader (this=this@entry=0x7fffffffd2a0) at src/common/dwarf/dwarf2reader.cc:354
#10 0x00005555555897c6 in google_breakpad::CompilationUnit::Start (this=this@entry=0x7fffffffd2a0) at src/common/dwarf/dwarf2reader.cc:402
#11 0x000055555559b52d in (anonymous namespace)::LoadDwarf<google_breakpad::ElfClass64> (module=0x5555555c7530, handle_inline=<optimized out>, handle_inter_cu_refs=<optimized out>, big_endian=false, elf_header=0x7fff70e00000, 
    dwarf_filename=...) at src/common/linux/dump_symbols.cc:347
#12 (anonymous namespace)::LoadSymbols<google_breakpad::ElfClass64> (obj_file=..., big_endian=<optimized out>, elf_header=0x7fff70e00000, read_gnu_debug_link=<optimized out>, info=0x7fffffffd5e0, options=..., module=0x5555555c7530)
    at src/common/linux/dump_symbols.cc:789
#13 0x000055555559c5ad in (anonymous namespace)::ReadSymbolDataElfClass<google_breakpad::ElfClass64> (out_module=0x7fffffffd740, options=..., debug_dirs=..., obj_os=..., obj_filename=..., elf_header=0x7fff70e00000)
    at /usr/include/c++/11/bits/stl_iterator.h:1027
#14 google_breakpad::ReadSymbolDataInternal (obj_file=0x7fff70e00000 "\177ELF\002\001\001", obj_filename=..., obj_os=..., debug_dirs=..., options=..., module=0x7fffffffd740) at src/common/linux/dump_symbols.cc:1066
#15 0x000055555559d2e9 in google_breakpad::ReadSymbolData (load_path=..., obj_file=..., obj_os=..., debug_dirs=..., options=..., module=0x7fffffffd740) at src/common/linux/dump_symbols.cc:1144
#16 0x000055555559d33d in google_breakpad::WriteSymbolFile (load_path=..., obj_file=..., obj_os=..., debug_dirs=..., options=..., sym_stream=...) at src/common/linux/dump_symbols.cc:1081
#17 0x000055555555f10d in main (argc=<optimized out>, argv=<optimized out>) at src/tools/linux/dump_syms/dump_syms.cc:137
(gdb)

### Expected behavior (Required)
gen_minidump_symbols.sh should generate symbols file

### Real behavior (Required)
gen_minidump_symbols.sh fails to generate symbols file

### StarRocks version (Required)
 - main-745097

### PR DESCRIPTION
**Pull request by rohitrs1983**
we are using and older version of dump_syms that doesn’t understand the .relr.dyn section

Fixes #60004 

update breakpad to version breakpad-2024.02.16

$ bash thirdparty/minidump/gen_minidump_symbols.sh
starrocks_be'size (2153mb) reduced to (556mb)
symbol file is at /home/ubuntu/starrocks/output/be/symbols/starrocks_be/AC7FAB7F8B5BF82100000000000000000

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

File: thirdparty/build-thirdparty.sh [hunk 1]
```diff
@@ -915,6 +915,7 @@ build_breakpad() {
     cd $TP_SOURCE_DIR/$BREAK_PAD_SOURCE
     mkdir -p src/third_party/lss
     cp $TP_PATCH_DIR/linux_syscall_support.h src/third_party/lss
+    LDFLAGS="-L${TP_INSTALL_DIR}/lib -L${TP_INSTALL_DIR}/lib64" \
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh]: will `-L${TP_LIB_DIR}` sufficient for the link ?

**Review by kevincai — COMMENTED** [review]
breakpad build failed on centos7 environment.

```
2025-06-17T17:50:39.4705575Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::IsCompressedHeader(const typename ElfClass::Shdr*)’:
2025-06-17T17:50:39.4706359Z #9 2755.4 src/common/linux/dump_symbols.cc:298:31: error: ‘SHF_COMPRESSED’ was not declared in this scope
2025-06-17T17:50:39.4706818Z #9 2755.4   298 |   return (section->sh_flags & SHF_COMPRESSED) != 0;
2025-06-17T17:50:39.4707140Z #9 2755.4       |                               ^~~~~~~~~~~~~~
2025-06-17T17:50:39.4707942Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘std::pair<unsigned char*, long unsigned int> {anonymous}::UncompressSectionContents(uint64_t, const uint8_t*, uint64_t, uint64_t)’:
2025-06-17T17:50:39.4708913Z #9 2755.4 src/common/linux/dump_symbols.cc:363:27: error: ‘ELFCOMPRESS_ZLIB’ was not declared in this scope; did you mean ‘ELFCOMPRESS_ZSTD’?
2025-06-17T17:50:39.4709569Z #9 2755.4   363 |   if (compression_type == ELFCOMPRESS_ZLIB) {
2025-06-17T17:50:39.4709871Z #9 2755.4       |                           ^~~~~~~~~~~~~~~~
2025-06-17T17:50:39.4710155Z #9 2755.4       |                           ELFCOMPRESS_ZSTD
2025-06-17T17:50:39.4710936Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::DwarfCFIRegisterNames(const typename ElfClass::Ehdr*, std::vector<std::__cxx11::basic_string<char> >*)’:
2025-06-17T17:50:39.4711909Z #9 2755.4 src/common/linux/dump_symbols.cc:549:10: error: ‘EM_RISCV’ was not declared in this scope
2025-06-17T17:50:39.4712295Z #9 2755.4   549 |     case EM_RISCV:
2025-06-17T17:50:39.4712516Z #9 2755.4       |          ^~~~~~~~
2025-06-17T17:50:39.4713097Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘const char* {anonymous}::ElfArchitecture(const typename ElfClass::Ehdr*)’:
2025-06-17T17:50:39.4713787Z #9 2755.4 src/common/linux/dump_symbols.cc:1125:10: error: ‘EM_RISCV’ was not declared in this scope
2025-06-17T17:50:39.4714215Z #9 2755.4  1125 |     case EM_RISCV:      return "riscv";
2025-06-17T17:50:39.4714473Z #9 2755.4       |          ^~~~~~~~
```

**Comment by rohitrs1983** [comment]
> breakpad build failed on centos7 environment.
> 
> ```
> 2025-06-17T17:50:39.4705575Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::IsCompressedHeader(const typename ElfClass::Shdr*)’:
> 2025-06-17T17:50:39.4706359Z #9 2755.4 src/common/linux/dump_symbols.cc:298:31: error: ‘SHF_COMPRESSED’ was not declared in this scope
> 2025-06-17T17:50:39.4706818Z #9 2755.4   298 |   return (section->sh_flags & SHF_COMPRESSED) != 0;
> 2025-06-17T17:50:39.4707140Z #9 2755.4       |                               ^~~~~~~~~~~~~~
> 2025-06-17T17:50:39.4707942Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘std::pair<unsigned char*, long unsigned int> {anonymous}::UncompressSectionContents(uint64_t, const uint8_t*, uint64_t, uint64_t)’:
> 2025-06-17T17:50:39.4708913Z #9 2755.4 src/common/linux/dump_symbols.cc:363:27: error: ‘ELFCOMPRESS_ZLIB’ was not declared in this scope; did you mean ‘ELFCOMPRESS_ZSTD’?
> 2025-06-17T17:50:39.4709569Z #9 2755.4   363 |   if (compression_type == ELFCOMPRESS_ZLIB) {
> 2025-06-17T17:50:39.4709871Z #9 2755.4       |                           ^~~~~~~~~~~~~~~~
> 2025-06-17T17:50:39.4710155Z #9 2755.4       |                           ELFCOMPRESS_ZSTD
> 2025-06-17T17:50:39.4710936Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::DwarfCFIRegisterNames(const typename ElfClass::Ehdr*, std::vector<std::__cxx11::basic_string<char> >*)’:
> 2025-06-17T17:50:39.4711909Z #9 2755.4 src/common/linux/dump_symbols.cc:549:10: error: ‘EM_RISCV’ was not declared in this scope
> 2025-06-17T17:50:39.4712295Z #9 2755.4   549 |     case EM_RISCV:
> 2025-06-17T17:50:39.4712516Z #9 2755.4       |          ^~~~~~~~
> 2025-06-17T17:50:39.4713097Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘const char* {anonymous}::ElfArchitecture(const typename ElfClass::Ehdr*)’:
> 2025-06-17T17:50:39.4713787Z #9 2755.4 src/common/linux/dump_symbols.cc:1125:10: error: ‘EM_RISCV’ was not declared in this scope
> 2025-06-17T17:50:39.4714215Z #9 2755.4  1125 |     case EM_RISCV:      return "riscv";
> 2025-06-17T17:50:39.4714473Z #9 2755.4       |          ^~~~~~~~
> ```

@kevincai these macros are present in /usr/include/elf.h. unavailable on centos7 since its pretty old. dont observe the same failure on ubuntu. how about a patch file to add these macros to dump_symbols.cc?

**Comment by kevincai** [comment]
> > breakpad build failed on centos7 environment.
> > ```
> > 2025-06-17T17:50:39.4705575Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::IsCompressedHeader(const typename ElfClass::Shdr*)’:
> > 2025-06-17T17:50:39.4706359Z #9 2755.4 src/common/linux/dump_symbols.cc:298:31: error: ‘SHF_COMPRESSED’ was not declared in this scope
> > 2025-06-17T17:50:39.4706818Z #9 2755.4   298 |   return (section->sh_flags & SHF_COMPRESSED) != 0;
> > 2025-06-17T17:50:39.4707140Z #9 2755.4       |                               ^~~~~~~~~~~~~~
> > 2025-06-17T17:50:39.4707942Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘std::pair<unsigned char*, long unsigned int> {anonymous}::UncompressSectionContents(uint64_t, const uint8_t*, uint64_t, uint64_t)’:
> > 2025-06-17T17:50:39.4708913Z #9 2755.4 src/common/linux/dump_symbols.cc:363:27: error: ‘ELFCOMPRESS_ZLIB’ was not declared in this scope; did you mean ‘ELFCOMPRESS_ZSTD’?
> > 2025-06-17T17:50:39.4709569Z #9 2755.4   363 |   if (compression_type == ELFCOMPRESS_ZLIB) {
> > 2025-06-17T17:50:39.4709871Z #9 2755.4       |                           ^~~~~~~~~~~~~~~~
> > 2025-06-17T17:50:39.4710155Z #9 2755.4       |                           ELFCOMPRESS_ZSTD
> > 2025-06-17T17:50:39.4710936Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘bool {anonymous}::DwarfCFIRegisterNames(const typename ElfClass::Ehdr*, std::vector<std::__cxx11::basic_string<char> >*)’:
> > 2025-06-17T17:50:39.4711909Z #9 2755.4 src/common/linux/dump_symbols.cc:549:10: error: ‘EM_RISCV’ was not declared in this scope
> > 2025-06-17T17:50:39.4712295Z #9 2755.4   549 |     case EM_RISCV:
> > 2025-06-17T17:50:39.4712516Z #9 2755.4       |          ^~~~~~~~
> > 2025-06-17T17:50:39.4713097Z #9 2755.4 src/common/linux/dump_symbols.cc: In function ‘const char* {anonymous}::ElfArchitecture(const typename ElfClass::Ehdr*)’:
> > 2025-06-17T17:50:39.4713787Z #9 2755.4 src/common/linux/dump_symbols.cc:1125:10: error: ‘EM_RISCV’ was not declared in this scope
> > 2025-06-17T17:50:39.4714215Z #9 2755.4  1125 |     case EM_RISCV:      return "riscv";
> > 2025-06-17T17:50:39.4714473Z #9 2755.4       |          ^~~~~~~~
> > ```
> 
> @kevincai these macros are present in /usr/include/elf.h. unavailable on centos7 since its pretty old. dont observe the same failure on ubuntu. how about a patch file to add these macros to dump_symbols.cc?

Yes, it's acceptable.

File: thirdparty/build-thirdparty.sh (hunk 1 above)
Comment (rohitrs1983) [reply thirdparty/build-thirdparty.sh]: @kevincai thanks for the review. updated.

**Comment by kevincai** [comment]
@mergifyio rebase

**Review by kevincai — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
