### PR TITLE
Array function type set to null when polymorphic type can't determine

### LINKED ISSUE #4829: array_length(null) executed error
### Steps to reproduce the behavior (Required)
1. 
```
select array_length(null);
```
### Expected behavior (Required)
NULL
### Real behavior (Required)
```
ERROR 1064 (HY000): No matching function with signature: array_length(unknown type: NULL_TYPE).
```
### StarRocks version (Required)
```
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER 35e3df8 |
+------------------------+
```

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4829

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java [hunk 1]
```diff
@@ -881,8 +881,8 @@ private Function checkPolymorphicFunction(Function fn, Type[] paramTypes) {
         } else if (typeElement != null) {
             typeArray = new ArrayType(typeElement);
         } else {
-            LOG.warn("could not determine polymorphic type because has unknown types");
-            return null;
+            typeElement = Type.NULL;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java:884]: here must be null type?

**Review by murphyatwork — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java (hunk 1 above)
Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java:884]: In fact, it is also possible to use Boolean instead of Null, and even other data types can be used

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FunctionSet.java|2|2|100.00%|

**Review by sduzh — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
