### PR TITLE
[BugFix] Support shuffle broker load for non duplicate keys table

### LINKED ISSUE #8707: Broker Load to non duplicate key table make replica inconsistent
### Steps to reproduce the behavior (Required)
1. CREATE TABLE hits_signed_uk (
 CounterID int(11) NULL ,
 EventDate date NULL ,
 UserID bigint(20) NULL ,
 WatchID bigint(20) NULL ,
 JavaEnable tinyint(4) NULL ,
 Title varchar(65533) NULL ,
 GoodEvent smallint(6) NULL ,
 EventTime datetime NULL ,
 ClientIP int(11) NULL
) ENGINE=OLAP
UNIQUE KEY(CounterID, EventDate, UserID)
DISTRIBUTED BY HASH(UserID) BUCKETS 10
PROPERTIES (
'replication_num' = '3'
)

2. LOAD LABEL test
(
    DATA INFILE('hdfs://x.x.x.x:9002/*')
    INTO TABLE hits_signed_uk
)
WITH BROKER 'broker1'
PROPERTIES
(
    'timeout' = '3600'
)
4. SELECT count(*) from hits_signed_uk;

### Expected behavior (Required)
replica consistent

### Real behavior (Required)
replica inconsistent

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8707 

## Problem Summary(Required) ：

Before we unify the ingestion interface, we solved the multi-replica inconsistency problem of non duplicate key table by adding shuffle service.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 53 (92.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|48|52|92.31%|[279, 280, 281, 289]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 53 (92.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|48|52|92.31%|[279, 280, 281, 289]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java [hunk 1]
```diff
@@ -200,6 +215,87 @@ public void plan(TUniqueId loadId, List<List<TBrokerFileStatus>> fileStatusesLis
...
+            throws UserException {
+        // Generate plan trees
+        // 1. Broker scan node
+        FileScanNode scanNode = new FileScanNode(new PlanNodeId(nextNodeId++), tupleDesc, "FileScanNode",
+                fileStatusesList, filesAdded);
+        scanNode.setLoadInfo(loadJobId, txnId, table, brokerDesc, fileGroups, strictMode, parallelInstanceNum);
+        scanNode.setUseVectorizedLoad(true);
+        scanNode.init(analyzer);
+        scanNode.finalizeStats(analyzer);
+        LOG.info("use vectorized load: {}, load job id: {}", true, loadJobId);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java:228]: Nonvectorized load is not supported already. You can remove the log.

File: fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java [hunk 2]
```diff
@@ -200,6 +215,87 @@ public void plan(TUniqueId loadId, List<List<TBrokerFileStatus>> fileStatusesLis
...
+            } catch (NotImplementedException e) {
+                LOG.info("Fragment finalize failed.{}", e.getMessage());
+                throw new UserException("Fragment finalize failed.");
+            }
+        }
+        Collections.reverse(fragments);
+    }
+
+    public Boolean needShufflePlan() {
+        if (KeysType.DUP_KEYS.equals(table.getKeysType())) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java:288]: If the tablet is aggregate table not have no REPLACE table, it also can use non-shuffle plan.

File: fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java [hunk 3]
```diff
@@ -200,6 +215,87 @@ public void plan(TUniqueId loadId, List<List<TBrokerFileStatus>> fileStatusesLis
...
+            return false;
+        }
+
+        if (table.getDefaultReplicationNum() <= 1) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java:292]: If the input file is one, we can use non-shuffle plan.

Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java:292]: seems not, since file can be split.

File: fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java (hunk 2 above)
Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/load/loadv2/LoadingTaskPlanner.java:288]: for easy and compatibility with insert into behavior, No specific distinct before implementing the shuffle service.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 48 / 52 (92.31%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|47|51|92.16%|[277, 278, 279, 287]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Review by chaoyli — DISMISSED** [review]

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Review by chaoyli — DISMISSED** [review]

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 56 / 62 (90.32%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|55|61|90.16%|[279, 280, 281, 289, 305, 306]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Review by chaoyli — DISMISSED** [review]

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 56 / 62 (90.32%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/loadv2/LoadingTaskPlanner.java|55|61|90.16%|[278, 279, 280, 288, 304, 305]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by chaoyli** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]
