### PR TITLE
[BugFix] Fix multi nest cte inline error

### LINKED ISSUE #9347: [sqlancer] query unknow error
### Steps to reproduce the behavior (Required)

```
DROP DATABASE IF EXISTS v0;
CREATE DATABASE v0;
USE v0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 BOOLEAN NULL ,c_0_2 DATETIME NULL ,c_0_3 SMALLINT NOT NULL ,c_0_4 DECIMAL(14, 7)  NOT NULL ,c_0_5 VARCHAR(11) NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 143 day)) DISTRIBUTED BY HASH (c_0_0,c_0_3,c_0_4,c_0_2) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NOT NULL,c_1_1 INT NOT NULL,c_1_2 DATE NOT NULL,c_1_3 BOOLEAN NOT NULL,c_1_4 TINYINT NOT NULL,c_1_5 BOOLEAN NOT NULL,c_1_6 VARCHAR(1) NOT NULL,c_1_7 DATE NOT NULL,c_1_8 LARGEINT NOT NULL,c_1_9 DATETIME NOT NULL,c_1_10 VARCHAR(11) NOT NULL,c_1_11 BOOLEAN NOT NULL,c_1_12 VARCHAR(21) NOT NULL, INDEX index1_c_1_0(`c_1_0`) USING BITMAP) PRIMARY KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 791 day)) DISTRIBUTED BY HASH (c_1_11,c_1_4,c_1_2,c_1_1,c_1_10,c_1_7,c_1_8) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_1, c_1_12") ;
DELETE FROM t0 WHERE c_0_2='1969-12-24 14:57:25' AND c_0_0='1969-12-08 12:04:07' AND c_0_1=true AND c_0_4 IS NOT NULL;
INSERT INTO t0 VALUES ('1969-12-17 10:58:05', false, '1969-12-24 23:09:27', 2, 0.2383073, '');
INSERT INTO t1 VALUES ('1969-12-21', 5, '1969-12-08', true, 0, true, '', '1970-01-02', -1285314842, '1970-01-02 08:33:39', '5PKbfln', true, '3'), ('1970-01-07', 3, '1969-12-21', false, 2, false, '', '1969-12-24', -732636552, '1969-12-29 19:59:26', 'd7Xw', false, '');
INSERT INTO t1 VALUES ('1970-01-08', 0, '1969-12-28', false, 5, false, '', '1970-01-15', -436269773, '1970-01-04 23:29:29', '', true, '');
INSERT INTO t1 VALUES ('1969-12-11', 5, '1970-01-08', true, 2, true, '', '1969-12-24', -229895015, '1970-01-16 08:50:38', 'yQqFfhUp', false, ''), ('1969-12-28', 3, '1970-01-04', true, 7, true, '', '1969-12-08', 617783883, '1969-12-29 16:08:24', 'zL', false, 's84');
INSERT INTO t1 VALUES ('1970-01-19', 1, '1970-01-09', false, 0, false, '', '1970-01-02', -926794156, '1969-12-17 16:51:06', 'T', false, '5m');
INSERT INTO t0 VALUES ('1970-01-19 19:58:31', true, '1969-12-17 08:10:10', 11, 0.7998302, NULL), ('1970-01-03 18:59:38', NULL, '1970-01-12 12:25:15', 10, 0.8054165, 'E');
INSERT INTO t1 VALUES ('292278994-08-17', 11, '1969-12-21', true, 5, false, '', '1970-01-17', 1190925678, '1970-01-08 15:16:17', 'jm', false, ''), ('1970-01-04', 25, '1970-01-09', false, 1, false, '', '1970-01-12', -1285314842, '1969-12-18 20:21:49', '', false, 'oL'), ('1969-12-15', 20, '1969-12-15', true, 3, false, '', '1970-01-08', 2910151, '1970-01-09 06:12:32', '90', true, '');
INSERT INTO t1 VALUES ('1969-12-27', 13, '1969-12-28', false, 5, true, '', '1969-12-18', 1423560660, '1969-12-19 11:47:06', '5W', false, 'AJ');
INSERT INTO t1 VALUES ('1970-01-07', 8, '1969-12-20', false, 7, false, '', '1970-01-04', -1037593810, '1969-12-07 23:31:05', 'v', true, 'yv9lf'), ('1969-12-19', 1, '1969-12-26', false, 4, false, '', '1970-01-14', -469931387, '1970-01-03 18:59:38', 'QFsT', true, 'VGfZk');
INSERT INTO t1 VALUES ('1970-01-08', 26, '1970-01-12', false, 4, false, '', '1969-12-22', 684752060, '1970-01-04 16:29:19', 'gMhI', false, '8v'), ('292269055-12-03', 2, '1970-01-24', true, 5, true, '', '1969-12-22', -1773861962, '1970-01-22 16:23:21', 'FBDEdc', true, '');
INSERT INTO t1 VALUES ('1969-12-11', 24, '1970-01-01', true, 1, true, '', '1970-01-10', 1457721027, '1969-12-24 11:05:12', 'lBmp6', true, 'l9');
INSERT INTO t0 VALUES (NULL, false, '1969-12-25 00:29:10', 5, 0.5751429, 'd'), ('1969-12-29 01:58:43', NULL, '1970-01-20 01:11:16', 10, 0.7069974, '');
INSERT INTO t1 VALUES ('1970-01-04', 8, '1969-12-22', false, 2, true, '', '1969-12-25', -316319418, '1970-01-03 04:22:31', 'fzA2GuB4', true, 'Fy'), ('1969-12-08', 15, '292269055-12-03', true, 0, true, '', '1970-01-12', -523153161, '1970-01-09 01:36:12', '5z', true, '');
INSERT INTO t1 VALUES ('1969-12-25', 9, '1969-12-28', true, 2, true, '', '1969-12-24', -1037593810, '1970-01-14 00:57:36', 'RrZbyKL', true, '03YGE'), ('1970-01-15', 27, '1970-01-10', false, 5, false, '', '1969-12-22', 504676693, '1969-12-17 05:28:11', 'ca', true, 'IAkK');
INSERT INTO t1 VALUES ('1969-12-27', 22, '1969-12-24', false, 3, true, '', '1969-12-29', 826627119, '1969-12-26 06:40:46', '', false, '2'), ('1970-01-14', 5, '1970-01-14', true, 6, true, '', '1970-01-23', -1295389093, '1970-01-12 02:58:00', '', true, '');
INSERT INTO t1 VALUES ('1970-01-20', 22, '1970-01-13', false, 2, false, '', '1969-12-08', -2084701994, '1970-01-08 11:36:23', 'YW', true, 'ggNtez'), ('1970-01-12', 18, '1970-01-12', false, 0, false, '', '1969-12-26', -1681366307, '1969-12-30 01:10:04', 'DeH6f', false, 'tM');
INSERT INTO t1 VALUES ('1969-12-27', 5, '1969-12-16', true, 6, true, '', '1970-01-09', 1269171380, '1970-01-19 14:12:25', '', true, ''), ('1970-01-07', 9, '1969-12-10', false, 3, false, '', '1970-01-25', -153158128, '1970-01-18 23:58:49', 'E1dUG', false, 'izU');
INSERT INTO t0 VALUES ('1970-01-25 18:43:13', true, '1969-12-25 14:40:52', 15, 0.2698900, ''), ('1970-01-03 08:30:41', true, '1970-01-04 12:15:21', 2, 0.8386012, 'KrPF');
TRUNCATE TABLE t1;
INSERT INTO t0 VALUES (NULL, true, '1969-12-12 00:57:01', 12, 0.2965062, 'f'), ('1970-01-18 23:58:49', true, '1969-12-22 14:17:49', 14, 0.6560177, '');
INSERT INTO t0 VALUES ('1969-12-30 17:19:38', false, '1969-12-20 06:22:53', 3, 0.4520553, ''), ('1969-12-25 04:23:43', true, '1970-01-04 20:00:30', 9, 0.1195689, 'Ev8');
INSERT INTO t0 VALUES ('1970-01-01 05:49:17', true, '1970-01-10 06:54:29', 6, 0.2195245, 'ee');
INSERT INTO t0 VALUES ('1969-12-18 20:31:53', false, '1969-12-22 18:37:56', 13, 0.2277670, NULL);
INSERT INTO t0 VALUES ('1970-01-19 20:27:40', false, NULL, 4, 0.2034775, 'jS'), ('1970-01-15 07:33:58', true, '1969-12-19 07:33:40', 1, 0.1214450, 'e'), ('1969-12-15 22:56:00', false, '1970-01-10 21:37:07', 7, 0.2710174, '');
INSERT INTO t0 VALUES ('1969-12-08 04:54:58', NULL, '1970-01-07 04:11:16', 11, 0.1261592, 'M7aGV8q');
INSERT INTO t0 VALUES ('1969-12-07 16:32:16', true, '1969-12-26 06:40:46', 2, 0.4559378, 'J1'), ('1969-12-25 14:40:52', true, '1970-01-21 15:22:47', 6, 0.5538548, 'V');
INSERT INTO t1 VALUES ('1970-01-01', 0, '1969-12-20', false, 1, false, '', '1970-01-20', -1208173428, '1970-01-09 11:20:37', 'R', true, ''), ('1969-12-29', 19, '1969-12-26', false, 4, false, '', '1970-01-08', 2016452798, '1970-01-19 23:28:32', 'Ld', false, 'DK0cZm'), ('1969-12-26', 10, '1970-01-09', false, 6, false, '', '1970-01-09', -957808962, '1970-01-04 20:00:30', 'ER', true, 'v');
INSERT INTO t1 VALUES ('1970-01-16', 15, '1969-12-18', true, 7, false, '', '1970-01-11', -1415039321, '1970-01-15 17:19:54', 'WN0', true, '');
INSERT INTO t0 VALUES ('1969-12-26 05:31:46', true, '1969-12-24 23:09:27', 15, 0.0065721, 'k9'), ('1969-12-28 16:08:00', NULL, '1969-12-08 13:54:09', 1, 0.2825800, 'xt'), ('1970-01-16 00:32:51', true, '1969-12-09 09:37:33', 8, 0.0634198, '');
INSERT INTO t1 VALUES ('1969-12-08', 28, '1970-01-12', false, 3, true, '', '1970-01-19', -278449266, '1970-01-18 00:39:33', 'Voi', false, 'SA4'), ('1969-12-22', 7, '1969-12-26', false, 2, true, '', '1969-12-15', 1977521204, '1970-01-04 23:29:29', 'iBTRnWd', false, ''), ('1969-12-15', 13, '1970-01-15', false, 3, true, '', '1970-01-20', 2114135728, '1970-01-10 21:37:07', 'P', false, 'jFM');
INSERT INTO t0 VALUES ('1969-12-20 09:38:14', false, '1969-12-28 19:43:37', 2, 0.8815150, 'tk');
CREATE VIEW v0 AS SELECT t0_2.c_0_0 FROM  t0 AS t0_2 LEFT SEMI JOIN t1 AS t1_3 ON t0_2.c_0_2 = t1_3.c_1_8 AND t0_2.c_0_2 > t1_3.c_1_8 AND t0_2.c_0_2 < t1_3.c_1_2 AND t0_2.c_0_2 != t1_3.c_1_2 AND t0_2.c_0_4 < t1_3.c_1_10 AND t0_2.c_0_4 > t1_3.c_1_10;
CREATE VIEW v1 AS SELECT t0_2.c_0_0 FROM  t0 AS t0_2 LEFT SEMI JOIN t1 AS t1_3 ON t0_2.c_0_2 = t1_3.c_1_8 AND t0_2.c_0_2 > t1_3.c_1_8 AND t0_2.c_0_2 < t1_3.c_1_2 AND t0_2.c_0_2 != t1_3.c_1_2 AND t0_2.c_0_4 < t1_3.c_1_10 AND t0_2.c_0_4 > t1_3.c_1_10 WHERE (NOT ( ( CASE  WHEN true THEN t0_2.c_0_5  WHEN true THEN NULL ELSE (('')||(((NULL)||('')))) END ) != ( CASE  WHEN true THEN ''  WHEN CASE  WHEN false THEN CAST('1969-12-21 12:50:00' AS BOOLEAN )   WHEN true THEN (NOT (true)) END THEN t0_2.c_0_5  WHEN false THEN t0_2.c_0_5 ELSE (('3')||('')) END ) ));
CREATE VIEW v63 AS WITH with_t_0 as (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE (v0_9.c_0_0) IN ('1969-12-10 20:34:02', '1970-01-08 05:04:17', '1970-01-06 08:45:31') ) SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0;
CREATE VIEW v1 AS WITH with_t_0 as (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE (v0_9.c_0_0) IN ('1969-12-10 20:34:02', '1970-01-08 05:04:17', '1970-01-06 08:45:31') ) SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ;
CREATE VIEW v2 AS WITH with_t_0 as (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE (v0_9.c_0_0) IN ('1969-12-10 20:34:02', '1970-01-08 05:04:17', '1970-01-06 08:45:31') ) SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE (NOT (NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ));
CREATE VIEW v3 AS WITH with_t_0 as (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE (v0_9.c_0_0) IN ('1969-12-10 20:34:02', '1970-01-08 05:04:17', '1970-01-06 08:45:31') ) SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE ((NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ) IS NULL);
CREATE VIEW v4 AS (WITH with_t_0 as (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE (v0_9.c_0_0) IN ('1969-12-10 20:34:02', '1970-01-08 05:04:17', '1970-01-06 08:45:31') ) (SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ) UNION ALL (SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE (NOT (NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ))) UNION ALL (SELECT subt0.c_0_0 FROM  (SELECT t0_7.c_0_0, t0_7.c_0_1, t0_7.c_0_2, t0_7.c_0_3, t0_7.c_0_4, t0_7.c_0_5 FROM t0 AS t0_7 WHERE  ( t0_7.c_0_4 ) = ( t0_7.c_0_4 ) ) subt0  LEFT JOIN t1 AS t1_8 ON subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_1 = t1_8.c_1_5 AND subt0.c_0_3 >= t1_8.c_1_12 AND subt0.c_0_3 <= t1_8.c_1_12 AND subt0.c_0_2 != t1_8.c_1_1 AND subt0.c_0_2 <= ((-714604160)+(NULL)),  (SELECT v0_9.c_0_0 FROM v0 AS v0_9 WHERE ('1969-12-27 16:26:06')  BETWEEN (CAST(v0_9.c_0_0 AS DATE ) ) AND (v0_9.c_0_0) ) subv0 RIGHT ANTI JOIN with_t_0 AS with_t_0 ON subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 = with_t_0.c_0_0 AND subv0.c_0_0 <= with_t_0.c_0_0 AND with_t_0.c_0_0 <= subv0.c_0_0 WHERE ((NULL_OR_EMPTY(CASE  WHEN (t1_8.c_1_8)  BETWEEN (t1_8.c_1_8) AND (t1_8.c_1_8)  THEN 'b'  WHEN (with_t_0.c_0_0)  BETWEEN (with_t_0.c_0_0) AND (with_t_0.c_0_0)  THEN CAST(CASE  WHEN true THEN with_t_0.c_0_0  WHEN true THEN with_t_0.c_0_0  WHEN false THEN with_t_0.c_0_0 ELSE '1970-01-19 20:27:40' END AS STRING )   WHEN  ( ((191785765)%(-134033443)) ) < ( t1_8.c_1_4 )  THEN MD5SUM('b3', '', 'V', '')  ELSE '' END) ) IS NULL)) );
CREATE VIEW v5 AS WITH with_t_0 as (SELECT v4_38.c_0_0 FROM v4 AS v4_38) SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0;
CREATE VIEW v6 AS WITH with_t_0 as (SELECT v4_38.c_0_0 FROM v4 AS v4_38) SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE ((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL) ORDER BY t0_32.c_0_0 DESC;
CREATE VIEW v39 AS WITH with_t_0 as (SELECT v4_38.c_0_0 FROM v4 AS v4_38) SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE (NOT (((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL))) ORDER BY t0_32.c_0_0 DESC;
CREATE VIEW v7 AS WITH with_t_0 as (SELECT v4_38.c_0_0 FROM v4 AS v4_38) SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE ((((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL)) IS NULL) ORDER BY t0_32.c_0_0 DESC;
CREATE VIEW v8 AS (WITH with_t_0 as (SELECT v4_38.c_0_0 FROM v4 AS v4_38) (SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE ((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL) ORDER BY t0_32.c_0_0 DESC) UNION ALL (SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE (NOT (((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL))) ORDER BY t0_32.c_0_0 DESC) UNION ALL (SELECT v2_36.c_0_0 FROM v2 AS v2_36, v4 AS v4_38, t0 AS t0_32, v63 AS v63_39, with_t_0 AS with_t_0 WHERE ((((CAST('1970-01-09 22:47:36' AS DATE ) ) IS NOT NULL)) IS NULL) ORDER BY t0_32.c_0_0 DESC) );
SELECT * FROM v8;
```

```
2022-07-29 10:54:31,715 WARN (starrocks-mysql-nio-pool-54|1652) [StmtExecutor.execute():482] execute Exception, sql SELECT * FROM v8
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.CTEContext.getCTEProduce(CTEContext.java:118) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeCTEConsume(StatisticsCalculator.java:1308) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalCTEConsume(StatisticsCalculator.java:1298) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalCTEConsume(StatisticsCalculator.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalCTEConsumeOperator.accept(LogicalCTEConsumeOperator.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:152) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:179) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:172) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.calculateStatistics(CTEUtils.java:164) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.collectCteProduce(CTEUtils.java:116) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.collectCteProduce(CTEUtils.java:123) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.CTEUtils.collectCteOperators(CTEUtils.java:64) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.logicalRuleRewrite(Optimizer.java:274) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:124) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:338) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:401) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:637) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------------+
| current_version()       |
+-------------------------+
| BRANCH-2.3-ASAN 9742790 |
+-------------------------+

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9347

## Problem Summary(Required) ：

e.g.
```
  with x1 (
      with x2 (select * from t0) select * from x2
  )
  select * from x1;
```
Transform result without inline cte:
```
                            CTEAnchor1
                         /             \
                   CTEProduce1         CTEConsume1
                      /
               CTEAnchor2
                /       \
        CTEProduce2    CTEConsume2
              /
         Scan(t0)
```
But we do inline cte in transform phase now, the expect result is:
```
                            CTEAnchor1
                         /             \
                   CTEProduce1         CTEConsume1
                      /                        \
               CTEAnchor2                    CTEAnchor2-1
                /       \                     /       \
        CTEProduce2    CTEConsume2    CTEProduce2-1    CTEConsume2-1
              /             \               /             \
         Scan(t0)        Scan(t0)      Scan(t0)           Scan(t0)

```
 CTEAnchor2 and CTEAnchor2-1 is from same CTE (with x2), but has different cteID.

But now result is:
```
                            CTEAnchor1
                         /             \
                   CTEProduce1         CTEConsume1
                      /                        \
               CTEAnchor2                    CTEAnchor2
                /       \                     /       \
        CTEProduce2    CTEConsume2    CTEProduce2   CTEConsume2
              /             \               /             \
         Scan(t0)        Scan(t0)      Scan(t0)           Scan(t0)
```

It's will cause find CTEAnchor/Produce error

so we need generate a new cteID when inline child plan

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 59 / 63 (93.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|0|2|00.00%|[25, 26]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|

**Comment by Seaven** [comment]
e.g.2
```
  with x1 (
      with x2 (select * from t0) select * from x2
      union 
      with x3 (select * from t1) select * from x3
  )
  select * from x1;
```

Transform result without inline cte:

```
                                CTEAnchor1
                             /             \
                       CTEProduce1         CTEConsume1
                          /
                        union
                   /             \
        CTEAnchor2                  CTEAnchor3                                   
         /       \                   /       \                                   
 CTEProduce2    CTEConsume2  CTEProduce3    CTEConsume3                                   
       /                           /                                   
  Scan(t0)                    Scan(t1)                                   
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CTERelation.java [hunk 1]
```diff
@@ -7,7 +7,8 @@
 import java.util.List;
 
 public class CTERelation extends Relation {
-    private final int cteId;
+    // @Note: don't join hash method, maybe multi-change
+    private int cteId;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CTERelation.java:11]: I think the cteId should be the unique identifier for the CTERelation, if the  cte id change, we should new a CTERelation.

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java [hunk 2]
```diff
@@ -241,6 +241,9 @@ public void testTPCDS54() throws Exception {
     public void testTPCDS23_1() throws Exception {
         Pair<QueryDumpInfo, String> replayPair =
                 getPlanFragment(getDumpInfoFromFile("query_dump/tpcds23_1"), null, TExplainLevel.NORMAL);
+        System.out.println(replayPair.first.getOriginStmt());
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java:244]: remove

**Review by Youngwb — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CTERelation.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/ast/CTERelation.java:11]: I see, but it's too difficult.

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java (hunk 2 above)
Comment (Seaven) [reply fe/fe-core/src/test/java/com/starrocks/sql/plan/ReplayFromDumpTest.java:244]: OK, I will remove it next pr

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+     *                          /             \
+     *                    CTEProduce1         CTEConsume1
+     *                       /                        \
+     *                CTEAnchor2                    CTEAnchor2-1
+     *                 /       \                     /       \
+     *         CTEProduce2    CTEConsume2    CTEProduce2-1    CTEConsume2-1
+     *               /             \               /             \
+     *          Scan(t0)        Scan(t0)      Scan(t0)           Scan(t0)
+     *
+     *  CTEAnchor2 and CTEAnchor2-1 is from same CTE (with x2), but has different cteID
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java:71]: `is` -> `are`, `has`->`have`?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java [hunk 4]
```diff
@@ -0,0 +1,83 @@
...
+import com.google.common.collect.Maps;
+
+import java.util.HashMap;
+import java.util.Map;
+import java.util.concurrent.atomic.AtomicInteger;
+
+public class CTETransformerContext {
+    private final Map<Integer, ExpressionMapping> cteExpressions;
+
+    // cteMould -> current cte ref
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java:15]: what's the meaning of `cteMould `?

Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/CTETransformerContext.java:15]: For discriminate cteID，means every instance of CTE is copy from this mould, would you give a better name?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Review by kangkaisen — DISMISSED** [review]

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
@Mergeify rebase

**Comment by Seaven** [comment]
@Mergefiy rebase

**Comment by Seaven** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Comment by Seaven** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Seaven** [comment]
run starrocks_fe_unittest
run starrocks_be_build

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_be_build

**Comment by Seaven** [comment]
run starrocks_be_build

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by Seaven** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Comment by Seaven** [comment]
backport branch-2.3

**Comment by Seaven** [comment]
@Mergifyio backport branch-2.4

**Comment by Seaven** [comment]
https://github.com/Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 63 / 66 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEContext.java|1|2|50.00%|[207]|
|:large_blue_circle:|com/starrocks/sql/ast/CTERelation.java|4|5|80.00%|[53]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CTEUtils.java|21|22|95.45%|[153]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SubqueryTransformer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/CTETransformerContext.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/QueryTransformer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/QueryAnalyzer.java|1|1|100.00%|[]|
