### PR TITLE
[Bugfix]cancel fragment_ctx when query is expired

### LINKED ISSUE #5814: Timeout query returns Empty set or Cancelled sometimes
### Steps to reproduce the behavior 
- Dataset: SSB dataset with 100g scale.
```sql
set query_timeout = 2;

select LO_CUSTKEY from lineorder_flat order by LO_CUSTKEY;
```

### Expected behavior 
```
mysql> select LO_CUSTKEY from lineorder_flat order by LO_CUSTKEY;
ERROR 1064 (HY000): Ocurrs time out with specfied time 1995 MILLISECONDS
```

### Real behavior 
Sometimes, it returns `Empty set` or `Cancelled`.
```
mysql> select LO_CUSTKEY from lineorder_flat order by LO_CUSTKEY;
ERROR 1064 (HY000): Cancelled

mysql> select LO_CUSTKEY from lineorder_flat order by LO_CUSTKEY;
Empty set (2.01 sec)

mysql> select LO_CUSTKEY from lineorder_flat order by LO_CUSTKEY;
ERROR 1064 (HY000): Ocurrs time out with specfied time 1995 MILLISECONDS
```

### StarRocks version 
 - You can get the StarRocks version by executing SQL `select current_version()`
 0f8b34cd7

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5814

## Problem Summary(Required) ：

If query is expired, PipelineDriverPoller will cancel operators directly without setting a timeout status and the BufferControlBlock will close with Status::OK(). 
When the fetch_data request arrived and the BufferControlBlock is closed, it will get an empty result.

In addition, if the fetch_data rpc times out, FE may return such an error to user: `ERROR 1064 (HY000): Ocurrs time out with specfied time 1986 MILLISECONDS`. The number in error message may not equal to the query_timeout setting by user, I think this might be misleading, so I change it to a more friendly pattern

### CODE REVIEW

**Comment by silverbullet233** [comment]
@Mergifyio backport branch-2.2

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|1|00.00%|

File: fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java [hunk 1]
```diff
@@ -125,7 +125,7 @@ public RowBatch getNext(Status status) throws TException {
             LOG.warn("fetch result execution exception, finstId={}", finstId, e);
             if (e.getMessage().contains("time out")) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:126]: Why `time out` instead of `timeout` ?

Comment (silverbullet233) [reply fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:126]: > Why `time out` instead of `timeout` ?

this meesage is generated by brpc, like 'Ocurrs time out with specfied time xxx MILLISECONDS'

File: fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java [hunk 2]
```diff
@@ -125,7 +125,7 @@ public RowBatch getNext(Status status) throws TException {
...
                 // if timeout, we set error code to TIMEOUT, and it will not retry querying.
-                status.setStatus(new Status(TStatusCode.TIMEOUT, e.getMessage()));
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:128]: why need change the error message?

**Review by ZiheLiu — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java [hunk 3]
```diff
@@ -125,14 +127,15 @@ public RowBatch getNext(Status status) throws TException {
...
+                status.setStatus(new Status(TStatusCode.TIMEOUT,
+                        String.format("Query exceeded time limit of %d seconds", expireSeconds)));
             } else {
                 status.setRpcStatus(e.getMessage());
                 SimpleScheduler.addToBlacklist(backendId);
             }
         } catch (TimeoutException e) {
             LOG.warn("fetch result timeout, finstId={}", finstId, e);
-            status.setStatus("query timeout");
+            status.setStatus(String.format("Query exceeded time limit of %d seconds", expireSeconds));
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:138]: You could get timeout value by  ConnectContext

Comment (silverbullet233) [reply fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:138]: > You could get timeout value by ConnectContext

But ResultReceiver don't have such a member variable, I think it's not necessary to add ConnectContext to its member variable just for output error message

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|1|4|25.00%|

File: fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java (hunk 3 above)
Comment (kangkaisen) [reply fe/fe-core/src/main/java/com/starrocks/qe/ResultReceiver.java:138]: what I mean you could use ConnectContext.get, not need  a new member variable.

**Review by kangkaisen — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by silverbullet233** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 5 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ResultReceiver.java|0|5|00.00%|
