### PR TITLE
[BugFix] fix an issue that user-defined variables sql unable to handle variable dependencies.

### LINKED ISSUE #47370: [Bug] user-defined variables sql unable to handle variable dependencies
### Steps to reproduce the behavior (Required)
case 1:
image

1 set @latest_obs_end_date_time = 5,@label_5day_5_obs_end_date_time = @latest_obs_end_date_time-1;

2 select @latest_obs_end_date_time, @label_5day_5_obs_end_date_time;

3 select @latest_obs_end_date_time, @label_5day_5_obs_end_date_time;

4 select @latest_obs_end_date_time, @label_5day_5_obs_end_date_time;

case 2:
image

### Expected behavior (Required)
label_5day_5_obs_end_date_time is 4 in first time execute
### Real behavior (Required)
label_5day_5_obs_end_date_time is null
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
### design
described in:
https://docs.google.com/document/d/1GGwjrV07UEW3qQlvt_8pBp1QdCGLASv6E5tEVMjuyIY/edit#heading=h.qctqko6x7wm5

### PR DESCRIPTION
**Pull request by zhangheihei**
## What I'm doing:

Fixes #47370

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java [hunk 1]
```diff
@@ -775,50 +776,65 @@ private void clearQueryScopeHintContext() {
...
+                    for (Map.Entry<String, UserVariable> entry : userVariableHint.getUserVariables().entrySet()) {
+                        if (context.userVariables.containsKey(entry.getKey())) {
+                            throw new SemanticException(PARSER_ERROR_MSG.invalidUserVariableHint(entry.getKey(),
+                                    "the user variable name in the hint must not match any existing variable names"));
                         }
+                        SetStmtAnalyzer.analyzeUserVariable(entry.getValue());
+                        SetStmtAnalyzer.calcuteUserVariable(entry.getValue());
+                        if (entry.getValue().getEvaluatedExpression() == null) {
+                            try {
+                                context.setQueryId(UUIDUtil.genUUID());
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:811]: please keep the latest code in the main
```
final UUID uuid = UUIDUtil.genUUID();
context.setQueryId(uuid);
context.setExecutionId(UUIDUtil.toTUniqueId(uuid));
entry.getValue().deriveUserVariableExpressionResult(context);
```

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java]: tks review

**Review by packy92 — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
