### PR TITLE
[BugFix] Fix unavailable external catalog when calculate object_dependencies base table

### LINKED ISSUE #37722: [BUG] query sys.object_dependencies failed error
### Steps to reproduce the behavior (Required)
1. CREATE catalog xxx which is unavailable
2. `select * from sys.object_dependencies`

### Expected behavior (Required)
We can query normally

### Real behavior (Required)
In my scenario, I originally had an iceberg catalog, but I can’t connect to it now.

```log
java.lang.IllegalArgumentException: java.net.UnknownHostException: cluster
        at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:475) ~[hadoop-common-3.3.6.jar:?]
        at org.apache.hadoop.hdfs.NameNodeProxiesClient.createProxyWithClientProtocol(NameNodeProxiesClient.java:134) ~[hadoop-hdfs-client-3.3.6.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:374) ~[hadoop-hdfs-client-3.3.6.jar:?]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:308) ~[hadoop-hdfs-client-3.3.6.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.initDFSClient(DistributedFileSystem.java:204) ~[hadoop-hdfs-client-3.3.6.jar:?]
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:189) ~[hadoop-hdfs-client-3.3.6.jar:?]
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3746) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:199) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3857) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3805) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.FileSystem.lambda$get$0(FileSystem.java:604) ~[starrocks-hadoop-ext.jar:?]
        at com.starrocks.connector.hadoop.HadoopExt.doAs(HadoopExt.java:61) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:598) ~[starrocks-hadoop-ext.jar:?]
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365) ~[hadoop-common-3.3.6.jar:?]
        at org.apache.iceberg.hadoop.Util.getFs(Util.java:56) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.hadoop.HadoopInputFile.fromLocation(HadoopInputFile.java:56) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.hadoop.HadoopFileIO.newInputFile(HadoopFileIO.java:90) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.io.ResolvingFileIO.newInputFile(ResolvingFileIO.java:61) ~[iceberg-core-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.io.IcebergCachingFileIO.newInputFile(IcebergCachingFileIO.java:133) ~[starrocks-fe.jar:?]
        at org.apache.iceberg.TableMetadataParser.read(TableMetadataParser.java:266) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$0(BaseMetastoreTableOperations.java:189) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.lambda$refreshFromMetadataLocation$1(BaseMetastoreTableOperations.java:208) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:413) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:219) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:203) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:196) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:208) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:185) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refreshFromMetadataLocation(BaseMetastoreTableOperations.java:180) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.hive.HiveTableOperations.doRefresh(HiveTableOperations.java:176) ~[iceberg-hive-metastore-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.refresh(BaseMetastoreTableOperations.java:97) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreTableOperations.current(BaseMetastoreTableOperations.java:80) ~[iceberg-core-1.2.1.jar:?]
        at org.apache.iceberg.BaseMetastoreCatalog.loadTable(BaseMetastoreCatalog.java:47) ~[iceberg-core-1.2.1.jar:?]
        at com.starrocks.connector.iceberg.hive.IcebergHiveCatalog.getTable(IcebergHiveCatalog.java:98) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.CachingIcebergCatalog.getTable(CachingIcebergCatalog.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.iceberg.IcebergMetadata.getTable(IcebergMetadata.java:227) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnectorMetadata.getTable(CatalogConnectorMetadata.java:111) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$3(MetadataMgr.java:290) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:290) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.BaseTableInfo.getTableByName(BaseTableInfo.java:190) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.BaseTableInfo.getTable(BaseTableInfo.java:154) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.system.sys.SysObjectDependencies.listObjectDependencies(SysObjectDependencies.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.service.FrontendServiceImpl.listObjectDependencies(FrontendServiceImpl.java:642) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Processor$listObjectDependencies.getResult(FrontendService.java:4701) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Processor$listObjectDependencies.getResult(FrontendService.java:4681) ~[starrocks-fe.jar:?]
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.net.UnknownHostException: cluster
```

### StarRocks version (Required)
 - 3.2.1-79ee91d

### PR DESCRIPTION
**Pull request by Jin-H**
Why I'm doing:

What I'm doing:

I just add try catch when invoke `getTable` method

Fixes https://github.com/StarRocks/starrocks/issues/37722

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by Jin-H** [comment]
@mofeiatwork Can you help review it?

**Review by LiShuMing — DISMISSED** [review]

File: fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysObjectDependenciesTest.java [hunk 1]
```diff
@@ -0,0 +1,166 @@
...
+        Assert.assertNotNull(objectDependencyRes);
+        Assert.assertEquals(2, objectDependencyRes.getItemsSize());
+        Assert.assertEquals("OLAP", objectDependencyRes.getItems().get(0).getRef_object_type());
+    }
+
+
+    @Test
+    public void testUnknownCatalogObjectDependencies() throws Exception {
+
+        Config.dynamic_partition_check_interval_seconds = 10000;
```
Comment (mofeiatwork) [inline fe/fe-core/src/test/java/com/starrocks/catalog/system/sys/SysObjectDependenciesTest.java:96]: Please restore the Config otherwise it would affect other test cases

**Review by murphyatwork — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]
