### PR TITLE
[Enhancement] Optimize colocate balance on backend restart

### LINKED ISSUE #10619: [Enhancement] Improve the colocate table balance strategy
### Steps to reproduce the behavior (Required)
1. Create a colocate table with replication_num = 1 in a cluster with 3 be node.
2. Restart one be.

### Expected behavior (Required)
The colcoate table should be stable.

### Real behavior (Required)
Colocate table become unstable. 

### StarRocks version (Required)
 - All

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #10619

## Problem Summary(Required) ：

This pr mainly do three things:
1. Won't make new relocation decision if there is still colocate relocation tasks in schedule.
    We want the previous relocation decision is handled completely before new decision is made, so
    this won't trigger concurrent relocation decision and may mess up the scheduling.
2. Let colocate repair take precedence over colocate balance because repair is more urgent to finish.
    If there is unavailable backend, balance task won't be scheduled.
3. Support fast recovery of scheduled tablets if previously considered backend comes alive, which can
    avoid lots of COLOCATE_MISMATCH task being scheduled and accelerate the colocate group to be
    in stable state.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 30 / 97 (30.93%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|14|59|23.73%|[98, 99, 100, 101, 102, 105, 109, 113, 117, 118, 123, 124, 125, 126, 221, 223, 231, 232, 233, 238, 240, 241, 329, 330, 331, 333, 335, 345, 346, 349, 350, 699, 700, 701, 707, 708, 709, 710, 711, 713, 716, 721, 722, 723, 725]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|10|30|33.33%|[652, 728, 729, 731, 732, 736, 737, 738, 739, 741, 743, 744, 745, 746, 747, 748, 749, 750, 751, 755]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|

**Comment by nshangyiming** [comment]
run starrocks_clang-tidy

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 35 / 101 (34.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|18|61|29.51%|[98, 99, 100, 101, 102, 105, 109, 113, 117, 118, 123, 124, 125, 126, 233, 234, 235, 240, 242, 243, 331, 332, 333, 335, 337, 347, 348, 351, 352, 701, 702, 703, 709, 710, 711, 712, 713, 715, 718, 723, 724, 725, 727]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|10|31|32.26%|[652, 728, 729, 731, 732, 736, 737, 738, 739, 741, 743, 744, 745, 746, 747, 748, 749, 750, 751, 755, 1111]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 104 (34.62%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|19|64|29.69%|[100, 101, 102, 103, 104, 107, 111, 115, 119, 120, 125, 126, 127, 128, 228, 229, 240, 241, 242, 247, 249, 250, 338, 339, 340, 342, 344, 354, 355, 358, 359, 708, 709, 710, 716, 717, 718, 719, 720, 722, 725, 730, 731, 732, 734]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|10|31|32.26%|[652, 728, 729, 731, 732, 736, 737, 738, 739, 741, 743, 744, 745, 746, 747, 748, 749, 750, 751, 755, 1111]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 1]
```diff
@@ -153,19 +216,43 @@ private void relocateAndBalanceGroup() {
                 continue;
             }
 
+            // Won't make new relocation decision if there is still colocate relocation tasks in schedule.
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:219]: What's the purpose of serial execution?

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 2]
```diff
@@ -153,19 +216,43 @@ private void relocateAndBalanceGroup() {
...
+            }
+
+            stat.counterColocateBalanceRound.incrementAndGet();
             Set<Long> unavailableBeIdsInGroup = getUnavailableBeIdsInGroup(infoService, colocateIndex, groupId);
             List<Long> availableBeIds = getAvailableBeIds(infoService);
             List<List<Long>> balancedBackendsPerBucketSeq = Lists.newArrayList();
             if (relocateAndBalance(groupId, unavailableBeIdsInGroup, availableBeIds, colocateIndex, infoService,
                     statistic, balancedBackendsPerBucketSeq)) {
+                group2ColocateRelocationInfo.put(groupId,
+                        new ColocateRelocationInfo(!unavailableBeIdsInGroup.isEmpty() ? true : false,
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:241]:
```suggestion
                        new ColocateRelocationInfo(unavailableBeIdsInGroup.isEmpty() ? false : true,
```

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 3]
```diff
@@ -358,11 +461,18 @@ private boolean relocateAndBalance(GroupId groupId, Set<Long> unavailableBeIds,
                 }
             }
 
+            if (!hasUnavailableBe && !unavailableBeIds.isEmpty() && isChanged) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:464]: hasUnavailableBe or !hasUnavailableBe?
!hasUnavailableBe means all the be is available.

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 4]
```diff
@@ -358,11 +466,18 @@ private boolean relocateAndBalance(GroupId groupId, Set<Long> unavailableBeIds,
                 }
             }
 
+            if (!disableRepairPrecedence && !hasUnavailableBe && !unavailableBeIds.isEmpty() && isChanged) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:469]: How about this case?
The table has one replica and failed. 
The repair can not succeed but occupy the slot. The normal balance tasks can not advance.

File: fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java [hunk 5]
```diff
@@ -114,6 +114,8 @@ public class TabletSchedulerStat {
     public AtomicLong counterReplicaColocateMismatch = new AtomicLong(0L);
     @StatField("num of colocate replica redundant")
     public AtomicLong counterReplicaColocateRedundant = new AtomicLong(0L);
+    @StatField("num of ")
```
[the remark this answers is not in the document]
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedulerStat.java:117]: fixed

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java (hunk 2 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:246]: fixed

File: fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java [hunk 6]
```diff
@@ -687,6 +711,49 @@ private void scheduleTablet(TabletSchedCtx tabletCtx, AgentBatchTask batchTask)
...
+     * If all the replicas for tablets that belongs to some bucket are healthy(e.g. previously
+     * considered not alive backend comes alive or backend decommission is canceled), in this case,
+     * we don't really need to continue to execute the previously made relocation decision, we just
+     * cancel the scheduling by setting the status to HEALTHY.
+     * <p>
+     * If some tablets belongs to the same bucket are already scheduled based on the new backend sequence,
+     * we won't try to skip the current scheduling and reset the backend sequence because this will cause the tablets
+     * which have finished scheduling to be scheduled again.
+     *
+     * @return true, if we can skip the schedule, otherwise false
```
[the remark this answers is not in the document]
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java:728]: fixed

File: fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java [hunk 7]
```diff
@@ -627,6 +649,8 @@ private void scheduleTablet(TabletSchedCtx tabletCtx, AgentBatchTask batchTask)
                 Preconditions.checkState(tabletOrderIdx != -1);
 
                 Set<Long> backendsSet = colocateTableIndex.getTabletBackendsByGroup(groupId, tabletOrderIdx);
+                trySkipRelocateSchedAndResetBackendSeq(tabletCtx, partition.getVisibleVersion(),
+                        replicaNum, backendsSet);
```
[the remark this answers is not in the document]
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java:657]: we just reuse the following logic, `tablet.getColocateHealthStatus(..` will check the health and stop the scheduing if necessary, and in some circumstances, although the backend set is reset, but the current backend set of the tablet may not be the same as the reset backends, in this case we still need to continue the scheduling.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 39 / 108 (36.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|20|65|30.77%|[105, 106, 107, 108, 109, 112, 116, 120, 124, 125, 130, 131, 132, 133, 234, 235, 245, 246, 247, 252, 254, 255, 343, 344, 345, 347, 349, 359, 360, 363, 364, 713, 714, 715, 721, 722, 723, 724, 725, 727, 730, 735, 736, 737, 739]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|12|34|35.29%|[656, 730, 731, 733, 734, 738, 739, 740, 741, 743, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 758, 1114]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java [hunk 8]
```diff
@@ -687,6 +711,49 @@ private void scheduleTablet(TabletSchedCtx tabletCtx, AgentBatchTask batchTask)
...
+            // check the backends of original sequence are all available
+            for (Long backendId : lastBackendsSet) {
+                Backend be = infoService.getBackend(backendId);
+                if (!be.isAvailable()) {
+                    return;
+                }
+            }
+
+            int num = ColocateTableBalancer.getInstance().getScheduledTabletNumForBucket(ctx);
+            if (num == 0) {
```
[the remark this answers is not in the document]
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/TabletScheduler.java]: Yes, i have been considering to optimize this, plz see the new commit.

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java (hunk 3 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java]: `!hasUnavailableBe` is right condition
1. `!hasUnavailableBe` means that we have already handled all the unavailable backends
2. `!unavailableBeIds.isEmpty()` means that there exists unvailable backend which we have to handle
3. `isChanged` means that we have changed the backend set because of unavailable backends.

btw: i have tested this in the unit test.

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java (hunk 1 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:225]: Like the comments said, we don't want to complicate the relocation logic and concurrent relocation decision won't accelerate the scheduling process. This is also to make repair task precede over balance task.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 39 / 120 (32.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|1|00.00%|[869]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|0|10|00.00%|[361, 362, 363, 364, 366, 367, 368, 370, 373, 376]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|20|65|30.77%|[105, 106, 107, 108, 109, 112, 116, 120, 124, 125, 130, 131, 132, 133, 234, 235, 245, 246, 247, 252, 254, 255, 343, 344, 345, 347, 349, 359, 360, 363, 364, 713, 714, 715, 721, 722, 723, 724, 725, 727, 730, 735, 736, 737, 739]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|12|35|34.29%|[663, 737, 738, 740, 741, 745, 746, 747, 748, 750, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 766, 1122]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java (hunk 4 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:469]: This pr https://github.com/StarRocks/starrocks/pull/11730 optimize single replica balance. It will not cause relocation if there is only one replica.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 39 / 120 (32.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|0|1|00.00%|[869]|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|0|10|00.00%|[361, 362, 363, 364, 366, 367, 368, 370, 373, 376]|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|20|65|30.77%|[105, 106, 107, 108, 109, 112, 116, 120, 124, 125, 130, 131, 132, 133, 234, 235, 245, 246, 247, 252, 254, 255, 343, 344, 345, 347, 349, 359, 360, 363, 364, 713, 714, 715, 721, 722, 723, 724, 725, 727, 730, 735, 736, 737, 739]|
|:large_blue_circle:|com/starrocks/clone/TabletScheduler.java|12|35|34.29%|[663, 737, 738, 740, 741, 745, 746, 747, 748, 750, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 766, 1122]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedCtx.java|6|8|75.00%|[476, 477]|
|:large_blue_circle:|com/starrocks/clone/TabletSchedulerStat.java|1|1|100.00%|[]|

**Review by chaoyli — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
