### PR TITLE
Fix the bug that the dp search space becomes larger by using BitSet as the key of dp reorder

### LINKED ISSUE #4339: Dp reorder takes too much time
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4339

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 38 / 38 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java|38|38|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java [hunk 1]
```diff
@@ -107,12 +97,32 @@ private GroupInfo getBestExpr(Set<OptExpression> joinKeys, List<GroupInfo> group
         return bestPlan;
     }
 
-    private Set<Set<Integer>> generatePartitions(int totalNodes) {
-        checkArgument(totalNodes > 1, "totalNodes must be greater than 1");
-        Set<Integer> numbers = IntStream.range(0, totalNodes).boxed().collect(toImmutableSet());
-        return powerSet(numbers).stream()
+    private List<BitSet> generatePartitions(BitSet totalNodes) {
+        Set<Integer> numbers = IntStream.range(0, totalNodes.cardinality()).boxed().collect(toImmutableSet());
+        Set<Set<Integer>> sets = powerSet(numbers).stream()
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java:102]: why not use bitset to generate powerSet

**Review by murphyatwork — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java (hunk 1 above)
Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/join/JoinReorderDP.java:102]: Because the input parameter of powerSet is Set<Integer>, BitSet cannot be used, so a conversion is here

**Review by Youngwb — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
