### PR TITLE
[BugFix] context switch until overflow-chunk is empty

### LINKED ISSUE #5997: overflow-chunk-empty context switch bug
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

If this select triggers context switch in segment iterators, then some data will lose.

### Expected behavior (Required)
Result correct

### Real behavior (Required)
Result num is less than expected

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
0cf04e94

### LINKED ISSUE #6007: Wrong result of select after delete.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `duplicate_table_without_null` ( `k1`  date NOT NULL, `k2`  datetime NOT NULL, `k3`  char(20) NOT NULL, `k4`  varchar(20) NOT NULL, `k5`  boolean NOT NULL, `k6`  tinyint NOT NULL, `k7`  smallint NOT NULL, `k8`  int NOT NULL, `k9`  bigint NOT NULL, `k10` largeint NOT NULL, `k11` float NOT NULL, `k12` double NOT NULL, `k13` decimal(27,9) NOT NULL ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T common/data/basic_types_data -XPUT -H label:load_duplicate_table_without_null_2ca6180c_d1ad_11ec_8fff_00163e0e489a -H max_filter_ratio:0.8 http://172.26.92.141:8034/api/test/duplicate_table_without_null/_stream_load
```
3.delete.
```
delete from duplicate_table_without_null where k1='2020-06-23' and k2='2020-06-23 00:00:00' and k3='beijing' and k4='haidian' and k5=1;
```
4. SELECT  '....'
```
select count(*) from duplicate_table_without_null where k9>-9223372036854775801;
```
### Expected behavior (Required)
```
mysql> select count(*) from duplicate_table_without_null where k9>-9223372036854775801;
+----------+
| count(*) |
+----------+
|    65528 |
+----------+
1 row in set (0.01 sec)

mysql> explain select count(*) from duplicate_table_without_null where k9>-9223372036854775801;
+-----------------------------------------------+
| Explain String                                |
+-----------------------------------------------+
| PLAN FRAGMENT 0                               |
|  OUTPUT EXPRS:14: count                       |
|   PARTITION: UNPARTITIONED                    |
|                                               |
|   RESULT SINK                                 |
|                                               |
|   3:AGGREGATE (merge finalize)                |
|   |  output: count(14: count)                 |
|   |  group by:                                |
|   |                                           |
|   2:EXCHANGE                                  |
|                                               |
| PLAN FRAGMENT 1                               |
|  OUTPUT EXPRS:                                |
|   PARTITION: RANDOM                           |
|                                               |
|   STREAM DATA SINK                            |
|     EXCHANGE ID: 02                           |
|     UNPARTITIONED                             |
|                                               |
|   1:AGGREGATE (update serialize)              |
|   |  output: count(*)                         |
|   |  group by:                                |
|   |                                           |
|   0:OlapScanNode                              |
|      TABLE: duplicate_table_without_null      |
|      PREAGGREGATION: ON                       |
|      PREDICATES: 9: k9 > -9223372036854775801 |
|      partitions=1/1                           |
|      rollup: duplicate_table_without_null     |
|      tabletRatio=3/3                          |
|      tabletList=180954158,180954160,180954162 |
|      cardinality=1                            |
|      avgRowSize=1.0                           |
|      numNodes=0                               |
+-----------------------------------------------+
35 rows in set (0.00 sec)
```
### Real behavior (Required)
```
mysql> select count(*) from duplicate_table_without_null where k9>-9223372036854775801;
+----------+
| count(*) |
+----------+
|    53248 |
+----------+
1 row in set (0.01 sec)

mysql> explain select count(*) from duplicate_table_without_null where k9>-9223372036854775801;
+-----------------------------------------------+
| Explain String                                |
+-----------------------------------------------+
| PLAN FRAGMENT 0                               |
|  OUTPUT EXPRS:14: count                       |
|   PARTITION: UNPARTITIONED                    |
|                                               |
|   RESULT SINK                                 |
|                                               |
|   3:AGGREGATE (merge finalize)                |
|   |  output: count(14: count)                 |
|   |  group by:                                |
|   |                                           |
|   2:EXCHANGE                                  |
|                                               |
| PLAN FRAGMENT 1                               |
|  OUTPUT EXPRS:                                |
|   PARTITION: RANDOM                           |
|                                               |
|   STREAM DATA SINK                            |
|     EXCHANGE ID: 02                           |
|     UNPARTITIONED                             |
|                                               |
|   1:AGGREGATE (update serialize)              |
|   |  output: count(*)                         |
|   |  group by:                                |
|   |                                           |
|   0:OlapScanNode                              |
|      TABLE: duplicate_table_without_null      |
|      PREAGGREGATION: ON                       |
|      PREDICATES: 9: k9 > -9223372036854775801 |
|      partitions=1/1                           |
|      rollup: duplicate_table_without_null     |
|      tabletRatio=3/3                          |
|      tabletList=180954150,180954152,180954154 |
|      cardinality=1                            |
|      avgRowSize=1.0                           |
|      numNodes=0                               |
+-----------------------------------------------+
35 rows in set (0.00 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - MAIN-RELEASE 8e5b859

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5997
Fixes #6007

## Problem Summary(Required) ：

This pr fix the second bug introduced by https://github.com/StarRocks/starrocks/pull/5701

In current implementation, we will perform context switch even if the _overflow_read_chunk
is not empty, this will leads to some data lost. We need to wait until the data in _overflow_read_chunk
processed in next batch, then we can safely perform context switch.

### CODE REVIEW

File: be/src/storage/rowset/segment_iterator.cpp [hunk 1]
```diff
@@ -279,14 +279,17 @@ class SegmentIterator final : public ChunkIterator {
...
 };
 
 SegmentIterator::SegmentIterator(std::shared_ptr<Segment> segment, vectorized::Schema schema,
                                  vectorized::SegmentReadOptions options)
         : ChunkIterator(std::move(schema), options.chunk_size),
           _segment(std::move(segment)),
           _opts(std::move(options)),
-          _predicate_columns(_opts.predicates.size()) {}
+          _predicate_columns(_opts.predicates.size()),
+          _context_switch_next_time(false) {}
```
Comment (stdpain) [inline be/src/storage/rowset/segment_iterator.cpp:292]: duplicate Initialize

**Review by kangkaisen — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
