### PR TITLE
[BugFix] Fix dcg data not read correctly when switching from column mode to row mode in partial update

### LINKED ISSUE #61469: DCG data not read correctly when switching from column mode to row mode in partial update
### Steps to reproduce the behavior (Required)
```sql
mysql> show variables like '%partial%';
+---------------------+-------+
| Variable_name       | Value |
+---------------------+-------+
| partial_update_mode | auto  |
+---------------------+-------+
1 row in set (0.02 sec)

mysql> create table tmp.t1(id int , os string, version string) primary key (id) properties ("replication_num" = "1");
Query OK, 0 rows affected (0.13 sec)

mysql> insert into tmp.t1(id, os, version) values (1, '1', 1);
Query OK, 1 row affected (1.15 sec)
{'label':'insert_32d8aa89-6dba-11f0-86ef-0ece293c0556', 'status':'VISIBLE', 'txnId':'569368626'}

mysql> select * from tmp.t1;
+------+------+---------+
| id   | os   | version |
+------+------+---------+
|    1 | 1    | 1       |
+------+------+---------+
1 row in set (0.03 sec)

mysql> set partial_update_mode = 'column';
Query OK, 0 rows affected (0.04 sec)

mysql> update tmp.t1 set os = '2' where id = 1;
Query OK, 1 row affected (0.14 sec)
{'label':'update_4604ce37-6dba-11f0-86ef-0ece293c0556', 'status':'VISIBLE', 'txnId':'569369685'}

mysql> select * from tmp.t1;
+------+------+---------+
| id   | os   | version |
+------+------+---------+
|    1 | 2    | 1       |
+------+------+---------+
1 row in set (0.03 sec)

mysql> insert into tmp.t1 (id, version ) values (1, 2);
Query OK, 1 row affected (0.21 sec)
{'label':'insert_54b52f18-6dba-11f0-86ef-0ece293c0556', 'status':'VISIBLE', 'txnId':'569370398'}

mysql> select * from tmp.t3;
+------+------+---------+
| id   | os   | version |
+------+------+---------+
|    1 | 1    | 2       |
+------+------+---------+
1 row in set (0.02 sec)
```

### Expected behavior (Required)
When performing partial updates in StarRocks Lake format, the system should correctly read the latest data including Delta Column Group (DCG) updates when switching from column update mode to row update mode.

### Real behavior (Required)
When switching from column mode to row mode, the system incorrectly reads old data from the original segment instead of the updated data from DCG files.

### StarRocks version (Required)
- 3.5.2 
- 3.3.8

### PR DESCRIPTION
**Pull request by predator4ann**
## What I'm doing:

Fixes #61469 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [x] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/storage/lake/update_manager.cpp [hunk 1]
```diff
@@ -588,9 +657,31 @@ Status UpdateManager::get_column_values(const RowsetUpdateStateParams& params, s
...
             const TabletColumn& col = tablet_schema->column(read_column_ids[i]);
-            ASSIGN_OR_RETURN(auto col_iter, (*segment)->new_column_iterator_or_default(col, nullptr));
+            std::unique_ptr<ColumnIterator> col_iter = nullptr;
+
+            // try dcg read only if dcg context exists
+            if (dcg_ctx != nullptr) {
+                auto dcg_col_iter_result = new_lake_dcg_column_iterator(*dcg_ctx, fs, iter_opts, col, tablet_schema);
+                if (dcg_col_iter_result.ok() && dcg_col_iter_result.value() != nullptr) {
+                    col_iter = std::move(dcg_col_iter_result.value());
+                }
```
Comment (smartlxh) [inline be/src/storage/lake/update_manager.cpp:738]: if !dcg_col_iter_result.ok(), error should be thrown?

File: be/src/storage/lake/update_manager.cpp [hunk 2]
```diff
@@ -518,6 +522,46 @@ Status UpdateManager::get_rowids_from_pkindex(int64_t tablet_id, int64_t base_ve
...
+    ASSIGN_OR_RETURN(auto dcg_segment, get_lake_dcg_segment(ctx, column.unique_id(), &col_index, read_tablet_schema));
+    if (dcg_segment != nullptr) {
+        if (ctx.dcg_read_files.count(dcg_segment->file_name()) == 0) {
+            ASSIGN_OR_RETURN(auto read_file, fs->new_random_access_file(dcg_segment->file_info()));
+            ctx.dcg_read_files[dcg_segment->file_name()] = std::move(read_file);
+        }
+        iter_opts.read_file = ctx.dcg_read_files[dcg_segment->file_name()].get();
+        return dcg_segment->new_column_iterator(column, nullptr);
+    }
+    return nullptr;
```
Comment (smartlxh) [inline be/src/storage/lake/update_manager.cpp]: The return value should't be `Staus<nullptr>`?

File: be/src/storage/lake/update_manager.cpp (hunk 1 above)
Comment (predator4ann) [reply be/src/storage/lake/update_manager.cpp:738]: yes, it should be throw.

File: be/src/storage/lake/update_manager.cpp (hunk 2 above)
Comment (predator4ann) [reply be/src/storage/lake/update_manager.cpp]: I'm not quite sure what the more appropriate return should be, but the design should be: 
- Success and with data: returns an iterator 
- Success but no data: Return a specific "no data" status 
- Failure: Return error status

File: be/src/storage/lake/update_manager.cpp [hunk 3]
```diff
@@ -518,6 +522,53 @@ Status UpdateManager::get_rowids_from_pkindex(int64_t tablet_id, int64_t base_ve
...
+static StatusOr<std::unique_ptr<ColumnIterator>> new_lake_dcg_column_iterator(
+        GetDeltaColumnContext& ctx, const std::shared_ptr<FileSystem>& fs, ColumnIteratorOptions& iter_opts,
+        const TabletColumn& column, const TabletSchemaCSPtr& read_tablet_schema) {
+    // build column iter from dcg
+    int32_t col_index = 0;
+    auto dcg_segment_result = get_lake_dcg_segment(ctx, column.unique_id(), &col_index, read_tablet_schema);
+    if (!dcg_segment_result.ok()) {
+        // Column not found in DCG, this is expected and not an error
+        if (dcg_segment_result.status().is_not_found()) {
+            return Status::NotFound("Column not found in DCG");
```
Comment (luohaha) [inline be/src/storage/lake/update_manager.cpp]: Why not just return this status?

File: be/src/storage/lake/update_manager.cpp [hunk 4]
```diff
@@ -588,9 +664,36 @@ Status UpdateManager::get_column_values(const RowsetUpdateStateParams& params, s
...
             const TabletColumn& col = tablet_schema->column(read_column_ids[i]);
-            ASSIGN_OR_RETURN(auto col_iter, (*segment)->new_column_iterator_or_default(col, nullptr));
+            std::unique_ptr<ColumnIterator> col_iter = nullptr;
+
+            // try dcg read only if dcg context exists
+            if (dcg_ctx != nullptr) {
+                auto dcg_col_iter_result = new_lake_dcg_column_iterator(*dcg_ctx, fs, iter_opts, col, tablet_schema);
+                if (dcg_col_iter_result.ok()) {
+                    col_iter = std::move(dcg_col_iter_result.value());
+                } else if (!dcg_col_iter_result.status().is_not_found()) {
```
Comment (luohaha) [inline be/src/storage/lake/update_manager.cpp:734]: This not found could be return because of data file not exist, which can't be skip

File: be/src/storage/lake/update_manager.cpp (hunk 3 above)
Comment (predator4ann) [reply be/src/storage/lake/update_manager.cpp]: done

File: be/src/storage/lake/update_manager.cpp (hunk 4 above)
Comment (predator4ann) [reply be/src/storage/lake/update_manager.cpp:734]: done

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by luohaha — DISMISSED** [review]

**Review by smartlxh — DISMISSED** [review]

**Review by smartlxh — APPROVED** [review]

**Review by luohaha — APPROVED** [review]

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-4.0
