### PR TITLE
[BugFix] fix default_warehouse initialization in multiple scenarios

### LINKED ISSUE #51576: Error "Warehouse id: 0 not  exist."
### Steps to reproduce the behavior (Required)
1. Create a frontend & backend in the same docker compose file.
2. Start docker compose & add the backend as a backend in the front end.
3. Create a database & a table under it.
4. Create a routine load to the table from a kafka stream.
5. Stop both instances by pressing CTRL+C
6. Wait for both all instances to stop
7. Start up the instances again

### Expected behavior (Required)
```
starrocks-fe-0  | WARNING: Exception thrown during asynchronous load
starrocks-fe-0  | java.util.concurrent.CompletionException: com.starrocks.common.ErrorReportException: Warehouse id: 0 not 
exist.
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)    
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)  
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)   
starrocks-fe-0  |       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)       
starrocks-fe-0  |       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)       
starrocks-fe-0  |       at java.base/java.lang.Thread.run(Thread.java:829)
starrocks-fe-0  | Caused by: com.starrocks.common.ErrorReportException: Warehouse id: 0 not exist.
starrocks-fe-0  |       at com.starrocks.common.ErrorReportException.report(ErrorReportException.java:38)
starrocks-fe-0  |       at com.starrocks.server.WarehouseManager.getWarehouse(WarehouseManager.java:91)
starrocks-fe-0  |       at com.starrocks.server.WarehouseManager.getBackgroundWarehouse(WarehouseManager.java:258)
starrocks-fe-0  |       at com.starrocks.statistic.StatisticUtils.buildConnectContext(StatisticUtils.java:111)
starrocks-fe-0  |       at com.starrocks.sql.optimizer.statistics.ColumnBasicStatsCacheLoader.lambda$asyncLoadAll$1(ColumnBasicStatsCacheLoader.java:91)
starrocks-fe-0  |       at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)   
starrocks-fe-0  |       ... 3 more
```

### Real behavior (Required)
Nothing.

### StarRocks version (Required)
 - 3.3.3-312ed45

### PR DESCRIPTION
**Pull request by kevincai**
## Why I'm doing:

Need to considering the following cases for the default_warehouse initialization.
1. new setup cluster for the first time, -> leader node initialization in `transferToLeader()` after all journals replayed
2. new setup cluster for the first time, -> non-leader node initialization in `transferToNonLeader()` after all journals replayed
3. fe node restart, no image exists, but edit log exists to replay, -> default_warehouse initialization just after `loadImage()` before `replayJournals()`
4. fe node restart, has images and editlog to replay, -> initializing the default_warehouse during the `warehouseManger.load()` as part of `loadImage()`

## What I'm doing:

Fixes #51576

1. If the FE started with meta image, the default warehouse will be initialized along with the `WarehouseManager::load()`, although `WarehouseManager::save()` is empty. So after `loadImage()`, the default warehouse will be ready for any actions in `postImageLoad()` or `replayJournal()` for both leader and non-leader nodes.
2. In case there is no meta image available at all, usually it is the cluster first setup or cluster running not for long and the first image is not trigger. The default warehouse will be initialized again inside the role transfer `transferToLeader()/transferToNonLeader()` before `replayJournal()` so that the default_warehouse will be still ready for journal replays in case any EditLog that may need default_warehouse to perform some checks.

Because the `initDefaultWarehouse()` may be called multiple times, one is from the WarehouseManager::load() if there is any meta image available, one is from the role transfer before `replayJournal()`, so the interface must be implemented idempotent. 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3

### CODE REVIEW

**Comment by gengjun-git** [comment]
Some many places to init default warehouse, It's hard to maintain consistent for all the cases and difficult to maintain and understand. How about persist it to edit log on the first start time?

**Comment by kevincai** [comment]
> Some many places to init default warehouse, It's hard to maintain consistent for all the cases and difficult to maintain and understand. How about persist it to edit log on the first start time?

may cause incompatiblilty upgrading from community version to enterprise version.

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -1524,19 +1525,19 @@ private void transferToNonLeader(FrontendNodeType newType) {
             return;
         }
 
-        // transfer from INIT/UNKNOWN to OBSERVER/FOLLOWER
+        if (!isDefaultWarehouseCreated) {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1528]: So isDefaultWarehouseCreated is useless if initDefaultWarehouse() is idempotent?

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1528]: yes

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java (hunk 1 above)
Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1528]: will keep it for now, this PR will be focused on the fix of order of default warehouse initialization

**Review by wyb — APPROVED** [review]
