### PR TITLE
[BugFix] Fix race condition of TMasterInfo

### LINKED ISSUE #7523: ASAN error use after free
```
==7697==ERROR: AddressSanitizer: heap-use-after-free on address 0x60f000034690 at pc 0x000007001c90 bp 0x7f09f9a0e2d0 sp 0x7f09f9a0e2c8
READ of size 4 at 0x60f000034690 thread T516
    #0 0x7001c8f in starrocks::TaskWorkerPool::_report_workgroup_thread_callback(void*) /root/starrocks/be/src/agent/task_worker_pool.cpp:1254
    #1 0x702149f in void* std::__invoke_impl<void*, void* (*)(void*), starrocks::TaskWorkerPool*>(std::__invoke_other, void* (*&&)(void*), starrocks::TaskWorkerPool*&&) /usr/include/c++/10.3.0/bits/invoke.h:60
    #2 0x70213c7 in std::__invoke_result<void* (*)(void*), starrocks::TaskWorkerPool*>::type std::__invoke<void* (*)(void*), starrocks::TaskWorkerPool*>(void* (*&&)(void*), starrocks::TaskWorkerPool*&&) /usr/include/c++/10.3.0/bits/invoke.h:95
    #3 0x7021338 in void* std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /usr/include/c++/10.3.0/thread:264
    #4 0x70212e5 in std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool*> >::operator()() (/home/disk1/sr/master_asan/be/lib/starrocks_be+0x70212e5)
    #5 0x70211b5 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool*> > >::_M_run() /usr/include/c++/10.3.0/thread:215
    #6 0xcf7422f in execute_native_thread_routine ../../../.././libstdc++-v3/src/c++11/thread.cc:80
    #7 0x7f0af85baea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #8 0x7f0af7bd58dc in __clone (/lib64/libc.so.6+0xfe8dc)

0x60f000034690 is located 48 bytes inside of 168-byte region [0x60f000034660,0x60f000034708)
freed by thread T0 here:
    #0 0x4ae59d7 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x68e033c in starrocks::TMasterInfo::~TMasterInfo() /root/starrocks/gensrc/build/gen_cpp/HeartbeatService_types.cpp:18
    #2 0x6187ee5 in starrocks::ExecEnv::_destroy() /root/starrocks/be/src/runtime/exec_env.cpp:423
    #3 0x61893af in starrocks::ExecEnv::destroy(starrocks::ExecEnv*) /root/starrocks/be/src/runtime/exec_env.cpp:568
    #4 0x4b25904 in main /root/starrocks/be/src/service/starrocks_main.cpp:305
    #5 0x7f0af7af9554 in __libc_start_main (/lib64/libc.so.6+0x22554)

previously allocated by thread T0 here:
    #0 0x4ae4bb7 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x618261c in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:219
    #2 0x61802f3 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:146
    #3 0x4b24f15 in main /root/starrocks/be/src/service/starrocks_main.cpp:248
    #4 0x7f0af7af9554 in __libc_start_main (/lib64/libc.so.6+0x22554)

Thread T516 created by T0 here:
    #0 0x4a8e8b2 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0xcf742f4 in __gthread_create /var/local/gcc/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663
    #2 0xcf742f4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ../../../.././libstdc++-v3/src/c++11/thread.cc:135
    #3 0x6ff2208 in starrocks::TaskWorkerPool::_spawn_callback_worker_thread(void* (*)(void*)) /root/starrocks/be/src/agent/task_worker_pool.cpp:306
    #4 0x6fef4c1 in starrocks::TaskWorkerPool::start() /root/starrocks/be/src/agent/task_worker_pool.cpp:161
    #5 0x6fd2cb4 in starrocks::AgentServer::AgentServer(starrocks::ExecEnv*, starrocks::TMasterInfo const&) /root/starrocks/be/src/agent/agent_server.cpp:90
    #6 0x64a0899 in starrocks::BackendService::BackendService(starrocks::ExecEnv*) /root/starrocks/be/src/service/service_be/backend_service.cpp:52
    #7 0x64a09ef in starrocks::BackendService::create_service(starrocks::ExecEnv*, int, starrocks::ThriftServer**) /root/starrocks/be/src/service/service_be/backend_service.cpp:55
    #8 0x649d239 in start_be() /root/starrocks/be/src/service/service_be/starrocks_be.cpp:42
    #9 0x4b25749 in main /root/starrocks/be/src/service/starrocks_main.cpp:286
    #10 0x7f0af7af9554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: heap-use-after-free /root/starrocks/be/src/agent/task_worker_pool.cpp:1254 in starrocks::TaskWorkerPool::_report_workgroup_thread_callback(void*)

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by sduzh**
The `TMasterInfo` instance of ExecEnv may be accessed by many `TaskWorkerPool` threads
and modified by `HeartbeatServer` from other threads.

Since `TMasterInfo` is read mostly and update rarely,  this implementation save `TMasterInfo` 
into a `butil::DoublyBufferedData` structure to achieve better read performance.

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

### CODE REVIEW

File: be/src/agent/agent_server.cpp [hunk 1]
```diff
@@ -51,10 +52,8 @@ const uint32_t ALTER_FINISH_TASK_MAX_RETRY = 10;
 
 FrontendServiceClientCache g_master_service_client_cache;
 
-AgentServer::AgentServer(ExecEnv* exec_env, const TMasterInfo& master_info)
-        : _exec_env(exec_env),
-          _master_info(master_info),
-          _master_client(new MasterServerClient(master_info, &g_master_service_client_cache)) {
+AgentServer::AgentServer(ExecEnv* exec_env)
```
Comment (sduzh) [inline be/src/agent/agent_server.cpp:55]: Removed the `TMasterInfo` parameter from the constructor.

**Review by imay — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
