### PR TITLE
[BugFix] Fixed unchecked cast leading to CCE 

### LINKED ISSUE #60439: array_generate 函数不支持传入动态的function
SELECT  array_generate(1, array_length(split('a,b,c', ',')));
错误如下：
ERROR 1064 (HY000): class com.starrocks.analysis.FunctionCallExpr cannot be cast to class com.starrocks.analysis.LargeIntLiteral (com.starrocks.analysis.FunctionCallExpr and com.starrocks.analysis.LargeIntLiteral are in unnamed module of loader 'app')

### PR DESCRIPTION
**Pull request by nozjkoitop**
## What I'm doing:
Unchecked cast causing class cast exception during analyze removed

Fixes #60439

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@nozjkoitop thanks for the contributing, could you sign the CLA?

File: fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java [hunk 1]
```diff
@@ -314,4 +314,10 @@ public void testFieldFunction() throws Exception {
         analyzeFail("select field(1)");
         analyzeFail("select field((1,2))");
     }
+
+    @Test
+    public void testArrayGenerate() throws Exception {
```
Comment (alvin-phoenix-ai) [inline fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java:319]: Could you add some test cases to cover the invalid input scenarios?

Comment (nozjkoitop) [reply fe/fe-core/src/test/java/com/starrocks/sql/analyzer/AnalyzeFunctionTest.java:319]: > Could you add some test cases to cover the invalid input scenarios?

Done, please take a look

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
