### PR TITLE
Truncate support decimal

### LINKED ISSUE #2605: TRUNCATE() result error
### Steps to reproduce the behavior (Required)
`SELECT TRUNCATE(0.0, 1326124691);`

### Expected behavior (Required)
0.000000000000000000000000000000
### Real behavior (Required)
```
+-------------------------+
| truncate(0, 1326124691) |
+-------------------------+
|                     nan |
+-------------------------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
select current_version();
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE 635482f |
+------------------------------------------+
```

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #2605

## Problem Summary(Required) ：

Double cannot represent the given floating-point number exactly (e.g. `18450.76` is stored as `18450.759999999998` )

Therefore, add another function `truncate_decimal` to support decimal. But this version of truncate have some limitations

1. If the second param must be literal or slotRef expression
1. if the first param's scale cannot be deduced in FE, then the scale of return type will be set to default decimal128(38,9)

### CODE REVIEW

**Comment by kangkaisen** [comment]
My question is： even if we use double return type，if we round the result, could we get the right result?

**Comment by liuyehcf** [comment]
> 

I think we cannot get right result by an extran round operator, because storing float-point as `double` may cause deviation, and round operator will lead to another deviation instead of compensation

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

File: be/src/exprs/vectorized/arithmetic_operation.h [hunk 1]
```diff
@@ -55,7 +55,8 @@ bool check_fpe_of_min_div_by_minus_one(LType lhs, RType rhs) {
 template <typename Op, PrimitiveType Type, typename = guard::Guard, typename = guard::Guard>
 struct ArithmeticBinaryOperator {
     template <typename LType, typename RType, typename ResultType>
-    static inline ReturnType<Type, ResultType> apply(const LType& l, const RType& r) {
+    static inline ReturnType<Type, ResultType> apply(const LType& l, const RType& r, const ColumnPtr& l_column,
+                                                     const ColumnPtr& r_column) {
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/arithmetic_operation.h:59]: This solution introduce some unnecessary parameters.

As my understanding, you need to some more information about the type, including precision and scale for decimal type. Indeed the Column contains this information, but other part is unnecessary.

Maybe, we could introduce the TypeInfo, which contains all information of a type?

File: be/src/exprs/vectorized/binary_function.h [hunk 2]
```diff
@@ -31,12 +31,12 @@ class ResultNopCheck {
 template <typename OP>
 class BaseBinaryFunction {
 public:
-    template <PrimitiveType LType, PrimitiveType RType, PrimitiveType ResultType>
-    static ColumnPtr vector_vector(const ColumnPtr& v1, const ColumnPtr& v2) {
+    template <PrimitiveType LType, PrimitiveType RType, PrimitiveType ResultType, typename... Args>
+    static ColumnPtr vector_vector(const ColumnPtr& v1, const ColumnPtr& v2, Args&&... args) {
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/binary_function.h:35]: Why changed?

File: be/src/exprs/vectorized/math_functions.cpp [hunk 3]
```diff
@@ -104,6 +115,36 @@ DEFINE_UNARY_FN_WITH_IMPL(ZeroCheck, value) {
...
+        template <typename LType, typename RType, typename ResultType>                                       \
+        static inline ResultType apply(const LType& l, const RType& r, const ColumnPtr& l_column,            \
+                                       const ColumnPtr& r_column) {                                          \
+            return Truncate<LTYPE, RESULT_PT>::truncate(l, r, l_column, r_column);                           \
+        }                                                                                                    \
+    };                                                                                                       \
+    ColumnPtr MathFunctions::NAME(FunctionContext* context, const starrocks::vectorized::Columns& columns) { \
+        static_assert(pt_is_decimal<LTYPE>, "LTYPE must be Decimal");                                        \
+        const auto& type = context->get_return_type();                                                       \
+        if (type.precision <= 9 && LTYPE == PrimitiveType::TYPE_DECIMAL32) {                                 \
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/math_functions.cpp:130]: What's `9`?

File: be/src/exprs/vectorized/math_functions.h [hunk 4]
```diff
@@ -161,10 +164,22 @@ class MathFunctions {
     DEFINE_VECTORIZED_FN(round_up_to);
 
     /**
-     * @param: [DoubleColumn, IntColumn]
-     * @return: DoubleColumn
+     * @param: [DecimalV3Column<int32_t>, IntColumn]
+     * @return: DecimalV3Column<int128_t>
+     */
+    DEFINE_VECTORIZED_FN(truncate_decimal32);
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/math_functions.h:170]: What if other double functions? All of them need to implement three variants?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java [hunk 5]
```diff
@@ -813,6 +820,65 @@ public static void analyzeExpression(Expr expression, AnalyzeState state, Scope
         expressionAnalyzer.analyze(expression, state, scope);
     }
 
+    private Type getReturnTypeOfTruncate(FunctionCallExpr node, List<Type> paramsTypes) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:823]: Incredible!!!!

File: be/src/exprs/vectorized/binary_function.h (hunk 2 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/binary_function.h:35]: DecimalV3Column::create(...) need extra precision and scale

File: be/src/exprs/vectorized/math_functions.cpp (hunk 3 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp:130]: It means the maximum precision of decimal
* decimal32 -> 9
* decimal64->18
* decimal128->38

I'll add some comments

File: be/src/exprs/vectorized/math_functions.h (hunk 4 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.h:170]: Currently, yes, we need to add three variants

File: be/src/exprs/vectorized/arithmetic_operation.h (hunk 1 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/arithmetic_operation.h:59]: Yes, but we cannot use TypeInfo directly because it belongs to storage. And maybe better to introduce a context which contains all the extra information we need?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java (hunk 5 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:823]: This is unbelievable, do we need to implement the logic of each decimal method in FE?

Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:823]: Doesn't decimal have a general rule?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java [hunk 6]
```diff
@@ -813,6 +820,80 @@ public static void analyzeExpression(Expr expression, AnalyzeState state, Scope
...
+        Type firstParamType = paramsTypes.get(0);
+        Expr secondParam = node.getParams().exprs().get(1);
+
+        if (!firstParamType.isDecimalV3()) {
+            throw new IllegalArgumentException("first param of function truncate must be decimalV3");
+        }
+
+        if (!(secondParam instanceof IntLiteral)) {
+            throw new IllegalArgumentException("second param of function truncate must be int literal");
+        }
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:833]: Maybe we can't promise the condition, find function will consider type cast, so the type of param may different from the type of function params.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java (hunk 5 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java]: This logic has been removed, and now precision and scale of return type are calcuated at be side

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java (hunk 6 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java]: This logic has been removed

**Comment by liuyehcf** [comment]
> 

The reason that I modify the generic template is that I want to reuse the util template `UnionNullableColumnBinaryFunction` and `UnpackConstColumnBinaryFunction`. If I choose to implement truncate independently, I need to implement another version of `UnionNullableColumnBinaryFunction` and `UnpackConstColumnBinaryFunction`

**Comment by liuyehcf** [comment]
> I don't recommend your modify. You can implement truncate for decimal alone in a more special way instead of directly modify the basic template, such as you can implement truncate throught redefine a new UnpackConstColumnBinaryFunction, don't need rely on `DEFINE_BINARY_FUNCTION_WITH_IMPL`, or like `StringFunctions::substring`

The reason that I modify the generic template is that I want to reuse the util template `UnionNullableColumnBinaryFunction` and `UnpackConstColumnBinaryFunction`. If I choose to implement truncate independently, I need to implement another version of `UnionNullableColumnBinaryFunction` and `UnpackConstColumnBinaryFunction`

File: be/src/runtime/types.h [hunk 7]
```diff
@@ -70,6 +70,13 @@ struct TypeDescriptor {
 
     explicit TypeDescriptor(PrimitiveType type) : type(type), len(-1), precision(-1), scale(-1) {}
 
+    bool is_wildcard_decimal() const {
```
Comment (kangkaisen) [inline be/src/runtime/types.h:73]: needn’t handle TYPE_DECIMAL.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java [hunk 8]
```diff
@@ -102,6 +110,51 @@ public static Type normalizeDecimalArgTypes(Type[] argTypes, FunctionName fnName
...
+                    returnScale = expectedScale;
+                }
+            } else if (expectedScale < 0) {
+                // Invalid expectedScale, modify it to lower bounder
+                returnScale = 0;
+            } else {
+                // Scale reduce
+                returnScale = expectedScale;
+            }
+        } else if (Expr.containsSlotRef(secondArg)) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java:147]: should call !isConstantImpl?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java [hunk 9]
```diff
@@ -614,7 +613,11 @@ Function getDecimalV3Function(FunctionCallExpr node, Type[] argumentTypes) {
                 Type returnType = fn.getReturnType();
                 // Decimal v3 function return type maybe need change
                 if (returnType.isDecimalV3() && commonType.isValid()) {
-                    returnType = commonType;
+                    if (FunctionSet.TRUNCATE_DECIMAL.equalsIgnoreCase(fnName)) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:616]: should comment why TRUNCATE_DECIMAL is special.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java (hunk 8 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java:147]: We decide not support constant expression, because not all the constant can be calcuated in fe

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java (hunk 9 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java:616]: ok

File: be/src/runtime/types.h (hunk 7 above)
Comment (liuyehcf) [reply be/src/runtime/types.h:73]: This method never used, I will remove it

File: be/src/exprs/vectorized/math_functions.h [hunk 10]
```diff
@@ -2,6 +2,9 @@
 
 #pragma once
 
+#include <column/vectorized_fwd.h>
+#include <util/decimal_types.h>
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/math_functions.h:6]: unused?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java [hunk 11]
```diff
@@ -102,6 +110,51 @@ public static Type normalizeDecimalArgTypes(Type[] argTypes, FunctionName fnName
...
+            returnScale = originalScale;
+        } else {
+            throw new IllegalArgumentException(
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java:150]: How about throw an starrocks exception with MySQL's error code?

File: gensrc/script/vectorized/vectorized_functions.py [hunk 12]
```diff
@@ -53,6 +53,7 @@
     [10132, "round", "DOUBLE", ["DOUBLE", "INT"], "MathFunctions::round_up_to"],
     [10133, "dround", "DOUBLE", ["DOUBLE", "INT"], "MathFunctions::round_up_to"],
     [10134, "truncate", "DOUBLE", ["DOUBLE", "INT"], "MathFunctions::truncate"],
```
Comment (mofeiatwork) [inline gensrc/script/vectorized/vectorized_functions.py:55]: How about leave a deprecated comment the `truncate` function?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java (hunk 11 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/DecimalV3FunctionAnalyzer.java:150]: ok

File: gensrc/script/vectorized/vectorized_functions.py (hunk 12 above)
Comment (liuyehcf) [reply gensrc/script/vectorized/vectorized_functions.py:55]: Since we provide a new function named `truncate_decimal`, so the original `truncate` is not deprecated.

File: be/src/exprs/vectorized/math_functions.h (hunk 10 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.h]: Removed

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java (hunk 6 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/ExpressionAnalyzer.java]: There is the limitation that the second arg of `truncate_decimal` must be int literal or SlotRef expressions.

File: be/src/exprs/vectorized/math_functions.cpp [hunk 13]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+        dec = 0;
+    }
+    int32_t max_precision = decimal_precision_limit<int128_t>;
+    if (dec > max_precision) {
+        dec = max_precision;
+    }
+    int32_t scale_diff = dec - l_scale;
+    int128_t result;
+    if (scale_diff > 0) {
+        if (keep_scale) {
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:425]: why introduce keep_scale?

File: be/src/exprs/vectorized/math_functions.cpp [hunk 14]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+            result = lv;
+        } else {
+            DecimalV3Cast::to_decimal_truncate<int128_t, int128_t, int128_t, true, true>(
+                    lv, get_scale_factor<int128_t>(scale_diff), &result);
+        }
+    } else if (scale_diff < 0) {
+        DecimalV3Cast::to_decimal_truncate<int128_t, int128_t, int128_t, false, true>(
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:432]: if result is overflow, how to handle it?  overflow is ignored?   suggest to  return NULL value for overflow result.

File: be/src/exprs/vectorized/math_functions.cpp [hunk 15]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+                lv, get_scale_factor<int128_t>(-scale_diff), &result);
+        if (keep_scale) {
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:434]:
```
        if (keep_scale) {
            int128_t new_result;
            DecimalV3Cast::to_decimal_truncate<int128_t, int128_t, int128_t, true, true>(
                    result, get_scale_factor<int128_t>(-scale_diff), &new_result);
            result = new_result;
        }
```
can we write this code as follows?
```
if (keep_scale) {
    result = lv;
} else {
   DecimalV3Cast::to_decimal_truncate<int128_t, int128_t, int128_t, false, true>(
        lv, get_scale_factor<int128_t>(-scale_diff), &result);
}
```

File: be/src/exprs/vectorized/math_functions.cpp [hunk 16]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+    } else {
+        result = lv;
+    }
+    return result;
+}
+
+ColumnPtr MathFunctions::truncate_decimal128(FunctionContext* context, const starrocks::vectorized::Columns& columns) {
+    const auto& type = context->get_return_type();
+
+    ColumnPtr maybe_nullable_c1 = columns[0];
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:449]: suggest to use c0, c1 instead of maybe_nullable_{c1, c2}, a ColumnPtr has four cases: const null, const, nullable, not nullable. it's a common sense.

File: be/src/exprs/vectorized/math_functions.cpp [hunk 17]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+    ColumnPtr maybe_nullable_c2 = columns[1];
+    if (maybe_nullable_c1->only_null() || maybe_nullable_c2->only_null()) {
+        return ColumnHelper::create_const_null_column(maybe_nullable_c1->size());
+    }
+
+    // Unpack nullable
+    ColumnPtr maybe_const_c1 = FunctionHelper::get_data_column_of_nullable(maybe_nullable_c1);
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:456]: NullableColumn(ConstantColumn(...)) is a valid column type.

File: be/src/exprs/vectorized/math_functions.cpp [hunk 18]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+
+    // Unpack const
+    ColumnPtr c1 = FunctionHelper::get_data_column_of_const(maybe_const_c1);
+    ColumnPtr c2 = FunctionHelper::get_data_column_of_const(maybe_const_c2);
+    ColumnPtr c3 = RunTimeColumnType<TYPE_DECIMAL128>::create(type.precision, type.scale);
+    c3->resize_uninitialized(c1->size());
+
+    const int32_t original_scale = ColumnHelper::cast_to_raw<TYPE_DECIMAL128>(c1)->scale();
+
+    int128_t* raw_c1 = ColumnHelper::cast_to_raw<TYPE_DECIMAL128>(c1)->get_data().data();
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:470]: use auto* instead of int128_t*

File: be/src/exprs/vectorized/math_functions.cpp [hunk 19]
```diff
@@ -405,6 +409,95 @@ std::string MathFunctions::decimal_to_base(int64_t src_num, int8_t dest_base) {
...
+    int128_t* raw_c3 = ColumnHelper::cast_to_raw<TYPE_DECIMAL128>(c3)->get_data().data();
+
+    const int size = c1->size();
+    // If c2 is not const, than we need to keep the originl scale
+    if (c1_is_const && c2_is_const) {
+        raw_c3[0] = MathFunctions::decimal_truncate(raw_c1[0], original_scale, raw_c2[0], false);
+        c3 = ConstColumn::create(c3, c3->size());
+    } else if (c1_is_const) {
+        for (auto i = 0; i < size; i++) {
+            raw_c3[i] = MathFunctions::decimal_truncate(raw_c1[0], original_scale, raw_c2[i], true);
```
Comment (satanson) [inline be/src/exprs/vectorized/math_functions.cpp:481]: if the 2nd argument varies, keep_scale?

File: be/src/exprs/vectorized/math_functions.cpp (hunk 13 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp:425]: Comments are written at the defination.

```cpp
    // Specifically, keep_scale means whether to keep the original scale of lv
    // Given an example
    //      col1 - decimal(38,4)      col2 - (int)
    //      1.2345                   3
    //      1.2300                   1
    // The return type is decimal(38, 4), and the result of truncate by col2 are list as follows
    //      without_compensate
    //      1.23 decimal(38,2) <==> 0.1234 decimal(38,4)
    //      1.2  decimal(38,1) <==> 0.0012 decimal(38,4)
    // So we need to compensate
    //      with_compensate = without_compensate * 10^(4 - col)
    //      1.2340          = 0.1234             * 10
    //      1.2000          = 0.0012             * 1000
    static int128_t decimal_truncate(const int128_t& lv, const int32_t& l_scale, const int32_t& rv, bool keep_scale);
```

File: be/src/exprs/vectorized/math_functions.cpp (hunk 14 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp:432]: Thanks, good suggestion, I will handle the overflow.

File: be/src/exprs/vectorized/math_functions.cpp (hunk 17 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp:456]: yes, indeed, but this code will work if `maybe_nullable_c1` is not `NullableColumn`

File: be/src/exprs/vectorized/math_functions.cpp (hunk 18 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp:470]: Since the expression is too complicated, specified type may be more clear? What do you think?

File: be/src/exprs/vectorized/math_functions.cpp (hunk 16 above)
Comment (liuyehcf) [reply be/src/exprs/vectorized/math_functions.cpp]: Ok. I got it.

**Review by Seaven — APPROVED** [review]
LGTM, the work is so hard

**Review by kangkaisen — APPROVED** [review]
