### PR TITLE
[BugFix] Fix unknown error of 'ANALYZE PROFILE FROM xx' sql

### LINKED ISSUE #47757: Analyze profile sql return Unknown error
### Steps to reproduce the behavior (Required)
1. set enable_profile = true;
2. select count(1) from example_tbl;
3. select last_query_id();
4. ANALYZE PROFILE FROM 'xx';

### Expected behavior (Required)
Profile Data

### Real behavior (Required)
mysql> ANALYZE PROFILE FROM 'c2769b41-3870-11ef-9530-024236b2e3c5';
ERROR 1064 (HY000): Unknown error

### StarRocks version (Required)
 - 3.3

### PR DESCRIPTION
**Pull request by skyyws**
## Why I'm doing:

Currently, 'ANALYZE PROFILE FROM xxx ' return 'Unknown error', instread of profile data.

## What I'm doing:

Remove 'coord' short circuit check when handling analyze profile stmt, since 'coord' not been initialized when sql is not QueryStatement, so I think the check is no necessary.

Fixes #47757

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java [hunk 1]
```diff
@@ -1245,11 +1245,6 @@ private void handleAnalyzeProfileStmt() throws IOException, UserException {
         List<Integer> planNodeIds = analyzeProfileStmt.getPlanNodeIds();
         ProfileManager.ProfileElement profileElement = ProfileManager.getInstance().getProfileElement(queryId);
         Preconditions.checkNotNull(profileElement, "query not exists");
-        if (coord.isShortCircuit()) {
```
Comment (alvin-celerdata) [inline fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:1248]: I think this protection is to tell the user that the analyzing profile is mutually exclusive with the short circuit query, so removing this check will cause other exceptions if `enable_short_circuit=true`. 
I suggest fixing this issue by adding a check if `coord = null`.

**Review by alvin-phoenix-ai — COMMENTED** [review]
@skyyws welcome to StarRocks community, thanks for your contribution.

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java (hunk 1 above)
Comment (skyyws) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:1248]: Thanks for advice, the original patch is worked for non short circuit query, but still return error for short circuit query. Thus, I change the if condition from 'coord = null' to 'profileElement.plan == null' for two reasons:
1. For analyze profile sql, 'coord' is not being initialized;
2. ProfilingExecPlan is null for short circuit query in 'StmtExecutor#tryProcessProfileAsync', except 'ExecPlan' itself if null:
```
            ProfilingExecPlan profilingPlan;
            if (coord.isShortCircuit()) {
                profilingPlan = null;
            } else {
                profilingPlan = plan == null ? null : plan.getProfilingPlan();
            }
            String profileContent = ProfileManager.getInstance().pushProfile(profilingPlan, profile);
```

Comment (skyyws) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:1248]: Thanks for advice, the original patch is worked for non short circuit query, but still return error for short circuit query. Thus, I change the if condition from 'coord = null' to 'profileElement.plan == null' for two reasons:
1. For analyze profile sql, 'coord' is not being initialized;
2. ProfilingExecPlan is null for short circuit query in 'StmtExecutor#tryProcessProfileAsync', except 'ExecPlan' itself if null:
```
            ProfilingExecPlan profilingPlan;
            if (coord.isShortCircuit()) {
                profilingPlan = null;
            } else {
                profilingPlan = plan == null ? null : plan.getProfilingPlan();
            }
            String profileContent = ProfileManager.getInstance().pushProfile(profilingPlan, profile);
```

Comment (skyyws) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:1248]: If we want to distinguish short circuit query or 'ExecPlan' itself is null exactly, we need to reserve 'isShortCircuit' into 'ProfileElement' when calling pushProfile. I think this is not necessary since we need to modify many code.

Comment (alvin-celerdata) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:1248]: Your solution is much better than what I suggested, great job

**Review by alvin-phoenix-ai — APPROVED** [review]

**Comment by alvin-celerdata** [comment]
@skyyws It seems you need to use another email address to commit the change.

**Comment by skyyws** [comment]
> @skyyws It seems you need to use another email address to commit the change.

Done, thanks for reminder.

**Review by kangkaisen — APPROVED** [review]
