### PR TITLE
[BugFix]Only when unsupported column is referred, exception will be thrown.

### LINKED ISSUE #8073: hive table which contains binary type unavailable througn hive connector
### Steps to reproduce the behavior (Required)
1. create hive table:
```
create table hive_hdfs_csv_default(
col_tinyint tinyint comment "column tinyint"
,col_smallint smallint comment "column smallint"
,col_int int comment "column int"
,col_integer integer comment "column integer"
,col_bigint bigint comment "column bigint"
,col_float float comment "column float"
,col_double double comment "column double"
,col_double_precision double precision comment "column double precision"
,col_decimal decimal comment "column decimal"
,col_timestamp timestamp comment "column timestamp"
,col_date date comment "column date"
,col_string string comment "column string"
,col_varchar varchar(100) comment "column varchar"
,col_binary binary comment "column binary"
,col_char char(100) comment "column char"
,col_boolean boolean comment "column boolean"
,col_array array<int> comment "column array"
)
clustered by(col_int) sorted by(col_int) into 32 buckets
stored as textfile;
insert into hive_hdfs_csv_default select 1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi hello','1110001010101011001001','nihao',true,array(1,10,100);
insert into hive_hdfs_csv_default select 2,2,2,2,2,2.001,20.1,210.1,2110.2,'2021-02-01 12:10:23','2021-02-01','hello world','hi hello','1110001010101011001001','nihao',true,array(2,20,200);
insert into hive_hdfs_csv_default select 3,3,3,3,3,3.001,30.1,310.1,3110.1,'2021-03-01 12:10:23','2021-03-01','hello world','hi abc','1110001010101011001001','nihao',true,array(3,30,300);
```

2. create catalog and select hive table:
```
create external catalog hive_catalog_1656512586190 PROPERTIES("type" = "hive","hive.metastore.uris" = "thrift://***.***.***.***:9083");
mysql> select col_int from hive_catalog_1656512586190.hive_extbl_test.hive_hdfs_csv_default limit 1;
ERROR 1064 (HY000): Unknown table 'hive_hdfs_csv_default'
```

3. fe.log:
```
2022-06-29 22:29:55,646 ERROR (starrocks-mysql-nio-pool-14|387) [HiveMetaCache.getTable():315] Failed to get table [databaseName: hive_extbl_test, tableName: hive_hdfs_csv]
java.util.concurrent.ExecutionException: com.starrocks.common.DdlException: hive table column type [BINARY] transform failed.
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:527) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:104) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:240) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2313) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2279) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.external.hive.HiveMetaCache.getTable(HiveMetaCache.java:313) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.hive.HiveMetadata.getTable(HiveMetadata.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$1(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_262]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:669) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:66) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:235) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:161) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:83) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:206) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:106) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:100) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:83) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:88) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.InsertAnalyzer.analyze(InsertAnalyzer.java:34) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitInsertStatement(Analyzer.java:139) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitInsertStatement(Analyzer.java:51) ~[starrocks-fe.jar:?]
        at com.starrocks.analysis.InsertStmt.accept(InsertStmt.java:939) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:53) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:48) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:43) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:335) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:277) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:631) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: com.starrocks.common.DdlException: hive table column type [BINARY] transform failed.
        at com.starrocks.external.HiveMetaStoreTableUtils.convertColumnType(HiveMetaStoreTableUtils.java:219) ~[starrocks-fe.jar:?]
        at com.starrocks.external.HiveMetaStoreTableUtils.convertToSRTable(HiveMetaStoreTableUtils.java:241) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetaCache.loadTable(HiveMetaCache.java:323) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetaCache.access$700(HiveMetaCache.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:144) ~[starrocks-fe.jar:?]
        at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:141) ~[starrocks-fe.jar:?]
        at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
        ... 39 more
```

### Expected behavior (Required)
select query return the right result

### Real behavior (Required)
query error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 52bfe63 |
+----------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [ ] bug
- [x] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8073 

## Problem Summary(Required) ：

Table binarytest has two columns, col_int and col_binary, and only col_int is unsupported.
The goal is that, only when unsupported column is referred, exception will be thrown.
```
mysql> select * from binarytest;
ERROR 1064 (HY000): Column col_binary convert failed!
mysql> select col_binary from binarytest;
ERROR 1064 (HY000): Column col_binary convert failed!
mysql> select col_int from binarytest;
+---------+
| col_int |
+---------+
|     100 |
|     100 |
+---------+
2 rows in set (0.95 sec)

mysql> select col_int from binarytest where col_binary != null;
ERROR 1064 (HY000): Column col_binary convert failed!
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 48 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|3|00.00%|[664, 665, 667]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|3|33.33%|[217, 218]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|12|58.33%|[218, 219, 716, 812, 817]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|3|66.67%|[253]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|23|23|100.00%|[]|

**Comment by adzfolc** [comment]
PTAL @DorianZheng @mofeiatwork @HangyuanLiu

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java [hunk 1]
```diff
@@ -156,6 +156,9 @@ public static boolean validateColumnType(String hiveType, Type type) {
                         primitiveType == PrimitiveType.VARCHAR;
             case "BOOLEAN":
                 return primitiveType == PrimitiveType.BOOLEAN;
+            case "BINARY":
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java:159]: `validateColumnType` is used to validate external table schema when creation, so we can just return fail when types are unsupported

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java [hunk 2]
```diff
@@ -210,6 +213,9 @@ public static Type convertColumnType(String hiveType) throws DdlException {
             case "BOOLEAN":
                 primitiveType = PrimitiveType.BOOLEAN;
                 break;
+            case "BINARY":
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java:216]: Not only `Binary`. All unsupported types should be captured.

**Comment by DorianZheng** [comment]
@adzfolc Plz add more ut to cover more case

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java (hunk 1 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java:159]: > `validateColumnType` is used to validate external table schema when creation, so we can just return fail when types are unsupported

All queries related to external hive tables need to validate hive column, so if we return false when table column is unsupported, even if the query has no relation with unsupported type, will fail here.

**Comment by HangyuanLiu** [comment]
why not use INVALID_TYPE?

**Comment by adzfolc** [comment]
> why not use INVALID_TYPE?

In my opinion, Invalid and convert failed have different semantics. Invalid is an invalid column, and invalid type is not allowed in any table; for convert failed column, it is allowed to have this type in a table, but it is not allowed to exist in q query, as long as there is this column in sql, then an error will be reported.

**Comment by adzfolc** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 47 (76.60%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|0|3|00.00%|[664, 665, 667]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|3|33.33%|[217, 218]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|7|12|58.33%|[218, 219, 716, 813, 818]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|23|23|100.00%|[]|

**Comment by adzfolc** [comment]
PR Regression Link http://39.101.206.100:8090/view/regression/job/starrocks_pr_regression/626/

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java [hunk 3]
```diff
@@ -708,6 +710,14 @@ private void handleQueryStmt(ExecPlan execPlan) throws Exception {
...
         List<String> colNames = execPlan.getColNames();
         List<Expr> outputExprs = execPlan.getOutputExprs();
+        int colId = 0;
+        for (Expr expr : outputExprs) {
+            if (expr.getType().getPrimitiveType().equals(PrimitiveType.UNKNOWN_TYPE)) {
+                throw new SemanticException("Column " + colNames.get(colId) +
+                        " convert failed, and column type is known!");
+            }
+            colId++;
+        }
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:720]: You needn't do this check here, this case will be checked when the sql is analyzed. We should make sure that  all unknown type will be checked when analyzing.

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java [hunk 4]
```diff
@@ -660,7 +661,11 @@ private void prepareContextSlots(PhysicalScanOperator node, ExecPlan context, Tu
                         context.getDescTbl().addSlotDescriptor(tupleDescriptor, new SlotId(entry.getKey().getId()));
                 slotDescriptor.setColumn(entry.getValue());
                 slotDescriptor.setIsNullable(entry.getValue().isAllowNull());
-                slotDescriptor.setIsMaterialized(true);
+                if (slotDescriptor.getColumn().getPrimitiveType().equals(PrimitiveType.UNKNOWN_TYPE)) {
+                    slotDescriptor.setIsMaterialized(false);
+                } else {
+                    slotDescriptor.setIsMaterialized(true);
+                }
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:668]: You needn't change logic here neither.

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java [hunk 5]
```diff
@@ -149,6 +150,7 @@ public abstract class Type implements Cloneable {
                     .add(DECIMAL64)
                     .add(DECIMAL128)
                     .add(JSON)
+                    .add(UNKNOWN_TYPE)
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:153]: why unknown type is added into supported types?

Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:153]: > why unknown type is added into supported types?

Because when Fe analzy table, it need to resolve table. All hive types would be converted to sr types, including `UNKNOWN_TYPE`. In code, `ScalarType.createType()` will find `UNKNOWN_TYPE` in `SUPPORTED_TYPES`, if it is removed, exception will be thrown like below.

```
2022-07-26 10:47:24,907 ERROR (starrocks-mysql-nio-pool-1|150) [HiveMetaCache.getTable():315] Failed to get table [databaseName: old_test, tableName: binarytest]
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: unknown type UNKNOWN_TYPE
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache.get(LocalCache.java:3962) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3985) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4946) ~[spark-dpp-1.0.0.jar:?]
    at com.starrocks.external.hive.HiveMetaCache.getTable(HiveMetaCache.java:313) ~[starrocks-fe.jar:?]
    at com.starrocks.connector.hive.HiveMetadata.getTable(HiveMetadata.java:61) ~[starrocks-fe.jar:?]
    at com.starrocks.server.MetadataMgr.lambda$getTable$1(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
    at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_321]
    at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:114) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer.resolveTable(QueryAnalyzer.java:669) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer.access$100(QueryAnalyzer.java:66) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.resolveTableRef(QueryAnalyzer.java:235) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:161) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitSelect(QueryAnalyzer.java:83) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.ast.SelectRelation.accept(SelectRelation.java:206) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:88) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryRelation(QueryAnalyzer.java:106) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:100) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.visitQueryStatement(QueryAnalyzer.java:83) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer$Visitor.process(QueryAnalyzer.java:88) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.QueryAnalyzer.analyze(QueryAnalyzer.java:76) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:204) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitQueryStatement(Analyzer.java:68) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.ast.QueryStatement.accept(QueryStatement.java:36) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:104) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:70) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:65) ~[starrocks-fe.jar:?]
    at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:43) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:346) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:273) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:391) ~[starrocks-fe.jar:?]
    at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:624) ~[starrocks-fe.jar:?]
    at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_321]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_321]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_321]
Caused by: java.lang.NullPointerException: unknown type UNKNOWN_TYPE
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:899) ~[spark-dpp-1.0.0.jar:?]
    at com.starrocks.catalog.ScalarType.createType(ScalarType.java:106) ~[starrocks-fe.jar:?]
    at com.starrocks.external.HiveMetaStoreTableUtils.convertColumnType(HiveMetaStoreTableUtils.java:229) ~[starrocks-fe.jar:?]
    at com.starrocks.external.HiveMetaStoreTableUtils.convertToSRTable(HiveMetaStoreTableUtils.java:247) ~[starrocks-fe.jar:?]
    at com.starrocks.external.hive.HiveMetaCache.loadTable(HiveMetaCache.java:323) ~[starrocks-fe.jar:?]
    at com.starrocks.external.hive.HiveMetaCache.access$700(HiveMetaCache.java:39) ~[starrocks-fe.jar:?]
    at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:144) ~[starrocks-fe.jar:?]
    at com.starrocks.external.hive.HiveMetaCache$8.load(HiveMetaCache.java:141) ~[starrocks-fe.jar:?]
    at com.google.common.cache.CacheLoader$1.load(CacheLoader.java:192) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155) ~[spark-dpp-1.0.0.jar:?]
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045) ~[spark-dpp-1.0.0.jar:?]
    ... 36 more
```

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java (hunk 3 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java]: > You needn't do this check here, this case will be checked when the sql is analyzed. We should make sure that all unknown type will be checked when analyzing.

Got.Now I have removed these, and check SQL contains star like `select * from binarytest` checks to `SelectAnalyzer.analyzeSelect()`

**Comment by adzfolc** [comment]
run starrocks_be_unittest

**Comment by adzfolc** [comment]
PR Regression Link http://39.101.206.100:8090/view/regression/job/starrocks_pr_regression/632/

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java (hunk 2 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java:216]: > Not only `Binary`. All unsupported types should be captured.

```
            case "BINARY":
            case "MAP":
            case "STRUCT":
            case "UNIONTYPE":
                primitiveType = PrimitiveType.UNKNOWN_TYPE;
                break;
```
Now complex types and binary type will all be converted to UNKNOWN_TYPE.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 37 / 47 (78.72%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|6|33.33%|[217, 218, 804, 809]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|3|33.33%|[220, 221]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|4|50.00%|[391, 392]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|23|23|100.00%|[]|

**Comment by adzfolc** [comment]
run starrocks_be_build

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 37 / 47 (78.72%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|6|33.33%|[220, 221, 815, 820]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|3|33.33%|[209, 210]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|4|50.00%|[396, 397]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|23|23|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java (hunk 2 above)
Comment (DorianZheng) [reply fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java:205]: why not capture it in `default` branch?

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java [hunk 6]
```diff
@@ -367,6 +378,7 @@ public abstract class Type implements Cloneable {
         compatibilityMatrix[DATETIME.ordinal()][DECIMAL32.ordinal()] = PrimitiveType.DECIMAL32;
         compatibilityMatrix[DATETIME.ordinal()][DECIMAL64.ordinal()] = PrimitiveType.DECIMAL64;
         compatibilityMatrix[DATETIME.ordinal()][DECIMAL128.ordinal()] = PrimitiveType.DECIMAL128;
+        compatibilityMatrix[DATETIME.ordinal()][UNKNOWN_TYPE.ordinal()] = PrimitiveType.INVALID_TYPE;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:381]: why do we need to add the UNKNOWN_TYPE to compatibilityMatrix?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java [hunk 7]
```diff
@@ -191,6 +192,13 @@ private List<Expr> analyzeSelect(SelectList selectList, Relation fromRelation, b
                 List<Field> fields = (item.getTblName() == null ? scope.getRelationFields().getAllFields()
                         : scope.getRelationFields().resolveFieldsWithPrefix(item.getTblName()))
                         .stream().filter(Field::isVisible).collect(Collectors.toList());
+                List<String> unknownTypeFields = fields.stream()
+                        .filter(field -> field.getType().getPrimitiveType().equals(PrimitiveType.UNKNOWN_TYPE))
+                        .map(Field::getName).collect(Collectors.toList());
+                if (!unknownTypeFields.isEmpty()) {
+                    throw new SemanticException("Column " + unknownTypeFields
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java:199]:
```suggestion
                    throw new SemanticException("External Table Column " + unknownTypeFields
```

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java [hunk 8]
```diff
@@ -53,7 +54,12 @@ private Optional<ResolvedField> resolveField(SlotRef expression, int fieldIndexO
         if (matchFields.size() > 1) {
             throw new SemanticException("Column '%s' is ambiguous", expression.getColumnName());
         } else if (matchFields.size() == 1) {
-            return Optional.of(asResolvedField(matchFields.get(0), fieldIndexOffset));
+            if (matchFields.get(0).getType().getPrimitiveType().equals(PrimitiveType.UNKNOWN_TYPE)) {
+                throw new SemanticException("Column " + matchFields.get(0).getName()
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java:58]: Would better add the `external table` prefix to the error msg

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java (hunk 5 above)
Comment (kangkaisen) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:155]: I think you should change the `convertColumnType` method, not here.  I think it's unreasonable we make the UNKNOWN_TYPE as the SUPPORTED_TYPES, but we actually don't support it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 40 (92.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|2|50.00%|[209]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|25|25|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java (hunk 8 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Scope.java]: > Would better add the `external table` prefix to the error msg

Added

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java (hunk 7 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/SelectAnalyzer.java]: > 

Added

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java (hunk 5 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:156]: > I think you should change the `convertColumnType` method, not here. I think it's unreasonable we make the UNKNOWN_TYPE as the SUPPORTED_TYPES, but we actually don't support it.

In `convertColumnType`, I transfer hive column type to sr column type, so even if unsupported types like hive `Binary` should be given a sr column type.So, `UNKNOWN_TYPE` matches this case.So, `UNKNOWN_TYPE` should be one of `PrimitiveType`.It's truly counter-intuitive, but we still need it.

File: fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java (hunk 2 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/HiveMetaStoreTableUtils.java]: > 

done

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java [hunk 9]
```diff
@@ -457,34 +480,16 @@ public abstract class Type implements Cloneable {
...
-                    continue;
-                }
-                if (t1 == PrimitiveType.DECIMAL128 || t2 == PrimitiveType.DECIMAL128) {
-                    continue;
-                }
-                if (t1 == PrimitiveType.TIME || t2 == PrimitiveType.TIME) {
-                    continue;
-                }
-                if (t1 == PrimitiveType.JSON || t2 == PrimitiveType.JSON) {
+                List<PrimitiveType> skipCompareTypes = Arrays.asList(
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:488]: should be static

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java (hunk 6 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Type.java:382]: > why do we need to add the UNKNOWN_TYPE to compatibilityMatrix?

Because `UNKNOWN_TYPE` is added to `PrimitiveType`, and types will be compared with `UNKNOWN_TYPE`.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 39 / 42 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|2|50.00%|[209]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|25|25|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 39 / 42 (92.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|2|50.00%|[209]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|25|25|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/Type.java (hunk 9 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Type.java]: > should be static

done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 38 / 41 (92.68%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|1|2|50.00%|[209]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Scope.java|2|3|66.67%|[58]|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|5|80.00%|[199]|
|:large_blue_circle:|com/starrocks/catalog/PrimitiveType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/HiveTable.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ScalarType.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Type.java|25|25|100.00%|[]|

**Comment by adzfolc** [comment]
http://39.101.206.100:8090/view/regression/job/starrocks_pr_regression/653/

**Review by kangkaisen — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by adzfolc** [comment]
@Mergifyio backport branch-2.3
