### PR TITLE
Move the log outside from the lock scope

### LINKED ISSUE #3539: 3 BE environment when 1 BE alive, create one replication multi-partition table stuck for 10+ hours in asan mode
### Steps to reproduce the behavior (Required)
```
mysql> admin show frontend config like '%max_create_table_timeout_second%';
+---------------------------------+-------+------+-----------+---------+
| Key                             | Value | Type | IsMutable | Comment |
+---------------------------------+-------+------+-----------+---------+
| max_create_table_timeout_second | 600   | int  | true      |         |
+---------------------------------+-------+------+-----------+---------+
1 row in set (0.00 sec)
mysql> admin show frontend config like '%tablet_create_timeout_second%';
+------------------------------+-------+------+-----------+---------+
| Key                          | Value | Type | IsMutable | Comment |
+------------------------------+-------+------+-----------+---------+
| tablet_create_timeout_second | 60    | int  | true      |         |
+------------------------------+-------+------+-----------+---------+
1 row in set (0.00 sec)
```
1. CREATE TABLE test_multi_unique (             event_day DATE,             site_id INT DEFAULT '10',             city_code VARCHAR(100),             user_name VARCHAR(32) DEFAULT '',             pv BIGINT DEFAULT '0'             )
UNIQUE KEY(event_day, site_id, city_code, user_name)             PARTITION BY RANGE(event_day)             (
 START ("2021-01-01") END ("2023-01-01") EVERY (INTERVAL 1 day)             )             DISTRIBUTED BY HASH(site_id) BUCKETS 10             PROPERTIES (                 "replication_num" = "1",                 "storage_format" = "v2"
);

### Expected behavior (Required)
create table success

### Real behavior (Required)
stuck for 10+ hours, when i create above table with 1 tablet ,it timeout returns, but is expected to execute successfully.
```
mysql> CREATE TABLE test_multi_unique ( event_day DATE, site_id INT DEFAULT '10', city_code VARCHAR(100), user_name VARCHAR(32) DEFAULT '', pv BIGINT DEFAULT '0' ) UNIQUE KEY(event_day, site_id, city_code, user_name) PARTITION BY RANGE(event_day) ( START ("2021-01-01") END ("2021-01-02") EVERY (INTERVAL 1 day) ) DISTRIBUTED BY HASH(site_id) BUCKETS 1 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
ERROR 1064 (HY000): fail to create tablet: timed out. unfinished replicas(1/1): 56422278(172.26.92.141)  timeout=60s
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
MASTER_ASAN 7f9e926

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3539

## Problem Summary(Required) ：

Under ASAN, print log during the lock scope will cause submit_tasks to stall.
As a result, the TaskWorkerPool can not do other tasks any more. Move the log outside from the lock scope

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

File: be/src/agent/task_worker_pool.cpp [hunk 1]
```diff
@@ -222,11 +222,22 @@ void TaskWorkerPool::submit_tasks(std::vector<TAgentTaskRequest>* tasks) {
                 ++it;
             } else {
                 it = tasks->erase(it);
-                LOG(INFO) << "fail to register task. type=" << type_str << ", signature=" << signature;
+                failed_task_vec.push_back(*it);
             }
         }
     }
 
+    if (!failed_task_vec.empty()) {
```
Comment (sduzh) [inline be/src/agent/task_worker_pool.cpp:230]: Check the utilities defined in gutil/strings/join.h

File: be/src/agent/task_worker_pool.cpp [hunk 2]
```diff
@@ -241,12 +252,15 @@ void TaskWorkerPool::submit_tasks(std::vector<TAgentTaskRequest>* tasks) {
         }
         _worker_thread_condition_variable->notify_all();
     }
-    for (auto const& task : *tasks) {
-        int64_t signature = task.signature;
-
-        LOG(INFO) << "success to submit task. type=" << type_str << ", signature=" << signature
-                  << ", task_count_in_queue=" << _tasks.size();
+    std::stringstream ss;
+    for (int i = 0; i < (*tasks).size(); ++i) {
```
Comment (sduzh) [inline be/src/agent/task_worker_pool.cpp:256]: Check the utilities defined in gutil/strings/join.h

**Review by sduzh — APPROVED** [review]
