### PR TITLE
[BugFix] Set 'could_local_shuffle' correctly when decompose pipeline

### LINKED ISSUE #12563: [Bug] Bucket shuffle join output wrong results
### Steps to reproduce the behavior (Required)

tpcds_1g-q65

Specify the 4-th plan

**👀The problem can only be reproduced after #12437**

```sql
select  /*+ SET_VAR(cbo_use_nth_exec_plan = 4) */
	s_store_name,
	i_item_desc,
	sc.revenue,
	i_current_price,
	i_wholesale_cost,
	i_brand
 from store, item,
     (select ss_store_sk, avg(revenue) as ave
 	from
 	    (select  ss_store_sk, ss_item_sk,
 		     sum(ss_sales_price) as revenue
 		from store_sales, date_dim
 		where ss_sold_date_sk = d_date_sk and d_month_seq between 1176 and 1176+11
 		group by ss_store_sk, ss_item_sk) sa
 	group by ss_store_sk) sb,
     (select  ss_store_sk, ss_item_sk, sum(ss_sales_price) as revenue
 	from store_sales, date_dim
 	where ss_sold_date_sk = d_date_sk and d_month_seq between 1176 and 1176+11
 	group by ss_store_sk, ss_item_sk) sc
 where sb.ss_store_sk = sc.ss_store_sk and
       sc.revenue <= 0.1 * sb.ave and
       s_store_sk = sc.ss_store_sk and
       i_item_sk = sc.ss_item_sk
 order by s_store_name, i_item_desc
limit 100;
```

### Expected behavior (Required)

100rows

### Real behavior (Required)

* Non-pipeline engine yields right results(100rows)
* Pipeline engine yields wrong results(20rows)
* The plans of pipeline/non-pipeline engine are exactly the same

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 6d1787536 |
+-------------------+
```

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12563

## Problem Summary(Required) ：

When use the feature of plan enumeration, there may be two-stage aggregates within single fragment, which is of couse not the optimal plan, but the legal plan nevertheless. 

For example, see the below piece of fragment, these two-stage aggregates(node_id=6/7) are the left child of hashJoin node(node_id=10), whose join type is `BUCKET_SHUFFLE_JOIN`, the fe will arrange the tablet list for every parallelism, so along the execution path from scan(node_id=0) to join(node_id=10), no shuffle operators are allowed to interwaved. But obviously, the logical of `decompose_to_pipeline` not live up to the the distribution requirement.

```
|   10:HASH JOIN                                                                                          |
|   |  join op: INNER JOIN (BUCKET_SHUFFLE)                                                               |
|   |  colocate: false, reason:                                                                           |
|   |  equal join conjunct: 107: ss_item_sk = 30: i_item_sk                                               |
|   |                                                                                                     |
|   |----9:EXCHANGE                                                                                       |
|   |                                                                                                     |
|   7:AGGREGATE (merge finalize)                                                                          |
|   |  output: sum(156: sum)                                                                              |
|   |  group by: 112: ss_store_sk, 107: ss_item_sk                                                        |
|   |                                                                                                     |
|   6:AGGREGATE (update serialize)                                                                        |
|   |  STREAMING                                                                                          |
|   |  output: sum(118: ss_sales_price)                                                                   |
|   |  group by: 112: ss_store_sk, 107: ss_item_sk                                                        |
|   |                                                                                                     |
|   5:Project                                                                                             |
|   |  <slot 107> : 107: ss_item_sk                                                                       |
|   |  <slot 112> : 112: ss_store_sk                                                                      |
|   |  <slot 118> : 118: ss_sales_price                                                                   |
|   |                                                                                                     |
|   4:HASH JOIN                                                                                           |
|   |  join op: INNER JOIN (BROADCAST)                                                                    |
|   |  colocate: false, reason:                                                                           |
|   |  equal join conjunct: 105: ss_sold_date_sk = 128: d_date_sk                                         |
|   |                                                                                                     |
|   |----3:EXCHANGE                                                                                       |
|   |                                                                                                     |
|   0:OlapScanNode                                                                                        |
|      TABLE: store_sales                                                                                 |
|      PREAGGREGATION: ON                                                                                 |
|      PREDICATES: 112: ss_store_sk IS NOT NULL                                                           |
|      partitions=1/1                                                                                     |
|      rollup: store_sales                                                                                |
|      tabletRatio=192/192                                                                                |
|      tabletList=62912,62914,62916,62918,62920,62922,62924,62926,62928,62930 ...                         |
|      cardinality=2750370                                                                                |
|      avgRowSize=20.0                                                                                    |
|      numNodes=0
```

## Changelist

1. Pipeline cannot adjust the distribution if `need_local_shuffle = false`, so the better naming is `could_local_shuffle`
2. When decompose aggregate nodes to pipeline, the original pipeline need to split into two pipelines, if the `could_local_shuffle` of the original pipeline is false, then we must pass it on to the new created pipeline.
3. Fix some warnings reported by `tscancode` and `clang-tidy` tests

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
BE Build Success

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
BE Build Success

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by kangkaisen** [comment]
could we merge the 6,7 aggregate node to one aggregate node?

**Comment by liuyehcf** [comment]
> could we merge the 6,7 aggregate node to one aggregate node?

Maybe, perform some transofrmation rules after plan is generated, the process is a little strange. Since it is a legal plan, of couse not the optimal plan, be should give the right outputs anyway.

**Comment by liuyehcf** [comment]
run starrocks_admit_test

File: be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp [hunk 1]
```diff
@@ -188,13 +188,15 @@ std::vector<std::shared_ptr<pipeline::OperatorFactory>> AggregateBlockingNode::_
     size_t degree_of_parallelism = down_cast<SourceOperatorFactory*>(ops_with_sink[0].get())->degree_of_parallelism();
 
     auto should_cache = context->should_interpolate_cache_operator(ops_with_sink[0], id());
-    auto operators_generator = [this, should_cache, &context](bool post_cache) {
+    bool could_local_shuffle = context->could_local_shuffle(ops_with_sink);
```
Comment (satanson) [inline be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp:191]: when local shuffle is interpolated,  query cache can not work. so when should_cache is true, turn off could_local_shuffle

```cpp
 bool could_local_shuffle =!should_cache && context->could_local_shuffle(ops_with_sink);
```

File: be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp [hunk 2]
```diff
@@ -249,19 +249,20 @@ void AggregateStreamingNode::_output_chunk_from_hash_map(ChunkPtr* chunk) {
...
-            down_cast<SourceOperatorFactory*>(operators_with_sink[0].get())->degree_of_parallelism();
-
-    auto should_cache = context->should_interpolate_cache_operator(operators_with_sink[0], id());
-    if (!should_cache && _tnode.agg_node.__isset.interpolate_passthrough && _tnode.agg_node.interpolate_passthrough) {
-        operators_with_sink = context->maybe_interpolate_local_passthrough_exchange(
-                runtime_state(), operators_with_sink, degree_of_parallelism, true);
+    size_t degree_of_parallelism = down_cast<SourceOperatorFactory*>(ops_with_sink[0].get())->degree_of_parallelism();
+
+    auto should_cache = context->should_interpolate_cache_operator(ops_with_sink[0], id());
+    bool could_local_shuffle = context->could_local_shuffle(ops_with_sink);
```
Comment (satanson) [inline be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp:258]: same as above

File: be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp [hunk 3]
```diff
@@ -139,9 +139,9 @@ std::vector<std::shared_ptr<pipeline::OperatorFactory> > DistinctBlockingNode::d
     OpFactories ops_with_sink = _children[0]->decompose_to_pipeline(context);
 
     // shared by sink operator and source operator
-
     auto should_cache = context->should_interpolate_cache_operator(ops_with_sink[0], id());
-    auto operators_generator = [this, should_cache, &context](bool post_cache) {
+    bool could_local_shuffle = context->could_local_shuffle(ops_with_sink);
```
Comment (satanson) [inline be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp:143]: same as above

File: be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp [hunk 4]
```diff
@@ -215,7 +215,8 @@ std::vector<std::shared_ptr<pipeline::OperatorFactory> > DistinctStreamingNode::
     // and we may set other parallelism for source operator in many special cases
     size_t degree_of_parallelism = down_cast<SourceOperatorFactory*>(ops_with_sink[0].get())->degree_of_parallelism();
     auto should_cache = context->should_interpolate_cache_operator(ops_with_sink[0], id());
-    auto operators_generator = [this, should_cache, &context](bool post_cache) {
+    bool could_local_shuffle = context->could_local_shuffle(ops_with_sink);
```
Comment (satanson) [inline be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp:218]: same as above

File: be/src/exec/pipeline/scan/scan_operator.h [hunk 5]
```diff
@@ -166,8 +166,8 @@ class ScanOperatorFactory : public SourceOperatorFactory {
     Status prepare(RuntimeState* state) override;
     void close(RuntimeState* state) override;
 
-    bool need_local_shuffle() const override { return _need_local_shuffle; }
```
Comment (satanson) [inline be/src/exec/pipeline/scan/scan_operator.h:169]: why rename need_local_shuffle to could_local_shuffle, it sounds a little reluctant.

File: be/src/exec/pipeline/scan/scan_operator.h [hunk 6]
```diff
@@ -166,8 +166,8 @@ class ScanOperatorFactory : public SourceOperatorFactory {
...
-    void set_need_local_shuffle(bool need_local_shuffle) override { _need_local_shuffle = need_local_shuffle; }
+    bool could_local_shuffle() const override { return _could_local_shuffle; }
+    void set_could_local_shuffle(bool could_local_shuffle) override { _could_local_shuffle = could_local_shuffle; }
```
Comment (ZiheLiu) [inline be/src/exec/pipeline/scan/scan_operator.h:170]: These could be removed, since they are the same as the methods of `SourceOperator`.

File: be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/exec/vectorized/aggregate/aggregate_blocking_node.cpp:191]: Ok, I'll update

File: be/src/exec/pipeline/scan/scan_operator.h (hunk 5 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/scan/scan_operator.h:169]: `need_local_shuffle=false` actually means DO NOT add local shuffle, so `could` is better than `need`

File: be/src/exec/pipeline/scan/scan_operator.h (hunk 6 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/scan/scan_operator.h:170]: Yes, exactly. Updated

File: be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp (hunk 2 above)
Comment (liuyehcf) [reply be/src/exec/vectorized/aggregate/aggregate_streaming_node.cpp]: Done

File: be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp (hunk 3 above)
Comment (liuyehcf) [reply be/src/exec/vectorized/aggregate/distinct_blocking_node.cpp]: Done

File: be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp (hunk 4 above)
Comment (liuyehcf) [reply be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp]: Done

**Review by ZiheLiu — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]
