### PR TITLE
[Enhancement] Refactor lake compaction task cancel checker in BE to ensure it can stop asap

### LINKED ISSUE #54071: lake compaction scheduler might introduce too many tasks on BE/CN while sending task rpc partially succeed
### Steps to reproduce the behavior (Required)

kill some CN node while compaction scheduler was busy

### Real behavior (Required)

```sql
MySQL [(none)]> select BE_ID, count(*) from information_schema.be_cloud_native_compactions group by BE_ID;
+--------+----------+
| BE_ID  | count(*) |
+--------+----------+
| 926056 |       912 |
| 926049 |       711 |
| 926048 |       610 |
| 926052 |        699 |
| 926051 |       710 |
+--------+----------+
10 rows in set (0.02 sec)
```

```sh
2024-12-18 19:14:30.790+08:00 ERROR (COMPACTION_DISPATCH|102) [CompactionScheduler.startCompaction():324] Unable to validate object
java.lang.RuntimeException: Unable to validate object
	at com.baidu.jprotobuf.pbrpc.transport.ChannelPool.getChannel(ChannelPool.java:86) ~[jprotobuf-rpc-core-4.2.1.jar:?]
	at com.baidu.jprotobuf.pbrpc.transport.RpcChannel.getConnection(RpcChannel.java:73) ~[jprotobuf-rpc-core-4.2.1.jar:?]
	at com.baidu.jprotobuf.pbrpc.client.ProtobufRpcProxy.invoke(ProtobufRpcProxy.java:499) ~[jprotobuf-rpc-core-4.2.1.jar:?]
	at com.sun.proxy.$Proxy43.compact(Unknown Source) ~[?:?]
	at com.starrocks.lake.compaction.CompactionTask.sendRequest(CompactionTask.java:115) ~[starrocks-fe.jar:?]
	at com.starrocks.lake.compaction.CompactionScheduler.startCompaction(CompactionScheduler.java:319) ~[starrocks-fe.jar:?]
	at com.starrocks.lake.compaction.CompactionScheduler.schedule(CompactionScheduler.java:213) ~[starrocks-fe.jar:?]
	at com.starrocks.lake.compaction.CompactionScheduler.runOneCycle(CompactionScheduler.java:113) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
Caused by: java.util.NoSuchElementException: Unable to validate object
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:506) ~[commons-pool2-2.3.jar:2.3]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:363) ~[commons-pool2-2.3.jar:2.3]
	at com.baidu.jprotobuf.pbrpc.transport.ChannelPool.getChannel(ChannelPool.java:80) ~[jprotobuf-rpc-core-4.2.1.jar:?]
```

### StarRocks version (Required)
- 3.x.x

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

#54071

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: be/src/storage/lake/compaction_scheduler.cpp [hunk 1]
```diff
@@ -304,48 +302,57 @@ Status compaction_should_cancel(CompactionTaskContext* context) {
     RETURN_IF_ERROR(context->callback->has_error());
 
     int64_t check_interval_seconds = 60LL * config::lake_compaction_check_valid_interval_minutes;
-    if (!context->is_checker || check_interval_seconds <= 0) {
+    if (check_interval_seconds <= 0) {
         return Status::OK();
     }
 
     int64_t now = time(nullptr);
     int64_t last_check_time = context->callback->last_check_time();
```
[the remark this answers is not in the document]
Comment (wxl24life) [reply be/src/storage/lake/compaction_scheduler.cpp]: done

**Review by starrocks-xupeng — APPROVED** [review]

File: be/src/storage/lake/compaction_scheduler.cpp [hunk 2]
```diff
@@ -302,52 +351,7 @@ void CompactionScheduler::thread_task(int id) {
...
-            }
-        } else {
-            LOG(WARNING) << "fail to validate compaction transaction " << context->txn_id << " for tablet "
-                         << context->tablet_id << ", error: leader FE address not found";
-        }
-#endif
-        // update check time, if check rpc failed, wait next round
-        context->callback->set_last_check_time(now);
-    }
+    RETURN_IF_ERROR(context->callback->is_txn_still_valid());
```
Comment (kevincai) [inline be/src/storage/lake/compaction_scheduler.cpp:354]:
```suggestion
    return context->callback->is_txn_still_valid();
```

**Comment by kevincai** [comment]
This PR just ensure that the txn status can be checked even if the first tablet is done, but not necessary to fix the related issue.

**Comment by wxl24life** [comment]
> This PR just ensure that the txn status can be checked even if the first tablet is done, but not necessary to fix the related issue.

The bug issue is more relevant to #54908 。 This pr is an optimization to make txn checking can continue even it's not the first tablet

File: be/src/storage/lake/compaction_scheduler.cpp [hunk 3]
```diff
@@ -302,52 +351,7 @@ void CompactionScheduler::thread_task(int id) {
...
-            }
-        } else {
-            LOG(WARNING) << "fail to validate compaction transaction " << context->txn_id << " for tablet "
-                         << context->tablet_id << ", error: leader FE address not found";
-        }
-#endif
-        // update check time, if check rpc failed, wait next round
-        context->callback->set_last_check_time(now);
-    }
+    return context->callback->is_txn_still_valid();
```
Comment (kevincai) [inline be/src/storage/lake/compaction_scheduler.cpp:354]: there is one more `return` after this line . lol

Comment (wxl24life) [reply be/src/storage/lake/compaction_scheduler.cpp:354]: fixed

**Review by caneGuy — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
