### PR TITLE
[BugFix] Fix the bug of lose catalog 

### LINKED ISSUE #8997: Catalog is lost when randomly pause some fes
### Steps to reproduce the behavior (Required)
using jepsen test: workload is catalogs and nemesis is pause-fe

### Expected behavior (Required)
the operation should be safe.

### Real behavior (Required)
catalog (c2279) is lost
```
INFO [2022-07-21 08:38:13,021] jepsen test runner - jepsen.core {:perf
 {:latency-graph {:valid? true},
  :rate-graph {:valid? true},
  :valid? true},
 :clock-skew {:valid? true},
 :workload
 {:worst-stale (),
  :duplicated-count 0,
  :valid? false,
  :lost-count 1,
  :lost (2279),
  :stable-count 3128,
  :stale-count 0,
  :stale (),
  :never-read-count 56,
  :stable-latencies {0 0, 0.5 0, 0.95 0, 0.99 0, 1 0},
  :attempt-count 3185,
  :lost-latencies {0 767, 0.5 767, 0.95 767, 0.99 767, 1 767},
  :never-read
  (982
   1286
   1288
   1290
   1637
   1638
   1639
   1640
   1789
   2058
   2061
   2276
   2277
   2278
   2280
   2281
   2282
   2283
   2284
   2285
   2286
   2292
   2519
   2520
   2521
   2522
   2523
   2524
   2525
   2526
   2527
   2528
   2529
   2530
   2531
   2532
   2533
   2534
   2535
   2536
   2537
   2539
   2540
   2564
   2571
   2625
   2809
   2937
   3110
   3178
   3179
   3180
   3181
   3182
   3183
   3184),
  :duplicated {}},
 :valid? false}


Analysis invalid! (ﾉಥ益ಥ）ﾉ ┻━┻

```

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8997

## Problem Summary(Required) ：

We should make sure the catalog is copied to majority of fe (write log success) before the catalog can be seen.

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by stephen-shelby — DISMISSED** [review]
LGTM

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 1]
```diff
@@ -74,11 +74,11 @@ public synchronized void createCatalog(CreateCatalogStmt stmt) throws DdlExcepti
         writeLock();
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:74]: since it's a synchronized method, why still use lock here?

Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:74]: Good catch!

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 2]
```diff
@@ -74,11 +74,11 @@ public synchronized void createCatalog(CreateCatalogStmt stmt) throws DdlExcepti
...
         try {
             catalogs.put(catalogName, catalog);
+            GlobalStateMgr.getCurrentState().getEditLog().logCreateCatalog(catalog);
```
[the remark this answers is not in the document]
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:77]: I think it's intended to do so in order to pass the jepsen test, the lock is mainly to block the `catalogs` reader. Before the log is synced to follower, read on leader cannot see the newly added catalog either, so that jepsen test will see a consistent state on leader and follower.

But actually under current design, we can only support eventual consistency, no causal consistency mechanism is provided, so the situation described in the issue is normal under eventual consistency. So the key point is that using a write lock here to log metadata change to just pass a specific jepsen test case is unnecessary. We need a fundamental  change in order to support causality which i think need further discuss wether we should support it.

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java (hunk 1 above)
Comment (stephen-shelby) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:74]: Synchronized of create method is mainly used to ensure that create cannot be executed in multiple threads at the same time. In addition, I need to ensure that when reading catalogs, It can't be written at the same time, so `catalogExists(String catalogName)` added a read lock.

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:77]: Causality is not necessary in our system. But the dirty read should be avoid. Add a write lock is to avoid the dirty read.

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:74]: I think the concurrency can be controlled by one lock.

Comment (stephen-shelby) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:74]: Yes, Only use one rwlock may be enough , but if the object lock is removed currently, there will be inconsistencies when creating catalog concurrently, such as failure of MetadataMgr.addMetadata(). I think we need to adjust the scope of writeLock in `createCatalog`. I record a todo.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by stephen-shelby — DISMISSED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Review by padmejin — DISMISSED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (DorianZheng) [reply fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:78]: Actually I don't dirty read should be avoid in this case, since catalog is ok to be eventual consistency, doesn't have to be linear consistency

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|8|8|100.00%|[]|

**Comment by DorianZheng** [comment]
I see. We need to make sure modifying memory and log as a transaction
