### PR TITLE
BugFix: Fix the wrong checksum when exit be graceful

### LINKED ISSUE #4351: Wrong checksum may be generated after stop be with kill
### Steps to reproduce the behavior (Required)

https://github.com/StarRocks/starrocks/blob/e0c1bc54d67b0480af2d00eba878df0d4d01a909/be/src/storage/task/engine_checksum_task.cpp#L110-L130

if bg_worker_stopped is true, may be return return checksum

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### LINKED ISSUE #4373: The checksum is wrong when exit BE graceful
### Steps to reproduce the behavior (Required)
1. Start BE process
2. send checksum HTTP operation
3. kill $pid

### Expected behavior (Required)
The expected behavior is return error status instead of the wrong checksum.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by chaoyli**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4373

## Problem Summary(Required) ：

When exit BE graceful, the checksum will be wrong. Under this circumstance, the calculation should return error status instead of wrong checksum

### CODE REVIEW

File: be/src/storage/task/engine_clone_task.cpp [hunk 1]
```diff
@@ -359,7 +359,7 @@ Status EngineCloneTask::_download_files(DataDir* data_dir, const std::string& re
                                         const std::string& local_path) {
     bool bg_worker_stopped = ExecEnv::GetInstance()->storage_engine()->bg_worker_stopped();
     if (bg_worker_stopped) {
-        return Status::InternalError("Process is going to quit. The download should be stopped as soon as possible.");
+        return Status::InternalError("Process is going to quit. The download will be stopped.");
```
Comment (imay) [inline be/src/storage/task/engine_clone_task.cpp:362]:
```suggestion
        return Status::InternalError("Process is going to quit. The download will stop.");
```

File: be/src/storage/task/engine_clone_task.cpp [hunk 2]
```diff
@@ -566,7 +564,7 @@ Status EngineCloneTask::_clone_incremental_data(Tablet* tablet, const TabletMeta
                                                 int64_t committed_version) {
     bool bg_worker_stopped = ExecEnv::GetInstance()->storage_engine()->bg_worker_stopped();
     if (bg_worker_stopped) {
-        return Status::InternalError("Process is going to quit. The clone should be stopped as soon as possible.");
+        return Status::InternalError("Process is going to quit. The clone should will be stopped.");
```
Comment (imay) [inline be/src/storage/task/engine_clone_task.cpp:567]:
```suggestion
        return Status::InternalError("Process is going to quit. The clone task will stop.");
```

**Comment by trueeyu** [comment]
pay attention to the tsscancode

**Review by imay — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]
