### PR TITLE
[BugFix] fix main branch version rollback cannot be started

### LINKED ISSUE #12871: main branch version rollback to 2.3 fe start failed
### Steps to reproduce the behavior (Required)
1. main branch create hudi catalog
2. rollback to 2.3 version
3. restart fe

### Real behavior (Required)
image

### StarRocks version (Required)
MySQL [(none)]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.3.3 164799c     |
+-------------------+
1 row in set (5.17 sec)

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/12871

## Problem Summary(Required) ：

when main version create hudi catalog rollback to 2.3version , fe can not restart
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java [hunk 1]
```diff
@@ -24,6 +26,8 @@ public class ConnectorMgr {
     private final ConcurrentHashMap<String, ConnectorFactory> connectorFactories = new ConcurrentHashMap<>();
     private final ReadWriteLock connectorLock = new ReentrantReadWriteLock();
 
+    public static final List<String> SUPPORT_CONNECTOR_TYPE = Lists.newArrayList();
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/connector/ConnectorMgr.java:29]: nit: it's better to use set

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 2]
```diff
@@ -147,9 +147,10 @@ public void replayCreateCatalog(Catalog catalog) throws DdlException {
         if (Strings.isNullOrEmpty(type)) {
             throw new DdlException("Missing properties 'type'");
         }
-        if (!CreateCatalogStmt.SUPPORTED_CATALOG.contains(type)) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:150]: I think you need to remove the SUPPORTED_CATALOG and use SUPPORT_CONNECTOR_TYPE to instead of it.  So you don't have to change the code with the version.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java [hunk 3]
```diff
@@ -49,7 +50,7 @@ public Void visitCreateCatalogStatement(CreateCatalogStmt statement, ConnectCont
                 throw new SemanticException("'type' can not be null or empty");
             }
             statement.setCatalogType(catalogType);
-            if (!CreateCatalogStmt.SUPPORTED_CATALOG.contains(catalogType)) {
+            if (!ConnectorMgr.SUPPORT_CONNECTOR_TYPE.contains(catalogType)) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java:53]: import this static var

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 4]
```diff
@@ -147,9 +147,10 @@ public void replayCreateCatalog(Catalog catalog) throws DdlException {
...
-            // if catalog type is not supported, skip it
-            LOG.warn("Replay catalog encounter unknown catalog type: " + type);
+
+        // skip unsupport connector type
+        if (!connectorMgr.SUPPORT_CONNECTOR_TYPE.contains(type)) {
+            LOG.warn("Replay catalog [{}] encounter unknown catalog type [{}]", catalogName, type);
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:153]: error

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 5]
```diff
@@ -173,7 +174,10 @@ public void replayDropCatalog(DropCatalogLog log) {
         String catalogName = log.getCatalogName();
         readLock();
         try {
-            Preconditions.checkState(catalogs.containsKey(catalogName), "Catalog '%s' doesn't exist", catalogName);
+            if (!catalogs.containsKey(catalogName)) {
+                LOG.warn("Catalog [{}] doesn't exist", catalogName);
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:178]: ditto

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|3|5|60.00%|[179, 180]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CatalogAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/ConnectorMgr.java|2|2|100.00%|[]|

**Review by stephen-shelby — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java [hunk 6]
```diff
@@ -147,9 +148,10 @@ public void replayCreateCatalog(Catalog catalog) throws DdlException {
         if (Strings.isNullOrEmpty(type)) {
             throw new DdlException("Missing properties 'type'");
         }
-        if (!CreateCatalogStmt.SUPPORTED_CATALOG.contains(type)) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/server/CatalogMgr.java:150]: plz delete CreateCatalogStmt.SUPPORT_CATALOG

**Review by stephen-shelby — APPROVED** [review]

**Comment by stephen-shelby** [comment]
run starrocks_admit_test

**Comment by leoyy0316** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/CatalogMgr.java|3|5|60.00%|[179, 180]|
|:large_blue_circle:|com/starrocks/sql/analyzer/CatalogAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/connector/ConnectorMgr.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]
