### PR TITLE
[BugFix] fix resource leak when doing checkpoint

### LINKED ISSUE #55269: Hikari JDBC connection keeps growing
### Steps to reproduce the behavior (Required)

1. create a jdbc catalog
2. create a async mv on this jdbc catalog
3. keep doing checkpoint

And by following command, you can see hikari connection pool keeps growing

> jstack `jps | grep StarRocksFE | awk '{print $1}'` | grep Hikari

### Expected behavior (Required)

JDBC connection number should be stable

### Real behavior (Required)

JDBC connection number keeps growing

### StarRocks version (Required)

```
MySQL root@127.0.0.1:zya> select current_version();
+------------------------------------+
| current_version()                  |
+------------------------------------+
| ryanz-release-je-starrocks-1f73917 |
+------------------------------------+
1 row in set
Time: 0.013s
```

### PR DESCRIPTION
**Pull request by dirtysalt**
## Why I'm doing:

I've observed that jdbc pool connection keep growing on doing checkpoint

```
2025-01-18 09:35:11.157+08:00 INFO (leaderCheckpointer|348) [JDBCMetadata.createHikariDataSource():136] create hikari data source
java.lang.Throwable: null
        at com.starrocks.connector.jdbc.JDBCMetadata.createHikariDataSource(JDBCMetadata.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.jdbc.JDBCMetadata.<init>(JDBCMetadata.java:94) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.jdbc.JDBCMetadata.<init>(JDBCMetadata.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.jdbc.JDBCConnector.getMetadata(JDBCConnector.java:98) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.LazyConnector.getMetadata(LazyConnector.java:33) ~[starrocks-fe.jar:?]
        at com.starrocks.connector.CatalogConnector.getMetadata(CatalogConnector.java:43) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getOptionalMetadata(MetadataMgr.java:190) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getOptionalMetadata(MetadataMgr.java:164) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:496) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:526) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.getTableWithIdentifier(MetadataMgr.java:531) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.rule.transformation.materialization.MvUtils.getTableWithIdentifier(MvUtils.java:1410) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.onReloadImpl(MaterializedView.java:985) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.MaterializedView.onReload(MaterializedView.java:916) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.processMvRelatedMeta(GlobalStateMgr.java:1557) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.postLoadImage(GlobalStateMgr.java:1547) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1536) ~[starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.replayAndGenerateGlobalStateMgrImage(Checkpoint.java:208) ~[starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.createImage(Checkpoint.java:193) ~[starrocks-fe.jar:?]
        at com.starrocks.leader.Checkpoint.runAfterCatalogReady(Checkpoint.java:110) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
```

And I checked the code, it's because we use a `CHECKPOINT` instance to do checkpoint. And after doing checkpoint,  we just set is null instead of freeing resources.

```
    public static void destroyCheckpoint() {
        if (CHECKPOINT != null) {
            CHECKPOINT = null;
        }
    }
```

## What I'm doing:

Add a `shutdown` method into `GlobalStateMgr` class, and call this method when `destroyCheckpoint`

Fixes #55269

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -834,6 +834,7 @@ public void transferToNonLeader(FrontendNodeType newType) {
 
     public static void destroyCheckpoint() {
         if (CHECKPOINT != null) {
+            CHECKPOINT.shutdown();
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:837]: Better to add a try catch, because this is the key path of the checkpoint.

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java]: got it. fixed

**Review by gengjun-git — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by DorianZheng — APPROVED** [review]
