### PR TITLE
Bugfix: ChunkPB::is_nulls() is empty

### LINKED ISSUE #2537: Stream load error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE：
```
CREATE TABLE `duplicate_tbl` (
    `k1`  date,
    `k2`  datetime,
    `k3`  char(20),
    `k4`  varchar(20),
    `k5`  boolean,
    `k6`  tinyint,
    `k7`  smallint,
    `k8`  int,
    `k9`  bigint,
    `k10` largeint,
    `k11` float,
    `k12` double,
    `k13` decimal(27,9)
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
PROPERTIES ("replication_num" = "1");
CREATE TABLE `duplicate_par_tbl` (
    `k1` date,
    `k2` datetime,
    `k3` char(20),
    `k4` varchar(20),
    `k5` boolean,
    `k6` tinyint,
    `k7` smallint,
    `k8` int,
    `k9` bigint,
    `k10` largeint,
    `k11` float,
    `k12` double,
    `k13` decimal(27,9)
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
PARTITION BY RANGE(`k1`)
(
    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
)
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
PROPERTIES ("replication_num" = "1");
```

2. STREAM LOAD：
```
[tiannan@doris-sandbox04 StarRocksTest]$ curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cses/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1640829824176 http://***.***.***.***:8434/api/test_single_cte_1640829823725/duplicate_tbl/_stream_load
{
    "TxnId": 93091,
    "Label": "stream_load_1640829824176",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 65546,
    "NumberLoadedRows": 65546,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 8790855,
    "LoadTimeMs": 135,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 1,
    "ReadDataTimeMs": 7,
    "WriteDataTimeMs": 103,
    "CommitAndPublishTimeMs": 29
}[tiannan@doris-sandbox04 StarRocksTest]$ curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cses/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1640829824177 http://***.***.***.***:8434/api/test_single_cte_1640829823725/duplicate_par_tbl/_stream_load
{
    "TxnId": 93092,
    "Label": "stream_load_1640829824177",
    "Status": "Fail",
    "Message": "close index channel failed, load_id=5641f992-2316-e300-02da-546850420984",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 8790855,
    "LoadTimeMs": 98,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 1,
    "ReadDataTimeMs": 7,
    "WriteDataTimeMs": 96,
    "CommitAndPublishTimeMs": 0
}
```

### Expected behavior (Required)
stream load success

### Real behavior (Required)
close index channel failed

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER d4f698d |
+------------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by sduzh**
The PTabletWriterAddChunkRequest may have no chunks.
in this situation, the chunk deserializing step should be skipped.

### CODE REVIEW

File: be/src/runtime/tablets_channel.cpp [hunk 1]
```diff
@@ -135,13 +135,12 @@ void TabletsChannel::add_chunk(brpc::Controller* cntl, const PTabletWriterAddChu
     }
 
     auto context = std::move(res).value();
-    auto channel_size = _tablet_id_to_sorted_indexes.size();
+    auto channel_size = request.has_chunk() ? _tablet_id_to_sorted_indexes.size() : 0;
     auto tablet_ids = request.tablet_ids().data();
     auto tablet_ids_size = request.tablet_ids_size();
```
Comment (chaoyli) [inline be/src/runtime/tablets_channel.cpp:140]: Why not return instantly after finding the PTabletWriterAddChunkRequest have no chunks?

Comment (sduzh) [reply be/src/runtime/tablets_channel.cpp:140]: > Why not return instantly after finding the PTabletWriterAddChunkRequest have no chunks?

need to handle eos

**Review by chaoyli — APPROVED** [review]

**Review by wyb — APPROVED** [review]
