### PR TITLE
[BugFix] Fix bug that the Show command gives inconsistent results on leader and Follower

### LINKED ISSUE #9269: The Show command gives inconsistent results on leader and Follower
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9269 

## Problem Summary(Required) ：

The Show command gives inconsistent results on leader and Follower, this PR will fix the following problems
1. hbTime msg not sync from leader to follower
2. Fe polling be tablet stat add new prop: version_count
3. Mark pathHash and schema as expired attributes

### CODE REVIEW

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Replica.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java [hunk 1]
```diff
@@ -41,6 +41,9 @@ public class Replica implements Writable {
     private static final Logger LOG = LogManager.getLogger(Replica.class);
     public static final VersionComparator<Replica> VERSION_DESC_COMPARATOR = new VersionComparator<Replica>();
 
+    public final int deprecatedPropConstSchameHash = 0;
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java:44]:
```suggestion
    public static final int DEPRECATED_PROP_SCHEMA_HASH = 0;
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java [hunk 2]
```diff
@@ -132,7 +132,11 @@ private void updateTabletStat(Long beId, TTabletStatResult result) {
                 continue;
             }
             // TODO(cmy) no db lock protected. I think it is ok even we get wrong row num
-            replica.updateStat(entry.getValue().getData_size(), entry.getValue().getRow_num());
+            replica.updateStat(
+                    entry.getValue().getData_size(),
+                    entry.getValue().getRow_num(),
+                    entry.getValue().getVersion_count()
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java:138]: Will it work for BE of older versions?

File: fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java (hunk 1 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Replica.java]: done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 11 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MetadataViewer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/TabletStatMgr.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/proc/LocalTabletsProcDir.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Replica.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java (hunk 2 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java:138]: I've tested it and there's nothing wrong with it

**Review by chaoyli — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java (hunk 2 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java:138]: ok then.

**Review by padmejin — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java [hunk 3]
```diff
@@ -132,7 +132,11 @@ private void updateTabletStat(Long beId, TTabletStatResult result) {
                 continue;
             }
             // TODO(cmy) no db lock protected. I think it is ok even we get wrong row num
-            replica.updateStat(entry.getValue().getData_size(), entry.getValue().getRow_num());
+            replica.updateStat(
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/TabletStatMgr.java:135]: Since you have update the version count in the TabletStatMgr. Is it necessary to delete the code that update the version count in tablet report?

**Review by gengjun-git — APPROVED** [review]
