### PR TITLE
[BugFix] Fix FE dead lock when commit txn and alter routine load job concurrrently

### LINKED ISSUE #33618: FE dead lock
### Steps to reproduce the behavior (Required)
2 threads cause this dead lock:
1. commit txn thread：get db write lock firstly, then get job write lock
2. alter routine load job thread：get job write lock firstly, then got db read lock

jstack info as follows:
```
"thrift-server-pool-344475915":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007fc9ecb8f350> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
        at com.starrocks.load.routineload.RoutineLoadJob.writeLock(RoutineLoadJob.java:368)
        at com.starrocks.load.routineload.RoutineLoadJob.executeBeforeCheck(RoutineLoadJob.java:779)
        at com.starrocks.load.routineload.RoutineLoadJob.beforeCommitted(RoutineLoadJob.java:769)
        at com.starrocks.transaction.TransactionState.beforeStateTransform(TransactionState.java:444)
        at com.starrocks.transaction.DatabaseTransactionMgr.commitTransaction(DatabaseTransactionMgr.java:449)
        at com.starrocks.transaction.GlobalTransactionMgr.commitTransaction(GlobalTransactionMgr.java:360)
        at com.starrocks.transaction.GlobalTransactionMgr.commitAndPublishTransaction(GlobalTransactionMgr.java:438)
        at com.starrocks.service.FrontendServiceImpl.loadTxnCommitImpl(FrontendServiceImpl.java:1017)
        at com.starrocks.service.FrontendServiceImpl.loadTxnCommit(FrontendServiceImpl.java:976)
        at com.starrocks.thrift.FrontendService$Processor$loadTxnCommit.getResult(FrontendService.java:2656)
        at com.starrocks.thrift.FrontendService$Processor$loadTxnCommit.getResult(FrontendService.java:2636)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
"thrift-server-pool-344475410":
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00007fc9ac5cd598> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
        at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
        at com.starrocks.catalog.Database.readLock(Database.java:154)
        at com.starrocks.load.routineload.RoutineLoadJob.getTableName(RoutineLoadJob.java:409)
        at com.starrocks.load.routineload.RoutineLoadJob.mergeLoadDescToOriginStatement(RoutineLoadJob.java:1628)
        at com.starrocks.load.routineload.RoutineLoadJob.modifyJob(RoutineLoadJob.java:1583)
        at com.starrocks.load.routineload.KafkaRoutineLoadJob.modifyJob(KafkaRoutineLoadJob.java:577)
        at com.starrocks.load.routineload.RoutineLoadManager.alterRoutineLoadJob(RoutineLoadManager.java:621)
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitAlterRoutineLoadStatement$22(DDLStmtExecutor.java:371)
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor$$Lambda$1401/260454893.apply(Unknown Source)
        at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:99)
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitAlterRoutineLoadStatement(DDLStmtExecutor.java:370)
        at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitAlterRoutineLoadStatement(DDLStmtExecutor.java:127)
        at com.starrocks.sql.ast.AlterRoutineLoadStmt.accept(AlterRoutineLoadStmt.java:198)
        at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:113)
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1213)
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:518)
        at com.starrocks.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:684)
        at com.starrocks.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:860)
        at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:2506)
        at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:2486)
        at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
        at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
        at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Expected behavior (Required)
No dead lock, alter routine load cmd works normally.

### Real behavior (Required)
Alter routine load cmd can't exit normally.

### StarRocks version (Required)
 - latest version

### PR DESCRIPTION
**Pull request by chen9t**
Fixes #33618

2 threads cause this dead lock:

commit txn thread：get db write lock firstly, then get job write lock
alter routine load job thread：get job write lock firstly, then got db read lock

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java [hunk 1]
```diff
@@ -516,6 +518,27 @@ public String getTableName() throws MetaNotFoundException {
         }
     }
 
+    // This method should be used by caller with other locks, like modifyJob()
+    public String getTableNameWithTimeout() throws UserException {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:522]: 1. tryGetTableName is better name?
2. This way is a workaround? The better way is to refactor the code logic to avoid deadlock rather than handling it so tricky.
We need to find out when the deadlock will happen, and fix it.

Comment (chen9t) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:522]: The deadlock happens when a routine load commit txn comes, meanwhile, alter routine load cmd was executed:

commit txn thread：get db write lock firstly, then get job write lock
alter routine load job thread：get job write lock firstly, then got db read lock

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java [hunk 2]
```diff
@@ -516,6 +518,27 @@ public String getTableName() throws MetaNotFoundException {
...
+        Database database = GlobalStateMgr.getCurrentState().getDb(dbId);
+        if (database == null) {
+            throw new MetaNotFoundException("Database " + dbId + "has been deleted");
+        }
+        if (!database.tryReadLock(GET_DB_LOCK_TIMEOUT_MS, TimeUnit.MILLISECONDS)) {
+            throw new UserException("get database read lock timeout, database="
+                    + database.getFullName() + ", timeoutMillis=" + GET_DB_LOCK_TIMEOUT_MS);
+        }
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:530]: There is no need to hold db lock here. database.getTable is thread safe

**Comment by nshangyiming** [comment]
@chen9t  you need to add sign-off, git commit -s --amend, git push -f

**Comment by nshangyiming** [comment]
@chen9t  Could you add ut to cover your code, the coverage ratio should reach 80% for added code.

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 1 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:522]: > alter routine load job thread：get job write lock firstly, then got db read lock

can you try to adjust the lock order, get db read lock first?

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 2 above)
Comment (chen9t) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:530]: It's true, I missed the code [here](https://github.com/StarRocks/starrocks/blob/main/fe/fe-core/src/main/java/com/starrocks/catalog/Database.java#L146).

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 1 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:522]: @chen9t , @rickif  is the owner of routine load, he will help you to find a thorough solution.

Comment (chen9t) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: Remove read lock to fix this issue, please check it again. Thank you!

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 2 above)
Comment (chen9t) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: Remove read lock to fix this issue, please check it again. Thank you!

**Review by nshangyiming — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 2 above)
Comment (chen9t) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: > image approved, but you need to fix the coverage issue before it's merged.

No code added, just removed the lock acquire code in the same function. Any suggestions?

Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: like setting up 2 threads in ut to simulate the dead lock situation and check no dead lock?

**Review by gengjun-git — APPROVED** [review]
