### PR TITLE
[BugFix] Account finalization cost to scheduler

### LINKED ISSUE #16432: Finalization of large query make small query execute slowly
### Steps to reproduce the behavior (Required)
When a large query is finalized, especially when it is cancelled and enable resource group, the other small query will wait a long time.

1. Create resource group `rg1` and `rg2`.

```sql
-- set small mem_limit to make large query failed by OOM and cancelled in runtime.
create resource group rg1 to ( user='rg1' ) with ('cpu_core_limit' = '6', 'mem_limit' = '50%');
create resource group rg2 to ( user='rg2' ) with ('cpu_core_limit' = '6', 'mem_limit' = '80%');

create user rg1@'%' identified by '123456';
create user rg2@'%' identified by '123456';

grant select_priv on *.* to rg1@'%';
grant select_priv on *.* to rg2@'%';

```

2. `rg1` executes large queries and `rg2` executes `select 1`.
```
mysqlslap --concurrency=8  \
           --iterations=1  \
           --number-of-queries="100000"      \
           --query="tpcds/query04.sql"   \
           --delimiter=";" -h <host>  -P <port> -u rg1 -p123456  --create-schema=tpcds_100g

mysqlslap --concurrency=1  \
           --iterations=100  \
           --number-of-queries="1"      \
           --query="select 1 from dual"   \
           --delimiter=";" -h <host>  -P <port> -u rg2/rg1 -p123456  --create-schema=tpcds_100g
```

### Expected behavior (Required)
The latency of `select 1` is smaller than 1s.

### Real behavior (Required)
Sometimes, `select 1` costs 20~40s, especially  when the large query tpcds/query04.sql is failed by OOM and being cancelled.

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16432

## Problem Summary(Required) ：

When a large query is finalized, especially when it is cancelled and resource group is enabled, the other small query will wait a long time.

The reason is that, finalization cost of driver isn't accounted in `driver_queue`. For exmaple, there is a group `rg1` executing a large query and finalizing and a group `rg2` executing a small query like `select 1`. If `rg1.vruntime` < `rg2.vruntime`, then all the drivers of this large query will be finalized before executing `select 1` in `rg2.

Therefore, account the finalization cost time to `driver_queue`.

## Test case
rg1 executes large queries and rg2 executes select 1.
```
# would fail by OOM
mysqlslap --concurrency=8  \
           --iterations=1  \
           --number-of-queries="100000"      \
           --query="tpcds/query04.sql"   \
           --delimiter=";" -h <host>  -P <port> -u rg1 -p123456  --create-schema=tpcds_100g

mysqlslap --concurrency=1  \
           --iterations=100  \
           --number-of-queries="1"      \
           --query="select 1 from dual"   \
           --delimiter=";" -h <host>  -P <port> -u rg2 -p123456  --create-schema=tpcds_100g
```

Before this PR, enabling resource group costs 20s and disabling resource group costs 4s.
After this PR, enabling and disabling costs 0.3s.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Review by satanson — APPROVED** [review]

File: be/src/exec/pipeline/pipeline_driver.cpp [hunk 1]
```diff
@@ -398,6 +394,19 @@ void PipelineDriver::_close_operators(RuntimeState* runtime_state) {
 }
 
 void PipelineDriver::finalize(RuntimeState* runtime_state, DriverState state) {
+    int64_t time_spent = 0;
```
Comment (LiShuMing) [inline be/src/exec/pipeline/pipeline_driver.cpp:397]: Why `finalize` will take a long time? is that another problem?

Comment (ZiheLiu) [reply be/src/exec/pipeline/pipeline_driver.cpp:397]: The `finalize` phase need to do some release jobs of fragment context and query context for the last time count down.
This costs about 0.1~08s, if there is 200 fragments of a large query, then it will cost 20s.

But it is indeed too heavy, maybe we could optimize this later.

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3
