### PR TITLE
[BugFix] Fix case-when return collection type bugs

### LINKED ISSUE #59921: [BUG][SQLancer] array column append crash
```
main RELEASE (build 1bcefb5)
query_id:01977697-2ff9-7bfc-9051-d11b38107507, fragment_instance:01977697-2ff9-7bfc-9051-d11b3810750a
*** Aborted at 1750041309 (unix time) try "date -d @1750041309" if you are using GNU date ***
PC: @          0x4ce5559 starrocks::ArrayColumn::append(starrocks::Column const&, unsigned long, unsigned long)
*** SIGSEGV (@0x0) received by PID 2751 (TID 0x2b7412258700) LWP(2982) from PID 0; stack trace: ***
    @     0x2b73f262e20b __pthread_once_slow
    @          0xbe16e54 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x2b73f2637630 (/usr/lib64/libpthread-2.17.so+0xf62f)
    @          0x4ce5559 starrocks::ArrayColumn::append(starrocks::Column const&, unsigned long, unsigned long)
    @          0x4d84489 starrocks::NullableColumn::append(starrocks::Column const&, unsigned long, unsigned long)
    @          0x6a9e3b2 starrocks::VectorizedCaseExpr<(starrocks::LogicalType)24, (starrocks::LogicalType)19>::evaluate_no_case(starrocks::ExprContext*, starrocks::Chunk*)
    @          0x6a9e72d starrocks::VectorizedCaseExpr<(starrocks::LogicalType)24, (starrocks::LogicalType)19>::evaluate_checked(starrocks::ExprContext*, starrocks::Chunk*)
    @          0x65788db starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::Chunk*, unsigned char*)
    @          0x7360218 starrocks::VectorizedFunctionCallExpr::evaluate_checked(starrocks::ExprContext*, starrocks::Chunk*)
    @          0x73ca053 starrocks::VectorizedIsNullPredicate::evaluate_checked(starrocks::ExprContext*, starrocks::Chunk*)
    @          0x65788db starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::Chunk*, unsigned char*)
    @          0x6578c1b starrocks::ExprContext::evaluate(starrocks::Chunk*, unsigned char*)
    @          0x4de8a92 starrocks::eager_prune_eval_conjuncts(std::vector<starrocks::ExprContext*, std::allocator<starrocks::ExprContext*> > const&, starrocks::Chunk*)
    @          0x4dea7ff starrocks::ExecNode::eval_conjuncts(std::vector<starrocks::ExprContext*, std::allocator<starrocks::ExprContext*> > const&, starrocks::Chunk*, std::shared_ptr<std::vector<unsigned char, starrocks::ColumnAllocator<unsigned char> > >*, bool)
    @          0x57f977d starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage(starrocks::RuntimeState*, starrocks::Chunk*)
    @          0x57f9f9a starrocks::pipeline::OlapChunkSource::_read_chunk(starrocks::RuntimeState*, std::shared_ptr<starrocks::Chunk>*)
    @          0x57ebd90 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking(starrocks::RuntimeState*, unsigned long, starrocks::workgroup::WorkGroup const*)
    @          0x52f6e6b auto starrocks::pipeline::ScanOperator::_trigger_next_scan(starrocks::RuntimeState*, int)::{lambda(auto:1&)#1}::operator()<starrocks::workgroup::YieldContext>(starrocks::workgroup::YieldContext&) const [clone .isra.0]
    @          0x5423a69 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x458591f starrocks::ThreadPool::dispatch_thread()
    @          0x457cef0 starrocks::Thread::supervise_thread(void*)
    @     0x2b73f262fea5 start_thread
    @     0x2b73f4b00b0d __clone
```

### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS w71;
CREATE DATABASE w71;
USE w71;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NOT NULL ,c_0_1 BIGINT NULL ,c_0_2 DATE NULL ) DUPLICATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL64(2,1) NULL ,c_1_1 DECIMAL128(34,13) NULL ,c_1_2 DATETIME NULL ,c_1_3 DECIMAL64(8,3) NULL ,c_1_4 DECIMAL(9,9) NOT NULL ,c_1_5 DECIMAL64(9,0) NULL ,c_1_6 BOOLEAN NOT NULL ,c_1_7 BIGINT NULL ,c_1_8 BIGINT NOT NULL ,c_1_9 DATETIME NOT NULL ,c_1_10 DECIMAL32(3,3) NOT NULL ,c_1_11 DECIMAL32(4,0) NULL ,c_1_12 DECIMAL(8,5) NOT NULL ,c_1_13 BOOLEAN NOT NULL ) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11,c_1_12) DISTRIBUTED BY HASH (c_1_0,c_1_2,c_1_4,c_1_8,c_1_1,c_1_5,c_1_6) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 DECIMAL128(8,0) NULL ,c_2_1 BOOLEAN NOT NULL ,c_2_2 LARGEINT NOT NULL ,c_2_3 DECIMAL64(13,0) NOT NULL ,c_2_4 DECIMAL128(12,9) NULL ,c_2_5 DECIMAL32(4,2) NULL ,c_2_6 VARCHAR(11) NOT NULL ,c_2_7 INT NULL ,c_2_8 DATE NULL ,c_2_9 DECIMAL32(6,2) NOT NULL ,c_2_10 DATE NULL ,c_2_11 VARCHAR(1) NOT NULL ,c_2_12 DECIMAL32(8,1) NULL ,c_2_13 BIGINT NULL ,c_2_14 INT NOT NULL ,c_2_15 BIGINT NOT NULL ,c_2_16 DECIMAL(8,3) NULL ) DUPLICATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11,c_2_12,c_2_13) DISTRIBUTED BY HASH (c_2_6,c_2_4,c_2_12,c_2_3) properties("replication_num"="1") ;
INSERT INTO t2 VALUES (59735109, false, -136561871, 2453646345905, 1.13E-7, 0.02, "", 29, "1970-01-01", 10.84, "1970-01-01", "", NULL, 642164333, 18, 1107397595, 57.190), (NULL, true, 905832105, 1995345390505, 2.07E-7, 0.44, "SYZ", 20, "1970-01-01", 82.93, "1970-01-01", "", 982261.4, -136561871, 2, -1496687048, NULL);
INSERT INTO t2 VALUES (70644312, false, -843953411, 6096569351457, 6.24E-7, 0.94, "FLs", 4, "1970-01-01", 20.57, "1970-01-01", "", 867762.5, 1505025683, 26, 1258215771, 27.230), (87971105, false, -466117783, 6823026380247, 4.29E-7, 0.30, "H35ubq", 25, "1970-01-01", 42.80, "1970-01-01", "", NULL, -615413137, 12, 1258215771, 7.890), (35294784, true, -1671296153, 7636147310195, 4.3E-8, 0.88, "l8w7J", NULL, "1970-01-01", 44.45, "1970-01-01", "", 289501.8, -1496687048, 15, -1496687048, 15.289);
INSERT INTO t1 VALUES (0.5, 11751191.5156981875790, "1970-01-01 08:00:00", 64.686, 0E-9, 230760250, true, 642164333, -1907043045, "1970-01-01 08:00:00", 0.001, 2419, 0.00594, true);
INSERT INTO t0 VALUES ("1970-01-01", 1943005856, "1970-01-01"), ("1970-01-01", -2126133800, "1970-01-01");
INSERT INTO t1 VALUES (0.0, 45811500.6321245652831, "1970-01-01 08:00:00", 70.990, 7E-9, 963767023, false, 960711459, -1596964085, "1970-01-01 08:00:00", 0.004, 3747, 0.00258, true);
INSERT INTO t2 VALUES (17695642, true, 788004753, 6663305519409, 3.13E-7, 0.67, "d", 20, "1970-01-01", 75.72, "1970-01-01", "", 387273.4, -44572784, 2, -970534881, 31.706);
INSERT INTO t2 VALUES (4427980, true, 1505025683, 5984471342732, 7.19E-7, 0.07, "mFqlsjyM7", NULL, NULL, 36.29, "1970-01-01", "", 898309.8, NULL, 12, 1753853522, 98.805), (97282244, false, 1258215771, 4355218038658, 2.58E-7, 0.69, "6E", 30, "1970-01-01", 60.56, "1970-01-01", "", 175445.9, 470508522, 17, -466117783, 39.898), (60299866, true, -661445109, 6934634533046, 9.34E-7, 0.28, "3x", 6, "1970-01-01", 9.02, "1970-01-01", "", 209833.7, 1753853522, 2, -114930972, NULL);
INSERT INTO t2 VALUES (85331573, true, -1327671624, 7580271458250, 9.23E-7, 0.04, "", 4, NULL, 57.66, "1970-01-01", "", 559349.9, -2126133800, 30, -1433645762, 51.459);
INSERT INTO t2 VALUES (54818083, false, -996101458, 6066732460592, 4.57E-7, 0.80, "RVopUi", 8, "1970-01-01", 49.87, "1970-01-01", "", 501223.7, 1106217301, 28, -433246617, 18.098);
INSERT INTO t0 VALUES ("1970-01-01", NULL, "1970-01-01"), ("1970-01-01", 1206523278, "1970-01-01"), ("1970-01-01", -1671296153, "1970-01-01");
INSERT INTO t1 VALUES (0.8, 35379699.3261744397003, "1970-01-01 08:00:00", 85.395, 4E-9, 453126746, false, -1524774563, -1596964085, "1970-01-01 08:00:00", 0.008, 3895, 0.00055, true);
INSERT INTO t0 VALUES ("1970-01-01", 1777718970, "1970-01-01"), ("1970-01-01", NULL, "1970-01-01"), ("1970-01-01", -1, "1970-01-01");
INSERT INTO t0 VALUES ("1970-01-01", -114930972, "1970-01-01"), ("1970-01-01", 1505025683, "1970-01-01"), ("1970-01-01", 1172229723, NULL);
INSERT INTO t1 VALUES (0.2, 32263401.5108748683691, "1970-01-01 08:00:00", 60.831, 2E-9, NULL, false, -2126133800, 788645893, "1970-01-01 08:00:00", 0.005, NULL, 0.00193, true), (0.2, 5097468.1957908978940, "1970-01-01 08:00:00", 76.075, 1E-9, 290393308, true, -1360434654, -1062100175, "1970-01-01 08:00:00", 0.008, 7741, 0.00081, true);
INSERT INTO t2 VALUES (22211184, true, 232680300, 4634628784555, NULL, 0.35, "CW", 1, NULL, 37.72, "1970-01-01", "", 719826.1, -1671296153, 26, -1225558158, 56.951), (10298809, false, 321566056, 1297694441390, 4E-9, 0.13, "V", 11, "1970-01-01", 53.86, "1970-01-01", "", NULL, 1528903138, 31, -1225558158, 37.078);
INSERT INTO t1 VALUES (0.6, 96512.9671031637711, "1970-01-01 08:00:00", 39.979, 8E-9, 598857893, false, 1652849507, -122692297, "1970-01-01 08:00:00", 0.008, 9160, 0.00711, false), (0.0, 43917837.5845967954093, "1970-01-01 08:00:00", NULL, 4E-9, 137049929, true, -1469171337, 1638682840, "1970-01-01 08:00:00", 0.001, 7054, 0.00060, true);
INSERT INTO t2 VALUES (57446118, false, 1172229723, 6823872884587, 5.30E-7, 0.87, "", 28, "1970-01-01", 59.25, "1970-01-01", "", 337442.2, 1206523278, 6, -1453286264, 30.894), (58625413, false, 2074248207, 5026396378963, 5.30E-7, NULL, "OAChW2z", 31, "1970-01-01", 53.66, "1970-01-01", "", 245969.4, -1832554567, 23, 2074097350, 62.280), (74687133, true, -466117783, 9917293436202, 5.34E-7, 0.37, "XEOo", 26, "1970-01-01", 84.90, "1970-01-01", "", 532700.2, -1566961684, 20, -40441962, 55.136), (1690506, true, 878078523, 1339999225743, 4.96E-7, 0.82, "", 17, "1970-01-01", 84.39, "1970-01-01", "", 930085.3, 679490011, 24, -1737397894, 94.696);
```

query:
```
SELECT t2.c_2_0 FROM t2, t0 WHERE ARRAY_CONTAINS_ALL([], CASE WHEN t2.c_2_1 THEN [map{1941097382: false,-1948382910: true,637104627: true,-992200745: false,679490011: true,829563307: true,-665423668: false,NULL: false}, map{-1433645762: true,1889335002: true,-1596964085: false}, map{-103943736: true,2074248207: true,1022324532: false,282588653: false,-1284040728: true,-992671205: true,-1906007493: true,764349941: true}, map{225818675: true,1089613292: true,-1028100310: false,1652849507: true}, map{-2033193097: false,1380483846: false,-407829057: false,NULL: NULL,790930565: false,-138898970: false,1865436429: true}, map{}, map{NULL: true,1081557622: false,-735682692: false,-128731392: true,-1453286264: true,-1737397894: false,-474499132: false,1258215771: false}, map{}, map{}] WHEN t2.c_2_1 THEN [NULL, map{NULL: true,-375636634: true,-1016499131: true,-1699137067: true,-1459750723: true,-1183071913: true,1109882502: true,671784302: true}, NULL, map{}, map{1645689740: NULL,1951807197: false,1505025683: true,514973128: true,2064297579: true,-777453213: false,1753853522: false}, map{507622772: true,1772060817: false,606132774: false,553109838: NULL,684294362: true}] END) UNION ALL SELECT t2.c_2_0 FROM t2, t0 WHERE (NOT (ARRAY_CONTAINS_ALL([], CASE WHEN t2.c_2_1 THEN [map{1941097382: false,-1948382910: true,637104627: true,-992200745: false,679490011: true,829563307: true,-665423668: false,NULL: false}, map{-1433645762: true,1889335002: true,-1596964085: false}, map{-103943736: true,2074248207: true,1022324532: false,282588653: false,-1284040728: true,-992671205: true,-1906007493: true,764349941: true}, map{225818675: true,1089613292: true,-1028100310: false,1652849507: true}, map{-2033193097: false,1380483846: false,-407829057: false,NULL: NULL,790930565: false,-138898970: false,1865436429: true}, map{}, map{NULL: true,1081557622: false,-735682692: false,-128731392: true,-1453286264: true,-1737397894: false,-474499132: false,1258215771: false}, map{}, map{}] WHEN t2.c_2_1 THEN [NULL, map{NULL: true,-375636634: true,-1016499131: true,-1699137067: true,-1459750723: true,-1183071913: true,1109882502: true,671784302: true}, NULL, map{}, map{1645689740: NULL,1951807197: false,1505025683: true,514973128: true,2064297579: true,-777453213: false,1753853522: false}, map{507622772: true,1772060817: false,606132774: false,553109838: NULL,684294362: true}] END) )) UNION ALL SELECT t2.c_2_0 FROM t2, t0 WHERE ((ARRAY_CONTAINS_ALL([], CASE WHEN t2.c_2_1 THEN [map{1941097382: false,-1948382910: true,637104627: true,-992200745: false,679490011: true,829563307: true,-665423668: false,NULL: false}, map{-1433645762: true,1889335002: true,-1596964085: false}, map{-103943736: true,2074248207: true,1022324532: false,282588653: false,-1284040728: true,-992671205: true,-1906007493: true,764349941: true}, map{225818675: true,1089613292: true,-1028100310: false,1652849507: true}, map{-2033193097: false,1380483846: false,-407829057: false,NULL: NULL,790930565: false,-138898970: false,1865436429: true}, map{}, map{NULL: true,1081557622: false,-735682692: false,-128731392: true,-1453286264: true,-1737397894: false,-474499132: false,1258215771: false}, map{}, map{}] WHEN t2.c_2_1 THEN [NULL, map{NULL: true,-375636634: true,-1016499131: true,-1699137067: true,-1459750723: true,-1183071913: true,1109882502: true,671784302: true}, NULL, map{}, map{1645689740: NULL,1951807197: false,1505025683: true,514973128: true,2064297579: true,-777453213: false,1753853522: false}, map{507622772: true,1772060817: false,606132774: false,553109838: NULL,684294362: true}] END) ) IS NULL);
```

### StarRocks version (Required)
main RELEASE (build 1bcefb5)

### PR DESCRIPTION
**Pull request by Seaven**
## What I'm doing:

Fixes https://github.com/StarRocks/starrocks/issues/59921

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

File: be/src/storage/lake/tablet_manager.cpp [hunk 1]
```diff
@@ -288,18 +288,13 @@ Status TabletManager::put_aggregate_tablet_metadata(std::map<int64_t, TabletMeta
...
     for (auto& [tablet_id, meta] : tablet_metas) {
-        if (schema_id != meta.schema().id()) {
-            return Status::InternalError("tablet schema not the same");
-        }
-        for (const auto& [ver, schema] : meta.historical_schemas()) {
-            unique_schemas.emplace(ver, schema);
+        (*shared_meta.mutable_tablet_to_schema())[tablet_id] = meta.schema().id();
+        unique_schemas.emplace(meta.schema().id(), meta.schema());
+        for (const auto& [schema_id, schema] : meta.historical_schemas()) {
+            unique_schemas.emplace(schema_id, schema);
```
Comment (alvin-phoenix-ai) [inline be/src/storage/lake/tablet_manager.cpp]: can you make these modifications in a separated PR?

**Review by alvin-phoenix-ai — APPROVED** [review]

**Review by satanson — APPROVED** [review]
