### PR TITLE
[BugFix] Fix transactionState deadlock between auto partition and new publish

### LINKED ISSUE #44975: TransactionState deadlock between auto partition and new publish
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

Found one Java-level deadlock:
=============================
"thrift-server-pool-4657350":
  waiting for ownable synchronizer 0x00007f325e119210, (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync),
  which is held by "thrift-server-pool-4657183"
"thrift-server-pool-4657183":
  waiting for ownable synchronizer 0x00007f2ea9823bf0, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
  which is held by "thrift-server-pool-4655690"
"thrift-server-pool-4655690":
  waiting to lock monitor 0x00007f2ca0130e88 (object 0x00007f333499cea0, a com.starrocks.transaction.TransactionState),
  which is held by "thrift-server-pool-4652583"
"thrift-server-pool-4652583":
  waiting for ownable synchronizer 0x00007f2ea9823bf0, (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync),
  which is held by "thrift-server-pool-4655690"

Java stack information for the threads listed above:
===================================================
"thrift-server-pool-4657350":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f325e119210> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at com.starrocks.load.loadv2.LoadMgr.readLock(LoadMgr.java:691)
	at com.starrocks.load.loadv2.LoadMgr.getLoadJobsByDb(LoadMgr.java:572)
	at com.starrocks.load.loadv2.LoadMgr.getLoadJobInfosByDb(LoadMgr.java:532)
	at com.starrocks.qe.ShowExecutor.handleShowLoad(ShowExecutor.java:1448)
	at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:319)
	at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1499)
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:652)
	at com.starrocks.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:813)
	at com.starrocks.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:1275)
	at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:4216)
	at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:4196)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"thrift-server-pool-4657183":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f2ea9823bf0> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at com.starrocks.common.util.QueryableReentrantReadWriteLock.sharedLock(QueryableReentrantReadWriteLock.java:43)
	at com.starrocks.catalog.Database.readLock(Database.java:182)
	at com.starrocks.load.loadv2.BulkLoadJob.checkAndSetDataSourceInfo(BulkLoadJob.java:171)
	at com.starrocks.load.loadv2.BulkLoadJob.fromLoadStmt(BulkLoadJob.java:162)
	at com.starrocks.load.loadv2.LoadMgr.createLoadJobFromStmt(LoadMgr.java:141)
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.lambda$visitLoadStatement$16(DDLStmtExecutor.java:365)
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor$$Lambda$1816/556260629.apply(Unknown Source)
	at com.starrocks.common.ErrorReport.wrapWithRuntimeException(ErrorReport.java:112)
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitLoadStatement(DDLStmtExecutor.java:355)
	at com.starrocks.qe.DDLStmtExecutor$StmtExecutorVisitor.visitLoadStatement(DDLStmtExecutor.java:158)
	at com.starrocks.sql.ast.LoadStmt.accept(LoadStmt.java:353)
	at com.starrocks.qe.DDLStmtExecutor.execute(DDLStmtExecutor.java:144)
	at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1573)
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:650)
	at com.starrocks.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:813)
	at com.starrocks.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:1275)
	at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:4216)
	at com.starrocks.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:4196)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"thrift-server-pool-4655690":
	at com.starrocks.transaction.TransactionState.prepareFinishChecker(TransactionState.java:1041)
	- waiting to lock <0x00007f333499cea0> (a com.starrocks.transaction.TransactionState)
	at com.starrocks.transaction.DatabaseTransactionMgr.commitTransaction(DatabaseTransactionMgr.java:459)
	at com.starrocks.transaction.GlobalTransactionMgr.commitTransaction(GlobalTransactionMgr.java:393)
	at com.starrocks.transaction.GlobalTransactionMgr.commitTransactionUnderDatabaseWLock(GlobalTransactionMgr.java:552)
	at com.starrocks.transaction.GlobalTransactionMgr.retryCommitOnRateLimitExceeded(GlobalTransactionMgr.java:518)
	at com.starrocks.transaction.GlobalTransactionMgr.commitAndPublishTransaction(GlobalTransactionMgr.java:486)
	at com.starrocks.service.FrontendServiceImpl.loadTxnCommitImpl(FrontendServiceImpl.java:1457)
	at com.starrocks.service.FrontendServiceImpl.loadTxnCommit(FrontendServiceImpl.java:1414)
	at com.starrocks.thrift.FrontendService$Processor$loadTxnCommit.getResult(FrontendService.java:4441)
	at com.starrocks.thrift.FrontendService$Processor$loadTxnCommit.getResult(FrontendService.java:4421)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"thrift-server-pool-4652583":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00007f2ea9823bf0> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at com.starrocks.common.util.QueryableReentrantReadWriteLock.sharedLock(QueryableReentrantReadWriteLock.java:43)
	at com.starrocks.catalog.Database.readLock(Database.java:182)
	at com.starrocks.service.FrontendServiceImpl.createPartitionProcess(FrontendServiceImpl.java:2388)
	- locked <0x00007f333499cea0> (a com.starrocks.transaction.TransactionState)
	at com.starrocks.service.FrontendServiceImpl.createPartition(FrontendServiceImpl.java:2252)
	at com.starrocks.thrift.FrontendService$Processor$createPartition.getResult(FrontendService.java:4716)
	at com.starrocks.thrift.FrontendService$Processor$createPartition.getResult(FrontendService.java:4696)
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## Why I'm doing:
This problem is mainly caused by two PRs. In #38598, in order to ensure that multiple be senders do not call the FE create partition interface concurrently, synchronized (txnState) is used. After successfully obtaining it, apply for db lock. #10099 is just the opposite
## What I'm doing:
Delete synchronized (txnState) in new publish, prepareFinishChecker in commit txn, and unify them into publish new.
Fixes #44975

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by decster — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -454,7 +454,6 @@ public VisibleStateWaiter commitPreparedTransaction(long transactionId) throws U
                 // after state transform
                 transactionState.afterStateTransform(TransactionStatus.COMMITTED, txnOperated, callback, null);
             }
-            transactionState.prepareFinishChecker(db);
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:457]: is this safe, when will `checkCanFinish` be called in old publish mechnism?

Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:457]: checkCanFinish only used in new publish

**Review by nshangyiming — APPROVED** [review]
