### PR TITLE
[BugFix] lz4 encode/decode

### LINKED ISSUE #63628: lz4 compress/decompress error can not be perceived
### Steps to reproduce the behavior (Required)
N.A.

### Expected behavior (Required)
LZ4_compress_fast and LZ4_decompress_safe will return int. Negative value will be returned when something goes wrong. (According to  https://github.com/lz4/lz4/blob/release/lib/lz4.h)

### Real behavior (Required)
The returned value will be assigned to uint64_t, which will lose the information of the negative value.

### StarRocks version (Required)
3.3.7

### PR DESCRIPTION
**Pull request by IHEII**
## Why I'm doing:
Fix #63628 

## What I'm doing:

Fix #63628 

According to https://github.com/lz4/lz4/blob/release/lib/lz4.h.
```
LZ4LIB_API int LZ4_compress_fast (const char* src, char* dst, int srcSize, int dstCapacity, int acceleration);
LZ4LIB_API int LZ4_decompress_safe (const char* src, char* dst, int compressedSize, int dstCapacity);
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

---

> [!NOTE]
> Updates LZ4 encode/decode to use inferred size types and adds detailed error messages with sizes in `be/src/serde/column_array_serde.cpp`.
> 
> - **Serde (LZ4 string compression/decompression)** in `be/src/serde/column_array_serde.cpp`:
>   - Use `auto` for `encode_size`/`decode_size` from `LZ4_compress_fast`/`LZ4_decompress_safe`.
>   - Replace generic errors with detailed messages including raw/compressed sizes.
>   - Keep existing bounds and size-equality checks unchanged.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9d52afbed48fb1e3761e4883b97134e3e15f9320. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/serde/column_array_serde.cpp [hunk 1]
```diff
@@ -118,7 +118,7 @@ uint8_t* encode_string_lz4(const void* data, size_t size, uint8_t* buff, int enc
         throw std::runtime_error(
                 fmt::format("The input size for compression should be less than {}", LZ4_MAX_INPUT_SIZE));
     }
-    uint64_t encode_size =
+    int64_t encode_size =
```
Comment (alvin-phoenix-ai) [inline be/src/serde/column_array_serde.cpp]: Could you use `auto` instead?

Comment (IHEII) [reply be/src/serde/column_array_serde.cpp]: Fixed :)

File: be/src/serde/column_array_serde.cpp [hunk 2]
```diff
@@ -135,7 +135,7 @@ uint8_t* encode_string_lz4(const void* data, size_t size, uint8_t* buff, int enc
 const uint8_t* decode_string_lz4(const uint8_t* buff, void* target, size_t size) {
     uint64_t encode_size = 0;
     buff = read_little_endian_64(buff, &encode_size);
-    uint64_t decode_size = LZ4_decompress_safe(reinterpret_cast<const char*>(buff), reinterpret_cast<char*>(target),
+    auto decode_size = LZ4_decompress_safe(reinterpret_cast<const char*>(buff), reinterpret_cast<char*>(target),
```
Comment (kevincai) [inline be/src/serde/column_array_serde.cpp:139]: 1. need fix the clang-format error
2. better bring the return code when throw the std::runtime_error in below line 141.

File: be/src/serde/column_array_serde.cpp [hunk 3]
```diff
@@ -118,7 +118,7 @@ uint8_t* encode_string_lz4(const void* data, size_t size, uint8_t* buff, int enc
         throw std::runtime_error(
                 fmt::format("The input size for compression should be less than {}", LZ4_MAX_INPUT_SIZE));
     }
-    uint64_t encode_size =
+    auto encode_size =
```
Comment (kevincai) [inline be/src/serde/column_array_serde.cpp:121]: include the return value in the runtime_error thrown in line 125.

**Review by kevincai — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]

**Comment by alvin-phoenix-ai** [comment]
@mergify rebase
