### PR TITLE
[BugFix]Fix hive column convert array containing unknown type

### LINKED ISSUE #10111: [Bug]Fe Hive Column convert failed
### Steps to reproduce the behavior (Required)
1. CREATE hive table with unsupported type
2. Query hive table

### Expected behavior (Required)
```
mysql> use old_hive.default;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> desc hive_all_type;
+-----------------+---------------+------+-------+---------+-------+
| Field           | Type          | Null | Key   | Default | Extra |
+-----------------+---------------+------+-------+---------+-------+
| col_tinyint     | TINYINT       | Yes  | false | NULL    |       |
| col_smallint    | SMALLINT      | Yes  | false | NULL    |       |
| col_int         | INT           | Yes  | false | NULL    |       |
| col_bigint      | BIGINT        | Yes  | false | NULL    |       |
| col_varchar     | VARCHAR(10)   | Yes  | false | NULL    |       |
| col_char        | CHAR(10)      | Yes  | false | NULL    |       |
| col_timestamp   | DATETIME      | Yes  | false | NULL    |       |
| col_decimals    | DECIMAL(10,0) | Yes  | false | NULL    |       |
| col_uniontype   | UNKNOWN_TYPE  | Yes  | false | NULL    |       |
| col_arrayint    | ARRAY<INT>    | Yes  | false | NULL    |       |
| col_arraystruct | UNKNOWN_TYPE  | Yes  | false | NULL    |       |
| col_binary      | UNKNOWN_TYPE  | Yes  | false | NULL    |       |
| col_map         | UNKNOWN_TYPE  | Yes  | false | NULL    |       |
| col_struct      | UNKNOWN_TYPE  | Yes  | false | NULL    |       |
+-----------------+---------------+------+-------+---------+-------+
14 rows in set (0.01 sec)

mysql> select * from hive_all_type;
ERROR 1064 (HY000): Datatype of external table column [col_uniontype, col_arraystruct, col_binary, col_map, col_struct] is not supported!
mysql> 
```

### Real behavior (Required)
1. Stack over flow

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/10111

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by adzfolc** [comment]
Reminder:need to backport to branch-2.4

**Comment by adzfolc** [comment]
run starrocks_fe_unittest

**Comment by adzfolc** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|3|4|75.00%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|

**Review by stephen-shelby — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java [hunk 1]
```diff
@@ -165,6 +168,10 @@ public static int[] getPrecisionAndScale(String typeStr) throws DdlException {
 
     // Array string like "Array<Array<int>>"
     public static Type convertToArrayType(String typeStr) throws DdlException {
+        if (!HIVE_UNSUPPORTED_TYPES.stream().filter(typeStr.toUpperCase()::contains).collect(Collectors.toList())
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java:171]: If typeStr is "array<brray<binary>>", it will convert to array<unknow>. but we need to convert it to unknown.

Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java:171]: If typeStr is "array<brray<int>>", it will convert to array<known>. but we need to convert it to unknown.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|6|7|85.71%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java (hunk 1 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/hive/Utils.java:171]: > If typeStr is `array<brray<int>>`, it will convert to `array<known>`. but we need to convert it to unknown.

It has been fixed, and add UT cover this case.

**Review by stephen-shelby — DISMISSED** [review]

**Comment by adzfolc** [comment]
@stephen-shelby @DorianZheng @dirtysalt  PTAL

**Review by caneGuy — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|6|7|85.71%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|

**Review by caneGuy — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by dirtysalt** [comment]
run starrocks_admit_test

**Comment by adzfolc** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|6|7|85.71%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|6|7|85.71%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 11 (90.91%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/Utils.java|6|7|85.71%|[173]|
|:large_blue_circle:|com/starrocks/external/HiveMetaStoreTableUtils.java|4|4|100.00%|[]|
