### PR TITLE
[BugFix] Fix the HttpServer not wait the threads finished.

### LINKED ISSUE #6738: BE crash in sqlancer_02_asan env
### Steps to reproduce the behavior (Required)
be.out
```
==195923==ERROR: AddressSanitizer: heap-use-after-free on address 0x619000216788 at pc 0x000006e914aa bp 0x7fa836874010 sp 0x7fa836874008
READ of size 1 at 0x619000216788 thread T509
    #0 0x6e914a9 in starrocks::PathTrie<starrocks::HttpHandler*>::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) /root/starrocks/be/src/util/path_trie.hpp:270
    #1 0x6e90a46 in starrocks::PathTrie<starrocks::HttpHandler*>::retrieve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, starrocks::HttpHandler**, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >*) /root/starrocks/be/src/util/path_trie.hpp:248
    #2 0x6e8aec6 in starrocks::EvHttpServer::_find_handler(starrocks::HttpRequest*) /root/starrocks/be/src/http/ev_http_server.cpp:262
    #3 0x6e8a9e9 in starrocks::EvHttpServer::on_header(evhttp_request*) /root/starrocks/be/src/http/ev_http_server.cpp:228
    #4 0x6e878a7 in on_header /root/starrocks/be/src/http/ev_http_server.cpp:67
    #5 0xb340369 in evhttp_read_header /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/http.c:2279
    #6 0xb342d22 in bufferevent_trigger_nolock_ /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/bufferevent-internal.h:411
    #7 0xb342d22 in bufferevent_readcb /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/bufferevent_sock.c:219
    #8 0xb32f301 in event_persist_closure /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/event.c:1608
    #9 0xb32f301 in event_process_active_single_queue /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/event.c:1667
    #10 0xb32fa3e in event_process_active /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/event.c:1768
    #11 0xb32fa3e in event_base_loop /var/local/thirdparty/src/libevent-24236aed01798303745470e6c498bf606e88724a/event.c:1991
    #12 0x6e88aaf in operator() /root/starrocks/be/src/http/ev_http_server.cpp:122
    #13 0x6e8fbbf in __invoke_impl<void, starrocks::EvHttpServer::start()::<lambda()> > /usr/include/c++/10.3.0/bits/invoke.h:60
    #14 0x6e8fb66 in __invoke<starrocks::EvHttpServer::start()::<lambda()> > /usr/include/c++/10.3.0/bits/invoke.h:95
    #15 0x6e8faf7 in _M_invoke<0> /usr/include/c++/10.3.0/thread:264
    #16 0x6e8fa47 in operator() /usr/include/c++/10.3.0/thread:271
    #17 0x6e8f583 in _M_run /usr/include/c++/10.3.0/thread:215
    #18 0xce9c2af in execute_native_thread_routine ../../../.././libstdc++-v3/src/c++11/thread.cc:80
    #19 0x7fa930678e64 in start_thread (/lib64/libpthread.so.0+0x7e64)
    #20 0x7fa92fc9388c in clone (/lib64/libc.so.6+0xfe88c)

0x619000216788 is located 264 bytes inside of 1000-byte region [0x619000216680,0x619000216a68)
freed by thread T0 here:
    #0 0x4a529d7 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x6450796 in std::default_delete<starrocks::EvHttpServer>::operator()(starrocks::EvHttpServer*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #2 0x6450a73 in std::__uniq_ptr_impl<starrocks::EvHttpServer, std::default_delete<starrocks::EvHttpServer> >::reset(starrocks::EvHttpServer*) (/home/disk1/sr/sqlancer_branch_asan/be/lib/starrocks_be+0x6450a73)
    #3 0x644ea84 in std::unique_ptr<starrocks::EvHttpServer, std::default_delete<starrocks::EvHttpServer> >::reset(starrocks::EvHttpServer*) (/home/disk1/sr/sqlancer_branch_asan/be/lib/starrocks_be+0x644ea84)
    #4 0x64478b8 in starrocks::HttpServiceBE::~HttpServiceBE() /root/starrocks/be/src/service/service_be/http_service.cpp:57
    #5 0x643dced in std::default_delete<starrocks::HttpServiceBE>::operator()(starrocks::HttpServiceBE*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #6 0x643ddb7 in std::__uniq_ptr_impl<starrocks::HttpServiceBE, std::default_delete<starrocks::HttpServiceBE> >::reset(starrocks::HttpServiceBE*) /usr/include/c++/10.3.0/bits/unique_ptr.h:182
    #7 0x643d8d4 in std::unique_ptr<starrocks::HttpServiceBE, std::default_delete<starrocks::HttpServiceBE> >::reset(starrocks::HttpServiceBE*) (/home/disk1/sr/sqlancer_branch_asan/be/lib/starrocks_be+0x643d8d4)
    #8 0x643b771 in start_be() /root/starrocks/be/src/service/service_be/starrocks_be.cpp:68
    #9 0x4a9279f in main /root/starrocks/be/src/service/starrocks_main.cpp:282
    #10 0x7fa92fbb7504 in __libc_start_main (/lib64/libc.so.6+0x22504)

previously allocated by thread T0 here:
    #0 0x4a51bb7 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x64477ca in starrocks::HttpServiceBE::HttpServiceBE(starrocks::ExecEnv*, int, int) /root/starrocks/be/src/service/service_be/http_service.cpp:53
    #2 0x643d6fb in std::_MakeUniq<starrocks::HttpServiceBE>::__single_object std::make_unique<starrocks::HttpServiceBE, starrocks::ExecEnv*&, int&, int&>(starrocks::ExecEnv*&, int&, int&) (/home/disk1/sr/sqlancer_branch_asan/be/lib/starrocks_be+0x643d6fb)
    #3 0x643b4ff in start_be() /root/starrocks/be/src/service/service_be/starrocks_be.cpp:55
    #4 0x4a9279f in main /root/starrocks/be/src/service/starrocks_main.cpp:282
    #5 0x7fa92fbb7504 in __libc_start_main (/lib64/libc.so.6+0x22504)

Thread T509 created by T0 here:
    #0 0x49fb8b2 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0xce9c374 in __gthread_create /var/local/gcc/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663
    #2 0xce9c374 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ../../../.././libstdc++-v3/src/c++11/thread.cc:135
    #3 0x6e8be04 in construct<std::thread, starrocks::EvHttpServer::start()::<lambda()>&> /usr/include/c++/10.3.0/ext/new_allocator.h:150
    #4 0x6e8b719 in construct<std::thread, starrocks::EvHttpServer::start()::<lambda()>&> /usr/include/c++/10.3.0/bits/alloc_traits.h:512
    #5 0x6e8b3fb in emplace_back<starrocks::EvHttpServer::start()::<lambda()>&> /usr/include/c++/10.3.0/bits/vector.tcc:115
    #6 0x6e88efc in starrocks::EvHttpServer::start() /root/starrocks/be/src/http/ev_http_server.cpp:124
    #7 0x644b8ff in starrocks::HttpServiceBE::start() /root/starrocks/be/src/service/service_be/http_service.cpp:193
    #8 0x643b55b in start_be() /root/starrocks/be/src/service/service_be/starrocks_be.cpp:56
    #9 0x4a9279f in main /root/starrocks/be/src/service/starrocks_main.cpp:282
    #10 0x7fa92fbb7504 in __libc_start_main (/lib64/libc.so.6+0x22504)

SUMMARY: AddressSanitizer: heap-use-after-free /root/starrocks/be/src/util/path_trie.hpp:270 in starrocks::PathTrie<starrocks::HttpHandler*>::split(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*)
Shadow bytes around the buggy address:
  0x0c328003aca0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c328003acb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328003acc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328003acd0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ace0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c328003acf0: fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ad00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ad10: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ad20: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ad30: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328003ad40: fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==195923==ABORTING
*** Aborted at 1653935967 (unix time) try "date -d @1653935967" if you are using GNU date ***
```

### Real behavior (Required)
BE crash in sqlancer_02_asan env

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN 39a4802 |
+-------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by chaoyli**
Upon exit gracefully, the HttpServer should guarantee all the threads
are finished. Otherwise, the memory leak will be thrown. The pull request fixes the bug.

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6738

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

File: be/src/http/ev_http_server.cpp [hunk 1]
```diff
@@ -123,12 +123,16 @@ Status EvHttpServer::start() {
...
     }
     return Status::OK();
 }
 
 void EvHttpServer::stop() {
+    for (auto& thread : _workers) {
+        if (thread.joinable()) {
+            thread.join();
+        }
+    }
```
Comment (imay) [inline be/src/http/ev_http_server.cpp:135]: seems should call these codes in `EvHttpServer::join()`

**Comment by chaoyli** [comment]
run starrocks_clang-format

File: be/src/http/ev_http_server.cpp [hunk 2]
```diff
@@ -99,40 +100,69 @@ Status EvHttpServer::start() {
...
+            struct event_base* base = event_base_new();
             if (base == nullptr) {
                 LOG(WARNING) << "Couldn't create an event_base.";
                 return;
             }
+            _event_bases.push_back(base);
+
             /* Create a new evhttp object to handle requests. */
-            std::shared_ptr<evhttp> http(evhttp_new(base.get()), [](evhttp* http) { evhttp_free(http); });
+            struct evhttp* http = evhttp_new(base);
```
Comment (imay) [inline be/src/http/ev_http_server.cpp:111]: this is not pushed to _https

**Review by trueeyu — APPROVED** [review]

**Review by imay — APPROVED** [review]
