### PR TITLE
[BugFix] PartialUpdate rowset rewrite may not work with tablet clone

### LINKED ISSUE #4880: PartialUpdate rowset rewrite may not work with tablet clone
### Steps to reproduce the behavior (Required)
Tablet clone assumes rowset file is immutable, while during rowset apply for partial update, rowset file may be changed.

### StarRocks version (Required)
main

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4880

## Problem Summary(Required) ：

Tablet clone assumes rowset file is immutable, while during rowset apply for a partial update, rowset file may be changed. It may raise a bug.

Actually, this bug is only related to the PrimaryKey table. If the tablet is a PrimaryKey table, we should dump the snapshot meta-file first and then link rowset files to the snapshot directory

When doing a partial update, if dump the snapshot meta-file first, there are four conditions as below:
1. rowset status is committed in meta, rowset file is a partial rowset
2. rowset status is committed in meta, rowset file is a partial rowset when we link files, and rowset applies success after link files.
3. rowset status is committed in meta, rowset file is full rowset
4. rowset status is applied in meta, rowset file is full rowset

case1 and case4 are normal cases, we don't need to do an additional process

case2 is almost the same as case1. In normal cases, partial rowset files will be deleted after rowset apply. But we do a hard link of partial rowset files, so the partial rowset files will not be deleted until snapshot dir is deleted. So the src BE will download the partial rowset files.

case3 is a bit tricky. If the rowset status is committed in meta but the rowset file is full rowset. The src be will download the full rowset file and apply it again. But we handle this contingency in partial rowset apply, because if BE crash before updating meta, we also need to apply this rowset again after BE restart.

### CODE REVIEW

File: be/src/storage/snapshot_manager.cpp [hunk 1]
```diff
@@ -329,19 +329,28 @@ StatusOr<std::string> SnapshotManager::snapshot_incremental(const TabletSharedPt
     (void)FileUtils::remove_all(snapshot_dir);
     RETURN_IF_ERROR(FileUtils::create_dir(snapshot_dir));
 
-    // 3. Link files to snapshot directory.
+    // If tablet is PrimaryKey table, we should dump snapshot meta file first and then link files
+    // to snapshot directory
+    // The reason is ablet clone assumes rowset file is immutable, but during rowset apply for partial update,
```
Comment (decster) [inline be/src/storage/snapshot_manager.cpp:334]: **t**ablet

File: be/src/storage/snapshot_manager.cpp [hunk 2]
```diff
@@ -329,19 +329,28 @@ StatusOr<std::string> SnapshotManager::snapshot_incremental(const TabletSharedPt
...
+    // rowset file may be changed.
+    // When doing partial update, if dump snapshot meta file first, there are four conditions as below
+    //  1. rowset status is committed in meta, rowset file is partial rowset
+    //  2. rowset status is committed in meta, rowset file is partial rowset, but rowset is apply success after link file
```
Comment (decster) [inline be/src/storage/snapshot_manager.cpp:338]: `but rowset is apply success after link file` what does this mean

Comment (sevev) [reply be/src/storage/snapshot_manager.cpp]: > `but rowset is apply success after link file` what does this mean

When we dump snapshot, `patial rowset` is committed but not apply, so we will do a hard link for partial rowset files. But when src BE start download snapshot, the`partial rowset` is applied.

This case should be the same with case1 theoretically. The partial rowset files will not be delete until snaoshot dir is deleted because of the hard link.  But to be on the safe side, it is differentiated from case1 and a test for case2 is added

File: be/src/storage/snapshot_manager.cpp (hunk 1 above)
Comment (sevev) [reply be/src/storage/snapshot_manager.cpp:334]: > **t**ablet

done， changed

**Review by decster — DISMISSED** [review]

File: be/src/storage/snapshot_manager.cpp [hunk 3]
```diff
@@ -329,19 +329,30 @@ StatusOr<std::string> SnapshotManager::snapshot_incremental(const TabletSharedPt
...
+    // rowset file may be changed.
+    // When doing partial update, if dump snapshot meta file first, there are four conditions as below
+    //  1. rowset status is committed in meta, rowset file is partial rowset
+    //  2. rowset status is committed in meta, rowset file is `partial rowset` when we link files, and rowset apply
+    //     success after link files.
+    //  3. rowset status is committed in meta, rowset file is full rowset
+    //  4. rowset status is applied in meta, rowset file is full rowset
+    // case1 and case4 is normal case, we don't need do additional process.
+    // case2 is almost the same as case1. In normal case, partial rowset files will be delete after rowset apply. But
+    // we do a hard link of partial rowset files, so the partial rowset files will not be delete until snaoshot dir is
```
[the remark this answers is not in the document]
Comment (sevev) [reply be/src/storage/snapshot_manager.cpp]: > spell error `snapshot`

done, changed in https://github.com/StarRocks/starrocks/pull/5488/commits/06f5d040f9941ac94ddd57b15ce6515f5d3191a6

File: be/src/storage/snapshot_manager.cpp [hunk 4]
```diff
@@ -329,19 +329,30 @@ StatusOr<std::string> SnapshotManager::snapshot_incremental(const TabletSharedPt
     (void)FileUtils::remove_all(snapshot_dir);
     RETURN_IF_ERROR(FileUtils::create_dir(snapshot_dir));
 
-    // 3. Link files to snapshot directory.
+    // If tablet is PrimaryKey tablet, we should dump snapshot meta file first and then link files
+    // to snapshot directory
+    // The reason is ablet clone assumes rowset file is immutable, but during rowset apply for partial update,
```
[the remark this answers is not in the document]
Comment (sevev) [reply be/src/storage/snapshot_manager.cpp]: > spell error `tablet`

done, changed in https://github.com/StarRocks/starrocks/pull/5488/commits/06f5d040f9941ac94ddd57b15ce6515f5d3191a6

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by decster** [comment]
Tablet clone assumes rowset file is immutable, while during rowset apply for a partial update, rowset file may be changed. It may raise a bug.

Actually, this bug is only related to the PrimaryKey table. If the tablet is a PrimaryKey table, we should dump the snapshot meta-file first and then link rowset files to the snapshot directory

When doing a partial update, if dump the snapshot meta-file first, there are four conditions as below:

rowset status is committed in meta, rowset file is a partial rowset
rowset status is committed in meta, rowset file is a partial rowset when we link files, and rowset applies success after link files.
rowset status is committed in meta, rowset file is full rowset
rowset status is applied in meta, rowset file is full rowset
case1 and case4 are normal cases, we don't need to do an additional process

case2 is almost the same as case1. In normal cases, partial rowset files will be deleted after rowset apply. But we do a hard link of partial rowset files, so the partial rowset files will not be deleted until snapshot dir is deleted. So the src BE will download the partial rowset files.

case3 is a bit tricky. If the rowset status is committed in meta but the rowset file is full rowset. The src be will download the full rowset file and apply it again. But we handle this contingency in partial rowset apply, because if BE crash before updating meta, we also need to apply this rowset again after BE restart.
