### PR TITLE
[BugFix] fix mv rewrite for join predicate pushdown

### LINKED ISSUE #27633: MV rewrite for join predicate pushdown case
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE pushdown_t1 (
    `c0` string,
    `c1` string,
    `c2` string,
    `c3` string,
    `c4` string,
    `c5` string ,
    `c6` string,
    `c7`  date
) 
DUPLICATE KEY (c0)
DISTRIBUTED BY HASH(c0)
properties('replication_num' = '1');

CREATE TABLE `pushdown_t2` (
  `c0` varchar(65533) NULL ,
  `c1` varchar(65533) NULL ,
  `c2` varchar(65533) NULL ,
  `c3` varchar(65533) NULL ,
  `c4` varchar(65533) NULL ,
  `c5` varchar(65533) NULL ,
  `c6` varchar(65533) NULL ,
  `c7` varchar(65533) NULL ,
  `c8` varchar(65533) NULL ,
  `c9` varchar(65533) NULL ,
  `c10` varchar(65533) NULL ,
  `c11` date NULL ,
  `c12` datetime NULL ,
  `c13` varchar(65533) NULL ,
  `c14` varchar(65533) NULL ,
  `c15` varchar(65533) NULL ,
  `c16` varchar(65533) NULL ,
  `c17` varchar(65533) NULL ,
  `c18` double NULL ,
  `c19` double NULL ,
  `c20` double NULL ,
  `c21` double NULL ,
  `c22` double NULL ,
  `c23` double NULL ,
  `c24` double NULL ,
  `c25` double NULL ,
  `c26` double NULL ,
  `c27` double NULL ,
  `c28` double NULL ,
  `c29` double NULL 
) ENGINE=OLAP
DUPLICATE KEY (c0)
DISTRIBUTED BY HASH(c0)
PROPERTIES ( "replication_num" = "1");

CREATE MATERIALIZED VIEW `_pushdown_predicate_join_mv1`  
DISTRIBUTED BY HASH(c12) BUCKETS 18 
REFRESH MANUAL 
PROPERTIES ( "replication_num" = "1", "storage_medium" = "HDD") 
AS
SELECT t1.c0, t1.c1, t2.c7, t2.c12
FROM
    ( SELECT `c0`, `c7`, `c12` FROM `pushdown_t2`) t2
    LEFT OUTER JOIN 
    ( SELECT c0, c1, c7 FROM pushdown_t1 ) t1
    ON `t2`.`c0` = `t1`.`c0`
    AND date(t2.`c12`) = `t1`.`c7`
   ;


```

**query:** 
```sql
SELECT t1.c0, t1.c1, t2.c7, t2.c12
FROM
    ( SELECT `c0`, `c7`, `c12` FROM `pushdown_t2`) t2
    LEFT OUTER JOIN 
    ( SELECT c0, c1, c7 FROM pushdown_t1 ) t1
    ON `t2`.`c0` = `t1`.`c0`
    AND date(t2.`c12`) = `t1`.`c7`
   ;
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by murphyatwork**
Fixes #27633

1. The join predicate contains `    AND date(t2.`c12`) = t1.c7 `
2. The `date(...)` will be push down under the join operator, and join predicates become `ColumnRef(date) = t1.c7`
3. The `ColumnRef(date)` should be compared with `equivalent` instead of equals, which means comparing with name instead of id 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 1]
```diff
@@ -189,6 +190,7 @@ boolean computeCompatibility(OptExpression queryExpr, OptExpression mvExpr) {
         LogicalOperator queryOp = (LogicalOperator) queryExpr.getOp();
         LogicalOperator mvOp = (LogicalOperator) mvExpr.getOp();
         if (!queryOp.getOpType().equals(mvOp.getOpType())) {
+            logMVPrepare("join type is different {} != {}", queryOp.getOpType(), mvOp.getOpType());
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:193]: we can add it into trace info? to better debug? and here it's rewrite phase, so use `logMVRewrite` directly?

**Review by ABingHuang — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 36 / 44 (81.82%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/PredicateOperator.java|8|11|72.73%|[93, 96, 100]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|7|9|77.78%|[168, 172]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|12|14|85.71%|[232, 1817]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|7|8|87.50%|[144]|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptimizerTraceUtil.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 36 / 44 (81.82%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/PredicateOperator.java|8|11|72.73%|[93, 96, 100]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|7|9|77.78%|[168, 172]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|12|14|85.71%|[232, 1817]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|7|8|87.50%|[144]|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptimizerTraceUtil.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 33 / 43 (76.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptimizerTraceUtil.java|0|2|00.00%|[137, 138]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/PredicateOperator.java|8|11|72.73%|[93, 96, 100]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|7|9|77.78%|[168, 172]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|11|13|84.62%|[232, 1817]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|7|8|87.50%|[144]|

**Review by LiShuMing — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
