### PR TITLE
[BugFix] storage volume delete should not be allowed if active snapshot present

### LINKED ISSUE #62172: NullPointerException   because "sv" is null
### Steps to reproduce the behavior (Required)
1. CREATE STORAGE VOLUME backup TYPE=S3 LOCATIONS=("s3://starrocks-bak/data") PROPERTIES("aws.s3.endpoint" = "http://xxx:9000",  "aws.s3.access_key" = "xxx",  "aws.s3.secret_key" = "xxx");
2. ADMIN SET AUTOMATED CLUSTER SNAPSHOT ON STORAGE VOLUME backup;
3. ...
4. DROP STORAGE VOLUME backup;

### Expected behavior (Required)
Maybe cannot be deleted or show me more info such as which sv is not found in the logs.
### Real behavior (Required)
```
2025-08-21 14:44:59.384+08:00 ERROR (cluster_snapshot_checkpoint_scheduler|196) [Daemon.run():100] daemon thread got exception. name: cluster_snapshot_checkpoint_scheduler
java.lang.NullPointerException: Cannot invoke "com.starrocks.storagevolume.StorageVolume.getLocations()" because "sv" is null
at com.starrocks.lake.snapshot.ClusterSnapshotUtils.getSnapshotImagePath(ClusterSnapshotUtils.java:25) ~[starrocks-fe.jar:?]
at com.starrocks.lake.snapshot.ClusterSnapshotUtils.uploadAutomatedSnapshotToRemote(ClusterSnapshotUtils.java:35) ~[starrocks-fe.jar:?]
at com.starrocks.lake.snapshot.ClusterSnapshotCheckpointScheduler.runCheckpointScheduler(ClusterSnapshotCheckpointScheduler.java:131) ~[starrocks-fe.jar:?]
at com.starrocks.lake.snapshot.ClusterSnapshotCheckpointScheduler.runAfterCatalogReady(ClusterSnapshotCheckpointScheduler.java:70) ~[starrocks-fe.jar:?]
at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
at com.starrocks.common.util.Daemon.run(Daemon.java:98) ~[starrocks-fe.jar:?]
```
### StarRocks version (Required)
**v3.5.3**

### PR DESCRIPTION
**Pull request by rohitrs1983**
image

Fixes #62172

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [X] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 4.0
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Review by srlch — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java [hunk 1]
```diff
@@ -136,6 +136,10 @@ public void removeStorageVolume(DropStorageVolumeStmt stmt) throws DdlException,
 
     public void removeStorageVolume(String name) throws DdlException, MetaNotFoundException {
         try (LockCloseable lock = new LockCloseable(rwLock.writeLock())) {
+            if (GlobalStateMgr.getCurrentState().getClusterSnapshotMgr().getAutomatedSnapshotSvName() != null
+                    && GlobalStateMgr.getCurrentState().getClusterSnapshotMgr().getAutomatedSnapshotSvName().equals(name)) {
```
Comment (xiangguangyxg) [inline fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java]: redundant code, could refactor

File: fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java [hunk 2]
```diff
@@ -1010,4 +1011,45 @@ public void testUpgrade() throws IOException, SRMetaBlockException, SRMetaBlockE
...
+                () -> svm.createStorageVolume(svName, "S3", locations, storageParams, Optional.empty(), ""));
+        storageParams.remove("aaa");
+        storageParams.put(AWS_S3_ENDPOINT, "endpoint");
+        storageParams.put(AWS_S3_USE_AWS_SDK_DEFAULT_BEHAVIOR, "true");
+        String svKey = svm.createStorageVolume(svName, "S3", locations, storageParams, Optional.empty(), "");
+        Assertions.assertEquals(true, svm.exists(svName));
+        Assertions.assertEquals(svName, svm.getStorageVolumeName(svKey));
+        // remove
+        try {
+            svm.removeStorageVolume(svName);
```
Comment (kevincai) [inline fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java]:
```
DdlException exception = Assertions.assertThrows(DdlException.class, () -> svm.removeStorageVolume(svName));
```

Comment (rohitrs1983) [reply fe/fe-core/src/test/java/com/starrocks/server/SharedDataStorageVolumeMgrTest.java]: updated

**Review by srlch — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java (hunk 1 above)
Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/server/StorageVolumeMgr.java]: introduce local var and adjust the check order.

**Review by kevincai — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
@mergifyio rebase

**Review by xiangguangyxg — APPROVED** [review]
