### PR TITLE
[BugFix] fix alter table in new publish; add detail error message for load/insert publish timeout

### LINKED ISSUE #11841: [Enhancement] More informative error messge for txn publish timeout
## Enhancement
Currently, when TXN publish timeout, error message only shows: `Publish timeout. The data will be visible after a while`, that's not useful, lagging table/partition/tablet/replica and BE information should be provided.

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Problem Summary(Required) ：

This PR fixes a bug in publish version check logic when alter table is undergoing. When alter table is in progress, the newly created alter tablet cannot achieve the desired version for publish task, so when checking for publish reach quorum conditions, should consider tablets under schemachange normal, so txn during schemachange can publish normally.
This PR also add more detailed error to client return message when publish is timeout for new publish mechanism. 

The error message will change from
```
"Message": "Publish timeout. The data will be visible after a while",
```
to something like:
```
"Message": "Publish timeout. The data will be visible after a while errors:  {tablet:31027 quorum:1 version:4 #replica:1 err:[be:192.168.100.72,version:3,ALTER]} #partition:1 #tablet:2",
```

Fixes: #11841
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 62 (66.13%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|11|00.00%|[968, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023, 1028, 1033]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|12|18|66.67%|[733, 734, 735, 737, 738, 742]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|2|3|66.67%|[933]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|3|4|75.00%|[747]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|5|6|83.33%|[1670]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|6|7|85.71%|[1481]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|13|13|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 41 / 63 (65.08%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|11|00.00%|[968, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023, 1028, 1033]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|12|19|63.16%|[733, 734, 735, 736, 738, 739, 743]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|2|3|66.67%|[933]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|3|4|75.00%|[747]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|5|6|83.33%|[1670]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|6|7|85.71%|[1481]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|13|13|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java [hunk 1]
```diff
@@ -713,11 +712,36 @@ public boolean quorumReachVersion(long version, long quorum, TxnFinishState fini
                     finishState.normalReplicas.add(replicaId);
                     finishState.abnormalReplicasWithVersion.remove(replicaId);
                 } else {
+                    if (replica.getState() == ReplicaState.ALTER && replicaVersion <= Partition.PARTITION_INIT_VERSION) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:715]: The problem and solution should be described in the commit message.

File: fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java [hunk 2]
```diff
@@ -713,11 +712,36 @@ public boolean quorumReachVersion(long version, long quorum, TxnFinishState fini
...
+
+    public void getAbnormalReplicaInfos(long version, long quorum, StringBuilder sb) {
+        synchronized (replicas) {
+            boolean empty = true;
+            for (Replica replica : replicas) {
+                long replicaId = replica.getId();
+                long replicaVersion = replica.getVersion();
+                if (replicaVersion < version) {
+                    if (empty) {
+                        sb.append(String.format(" {tablet:%d quorum:%d version:%d #replica:%d err:", id, quorum, version,
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:734]: tablet_id + backend_id is enough

Comment (decster) [reply fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:733]: removed replicaid and lastfailedversion

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 62 (04.84%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|11|00.00%|[968, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023, 1028, 1033]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|0|13|00.00%|[41, 42, 43, 44, 45, 46, 47, 48, 49, 74, 75, 76, 77]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|0|6|00.00%|[1663, 1665, 1667, 1669, 1670, 1672]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|4|00.00%|[745, 746, 747, 749]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|0|3|00.00%|[930, 931, 933]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|18|11.11%|[727, 728, 729, 730, 731, 732, 733, 734, 735, 737, 738, 740, 741, 742, 744, 745]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|7|14.29%|[1477, 1478, 1479, 1480, 1481, 1483]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java [hunk 3]
```diff
@@ -713,11 +712,35 @@ public boolean quorumReachVersion(long version, long quorum, TxnFinishState fini
...
+            boolean empty = true;
+            for (Replica replica : replicas) {
+                long replicaVersion = replica.getVersion();
+                if (replicaVersion < version) {
+                    if (empty) {
+                        sb.append(String.format(" {tablet:%d quorum:%d version:%d #replica:%d err:", id, quorum, version,
+                                replicas.size()));
+                        empty = false;
+                    }
+                    sb.append(String.format("[be:%d,v:%d%s]", replica.getBackendId(), replicaVersion,
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:737]: You can change to backendId to host or IP, `v` changed to version

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 64 (04.69%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|11|00.00%|[968, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023, 1028, 1033]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|0|13|00.00%|[41, 42, 43, 44, 45, 46, 47, 48, 49, 74, 75, 76, 77]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|0|6|00.00%|[1663, 1665, 1667, 1669, 1670, 1672]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|4|00.00%|[743, 747, 748, 749]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|0|3|00.00%|[930, 931, 933]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|20|10.00%|[727, 728, 729, 730, 731, 732, 733, 734, 735, 737, 738, 739, 740, 742, 743, 744, 746, 747]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|7|14.29%|[1477, 1478, 1479, 1480, 1481, 1483]|

**Review by chaoyli — DISMISSED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 64 (04.69%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|11|00.00%|[968, 1015, 1016, 1017, 1018, 1019, 1020, 1022, 1023, 1028, 1033]|
|:large_blue_circle:|com/starrocks/transaction/TransactionChecker.java|0|13|00.00%|[41, 42, 43, 44, 45, 46, 47, 48, 49, 74, 75, 76, 77]|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|0|6|00.00%|[1663, 1665, 1667, 1669, 1670, 1672]|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|4|00.00%|[743, 747, 748, 749]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|0|3|00.00%|[930, 931, 933]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|20|10.00%|[727, 728, 729, 730, 731, 732, 733, 734, 735, 737, 738, 739, 740, 742, 743, 744, 746, 747]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|1|7|14.29%|[1477, 1478, 1479, 1480, 1481, 1483]|

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
@mergify backport branch-2.4
