### PR TITLE
Fix the bug of unregistering clone tablet when clone task fails(#3134)

### LINKED ISSUE #3134: There is a bug in clone task
In EngineCloneTask, it registered the clone tablet to tablet manager to prevent being deleted by gc. But do not deregister when exit with failure, which will lead to the fact that the tablet will not be collected after dropped.

### Expected behavior (Required)

deregister the tablet from tablet manager whenever clone task finished, no matter whether it success or fail.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.0

### PR DESCRIPTION
**Pull request by DeepThinker666**
## What type of PR is this：
- [X] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3134 

## Problem Summary(Required) ：

clone task do not deregister itself when fails, which will lead to the fact that the tablet can not be GCed when dropped.

### CODE REVIEW

File: be/src/storage/task/engine_clone_task.cpp [hunk 1]
```diff
@@ -71,9 +71,12 @@ EngineCloneTask::EngineCloneTask(MemTracker* mem_tracker, const TCloneReq& clone
 
 Status EngineCloneTask::execute() {
     MemTracker* prev_tracker = tls_thread_status.set_mem_tracker(_mem_tracker.get());
-    DeferOp op([&] { tls_thread_status.set_mem_tracker(prev_tracker); });
-
     auto tablet_manager = StorageEngine::instance()->tablet_manager();
+    DeferOp op([&] {
```
Comment (imay) [inline be/src/storage/task/engine_clone_task.cpp:75]: This should be defined after `tablet_manager->register_clone_tablet(_clone_req.tablet_id);`

Comment (DeepThinker666) [reply be/src/storage/task/engine_clone_task.cpp:77]: ok, done

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]
