### PR TITLE
[BugFix] enhance column pruning for query with predicates after mv rewrite

### LINKED ISSUE #45272: extra columns have been read after mv rewrite for query with predicates
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
create materialized view mv1
refresh manual
as
select lo_orderkey, lo_orderdate, lo_linenumber," +
                    " sum(lo_quantity) total_quantity," +
                    " sum(lo_revenue) as total_revenue," +
                    " sum(lo_tax) as total_tax" +
                    " from lineorder" +
                    " group by lo_orderkey, lo_orderdate, lo_linenumber";

2. query
"select lo_orderdate," +
                    " sum(lo_quantity) total_quantity," +
                    " sum(lo_tax) as total_tax" +
                    " from lineorder" +
                    " where lo_orderkey = 100" +
                    " group by lo_orderdate"

### Expected behavior (Required)
the query has been rewritten by mv1 with  a projection above mv scan node.
### Real behavior (Required)

the query has been rewritten by mv1 without  a projection above mv scan node.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## Why I'm doing:
the query with predicates may be rewritten by mv without a projection above scan node.

## What I'm doing:
add a projection above scan node after query rewritten to reduce the size of data.

Fixes #45272

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java [hunk 1]
```diff
@@ -93,6 +95,20 @@ public OptExpression visitLogicalTableScan(OptExpression optExpression, Void con
...
+                    Map<ColumnRefOperator, ScalarOperator> projectionMap = Maps.newHashMap();
+                    for (ColumnRefOperator columnRefOperator : outputColumns) {
+                        if (outputRefSet.contains(columnRefOperator)) {
+                            continue;
+                        }
+                        projectionMap.put(columnRefOperator, columnRefOperator);
+                    }
+                    Projection newProjection = new Projection(projectionMap);
+                    builder.setProjection(newProjection);
+                }
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java:111]: What about other operators?

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java:111]: I add more uts to cover other operators. I found no problems

**Review by LiShuMing — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by jaogoy** [comment]
ignore backport check: 2.5.22
