### PR TITLE
[BugFix] Fix reorder rule not deal column to  column projection with different…

### LINKED ISSUE #6089: [sqlancer]Unknown error.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NULL ,c_0_1 SMALLINT NOT NULL ,c_0_2 ARRAY<INT> NULL ,c_0_3 DECIMAL(22, 14)  NOT NULL ,c_0_4 DECIMAL(25, 12)  NULL ,c_0_5 VARCHAR(31) NULL , INDEX index1_c_0_0(`c_0_0`) USING BITMAP) UNIQUE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 132 day)) DISTRIBUTED BY HASH (c_0_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DATETIME NULL ,c_1_1 SMALLINT NOT NULL ,c_1_2 BOOLEAN NOT NULL ,c_1_3 VARCHAR(21) NOT NULL ,c_1_4 DECIMAL(19, 14)  NOT NULL ,c_1_5 BOOLEAN NOT NULL ,c_1_6 DATETIME NULL ,c_1_7 DATETIME NULL ,c_1_8 BOOLEAN NOT NULL ,c_1_9 DECIMAL(2, 0)  NULL ,c_1_10 DATE NULL ,c_1_11 BOOLEAN NOT NULL ,c_1_12 LARGEINT NULL ,c_1_13 BOOLEAN NULL ,c_1_14 DATETIME NOT NULL ,c_1_15 ARRAY<INT> NULL ,c_1_16 SMALLINT NOT NULL , INDEX index1_c_1_1(`c_1_1`) USING BITMAP) DUPLICATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11,c_1_12) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 101 day)) DISTRIBUTED BY HASH (c_1_2,c_1_4,c_1_1) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t1 VALUES ("2010-01-07 08:00:14", 8, false, "", 9.7512E-10, false, "2010-01-24 08:00:14", "2010-01-08 08:00:14", false, 51, "2010-01-27", false, 844743687, false, "2010-01-26 08:00:14", [-1239716952, -1189826518, 1040263934, -2112055990, -569521847, -1239716952, -92295569, -92295569, 2044928903], 10), ("2010-01-06 08:00:14", 14, false, "Obw", 1.5688E-10, false, "2010-01-31 08:00:14", "2010-01-02 08:00:14", true, 28, "2010-01-25", true, -1239716952, true, "2010-01-23 08:00:14", [-1189826518], 14);
INSERT INTO t0 VALUES ("2010-01-31", 2, [-93748879, 844743687, -1189826518], 3.4440995E-7, 9.071898846350, "GOOZaL"), ("2010-01-15", 10, [154304823, -1189826518, -1318062803, 1145501738, 497341188, 844743687, -1316141115, -149768130, -149768130, 154304823, -651067390, 0, -1878382981, 382256388, 9223372036854775807], 8.9410038E-7, 5.601180596559, "rkwn8F");
INSERT INTO t0 VALUES ("2010-01-06", 11, [171946639, -1359078558, -1772392736, -889565166, 406341945, -1941864921, 486322122, -1189826518, 2044928903, 1262352759], 9.3083545E-7, 0.880571577601, NULL), ("2010-01-24", 13, [9223372036854775807, 709077588, 1145501738, -1617993831, -1268717957, 1, -149768130, -1359078558, -1318062803, 616066317, -148008930, 358031605, -216968846, 171946639, -1049204107], 5.8598547E-7, NULL, "u5");
INSERT INTO t0 VALUES ("2010-01-26", 10, [-1318062803, -2002168231, -872615771, -28424701, -1894825911, -1954392745, 2044928903, -1772392736, -9223372036854775808, 1623873170, -28424701, 1096835824], 5.2364792E-7, NULL, "LK2");
INSERT INTO t0 VALUES ("2010-01-11", 15, [-92295569, -1673882313, 757062702, 101973383, 1040263934, 505586439, 757062702, -252047341, 909808341, -1887817959, 57801269], 8.9576737E-7, 9.914148847612, "Kk"), ("2009-12-31", 3, [-1443824859, -93748879], 5.1777534E-7, 6.879563787459, "r9b"), ("2010-01-07", 1, [2021198944, -9968866, 229358979, -665179945, 480639020, 480639020, 1240243643, -469995211, 1897536876, 1096835824, 1262352759, -287637245, 185267274, 382256388], 5.5391056E-7, NULL, NULL);
DELETE FROM t1 WHERE c_1_8=false AND c_1_4=1.3769E-10 AND c_1_6="1970-01-16 08:30:10" AND c_1_3="6d8tKTL" AND c_1_11=true AND c_1_7="1969-12-30 10:31:07" AND c_1_9=42 AND c_1_0="1970-01-08 07:20:50";
INSERT INTO t0 VALUES ("2010-01-06", 8, [185267274, -2067304097], 8.8654261E-7, 6.001648452298, "KcVq0f");
INSERT INTO t0 VALUES ("2010-01-05", 11, [705810637, 656087281, -921005036, 118594188, -93748879, -1074938766, 1060752659, 1880027017, 1238056037, 1001315729, -872615771, -2033203335, 602450594], 2.6130287E-7, NULL, "");
```
2. INSERT INTO '....'
3. SELECT  '....'
```
WITH with_t_0 as (SELECT t1_3.c_1_0, t1_3.c_1_1, t1_3.c_1_2, t1_3.c_1_3, t1_3.c_1_4, t1_3.c_1_5, t1_3.c_1_6, t1_3.c_1_7, t1_3.c_1_8, t1_3.c_1_9, t1_3.c_1_10, t1_3.c_1_11, t1_3.c_1_12, t1_3.c_1_13, t1_3.c_1_14, t1_3.c_1_16 FROM t1 AS t1_3 WHERE  ( (SELECT t1_3.c_1_3 FROM t1 AS t1_3, t0 AS t0_2 WHERE false)  ) < ( (SELECT t0_2.c_0_0 FROM t0 AS t0_2 WHERE true)  ) ) SELECT SUM(count) FROM (SELECT CAST((CAST(false AS BOOLEAN) = true) AND (CAST(false AS BOOLEAN) IS NOT NULL) AS INT) as count FROM   t1 AS t1_3 FULL JOIN (SELECT with_t_0.c_1_0, with_t_0.c_1_1, with_t_0.c_1_2, with_t_0.c_1_3, with_t_0.c_1_4, with_t_0.c_1_5, with_t_0.c_1_6, with_t_0.c_1_7, with_t_0.c_1_8, with_t_0.c_1_9, with_t_0.c_1_10, with_t_0.c_1_11, with_t_0.c_1_12, with_t_0.c_1_13, with_t_0.c_1_14, with_t_0.c_1_16 FROM with_t_0 AS with_t_0 WHERE (CASE  WHEN true THEN with_t_0.c_1_12  WHEN true THEN with_t_0.c_1_12  WHEN false THEN ((616066317)*(WEEKOFYEAR(NULL) )) ELSE -216968846 END) IN ((SELECT t1_3.c_1_12 FROM t1 AS t1_3 WHERE true) ) ) subwith_t_0 ON t1_3.c_1_9 = subwith_t_0.c_1_8 AND t1_3.c_1_9 > subwith_t_0.c_1_8 AND t1_3.c_1_3 <= subwith_t_0.c_1_14 AND t1_3.c_1_3 < subwith_t_0.c_1_14 AND t1_3.c_1_13 >= subwith_t_0.c_1_7 AND t1_3.c_1_13 = subwith_t_0.c_1_7) t;
```
### Real behavior (Required)
```
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:60) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:190) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeJoinNode(StatisticsCalculator.java:822) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:716) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:117) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:151) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:309) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH-2.2-RELEASE dffad40

### PR DESCRIPTION
**Pull request by Youngwb**
… name

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #6089 

## Problem Summary(Required) ：

During the processing of subqueries, a column-to-column mapping is generated with name "expr"->column_name, we should deal with this situation at reorder rule,  treat it as expression mapping of projection.

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Comment by kangkaisen** [comment]
```
a column-to-column mapping is generated with name "expr"->column_name,
```

why we need to generate the column-to-column mapping?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java|2|2|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java [hunk 1]
```diff
@@ -55,14 +55,7 @@ public <R, C> R accept(OptExpressionVisitor<R, C> visitor, OptExpression optExpr
...
     public boolean equals(Object o) {
-        if (this == o) {
-            return true;
-        }
-        if (o == null || getClass() != o.getClass()) {
-            return false;
-        }
-        PhysicalAssertOneRowOperator that = (PhysicalAssertOneRowOperator) o;
-        return checkRows == that.checkRows && assertion == that.assertion && Objects.equal(tips, that.tips);
+        return this == o;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java:58]: if you change the equals method, the hashCode method should also be changed

**Comment by Youngwb** [comment]
> ```
> a column-to-column mapping is generated with name "expr"->column_name,
> ```
> 
> why we need to generate the column-to-column mapping?

subquery and CTE will generate the column-to-column mapping

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java (hunk 1 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java:58]: done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 8 / 9 (88.89%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalAssertOneRowOperator.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAssertOneRowOperator.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/JoinAssociativityRule.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SemiReorderRule.java|2|2|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.2
