### PR TITLE
[BugFix] Fixed incorrect config value obtained by /varz

### LINKED ISSUE #41369: The value returned via BE's HTTP interface '/varz' may be wrong
`/varz` gets its value from the global map `full_conf_map`, but `full_conf_map` is only updated when `set_config` is called, and there are configurations in our code that are updated by directly assigning a value to a configuration item, like this: https://github.com/StarRocks/starrocks/blob/60515a27f2105dc0daaf513cb4211e270716b09b/be/src/runtime/exec_env.cpp#L506
For this case, the value obtained by /varz is outdated:
```
> curl http://127.0.0.1:58045/varz | grep starlet_cache_dir
starlet_cache_dir=
```
And the value shown in information_schema.be_configs is correct:
```
> select NAME, VALUE from information_schema.be_configs where name = 'starlet_cache_dir';                                                                                                                              
+-------------------+------------------------------------------------------------+
| NAME              | VALUE                                                      |
+-------------------+------------------------------------------------------------+
| starlet_cache_dir | /home/disk3/zhuming/local_cluster/be/storage/starlet_cache |
+-------------------+------------------------------------------------------------+
1 row in set (0.02 sec)

```

### PR DESCRIPTION
**Pull request by sduzh**
Fixes #41369 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by imay — APPROVED** [review]

File: be/src/common/configbase.cpp [hunk 1]
```diff
@@ -343,39 +330,59 @@ Status set_config(const std::string& field, const std::string& value) {
 
     // The other types are not thread safe to change dynamically.
     return Status::NotSupported(
-            strings::Substitute("'$0' is type of '$1' which is not support to modify", field, it->second.type));
+            fmt::format("'{}' is type of '{}' which is not support to modify", field, it->second.type));
```
Comment (kevincai) [inline be/src/common/configbase.cpp:333]:
```suggestion
            fmt::format("'{}' is type of '{}' which is immutable", field, it->second.type));
```

**Review by kevincai — APPROVED** [review]
