### PR TITLE
BugFix: Fix bug of master exit wrong when adding follower

### LINKED ISSUE #4426: Master is crashed when adding new follower node
### Steps to reproduce the behavior (Required)
1. Set up a cluster with a single follower node.
2. Set the config of metadata_checkopoint_memory_threshold to 0 to pause the checkpoint.
3. Create/Drop tables non-stop.
4. When the size of dir meta/bdb grows to a few GBs.
5. Add new follower to the cluster.

### Expected behavior (Required)
Expand should success.

### Real behavior (Required)
Master node is crashed with following log:
image

Newly added node is crashed with following log:
image

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4426

## Problem Summary(Required) ：

Set the bdb electable group size to (the_total_number_of_followers - the_number_of_adding_followers). After the follower is joined successfully, reset the electable group size to the_total_number_of_followers.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 33 (03.03%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|0|18|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/system/Frontend.java|1|3|33.33%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 1]
```diff
@@ -2574,8 +2574,10 @@ public void addFrontend(FrontendNodeType role, String host, int editLogPort) thr
             fe = new Frontend(role, nodeName, host, editLogPort);
             frontends.put(nodeName, fe);
             if (role == FrontendNodeType.FOLLOWER || role == FrontendNodeType.REPLICA) {
-                ((BDBHA) getHaProtocol()).addHelperSocket(host, editLogPort);
+                BDBHA ha = (BDBHA) haProtocol;
+                ha.addHelperSocket(host, editLogPort);
                 helperNodes.add(Pair.create(host, editLogPort));
+                ha.addUnstableNode(host, getFollowerCnt());
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:2580]: If the master transferred between the addFrontend and dropBackend, what will happen?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:2580]: If master transferred during the join progress, the new master won't have the unstable node info. But that is ok because transferring master means there is quorum size node alive, there is no need to wait the joining node's ack before completing a write operation.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 19 / 33 (57.58%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/system/Frontend.java|1|3|33.33%|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|18|18|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 32 / 33 (96.97%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|18|18|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|11|11|100.00%|

**Review by chaoyli — DISMISSED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 30 / 31 (96.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/ha/BDBHA.java|18|18|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|9|9|100.00%|

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
