### PR TITLE
[BugFix] fix some problems when be exits gracefully

### LINKED ISSUE #12815: ASAN will report an error when be exits gracefully
### Steps to reproduce the behavior (Required)
1. start fe and be
2. ```./bin/stop_be.sh -g```

### Expected behavior (Required)

BE exit without any error

### Real behavior (Required)
```
==127088==ERROR: AddressSanitizer: heap-use-after-free on address 0x6190001764e9 at pc 0x000009c9b086 bp 0x7f33c28e0b30 sp 0x7f33c28e0b28
READ of size 1 at 0x6190001764e9 thread T1046
    #0 0x9c9b085 in starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}::operator()() const /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/storage/storage_engine.h:148
    #1 0x9caf74f in bool std::condition_variable::wait_until<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> >, starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}>(std::unique_lock<std::mutex>&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&, starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/condition_variable:159
    #2 0x9caa4fa in bool std::condition_variable::wait_for<long, std::ratio<1l, 1l>, starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}>(std::unique_lock<std::mutex>&, std::chrono::duration<long, std::ratio<1l, 1l> > const&, starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/condition_variable:185
    #3 0x9c9b20e in starrocks::StorageEngine::wait_for_report_notify(long, bool) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/storage/storage_engine.h:148
    #4 0x9c947af in starrocks::ReportDiskStateTaskWorkerPool::_worker_thread_callback(void*) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/agent/task_worker_pool.cpp:605
    #5 0x9ce1dcf in void* std::__invoke_impl<void*, void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*>(std::__invoke_other, void* (*&&)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*&&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #6 0x9ce14f1 in std::__invoke_result<void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*>::type std::__invoke<void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*>(void* (*&&)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*&&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #7 0x9ce0d58 in void* std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*> >::_M_invoke<0ul, 1ul>(std::_Index_tuple<0ul, 1ul>) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/thread:264
    #8 0x9ce02a5 in std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*> >::operator()() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/thread:271
    #9 0x9cdf2bd in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void* (*)(void*), starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>*> > >::_M_run() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/thread:215
    #10 0x13b3bdff in execute_native_thread_routine ../../../../../libstdc++-v3/src/c++11/thread.cc:80
    #11 0x7f35c14e6ea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #12 0x7f35c0b01b0c in clone (/lib64/libc.so.6+0xfeb0c)

0x6190001764e9 is located 873 bytes inside of 1000-byte region [0x619000176180,0x619000176568)
freed by thread T0 here:
    #0 0x9bc5637 in operator delete(void*, unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:172
    #1 0xf2adba6 in starrocks::StorageEngine::~StorageEngine() /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/storage/storage_engine.cpp:113
    #2 0x9c05587 in main /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/service/starrocks_main.cpp:320
    #3 0x7f35c0a25554 in __libc_start_main (/lib64/libc.so.6+0x22554)

previously allocated by thread T0 here:
    #0 0x9bc4817 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0xf2d0460 in std::_MakeUniq<starrocks::StorageEngine>::__single_object std::make_unique<starrocks::StorageEngine, starrocks::EngineOptions const&>(starrocks::EngineOptions const&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/unique_ptr.h:962
    #2 0xf2ac536 in starrocks::StorageEngine::open(starrocks::EngineOptions const&, starrocks::StorageEngine**) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/storage/storage_engine.cpp:77
    #3 0x9c04a40 in main /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/service/starrocks_main.cpp:268
    #4 0x7f35c0a25554 in __libc_start_main (/lib64/libc.so.6+0x22554)

Thread T1046 created by T0 here:
    #0 0x9b6e512 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x13b3bec4 in __gthread_create /home/disk2/zc/tools/toolchain/build/gcc-10.3.0/build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:663
    #2 0x13b3bec4 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) ../../../../../libstdc++-v3/src/c++11/thread.cc:135
    #3 0x9ca8666 in starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>::_spawn_callback_worker_thread(void* (*)(void*)) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/agent/task_worker_pool.cpp:236
    #4 0x9ca66db in starrocks::TaskWorkerPool<starrocks::AgentTaskRequestWithoutReqBody>::start() /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/agent/task_worker_pool.cpp:88
    #5 0x9c1c24b in starrocks::AgentServer::Impl::init_or_die() /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/agent/agent_server.cpp:209
    #6 0x9c2c947 in starrocks::AgentServer::init_or_die() /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/agent/agent_server.cpp:552
    #7 0xffd64b0 in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/runtime/exec_env.cpp:294
    #8 0xffd203d in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/runtime/exec_env.cpp:127
    #9 0x9c04c0a in main /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/service/starrocks_main.cpp:276
    #10 0x7f35c0a25554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: heap-use-after-free /home/disk2/xujia/WorkSpace/silverbullet233/starrocks/be/src/storage/storage_engine.h:148 in starrocks::StorageEngine::wait_for_report_notify(long, bool)::{lambda()#2}::operator()() const
Shadow bytes around the buggy address:
  0x0c3280026c40: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3280026c50: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3280026c60: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3280026c70: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c3280026c80: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c3280026c90: fd fd fd fd fd fd fd fd fd fd fd fd fd[fd]fd fd
  0x0c3280026ca0: fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa
  0x0c3280026cb0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280026cc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3280026cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3280026ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==127088==ABORTING
```

### StarRocks version (Required)

main 6c3cfc6272ee9edcb44687bc624a2bf64f3e786a

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12815 #12838 

## Problem Summary(Required) ：

`ExecEnv`, `StorageEngine` and `AgentServer` have complex dependencies, some threads in AgentServer need to access `StorageEngine::instance()`, we should make sure the lifetime of StorageEngine is longer than these threads, so I add a stop method into `AgentServer` to release resources which will be invoked before deleting `StorageEngine`.

After I fixed the above issue, a memory leak of brpc was detected by ASAN(I mentioned it in the comment of #12815 ), but from the comments of brpc's code, this leak is expected, so I add `asan_supressions.conf` to filter it out.
image

The above problem of memory access errors may cause jemalloc calls to appear on the coredump stack. In addition, I found that when the process exits, in some cases, `nullptr` may be passed to `my_free` function, which will cause coredump when calling `je_malloc_usable_size`, I don't know where the root case is yet, but  a special check for `nullptr` can avoid this problem.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by satanson — DISMISSED** [review]

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_fe_unittest

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

**Comment by silverbullet233** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by silverbullet233** [comment]
run starrocks_be_unittest

File: be/src/storage/storage_engine.cpp [hunk 1]
```diff
@@ -110,6 +110,9 @@ StorageEngine::~StorageEngine() {
         _s_instance = _p_instance;
     }
 #endif
+    if (_s_instance != nullptr) {
+        _s_instance = nullptr;
+    }
```
Comment (Linkerist) [inline be/src/storage/storage_engine.cpp:115]:
```suggestion
#else
    if (_s_instance != nullptr) {
        _s_instance = nullptr;
    }
#endif
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]
