### PR TITLE
[Enhancement] Support complex expressions in Sync MV

### LINKED ISSUE #17933: Single(Sync) Table MV cannot support agg function + expr
### Steps to reproduce the behavior (Required)
```
CREATE TABLE customer ( C_CUSTKEY     INTEGER NOT NULL,
                        C_NAME        VARCHAR(25) NOT NULL,
                        C_ADDRESS     VARCHAR(40) NOT NULL,
                        C_NATIONKEY   INTEGER NOT NULL,
                        C_PHONE       CHAR(15) NOT NULL,
                        C_ACCTBAL     double   NOT NULL,
                        C_MKTSEGMENT  CHAR(10) NOT NULL,
                        C_COMMENT     VARCHAR(117) NOT NULL,
                        PAD char(1) NOT NULL)
    ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

```

### Real behavior (Required)

Bug1:`Duplicate column name`:  error msg is wrong???
```
create materialized view customer_mv2
properties (
    "replication_num" = "1"
)
as select
              c_custkey, c_phone, c_acctbal, count(C_MKTSEGMENT) as c_count2, sum(c_acctbal) as c_sum
   from
              customer
   group by c_custkey, c_phone, c_acctbal;

ERROR 1064 (HY000): Duplicate column name 'c_acctbal'
```

Bug2: Why cannot handle agg function + expr ?
```
create materialized view customer_mv3
properties (
    "replication_num" = "1"
)
as select
              c_custkey, count(C_MKTSEGMENT) as c_count2,  sum(c_acctbal % 10) as c_sum
   from
              customer
   group by c_custkey;


ERROR 1064 (HY000): The function sum must match pattern:sum(column)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

the latest main branch.
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN ef9b113e3 |
+-------------------+
1 row in set (0.07 sec)
```

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #22401 #17933

### Backgroud
Old Sync MV can only support several pattern: input must be slot-ref or agg_func(slot_ref).
Since https://github.com/StarRocks/starrocks/pull/24750 and https://github.com/StarRocks/starrocks/pull/24764
have been merged, we can loose the restriction to support more complex expressions in sync mv.

### Usage
```
create table user_tags (time date, user_id int, user_name varchar(20), tag_id int) partition by range (time)  (partition p1 values less than MAXVALUE) distributed by hash(time) buckets 3 properties('replication_num' = '1');
insert into user_tags values('2023-04-13', 1, 'a', 1), ('2023-04-13', 1, 'b', 2), ('2023-04-13', 1, 'c', 3), ('2023-04-13', 1, 'd', 4), ('2023-04-13', 1, 'e', 5), ('2023-04-13', 2, 'e', 5), ('2023-04-13', 3, 'e', 6);


create materialized view user_tags_mv2
as select user_id, time, bitmap_union(to_bitmap(tag_id * 100)) as agg1 from user_tags group by user_id, time;


create materialized view user_tags_hll_mv2
as select user_id * 2 as col1, time, hll_union(hll_hash(abs(tag_id))) as agg2 from user_tags group by col1, time;


create materialized view user_tags_percential_mv2
as select user_id + 1 as col1, time, percentile_union(percentile_hash(cast(tag_id * 10 as double))) as agg3 from user_tags group by col1, time;


create materialized view same_column_ref_mv1
as select user_id + 1 as col1, time, sum(tag_id* 10) as sum1 , sum(tag_id* 100) as sum2, count(tag_id* 10) as count1 from user_tags group by col1, time;

```
### Description
- There are still some limitations about the PR:
  -  Complex expression must have the alias name like Async MV. And the alias name should not be the same with the table's full schema.
  - Complex expression only can refer one column for now.
- We reuse the async mv rewrite rule to rewrite/compensate the mv, you need take care for you mv definition.

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 296 / 339 (87.32%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|20|26|76.92%|[489, 492, 497, 498, 516, 517]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|35|44|79.55%|[106, 112, 118, 123, 128, 131, 135, 139, 143]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|114|136|83.82%|[236, 237, 239, 240, 241, 245, 246, 247, 282, 290, 307, 308, 311, 312, 316, 317, 356, 388, 399, 424, 468, 469]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|54|60|90.00%|[166, 167, 168, 180, 181, 182]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|5|5|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 427 / 476 (89.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|20|26|76.92%|[489, 492, 497, 498, 516, 517]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|35|44|79.55%|[106, 112, 118, 123, 128, 131, 135, 139, 143]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|115|138|83.33%|[236, 237, 239, 240, 241, 245, 246, 247, 283, 291, 306, 307, 310, 311, 315, 316, 356, 360, 394, 405, 430, 474, 475]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/OnlyScanRule.java|8|9|88.89%|[52]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|79|85|92.94%|[180, 181, 182, 194, 195, 196]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|59|63|93.65%|[428, 448, 451, 452]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/OlapTable.java|24|24|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/PartitionInfo.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Field.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|11|11|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java [hunk 1]
```diff
@@ -171,7 +171,7 @@ public TAlterTabletReqV2 toThrift() {
                 List<SlotRef> slots = Lists.newArrayList();
                 entry.getValue().collect(SlotRef.class, slots);
                 TAlterMaterializedViewParam mvParam = new TAlterMaterializedViewParam(entry.getKey());
-                mvParam.setOrigin_column_name(slots.get(0).getLabel());
+                mvParam.setOrigin_column_name(slots.get(0).getColumnName());
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/task/AlterReplicaTask.java:174]: what???

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 203 / 234 (86.75%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|13|19|68.42%|[490, 493, 498, 499, 517, 518]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|122|147|82.99%|[237, 238, 240, 241, 242, 284, 292, 307, 308, 311, 312, 316, 317, 357, 358, 362, 363, 364, 397, 408, 418, 419, 441, 485, 486]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|11|11|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 210 / 242 (86.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|13|19|68.42%|[490, 493, 498, 499, 517, 518]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|123|149|82.55%|[237, 238, 240, 241, 242, 284, 292, 307, 308, 311, 312, 316, 317, 357, 358, 362, 363, 364, 397, 408, 419, 420, 421, 443, 487, 488]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToSQLBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|11|11|100.00%|[]|

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 215 / 247 (87.04%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|13|19|68.42%|[490, 493, 498, 499, 517, 518]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|123|149|82.55%|[237, 238, 240, 241, 242, 284, 292, 307, 308, 311, 312, 316, 317, 357, 358, 362, 363, 364, 397, 408, 419, 420, 421, 443, 487, 488]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToSQLBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|2|2|100.00%|[]|

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 2]
```diff
@@ -158,7 +158,7 @@ public void prepareSyncMvCandidatesForPlan(ConnectContext connectContext) {
                             new MaterializedView.MvRefreshScheme(MaterializedView.RefreshType.SYNC);
                     MaterializedView mv = new MaterializedView(db, mvName, indexMeta, olapTable,
                             mvPartitionInfo, mvDistributionInfo, mvRefreshScheme);
-                    mv.setViewDefineSql(viewDefineSql);
+                    mv.setViewDefineSql(" " + viewDefineSql);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:161]: why add a space?

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java [hunk 3]
```diff
@@ -57,23 +58,17 @@ public class MVColumnItem {
     private boolean isAllowNull;
     private boolean isAggregationTypeImplicit;
     private Expr defineExpr;
-    private final String baseColumnName;
+    private Set<String> baseColumnNames;
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java:61]: why it is a set?

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java [hunk 4]
```diff
@@ -130,16 +134,12 @@ public class CreateMaterializedViewStmt extends DdlStmt {
     private String dbName;
     private KeysType mvKeysType = KeysType.DUP_KEYS;
 
-    //if process is replaying log, isReplay is true, otherwise is false, avoid replay process error report, only in Rollup or MaterializedIndexMeta is true
+    // If the process is replaying log, isReplay is true, otherwise is false,
+    // avoid replay process error report, only in Rollup or MaterializedIndexMeta is true
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:138]:
```suggestion
    // avoid throwing error during replay process, only in Rollup or MaterializedIndexMeta is true
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java [hunk 5]
```diff
@@ -291,84 +262,76 @@ public <R, C> R accept(AstVisitor<R, C> visitor, C context) {
...
 
-    public static void analyze(StatementBase stmt, ConnectContext session) {
-        new OldMVAnalyzerVisitor().visit(stmt, session);
-    }
+    public void analyze(ConnectContext context) {
+        QueryStatement queryStatement = this.getQueryStatement();
+        long originSelectLimit = context.getSessionVariable().getSqlSelectLimit();
+        // ignore limit in creating mv
+        context.getSessionVariable().setSqlSelectLimit(SessionVariable.DEFAULT_SELECT_LIMIT);
+        context.getSessionVariable().setSqlSelectLimit(originSelectLimit);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:270]: why here? bug?

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java [hunk 6]
```diff
@@ -291,84 +262,76 @@ public <R, C> R accept(AstVisitor<R, C> visitor, C context) {
...
-                throw new SemanticException("Do not support alter non-OLAP table[" + table.getName() + "]");
-            } else if (!(table instanceof OlapTable)) {
-                throw new SemanticException("The materialized view only support olap table.");
-            }
-            TableName tableName = entry.getKey();
-            statement.setBaseIndexName(table.getName());
-            statement.setDBName(tableName.getDb());
+        // forbid explain query
+        if (queryStatement.isExplain()) {
+            throw new IllegalArgumentException("Materialized view does not support explain query");
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:276]:
```suggestion
            throw new IllegalArgumentException("Creating materialized view does not support explain query");
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java [hunk 7]
```diff
@@ -414,139 +379,177 @@ private static int genColumnAndSetIntoStmt(CreateMaterializedViewStmt statement,
...
+                            existedDefinedExpr.toSqlWithoutTbl(), mvColumnItem.getDefineExpr().toSqlWithoutTbl()));
+                }
             }
         }
         if (beginIndexOfAggregation == 0) {
             throw new SemanticException("Only %s found in the select list. " +
                     "Please add group by clause and at least one group by column in the select list", joiner);
         }
-        statement.setMvColumnItemList(mvColumnItemList);
+        this.setMvColumnItemList(mvColumnItemList);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:429]:
```suggestion
        setMvColumnItemList(mvColumnItemList);?
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java [hunk 8]
```diff
@@ -586,22 +589,22 @@ private static void analyzeOrderByClause(CreateMaterializedViewStmt statement,
     /*
     This function is used to supply order by columns and calculate short key count
     */
-    private static void supplyOrderColumn(CreateMaterializedViewStmt statement) {
-        List<MVColumnItem> mvColumnItemList = statement.getMVColumnItemList();
+    private void supplyOrderColumn() {
+        List<MVColumnItem> mvColumnItemList = this.getMVColumnItemList();
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:593]: no need to add this?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java [hunk 9]
```diff
@@ -64,13 +64,7 @@ public boolean match(Expr expr) {
             if (!child0FnExpr.getFnName().getFunction().equalsIgnoreCase(FunctionSet.TO_BITMAP)) {
                 return false;
             }
-            SlotRef slotRef = child0FnExpr.getChild(0).unwrapSlotRef();
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java:67]: why remove this check?

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java:67]: Now we can support non-slot ref expressions, eg to_bitmap(a * 100)

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java (hunk 5 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java:270]: no need `OldMVAnalyzerVisitor ` visitor any more because only `visitCreateMaterializedViewStmt ` is hit, just mov old visitCreateMaterializedViewStmt' codes here.

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java (hunk 3 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/ast/MVColumnItem.java:61]: We can support more complex expressions later, eg, a+b as Sync MV's column.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java (hunk 2 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: fix it.

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java (hunk 4 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStmt.java]: done

**Review by ABingHuang — DISMISSED** [review]

**Review by ABingHuang — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 214 / 246 (86.99%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|13|19|68.42%|[490, 493, 498, 499, 517, 518]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|123|149|82.55%|[237, 238, 240, 241, 242, 285, 293, 308, 309, 312, 313, 317, 318, 358, 359, 363, 364, 365, 398, 409, 420, 421, 422, 444, 488, 489]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnBitmapUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MVUtils.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/StatisticExecutor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AstToSQLBuilder.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/analysis/Expr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/MVColumnItem.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnOneChildPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/task/AlterReplicaTask.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/mvpattern/MVColumnPercentileUnionPattern.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/MaterializedViewRule.java|12|12|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|2|2|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
