### PR TITLE
[Enhancement] Refine error prompt

### LINKED ISSUE #34321: broker load failed without detail error message
## Enhancement
sRqwv3Z5AR

The error message "listPath failed" is not helpful for troubleshooting issues. More specific error information should be displayed.

### PR DESCRIPTION
**Pull request by sduzh**
Fixes #34321

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by kevincai — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java [hunk 1]
```diff
@@ -1193,7 +1193,7 @@ public List<FileStatus> listFileMeta(String path, Map<String, String> properties
             throw new UserException("file not found: " + path, e);
         } catch (Exception e) {
             LOG.error("errors while get file status ", e);
-            throw new UserException("listPath failed", e);
+            throw new UserException(e.getMessage(), e);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java:1196]: Why not give the operation at the same time;
Like `"Fail to get file status because " + e.getMessage()`

**Review by kevincai — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java (hunk 1 above)
Comment (sduzh) [reply fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java]: updated, @imay PTAL

**Review by imay — APPROVED** [review]
