### PR TITLE
[Enhancement] Change the parameter strict_mode to null_if_not_found of dict_mapping function(#40897)

### LINKED ISSUE #40897: [BugFix] Fix dict_mapping problems
Problem:
1. Crash when using dict_mapping function with multiple key columns(In debug mode)
2. Crash if there is null value in key columns
3. Crash if there specify NOT bigint type value in value list for insert stmt
4. db not selected if dict_mapping function used in streamload with table name without dbname
5. Do not support type cast for dict_mapping function parameter automatically.
6. Boolean parameter's behavior which indicate return null or exception for dict_mapping if key is not found is unexpected.

Solution:
1. Reset key chunk row in dict_query_expr
2. return error if there is null value for key.
3. Fix the return type for DictQueryOperator
4. Add dbname when analyze load plan for streamload
5. Cast the type in expressionAnalyzer if it can be cast to target type.
6. Change boolean parameter's behavior, if it is false (default) return exception if key not found, if true, return null if key not found.

### PR DESCRIPTION
**Pull request by srlch**
The last optional parameter for dict_mapping is strict_mode(boolean), and its behavior if following:

If strict_mode is True : return an exception if the key is not found in dictionary table.
If strict_mode is False(Default) : return null if the key is not found in dictionary table.

We change the strict_mode into null_if_not_found to make more clear for user to use this function, and the behavior of null_if_not_found is following:
If null_if_not_found is True : return null if the key is not found in dictionary table.
If null_if_not_found is False(Default) : return an exception if the key is not found in dictionary table.

Fixes #40897

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [x] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/exprs/dict_query_expr.cpp [hunk 1]
```diff
@@ -33,6 +33,7 @@ DictQueryExpr::DictQueryExpr(const TExprNode& node) : Expr(node), _dict_query_ex
 StatusOr<ColumnPtr> DictQueryExpr::evaluate_checked(ExprContext* context, Chunk* ptr) {
     Columns columns(children().size());
     size_t size = ptr != nullptr ? ptr->num_rows() : 1;
+    bool null_if_not_found = !_dict_query_expr.strict_mode;
```
Comment (trueeyu) [inline be/src/exprs/dict_query_expr.cpp:36]: If later insert_to_dict_table_if_not_found, how to name the session variables.

Comment (trueeyu) [reply be/src/exprs/dict_query_expr.cpp:36]: null_if_not_found, insert_if_not_found, exception_if_not_found ?

**Review by trueeyu — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Review by trueeyu — DISMISSED** [review]

**Review by wyb — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by packy92 — APPROVED** [review]
