### PR TITLE
[BugFix] Set initial value type to size_t to avoid overflow

### LINKED ISSUE #10742: [persistent index] BE crash because of bad_alloc when primary table stream load
### Steps to reproduce the behavior (Required)
BE crash:
```
tcmalloc: large alloc 12935438336 bytes == 0x1cebb6000 @  0x5efbe99 0x618559c 0x2632b30 0x60d3335 0x2317775 0x231793c 0x231abd9 0x231bee9 0x231e430 0x206d80e 0x1ef2d8e 0x1ef73d3 0x26ede25 0x26e925a 0x7fdc9db1bea5
tcmalloc: large alloc 12935438336 bytes == 0x4d2be8000 @  0x5efbe99 0x618559c 0x2632b30 0x60d3335 0x2317775 0x231793c 0x231abd9 0x231bee9 0x231e430 0x206d80e 0x1ef2d8e 0x1ef73d3 0x26ede25 0x26e925a 0x7fdc9db1bea5
tcmalloc: large alloc 12935438336 bytes == 0x7d641a000 @  0x5efbe99 0x618559c 0x2632b30 0x60d3335 0x2317775 0x231793c 0x231abd9 0x231bee9 0x231e430 0x206d80e 0x1ef2d8e 0x1ef73d3 0x26ede25 0x26e925a 0x7fdc9db1bea5
tcmalloc: large alloc 12935438336 bytes == 0xada44c000 @  0x5efbe99 0x618559c 0x2632b30 0x60d3335 0x2317775 0x231793c 0x231abd9 0x231bee9 0x231e430 0x206d80e 0x1ef2d8e 0x1ef73d3 0x26ede25 0x26e925a 0x7fdc9db1bea5
tcmalloc: large alloc 413933789184 bytes == (nil) @  0x5efbe99 0x618559c 0x2632b30 0x60d3335 0x2317775 0x231793c 0x231abd9 0x231bee9 0x231e430 0x206d80e 0x1ef2d8e 0x1ef73d3 0x26ede25 0x26e925a 0x7fdc9db1bea5
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
*** Aborted at 1662094956 (unix time) try "date -d @1662094956" if you are using GNU date ***
PC: @     0x7fdc9c519387 __GI_raise
*** SIGABRT (@0x3e80000dbae) received by PID 56238 (TID 0x7fdc80bd1700) from PID 56238; stack trace: ***
    @          0x472db72 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fdc9db23630 (unknown)
    @     0x7fdc9c519387 __GI_raise
    @     0x7fdc9c51aa78 __GI_abort
    @          0x1cd2f17 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x60d2dd6 __cxxabiv1::__terminate()
    @          0x60d2e41 std::terminate()
    @          0x60d2f95 __cxa_throw
    @          0x1cd2e1e _Znwm.cold
    @          0x2312037 starrocks::ImmutableIndexShard::try_create()
    @          0x2317775 starrocks::ImmutableIndexShard::create()
    @          0x231793c starrocks::ImmutableIndexWriter::write_shard()
    @          0x231abd9 starrocks::PersistentIndex::_merge_compaction()
    @          0x231bee9 starrocks::PersistentIndex::_check_and_flush_l0()
    @          0x231e430 starrocks::PersistentIndex::commit()
    @          0x206d80e starrocks::PrimaryIndex::commit()
    @          0x1ef2d8e starrocks::TabletUpdates::_apply_rowset_commit()
    @          0x1ef73d3 starrocks::TabletUpdates::do_apply()
    @          0x26ede25 starrocks::ThreadPool::dispatch_thread()
    @          0x26e925a starrocks::Thread::supervise_thread()
    @     0x7fdc9db1bea5 start_thread
    @     0x7fdc9c5e1b0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
2.4.0-0901-133fd49
```

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10742 

## Problem Summary(Required) ：

The result type of function `std::accumulate` is the same as the initial value, and the default type of initial value is `int32`. So if the total l1 file size is more than 2GB, the following code will cause an overflow exception.

```
        const auto l1_kv_pairs_size = std::accumulate(std::next(_l1->_shards.begin(), l1_shard_offset),
                                                      std::next(_l1->_shards.begin(), l1_shard_offset + l1_shard_size),
                                                      0, [](size_t s, const auto& e) { return s + e.size; });
        const auto l1_kv_pairs_usage = std::accumulate(std::next(_l1->_shards.begin(), l1_shard_offset),
                                                       std::next(_l1->_shards.begin(), l1_shard_offset + l1_shard_size),
                                                       0, [](size_t s, const auto& e) { return s + e.bytes; });
``` 

So we set the initial value type to `size_t` to avoid overflow

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Comment by sevev** [comment]
run starrocks_admit_test

File: be/src/storage/persistent_index.cpp [hunk 1]
```diff
@@ -497,7 +497,7 @@ Status ImmutableIndexWriter::write_shard(size_t key_size, size_t npage_hint, siz
         _total_kv_size += (key_size + kIndexValueSize) * kvs.size();
     } else {
         _total_kv_size +=
-                std::accumulate(kvs.begin(), kvs.end(), 0, [](size_t s, const auto& e) { return s + e.size; });
+                std::accumulate(kvs.begin(), kvs.end(), (size_t)0, [](size_t s, const auto& e) { return s + e.size; });
```
Comment (trueeyu) [inline be/src/storage/persistent_index.cpp:500]: Won't it be automatically converted to size_t here?

Comment (sevev) [reply be/src/storage/persistent_index.cpp:500]: > Won't it be automatically converted to size_t here?

No auto conversion from test results

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Comment by Linkerist** [comment]
not only here exist this problem, there are several std::accumulate elsewhere.
