### PR TITLE
[BugFix] Fix dictionary problem and refactor rpc interface (#35559)

### LINKED ISSUE #35559: [Feature] Support Dictionary
Support Dictionary

### PR DESCRIPTION
**Pull request by srlch**
What I'm doing:
(1) Fix problem:
    1. rename DictionaryExpr into DictionaryGetExpr (be, fe, TExprNodeType, TDictionaryExpr -> TDictionaryGetExpr)
    2. rename DictionaryExprOperator -> DictionaryGetOperator
    3. return if error happen in refresh_dictionary_cache_begin/refresh_dictionary_cache_commit
    4. use .reset instead of ->reset in DictionaryCacheManager::refresh to release the memory consume
    5. remove storage_engine.h in rumtime_state.cpp
    6. release chunk and schea when get http stub failed in dictionary_writer
    7. remove useless scope in dictionary_get_expr

(2) Refactor, merge rpc function into one

(3) add more Be UT

Fixes #35559

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by fzhedu — DISMISSED** [review]

File: be/src/service/internal_service.cpp [hunk 1]
```diff
@@ -777,81 +777,62 @@ void PInternalServiceImplBase<T>::get_file_schema(google::protobuf::RpcControlle
...
-
-template <typename T>
-void PInternalServiceImplBase<T>::get_dictionary_statistic(google::protobuf::RpcController* controller,
-                                                           const PGetDictionaryStatisticRequest* request,
-                                                           PGetDictionaryStatisticResult* response,
-                                                           google::protobuf::Closure* done) {
-    ClosureGuard closure_guard(done);
-    StorageEngine::instance()->dictionary_cache_manager()->get_info(request->dict_id(), *response);
-    Status::OK().to_protobuf(response->mutable_status());
+    return;
```
Comment (trueeyu) [inline be/src/service/internal_service.cpp:835]: remove return?

File: be/test/storage/lake/local_pk_index_manager_test.cpp [hunk 2]
```diff
@@ -91,6 +91,7 @@ class LocalPkIndexManagerTest : public TestBase {
     int64_t _partition_id = next_id();
 };
 
+/*
```
Comment (trueeyu) [inline be/test/storage/lake/local_pk_index_manager_test.cpp:94]: why remove the test case?

File: fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java [hunk 3]
```diff
@@ -149,6 +144,41 @@ public void scheduleTasks() {
...
+            try {
+                Future<PProcessDictionaryCacheResult> future =
+                        BackendServiceClient.getInstance().processDictionaryCache(address, request);
+                result = future.get();
+            } catch (Exception e) {
+                LOG.warn(" processDictionaryCache failed in: " + address + " rpc error :" + e.getMessage());
+                if (errMsg != null) {
+                    errMsg = e.getMessage();
+                }
+                return true;
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java:161]: true meas fail?

File: fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java [hunk 4]
```diff
@@ -652,32 +636,12 @@ private void commit() {
...
-                if (code != TStatusCode.OK) {
-                    LOG.warn(" RefreshDictionaryCacheCommit failed in: " + address + " err " + result.status.errorMsgs);
-                    errMsg = result.status.errorMsgs.size() == 0 ? "" : result.status.errorMsgs.get(0);
-                    error = true;
-                    return;
-                }
-            }
-
-            LOG.info("finish RefreshDictionaryCacheCommit dictionary id: {}, txn id: {}", request.dictId, request.txnId);
+            error = DictionaryMgr.processDictionaryCacheInteranl(request, errMsg, beNodes, null);
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java:644]: error is not handled?

File: be/src/service/internal_service.cpp (hunk 1 above)
Comment (srlch) [reply be/src/service/internal_service.cpp:835]: done

File: fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java (hunk 3 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java:161]: yes

File: fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java (hunk 4 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java:644]: It will handle in another place, not here

File: be/test/storage/lake/local_pk_index_manager_test.cpp (hunk 2 above)
Comment (srlch) [reply be/test/storage/lake/local_pk_index_manager_test.cpp]: fix it, mistake

**Review by trueeyu — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
