### PR TITLE
[BugFix] Expr prepare() should do only once

### LINKED ISSUE #33852: Lambda arguments get ids failed, just get 2 ids from 1 arguments. backend:59edfc7d0cc1
### Steps to reproduce the behavior (Required)
Unzip [bug.zip](https://github.com/StarRocks/starrocks/files/13192244/bug.zip)
Edit bug.sh, changing `<your docker image>` to a valid image
run bug.sh

### Expected behavior (Required)
Shouldn't fail

### Real behavior (Required)
ERROR 1064 (HY000) at line 28: Lambda arguments get ids failed, just get 2 ids from 1 arguments. backend:59edfc7d0cc1

### StarRocks version (Required)
branch-3.1-cs, commit 68bd0348

### PR DESCRIPTION
**Pull request by fzhedu**
Fixes https://github.com/StarRocks/starrocks/issues/33852

rf clone the expr that was prepared, then prepare again, result into crashing. To fix it,  prepared state of expressions are safely reenterable.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: be/src/exprs/lambda_function.cpp [hunk 1]
```diff
@@ -28,6 +28,10 @@ namespace starrocks {
 LambdaFunction::LambdaFunction(const TExprNode& node) : Expr(node, false), _common_sub_expr_num(node.output_column) {}
 
 Status LambdaFunction::prepare(starrocks::RuntimeState* state, starrocks::ExprContext* context) {
+    if (_is_prepared) {
+        return Status::OK();
+    }
+    _is_prepared = true;
```
Comment (imay) [inline be/src/exprs/lambda_function.cpp:34]: This should be set to false in the close function.

**Review by imay — CHANGES_REQUESTED** [review]
I don't think your change can fix the issue.
The real execution sequence is 
prepare, close, prepare.
not 
prepare, prepare
close will destroy some member variable

File: be/src/exprs/lambda_function.cpp (hunk 1 above)
Comment (fzhedu) [reply be/src/exprs/lambda_function.cpp:34]: @imay the rf push down expr to scan, then a expr will be shared among scan and project. The project will prepare the expr, following the scan also prepare the expr, then project-open, scan-open .... scan-close, project-close.

Comment (imay) [reply be/src/exprs/lambda_function.cpp:34]: what is the relation between open, prepare and close?

Comment (fzhedu) [reply be/src/exprs/lambda_function.cpp:34]: prepare->open->eval->close is a whole calling chain. prepare may init some states, which should be exist until deleting the expr. open-eval-close is called per task, like in some scan tasks.

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by fzhedu** [comment]
@mergify backport branch-3.1-cs
