### PR TITLE
Do not compare versionHash when looking up replica for backup

### LINKED ISSUE #580: Backup failed to choose replica to make snapshot for tablet
### Steps to reproduce the behavior (Required)
backup table whose table version hash is inconsistent with partition version hash.

### Expected behavior (Required)
backup should succeed.

### Real behavior (Required)
image

### StarRocks version (Required)
1.18.1

### PR DESCRIPTION
**Pull request by gengjun-git**
Fix #580 
VersionHash has been deprecated.
Do not compare versionHash when looking up replica for backup.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java [hunk 1]
```diff
@@ -670,7 +669,7 @@ private boolean validateLocalFile(String filePath) {
      * Choose a replica order by replica id.
      * This is to expect to choose the same replica at each backup job.
      */
-    private Replica chooseReplica(Tablet tablet, long visibleVersion, long visibleVersionHash) {
+    private Replica chooseReplica(Tablet tablet, long visibleVersion) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java:672]: Please add some comments

**Review by chaoyli — APPROVED** [review]

**Review by wyb — APPROVED** [review]
