### PR TITLE
[BugFix] Fix desc storage volume privilege error msg

### LINKED ISSUE #26910: [storage volume] error message is unreasonable when user have no permission
### Steps to reproduce the behavior (Required)
```
CREATE STORAGE VOLUME
mysv1
TYPE = S3
LOCATIONS = ("s3://xxx/")
COMMENT "default storage"
PROPERTIES(
    "aws.s3.region" = "xxx",
    "aws.s3.endpoint" = "xxx",
    "aws.s3.use_aws_sdk_default_behavior" = "false",
    "aws.s3.use_instance_profile" = "false",
    "aws.s3.access_key" = "xxx",
    "aws.s3.secret_key" = "xxx"
);
create user jack identified by '123456';
```

login as jack

`desc STORAGE VOLUME mysv1;`

### Expected behavior (Required)
`reasonable error message`
### Real behavior (Required)
`ERROR 1064 (HY000): Getting analyzing error. Detail message: Access denied; you need (at least one of) the DESC STORAGE VOLUME privilege(s) for this operation.`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-5a3acb9`

### PR DESCRIPTION
**Pull request by TszKitLo40**
Fixes #26910 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java [hunk 1]
```diff
@@ -319,7 +319,10 @@ public enum ErrorCode {
     ERR_UNKNOWN_PIPE(6011, new byte[] {'4', '2', '0', '0', '0'}, "Unknown pipe '%s'"),
     ERR_PIPE_EXISTS(6012, new byte[] {'4', '2', '0', '0', '0'}, "Pipe exists"),
     ERR_UNKNOWN_PROPERTY(6013, new byte[] {'4', '2', '0', '0', '0'}, "Unknown property %s"),
-    ERR_INVALID_PARAMETER(6013, new byte[] {'4', '2', '0', '0', '0'}, "Invalid parameter %s");
+    ERR_INVALID_PARAMETER(6013, new byte[] {'4', '2', '0', '0', '0'}, "Invalid parameter %s"),
+
+    ERR_PRIVILEGE_STORAGE_VOLUME_DENIED(6020, new byte[] {'4', '2', '0', '0', '0'},
+            "Access denied for user '%s' to storage volume '%s' when checking privilege");
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java:325]:
```suggestion
            "Access denied for user '%s' to storage volume '%s'");
```

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeChecker.java|2|2|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
