### PR TITLE
[BugFix] create or replace view supports modifying comments

### LINKED ISSUE #37281: Create or replace view doesn't update comment
### Steps to reproduce the behavior (Required)
1. `create or replace view test_view
comment 'test comment 1'
as (
    select "test" as test_column
)`

2. `select TABLE_NAME, TABLE_COMMENT from information_schema.tables WHERE
TABLE_NAME = 'test_view'`

3. `create or replace view test_view
comment 'test comment 2'
as (
    select "test 2" as test_column
);`

4. `select TABLE_NAME, TABLE_COMMENT from information_schema.tables WHERE
TABLE_NAME = 'test_view'`

### Expected behavior (Required)
Expected to get "test_view, test comment 2" on step 4

### Real behavior (Required)
Got "test_view, test comment 1" on step 4
Comment didn't get updated

### StarRocks version (Required)
3.1.1

### PR DESCRIPTION
**Pull request by Astralidea**
Why I'm doing:
create or replace view does not have the function of modifying comments

What I'm doing:
Add and improve this feature.

Fixes #37281

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by murphyatwork — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/persist/AlterViewInfo.java [hunk 1]
```diff
@@ -89,9 +97,17 @@ public boolean equals(Object other) {
...
         }
         AlterViewInfo otherInfo = (AlterViewInfo) other;
+        boolean commentEqual;
+        if (comment == null && otherInfo.getComment() == null) {
+            commentEqual = true;
+        } else if (comment != null) {
+            commentEqual = comment.equalsIgnoreCase(otherInfo.getComment());
+        } else {
+            commentEqual = false;
+        }
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/persist/AlterViewInfo.java:107]: StringUtils.equalsIgnoreCase(comment, otherInfo.getComment());

**Review by Seaven — APPROVED** [review]
