### PR TITLE
[Enhancement] clearer json parsing error

### LINKED ISSUE #7532: json parse error should be clearer
## Enhancement
When the json input of load contains character(s) that should be escaped, the returned error is `can not get first row of json`, which is very confusing.
```
CREATE TABLE `tbl_escape` (
  `id` int(11) NOT NULL COMMENT "",
  `val` varchar(10) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false"
);
```
```
> cat data.json
{"id": 1, "val": "1"} {"id": 1, "val": ""aaaa "}
> curl --location-trusted -u root:  'http://127.0.0.1:8082/api/db0/tbl_escape/_stream_load' \-X PUT \-H 'format: json' -T data.json
{
    "TxnId": 98,
    "Label": "stream_load_1655726352824",
    "Status": "Fail",
    "Message": "can not get first row of json",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 49,
    "LoadTimeMs": 2,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 0,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
```

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7532

## Problem Summary(Required) ：

This PR attaches the error returned by json parser to the `Message`.
```
{
    "TxnId": 115,
    "Label": "a2a415c5-4ba5-4249-a8a2-343f63737ad9",
    "Status": "Fail",
    "Message": "Failed to iterate document stream as object. error: Within strings, some characters must be escaped, we found unescaped characters",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 49,
    "LoadTimeMs": 2,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 0,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
```

### CODE REVIEW

File: be/src/exec/vectorized/json_scanner.cpp [hunk 1]
```diff
@@ -645,8 +645,9 @@ Status JsonReader::_build_slot_descs() {
 
     // get the first row of json.
     simdjson::ondemand::object obj;
-    if (!_parser->get_current(&obj).ok()) {
-        return Status::DataQualityError("can not get first row of json");
+    auto st = _parser->get_current(&obj);
+    if (!st.ok()) {
+        return Status::DataQualityError(fmt::format("can not get first row of json, err: {}", st.get_error_msg()));
```
Comment (chaoyli) [inline be/src/exec/vectorized/json_scanner.cpp:650]: "can not get first row of json" is not necessary.

Comment (rickif) [reply be/src/exec/vectorized/json_scanner.cpp]: updated.

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
