### PR TITLE
BugFix: make the variable take effect immediately when set as global

### LINKED ISSUE #2649: When connecting a non-master node, the set global variable command will not take effect in the current session.
### Steps to reproduce the behavior (Required)
1. connection to a no-master node
2. set global variable
 `set global exec_mem_limit=2147483649;`
3. show variable
  `show variables like 'exec_mem_limit';`

### Expected behavior (Required)
the result should be 2147483649

### Real behavior (Required)
but the result dose not change.

image

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
The follower forward `set global` to the master node. For the non-master node, the execution will not change the variables of the current session. The SetStmt needs to be executed again for the current session after success.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java [hunk 1]
```diff
@@ -54,13 +54,25 @@ private void setVariable(SetVar var) throws DdlException {
...
+    private boolean isSessionVar(SetVar var) {
+        return !(var instanceof SetPassVar
+                || var instanceof SetNamesVar
+                || var instanceof SetTransaction);
+    }
+
+    public void execute(boolean onlySessionVar) throws DdlException {
         for (SetVar var : stmt.getSetVars()) {
-            setVariable(var);
+            if (onlySessionVar) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java:69]: What's the difference between VariableMgr.setVar and setVariable?

File: fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java [hunk 2]
```diff
@@ -71,6 +80,18 @@ public void execute() throws Exception {
             MysqlStateType state = MysqlStateType.fromString(result.state);
             if (state != null) {
                 ctx.getState().setStateType(state);
+                if (state == MysqlStateType.EOF || state == MysqlStateType.OK) {
+                    afterForward();
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java:84]: If the follower execute failed, how to rollback it ?

File: fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java [hunk 3]
```diff
@@ -54,13 +54,25 @@ private void setVariable(SetVar var) throws DdlException {
...
     }
 
-    public void execute() throws DdlException {
+    private boolean isSessionVar(SetVar var) {
+        return !(var instanceof SetPassVar
+                || var instanceof SetNamesVar
+                || var instanceof SetTransaction);
+    }
+
+    public void execute(boolean onlySessionVar) throws DdlException {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java:67]: What's does the onlySessionVar meaning?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java:67]: If onlySessionVar is true, it will only set the session variables, and ignore others variables.

File: fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/qe/SetExecutor.java:69]: VariableMgr.setVar will only set the session variable.
setVariable will set the session variables and password. 
```java
private void setVariable(SetVar var) throws DdlException {
        if (var instanceof SetPassVar) {
            // Set password
            SetPassVar setPassVar = (SetPassVar) var;
            ctx.getCatalog().getAuth().setPassword(setPassVar);
        } else if (var instanceof SetNamesVar) {
            // do nothing
            return;
        } else if (var instanceof SetTransaction) {
            // do nothing
            return;
        } else {
            VariableMgr.setVar(ctx.getSessionVariable(), var, false);
        }
}
```

File: fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java (hunk 2 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java:84]: It is not easy to ensure that the global settings and session settings are consistent, because rollback may also fail. We can add some hints and how to eliminate these inconsistencies, if the follower execute failed.

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
