### PR TITLE
[BugFix] generate statistics for empty iceberg table

### LINKED ISSUE #6840: read empty iceberg table will cause exception
### Steps to reproduce the behavior (Required)
1.
```
CREATE EXTERNAL TABLE `iceberg_t3` (
  `order_id` bigint(20) NULL COMMENT "",
  `order_time` datetime NULL COMMENT ""
) ENGINE=ICEBERG
COMMENT "ICEBERG"
PROPERTIES (
"database" = "iceberg_db",
"table" = "iceberg_t2",
"resource" = "iceberg0"
);
```
2.  `select * from iceberg_t3 where order_time > "2022-04-03 00:10:00"`

### Expected behavior (Required)
```
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:60) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:324) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:215) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:32) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:29) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1243) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitOperator(StatisticsCalculator.java:171) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeIcebergScanNode(StatisticsCalculator.java:259) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalIcebergScan(StatisticsCalculator.java:242) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalIcebergScan(StatisticsCalculator.java:135) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalIcebergScanOperator.accept(LogicalIcebergScanOperator.java:79) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:151) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:92) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:86) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:312) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
```
### Real behavior (Required)
select result

### StarRocks version (Required)
 -  branch-2.2

### PR DESCRIPTION
**Pull request by hongli-my**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6840

## Problem Summary(Required) ：
return  statistics for empty iceberg table, and record is zero.

### CODE REVIEW

**Comment by hongli-my** [comment]
@DorianZheng , plz  review it.   

I want to add  ut,  maybe add in  generate optimizedPlan,  but how to contruct iceberg table.

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java [hunk 1]
```diff
@@ -227,6 +221,10 @@ private IcebergFileStats generateIcebergFileStats(List<Expression> icebergPredic
         try (CloseableIterable<FileScanTask> fileScanTasks = tableScan.planFiles()) {
             for (FileScanTask fileScanTask : fileScanTasks) {
                 DataFile dataFile = fileScanTask.file();
+                // ignore this data file.
+                if (dataFile.recordCount() == 0) {
```
Comment (hongli-my) [inline fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:225]: ingore empty orc file  or  to check corruptedStats is null.

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java [hunk 2]
```diff
@@ -96,16 +93,13 @@ private Statistics makeTableStatistics(List<Expression> icebergPredicates,
         LOG.debug("Begin to make iceberg table statistics!");
         List<Types.NestedField> columns = icebergTable.schema().columns();
         IcebergFileStats icebergFileStats = generateIcebergFileStats(icebergPredicates, columns);
-        if (icebergFileStats == null) {
-            return Statistics.builder().build();
```
Comment (caneGuy) [inline fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:100]: why remove this? i wonder if this will cause wrong plan or not

**Review by caneGuy — COMMENTED** [review]
other LGTM

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java (hunk 2 above)
Comment (hongli-my) [reply fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:100]: `makeTableStatistics` or `makeColumnStatistics`  is `return null` will cause  compute statistics fail for empty table.

but in my cause,  only call  `makeColumnStatistics` function . so `makeTableStatistics` can return null statistics ?

**Comment by hongli-my** [comment]
run starrocks_fe_unittest

**Review by DorianZheng — APPROVED** [review]
LGTM

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java [hunk 3]
```diff
@@ -66,27 +66,24 @@ private List<ColumnStatistic> makeColumnStatistics(List<Expression> icebergPredi
...
+            List<ColumnRefOperator> columnList = colRefToColumnMetaMap.keySet().stream().filter(
+                    key -> key.getName().equalsIgnoreCase(idColumn.getValue())).collect(Collectors.toList());
+            if (columnList == null || columnList.size() != 1) {
+                LOG.debug("This column is not required column name " + idColumn.getValue() + " column list size "
+                        + (columnList == null ? "null" : columnList.size()));
+                continue;
             }
+
+            int fieldId = idColumn.getKey();
+            columnStatistics.add(
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:85]: @hongli-my Cuz we are not able to get ndv from table file, so the column statistics will be set to unknown any way. cc @caneGuy @dirtysalt

**Comment by DorianZheng** [comment]
run starrocks_fe_unittest

**Review by DorianZheng — CHANGES_REQUESTED** [review]
plz add ut

**Comment by hongli-my** [comment]
> plz add ut

done,       I mock  currentSnapshot function to  return null  to  generate IcebergFileStats

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 17 (05.88%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java|1|17|05.88%|[70, 71, 72, 74, 75, 76, 77, 78, 79, 80, 81, 84, 85, 86, 225, 226]|

**Comment by wangruin** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java [hunk 4]
```diff
@@ -96,16 +93,13 @@ private Statistics makeTableStatistics(List<Expression> icebergPredicates,
...
-            return Statistics.builder().build();
-        }
 
         Map<Integer, String> idToColumnNames = columns.stream()
                 .filter(column -> column.type().isPrimitiveType())
                 .collect(Collectors.toMap(Types.NestedField::fieldId, column -> column.name()));
 
         Statistics.Builder statisticsBuilder = Statistics.builder();
-        double recordCount = Math.max(icebergFileStats.getRecordCount(), 1);
+        double recordCount = Math.max(icebergFileStats == null ? 0 : icebergFileStats.getRecordCount(), 1);
```
Comment (caneGuy) [inline fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:102]: what's the difference between NaN and 0? @Youngwb

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java (hunk 4 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/external/iceberg/cost/IcebergTableStatisticCalculator.java:102]: 0 means no rows，NaN is not a legal state for row count

**Review by caneGuy — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.4
