### PR TITLE
[BugFix] Fix potential huge leader fe memory occupation when load profile is enabled

### LINKED ISSUE #43715: Leader FE's heap size increased quickly with many non-transactional stream loads tasks finished
### Steps to reproduce the behavior (Required)
1. enable stream load profile by `set enable_load_profile = true`
2. continuously running many non-transactional stream loads tasks
3. observing the leader FE's `JVM Heap Size` metrics

### Real behavior (Required)

Leader FE's `JVM Heap Size` is increasing with more and more stream load tasks finished.

### StarRocks version (Required)
 - 3.2.4

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

Fixes #43715

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java [hunk 1]
```diff
@@ -997,8 +997,12 @@ public void afterCommitted(TransactionState txnState, boolean txnOperated) throw
...
         // sync stream load collect profile
-        if (isSyncStreamLoad() && coord.isProfileAlreadyReported()) {
-            collectProfile();
+        if (isSyncStreamLoad() && coord.isEnableLoadProfile()) {
+            if (coord.isProfileAlreadyReported()) {
+                // collect profile only when be has reported
+                collectProfile();
+            }
+            // make sure query info is unregistered
             QeProcessorImpl.INSTANCE.unregisterQuery(loadId);
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java:1006]: Mv `QeProcessorImpl.INSTANCE.unregisterQuery(loadId);` outside of if?

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java]: have moved it into `finally` block

**Review by trueeyu — DISMISSED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java [hunk 2]
```diff
@@ -1292,6 +1291,10 @@ public String getStateName() {
         return state.name();
     }
 
+    public TUniqueId getTUniqueId() {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java:1294]: interface seems unnecessary, in the unit test, the unique id is set manually, no need to get uniqueid from the task.

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java:1294]: sorry it's a mistake

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java:1294]: > interface seems unnecessary, in the unit test, the unique id is set manually, no need to get uniqueid from the task.

This method is used by unit test

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadTask.java:1294]: I mean in unit test, the unique id is set in the testbody, why not directly use the value instead of get the unique id again from the stream task?
