### PR TITLE
Fix bug CTAS for inlineView Query with branch 2.1

### LINKED ISSUE #5420: CTAS does not consider inlineView
### Steps to reproduce the behavior (Required)
1.
```
CREATE TABLE `duplicate_table_with_null` (
  `k1` date NULL COMMENT "",
  `k2` datetime NULL COMMENT "",
  `k3` char(20) NULL COMMENT "",
  `k4` varchar(20) NULL COMMENT "",
  `k5` boolean NULL COMMENT "",
  `k6` tinyint(4) NULL COMMENT "",
  `k7` smallint(6) NULL COMMENT "",
  `k8` int(11) NULL COMMENT "",
  `k9` bigint(20) NULL COMMENT "",
  `k10` largeint(40) NULL COMMENT "",
  `k11` float NULL COMMENT "",
  `k12` double NULL COMMENT "",
  `k13` decimal128(27, 9) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "V2"
```
2.
```
create table inlineview as select aa.k1, aa.k2
from (
select k1,k2 from duplicate_table_with_null
) aa
left join (
select a.k1,b.k2 from 
	(select k1,k2 from duplicate_table_with_null) a
	left join 
	(select k1,k2 from duplicate_table_with_null) b
	on a.k1=b.k1
) cc on aa.k1=cc.k1
```

### Expected behavior (Required)
Success.
### Real behavior (Required)

java.lang.NullPointerException: null
	at com.starrocks.sql.analyzer.CTASAnalyzer.transformCTASStmt(CTASAnalyzer.java:66) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:60) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:34) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:299) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) [starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$419(ReadListener.java:55) [starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener$$Lambda$76/1964807365.run(Unknown Source) [starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
	

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.1.4 & later

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5420

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java [hunk 1]
```diff
@@ -151,6 +136,35 @@ public Relation transformCTASStmt(CreateTableAsSelectStmt createTableAsSelectStm
...
     }
 
+    private int getReplicationNumAndGenTableRef(SelectStmt queryStmt, Map<String, Table> tableRefToTable) {
+        int defaultReplicationNum = 1;
+        List<TableRef> tableRefs = queryStmt.getTableRefs();
+        for (TableRef tableRef : tableRefs) {
+            String[] aliases = tableRef.getAliases();
+            if (tableRef instanceof InlineViewRef) {
+                InlineViewRef inlineViewRef = (InlineViewRef) tableRef;
+                getReplicationNumAndGenTableRef((SelectStmt) inlineViewRef.getViewStmt(), tableRefToTable);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java:146]: return ?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java [hunk 2]
```diff
@@ -151,6 +136,39 @@ public Relation transformCTASStmt(CreateTableAsSelectStmt createTableAsSelectStm
...
+        List<TableRef> tableRefs = queryStmt.getTableRefs();
+        for (TableRef tableRef : tableRefs) {
+            String[] aliases = tableRef.getAliases();
+            if (tableRef instanceof InlineViewRef) {
+                InlineViewRef inlineViewRef = (InlineViewRef) tableRef;
+                int detectReplicateNum = getReplicationNumAndGenTableRef((SelectStmt) inlineViewRef.getViewStmt(),
+                        tableRefToTable);
+                if (detectReplicateNum > defaultReplicationNum) {
+                    defaultReplicationNum = detectReplicateNum;
+
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java:150]:
```suggestion
}
```

**Review by wyb — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]
