### PR TITLE
[BugFix] Fix ctas nullable bug

### LINKED ISSUE #22085: nullable of table create by ctas is wrong
### Steps to reproduce the behavior (Required)
create external catalog hudi_catalog PROPERTIES("type"="hudi","hive.metastore.uris"="");
create database test;
use test;
create table ttt as select col_boolean,sum(col_float),max(col_int),min(length(col_string)),cast(avg(col_double) as int) from hudi_catalog.hudi_db.hudi_parquet_gzip group by 1 order by 1;

all fields of hudi_parquet_gzip are nullable,
but the col_boolean column's nullable of ttt is false

### Expected behavior (Required)
the col_boolean column's nullable of ttt is true
### Real behavior (Required)
the col_boolean column's nullable of ttt is false
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #22085 

## Problem Summary(Required) ：

Fix ctas column nullable bug
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Field.java [hunk 1]
```diff
@@ -55,7 +55,7 @@ public Field(String name, Type type, TableName relationAlias, Expr originExpress
         this.relationAlias = relationAlias;
         this.originExpression = originExpression;
         this.visible = visible;
-        this.isNullable = false;
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Field.java:58]: Are you sure modify this not effect other logical?

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/Field.java:58]: I add this field. the original default is true.

**Review by Youngwb — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/SelectAnalyzer.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Field.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
