### PR TITLE
[BugFix] Remove the deregister logic from container

### LINKED ISSUE #62915: Compute Node does not gracefully exit and deregister from FE Node on shutdown
### Steps to reproduce the behavior (Required)
Run Compute Node deployment [with StarRocks operator](https://github.com/StarRocks/starrocks-kubernetes-operator) using the default configuration (i.e no overrides on pre-stop hooks or other scripts).

Scale down the number of compute nodes running by changing the value of `starRocksCnSpec.replicas` to something less on the StarRocksCluster object definition, for example from `3` → `2`.

Wait for the node to shutdown and terminate. Observe that the Compute Node that was just terminated is still registered with the FE leader node but with StatusCode `DISCONNECTED`. This can be seen by running `SHOW COMPUTE NODES`. Additionally, the StarRocks operator node_info metric for the `cn_node_num` type dimension will report that the number of nodes in the `total` state is greater than the number of nodes in the `alive` state indicating there is an issue with one or more compute nodes. Finally, observe the repetitive logs from the FE leader node indicating that it is trying to and cannot resolve the address for the Compute Node that was just shut down. This should not happen as the FE should recognise that the Compute Node was gracefully shut down and hence it should not try and connect to it.

```sh
 WARNING: [Channel<313102>: (a-starrocks-in-share-data-mode-cn-2.a-starrocks-in-share-data-mode-cn-search.starrocks.
     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)                                 
     at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)                                        
     at io.grpc.grpclb.GrpclbNameResolver.doResolve(GrpclbNameResolver.java:63)                                     
     at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)                                      
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)                   
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)                   
     at java.base/java.lang.Thread.run(Thread.java:829)                                                              
 Caused by: java.net.UnknownHostException: a-starrocks-in-share-data-mode-cn-2.a-starrocks-in-share-data-mode-cn-sea 
     at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)                                     
     at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1533)                                          
     at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1386)                                           
     at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1307)                                           
     at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:632)                 
     at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:219)                                  
     ... 6 more                                                                                                      
 }
```

### Expected behavior (Required)

We expect that the compute node does a clean shutdown and de-registers itself from the leader FE Node. The FE node should not try and poll the compute node as it should be aware that it was removed and the operator metrics should indicate that all running nodes are healthy.

On a graceful exit of the compute node, when inspecting the logs, we should expect to see the entrypoint cleanup script run which does the deregistering https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/be/cn_entrypoint.sh#L140 and hence see the logs indicating so.

```sh
E20250904 03:52:07.084132 139650349562560 daemon.cpp:259] got signal: Terminated from pid: 1130481248, is going to exit
...
[Thu Sep  4 03:52:16 UTC 2025[] Receives signal to exit ...
[Thu Sep  4 03:52:16 UTC 2025[] Can't find /opt/starrocks/cn/bin/cn.pid!
[Thu Sep  4 03:52:16 UTC 2025[] try to drop myself(a-starrocks-in-share-data-mode-cn-2.a-starrocks-in-share-data-mode-cn-search.starrocks.svc.cluster.local) from FE ...
[Thu Sep  4 03:52:16 UTC 2025[] drop my self a-starrocks-in-share-data-mode-cn-2.a-starrocks-in-share-data-mode-cn-search.starrocks.svc.cluster.local:9050 ...
stream closed EOF for starrocks/a-starrocks-in-share-data-mode-cn-2 (cn)
```

### Real behavior (Required)

In versions 3.4.6+ we observe that the main application receives the `SIGTERM` but the entrypoint process does not and hence we are missing those logs indicating it is deregistering itself from the FE leader node.

```sh
E20250904 03:34:21.817762 134151544224512 daemon.cpp:259] got signal: Terminated from pid: 1606223648, is going to exit
...
stream closed EOF for starrocks/a-starrocks-in-share-data-mode-cn-2 (cn)
```

The bug was seemingly introduced in the following PR https://github.com/StarRocks/starrocks/pull/60481 which introduces a while loop to hang in the `stop_cn.sh` script which is run as a preStop hook in k8s.

In particular, the behaviour exhibited is that the script signals the main application to shut down, then enters a while loop that checks if the application has exited and `sleep`s for a second in between each check. The expected behaviour is that once the main application exits then [the preStop hook exits, thereby sending a SIGTERM to PID 1 ](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks)(the entrypoint) to shut down as the child process has shut down. However, what actually happens is that as soon as the child process (main application) shuts down, it immediately returns and exits the entrypoint https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/be/cn_entrypoint.sh#L188, thereby never encountering the SIGTERM and triggering the trap that does a graceful shutdown https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/be/cn_entrypoint.sh#L178. The suspicion is that the 1 second delay in the while loop between each check makes the logic error-prone to this race condition. There is not enough time for the preStopHook to finish running and send the `SIGTERM` to the entrypoint. Instead the entrypoint immediately exits and the preStopHook never finishes running.

You can confirm this behaviour as well by checking the system events of the pod which indicates that the PreStopHook fails. This is because once the main application is terminated and the entrypoint exits, the preStopHook is forcefully terminated as the container will no longer be running.

```
Events:
  Type     Reason             Age              From               Message
  ----     ------             ----             ----               -------
  Normal   Scheduled          37s              default-scheduler  Successfully assigned starrocks/a-starrocks-in-share-data-mode-cn-1 to ip-10-7-48-17.ap-southeast-2.compute.internal
  Normal   Pulled             38s              kubelet            Container image "starrocks/cn-ubuntu:3.4.7" already present on machine
  Normal   Created            38s              kubelet            Created container: cn
  Normal   Started            38s              kubelet            Started container cn
  Normal   Pulled             38s              kubelet            Container image "644975362233.dkr.ecr.ap-southeast-2.amazonaws.com/kitt/iam-sidecar:2.2.0" already present on machine
  Normal   Created            38s              kubelet            Created container: iam-sidecar
  Normal   Started            37s              kubelet            Started container iam-sidecar
  Normal   Killing            10s              kubelet            Stopping container cn
  Normal   Killing            10s              kubelet            Stopping container iam-sidecar
  Warning  Unhealthy          2s (x2 over 7s)  kubelet            Readiness probe failed: Get "http://10.7.47.109:8040/api/health": dial tcp 10.7.47.109:8040: connect: connection refused
  Warning  FailedPreStopHook  1s               kubelet            PreStopHook failed
```

Previously, before the introduced change, the preStop hook script would signal to terminate the main application then immediately exit, sending a SIGTERM to PID 1 which is the `cn_entrypoint.sh`. As this occurs immediately and the shutdown of the main application may take some time, the `trap` is always triggered. The `exit_clean` function which is triggered waits for the child process to shutdown before proceeding with the rest of the shut down process https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/be/cn_entrypoint.sh#L154 and so gracefully shuts down.

### Suggested Fix

I will raise a PR per the suggested fix here but am open to other suggestions. The proposal here would be to modify the trap to also respect clean exits i.e trap exit_clean SIGTERM EXIT. This should be the expected behaviour as the trap is injected after registering itself with the FE node https://github.com/StarRocks/starrocks/blob/main/docker/dockerfiles/be/cn_entrypoint.sh#L177 so on any exits, it should always do a cleanup.

The change has been tested in our cluster and resolves the issue described above.

### StarRocks version (Required)

3.4.7 - The bug looks like it was introduced in 3.4.6 based on testing versions prior and after and observing the behaviour.

### PR DESCRIPTION
**Pull request by yandongxiao**
## Why I'm doing:

There are two different scenarios of CN pod exit.

1. POD restart (due to config update or version upgrade) or crash
2. POD scale in

It is not necessary to deregister the CN POD in the first scenario while it is needed in the second scenario.

The operator will know the scale in op and do the deregistration, user should use the >= v1.11.1 operator version.

## What I'm doing:

Fixes #62915

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Comment by yandongxiao** [comment]
> @cursor review

I need to check how SIGKILL is handled

**Comment by yandongxiao** [comment]
> > @cursor review
> 
> I need to check how SIGKILL is handled

Regardless of whether the `preStop` configuration is `/opt/starrocks/cn/bin/stop_cn.sh` or `/opt/starrocks/cn/bin/stop_cn.sh -g`, after k8s uses SIGKILL or SIGTERM to kill the BE process, k8s will immediately send the SIGTERM signal to the entrypoint script, so it can always exit in a timely manner.

File: docker/dockerfiles/be/cn_entrypoint.sh [hunk 1]
```diff
@@ -139,30 +139,8 @@ drop_my_self()
...
-                else
-                    log_stderr "cn process $pid dead."
-                    break;
-                fi
-            done
-        fi
-    fi
-    # remove myself from FE
-    drop_my_self $svc_name
+    log_stderr "Got SIGTERM, exit ..."
```
Comment (kevincai) [inline docker/dockerfiles/be/cn_entrypoint.sh:142]: this makes `exit_clean` trap useless, so a cleaner way is remove exit_clean() and the corresponding signal trap.

File: docker/dockerfiles/be/cn_entrypoint.sh [hunk 2]
```diff
@@ -185,12 +163,8 @@ if [[ "x$LOG_CONSOLE" == "x1" ]] ; then
...
-    tail -n $nol $STARROCKS_HOME/log/cn.INFO
-    log_stderr "Last $nol lines of cn.out ..."
-    tail -n $nol $STARROCKS_HOME/log/cn.out
-fi
-exit $ret
+
+# the reason why we need to sleep here is to avoid the pod being killed by k8s
+# before the preStop hook is exited.
+# 120 is the default value of terminationGracePeriodSeconds
+sleep 120
```
Comment (kevincai) [inline docker/dockerfiles/be/cn_entrypoint.sh]: this makes the pod termination wait for 120seconds under no condition, brutal in prod env to hold a pod exit for additional 120 seconds.

[the remark this answers is not in the document]
Comment (yandongxiao) [reply docker/dockerfiles/be/cn_entrypoint.sh]: If the CN subprocess fails to start, there will indeed be an issue where the container cannot exit immediately, which is not a good practice. Our original intention was that the `entrypoint` script should only exit after the `preStop` script (whose main purpose is to kill the CN subprocess) has been successfully executed; otherwise, there will be an error indicating that the preStop script execution has failed. Determining whether the process was actively killed or encountered a startup exception based on the return code of the CN subprocess also does not seem to be a good option. In summary, I think we should adjust the sleep time to 5 seconds.

**Review by kevincai — COMMENTED** [review]
The key thing is, how to take the compatibility into consideration. The deregistration of CN node is only available since v1.11+, so there are two cases:
1. operator v1.11+, starrocks core removed the deregister logic completely, or
2. operator below v1.111, starrocks core still do the best to deregister the node.

For a long term view, option 1 is preferred. so the cn deregister logic shall be completely removed from starrocks core. However, if the user doesn't upgrade the operator to v1.11, it means the deregistration will be completely lost with only the entrypoint change.

Also consider remove the preStop hook for the pod, if the SIGTERM can be properly propagated to the CN/BE process, then exit. So the preStop hook can be returned to the user to do whatever they need to do before stop

File: docker/dockerfiles/be/cn_entrypoint.sh (hunk 1 above)
Comment (yandongxiao) [reply docker/dockerfiles/be/cn_entrypoint.sh:142]: Without a trap, script would have to execute the sleep operation, causing the container's exit time to increase.

File: docker/dockerfiles/be/cn_entrypoint.sh (hunk 2 above)
Comment (yandongxiao) [reply docker/dockerfiles/be/cn_entrypoint.sh]: Good catch. I have changed it to 5s.

[the remark this answers is not in the document]
Comment (yandongxiao) [reply docker/dockerfiles/be/cn_entrypoint.sh]: @kevincai here is my think.

[the remark this answers is not in the document]
Comment (kevincai) [reply docker/dockerfiles/be/cn_entrypoint.sh]: under what condition, the cn subprocess failed to start, but the entrypoint doesn't exit?

[the remark this answers is not in the document]
Comment (kevincai) [reply docker/dockerfiles/be/cn_entrypoint.sh]: the original preStop script is introduced because CN/BE had a bad exit behavior since v2.4/v2.5, a SIGTERM can rarely kill the be/cn process to exit quickly, that's why a prestop is introduced to stop with -g or stop directly without -g (kill -9) to force stop the be/cn process.

Since v3.2, the situation changes a lot, the exit behavior is properly maintained for most of the time, so we shall turn to the regular way to think about the exit procedure in k8s env.

File: docker/dockerfiles/be/cn_entrypoint.sh [hunk 3]
```diff
@@ -185,12 +163,9 @@ if [[ "x$LOG_CONSOLE" == "x1" ]] ; then
...
-    log_stderr "Last $nol lines of cn.out ..."
-    tail -n $nol $STARROCKS_HOME/log/cn.out
-fi
-exit $ret
+
+# The reason why we need to sleep here is to avoid the pod being killed by k8s
+# before the preStop hook is exited.
+# If the CN subprocess fails to start, we also want the entrypoint script to exit as soon as possible.
+# Taking all the above into consideration, we set it to five seconds.
+sleep 5
```
Comment (kevincai) [inline docker/dockerfiles/be/cn_entrypoint.sh]: this will override the exit code, no matter it is a normal exit or a crash or whatever, better keep the sam return code from start_cn.sh

Comment (kevincai) [reply docker/dockerfiles/be/cn_entrypoint.sh]: maybe we can do this:

```
if [[ $ret -eq 0 ]] ; then
    sleep 5
else
    exit $ret
fi
```

exit immediately if exit code is non-zero, otherwise sleep for a while to be favor of the preStop hook.

Comment (yandongxiao) [reply docker/dockerfiles/be/cn_entrypoint.sh]: I think this suggestion is fine. Previously, I always executed sleep 5 because I was unsure whether the normal exit logic of BE would return 0.

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by kevincai — APPROVED** [review]

**Review by wangruin — APPROVED** [review]
