### PR TITLE
[BugFix] Don't prune const group by keys if agg's predicates are not null

### LINKED ISSUE #17972: [sqlancer] query of result set mismatch
### Steps to reproduce the behavior (Required)
```sql
DROP DATABASE IF EXISTS h17;
CREATE DATABASE h17;
USE h17;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATETIME NULL ,c_0_1 DATETIME NULL ,c_0_2 DATETIME NOT NULL ,c_0_3 INT NOT NULL ,c_0_4 CHAR(21) NULL ,c_0_5 LARGEINT NOT NULL ,c_0_6 DECIMAL(30, 7)  NULL ,c_0_7 DATE NULL ,c_0_8 DATE NULL ,c_0_9 VARCHAR(11) NOT NULL ,c_0_10 TINYINT NULL ,c_0_11 BOOLEAN NULL ,c_0_12 DECIMAL(24, 9)  NOT NULL ,c_0_13 DECIMAL(35, 10)  NULL ,c_0_14 BOOLEAN NOT NULL ,c_0_15 DATETIME NOT NULL ,c_0_16 BOOLEAN NULL ,c_0_17 DECIMAL(8, 0)  NULL , INDEX index1_c_0_2(`c_0_2`) USING BITMAP, INDEX index1_c_0_10(`c_0_10`) USING BITMAP, INDEX index1_c_0_14(`c_0_14`) USING BITMAP) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11,c_0_12,c_0_13,c_0_14,c_0_15,c_0_16) PARTITION BY RANGE(c_0_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 94 day)) DISTRIBUTED BY HASH (c_0_8,c_0_5,c_0_2,c_0_14,c_0_4,c_0_13,c_0_3) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(14, 3)  NOT NULL ,c_1_1 DATE NULL ,c_1_2 DATETIME NOT NULL ,c_1_3 DECIMAL(4, 0)  NULL ,c_1_4 BOOLEAN NOT NULL ,c_1_5 SMALLINT REPLACE_IF_NOT_NULL NOT NULL ,c_1_6 LARGEINT SUM NOT NULL ,c_1_7 PERCENTILE PERCENTILE_UNION NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 791 day)) DISTRIBUTED BY HASH (c_1_0,c_1_4,c_1_2,c_1_3) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2010-01-05 08:00:14', '2010-01-26 08:00:14', '2010-01-25 08:00:14', 16, '', 1897146240, 6640905153312104.4056480, '2010-01-22', '2010-01-08', '8', 1, true, 580121.274796995, 628814425984832.5035023621, true, '2010-01-04 08:00:14', false, 84061900);
TRUNCATE TABLE t0;
INSERT INTO t0 VALUES ('2010-01-09 08:00:14', '2010-01-08 08:00:14', '2010-01-11 08:00:14', 20, 'IOO', 1897146240, 9909607389680132.9134909, '2010-01-09', '2010-01-22', '2', 7, true, 616039.346167272, 318181077837647.4857509993, true, '2010-01-16 08:00:14', true, 33946962), ('2010-01-19 08:00:14', '2010-01-29 08:00:14', '2010-01-25 08:00:14', 27, '94', 1897146240, 7679397674696844.0104739, '2010-01-09', '2010-01-19', 'c', 0, true, 778405.788062906, NULL, false, '2010-01-17 08:00:14', false, 32850087);
INSERT INTO t0 VALUES ('2010-01-17 08:00:14', '2010-01-21 08:00:14', '2010-01-30 08:00:14', 20, 'Kmy', -1500837745, 5937898085069690.5239721, NULL, '2010-01-30', '', 0, true, 297701.718807601, 2285329196417.3294559726, true, '2010-01-22 08:00:14', true, 32377884);
CREATE VIEW v0 AS SELECT t1_143.c_1_0, t1_143.c_1_1, t1_143.c_1_2, t1_143.c_1_3, t1_143.c_1_4, t1_143.c_1_5, t1_143.c_1_6 FROM t1 AS t1_143 WHERE true GROUP BY t1_143.c_1_0, t1_143.c_1_1, t1_143.c_1_2, t1_143.c_1_3, t1_143.c_1_4, t1_143.c_1_5, t1_143.c_1_6 ORDER BY t1_143.c_1_0, t1_143.c_1_0, t1_143.c_1_3, t1_143.c_1_2, t1_143.c_1_0, t1_143.c_1_1, t1_143.c_1_1;
INSERT INTO t1 VALUES (6234880.389, '2010-01-19', '2010-01-20 08:00:14', 1192, true, 2, 511130635, percentile_hash('-1586543464')), (76802069.421, '2010-01-02', '2010-01-03 08:00:14', 6467, false, 11, -1820042851, percentile_hash('580519679')), (23407116.062, NULL, '2010-01-04 08:00:14', 8785, true, 8, -2107870326, percentile_hash('1212629610')), (55659875.424, '2010-01-18', '2010-01-11 08:00:14', 2663, false, 14, -1453795718, percentile_hash('-1453795718'));
INSERT INTO t0 VALUES ('2010-01-05 08:00:14', '2010-01-07 08:00:14', '2010-01-23 08:00:14', 22, 'm', 1329360486, 3257289259528448.6135756, '2010-01-02', NULL, 't5xr5', 3, true, 863457.363939543, 36437563057771.3494062667, false, '2010-01-09 08:00:14', true, 42152268);
INSERT INTO t0 VALUES ('2010-01-13 08:00:14', '2010-01-20 08:00:14', '2010-01-04 08:00:14', 4, 'c5Rmy', 288715080, 9427781390477747.4368027, '2010-01-18', NULL, 'a', 1, true, 753742.738254159, NULL, false, '2010-01-03 08:00:14', false, NULL), ('2010-01-21 08:00:14', '2010-01-24 08:00:14', '2010-01-30 08:00:14', 26, 'EHxh', 2140362214, 3132963133170818.6470340, '2010-01-20', '2010-01-02', '', 2, false, 456101.368457764, 694798277985761.9917152160, true, '2010-01-22 08:00:14', true, 98260779), (NULL, '2010-01-12 08:00:14', '2010-01-11 08:00:14', 30, 'y', 292382021, 6503990111691422.2789247, '2010-01-29', '2010-01-24', 'r', 0, true, 336628.194814874, NULL, true, '2010-01-18 08:00:14', true, 85242758);
DELETE FROM t0 WHERE c_0_9 IS NULL AND c_0_16=false;
INSERT INTO t1 VALUES (94918099.853, '2010-01-05', '2010-01-28 08:00:14', 9501, false, 8, 580519679, percentile_hash('-657188452')), (71058151.222, '2010-01-24', '2010-01-04 08:00:14', 344, false, 12, 1092848882, percentile_hash('-1500837745')), (39476548.213, NULL, '2010-01-27 08:00:14', 5256, true, 5, 1962227832, percentile_hash('2035693513')), (45297795.388, '2010-01-09', '2009-12-31 08:00:14', 343, true, 9, 580519679, percentile_hash('-1586543464'));
INSERT INTO t1 VALUES (13680228.122, NULL, '2009-12-31 08:00:14', NULL, false, 0, -1525446617, percentile_hash('-882369145')), (25002389.567, '2010-01-31', '2010-01-22 08:00:14', 7966, true, 2, -2066010754, percentile_hash('-1625908138')), (12278212.283, '2010-01-11', '2010-01-21 08:00:14', 8780, false, 1, -1586543464, percentile_hash('1456692756'));
INSERT INTO t0 VALUES ('2010-01-31 08:00:14', '2010-01-18 08:00:14', '2010-01-15 08:00:14', 24, '', -1849399713, 4870876771567652.3203367, '2010-01-01', '2010-01-21', '', 6, true, 265688.416869328, 163440812956513.2483663271, false, '2010-01-10 08:00:14', true, 93391773), ('2010-01-27 08:00:14', '2010-01-21 08:00:14', '2010-01-07 08:00:14', 19, '', -657188452, 951887342485946.4661710, NULL, '2010-01-19', '', 7, false, 429392.859863663, 628197058684810.9050493789, false, '2010-01-31 08:00:14', false, 80504390);
INSERT INTO t0 VALUES ('2010-01-30 08:00:14', '2010-01-09 08:00:14', '2010-01-29 08:00:14', 18, '', -1354278486, NULL, '2010-01-16', '2010-01-26', '', NULL, NULL, 714332.966110445, 741151106927548.9305142035, false, '2010-01-17 08:00:14', true, 10850254), ('2010-01-12 08:00:14', '2010-01-10 08:00:14', '2010-01-02 08:00:14', 3, 'l', 1212629610, NULL, '2010-01-14', '2010-01-21', 'H', 0, true, 51362.597730629, 441392541628462.5313779265, false, '2010-01-19 08:00:14', true, NULL);
INSERT INTO t0 VALUES ('2010-01-11 08:00:14', '2010-01-10 08:00:14', '2010-01-08 08:00:14', 21, 'iQLTl1v4', -1820042851, 457739546290980.5710845, '2010-01-03', '2010-01-30', '020aVER', 2, true, 858644.729468570, 557021911925210.6665385645, true, '2010-01-04 08:00:14', false, 76434768), ('2010-01-01 08:00:14', '2010-01-06 08:00:14', '2010-01-19 08:00:14', 23, 'tR', -493309038, 8260230760112819.1375960, '2010-01-03', '2010-01-21', '5', 3, false, 91702.346473906, NULL, true, '2010-01-01 08:00:14', true, 29077996);
INSERT INTO t0 VALUES ('2010-01-09 08:00:14', '2010-01-06 08:00:14', '2010-01-12 08:00:14', 21, 'V', -1625908138, 9208917741654119.1146976, '2010-01-09', '2010-01-03', '', 2, true, 960262.484043482, 303416487152566.6384855216, true, '2010-01-10 08:00:14', true, 73008051);
INSERT INTO t1 VALUES (35160747.234, '2010-01-15', '2010-01-01 08:00:14', 8896, false, 13, 1329360486, percentile_hash('494640318')), (58451053.411, '2010-01-01', '2010-01-20 08:00:14', NULL, false, 10, 1, percentile_hash('-1721522492'));
INSERT INTO t0 VALUES ('2010-01-23 08:00:14', '2010-01-09 08:00:14', '2010-01-20 08:00:14', 21, 'CNbI0UMXF', -786907741, 4640324391212828.9310233, '2010-01-04', '2010-01-03', '', 1, true, 126814.694842502, 33592878015399.2434520660, false, '2010-01-09 08:00:14', true, NULL), ('2010-01-27 08:00:14', '2010-01-02 08:00:14', '2010-01-10 08:00:14', 31, 'N1PObtNk', -1625908138, 5655479541218113.6431909, NULL, '2010-01-24', '', 5, true, 48718.602147162, 1666392206817.4130686544, true, '2010-01-27 08:00:14', true, 25262792), ('2010-01-28 08:00:14', '2010-01-05 08:00:14', '2010-01-05 08:00:14', 6, '', -678822006, 8130189380018322.3077177, '2010-01-26', '2010-01-16', 'X3e90', 1, true, 861468.297089556, 221309644976943.6091514815, true, '2010-01-29 08:00:14', false, 74963935), ('2010-01-30 08:00:14', '2010-01-13 08:00:14', '2010-01-20 08:00:14', 28, 'NZfO', 979455029, NULL, '2010-01-09', '2010-01-21', '', 4, true, 560711.330031628, 529026184065041.4271181639, false, '2010-01-08 08:00:14', false, 19879904);
-- SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL;
-- cardinality: 1
-- SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING ((DROUND(0.09733420538671422) ) IS NOT NULL) UNION ALL SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING (NOT (((DROUND(0.09733420538671422) ) IS NOT NULL))) UNION ALL SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING ((((DROUND(0.09733420538671422) ) IS NOT NULL)) IS NULL);
-- cardinality: 3
```

### Real behavior (Required)
```sql
mysql> SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL;
+--------------+
| 15187596.591 |
+--------------+
| 15187596.591 |
+--------------+
1 row in set (0.05 sec)

mysql> SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING ((DROUND(0.09733420538671422) ) IS NOT NULL) UNION ALL SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING (NOT (((DROUND(0.09733420538671422) ) IS NOT NULL))) UNION ALL SELECT 15187596.591 FROM  v0 AS v0_149 RIGHT ANTI JOIN (SELECT t1_148.c_1_0, t1_148.c_1_1, t1_148.c_1_2, t1_148.c_1_3, t1_148.c_1_4, t1_148.c_1_5, t1_148.c_1_6 FROM t1 AS t1_148) subt1 ON v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 = subt1.c_1_2 AND v0_149.c_1_1 != subt1.c_1_4 AND v0_149.c_1_1 >= (v0_149.c_1_2)  BETWEEN (NULL) AND ('1970-01-10 17:02:26')  GROUP BY NULL HAVING ((((DROUND(0.09733420538671422) ) IS NOT NULL)) IS NULL);
+--------------+
| 15187596.591 |
+--------------+
| 15187596.591 |
| 15187596.591 |
| 15187596.591 |
+--------------+
3 rows in set (0.12 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```sql
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE b06b180 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by LiShuMing**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17972

## Problem Summary(Required) ：

```
        // If agg's predicate is not null, cannot prune it.
         // eg: select 1 from t group by null having 1=0, it returns empty rather than input + limit 1.
```

- TODO: Maybe we can const-folding the const operators  and return empty directly.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 1]
```diff
@@ -2117,6 +2117,41 @@ public void testPruneGroupByKeysRule() throws Exception {
                 "     limit: 1");
     }
 
+    @Test
+    public void testPruneGroupByKeysRule2() throws Exception {
+        String sql = "select 1 from test_all_type group by NULL " +
+                "having (NOT (((DROUND(0.09733420538671422) ) IS NOT NULL)))";
+        String plan = getFragmentPlan(sql);
+        System.out.println(plan);
+        // t1b+1 will be pruned
```
Comment (silverbullet233) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:2126]:
```suggestion
```

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 2]
```diff
@@ -2117,6 +2117,41 @@ public void testPruneGroupByKeysRule() throws Exception {
...
+                "  |  <slot 11> : NULL");
+    }
+
+    @Test
+    public void testPruneGroupByKeysRule3() throws Exception {
+        String sql = "select count(*), sum(t1b) from test_all_type group by NULL " +
+                "having (NOT (((DROUND(0.09733420538671422) ) IS NOT NULL)))";
+        String plan = getFragmentPlan(sql);
+        System.out.println(plan);
+        // t1b+1 will be pruned
```
Comment (silverbullet233) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:2144]:
```suggestion
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java|6|6|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneGroupByKeysRule.java|6|6|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by LiShuMing** [comment]
run starrocks_admit_test

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
