### PR TITLE
Fix binary predicate operator nullable

### LINKED ISSUE #2879: Query sql crash
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d0;
CREATE DATABASE d0;
USE d0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DECIMAL32(5, 1)  NOT NULL ,c_0_1 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_2 DECIMAL64(1, 0)  REPLACE_IF_NOT_NULL NULL ,c_0_3 BOOLEAN REPLACE NULL ,c_0_4 PERCENTILE PERCENTILE_UNION NULL ,c_0_5 PERCENTILE PERCENTILE_UNION NULL ,c_0_6 FLOAT REPLACE NULL ) AGGREGATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 BOOLEAN NOT NULL ,c_1_1 DATE NULL ,c_1_2 DECIMAL32(3, 3)  NOT NULL ,c_1_3 DATE NOT NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 BOOLEAN NULL ,c_2_1 BOOLEAN NULL ,c_2_2 DATETIME NULL ,c_2_3 CHAR(1) NOT NULL ,c_2_4 DECIMAL128(22, 16)  NOT NULL ,c_2_5 DATE NOT NULL ,c_2_6 DECIMAL64(12, 12)  NOT NULL ,c_2_7 DECIMAL128(14, 6)  NULL ,c_2_8 DECIMAL64(9, 6)  NOT NULL ,c_2_9 DECIMAL(13, 8)  SUM NULL ,c_2_10 HLL HLL_UNION NOT NULL ,c_2_11 DECIMAL(16, 5)  SUM NOT NULL ,c_2_12 DECIMAL32(5, 2)  REPLACE NOT NULL ,c_2_13 DECIMAL32(5, 1)  REPLACE NOT NULL ,c_2_14 VARCHAR(31) REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8) DISTRIBUTED BY HASH (c_2_6,c_2_2,c_2_5,c_2_7,c_2_3) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 TINYINT NOT NULL ,c_3_1 BOOLEAN NOT NULL ,c_3_2 DECIMAL64(15, 1)  NOT NULL ,c_3_3 DECIMAL32(8, 1)  NOT NULL ,c_3_4 BOOLEAN NULL ,c_3_5 DECIMAL64(1, 1)  NULL ,c_3_6 DATE NOT NULL ,c_3_7 CHAR(11) NULL ,c_3_8 DECIMAL64(17, 8)  NOT NULL ,c_3_9 BOOLEAN NULL ,c_3_10 DECIMAL64(16, 11)  NULL ,c_3_11 DECIMAL128(20, 14)  NOT NULL ,c_3_12 DECIMAL(16, 7)  NOT NULL ,c_3_13 TINYINT NOT NULL ,c_3_14 DECIMAL(9, 2)  NULL ,c_3_15 DECIMAL32(4, 1)  NULL ,c_3_16 DATE NOT NULL ,c_3_17 DOUBLE NULL ,c_3_18 DECIMAL32(4, 0)  NULL ) UNIQUE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6,c_3_7,c_3_8,c_3_9,c_3_10,c_3_11,c_3_12,c_3_13,c_3_14) DISTRIBUTED BY HASH (c_3_5,c_3_9,c_3_3,c_3_11,c_3_7,c_3_6,c_3_13,c_3_4,c_3_0) properties("replication_num"="1") ;
INSERT INTO t0 VALUES (121.3, percentile_hash("1000329950"), 0, NULL, percentile_hash("1372825108"), percentile_hash("65218225"), NULL);
INSERT INTO t3 VALUES (7, false, 8905262525853.0, 97273.1, false, NULL, "1970-01-01", "Qd", 5.44989810, NULL, 6.2843E-7, 2.26256E-9, 3.6147117, 7, 50023.48, 57.3, "1970-01-01", 0.4962472878021824, 960), (4, false, 2138960670422.8, 930035.4, NULL, 0.7, "1970-01-01", "", 8.34878130, true, 5.7546E-7, 4.17998E-9, 99.0539026, 2, 34184.24, NULL, "1970-01-01", NULL, 1527), (3, false, 747545165640.6, 48718.8, false, 0.8, "1970-01-01", "", 2.71779434, true, 2.3975E-7, 2.24133E-9, 46.4615224, 4, 93515.67, 22.0, "1970-01-01", 0.7168228208523933, 6798);
INSERT INTO t1 VALUES (false, "1970-01-01", 0.008, "1970-01-01"), (false, NULL, 0.002, "1970-01-01");
DELETE FROM t2 WHERE c_2_0=false AND c_2_7=15.741495 AND c_2_3="" AND c_2_5="1969-12-23" AND c_2_1=false AND c_2_8=0.000159;
INSERT INTO t3 VALUES (1, true, 6513569200104.1, 828078.9, false, 0.5, "1970-01-01", "xdM", 3.82361116, false, 6.7443E-7, 7.56234E-9, 78.8545013, 0, 13958.84, 64.4, "1970-01-01", 0.5204036158621744, 1791), (4, true, 3327995663644.8, 159830.6, true, 0.1, "1970-01-01", "6", 0.63047753, true, NULL, 2.44619E-9, 55.1143830, 5, NULL, 22.9, "1970-01-01", 0.6152024641175707, 2581), (6, true, 3921102886725.6, 629641.3, false, 0.7, "1970-01-01", "fGRV", 5.96640008, true, 1.6994E-7, 1.21215E-9, 91.3705135, 2, 6539.10, 30.7, "1970-01-01", NULL, 6863);
INSERT INTO t0 VALUES (222.7, percentile_hash("591949327"), 1, false, percentile_hash("-1401805116"), percentile_hash("-1809729890"), 0.6547019339699226), (775.9, percentile_hash("1043104834"), 3, true, percentile_hash("1749602374"), percentile_hash("-2110676122"), 0.24571422738508986);
INSERT INTO t0 VALUES (41.5, percentile_hash("-2069871153"), 2, false, percentile_hash("1133695085"), percentile_hash("1438478140"), NULL);
2.  SELECT DISTINCT * FROM (SELECT DISTINCT  ( t1.c_1_0 ) < ( t1.c_1_0 )  FROM  t1 LEFT ANTI JOIN t3 ON t1.c_1_1 = t3.c_3_7 AND t1.c_1_1 <= t3.c_3_7 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_0 <= t3.c_3_5 AND t1.c_1_0 >= t3.c_3_5 WHERE true UNION ALL SELECT DISTINCT  ( t1.c_1_0 ) < ( t1.c_1_0 )  FROM  t1 LEFT ANTI JOIN t3 ON t1.c_1_1 = t3.c_3_7 AND t1.c_1_1 <= t3.c_3_7 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_0 <= t3.c_3_5 AND t1.c_1_0 >= t3.c_3_5 WHERE (NOT (true)) UNION ALL SELECT DISTINCT  ( t1.c_1_0 ) < ( t1.c_1_0 )  FROM  t1 LEFT ANTI JOIN t3 ON t1.c_1_1 = t3.c_3_7 AND t1.c_1_1 <= t3.c_3_7 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_2 < t3.c_3_4 AND t1.c_1_0 <= t3.c_3_5 AND t1.c_1_0 >= t3.c_3_5 WHERE ((true) IS NULL)) t;

```
crash.log:
*** Aborted at 1642389845 (unix time) try "date -d @1642389845" if you are using GNU date ***
PC: @          0x21d5682 starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
*** SIGSEGV (@0xbcf6000) received by PID 6978 (TID 0x7f730c956700) from PID 198139904; stack trace: ***
    @          0x34682c2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f736343b630 (unknown)
    @          0x21d5682 starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
    @          0x21c4efa starrocks::vectorized::DistinctStreamingNode::get_next()
    @          0x1c8b68a starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1c8cfc5 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1c8db97 starrocks::PlanFragmentExecutor::open()
    @          0x1c2a542 starrocks::FragmentExecState::execute()
    @          0x1c2ea4c starrocks::FragmentMgr::exec_actual()
    @          0x1d53479 starrocks::ThreadPool::dispatch_thread()
    @          0x1d4f038 starrocks::Thread::supervise_thread()
    @     0x7f7363433ea5 start_thread
    @     0x7f73628388dd __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main Release
 - mysql> select current_version();
+-----------------------------+
| current_version()           |
+-----------------------------+
| SQLANCER_01_RELEASE 6d8e035 |
+-----------------------------+

### PR DESCRIPTION
**Pull request by Youngwb**
Fix #2879 

In #2770 , we use scalarOperaotr isNullale instead of expr at relation transform, but we do not use scalarOperator nullable at planFragement builder which is used for translate scalarOperator to expr, we should unify this logical.
The isNullable method of the binaryPredicateOperator has also been overridden

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java [hunk 1]
```diff
@@ -178,6 +178,9 @@ protected FunctionCallExpr(FunctionCallExpr other) {
                     .add(FunctionSet.MONTH)
                     .add(FunctionSet.DAY)
                     .add(FunctionSet.HOUR)
+                    .add(FunctionSet.ADD)
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java:181]: add for ut，because of we use CallOperator nullable instread of ArithmeticExpr

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by stdpain** [comment]
decimal add will return NULL when overflow happened

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java [hunk 2]
```diff
@@ -114,6 +114,10 @@ public boolean isNullable() {
         if (fn != null && !fn.isNullable()) {
             return false;
         }
+        // decimal operation may overflow
+        if (arguments.stream().anyMatch(argument -> argument.getType().isDecimalOfAnyVersion())) {
+            return true;
+        }
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java:120]: Add in liine 123?

Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/CallOperator.java]: done

**Review by kangkaisen — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
