### PR TITLE
[BugFix] Unable to build from source, fix cmake error and use correct dependencies specified by third-party, clean unused variable.

### LINKED ISSUE #23111: [Bug] The current Starrocks is not using the correct dependencies version, and also can't build correctly.
# TLDR; 
Users can't build Starrocks from the source. And Starrocks is now using incorrect dependencies which does not follow the restriction.

### Furthermore, even if we successfully pack the project for distribution, the several packages inside the libraries may come from the "packing machine", not the wanted versions of the library indicated in Starrocks' third-party restrictions.

# Steps to reproduce the behavior (Required)
git clone https://github.com/StarRocks/starrocks.git
cd starrocks
./build -j32 # just paralleled

# Expected behavior (Required)
BUILD SUCCESS

# Real behavior (Required)
Several Errors Occured

# StarRocks version (Required)
- branch main
- branch 3.0

# dive into codes & explain

> cmake version 3.26

Tow main parts:
1. third-party build errors - the procedure may not correct
2. one unused variable in starrocks

## third-party building
The error is mainly concentrated in the `apache arrow` build section.
Several packages can't be found by arrow even starrocks already built them before arrow.

### Error 1: CMake Error: Could NOT find Snappy (missing: Snappy_LIB)
The error below occurred even though we compiled snappy before building arrow.
```bash
CMake Error at /usr/local/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Snappy (missing: Snappy_LIB)
Call Stack (most recent call first):
  /usr/local/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindSnappy.cmake:55 (find_package_handle_standard_args)
  cmake_modules/ThirdpartyToolchain.cmake:235 (find_package)
  cmake_modules/ThirdpartyToolchain.cmake:948 (resolve_dependency)
  CMakeLists.txt:515 (include)
```
This is mainly caused by the wrong library type used in `build-thirdparty.sh`. In the standard operation, we should not install `libsnappy-dev` by `apt` in Ubuntu or `yum` in Centos, so there is something wrong when building.

According to the `CMakeLists.txt` which includes `ThirdpartyToolchain` in Line 515, `ThirdpartyToolchain.cmake` is the cmake module in the Apache arrow, which contains snappy and other dependencies needed by arrow 
>(some of them are built by `build-thirdparty.sh` before we build `arrow` such as `snappy` is built before `arrow` building, but some building procedures are still triggered by `arrow`).

So the snappy **should be found**. According to `FindSnappy.cmake` in `arrow`, I noticed that 
```cmake
if(ARROW_SNAPPY_USE_SHARED)
  set(SNAPPY_LIB_NAMES)
 # other things...
endif()
```
After checking this `ARROW_SNAPPY_USE_SHARED` setting, I found that in the current build settings, starrocks is trying to use DYNAMIC LIBRARY of Snappy to build arrow, but most of the packages are built to STATIC. So we will never find Snappy for arrow appropriately, because the library name we tried to find is **libsnappy.so**. 

How to fix: just use `-DARROW_SNAPPY_USE_SHARED=OFF` in `build-thirdparty.sh` when building arrow. Note that definitions like `-DARROW_BUILD_SHARED=OFF` or `-DARROW_BUILD_STATIC=ON` are not sufficient for arrow to use all static library for dependencies (already tested).

### Error 2: CMakeError: Count NOT find RapidJSONAlt

Error output:
```cmake
CMake Error at /usr/local/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find RapidJSONAlt (missing: RAPIDJSON_INCLUDE_DIR) (Required is
  at least version "1.1.0")
Call Stack (most recent call first):
  /usr/local/bin/cmake/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake_modules/FindRapidJSONAlt.cmake:69 (find_package_handle_standard_args)
  cmake_modules/ThirdpartyToolchain.cmake:235 (find_package)
  cmake_modules/ThirdpartyToolchain.cmake:1839 (resolve_dependency)
  CMakeLists.txt:515 (include)
```
Using the same thoughts to check the building procedure, this error is mainly caused by missing RapidJSON directory which should be provided to arrow cmake module.

**Note again**: we can manually install RapidJSON package by apt or yum in different systems, but if we do that, then the third-party section in starrocks will be meaningless.

**How to fix**: add cmake definition `-DRapidJSON_ROOT=$TP_INSTALL_DIR` in `build-thirdparty.sh` to help arrow find the `RapidJSON` package in the STARROCKS own thrid-party directory. 

Then we can get:
```
-- Found RapidJSONAlt: <my own directory>/starrocks/thirdparty/installed/include
```

### Error 3:  Could NOT find Lz4 (missing: LZ4_LIB LZ4_INCLUDE_DIR)

Same error type as before and the same inspecting method.

Add cmake options in `build-thirdparty.sh`. 
```
-DLZ4_INCLUDE_DIR=$TP_INSTALL_DIR/include/lz4 \
-DARROW_LZ4_USE_SHARED=OFF \
```

### Error 4: Not using zlib in third-party

Though `zlib.so` in my python virtual environment is found by arrow. But again, we need to use `zlib.a`.

**How to fix**: add cmake build definition `-DZLIB_ROOT=$TP_INSTALL_DIR` while building arrow. 

Note: this solution also meets a TODO task in arrow. 
>  TODO: Don't use global includes but rather target_include_directories

The more important thing is this enables Starrocks to use the correct & specific version of dependencies.

Then we can have:
```
Found ZLIB: /home/cm/projects/starrocks/thirdparty/installed/lib/libz.a (found version "1.2.11")  
```

### Error 5 & 6: Brotli is also using the library in the environment and files missing

Now arrow also finds brotli in my Python environment.
```
-- Found Brotli: <my miniconda path>/envs/py38/lib/libbrotlicommon.so
```
and files are missing
```
cp: cannot stat './brotli_ep/src/brotli_ep-install/lib/libbrotlienc-static.a': No such file or directory
```
Here is the code lines triggering the errors. [3 lines in total, 600-602] (https://github.com/StarRocks/starrocks/blob/cfea2ec3002254c93207523ff699491a6ace13af/thirdparty/build-thirdparty.sh#L600)

This is mainly because `brotli` will not be built by arrow. There is just non-exist the several files or directories we want to copy by command `cp`.

And more **IMPORTANT** is that I found that the library `libbrotlienc.a`, `libbrotlidec.a`, `libbrotlicommon.a` are needed by Starrocks main building procedure.
So if we don't install the library manually, we should fix the building error.

**How to fix**:
add `build_brotli()` function in `build-thirdparty.sh` script then call it to trigger building.
```
build_brotli() {
    check_if_source_exist $BROTLI_SOURCE
    cd $TP_SOURCE_DIR/$BROTLI_SOURCE
    mkdir -p $BUILD_DIR
    cd $BUILD_DIR
    rm -rf CMakeCache.txt CMakeFiles/
    ${CMAKE_CMD} .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR
    ${CMAKE_CMD} --build . --config Release --target install

    cp -rf $TP_INSTALL_DIR/lib/libbrotlienc-static.a $TP_INSTALL_DIR/lib64/libbrotlienc.a
    cp -rf $TP_INSTALL_DIR/lib/libbrotlidec-static.a $TP_INSTALL_DIR/lib64/libbrotlidec.a
    cp -rf $TP_INSTALL_DIR/lib/libbrotlicommon-static.a $TP_INSTALL_DIR/lib64/libbrotlicommon.a
}
```

and call `build_brotli` before `build_arrow`

Also add cmake definitions
``` 
 -DBROTLI_ROOT=$TP_INSTALL_DIR \
-DARROW_BROTLI_USE_SHARED=OFF \
```

Then we have 
```
-- Found Brotli: <my home directory>/starrocks/thirdparty/installed/lib/libbrotlicommon-static.a 
```

### Error 7: Declared but not used variable

Due to Starrocks treating warnings as errors in cpp.

Here is a warning (also an error).

(https://github.com/StarRocks/starrocks/blob/cfea2ec3002254c93207523ff699491a6ace13af/be/src/exprs/agg/stream/retract_maxmin.h#L239)

`column` defined but never used. It seems that the if branch 
(https://github.com/StarRocks/starrocks/blob/cfea2ec3002254c93207523ff699491a6ace13af/be/src/exprs/agg/stream/retract_maxmin.h#L240)
is also meaningless. 
For passing build and having no effects for behaviors, I propose just deleting the several lines. Or a student like me who wants to contribute to Starrocks will never build the project successfully...

I would like to provide a PR to solve several questions!

### PR DESCRIPTION
**Pull request by matchyc**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #23111 

## Problem Summary(Required):

TLDR; 
Users can't build Starrocks from the source.  And Starrocks is now using incorrect dependencies which does not follow the restriction.

### All the libraries mentioned below are now used in starrocks in a wrong way (not the restricted version), starrocks is searching on users local environment instead of using specified third-party, which may cause unknown behavior.

**Furthermore, even if we successfully pack the project for distribution, the several packages inside the libraries may come from the "packing machine", not the wanted versions of the library indicated in Starrocks' third-party restrictions.**

Mainly because the wrong build script and a little unused variable.

More **IMPORTATNT**, this PR enable Starrocks use correct and specified dependencies indicated by third-party file. 

Before this, many packages are used from system or python environment. 

In issue #23111 , I described the situation in detail, including how to locate the bug and a description of the solution.
Errors:
1. CMake Error: Could NOT find Snappy (missing: Snappy_LIB)
2. CMakeError: Count NOT find RapidJSONAlt
3. Could NOT find Lz4 (missing: LZ4_LIB LZ4_INCLUDE_DIR)
4. Not using zlib in third-party
5. Brotli is also using library in the environment 
6. Copy files missing
7. Declared but not used variable

If a user can build from the source, then these dependencies are installed manually by apt on Ubuntu or yum on CentOS, which is strongly not recommended.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by kevincai** [comment]
those dependencies are not supposed to be manually installed by `apt` or `yum`, we have strict version control of the thirdparty dependencies.

please refer to doc: https://docs.starrocks.io/en-us/main/developers/build-starrocks/Build_in_docker, suggest following the instructions from the doc and try again.

File: be/src/exprs/agg/stream/retract_maxmin.h [hunk 1]
```diff
@@ -236,10 +236,13 @@ class MaxMinAggregateFunctionRetractable final
         }
 
         // sync previous records from detail state table
+        // never used variable for now
```
Comment (kevincai) [inline be/src/exprs/agg/stream/retract_maxmin.h:239]: let's delete the code if not used

File: thirdparty/build-thirdparty.sh [hunk 2]
```diff
@@ -557,6 +557,20 @@ build_flatbuffers() {
   cp libflatbuffers.a $TP_LIB_DIR/libflatbuffers.a
 }
 
+build_brotli() {
+    check_if_source_exist $BROTLI_SOURCE
+    cd $TP_SOURCE_DIR/$BROTLI_SOURCE
+    mkdir -p $BUILD_DIR
+    cd $BUILD_DIR
+    rm -rf CMakeCache.txt CMakeFiles/
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:565]: thirdparty is supposed to be built from a brand new env. this clean up is not necessary.

File: thirdparty/build-thirdparty.sh [hunk 3]
```diff
@@ -1110,8 +1132,9 @@ build_brpc
 build_rocksdb
 build_librdkafka
 build_flatbuffers
-# must build before arrow
 build_jemalloc
+build_brotli
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:1136]: brotli is built by arrow, we copied that after arrow is built, check the code line 621~624.

so we may not need to build it explicitly.

**Comment by matchyc** [comment]
> those dependencies are not supposed to be manually installed by `apt` or `yum`, we have strict version control of the thirdparty dependencies.
> 
> please refer to doc: https://docs.starrocks.io/en-us/main/developers/build-starrocks/Build_in_docker, suggest following the instructions from the doc and try again.

That is exactly what I fixed in this PR. This PR is actually fix the version control. 
Before: can't build and library will be found on users local environments.
Fixed: Use starrocks speficied third-party dependencies. 
Please see detail description in issue #23111 . I described how the bug occurs and the correspond solution.

File: thirdparty/build-thirdparty.sh [hunk 4]
```diff
@@ -568,6 +582,7 @@ build_arrow() {
 
     check_if_source_exist $ARROW_SOURCE
     cd $TP_SOURCE_DIR/$ARROW_SOURCE/cpp
+    rm -rf CMakeCache.txt CMakeFiles/
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:585]: ditto

**Comment by imay** [comment]
@matchyc could you sign the CAL?

**Comment by matchyc** [comment]
> @matchyc could you sign the CAL?

Sure, signed it.

File: thirdparty/build-thirdparty.sh [hunk 5]
```diff
@@ -566,6 +566,19 @@ build_flatbuffers() {
   cp libflatbuffers.a $TP_LIB_DIR/libflatbuffers.a
 }
 
+build_brotli() {
+    check_if_source_exist $BROTLI_SOURCE
+    cd $TP_SOURCE_DIR/$BROTLI_SOURCE
+    mkdir -p $BUILD_DIR
+    cd $BUILD_DIR
+    ${CMAKE_CMD} .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR
+    ${CMAKE_CMD} --build . --config Release --target install
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:575]:
```suggestion
    ${CMAKE_CMD} .. -G "${CMAKE_GENERATOR}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR
    ${BUILD_SYSTEM} -j$PARALLEL
    ${BUILD_SYSTEM} install
```

Comment (kevincai) [reply thirdparty/build-thirdparty.sh:575]: if we can keep consistent with other dependency build command. support both make and ninja and takes `$PARALLEL` in consideration.

File: thirdparty/build-thirdparty.sh [hunk 6]
```diff
@@ -566,6 +566,19 @@ build_flatbuffers() {
...
+
+    cp -rf $TP_INSTALL_DIR/lib/libbrotlienc-static.a $TP_INSTALL_DIR/lib64/libbrotlienc.a
+    cp -rf $TP_INSTALL_DIR/lib/libbrotlidec-static.a $TP_INSTALL_DIR/lib64/libbrotlidec.a
+    cp -rf $TP_INSTALL_DIR/lib/libbrotlicommon-static.a $TP_INSTALL_DIR/lib64/libbrotlicommon.a
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:579]: I would rather use `mv` than `cp`, don't want multiple copies in the target install location.

Comment (kevincai) [reply thirdparty/build-thirdparty.sh:579]: also need to remove line 629~631, since we do it separately, so no need to ask arrow to do it again.

File: be/src/exprs/agg/stream/retract_maxmin.h [hunk 7]
```diff
@@ -236,10 +236,7 @@ class MaxMinAggregateFunctionRetractable final
         }
 
         // sync previous records from detail state table
-        InputColumnType* column;
-        if constexpr (!lt_is_string<LT>) {
-            column = down_cast<InputColumnType*>(columns[0].get());
-        }
+
```
Comment (kevincai) [inline be/src/exprs/agg/stream/retract_maxmin.h:239]: remove this empty line.

**Review by kevincai — COMMENTED** [review]
overall LGTM. let's check the CI job, if everything goes as exepcted. (https://github.com/StarRocks/starrocks/actions/runs/4936858122/jobs/8824929321?pr=23112)

File: thirdparty/build-thirdparty.sh [hunk 8]
```diff
@@ -566,6 +566,20 @@ build_flatbuffers() {
...
+build_brotli() {
+    check_if_source_exist $BROTLI_SOURCE
+    cd $TP_SOURCE_DIR/$BROTLI_SOURCE
+    mkdir -p $BUILD_DIR
+    cd $BUILD_DIR
+    ${CMAKE_CMD} .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR
+    ${BUILD_SYSTEM} -j$PARALLEL
+    ${BUILD_SYSTEM} install
+
+    mv -f $TP_INSTALL_DIR/lib/libbrotlienc-static.a $TP_INSTALL_DIR/lib64/libbrotlienc.a
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:578]: image

Comment (kevincai) [reply thirdparty/build-thirdparty.sh:578]: 1. need disable shared library build, only build static library
2. installed to `lib64` location by default on centos7, but possibly to `lib` location on ubuntu, need specify cmake_lib_dir to make the target library location predictable.

**Comment by matchyc** [comment]
It seems that the building test runs well. Note that in the latest commit. I also fixed that arrow is now using the correct boost library in third-party instead of using the environment boost library.

**Comment by kevincai** [comment]
image

looks like still can't find the rapidjson?

**Comment by matchyc** [comment]
> image
> 
> looks like still can't find the rapidjson?

After checking this warning carefully, I found it meaningless. I use `RapidJSON_ROOT` to indicate the path and ensure starrocks will use the specific third-party library, but before that:

In arrow cmake_module files `FindRapidJSONAlt.cmake`
```cmake
set(find_package_args)
if(RapidJSONAlt_FIND_VERSION)
  list(APPEND find_package_args ${RapidJSONAlt_FIND_VERSION})
endif()
if(RapidJSONAlt_FIND_QUIETLY)
  list(APPEND find_package_args QUIET)
endif()
find_package(RapidJSON ${find_package_args}) # note here!!!
if(RapidJSON_FOUND)
  set(RapidJSONAlt_FOUND TRUE)
  set(RAPIDJSON_INCLUDE_DIR ${RAPIDJSON_INCLUDE_DIRS})
  return()
endif()

if(RapidJSON_ROOT)
  find_path(RAPIDJSON_INCLUDE_DIR
            NAMES rapidjson/rapidjson.h
            PATHS ${RapidJSON_ROOT}
            NO_DEFAULT_PATH
            PATH_SUFFIXES "include")
else()
  find_path(RAPIDJSON_INCLUDE_DIR
            NAMES rapidjson/rapidjson.h
            PATH_SUFFIXES "include")
endif()
```
This means, arrow triggers find_package to find RapidJSON, which will do nothing. Eventually, it will find RapidJSON in the `RapidJSON_ROOT` directory. 
And we can't modify this because it is inside the arrow project. Except for the warning, everything goes well as expected.

File: thirdparty/build-thirdparty.sh [hunk 9]
```diff
@@ -566,6 +566,19 @@ build_flatbuffers() {
...
 
+build_brotli() {
+    check_if_source_exist $BROTLI_SOURCE
+    cd $TP_SOURCE_DIR/$BROTLI_SOURCE
+    mkdir -p $BUILD_DIR
+    cd $BUILD_DIR
+    ${CMAKE_CMD} .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR -DBROTLI_EMSCRIPTEN=ON -DCMAKE_INSTALL_LIBDIR=lib64
+    ${BUILD_SYSTEM} -j$PARALLEL
+
+    cp -f libbrotlienc-static.a $TP_INSTALL_DIR/lib64/libbrotlienc.a
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:577]: one last question, why use cp instead of `${BUILD_SYSTEM} install`

**Comment by kevincai** [comment]
have manual tried with a complete log. looks like arrow is still trying to rebuild brotli_ep itself.

image

If this is the case, looks like we are doing for nothing building the brotli outside arrow project.

**Comment by matchyc** [comment]
> have manual tried with a complete log. looks like arrow is still trying to rebuild brotli_ep itself.
> 
> image
> 
> If this is the case, looks like we are doing for nothing building the brotli outside arrow project.

That's weird because it is not suited for the logic of code. Checking the CMakelists and cmake_modules provided by arrow, we know it won't be built unless specific args were set. Like options for `xsimd` is set to "BUNDLE" by hard code. That is why `zstd` and `xsimd` will be built by arrow. 
```cmake
# this file is from arrow
if(...)
  set(xsimd_SOURCE "BUNDLED") # note this !!!!
 # ...
endif()
```
But there is no flag for `brotli`. And in my local Ubuntu machine with cmake version 3.26 or 3.16, `brotli` will always be found.
```
-- Found Brotli: <my_path>/starrocks/thirdparty/installed/lib64/libbrotlicommon.a  
-- Providing CMake module for Brotli
```

Could you provide the commit_id you use to reproduce the procedure? The latest one in this pr is `69e38e1206496c1bf390bd5b6bde49bcfcfa8512`

**Comment by kevincai** [comment]
> > have manual tried with a complete log. looks like arrow is still trying to rebuild brotli_ep itself.
> > image
> > If this is the case, looks like we are doing for nothing building the brotli outside arrow project.
> 
> That's weird because it is not suited for the logic of code. Checking the CMakelists and cmake_modules provided by arrow, we know it won't be built unless specific args were set. Like options for `xsimd` is set to "BUNDLE" by hard code. That is why `zstd` and `xsimd` will be built by arrow.
> 
> ```cmake
> # this file is from arrow
> if(...)
>   set(xsimd_SOURCE "BUNDLED") # note this !!!!
>  # ...
> endif()
> ```
> 
> But there is no flag for `brotli`. And in my local Ubuntu machine with cmake version 3.26 or 3.16, `brotli` will always be found.
> 
> ```
> -- Found Brotli: <my_path>/starrocks/thirdparty/installed/lib64/libbrotlicommon.a  
> -- Providing CMake module for Brotli
> ```
> 
> Could you provide the commit_id you use to reproduce the procedure? And I can check deep in, or the full log for the arrow building part. There are library finding in formation above the messages in this picture. The latest one in this pr is `69e38e1206496c1bf390bd5b6bde49bcfcfa8512`

I uses exactly this PR's commit `gh checkout pr 23112`

Reproduce it docker build command as follows: 
```
DOCKER_BUILDKIT=1 docker build --build-arg predownload_thirdparty=true --build-arg prebuild_maven=false -f docker/dockerfiles/dev-env/dev-env.Dockerfile --build-arg distro=centos7 -t nobody/dev-env-centos7:main-pr23112-2 .
```

to produce a centos7 env build.

**Comment by kevincai** [comment]
```
#12 631.4 -- Looking for pthread.h
#12 631.5 -- Looking for pthread.h - found
#12 631.5 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
#12 631.6 -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
#12 631.6 -- Found Threads: TRUE  
#12 631.6 -- Found Thrift: /root/starrocks/thirdparty/installed/lib/libthrift.a (found suitable version "0.13.0", minimum required is "0.11.0")  
#12 631.6 -- Looking for __SIZEOF_INT128__
#12 631.7 -- Looking for __SIZEOF_INT128__ - found
#12 631.7 -- Found Snappy: /root/starrocks/thirdparty/installed/lib64/libsnappy.a  
#12 631.7 -- Providing CMake module for Snappy
#12 631.7 -- Could NOT find Brotli (missing: BROTLI_INCLUDE_DIR) 
#12 631.7 -- Building brotli from source
#12 631.7 -- Building without OpenSSL support. Minimum OpenSSL version 1.0.2 required.
#12 631.7 -- Building (vendored) jemalloc from source
```

I guess most likely because the `brotli` include file is not installed?

**Comment by matchyc** [comment]
> > > have manual tried with a complete log. looks like arrow is still trying to rebuild brotli_ep itself.
> > > image
> > > If this is the case, looks like we are doing for nothing building the brotli outside arrow project.
> > 
> > 
> > That's weird because it is not suited for the logic of code. Checking the CMakelists and cmake_modules provided by arrow, we know it won't be built unless specific args were set. Like options for `xsimd` is set to "BUNDLE" by hard code. That is why `zstd` and `xsimd` will be built by arrow.
> > ```cmake
> > # this file is from arrow
> > if(...)
> >   set(xsimd_SOURCE "BUNDLED") # note this !!!!
> >  # ...
> > endif()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But there is no flag for `brotli`. And in my local Ubuntu machine with cmake version 3.26 or 3.16, `brotli` will always be found.
> > ```
> > -- Found Brotli: <my_path>/starrocks/thirdparty/installed/lib64/libbrotlicommon.a  
> > -- Providing CMake module for Brotli
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could you provide the commit_id you use to reproduce the procedure? And I can check deep in, or the full log for the arrow building part. There are library finding in formation above the messages in this picture. The latest one in this pr is `69e38e1206496c1bf390bd5b6bde49bcfcfa8512`
> 
> I uses exactly this PR's commit `gh checkout pr 23112`
> 
> Reproduce it docker build command as follows:
> 
> ```
> DOCKER_BUILDKIT=1 docker build --build-arg predownload_thirdparty=true --build-arg prebuild_maven=false -f docker/dockerfiles/dev-env/dev-env.Dockerfile --build-arg distro=centos7 -t nobody/dev-env-centos7:main-pr23112-2 .
> ```
> 
> to produce a centos7 env build.

Tried several times but can't reproduce. Docker (docker 23.0.2) didn't give the expected output (some are omitted even --progress=plain), would you like to help to try adding a definition like ` -DBROTLI_INCLUDE_DIR=$TP_INSTALL_DIR/include/brotli` to see if it goes well?  Because that's hard for me to debug this if I can't reproduce it.

**Comment by matchyc** [comment]
If it does, then that may be different behaviors between os? But may only give benefit because without building brotli it can't be built from source indeed in `ubuntu 20.04 5.15.0-56-generic`

**Comment by kevincai** [comment]
> If it does, then that may be different behaviors between os? But may only give benefit because without building brotli it can't be built from source indeed in `ubuntu 20.04 5.15.0-56-generic`

It is not specific on centos7, I tried both centos7 and ubuntu22.04.

**Comment by kevincai** [comment]
> > > > have manual tried with a complete log. looks like arrow is still trying to rebuild brotli_ep itself.
> > > > image
> > > > If this is the case, looks like we are doing for nothing building the brotli outside arrow project.
> > > 
> > > 
> > > That's weird because it is not suited for the logic of code. Checking the CMakelists and cmake_modules provided by arrow, we know it won't be built unless specific args were set. Like options for `xsimd` is set to "BUNDLE" by hard code. That is why `zstd` and `xsimd` will be built by arrow.
> > > ```cmake
> > > # this file is from arrow
> > > if(...)
> > >   set(xsimd_SOURCE "BUNDLED") # note this !!!!
> > >  # ...
> > > endif()
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > But there is no flag for `brotli`. And in my local Ubuntu machine with cmake version 3.26 or 3.16, `brotli` will always be found.
> > > ```
> > > -- Found Brotli: <my_path>/starrocks/thirdparty/installed/lib64/libbrotlicommon.a  
> > > -- Providing CMake module for Brotli
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Could you provide the commit_id you use to reproduce the procedure? And I can check deep in, or the full log for the arrow building part. There are library finding in formation above the messages in this picture. The latest one in this pr is `69e38e1206496c1bf390bd5b6bde49bcfcfa8512`
> > 
> > 
> > I uses exactly this PR's commit `gh checkout pr 23112`
> > Reproduce it docker build command as follows:
> > ```
> > DOCKER_BUILDKIT=1 docker build --build-arg predownload_thirdparty=true --build-arg prebuild_maven=false -f docker/dockerfiles/dev-env/dev-env.Dockerfile --build-arg distro=centos7 -t nobody/dev-env-centos7:main-pr23112-2 .
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to produce a centos7 env build.
> 
> Tried several times but can't reproduce. Docker (docker 23.0.2) didn't give the expected output (some are omitted even --progress=plain), would you like to help to try adding a definition like ` -DBROTLI_INCLUDE_DIR=$TP_INSTALL_DIR/include/brotli` during arrow building to see if it goes well? Because that's hard for me to debug this if I can't reproduce it.

you can comment out some unrelated build packages, e.g. aws sdk cpp, to save the output.

**Review by kevincai — APPROVED** [review]

**Comment by matchyc** [comment]
2 approving reviews are needed

**Comment by kevincai** [comment]
> 2 approving reviews are needed

@chaoyli @imay please take a look.

**Review by imay — APPROVED** [review]
