### PR TITLE
[StarRocks On ES] Support ES 8.x 

### LINKED ISSUE #7823: [StarrRocks On ES] when create external ES with 8.0 or above,   external ES table can not work
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by RowenWoo**
1. Elasticsearch 7.x, type was removed from ES mapping, default type is `_doc` 
    [7.0 reference](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/removal-of-types.html)
2. From Elasticsearch 8.x
    a. Specifying types in requests is no longer supported,
    b. The include_type_name parameter is removed
    [7.17 reference](        https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html
)

If the version of Elasticsearch is 8.x, do not specify the type when creating the table， such as

```
CREATE EXTERNAL TABLE `es8x` (
  `k1` varchar(20) NULL COMMENT "",
  `k2` varchar(20) NULL COMMENT ""
) ENGINE=ELASTICSEARCH 
COMMENT "ELASTICSEARCH"
PROPERTIES (
"hosts" = "http://127.0.0.1:9200",
"index" = "test_index"
);

```

If the version of ES is greater than or equal to 7.x, it is recommended to no longer specify type

**Known compatibility issues Please Note**：

**If the table ( only for 8.x ES) was created before upgrading the version that contains this PR, you need to delete the created table and recreate it after the upgrade**

## What type of PR is this：
- [x] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/7823

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|1|1|100.00%|

File: be/src/exec/es/es_scan_reader.cpp [hunk 1]
```diff
@@ -79,18 +81,30 @@ ESScanReader::ESScanReader(const std::string& target, const std::map<std::string
         _exactly_once = true;
         std::stringstream scratch;
         // just send a normal search  against the elasticsearch with additional terminate_after param to achieve terminate early effect when limit take effect
-        scratch << _target << REQUEST_SEPARATOR << _index << REQUEST_SEPARATOR << _type << "/_search?"
-                << "terminate_after=" << props.at(KEY_TERMINATE_AFTER) << REQUEST_PREFERENCE_PREFIX << _shards << "&"
-                << filter_path;
+        if (_type.empty()) {
```
Comment (imay) [inline be/src/exec/es/es_scan_reader.cpp:84]: how about define a static patten like 
static const char* pattern = "{}/{}/_search?terminate_after={}&preference=_shards:{}&{}"
then you can use fmt::format(pattern, _target, _index, props.at(), _shards)
I think it is easy of read

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|1|1|100.00%|

**Review by imay — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by dirtysalt** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 4 / 11 (36.36%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/EsScanNode.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|3|6|50.00%|
|:large_blue_circle:|com/starrocks/external/elasticsearch/MappingPhase.java|1|1|100.00%|
