### PR TITLE
[BugFix] Fix count distinct multi columns with avg distinct plan

### LINKED ISSUE #7369: count distinct multi columns with avg distinct give wrong plan
### Steps to reproduce the behavior (Required)
```
mysql> explain select avg(distinct s_suppkey), count(distinct s_acctbal,s_nationkey) from supplier;
+-----------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                                                         |
|  OUTPUT EXPRS:8: avg | 9: count                                                                                                         |
|   PARTITION: UNPARTITIONED                                                                                                              |
|                                                                                                                                         |
|   RESULT SINK                                                                                                                           |
|                                                                                                                                         |
|   4:Project                                                                                                                             |
|   |  <slot 8> : CAST(11: multi_distinct_sum AS DOUBLE) / CAST(10: multi_distinct_count AS DOUBLE)                                       |
|   |  <slot 9> : 9: count                                                                                                                |
|   |                                                                                                                                     |
|   3:AGGREGATE (merge finalize)                                                                                                          |
|   |  output: multi_distinct_count(9: count), multi_distinct_count(10: multi_distinct_count), multi_distinct_sum(11: multi_distinct_sum) |
|   |  group by:                                                                                                                          |
|   |                                                                                                                                     |
|   2:EXCHANGE                                                                                                                            |
|                                                                                                                                         |
| PLAN FRAGMENT 1                                                                                                                         |
|  OUTPUT EXPRS:                                                                                                                          |
|   PARTITION: RANDOM                                                                                                                     |
|                                                                                                                                         |
|   STREAM DATA SINK                                                                                                                      |
|     EXCHANGE ID: 02                                                                                                                     |
|     UNPARTITIONED                                                                                                                       |
|                                                                                                                                         |
|   1:AGGREGATE (update serialize)                                                                                                        |
|   |  output: multi_distinct_count(6: S_ACCTBAL, 4: S_NATIONKEY), multi_distinct_count(1: S_SUPPKEY), multi_distinct_sum(1: S_SUPPKEY)   |
|   |  group by:                                                                                                                          |
|   |                                                                                                                                     |
|   0:OlapScanNode                                                                                                                        |
|      TABLE: supplier                                                                                                                    |
|      PREAGGREGATION: ON                                                                                                                 |
|      partitions=1/1                                                                                                                     |
|      rollup: supplier                                                                                                                   |
|      tabletRatio=12/12                                                                                                                  |
|      tabletList=1565769,1565771,1565773,1565775,1565777,1565779,1565781,1565783,1565785,1565787 ...                                     |
|      cardinality=1                                                                                                                      |
|      avgRowSize=3.0                                                                                                                     |
|      numNodes=0                                                                                                                         |
+-----------------------------------------------------------------------------------------------------------------------------------------+
```
multi_distinct_count function do not support multi columns

so the result is also wrong

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7369 

## Problem Summary(Required) ：

this plan should be forbidden

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 1]
```diff
@@ -1322,4 +1322,15 @@ public void testOuterJoinSatisfyAgg() throws Exception {
                 "  6:EXCHANGE");
         connectContext.getSessionVariable().setNewPlanerAggStage(0);
     }
+
+    @Test
+    public void testAvgCountDistinctWithMultiColumns() {
+        String sql = "select avg(distinct s_suppkey), count(distinct s_acctbal,s_nationkey) from supplier;";
+        try {
+            getFragmentPlan(sql);
+        } catch (Throwable e) {
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:1331]: could use ExpectedException

**Review by HangyuanLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|2|2|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|2|2|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
