### PR TITLE
[BugFix] Report tablet ids when publish is failed 

### LINKED ISSUE #6500: no error tablet id is reported when submitting publish task failed
https://github.com/StarRocks/starrocks/blob/599d99a394c6bf5ce8502aa4e1a6a54b348bfd6a/be/src/agent/task_worker_pool.cpp#L782-L809

When the `Status TaskWorkerPool::_publish_version_in_parallel` fails to submit task to the thread pool, the error status is returned directly without error tablet id assigned. 
While the FE check whether the transaction is successful according to the error table ids reported. So, the FE would wrongly treat this transaction as success.

### Expected behavior (Required)
The transaction returns failure.
### Real behavior (Required)
The transaction returns success while the publish is not executed.
### StarRocks version (Required)
main, 2.1, 2.2

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6500

## Problem Summary(Required) ：

This PR fix the problem that no error tablet id is reported when the publish task submitting is failed.

### CODE REVIEW

**Comment by rickif** [comment]
run all

File: be/src/agent/task_worker_pool.cpp [hunk 1]
```diff
@@ -752,48 +752,49 @@ Status TaskWorkerPool::_publish_version_in_parallel(void* arg_this, std::unique_
...
-
-            // error category:
-            // 1. ServiceUnavailable, which means that the threadpool is busy even in retry.
-            // 2. error that is not ServiceUnavailable.
-            if (!st.ok()) return st;
 
+                // Status::ServiceUnavailable is returned when all of the threads of the pool are busy.
+                LOG(WARNING) << "publish version thread pool is not ready, retry later. txn_id: "
+                             << publish_version_req.transaction_id << ", tablet_id: " << tablet_rs.first.tablet_id
+                             << ", err: " << st;
```
Comment (chaoyli) [inline be/src/agent/task_worker_pool.cpp:787]: st.get_error_msg()

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by rickif** [comment]
@mergifyio backport branch-2.1
