### PR TITLE
[Bugfix] Fix bug defineExpr is not set use old Analyzer

### LINKED ISSUE #7198: failed to load data when upgrade the materialized view use COUNT
related issue #6124
### Steps to reproduce the behavior (Required)
This must use 3 Fe to reproduce.
1.CREATE TABLE testmv (
int12 int(11) NOT NULL COMMENT "",
clicked tinyint(4) NULL COMMENT "",
int1 int(11) NOT NULL COMMENT "",
int10 int(11) NULL COMMENT "",
int11 int(11) NULL COMMENT "",
icat12 varchar(65533) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(int12, clicked, int1)
COMMENT "OLAP"
DISTRIBUTED BY HASH(int12, clicked, int1) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

2.create materialized view c_mv as
SELECT int10, int11, count(int12) AS stars
FROM testmv
GROUP BY int10, int11;

3.use stream load to load any data.

4. when FE 1.Master 2.Follower 3. Follower
stop FE Master waiting For 2.Master 3.Follower
start 1 to Follwer

5.use stream load to load any data.

{
    "TxnId": 1008,
    "Label": "2d4aecdc-5884-4800-968d-f2b99b9010ea",
    "Status": "Fail",
    "Message": "Invalid number format: ",
    "NumberTotalRows": 0,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 0,
    "LoadTimeMs": 0,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 1,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 0,
    "CommitAndPublishTimeMs": 0
}
Routine Load logical is same
### Expected behavior (Required)
Load success
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.3.0

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7198

## Problem Summary(Required) ：

this because #6459 remove old analyze method but defineExpr need use old Analyzer to generated.

### CODE REVIEW

**Review by imay — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java [hunk 1]
```diff
@@ -827,24 +823,16 @@ public void gsonPostProcess() throws IOException {
...
-            return;
-        }
-        connectContext.setDatabase(db.getFullName());
-        Analyzer analyzer = new Analyzer(GlobalStateMgr.getCurrentState(), connectContext);
-        analyzer.setIgnoreCast();
         CreateMaterializedViewStmt stmt = null;
         try {
             stmt = (CreateMaterializedViewStmt) SqlParserUtils.getStmt(parser, origStmt.idx);
             stmt.setIsReplay(true);
-            stmt.analyze(analyzer);
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java:843]: why  needn't analyze?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/alter/RollupJobV2.java:843]: Because the main purpose of this code is to restore defineExpr.
The old idea is to use Analyzer to generate Stmt and then calculate MVColumn, and generate defineExpr through MVColumn, but our new Analyzer will use this method again, because the new one uses QueryStatement, and there is no old SelectStmt processing.
In addition, there is another advantage of not analyzing, that is, when the table name changes, only parse does not actually affect the logic of restoring defineExpr. And if you use Analyze, it will be easy to report errors here. resulting in other problems.

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|1|1|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|1|1|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 6 / 7 (85.71%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/RollupJobV2.java|5|6|83.33%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedIndexMeta.java|1|1|100.00%|
