### PR TITLE
Bugfix: check geo-function except st_astext generted invalid utf8 string

### LINKED ISSUE #3009: REVERSE function  crash
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d3;
CREATE DATABASE d3;
USE d3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 LARGEINT NOT NULL ,c_0_1 SMALLINT NULL ,c_0_2 FLOAT NOT NULL ,c_0_3 VARCHAR(11) NOT NULL ,c_0_4 CHAR(1) NOT NULL ,c_0_5 BOOLEAN NULL ,c_0_6 DECIMAL(11, 7)  NOT NULL ,c_0_7 VARCHAR(1) NULL ,c_0_8 FLOAT NULL ,c_0_9 SMALLINT NULL ) DUPLICATE KEY (c_0_0) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NOT NULL ) UNIQUE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (732196623, 12, 0.9347654020525136, "", "", true, 0.0004866, "", 0.20627739544887003, NULL), (732196623, 8, 0.6246024900862912, "", "", true, 0.0000752, "", 0.34675054503688996, 1);
INSERT INTO t0 VALUES (732196623, 6, 0.5625578091153415, "z", "", true, 0.0008796, "", 0.6157763647655319, 1), (-2055788698, 5, 0.5625578091153415, "QgUEh9", "", true, 0.0005359, "", 7.32196623E8, NULL);
INSERT INTO t0 VALUES (1073640858, 6, 0.20627739544887003, "Sgk", "", false, 0.0000674, "", 0.3365661518772073, 1), (1073640858, 3, 0.8160283144526207, "Iy7e", "", false, 0.0006554, "", NULL, 13), (1073640858, 5, 0.4709532584281666, "", "", NULL, 0.0001457, "", 0.9828689197800347, NULL);
INSERT INTO t0 VALUES (1073640858, 12, 0.12683060625996345, "rW", "", true, 0.0004134, "", 0.23173887602844978, 0);
INSERT INTO t1 VALUES ("1970-01-01 08:00:00");
INSERT INTO t0 VALUES (-1389046494, 6, 0.9347654020525136, "A", "", true, 0.0009866, "", NULL, 2);
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t0 VALUES (450563746, 10, 0.9638147272599331, "NfL", "", true, 0.0008078, "", 7.32196623E8, 4);
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t1 VALUES ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00"), ("1970-01-01 08:00:00");
INSERT INTO t0 VALUES (1073640858, 11, 7.32196623E8, "", "", true, 0.0000062, "", 0.9347654020525136, 2), (-191956643, 6, 1.073640858E9, "birCq", "", NULL, 0.0008505, "", 0.801871576816039, 13);
INSERT INTO t0 VALUES (1073640858, 1, 0.801871576816039, "epW", "", false, 0.0007422, "", 7.32196623E8, 14);
TRUNCATE TABLE t1;
2.SELECT DISTINCT * FROM (SELECT DISTINCT t1.c_1_0 FROM  t1 RIGHT JOIN t0 ON t1.c_1_0 = t0.c_0_1 AND t1.c_1_0 <= t0.c_0_1 AND t1.c_1_0 < t0.c_0_2 AND t1.c_1_0 > t0.c_0_2 WHERE ("")  BETWEEN (((((((NULL)||("O")))||("W")))||(REVERSE(ST_CIRCLE(0.07738263892674535, 0.5198486356310993, 0.4043626212184187) ) ))) AND (((((UPPER("S") )||(((((NULL)||("N")))||("")))))||((("")||("")))))  UNION ALL SELECT DISTINCT t1.c_1_0 FROM  t1 RIGHT JOIN t0 ON t1.c_1_0 = t0.c_0_1 AND t1.c_1_0 <= t0.c_0_1 AND t1.c_1_0 < t0.c_0_2 AND t1.c_1_0 > t0.c_0_2 WHERE (NOT (("")  BETWEEN (((((((NULL)||("O")))||("W")))||(REVERSE(ST_CIRCLE(0.07738263892674535, 0.5198486356310993, 0.4043626212184187) ) ))) AND (((((UPPER("S") )||(((((NULL)||("N")))||("")))))||((("")||(""))))) )) UNION ALL SELECT DISTINCT t1.c_1_0 FROM  t1 RIGHT OUTER JOIN t0 ON t1.c_1_0 = t0.c_0_1 AND t1.c_1_0 <= t0.c_0_1 AND t1.c_1_0 < t0.c_0_2 AND t1.c_1_0 > t0.c_0_2 WHERE ((("")  BETWEEN (((((((NULL)||("O")))||("W")))||(REVERSE(ST_CIRCLE(0.07738263892674535, 0.5198486356310993, 0.4043626212184187) ) ))) AND (((((UPPER("S") )||(((((NULL)||("N")))||("")))))||((("")||(""))))) ) IS NULL)) t;

```
crash.log:
==22870==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x606001c580be at pc 0x000003ecabeb bp 0x7fd258dc6ce0 sp 0x7fd258dc6cd8
WRITE of size 4 at 0x606001c580be thread T214 (fragment_mgr)
    #0 0x3ecabea in strings::memcpy_inlined(void*, void const*, unsigned long) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/gutil/strings/fastmem.h:117
    #1 0x885eb71 in utf8_reverse_per_slice /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1664
    #2 0x888d723 in reverse<false> /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1680
    #3 0x8888847 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::ReverseFunction::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1703
    #4 0x887e8d9 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction>::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:138
    #5 0x886cbc1 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:205
    #6 0x8862f27 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:211
    #7 0x884a53e in starrocks::vectorized::StringFunctions::reverse(starrocks_udf::FunctionContext*, std::vector<std::shared_ptr<starrocks::vectorized::Column>, std::allocator<std::shared_ptr<starrocks::vectorized::Column> > > const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1710
    #8 0x810fecc in starrocks::vectorized::VectorizedFunctionCallExpr::evaluate(starrocks::ExprContext*, starrocks::vectorized::Chunk*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:142
    #9 0x76a7b43 in starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::vectorized::Chunk*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:194
    #10 0x76b250d in operator() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:599
    #11 0x76b2f5c in __invoke_impl<void, starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #12 0x76b2f2b in __invoke<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #13 0x76b2d37 in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:717
    #14 0x76b2d5a in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #15 0x76b2d6b in _FUN /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #16 0x7fd2b324e20a in __pthread_once_slow (/lib64/libpthread.so.0+0x620a)
    #17 0x76aa3b5 in __gthread_once /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/x86_64-pc-linux-gnu/bits/gthr-default.h:700
    #18 0x76b2e83 in call_once<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:729
    #19 0x76b270e in starrocks::Expr::evaluate_const(starrocks::ExprContext*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:598
    #20 0x810e76c in starrocks::vectorized::VectorizedFunctionCallExpr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:65
    #21 0x76af5d6 in starrocks::Expr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:437
    #22 0x76af5d6 in starrocks::Expr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:437
    #23 0x76af5d6 in starrocks::Expr::open(starrocks::RuntimeState*, starrocks::ExprContext*, starrocks_udf::FunctionContext::FunctionStateScope) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:437
    #24 0x76a4a71 in starrocks::ExprContext::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:69
    #25 0x76af087 in starrocks::Expr::open(std::vector<starrocks::ExprContext*, std::allocator<starrocks::ExprContext*> > const&, starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:429
    #26 0x5b55e75 in starrocks::ExecNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/exec_node.cpp:220
    #27 0x6027784 in starrocks::vectorized::OlapScanNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/vectorized/olap_scan_node.cpp:68
    #28 0x66f066e in starrocks::vectorized::ProjectNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/vectorized/project_node.cpp:94
    #29 0x6173620 in starrocks::vectorized::HashJoinNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/vectorized/hash_join_node.cpp:225
    #30 0x66f066e in starrocks::vectorized::ProjectNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/vectorized/project_node.cpp:94
    #31 0x5f734bf in starrocks::vectorized::DistinctStreamingNode::open(starrocks::RuntimeState*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exec/vectorized/aggregate/distinct_streaming_node.cpp:26
    #32 0x500a886 in starrocks::PlanFragmentExecutor::_open_internal_vectorized() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:203
    #33 0x5009f74 in starrocks::PlanFragmentExecutor::open() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/plan_fragment_executor.cpp:186
    #34 0x4e89809 in starrocks::FragmentExecState::execute() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:193
    #35 0x4e8e8d2 in starrocks::FragmentMgr::exec_actual(std::shared_ptr<starrocks::FragmentExecState>*, std::function<void (starrocks::PlanFragmentExecutor*)> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:379
    #36 0x4e8f2ee in operator() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:438
    #37 0x4e983a3 in __invoke_impl<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #38 0x4e97f94 in __invoke_r<void, starrocks::FragmentMgr::exec_plan_fragment(const starrocks::TExecPlanFragmentParams&, const StartSuccCallback&, const FinishCallback&)::<lambda()>&> /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #39 0x4e97745 in _M_invoke /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #40 0x3dd2ddb in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #41 0x527c60f in starrocks::FunctionRunnable::run() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:45
    #42 0x52790ed in starrocks::ThreadPool::dispatch_thread() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:514
    #43 0x5296737 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:73
    #44 0x529601a in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #45 0x5295431 in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:416
    #46 0x5293f9d in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/functional:499
    #47 0x5290e83 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #48 0x528ee4b in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:110
    #49 0x528a5e6 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:291
    #50 0x3dd2ddb in std::function<void ()>::operator()() const /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/std_function.h:622
    #51 0x5263670 in starrocks::Thread::supervise_thread(void*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/thread.cpp:312
    #52 0x7fd2b324fea4 in start_thread (/lib64/libpthread.so.0+0x7ea4)
    #53 0x7fd2b26548dc in __clone (/lib64/libc.so.6+0xfe8dc)

0x606001c580be is located 2 bytes to the left of 50-byte region [0x606001c580c0,0x606001c580f2)
allocated by thread T214 (fragment_mgr) here:
    #0 0x3d62747 in operator new(unsigned long) ../../../../libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x3de9254 in __gnu_cxx::new_allocator<unsigned char>::allocate(unsigned long, void const*) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/ext/new_allocator.h:115
    #2 0x3de8683 in starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >::allocate(unsigned long) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/raw_container.h:44
    #3 0x3de3083 in std::allocator_traits<starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::allocate(starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> >&, unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/alloc_traits.h:314
    #4 0x3ddd42f in std::_Vector_base<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_allocate(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:346
    #5 0x3f9f574 in std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::_M_default_append(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/vector.tcc:635
    #6 0x3f9b98c in std::vector<unsigned char, starrocks::raw::RawAllocator<unsigned char, 16ul, std::allocator<unsigned char> > >::resize(unsigned long) /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/stl_vector.h:940
    #7 0x88887de in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::ReverseFunction::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1697
    #8 0x887e8d9 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction>::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:138
    #9 0x886cbc1 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10, (starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:205
    #10 0x8862f27 in std::shared_ptr<starrocks::vectorized::Column> starrocks::vectorized::DealNullableColumnUnaryFunction<starrocks::vectorized::UnpackConstColumnUnaryFunction<starrocks::vectorized::ReverseFunction> >::evaluate<(starrocks::PrimitiveType)10>(std::shared_ptr<starrocks::vectorized::Column> const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/unary_function.h:211
    #11 0x884a53e in starrocks::vectorized::StringFunctions::reverse(starrocks_udf::FunctionContext*, std::vector<std::shared_ptr<starrocks::vectorized::Column>, std::allocator<std::shared_ptr<starrocks::vectorized::Column> > > const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/string_functions.cpp:1710
    #12 0x810fecc in starrocks::vectorized::VectorizedFunctionCallExpr::evaluate(starrocks::ExprContext*, starrocks::vectorized::Chunk*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/vectorized/function_call_expr.cpp:142
    #13 0x76a7b43 in starrocks::ExprContext::evaluate(starrocks::Expr*, starrocks::vectorized::Chunk*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr_context.cpp:194
    #14 0x76b250d in operator() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/exprs/expr.cpp:599
    #15 0x76b2f5c in __invoke_impl<void, starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:60
    #16 0x76b2f2b in __invoke<starrocks::Expr::evaluate_const(starrocks::ExprContext*)::<lambda()> > /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/invoke.h:95
    #17 0x76b2d37 in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:717
    #18 0x76b2d5a in operator() /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #19 0x76b2d6b in _FUN /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/mutex:722
    #20 0x7fd2b324e20a in __pthread_once_slow (/lib64/libpthread.so.0+0x620a)

Thread T214 (fragment_mgr) created by T0 here:
    #0 0x3d0c442 in __interceptor_pthread_create ../../../../libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x5262ac4 in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/thread.cpp:267
    #2 0x5280c74 in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/thread.h:55
    #3 0x527a34d in starrocks::ThreadPool::create_thread() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:564
    #4 0x52745ee in starrocks::ThreadPool::init() /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:253
    #5 0x52712a9 in starrocks::ThreadPoolBuilder::build(std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >*) const /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/util/threadpool.cpp:82
    #6 0x4e8ddcc in starrocks::FragmentMgr::FragmentMgr(starrocks::ExecEnv*) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/fragment_mgr.cpp:349
    #7 0x4e1721f in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/exec_env.cpp:142
    #8 0x4e16741 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/runtime/exec_env.cpp:118
    #9 0x3da1af1 in main /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/service/starrocks_main.cpp:207
    #10 0x7fd2b2578554 in __libc_start_main (/lib64/libc.so.6+0x22554)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/disk2/jenkins/workspace/sqlancer_01_asan/cluster-management/resource/starrocks/be/src/gutil/strings/fastmem.h:117 in strings::memcpy_inlined(void*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0c0c80382fc0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80382fd0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80382fe0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80382ff0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c0c80383000: 00 00 00 00 00 00 00 fa fa fa fa fa fa fa fa fa
=>0x0c0c80383010: fa fa fa fa fa fa fa[fa]00 00 00 00 00 00 02 fa
  0x0c0c80383020: fa fa fa fa 00 00 00 00 00 00 02 fa fa fa fa fa
  0x0c0c80383030: 00 00 00 00 00 00 00 fa fa fa fa fa 00 00 00 00
  0x0c0c80383040: 00 00 00 fa fa fa fa fa fd fd fd fd fd fd fd fa
  0x0c0c80383050: fa fa fa fa 00 00 00 00 00 00 02 fa fa fa fa fa
  0x0c0c80383060: fd fd fd fd fd fd fd fd fa fa fa fa fd fd fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==22870==ABORTING

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 asan
 - mysql> select current_version();
+--------------------------+
| current_version()        |
+--------------------------+
| SQLANCER_01_ASAN 5bfc8b3 |
+--------------------------+

### PR DESCRIPTION
**Pull request by satanson**
https://github.com/StarRocks/starrocks/issues/3009
Geo functions (except st_astext) that return invalid utf8 string can not be arguments to string-typed parameters of another functions(except at_astext). 
such as: 

1. select as_astext(st_circle(0.1, 0.2, 0.4)) valid
2. select reverse(st_circle(0.1, 0.2, 0.4)) invalid
3. select reverse(as_astext(st_circle(0.1, 0.2, 0.4))) valid

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java [hunk 1]
```diff
@@ -962,4 +964,56 @@ public boolean isSelfMonotonic() {
...
         return false;
     }
+
+    // geo function whose name starts_with 'st_' and is not 'st_astext' generates invalid utf8 strings. so it cannot
+    // be used as a argument to a string-typed parameter of a function.
+    // 1. select reverse(st_circle(...)) unacceptable
+    // 2. select reverse(st_astext(st_circle(...)) acceptable
+    // 3. select reverse(cast(st_circle(...) as varchar)) unacceptable
+    // 4. select reverse(cast(cast(st_circle(...) as varchar) as varchar))) unacceptable
+    public static void checkGeoFunctionGeneratedInvalidUtf8(FunctionCallExpr node) throws SemanticException {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java:974]: FunctionCallExpr.java is treated as a defined structure in the new optimizer, no new logic code will be added, and existing code will also be deleted. The new function analyze logic code should be placed in FunctionAnalyzer

Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java:974]: I think put this function in  FunctionAnalyzer is better

Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/analysis/FunctionCallExpr.java]: ok

**Review by HangyuanLiu — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
