### PR TITLE
Fix CTAS Type is referenced by multiple tables in memory.

### LINKED ISSUE #2756: can't CTAS full data after fe restart
### Steps to reproduce the behavior (Required)
**create table and insert data**
```
select count(*) from t6;
+----------+
| count(*) |
+----------+
| 33559552 |
+----------+
create table t8 as select * from t6;
```
**restart fe pid at the same time** 
```
create table t9 as select * from t6;
select count(*) from t9;
```
### Expected behavior (Required)
33559552
### Real behavior (Required)
5120
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_BRANCH ee42572 |
+------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
Fix #2756
The root cause is that the type created in TypeDef(type) is changed.
This parsed type should create new and not use allFields.get(i).getType();
Because a reference to this object may lead to very unexpected changes
resulting in a series of problems.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java [hunk 1]
```diff
@@ -94,14 +94,27 @@ public Relation transformCTASStmt(CreateTableAsSelectStmt createTableAsSelectStm
...
+                }
+                ScalarType stringType = ScalarType.createVarcharType(len);
+                stringType.setAssignedStrLenInColDefinition();
                 type = stringType;
-            } else if (PrimitiveType.DOUBLE == type.getPrimitiveType()) {
-                type = Type.DEFAULT_DECIMAL128;
+            } else if (PrimitiveType.FLOAT == type.getPrimitiveType() ||
+                    PrimitiveType.DOUBLE == type.getPrimitiveType()) {
+                type = ScalarType.createDecimalV3Type(PrimitiveType.DECIMAL128, 38, 9);
+            } else if (PrimitiveType.DECIMAL128 == type.getPrimitiveType()) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CTASAnalyzer.java:113]: How about the array type?

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
