### PR TITLE
BugFix: Rowset id cache leak

### LINKED ISSUE #4277: Rowset id cache will leak In some scenarios
### Steps to reproduce the behavior (Required)

Rowset id cache will leak In some scenarios

* alloc rowset id success, but create file failed
* other scenariose
* ....

There should be a way to solve this problem completely.

Can rowset id be removed from cache, when rowset meta destruct?

### Real behavior (Required)

image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

2.1.x

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4277 #4292

## Problem Summary(Required) ：

Rowset id cache will leak in some scenarios:
+ allocate rowset id success, but create rowset writer failed
+ create rowset writer success, but no data written
....

Anyway, if allocate rowset id success, but does not generate `rowset_ptr`, we don't release the rowset_id, resulting in a memory leak.

In addition, when we do load data, we create a `delta_writer` for each tablet in advance, but only a few of the `delta_writer` may have data written to them.  This speeds up memory leak and output a lot of useless `rollback` logs in `be.INFO`

This pr will call `release_rowset_id` in deconstruct function of `delta_writer` if rowset is not built and reduce the `rollback` log.

### CODE REVIEW

File: be/src/storage/vectorized/delta_writer.h [hunk 1]
```diff
@@ -89,6 +89,7 @@ class DeltaWriter {
 private:
     enum State {
         kUninitialized,
+        kPrepared,
         kWriting,
```
Comment (chaoyli) [inline be/src/storage/vectorized/delta_writer.h:93]: Does kWriting is meaningless?

**Review by ABingHuang — CHANGES_REQUESTED** [review]

File: be/src/storage/vectorized/delta_writer.cpp [hunk 2]
```diff
@@ -199,24 +192,41 @@ Status DeltaWriter::write(const Chunk& chunk, const uint32_t* indexes, uint32_t
...
-            st = _flush_memtable();
-            _reset_mem_table();
-        } else if (full) {
-            st = _flush_memtable_async();
-            _reset_mem_table();
-        }
+        return Status::OK();
+    case kPrepared: {
+        std::lock_guard push_lock(_tablet->get_push_lock());
+        st = _storage_engine->txn_manager()->prepare_txn(_opt.partition_id, _tablet, _opt.txn_id, _opt.load_id);
```
Comment (chaoyli) [inline be/src/storage/vectorized/delta_writer.cpp:200]: It's also hold migration_lock when prepare_txn().

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: be/src/storage/vectorized/delta_writer.cpp [hunk 3]
```diff
@@ -185,12 +179,11 @@ Status DeltaWriter::_init() {
     _tablet_schema = writer_context.tablet_schema;
     _reset_mem_table();
     _flush_token = _storage_engine->memtable_flush_executor()->create_flush_token();
-    _set_state(kWriting);
+    _set_state(kPrepared);
```
Comment (meegoo) [inline be/src/storage/vectorized/delta_writer.cpp:182]: kPrepared -> kInitialized

File: be/src/storage/vectorized/delta_writer.cpp [hunk 4]
```diff
@@ -199,24 +192,41 @@ Status DeltaWriter::write(const Chunk& chunk, const uint32_t* indexes, uint32_t
...
-        }
+        return Status::OK();
+    case kPrepared: {
+        std::lock_guard push_lock(_tablet->get_push_lock());
+        st = _storage_engine->txn_manager()->prepare_txn(_opt.partition_id, _tablet, _opt.txn_id, _opt.load_id);
         if (!st.ok()) {
             _set_state(kAborted);
+            return st;
         }
+        _set_state(kWriting);
```
Comment (meegoo) [inline be/src/storage/vectorized/delta_writer.cpp:205]: kWriting -> kPrepared

File: be/src/storage/vectorized/delta_writer.cpp [hunk 5]
```diff
@@ -199,24 +192,41 @@ Status DeltaWriter::write(const Chunk& chunk, const uint32_t* indexes, uint32_t
...
-        } else if (_mem_tracker->parent() && _mem_tracker->parent()->limit_exceeded()) {
-            VLOG(2) << "Flushing memory table due to parent memory limit exceeded";
-            st = _flush_memtable();
-            _reset_mem_table();
-        } else if (full) {
-            st = _flush_memtable_async();
-            _reset_mem_table();
-        }
+        return Status::OK();
+    case kPrepared: {
```
Comment (meegoo) [inline be/src/storage/vectorized/delta_writer.cpp:198]: do prepare after it already in prepared state is little bit confuse

File: be/src/storage/vectorized/delta_writer.cpp [hunk 6]
```diff
@@ -37,8 +37,9 @@ DeltaWriter::~DeltaWriter() {
     switch (_get_state()) {
     case kUninitialized:
     case kCommitted:
+    case kInitialized:
         break;
-    case kWriting:
+    case kPrepared:
```
Comment (trueeyu) [inline be/src/storage/vectorized/delta_writer.cpp:42]: What does kWriting mean?

File: be/src/storage/vectorized/delta_writer.cpp [hunk 7]
```diff
@@ -199,28 +192,46 @@ Status DeltaWriter::write(const Chunk& chunk, const uint32_t* indexes, uint32_t
...
-            _reset_mem_table();
-        } else if (full) {
-            st = _flush_memtable_async();
-            _reset_mem_table();
-        }
+                fmt::format("Fail to prepare. tablet_id: {}, state: {}", _opt.tablet_id, _state_name(state)));
+    case kPrepared:
+        return Status::OK();
+    case kInitialized: {
+        std::shared_lock base_migration_rlock(_tablet->get_migration_lock());
```
Comment (trueeyu) [inline be/src/storage/vectorized/delta_writer.cpp:199]: why change the push_lock() to migration_lock()?

File: be/src/storage/vectorized/delta_writer.cpp [hunk 8]
```diff
@@ -199,24 +192,41 @@ Status DeltaWriter::write(const Chunk& chunk, const uint32_t* indexes, uint32_t
...
+    } else if (_mem_tracker->parent() && _mem_tracker->parent()->limit_exceeded()) {
+        VLOG(2) << "Flushing memory table due to parent memory limit exceeded";
+        st = _flush_memtable();
+        _reset_mem_table();
+    } else if (full) {
+        st = _flush_memtable_async();
+        _reset_mem_table();
+    }
+    if (!st.ok()) {
+        _set_state(kAborted);
```
[the remark this answers is not in the document]
Comment (sevev) [reply be/src/storage/vectorized/delta_writer.cpp:230]: done, changed

File: be/src/storage/vectorized/delta_writer.cpp (hunk 3 above)
Comment (sevev) [reply be/src/storage/vectorized/delta_writer.cpp]: done, change in https://github.com/StarRocks/starrocks/pull/4333/commits/0edd9627577ca337779715829abc0f9228517099

File: be/src/storage/vectorized/delta_writer.cpp (hunk 6 above)
Comment (sevev) [reply be/src/storage/vectorized/delta_writer.cpp:42]: > What does kWriting mean?

`kWriting` means  this delta_wirter has data written, and it will exec `rollback` if some error happened during transaction.

File: be/src/storage/vectorized/delta_writer.cpp (hunk 2 above)
Comment (sevev) [reply be/src/storage/vectorized/delta_writer.cpp:201]: > It's also hold migration_lock when prepare_txn().

done, changed

File: be/src/storage/rowset/beta_rowset_writer.cpp [hunk 9]
```diff
@@ -548,6 +550,8 @@ VerticalBetaRowsetWriter::~VerticalBetaRowsetWriter() {
             auto st = _env->delete_file(path);
             LOG_IF(WARNING, !st.ok()) << "Fail to delete file=" << path << ", " << st.to_string();
         }
+        // if _already_built is false, we need to release rowset_id to avoid rowset_id leak
+        StorageEngine::instance()->release_rowset_id(_context.rowset_id);
```
[the remark this answers is not in the document]
Comment (sevev) [reply be/src/storage/rowset/beta_rowset_writer.cpp:554]: > You should take care of convert_rowsets_id() in storage/snapshot_manager.cpp. Also, check the release upon failure. It's better to take care of next_rowset_id() call in every place.

check, if `convert_rowsets_id` failed. The rowset built success will be added in `unused_rowset` and the rowset_ids can be released

**Review by trueeyu — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
