### PR TITLE
[BugFix] fix es can not read `nested` type field

### LINKED ISSUE #42816: Starrocks can not read `nested` type field
### Steps to reproduce the behavior (Required)

Create es table with index mapping like following

```
{
  "xxx": {
    "mappings": {
      "event": {
        "_all": {
          "enabled": true
        },
        "properties": {
          "accountId": {
            "type": "nested",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              },
             "emailAddress": {
                "type": "text",
                "analyzer": "emailAnalyzer"
              }
            }
          }
   }
 }
}
}
```

And create external es catalog to read this table.

### Expected behavior (Required)

Following sql shoudl work

> select accountId from t

### Real behavior (Required)

It's reporting error like

```
SQL Error [1064] [42000]: Expected value of type: VARCHAR; but found type: Array;
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by dirtysalt**
## Why I'm doing:

Right now sr can not read es table which has `nested` type field, because it's mapped to string type.

## What I'm doing:

Map `nested` and `object` type field to json type. So user can read it out and parse data to json to do more analysis.

Plus, right now we assume `es.hosts` starts with http:// or https://, but we don't check it. So better to check it in validation function.

Pasted Graphic 2

Fixes https://github.com/StarRocks/starrocks/issues/42816

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by stephen-shelby — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java [hunk 1]
```diff
@@ -202,6 +203,11 @@ private void validate(Map<String, String> properties) throws DdlException {
         }
         hosts = properties.get(KEY_HOSTS).trim();
         seeds = hosts.split(",");
+        for (String seed : seeds) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:206]: Seed should trim? Like "http://1.1.1.1; http://1.1.1.1" the second seed has a space

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:206]: yes, better to trim again for each seed

File: fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java [hunk 2]
```diff
@@ -202,6 +203,14 @@ private void validate(Map<String, String> properties) throws DdlException {
         }
         hosts = properties.get(KEY_HOSTS).trim();
         seeds = hosts.split(",");
+        for (int i = 0; i < seeds.length; i++) {
+            seeds[i] = seeds[i].trim();
+        }
+        for (String seed : seeds) {
+            if (!seed.startsWith("http://") && !seed.startsWith("https://")) {
+                throw new DdlException("Host of ES table should start with 'http:// or 'https://'. Current value is " + seed);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:211]: I'm wondering why the prefix of http and https is necessary.
Is there any possibility that someone has already has some property without "http" or https as prefix, but after they upgrade to the new version, the existing ES external table can work as normal.

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:211]: image

I've posted that in description. That's to say, if you don't prefix with http:// or https://, port will be wrong.

And at the BE side, you will get url like 'http://127.0.0.1:9300:80', which will make error message like 'port must be a decimal number between 0~65535' which is very weird and hard to diagnose.

**Review by imay — DISMISSED** [review]

**Review by stephen-shelby — DISMISSED** [review]

**Review by imay — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
