### PR TITLE
[BugFix] fix comment lost escape character

### LINKED ISSUE #24908: can not use the show create table result to create table again
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `comment_test` (
  `a` varchar(125) NULL COMMENT "\\'abc'",
  `b` varchar(125) NULL COMMENT 'abc "ef" abc',
  `c` varchar(123) NULL COMMENT "abc \"ef\" abc",
  `d` varchar(123) NULL COMMENT "\\abc",
  `e` varchar(123) NULL COMMENT '\\\\"'
) ENGINE=OLAP
DUPLICATE KEY(`a`)
COMMENT "abc \"ef\" 'abc' \\abc"
DISTRIBUTED BY HASH(`a`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
```
show create table comment_test;

```
CREATE TABLE `comment_test` (
  `a` varchar(125) NULL COMMENT "\'abc'",
  `b` varchar(125) NULL COMMENT "abc "ef" abc",
  `c` varchar(123) NULL COMMENT "abc "ef" abc",
  `d` varchar(123) NULL COMMENT "\abc",
  `e` varchar(123) NULL COMMENT "\\""
) ENGINE=OLAP
DUPLICATE KEY(`a`)
COMMENT "abc "ef" 'abc' \abc"
DISTRIBUTED BY HASH(`a`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);
```
failed in parser phase when use the result create table again

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by packy92**
Fixes #24908

When parse a string, we need obtain the real meaning of a character followed by a escape character (like insert string values). The `escapeBackSlash()` method do this job. 
```
@Override
    public ParseNode visitString(StarRocksParser.StringContext context) {
        String quotedString;
        NodePosition pos = createPos(context);
        if (context.SINGLE_QUOTED_TEXT() != null) {
             ....
        } else {
            .....
        }
        return new StringLiteral(escapeBackSlash(quotedString), pos);
    }
```
But when parse comment string value, we need remain these escape character or the show result is not a legal string. Like comment `"\"abc\""`, it becomes `""abc""` if we remove the escape character.

I don't want to change the exist comment object too much, so I just add the escape character back when print the comment string.

Reason for removing `QUOTED_IDENTIFIER` in `StarRocksLex.g4`:
Some tokens have been regard as `QUOTED_IDENTIFIER` affectting the extract string process. Actually, ee haven't referenced this lex def in `StarRocks.g4`, so delete it.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java [hunk 1]
```diff
@@ -352,4 +353,22 @@ public static int calAvgBucketNumOfRecentPartitions(OlapTable olapTable, int rec
         return bucketNum;
     }
 
+    public static String addEscapeCharacter(String comment) {
+        if (StringUtils.isEmpty(comment)) {
+            return comment;
+        }
+        StringBuilder output = new StringBuilder();
+        for (int i = 0; i < comment.length(); i++) {
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java:361]: only support \\ \n ? if sql is constructed by a program, it may be contains other escape characters,  if we do not support other escaped characters, reporting error when encountering them is  just OK

**Review by satanson — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java (hunk 1 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java:361]: Most `escape characters` processed in `escapeBackSlash()` not affect the string meaning except '\' and '"'`, so special process for these two characters.

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 44 (70.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|3|00.00%|[210, 211, 213]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|2|50.00%|[839]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|16|50.00%|[2729, 2764, 2780, 2781, 2787, 2797, 2807, 2871]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|2|3|66.67%|[180]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 44 (70.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|3|00.00%|[210, 211, 213]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|2|50.00%|[839]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|16|50.00%|[2729, 2764, 2780, 2781, 2787, 2797, 2807, 2871]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|2|3|66.67%|[180]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 31 / 44 (70.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/LakeTable.java|0|3|00.00%|[210, 211, 213]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|2|50.00%|[839]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|8|16|50.00%|[2729, 2764, 2780, 2781, 2787, 2797, 2807, 2871]|
|:large_blue_circle:|com/starrocks/lake/LakeMaterializedView.java|2|3|66.67%|[180]|
|:large_blue_circle:|com/starrocks/catalog/Table.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Column.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/CatalogUtils.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|4|4|100.00%|[]|

**Review by HangyuanLiu — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by packy92** [comment]
@Mergifyio backport branch-3.1
