### PR TITLE
[BugFix] fix aggregate with key projection rewrite bug

### LINKED ISSUE #14847: aggregate mv rewrite failed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE

CREATE TABLE `lineitem` (
  `l_shipdate` date NOT NULL COMMENT "",
  `l_orderkey` int(11) NOT NULL COMMENT "",
  `l_linenumber` int(11) NOT NULL COMMENT "",
  `l_partkey` int(11) NOT NULL COMMENT "",
  `l_suppkey` int(11) NOT NULL COMMENT "",
  `l_quantity` decimal64(15, 2) NOT NULL COMMENT "",
  `l_extendedprice` decimal64(15, 2) NOT NULL COMMENT "",
  `l_discount` decimal64(15, 2) NOT NULL COMMENT "",
  `l_tax` decimal64(15, 2) NOT NULL COMMENT "",
  `l_returnflag` varchar(1) NOT NULL COMMENT "",
  `l_linestatus` varchar(1) NOT NULL COMMENT "",
  `l_commitdate` date NOT NULL COMMENT "",
  `l_receiptdate` date NOT NULL COMMENT "",
  `l_shipinstruct` varchar(25) NOT NULL COMMENT "",
  `l_shipmode` varchar(10) NOT NULL COMMENT "",
  `l_comment` varchar(44) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`l_shipdate`, `l_orderkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`l_orderkey`) BUCKETS 10
PROPERTIES (
"replication_num" = "1"
); 

2. create mv
CREATE MATERIALIZED VIEW `mv_1`
COMMENT "MATERIALIZED_VIEW"
DISTRIBUTED BY HASH(`l_linenumber`) BUCKETS 6
REFRESH MANUAL
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD"
)
AS SELECT `lineitem`.`l_linenumber`, abs(`lineitem`.`l_linenumber`) AS `abs_ln`, avg(`lineitem`.`l_quantity`) AS `q_avg`
FROM `tpch`.`lineitem`
GROUP BY `lineitem`.`l_linenumber`;

3. insert data
4. refresh mv
5. query
 SELECT `lineitem`.`l_linenumber`, abs(`lineitem`.`l_linenumber`), avg(`lineitem`.`l_quantity`)
FROM `tpch`.`lineitem`
GROUP BY `lineitem`.`l_linenumber`;

### Expected behavior (Required)
rewritten by mv_1
### Real behavior (Required)
not rewritten by mv_1
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14847 

## Problem Summary(Required) ：

The bug comes from the invalid process of aggregation key projection, which leads to mv rewrite failure. Fix it by considering aggregation key projection.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java [hunk 1]
```diff
@@ -153,10 +153,10 @@ public Map<ColumnRefOperator, ScalarOperator> getColumnRefMap() {
     public Map<ColumnRefOperator, ScalarOperator> getLineage(
             ColumnRefFactory refFactory, ExpressionContext expressionContext) {
         Map<ColumnRefOperator, ScalarOperator> columnRefMap = Maps.newHashMap();
-        columnRefMap.putAll(getColumnRefMap());
         if (projection != null) {
             columnRefMap.putAll(projection.getColumnRefMap());
         }
+        columnRefMap.putAll(getColumnRefMap());
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java:159]: What's the difference

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 2]
```diff
@@ -488,6 +488,9 @@ protected OptExpression rewriteProjection(RewriteContext rewriteContext,
         for (Map.Entry<ColumnRefOperator, ScalarOperator> entry : swappedQueryColumnMap.entrySet()) {
             ScalarOperator rewritten = replaceExprWithTarget(entry.getValue(),
                     normalizedViewMap, rewriteContext.getOutputMapping());
+            if (rewritten == null) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:491]: What's the situation of being null?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java [hunk 3]
```diff
@@ -60,6 +62,8 @@ public class AggregatedMaterializedViewRewriter extends MaterializedViewRewriter
             .put(FunctionSet.COUNT, FunctionSet.SUM)
             .build();
 
+    private static Set<String> UNSUPPORTED_FUNCTIONS = ImmutableSet.<String>builder().add(FunctionSet.AVG).build();
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:65]: What does unsupported mean ?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 64 / 65 (98.46%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|59|60|98.33%|[240]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateRewriteChecker.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java:159]: rojection.getColumnRefMap() may have the same keys with getColumnRefMap(). I want getColumnRefMap() to replace the same keys of projection.getColumnRefMap()

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:491]: if the entry.getValue can not be rewritten by normalizedViewMap's keys, it will return null.
for example. mv has output columns a, b. query has output columns c. then it will return null.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:65]: unsupported rollup. I will change it to UNSUPPORTED_ROLLUP_FUNCTIONS

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 69 / 70 (98.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|64|65|98.46%|[246]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregateRewriteChecker.java|1|1|100.00%|[]|

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
