### PR TITLE
[Enhancement] Do not throw exception if calling hms stats thrift api fails

### LINKED ISSUE #38620: StarRocks can not insert to Hive4 tables
## Enhancement
Test env:
StarRocks latest 3.2.2 version, Hive master(or 4.0.0-beta-1).

I use SR3.2.2 to insert Hive4 tables, it will faill with exception:
`mysql> insert into hivecat.testdb.testsr values(1143);`
`ERROR 1064 (HY000): Failed to update following tasks: alter table parameters testsr
`

The detail from fe.log
`Caused by: org.apache.thrift.TApplicationException: Required field 'engine' is unset! Struct:TableStatsRequest(dbName:testdb, tblName:testsr, colNames:[id], engine:null)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_statistics_req(ThriftHiveMetastore.java:4161) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.get_table_statistics_req(ThriftHiveMetastore.java:4148) ~[hive-apache-3.1.2-13.jar:?]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTableColumnStatistics(HiveMetaStoreClient.java:735) ~[starrocks-fe.jar:?]
        at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.getTableColumnStatistics(HiveMetaStoreClient.java:727) ~[starrocks-fe.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
        at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:208) ~[hive-apache-3.1.2-13.jar:?]
        at com.sun.proxy.$Proxy32.getTableColumnStatistics(Unknown Source) ~[?:?]
        ... 22 more
`

The reason is that Hive4 added a `engine `field in hms thrift column stats api, which is not backward compatibility, and StarRocks use the TrinoDB HMS client which is compatible with Hive3 to access Hive4, so this exception will happen.

I have thought some workarounds to fix this issue:

1. First, StarRocks does't need to throw exception when invoking the hms column stats api, as stats is only used for CBO stage, and we can allow users to insert hive table and just log a error if getting the hms stats api unsuccessfully.

2. Second, i will file a ticket in Apache Hive, and try to fix the issue under the hood. You can to track this ticket https://issues.apache.org/jira/browse/HIVE-27984 .

### PR DESCRIPTION
**Pull request by zhangbutao**
Why I'm doing:
SR can not wirte to Hive4 tables. see details from #38620

What I'm doing:
Add a workaround to let SR to write to Hive4 tables.
Fixes #38620

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by zhangbutao** [comment]
@stephen-shelby Could you please take a look? Thx!

**Comment by stephen-shelby** [comment]
@zhangbutao https://github.com/StarRocks/starrocks/issues/38620 sr 2.2.1 can't support hive sink. and how does this pr solve the issue of not being able to write hive4.

**Comment by zhangbutao** [comment]
> @zhangbutao #38620 sr 2.2.1 can't support hive sink. we support to hive sink in the 3.2 version. and how does this pr solve the issue of not being able to write hive4.

@stephen-shelby Sorry, my mistake. I used the latest 3.2 version.

**Comment by stephen-shelby** [comment]
Can adapting in `HiveMetastoreClient#alterTable` or `HiveMetastoreClient#alterPartition` solve the issue?

**Comment by stephen-shelby** [comment]
@zhangbutao I think update the column statistics to hive metastore is necessary. You could think about whether it can be solved in other ways instead of not throwing exceptions. If it cannot be solved, you can add a session variable for control.

**Comment by zhangbutao** [comment]
> Can adapting in `HiveMetastoreClient#alter_table` or `HiveMetastoreClient#alter_partition` solve the issue?

NO. The error will always exist, Unless SR dosen't call hive4 column stats api.
But fetching column statistics failing should not stop SR from writing into Hive tables. 
column statistics is good for cbo, but it shoule be not mandatory in anywhere.

**Comment by stephen-shelby** [comment]
> > Can adapting in `HiveMetastoreClient#alter_table` or `HiveMetastoreClient#alter_partition` solve the issue?
> 
> NO. The error will always exist, Unless SR dosen't call hive4 column stats api. But fetching column statistics failing should not stop SR from writing into Hive tables. column statistics is good for cbo, but it shoule be not mandatory in anywhere.

could you send a complete stack? Does it mean that the alter table can be executed successfully, but the refresh statistics fail? If you query the table of Hive 4 normally, is there also an error log in the background of fe.log?

**Comment by zhangbutao** [comment]
> @zhangbutao I think update the column statistics to hive metastore is necessary. You could think about whether it can be solved in other ways instead of not throwing exceptions. If it cannot be solved, you can add a session variable for control.

Thx for suggestion. As i said in https://github.com/StarRocks/starrocks/issues/38620, fix in Apache Hive is the best way, but this can not be promised.
I will explore how to add a session variable to control this behavior.

**Comment by zhangbutao** [comment]
[fe_exception_insert_hive4.txt](https://github.com/StarRocks/starrocks/files/13869392/fe_exception_insert_hive4.txt)
The full exception when insert into hive4 tables.
The mysql client also occur error:
```
mysql> show create table hivecat.testdb.testsr;
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                                                          |
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| testsr | CREATE TABLE `testsr` (
  `id` int(11) DEFAULT NULL
)
PROPERTIES ("location" = "hdfs://localhost:8028/user/hive/warehouse/external/hiveicetest/testdb.db/testsr"); |
+--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

mysql> insert into hivecat.testdb.testsr values(1143);
ERROR 1064 (HY000): Failed to update following tasks: alter table parameters testsr
```
Note: testsr is a non-partitioned table, and i didn't find similar error when select this table, that is to say, **querying the non-partitioned hive table may won't call the column stats api**.

But **if i select a partitoned table, the select can be execute sucessfully(No error in mysql client), but i can see the same error in fe.log**
[fe_error_when_select_partitioned_hive4.txt](https://github.com/StarRocks/starrocks/files/13869508/fe_error_when_select_partitioned_hive4.txt)

**Comment by stephen-shelby** [comment]
@zhangbutao Can you add me on wechat `Stephen5217`

**Comment by stephen-shelby** [comment]
> [fe_exception_insert_hive4.txt](https://github.com/StarRocks/starrocks/files/13869392/fe_exception_insert_hive4.txt) The full exception when insert into hive4 tables. The mysql client also occur error:
> 
> ```
> mysql> show create table hivecat.testdb.testsr;
> +--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Table  | Create Table                                                                                                                                                          |
> +--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | testsr | CREATE TABLE `testsr` (
>   `id` int(11) DEFAULT NULL
> )
> PROPERTIES ("location" = "hdfs://localhost:8028/user/hive/warehouse/external/hiveicetest/testdb.db/testsr"); |
> +--------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> 
> mysql> insert into hivecat.testdb.testsr values(1143);
> ERROR 1064 (HY000): Failed to update following tasks: alter table parameters testsr
> ```
> 
> Note: testsr is a non-partitioned table, and i didn't find similar error when select this table, that is to say, **querying the non-partitioned hive table may won't call the column stats api**.
> 
> But **if i select a partitoned table, the select can be execute sucessfully(No error in mysql client), but i can see the same error in fe.log** [fe_error_when_select_partitioned_hive4.txt](https://github.com/StarRocks/starrocks/files/13869508/fe_error_when_select_partitioned_hive4.txt)

image
I think you should have thrown the exception at line 397. And the update of statistical information has been completed. If you are sure that the update of statistical has been completed in HMS, then fetching failed is not important. You can add a session var to control it.

File: fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveCommitter.java [hunk 1]
```diff
@@ -334,7 +334,13 @@ private void runUpdateStatsTasks() {
             Joiner.on("; ").appendTo(message, failedUpdateStatsTaskDescs);
             StarRocksConnectorException exception = new StarRocksConnectorException(message.toString());
             suppressedExceptions.forEach(exception::addSuppressed);
-            throw exception;
+            // Insert into Hive4 table occur failure caused by compatibility issue between Hive3 and Hive4 thrift HMS client.
+            // Check https://github.com/StarRocks/starrocks/issues/38620 and HIVE-27984 for more details.
+            if (ConnectContext.get().getSessionVariable().enableHiveColumnStats()) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveCommitter.java:339]: add `ConnectContext.get() != null`

Comment (zhangbutao) [reply fe/fe-core/src/main/java/com/starrocks/connector/hive/HiveCommitter.java]: Done. Thx!

**Review by stephen-shelby — APPROVED** [review]

**Comment by zhangbutao** [comment]
https://github.com/StarRocks/starrocks/pull/38627/checks?check_run_id=20299873434
Not sure why the CI has failed tests. I rerun these failed test in local env, and it can run successfully. So i think the failed tests is not related this PR, maybe they are flaky.

**Review by Youngwb — APPROVED** [review]
