### PR TITLE
[BugFix]: NPE when BE report exceptional status

### LINKED ISSUE #5769: NPE when backend report exceptional status
### Steps to reproduce the behavior (Required)
Create a case that BE report exceptional status.

### Expected behavior (Required)
FE handle the status and reply to client.

### Real behavior (Required)
NPE at `Coordinator.java:1601`.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main `84ce7af`

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5769 #5714 #5761

## Problem Summary(Required) ：

Fix the NPE when backend report exceptional status.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 3 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|0|3|00.00%|

**Review by kangkaisen — DISMISSED** [review]

**Comment by dirtysalt** [comment]
Also fixes https://github.com/StarRocks/starrocks/issues/5714

**Comment by dirtysalt** [comment]
When some BE nodes report error like `Status::RuntimeError` or something,  this error is not properly handled by FE, and mysql client does not specific error, instead of showing empty set.

File: fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java [hunk 1]
```diff
@@ -1598,7 +1599,10 @@ public void updateFragmentExecStatus(TReportExecStatusParams params) {
         // and returned_all_results_ is true.
         // (UpdateStatus() initiates cancellation, if it hasn't already been initiated)
         if (!(returnedAllResults && status.isCancelled()) && !status.ok()) {
-            ConnectContext.get().setErrorCode(status.getErrorCode() == null ? "UNKNOWN" : status.getErrorCode().toString());
+            ConnectContext ctx = ConnectContext.get();
```
Comment (dirtysalt) [inline fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java:1602]: I've a question that, `ConnnectContext` is passed to ctor, could not we just save this context, instead of calling `ConnectContext.get()` all the time?

```
    // Used for new planner
   // <--- ConnectContext != null
    public Coordinator(ConnectContext context, List<PlanFragment> fragments, List<ScanNode> scanNodes,
                       TDescriptorTable descTable) {

    // Used for broker load task/export task coordinator
   // <--- ConnectContext == null
    public Coordinator(Long jobId, TUniqueId queryId, DescriptorTable descTable, List<PlanFragment> fragments,
                       List<ScanNode> scanNodes, String cluster, String timezone, long startTime) {
```

**Review by dirtysalt — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java (hunk 1 above)
Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/qe/Coordinator.java:1602]: Good advice. I will change it.

**Review by dirtysalt — APPROVED** [review]

**Comment by stdpain** [comment]
Is it the log like
```
2022-05-06 10:03:31,383 WARN (thrift-server-pool-169|421) [QeProcessorImpl.reportExecStatus():126
] ReportExecStatus() failed, fragment_instance_id=ba5dc209-cce0-11ec-aab7-00163e0e2d06, query_id=
ba5dc209-cce0-11ec-aab7-00163e0e2cf9, error: null
```

It seems #5761 is the same problem

**Comment by dirtysalt** [comment]
> Is it the log like
> 
> ```
> 2022-05-06 10:03:31,383 WARN (thrift-server-pool-169|421) [QeProcessorImpl.reportExecStatus():126
> ] ReportExecStatus() failed, fragment_instance_id=ba5dc209-cce0-11ec-aab7-00163e0e2d06, query_id=
> ba5dc209-cce0-11ec-aab7-00163e0e2cf9, error: null
> ```
> 
> It seems #5761 is the same problem

Probably the same bug.

**Review by stdpain — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run all

**Comment by mofeiatwork** [comment]
run all

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 15 / 27 (55.56%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/Coordinator.java|15|27|55.56%|
