### PR TITLE
[BugFix] Fix heap-use-after-free of ThreadPool bvar

### LINKED ISSUE #42319: heap-use-after-free
```
I0308 05:05:21.852730 214483 runtime_filter_worker.cpp:929] RuntimeFilterWorker going to exit.
  I0308 05:05:21.893026 214488 profile_report_worker.cpp:124] ProfileReportWorker going to exit.
  I0308 05:05:21.994668 214494 result_buffer_mgr.cpp:173] result buffer manager cancel thread finish.
  I0308 05:05:22.217666 214309 fragment_mgr.cpp:582] FragmentMgr cancel worker is going to exit.
  =================================================================
  ==212850==ERROR: AddressSanitizer: heap-use-after-free on address 0x61900037b198 at pc 0x000019698961 bp 0x7fe585be1d30 sp 0x7fe585be1d28
  READ of size 8 at 0x61900037b198 thread T113 (pip_wg_executor)
      #0 0x19698960 in bvar::detail::AddTo<long>::operator()(long&, long) const (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x19698960)
      #1 0x19695e92 in void bvar::detail::call_op_returning_void<bvar::detail::AddTo<long>, long, long>(bvar::detail::AddTo<long> const&, long&, long const&) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x19695e92)
      #2 0x2075457a in bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::commit_and_erase(bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::Agent*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x2075457a)
      #3 0x207526f2 in bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::Agent::~Agent() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x207526f2)
      #4 0x2075249f in bvar::detail::AgentGroup<bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::Agent>::ThreadBlock::~ThreadBlock() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x2075249f)
      #5 0x2075252f in bvar::detail::AgentGroup<bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::Agent>::_destroy_tls_blocks() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x2075252f)
      #6 0x25a5c0a2 in butil::detail::delete_thread_exit_helper(void*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x25a5c0a2)
      #7 0x7fe5fdb57ca1 in __nptl_deallocate_tsd (/lib64/libpthread.so.0+0x7ca1)
      #8 0x7fe5fdb57eb2 in start_thread (/lib64/libpthread.so.0+0x7eb2)
      #9 0x7fe5fcf58b0c in clone (/lib64/libc.so.6+0xfeb0c)
  
  0x61900037b198 is located 536 bytes inside of 904-byte region [0x61900037af80,0x61900037b308)
  freed by thread T0 here:
      #0 0x1450e1e7 in operator delete(void*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1450e1e7)
      #1 0x1457b077 in std::default_delete<starrocks::ThreadPool>::operator()(starrocks::ThreadPool*) const (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1457b077)
      #2 0x1456a940 in std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >::~unique_ptr() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1456a940)
      #3 0x23518a2c in starrocks::pipeline::GlobalDriverExecutor::~GlobalDriverExecutor() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23518a2c)
      #4 0x23518a63 in starrocks::pipeline::GlobalDriverExecutor::~GlobalDriverExecutor() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23518a63)
      #5 0x234db806 in starrocks::ExecEnv::destroy() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x234db806)
      #6 0x1454d7a5 in starrocks::init_test_env(int, char**) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454d7a5)
      #7 0x1454dea8 in main (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454dea8)
      #8 0x7fe5fce7c554 in __libc_start_main (/lib64/libc.so.6+0x22554)
  
  previously allocated by thread T0 here:
      #0 0x1450d817 in operator new(unsigned long) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1450d817)
      #1 0x23be0f7e in starrocks::ThreadPoolBuilder::build(std::unique_ptr<starrocks::ThreadPool, std::default_delete<starrocks::ThreadPool> >*) const (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23be0f7e)
      #2 0x234d62c9 in starrocks::ExecEnv::init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&, bool) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x234d62c9)
      #3 0x1454d42a in starrocks::init_test_env(int, char**) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454d42a)
      #4 0x1454dea8 in main (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454dea8)
      #5 0x7fe5fce7c554 in __libc_start_main (/lib64/libc.so.6+0x22554)
  
  Thread T113 (pip_wg_executor) created by T0 here:
      #0 0x144b7512 in __interceptor_pthread_create (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x144b7512)
      #1 0x23bd114c in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23bd114c)
      #2 0x23bf0e2e in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23bf0e2e)
      #3 0x23beb3c3 in starrocks::ThreadPool::create_thread() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23beb3c3)
      #4 0x23be739d in starrocks::ThreadPool::do_submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPoolToken*, starrocks::ThreadPool::Priority) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23be739d)
      #5 0x23be5dbd in starrocks::ThreadPool::submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPool::Priority) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23be5dbd)
      #6 0x23be5f5e in starrocks::ThreadPool::submit_func(std::function<void ()>, starrocks::ThreadPool::Priority) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x23be5f5e)
      #7 0x235059fe in starrocks::pipeline::GlobalDriverExecutor::initialize(int) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x235059fe)
      #8 0x234d666a in starrocks::ExecEnv::init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&, bool) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x234d666a)
      #9 0x1454d42a in starrocks::init_test_env(int, char**) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454d42a)
      #10 0x1454dea8 in main (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x1454dea8)
      #11 0x7fe5fce7c554 in __libc_start_main (/lib64/libc.so.6+0x22554)
  
  SUMMARY: AddressSanitizer: heap-use-after-free (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x19698960) in bvar::detail::AddTo<long>::operator()(long&, long) const
  Shadow bytes around the buggy address:
    0x0c32800675e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c32800675f0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067600: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067610: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067620: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  =>0x0c3280067630: fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067640: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067650: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
    0x0c3280067660: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c3280067670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
    0x0c3280067680: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  Shadow byte legend (one shadow byte represents 8 application bytes):
    Addressable:           00
    Partially addressable: 01 02 03 04 05 06 07 
    Heap left redzone:       fa
    Freed heap region:       fd
    Stack left redzone:      f1
    Stack mid redzone:       f2
    Stack right redzone:     f3
    Stack after return:      f5
    Stack use after scope:   f8
    Global redzone:          f9
    Global init order:       f6
    Poisoned by user:        f7
    Container overflow:      fc
    Array cookie:            ac
    Intra object redzone:    bb
    ASan internal:           fe
    Left alloca redzone:     ca
    Right alloca redzone:    cb
    Shadow gap:              cc
  ==212850==ABORTING
```

### PR DESCRIPTION
**Pull request by banmoy**
## Why I'm doing:
Fix #42319.
The problem is introduced by #40171. The pr adds bvar members in `ThreadPool`, and each thread will update the bvars. bvar uses thread-local to improve performance, and will do some work (`delete_thread_exit_helper`) in `__nptl_deallocate_tsd` before the pthread exits. It will access bvar members here.
```
      #5 0x2075252f in bvar::detail::AgentGroup<bvar::detail::AgentCombiner<long, long, bvar::detail::AddTo<long> >::Agent>::_destroy_tls_blocks() (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x2075252f)
      #6 0x25a5c0a2 in butil::detail::delete_thread_exit_helper(void*) (/root/starrocks/be/ut_build_ASAN/test/starrocks_test+0x25a5c0a2)
      #7 0x7fe5fdb57ca1 in __nptl_deallocate_tsd (/lib64/libpthread.so.0+0x7ca1)
      #8 0x7fe5fdb57eb2 in start_thread (/lib64/libpthread.so.0+0x7eb2)
```
But `ThreadPool` does not join the thread before destructing the pool itself, so it's possible that the bvar members are destroyed before `delete_thread_exit_helper` finishes which will lead to heap-use-after-free.

## What I'm doing:
There are two ways to fix the problem
1. the threadpool joins the thread to ensure the thread totally exits, and then destructs the pool itself
2. replace bvar with CoreLocalCounter to ensure the thread will not access threadpool members out of `ThreadPool::dispatch_thread`

The 1 is more elegant, but more complicated because the threadpool is dynamic, and need a way to join threads (only join the threads in the destructor is not enough). Currently use 2 to fix the problem. According to the test, updating bvar takes about 10ns constantly as the number of threads increase, and CoreLocalCounter takes about 20ns constantly. I think it's acceptable to use CoreLocalCounter in this scenario.

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [X] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/util/threadpool.cpp [hunk 1]
```diff
@@ -571,9 +571,9 @@ void ThreadPool::dispatch_thread() {
         task.runnable.reset();
         MonoTime finish_time = MonoTime::Now();
 
-        _total_executed_tasks << 1;
-        _total_pending_time_ns << start_time.GetDeltaSince(task.submit_time).ToNanoseconds();
-        _total_execute_time_ns << finish_time.GetDeltaSince(start_time).ToNanoseconds();
+        _total_executed_tasks.fetch_add(1);
```
Comment (sduzh) [inline be/src/util/threadpool.cpp:574]:
```suggestion
        _total_executed_tasks.fetch_add(1, std::memory_order_relaxed);
```

File: be/src/util/threadpool.cpp [hunk 2]
```diff
@@ -571,9 +571,9 @@ void ThreadPool::dispatch_thread() {
...
+        _total_pending_time_ns.fetch_add(start_time.GetDeltaSince(task.submit_time).ToNanoseconds());
```
Comment (sduzh) [inline be/src/util/threadpool.cpp:575]: ditto

File: be/src/util/threadpool.cpp [hunk 3]
```diff
@@ -571,9 +571,9 @@ void ThreadPool::dispatch_thread() {
...
+        _total_execute_time_ns.fetch_add(finish_time.GetDeltaSince(start_time).ToNanoseconds());
```
Comment (sduzh) [inline be/src/util/threadpool.cpp:576]: ditto

File: be/src/util/threadpool.h [hunk 4]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
 
     int max_threads() const { return _max_threads.load(std::memory_order_acquire); }
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_executed_tasks() const { return _total_executed_tasks.get_value(); }
+    int64_t total_executed_tasks() const { return _total_executed_tasks; }
```
Comment (sduzh) [inline be/src/util/threadpool.h:251]:
```suggestion
    int64_t total_executed_tasks() const { return _total_executed_tasks.load(std::memory_order_relaxed); }
```

File: be/src/util/threadpool.h [hunk 5]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
...
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_pending_time_ns() const { return _total_pending_time_ns.get_value(); }
+    int64_t total_pending_time_ns() const { return _total_pending_time_ns; }
```
Comment (sduzh) [inline be/src/util/threadpool.h:253]: ditto

File: be/src/util/threadpool.h [hunk 6]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
...
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_execute_time_ns() const { return _total_execute_time_ns.get_value(); }
+    int64_t total_execute_time_ns() const { return _total_execute_time_ns; }
```
Comment (sduzh) [inline be/src/util/threadpool.h:255]: ditto

File: be/src/util/threadpool.h [hunk 7]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
 
     int max_threads() const { return _max_threads.load(std::memory_order_acquire); }
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_executed_tasks() const { return _total_executed_tasks.get_value(); }
+    int64_t total_executed_tasks() const { return _total_executed_tasks.load(); }
```
Comment (sduzh) [inline be/src/util/threadpool.h:251]:
```suggestion
    int64_t total_executed_tasks() const { return _total_executed_tasks.load(std::memory_order_relaxed); }
```

File: be/src/util/threadpool.h [hunk 8]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
...
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_pending_time_ns() const { return _total_pending_time_ns.get_value(); }
+    int64_t total_pending_time_ns() const { return _total_pending_time_ns.load(); }
```
Comment (sduzh) [inline be/src/util/threadpool.h:253]: ditto

File: be/src/util/threadpool.h [hunk 9]
```diff
@@ -249,14 +248,11 @@ class ThreadPool {
...
 
-    // Use bvar as the counter, and should not be called frequently.
-    int64_t total_execute_time_ns() const { return _total_execute_time_ns.get_value(); }
+    int64_t total_execute_time_ns() const { return _total_execute_time_ns.load(); }
```
Comment (sduzh) [inline be/src/util/threadpool.h:255]: ditto

**Comment by sduzh** [comment]
Is the performance impact of using std::atomic acceptable? Has there been any comparison done with CoreLocalCounter?

**Comment by banmoy** [comment]
|  Threads  | bvar  | CoreLocalCounter | atomic |
|  ----  |  ----  |  ----  |  ----  |  
| 1 | 9 | 19 | 6 |
| 1 | 9 | 19 | 6 |
| 1 | 9 | 19 | 6 |
| 1 | 9 | 19 | 6 |
| 1 | 9 | 19 | 6 |

**Comment by banmoy** [comment]
@sduzh Thanks for your advice. I add `CoreLocalCounterTest.test_perf` to compare the update performance among bvar, CoreLocalCounter and atomic with different threads. The results are as following
* the performance of both bvar and CoreLocalCounter remains low as the number of threads increases, but the performance of atomic decreases as the number of threads increases
* the cost of bvar is about 10ns, and the cost of CoreLocalCounter is about 20ns
As a result, I think using `CoreLocalCounter` to replace `bvar` is acceptable although it has 10ns overhead than `bvar`
|  threads  | 1  | 2  | 3  | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 24 |
|  ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  | ----  |
| bvar | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 9 | 10 | 10 | 10 | 10 |  10 | 10 | 10 | 10 |
| CoreLocalCounter | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 | 19 |  19 | 19 | 19 | 19 | 19 |
| atomic | 6 | 11 | 34 | 54 | 68 | 81 | 90 | 109 | 113 | 149 | 153 | 173 | 181 | 201 | 211 | 250 | 234 | 255 | 270 |  291 | 291 | 313 | 369 | 335 |

**Review by sduzh — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
