### PR TITLE
[Enhancement] Provide clear error message if skip_headers is set in select from files option

### LINKED ISSUE #42799: [table function format:csv] when csv.skip_header value greater than actual rows, error message is incorrect
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
data file rows is 20
```
2020-06-23	2020-06-23 00:00:00	beijing	haidian	1	-128	-32768	-2147483648	-9223372036854775808	-18446744073709551616	-3.1	-3.14	-3.141
2020-06-23	2020-06-23 00:00:01	beijing	haidian	0	-127	-32767	-2147483647	-9223372036854775807	-18446744073709551615	-3	-3.13	-3.14
2020-06-23	2020-06-23 00:00:02	beijing	haidian	1	-126	-32766	-2147483646	-9223372036854775806	-18446744073709551614	-2.9	-3.12	-3.139
2020-06-23	2020-06-23 00:00:03	beijing	haidian	0	-125	-32765	-2147483645	-9223372036854775805	-18446744073709551613	-2.8	-3.11	-3.138
2020-06-23	2020-06-23 00:00:04	beijing	haidian	1	-124	-32764	-2147483644	-9223372036854775804	-18446744073709551612	-2.7	-3.1	-3.137
2020-06-23	2020-06-23 00:00:05	beijing	haidian	0	-123	-32763	-2147483643	-9223372036854775803	-18446744073709551611	-2.6	-3.09	-3.136
2020-06-23	2020-06-23 00:00:06	beijing	haidian	1	-122	-32762	-2147483642	-9223372036854775802	-18446744073709551610	-2.5	-3.08	-3.135
2020-06-23	2020-06-23 00:00:07	beijing	haidian	0	-121	-32761	-2147483641	-9223372036854775801	-18446744073709551609	-2.4	-3.07	-3.134
2020-06-23	2020-06-23 00:00:08	beijing	haidian	1	-120	-32760	-2147483640	-9223372036854775800	-18446744073709551608	-2.3	-3.06	-3.133
2020-06-23	2020-06-23 00:00:09	beijing	haidian	0	-119	-32759	-2147483639	-9223372036854775799	-18446744073709551607	-2.2	-3.05	-3.132
2020-06-23	2020-06-23 00:00:10	beijing	haidian	1	-118	-32758	-2147483638	-9223372036854775798	-18446744073709551606	-2.1	-3.04	-3.131
2020-06-23	2020-06-23 00:00:11	beijing	haidian	0	-117	-32757	-2147483637	-9223372036854775797	-18446744073709551605	-2	-3.03	-3.13
2020-06-23	2020-06-23 00:00:12	beijing	haidian	1	-116	-32756	-2147483636	-9223372036854775796	-18446744073709551604	-1.9	-3.02	-3.129
2020-06-23	2020-06-23 00:00:13	beijing	haidian	0	-115	-32755	-2147483635	-9223372036854775795	-18446744073709551603	-1.8	-3.01	-3.128
2020-06-23	2020-06-23 00:00:14	beijing	haidian	1	-114	-32754	-2147483634	-9223372036854775794	-18446744073709551602	-1.7	-3	-3.127
2020-06-23	2020-06-23 00:00:15	beijing	haidian	0	-113	-32753	-2147483633	-9223372036854775793	-18446744073709551601	-1.6	-2.99	-3.126
2020-06-23	2020-06-23 00:00:16	beijing	haidian	1	-112	-32752	-2147483632	-9223372036854775792	-18446744073709551600	-1.5	-2.98	-3.125
2020-06-23	2020-06-23 00:00:17	beijing	haidian	0	-111	-32751	-2147483631	-9223372036854775791	-18446744073709551599	-1.4	-2.97	-3.124
2020-06-23	2020-06-23 00:00:18	beijing	haidian	1	-110	-32750	-2147483630	-9223372036854775790	-18446744073709551598	-1.3	-2.96	-3.123
2020-06-23	2020-06-23 00:00:19	beijing	haidian	0	-109	-32749	-2147483629	-9223372036854775789	-18446744073709551597	-1.2	-2.95	-3.122
```
```
select * from files("path" = "hdfs://xxx.xx.xxx.xxx:xxxx/xxx/csv/csv_files_skip_header/skip_header.csv",
                          "format" = "csv",
                          "csv.skip_header"="20"
                           );


 select * from files("path" = "hdfs://xxx.xx.xxx.xxx:xxxx/xxx/csv/csv_files_skip_header/skip_header.csv",
                          "format" = "csv",
                          "csv.skip_header"="21"
                           );
```

### Expected behavior (Required)
error message is clear
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| main-a0223f6      |
+-------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by tracymacding**
## What I'm doing:

Fixes #42799

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

## Documentation PRs only:

If you are submitting a PR that adds or changes English documentation and have not
included Chinese documentation, then you can check the box to request GPT to translate the
English doc to Chinese. Please ensure to uncheck the **Do not translate** box if translation is needed.
The workflow will generate a new PR with the Chinese translation after this PR is merged.

- [ ] Yes, translate English markdown files with GPT
- [x] Do not translate

### CODE REVIEW

**Review by meegoo — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]

File: be/src/exec/csv_scanner.cpp [hunk 1]
```diff
@@ -259,7 +259,15 @@ Status CSVScanner::_init_reader() {
         if (_parse_options.skip_header) {
             for (int64_t i = 0; i < _parse_options.skip_header; i++) {
                 CSVReader::Record dummy;
-                RETURN_IF_ERROR(_curr_reader->next_record(&dummy));
+		auto st = _curr_reader->next_record(&dummy);
+                if (!st.ok()) {
+                    if (st.is_end_of_file()) {
+                        auto err_msg = fmt::format("You've set skip_header to {}, but there are only {} rows in csv file", _parse_options.skip_header, i);
```
Comment (kevincai) [inline be/src/exec/csv_scanner.cpp:265]:
```suggestion
                        auto err_msg = fmt::format("the parameter 'skip_header' is set to {}, but there are only {} rows in the csv file", _parse_options.skip_header, i);
```

**Review by kevincai — DISMISSED** [review]

**Review by meegoo — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by jaogoy** [comment]
ignore backport check: 3.1.15
