### PR TITLE
[Enhancement] Consider key container memory usages for streaming aggregate

### LINKED ISSUE #6212: [Enhancement] Aggr streaming bug-1:  count(distinct c1) run streaming failed if c1 is int
## Enhancement

For sql

```
select count(distinct lo_orderkey*10+lo_linenumber) from lineorder;
```

the profile

```
        AGGREGATION_NODE (id=2):(Active: 11s716ms[11716801021ns], % non-child: 48.12%)
           - AggregateFunctions: multi_distinct_count(18: expr)
           - AggComputeTime: 10s393ms
           - ExprComputeTime: 4.139ms
           - ExprReleaseTime: 11.20ms
           - GetResultsTime: 686.976ms
           - HashTableSize: 0
           - InputRowCount: 119.994608M (119994608)
           - PassThroughRowCount: 0
 ```

PassThroughRowCount is 0, bug the data actually has no degree of aggregation, so Streaming is more suitable here

The main cause of the problem:

We judge that the degree of aggregation has a gradient. If it is less than 256K, all use PreAgg, then 256~2M, >2M, there are certain requirements for the degree of aggregation, and there are three intervals in total. The purpose of this is that the larger the Hash table, the greater the cost of looking up the Hash table, which requires higher benefits brought by PreAggr.
In the initial implementation, all our keys are applied in MemPool, so I directly use the Size in MemPool as the Size in the gradient judgment. similar to this

```
hash_set.lazy_emplace(key, [&](const auto& ctor) {
    // we must persist the slice before insert
    uint8_t* pos = pool->allocate(key.size);
    memcpy(pos, key.data, key.size);
    ctor(pos, key.size, key.hash);
});
```

But later, for performance, we directly emplace, and the memory is no longer applied from MemPool

```

// TODO: calc the real capacity of hashtable, will add one interface in the class of habletable
size_t real_capacity =
        _aggregator->hash_map_variant().capacity() - _aggregator->hash_map_variant().capacity() / 8;
size_t remain_size = real_capacity - _aggregator->hash_map_variant().size();
[[maybe_unused]] bool ht_needs_expansion = remain_size < input_chunk_size;
```

Then there is a problem with using MemPool for gradients, because it is always 0, and less than 256K, even if there is no degree of aggregation, it will still be PreAggr.

Possible implementations:
Phmap provides an interface to obtain the memory of the current element, through which the current memory usage is obtained as the gradient

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR relates：

Closes #6212.

## Problem Summary：

Streaming Agg decides whether to PreAgg according to the memory usage of Hash Table and the aggregation degree. When the HT memory is less than 256KB, PreAgg will be always used.

For now, HT memory only counts the memory allocated by `MemPool`. However, in some scenarios, in order to optimize performance, HT's keys don't allocate from MemPool, such as `AggHashSetOfSerializedKeyFixedSize`, which will cause `MemPool` to be always 0. Therefore, even if there is no degree of aggregation, PreAgg will always be used.

Therefore, this PR consider the key memory used for streaming aggregate.
- If keys are allocated from `MemPool`, the key memory usage is the pointer of the key.
- Otherwise, the key memory usage is the real key memory usage.

### Environment
- 3BE with 64GB memory and 16vCPUs.

### Query
```sql
-- Q1 Stremaing Distinct Aggregate
select count(distinct lo_orderkey*10+lo_linenumber) from lineorder;

-- Q2 Stremaing Distinct Aggregate
select count(*) from (
    SELECT LO_CUSTKEY, LO_SUPPKEY, sum(LO_REVENUE) 
    FROM lineorder_flat 
    GROUP BY LO_CUSTKEY, LO_SUPPKEY
) AS a;

-- Q3 Stremaing Distinct Aggregate
select count(*) from (
    SELECT LO_PARTKEY, LO_LINENUMBER, LO_DISCOUNT, sum(LO_REVENUE) 
    FROM lineorder_flat 
    GROUP BY LO_PARTKEY, LO_LINENUMBER, LO_DISCOUNT 
) AS a;

-- Q4 Stremaing Aggregate
select sum(LO_REVENUE) 
from lineorder 
group by LO_PARTKEY, LO_LINENUMBER, LO_DISCOUNT 
limit 10;
```

### Result
| Name    | Before (s) | After (s) | After/Before |
| ------- | ---------- | --------- | ------------ |
| query01 | 10.01      | 6.36      | 0.64         |
| query02 | 9.77       | 6.17      | 0.63         |
| query03 | 5.99       | 3.51      | 0.59         |
| query04 | 4.02       | 3.72      | 0.93         |
| SUM     | 29.79      | 19.76     | 0.66         |

### CODE REVIEW

File: be/src/exec/vectorized/aggregate/agg_hash_variant.h [hunk 1]
```diff
@@ -402,14 +402,29 @@ struct AggHashMapVariant {
...
+        }
+
+        return 0;
+    }
+
+    size_t allocated_memory_usage(const MemPool* pool) const {
+        switch (type) {
+#define M(NAME)      \
+    case Type::NAME: \
+        return sizeof(decltype(NAME)::element_type::KeyType) * NAME->hash_map.size() + pool->total_allocated_bytes();
```
Comment (mofeiatwork) [inline be/src/exec/vectorized/aggregate/agg_hash_variant.h:422]: Why `type_size * entries + total_allocated_bytes()` ?

**Review by kangkaisen — APPROVED** [review]

File: be/src/exec/vectorized/aggregate/agg_hash_variant.h (hunk 1 above)
Comment (ZiheLiu) [reply be/src/exec/vectorized/aggregate/agg_hash_variant.h:422]: There are two kinds of key:
1. A pointer `char*`, which memory is allocated from `mem_pool`.
2. A trivial struct or a int, which memory is allocated from operator system.

Therefore,
- for the first type, `mem_pool-> total_allocated_bytes()` is the real key memory usage, and `type_size` is the pointer memory usage.
- for the second type, `mem_pool-> total_allocated_bytes()` is 0, and `type_size` is the real key memory usage.

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3
