### PR TITLE
[BugFix] Rewrite repair

### LINKED ISSUE #50329: [Bug]cache data is confusion
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...' (Field `col_1` uses 'BAUTO_INCREMENT')
2. stream load:  partial_update + no write `col_1`
3. SELECT  '....' from ... where id in (The latest ones just written)

Step 2/3 runs in parallel simultaneously and for a long time. 

### Expected behavior (Required)
normal.

### Real behavior (Required)
occasionally except:
1. ERROR 1064 (HY000): invalid encoding type:8
2. ERROR 1064 (HY000): num of element information corrupted, _num_element_after_padding:262721024, _num_elements:8
3. [42000][1064] Bad page: checksum mismatch (actual=2952600861 vs expect=1277960), file=/data/starRocks/storage/data/365/15004/2129610567/0200000000382bb9cd41910b6e0b0d512336bca4efb70dad_0.dat

### StarRocks version (Required)
 - 3.1.8

### PR DESCRIPTION
**Pull request by motto1314**
## Why I'm doing:
#50329 cache data is confusion

## What I'm doing:
Rewrite will read the unsubmitted update data, which will be overwritten during submission and should not be cached.
Although 'page_cache=true' was not configured during reading, segment_iterator's 'use_page_cache' did not take effect because scalar_column_iterator.cpp directly referenced 'config::disable_storage_page_cache'.
So add parameter 'temporary_data' to identify temporary data that has not been submitted.

Fixes #50329 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [x] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/storage/rowset/scalar_column_iterator.cpp [hunk 1]
```diff
@@ -381,8 +381,8 @@ Status ScalarColumnIterator::get_row_ranges_by_zone_map(const std::vector<const
         }
 
         IndexReadOptions opts;
-        opts.use_page_cache = config::enable_zonemap_index_memory_page_cache || !config::disable_storage_page_cache;
-        opts.kept_in_memory = config::enable_zonemap_index_memory_page_cache;
+        opts.use_page_cache = !opts.temporary_data && config::enable_zonemap_index_memory_page_cache || !config::disable_storage_page_cache;
```
Comment (trueeyu) [inline be/src/storage/rowset/scalar_column_iterator.cpp:384]:
```
int main() {
    bool temporary_data = true;
    bool enable_zonemap_index_memory_page_cache = false;
    bool disable_storage_page_cache = false;

    bool v = !temporary_data && enable_zonemap_index_memory_page_cache || !disable_storage_page_cache;
    std::cout << "RESULT: " << v << std::endl;

    return 0;
}
``

the result is true, maybe invalid

**Comment by trueeyu** [comment]
@Mergifyio rebase main

**Review by trueeyu — APPROVED** [review]

**Review by sevev — APPROVED** [review]

**Review by wyb — APPROVED** [review]
