### PR TITLE
[BugFix] fix format error when create table with invalid sort key

### LINKED ISSUE #34058: [BUG] create table with invalid sort key will cause format error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```sql
CREATE TABLE starrocks_test_table
(
    `tag_id` string,
    `tag_name` string
) ENGINE = OLAP PRIMARY KEY(`id`)
DISTRIBUTED BY HASH(`id`)
ORDER BY(`id`)
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "true",
"replicated_storage" = "true",
"compression" = "LZ4"
)

```

### Expected behavior (Required)
expected errors msg `Invalid column 'id' not exists in all columns.`

### Real behavior (Required)
error msg `[42000][1064] Format specifier '%s'`

### StarRocks version (Required)
 - 3.1.2-4f3a2ee91b

### PR DESCRIPTION
**Pull request by Jin-H**
Fixes #34058

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by kangkaisen — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java [hunk 1]
```diff
@@ -324,7 +324,7 @@ public Void visitOptimizeClause(OptimizeClause clause, ConnectContext context) {
             for (String column : clause.getSortKeys()) {
                 int idx = columnNames.indexOf(column);
                 if (idx == -1) {
-                    throw new SemanticException("Invalid column '%s' not exists in all columns. '%s', '%s'", column);
+                    throw new SemanticException("Invalid column '%s' not exists in all columns.", column);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AlterTableClauseVisitor.java:327]:
```suggestion
                    throw new SemanticException("Unknown column '%s' does not exist", column);
```

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java [hunk 2]
```diff
@@ -178,7 +178,7 @@ public static void analyze(CreateTableStmt statement, ConnectContext context) {
                 for (String column : statement.getSortKeys()) {
                     int idx = columnNames.indexOf(column);
                     if (idx == -1) {
-                        throw new SemanticException("Invalid column '%s' not exists in all columns. '%s', '%s'", column);
+                        throw new SemanticException("Invalid column '%s' not exists in all columns.", column);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java:181]:
```suggestion
                        throw new SemanticException("Unknown column '%s' does not exist", column);
```

**Comment by Jin-H** [comment]
@imay Could you help review it?

**Review by imay — APPROVED** [review]
