### PR TITLE
[BugFix] Fix InternalService_RecoverableStub race condition

### LINKED ISSUE #59929: [BUG] Random crash in PInternalService_RecoverableStub, __cxa_pure_virtual_
### Steps to reproduce the behavior (Required)

```
*** SIGABRT (@0x272000296e6) received by PID 169702 (TID 0x15162f6fb640) from PID 169702; stack trace: ***
    @     0x151dd468ee18 __pthread_once_slow
    @          0x7da2500 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x151dd463e6f0 (/usr/lib64/libc.so.6+0x3e6ef)
    @     0x151dd468b94c __pthread_kill_implementation
    @     0x151dd463e646 __GI_raise
    @     0x151dd46287f3 __GI_abort
    @          0x3328555 __gnu_cxx::__verbose_terminate_handler() [clone .cold]
    @          0xc480c56 __cxxabiv1::__terminate(void (*)())
    @          0xc480cc1 std::terminate()
    @          0xc48144f __cxa_pure_virtual
    @          0x3821545 starrocks::LocalTabletsChannel::_abort_replica_tablets(starrocks::PTabletWriterAddChunkRequest const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unordered_map<long, std::vector<long, std::allocator<long> >X^S
    @          0x38237f0 starrocks::LocalTabletsChannel::add_chunk(starrocks::Chunk*, starrocks::PTabletWriterAddChunkRequest const&, starrocks::PTabletWriterAddBatchResult*)
    @          0x3815939 starrocks::LoadChannel::_add_chunk(starrocks::Chunk*, starrocks::PTabletWriterAddChunkRequest const&, starrocks::PTabletWriterAddBatchResult*)
    @          0x3816b2c starrocks::LoadChannel::add_chunks(starrocks::PTabletWriterAddChunksRequest const&, starrocks::PTabletWriterAddBatchResult*)
    @          0x38101c3 starrocks::LoadChannelMgr::add_chunks(starrocks::PTabletWriterAddChunksRequest const&, starrocks::PTabletWriterAddBatchResult*)
    @          0x38d163b starrocks::BackendInternalServiceImpl<starrocks::PInternalService>::tablet_writer_add_chunks(google::protobuf::RpcController*, starrocks::PTabletWriterAddChunksRequest const*, starrocks::PTabletWriterAddBatchResult*, google::protobuf::Closure*)
    @          0x802f2d4 brpc::policy::ProcessRpcRequest(brpc::InputMessageBase*)
    @          0x7f5b677 brpc::ProcessInputMessage(void*)
    @          0x7f5c9f5 brpc::InputMessenger::OnNewMessages(brpc::Socket*)
    @          0x7f4acee brpc::Socket::ProcessEvent(void*)
    @          0x7f1bd72 bthread::TaskGroup::task_runner(long)
    @          0x8071201 bthread_make_fcontext
```

```
*** SIGABRT (@0x27200029275) received by PID 168565 (TID 0x14e21a04a640) from PID 168565; stack trace: ***
    @     0x14e76a28ee18 __pthread_once_slow
    @          0x7d9f940 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x14e76a23e6f0 (/usr/lib64/libc.so.6+0x3e6ef)
    @     0x14e76a28b94c __pthread_kill_implementation
    @     0x14e76a23e646 __GI_raise
    @     0x14e76a2287f3 __GI_abort
    @          0x3328615 __gnu_cxx::__verbose_terminate_handler() [clone .cold]
    @          0xc47dc56 __cxxabiv1::__terminate(void (*)())
    @          0xc47dcc1 std::terminate()
    @          0xc47e44f __cxa_pure_virtual
    @          0x40f7d41 starrocks::NodeChannel::_cancel(long, starrocks::Status const&)
    @          0x40f7f32 starrocks::NodeChannel::cancel()
    @          0x40fc82b std::_Function_handler<void (starrocks::NodeChannel*), starrocks::TabletSinkSender::try_close(starrocks::RuntimeState*)::{lambda(starrocks::NodeChannel*)#4}>::_M_invoke(std::_Any_data const&, starrocks::NodeChannel*&&)
    @          0x40fc203 starrocks::TabletSinkSender::try_close(starrocks::RuntimeState*)
    @          0x44498ad starrocks::pipeline::OlapTableSinkOperator::pending_finish() const
    @          0x44d9ccb starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int)
    @          0x479b583 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x397eab3 starrocks::ThreadPool::dispatch_thread()
    @          0x3976d56 starrocks::Thread::supervise_thread(void*)
    @     0x14e76a289c02 start_thread
    @     0x14e76a30ec40 __clone3
```

### Expected behavior (Required)

No Crash

### Real behavior (Required)

Crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kevincai**
* RecoverableStub's _stub access is not all protected under lock, which may cause the _M_ptr invalid in the middle by the shared_ptr assignment.

## What I'm doing:

Fixes #59929

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2

### CODE REVIEW

File: be/src/util/internal_service_recoverable_stub.cpp [hunk 1]
```diff
@@ -24,12 +24,15 @@ class RecoverableClosure : public ::google::protobuf::Closure {
 public:
     RecoverableClosure(std::shared_ptr<starrocks::PInternalService_RecoverableStub> stub,
                        ::google::protobuf::RpcController* controller, ::google::protobuf::Closure* done)
-            : _stub(std::move(std::move(stub))), _controller(controller), _done(done) {}
+            : _stub(std::move(std::move(stub))),
```
Comment (alvin-phoenix-ai) [inline be/src/util/internal_service_recoverable_stub.cpp]: Why are there two recursive `std::move`?

Comment (kevincai) [reply be/src/util/internal_service_recoverable_stub.cpp]: removed

**Review by alvin-phoenix-ai — APPROVED** [review]

**Review by meegoo — APPROVED** [review]
