### PR TITLE
[BugFix] Fix Create automic partitions with case insensitive bug

### LINKED ISSUE #54202: Refresh of asynchronous materialized view fails if base table is partitioned using expression partitioning.
Refresh of asynchronous materialized view fails if base table is partitioned using expression partitioning.

Facts:
1. Cluster is in shared-data mode.
2. Base table is partitioned on string data type column using expression partitioning
3. Asynchronous materialized view is also partitioned on same column as base table using expression partitioning. 

### Steps to reproduce the behavior (Required)

```
CREATE TABLE `test_base_tbl` (
  col1 varchar(100),
  col2 varchar(100),
  col3 bigint
) ENGINE=OLAP
PRIMARY KEY (col1)
PARTITION BY (col1)
DISTRIBUTED BY HASH(col1) BUCKETS 5
ORDER BY (col2)
PROPERTIES (
  "persistent_index_type" = "CLOUD_NATIVE"
);

insert into test_base_tbl values
('a.com', 'val1', 100),
('A.com', 'val1', 200),
('A.Com', 'val1', 300)

CREATE MATERIALIZED VIEW `test_async_mv`
PARTITION BY (col1)
DISTRIBUTED BY HASH(col1)
REFRESH MANUAL
PROPERTIES (
"query_rewrite_consistency" = "LOOSE",
"session.enable_spill" = "true",
"datacache.enable" = "true",
"enable_async_write_back" = "false",
"storage_volume" = "builtin_storage_volume"
)
AS SELECT col1, sum(col3) from test_base_tbl group by col1;
```

### Expected behavior (Required)
Refresh of this asynchronous materialized view should be successful.

### Real behavior (Required)
Refresh of this asynchronous materialized view fails with the following error:

```
Refresh materialized view test_async_mv failed after retrying 1 times(try-lock 0 times), error-msg : com.starrocks.sql.analyzer.SemanticException: Getting analyzing error. Detail message: Duplicate partition name pA2ecom.
	at com.starrocks.sql.analyzer.AlterTableClauseAnalyzer.visitAddPartitionClause(AlterTableClauseAnalyzer.java:1079)
	at com.starrocks.sql.analyzer.AlterTableClauseAnalyzer.visitAddPartitionClause(AlterTableClauseAnalyzer.java:111)
	at com.starrocks.sql.ast.AddPartitionClause.accept(AddPartitionClause.java:80)
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:71)
	at com.starrocks.sql.analyzer.AlterTableClauseAnalyzer.analyze(AlterTableClauseAnalyzer.java:119)
	at com.starrocks.scheduler.mv.MVPCTRefreshListPartitioner.addListPartitions(MVPCTRefreshListPartitioner.java:378)
	at com.starrocks.scheduler.mv.MVPCTRefreshListPartitioner.syncAddOrDropPartitions(MVPCTRefreshListPartitioner.java:113)
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.syncPartitions(PartitionBasedMvRefreshProcessor.java:914)
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doRefreshMaterializedView(PartitionBasedMvRefreshProcessor.java:413)
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doRefreshMaterializedViewWithRetry(PartitionBasedMvRefreshProcessor.java:368)
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:327)
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:199)
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:272)
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### StarRocks version (Required)
3.3.5-8fold-1210-aa794ea

### PR DESCRIPTION
**Pull request by LiShuMing**
## Why I'm doing:

```
CREATE TABLE `test_base_tbl` (
  col1 varchar(100),
  col2 varchar(100),
  col3 bigint
) ENGINE=OLAP
PRIMARY KEY (col1)
PARTITION BY (col1)
DISTRIBUTED BY HASH(col1) BUCKETS 5
ORDER BY (col2)
PROPERTIES (
  "persistent_index_type" = "CLOUD_NATIVE"
);

mysql> insert into test_base_tbl values
    -> ('a.com', 'val1', 100),
    -> ('A.com', 'val1', 200),
    -> ('A.Com', 'val1', 300);
ERROR 1064 (HY000): Insert has filtered data, txn_id = 19015, tracking sql = select tracking_log from information_schema.load_tracking_logs where job_id=30034
mysql> select tracking_log from information_schema.load_tracking_logs where job_id=30034
    -> ;
+------------------------------------------------------------------------------------------------------+
| tracking_log                                                                                         |
+------------------------------------------------------------------------------------------------------+
| Error: The row is out of partition ranges. Please add a new partition.. Row: ['A.com', 'val1', 200]
 |
+------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> show partitions from test_base_tbl;
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+-------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
| PartitionId | PartitionName | VisibleVersion | VisibleVersionTime  | VisibleVersionHash | State  | PartitionKey | List        | DistributionKey | Buckets | ReplicationNum | StorageMedium | CooldownTime        | LastConsistencyCheckTime | DataSize | IsInMemory | RowCount | DataVersion | VersionEpoch       | VersionTxnType |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+-------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
| 30036       | pa2ecom       | 1              | 2024-12-24 13:38:57 | 0                  | NORMAL | col1         | [["a.com"]] | col1            | 5       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        | 1           | 329634415550398464 | TXN_NORMAL     |
| 30060       | pA2eCom       | 1              | 2024-12-24 13:38:57 | 0                  | NORMAL | col1         | [["A.Com"]] | col1            | 5       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        | 1           | 329634415550398466 | TXN_NORMAL     |
| 30048       | pA2ecom       | 1              | 2024-12-24 13:38:57 | 0                  | NORMAL | col1         | [["A.com"]] | col1            | 5       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        | 1           | 329634415550398465 | TXN_NORMAL     |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+-------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
3 rows in set (0.01 sec)
```
## What I'm doing:
- our partition names in FE's metadata are always case-insensitive, but automatic partitions in be will create case-sensitive partitions.

Fixes https://github.com/StarRocks/starrocks/issues/54202

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java [hunk 1]
```diff
@@ -1412,11 +1419,26 @@ public static AddPartitionClause getAddPartitionClauseFromPartitionValues(OlapTa
                     partitionName = partitionNamePrefix + PARTITION_NAME_PREFIX_SPLIT + partitionName;
                 }
                 if (!partitionColNames.contains(partitionName)) {
+                    List<List<String>> partitionItems = Collections.singletonList(partitionValue);
+                    PListCell cell = new PListCell(partitionItems);
+                    // If partition name already exists and their partition values are not the same, change partition name.
+                    if (tablePartitions.containsKey(partitionName) && !tablePartitions.get(partitionName).equals(cell)) {
+                        // change partition name, how to generate a unique partition name
+                        int diff = calculateStringDiff(partitionName, partitionName.toLowerCase(Locale.ROOT));
+                        partitionName = partitionName + "_" + Integer.toHexString(diff);
```
Comment (murphyatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java:1428]: what's the purpose to add the diff into partition name ? 
is there any compatibility issue with it ?

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzerUtils.java:1428]: partiiton names in FE  are stored as case-insensitive, we should ensure its name should be different in  case-insensitive.

You can see current bug in : https://github.com/StarRocks/starrocks/issues/54202
```
    @SerializedName(value = "idToPartition")
    protected Map<Long, Partition> idToPartition = new HashMap<>();
    protected Map<String, Partition> nameToPartition = Maps.newTreeMap(String.CASE_INSENSITIVE_ORDER)
```

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]
