### PR TITLE
[BugFix] check null as default catalog

### LINKED ISSUE #26942: DynamicPartitionScheduler thread got exception and cause mv duplicate partition
add  partition_ttl_number for mv and let partitions deleted ,  after restart fe,   `show partitions from mv`  will have  duplicate partitions

### Steps to reproduce the behavior (Required)
1. CREATE TABLE 
```
CREATE TABLE `event1` (
  `event_id` int(11) NULL COMMENT "Unique query id",
  `event_type` varchar(65533) NULL COMMENT "Unique query id",
  `event_time` datetime NULL COMMENT "Query start time"
) ENGINE=OLAP
DUPLICATE KEY(`event_id`, `event_type`)
COMMENT "OLAP"
PARTITION BY RANGE(`event_time`)
(PARTITION p20230101 VALUES [("2023-01-01 00:00:00"), ("2023-01-02 00:00:00")),
PARTITION p20230102 VALUES [("2023-01-02 00:00:00"), ("2023-01-03 00:00:00")),
PARTITION p20230103 VALUES [("2023-01-03 00:00:00"), ("2023-01-04 00:00:00")),
PARTITION p20230104 VALUES [("2023-01-04 00:00:00"), ("2023-01-05 00:00:00")),
PARTITION p20230105 VALUES [("2023-01-05 00:00:00"), ("2023-01-06 00:00:00")),
PARTITION p20230106 VALUES [("2023-01-06 00:00:00"), ("2023-01-07 00:00:00")),
PARTITION p20230107 VALUES [("2023-01-07 00:00:00"), ("2023-01-08 00:00:00")),
PARTITION p20230108 VALUES [("2023-01-08 00:00:00"), ("2023-01-09 00:00:00")))
DISTRIBUTED BY HASH(`event_id`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"dynamic_partition.enable" = "false",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-3",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "1",
"dynamic_partition.history_partition_num" = "0",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

CREATE MATERIALIZED VIEW `event1_mv` (`event_id`, `event_type`, `event_time`)
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`event_time`)
DISTRIBUTED BY HASH(`event_id`) BUCKETS 1
REFRESH ASYNC
PROPERTIES (
"replication_num" = "1",
"replicated_storage" = "true",
"partition_ttl_number" = "4",
"partition_refresh_number" = "1",
"force_external_table_query_rewrite" = "true",
"storage_medium" = "HDD"
)
AS SELECT `event1`.`event_id`, `event1`.`event_type`, `event1`.`event_time`
FROM `event`.`event1`;

```
3. INSERT INTO 
```
insert into event1 values(81, "A81", "2023-01-01 14:09:10");
insert into event1 values(81, "A81", "2023-01-02 14:09:10");
insert into event1 values(81, "A81", "2023-01-03 14:09:10");
insert into event1 values(81, "A81", "2023-01-05 14:09:10");
insert into event1 values(81, "A81", "2023-01-07 14:09:10");
insert into event1 values(81, "A81", "2023-01-08 14:09:10");

```

### Expected behavior (Required)
mv partition_ttl_number work well. 

### Real behavior (Required)
have duplicate partition and  DynamicPartitionScheduler get npe 
```
show partitions from event1_mv;
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+------------------------------------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+
| PartitionId | PartitionName | VisibleVersion | VisibleVersionTime  | VisibleVersionHash | State  | PartitionKey | Range                                                                                                | DistributionKey | Buckets | ReplicationNum | StorageMedium | CooldownTime        | LastConsistencyCheckTime | DataSize | IsInMemory | RowCount |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+------------------------------------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+
| 10145       | p20230101     | 1              | 2023-07-11 10:56:51 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-01 00:00:00]; ..types: [DATETIME]; keys: [2023-01-02 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 11005       | p20230101     | 1              | 2023-07-11 10:58:16 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-01 00:00:00]; ..types: [DATETIME]; keys: [2023-01-02 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 10136       | p20230104     | 1              | 2023-07-11 10:56:51 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-04 00:00:00]; ..types: [DATETIME]; keys: [2023-01-05 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 11010       | p20230105     | 2              | 2023-07-11 10:58:19 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-05 00:00:00]; ..types: [DATETIME]; keys: [2023-01-06 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 10142       | p20230106     | 1              | 2023-07-11 10:56:51 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-06 00:00:00]; ..types: [DATETIME]; keys: [2023-01-07 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 10139       | p20230107     | 1              | 2023-07-11 10:56:51 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-07 00:00:00]; ..types: [DATETIME]; keys: [2023-01-08 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
| 11037       | p20230108     | 2              | 2023-07-11 10:58:27 | 0                  | NORMAL | event_time   | [types: [DATETIME]; keys: [2023-01-08 00:00:00]; ..types: [DATETIME]; keys: [2023-01-09 00:00:00]; ) | event_id        | 1       | 1              | HDD           | 9999-12-31 23:59:59 | NULL                     | 0B       | false      | 0        |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+------------------------------------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by hongli-my**
Fixes #26942

mv partitionRefTableExprs  do not save catalog after restart fe will cause exception

TableName   do not save default catalog
```
    public String toString() {
        StringBuilder stringBuilder = new StringBuilder();
        if (catalog != null && !CatalogMgr.isInternalCatalog(catalog)) {
            stringBuilder.append(catalog).append(".");
        }
        if (db != null) {
            stringBuilder.append(db).append(".");
        }
        stringBuilder.append(tbl);
        return stringBuilder.toString();
    }
```
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java [hunk 1]
```diff
@@ -71,6 +73,9 @@ public MetadataMgr(LocalMetastore localMetastore, ConnectorMgr connectorMgr,
     }
 
     public Optional<ConnectorMetadata> getOptionalMetadata(String catalogName) {
+        if (Strings.isNullOrEmpty(catalogName)) {
+            catalogName = InternalCatalog.DEFAULT_INTERNAL_CATALOG_NAME;
+        }
```
Comment (hongli-my) [inline fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java:78]: or  add check in isInternalCatalog ?

Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java:78]: The current change makes sense. It means if the input catalog-name is null, the internal catalog will be returned.
But this will change this function's behaviour, I suggest you add a comment for this functions behavior and make sure all the usages of this function won't be influenced by this change.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|1|2|50.00%|[82]|

File: fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java (hunk 1 above)
Comment (hongli-my) [reply fe/fe-core/src/main/java/com/starrocks/server/MetadataMgr.java:83]: done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/MetadataMgr.java|2|2|100.00%|[]|

**Review by imay — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
