### PR TITLE
[BugFix] Fix concurrency bug of insert overwrite with drop table

### LINKED ISSUE #10681: there is concurrency bug when insert overwrite with drop table/mv
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t1
2. create materialized view based on table t1 with refresh async
3. insert some records into t1
4. drop materialized view

### Expected behavior (Required)
there is no concurrency problem.
### Real behavior (Required)

the FE restart failed
2022-09-01 10:59:36,156 INFO (replayer|72) [Database.unprotectDropTable():471] finished dropping table[mv1] in db[test_mv_async_db_7db0fb9a_29a0_11ed_9998_00163e0e489a], tableId: 14952216
2022-09-01 10:59:36,156 INFO (replayer|72) [DatabaseTransactionMgr.replayUpsertTransactionState():1588] replay a visible transaction TransactionState. txn_id: 1269130, label: insert_7dd6f993-29a0-11ed-91ae-00163e0bb6a9, db id: 10002, table id list: 10452371, callback id: -1, coordinator: FE: [172.26.195.98](http://172.26.195.98/), transaction status: VISIBLE, error replicas num: 0, repl
ica ids: , prepare time: 1662000480117, commit time: 1662000480130, finish time: 1662000480151, write cost: 13ms, publish cost: 21ms, total cost: 34ms, reason:  attachment: com.starrocks.transaction.InsertTxnCommitAttachment@656c57d8
2022-09-01 10:59:36,158 INFO (replayer|72) [TaskManager.dropTasks():307] drop tasks:[14952259]
2022-09-01 10:59:36,158 ERROR (replayer|72) [EditLog.loadJournal():943] Operation Type 10002
java.lang.NullPointerException: null
        at com.starrocks.server.LocalMetastore.replayAddPartition(LocalMetastore.java:1356) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayAddPartition(GlobalStateMgr.java:1826) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:210) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1702) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1568) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1631) [starrocks-fe.jar:?]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.4

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10681

## Problem Summary(Required) ：

insert overwrite will lead to restart fe failure. the reason is that there is concurrency bug when add partition during insert overwrite. fix it by checking whether the target table exists during insert overwrite

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java [hunk 1]
```diff
@@ -205,17 +204,25 @@ private void executeInsert() throws Exception {
 
     private void createTempPartitions() throws DdlException {
         long createPartitionStartTimestamp = System.currentTimeMillis();
+        Database db = getAndWriteLockDatabase(dbId);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java:207]: You get db write lock here but not release it.

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/load/InsertOverwriteJobRunner.java]: fixed

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 36 / 46 (78.26%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/PartitionUtils.java|3|5|60.00%|[36, 39]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobRunner.java|32|40|80.00%|[223, 247, 249, 278, 302, 311, 314, 322]|
|:large_blue_circle:|com/starrocks/load/InsertOverwriteJobManager.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
@Mergifyio backport branch-2.4
