### PR TITLE
[BugFix] shorten jdbc driver name to avoid file name too long

### LINKED ISSUE #42857: ERROR when using long jdbc_uri in JDBC Catalogue config
### Steps to reproduce the behavior (Required)
1. Create the external JDBC catalog with jdbc_uri longer than 136 characters:
```
CREATE EXTERNAL CATALOG ext
PROPERTIES (
    "type"="jdbc",
    "user"="user",
    "password"="pass",
    "jdbc_uri"="jdbc:mysql://(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,zeroDateTimeBehavior=ROUND)",
    "driver_url"="https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar",
    "driver_class"="com.mysql.cj.jdbc.Driver"
);
```
2. `SELECT * from ext.db.table;`

### Expected behavior (Required)
Query executed and result returned.

### Real behavior (Required)
Query 1 ERROR at Line 647: : fail to open tmp file when downloading file from https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.30/mysql-connector-java-8.0.30.jar

### StarRocks version (Required)
3.2.4

### Additional info
It looks like the driver jar file link is created in BE node that has the name longer that allowed:
`'jdbc_mysql_(host=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.com,zeroDateTimeBehavior=ROUND)_95cde01c78e7b04e13305338d60e056a_1710923312296.jar'`

### PR DESCRIPTION
**Pull request by dirtysalt**
## Why I'm doing:

If user specify long jdbc uri, we will fail to download file. because right now, file name length is almost identical to jdbc uri length, and it will probably exceed linx file name max size(255)

## What I'm doing:

This PR do:
- shorten jdbc driver name: if it's too long, reduce it using crypto hash.
- refactor be side error message, easily to identify real problem.

And after that, downloaded file will be

> jdbc_db64f463c250eccc7f19f6c69aa5f83b19211209df86783b681a9e0a139abd78_95cde01c78e7b04e13305338d60e056a_1711579009617.jar

And error message will be 
>  (1064, 'fail to open tmp file when downloading file from http://127.0.0.1:41006/data/mysql-connector-java-8.0.28.jar. error = File name too long')

Fixes https://github.com/StarRocks/starrocks/issues/42857

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java [hunk 1]
```diff
@@ -180,9 +182,34 @@ private static String buildCatalogDriveName(String uri) {
         // -> jdbc_postgresql_172.26.194.237_5432_db_pg_select
         // requirement: it should be used as local path.
         // and there is no ':' in it to avoid be parsed into non-local filesystem.
-        return uri.replace("//", "")
-                .replace("/", "_")
-                .replace(":", "_");
+
+        String ans = uri.replace("//", "")
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:186]: can we remove all non [^0-9a-zA-Z_] chars for safety.

File: fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java [hunk 2]
```diff
@@ -180,9 +182,34 @@ private static String buildCatalogDriveName(String uri) {
...
+                .replace('/', '_')
+                .replace(':', '_');
+
+        // currently we use this uri as part of name of download file.
+        // so if this uri is too long, we might fail to write file on BE side.
+        // so here we have to shorten it to reduce fail probability because of long file name.
+
+        // in most cases, jdbc uri is not that long, so we can preserve original information.
+        if (ans.length() > 128) {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:195]: might be to make it configurable in case in user's env, it needs to be even shorter.

File: be/src/util/download_util.cpp [hunk 3]
```diff
@@ -42,8 +41,10 @@ Status DownloadUtil::download(const std::string& url, const std::string& target_
     });
 
     if (fp == nullptr) {
-        LOG(ERROR) << fmt::format("fail to open file {}", tmp_file);
-        return Status::InternalError(fmt::format("fail to open tmp file when downloading file from {}", url));
+        int errnum = errno;
```
Comment (kevincai) [inline be/src/util/download_util.cpp:44]:
```suggestion
        std::string errmsg = strerror(errnum);
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java (hunk 1 above)
Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:186]: I thin it's ok.

File: fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java (hunk 2 above)
Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:195]: well,  I've counted that 128 will be very safe without filename too long problem.

if you insist, I can add a config item.

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:195]: can't hold high expectation on user's env. e.g what kind of fs type they will use. lol

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:195]: @kevincai do you insist or just suggestion? if suggestion, I think we can introduce config item later. because by my calculation, 128 bytes is enough.

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:195]: ok. do it later or encounter it in user's env.

File: test/sql/test_catalog/R/test_iceberg_hadoop_catalog
Comment (kevincai) [inline test/sql/test_catalog/R/test_iceberg_hadoop_catalog:1]: is this a separate fix for the FE sql test?

**Review by kevincai — DISMISSED** [review]

File: test/sql/test_catalog/R/test_iceberg_hadoop_catalog
Comment (dirtysalt) [reply test/sql/test_catalog/R/test_iceberg_hadoop_catalog:1]: no, just merge this pr https://github.com/StarRocks/starrocks/pull/43360 to pass sql-test.

File: fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java [hunk 4]
```diff
@@ -180,9 +182,33 @@ private static String buildCatalogDriveName(String uri) {
...
+        String ans = uri.replaceAll("[^0-9a-zA-Z]", "_");
+
+        // currently we use this uri as part of name of download file.
+        // so if this uri is too long, we might fail to write file on BE side.
+        // so here we have to shorten it to reduce fail probability because of long file name.
+        // in most cases, jdbc uri is not that long, so we can preserve original information.
+
+        final String prefix = "jdbc_";
+        final int signLength = 64;
+        if (ans.length() > (signLength + prefix.length())) {
```
Comment (silverbullet233) [inline fe/fe-core/src/main/java/com/starrocks/catalog/JDBCTable.java:194]: can we not distinguish length? All driver names are generated in some way instead of using URL directly. We only need to ensure that the name generated by the same jdbc uri is the same.

**Review by silverbullet233 — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Review by kevincai — APPROVED** [review]

**Comment by kevincai** [comment]
A potential issue about this change. When user upgrades its cluster, the driver has to be download again. In case there is no out internet accessing or the original download url invalid, it will cause the function break immediately.

Worth to mention this as a "Behavior Change"!

**Comment by dirtysalt** [comment]
@mergify backport branch-3.2
