### PR TITLE
[BugFix]fix core dump when start the be with page_cache init metrics

### LINKED ISSUE #52753: Bug: BE crash when start up with calculate_metrics stack
### Steps to reproduce the behavior (Required)
```
*** Aborted at 1730782578 (unix time) try "date -d @1730782578" if you are using GNU date ***
PC: @          0x5e7b608 std::_Function_handler<void (), starrocks::init_metrics()::{lambda()#2}>::_M_invoke(std::_Any_data const&)
*** SIGSEGV (@0x10) received by PID 23969 (TID 0x7f269307c700) from PID 16; stack trace: ***
    @     0x7f269cb88997 __pthread_once_slow
    @          0x7a6fc00 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x7f269cb8b730 (/usr/lib/x86_64-linux-gnu/libpthread-2.28.so+0x1272f)
    @          0x5e7b608 std::_Function_handler<void (), starrocks::init_metrics()::{lambda()#2}>::_M_invoke(std::_Any_data const&)
    @          0x3517746 starrocks::calculate_metrics(void*)
    @          0xc1a8360 execute_native_thread_routine
    @     0x7f269cb80fa3 start_thread
    @     0x7f269c90406f clone
start time: Tue 05 Nov 2024 01:20:11 PM CST, server uptime:  13:20:11 up 27 min,  0 users,  load average: 0.11, 0.04, 0.03
Ignored unknown config: routine_load_thread_pool_size
Ignored unknown config: starlet_fslib_s3client_read_max_retries
```
### Expected behavior (Required)
Started
### Real behavior (Required)
Core 
### StarRocks version (Required)
3.3.3

### PR DESCRIPTION
**Pull request by SaintBacchus**
## What I'm doing:

Fixes #52753

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by trueeyu** [comment]
@Mergifyio rebase main

**Review by trueeyu — APPROVED** [review]

File: be/src/storage/page_cache.cpp [hunk 1]
```diff
@@ -85,11 +68,27 @@ static void init_metrics() {
...
 }
 
+void StoragePageCache::release_global_cache() {
+    if (_s_instance != nullptr) {
+        delete _s_instance;
+        _s_instance = nullptr;
+    }
+}
+
+void StoragePageCache::prune() {
```
Comment (kevincai) [inline be/src/storage/page_cache.cpp:85]: thought it was unnecessary moved code. lol.

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]
