### PR TITLE
check decimal overflow in predicate in decimal style instead binary style

### LINKED ISSUE #3335: decimal overflow issue
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h0;
CREATE DATABASE h0;
USE h0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 SMALLINT NULL ,c_0_1 BOOLEAN NULL ,c_0_2 BOOLEAN NOT NULL ,c_0_3 DECIMAL(3, 2)  NOT NULL ,c_0_4 DOUBLE NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_1) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 CHAR(11) NULL ,c_1_1 DECIMAL(33, 18)  MIN NULL ) AGGREGATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
INSERT INTO t1 VALUES ("8ZCRF6", 0.000279356791742725), ("U", NULL);
INSERT INTO t0 VALUES (3, false, true, 0.03, 0.3161943737412014), (NULL, false, true, 0.02, 0.2187381172916819), (NULL, false, false, 0.00, 0.6767061395079788);
INSERT INTO t0 VALUES (11, true, false, 0.05, 0.8910327185329213), (NULL, false, true, 0.04, 0.11126594789601851);
2.  SELECT t1.c_1_0 FROM t1 WHERE STARTS_WITH(CASE  WHEN false THEN CASE  WHEN ("")  BETWEEN ("") AND (NULL)  THEN "5" END  WHEN false THEN MONEY_FORMAT(-344970686)  ELSE "" END, (("")||("")))  GROUP BY t1.c_1_0 HAVING ((MIN(CAST(165382566 AS DECIMAL(7, 4) ) ) ) IS NOT NULL) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE STARTS_WITH(CASE  WHEN false THEN CASE  WHEN ("")  BETWEEN ("") AND (NULL)  THEN "5" END  WHEN false THEN MONEY_FORMAT(-344970686)  ELSE "" END, (("")||("")))  GROUP BY t1.c_1_0 HAVING (NOT (((MIN(CAST(165382566 AS DECIMAL(7, 4) ) ) ) IS NOT NULL))) UNION ALL SELECT t1.c_1_0 FROM t1 WHERE STARTS_WITH(CASE  WHEN false THEN CASE  WHEN ("")  BETWEEN ("") AND (NULL)  THEN "5" END  WHEN false THEN MONEY_FORMAT(-344970686)  ELSE "" END, (("")||("")))  GROUP BY t1.c_1_0 HAVING ((((MIN(CAST(165382566 AS DECIMAL(7, 4) ) ) ) IS NOT NULL)) IS NULL);

```
crash.log:
*** Check failure stack trace: ***
    @          0x8e0699d  google::LogMessage::Fail()
    @          0x8e08c79  google::LogMessage::SendToLog()
    @          0x8e06519  google::LogMessage::Flush()
    @          0x8e09279  google::LogMessageFatal::~LogMessageFatal()
    @          0x72e419f  starrocks::vectorized::MaxMinAggregateFunction<>::update()
    @          0x72e54c7  starrocks::vectorized::AggregateFunctionBatchHelper<>::update_batch()
    @          0x6a5d54e  starrocks::Aggregator::compute_batch_agg_states()
    @          0x5c4767f  starrocks::vectorized::AggregateBlockingNode::open()
    @          0x670a691  starrocks::vectorized::ProjectNode::open()
    @          0x5018761  starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x5017e4f  starrocks::PlanFragmentExecutor::open()
    @          0x4e92d08  starrocks::FragmentExecState::execute()
    @          0x4e97dd1  starrocks::FragmentMgr::exec_actual()
    @          0x4e987ed  _ZZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS_23TExecPlanFragmentParamsERKSt8functionIFvPNS_20PlanFragmentExecutorEEESA_ENKUlvE_clEv
    @          0x4ea18d2  _ZSt13__invoke_implIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEESB_EUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x4ea14c3  _ZSt10__invoke_rIvRZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS0_23TExecPlanFragmentParamsERKSt8functionIFvPNS0_20PlanFragmentExecutorEEESB_EUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESF_E4typeEOSG_DpOSH_
    @          0x4ea0c74  _ZNSt17_Function_handlerIFvvEZN9starrocks11FragmentMgr18exec_plan_fragmentERKNS1_23TExecPlanFragmentParamsERKSt8functionIFvPNS1_20PlanFragmentExecutorEEESC_EUlvE_E9_M_invokeERKSt9_Any_data
    @          0x3ddbb18  std::function<>::operator()()
    @          0x528e5a2  starrocks::FunctionRunnable::run()
    @          0x528b080  starrocks::ThreadPool::dispatch_thread()
    @          0x52a86ca  std::__invoke_impl<>()
    @          0x52a7fad  std::__invoke<>()
    @          0x52a73c4  _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x52a5f30  std::_Bind<>::operator()<>()
    @          0x52a2e16  std::__invoke_impl<>()
    @          0x52a0dde  _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0x529c579  std::_Function_handler<>::_M_invoke()
    @          0x3ddbb18  std::function<>::operator()()
    @          0x5275603  starrocks::Thread::supervise_thread()
    @     0x7f55df470ea5  start_thread
    @     0x7f55de8758dd  __clone
    @              (nil)  (unknown)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_01_ASAN f9efae0 |
+------------------------------+

### LINKED ISSUE #3336: decimal v3 overflow check bug
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d0;
CREATE DATABASE d0;
USE d0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 VARCHAR(21) NOT NULL ,c_0_1 DECIMAL(23, 16)  NOT NULL ,c_0_2 CHAR(1) NOT NULL ,c_0_3 DATETIME NULL ,c_0_4 CHAR(31) NOT NULL ,c_0_5 VARCHAR(21) NOT NULL ,c_0_6 DECIMAL(21, 10)  NULL ,c_0_7 TINYINT NULL ,c_0_8 CHAR(11) NOT NULL ,c_0_9 DECIMAL(3, 1)  NOT NULL ,c_0_10 CHAR(1) NOT NULL ,c_0_11 DECIMAL(4, 1)  NOT NULL ,c_0_12 TINYINT NULL ,c_0_13 LARGEINT NOT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11,c_0_12) DISTRIBUTED BY HASH (c_0_10,c_0_2,c_0_12,c_0_11,c_0_6,c_0_8,c_0_7,c_0_9) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 DECIMAL(28, 8)  NOT NULL ,c_1_1 HLL HLL_UNION NULL ,c_1_2 CHAR(21) MIN NULL ,c_1_3 PERCENTILE PERCENTILE_UNION NULL ,c_1_4 BITMAP BITMAP_UNION NOT NULL ,c_1_5 DECIMAL(2, 1)  REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DECIMAL(14, 5)  NOT NULL ,c_2_1 DECIMAL(6, 5)  NOT NULL ,c_2_2 DECIMAL(17, 4)  NULL ,c_2_3 VARCHAR(1) NOT NULL ) UNIQUE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_1,c_2_0) properties("replication_num"="3") ;
INSERT INTO t1 VALUES (295336227254.19593924, hll_hash(""), "xcq7P", percentile_hash("-2033817773"), bitmap_hash("QjPY"), 0.3), (557965786181.70153522, hll_hash("vPG"), NULL, percentile_hash("-92178641"), bitmap_hash("N"), 0.3), (972047080868.44401646, hll_hash("KY"), "VdJa52qHd", percentile_hash("15921951"), bitmap_hash("ocIkk9A"), 0.7), (521350111150.28895167, hll_hash(""), "li", percentile_hash("15921951"), bitmap_hash("aAyk"), 0.3);
INSERT INTO t1 VALUES (445817411073.79093586, hll_hash(""), "", percentile_hash("-92178641"), bitmap_hash(""), 0.7), (788401212957.00369564, hll_hash("Xzo9a5uyP"), "r", percentile_hash("-476624963"), bitmap_hash(""), 0.3);
INSERT INTO t0 VALUES ("by", 7.813734E-10, "", "1970-01-01 08:00:00", "nJ", "Ef81", 9.0543076188, 1, "MbSu", 2.2, "", 13.9, 0, -2033817773), ("Jr", 5.412421E-10, "", "1970-01-01 08:00:00", "aEe1", "qP", 3.2730243691, 7, "FLBj", 9.4, "", 86.5, 3, -1761985674);
INSERT INTO t1 VALUES (932961862625.90303870, hll_hash("IZnEy"), "XY0xTNd4U", percentile_hash("-476624963"), bitmap_hash("UmcU"), 0.8), (828798054187.75596402, hll_hash("wN"), "mKAGv", percentile_hash("-1862154947"), bitmap_hash("7d"), 0.1);
INSERT INTO t0 VALUES ("0YbmO", 5.708338E-10, "", NULL, "RqoddxtYv", "sF", 7.4490549636, 0, "a", 4.1, "", 72.7, 0, -2095859705);
INSERT INTO t2 VALUES (6467.05542, 0.00001, 542786051.8816, "");
INSERT INTO t0 VALUES ("", 2.274393E-10, "", "1970-01-01 08:00:00", "uQZjr8h8K", "SZ", 1.3935338214, 5, "y", 5.5, "", 82.1, 4, -1146830204), ("4Z", 1.03494E-11, "", "1970-01-01 08:00:00", "", "Rm", 1.8138247045, 2, "Y3", 7.0, "", 30.1, 0, -92178641);
INSERT INTO t1 VALUES (612876716177.26535017, hll_hash(""), "xULm", percentile_hash("-1637855760"), bitmap_hash(""), 0.1);
INSERT INTO t0 VALUES ("cBlVI", 2.386275E-10, "", "1970-01-01 08:00:00", "27", "owJ2Gtg", 3.5100122066, 3, "4", 1.5, "", 92.7, 7, -765850697);
INSERT INTO t0 VALUES ("LUz77", 4.273354E-10, "", "1970-01-01 08:00:00", "bg", "x", 8.5578423633, 0, "X", 9.3, "", 76.5, 6, -1);
INSERT INTO t2 VALUES (18.07556, 0.00005, 398378129.2931, "");
INSERT INTO t0 VALUES ("3rPl1", 9.528245E-10, "", "1970-01-01 08:00:00", "oVpQP", "E", 9.0477259393, 7, "WB", 0.0, "", 73.2, 7, -588987548), ("", 5.7657E-12, "", "1970-01-01 08:00:00", "", "", 4.8706785669, 1, "", 4.6, "", 22.2, 7, -1877199665);
INSERT INTO t2 VALUES (9433.66081, 0.00000, 456409896.6126, ""), (694.59872, 0.00006, 554963914.2733, "");
INSERT INTO t1 VALUES (949227741045.01600446, hll_hash(""), NULL, percentile_hash("-2095859705"), bitmap_hash("j"), 0.0), (362597929218.38208270, hll_hash(""), "", percentile_hash("-825551532"), bitmap_hash("VFSqY7Y"), 0.4);
INSERT INTO t2 VALUES (5181.74486, 0.00001, 579768604.7874, ""), (9305.74778, 0.00004, NULL, "");
INSERT INTO t2 VALUES (4591.05097, 0.00008, 68392216.3541, "");
INSERT INTO t2 VALUES (8144.89677, 0.00001, 830697646.4410, "");
2. SELECT DISTINCT CAST(4230.10443 AS DECIMAL(7, 4) )  FROM t1,  (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3 FROM t2) subt2 LEFT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8, t0.c_0_9, t0.c_0_10, t0.c_0_11, t0.c_0_12, t0.c_0_13 FROM t0 WHERE  ( t0.c_0_7 ) < ( t0.c_0_7 ) ) subt0 ON subt2.c_2_2 = subt0.c_0_1 AND subt2.c_2_2 <= subt0.c_0_1 AND subt2.c_2_0 >= subt0.c_0_10 AND subt2.c_2_0 < subt0.c_0_10 AND subt2.c_2_0 = subt0.c_0_2 AND 1111.60392 > (("")||(""));

```
crash.log:
*** Aborted at 1644808393 (unix time) try "date -d @1644808393" if you are using GNU date ***
PC: @          0x21dbe4a starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
*** SIGSEGV (@0x13406000) received by PID 30334 (TID 0x7f5ed1b55700) from PID 322985984; stack trace: ***
    @          0x347bf62 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f5f28ff7630 (unknown)
    @          0x21dbe4a starrocks::vectorized::AggHashSetOfOneNumberKey<>::build_set()
    @          0x21cbeb2 starrocks::vectorized::DistinctStreamingNode::get_next()
    @          0x1c8fbfa starrocks::PlanFragmentExecutor::_get_next_internal_vectorized()
    @          0x1c91535 starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1c92107 starrocks::PlanFragmentExecutor::open()
    @          0x1c2db32 starrocks::FragmentExecState::execute()
    @          0x1c31fdc starrocks::FragmentMgr::exec_actual()
    @          0x1d58d59 starrocks::ThreadPool::dispatch_thread()
    @          0x1d54918 starrocks::Thread::supervise_thread()
    @     0x7f5f28fefea5 start_thread
    @     0x7f5f283f48dd __clone
    @                0x0 (unknown)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER01_RELEASE f9efae0 |
+---------------------------------+

### LINKED ISSUE #3337: Query sql crash
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS h0;
CREATE DATABASE h0;
USE h0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 SMALLINT NOT NULL ,c_0_1 BOOLEAN NOT NULL ,c_0_2 DECIMAL(17, 16)  NULL ,c_0_3 BOOLEAN NOT NULL ,c_0_4 DATETIME NOT NULL ,c_0_5 BOOLEAN NOT NULL ,c_0_6 SMALLINT NOT NULL ,c_0_7 CHAR(1) NOT NULL ,c_0_8 INT NULL ,c_0_9 DECIMAL(20, 3)  NOT NULL ,c_0_10 BOOLEAN NOT NULL ,c_0_11 DATE NULL ,c_0_12 FLOAT NOT NULL ,c_0_13 DECIMAL(6, 4)  NULL ,c_0_14 INT NULL ,c_0_15 DATE NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10,c_0_11) DISTRIBUTED BY HASH (c_0_8,c_0_9,c_0_5,c_0_0,c_0_2) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 BOOLEAN NOT NULL ,c_1_1 BOOLEAN NOT NULL ,c_1_2 DOUBLE NOT NULL ,c_1_3 DOUBLE NOT NULL ) UNIQUE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_1,c_1_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (13, false, 3E-16, true, "1970-01-01 08:00:00", false, 2, "", 2, 64517933055706.827, true, "1970-01-01", 0.7053804648775668, 0.0008, NULL, "1970-01-01"), (8, true, 6E-16, true, "1970-01-01 08:00:00", false, 8, "", 10, 62469880816815.198, true, "1970-01-01", 1.431180356E9, 0.0063, 20, "1970-01-01");
INSERT INTO t1 VALUES (false, true, 1.559530553E9, 8.10534736E8), (true, true, 0.06846710466493344, 0.5410257147015458);
INSERT INTO t1 VALUES (true, true, 0.6605629197176323, 0.7952242433407759);
INSERT INTO t0 VALUES (5, true, 6E-16, false, "1970-01-01 08:00:00", false, 4, "", 28, 86514164896164.826, false, "1970-01-01", 0.4376730790619191, 0.0027, 17, "1970-01-01");
INSERT INTO t1 VALUES (true, false, 0.2672029978729118, 0.6579393933973888), (false, false, 0.9440533066289989, 0.5295148289491246);
INSERT INTO t1 VALUES (true, false, 0.7760999474928164, 0.159173698111437);
INSERT INTO t1 VALUES (true, true, 0.6072236058483556, 0.890583452109418), (true, false, 1.638208903E9, -9.56904592E8);
2. SELECT ((-924846790)/(-948029484)) FROM  t1 RIGHT ANTI JOIN t0 ON t1.c_1_0 = t0.c_0_8 AND t1.c_1_0 < t0.c_0_8 AND t1.c_1_3 >= t0.c_0_5 AND t1.c_1_3 >= t0.c_0_5 GROUP BY CASE  WHEN (("1970-01-15") IS NOT NULL) THEN CAST(((-471308111)+(1586188230)) AS DECIMAL(7, 4) )   WHEN true THEN CASE  WHEN false THEN t0.c_0_2 ELSE t0.c_0_2 END ELSE t0.c_0_2 END;

```
crash.log:
PC: @          0x216dc0a starrocks::vectorized::DistinctBlockingNode::open()
*** SIGSEGV (@0x17944000) received by PID 10378 (TID 0x7f5030754700) from PID 395591680; stack trace: ***
    @          0x347bf62 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f508830c630 (unknown)
    @          0x216dc0a starrocks::vectorized::DistinctBlockingNode::open()
    @          0x2385180 starrocks::vectorized::ProjectNode::open()
    @          0x1c9141b starrocks::PlanFragmentExecutor::_open_internal_vectorized()
    @          0x1c92107 starrocks::PlanFragmentExecutor::open()
    @          0x1c2db32 starrocks::FragmentExecState::execute()
    @          0x1c31fdc starrocks::FragmentMgr::exec_actual()
    @          0x1d58d59 starrocks::ThreadPool::dispatch_thread()
    @          0x1d54918 starrocks::Thread::supervise_thread()
    @     0x7f5088304ea5 start_thread
    @     0x7f50877098dd __clone
    @                0x0 (unknown)

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_02_RELEASE f9efae0 |
+---------------------------------+

### LINKED ISSUE #3342: Large decimal overflows when constructing VectorizedLiteral because of lack of castexpr turning decimal type to wider one.
### Steps to reproduce the behavior (Required)
```
select connection_id()
create database test_filter_8bda5706_8ce9_11ec_9403_00163e0e489a
use test_filter_8bda5706_8ce9_11ec_9403_00163e0e489a
set vectorized_engine_enable=true

        CREATE TABLE t0 (
          c0 BOOLEAN,
          c1 DECIMAL(13, 0)
        )
        DUPLICATE KEY (c0,c1)
        DISTRIBUTED BY HASH (c1) BUCKETS 5
        properties("replication_num"="1")
        
insert into t0 values(0, 10),(1, NULL)
select * from t0 where c1 > -9.223372E+18 order by c0 asc nulls last;
```

### Expected behavior (Required)
output as follows
```
+------+------+
| c0   | c1   |
+------+------+
|    0 |   10 |
+------+------+
```

### Real behavior (Required)

empty result set

### StarRocks version (Required)
 - 46b98a3767d49c994a9423f80299f9156871843c

### PR DESCRIPTION
**Pull request by satanson**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：
https://github.com/StarRocks/starrocks/issues/3342
Fixes #

## Problem Summary(Required) ：
for Predicates that contain constant operators of decimal type, the constant value is transferred to
to BE in string type, and in BE, an corresponding VectorizedLiteral is constructed after string value
is converted to decimal via the string-to-decimal casting function who checks decimal overflowing in
decimal style. but in FE, checking decimal overflow in binary style instead of decimal style would
given an incorrect result that overflow checking should fail(in decimal style) expectedly but succeeds
(in decimal style)actually. When checkLiteralOverflowInDecimalStyle fails, proper cast exprs are interpolated
into Predicates to cast the type of decimal constant value to a type wider enough to holds the value.

Why we needs two decimal overflow checking function?
1. for a Predicate like col_decimal32p9s0 > -2147483648, the type of col_decimal32p9s3 is DECIMAL32(9,0), the type of -2147483.648 is DECIMAL64(10,0).  Underlying integer value of -2147483.648 is -2147483648, becase  int32_t can holds this value, so overflow check in binary style tells that -2147483.648 not overflows, so change type of  -2147483.648 to DECIMAL32(9,0) in Predicate and turn it into string " -2147483.648" and transfer it to BE, on BE's receiving, BE try to parse "-2147483.648" into DECIMAL32(9,0), it fails because -2147483.648 is less than -99999.9999. so we should adopt overflow checking in decimal style which tells that -2147483.648 overflows, so common type DECIML64(10,0) is computed out, and both lhs and rhs of the predicate are casted into DECIMAL64(10, 0), ...., BE succeeds in parseing "-2147483.648" into DECIMAL64(10,0).
2. for ArithmeticExpr and CastExpr involving non-constant expr, correct result type is always computed, a decimal literal  that fails in overflow checking in decimal style are always cast to a wide type. But in BE, overflow checking in binary style is adopted  for performance purpose.
3. for ArithmeticExpr and CastExpr only involving constant expr, the evaluation happens on FE side, FE should abides by BE in overflow checking, so binary style is adopted.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java [hunk 1]
```diff
@@ -400,11 +400,33 @@ public static void checkLiteralOverflow(BigDecimal value, ScalarType scalarType)
...
     }
 
+    // for Predicates that contain constant operators of decimal type, the constant value is transferred to
+    // to BE in string type, and in BE, an corresponding VectorizedLiteral is constructed after string value
+    // is converted to decimal via the string-to-decimal casting function who checks decimal overflowing in
+    // decimal style. but in FE, checking decimal overflow in binary style instead of decimal style would
+    // given an incorrect result that overflow checking should fail(in decimal style) expectedly but succeeds
+    // (in decimal style)actually. When checkLiteralOverflowInDecimalStyle fails, proper cast exprs are interpolated
+    // into Predicates to cast the type of decimal constant value to a type wider enough to holds the value.
+    public static void checkLiteralOverflowInDecimalStyle(BigDecimal value, ScalarType scalarType) throws AnalysisException {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:410]: I still don't understand why we need check by binary overflow and check by decimal overflow logic at the same time.

**Comment by kangkaisen** [comment]
@satanson when you explain a complex logic, would better give an example.

File: fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java (hunk 1 above)
Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:410]: When CastExpr and ArithmeticExpr invokes decimal types, checking overflow in binary type is used. When Predicate invokes decimal types, checking overflow in decimal type is used. examples are showed in Description.

Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:410]: When CastExpr and ArithmeticExpr invokes decimal types, checking overflow in binary type is used. When Predicate invokes decimal types, checking overflow in decimal type is used. examples are showed in Description.

**Comment by kangkaisen** [comment]
```
 Predicate and turn it into string " -2147483.648" and transfer it to BE, on BE's receiving, BE try to parse "-2147483.648" into DECIMAL32(9,0), 
```
Why not pass "-2147483648" format  string  to BE？

File: be/src/exprs/vectorized/literal.cpp [hunk 2]
```diff
@@ -17,25 +19,40 @@ namespace starrocks::vectorized {
...
     }
 
+template <PrimitiveType PT>
+static RunTimeCppType<PT> unpack_decimal(const std::string& s) {
+    static_assert(pt_is_decimal<PT>);
+    RunTimeCppType<PT> value;
+#ifdef IS_LITTLE_ENDIAN
+    strings::memcpy_inlined(&value, &s.front(), sizeof(value));
+#else
+    std::copy(s.rbegin(), s.rend(), (char*)&datum);
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/literal.cpp:29]: typo?

File: be/src/exprs/vectorized/literal.cpp [hunk 3]
```diff
@@ -91,7 +108,13 @@ VectorizedLiteral::VectorizedLiteral(const TExprNode& node) : Expr(node) {
         break;
     }
     case TYPE_DECIMALV2: {
-        _value = ColumnHelper::create_const_column<TYPE_DECIMALV2>(DecimalV2Value(node.decimal_literal.value), 1);
+        DecimalV2Value datum;
+        if (node.decimal_literal.__isset.integer_value) {
```
Comment (kangkaisen) [inline be/src/exprs/vectorized/literal.cpp:112]: After decimal V3 enable, when we will use decimal v2

File: fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java [hunk 4]
```diff
@@ -344,8 +379,9 @@ public double getDoubleValue() {
     protected void toThrift(TExprNode msg) {
         // TODO(hujie01) deal with loss information
         msg.node_type = TExprNodeType.DECIMAL_LITERAL;
-        BigDecimal v = new BigDecimal(value.toBigInteger());
-        msg.decimal_literal = new TDecimalLiteral(value.toPlainString());
+        msg.decimal_literal = new TDecimalLiteral();
+        msg.decimal_literal.value = value.toPlainString();
+        msg.decimal_literal.integer_value = packDecimal();
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:384]: you should call set method.

File: fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java [hunk 5]
```diff
@@ -382,7 +418,7 @@ public int getFracValue() {
         return fracPart.intValue();
     }
 
-    public static void checkLiteralOverflow(BigDecimal value, ScalarType scalarType) throws AnalysisException {
+    public static void checkLiteralOverflowInBinaryStyle(BigDecimal value, ScalarType scalarType) throws AnalysisException {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:421]: should comment when should use `checkLiteralOverflowInBinaryStyle`, when should use `checkLiteralOverflowInDecimalStyle `

File: fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java [hunk 6]
```diff
@@ -237,6 +238,40 @@ private void checkType(Type type) {
         }
     }
 
+    // pack an int32/64/128 value into ByteBuffer in little endian
+    ByteBuffer packDecimal() {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/analysis/DecimalLiteral.java:242]: Add UT for pack and unpack logic

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java [hunk 7]
```diff
@@ -327,6 +327,30 @@ public boolean isNullable() {
         return type.equals(Type.NULL) || isNull;
     }
 
+    public ConstantOperator castToStrictly(Type type) throws Exception {
```
[the remark this answers is not in the document]
Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java:330]: BE adopts binary-style overflow check, which speed up 2.5X ~3.0X in ArithmeticExpr/CastExpr evaluation. when reducing
constant ArithmeticExpr and CastExpr in FE, FE should abides by BE,so it should use binary-style,too. but Predicates contains decimal literal, it should use decimal-style overflow check. it's quite tricky, but there exists no neat and clean solution to this issue.

**Comment by satanson** [comment]
run starrocks_be_unittest

**Comment by satanson** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_be_unittest
