### PR TITLE
[BugFix] Support catalog name in Show materialized views

### LINKED ISSUE #54134: Show Materialized View should honor fully qualified name of database ie.., catalog_name.database_name
### Steps to reproduce the behavior (Required)
```
mysql>
mysql> show materialized views from default_catalog.test;
ERROR 5501 (3F000): Getting analyzing error. Detail message: Unknown database 'default_catalog.test'.
mysql>
mysql>
mysql> use default_catalog.test;
Database changed
mysql> show materialized views;
+-------+---------------+-------+--------------+-----------+-----------------+----------------+---------+-----------+-------------------------+----------------------------+-----------------------+--------------------+----------------------------+------------------------------+----------------------------+--------------------------------------+------------------------------------+-------------------------+----------------------------+------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+------------+
| id    | database_name | name  | refresh_type | is_active | inactive_reason | partition_type | task_id | task_name | last_refresh_start_time | last_refresh_finished_time | last_refresh_duration | last_refresh_state | last_refresh_force_refresh | last_refresh_start_partition | last_refresh_end_partition | last_refresh_base_refresh_partitions | last_refresh_mv_refresh_partitions | last_refresh_error_code | last_refresh_error_message | rows | text
```
### Expected behavior (Required)
Should work like last command above.
### Real behavior (Required)
Throws error: ERROR 5501 (3F000): Getting analyzing error. Detail message: Unknown database 'default_catalog.test'.
### StarRocks version (Required)
 - 3.3.7

### PR DESCRIPTION
**Pull request by amoghmargoor**
## Why I'm doing:
Show Materialized View should honor fully qualified name of database ie.., catalog_name.database_name which fails currently
`mysql>
mysql> show materialized views from default_catalog.test;
ERROR 5501 (3F000): Getting analyzing error. Detail message: Unknown database 'default_catalog.test'.
mysql>
mysql>
`

## What I'm doing:
In this patch the catalog name will be accepted as a part of fully qualified database name in `SHOW MATERIALIZED VIEW`.

Fixes #54134 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java [hunk 1]
```diff
@@ -310,7 +310,14 @@ public ShowResultSet visitShowStatement(ShowStmt statement, ConnectContext conte
         @Override
         public ShowResultSet visitShowMaterializedViewStatement(ShowMaterializedViewsStmt statement, ConnectContext context) {
             String dbName = statement.getDb();
-            Database db = GlobalStateMgr.getCurrentState().getLocalMetastore().getDb(dbName);
+            String catalogName = statement.getCatalogName();
```
Comment (stevenzwu) [inline fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java:313]: why do we need to update/fix `ShowExecutor` for `show materialized views`?

Comment (amoghmargoor) [reply fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java:313]: because ShowExecutor handles the SHOW command including who materialised views.

Comment (stevenzwu) [reply fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java:313]: oh. Somehow I thought `ShowExecutor` is for `show backends` for the backend/executor nodes. This is for executing `show` statements.

**Review by murphyatwork — DISMISSED** [review]

**Comment by amoghmargoor** [comment]
@murphyatwork Just added UT for more code coverage. Can you reapprove it ?

**Review by murphyatwork — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
