### PR TITLE
[BugFix] showing unkonwn resource group should throw Exception

### LINKED ISSUE #6813: Wrong result of show resource group
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'
image

The `show resource group rg1` command accesses a non-existent resource group, which should report an error but not the empty result.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by huangfeng1993**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6813

## Problem Summary(Required) ：
Showing a non-existent resource group should throw Exception，not return empty set.

### CODE REVIEW

**Comment by huangfeng1993** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java [hunk 1]
```diff
@@ -258,7 +258,9 @@ public enum ErrorCode {
     ERR_QUERY_EXCEPTION(5077, new byte[] {'4', '2', '0', '0', '0'},
             "Query cancelled by crash of backends."),
     ERR_BAD_CATALOG_ERROR(5078, new byte[] {'4', '2', '0', '0', '0'},
-            "Unknown catalog.db '%s'");
+            "Unknown catalog.db '%s'"),
+    ERROR_NO_WG_ERROR(5077, new byte[] {'4', '2', '0', '0', '0'},
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java:262]: this code is the same with ERR_QUERY_EXCEPTION.

File: fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java [hunk 2]
```diff
@@ -1545,9 +1545,12 @@ private void handleShowAnalyze() {
         resultSet = new ShowResultSet(stmt.getMetaData(), rows);
     }
 
-    private void handleShowWorkGroup() {
+    private void handleShowWorkGroup() throws AnalysisException {
         ShowWorkGroupStmt showWorkGroupStmt = (ShowWorkGroupStmt) stmt;
         List<List<String>> rows = GlobalStateMgr.getCurrentState().getWorkGroupMgr().showWorkGroup(showWorkGroupStmt);
+        if(showWorkGroupStmt.getName() != null && rows.isEmpty()){
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java:1551]: It will be better to throw this exception in `showWorkGroup(showWorkGroupStmt);` function when the specified database is not found.

Comment (huangfeng1993) [reply fe/fe-core/src/main/java/com/starrocks/qe/ShowExecutor.java]: yeah, you are right.

**Comment by huangfeng1993** [comment]
@Mergifyio rebase

**Comment by huangfeng1993** [comment]
@Mergifyio backport branch-2.2 branch-2.3

**Review by imay — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]
