### PR TITLE
[Bugfix] Remove MultiWorkerPool and only use one thread for publish version worker

### LINKED ISSUE #6524: Publish version tasks in BE do not execute in order as expected and may execute multiple times
### Steps to reproduce the behavior (Required)
In code review for multi_worker_pool.cpp, found pr #61 does not work as expected

https://github.com/StarRocks/starrocks/pull/61#discussion_r881452153

### Expected behavior (Required)
Task execute in different threads and in version order

### Real behavior (Required)
Multiple copies of task submitted to threads and may execute in any order.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6524

## Problem Summary(Required) ：

In MultiWorkerPool's code:
```
    for (auto& partition : req.partition_version_infos) {
        auto pool_id = partition.partition_id % _pools.size();
        auto pool = _pools[pool_id];
        pool->submit_task(task);
    }
```

If a transaction has multiple partitions, it will submit the same task multiple times, and this does not guarantee task execution order, so this PR removes this. 

Since only one thread can order publish version execution to some degree, and the workerpool thread already uses another threadpool(default 8 thread), so workerpool thread count can be set to 1.

### CODE REVIEW

File: be/src/common/config.h [hunk 1]
```diff
@@ -82,12 +82,12 @@ CONF_Int32(create_tablet_worker_count, "3");
...
 CONF_Int32(push_worker_count_normal_priority, "3");
-// Rhe count of thread to high priority batch load.
+// The count of thread to high priority batch load.
 CONF_Int32(push_worker_count_high_priority, "3");
-// Rhe count of thread to publish version.
-CONF_Int32(publish_version_worker_count, "2");
-// The count of thread to publish version per partition.
-CONF_Int32(partition_publish_version_worker_count, "8");
+// The count of thread to publish version. Not used anymore
+CONF_Int32(publish_version_worker_count, "1");
```
Comment (imay) [inline be/src/common/config.h:88]: if this is not used any more why not remove it?

File: be/src/agent/agent_server.cpp [hunk 2]
```diff
@@ -76,7 +75,7 @@ AgentServer::AgentServer(ExecEnv* exec_env, const TMasterInfo& master_info)
     // Both PUSH and REALTIME_PUSH type use _push_workers
     CREATE_AND_START_POOL(PUSH, _push_workers,
                           config::push_worker_count_normal_priority + config::push_worker_count_high_priority);
-    CREATE_AND_START_MULTI_POOL(PUBLISH_VERSION, _publish_version_workers, config::publish_version_worker_count);
```
Comment (imay) [inline be/src/agent/agent_server.cpp:79]: CREATE_AND_START_MULTI_POOL can be removed too?

File: be/src/common/config.h (hunk 1 above)
Comment (wuleistarrocks) [reply be/src/common/config.h:88]: > if this is not used any more why not remove it?

+1 :)

**Review by imay — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
