### PR TITLE
Throw an error when dropping a not-exist user

### LINKED ISSUE #3087: no error reported when drop a non-existent user
### Steps to reproduce the behavior (Required)
`DROP USER user1;`

### Expected behavior (Required)
`user not exist`
### Real behavior (Required)
`Query OK, 0 rows affected (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE 9d8b946 |
+------------------------------------------+
```

### PR DESCRIPTION
**Pull request by chaoyli**
Before this pull request.
```
mysql> drop user Tim;
Query OK, 0 rows affected (0.02 sec)
```

After this pull request.
```
mysql> drop user Tim;
ERROR 1064 (HY000): user default_cluster:Tim does not exist
```

## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3087

### CODE REVIEW

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java [hunk 1]
```diff
@@ -620,6 +620,11 @@ public void dropUser(DropUserStmt stmt) throws DdlException {
             // Allow dropping `superuser@%` when doing `DROP CLUSTER`, but not for `DROP USER`.
             throw new DdlException(String.format("User `%s`@`%s` is not allowed to be dropped.", user, host));
         }
+
+        if (!doesUserExist(stmt.getUserIdentity())) {
+            throw new DdlException("user " + user + " does not exist");
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java:625]:
```suggestion
            throw new DdlException(String.format("User `%s`@`%s` does not exist.", user, host));
```

File: fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java [hunk 2]
```diff
@@ -620,6 +620,11 @@ public void dropUser(DropUserStmt stmt) throws DdlException {
             // Allow dropping `superuser@%` when doing `DROP CLUSTER`, but not for `DROP USER`.
             throw new DdlException(String.format("User `%s`@`%s` is not allowed to be dropped.", user, host));
         }
+
+        if (!doesUserExist(stmt.getUserIdentity())) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/mysql/privilege/Auth.java:624]: Why not do this check in `dropUserInternal`
Some concurrent clients will drop this user after this clause.
It's better to make checking and removing as one atomic operation

**Review by imay — APPROVED** [review]
LGTM

**Review by Astralidea — APPROVED** [review]
