### PR TITLE
[Enhancement] Use original expression as column name for MV

### LINKED ISSUE #18465: [materialized view]column display wrong when use expression
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE t1 (
    k1 date,
    k2 int
) ENGINE=OLAP
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1);

CREATE MATERIALIZED VIEW mv1 DISTRIBUTED BY HASH(k1) BUCKETS 10 AS SELECT k1,k2+1 FROM t1;

DESC mv1
````

### Expected behavior (Required)
```
+--------+--------+------+------+---------+-------+
| Field  | Type   | Null | Key  | Default | Extra |
+--------+--------+------+------+---------+-------+
| k1     | date   | YES  | true | NULL    |       |
| k2+1   | bigint | YES  | true | NULL    |       |
+--------+--------+------+------+---------+-------+
```
### Real behavior (Required)
```
+--------+--------+------+------+---------+-------+
| Field  | Type   | Null | Key  | Default | Extra |
+--------+--------+------+------+---------+-------+
| k1     | date   | YES  | true | NULL    |       |
| EXPR$0 | bigint | YES  | true | NULL    |       |
+--------+--------+------+------+---------+-------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`BRANCH-3.0-RELEASE-3d4e18a`

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18465

## Problem Summary(Required) ：

```sql
CREATE MATERIALIZED VIEW mv1 
DISTRIBUTED BY HASH(k1) 
BUCKETS 10 AS 
SELECT k1,k2+1 FROM t1;

DESC mv1
+--------+--------+------+------+---------+-------+
| Field  | Type   | Null | Key  | Default | Extra |
+--------+--------+------+------+---------+-------+
| k1     | date   | YES  | true | NULL    |       |
| k2+1   | bigint | YES  | true | NULL    |       |
+--------+--------+------+------+---------+-------+

```

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 1]
```diff
@@ -277,9 +276,8 @@ public Void visitCreateMaterializedViewStatement(CreateMaterializedViewStatement
 
         private void deriveSelectAlias(SelectList selectList, HashSet<String> aliases) {
             for (SelectListItem selectListItem : selectList.getItems()) {
-                if (!(selectListItem.getExpr() instanceof SlotRef)
-                        && selectListItem.getAlias() == null) {
-                    String alias = Util.deriveAliasFromOrdinal(aliases.size());
+                if (!(selectListItem.getExpr() instanceof SlotRef) && selectListItem.getAlias() == null) {
+                    String alias = selectListItem.getExpr().toSql();
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:280]: Really need to change this?

Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java]: removed. Use name from query relation

**Review by dirtysalt — APPROVED** [review]

**Review by Dshadowzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
