### PR TITLE
[BugFix] Fix the error config in start_be.sh

### LINKED ISSUE #9178: [Bug]When start be with JDK11, be would start fail.
### Steps to reproduce the behavior (Required)
When start be with JDK11, be would start fail.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9178

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: bin/start_be.sh [hunk 1]
```diff
@@ -91,11 +91,9 @@ export LD_LIBRARY_PATH=$STARROCKS_HOME/lib/hadoop/native:$LD_LIBRARY_PATH
 JAVA_VERSION=$(jdk_version)
 final_java_opt=$JAVA_OPTS
 if [[ "$JAVA_VERSION" -gt 8 ]]; then
-    if [ -z "$JAVA_OPTS_FOR_JDK_9" ]; then
-        echo "JAVA_OPTS_FOR_JDK_9 is not set in be.conf" >> $LOG_DIR/be.out
-        exit -1
+    if [ -n "$JAVA_OPTS_FOR_JDK_9_AND_LATER" ]; then
```
Comment (imay) [inline bin/start_be.sh:94]: there is no JAVA_OPTS_FOR_JDK_9_AND_LATER set

Comment (adzfolc) [reply bin/start_be.sh:94]: > 
`JAVA_OPTS_FOR_JDK_9_AND_LATER` is an optional config, it can be read and loaded as LIBHDFS_OPTS
