### PR TITLE
[BugFix] fix jni scanner field initialization and `do_close` method

### LINKED ISSUE #29499: [daily] cn crash
### Steps to reproduce the behavior (Required)
```
*** Aborted at 1692273119 (unix time) try "date -d @1692273119" if you are using GNU date ***
PC: @     0x7fd95fd570d5 jni_CallVoidMethodV
*** SIGSEGV (@0xffffffff00000036) received by PID 2716 (TID 0x7fd8c00f5700) from PID 54; stack trace: ***
    @          0x600ec02 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fd95ff8b235 os::Linux::chained_handler()
    @     0x7fd95ff90031 JVM_handle_linux_signal
    @     0x7fd95ff830c8 signalHandler()
    @     0x7fd95f43a630 (unknown)
    @     0x7fd95fd570d5 jni_CallVoidMethodV
    @          0x40c9b79 JNIEnv_::CallVoidMethod()
    @          0x52db608 starrocks::JniScanner::do_close()
    @          0x52e3248 starrocks::HdfsScanner::close()
    @          0x5252e58 _ZZN9starrocks10ObjectPool3addINS_10JniScannerEEEPT_S4_ENUlPvE_4_FUNES5_
    @          0x5254748 starrocks::connector::HiveDataSource::~HiveDataSource()
    @          0x293e48b starrocks::pipeline::ConnectorChunkSource::~ConnectorChunkSource()
    @          0x27eed0a std::_Sp_counted_base<>::_M_release()
    @          0x293a95b _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x2943121 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x4c279b2 starrocks::ThreadPool::dispatch_thread()
    @          0x4c224aa starrocks::Thread::supervise_thread()
    @     0x7fd95f432ea5 start_thread
    @     0x7fd95ea4db0d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-3.1-00dc135

### PR DESCRIPTION
**Pull request by dirtysalt**
Fixes #29499

This PR:
1. explicitly set critical fields to nullptr in jni_scanner
2. check if it fails to get jni method during initialization.
3. fix `do_close` method(check if jni_obj, jni_cls, jni_close if nullptr or not).

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

File: be/src/exec/jni_scanner.cpp [hunk 1]
```diff
@@ -58,30 +58,38 @@ Status JniScanner::do_open(RuntimeState* state) {
...
 void JniScanner::do_close(RuntimeState* runtime_state) noexcept {
-    if (_jni_scanner_obj == nullptr) return;
     JNIEnv* _jni_env = JVMFunctionHelper::getInstance().getEnv();
-    _jni_env->CallVoidMethod(_jni_scanner_obj, _jni_scanner_close);
-    _check_jni_exception(_jni_env, "Failed to close the off-heap table scanner.");
-    _jni_env->DeleteLocalRef(_jni_scanner_obj);
-    _jni_env->DeleteLocalRef(_jni_scanner_cls);
+    if (_jni_scanner_obj != nullptr) {
+        if (_jni_scanner_close != nullptr) {
+            _jni_env->CallVoidMethod(_jni_scanner_obj, _jni_scanner_close);
```
Comment (imay) [inline be/src/exec/jni_scanner.cpp:64]: Set close to nullptr?

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/exec/jni_scanner.cpp (hunk 1 above)
Comment (dirtysalt) [reply be/src/exec/jni_scanner.cpp:64]: well, No need to. 

set _jni_scanner_obj/_jni_scanner_cls to nullptr is also kind of unecessary either.

**Review by imay — APPROVED** [review]

**Comment by dirtysalt** [comment]
@mergify backport branch-3.1

**Comment by dirtysalt** [comment]
@mergify backport branch-3.0
