### PR TITLE
[BugFix] Fix in-subquery cast to outer join bug

### LINKED ISSUE #7039: sqlancer query result error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS w2;
CREATE DATABASE w2;
USE w2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NOT NULL ,c_0_1 DATETIME NOT NULL ,c_0_2 DOUBLE REPLACE_IF_NOT_NULL NULL ,c_0_3 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_4 BOOLEAN REPLACE NOT NULL ,c_0_5 TINYINT SUM NULL ,c_0_6 BOOLEAN REPLACE NULL ,c_0_7 HLL HLL_UNION NULL ,c_0_8 DECIMAL(33, 10)  REPLACE_IF_NOT_NULL NULL ) AGGREGATE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 162 day)) DISTRIBUTED BY HASH (c_0_1) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ) UNIQUE KEY (c_1_0) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 89 day)) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ('2010-01-15', '2010-01-19 08:00:14', 0.5452490003832424, percentile_hash('953528061'), false, 2, false, hll_hash(''), NULL), ('2010-01-14', '2010-01-06 08:00:14', NULL, percentile_hash('953528061'), false, NULL, true, hll_hash(''), 962684924858.9054697244);
INSERT INTO t1 VALUES ('2010-01-28 08:00:14'), ('2010-01-07 08:00:14');
INSERT INTO t0 VALUES ('2010-01-05', '2010-01-06 08:00:14', 0.5452490003832424, percentile_hash('-148935372'), false, 4, false, hll_hash('ZW'), 7936594214024.0982144119), ('2010-01-31', '2010-01-24 08:00:14', 0.9736537942295025, percentile_hash('-1818295837'), false, 7, true, hll_hash('yc'), 8737205530156.4444108050);
CREATE MATERIALIZED VIEW v0 AS SELECT t0_21.c_0_0, t0_21.c_0_1, t0_21.c_0_2, t0_21.c_0_4, t0_21.c_0_5, t0_21.c_0_8, MIN(t0_21.c_0_6)  FROM t0 AS t0_21 GROUP BY t0_21.c_0_0, t0_21.c_0_1, t0_21.c_0_2, t0_21.c_0_4, t0_21.c_0_5, t0_21.c_0_8 ORDER BY t0_21.c_0_0 ASC, t0_21.c_0_1 DESC, t0_21.c_0_2 DESC, t0_21.c_0_4 ASC, t0_21.c_0_5, t0_21.c_0_8 ASC;
CREATE MATERIALIZED VIEW v0 AS SELECT t1_24.c_1_0 FROM t1 AS t1_24;
INSERT INTO t1 VALUES ('2010-01-20 08:00:14');
INSERT INTO t1 VALUES ('2010-01-06 08:00:14');
INSERT INTO t1 VALUES ('2010-01-21 08:00:14'), (NULL);
INSERT INTO t1 VALUES ('2010-01-29 08:00:14');
INSERT INTO t1 VALUES ('2010-01-01 08:00:14');
INSERT INTO t0 VALUES ('2010-01-06', '2010-01-10 08:00:14', 0.5233367744533225, percentile_hash('378760856'), true, 7, true, hll_hash('PVf'), 7656679148717.1315397448), ('2010-01-02', '2010-01-27 08:00:14', 0.8625868723352262, percentile_hash('-318393413'), true, 5, false, hll_hash('1u09'), 2122324753894.8448254375);
INSERT INTO t0 VALUES ('2010-01-27', '2010-01-14 08:00:14', 0.9070376520096485, percentile_hash('953528061'), true, 2, false, hll_hash(''), 3635090075017.1891040765), ('2010-01-13', '2010-01-29 08:00:14', 0.38394557988890776, percentile_hash('-908702325'), false, 3, false, hll_hash('gUeqM'), 525965262182.3818213735), ('2010-01-15', '2010-01-07 08:00:14', -1.818295837E9, percentile_hash('-1643100528'), false, 0, true, hll_hash(''), 9944264635623.0568497890);
INSERT INTO t0 VALUES ('2009-12-31', '2010-01-09 08:00:14', 0.7379085190975122, percentile_hash('-1476014809'), false, 6, true, hll_hash('zA5SH304'), 2458448121423.2312894284);
INSERT INTO t0 VALUES ('2010-01-04', '2010-01-03 08:00:14', 0.4376425021860991, percentile_hash('-908702325'), true, NULL, true, hll_hash('nrcSjzO'), NULL), ('2010-01-24', '2010-01-24 08:00:14', 0.08446065655443558, percentile_hash('-1476014809'), false, 5, false, hll_hash('7C'), 3876630147997.1341395953), ('2010-01-30', '2010-01-18 08:00:14', 0.31080383378731524, percentile_hash('-944453900'), true, 0, true, hll_hash('oc'), 3045772033120.6417215440);
INSERT INTO t0 VALUES ('2010-01-29', '2010-01-31 08:00:14', 0.4376425021860991, percentile_hash('750807590'), false, 2, false, hll_hash('5QJHA'), 9644641160904.6833746687);
-- SELECT t0_27.c_0_0 FROM t0 AS t0_27, t1 AS t1_28;
-- cardinality: 78
-- SELECT t0_27.c_0_0 FROM t0 AS t0_27, t1 AS t1_28 WHERE (t0_27.c_0_2) IN ((SELECT t0_27.c_0_2 FROM t0 AS t0_27 WHERE (t1_28.c_1_0) IN ('1970-01-18 15:14:39') ) )  UNION ALL SELECT t0_27.c_0_0 FROM t0 AS t0_27, t1 AS t1_28 WHERE (NOT ((t0_27.c_0_2) IN ((SELECT t0_27.c_0_2 FROM t0 AS t0_27 WHERE (t1_28.c_1_0) IN ('1970-01-18 15:14:39') ) ) )) UNION ALL SELECT t0_27.c_0_0 FROM t0 AS t0_27, t1 AS t1_28 WHERE (((t0_27.c_0_2) IN ((SELECT t0_27.c_0_2 FROM t0 AS t0_27 WHERE (t1_28.c_1_0) IN ('1970-01-18 15:14:39') ) ) ) IS NULL);
-- cardinality: 84
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c728f6e |
+----------------------+
```

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7039 #7017

## Problem Summary(Required) ：

when left table column is null and result of subquery is empty, case when will hit null, not false

```
MySQL w2> select t0_27.c_0_2, ((t0_27.c_0_2) IN ((SELECT t0_27.c_0_2 FROM t0 AS t0_27 WHERE (t1_28.c_1_0) IN ('1970-01-18 15:14:39') ) ) ) from t0 AS t0_27, t1 AS t1_28;
+--------------------+-------------------------------------------------------------------------------------+
| c_0_2              | c_0_2 IN (((SELECT c_0_2 FROM t0 AS t0_27 WHERE c_1_0 IN ('1970-01-18 15:14:39')))) |
+--------------------+-------------------------------------------------------------------------------------+
| 0.9736537942295025 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| <null>             | <null>                                                                              |
| <null>             | <null>                                                                              |
| 0.9736537942295025 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
+--------------------+-------------------------------------------------------------------------------------+
8 rows in set
Time: 0.077s
```

should be 
```
MySQL w2> select t0_27.c_0_2, ((t0_27.c_0_2) IN ((SELECT t0_27.c_0_2 FROM t0 AS t0_27 WHERE (t1_28.c_1_0) IN ('1970-01-18 15:14:39') ) ) ) from t0 AS t0_27, t1 AS t1_28;
+--------------------+-------------------------------------------------------------------------------------+
| c_0_2              | c_0_2 IN (((SELECT c_0_2 FROM t0 AS t0_27 WHERE c_1_0 IN ('1970-01-18 15:14:39')))) |
+--------------------+-------------------------------------------------------------------------------------+
| 0.9736537942295025 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| <null>             | 0                                                                                   |
| <null>             | 0                                                                                   |
| 0.9736537942295025 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
| 0.5452490003832424 | 0                                                                                   |
+--------------------+-------------------------------------------------------------------------------------+
8 rows in set
Time: 0.077s

```

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java [hunk 1]
```diff
@@ -157,8 +157,8 @@ public CorrelationOuterJoinTransformer(OptExpression input, OptimizerContext con
          * after: with xx as (select t1.v2, t1.v3 from t1)
          *        select t0.v1,
          *             case
-         *                 // t1 empty table, if t1Rows is null, means the result of join correlation predicate must be false, will hit else
-         *                 when t1Rows = 0 then false
+         *                 // t1 empty table, if t1Rows is null, means the result of join correlation predicate must be false
+         *                 when t1Rows = 0 or t1Rows is null then false
          *                 when t0.v2 is null then null
          *                 when t1d.v2 is not null then true
          *                 when v2Nulls < t1Rows then null
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java:164]: v2Nulls -> v2NotNull

**Review by liuyehcf — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by kangkaisen** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|2|2|100.00%|
