### PR TITLE
[Bugfixi] not support create mv by mv #9543

### LINKED ISSUE #9543: [sync materialized view]create mv successed by mv
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1
(a BIGINT,
b BIGINT,
c BIGINT,
d BIGINT,
e BIGINT,
f BIGINT)
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM t1;

CREATE MATERIALIZED VIEW mv2
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM mv1;
```

### Expected behavior (Required)
`execute failed`
### Real behavior (Required)
`Query OK, 0 rows affected (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 12c19a2 |
+----------------------+

### PR DESCRIPTION
**Pull request by QingdongZeng3**
[Bugfix] not support create mv by mv #9543

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9543 

## Problem Summary(Required) ：

```
CREATE TABLE t1
(a BIGINT,
b BIGINT,
c BIGINT,
d BIGINT,
e BIGINT,
f BIGINT)
DUPLICATE KEY(a)
DISTRIBUTED BY HASH(a) BUCKETS 10
PROPERTIES ("replication_num" = "1");

CREATE MATERIALIZED VIEW mv1
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM t1;

CREATE MATERIALIZED VIEW mv2
DISTRIBUTED BY HASH(a) BUCKETS 10
REFRESH ASYNC
AS SELECT a, b, c
FROM mv1;
```

Result:
```
MySQL [n1]> CREATE MATERIALIZED VIEW mv2
    -> DISTRIBUTED BY HASH(a) BUCKETS 10
    -> REFRESH ASYNC
    -> AS SELECT a, b, c
    -> FROM mv1;
ERROR 1064 (HY000): Materialized view not supports base on Materialized view so far, but the type of table: mv1 is: MATERIALIZED_VIEW
```

image

### CODE REVIEW

**Comment by QingdongZeng3** [comment]
@Astralidea PTAL

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

**Review by Astralidea — DISMISSED** [review]

**Comment by QingdongZeng3** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 1]
```diff
@@ -115,6 +115,11 @@ public Void visitCreateMaterializedViewStatement(CreateMaterializedViewStatement
                             "Materialized view only supports olap table, but the type of table: " +
                                     table.getName() + " is: " + table.getType().name());
                 }
+                if (table instanceof MaterializedView) {
+                    throw new SemanticException(
+                            "Materialized view not supports base on Materialized view so far, but the type of table: " +
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:120]: creating a materialized view from materialized view is not supported now. The type of table: + table.getName is a materialized view.

**Review by ABingHuang — CHANGES_REQUESTED** [review]

**Comment by QingdongZeng3** [comment]
run starrocks_fe_unittest

**Comment by QingdongZeng3** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Comment by imay** [comment]
@QingdongZeng3 should merged into branch-2.4
@mergify cherry-pick branch-2.4

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|
