### PR TITLE
Fix explain verbose plan of HdfsNode

### LINKED ISSUE #167: [Bug] Explain verbose plan for hdfsnode has redundant information
mysql> explain verbose   select * from scan_test where col1 > 1 limit 10;
+----------------------------------------------------------------+
| Explain String                                                 |
+----------------------------------------------------------------+
| WORK ON CBO OPTIMIZER                                          |
| PLAN FRAGMENT 0(F01)                                           |
|   Output Exprs:1: col1 | 2: col2 | 3: col3 | 4: col4 | 5: pcol |
|   Input Partition: UNPARTITIONED                               |
|   RESULT SINK                                                  |
|                                                                |
|   1:EXCHANGE                                                   |
|      limit: 10                                                 |
|      cardinality: 10                                           |
|                                                                |
| PLAN FRAGMENT 1(F00)                                           |
|                                                                |
|   Input Partition: RANDOM                                      |
|   OutPut Partition: UNPARTITIONED                              |
|   OutPut Exchange Id: 01                                       |
|                                                                |
|   0:HdfsScanNode                                               |
|      TABLE: scan_test                                          |
|      NON-PARTITION PREDICATES: 1: col1 > 1                     |
|      partitions=4/4                                            |
|      cardinality=113                                           |
|      avgRowSize=48.0                                           |
|      numNodes=0                                                |
|      limit: 10                                                 |
|      cardinality: 113                                          |
+----------------------------------------------------------------+

cardinality is redundant

### PR DESCRIPTION
**Pull request by Youngwb**
Fix #167

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java [hunk 1]
```diff
@@ -375,7 +375,6 @@ public PlanFragment visitPhysicalHiveScan(OptExpression optExpression, ExecPlan
                 hdfsScanNode.setSelectedPartitionIds(node.getSelectedPartitionIds());
                 hdfsScanNode.setIdToPartitionKey(node.getIdToPartitionKey());
                 hdfsScanNode.getScanRangeLocations(context.getDescTbl());
-                hdfsScanNode.computeCardinality();
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:378]: this is no more need because we hvae `hdfsScanNode.computeStatistics` already

**Review by HangyuanLiu — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
