### PR TITLE
Fix default CURRENT_TIMESTAMP should not support change default value

### LINKED ISSUE #2831: no error when modify default timestamp
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                `k1`  date,
                `k2`  datetime default current_timestamp
            ) ENGINE=OLAP
            DUPLICATE KEY(`k1`)
            COMMENT "OLAP"
            DISTRIBUTED BY HASH(`k1`) BUCKETS 3
            PROPERTIES (
                "replication_num" = "1",
                "storage_format" = "v2"
            );
ALTER TABLE t1 MODIFY COLUMN k2 datetime;

```
### Expected behavior (Required)
`ERROR 1064 (HY000): Can not change default value`
### Real behavior (Required)
`Query OK, 0 rows affected (0.00 sec)`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_BRANCH e99bca0 |
+------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
Fix #2831

The previous design is that this column cannot be modified if there is a default value.
DEFAULT CURRENT_TIME should also be consistent; no exceptions should be made.

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/catalog/Column.java [hunk 1]
```diff
@@ -335,13 +333,29 @@ public void checkSchemaChangeAllowed(Column other) throws DdlException {
...
+        DefaultValueType thisDefaultValueType = this.getDefaultValueType();
+        DefaultValueType otherDefaultValueType = other.getDefaultValueType();
+        // Adding a default value to a column without a default value is not supported
+        if (thisDefaultValueType != otherDefaultValueType) {
+            throw new DdlException(CAN_NOT_CHANGE_DEFAULT_VALUE);
+        }
+
+        // default value should same
+        if (thisDefaultValueType == DefaultValueType.VARY) {
+            if (!this.getDefaultExpr().getExpr().equals(other.getDefaultExpr().getExpr())) {
```
[the remark this answers is not in the document]
Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Column.java:345]: in 339 line thisDefaultValueType != otherDefaultValueType will true then throw CAN_NOT_CHANGE_DEFAULT_VALUE

[the remark this answers is not in the document]
Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Column.java:345]: the code above thisDefaultValueType != otherDefaultValueType make this situation does not occur here, an DdlException will be throw

File: fe/fe-core/src/main/java/com/starrocks/catalog/Column.java [hunk 2]
```diff
@@ -335,13 +333,29 @@ public void checkSchemaChangeAllowed(Column other) throws DdlException {
...
             }
-        } else {
-            if (!this.getDefaultValue().equals(other.getDefaultValue())) {
-                throw new DdlException("Can not change default value");
+        } else if (this.getDefaultValueType() == DefaultValueType.CONST) {
+            if (this.getDefaultValue() != null && other.getDefaultValue() != null) {
+                if (!this.getDefaultValue().equals(other.getDefaultValue())) {
+                    throw new DdlException(CAN_NOT_CHANGE_DEFAULT_VALUE);
+                }
+            } else if (this.getDefaultExpr() != null && other.getDefaultExpr() != null) {
```
[the remark this answers is not in the document]
Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Column.java:353]: This is because CONST has 2 cases, one is DEFAULT "1" , this will make this.getDefaultExpr == null
and the other is DEFAULT CURRENT_TIMESTAMP, this will make this.getDefaultExpr != null

File: fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java [hunk 3]
```diff
@@ -111,8 +116,104 @@ public void testSerialization() throws Exception {
...
+                    new ColumnDef.DefaultValueDef(true, new StringLiteral("0")), "");
+            Column newColumn = new Column("user", ScalarType.createType(PrimitiveType.INT), true, null, false,
+                    NOT_SET, "");
+            oldColumn.checkSchemaChangeAllowed(newColumn);
+            Assert.fail("No exception throws.");
+        } catch (DdlException ex) {
+        }
+
+        try {
+            Column oldColumn = new Column("user", ScalarType.createType(PrimitiveType.INT), true, null, false,
```
Comment (wyb) [inline fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java:153]: PrimitiveType.DATETIME

File: fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java [hunk 4]
```diff
@@ -111,8 +116,104 @@ public void testSerialization() throws Exception {
...
+    public void testSchemaChangeAllowNormal() throws DdlException {
+        Column oldColumn = new Column("user", ScalarType.createType(PrimitiveType.INT), true, null, false,
+                NULL_DEFAULT_VALUE, "");
+        Column newColumn = new Column("user", ScalarType.createType(PrimitiveType.VARCHAR), true, null, false,
+                NULL_DEFAULT_VALUE, "");
+        oldColumn.checkSchemaChangeAllowed(newColumn);
+
+        oldColumn = new Column("user", ScalarType.createType(PrimitiveType.VARCHAR), true, null, false,
+                new ColumnDef.DefaultValueDef(true, new StringLiteral("0")), "");
+        newColumn = new Column("user1", ScalarType.createType(PrimitiveType.VARCHAR), true, null, false,
```
Comment (wyb) [inline fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java:129]: Column name is different.

File: fe/fe-core/src/main/java/com/starrocks/catalog/Column.java [hunk 5]
```diff
@@ -335,13 +333,29 @@ public void checkSchemaChangeAllowed(Column other) throws DdlException {
...
+                if (!this.getDefaultExpr().getExpr().equals(other.getDefaultExpr().getExpr())) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Column.java:354]: Better to use `equalsIgnoreCase`.

File: fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java (hunk 4 above)
Comment (Astralidea) [reply fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java:129]: this case is test for change column name.

Comment (wyb) [reply fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java:129]: Change column name is not supported currently.

File: fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java [hunk 6]
```diff
@@ -111,8 +116,104 @@ public void testSerialization() throws Exception {
...
+                    new ColumnDef.DefaultValueDef(true, new StringLiteral("0")), "");
+            oldColumn.checkSchemaChangeAllowed(newColumn);
+            Assert.fail("No exception throws.");
+        } catch (DdlException ex) {
+        }
+
+        try {
+            Column oldColumn = new Column("user", ScalarType.createType(PrimitiveType.INT), true, null, false,
+                    NOT_SET, "");
+            Column newColumn = new Column("user", ScalarType.createType(PrimitiveType.INT), true, null, false,
```
Comment (wyb) [inline fe/fe-core/src/test/java/com/starrocks/catalog/ColumnTest.java:175]: There are still a lot of wrong `DATETIME` type cases.

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
