### PR TITLE
[BugFix] fix segment mem_usage race condition

### LINKED ISSUE #34273: [BE] Crash at starrocks::ColumnReader::mem_usage()
### Steps to reproduce the behavior (Required)

```
branch-3.1 RELEASE (build de6c740)
query_id:00d5e8a2-794f-11ee-8f84-00163e3819f5, fragment_instance:00d5e8a2-794f-11ee-8f84-00163e3819fe
tracker:process consumption: 66891166480
tracker:query_pool consumption: 763808
tracker:load consumption: 5341664
tracker:metadata consumption: 1379690845
tracker:tablet_metadata consumption: 758381
tracker:rowset_metadata consumption: 0
tracker:segment_metadata consumption: 196072959
tracker:column_metadata consumption: 1182859505
tracker:tablet_schema consumption: 758381
tracker:segment_zonemap consumption: 146622160
tracker:short_key_index consumption: 10485312
tracker:column_zonemap_index consumption: 308973537
tracker:ordinal_index consumption: 459981304
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 54192288144
tracker:update consumption: 1230134890
tracker:chunk_allocator consumption: 2147931456
tracker:clone consumption: 0
tracker:consistency consumption: 0
*** Aborted at 1698909072 (unix time) try "date -d @1698909072" if you are using GNU date ***
PC: @          0x4aa9a14 starrocks::ColumnReader::mem_usage()
*** SIGSEGV (@0x0) received by PID 164223 (TID 0x7f3db3610700) from PID 0; stack trace: ***
    @          0x6386f02 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f3ede847095 os::Linux::chained_handler()
    @     0x7f3ede84c091 JVM_handle_linux_signal
    @     0x7f3ede83ee48 signalHandler()
    @     0x7f3eddcf2630 (unknown)
    @          0x4aa9a14 starrocks::ColumnReader::mem_usage()
    @          0x463cafd starrocks::Segment::_column_index_mem_usage()
    @          0x47db47f starrocks::lake::Metacache::cache_segment()
    @          0x47a2fe9 starrocks::lake::TabletManager::update_segment_cache_size()
    @          0x4641091 starrocks::Segment::open()
    @          0x47a0aec starrocks::lake::Tablet::load_segment()
    @          0x4792a16 starrocks::lake::Rowset::load_segments()
    @          0x4794a8e starrocks::lake::Rowset::read()
    @          0x47af895 starrocks::lake::TabletReader::get_segment_iterators()
    @          0x47b0921 starrocks::lake::TabletReader::init_collector()
    @          0x47b20eb starrocks::lake::TabletReader::open()
    @          0x55c5ce4 starrocks::connector::LakeDataSource::init_tablet_reader()
    @          0x55c66a4 starrocks::connector::LakeDataSource::open()
    @          0x2afab01 starrocks::pipeline::ConnectorChunkSource::_open_data_source()
    @          0x2afbbe1 starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0x2daff67 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2af840b _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0x2b00eb1 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x4f76e32 starrocks::ThreadPool::dispatch_thread()
    @          0x4f718ca starrocks::Thread::supervise_thread()
    @     0x7f3eddceaea5 start_thread
    @     0x7f3edd0ebb0d __clone
    @                0x0 (unknown)
```

### Expected behavior (Required)

No crash

### Real behavior (Required)

BE Core

code base: https://github.com/StarRocks/starrocks/pull/33810

### StarRocks version (Required)

`branch-3.1 RELEASE (build de6c740)`

attachment is the full threads back trace.

[bt-34273.txt](https://github.com/StarRocks/starrocks/files/13246993/bt-34273.txt)

Should be a regression introduced in combination of #32996 and #31978

### PR DESCRIPTION
**Pull request by kevincai**
* protect the Segment::mem_usage() with open_once flag
* TabletManager is able to skip the cache size update if the segment in the cache is not the same as expected one.
* MetaCache support `cache_segment_if_absent` interface.

Fixes #34273

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.2
  - [X] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/storage/lake/tablet_manager.h [hunk 1]
```diff
@@ -141,7 +141,7 @@ class TabletManager {
     // only for TEST purpose
     void TEST_set_global_schema_cache(int64_t index_id, TabletSchemaPtr schema);
 
-    void update_segment_cache_size(std::string_view key);
+    void update_segment_cache_size(std::string_view key, const void* segment_hint = nullptr);
```
Comment (wyb) [inline be/src/storage/lake/tablet_manager.h:144]: why not use `const Segment* segment_hint = nullptr`

Comment (kevincai) [reply be/src/storage/lake/tablet_manager.h:144]: I am thinking of change it to `intptr_t`, because here we don't want to do any member accessing to the type, just an memory address or the object address that matters. typeinfo can be erased as much as possible.

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by kevincai** [comment]
manual backport to branch-3.1 at https://github.com/StarRocks/starrocks/pull/34446
