### PR TITLE
[pipeline] fix exit logic of exchange and result sink when the query is canceled

### LINKED ISSUE #1534: [pipeline] Should return error when AssertNum is unsatisfied
### Steps to reproduce the behavior (Required)
```sql
create database assert_test_1637648317796;
use assert_test_1637648317796;

CREATE TABLE `t2` ( `c1` int(11) NOT NULL COMMENT "", `c2` int(11) NOT NULL COMMENT "" ) ENGINE=OLAP DUPLICATE KEY(`c1`) COMMENT "OLAP" DISTRIBUTED BY HASH(`c1`) BUCKETS 10 PROPERTIES ( "replication_num" = "1", "in_memory" = "false", "storage_format" = "DEFAULT" );

insert into assert_test_1637648317796.t2 values (1, 3), (2, 9), (0, 134);

select * from t2 where c1 = (select c1 from t2 limit 2);
```

### Expected behavior (Required)
```
ERROR 1064 (HY000): Expected LE 1 to be returned by expression
```

### Real behavior (Required)
```
Empty set (0.74 sec)
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
### Introduction
When the query is cancelled, exchange sink and result shouldn't send EOS. Otherwise, EOS from result sink may arrived at  FE earlier than cancel report, which causes FE returns success empty result to MySQL client instead of error result.

What's more, destructor of SinkBuffer shouldn't block and wait RPC to response, because SinkBuffer is destructed in the PipelineDispatcher thread, and ExchangeSource responses to SinkBuffer also in  the PipelineDispatcher thread, which causes dead lock.

Fix #1534 .

### Changes
- `ExchangeSinkOperator::close()` and `ResultSinkOperator::close()` don't send EOS when query is cancelled.
- In `DataStreamRecvr::SenderQueue::_add_chunks_internal()`, check `_is_cancelled` again before adding `closures` into `_pending_closures` , because the lock is released between checking `_is_cancelled` and adding `closures` into `_pending_closures`, where `_is_cancelled` may be changed by `PInternalServiceImpl::cancel_plan_fragment()`. The code is as follows.
- Add `pending_finish()` to base class `Operator`, and add override implementation to `ExchangeSinkOperator`. Don't wait RPC to response in `~SinkBuffer()`.
```C++
Status DataStreamRecvr::SenderQueue::_add_chunks_internal(const PTransmitChunkParams& request,
                                                          ::google::protobuf::Closure** done,
                                                          const std::function<void()>& cb) {
{
    std::unique_lock<std::mutex> l(_lock);
    if (_is_cancelled) {
        return Status::OK();
    }

    // Check RPC sequence, and deserialize _chunk_meta.
    // ....
}

/// `_is_cancelled` may be changed by `PInternalServiceImpl::cancel_plan_fragment()` here.
// Deserialize chunk from request.
// ...

{
    std::unique_lock<std::mutex> l(_lock);
    for (auto& pair : chunks) {
        _chunk_queue.emplace_back(std::move(pair));
    }
    // if done is nullptr, this function can't delay this response
    if (done != nullptr && _recvr->exceeds_limit(total_chunk_bytes)) {
        MonotonicStopWatch monotonicStopWatch;
        DCHECK(*done != nullptr);
        _pending_closures.emplace_back(*done, monotonicStopWatch);
        *done = nullptr;
    }
    _recvr->_num_buffered_bytes += total_chunk_bytes;
}

```

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run starrocks_clang-format

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

File: be/src/exec/pipeline/exchange/exchange_sink_operator.cpp [hunk 1]
```diff
@@ -195,31 +195,37 @@ Status ExchangeSinkOperator::Channel::send_chunk_request(PTransmitChunkParamsPtr
     return Status::OK();
 }
 
-Status ExchangeSinkOperator::Channel::_close_internal() {
+Status ExchangeSinkOperator::Channel::_close_internal(RuntimeState* state, FragmentContext* fragment_ctx) {
```
Comment (kangkaisen) [inline be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:198]: Needn't pass FragmentContext here. we could check `is_canceled ` from RuntimeState.

```
    bool is_cancelled() const { return _is_cancelled; }
    void set_is_cancelled(bool v) { _is_cancelled = v; }
```

Comment (ZiheLiu) [reply be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:198]: `set_is_cancelled()` is only called in the calling sequence: `PInternalServiceImpl::cancel_plan_fragment -> FragmentMgr::cancel ->  FragmentExecState::cancel -> PlanFragmentExecutor::cancel -> RuntimeState::set_is_cancelled`, but `FragmentMgr::cancel` is only called by `PInternalServiceImpl::cancel_plan_fragment` when it is not pipeline.

```C++
template <typename T>
void PInternalServiceImpl<T>::cancel_plan_fragment(google::protobuf::RpcController* cntl_base,
                                                   const PCancelPlanFragmentRequest* request,
                                                   PCancelPlanFragmentResult* result, google::protobuf::Closure* done) {
    if (request->has_is_pipeline() && request->is_pipeline()) {
        // ...
    } else {
        if (request->has_cancel_reason()) {
            st = _exec_env->fragment_mgr()->cancel(tid, request->cancel_reason());
        } else {
            LOG(INFO) << "cancel framgent, fragment_instance_id=" << print_id(tid);
            st = _exec_env->fragment_mgr()->cancel(tid);
        }
        if (!st.ok()) {
            LOG(WARNING) << "cancel plan fragment failed, errmsg=" << st.get_error_msg();
        }
    }
```

Comment (ZiheLiu) [reply be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:198]: In the internal of pipeline, `FragmentContext::_cancel_flag` is used as the cancel flag of a fragment. 
Except FE calling RPC `PInternalServiceImpl::cancel_plan_fragment`, the fragment may be cancelled by itself in `GlobalDriverDispatcher`, when `push_chunk()` and `pull_chunk()` return error.

**Review by kangkaisen — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by satanson — APPROVED** [review]
