### PR TITLE
[BugFix] fix #6782: make hdfs scan use individual WorkgroupOwner

### LINKED ISSUE #6782: BE crash when enable_resource_group = true
### Steps to reproduce the behavior (Required)
be.out:
```
*** Aborted at 1654003116 (unix time) try "date -d @1654003116" if you are using GNU date ***
PC: @          0x28cda28 starrocks::workgroup::WorkGroupManager::get_owners_of_scan_worker()
*** SIGSEGV (@0x0) received by PID 4701 (TID 0x7f0a5eb62700) from PID 0; stack trace: ***
    @          0x3f71ad2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f0aaff7c765 os::Linux::chained_handler()
    @     0x7f0aaff81561 JVM_handle_linux_signal
    @     0x7f0aaff745f8 signalHandler()
    @     0x7f0aaf42f630 (unknown)
    @          0x28cda28 starrocks::workgroup::WorkGroupManager::get_owners_of_scan_worker()
    @          0x28d554b starrocks::workgroup::ScanTaskQueueWithWorkGroup::_select_next_wg()
    @          0x28d5e8b starrocks::workgroup::ScanTaskQueueWithWorkGroup::take()
    @          0x28d4e81 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x210e2a9 starrocks::ThreadPool::dispatch_thread()
    @          0x2109e5a starrocks::Thread::supervise_thread()
    @     0x7f0aaf427ea5 start_thread
    @     0x7f0aaea428dd __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE e19accd |
+----------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6782

## Problem Summary(Required) ：

HdfsScanExecutor would use different number of thread with OlapScan, so it should use a individual WorkgroupOwner to calculate the workgroup of thread worker.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

File: be/src/exec/workgroup/work_group_fwd.h [hunk 1]
```diff
@@ -12,4 +12,10 @@ class ScanExecutor;
 
 using WorkGroupPtr = std::shared_ptr<WorkGroup>;
 
+// Two types of scan executor: OlapScan and HdfsScan
+enum ScanExecutorType {
+    TypeOlapScanExecutor,
+    TypeHdfsScanExecutor,
```
Comment (kangkaisen) [inline be/src/exec/workgroup/work_group_fwd.h:18]: What about other scan executor?

**Review by ZiheLiu — APPROVED** [review]

File: be/src/exec/workgroup/work_group_fwd.h (hunk 1 above)
Comment (mofeiatwork) [reply be/src/exec/workgroup/work_group_fwd.h:18]: Current there're only two kinds of ScanExecutor.

**Review by kangkaisen — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3
