### PR TITLE
[BugFix] fix cpu cores updating

### LINKED ISSUE #12188: Cpu cores could not be updated when updating BE cpu
### Steps to reproduce the behavior (Required)
1. Update cpu cores of BE 
2. The cpu cores cached in FE should be updated, but it's not.

### StarRocks version (Required)
- 2.2, 2.3, 2.4

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12188

## Problem Summary(Required) ：

cpu cores cached in FE should be updated when BE upgrading.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2 branch-2.3 branch-2.4

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/system/BackendCoreStat.java [hunk 1]
```diff
@@ -14,7 +14,8 @@ public class BackendCoreStat {
     private static AtomicInteger cachedAvgNumOfHardwareCores = new AtomicInteger(-1);
 
     public static void setNumOfHardwareCoresOfBe(long be, int numOfCores) {
-        if (numOfHardwareCoresPerBe.putIfAbsent(be, numOfCores) == null) {
+        Integer previous = numOfHardwareCoresPerBe.put(be, numOfCores);
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/system/BackendCoreStat.java:17]: previous == null || previous != numOfCores can merged into one stmt
modify it to if (numOfHardwareCoresPerBe.putIfAbsent(be, numOfCores)!=numOfCores)

**Review by trueeyu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
