### PR TITLE
[BugFix] fix query_excluding_mv_names and query_including_mv_names bugs

### LINKED ISSUE #34867: when query_excluding_mv_names is set without setting query_including_mv_names, mv rewrite will fail
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
create two same mv
CREATE MATERIALIZED VIEW mv_agg_1 " +
                " distributed by hash(empid) " +
                "AS " +
                "SELECT empid, sum(salary) as total " +
                "FROM emps " +
                "GROUP BY empid"

CREATE MATERIALIZED VIEW mv_agg_2 " +
                " distributed by hash(empid) " +
                "AS " +
                "SELECT empid, sum(salary) as total " +
                "FROM emps " +
                "GROUP BY empid"

3. set query_excluding_mv_names to 'mv_agg_1'
4. then query 
SELECT empid, sum(salary) as total 
FROM emps
GROUP BY empid

### Expected behavior (Required)
the query can be rewritten by mv_agg_2
### Real behavior (Required)
the query can not be rewritten by any mv
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Fix #34867 
Why I'm doing:
1. when query_excluding_mv_names is set and query_including_mv_names is not set, no related mv is considered for rewrite
2. mv names with pre or post space is not applicable.

What I'm doing:
1. when query_including_mv_names is not set, should consider all related mvs
3. add trim for mv names for better usability

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvPlanContextBuilder.java [hunk 1]
```diff
@@ -17,24 +17,11 @@
...
-        optimizerConfig.disableRuleSet(RuleSetType.PARTITION_PRUNE);
-        optimizerConfig.disableRuleSet(RuleSetType.SINGLE_TABLE_MV_REWRITE);
-        optimizerConfig.disableRule(RuleType.TF_REWRITE_GROUP_BY_COUNT_DISTINCT);
-        optimizerConfig.disableRule(RuleType.TF_PRUNE_EMPTY_SCAN);
-        // For sync mv, no rewrite query by original sync mv rule to avoid useless rewrite.
-        if (mv.getRefreshScheme().isSync()) {
-            optimizerConfig.disableRule(RuleType.TF_MATERIALIZED_VIEW);
-        }
-        optimizerConfig.setMVRewritePlan(true);
-        return mvOptimizer.optimize(mv, new ConnectContext(), optimizerConfig);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvPlanContextBuilder.java:38]: Why remove this?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 2]
```diff
@@ -183,11 +184,14 @@ public void prepareRelatedMVs(Set<Table> queryTables, Set<MaterializedView> rela
             logMVPrepare(connectContext, "queryExcludingMVNames:{}, queryIncludingMVNames:{}",
                     Strings.nullToEmpty(queryExcludingMVNames), Strings.nullToEmpty(queryIncludingMVNames));
 
-            Set<String> queryExcludingMVNamesSet = Sets.newHashSet(queryExcludingMVNames.split(","));
-            Set<String> queryIncludingMVNamesSet = Sets.newHashSet(queryIncludingMVNames.split(","));
+            final Set<String> queryExcludingMVNamesSet = Strings.isNullOrEmpty(queryExcludingMVNames) ? Sets.newHashSet()
+                    : Arrays.stream(queryExcludingMVNames.split(",")).map(String::trim).collect(Collectors.toSet());
+
+            final Set<String> queryIncludingMVNamesSet = Strings.isNullOrEmpty(queryIncludingMVNames) ? Sets.newHashSet()
+                    : Arrays.stream(queryIncludingMVNames.split(",")).map(String::trim).collect(Collectors.toSet());
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:191]: My question is how the spaces are introduced.

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:191]: This is a session variable, it is configured by user, maybe like this
set query_excluding_mv_names = "mv1 , mv2, mv3";
so add trim here to process more cases.

**Review by kangkaisen — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]
