### PR TITLE
[BugFix] Fix disk metrics bug when partition name does not end with number.

### LINKED ISSUE #29093: [Bug] values of disk device metrics is always zero when device name ends with number
### Steps to reproduce the behavior (Required)
1. Using disk device which name ends with number, like
nvme0n1p1
2. Get be metrics from be:8040/metrics, we can find
- value of disk device metrics is always 0
- device name, which is deleted the rightest number from origin name
starrocks_be_disk_io_time_ms{device="nvme0n1p"}

### Expected behavior (Required)
 value of disk device metrics is real value

### Real behavior (Required)
value of disk device metrics is always 0

### StarRocks version (Required)
2.3.11
2.5.4
2.5.8

### PR DESCRIPTION
**Pull request by gengjun-git**
## Why I'm doing:
When the partition name does not end with a number, it is incorrect to trim the suffix number to get the device name. For example, the device name is `nvme0n1` and the partition name is `nvme0n1p1`, in this case the device name generated from the partition is `nvme0n1p` and using this name to find statistics from `/proc/diskstats` will fail.

## What I'm doing:
Do not trim the partition name, and show the device partition statistic.

Fixes #29093

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Comment by gengjun-git** [comment]
@kevincai @dirtysalt PTAL

File: be/src/util/disk_info.cpp [hunk 1]
```diff
@@ -64,9 +62,6 @@ void DiskInfo::get_device_names() {
             continue;
         }
 
-        // Remove the partition# from the name.  e.g. sda2 --> sda
```
Comment (kevincai) [inline be/src/util/disk_info.cpp:67]: will it cause problem if is a hdd driver named as `sdxx##` or virtual disk like `vd[abc][0-9]`?

**Review by kevincai — COMMENTED** [review]
not quite sure what's the expected behavior here w.r.t. the device name.

File: be/src/util/disk_info.cpp (hunk 1 above)
Comment (gengjun-git) [reply be/src/util/disk_info.cpp:67]: Yes, I have add some details in the PR.

**Review by kevincai — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
