### PR TITLE
[BugFix] support negative value in skew hint

### LINKED ISSUE #66917: Negative value in skew hint cause syntax error
### Steps to reproduce the behavior (Required)

Using positive value in skew hint works, but negative value not.

```
CREATE TABLE `ta` (
  `c1` largeint(40) NULL COMMENT "",
  `c2` varchar(65533) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c1`, `c2`);
CREATE TABLE `tb` (
  `c1` largeint(40) NULL COMMENT "",
  `c2` varchar(65533) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c1`, `c2`);

MySQL root@127.1:ssb> select * from ta left join [skew|ta.c1(-100)] tb using(c1);
(1064, "Getting syntax error at line 1, column 44. Detail message: Unexpected input ']', the most similar input is {'('}.")

MySQL root@127.1:ssb> select * from ta left join [skew|ta.c1(100)] tb using(c1);
+----+----+----+
| c1 | c2 | c2 |
+----+----+----+
+----+----+----+
```

### StarRocks version (Required)
- main 20251218

### PR DESCRIPTION
**Pull request by murphyatwork**
## What I'm doing:

`literalExpression` cannot represent a negative value, while it is used in `bracketHint` syntax.

Fixes #66917

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> Enables negative numeric values in `bracketHint` skew syntax by extending grammar and parser handling.
> 
> - Update grammar: add `generalLiteralExpression` and `generalLiteralExpressionList` (supports `- number`) and use them in `bracketHint`
> - Parser: `AstBuilder` now visits `generalLiteralExpression` and builds negated `IntLiteral`/`LargeIntLiteral`/`DecimalLiteral`/`FloatLiteral`; `bracketHint` now consumes `generalLiteralExpressionList`
> - Add `FloatLiteral(Double, NodePosition)` constructor to preserve source positions when creating negated floats
> - Tests: add `ParserTest.testSkewHintWithNegativeValues`
> - Benchmark: add `InPredicateParserBench` for large `IN` predicate parsing
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 979d1837bc9d28123905860f47e389cfbc850f47. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java [hunk 1]
```diff
@@ -8032,7 +8032,27 @@ public ParseNode visitBooleanLiteral(com.starrocks.sql.parser.StarRocksParser.Bo
...
+                return new LargeIntLiteral(val.toString(), node.getPos());
+            } else if (node instanceof DecimalLiteral) {
+                BigDecimal val = ((DecimalLiteral) node).getValue();
+                return new DecimalLiteral(val.negate(), node.getPos());
+            } else if (node instanceof FloatLiteral) {
+                double val = ((FloatLiteral) node).getDoubleValue();
+                return new FloatLiteral(-val);
+            }
+        }
+        return node;
```
[the remark this answers is not in the document]
Comment (murphyatwork) [reply fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java]: fixed

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-grammar/src/main/antlr/com/starrocks/grammar/StarRocks.g4 [hunk 2]
```diff
@@ -2678,7 +2678,7 @@ primaryExpression
     ;
 
 literalExpression
-    : number                                                                              #numericLiteral
+    : MINUS_SYMBOL? number                                                                #numericLiteral
```
Comment (stephen-shelby) [inline fe/fe-grammar/src/main/antlr/com/starrocks/grammar/StarRocks.g4]: If the SQL contains a large number of literals, such as in IN predicates, the parser performance will severely degrade.

Comment (murphyatwork) [reply fe/fe-grammar/src/main/antlr/com/starrocks/grammar/StarRocks.g4]: fixed. keep `literalExpression`, introduce another `generateLiteralExpression` to represent negative values

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by Youngwb — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]
