### PR TITLE
[BugFix] Support transferring json using HTTP chunk

### LINKED ISSUE #5515: chunked json payload parsing failed
### Steps to reproduce the behavior (Required)
1. do stream load with json file of size 100MB

### Expected behavior (Required)
stream load success.
### Real behavior (Required)
stream load failed silently.
```
W0425 16:49:26.979848 1331570 json_scanner.cpp:726] illegal json started with [n]
```
### StarRocks version (Required)
main, branch-2.2

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #5515

## Problem Summary(Required) ：

This PR is the last part of the fix of #5515, including the following modifications:
1. building json buffer in handler of stream load to support chunked json http body
2. removing `Status MessageBodySink::append(const ByteBufferPtr& buf)` to reduce memory copy

### CODE REVIEW

**Comment by rickif** [comment]
# Attachment
## Table Schema
```
CREATE TABLE tbl_chunked_json (
  key0 varchar(1) NULL COMMENT '',
  key1 varchar(1) NULL COMMENT '',
  key2 varchar(1) NULL COMMENT '',
  key3 varchar(1) NULL COMMENT '',
  key4 varchar(1) NULL COMMENT '',
  key5 varchar(1) NULL COMMENT '',
  key6 varchar(1) NULL COMMENT '',
  key7 varchar(1) NULL COMMENT '',
  key8 varchar(1) NULL COMMENT '',
  key9 varchar(1) NULL COMMENT ''
) ENGINE=OLAP
DUPLICATE KEY(key0)
COMMENT 'OLAP'
DISTRIBUTED BY HASH(key0) BUCKETS 10
PROPERTIES (
'replication_num' = '1',
'in_memory' = 'false',
'storage_format' = 'DEFAULT'
);
```
## Sample Data
```
#!/usr/bin/env python3
import json

if __name__ == "__main__":

    data = {"key0": "0", "key1": "1", "key2": "2", "key3": "3", "key4": "4",
            "key5": "5", "key6": "6", "key7": "7", "key8": "8", "key9": "9"}

    f = open('a.json', 'w')

    for i in range(0, 15000000):
        json.dump(data, f)

    f.close()
```
## Stream Load
```
#!/usr/bin/env python3
import threading
import command
import os


def do_stream_load(url, filename):
    os.system(
        f"curl --location-trusted -u root: -H 'ignore_json_size: true' -H 'strip_outer_array: false' -H 'format:json' -T {filename} {url}")


def do_n_stream_load(url, filename,  task_num):
    for i in range(0, task_num):
        do_stream_load(url, filename)


if __name__ == "__main__":

    url = "http://127.0.0.1:8072/api/db0/tbl_chunked_json/_stream_load"
    filename = "ndjson.json"
    parallel = 32

    ts = []
    for i in range(0, parallel):
        t = threading.Thread(target=do_n_stream_load,
                             args=(url, filename, 100))
        ts.append(t)

    for t in ts:
        t.start()

    for t in ts:
        t.join()

    # both threads completely executed
    print("Done!")
```

File: be/src/http/action/stream_load.cpp [hunk 1]
```diff
@@ -237,6 +242,9 @@ Status StreamLoadAction::_on_header(HttpRequest* http_req, StreamLoadContext* ct
             ss << "body exceed max size: " << max_body_bytes << ", limit: " << max_body_bytes;
             return Status::InternalError(ss.str());
         }
+
+        // allocate buffer in advance.
+        ctx->buf = ByteBuffer::allocate(ctx->body_bytes);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:247]: If this is not a json file, there is no need to allocate a buffer of size `body_bytes`, it would be a waste of memory.

File: be/src/http/action/stream_load.cpp [hunk 2]
```diff
@@ -168,6 +168,11 @@ Status StreamLoadAction::_handle(StreamLoadContext* ctx) {
         ctx->body_sink.reset();
         RETURN_IF_ERROR(_exec_env->stream_load_executor()->execute_plan_fragment(ctx));
     } else {
+        if (ctx->buf->pos > 0) {
+            ctx->buf->flip();
+            ctx->body_sink->append(std::move(ctx->buf));
+            ctx->buf = ByteBuffer::allocate(ctx->buf_default_sz);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:174]: Q: When will the function `StreamLoadAction::_handle` be called? Is it still necessary to allocate a new buffer?

File: be/src/http/action/stream_load.cpp [hunk 3]
```diff
@@ -299,23 +307,40 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
+                buf->put_bytes(ctx->buf->ptr, ctx->buf->pos);
+                std::swap(buf, ctx->buf);
+
+            } else {
+                // For non-json format, we could push buffer to the body_sink in streaming mode.
+                // buffer capacity is not enough, so we push the buffer to the pipe and allocate new one.
+                ctx->buf->flip();
+                auto st = ctx->body_sink->append(std::move(ctx->buf));
+                if (!st.ok()) {
+                    LOG(WARNING) << "append body content failed. errmsg=" << st.get_error_msg() << ctx->brief();
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:327]:
```suggestion
                    LOG(WARNING) << "append body content failed. errmsg=" << st << " context=" << ctx->brief();
```

File: be/src/http/action/stream_load.cpp [hunk 4]
```diff
@@ -299,23 +307,40 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
+                    ctx->status = st;
+                    return;
+                }
+
+                ctx->buf = ByteBuffer::allocate(ctx->buf_default_sz);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:332]:
```suggestion
                ctx->buf = ByteBuffer::allocate(std::max(len, ctx->buf_default_sz));
```

File: be/src/runtime/stream_load/stream_load_context.h [hunk 5]
```diff
@@ -197,6 +197,10 @@ class StreamLoadContext {
 
     int32_t idle_timeout_sec = -1;
 
+    // buf for reading data from ev_buffer
+    static const size_t buf_default_sz = 64 * 1024;
+    ByteBufferPtr buf = ByteBuffer::allocate(buf_default_sz);
```
Comment (sduzh) [inline be/src/runtime/stream_load/stream_load_context.h:202]: This allocation is useless since a new buffer will be allocated in `_on_header`, am I right?

Comment (rickif) [reply be/src/runtime/stream_load/stream_load_context.h:202]: Only `CONTENT_LENGTH` is specified the buffer would be re-allocated. Maybe a better solution is to allocate memory when it is needed.

File: be/src/http/action/stream_load.cpp (hunk 4 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp:332]: `len` denotes the length of current returned data, but the `ctx->buf` is prepared for next read. What's your consideration here?

File: be/src/http/action/stream_load.cpp [hunk 6]
```diff
@@ -299,23 +307,40 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
-    while (evbuffer_get_length(evbuf) > 0) {
-        ByteBufferPtr bb = ByteBuffer::allocate(4096);
+
+    size_t len = 0;
+    while ((len = evbuffer_get_length(evbuf)) > 0) {
+        if (ctx->buf->remaining() < len) {
+            if (ctx->format == TFileFormatType::FORMAT_JSON) {
+                // For json format, we need build a complete json before we push the buffer to the pipe.
+                // buffer capacity is not enough, so we try to expand the buffer.
+                ByteBufferPtr buf = ByteBuffer::allocate(BitUtil::RoundUpToPowerOfTwo(ctx->buf->pos + len));
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:317]:
```suggestion
                ByteBufferPtr buf = ByteBuffer::allocate(std::max(ctx->buf->pos + len, ctx->buf->capacity * 1.5)));
```

File: be/src/http/action/stream_load.cpp (hunk 1 above)
Comment (sduzh) [reply be/src/http/action/stream_load.cpp:247]: Allocate extras SIMDJSON_PADDING bytes if this is a JSON file for better performance.

File: be/src/http/action/stream_load.cpp (hunk 4 above)
Comment (sduzh) [reply be/src/http/action/stream_load.cpp:332]: `ctx->buf` is used to read from `evbuf` through `evbuffer_remove`, according to the following code at line 341, if the capacity of `ctx->buf` is less than `len` the `evbuf` cannot be read fully at once, right?

File: be/src/http/action/stream_load.cpp (hunk 1 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp:247]: The CSV format load request may also provide `Content-Length`, so this is necessary.

Comment (sduzh) [reply be/src/http/action/stream_load.cpp]: But CSV does not need to buffer all data.

File: be/src/http/action/stream_load.cpp (hunk 6 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp]: This may slow down the expanding of buffer. What's your consideration?

File: be/src/http/action/stream_load.cpp (hunk 2 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp]: Updated. The buffer is allocated on demand now.

File: be/src/http/action/stream_load.cpp (hunk 4 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp]: Got that. Updated.

File: be/src/http/action/stream_load.cpp (hunk 1 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp]: Got it. This allocation now only work for JSON.

File: be/src/http/action/stream_load.cpp [hunk 7]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
+        if (ctx->buffer == nullptr) {
+            // Initialize buffer.
+            ctx->buffer = ByteBuffer::allocate(ctx->kDefaultBufferSize);
+
+        } else if (ctx->buffer->remaining() < len) {
+            if (ctx->format == TFileFormatType::FORMAT_JSON) {
+                // For json format, we need build a complete json before we push the buffer to the pipe.
+                // buffer capacity is not enough, so we try to expand the buffer.
+                ByteBufferPtr buf = ByteBuffer::allocate(BitUtil::RoundUpToPowerOfTwo(ctx->buffer->pos + len));
+                buf->put_bytes(ctx->buffer->ptr, ctx->buffer->pos);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:324]: Reallocation in this way results in O(n^2) complexity for insertions. 
Reference: https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md

File: be/src/http/action/stream_load.cpp [hunk 8]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
 
     int64_t start_read_data_time = MonotonicNanos();
-    while (evbuffer_get_length(evbuf) > 0) {
-        ByteBufferPtr bb = ByteBuffer::allocate(4096);
+
+    size_t len = 0;
+    while ((len = evbuffer_get_length(evbuf)) > 0) {
+        if (ctx->buffer == nullptr) {
+            // Initialize buffer.
+            ctx->buffer = ByteBuffer::allocate(ctx->kDefaultBufferSize);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:317]:
```suggestion
            ctx->buffer = ByteBuffer::allocate(std::max(len, ctx->kDefaultBufferSize));
```

File: be/src/http/action/stream_load.cpp [hunk 9]
```diff
@@ -237,6 +242,11 @@ Status StreamLoadAction::_on_header(HttpRequest* http_req, StreamLoadContext* ct
             ss << "body exceed max size: " << max_body_bytes << ", limit: " << max_body_bytes;
             return Status::InternalError(ss.str());
         }
+
+        if (ctx->format == TFileFormatType::FORMAT_JSON) {
+            // Allocate buffer in advance, since the json payload cannot be parsed in stream mode.
+            ctx->buffer = ByteBuffer::allocate(ctx->body_bytes);
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:248]:
```suggestion
            ctx->buffer = ByteBuffer::allocate(ctx->body_bytes + simdjson::SIMDJSON_PADDING);
```

File: be/src/http/action/stream_load.cpp (hunk 6 above)
Comment (sduzh) [reply be/src/http/action/stream_load.cpp]: Reallocation in this way results in O(n^2) complexity for insertions.
Reference: https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md

File: be/src/http/action/stream_load.cpp [hunk 10]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
     auto evbuf = evhttp_request_get_input_buffer(ev_req);
 
     int64_t start_read_data_time = MonotonicNanos();
-    while (evbuffer_get_length(evbuf) > 0) {
-        ByteBufferPtr bb = ByteBuffer::allocate(4096);
+
+    size_t len = 0;
+    while ((len = evbuffer_get_length(evbuf)) > 0) {
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:314]: If `len` is zero but `ctx->buffer` is nonempty, when will the buffer be flushed to the body sink?

File: be/src/http/action/stream_load.cpp [hunk 11]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
-        bb->pos = remove_bytes;
-        bb->flip();
-        auto st = ctx->body_sink->append(bb);
-        if (!st.ok()) {
-            LOG(WARNING) << "append body content failed. errmsg=" << st.get_error_msg() << ctx->brief();
-            ctx->status = st;
-            return;
+            remove_bytes = evbuffer_remove(evbuf, ctx->buffer->ptr + ctx->buffer->pos, ctx->buffer->remaining());
         }
+        ctx->buffer->pos += remove_bytes;
```
Comment (sduzh) [inline be/src/http/action/stream_load.cpp:349]: If this is not a json file, call `ctx->body_sink->append(std::move(ctx->buffer));`

File: be/src/http/action/stream_load.cpp [hunk 12]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
-    while (evbuffer_get_length(evbuf) > 0) {
-        ByteBufferPtr bb = ByteBuffer::allocate(4096);
+
+    size_t len = 0;
+    while ((len = evbuffer_get_length(evbuf)) > 0) {
+        if (ctx->buffer == nullptr) {
+            // Initialize buffer.
+            ctx->buffer = ByteBuffer::allocate(ctx->kDefaultBufferSize);
+
+        } else if (ctx->buffer->remaining() < len) {
```
Comment (chaoyli) [inline be/src/http/action/stream_load.cpp:319]: Also, the file using the gzip/bzip2/lz4/deflate/zstd, the file should be complete.

File: be/src/http/action/stream_load.cpp [hunk 13]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
+                // buffer capacity is not enough, so we push the buffer to the pipe and allocate new one.
+                ctx->buffer->flip();
+                auto st = ctx->body_sink->append(std::move(ctx->buffer));
+                if (!st.ok()) {
+                    LOG(WARNING) << "append body content failed. errmsg=" << st << " context=" << ctx->brief();
+                    ctx->status = st;
+                    return;
+                }
+
+                ctx->buffer = ByteBuffer::allocate(std::max(len, ctx->kDefaultBufferSize));
```
Comment (chaoyli) [inline be/src/http/action/stream_load.cpp:338]: If the len is large, you will allocate much memory to read it.

File: be/src/http/action/stream_load.cpp [hunk 14]
```diff
@@ -299,23 +309,44 @@ void StreamLoadAction::on_chunk_data(HttpRequest* req) {
...
+    while ((len = evbuffer_get_length(evbuf)) > 0) {
+        if (ctx->buffer == nullptr) {
+            // Initialize buffer.
+            ctx->buffer = ByteBuffer::allocate(ctx->kDefaultBufferSize);
+
+        } else if (ctx->buffer->remaining() < len) {
+            if (ctx->format == TFileFormatType::FORMAT_JSON) {
+                // For json format, we need build a complete json before we push the buffer to the pipe.
+                // buffer capacity is not enough, so we try to expand the buffer.
+                ByteBufferPtr buf = ByteBuffer::allocate(BitUtil::RoundUpToPowerOfTwo(ctx->buffer->pos + len));
```
Comment (chaoyli) [inline be/src/http/action/stream_load.cpp:323]: Does it seem the JSON must read all of the data?

File: be/src/http/action/stream_load.cpp (hunk 11 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp:349]: The original implement batches buffer as 64KB per group in `stream_load_pipe`. Since `Status StreamLoadPipe::append(ByteBufferPtr&& buf)` does not batch buffer, now the batch is done in 
https://github.com/StarRocks/starrocks/blob/c9b99d66b56f38ae79955d47144f6d01d05e5436/be/src/http/action/stream_load.cpp#L347. 
If `ctx->body_sink->append(std::move(ctx->buffer))` is called here, the batch is unavailable.

File: be/src/http/action/transaction_stream_load.cpp [hunk 15]
```diff
@@ -421,7 +421,7 @@ void TransactionStreamLoadAction::on_chunk_data(HttpRequest* req) {
         }
         bb->pos = remove_bytes;
         bb->flip();
-        auto st = ctx->body_sink->append(bb);
+        auto st = ctx->body_sink->append(std::move(bb));
```
Comment (meegoo) [inline be/src/http/action/transaction_stream_load.cpp:424]: should support chunked json transfer both StreamLoad & TransactionStreamLoad

File: be/src/http/action/stream_load.cpp (hunk 14 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp:323]: Yes. The json parser input must be a complete json,

**Review by sduzh — DISMISSED** [review]

File: be/src/http/action/stream_load.cpp (hunk 12 above)
Comment (rickif) [reply be/src/http/action/stream_load.cpp:321]: Since the json parser need complete json as input, the allocation of memory whose size is equal to file size is necessary. Maybe some other measure should be taken to avoid allocating too much memory simultaneously.

File: be/src/http/action/transaction_stream_load.cpp (hunk 15 above)
Comment (rickif) [reply be/src/http/action/transaction_stream_load.cpp:424]: I see. Maybe it's better to create another PR to solve this.

**Review by chaoyli — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by sduzh — APPROVED** [review]
