### PR TITLE
BugFix : keep storage_medium property consistent when add partition dynamically

### LINKED ISSUE #1692: The default medium of a dynamic partition table is SSD, and the automatically created partition is HDD
### Steps to reproduce the behavior (Required)
1. CREATE TABLE test2 (
    k1 DATE,
    k2 INT,
    k3 SMALLINT,
    v1 VARCHAR(2048),
    v2 DATETIME DEFAULT "2014-02-04 15:36:00"
)
ENGINE=olap
DUPLICATE KEY(k1, k2, k3)
PARTITION BY RANGE (k1) (
     START ("2021-09-01") END ("2021-11-03") EVERY (INTERVAL 1 WEEK)
)
DISTRIBUTED BY HASH(k2) BUCKETS 6
PROPERTIES (
    "replication_num" = "1",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "WEEK",
    "dynamic_partition.time_zone" = "Asia/Shanghai",
    "dynamic_partition.start" = "-2147483648",
    "dynamic_partition.end" = "1",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "6",
    "in_memory" = "false",
    "storage_format" = "DEFAULT",
    "storage_medium" = "ssd"
);
2. show partitions from test2;

### Expected behavior (Required)
all partition is SSD
### Real behavior (Required)
some parition is SSD dynamic create partition is HDD。

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
1.19.2

### PR DESCRIPTION
**Pull request by Astralidea**
Fix #1692
1. If the user sets `storage_medium` when creating a table. 
    we need to save this property so that dynamic partitioning can be used.
2. If the user has not set it, then the default behavior("storage_medium" = "HDD") is used. 
3. If the `storage_medium` property is set when adding a partition instead of creating a table. 
    ```
    alter table test2 add partition p11 values less than ("2021-12-24") properties ("storage_medium" = "SSD")
   ```
   Under this circumstance, the property should be passed to other partitions when using dynamic partitioning.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 1]
```diff
@@ -3915,9 +3915,13 @@ private void createOlapTable(Database db, CreateTableStmt stmt) throws DdlExcept
             // use table name as this single partition name
             long partitionId = partitionNameToId.get(tableName);
             DataProperty dataProperty = null;
+            boolean hasMedium = stmt.getProperties().containsKey(PropertyAnalyzer.PROPERTIES_STORAGE_MEDIUM);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:3918]: properties maybe null.

File: fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java [hunk 2]
```diff
@@ -186,6 +187,11 @@ public void createOrUpdateRuntimeInfo(String tableName, String key, String value
                 partitionProperties
                         .put("replication_num", String.valueOf(dynamicPartitionProperty.getReplicationNum()));
             }
+            Map<String, String> tableProperty = olapTable.getTableProperty().getProperties();
+            if (tableProperty != null && tableProperty.containsKey(PropertyAnalyzer.PROPERTIES_STORAGE_MEDIUM)) {
+                partitionProperties.put(PropertyAnalyzer.PROPERTIES_STORAGE_MEDIUM,
+                        tableProperty.get(PropertyAnalyzer.PROPERTIES_STORAGE_MEDIUM));
+            }
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/clone/DynamicPartitionScheduler.java:194]: I think it is better to put this into Catalog.getOrSetDefaultProperties when addPartitions.
In this way, both alter table and dynamic partition scheduler add partition are effective.
Only dynamic properties need to be checked here.

**Review by wyb — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 3]
```diff
@@ -3154,11 +3154,20 @@ public void addPartitions(Database db, String tableName, List<SingleRangePartiti
             RangePartitionInfo rangePartitionInfo = (RangePartitionInfo) partitionInfo;
             Set<String> existPartitionNameSet =
                     CatalogChecker.checkPartitionNameExistForAddPartitions(olapTable, singleRangePartitionDescs);
-
+            // partition properties is prior to clause properties
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:3157]: What is clause property?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:3157]: The clasue property has the form for example:
alter table test2 add partition p11 values less than ("2021-12-24") properties ("storage_medium" = "ssd")
this properties is clasue property because alter table could do batch operation.
if partition is not set property clasue property will apply to set every partition their properties.

**Review by chaoyli — APPROVED** [review]
