### PR TITLE
[BugFix] Non-existed jsonpath

### LINKED ISSUE #19357: Non-existed jsonpath key
Imagine we have a json document `{"key": 1}`.
If we set the jsonpath as `$.key_not_exsited`, the stream load would load a null value into the table.
But if we set the jsonpath as `$.key.not_existed`, the stream load get error.

### Steps to reproduce the behavior (Required)
1. Create table
```
CREATE TABLE `tbl_simple` ( `key1` int NULL COMMENT "", `key2` int NULL COMMENT "" ) ENGINE = OLAP DUPLICATE KEY(`key1`) COMMENT "OLAP" DISTRIBUTED BY HASH(`key1`) BUCKETS 10 PROPERTIES ( "replication_num" = "1");
```
3. Load data
```
 curl --location-trusted -u root:  'http://127.0.0.1:8063/api/db0/tbl_simple/_stream_load' \-X PUT  \-H 'format: json' -H 'jsonpaths: ["$.key1.non-existed"]' -d '{"key1": 1, "key2": 1}'
```

### Expected behavior (Required)
Load successfully.

### Real behavior (Required)

```
{
    "TxnId": 10,
    "Label": "d4936b4c-e8ba-4531-bf2b-688337fef54b",
    "Status": "Fail",
    "Message": "too many filtered rows",
    "NumberTotalRows": 1,
    "NumberLoadedRows": 0,
    "NumberFilteredRows": 1,
    "NumberUnselectedRows": 0,
    "LoadBytes": 22,
    "LoadTimeMs": 27,
    "BeginTxnTimeMs": 4,
    "StreamLoadPutTimeMs": 11,
    "ReadDataTimeMs": 0,
    "WriteDataTimeMs": 10,
    "CommitAndPublishTimeMs": 0,
    "ErrorURL": "http://127.0.0.1:8063/api/_load_error_log?file=error_log_5a4c9116f49fbae8_b605d30240f4bf9a"

Error: Data quality error: err: The JSON element does not have the requested type., msg: unable to find field: non-existed. Row: {"key1": 1, "key2": 1}
```

### StarRocks version (Required)
2.5.2, 2.4.4, 2.3.6

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19357 #18641

## Problem Summary(Required) ：

This PR solves some jsonpath issues. Please refer the test case in `be/test/exprs/json_functions_test.cpp` to know the change.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Comment by rickif** [comment]
run starrocks_be_unittest

**Review by chaoyli — DISMISSED** [review]

File: be/src/exprs/json_functions.cpp [hunk 1]
```diff
@@ -218,6 +231,14 @@ void JsonFunctions::parse_json_paths(const std::string& path_string, std::vector
     _get_parsed_paths(paths, parsed_paths);
 }
 
+std::string JsonFunctions::jsonpaths_to_string(const std::vector<SimpleJsonPath>& paths) {
+    std::string output;
+    for (auto const& path : paths) {
+        output.append(".").append(path.to_string());
```
Comment (jaogoy) [inline be/src/exprs/json_functions.cpp:237]: starts with `.`, without leading `$`?

File: be/src/exprs/json_functions.cpp [hunk 2]
```diff
@@ -147,7 +147,7 @@ Status JsonFunctions::extract_from_object(simdjson::ondemand::object& obj, const
     // Skip the first $.
     for (int i = 1; i < jsonpath.size(); i++) {
         if (UNLIKELY(!jsonpath[i].is_valid)) {
-            return Status::InvalidArgument(fmt::format("invalid json path: {}", jsonpath[i].key));
+            return Status::InvalidArgument(fmt::format("invalid json path: {}", jsonpaths_to_string(jsonpath)));
```
Comment (jaogoy) [inline be/src/exprs/json_functions.cpp:150]: why do you print the whole jsonpath rather than the exect error part?
that is : if we cant find the value of key `$.a.b`, don't print the whole jsonpath `$.a.b.c.d`

File: be/src/exprs/json_functions.cpp [hunk 3]
```diff
@@ -157,35 +157,42 @@ Status JsonFunctions::extract_from_object(simdjson::ondemand::object& obj, const
...
+            // 1. {"field_name": null}
+            // 2. {"field_name": {"field_type": data}}
+            // For pattern1, we just return null value.
+            // For pattern2, we get the first field of object as next value.
+
+            if (tvalue.is_null()) {
+                return Status::NotFound(fmt::format("unable to find key: {}", jsonpaths_to_string(jsonpath)));
+            }
+
+            if (tvalue.type() != simdjson::ondemand::json_type::object) {
```
Comment (jaogoy) [inline be/src/exprs/json_functions.cpp:184]: is `$.a` for `{"a":1}` wrong?

File: be/src/exprs/json_functions.cpp [hunk 4]
```diff
@@ -157,35 +157,42 @@ Status JsonFunctions::extract_from_object(simdjson::ondemand::object& obj, const
...
-                // For pattern1, we just return null value.
-                // For pattern2, we get the first field of object as next value.
-                if (tvalue.is_null()) {
-                    return Status::NotFound("null value");
-                }
-                if (tvalue.type() != simdjson::ondemand::json_type::object) {
-                    return Status::InvalidArgument(fmt::format(
-                            "extracting * from non-object type is not supported, the json path: {}", jsonpath[i].key));
-                }
                 for (auto field : tvalue.get_object()) {
```
Comment (jaogoy) [inline be/src/exprs/json_functions.cpp:189]: will tvalue.get_object() return null if `$.a[*]` is not a JSON object, such as `{"a":1}`?

File: be/src/exprs/json_functions.cpp [hunk 5]
```diff
@@ -194,13 +201,19 @@ Status JsonFunctions::extract_from_object(simdjson::ondemand::object& obj, const
             // If the index is beyond the length of array, simdjson::INDEX_OUT_OF_BOUNDS would be returned.
             simdjson::ondemand::array arr;
             HANDLE_SIMDJSON_ERROR(tvalue.get_array().get(arr),
```
Comment (jaogoy) [inline be/src/exprs/json_functions.cpp:203]: will tvalue.get_array() return null

File: be/src/exprs/json_functions.cpp (hunk 4 above)
Comment (jaogoy) [reply be/src/exprs/json_functions.cpp:189]: Does  `$.a.*`  stand for any key name?

File: be/test/exprs/json_functions_test.cpp [hunk 6]
```diff
@@ -721,6 +721,12 @@ TEST_F(JsonFunctionsTest, extract_from_object_test) {
 
     EXPECT_STATUS(Status::DataQualityError(""),
                   test_extract_from_object(R"({"data1 " : 1, "data2":})", "$.data", &output));
+
+    EXPECT_STATUS(Status::NotFound(""), test_extract_from_object(R"({"data": null})", "$.data", &output));
```
Comment (jaogoy) [inline be/test/exprs/json_functions_test.cpp:725]: It's better to test `{}` and null also.

File: be/src/exprs/json_functions.cpp (hunk 3 above)
Comment (rickif) [reply be/src/exprs/json_functions.cpp:184]: `$.a` is OK. But `$.a.b` is not OK.

**Review by chaoyli — DISMISSED** [review]

File: be/src/exprs/json_functions.cpp (hunk 5 above)
Comment (rickif) [reply be/src/exprs/json_functions.cpp:212]: No. An error would be returned.

File: be/src/exprs/json_functions.cpp (hunk 4 above)
Comment (rickif) [reply be/src/exprs/json_functions.cpp:198]: > will tvalue.get_object() return null if `$.a[*]` is not a JSON object, such as `{"a":1}`?

Yes.

Comment (rickif) [reply be/src/exprs/json_functions.cpp:198]: > Does `$.a.*` stand for any key name?

`$.a.*` only works for `{"a": {"somekey": xxx}}`. The result is `{"somekey": xxx}`.
If the input is `{"a": 1}`, and the result would be null.

**Comment by rickif** [comment]
@mergifyio rebase

**Review by jaogoy — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
