### PR TITLE
[BugFix]  Check the BE service exit status code before launching the be process

### LINKED ISSUE #46482: [bug] SimpleScheduler fails to track node status
### Steps to reproduce the behavior (Required)
1. deploy a SR cluster with multiple BE pods, some configurations to highlight:
  * `failureThreshold: 60`
  *  `lifecycle.preStop.exec.command: /opt/starrocks/be_prestop.sh`
  * FE_conf: 
```
      heartbeat_retry_times = 180
      heartbeat_timeout_second = 60
```

2. run load requests and/or SQL queries in the cluster;

3. kill a BE pod by running `kubectl delete pod be-x`, waiting for Kubernetes to bring it back;

### Expected behavior (Required)

a. after `kubectl delete`, the BE node should be **moved** to blacklist;
b. after k8s brings back the pod, the BE node should be **removed** from blacklist;
c. during the period, no work task is assigned to the BE node; 

### Real behavior (Required)
(b) and (c) is not guaranteed, see below examples for details:

-------
The example below provides more details:

* pod delete event timeline
```
2024-05-28 22:44:10 +0000 UTC   —- 1 Killing: Stopping container be 1 Killing: Stopping container pod-debugger
2024-05-28 22:45:15 +0000 UTC  Started container be 1
```

* SimpleScheduler event timeline

Screenshot 2024-05-30 at 1 37 06 PM

  * the BE node is added back early, at `May 28 15:44:27.642`;
  * a task is dispatched to the BE node at `May 28, 2024 at 3:45:12.676 pm`, failed later
> (loading_load_task_scheduler_priority_pool-7|632) [DefaultCoordinator.prepareProfile():522] dispatch load job: e60832f6-4550-4bfc-a055-9fd171a2893a to [10004, 10005, 10006, 10007, 17002, 17003, 17004, 17005, 17006, 17007]
Screenshot 2024-05-30 at 1 40 24 PM

### StarRocks version (Required)
3.2

cc @chaoyli @dengliu

### PR DESCRIPTION
**Pull request by yandongxiao**
## Why I'm doing:

BE should exit when BE service exits with status 0. This commit fixes this issue by adding a check for the exit status of BE service.

## What I'm doing:

Fixes #46482

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: docker/dockerfiles/be/be_entrypoint.sh [hunk 1]
```diff
@@ -132,7 +132,7 @@ while true; do
       tail -n $nol $STARROCKS_HOME/log/be.out
   fi
 
-  if [[ "$COREDUMP_ENABLED" != "true" ]]; then
+  if [[ "$COREDUMP_ENABLED" != "true" || $ret -eq 0 ]]; then
```
Comment (kevincai) [inline docker/dockerfiles/be/be_entrypoint.sh:135]: > 128+n | Fatal error signal “n”

if coredump enabled, only catch SIGABRT (6), SIGSEGV(11) and repeat launching be process, should still exit for rest error codes.

Comment (yandongxiao) [reply docker/dockerfiles/be/be_entrypoint.sh:135]: So do you mean:
```
if [[ "$COREDUMP_ENABLED" != "true" || $ret != 134 || $ret != 139 ]]; then
```

Comment (yandongxiao) [reply docker/dockerfiles/be/be_entrypoint.sh]: Updated

**Review by ZiheLiu — APPROVED** [review]

**Review by mingmxu — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
