### PR TITLE
[BugFix] Check invalid window argument

### LINKED ISSUE #5935: 【window_funnel】be crash when sliding_window=0 or  sliding_window= negative
### Steps to reproduce the behavior (Required)
1. 
```
CREATE TABLE `window_funnel_date` (
    `uid` int NOT NULL,
    `event_type` varchar(20) NOT NULL,
    `time` date NOT NULL)
DUPLICATE KEY(`uid`) DISTRIBUTED BY HASH(`uid`) buckets 4
PROPERTIES ("replication_num" = "1");
```
2. 
```
insert into window_funnel_date  values (1, "浏览", "2020-01-02"),
            (1, "点击", "2020-01-03"),
            (1, "下单", "2020-01-04"),
            (1, "支付", "2020-01-05"),
            (1, "浏览", "2020-01-06"),
            (2, "下单", "2020-01-07"),
            (2, "支付", "2020-01-08"),
            (3, "浏览", "2020-01-09"),
            (3, "点击", "2020-01-10"),
            (4, "浏览", "2020-01-11"),
            (4, "点击", "2020-01-12"),
            (5, "浏览", "2020-01-13"),
            (5, "点击", "2020-01-14"),
            (5, "下单", "2020-01-15"),
            (6, "浏览", "2020-01-25"),
            (6, "点击", "2020-01-26"),
            (6, "下单", "2020-01-27")
```
3. 
```
select window_funnel(0,time,0,[event_type="浏览", event_type="点击", event_type="下单", event_type="支付"]) from window_funnel_date;
```

### Expected behavior (Required)
return '' or return Reasonable explanation
### Real behavior (Required)
```ERROR 1064 (HY000): Backend not found. Check if any backend is down or not```

```
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  std::get: wrong index for variant
*** Aborted at 1652238011 (unix time) try "date -d @1652238011" if you are using GNU date ***
PC: @     0x7f25b463b387 __GI_raise
*** SIGABRT (@0x3f700000409) received by PID 1033 (TID 0x7f24fbe91700) from PID 1033; stack trace: ***
    @          0x3ec6d32 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f25b50f0630 (unknown)
    @     0x7f25b463b387 __GI_raise
    @     0x7f25b463ca78 __GI_abort
    @          0x180e84d _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x58850c6 __cxxabiv1::__terminate()
    @          0x5885131 std::terminate()
    @          0x5885284 __cxa_throw
    @          0x156aec6 std::__throw_bad_variant_access()
    @          0x156aee3 std::__throw_bad_variant_access()
    @          0x1920ae4 starrocks::vectorized::FixedLengthColumnBase<>::append_datum()
    @          0x2431477 starrocks::vectorized::NullableColumn::append_datum()
    @          0x241d9e0 starrocks::vectorized::ArrayColumn::append_datum()
    @          0x2b22e31 starrocks::vectorized::WindowFunnelAggregateFunction<>::serialize_to_column()
    @          0x2a6d524 starrocks::vectorized::NullableAggregateFunctionBase<>::serialize_to_column()
    @          0x287bd4d starrocks::Aggregator::convert_to_chunk_no_groupby()
    @          0x281ef92 starrocks::pipeline::AggregateBlockingSourceOperator::pull_chunk()
    @          0x280f1da starrocks::pipeline::PipelineDriver::process()
    @          0x2805728 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x20a62b9 starrocks::ThreadPool::dispatch_thread()
    @          0x20a1e6a starrocks::Thread::supervise_thread()
    @     0x7f25b50e8ea5 start_thread
    @     0x7f25b47038dd __clone
    @                0x0 (unknown)
(END)
```
### StarRocks version (Required)
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 5742dc4 |
+----------------------+

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/5935

## Problem Summary(Required) ：

Report Error message for nagative value of window.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|6|8|75.00%|

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 1]
```diff
@@ -819,6 +819,11 @@ public void testWindowFunnel() throws Exception {
         plan = getFragmentPlan(sql);
         assertContains(plan, "window_funnel(1800, 11: L_SHIPDATE, 3, 18: expr)");
 
+        sql =
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:822]: The UT should cover the invalid argument.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|7|8|87.50%|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java [hunk 2]
```diff
@@ -171,6 +171,17 @@ private static void analyzeBuiltinAggFunction(FunctionCallExpr functionCallExpr)
...
+
+            Expr windowArg = functionCallExpr.getChild(0);
+            if (windowArg instanceof IntLiteral) {
+                IntLiteral windowIntLiteral = (IntLiteral) windowArg;
+                long windowValue = windowIntLiteral.getValue();
+                if (windowValue < 0) {
+                    throw new SemanticException("window argument must >= 0");
+                }
+            } else {
+                throw new SemanticException("window argument must be numerical type");
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java:183]: UT should cover this Exception

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 3]
```diff
@@ -819,6 +820,16 @@ public void testWindowFunnel() throws Exception {
...
+                "select L_ORDERKEY,window_funnel(-1, L_SHIPDATE, 3, [L_PARTKEY = 1]) from lineitem_partition_colocate group by L_ORDERKEY;";
+	try {
+            plan = getFragmentPlan(sql);
+        } catch (SemanticException e) {
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:827]: could use ExpectedException, refer to ColocateTableTest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|6|8|75.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|7|8|87.50%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|7|8|87.50%|

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java (hunk 3 above)
Comment (Pslydhh) [reply fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java]: > could use ExpectedException, refer to ColocateTableTest

done

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java (hunk 2 above)
Comment (kangkaisen) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/FunctionAnalyzer.java:183]: The Exception: window argument must >= 0 and window argument must be numerical type both need to cover

**Comment by Pslydhh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|8|8|100.00%|

**Review by murphyatwork — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.3

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java [hunk 4]
```diff
@@ -822,6 +823,34 @@ public void testWindowFunnel() throws Exception {
         FeConstants.runningUnitTest = false;
     }
 
+    @Test
+    public void testWindowFunnelWithInvalidDecimalWindow() throws Exception {
+        FeConstants.runningUnitTest = true;
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:828]: Why need to change the FeConstants.runningUnitTest  in the test?

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Pslydhh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java (hunk 4 above)
Comment (Pslydhh) [reply fe/fe-core/src/test/java/com/starrocks/sql/plan/AggregateTest.java:827]: > Why need to change the FeConstants.runningUnitTest in the test?

It must be used to avoid failure of others uts.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Pslydhh** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|not covered line detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|8|8|100.00%|[]|

**Comment by Pslydhh** [comment]
run starrocks_admit_test

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
