### PR TITLE
[Enhancement] Allow SELECT/SET in explicit transactions and add error 5307 for SELECT on previously modified tables

### LINKED ISSUE #63741: Duckdb (MySQL extension) throwing error
Since the addition of this check:
https://github.com/StarRocks/starrocks/blob/e5bf03cda5acc66f9321760c046fdcbb30a8fa16/fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java#L406-L415
Starrocks + Duckdb (with MySQL extension) it can no longer be used, because internally DuckDB [launches a SELECT to retrieve information from all the schemas](https://github.com/duckdb/duckdb-mysql/blob/2af8a98b7bd442df82305ae1f1578d56d424f083/src/storage/mysql_schema_set.cpp#L18-L21). This SELECT, together with this check inside StarRocks, causes an error in StarRocks when you try to perform an INSERT (or any command) using DuckDB + the MySQL extension. What was the purpose of this check? Why limit transactions to only pure INSERTs?
### Steps to reproduce the behavior (Required)
```python
uri = '[mysql_uri_connection_parameters]'
duckdb_conn = duckdb.connect()
duckdb_conn.execute(f"""
            INSTALL mysql;
            LOAD mysql;
            ATTACH '{uri}' AS starrock_db
            (TYPE mysql);")
duckdb_conn.execute("SELECT * FROM starrock_db.any.table;")

"""Will throw error:
IO Error: Failed to run query " # Query specified above, from duckdb-mysql
SELECT schema_name
FROM information_schema.schemata;
": Explicit transaction only support insert statement
"""

```

### Expected behavior (Required)
Allow SELECT statement in transaction
### Real behavior (Required)
Throwing error because SELECTs are not allowed.
### StarRocks version (Required)
 - 3.5.6-3ba6b8d (Also happens in >3.4 and 4.0-rc2)

### PR DESCRIPTION
**Pull request by meegoo**
## Why I'm doing:

Ensures explicit transactions are flexible (read after write on other tables allowed) while preventing inconsistent rereads of tables already mutated in the same transaction and providing a precise diagnostic code.

## What I'm doing:

Introduce finer-grained explicit transaction controls:

Allow SELECT and SET inside BEGIN/COMMIT transactions Maintain modified table id set in ExplicitTxnState (updated via TransactionStmtExecutor after DML) Block SELECT that references any table already modified earlier in the same explicit transaction with new error code 5307 (ERR_EXPLICIT_TXN_SELECT_ON_MODIFIED_TABLE) Refine generic unsupported statement error (5305) to enumerate allowed statements: BEGIN/COMMIT/ROLLBACK/INSERT/UPDATE/DELETE/SET/SELECT Update ConnectProcessor gating logic and table collection for SELECT (Analyzer + AnalyzerUtils) Add new error code definition and message; adjust existing 5305 message

Fixes #63741

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> Enables SELECT and SET within explicit transactions, tracks modified tables, and validates to reject SELECTs (including INSERT ... SELECT sources) that read tables already mutated in the same transaction with new error 5307.
> 
> - **Explicit transaction validation**
>   - Add `ExplicitTxnStatementValidator` to validate statements in explicit transactions, allowing `select`, `set`, and txn statements; disallow `insert overwrite`; block reads of tables modified earlier (error `5307`).
> - **State tracking**
>   - Extend `ExplicitTxnState` with `modifiedTableIds` and accessors to record DML target table IDs.
>   - Update `TransactionStmtExecutor` to add modified table IDs on DML.
> - **Planner/execution integration**
>   - Invoke `ExplicitTxnStatementValidator.validate(...)` in `ConnectProcessor` and `StatementPlanner` after analysis (both deferred and non-deferred paths).
> - **Error codes**
>   - Refine `ERR_EXPLICIT_TXN_NOT_SUPPORT_STMT (5305)` message to enumerate allowed statements.
>   - Add `ERR_EXPLICIT_TXN_SELECT_ON_MODIFIED_TABLE (5307)` with message for forbidden SELECTs.
> - **Tests**
>   - Add SQL tests under `test/sql/test_explicit_txn_select` for SELECT restrictions and allowed SET/SELECT flows.
>   - Adjust `ExplicitTxnTest` to permit simple SELECT in explicit txn and keep `insert overwrite` disallowed.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 80b0a2e58da168445bd8c0b51daaea17be39654b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java [hunk 1]
```diff
@@ -403,16 +398,8 @@ protected void handleQuery() {
...
-                                parsedStmt instanceof BeginStmt ||
-                                parsedStmt instanceof CommitStmt ||
-                                parsedStmt instanceof UpdateStmt ||
-                                parsedStmt instanceof DeleteStmt ||
-                                parsedStmt instanceof RollbackStmt)) {
-                    ErrorReport.report(ErrorCode.ERR_EXPLICIT_TXN_NOT_SUPPORT_STMT);
-                    ctx.getState().setErrType(QueryState.ErrType.ANALYSIS_ERR);
-                    return;
+                if (ctx.getTxnId() != 0) {
+                    ExplicitTxnStatementValidator.validate(parsedStmt, ctx);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java:402]: setErrType？

Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java:402]: reportSemanticException will throw exception

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by wyb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
