### PR TITLE
[FixBug] Fix lose of meta data bug after alter routine load

### LINKED ISSUE #6936: [BUG] Some load parameters are lost after alter routine load
### Steps to reproduce the behavior (Required)
1. create routine load
```
CREATE ROUTINE LOAD partsuppload ON partsupp
COLUMNS TERMINATED BY ",",
COLUMNS (a)
PROPERTIES
(
 "max_error_number"="10000",
 "desired_concurrent_number"="55",
 "strict_mode" = "false"
)
FROM KAFKA
(
 "kafka_broker_list"= "1.2.2.2",
 "kafka_topic" = "table1123",
 "property.group.id" = "group1",
 "property.kafka_default_offsets" = "OFFSET_END"
);
```

2. alter routine load
```
alter routine load for partsuppload COLUMNS TERMINATED BY "\t"
```

3. After master makes a new image and push it to other fes, restart all fe.

### Expected behavior (Required)
the columns should be reserved.

### Real behavior (Required)
the columns in routine load meta is lost.

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6936

## Problem Summary(Required) ：

When routine load serializes the load properties(columns/rows separator, column list, partitions, where filter), it stores the sql statement, and get the load properties by parsing the sql for deserialization. But after `alter routine load` is done, it will only keep the alter statement, this will cause the loss of metadata. We should merge the alter sql with the origin create sql to retain all load properties.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 76 / 94 (80.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadManager.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|23|38|60.53%|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|37|38|97.37%|
|:large_blue_circle:|com/starrocks/analysis/CreateRoutineLoadStmt.java|16|16|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java [hunk 1]
```diff
@@ -1540,6 +1529,68 @@ public void modifyJob(RoutineLoadDesc routineLoadDesc,
...
+        }
+        if (routineLoadDesc.getWherePredicate() != null) {
+            originLoadDesc.setWherePredicate(routineLoadDesc.getWherePredicate());
+        }
+        if (routineLoadDesc.getPartitionNames() != null) {
+            originLoadDesc.setPartitionNames(routineLoadDesc.getPartitionNames());
+        }
+
+        // we use sql to persist the load properties, so we just put the load properties to sql.
+        String sql = "CREATE ROUTINE LOAD job ON tbl "
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:1558]: `job`, `tbl` should be replace with current name.

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java [hunk 2]
```diff
@@ -1540,6 +1529,68 @@ public void modifyJob(RoutineLoadDesc routineLoadDesc,
...
+                + originLoadDesc.toSql()
+                + " PROPERTIES (\"desired_concurrent_number\"=\"1\")"
+                + " FROM KAFKA (\"kafka_topic\" = \"my_topic\")";
+        LOG.debug("merge result: {}", sql);
+        origStmt = new OriginStatement(sql, 0);
+    }
+
+    public RoutineLoadDesc getLoadDesc(OriginStatement origStmt, Map<String, String> sessionVariables)
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:1566]: This function seems to be identical with CreateRoutineLoadStmt.getLoadDesc()? Is it useful? I can't find the usage of this one.

File: fe/fe-core/src/main/java/com/starrocks/load/RoutineLoadDesc.java [hunk 3]
```diff
@@ -48,20 +55,90 @@ public ColumnSeparator getColumnSeparator() {
...
+                    + ")";
+            subSQLs.add(subSQL);
+        }
+        if (wherePredicate != null) {
+            subSQLs.add("WHERE " + wherePredicate.getExpr().toSql());
+        }
+        return String.join(", ", subSQLs);
+    }
+
+    public String pack(String str) {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/load/RoutineLoadDesc.java:128]: public -> private

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 2 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java:1566]: I forget to remove it.

File: fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java [hunk 4]
```diff
@@ -285,6 +297,33 @@ public void analyze(Analyzer analyzer) throws UserException {
...
+                        buildLoadDesc(((CreateRoutineLoadStmt) stmt).getLoadPropertyList());
+            } else if (stmt instanceof AlterRoutineLoadStmt) {
+                return CreateRoutineLoadStmt.
+                        buildLoadDesc(((AlterRoutineLoadStmt) stmt).getLoadPropertyList());
+            } else {
+                throw new IOException("stmt is neither CreateRoutineLoadStmt nor AlterRoutineLoadStmt");
+            }
+        } catch (Exception e) {
+            LOG.error("error happens when parsing create/alter routine load stmt: " + origStmt.originStmt, e);
+            return null;
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java:323]: why return null not throw exception, inconsistent with previous behavior

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: done

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java (hunk 2 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/RoutineLoadJob.java]: done

File: fe/fe-core/src/main/java/com/starrocks/load/RoutineLoadDesc.java (hunk 3 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/load/RoutineLoadDesc.java]: done

File: fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java (hunk 4 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/analysis/CreateRoutineLoadStmt.java:323]: If exception is thrown here, the fe will start failed.  I'm afraid that there may be some corner case I have not considered. This is not a critical problem, so we just return null, and the load desc can be null.

**Review by padmejin — DISMISSED** [review]
LGTM

**Review by Astralidea — DISMISSED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 80 / 85 (94.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadManager.java|0|2|00.00%|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|27|29|93.10%|
|:large_blue_circle:|com/starrocks/load/RoutineLoadDesc.java|37|38|97.37%|
|:large_blue_circle:|com/starrocks/analysis/CreateRoutineLoadStmt.java|16|16|100.00%|

**Review by wyb — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
