### PR TITLE
[Enhancement] Optimize memory usage of bitmap_index_writer for high cardinality case

### LINKED ISSUE #34606: Alter table OOM and no detailed error message
### Real behavior (Required)
When alter table OOM, the error message just says runtime error without root cause, and the alter process will invoke multiple retries which is expected to fail again(without changing memory limit), so wasting a lot of resources. 

There are 3 issues that can be improved:

1. more detailed error message(in this case OOM) rather than just RUNTIME_ERROR
2. optimize bitmap index build memory usage
3. if Alter got OOM, should not retry alter task before  increasing memory limit

```
mysql> alter table testbitmap add index idx_v0 (v0) using bitmap;
Query OK, 0 rows affected (0.03 sec)

mysql> show alter table column;
+-------+------------+---------------------+---------------------+------------+---------+---------------+---------------+---------------+-----------+-------------------------------------------------------------------------------------------------------------+----------+---------+
| JobId | TableName  | CreateTime          | FinishTime          | IndexName  | IndexId | OriginIndexId | SchemaVersion | TransactionId | State     | Msg                                                                                                         | Progress | Timeout |
+-------+------------+---------------------+---------------------+------------+---------+---------------+---------------+---------------+-----------+-------------------------------------------------------------------------------------------------------------+----------+---------+
| 78076 | testbitmap | 2023-11-08 19:40:38 | 2023-11-08 19:42:06 | testbitmap | 78077   | 78060         | 1:1698655310  | 29047         | CANCELLED | schema change task failed: task type: ALTER, status_code: RUNTIME_ERROR, backendId: 10006, signature: 78078 | NULL     | 86400   |
+-------+------------+---------------------+---------------------+------------+---------+---------------+---------------+---------------+-----------+-------------------------------------------------------------------------------------------------------------+----------+---------+
1 row in set (0.00 sec)

I1108 19:40:46.063531 277033 agent_task.cpp:252] [Alter Job:78076, tablet:78061]: get alter table task, signature: 78078
I1108 19:40:46.063580 277033 schema_change.cpp:617] [Alter Job:78076, tablet:78061]: begin to do request alter tablet: base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310, alter_version=2
I1108 19:40:46.063597 277033 schema_change.cpp:667] [Alter Job:78076, tablet:78061]: finish to validate alter tablet request. begin to convert data from base tablet to new tablet base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:40:46.063665 277033 schema_change.cpp:861] [Alter Job:78076, tablet:78061]: begin to remove all data from new tablet to prevent rewrite. new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:40:46.066526 277033 schema_change.cpp:958] [Alter Job:78076, tablet:78061]: begin to convert historical rowsets for new_tablet from base_tablet. base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3, new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:40:46.066550 277033 schema_change.cpp:975] [Alter Job:78076, tablet:78061]: doing directly schema change for base_tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3
W1108 19:40:59.977465 277033 schema_change.cpp:442] [Alter Job:78076, tablet:78061]: fail to execute schema change: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149183640, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
W1108 19:40:59.977519 277033 schema_change.cpp:1025] [Alter Job:78076, tablet:78061]: failed to process the schema change. from tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 to tablet 78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189 version=0-2 error Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149183640, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
I1108 19:41:07.134586 277033 schema_change.cpp:635] [Alter Job:78076, tablet:78061]: finished alter tablet process, status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149183640, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] duration: 21071ms, peak_mem_usage: 2149183640 bytes
W1108 19:41:07.134621 277033 engine_alter_tablet_task.cpp:71] [Alter Job:78076, tablet:78061]: failed to do alter task. status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149183640, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310
W1108 19:41:07.134646 277033 agent_task.cpp:122] [Alter Job:78076, tablet:78061]: alter failed. signature: 78078
I1108 19:41:10.416699 277051 agent_task.cpp:252] [Alter Job:78076, tablet:78061]: get alter table task, signature: 78078
I1108 19:41:10.416751 277051 schema_change.cpp:617] [Alter Job:78076, tablet:78061]: begin to do request alter tablet: base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310, alter_version=2
I1108 19:41:10.416770 277051 schema_change.cpp:667] [Alter Job:78076, tablet:78061]: finish to validate alter tablet request. begin to convert data from base tablet to new tablet base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:10.416868 277051 schema_change.cpp:861] [Alter Job:78076, tablet:78061]: begin to remove all data from new tablet to prevent rewrite. new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:10.420683 277051 schema_change.cpp:958] [Alter Job:78076, tablet:78061]: begin to convert historical rowsets for new_tablet from base_tablet. base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3, new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:10.420702 277051 schema_change.cpp:975] [Alter Job:78076, tablet:78061]: doing directly schema change for base_tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3
W1108 19:41:24.152643 277051 schema_change.cpp:442] [Alter Job:78076, tablet:78061]: fail to execute schema change: Memory of schema change task exceed limit. DirectSchemaChange Used: 2148508848, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
W1108 19:41:24.152702 277051 schema_change.cpp:1025] [Alter Job:78076, tablet:78061]: failed to process the schema change. from tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 to tablet 78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189 version=0-2 error Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2148508848, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
I1108 19:41:31.426074 277051 schema_change.cpp:635] [Alter Job:78076, tablet:78061]: finished alter tablet process, status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2148508848, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] duration: 21009ms, peak_mem_usage: 2148508848 bytes
W1108 19:41:31.426110 277051 engine_alter_tablet_task.cpp:71] [Alter Job:78076, tablet:78061]: failed to do alter task. status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2148508848, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310
W1108 19:41:31.426133 277051 agent_task.cpp:122] [Alter Job:78076, tablet:78061]: alter failed. signature: 78078
I1108 19:41:40.419538 277061 agent_task.cpp:252] [Alter Job:78076, tablet:78061]: get alter table task, signature: 78078
I1108 19:41:40.419595 277061 schema_change.cpp:617] [Alter Job:78076, tablet:78061]: begin to do request alter tablet: base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310, alter_version=2
I1108 19:41:40.419615 277061 schema_change.cpp:667] [Alter Job:78076, tablet:78061]: finish to validate alter tablet request. begin to convert data from base tablet to new tablet base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:40.419720 277061 schema_change.cpp:861] [Alter Job:78076, tablet:78061]: begin to remove all data from new tablet to prevent rewrite. new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:40.429003 277061 schema_change.cpp:958] [Alter Job:78076, tablet:78061]: begin to convert historical rowsets for new_tablet from base_tablet. base_tablet=78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3, new_tablet=78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189
I1108 19:41:40.429025 277061 schema_change.cpp:975] [Alter Job:78076, tablet:78061]: doing directly schema change for base_tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3
W1108 19:41:53.954239 277061 schema_change.cpp:442] [Alter Job:78076, tablet:78061]: fail to execute schema change: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149545720, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
W1108 19:41:53.954296 277061 schema_change.cpp:1025] [Alter Job:78076, tablet:78061]: failed to process the schema change. from tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3 to tablet 78078.1698655310.ba4d84c9d4d46490-aaea2c3170244189 version=0-2 error Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149545720, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change]
I1108 19:42:01.309376 277061 schema_change.cpp:635] [Alter Job:78076, tablet:78061]: finished alter tablet process, status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149545720, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] duration: 20889ms, peak_mem_usage: 2149545720 bytes
W1108 19:42:01.309409 277061 engine_alter_tablet_task.cpp:71] [Alter Job:78076, tablet:78061]: failed to do alter task. status=Memory limit exceeded: Memory of schema change task exceed limit. DirectSchemaChange Used: 2149545720, Limit: 2147483648. You can change the limit by modify BE config [memory_limitation_per_thread_for_schema_change] base_tablet_id=78061, base_schema_hash=643042751, new_tablet_id=78078, new_schema_hash=1698655310
W1108 19:42:01.309433 277061 agent_task.cpp:122] [Alter Job:78076, tablet:78061]: alter failed. signature: 78078

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
Why I'm doing:
User may experience OOM when adding bitmap index for a high cardinality column, currently implementation of bitmap_index_writer will maintain a roaring bitmap for each unique value which takes lot of memory.

What I'm doing:
For high cardinality case with lot of values having only one occurrence, maintaining a whole bitmap is too heavy weight, for this case, this PR will reuse BitmapUpdateContext pointer to store the single rowid_t value, cause pointer value % 2 == 0, so we can reuse the value space to store single rowid_t value. 

A new class named BitmapUpdateContextRefOrSingleValue is introduced, basically, it's an uint64_t

if last bit is 0 it is `BitmapUpdateContext*`, else it is a single value

Result:
```
alter table testbitmap2 add index idx_v0 (v0) using bitmap;

before:

I1113 14:59:50.142939 116396 schema_change.cpp:983] [Alter Job:81061, tablet:78061]: doing directly schema change for base_tablet 78061.643042751.f94268c285e1b6a8-1ae5fba9800c39b3
I1113 15:05:19.278360 116396 schema_change.cpp:643] [Alter Job:81061, tablet:78061]: finished alter tablet process, status=OK duration: 329608ms, peak_mem_usage: 5740344368 bytes

after:

I1113 15:57:53.338670 123179 schema_change.cpp:983] [Alter Job:82062, tablet:78071]: doing directly schema change for base_tablet 78071.643042751.8540e69ebf2aabb5-f4f582dc2198e1b3
I1113 16:01:10.065783 123179 schema_change.cpp:643] [Alter Job:82062, tablet:78071]: finished alter tablet process, status=OK duration: 196731ms, peak_mem_usage: 2380399632 bytes

```

Fixes #34606

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/storage/rowset/bitmap_index_writer.cpp [hunk 1]
```diff
@@ -115,14 +116,64 @@ class BitmapUpdateContext {
     bool _size_changed{false};
 };
 
+// if last bit is 0 it is std::unique_ptr<BitmapUpdateContext>
+// else it is a single value
+class BitmapUpdateContextRefOrSingleValue {
```
Comment (imay) [inline be/src/storage/rowset/bitmap_index_writer.cpp:121]: Did you consider replacing Roaring with BitmapValue in BitmapUpdateContext?
I think BitmapValue is more memory efficient than Roaring because it will only allocate it when it is needed.
BitmapValue may be more efficient than this CL solution when the distinct values are more than 1.
In this CL, if the distinct values are more than 1, it will be the same as before. But with BitmapValue, it will use less memory.

Comment (decster) [reply be/src/storage/rowset/bitmap_index_writer.cpp:121]: > Did you consider replacing Roaring with BitmapValue in BitmapUpdateContext?
Tried this today, just found out they have different serialization format and is not compatible with old format, are you sure to continue this path?

**Review by trueeyu — APPROVED** [review]

**Comment by trueeyu** [comment]
Maybe this is not a general optimization, it will fail if the base exceeds 1

**Comment by decster** [comment]
> Maybe this is not a general optimization, it will fail if the base exceeds 1

It's not general, the current bitmap index implementation seems suboptimal in many ways in  high cardinality cases(e.g. store bitmap with key maybe more efficient), although changing it may broke compatibility.

**Review by sevev — APPROVED** [review]
