### PR TITLE
[BugFix] array_agg process cancelled

### LINKED ISSUE #29400: array_agg cause BE crash when canceled
stack:
```
b16f9298e8 ASAN (build b16f9298e8)
query_id:85e1bc4e-3cd8-11ee-95fe-8e20563011de, fragment_instance:85e1bc4e-3cd8-11ee-95fe-8e20563011e0
tracker:process consumption: 0
tracker:query_pool consumption: 0
tracker:load consumption: 0
tracker:metadata consumption: 10301618
tracker:tablet_metadata consumption: 6390949
tracker:rowset_metadata consumption: 3896332
tracker:segment_metadata consumption: 4905
tracker:column_metadata consumption: 9432
tracker:tablet_schema consumption: 151309
tracker:segment_zonemap consumption: 2016
tracker:short_key_index consumption: 0
tracker:column_zonemap_index consumption: 4032
tracker:ordinal_index consumption: 1512
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 0
tracker:update consumption: 0
tracker:chunk_allocator consumption: -2097152
tracker:clone consumption: 0
tracker:consistency consumption: 0
*** Aborted at 1692261115 (unix time) try "date -d @1692261115" if you are using GNU date ***
PC: @          0x9844f70 __sanitizer::internal_memmove()
*** SIGSEGV (@0x2) received by PID 2440946 (TID 0x7f2cdc22e640) from PID 2; stack trace: ***
    @         0x14d8144a google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f2df4dbb520 (unknown)
    @          0x9844f70 __sanitizer::internal_memmove()
    @          0x98dc20a std::__copy_move<>::__copy_m<>()
    @          0x98d4d96 std::__copy_move_a2<>()
    @          0x98cf407 std::__copy_move_a1<>()
    @          0x98d7a1e std::__copy_move_a<>()
    @          0x98d1a93 std::copy<>()
    @          0x98cbc43 std::__uninitialized_copy<>::__uninit_copy<>()
    @          0x98c4e8b std::uninitialized_copy<>()
    @          0x98bc866 std::__uninitialized_copy_a<>()
    @          0x9b35f6a std::vector<>::_M_range_insert<>()
    @          0x9b0f18c std::vector<>::_M_insert_dispatch<>()
    @          0x9afae6e std::vector<>::insert<>()
    @          0x9a81e35 starrocks::FixedLengthColumnBase<>::append()
    @          0xb41aae8 starrocks::NullableColumn::append()
    @          0xe714b1a starrocks::ArrayAggAggregateFunctionV2::finalize_to_column()
    @          0xe838963 starrocks::AggregateFunctionBatchHelper<>::batch_finalize_with_selection()
    @          0xd212122 starrocks::SortedStreamingAggregator::_get_agg_result_columns()
    @          0xd20de05 starrocks::SortedStreamingAggregator::streaming_compute_agg_state()
    @          0xc8b8bfd starrocks::pipeline::SortedAggregateStreamingSinkOperator::push_chunk()
    @          0xc7f7df0 starrocks::pipeline::PipelineDriver::process()
    @          0xc7b7cf9 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0xc7b656e _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE_clEv
    @          0xc7c15b8 _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0xc7c09a9 _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @          0xc7bfaca _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x98b3c56 std::function<>::operator()()
    @          0xa3e27f4 starrocks::FunctionRunnable::run()
    @          0xa3dee3e starrocks::ThreadPool::dispatch_thread()
    @          0xa3fe664 std::__invoke_impl<>()
    @          0xa3fe0f3 std::__invoke<>()
```

1. hook cancel in :
```
diff --git a/be/src/exec/sorted_streaming_aggregator.cpp b/be/src/exec/sorted_streaming_aggregator.cpp
index 3766e70bff..a9905d4c72 100644
--- a/be/src/exec/sorted_streaming_aggregator.cpp
+++ b/be/src/exec/sorted_streaming_aggregator.cpp
@@ -313,6 +313,9 @@ StatusOr<ChunkPtr> SortedStreamingAggregator::streaming_compute_agg_state(size_t
 
     _tmp_agg_states.resize(chunk_size);
     _cmp_vector.resize(chunk_size);
+    if (!_last_columns.empty()) {
+        _state->set_is_cancelled(true);
+    }
 
     if (_last_columns.empty()) {
         _last_columns.resize(_group_by_columns.size());
```

```
select c0, sum(c1), max(c2), count(*), max(c2 + 1), max(c0 +1), max(c0 + 2), max(c0 + 3), array_agg(c1 + 2), array_agg(c1 + 3), array_agg(c1 + 4), array_agg(c1 + 5), array_agg(c1 + 6 order by c1, c2) from t0 group by c0 order by c0;
```

### StarRocks version (Required)
 - b16f9298e8 ASAN (build b16f9298e8)

### PR DESCRIPTION
**Pull request by fzhedu**
Fix https://github.com/StarRocks/starrocks/issues/29400
after cancelled, the following process is wrong as the sort perm is empty. so return if detecting cancelled.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — DISMISSED** [review]

File: be/src/exprs/agg/array_agg.h [hunk 1]
```diff
@@ -226,7 +238,14 @@ class ArrayAggAggregateFunctionV2
             // release order-by columns early
             order_by_columns.clear();
             state_impl.release_order_by_columns();
-            DCHECK(ctx->state()->cancelled_ref() || st.ok());
+            if (UNLIKELY(ctx->state()->cancelled_ref())) {
```
Comment (kangkaisen) [inline be/src/exprs/agg/array_agg.h:241]: I think we shouldn't check the cancel status in aggregate function internal.

Comment (fzhedu) [reply be/src/exprs/agg/array_agg.h:241]: this is effected by L237, as the sort need to know the cancel statues. if do know it in time, the cancel process would be long, instead of stopping as soon as possible.
`Status st = sort_and_tie_columns(ctx->state()->cancelled_ref(), order_by_columns, sort_desc, &perm);`

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by stdpain — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by Gatsby-Lee** [comment]
@wanpengfei-git backport branch-3.2

**Comment by murphyatwork** [comment]
@Mergifyio backport branch-3.2

**Comment by Gatsby-Lee** [comment]
HI @murphyatwork,
I noticed that you closed the created PR due to the merge conflict.
Do you have any places to resolve the merge conflict and backport this PR into branch-3.2?

Thank you
Gatsby
