### PR TITLE
[Enhancement] optimize mv plan cache by using lru cache

### LINKED ISSUE #30316: MV Rewrite failed: rewrite group by a, b to count (distinct b) group by a
### Steps to reproduce the behavior (Required)
```
        starRocksAssert.withTable("CREATE TABLE count_tbl_1 (\n" +
                "k1 int,\n" +
                "k2 int\n" +
                ")\n" +
                "DISTRIBUTED BY HASH(k1)" +
                "PROPERTIES (" +
                "\"replication_num\" = \"1\")\n");

        testRewriteOK("select k1, k2, count(*) from count_tbl_1 group by k1, k2",
                "SELECT count(distinct k1) FROM count_tbl_1 group by k2");
```

### StarRocks version (Required)
main

### PR DESCRIPTION
**Pull request by ABingHuang**
optimize mv plan cache by using lru cache and clear cache item after mv become inactive/dropped.
Fixes #30361

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 81 / 84 (96.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|2|4|50.00%|[2281, 2282]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[235]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MvPlanContext.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvPlanContextBuilder.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

File: fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java [hunk 1]
```diff
@@ -419,6 +420,9 @@ private void updateMeta(Set<String> mvRefreshedPartitions,
                 throw new DmlException(
                         "update meta failed. materialized view:" + materializedView.getName() + " not exist");
             }
+            // invalid mv's plan cache because plan may change
+            CachingMvPlanContextBuilder.getInstance().invalidateFromCache(materializedView);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java:424]: Why invalid this? Only invalid when necccesary, otherwise the cache maybe overhead if the refresh is too quick.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 2]
```diff
@@ -190,6 +189,10 @@ private void prepareRelatedMVs(Set<Table> queryTables, Set<MaterializedView> rel
 
         Set<ColumnRefOperator> originQueryColumns = Sets.newHashSet(queryColumnRefFactory.getColumnRefs());
         for (MaterializedView mv : relatedMvs) {
+            if (!mv.isValidPlan()) {
+                // skip to process unsupported plan tree
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:193]: Log warning?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+
+    }
+
+    public static CachingMvPlanContextBuilder getInstance() {
+        return INSTANCE;
+    }
+
+    public MvPlanContext getPlanContext(MaterializedView mv, boolean useCache) {
+        MvId mvId = new MvId(mv.getDbId(), mv.getId());
+        MvPlanContext result = useCache ? mvPlanContextCache.getIfPresent(mvId) : null;
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:52]: if `useCache ` is false, `null` is returned and the mv cannot be used for rewritten?

**Review by satanson — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+public class CachingMvPlanContextBuilder {
+    private static final CachingMvPlanContextBuilder INSTANCE = new CachingMvPlanContextBuilder();
+
+    private final Executor mvPlanCacheExecutor = Executors.newFixedThreadPool(10,
+            new ThreadFactoryBuilder().setDaemon(true).setNameFormat("mv-plan-cache-refresher-%d").build());
+
+    private Cache<MvId, MvPlanContext> mvPlanContextCache = Caffeine.newBuilder()
+            .expireAfterWrite(Config.mv_plan_cache_expire_interval_sec, TimeUnit.SECONDS)
+            .maximumSize(1000)
+            .executor(mvPlanCacheExecutor)
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:39]: Why not refresh the cache in foreground thread? Why bother the executor

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    }
+
+    public static CachingMvPlanContextBuilder getInstance() {
+        return INSTANCE;
+    }
+
+    public MvPlanContext getPlanContext(MaterializedView mv, boolean useCache) {
+        MvId mvId = new MvId(mv.getDbId(), mv.getId());
+        MvPlanContext result = useCache ? mvPlanContextCache.getIfPresent(mvId) : null;
+        if (result == null) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:53]: Why not use the `LoadingCache`, which could load the cache if missed ? j

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+
+public class CachingMvPlanContextBuilder {
+    private static final CachingMvPlanContextBuilder INSTANCE = new CachingMvPlanContextBuilder();
+
+    private final Executor mvPlanCacheExecutor = Executors.newFixedThreadPool(10,
+            new ThreadFactoryBuilder().setDaemon(true).setNameFormat("mv-plan-cache-refresher-%d").build());
+
+    private Cache<MvId, MvPlanContext> mvPlanContextCache = Caffeine.newBuilder()
+            .expireAfterWrite(Config.mv_plan_cache_expire_interval_sec, TimeUnit.SECONDS)
+            .maximumSize(1000)
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:38]: Should the cache capacity be configurable ? What if user has a lot of mv

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java [hunk 7]
```diff
@@ -0,0 +1,73 @@
...
+import java.util.concurrent.TimeUnit;
+
+public class CachingMvPlanContextBuilder {
+    private static final CachingMvPlanContextBuilder INSTANCE = new CachingMvPlanContextBuilder();
+
+    private final Executor mvPlanCacheExecutor = Executors.newFixedThreadPool(10,
+            new ThreadFactoryBuilder().setDaemon(true).setNameFormat("mv-plan-cache-refresher-%d").build());
+
+    private Cache<MvId, MvPlanContext> mvPlanContextCache = Caffeine.newBuilder()
+            .expireAfterWrite(Config.mv_plan_cache_expire_interval_sec, TimeUnit.SECONDS)
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:37]: How about using the `expireAfterAccess` strategy ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java:53]: I just want to push valid plan into the cache, so I write the loader logical manually.

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java [hunk 8]
```diff
@@ -1173,6 +1175,10 @@ public void setEnableParallelMerge(boolean enableParallelMerge) {
     @VarAttr(name = ENABLE_MATERIALIZED_VIEW_REWRITE_GREEDY_MODE)
     private boolean enableMaterializedViewRewriteGreedyMode = false;
 
+    // whether to use materialized view plan context cache to reduce mv rewrite time cost
+    @VarAttr(name = ENABLE_MATERIALIZED_VIEW_PLAN_CACHE, flag = VariableMgr.INVISIBLE)
+    private boolean enableMaterializedViewPlanCache = true;
```
[the remark this answers is not in the document]
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:1180]: I prefer to use SessionVariable here, because although Mv plan cache is global, but you can decide to whether to use cache in every session.

**Review by LiShuMing — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 80 / 81 (98.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[235]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MvPlanContext.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java|20|20|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvPlanContextBuilder.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 80 / 81 (98.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[235]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MvPlanContext.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java|20|20|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvPlanContextBuilder.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 80 / 81 (98.77%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|12|13|92.31%|[235]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/MvPlanContext.java|16|16|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/CachingMvPlanContextBuilder.java|20|20|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvPlanContextBuilder.java|10|10|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MaterializedViewOptimizer.java|3|3|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
