### PR TITLE
[Enhancement] Improve IcebergRESTCatalog's the error handling for

### LINKED ISSUE #56513: Improve the error handling for IcebergRESTCatalog
## Enhancement

Currently, it's challenging to diagnose errors that occur during IcebergRESTCatalog operations. The REST Catalog throws a `RESTException`, but this is not being properly handled in the IcebergRESTCatalog. This pull request aims to enhance error management by associating specific error codes and messages with relevant operations.

### PR DESCRIPTION
**Pull request by osscm**
## Why I'm doing:
This change will improve the `IcebergRESTCatalog`'s exception handling. So, that the user can see a proper message and error code based on the operation. Currently it also depends on the server side message, that can be mis-leading.

## What I'm doing:

Fixes #56513

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+// limitations under the License.
+
+package com.starrocks.catalog.exception;
+
+import com.starrocks.common.InternalErrorCode;
+
+/**
+ * Exception for meta info is null, like db table partition tablet replica job
+ */
+public class CatalogException extends RuntimeException {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java:22]: We alreay have `StarRocksConnectorException`, I think you could reuse this exception

File: fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java [hunk 2]
```diff
@@ -38,7 +38,9 @@ public enum InternalErrorCode {
     TOO_MANY_FAILURE_ROWS_ERR(102),
     CREATE_TASKS_ERR(103),
     TASKS_ABORT_ERR(104),
-    SLOW_RUNNING_ERR(105);
+    SLOW_RUNNING_ERR(105),
+    ICEBERG_CATALOG_ERROR(106),
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java:42]: If use StarRocksConnectorException, there is no need to use error code, the error message is enough?

**Comment by Youngwb** [comment]
@osscm  There is a FE UT you need to fix 
image

File: fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java (hunk 1 above)
Comment (osscm) [reply fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java:22]: I thought `CatalogException` is required as it is Catalog exception, `StarRocksConnectorException` represents a connector level exception, which is much wider.
WDYT?

Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java:22]: I think using  StarRocksConnectorException   is sufficient. We have already thrown  StarRocksConnectorException   in many other places. Changing it to   CatalogException  might involve additional modifications.

File: fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java (hunk 2 above)
Comment (osscm) [reply fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java]: modified it.

File: fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java (hunk 1 above)
Comment (osscm) [reply fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java:22]: I modified it to use `StarRocksConnectorException`

**Comment by osscm** [comment]
> @osscm There is a FE UT you need to fix image

fixed this test-case.

File: fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java [hunk 3]
```diff
@@ -38,7 +38,8 @@ public enum InternalErrorCode {
     TOO_MANY_FAILURE_ROWS_ERR(102),
     CREATE_TASKS_ERR(103),
     TASKS_ABORT_ERR(104),
-    SLOW_RUNNING_ERR(105);
+    SLOW_RUNNING_ERR(105),
+    ICEBERG_CATALOG_ERROR(106);
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/common/InternalErrorCode.java:42]: This is useless

File: fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java (hunk 1 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/catalog/exception/CatalogException.java:22]: You can just delete this file

File: fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java [hunk 4]
```diff
@@ -91,13 +93,19 @@ public IcebergRESTCatalog(String name, Configuration conf, Map<String, String> p
...
         OAuth2SecurityConfig securityConfig = OAuth2SecurityConfigBuilder.build(copiedProperties);
         OAuth2SecurityProperties securityProperties = new OAuth2SecurityProperties(securityConfig);
         copiedProperties.putAll(securityProperties.get());
 
-        delegate = (RESTCatalog) CatalogUtil.loadCatalog(RESTCatalog.class.getName(), name, copiedProperties, conf);
+        try {
+            delegate = (RESTCatalog) CatalogUtil.loadCatalog(RESTCatalog.class.getName(), name, copiedProperties, conf);
+        } catch (Exception re) {
+            LOG.error("Failed to rest load catalog", re);
+            throw new StarRocksConnectorException("Failed to rest load catalog",
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java:105]:
```suggestion
            throw new StarRocksConnectorException("Failed to load rest catalog",
```

File: fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java [hunk 5]
```diff
@@ -168,31 +200,59 @@ public void dropDB(String dbName) throws MetaNotFoundException {
...
     @Override
     public List<String> listTables(String dbName) {
         Namespace ns = convertDbNameToNamespace(dbName);
-        List<TableIdentifier> tableIdentifiers = new ArrayList<>(delegate.listTables(ns));
+        List<TableIdentifier> tableIdentifiers = null;
+        try {
+            tableIdentifiers = delegate.listTables(ns);
+        } catch (RESTException re) {
+            LOG.error("Failed to list tables using REST Catalog, for dbName {}", dbName, re);
+            // creating a new RuntimeException with the custom message, as in the upstream code, it picks the `exception.getCause().getMessage()`
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java:232]: Could we throw exception like this :
```
throw new StarRocksConnectorException("Failed to list tables using REST Catalog, exception:" 
+ re.getMessage(), re);
```

**Comment by Youngwb** [comment]
@osscm could you please add some UT to cover your code, Fe Cover Checker need 80% at least

File: fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java (hunk 5 above)
Comment (osscm) [reply fe/fe-core/src/main/java/com/starrocks/connector/iceberg/rest/IcebergRESTCatalog.java:232]: @Youngwb problem is when it is printed on the mysql cli (JDBC client) it print the `re.getMessage()` and not the `"Failed to list tables using REST Catalog, exception:" ` of the `StarRocksConnectorException` therefore have to add the custom message in the parent exception.

**Review by Youngwb — APPROVED** [review]

**Comment by Youngwb** [comment]
@mergify backport branch-3.5

**Comment by Youngwb** [comment]
@osscm thanks for your contribution
