### PR TITLE
[Enhancement] Support complex type in column with row

### LINKED ISSUE #38174: [column_with_row] pk table with bigmap column stream load failed: row encode type not supported: OBJECT
### Steps to reproduce the behavior (Required)
```
CREATE TABLE pk_bitmap (
                    `k1`  boolean,
                    `k2`  tinyint,
                    `k3`  smallint,
                    `k4`  int,
                    `k5`  bigint,
                    `v1`  bitmap,
                    `v2`  bitmap,
                    `v3`  bitmap,
                    `v4`  bitmap,
                    `v5`  bitmap
                )
                primary key(k1, k2, k3)
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
                PROPERTIES (
                    "replication_num" = "3",
                    "storage_format" = "v2",
                    "storage_type" = "column_with_row"
                );
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest//common/data/bitmap_type_data -XPUT -H label:stream_load_1703851708416_QlN -H columns:k1,k2,k3,k4,k5,v1=to_bitmap(k1),v2=to_bitmap(k2),v3=to_bitmap(k3),v4=to_bitmap(k4),v5=to_bitmap(k5) http://172.26.81.31:8030/api/pk_col_with_row_f9cc7a90_a642_11ee_8cc7_00163e0e550b/pk_bitmap/_stream_load
CompletedProcess(args=['curl', '--location-trusted', '-u', 'root:', '-T', '/home/disk5/tiannan/sr_cases/StarRocksTest//common/data/bitmap_type_data', '-XPUT', '-H', 'label:stream_load_1703851708416_QlN', '-H', 'columns:k1,k2,k3,k4,k5,v1=to_bitmap(k1),v2=to_bitmap(k2),v3=to_bitmap(k3),v4=to_bitmap(k4),v5=to_bitmap(k5)', 'http://172.26.81.31:8030/api/pk_col_with_row_f9cc7a90_a642_11ee_8cc7_00163e0e550b/pk_bitmap/_stream_load'], returncode=0, stdout='{\n    "TxnId": 42,\n    "Label": "stream_load_1703851708416_QlN",\n    "Status": "Fail",\n    "Message": "172.26.81.34: row encode type not supported: OBJECT ",\n    "NumberTotalRows": 0,\n    "NumberLoadedRows": 0,\n    "NumberFilteredRows": 0,\n    "NumberUnselectedRows": 0,\n    "LoadBytes": 2740174,\n    "LoadTimeMs": 110,\n    "BeginTxnTimeMs": 0,\n    "StreamLoadPlanTimeMs": 5,\n    "ReadDataTimeMs": 0,\n    "WriteDataTimeMs": 104,\n    "CommitAndPublishTimeMs": 0,\n    "ErrorURL": "http://172.26.81.32:8040/api/_load_error_log?file=error_log_e848c9f2a674b46b_675ce0f7fc72789b"\n}', stderr='  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\n  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n  0 2675k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\n\n100 2676k  100   575  100 2675k   4542  20.6M --:--:-- --:--:-- --:--:-- 20.6M\n')
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+--------------------+
| current_version()  |
+--------------------+
| branch-3.2-53f8343 |
+--------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by decster**
## Why I'm doing:

Currently, column with row storage type does not support complex types like bitmap, array, struct, bitmap

## What I'm doing:

Support those types

Fixes #38174 #38090

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Seaven — APPROVED** [review]

File: be/src/column/object_column.h [hunk 1]
```diff
@@ -122,6 +123,8 @@ class ObjectColumn : public ColumnFactory<Column, ObjectColumn<T>> {
 
     const uint8_t* deserialize_and_append(const uint8_t* pos) override;
 
+    bool deserialize_and_append(const Slice& src);
```
Comment (Seaven) [inline be/src/column/object_column.h:126]: JsonColumn is extend ObjectColumn, need implement the method?

Comment (decster) [reply be/src/column/object_column.h:126]: jsonColumn already have old deserialize_and_append implemented and follows the old convention, so no need to implement this.

**Review by wyb — APPROVED** [review]
