### PR TITLE
[BugFix] Data lost when resume failed routine load

### LINKED ISSUE #7849: Data lost when resume failed routine load
When the routine load is executed with json root, the job would be paused due to the specific json root accessing failure.
But, if we resume the paused routine load job, some valid data would be lost.
 
### Steps to reproduce the behavior (Required)
1. Create table
```
CREATE TABLE `tbl_test_resume` (
  `key1` int(11) NULL COMMENT "",
  `key2` int(11) NULL COMMENT ""
) ENGINE=OLAP 
DUPLICATE KEY(`key1`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`key1`) BUCKETS 3 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
); 
```
2. Prepare some test data in kafka
```
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": null}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}
{"data": [{"key1": 1, "key2": 2}]}

```
3. Create routine load
```
CREATE ROUTINE LOAD rl_test_resume ON tbl_test_resume COLUMNS (key1, key2) PROPERTIES ( "format" = "json", "strip_outer_array"="true", "json_root"="$.data" ) FROM KAFKA ( "kafka_broker_list" = "xxx", "kafka_topic" = "topic_test_resume", "kafka_partitions" = "0", "kafka_offsets" = "0" ); 

```
### Expected behavior (Required)
All valid data is consumed.
### Real behavior (Required)
```
Only part of valid data is inserted, the other would not be inserted.
```
### StarRocks version (Required)
2.0.7

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7849 

## Problem Summary(Required) ：

The previous implement would pause the routine load if the job gets error, but the progress is promoted as usual. Only part of the valid data in the failed batch would be inserted.

This PR changes the behavior as following: 
1. The routine load would be paused with abort transaction, so the progress of routine load would not be promoted.
1. Only routine load gets `Unrecoverable error` would be paused.
1. To make it easier to inspect the job failure, the routine load job error message would be put into `ErrorLogUrls`
```
                  Id: 10063
                Name: rl_test_resume
          CreateTime: 2022-07-04 22:46:48
           PauseTime: 2022-07-05 11:06:36
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_test_resume
               State: PAUSED
      DataSourceType: KAFKA
      CurrentTaskNum: 0
       JobProperties: {"partitions":"*","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"$.data","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"true","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic_test_resume","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":0,"errorRows":0,"committedTaskNum":0,"loadedRows":0,"loadRowsRate":0,"abortedTaskNum":15,"totalRows":0,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":1}
            Progress: {"0":"29"}
ReasonOfStateChanged: ErrorReason{errCode = 104, msg='be 10003 abort task with reason: UNRECOVERABLE_ERROR: JSON data is not an arrayobject, strip_outer_array must be set false'}
        ErrorLogUrls: http://172.26.92.139:8082/api/_load_error_log?file=__shard_11/error_log_insert_stmt_2c64bac2-3edc-432b-97ec-531baca80948_2c64bac23edc432b_97ec531baca80948, http://172.26.92.139:8082/api/_load_error_log?file=__shard_12/error_log_insert_stmt_7cb7a327-e587-43bf-a8b7-e28c75c1718a_7cb7a327e58743bf_a8b7e28c75c1718a
            OtherMsg:

```

### CODE REVIEW

**Comment by rickif** [comment]
run starrocks_clang-format

File: be/src/exec/vectorized/json_scanner.cpp [hunk 1]
```diff
@@ -79,6 +79,14 @@ StatusOr<ChunkPtr> JsonScanner::get_next() {
         _cur_file_eof = true;
```
Comment (trueeyu) [inline be/src/exec/vectorized/json_scanner.cpp:79]: remove the `if` ?

**Review by trueeyu — DISMISSED** [review]

**Review by meegoo — DISMISSED** [review]

File: be/src/exec/vectorized/json_scanner.cpp [hunk 2]
```diff
@@ -75,8 +75,12 @@ StatusOr<ChunkPtr> JsonScanner::get_next() {
         _cur_file_eof = false;
     }
     Status status = _cur_file_reader->read_chunk(src_chunk.get(), _max_chunk_size, _src_slot_descriptors);
-    if (status.is_end_of_file()) {
-        _cur_file_eof = true;
+    if (!status.ok()) {
+        if (status.is_end_of_file()) {
+            _cur_file_eof = true;
+        } else {
+            return status;
```
Comment (chaoyli) [inline be/src/exec/vectorized/json_scanner.cpp:82]: If the status is an error, will it not be paused?

Comment (rickif) [reply be/src/exec/vectorized/json_scanner.cpp:82]: No. The job would be aborted and retry later.

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by rickif** [comment]
run all

**Review by chaoyli — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java [hunk 3]
```diff
@@ -121,6 +121,9 @@ public static TxnStatusChangeReason fromString(String reasonString) {
                 if (reasonString.contains(txnStatusChangeReason.toString())) {
                     return txnStatusChangeReason;
                 }
+                if (reasonString.contains("Unrecoverable error: ")) {
```
[the remark this answers is not in the document]
Comment (rickif) [reply fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java]: https://github.com/rickif/starrocks/blob/f6738f3b1555931df1a51245a487599716238c3f/fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java#L114
The `TStatusCode` may be not OK here, since the code info is removed in BE. So I add a enum here.

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_be_unittest

File: fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java [hunk 4]
```diff
@@ -110,13 +110,19 @@ public enum TxnStatusChangeReason {
...
+        NO_PARTITIONS,
+        UNRECOVERABLE_ERROR;
 
         public static TxnStatusChangeReason fromString(String reasonString) {
             if (Strings.isNullOrEmpty(reasonString)) {
                 return null;
             }
 
+            // Pause on unrecoverable error.
+            if (reasonString.contains(UNRECOVERABLE_ERROR.toString())) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java:122]: Add StatusCode in TLoadTxnRollbackRequest to pause it.

File: gensrc/thrift/Status.thrift [hunk 5]
```diff
@@ -82,7 +82,10 @@ enum TStatusCode {
     DUPLICATE_RPC_INVOCATION        = 47,
     GLOBAL_DICT_ERROR = 48,
 
-    UNKNOWN = 50
+   UNKNOWN = 50,
```
Comment (chaoyli) [inline gensrc/thrift/Status.thrift:85]: The ident is not aligned.

File: fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java [hunk 6]
```diff
@@ -117,6 +118,11 @@ public static TxnStatusChangeReason fromString(String reasonString) {
                 return null;
             }
 
+            // Pause on unrecoverable error.
+            if (reasonString.contains(TStatusCode.UNRECOVERABLE_ERROR.toString())) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java:122]: Must to convert to string to be compared?

File: gensrc/thrift/StatusCode.thrift [hunk 7]
```diff
@@ -82,6 +82,9 @@ enum TStatusCode {
     DUPLICATE_RPC_INVOCATION        = 47,
     GLOBAL_DICT_ERROR = 48,
 
-    UNKNOWN = 50
+    UNKNOWN = 50,
+
+   // To be compatible with newer version,  we skip code 51/52
+   UNRECOVERABLE_ERROR = 53
```
Comment (chaoyli) [inline gensrc/thrift/StatusCode.thrift:88]: The ident is not aligned

File: fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java (hunk 6 above)
Comment (rickif) [reply fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java:122]: Otherwise, the signature of `abortTransaction` would be changed, which may brings many modifications.

**Review by chaoyli — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]
