### PR TITLE
BugFix: Fix Be crash while doing schema change

### LINKED ISSUE #1296: Be crash while doing schemachange
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `customer5` (
  `c_custkey` int(11) NOT NULL COMMENT "",
  `c_name` varchar(26) NOT NULL COMMENT "",
  `c_address` varchar(41) NOT NULL COMMENT "",
  `c_city` varchar(11) NOT NULL COMMENT "",
  `c_nation` varchar(16) NOT NULL COMMENT "",
  `c_region` varchar(13) NOT NULL COMMENT "",
  `c_phone` varchar(16) NOT NULL COMMENT "",
  `c_mktsegment` varchar(11) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c_custkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`c_custkey`) BUCKETS 120
PROPERTIES (
"replication_num" = "3",
"colocate_with" = "groupa2",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
mysql> alter table customer5 modify column c_mktsegment varchar(15);
Query OK, 0 rows affected (0.23 sec)```


### Expected behavior (Required)
schema change success

### Real behavior (Required)
`*** Aborted at 1636978918 (unix time) try "date -d @1636978918" if you are using GNU date ***
PC: @     0x7f48abf6ac19 __memcpy_ssse3_back
*** SIGSEGV (@0x1a35) received by PID 22174 (TID 0x7f4843130700) from PID 6709; stack trace: ***
    @          0x341e902 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f48acb17630 (unknown)
    @     0x7f48abf6ac19 __memcpy_ssse3_back
    @          0x2bed0db starrocks::segment_v2::ScalarColumnWriter::append()
    @          0x2beebc3 starrocks::segment_v2::StringColumnWriter::finish()
    @          0x2b5599e starrocks::segment_v2::SegmentWriter::finalize()
    @          0x1aa5c42 starrocks::BetaRowsetWriter::_flush_segment_writer()
    @          0x2ba0874 starrocks::vectorized::SchemaChangeDirectly::process()
    @          0x2ba3d4a starrocks::vectorized::SchemaChangeHandler::_convert_historical_rowsets()
    @          0x2ba727e starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2_normal()
    @          0x2ba892f starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2()
    @          0x2ba921a starrocks::vectorized::SchemaChangeHandler::process_alter_tablet_v2()
    @          0x2b83d47 starrocks::EngineAlterTabletTask::execute()
    @          0x16d7e5a starrocks::StorageEngine::execute_task()
    @          0x1f2fc5b starrocks::TaskWorkerPool::_alter_tablet()
    @          0x1f331f4 starrocks::TaskWorkerPool::_alter_tablet_worker_thread_callback()
    @          0x4cf6440 execute_native_thread_routine
    @     0x7f48acb0fea5 start_thread
    @     0x7f48abf149fd __clone
    @                0x0 (unknown)
Waiting for data... (interrupt to abort)`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------- --+
| current_version()          |
+-----------------------+
| UNKNOWN 6e2dca90  |
+-----------------------+
1 row in set (0.18 sec)

### PR DESCRIPTION
**Pull request by sevev**
Add a check for consistency between the nullable of the new column and the old column when doing schema_change
If nullable is inconsistent, new column can not be assigned as old column directly
close https://github.com/StarRocks/starrocks/issues/1296

### CODE REVIEW

File: be/src/storage/vectorized/schema_change.cpp [hunk 1]
```diff
@@ -336,7 +336,7 @@ bool ChunkChanger::change_chunk(ChunkPtr& base_chunk, ChunkPtr& new_chunk, Table
 
             if (new_type == ref_type && (!is_decimalv3_field_type(new_type) ||
                                          (reftype_precision == newtype_precision && reftype_scale == newtype_scale))) {
-                if (new_type == OLAP_FIELD_TYPE_CHAR) {
+                if (new_type == OLAP_FIELD_TYPE_CHAR || (new_col->is_nullable() ^ base_col->is_nullable())) {
```
Comment (imay) [inline be/src/storage/vectorized/schema_change.cpp:339]: I think (new_col->is_nullable() != base_col->is_nullable()) is more straight.

Comment (sevev) [reply be/src/storage/vectorized/schema_change.cpp]: > I think (new_col->is_nullable() != base_col->is_nullable()) is more straight.

Seems you are right, fix in https://github.com/StarRocks/starrocks/pull/1297/commits/b5e98d83d5c855a761b1f95fffcafcccf23301c9

File: be/src/storage/vectorized/schema_change.cpp [hunk 2]
```diff
@@ -336,7 +336,7 @@ bool ChunkChanger::change_chunk(ChunkPtr& base_chunk, ChunkPtr& new_chunk, Table
 
             if (new_type == ref_type && (!is_decimalv3_field_type(new_type) ||
                                          (reftype_precision == newtype_precision && reftype_scale == newtype_scale))) {
-                if (new_type == OLAP_FIELD_TYPE_CHAR) {
+                if (new_type == OLAP_FIELD_TYPE_CHAR || (new_col->is_nullable() != base_col->is_nullable())) {
```
Comment (Linkerist) [inline be/src/storage/vectorized/schema_change.cpp:339]: The parenthese is redundant, because the c++ operator precedence is obvious, it is is unnecessary to writing it out explicitly. It can be removed to improve readability

**Comment by trueeyu** [comment]
please add test case

File: be/src/storage/vectorized/schema_change.cpp [hunk 3]
```diff
@@ -336,7 +336,7 @@ bool ChunkChanger::change_chunk(ChunkPtr& base_chunk, ChunkPtr& new_chunk, Table
...
                     for (size_t row_index = 0; row_index < base_chunk->num_rows(); ++row_index) {
```
Comment (trueeyu) [inline be/src/storage/vectorized/schema_change.cpp:340]: Can append_column achieve this function?

Comment (trueeyu) [reply be/src/storage/vectorized/schema_change.cpp:340]: check thre return ptr of  slice.data = reinterpret_cast<char*>(mem_pool->allocate(slice.size));

**Comment by trueeyu** [comment]
https://github.com/StarRocks/starrocks/blob/b5e98d83d5c855a761b1f95fffcafcccf23301c9/be/src/storage/vectorized/schema_change.cpp#L340

Can append_column achieve this function?

**Comment by trueeyu** [comment]
https://github.com/StarRocks/starrocks/blob/b5e98d83d5c855a761b1f95fffcafcccf23301c9/be/src/storage/vectorized/schema_change.cpp#L352
check thre return ptr of slice.data = reinterpret_cast<char*>(mem_pool->allocate(slice.size));

**Comment by sevev** [comment]
> https://github.com/StarRocks/starrocks/blob/b5e98d83d5c855a761b1f95fffcafcccf23301c9/be/src/storage/vectorized/schema_change.cpp#L352
> 
> 
> check thre return ptr of slice.data = reinterpret_cast<char*>(mem_pool->allocate(slice.size));

fix in https://github.com/StarRocks/starrocks/pull/1297/commits/fb63cfe122c9c9e9e0f17da6c108800515589c60

**Comment by sevev** [comment]
> https://github.com/StarRocks/starrocks/blob/b5e98d83d5c855a761b1f95fffcafcccf23301c9/be/src/storage/vectorized/schema_change.cpp#L340
> 
> Can append_column achieve this function?

if column type is `OLAP_FIELD_TYPE_CHAR`, the size of slice should be reset to length of new column, otherwise `append_column` can replace `append_datum`. PTAL https://github.com/StarRocks/starrocks/commit/fb63cfe122c9c9e9e0f17da6c108800515589c60

**Review by trueeyu — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]
