### PR TITLE
[Enhancement] Using lru cache to limit the number of starlet filesystem instance

### LINKED ISSUE #55765: [shared-data] create table failed with hdfs storage volume
【详述】把2x集群的表，在3x（hfds存算分离）重建一遍，开始是OK的，建了几个小时后，fe报错Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unexpected exception: Failed to get primary backend. shard id: 344953
其中一个cn，cpu打高一直gc。

【是否存算分离】是
【StarRocks版本】例如：3.2.12
【集群规模】例如：1fe +3cn
【机器信息】16c 60g
cpu高cn的stack，jmap统计，线程top cpu信息见：
https://forum.mirrorship.cn/t/topic/17333

### PR DESCRIPTION
**Pull request by xiangguangyxg**
## Why I'm doing:
When there are too many partitions, the starlet filesystem instances also has a lot, this may take too many memory. 

## What I'm doing:
Using lru cache to limit the number of starlet filesystem instance.
Add be config starlet_filesystem_instance_cache_capacity to config the lru cache capacity, default 10000.

Fixes https://github.com/StarRocks/starrocks/issues/55765

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by kevincai — COMMENTED** [review]
Could have a different issue after current implementation. e.g. A few of the shards/tablets deleted, the filesystem will never be used again. However if the LRU cache still has plenty of slots, the filesystem instance in the cache will not be evicted at all which in turns causes the related objects are not released unless a service restart.

**Comment by xiangguangyxg** [comment]
> Could have a different issue after current implementation. e.g. A few of the shards/tablets deleted, the filesystem will never be used again. However if the LRU cache still has plenty of slots, the filesystem instance in the cache will not be evicted at all which in turns causes the related objects are not released unless a service restart.

@kevincai Yes it has the issue. Once a cache slot used, It will not be released actively, but will be evicted passively. That is a bit like the starcache.

**Comment by kevincai** [comment]
> > Could have a different issue after current implementation. e.g. A few of the shards/tablets deleted, the filesystem will never be used again. However if the LRU cache still has plenty of slots, the filesystem instance in the cache will not be evicted at all which in turns causes the related objects are not released unless a service restart.
> 
> @kevincai Yes it has the issue. Once a cache slot is used, It will not be released actively, but will be evicted passively. That is a bit like the starcache.

sounds like a LRU with auto expiration perfectly match the use scenario.

File: be/src/common/config.h [hunk 1]
```diff
@@ -1050,6 +1050,7 @@ CONF_mInt32(starlet_fslib_s3client_connect_timeout_ms, "1000");
 // NOTE: need to handle the negative value properly
 CONF_Alias(object_storage_request_timeout_ms, starlet_fslib_s3client_request_timeout_ms);
 CONF_mInt32(starlet_delete_files_max_key_in_batch, "1000");
+CONF_Int32(starlet_filesystem_max_cache_size, "10000");
```
[the remark this answers is not in the document]
Comment (xiangguangyxg) [reply be/src/common/config.h]: done

File: be/src/http/action/update_config_action.cpp [hunk 2]
```diff
@@ -368,6 +368,13 @@ Status UpdateConfigAction::update_config(const std::string& name, const std::str
         UPDATE_STARLET_CONFIG(s3_use_list_objects_v1, fslib_s3client_use_list_objects_v1);
         UPDATE_STARLET_CONFIG(starlet_delete_files_max_key_in_batch, delete_files_max_key_in_batch);
 #undef UPDATE_STARLET_CONFIG
+
+        _config_callback.emplace("starlet_filesystem_instance_cache_capacity", [&]() -> Status {
+            LOG(INFO) << "set starlet_filesystem_instance_cache_capacity:"
+                      << config::starlet_filesystem_instance_cache_capacity;
+            g_worker->set_fs_cache_capacity(config::starlet_filesystem_instance_cache_capacity);
```
Comment (kevincai) [inline be/src/http/action/update_config_action.cpp:375]: if g_worker is nullptr, just ignore the setting or return non-OK.

File: be/src/service/staros_worker.cpp [hunk 3]
```diff
@@ -203,8 +208,12 @@ absl::StatusOr<std::shared_ptr<fslib::FileSystem>> StarOSWorker::get_shard_files
             l.unlock();
             return build_filesystem_on_demand(id, conf);
         }
-        if (it->second.fs) {
-            return it->second.fs;
+        const auto& fs_cache_key = it->second.fs_cache_key;
+        if (!fs_cache_key.empty()) {
+            auto fs = lookup_fs_cache(fs_cache_key);
```
Comment (kevincai) [inline be/src/service/staros_worker.cpp:213]: if the lookup_fs_cache() can return nullptr anyway, wondering if this cache_key empty check can be moved into lookup_fs_cache().

**Review by kevincai — COMMENTED** [review]
do we want to get the LRU with expiration done in this PR or do it later?

File: be/src/http/action/update_config_action.cpp (hunk 2 above)
Comment (xiangguangyxg) [reply be/src/http/action/update_config_action.cpp]: done

File: be/src/service/staros_worker.cpp (hunk 3 above)
Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp]: done

**Comment by xiangguangyxg** [comment]
> do we want to get the LRU with expiration done in this PR or do it later?

Do it later. Let me think of a way

**Review by kevincai — DISMISSED** [review]

**Comment by kevincai** [comment]
think about add unit test to ensure this new behavior via syncpoint or failpoint to mockup underlying new_filesystem(). check the correctness of the caching and lru eviction.

**Review by wyb — DISMISSED** [review]

**Comment by xiangguangyxg** [comment]
> think about add unit test to ensure this new behavior via syncpoint or failpoint to mockup underlying new_filesystem(). check the correctness of the caching and lru eviction.

Added active cache deletion and unit test.

File: be/src/service/staros_worker.cpp [hunk 4]
```diff
@@ -260,11 +269,15 @@ absl::StatusOr<std::shared_ptr<fslib::FileSystem>> StarOSWorker::build_filesyste
     if (!info_or.ok()) {
         return info_or.status();
     }
-    return build_filesystem_from_shard_info(info_or.value(), conf);
+    auto fs_or = build_filesystem_from_shard_info(info_or.value(), conf);
+    if (!fs_or.ok()) {
+        return fs_or.status();
+    }
+    return fs_or->second;
```
Comment (kevincai) [inline be/src/service/staros_worker.cpp:276]: the cache key shared_ptr is not held by anyone, so after this function call returned, the shared_ptr cache key will be expired, and the fs instance will be removed from the cache immediately. This is the expected behavior, right? Better add comments here to make this behavior explicit.

File: be/src/service/staros_worker.cpp [hunk 5]
```diff
@@ -367,6 +368,66 @@ std::string StarOSWorker::get_cache_key(std::string_view scheme, const Configura
...
+        return nullptr;
+    }
+
+    return value_or->second;
+}
+
+absl::StatusOr<std::pair<std::shared_ptr<std::string>, std::shared_ptr<fslib::FileSystem>>> StarOSWorker::find_fs_cache(
+        const std::string& key) {
+    if (key.empty()) {
+        return absl::NotFoundError(key + " not found");
```
Comment (kevincai) [inline be/src/service/staros_worker.cpp:416]: this will yield an `" not found"` message, which is odd. make the error message more accurate.

File: be/src/service/staros_worker.cpp [hunk 6]
```diff
@@ -367,6 +368,66 @@ std::string StarOSWorker::get_cache_key(std::string_view scheme, const Configura
...
+    CacheKey cache_key(key);
+    auto handle = _fs_cache->lookup(cache_key);
+    if (handle == nullptr) {
+        return absl::NotFoundError(key + " not found");
+    }
+
+    auto value = static_cast<CacheValue*>(_fs_cache->value(handle));
+    _fs_cache->release(handle);
+
+    return std::make_pair(value->key.lock(), value->fs);
```
Comment (kevincai) [inline be/src/service/staros_worker.cpp:428]: what if the `value->key` is expired? the value->key.lock() will return an empty shared_ptr.

File: be/src/service/staros_worker.cpp (hunk 4 above)
Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp:276]: Yes, if not hit the fs cache, the new fs instance will be removed from the cache immediately.

File: be/src/service/staros_worker.cpp (hunk 6 above)
Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp:428]: this behavior is ok ? do you mean an error status should be returned in this situation ?

Comment (kevincai) [reply be/src/service/staros_worker.cpp:428]: it will be ok, but then the caller will get a shared_ptr of the empty string. Shall reset the value->key or reset the value item with a valid item there?

Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp]: the caller will get an empty key shared_ptr and a valid fs instance in this situation. It means the cache item is about to be removed but it is not yet removed by other thread. If we reset the value->key,  It will also be removed by other thread.

Comment (kevincai) [reply be/src/service/staros_worker.cpp]: so what should do? take it as cache miss and rebuild the fs?

Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp]: the current code is like taking it as cache miss but reuse the fs instance.

Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp]: add some comments to explain this situation.

File: be/src/service/staros_worker.cpp (hunk 4 above)
Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp:278]: added comments.

File: be/src/service/staros_worker.cpp (hunk 5 above)
Comment (xiangguangyxg) [reply be/src/service/staros_worker.cpp]: updated

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]
