### PR TITLE
[BugFix] Fix shortcut compaction when only has one delete version

### LINKED ISSUE #24056: ASAN crash since shortcut compaction on delete rowset
### Steps to reproduce the behavior (Required)
*** SIGABRT (@0x3e800002579) received by PID 9593 (TID 0x7fabf4573700) from PID 9593; stack trace: ***
    @         0x13892112 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fad58230630 (unknown)
    @     0x7fad5777b387 __GI_raise
    @     0x7fad5777ca78 __GI_abort
    @          0x9981305 starrocks::failure_function()
    @         0x13885aed google::LogMessage::Fail()
    @         0x13887f5f google::LogMessage::SendToLog()
    @         0x1388563e google::LogMessage::Flush()
    @         0x13888569 google::LogMessageFatal::~LogMessageFatal()
    @          0xf0a0050 starrocks::TabletMeta::remove_delete_predicate_by_version()
    @          0xf09ec65 starrocks::TabletMeta::modify_rs_metas()
    @          0xeff50ec starrocks::Tablet::modify_rowsets()
    @         0x10ce5cbf starrocks::CompactionTask::_commit_compaction()
    @         0x10cdf937 starrocks::HorizontalCompactionTask::run_impl()
    @         0x10cd8680 starrocks::CompactionTask::run()
    @          0xf3e8dd8 starrocks::BackgroundTask::start()
    @          0xf64e581 _ZZN9starrocks17CompactionManager9_scheduleEvENKUlvE_clEv
    @          0xf658690 _ZSt13__invoke_implIvRZN9starrocks17CompactionManager9_scheduleEvEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0xf65827c _ZSt10__invoke_rIvRZN9starrocks17CompactionManager9_scheduleEvEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES5_E4typeEOS6_DpOS7_
    @          0xf657ce0 _ZNSt17_Function_handlerIFvvEZN9starrocks17CompactionManager9_scheduleEvEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x9889b44 std::function<>::operator()()
    @         0x113a9d8c starrocks::FunctionRunnable::run()
    @         0x113a6b41 starrocks::ThreadPool::dispatch_thread()
    @         0x113c279a std::__invoke_impl<>()
    @         0x113c20f3 std::__invoke<>()
    @         0x113c14ea _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @         0x113bfe4c std::_Bind<>::operator()<>()
    @         0x113bceb0 std::__invoke_impl<>()
    @         0x113ba814 _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @         0x113b687d std::_Function_handler<>::_M_invoke()
    @          0x9889b44 std::function<>::operator()()
    @         0x1138e8fd starrocks::Thread::supervise_thread()

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
Fixes #24056

### CODE REVIEW

File: be/src/storage/size_tiered_compaction_policy.cpp [hunk 1]
```diff
@@ -301,10 +320,10 @@ Status SizeTieredCompactionPolicy::_pick_rowsets_to_size_tiered_compact(bool for
         }
     }
 
-    // Cumulative compaction will process with at least 1 rowset.
-    // So when there is no rowset being chosen, we should return Status::NotFound("cumulative compaction no suitable version error.");
+    // compaction will process with at least 1 rowset.
+    // So when there is no rowset being chosen, we should return Status::NotFound("compaction no suitable version error.");
     if (input_rowsets->empty()) {
-        return Status::NotFound("cumulative compaction no suitable version error.");
+        return Status::NotFound("compaction no suitable version error.");
```
Comment (chaoyli) [inline be/src/storage/size_tiered_compaction_policy.cpp:326]: It's better to add tablet_id in the error for better tracing.

**Review by chaoyli — APPROVED** [review]

**Review by wyb — APPROVED** [review]
