### PR TITLE
Fix missing invoking buffered brpc closure

### LINKED ISSUE #2929: TPCDS-Q37 execution blocked
### Steps to reproduce the behavior (Required)

1. enable_pipeline_engine=true
2. pipeline_dop=32(half of the cores)
3. test set: tpcds, scale factor=100

Query-37

```sql
select  i_item_id
       ,i_item_desc
       ,i_current_price
 from item, inventory, date_dim, catalog_sales
 where i_current_price between 68 and 68 + 30
 and inv_item_sk = i_item_sk
 and d_date_sk=inv_date_sk
 and d_date between cast('2000-02-01' as date) and date_add(cast('2000-02-01' as date),  60)
 and i_manufact_id in (677,940,694,808)
 and inv_quantity_on_hand between 100 and 500
 and cs_item_sk = i_item_sk
 group by i_item_id,i_item_desc,i_current_price
 order by i_item_id
 limit 100;
```

### Expected behavior (Required)

return result

### Real behavior (Required)

blocked

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`62791fbb`

### PR DESCRIPTION
**Pull request by liuyehcf**
# Root cause

For [#2929](https://github.com/StarRocks/starrocks/issues/2929)

`exchange_source_operator` has multiple instances, with one part of them receiving data normally, and the other part is short-circuited in advance. We need to make sure about the following two things: 

1. Buffer closure properly
2. Invoke buffered closure exactly once in any case

See the original code here. If the channel of `driver_sequence` is short-circuited, the chunk is dropped, but closure is still saved, which may overwrite the previous buffered closure and finally leading the loss of the previous buffered closure.

```cpp
        for (auto& item : chunks) {
            // This chunks may contains different driver_sequence
            if (item.driver_sequence >= 0 &&
                _short_circuit_driver_sequences.find(item.driver_sequence) != _short_circuit_driver_sequences.end()) {
                continue;
            }
            _chunk_queue.emplace_back(std::move(item));
        }
        if (!chunks.empty() && done != nullptr && _recvr->exceeds_limit(total_chunk_bytes)) {
            _chunk_queue.back().closure = *done;
            *done = nullptr;
        }
```

### CODE REVIEW

**Comment by satanson** [comment]
create a issue and link this pr to the issue

**Review by satanson — DISMISSED** [review]

File: be/src/runtime/data_stream_recvr.cc [hunk 1]
```diff
@@ -484,7 +487,7 @@ Status DataStreamRecvr::SenderQueue::add_chunks(const PTransmitChunkParams& requ
             }
             _chunk_queue.emplace_back(std::move(item));
         }
-        if (!chunks.empty() && done != nullptr && _recvr->exceeds_limit(total_chunk_bytes)) {
+        if (_chunk_queue.size() > original_size && done != nullptr && _recvr->exceeds_limit(total_chunk_bytes)) {
```
Comment (kangkaisen) [inline be/src/runtime/data_stream_recvr.cc:490]: Comment for the first condition.

**Comment by chaoyli** [comment]
```We need to make sure that closure buffered correctly and closure will be executed in any case.``` What's the meaning of this sentence?

File: be/src/runtime/data_stream_recvr.cc (hunk 1 above)
Comment (liuyehcf) [reply be/src/runtime/data_stream_recvr.cc]: Using variable `has_new_chunks` to make it meaningful

**Review by satanson — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by liuyehcf** [comment]
> `We need to make sure that closure buffered correctly and closure will be executed in any case.` What's the meaning of this sentence?

I rearranged the description
