### PR TITLE
Opt hive external table error message for some table type & input format

### LINKED ISSUE #1110: External hive table when error message unfriendly
Currently, StarRocks does not support Hive external table and hive view table. Inputformat errors are also unfriendly.
### Steps to reproduce the behavior (Required)
create external table hive_ex_ex_tbl
 (viewtime INT,userid BIGINT,page_url varchar(100)) 
 engine=hive                       
 properties (                             
  "resource" = "hive_resource",                             
  "table" = "hive_external_tbl",                            
   "database" = "hive_external_tbl");
select * from hive_ex_ex_tbl;

create external table hive_ex_tbl_fromview
 (col_date date,col_smallint smallint) 
 engine=hive                               
 properties (                                     
  "resource" = "hive_resource",                                     
  "table" = "v_hive",                                     
  "database" = "hive_resource");
select * from hive_ex_tbl_fromview;

### Expected behavior (Required)

create external hive view table is not supported.
create external hive external table is not supported.

### Real behavior (Required)

java.util.concurrent.ExecutionException: com.starrocks.common.DdlException: get table partition stats failed: 

### StarRocks version (Required)
1.19.1

### PR DESCRIPTION
**Pull request by Astralidea**
Fix #1110

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java [hunk 1]
```diff
@@ -350,6 +350,15 @@ private void validate(Map<String, String> properties) throws DdlException {
...
             org.apache.hadoop.hive.metastore.api.Table hiveTable = Catalog.getCurrentCatalog().getHiveRepository()
                     .getTable(resourceName, this.hiveDb, this.hiveTable);
+            String hiveTableType = hiveTable.getTableType();
+            if (!"MANAGED_TABLE".equals(hiveTableType)) {
+                if ("VIRTUAL_VIEW".equals(hiveTableType)) {
+                    throw new DdlException("create external hive view table is not supported.");
+                } else if ("EXTERNAL_TABLE".equals(hiveTableType)) {
+                    throw new DdlException("create external hive external table is not supported.");
+                }
+                throw new DdlException("unsupported hive table type [" + hiveTable.getTableType() + "].");
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java:360]:
```suggestion
                throw new DdlException("unsupported hive table type [" + hiveTableType + "].");
```
```suggestion
                throw new DdlException("unsupported hive table type [" + hiveTable.getTableType() + "].");
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java [hunk 2]
```diff
@@ -350,6 +350,15 @@ private void validate(Map<String, String> properties) throws DdlException {
             // 3. check hive partition column exists in table column list
             org.apache.hadoop.hive.metastore.api.Table hiveTable = Catalog.getCurrentCatalog().getHiveRepository()
                     .getTable(resourceName, this.hiveDb, this.hiveTable);
+            String hiveTableType = hiveTable.getTableType();
+            if (!"MANAGED_TABLE".equals(hiveTableType)) {
+                if ("VIRTUAL_VIEW".equals(hiveTableType)) {
+                    throw new DdlException("create external hive view table is not supported.");
+                } else if ("EXTERNAL_TABLE".equals(hiveTableType)) {
+                    throw new DdlException("create external hive external table is not supported.");
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java:358]:
```suggestion
                    throw new DdlException("Hive external table is not supported.");
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java [hunk 3]
```diff
@@ -350,6 +350,15 @@ private void validate(Map<String, String> properties) throws DdlException {
             // 3. check hive partition column exists in table column list
             org.apache.hadoop.hive.metastore.api.Table hiveTable = Catalog.getCurrentCatalog().getHiveRepository()
                     .getTable(resourceName, this.hiveDb, this.hiveTable);
+            String hiveTableType = hiveTable.getTableType();
+            if (!"MANAGED_TABLE".equals(hiveTableType)) {
+                if ("VIRTUAL_VIEW".equals(hiveTableType)) {
+                    throw new DdlException("create external hive view table is not supported.");
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/HiveTable.java:356]:
```suggestion
                    throw new DdlException("Hive view table is not supported.");
```

**Review by gengjun-git — APPROVED** [review]

**Review by wyb — APPROVED** [review]
