### PR TITLE
[BugFix] fix HttpResultWriter ill-formatted json string

### LINKED ISSUE #54557: HTTP Request SQL Query Returns Incorrect Results for Same selectItem
### Steps to reproduce the behavior (Required)
结果错误
```
curl --location 'http://127.0.0.1:8061/api/v1/catalogs/default_catalog/databases/database_name/sql' \
--header 'Content-Type: application/json' \
--data '{
    "query":"SELECT count(*) AS logCount, count(*) AS totalMetric FROM table",
    "sessionVariables":{
        "sql_mode":"MODE_DOUBLE_LITERAL"
    }
}'
```

企业微信截图_445ac6ad-eab6-4706-8b88-28fffbca4091

### Expected behavior (Required)
{
    "data": [
        0,
        0
    ]
}
### Real behavior (Required)
{
    "data": [
        00
    ]
}
### StarRocks version (Required)
version: 3.3.7-00177de

### PR DESCRIPTION
**Pull request by kevincai**
## What I'm doing:

Fixes #54557

Introduced in #25760

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by luohaha — DISMISSED** [review]

File: be/src/runtime/http_result_writer.cpp [hunk 1]
```diff
@@ -52,7 +52,8 @@ Status HttpResultWriter::_transform_row_to_json(const Columns& result_columns, i
         std::string row;
         ASSIGN_OR_RETURN(row, cast_type_to_json_str(result_column, idx));
         _row_str.append(row);
-        if (result_column != result_columns[num_columns - 1]) {
+        if (&result_column != &(result_columns[num_columns - 1])) {
```
Comment (trueeyu) [inline be/src/runtime/http_result_writer.cpp:55]: Will there be any problem if different columns are later supported to reference the same column through SharedPtr?

**Review by LiShuMing — APPROVED** [review]

File: be/src/runtime/http_result_writer.cpp (hunk 1 above)
Comment (kevincai) [reply be/src/runtime/http_result_writer.cpp]: done

**Review by trueeyu — APPROVED** [review]
