### PR TITLE
[BugFix] Fix BE crash when restoring snapshots of lake table using hdfs

### LINKED ISSUE #17894: [StarOS] BE crash when default_fs_type = HDFS
### Steps to reproduce the behavior (Required)
be.out:
```
*** Aborted at 1676469486 (unix time) try "date -d @1676469486" if you are using GNU date ***
PC: @          0x5c8be89 methodIdFromClass.part.0
*** SIGSEGV (@0x0) received by PID 14344 (TID 0x7fa7387d0700) from PID 0; stack trace: ***
    @          0x62c1002 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa880a9e655 os::Linux::chained_handler()
    @     0x7fa880aa3481 JVM_handle_linux_signal
    @     0x7fa880a96678 signalHandler()
    @     0x7fa87f9a5630 (unknown)
    @          0x5c8be89 methodIdFromClass.part.0
    @          0x5c8beea constructNewObjectOfJclass
    @          0x5c8c22d constructNewObjectOfCachedClass
    @          0x5c8e9e9 hdfsBuilderConnect
    @          0x5c29390 staros::starlet::fslib::HdfsFileSystem::initialize()
    @          0x5c0134a staros::starlet::fslib::FileSystemFactoryImpl::new_filesystem()
    @          0x5c01560 staros::starlet::fslib::FileSystemFactory::new_filesystem()
    @          0x5c1b8a9 staros::starlet::fslib::CacheFileSystem::initialize()
    @          0x5c0134a staros::starlet::fslib::FileSystemFactoryImpl::new_filesystem()
    @          0x5c01560 staros::starlet::fslib::FileSystemFactory::new_filesystem()
    @          0x50b4204 starrocks::StarOSWorker::get_shard_filesystem()
    @          0x4793680 starrocks::StarletFileSystem::new_writable_file()
    @          0x4a919a1 starrocks::fs::new_writable_file()
    @          0x4a8d38e starrocks::lake::TabletManager::put_tablet_metadata()
    @          0x5a62a06 starrocks::LakeSnapshotLoader::restore()
    @          0x50c1e5f starrocks::LakeServiceImpl::restore_snapshots()
    @          0x64d705d brpc::policy::ProcessRpcRequest()
    @          0x6484677 brpc::ProcessInputMessage()
    @          0x648554b brpc::InputMessenger::OnNewMessages()
    @          0x6448dbe brpc::Socket::ProcessEvent()
    @          0x641bb0f bthread::TaskGroup::task_runner()
    @          0x6562331 bthread_make_fcontext
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 46580be   |
+-------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by TszKitLo40**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17894 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by sduzh — DISMISSED** [review]

File: be/src/service/service_be/lake_service.cpp [hunk 1]
```diff
@@ -587,11 +587,23 @@ void LakeServiceImpl::restore_snapshots(::google::protobuf::RpcController* contr
         return;
     }
 
-    auto loader = std::make_unique<LakeSnapshotLoader>(_env);
-    auto st = loader->restore(request);
+    auto thread_pool = _env->agent_server()->get_thread_pool(TTaskType::MAKE_SNAPSHOT);
```
Comment (wyb) [inline be/src/service/service_be/lake_service.cpp:590]: TTaskType::DOWNLOAD

and use TTaskType::UPLOAD in `upload_snapshots`

**Comment by TszKitLo40** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]
