### PR TITLE
[BugFix] support both inner and outer table column in one side of operator in correlated predicate

### LINKED ISSUE #10815: unknown error from CTE query
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS h9;
CREATE DATABASE h9;
USE h9;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATE NOT NULL ,c_0_1 VARCHAR(11) NULL ,c_0_2 DATETIME NOT NULL ,c_0_3 DATE NOT NULL ,c_0_4 BIGINT NOT NULL ,c_0_5 BOOLEAN REPLACE NULL ,c_0_6 DATETIME REPLACE_IF_NOT_NULL NOT NULL ,c_0_7 BOOLEAN REPLACE NOT NULL ,c_0_8 DECIMAL(11, 8)  REPLACE NOT NULL ,c_0_9 FLOAT SUM NULL ,c_0_10 DATETIME REPLACE_IF_NOT_NULL NOT NULL ,c_0_11 DATETIME REPLACE_IF_NOT_NULL NOT NULL ,c_0_12 HLL HLL_UNION NOT NULL ,c_0_13 DECIMAL(33, 3)  REPLACE_IF_NOT_NULL NULL ,c_0_14 BOOLEAN REPLACE NULL ,c_0_15 BOOLEAN REPLACE NOT NULL ,c_0_16 FLOAT MAX NULL ,c_0_17 BOOLEAN REPLACE NULL , INDEX index1_c_0_1(`c_0_1`) USING BITMAP, INDEX index1_c_0_3(`c_0_3`) USING BITMAP) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 339 day)) DISTRIBUTED BY HASH (c_0_4,c_0_1,c_0_2) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_0_1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 INT NOT NULL ,c_1_1 DATE NOT NULL ,c_1_2 INT NOT NULL ,c_1_3 FLOAT NULL ,c_1_4 FLOAT NOT NULL ,c_1_5 VARCHAR(11) NULL ,c_1_6 DATETIME NULL ,c_1_7 BOOLEAN NOT NULL ,c_1_8 TINYINT NULL ,c_1_9 BOOLEAN NOT NULL ,c_1_10 DATE NOT NULL ,c_1_11 JSON NOT NULL ,c_1_12 JSON NULL ,c_1_13 ARRAY<STRING> NULL ,c_1_14 DATETIME NOT NULL ,c_1_15 JSON NULL ,c_1_16 CHAR(31) NULL ,c_1_17 BOOLEAN NOT NULL , INDEX index1_c_1_14(`c_1_14`) USING BITMAP, INDEX index1_c_1_17(`c_1_17`) USING BITMAP) DUPLICATE KEY (c_1_0,c_1_1,c_1_2) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 115 day)) DISTRIBUTED BY HASH (c_1_0,c_1_2,c_1_1) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_5") ;
INSERT INTO t0 VALUES ('2010-01-21', 'I', '2010-01-29 08:00:14', '2010-01-15', -178438271, true, '2010-01-14 08:00:14', false, 0.00000113, -1.78438271E8, '2010-01-29 08:00:14', NULL, hll_hash(''), 448300852830127067430787679.569, false, true, 0.8848129608238124, true), ('2010-01-01', 'fT3l', '2010-01-30 08:00:14', '2010-01-28', 1494079706, true, '2010-01-12 08:00:14', false, 0.00000145, NULL, '2010-01-29 08:00:14', '2010-01-16 08:00:14', hll_hash('eVPwDuD'), 9219181926354544298163329.330, false, false, 0.3207072201639155, false), ('2010-01-03', NULL, '2010-01-15 08:00:14', '2010-01-25', -1340650222, true, NULL, false, 0.00000886, 0.20867900642643056, NULL, '2010-01-16 08:00:14', hll_hash('e'), 920818492578523219035069313.775, true, false, '-Inf', true), ('2010-01-26', 'FfqL3f', '2010-01-14 08:00:14', '2010-01-04', -178438271, false, '2010-01-03 08:00:14', true, 0.00000327, 0.5796904759098853, '2010-01-29 08:00:14', '2010-01-13 08:00:14', hll_hash(''), 916371859546093318295489904.556, true, false, 0.1116518411016838, false);
INSERT INTO t1 VALUES (30, '2010-01-02', 8, 0.8858894846973926, -1.78438271E8, 'mf173', '2010-01-01 08:00:14', true, 7, false, '2010-01-18', parse_json('{"rfLhg": true, "Iin9": null, "hozNb": -1.78438271E8, "jw": null, "n": 1885697362, "M45": null, "Vw06": null, "Q": true, "R": false, "QGI": false, "zp": "d", "8": 0.12126943657989575, "zMhu": false, "lG": true, "APxOX2JbO": 1.885697362E9}'), parse_json('{"Ph5R": {"PAO": 0.43238865172539664}}'), ["B", "fiI", "FSJ", "wIYU8v3", "Yr", "se", "", "gzlEOONl", "V3", "uXQ", "QZzJL"], '2010-01-21 08:00:14', parse_json('{"B": true, "MPndEYX4g": 0.5796904759098853, "eTSaz": "3", "O": "WA", "re6D99": false, "WPHlP3Uqv": -1586346787, "kSx": ["qlBs8Mf3", -1634414582, [true, "NC", 1933514049, false, -1634414582, 0.5796904759098853, null, "M", false, true, null, true, "77iv7", false], {"7": true}], "49W": 0.480046016889663, "aYC07": 0.9068449877364881, "sdMiDn": -252740212, "edSl4JOh": "", "lB": -1248142758, "7": "", "z": null, "TzNjX3Ze": false}'), 'D', true);
DELETE FROM t1 WHERE c_1_2=-532121622 AND c_1_1='1969-12-25' AND c_1_0=-487571678;
WITH with_t_0 as (SELECT t0_126.c_0_0, t0_126.c_0_1, t0_126.c_0_2, t0_126.c_0_3, t0_126.c_0_4, t0_126.c_0_5, t0_126.c_0_6, t0_126.c_0_7, t0_126.c_0_8, t0_126.c_0_9, t0_126.c_0_10, t0_126.c_0_11, t0_126.c_0_13, t0_126.c_0_14, t0_126.c_0_15, t0_126.c_0_16, t0_126.c_0_17 FROM t0 AS t0_126) , with_t_1 as (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127) SELECT ((NULL)-(-754600767)) FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127 WHERE BITMAP_CONTAINS(bitmap_hash(''), ((313476454)*(1757278421))) ) subt1  LEFT JOIN (SELECT t0_126.c_0_0, t0_126.c_0_1, t0_126.c_0_2, t0_126.c_0_3, t0_126.c_0_4, t0_126.c_0_5, t0_126.c_0_6, t0_126.c_0_7, t0_126.c_0_8, t0_126.c_0_9, t0_126.c_0_10, t0_126.c_0_11, t0_126.c_0_13, t0_126.c_0_14, t0_126.c_0_15, t0_126.c_0_16, t0_126.c_0_17 FROM t0 AS t0_126) subt0 ON subt1.c_1_16 = subt0.c_0_16 AND CAST(NULL AS STRING )  <= subt0.c_0_16 AND subt1.c_1_14 < subt0.c_0_17 AND subt1.c_1_14 = subt0.c_0_17 WHERE false GROUP BY true,  ( subt0.c_0_9 ) < ( (SELECT t0_126.c_0_9 FROM  t0 AS t0_126  LEFT JOIN (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127 WHERE CAST(YEARS_DIFF(NULL, CAST(t1_127.c_1_7 AS DATE ) )  AS BOOLEAN ) ) subt1 ON t0_126.c_0_2 = subt1.c_1_16 AND t0_126.c_0_2 >= subt1.c_1_16 AND t0_126.c_0_4 < subt1.c_1_17 AND t0_126.c_0_4 >= subt1.c_1_17 WHERE (CASE  WHEN CAST(subt0.c_0_9 AS BOOLEAN )  THEN '1969-12-21 16:43:21'  WHEN CASE  WHEN false THEN ((subt0.c_0_16) IS NOT NULL) END THEN t0_126.c_0_2 ELSE t0_126.c_0_2 END) IN ('1970-01-16 10:41:23') )  ) ;
```

fe.warn.log:
```
2022-09-03 14:49:09,313 WARN (starrocks-mysql-nio-pool-10|337) [StmtExecutor.execute():493] execute Exception, sql WITH with_t_0 as (SELECT t0_126.c_0_0, t0_126.c_0_1, t0_126.c_0_2, t0_126.c_0_3, t0_126.c_0_4, t0_126.c_0_5, t0_126.c_0_6, t0_126.c_0_7, t0_126.c_0_8, t0_126.c_0_9, t0_126.c_0_10, t0_126.c_0_11, t0_126.c_0_13, t0_126.c_0_14, t0_126.c_0_15, t0_126.c_0_16, t0_126.c_0_17 FROM t0 AS t0_126) , with_t_1 as (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127) SELECT ((NULL)-(-754600767)) FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127 WHERE BITMAP_CONTAINS(bitmap_hash(''), ((313476454)*(1757278421))) ) subt1  LEFT JOIN (SELECT t0_126.c_0_0, t0_126.c_0_1, t0_126.c_0_2, t0_126.c_0_3, t0_126.c_0_4, t0_126.c_0_5, t0_126.c_0_6, t0_126.c_0_7, t0_126.c_0_8, t0_126.c_0_9, t0_126.c_0_10, t0_126.c_0_11, t0_126.c_0_13, t0_126.c_0_14, t0_126.c_0_15, t0_126.c_0_16, t0_126.c_0_17 FROM t0 AS t0_126) subt0 ON subt1.c_1_16 = subt0.c_0_16 AND CAST(NULL AS STRING )  <= subt0.c_0_16 AND subt1.c_1_14 < subt0.c_0_17 AND subt1.c_1_14 = subt0.c_0_17 WHERE false GROUP BY true,  ( subt0.c_0_9 ) < ( (SELECT t0_126.c_0_9 FROM  t0 AS t0_126  LEFT JOIN (SELECT t1_127.c_1_0, t1_127.c_1_1, t1_127.c_1_2, t1_127.c_1_3, t1_127.c_1_4, t1_127.c_1_5, t1_127.c_1_6, t1_127.c_1_7, t1_127.c_1_8, t1_127.c_1_9, t1_127.c_1_10, t1_127.c_1_14, t1_127.c_1_16, t1_127.c_1_17 FROM t1 AS t1_127 WHERE CAST(YEARS_DIFF(NULL, CAST(t1_127.c_1_7 AS DATE ) )  AS BOOLEAN ) ) subt1 ON t0_126.c_0_2 = subt1.c_1_16 AND t0_126.c_0_2 >= subt1.c_1_16 AND t0_126.c_0_4 < subt1.c_1_17 AND t0_126.c_0_4 >= subt1.c_1_17 WHERE (CASE  WHEN CAST(subt0.c_0_9 AS BOOLEAN )  THEN '1969-12-21 16:43:21'  WHEN CASE  WHEN false THEN ((subt0.c_0_16) IS NOT NULL) END THEN t0_126.c_0_2 ELSE t0_126.c_0_2 END) IN ('1970-01-16 10:41:23') )  )
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.optimizer.statistics.Statistics.getColumnStatistic(Statistics.java:56) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:63) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitVariableReference(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCastOperator(ExpressionStatisticCalculator.java:102) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCastOperator(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CastOperator.accept(CastOperator.java:68) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.lambda$visitCall$0(ExpressionStatisticCalculator.java:143) ~[starrocks-fe.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_272]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[?:1.8.0_272]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_272]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_272]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_272]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_272]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_272]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCall(ExpressionStatisticCalculator.java:143) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator$ExpressionStatisticVisitor.visitCall(ExpressionStatisticCalculator.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.CallOperator.accept(CallOperator.java:173) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.ExpressionStatisticCalculator.calculate(ExpressionStatisticCalculator.java:35) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.getExpressionStatistic(PredicateStatisticsCalculator.java:310) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:195) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator$PredicateStatisticsCalculatingVisitor.visitBinaryPredicate(PredicateStatisticsCalculator.java:31) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.BinaryPredicateOperator.accept(BinaryPredicateOperator.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.PredicateStatisticsCalculator.statisticsCalculate(PredicateStatisticsCalculator.java:28) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimateStatistics(StatisticsCalculator.java:1308) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.computeJoinNode(StatisticsCalculator.java:868) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:747) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.visitLogicalJoin(StatisticsCalculator.java:137) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.logical.LogicalJoinOperator.accept(LogicalJoinOperator.java:127) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.statistics.StatisticsCalculator.estimatorStats(StatisticsCalculator.java:153) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.DeriveStatsTask.execute(DeriveStatsTask.java:76) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:169) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:107) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:62) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:39) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:342) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:312) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:427) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:665) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE b438184 |
+----------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes [#10815](https://github.com/StarRocks/starrocks/issues/10815)

## Problem Summary(Required) ：

This pr helps to solve the problem when correlated predicate contains both inner table column and outer table column in one side of eq operator. For example, this sql `select t1.a from t1 where t1.b < (select t2.d  from 
t2 where t1.b+abs(t2.a) = t2.c)`, we should extract `abs(t2.a)`, `t2.c` from the correlated predicate `t1.b+abs(t2.a) = t2.c` and add them into the inner table output.

To solve the bug, I did things as below:
1. add CorrelatedPredicateRewriter to rewrite the correlated predicate. In the rewrite, we only extract distinct expr which only contains inner table column and replace it with a new columnRef. This helps to avoid extract const value and duplicate expr which add extra cost to the child input process. In the future, we could enhance the ability of this rewriter to support more correlated predicate in subquery.
2. extract common logic from four subqueryToJoin rules to `SubqueryUtils` to simplify the code.
3. modify the check() method in  `HashJoinImplementationRule` and `NestloopJoinImplementationRule` . Only contains eq conditon and operands in each side of equal operator belongs to one child input  can implement to hash join.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java [hunk 1]
```diff
@@ -0,0 +1,216 @@
...
+import com.starrocks.sql.optimizer.operator.scalar.InPredicateOperator;
+import com.starrocks.sql.optimizer.operator.scalar.IsNullPredicateOperator;
+import com.starrocks.sql.optimizer.operator.scalar.LikePredicateOperator;
+import com.starrocks.sql.optimizer.operator.scalar.PredicateOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ScalarOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ScalarOperatorVisitor;
+
+import java.util.List;
+
+public class BaseScalarOperatorShuttle extends ScalarOperatorVisitor<ScalarOperator, Void> {
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: the class just use for clone? why don't use clone directly?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java [hunk 2]
```diff
@@ -0,0 +1,115 @@
...
+import com.starrocks.sql.optimizer.operator.scalar.CallOperator;
+import com.starrocks.sql.optimizer.operator.scalar.CaseWhenOperator;
+import com.starrocks.sql.optimizer.operator.scalar.CastOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ScalarOperator;
+
+import java.util.List;
+import java.util.Map;
+
+public class CorrelatedPredicateRewriter extends BaseScalarOperatorShuttle {
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java:17]: add comment

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: this is a base class which used to generate a new scalarOperator when we want to replace a node in the old scalarOperator.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java [hunk 3]
```diff
@@ -172,4 +123,31 @@ private static boolean checkPredicateContainColumnRef(List<ColumnRefOperator> cr
...
+            ScalarOperator correlationPredicate, BaseScalarOperatorShuttle scalarOperatorShuttle) {
+        if (correlationPredicate == null) {
+            return null;
+        }
+        return correlationPredicate.clone().accept(scalarOperatorShuttle, null);
+    }
+
+    public static boolean containsExpr(Map<ColumnRefOperator, ScalarOperator> innerRefMap) {
+        return innerRefMap.values().stream().anyMatch(e -> !e.isColumnRef());
+    }
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:144]: emmm, not recommended extract to a method...inline may be easier to understand.

Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:144]: It's a common action in all the apply to join rules. I think it's a bit of tedious to write it four places. So if inline is our style, I will change it back.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: so why don't use ScalarOperator.clone() directly? It seems that the works are the same

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java (hunk 3 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:144]: Inline isn't our style, the name of this method isn't clear, isn't as good as inline

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java [hunk 4]
```diff
@@ -172,4 +124,31 @@ private static boolean checkPredicateContainColumnRef(List<ColumnRefOperator> cr
...
+
+    public static Map<ColumnRefOperator, ScalarOperator> updateOutputColumns(
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:146]: should give a better name

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: We shoud never directly use this class. If you don't override its visit method, this shuttle just traverse the operator tree and do nothing even copy the operator. But when you want change some nodes in the original operator tree in your way, you can extend this class implement your own shuttle. If you changed some node, the shuttle will detect it and generate a new operator tree to you. I think it helps to avoid duplication work when you want to rewrite the operator tree.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java (hunk 3 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java]: yeh. I renamed the method to express its usage more explicit.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java (hunk 4 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java]: renamed it.

**Comment by packy92** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java [hunk 5]
```diff
@@ -19,12 +18,21 @@
...
 
+import java.util.Collection;
 import java.util.List;
 import java.util.Map;
 
 public class SubqueryUtils {
 
+    public static final String EXIST_NON_EQ_PREDICATE = "Not support Non-EQ correlated predicate in correlated subquery";
+
+    public static final String NONE_CORRELATED_PREDICATE = "Not support without correlated predicate in correlated subquery";
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:31]: It should called non-correlated subquery if not containing correlated predicate. How to understand this error message?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefFactory.java [hunk 6]
```diff
@@ -73,6 +76,17 @@ public ColumnRefOperator getColumnRef(int id) {
         return columnRefs.get(id - 1);
     }
 
+    public Set<ColumnRefOperator> getColumnRefs(ColumnRefSet columnRefSet) {
+        Preconditions.checkState(!columnRefSet.isEmpty());
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefFactory.java:80]: Is this check necessary for sake of generality?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: If I want to remove, not replace, some of the inner nodes from the originl tree, can I make it though this class?

Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: Technically, I think it is feasible but logic maybe complex. If you remove a node, his father's child decrease and this may affect the type of his father.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefFactory.java (hunk 6 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/ColumnRefFactory.java:80]: You are right. It can remove.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java [hunk 7]
```diff
@@ -0,0 +1,216 @@
...
+            int whenThenEndIdx = operator.getElseClause() == null ? clonedOperators.size() : clonedOperators.size() - 1;
+            clonedWhenThenClauses = clonedOperators.subList(operator.getWhenStart(), whenThenEndIdx);
+
+            return new CaseWhenOperator(operator.getType(), clonedCaseClause, clonedElseClause, clonedWhenThenClauses);
+        } else {
+            return operator;
+        }
+    }
+
+    protected List<ScalarOperator> visitList(List<ScalarOperator> operators, boolean[] update) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:205]: seems you only use  update[0], why we need a boolean[] here?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java [hunk 8]
```diff
@@ -0,0 +1,126 @@
...
+/**
+ * used to extract distinct expr which only contains inner table column and replace it with a new columnRef.
+ * e.g. t1 is inner table, t2 is outer table. correlated predicate is:
+ * t1.col1 + t2.col1 = abs(t1.col2) + t2.col1 + concat(t1.col1, t2.col1)
+ * The rewriter will extract abs(t1.col2), t2.col1 and build scalarOperator to new columnRef map like:
+ * t1.col1 : t1.col1
+ * abs(t1.col2) : columnRef1
+ *
+ * then and rewrite the predicate like:
+ * t1.col1 + t2.col1 = columnRef1 + t2.col1 + concat(t1.col1, t2.col1)
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java:26]: why only handle abs(t1.col2), not handle concat(t1.col1, t2.col1)?

Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java:26]: Our main purpose is extract all distinct exprs belong to inner table. concat(t1.col1, t2.col1) contains outer table t1.col1. In this expr, the atom expr from inner table is t2.col1, so we only need extract t2.col1.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 7 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:205]: I need visitList return the update flag info at the same time. boolean is primitive data type, so I use a array to pass the reference.

Comment (kangkaisen) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:205]: so, why not Boolean?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java (hunk 5 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:31]: The old logic split predicate in subquery into two groups(correlated and uncorrelated).  when correlated group is empty will throw an exception. It seems in the check() method we had ensure it contains correlated predicate. @Seaven  do you know the reason why we check it again? 
```
PushDownApplyAggFilterRule.class
if (correlationPredicate.isEmpty()) {
            // If the correlation predicate doesn't appear in here,
            // it should not be a situation that we currently support.
            throw new SemanticException(SubqueryUtils.NONE_CORRELATED_PREDICATE);
        }
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:27]: Fine, I got it, it's means all the nodes above it will be re-new when a node is modified, but add comment and give a explicit name plz, help others can use it quickly

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java (hunk 5 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/SubqueryUtils.java:31]: The push down rule depends on correlation predicate, if don't support correlation predicate, we can't push down apply node

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java (hunk 2 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java:29]: added

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java (hunk 1 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java:32]: yeh, I add some comments and explain the shuttle meaning.

**Comment by packy92** [comment]
run starrocks_clang-tidy

**Comment by packy92** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 134 / 209 (64.11%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/BetweenPredicateOperator.java|0|4|00.00%|[21, 22, 23, 24]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LikePredicateOperator.java|0|4|00.00%|[26, 27, 28, 29]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java|31|87|35.63%|[35, 45, 50, 51, 52, 53, 55, 61, 62, 63, 64, 66, 71, 72, 73, 74, 76, 94, 99, 100, 101, 102, 104, 133, 134, 135, 136, 138, 144, 145, 146, 147, 149, 155, 156, 157, 158, 160, 166, 167, 168, 169, 171, 188, 189, 190, 191, 192, 194, 195, 197, 198, 201, 202, 204, 206]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|9|11|81.82%|[108, 114]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|31|38|81.58%|[51, 82, 84, 85, 88, 89, 92]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|10|11|90.91%|[241]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|22|23|95.65%|[105]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/implementation/MergeJoinImplementationRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/CompoundPredicateOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/ColumnRefFactory.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 173 / 211 (81.99%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/BetweenPredicateOperator.java|0|4|00.00%|[21, 22, 23, 24]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/LikePredicateOperator.java|0|4|00.00%|[26, 27, 28, 29]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/BaseScalarOperatorShuttle.java|70|89|78.65%|[35, 53, 64, 74, 94, 102, 136, 147, 158, 169, 191, 192, 194, 195, 197, 198, 201, 202, 204]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownApplyAggFilterRule.java|9|11|81.82%|[108, 114]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/CorrelatedPredicateRewriter.java|31|38|81.58%|[51, 82, 84, 85, 88, 89, 92]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ExistentialApply2OuterJoinRule.java|10|11|90.91%|[241]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/QuantifiedApply2OuterJoinRule.java|22|23|95.65%|[105]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/implementation/MergeJoinImplementationRule.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/ScalarApply2JoinRule.java|11|11|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/CompoundPredicateOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/SubqueryUtils.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/ColumnRefFactory.java|4|4|100.00%|[]|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by packy92** [comment]
run starrocks_admit_test

**Review by liuyehcf — APPROVED** [review]
