### PR TITLE
[BugFix] fix replica meta falsely deleted right after clone finished

### LINKED ISSUE #7879: Tablet clone finished but then it got deleted and cloned again, metadata is falsely deleted
### Steps to reproduce the behavior (Required)
1. create a table with 3 replicas
2. stard a couple of simultaneously load task
3. decommission one BE

### Expected behavior (Required)

clone for BE decommission acts normally 

### Real behavior (Required)

clone finished but then it got deleted and cloned again, metadata is falsely deleted.

```
2022-06-24 11:51:20,111 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1894/-1/1894,4110591:1894/-1/1894,129
045:1894/-1/1894, dest:-1 try to find a new backend
2022-06-24 11:51:29,318 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1904/-1/1904,4110591:1904/-1/1904,129
045:1904/-1/1904, dest:-1 try to find a new backend
2022-06-24 11:51:38,417 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1912/-1/1912,4110591:1912/-1/1912,129
045:1912/-1/1912, dest:-1 try to find a new backend
2022-06-24 11:51:54,171 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1921/-1/1921,4110591:1921/-1/1921,129
045:1921/-1/1921, dest:-1 try to find a new backend
2022-06-24 11:52:08,436 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1926/-1/1926,4110591:1926/-1/1926,129
045:1926/-1/1926, dest:-1 try to find a new backend
2022-06-24 11:52:08,436 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():748] succeed to find new backend for tablet relocating. tablet: 7856532 replicas: 370168:1926/-1/1926,4110591:1926/-1/1926,129045:1926/-1/1926,370169:-1/1926/-1, 370168->370169
2022-06-24 11:52:08,445 INFO (tablet scheduler|43) [TabletScheduler.schedulePendingTablets():463] add clone task to agent task queue: tablet id: 7856532, schema hash: 2119321583, storageMedium: HDD, visible version(hash): 1926-0, src backend: 172.26.195.25, src path hash: 1687259094134121138, dest backend: 370169, dest path hash: 3113974398250995690, is local: false
2022-06-24 11:52:08,552 INFO (thrift-server-pool-22|198) [TabletSchedCtx.finishCloneTask():940] clone finished: tablet id: 7856532, status: REPLICA_RELOCATING, state: FINISHED, type: REPAIR. from backend: 370168, src path hash: 1687259094134121138. to backend: 370169, dest path hash: 3113974398250995690
2022-06-24 11:52:08,552 INFO (thrift-server-pool-22|198) [TabletScheduler.removeTabletCtx():1228] remove the tablet 7856532. because: finished
2022-06-24 11:52:08,644 WARN (Thread-44|96) [ReportHandler.deleteFromMeta():745] delete replica[7857127] in tablet[7856532] from meta. backend[370169], report version: 16560401930086, current report version: 16560401930086
2022-06-24 11:52:23,309 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1936/-1/1936,4110591:1936/-1/1936,129045:1936/-1/1936, dest:-1 try to find a new backend
2022-06-24 11:52:31,418 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1936/-1/1936,4110591:1936/-1/1936,129045:1936/-1/1936, dest:-1 try to find a new backend
2022-06-24 11:52:42,120 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1940/-1/1940,4110591:1940/-1/1940,129
045:1940/-1/1940, dest:-1 try to find a new backend
2022-06-24 11:52:51,389 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1941/-1/1941,4110591:1941/-1/1941,129
045:1941/-1/1941, dest:-1 try to find a new backend
2022-06-24 11:52:59,511 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1941/-1/1941,4110591:1941/-1/1941,129
045:1941/-1/1941, dest:-1 try to find a new backend
2022-06-24 11:53:08,958 WARN (Thread-44|96) [ReportHandler.deleteFromBackend():799] failed add to meta. tablet[7856532], backend[370169]. version is invalid. tablet:1926 < partitionVisible:1946 replicas:370168:1946/-1/1946,4110591:1946/-1/1946,129045:1946/-1/1946,
2022-06-24 11:53:08,958 WARN (Thread-44|96) [ReportHandler.deleteFromBackend():813] delete tablet[7856532] from backend[370169] because not found in meta
2022-06-24 11:53:15,131 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1946/-1/1946,4110591:1946/-1/1946,129
045:1946/-1/1946, dest:-1 try to find a new backend
2022-06-24 11:53:24,494 INFO (tablet scheduler|43) [TabletScheduler.handleReplicaRelocating():739] failed to find version incomplete replica from tablet relocating. reason: [unable to choose dest replica], tablet: [7856532], replicas: 370168:1946/-1/1946,4110591:1946/-1/1946,129
045:1946/-1/1946, dest:-1 try to find a new backend
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7879

## Problem Summary(Required) ：

```
    /**
     * In the following situation, a normally cloned replica could be falsely deleted:
     * <p>
     * 1. BE X generates tablet report and sends it to FE<p>
     * 2. FE creates clone task(for balance or repair) and a new replica on BE X,
     *    so the corresponding tablet is not included in the report sent above.<p>
     * 3. BE X finishes clone and then FE will receive the message and set the state
     *    of new replica to NORMAL<p>
     * 4. FE processes the tablet report from step 1 and finds that BE X doesn't report
     *    the tablet info corresponding to the newly created replica, so it will delete
     *    the replica from its meta<p>
     * 5. On the next tablet report of BE X which will include the tablet info, FE finds
     *    that the tablet reported by BE X doesn't exist in its meta, so it will send a
     *    request asking BE X to delete the newly cloned replica physically.
     *  <p>
     * The main reason causes this problem is that FE handles tablet report task and clone
     * task concurrently, with specific timing, this will happen. So we add a new state
     * `deferReplicaDeleteToNextReport` for `Replica`, default to true. When FE meets a replica
     * only existed in FE's meta, not in the tablet report, it will check
     * `deferReplicaDeleteToNextReport` and defer the meta delete till next report of the BE.
     */
```
This bug is reproduced, see the log in #7879  for a proof.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 11 (09.09%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|7|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Replica.java|1|4|25.00%|

**Comment by kangkaisen** [comment]
How did you test this PR and where are test cases?

File: fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java [hunk 1]
```diff
@@ -731,8 +731,15 @@ private static void deleteFromMeta(ListMultimap<Long, Long> tabletDeleteFromMeta
                             continue;
                         }
 
-                        tablet.deleteReplicaByBackendId(backendId);
-                        ++deleteCounter;
+                        // Defer the meta delete to next tablet report, see `Replica.deferReplicaDeleteToNextReport`
+                        // for details.
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java:735]: if there are more than one old report(network delay), then replica will still be deleted?

Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java:735]: It could happen in theory, but i think it's quiet a rare case because currently BE reports tablet info with a relatively long interval(every 60s by default) and FE handle tablet report in a single thread and just does some simple computation. For now i haven't thought of a simpler solution without adding some extra syncing mechanism to do this precisely. And if that rare case do happen, it won't cause some serious problem, just some waste of clone work. So i think this pr is simple enough to handle current problem.

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by nshangyiming** [comment]
@mergify backport branch-2.3
