### PR TITLE
[BugFix] fix bug to report error of type mismatch between int96 and string

### LINKED ISSUE #11839: BE crashes when query parquet file if type mismatches
### Steps to reproduce the behavior (Required)

Create hive table like 
```
vin string
collection_time string
```

but actually put parquet file whose schema is like

```
vin string
collection_time timestamp
```

onto hdfs.

And select data from table, then BE crashes

### Expected behavior (Required)

BE should report error

### Real behavior (Required)

BE crashes

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```
MySQL [zya]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| ZHANGYAN 4b7a373  |
+-------------------+
1 row in set (0.01 sec)
```

internal JIRA: https://starrocks.atlassian.net/browse/SR-12571

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11839

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Review by DorianZheng — APPROVED** [review]

**Review by Smith-Cruise — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: be/src/formats/parquet/column_converter.cpp [hunk 1]
```diff
@@ -382,8 +382,8 @@ Status ColumnConverterFactory::create_converter(const ParquetField& field, const
         break;
     }
     case tparquet::Type::type::INT96: {
+        need_convert = true;
```
Comment (GavinMar) [inline be/src/formats/parquet/column_converter.cpp:385]: Is it necessary to perform the convert for INT96 for any types? The convert function will cause some cpu overhead from my tests a few days ago, especially with cache. Perhaps set `need_convert` flag only for string type and datetime is more proper.

Comment (dirtysalt) [reply be/src/formats/parquet/column_converter.cpp:385]: if you look close to the pattern
- set `need_converter` for incompatible type
- set `converter` only when type conversion has been done by us
- and check `need_convert` and `converter` at final phase

It's just the old pattern. It's not very clear but clear enough.

So int96 is only compatible to datetime.

```
        if (col_type == PrimitiveType::TYPE_DATETIME) {
            auto _converter = std::make_unique<Int96ToDateTimeConverter>();
            RETURN_IF_ERROR(_converter->init(timezone));
            *converter = std::move(_converter);
        }
        break;

    if (need_convert && *converter == nullptr) {
        return Status::NotSupported(
                strings::Substitute("parquet column reader: not supported convert from parquet `$0` to `$1`",
                                    ::tparquet::to_string(parquet_type), type_to_string(col_type)));
    }
```

**Review by GavinMar — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by satanson — APPROVED** [review]
