### PR TITLE
[BugFix] Remove limit for committing empty transaction

### LINKED ISSUE #2862: routine load 不提交offset
发现在某种情况下routine load 不提交offset
问题复现
### Steps to reproduce the behavior (Required)
建表
1. CREATE TABLE `routine_test2` (
`cdate` date NOT NULL COMMENT '分区日期',
`id` varchar(32) NOT NULL,
`create_time` varchar(32) NOT NULL
) ENGINE=OLAP 
PRIMARY KEY(`cdate`,`id`) COMMENT "routine测试表" 
PARTITION BY RANGE (`cdate`) (
    START ("2022-01-10") END ("2022-01-18") EVERY (INTERVAL 1 day)
)
DISTRIBUTED BY HASH(`id`) 
BUCKETS 1
PROPERTIES ( 
    "replication_num" = "1", 
    "in_memory" = "false",
    "dynamic_partition.enable" = "true",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-3",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "dynamic_partition.buckets" = "1",
    "storage_format" = "DEFAULT"
);
建routine load
2. create routine load routine_routine_test_c2 on routine_test2
columns (id,create_time,cdate=date(create_time)),
WHERE cdate >= date_add(curdate(),-2)
PROPERTIES ( 
    "format"="json", 
    "desired_concurrent_number" = "1", 
    "strip_outer_array" ="true",  
    "json_root"="$.data", 
    "max_batch_interval" = "5", 
    "max_error_number"="1000" 
) 
FROM KAFKA (     
    "kafka_broker_list"= "xxx:9092",     
    "kafka_topic" = "routine_test2",
    "property.group.id" = "starrocks_routine_test_c2",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);

### Expected behavior (Required)
3.kafka 写入数据
"{\"data\":[{\"id\":\"2\",\"create_time\": \"2022-01-14 00:00:00\"}]}"
routine load Progress offset 更新offset ，且kafka consumer offset 也更新 ，并和Progress保持一致
当写入"{\"data\":[{\"id\":\"2\",\"create_time\": \"2022-01-11 00:00:00\"}]}"
数据这where中过滤掉了时
routine load Progress offset 更新offset ，但kafka consumer offset 不会更新 ，和Progress中offset不一致

4.得出结论：routine load where 条件过滤数据时，不会提交offset到kafka

### StarRocks version (Required)
 - 1.19.5 ,1.19.3

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #2862

## Problem Summary(Required) ：

This PR removes the limit for the empty transaction.

The previous implement forbids empty transactions and would return the error `all partitions have no load data`. 

But when loaded data are filtered by `JSON path` or `where condition`, the JSON/CSV scanner may return zero rows and the transaction would be aborted with the error `all partitions have no load data`. The result is confusing for the user. Besides, in routine load, the commit offset would not be advanced.

For compatible consideration, `empty_load_as_error` is added to fe config. The default behaviour stay the same as before.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 1]
```diff
@@ -1425,4 +1425,10 @@ public class Config extends ConfigBase {
      */
     @ConfField(mutable = true)
     public static boolean enable_password_reuse = true;
+    /**
+     * If set to false, when the load is empty, sucess is returned.
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1429]:
```suggestion
     * If set to false, when the load is empty, success is returned.
```

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java [hunk 2]
```diff
@@ -220,18 +219,6 @@ protected boolean checkCommitInfo(RLTaskTxnCommitAttachment rlTaskTxnCommitAttac
             return true;
         }
 
-        if (txnStatusChangeReason != null &&
-                txnStatusChangeReason == TransactionState.TxnStatusChangeReason.NO_PARTITIONS) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java:224]: Should not remove because the default behavior is still abort when no data loaded.
Add some comments for this.

**Review by chaoyli — DISMISSED** [review]

**Comment by xiaoyong-z** [comment]
Does this also happen for other types of loads besides kafka routine loads ? 
Maybe it is also necessary to deal with this situation for other loads?

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java (hunk 2 above)
Comment (rickif) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaRoutineLoadJob.java:224]: The default behaviour of empty transaction in routine load should be changed to commit successfully. Otherwise, #2862 cannot be resolved.

**Comment by rickif** [comment]
> Does this also happen for other types of loads besides kafka routine loads ? Maybe it is also necessary to deal with this situation for other loads?

It works for all 

> Does this also happen for other types of loads besides kafka routine loads ? Maybe it is also necessary to deal with this situation for other loads?

It is expected to work for all load types, including routine load and stream load.

**Comment by chaoyli** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|

**Review by wyb — APPROVED** [review]

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|1|100.00%|

**Review by chaoyli — APPROVED** [review]
