### PR TITLE
[BugFix] update error when table with generate column (#25600)

### LINKED ISSUE #25600: [generate column] update error when table with generate column
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE t1(
a int,
b int,
c int,
d bigint as b+c)
primary KEY (a)
DISTRIBUTED BY HASH(a);

insert into t1 values (1,1,1);
update t1 set b=2 where d=2;
````

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
2023-06-19 21:04:25,670 WARN (starrocks-mysql-nio-pool-61|530) [StmtExecutor.execute():615] execute Exception, sql update t1 set b=2 where d=2
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:496) ~[spark-dpp-1.0.0.jar:?]
	at com.starrocks.sql.analyzer.UpdateAnalyzer.analyze(UpdateAnalyzer.java:236) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitUpdateStatement(Analyzer.java:372) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.visitUpdateStatement(Analyzer.java:143) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.UpdateStmt.accept(UpdateStmt.java:109) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.ast.AstVisitor.visit(AstVisitor.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer$AnalyzerVisitor.analyze(Analyzer.java:145) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.analyzer.Analyzer.analyze(Analyzer.java:140) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:71) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:55) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:408) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:359) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:473) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:739) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_292]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-9547469`

### PR DESCRIPTION
**Pull request by srlch**
Fix the following Problems:
1. The variable selectlist in the update analyzer miss for generated column causing NPE problem
2. The update stmt with partial update mode will write the partial segment file
    and does not need all slotDescriptor except for generated column.
    Because generated can not be set in the assignment list but it must 
    be computed and written in the OlapTableSink phase.
4. partial update for update stmt could not miss all ref columns for all generated columns.

Fixes #25600

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 22 (04.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|0|20|00.00%|[154, 181, 182, 183, 184, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 204, 205]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|2|50.00%|[88]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 22 (04.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|0|20|00.00%|[154, 181, 182, 183, 184, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 204, 205]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|2|50.00%|[88]|

File: fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java [hunk 1]
```diff
@@ -84,8 +84,10 @@ public ExecPlan plan(UpdateStmt updateStmt, ConnectContext session) {
             long tableId = table.getId();
             List<Pair<Integer, ColumnDict>> globalDicts = Lists.newArrayList();
             for (Column column : table.getFullSchema()) {
-                if (updateStmt.usePartialUpdate() && !updateStmt.isAssignmentColumn(column.getName()) && !column.isKey()) {
-                    // When using partial update, skip columns which aren't key column and not be assign
+                if (updateStmt.usePartialUpdate() && !column.isMaterializedColumn() &&
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java:87]: What's this meaning?
The generated column can be not written in the update DML?

Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/sql/UpdatePlanner.java:87]: In partial update mode, generated column must be computed in OlapTableSink phase and can not be done in apply. The code here means that we SHOULD computed and write the generated column in the OlapTableSink phase. And it does not means that we could rewritten the  generated column using some specified value by user. e.g. update t set generated_column = value where pk = xxx will always throw an exception.

**Review by luohaha — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 22 (04.55%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|0|20|00.00%|[154, 181, 182, 183, 184, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 204, 205]|
|:large_blue_circle:|com/starrocks/sql/UpdatePlanner.java|1|2|50.00%|[88]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
