### PR TITLE
[BugFix] Fix the issue where tablets fail to load completely from datadir

### LINKED ISSUE #58203: Query Failures Due to Missing Rowset Files
I am encountering inconsistent behavior when querying a specific table in StarRocks. Sometimes the query runs successfully, while at other times, I receive one of two different errors. Upon checking the statistics on the FE dashboard, all tablets appear to be healthy. However, the issue seems isolated to a specific BE instance: BE:10003.

### Steps to reproduce the behavior (Required)
Create Table Command
```
CREATE TABLE trip_history_partitioned(
    id VARCHAR(36) NOT NULL,
    updated_at DATETIME,
    created_at DATETIME ,
    deleted_at DATETIME,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    deleted_by VARCHAR(255),
    version INT,
    rider_id VARCHAR(36),
    is_valid BOOLEAN,
    status VARCHAR(255),
    extra_details JSON,
    INDEX trip_idx_status (status) USING BITMAP,
)
ENGINE=olap
PRIMARY KEY (id, updated_at)
PARTITION BY date_trunc('day', updated_at)
ORDER BY (updated_at, status, rider_id)
PROPERTIES (
    'replication_num' = '2',
    'enable_persistent_index' = 'true',
    'partition_live_number' = '90'
);
```

- Select Query

`select * from dms.trip_history_partitioned `

- Statistic From FE:

Image

### Expected behavior (Required)
The table query should return results consistently without errors, provided that all tablets are healthy.

### Real behavior (Required)
Occasional query failures occur with errors pointing to a single BE instance (BE:10003). Errors observed:

```
mysql error: get_applied_rowsets failed, tablet updates is in error state:
tablet:10738 apply tablet: 10738 failed, status: Not found:
_apply_rowset_commit error: load primary index failed:
Not found: Load rowset failed tablet:10738 rowset:0200000001577e71ad442d093b1cb2c06476d3ac82ded5a6
rssid:578 seg:0 path:/opt/starrocks/be/storage/data/120/10738/1590713962/0200000001577e71ad442d093b1cb2c06476d3ac82ded5a6_0.dat:
No such file or directory
```

```
mysql error: Load rowset failed tablet:474794 rowset:02000000015764adad442d093b1cb2c06476d3ac82ded5a6
rssid:18 seg:0 path:/opt/starrocks/be/storage/data/161/474794/1590713962/02000000015764adad442d093b1cb2c06476d3ac82ded5a6_0.dat:
No such file or directory: BE:10003
```
### StarRocks version (Required)

- 3.3.12-4cd554b

### PR DESCRIPTION
**Pull request by luohaha**
## Why I'm doing:
You can get more info about this issue from #58203

Conclusion is that this BUG occurs because our code fails to properly handle exceptions during the data directory loading process, resulting in a large number of tablets failing to load correctly. Consequently, when this BE node processes subsequently added tablets, it conflicts with the metadata of existing tablets, leading to a "file not found" error state.

## What I'm doing:

Ensure that ​​DataDir::load​​ does not get interrupted by unnecessary exception throws during execution, as the outer layer does not handle error codes. So we must ensure that all tablets are either properly loaded or handled within load().

Fixes #58203

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: be/src/storage/data_dir.cpp [hunk 1]
```diff
@@ -302,14 +303,14 @@ Status DataDir::load() {
...
         Status s = _kv_store->compact();
         if (!s.ok()) {
+            // We don't need to make sure compact MUST success. Just ignore the error.
             LOG(ERROR) << "data dir " << _path << " compact meta before load failed";
-            return s;
         }
         for (auto tablet_id : tablet_ids) {
             Status s = _tablet_manager->drop_tablet(tablet_id, kKeepMetaAndFiles);
             if (!s.ok()) {
+                // Only print log, do not return error. Later load tablet from rocksdb can handle this.
```
Comment (kevincai) [inline be/src/storage/data_dir.cpp:312]: LOG messge on line 316 needs an update.

File: be/src/storage/data_dir.cpp [hunk 2]
```diff
@@ -269,7 +269,8 @@ std::string DataDir::get_root_path_from_schema_hash_path_in_trash(const std::str
             .string();
 }
 
-// TODO(ygl): deal with rowsets and tablets when load failed
+// [NOTICE] We will igore error throw by load(),
+// so we must ensure that all tablets are either properly loaded or handled within load().
```
Comment (kevincai) [inline be/src/storage/data_dir.cpp:273]: or change it to `void DataDir::load()`

Comment (luohaha) [reply be/src/storage/data_dir.cpp]: done

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]
