### PR TITLE
[pipeline] use ContextBase to short-circuit and close complex operators

### LINKED ISSUE #1382: [pipeline] Crash when the subsequent operator of Aggregate Sink is finished early
### Steps to reproduce the behavior (Required)
1. dataset
TPC-H

2. Query SQL
```SQL
select
  cntrycode,
  count(*) as numcust,
  sum(c_acctbal) as totacctbal
from
  (
    select
      substr(c_phone, 1, 2) as cntrycode,
      c_acctbal
    from
      customer
    where
      substr(c_phone, 1, 2) in
        ('13', '31', '23', '29', '30', '18', '17')
      and c_acctbal > ( 
        select
          avg(c_acctbal)
        from
          customer
        where
          c_acctbal > 0.00
          and substr(c_phone, 1, 2) in
            ('13', '31', '23', '29', '30', '18', '17')
      )   
      and not exists (
        select
          *
        from
          orders
        where
          o_custkey = c_custkey
      )   
  ) as custsale
group by
  cntrycode
order by
  cntrycode;

```

### Expected behavior (Required)
The result is the same the non-pipeline result.

### Real behavior (Required)
Sometimes, BE crashed.

### Reason
The complex ExecNode is usually decomposed to multiple operators, which share some variables in a context, and have dependency relationships between them.
For example, HashJoinNode is composed to HashJoinBuildOperator and HashJoinProbeOperator,
which share a HashJoiner context. And HashJoinProbeOperator depends on HashJoinBuildOperator.

Assume `OpA` depends on `OpB`.
However, `OpA` can be finished earlier than OpB, if it's successor operator is finished early.
Therefore, there are two problems which needs to be considered:
1. `OpB` should perceive that `OpA` has been finished early.
2. Context object can be released only if both `OpA` and `OpB` are closed,
   because the close order of `OpA` and `OpB` are uncertain.

An example is as follows. 
1. `HashJoinBuild` in pipeline1 is finished and the hash table is empty.
2. `HashJoinProbe` in pipeline2 is finished immediately, and so as `SinkOperator` and `AggregateSource` in pipeline2. 
3. `SinkOperator` in pipeline2 is finished means the pipeline2 is finished, which will close all the operators in pipeline2.
4. Therefore, `AggregateSource` is closed, which closes `AggregateContext`. However, `AggregateSink` may be still running, and use `AggregateContext`, which causes BE crashed.

Sink Stop early

### PR DESCRIPTION
**Pull request by ZiheLiu**
For example, HashJoinNode is composed to HashJoinBuildOperator and HashJoinProbeOperator,
which share a HashJoiner context. And HashJoinProbeOperator depends on HashJoinBuildOperator.
> 
> Assume `OpA` depends on `OpB`.
However, `OpA` can be finished earlier than OpB, if its successor operator is finished early.
Therefore, there are two problems which needs to be considered:
> 1. `OpB` should perceive that `OpA` has been finished early.
> 2. Context object can be released only if both `OpA` and `OpB` are closed,  because the close order of `OpA` and `OpB` are uncertain.

### Changes
1. Add a class `pipeline::ContextBase`.
    -  `ref_no_barrier()` and `unref()` use  an atomic variable to guarantee that the context will be closed when the last running operator is closed.
    - `set_finished()` and `is_finished()` is used to mark output operator is finished, and non-output operator can be finished immediately.
2.  Call  `ContextBase::ref_no_barrier()` in the constructor of `XxxSinkOperator` and `XxxSourceOperator`.
3. Call `ContextBase::unref()` in `close()` of `XxxSinkOperator` and `XxxSourceOperator`.
4. Call `ContextBase::set_finished()` in `set_finished()` of `XxxSourceOperator`.
5. Call  `ContextBase::is_finished()` in `is_finished()` of `XxxSinkOperator`.

Fix #1382

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Comment by satanson** [comment]
create a issue and link the issue to this PR

File: be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.h [hunk 1]
```diff
@@ -11,12 +11,17 @@ namespace starrocks::pipeline {
...
+        _aggregator->create_one_operator();
+    }
+
     ~AggregateBlockingSourceOperator() override = default;
 
     bool has_output() const override;
     bool is_finished() const override;
-    void set_finishing(RuntimeState* state) override;
+    // set_finishing does nothing.
+    void set_finishing(RuntimeState* state) override {}
```
Comment (liuyehcf) [inline be/src/exec/pipeline/aggregate/aggregate_blocking_source_operator.h:23]: The default implementation can be placed in Operator

File: be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_source_operator.h [hunk 2]
```diff
@@ -12,12 +12,17 @@ class AggregateDistinctBlockingSourceOperator : public SourceOperator {
...
+              _aggregator(std::move(aggregator)) {
+        _aggregator->create_one_operator();
+    }
+
     ~AggregateDistinctBlockingSourceOperator() override = default;
 
     bool has_output() const override;
     bool is_finished() const override;
-    void set_finishing(RuntimeState* state) override;
+    // set_finishing does nothing.
```
Comment (liuyehcf) [inline be/src/exec/pipeline/aggregate/aggregate_distinct_blocking_source_operator.h:23]: As above

File: be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.h [hunk 3]
```diff
@@ -12,12 +12,17 @@ class AggregateDistinctStreamingSourceOperator : public SourceOperator {
...
+        _aggregator->create_one_operator();
+    }
+
     ~AggregateDistinctStreamingSourceOperator() override = default;
 
     bool has_output() const override;
     bool is_finished() const override;
-    void set_finishing(RuntimeState* state) override;
+    // set_finishing does nothing.
+    void set_finishing(RuntimeState* state) override {}
```
Comment (liuyehcf) [inline be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.h:24]: As above

File: be/src/exec/pipeline/aggregate/aggregate_streaming_source_operator.cpp [hunk 4]
```diff
@@ -47,10 +47,14 @@ void AggregateStreamingSourceOperator::set_finishing(RuntimeState* state) {
     _is_finished = true;
 }
 
+void AggregateStreamingSourceOperator::set_finished(RuntimeState* state) {
+    _aggregator->set_finished();
+}
+
 Status AggregateStreamingSourceOperator::close(RuntimeState* state) {
     // _aggregator is shared by sink operator and source operator
     // we must only close it at source operator
```
Comment (liuyehcf) [inline be/src/exec/pipeline/aggregate/aggregate_streaming_source_operator.cpp:56]: Sink aggregator will be closed at both sink/source operators, change or remove this comment

File: be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp [hunk 5]
```diff
@@ -12,8 +12,9 @@ Status AggregateBlockingSinkOperator::prepare(RuntimeState* state) {
     return _aggregator->open(state);
 }
 
-bool AggregateBlockingSinkOperator::is_finished() const {
-    return _is_finished;
+Status AggregateBlockingSinkOperator::close(RuntimeState* state) {
+    RETURN_IF_ERROR(_aggregator->close_one_operator(state));
```
Comment (satanson) [inline be/src/exec/pipeline/aggregate/aggregate_blocking_sink_operator.cpp:16]: close/create_one_operator are confusing,  it's a refcount of close/create operations.  suggest to rename 
 them to:
1. ref()/unref(): referring to src/util/callback_closure.h, leveldb also use Ref/Unref.
2. AddRef()/Release(): referring to src/gutil/ref_counted.cc

File: be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.cpp [hunk 6]
```diff
@@ -29,14 +29,14 @@ bool AggregateDistinctStreamingSourceOperator::is_finished() const {
...
 
-void AggregateDistinctStreamingSourceOperator::set_finishing(RuntimeState* state) {
-    _is_finished = true;
+void AggregateDistinctStreamingSourceOperator::set_finished(RuntimeState* state) {
+    _aggregator->set_finished();
 }
 
 Status AggregateDistinctStreamingSourceOperator::close(RuntimeState* state) {
     // _aggregator is shared by sink operator and source operator
     // we must only close it at source operator
```
Comment (liuyehcf) [inline be/src/exec/pipeline/aggregate/aggregate_distinct_streaming_source_operator.cpp:38]: Sink aggregator will be closed at both sink/source operators, change or remove this comment

File: be/src/exec/pipeline/analysis/analytic_sink_operator.cpp [hunk 7]
```diff
@@ -38,8 +38,13 @@ Status AnalyticSinkOperator::prepare(RuntimeState* state) {
...
 }
 
+Status AnalyticSinkOperator::close(RuntimeState* state) {
+    RETURN_IF_ERROR(_analytor->close_one_operator(state));
+    return Operator::close(state);
+}
+
 bool AnalyticSinkOperator::is_finished() const {
-    return _is_finished;
+    return _is_finished || _analytor->is_finished();
```
Comment (liuyehcf) [inline be/src/exec/pipeline/analysis/analytic_sink_operator.cpp:47]: Be consistent with the previous changes, move this to header file

File: be/src/exec/pipeline/analysis/analytic_source_operator.h [hunk 8]
```diff
@@ -11,12 +11,16 @@ namespace starrocks::pipeline {
...
+            : SourceOperator(id, "analytic_source", plan_node_id), _analytor(std::move(analytor)) {
+        _analytor->create_one_operator();
+    }
     ~AnalyticSourceOperator() override = default;
 
     bool has_output() const override;
     bool is_finished() const override;
-    void set_finishing(RuntimeState* state) override;
+    // set_finishing does nothing.
+    void set_finishing(RuntimeState* state) override {}
```
Comment (liuyehcf) [inline be/src/exec/pipeline/analysis/analytic_source_operator.h:22]: As memtioned above

File: be/src/exec/pipeline/set/except_output_source_operator.h [hunk 9]
```diff
@@ -26,8 +28,9 @@ class ExceptOutputSourceOperator final : public SourceOperator {
         return _except_ctx->is_dependency_finished(_dependency_index) && _except_ctx->is_output_finished();
     }
 
-    // Finish is noop.
+    // set_finishing does nothing.
     void set_finishing(RuntimeState* state) override {}
```
Comment (liuyehcf) [inline be/src/exec/pipeline/set/except_output_source_operator.h:32]: As memtioned above

File: be/src/exec/pipeline/crossjoin/cross_join_context.h [hunk 10]
```diff
@@ -7,14 +7,17 @@
 
 #include "column/chunk.h"
 #include "column/vectorized_fwd.h"
+#include "exec/pipeline/context_base.h"
 
 namespace starrocks::pipeline {
 
-class CrossJoinContext {
+class CrossJoinContext : public ContextBase {
```
Comment (kangkaisen) [inline be/src/exec/pipeline/crossjoin/cross_join_context.h:14]: Should mark `final`  to all final subclasses.

File: be/src/exec/pipeline/context_base.h [hunk 11]
```diff
@@ -0,0 +1,63 @@
...
+    // without calling ref and unref.
+    virtual Status close(RuntimeState* state) = 0;
+
+    // ref_no_barrier and unref are used to close context
+    // when the last running related operator is closed.
+    // - ref_no_barrier is called by operator::constructor() at the preparation stage.
+    // - unref is called by operator::close() at the close stage.
+    // It is the guaranteed by the dispatcher queue that the increment operations
+    // by ref_no_barrier() are visible to unref(), so we needn't barrier here.
+    void ref_no_barrier() { _num_running_operators.fetch_add(1, std::memory_order_relaxed); }
```
Comment (kangkaisen) [inline be/src/exec/pipeline/context_base.h:41]: Why the name need `no_barrier`?

File: be/src/exec/pipeline/context_base.h [hunk 12]
```diff
@@ -0,0 +1,63 @@
...
+    ContextBase() = default;
+    ~ContextBase() = default;
+
+    ContextBase(const ContextBase&) = delete;
+    ContextBase(ContextBase&&) = delete;
+    ContextBase& operator=(ContextBase&&) = delete;
+    ContextBase& operator=(const ContextBase&) = delete;
+
+    // For pipeline, it is called by unref() when the last operator is unreffed.
+    // For non-pipeline, it is called by close() of the exec node directly
```
Comment (kangkaisen) [inline be/src/exec/pipeline/context_base.h:31]: Why non-pipeline will call this class method?

File: be/src/exec/pipeline/context_base.h (hunk 11 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/context_base.h:41]: The reason is that we only use **relaxed** memory order instead of more serious memory order in `ref_no_barrier()`.

File: be/src/exec/pipeline/context_base.h (hunk 12 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/context_base.h:31]: `Aggregator` is also used by `AggregateBlockingNode` and `AggregateStreamingNode`, let me add some comment.

File: be/src/exec/pipeline/context_base.h (hunk 11 above)
Comment (kangkaisen) [reply be/src/exec/pipeline/context_base.h:41]: I see. but i think for method name, ref is enough.

**Review by satanson — DISMISSED** [review]

File: be/src/exec/pipeline/context_base.h (hunk 11 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/context_base.h]: Sounds great. Let me rename it.

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
