### PR TITLE
[BugFix] Support Iceberg multi level namespace and vended-credentials

### LINKED ISSUE #50585: Iceberg-REST s3.path-style-access flag is not honored
### Steps to reproduce the behavior (Required)
Launch an iceberg-rest catalog and minio in a docker container. I created an example that can be run with docker-compose:
```sh
git clone https://github.com/hansetag/iceberg-catalog.git
git checkout ct/starrocks-integration
cd iceberg-catalog

docker build -t localhost/iceberg-catalog-local:latest -f docker/full.Dockerfile .
export ICEBERG_REST_TEST_SPARK_IMAGE=apache/spark:3.5.1-java17-python3
export ICEBERG_REST_TEST_SERVER_IMAGE=localhost/iceberg-catalog-local:latest
cd tests
docker compose run spark /opt/entrypoint.sh bash -c "cd /opt/tests && bash run_starrocks.sh"
```

In the example the following steps are run
1. 
```sql
        CREATE EXTERNAL CATALOG rest_catalog
        PROPERTIES
        (
            "type" = "iceberg",
            "iceberg.catalog.type" = "rest",
            "iceberg.catalog.uri" = "{warehouse.server.catalog_url}",
            "iceberg.catalog.warehouse" = "{warehouse.project_id}/{warehouse.warehouse_name}",
            "header.x-iceberg-access-delegation" = "vended-credentials",
            "iceberg.catalog.oauth2-server-uri" = "{OPENID_PROVIDER_URL}",
            "iceberg.catalog.credential" = "{OPENID_CLIENT_ID}:{OPENID_CLIENT_SECRET}"
        )
```

2. `SET CATALOG rest_catalog`
3.  `CREATE DATABASE test_create_table_with_data_starrocks`
4. `CREATE TABLE test_create_table_with_data_starrocks.my_table (my_ints INT, my_floats DOUBLE, strings VARCHAR)`
5. `INSERT INTO test_create_table_with_data_starrocks.my_table VALUES (1, 1.0, 'a'), (2, 2.0, 'b')`

### Expected behavior (Required)
It works

### Real behavior (Required)
```log
2024-09-02 13:04:09.365Z WARN (thrift-server-pool-236|431) [DefaultCoordinator.updateFragmentExecStatus():948] exec state report failed status=errorCode IO_ERROR S3: Fail to create multipart upload for object tests/0191b2d5-2237-7293-809f-c62e91f11e83/0191b2d5-223d-7fa3-8346-c370eb206844/data/b91250cd-692b-11ef-8898-1a79bacc43a1_0_0_0.parquet: curlCode: 6, Couldn't resolve host name, query_id=b91250cd-692b-11ef-8898-1a79bacc43a1, instance_id=b91250cd-692b-11ef-8898-1a79bacc43a2, backend_id=10001
 2024-09-02 13:04:09.365Z WARN (thrift-server-pool-236|431) [DefaultCoordinator.updateStatus():762] one instance report fail throw updateStatus(), need cancel. job id: -1, query id: b91250cd-692b-11ef-8898-1a79bacc43a1, instance id: b91250cd-692b-11ef-8898-1a79bacc43a2
 2024-09-02 13:04:09.366Z WARN (starrocks-mysql-nio-pool-1|405) [StmtExecutor.handleDMLStmt():2146] insert failed: S3: Fail to create multipart upload for object tests/0191b2d5-2237-7293-809f-c62e91f11e83/0191b2d5-223d-7fa3-8346-c370eb206844/data/b91250cd-692b-11ef-8898-1a79bacc43a1_0_0_0.parquet: curlCode: 6, Couldn't resolve host name
 2024-09-02 13:04:09.366Z WARN (starrocks-mysql-nio-pool-1|405) [StmtExecutor.handleDMLStmt():2300] failed to handle stmt [INSERT INTO test_create_table_with_data_starrocks.my_table VALUES (1, 1.0, 'a'), (2, 2.0, 'b')] label: b91250cd-692b-11ef-8898-1a79bacc43a1
 com.starrocks.common.DdlException: S3: Fail to create multipart upload for object tests/0191b2d5-2237-7293-809f-c62e91f11e83/0191b2d5-223d-7fa3-8346-c370eb206844/data/b91250cd-692b-11ef-8898-1a79bacc43a1_0_0_0.parquet: curlCode: 6, Couldn't resolve host name
        at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:95)
        at com.starrocks.qe.StmtExecutor.handleDMLStmt(StmtExecutor.java:2147)
        at com.starrocks.qe.StmtExecutor.handleDMLStmtWithProfile(StmtExecutor.java:1926)
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:673)
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:355)
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:550)
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:884)
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2024-09-02 13:04:09.367Z ERROR (starrocks-mysql-nio-pool-1|405) [MetadataMgr.getOptionalMetadata():181] Failed to get rest_catalog catalog
 2024-09-02 13:04:09.367Z WARN (starrocks-mysql-nio-pool-1|405) [StmtExecutor.handleDMLStmtWithProfile():1928] DML statement(INSERT INTO test_create_table_with_data_starrocks.my_table VALUES (1, 1.0, 'a'), (2, 2.0, 'b')) process failed.
 com.starrocks.common.UserException: S3: Fail to create multipart upload for object tests/0191b2d5-2237-7293-809f-c62e91f11e83/0191b2d5-223d-7fa3-8346-c370eb206844/data/b91250cd-692b-11ef-8898-1a79bacc43a1_0_0_0.parquet: curlCode: 6, Couldn't resolve host name
        at com.starrocks.qe.StmtExecutor.handleDMLStmt(StmtExecutor.java:2348)
        at com.starrocks.qe.StmtExecutor.handleDMLStmtWithProfile(StmtExecutor.java:1926)
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:673)
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:355)
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:550)
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:884)
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.starrocks.common.DdlException: S3: Fail to create multipart upload for object tests/0191b2d5-2237-7293-809f-c62e91f11e83/0191b2d5-223d-7fa3-8346-c370eb206844/data/b91250cd-692b-11ef-8898-1a79bacc43a1_0_0_0.parquet: curlCode: 6, Couldn't resolve host name
        at com.starrocks.common.ErrorReport.reportDdlException(ErrorReport.java:95)
        at com.starrocks.qe.StmtExecutor.handleDMLStmt(StmtExecutor.java:2147)
        ... 9 more
```

### StarRocks version (Required)
3.3.2

### PR DESCRIPTION
**Pull request by Smith-Cruise**
## Why I'm doing:
Support nested namespace access, like Polaris.
```sql
mysql> select * from iceberg_rest.`ns1.ns2.tpch_namespace`.tbl;                                                                         
+------+                                                                                                                                
| c1   |                                                                                                                                
+------+                                                                                                                                
| 1    |                                                                                                                                
| 2    |                                                                                                                                
| 3    |                                                                                                                                
+------+                                                                                                                                
3 rows in set (4.55 sec)
```

Support vended-credentials, create catalog like this:
```sql
CREATE EXTERNAL CATALOG iceberg_rest 
PROPERTIES (   
    "iceberg.catalog.uri"  = "http://localhost:8181/api/catalog",   
    "type"  =  "iceberg",   
    "iceberg.catalog.type"  =  "rest",   
    "iceberg.catalog.warehouse" = "starrocks_catalog",
    "iceberg.catalog.credential" = "f7357cfbe9583aa1:7b90fc77e4fbe288a5c41eaa05da3a3b",
    "iceberg.catalog.scope"='PRINCIPAL_ROLE:ALL',
    "iceberg.catalog.client.region" = "us-west-2"
 );
```

You can also disable vended-credentials like this:
```sql
CREATE EXTERNAL CATALOG iceberg_rest 
PROPERTIES (   
    "iceberg.catalog.uri"  = "http://localhost:8181/api/catalog",   
    "type"  =  "iceberg",   
    "iceberg.catalog.type"  =  "rest",   
    "iceberg.catalog.warehouse" = "starrocks_catalog",
    "iceberg.catalog.credential" = "f7357cfbe9583aa1:7b90fc77e4fbe288a5c41eaa05da3a3b",
    "iceberg.catalog.scope"='PRINCIPAL_ROLE:ALL',
    "iceberg.catalog.client.region" = "us-west-2",
    "iceberg.catalog.vended-credentials-enabled"="false"
 );
```

We recommend to use oauth2 to authentication, so add below new parameters

`iceberg.catalog.security`: The type of security to use (default: NONE). OAUTH2 requires either a token or credential. Example: OAUTH2
`iceberg.catalog.oauth2.token`: The bearer token used for interactions with the server. A token or credential is required for OAUTH2 security. Example: AbCdEf123456
`iceberg.catalog.oauth2.credential`:  The credential to exchange for a token in the OAuth2 client credentials flow with the server. A token or credential is required for OAUTH2 security. Example: AbCdEf123456
`iceberg.catalog.oauth2.scope`: Scope to be used when communicating with the REST Catalog. Applicable only when using credential.
`iceberg.catalog.oauth2.server-uri`: The endpoint to retrieve access token from OAuth2 Server.

For example you can create catalog like:
```sql
CREATE EXTERNAL CATALOG new_iceberg_rest 
PROPERTIES (   
    "iceberg.catalog.uri"  = "http://localhost:8181/api/catalog",   
    "type"  =  "iceberg",   
    "iceberg.catalog.type"  =  "rest",   
    "iceberg.catalog.warehouse" = "starrocks_catalog",
    "iceberg.catalog.security" = "oauth2",
    "iceberg.catalog.oauth2.credential" = "f7357cfbe9583aa1:7b90fc77e4fbe288a5c41eaa05da3a3b",
    "iceberg.catalog.oauth2.scope"='PRINCIPAL_ROLE:ALL',
    "iceberg.catalog.client.region" = "us-west-2"
 );
```

## What I'm doing:

Fix #50585 #52451

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java [hunk 1]
```diff
@@ -130,11 +131,11 @@ default StarRocksIcebergTableScan getTableScan(Table table, StarRocksIcebergTabl
                 srScanContext);
     }
 
-    default String defaultTableLocation(String dbName, String tableName) {
+    default String defaultTableLocation(Namespace ns, String tableName) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java:134]: Why only modify params of these two methods?

Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/connector/iceberg/IcebergCatalog.java:134]: Because these two functions only used in rest-catalog, change it's signature will not affect other's code.

**Review by dirtysalt — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
