### PR TITLE
[BugFix]Fix truncate table throws NPE bug

### LINKED ISSUE #16773: [BUG] Truncate partition failure causes FE crash
### Steps to reproduce the behavior (Required)
1. Create a dynamic partition table with large number partitions and set start = -1 .
2. Truncate the table and the operation will fail with NPE.
3. Load data to the table.

### Expected behavior (Required)
System runs normally

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16773

## Problem Summary(Required) ：

Check existence of partition should be done from the existing olapTable, not the copiedTbl, copiedTbl will never change.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 3 (66.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|3|66.67%|[4525]|

File: fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java [hunk 1]
```diff
@@ -4519,9 +4519,10 @@ public void truncateTable(TruncateTableStmt truncateTableStmt) throws DdlExcepti
 
             // check partitions
             for (Map.Entry<String, Partition> entry : origPartitions.entrySet()) {
-                Partition partition = copiedTbl.getPartition(entry.getValue().getId());
+                Partition partition = olapTable.getPartition(entry.getValue().getId());
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java:4522]: Add a cast to test it.

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Comment by gengjun-git** [comment]
@mergify backport branch-2.5 branch-2.4 branch-2.3 branch-2.2
