### PR TITLE
[BugFix] Fix deadLock when routineLoad task abortTxn

### LINKED ISSUE #57420: Dead lock when commit & abort
for routine load:  concurrent task  is large than 1;   one task execute commit (loadTxnCommit), one task execute rollback (loadTxnRollback),   there is a possibility of deadlock

1:  commit lock order:   db/table lock,  transactionState lock,  routineLoadJob lock
2:  rollback lock order:   routineLoadJob lock,  transactionState lock, transactionLock, 

Image

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
working normally

### Real behavior (Required)
dead lock
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `3.3` ,`main`

### PR DESCRIPTION
**Pull request by hongli-my**
## Why I'm doing:

Fixes #57420 for routine load,   commit & abort will cause deadlock

## What I'm doing:

Fixes #57420

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

**Review by kevincai — DISMISSED** [review]

**Review by HangyuanLiu — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -601,11 +601,10 @@ public void abortTransaction(long transactionId, boolean abortPrepared, String r
             transactionState.setTxnCommitAttachment(txnCommitAttachment);
         }
 
+        transactionState.writeLock();
         // before state transform
         transactionState.beforeStateTransform(TransactionStatus.ABORTED);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:606]: better to move `beforeStateTransform`  into `try {}` block

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by hongli-my** [comment]
@HangyuanLiu please review

**Review by HangyuanLiu — APPROVED** [review]
