### PR TITLE
[BugFix] Reject query when non-existing column appear in the update statement

### LINKED ISSUE #10907: update operation should be report error when update column does not exist
### Steps to reproduce the behavior (Required)
```
mysql> create table pri_tbl(c1 int,c2 varchar,c3 date) primary key(c1) distributed by hash(c1);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into pri_tbl values(1,'A','2022-09-01'),(2,'B','2022-09-02');
Query OK, 2 rows affected (0.03 sec)
{'label':'insert_37a891ff-2ddd-11ed-8960-00163e14c85e', 'status':'VISIBLE', 'txnId':'11135'}

mysql> update pri_tbl set c4=10 where c1>0;
Query OK, 2 rows affected (0.03 sec)
{'label':'update_3d1cbfe4-2ddd-11ed-8960-00163e14c85e', 'status':'VISIBLE', 'txnId':'11137'}
```

### Expected behavior (Required)
update operation should be report error when update column does not exist

### Real behavior (Required)
update executed successfully

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE a3cda44 |
+----------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10907

## Problem Summary(Required) ：

```
mysql> create table pri_tbl(c1 int,c2 varchar,c3 date) primary key(c1) distributed by hash(c1);
Query OK, 0 rows affected (0.02 sec)

mysql> insert into pri_tbl values(1,'A','2022-09-01'),(2,'B','2022-09-02');
Query OK, 2 rows affected (0.03 sec)
{'label':'insert_37a891ff-2ddd-11ed-8960-00163e14c85e', 'status':'VISIBLE', 'txnId':'11135'}

mysql> update pri_tbl set c4=10 where c1>0;
Query OK, 2 rows affected (0.03 sec)
{'label':'update_3d1cbfe4-2ddd-11ed-8960-00163e14c85e', 'status':'VISIBLE', 'txnId':'11137'}
```
As mentioned above, update query still success even though target column does not exist in the table, not right.
So this PR reject query when non-existing column appear in target columns of update set assignment list.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java [hunk 1]
```diff
@@ -52,7 +52,11 @@ public static void analyze(UpdateStmt updateStmt, ConnectContext session) {
         List<ColumnAssignment> assignmentList = updateStmt.getAssignments();
         Map<String, ColumnAssignment> assignmentByColName = assignmentList.stream().collect(
                 Collectors.toMap(assign -> assign.getColumn().toLowerCase(), a -> a));
-
+        for (String colName : assignmentByColName.keySet()) {
+            if (table.getColumn(colName) == null) {
```
[the remark this answers is not in the document]
Comment (Linkerist) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java:56]: no, columns in the table are case-insensitive
https://github.com/StarRocks/starrocks/blob/1d2ee8276b421ec3e94a2a879a6c64e04d892793/fe/fe-core/src/main/java/com/starrocks/catalog/Table.java#L220-L222

https://github.com/StarRocks/starrocks/blob/1d2ee8276b421ec3e94a2a879a6c64e04d892793/fe/fe-core/src/main/java/com/starrocks/catalog/Table.java#L127

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Linkerist** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 3 / 4 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|4|75.00%|[57]|

**Review by chaoyli — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java [hunk 2]
```diff
@@ -52,7 +52,11 @@ public static void analyze(UpdateStmt updateStmt, ConnectContext session) {
...
+                throw new SemanticException("table '%s' do not existing column '%s'", tableName.getTbl(), colName);
```
Comment (decster) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java:57]: `do not exist`

Comment (decster) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java:57]: table '%s' do not existing column '%s'
table does not have column 'xxx'

**Comment by Linkerist** [comment]
@Mergifyio backport branch-2.4

**Comment by Linkerist** [comment]
@Mergifyio backport branch-2.3
