### PR TITLE
[BugFix] Fix check of overflow for converting floating to intergal

### LINKED ISSUE #49591: When int64 overflows, an error value is returned.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Expected behavior (Required)
NULL
### Real behavior (Required)
- x86 returns the smallest int64
- ARM returns the largest int64
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

### PR DESCRIPTION
**Pull request by ZiheLiu**
## Why I'm doing:
For floating-point numbers, we cannot use `value > (Type)std::numeric_limits<ResultType>::max()` to determine whether `value` exceeds the maximum value of ResultType. The reason is as follows:

`std::numeric_limits<ResultType>::max()` is `2^n-1`, where n is 63, 31, 15 or 7, this number cannot be exactly represented by floating-point numbers, so when converted to Type, it will be rounded up to `2^n`. Therefore, when `value` is `2^n`, `value > (Type)std::numeric_limits<ResultType>::max()` will return false. However, in actual conversion, overflow will occur, resulting in the maximum or minimum value of ResultType, depending on the architecture, compiler, and compilation parameters.

## What I'm doing:

Because `2^n` can be exactly represented by floating-point numbers, we use `value >= (Type)2^n` to determine whether it is overflow, rather than `value > (Type)2^n-1`.

Fixes #49591

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

## Documentation PRs only:

If you are submitting a PR that adds or changes English documentation and have not
included Chinese documentation, then you can check the box to request GPT to translate the
English doc to Chinese. Please ensure to uncheck the **Do not translate** box if translation is needed.
The workflow will generate a new PR with the Chinese translation after this PR is merged.

- [ ] Yes, translate English markdown files with GPT
- [x] Do not translate

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

File: be/src/util/numeric_types.h [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        static_cast<FromType>(std::numeric_limits<ToType>::lowest());
+
+template <typename FromType, typename ToType>
+static constexpr FromType floating_to_intergral_upper_bound = static_cast<FromType>(2) *
+                                                              (std::numeric_limits<ToType>::max() / 2 + 1);
+
+/// Check whether the value of type `FromType` overflows when converted to type `ToType`.
+/// If overflow, return true; otherwise, return false.
+template <typename FromType, typename ToType>
+bool check_number_overflow(FromType value) {
```
Comment (alvin-celerdata) [inline be/src/util/numeric_types.h:33]: NIT: It will be better to create UT for this function, easy to construct and cover corner cases. And it won't be influenced by the usage of this function.

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]
