### PR TITLE
Bugfix: getCommonTypeOfDecimalV3 should return a wider type

### LINKED ISSUE #3103: Decimal 64 cast error
### Steps to reproduce the behavior (Required)

```
1. DROP DATABASE IF EXISTS n9;
CREATE DATABASE n9;
USE n9;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 BIGINT NULL ,c_0_1 BOOLEAN NULL ,c_0_2 LARGEINT NOT NULL ,c_0_3 INT NOT NULL ,c_0_4 BOOLEAN NULL ,c_0_5 DOUBLE NOT NULL ,c_0_6 VARCHAR(51) NULL ,c_0_7 BOOLEAN NULL ,c_0_8 DECIMAL(28, 20)  NULL ,c_0_9 DATE NOT NULL ,c_0_10 DATETIME NOT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3) DISTRIBUTED BY HASH (c_0_3,c_0_2,c_0_0,c_0_1) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL(29, 1)  NOT NULL ,c_1_1 DATE NOT NULL ,c_1_2 CHAR(51) NULL ,c_1_3 DECIMAL(33, 16)  NULL ,c_1_4 BIGINT NOT NULL ,c_1_5 DATE NOT NULL ,c_1_6 DOUBLE NOT NULL ,c_1_7 DECIMAL(23, 9)  NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5) DISTRIBUTED BY HASH (c_1_1,c_1_4,c_1_2,c_1_3,c_1_5,c_1_0) properties("replication_num"="3") ;
INSERT INTO t0 VALUES (1046068023, false, 1513621755, 3, false, 0.9678057174026785, "", true, 6.1324042E-13, "1970-01-01", "1970-01-01 08:00:00"), (1373253845, true, 1667904941, 17, false, 0.3154281168104238, "aXylud", false, 3.6135162E-13, "1970-01-01", "1970-01-01 08:00:00"), (NULL, true, 730459795, 22, false, 0.23805926602491445, "p", NULL, 5.1869979E-13, "1970-01-01", "1970-01-01 08:00:00"), (-1458647320, false, 1046068023, 29, true, 0.7329231320658387, "a", true, 9.1627827E-13, "1970-01-01", "1970-01-01 08:00:00"), (1667904941, NULL, 953455359, 16, false, 0.9238870519959698, "", true, 3.8572772E-13, "1970-01-01", "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (213818431780779544149062587.6, "1970-01-01", "", 8.7109135671077497, -1496685915, "1970-01-01", 0.9856685729703683, 44908.582191355);
INSERT INTO t0 VALUES (1667904941, true, 1373253845, 1, NULL, 0.17592095962025456, "a04VGJfH3", true, 1.2409638E-13, "1970-01-01", "1970-01-01 08:00:00"), (730459795, true, 1880300121, 13, false, 0.18503599686172667, "e", false, 4.644948E-14, "1970-01-01", "1970-01-01 08:00:00");
INSERT INTO t0 VALUES (-2004583899, false, -2004583899, 28, true, 0.07506956840022072, "Fcj2", true, 8.8029645E-13, "1970-01-01", "1970-01-01 08:00:00"), (1207358419, true, 1168295397, 16, true, 0.9581873514108471, "", false, 3.4991301E-13, "1970-01-01", "1970-01-01 08:00:00");
INSERT INTO t0 VALUES (NULL, false, 1513621755, 16, true, 0.9581873514108471, "O863N", true, 1.782071E-14, "1970-01-01", "1970-01-01 08:00:00"), (1837613266, NULL, 1837613266, 13, false, 0.18741869447382586, NULL, true, 4.7170687E-13, "1970-01-01", "1970-01-01 08:00:00");
INSERT INTO t1 VALUES (629638963474094493277810613.5, "1970-01-01", "", NULL, -1219066683, "1970-01-01", 0.18741869447382586, 95474.072498365), (655264403566190509589084456.3, "1970-01-01", "", 4.0046334695743776, -2139571685, "1970-01-01", 0.5870164010461694, 58755.734712770);
INSERT INTO t1 VALUES (496135449423083832320990893.5, "1970-01-01", "xp", 6.9052879218670650, 730459795, "1970-01-01", 0.4184840211131412, 79623.860186445);
INSERT INTO t1 VALUES (443261319692938322156727792.8, "1970-01-01", "", NULL, -39813596, "1970-01-01", 0.12841605625949937, 43964.700420913), (412991552490639852757148275.9, "1970-01-01", "zFwr", 4.5646177235356029, -1219066683, "1970-01-01", -1.45864732E9, 7122.406335939);
INSERT INTO t1 VALUES (245340947483650346661043784.0, "1970-01-01", "", 8.5195272243113207, -2139571685, "1970-01-01", 0.9725835057364384, 24674.310106660), (268645619168659616549099666.8, "1970-01-01", "QJ", 3.0454716788290222, -1006828795, "1970-01-01", 0.1668336823273996, 65836.805586381), (951811286298399639256295756.6, "1970-01-01", NULL, 7.2232477778781406, -379638655, "1970-01-01", '+Inf', NULL);
INSERT INTO t1 VALUES (618734106926238829005093577.9, "1970-01-01", "T9ni", 2.0347632240619830, -1393839647, "1970-01-01", '-Inf', 63825.662334789), (627936368788221439207752894.1, "1970-01-01", "25Yb", 1.5210057625938190, 984021653, "1970-01-01", 0.8891807122377494, 59600.501485725);
INSERT INTO t0 VALUES (2048845826, false, -961708791, 10, NULL, 0.9324359419460211, "c", NULL, 5.8909122E-13, "1970-01-01", "1970-01-01 08:00:00"), (-350850758, false, 1207358419, 21, false, 0.9016888642786596, "Jy", true, 5.5884662E-13, "1970-01-01", "1970-01-01 08:00:00");
INSERT INTO t0 VALUES (NULL, true, -1414414988, 29, false, 0.9642879850721146, "h3", false, 3.4803004E-13, "1970-01-01", "1970-01-01 08:00:00");
mysql> SELECT COUNT(*) FROM t0 WHERE  ( 5 ) < ( CASE  WHEN true THEN CAST(t0.c_0_9 AS DECIMAL(7, 4) )   WHEN (NOT ((NOT ((t0.c_0_2)  BETWEEN (t0.c_0_2) AND (t0.c_0_2) )))) THEN 7  WHEN true THEN 4 END ) ;
+----------+
| count(*) |
+----------+
|       14 |
+----------+
mysql>  SELECT SUM(count) FROM (SELECT CAST((CAST( ( 5 ) < ( CASE  WHEN true THEN CAST(t0.c_0_9 AS DECIMAL(7, 4) )   WHEN (NOT ((NOT ((t0.c_0_2)  BETWEEN (t0.c_0_2) AND (t0.c_0_2) )))) THEN 7  WHEN true THEN 4 END )  AS BOOLEAN) = true) AND (CAST( ( 5 ) < ( CASE  WHEN true THEN CAST(t0.c_0_9 AS DECIMAL(7, 4) )   WHEN (NOT ((NOT ((t0.c_0_2)  BETWEEN (t0.c_0_2) AND (t0.c_0_2) )))) THEN 7  WHEN true THEN 4 END )  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t0 ) t;
+--------------+
| sum(`count`) |
+--------------+
|            0 |
+--------------+
```

```
2.DROP DATABASE IF EXISTS n8;
CREATE DATABASE n8;
USE n8;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BIGINT NOT NULL ,c_0_1 CHAR(1) NOT NULL ,c_0_2 VARCHAR(41) NULL ,c_0_3 INT NOT NULL ,c_0_4 DECIMAL(20, 2)  NOT NULL ,c_0_5 FLOAT NULL ,c_0_6 DATE NOT NULL ) DUPLICATE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_2,c_0_1) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 VARCHAR(31) NOT NULL ) DUPLICATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
TRUNCATE TABLE t0;
INSERT INTO t0 VALUES (-181285441, "", "", 21, 6511378705389569.77, NULL, "1970-01-01"), (765103985, "", "Wz", 11, 7749041067306443.39, 0.5698526651755422, "1970-01-01");
INSERT INTO t0 VALUES (328805824, "", "3YCK", 19, 2292425435669095.91, 0.6136085096295204, "1970-01-01"), (39149198, "", "4Re", 5, 3902528714624808.10, 0.8823705498673703, "1970-01-01"), (1595186900, "", "", 20, 2227042320670954.31, -2.55413265E8, "1970-01-01");
INSERT INTO t1 VALUES ("4GU");
INSERT INTO t0 VALUES (177389241, "", "", 11, 4246462021442979.68, 0.6761923955831359, "1970-01-01"), (2009362446, "", "mhJE7z", 23, 8339520643951730.93, 0.46159070509386857, "1970-01-01");
INSERT INTO t1 VALUES ("Q");
INSERT INTO t1 VALUES ("wQo"), ("Q"), ("");
INSERT INTO t0 VALUES (407895548, "", NULL, 24, 5806026306548648.48, 0.03614023722335957, "1970-01-01"), (1530047785, "", "HpEE", 16, 5113023770685791.12, 0.6826672942208825, "1970-01-01"), (882801678, "", "1f", 29, 8953085141533772.00, 0.5718429390378053, "1970-01-01"), (-2137092790, "", "PT", 23, 9161334251143233.29, 1.617697946E9, "1970-01-01"), (1137583221, "", "", 26, 7003009261032234.86, 0.1560704102688909, "1970-01-01");
INSERT INTO t1 VALUES (""), ("");
INSERT INTO t1 VALUES ("h"), ("p"), ("");
INSERT INTO t0 VALUES (1474824372, "", "dNWu", 6, 3542224135479398.07, 0.33334877769036064, "1970-01-01"), (1886908454, "", "9a6oVI", 13, 9595494137824630.40, 0.06571205570460015, "1970-01-01"), (-645364618, "", "WNmnd", 14, 893378785015013.11, 0.801728202577927, "1970-01-01"), (-386851588, "", "2o7", 28, 659450835432513.06, 0.6362734112137423, "1970-01-01");
INSERT INTO t0 VALUES (-2119454552, "", "8dJ", 2, 5793092142370635.25, -1.7976931348623157E308, "1970-01-01");
INSERT INTO t1 VALUES (""), ("UPe"), ("P");
INSERT INTO t0 VALUES (-1107062778, "", "", 8, 3372094212265199.45, 2.09046859E8, "1970-01-01"), (-2023589822, "", "n", 0, 9170388541941173.49, 0.8015163940087427, "1970-01-01");
INSERT INTO t0 VALUES (-579659363, "", "sH", 1, 9636681817857969.68, 0.2571476067225694, "1970-01-01");
INSERT INTO t0 VALUES (-632838192, "", "", 20, 6906933623977710.04, 1.691291714E9, "1970-01-01");
INSERT INTO t0 VALUES (315601172, "", "5", 1, 3616336330245913.83, 0.8327951854571767, "1970-01-01"), (1886889086, "", "", 11, 7198478651693211.21, 0.503122098468221, "1970-01-01");
mysql> SELECT COUNT(*) FROM  (SELECT t1.c_1_0 FROM t1 WHERE CASE  WHEN NULL_OR_EMPTY((("")||(CAST("" AS STRING ) )))  THEN (CASE  WHEN  ( "4" ) = ( "ar" )  THEN CASE  WHEN false THEN "" ELSE t1.c_1_0 END  WHEN (t1.c_1_0)  BETWEEN ((("")||(""))) AND ((("")||("U")))  THEN t1.c_1_0 ELSE ((CAST(t1.c_1_0 AS STRING ) )||("d")) END)  BETWEEN ((((("")||("")))||((((("q")||("")))||(""))))) AND (((LCASE("") )||((((("")||("FS")))||(((NULL)||("7")))))))   WHEN true THEN false END ORDER BY t1.c_1_0, t1.c_1_0 DESC, t1.c_1_0 ASC) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6 FROM t0 WHERE true) subt0 ON subt1.c_1_0 = subt0.c_0_6 AND subt1.c_1_0 != subt0.c_0_6 WHERE (subt0.c_0_5)  BETWEEN (POW(CAST(subt0.c_0_2 AS FLOAT ) , 0.034181035530687076) ) AND (subt0.c_0_5) ;
+----------+
| count(*) |
+----------+
|        3 |
+----------+

mysql> SELECT SUM(count) FROM (SELECT CAST((CAST((subt0.c_0_5)  BETWEEN (POW(CAST(subt0.c_0_2 AS FLOAT ) , 0.034181035530687076) ) AND (subt0.c_0_5)  AS BOOLEAN) = true) AND (CAST((subt0.c_0_5)  BETWEEN (POW(CAST(subt0.c_0_2 AS FLOAT ) , 0.034181035530687076) ) AND (subt0.c_0_5)  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM   (SELECT t1.c_1_0 FROM t1 WHERE CASE  WHEN NULL_OR_EMPTY((("")||(CAST("" AS STRING ) )))  THEN (CASE  WHEN  ( "4" ) = ( "ar" )  THEN CASE  WHEN false THEN "" ELSE t1.c_1_0 END  WHEN (t1.c_1_0)  BETWEEN ((("")||(""))) AND ((("")||("U")))  THEN t1.c_1_0 ELSE ((CAST(t1.c_1_0 AS STRING ) )||("d")) END)  BETWEEN ((((("")||("")))||((((("q")||("")))||(""))))) AND (((LCASE("") )||((((("")||("FS")))||(((NULL)||("7")))))))   WHEN true THEN false END ORDER BY t1.c_1_0, t1.c_1_0 DESC, t1.c_1_0 ASC) subt1 RIGHT ANTI JOIN (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6 FROM t0 WHERE true) subt0 ON subt1.c_1_0 = subt0.c_0_6 AND subt1.c_1_0 != subt0.c_0_6) t;
+--------------+
| sum(`count`) |
+--------------+
|            6 |
+--------------+
```

```
DROP DATABASE IF EXISTS n19;
CREATE DATABASE n19;
USE n19;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NOT NULL ,c_0_1 BOOLEAN NULL ,c_0_2 TINYINT NOT NULL ,c_0_3 DECIMAL(18, 11)  NULL ,c_0_4 TINYINT NOT NULL ,c_0_5 DATETIME NOT NULL ,c_0_6 VARCHAR(1) NULL ,c_0_7 LARGEINT NULL ,c_0_8 DECIMAL(7, 5)  NOT NULL ,c_0_9 FLOAT NULL ,c_0_10 BOOLEAN NULL ,c_0_11 DATETIME NOT NULL ,c_0_12 DOUBLE NULL ,c_0_13 DOUBLE NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8) DISTRIBUTED BY HASH (c_0_1,c_0_7,c_0_2) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 CHAR(41) NOT NULL ,c_1_1 BOOLEAN NULL ,c_1_2 CHAR(11) NOT NULL ,c_1_3 DECIMAL(22, 7)  NOT NULL ,c_1_4 DECIMAL(4, 0)  NULL ,c_1_5 VARCHAR(1) NULL ,c_1_6 DATETIME NULL ,c_1_7 VARCHAR(11) NULL ,c_1_8 VARCHAR(1) NOT NULL ,c_1_9 VARCHAR(11) NULL ,c_1_10 DATE NOT NULL ,c_1_11 BOOLEAN NOT NULL ,c_1_12 VARCHAR(1) NULL ,c_1_13 FLOAT NOT NULL ,c_1_14 DECIMAL(8, 2)  NOT NULL ,c_1_15 FLOAT NULL ,c_1_16 BOOLEAN NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8) DISTRIBUTED BY HASH (c_1_1,c_1_3,c_1_4,c_1_6,c_1_2,c_1_5,c_1_0) properties("replication_num"="3") ;
CREATE TABLE t2 (c_2_0 INT NOT NULL ,c_2_1 TINYINT NULL ,c_2_2 BOOLEAN REPLACE NULL ,c_2_3 BITMAP BITMAP_UNION NULL ,c_2_4 PERCENTILE PERCENTILE_UNION NULL ,c_2_5 DECIMAL(24, 14)  MAX NULL ,c_2_6 BITMAP BITMAP_UNION NOT NULL ,c_2_7 BOOLEAN REPLACE NOT NULL ,c_2_8 DECIMAL(30, 12)  SUM NULL ,c_2_9 BOOLEAN REPLACE NOT NULL ,c_2_10 BOOLEAN REPLACE NOT NULL ,c_2_11 DECIMAL(36, 16)  MAX NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="3") ;
INSERT INTO t2 VALUES (18, 6, true, bitmap_hash(""), percentile_hash("-200914361"), 0.00003282617141, bitmap_hash("q"), false, 621979.698965781857, true, false, 8260.4324721893088659);
TRUNCATE TABLE t0;
INSERT INTO t1 VALUES ("", true, "a", 43305140.3348096, 5466, "", "1970-01-01 08:00:00", "z", "", "yTXWxhP", "1970-01-01", false, "", 0.5125221009785109, 1896.60, 0.46961008935591253, false), ("", true, "", 60661927.4651407, 5225, "", "1970-01-01 08:00:00", "0bV", "", "", "1970-01-01", true, NULL, 0.7161513809990966, 2420.47, 0.29849729040603756, false);
INSERT INTO t1 VALUES ("n4S4", true, "t", 71581954.6018440, 196, "", "1970-01-01 08:00:00", "dF", "", "", "1970-01-01", true, "", 0.18026825126665247, 7943.55, 0.9136244798640146, true);
INSERT INTO t2 VALUES (9, 2, false, bitmap_hash("a1"), percentile_hash("-2068660665"), 0.00008502241972, bitmap_hash("QX"), false, 869595.994887632632, true, false, 8732.3586719476987267);
INSERT INTO t0 VALUES ("1970-01-01 08:00:00", true, 6, 0.00008531039, 2, "1970-01-01 08:00:00", "", -1129383145, 0.00072, NULL, false, "1970-01-01 08:00:00", 0.5266170518041832, 0.7751117286503127);
INSERT INTO t1 VALUES ("sDf2n", false, "a", 58213465.8012902, NULL, NULL, "1970-01-01 08:00:00", "", "", "A", "1970-01-01", true, "", 0.45752556689078006, 8845.37, 0.6040444503462647, true), ("Swm", true, "", 14641454.3376738, 1942, "", "1970-01-01 08:00:00", "7", "", NULL, "1970-01-01", false, "", 1.040928496E9, 5965.80, 0.6955139027210182, false);
INSERT INTO t0 VALUES ("1970-01-01 08:00:00", false, 2, 0.00004890047, 3, "1970-01-01 08:00:00", "", 920640194, 0.00034, -1.048446983E9, false, "1970-01-01 08:00:00", 0.41722859048372607, NULL), ("1970-01-01 08:00:00", NULL, 6, NULL, 5, "1970-01-01 08:00:00", NULL, 407449068, 0.00018, NULL, true, "1970-01-01 08:00:00", 0.07005898544695255, 0.7871498366386058), ("1970-01-01 08:00:00", false, 2, 0.00002090073, 5, "1970-01-01 08:00:00", "", 1042995026, 0.00001, 2.123165074E9, false, "1970-01-01 08:00:00", 0.22556422230418038, 0.2697613472870385);
DELETE FROM t0 WHERE c_0_0="1970-01-12 16:07:34" AND c_0_5="1969-12-09 23:27:57" AND c_0_1=true;
INSERT INTO t0 VALUES ("1970-01-01 08:00:00", true, 1, 0.00007106503, 1, "1970-01-01 08:00:00", "", 1790221897, 0.00095, 0.29116122993821325, false, "1970-01-01 08:00:00", 0.18698206548252982, 0.7392576733687922);
mysql> SELECT COUNT(*) FROM  t0 LEFT ANTI JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11, t1.c_1_12, t1.c_1_13, t1.c_1_14, t1.c_1_15, t1.c_1_16 FROM t1 WHERE true) subt1 ON t0.c_0_2 = subt1.c_1_10 AND t0.c_0_2 >= subt1.c_1_10 WHERE (t0.c_0_12)  BETWEEN (DPOW(CAST(CASE  WHEN NULL THEN t0.c_0_3 ELSE t0.c_0_3 END AS FLOAT ) , LOG(0.9727195114405448, 0.4678160512564973) ) ) AND (t0.c_0_12) ;
+----------+
| count(*) |
+----------+
|        4 |
+----------+
mysql> SELECT SUM(count) FROM (SELECT CAST((CAST((t0.c_0_12)  BETWEEN (DPOW(CAST(CASE  WHEN NULL THEN t0.c_0_3 ELSE t0.c_0_3 END AS FLOAT ) , LOG(0.9727195114405448, 0.4678160512564973) ) ) AND (t0.c_0_12)  AS BOOLEAN) = true) AND (CAST((t0.c_0_12)  BETWEEN (DPOW(CAST(CASE  WHEN NULL THEN t0.c_0_3 ELSE t0.c_0_3 END AS FLOAT ) , LOG(0.9727195114405448, 0.4678160512564973) ) ) AND (t0.c_0_12)  AS BOOLEAN) IS NOT NULL) AS INT) as count FROM   t0 LEFT ANTI JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6, t1.c_1_7, t1.c_1_8, t1.c_1_9, t1.c_1_10, t1.c_1_11, t1.c_1_12, t1.c_1_13, t1.c_1_14, t1.c_1_15, t1.c_1_16 FROM t1 WHERE true) subt1 ON t0.c_0_2 = subt1.c_1_10 AND t0.c_0_2 >= subt1.c_1_10) t;
+--------------+
| sum(`count`) |
+--------------+
|            5 |
+--------------+

```

```
DROP DATABASE IF EXISTS n3;
CREATE DATABASE n3;
USE n3;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 BOOLEAN NOT NULL ,c_0_1 VARCHAR(31) NULL ,c_0_2 CHAR(11) NOT NULL ,c_0_3 HLL HLL_UNION NULL ,c_0_4 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_5 HLL HLL_UNION NOT NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_0,c_0_1) properties("replication_num"="3") ;
CREATE TABLE t1 (c_1_0 BIGINT NOT NULL ) DUPLICATE KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 DECIMAL(16, 12)  NOT NULL ,c_2_1 CHAR(1) NOT NULL ,c_2_2 TINYINT NULL ,c_2_3 INT NULL ,c_2_4 BOOLEAN NOT NULL ,c_2_5 DECIMAL(19, 18)  NOT NULL ,c_2_6 VARCHAR(21) NULL ,c_2_7 SMALLINT NOT NULL ,c_2_8 BIGINT NOT NULL ,c_2_9 BOOLEAN NOT NULL ,c_2_10 BOOLEAN NOT NULL ,c_2_11 DATETIME NULL ,c_2_12 VARCHAR(11) NULL ,c_2_13 BOOLEAN NULL ,c_2_14 DATE NOT NULL ,c_2_15 VARCHAR(51) NULL ,c_2_16 VARCHAR(11) NULL ,c_2_17 DECIMAL(8, 7)  NOT NULL ) DUPLICATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6,c_2_7,c_2_8,c_2_9,c_2_10,c_2_11,c_2_12,c_2_13,c_2_14) DISTRIBUTED BY HASH (c_2_3,c_2_13,c_2_2,c_2_6,c_2_7) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t3 (c_3_0 DATETIME NOT NULL ,c_3_1 DATETIME NULL ,c_3_2 CHAR(11) NULL ,c_3_3 VARCHAR(11) NOT NULL ,c_3_4 CHAR(11) NOT NULL ,c_3_5 BOOLEAN NOT NULL ,c_3_6 BIGINT NOT NULL ,c_3_7 DOUBLE NOT NULL ) DUPLICATE KEY (c_3_0,c_3_1,c_3_2,c_3_3,c_3_4,c_3_5,c_3_6) DISTRIBUTED BY HASH (c_3_5,c_3_2,c_3_0) properties("replication_num"="3") ;
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "", "8nL", "u9G", true, -1889084753, 0.08440432439335688), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "h0SZ66", "oVJL7", "l", false, -1889084753, 0.5461331774172024), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "K", "7", "BwEiX", true, -1889084753, 0.4270657238192479);
TRUNCATE TABLE t0;
INSERT INTO t0 VALUES (true, "", "tO83", hll_hash("fbrBRX"), percentile_hash("1109605106"), hll_hash(""));
INSERT INTO t2 VALUES (9.927E-9, "", 4, 15, false, 6E-18, "vL", 4, -1889084753, false, false, NULL, "x4F", NULL, "1970-01-01", "PQnTD", "0", 1E-7);
INSERT INTO t1 VALUES (1138108299), (-1889084753);
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "", "", "", false, 1138108299, 0.981994891783431);
INSERT INTO t2 VALUES (5.588E-9, "", 7, 31, false, 2E-18, "FwSj6vkqI", 13, -1442456386, false, true, "1970-01-01 08:00:00", "o", NULL, "1970-01-01", "", "Ixu", 1E-7);
INSERT INTO t0 VALUES (false, "", "XP5", hll_hash("4r3goSD"), percentile_hash("-2144467165"), hll_hash("3"));
INSERT INTO t0 VALUES (true, "93H", "", hll_hash("4lC9"), percentile_hash("-1889084753"), hll_hash("TLtel79"));
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "", "", "", true, -1035053215, 0.489793352610551), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", NULL, "M5", "5", false, 1109605106, 0.4306449186475214);
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", NULL, "iT", "FHEJ", "", true, 1263780336, 0.805989988463808), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "pgKwPzT", "f", "4dY", false, -1204852640, -1.442456386E9);
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "Fp", "ATou4w4", "", false, 2096217524, 0.34431043228841285), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", NULL, "4", "", false, 1913401307, 0.26491919286723453);
INSERT INTO t1 VALUES (2064926448);
INSERT INTO t0 VALUES (false, "2Z", "h", hll_hash("zYrgd"), percentile_hash("499442268"), hll_hash("bPGj")), (true, "3uWYC", "9FrCEN", hll_hash("jM"), percentile_hash("930194311"), hll_hash("zBiecmUED"));
INSERT INTO t3 VALUES ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "TJLx", "8", "vr9bM", false, 463196325, 0.34431043228841285), ("1970-01-01 08:00:00", NULL, "1tT", "0XvLCx", "P95", true, -143304510, 0.26107869914667914), ("1970-01-01 08:00:00", "1970-01-01 08:00:00", "wVOVd5ZYi", "", "7TKfko", true, -553856167, 0.5539127522848989);
INSERT INTO t2 VALUES (1.448E-9, "", 4, 10, false, 2E-18, "uLX", 11, 2096217524, false, true, "1970-01-01 08:00:00", "XZx", true, "1970-01-01", NULL, "Xp", 3E-7);
INSERT INTO t0 VALUES (false, "e9F", "", hll_hash("G"), percentile_hash("1749135979"), hll_hash("")), (true, "", "3", hll_hash(""), percentile_hash("559993258"), hll_hash("aV8")), (true, "", "", hll_hash(""), percentile_hash("313384528"), hll_hash("Tm"));
INSERT INTO t1 VALUES (-1852902655), (983290343);
INSERT INTO t1 VALUES (-1442456386);
mysql> SELECT COUNT(*) FROM t1, t0, t2, t3 WHERE (NOT (CAST(FPOW(CAST(t2.c_2_16 AS FLOAT ) , 0.9533189153826871)  AS BOOLEAN ) ));
+----------+
| count(*) |
+----------+
|      624 |
+----------+
mysql> SELECT SUM(count) FROM (SELECT CAST((CAST((NOT (CAST(FPOW(CAST(t2.c_2_16 AS FLOAT ) , 0.9533189153826871)  AS BOOLEAN ) )) AS BOOLEAN) = true) AND (CAST((NOT (CAST(FPOW(CAST(t2.c_2_16 AS FLOAT ) , 0.9533189153826871)  AS BOOLEAN ) )) AS BOOLEAN) IS NOT NULL) AS INT) as count FROM t1, t0, t2, t3 ) t;
+--------------+
| sum(`count`) |
+--------------+
|         1872 |
+--------------+

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_02_RELEASE 4199713 |
+---------------------------------+

### PR DESCRIPTION
**Pull request by satanson**
https://github.com/StarRocks/starrocks/issues/3103

common type of decimal64(7,4) and decimal32(3,0) should be decimal64(7,4) instead of decimal32(7,4), although decimal32(7,4) can hold a value of decimal64(7,4) without precision loss, but in computation, overflow checking on decimal64(7,4) and decimal32(7,4) are quite different, they underlying types int64_t and int32_t are used for overflow checking irrespectively.

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/TestCommonTypeInvolvingDecimalTypes.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
+// This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Limited.
+package com.starrocks.sql.plan;
+
+import org.junit.AfterClass;
+import org.junit.Assert;
+import org.junit.BeforeClass;
+import org.junit.Test;
+
+public class TestCommonTypeInvolvingDecimalTypes extends PlanTestBase {
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/TestCommonTypeInvolvingDecimalTypes.java:9]: There are many decimal v3 test classes. suggest  move all decimate v3 related tests to one test class.
1. which could reduce UT time
2. which could help use know which point we don't test

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
