### PR TITLE
[Bugfix] Should check cast expr validity in update statement

### LINKED ISSUE #6317: result error when update primary table with data out of bound
### Steps to reproduce the behavior (Required)
1. create primary table and insert data:
```
create table num_test(c_dis int,c_tinyint tinyint,c_smallint smallint,c_int int,c_bigint bigint,c_largeint largeint,c_float float,c_double double,c_dec32p1s0 decimal32(1,0),c_dec32p9s9 decimal32(9,9),c_dec32p7s3 decimal(7,3),c_dec64p18s0 decimal64(18,0),c_dec64p18s18 decimal64(18,18),c_dec64p10s5 decimal64(10,5),c_dec128p38s18 decimal128(38,18),c_dec128p38s0 decimal(38,0),c_dec128p38s16 decimal128(38,16))
        primary key(c_dis)
        distributed by hash(c_dis);
insert into num_test values(1,127,32767,2147483647,9223372036854775807,170141183460469231731687303715884105727,3.4E+38,1.79E+308,10,1,10000.000,1000000000000000000,1,100000.00000,100000000000000000000.000000000000000001,99999999999999999999999999999999999999,10000000000000000000000.0000000000000000);
insert into num_test values(2,-128,-32768,-2147483648,-9223372036854775808,-170141183460469231731687303715884105728,-3.4E+38,-1.79E+308,-10,-1,-10000,-1000000000000000000,-1,-100000,-100000000000000000000,-99999999999999999999999999999999999999,-10000000000000000000000.0000000000000000);
```

2. update decimal128(38,0) with data out of bound:
set c_dec128p38s0=1e+38, error:
```
mysql> update num_test set c_dec128p38s0=1e+38 where c_dis = 1;
ERROR 1064 (HY000): Non-typed decimal literal is overflow, value='100000000000000000000000000000000000000' (precision=39, scale=0)
```

set c_dec128p38s0=1e+39, update success:
```
mysql> update num_test set c_dec128p38s0=1e+39 where c_dis = 1;
Query OK, 1 row affected (0.04 sec)
{'label':'update_e46acab7-d742-11ec-a5fb-00163e10c9d6', 'status':'VISIBLE', 'txnId':'245825'}

mysql> select c_dec128p38s0 from num_test where c_dis = 1;
+---------------+
| c_dec128p38s0 |
+---------------+
|          NULL |
+---------------+
1 row in set (0.01 sec)
``` 
 
### Expected behavior (Required)
return error when update data out bound

### Real behavior (Required)
sometimes update success with null

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-master

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6317

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|3|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java [hunk 1]
```diff
@@ -58,7 +60,11 @@ public static void analyze(UpdateStmt updateStmt, ConnectContext session) {
                 if (col.isKey()) {
                     throw new SemanticException("primary key column cannot be updated: " + col.getName());
                 }
-                item = new SelectListItem(new CastExpr(col.getType(), assign.getExpr()), col.getName());
+                if (assign.getExpr() instanceof LiteralExpr) {
+                    item = new SelectListItem(TypeManager.addCastExpr(assign.getExpr(), col.getType()), col.getName());
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java:64]: Could you add comment why call TypeManger.addCastExpr for LiteralExpr?
And why not call `TypeManager.addCastExpr` for other expressions?

**Review by imay — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by kangkaisen** [comment]
should add UT
