### PR TITLE
[BugFix] Fix two NPE problem for backup/restore(#40091)

### LINKED ISSUE #40091: Two NPE show problem for backup/restore
### Steps to reproduce the behavior (Required)
problem 1:
CANCEL BACKUP/CANCEL RESTORE
problem 2:
SHOW RESTORE/SHOW BACKUP

### Expected behavior (Required)
1. some error exception
2. BACKUP/RESTORE info
### Real behavior (Required)
1. NPE
2. NPE 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by srlch**
Problem 1:
CANCEL BACKUP/RESTORE without FROM dbname clause will get NPE This is because in g4 we define FROM dbname as a optional clause but actually we expect that user should sepecify the db name in cancel statement which cause the NPE problem:

Problem 2;
SHOW BACKUP/RESTORE maybe get NPE because some meta data for backup/restore will be updated concurrently during SHOW BACKUP/RESTORE.

Solution:
For problem 1:
Check whether the dbname has been given in parser and returun a readable information for user if miss the dbname

For problem 2:
Just return a readable information to tell user to retry SHOW BACKUP/RESTORE again for simplicity.

Fixes #40091

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by srlch** [comment]
rebase

**Comment by srlch** [comment]
@Mergify rebase

**Review by nshangyiming — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java [hunk 1]
```diff
@@ -858,12 +859,16 @@ public List<String> getInfo() {
...
-                + "]").collect(Collectors.toList())));
+        try {
+            info.add(Joiner.on(", ").join(unfinishedTaskIds.entrySet()));
+            info.add(Joiner.on(", ").join(taskProgress.entrySet().stream().map(
+                    e -> "[" + e.getKey() + ": " + e.getValue().first + "/" + e.getValue().second + "]").collect(
+                    Collectors.toList())));
+            info.add(Joiner.on(", ").join(taskErrMsg.entrySet().stream().map(n -> "[" + n.getKey() + ": " + n.getValue()
+                    + "]").collect(Collectors.toList())));
+        } catch (Exception e) {
+            throw new AnalysisException("meta data may has been updated during this period, please try again");
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/backup/BackupJob.java:870]: return error is not friendly to users.
maybe we can use lock or ConcurrentXxx, or just return the old states.

**Review by Seaven — APPROVED** [review]

**Comment by srlch** [comment]
ignore backport check: 3.1.9
