### PR TITLE
[BugFix] fix left outer join to inner join bug and string not equal rewrite bug

### LINKED ISSUE #39330: mv join rewrite failed
### Steps to reproduce the behavior (Required)
String mv = "select t1a, t1b, v5, v8 " +
                    "from test.test_all_type left outer join test.t1 on t1d = v4 " +
                    "left outer join test.t2 on v5 = v7 where v9 = 10";
String query = "select t1a, t1b, v5, v8 " +
                    "from test.test_all_type left outer join test.t1 on t1d = v4 " +
                    "left outer join test.t2 on v5 = v7 where v9 = 10 and t1a != 'xxx'";

### Expected behavior (Required)

query should be rewritten by mv
### Real behavior (Required)
query is not rewritten by mv
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Why I'm doing:
mv with string not equal predicate rewrite failed because converting left outer join to inner join failed.

What I'm doing:
Fix it by:
1. fix converting left outer join to inner join bug
2. fix query with string not equal predicate rewrite failed bug.

Fixes #39330 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by LiShuMing — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java [hunk 1]
```diff
@@ -75,6 +76,8 @@ public class OptimizerContext {
 
     private boolean isShortCircuit = false;
 
+    private List<IsNullPredicateOperator> pushdownNotNullPredicates = Lists.newArrayList();
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java:79]: the nullable info isn't global. If the predicate is deduced first and then push down outer join. like:join->outer join->join, will take bugs
BTW, push down worked by Top-Down, shoulde be not question, but you'd better test it

Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java:79]: BTW, add comment

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/OptimizerContext.java:79]: fixed.

**Review by Seaven — APPROVED** [review]

**Review by LiShuMing — APPROVED** [review]
