### PR TITLE
[BugFix] HeartbeatResponse add prop aliveStatus

### LINKED ISSUE #12473: heartbeatRetryTimes makes node alive status which stored in follower wrong
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12473 

Prop 'heartbeatRetryTimes' makes node alive status which stored in follower wrong, the alive of nodes in Follower depends on the calculation of heartbeatRetryTimes, which is not accurate, this PR adds a new prop 'aliveStatus' in HeartbeatResponse and uses 'aliveStatus' to decide node alive status which stored in follower

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|2|4|50.00%|[98, 99]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|4|50.00%|[437, 438]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|1|2|50.00%|[246]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 14 (64.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|2|4|50.00%|[98, 99]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|4|50.00%|[437, 438]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|1|2|50.00%|[246]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

File: fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java [hunk 1]
```diff
@@ -89,10 +89,15 @@ public boolean handleHbResponse(BrokerHbResponse hbResponse) {
             // this heartbeat info also need to be synced to follower.
             // Since the failed heartbeat info also modifies fe's memory, (this.heartbeatRetryTimes++;)
             // if this heartbeat is not synchronized to the follower, 
-            // that will cause the Follower and master’s memory to be inconsistent
+            // that will cause the Follower and leader’s memory to be inconsistent
             isChanged = true;
         }
-
+        if (!isReplay) {
+            hbResponse.aliveStatus = isAlive;
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java:96]: Should consider the upgrade case.

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 10 / 19 (52.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|2|5|40.00%|[100, 101, 102]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|5|40.00%|[438, 439, 440]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|1|2|50.00%|[246]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|5|60.00%|[165, 166]|
|:large_blue_circle:|com/starrocks/system/HeartbeatResponse.java|2|2|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java [hunk 2]
```diff
@@ -89,10 +90,18 @@ public boolean handleHbResponse(BrokerHbResponse hbResponse) {
...
-            // that will cause the Follower and master’s memory to be inconsistent
+            // that will cause the Follower and leader’s memory to be inconsistent
             isChanged = true;
         }
-
+        if (!isReplay) {
+            hbResponse.aliveStatus = isAlive ?
+                HeartbeatResponse.AliveStatus.ALIVE : HeartbeatResponse.AliveStatus.NOT_ALIVE;
+        } else {
+            if (hbResponse.aliveStatus != null) {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java:100]: Better add some comment that why hbResponse.aliveStatus can be null.

Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java:100]: done

File: fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java (hunk 1 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/catalog/FsBroker.java]: done

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 19 (57.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|2|5|40.00%|[100, 103, 104]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|5|40.00%|[438, 441, 442]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|5|60.00%|[167, 168]|
|:large_blue_circle:|com/starrocks/system/HeartbeatResponse.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|2|2|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by nshangyiming — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 19 (57.89%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|2|5|40.00%|[100, 103, 104]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|5|40.00%|[438, 441, 442]|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|5|60.00%|[167, 168]|
|:large_blue_circle:|com/starrocks/system/HeartbeatResponse.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 17 / 19 (89.47%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/Frontend.java|3|5|60.00%|[167, 168]|
|:large_blue_circle:|com/starrocks/system/HeartbeatResponse.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/FsBroker.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|2|2|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
