### PR TITLE
[BugFix] Fix bug that thrift server daemon exits quietly

### LINKED ISSUE #7972: [BUG] fe thrift server cannot be connected: connection reset by peer
### Steps to reproduce the behavior (Required)
1. set the linux machine config (`/proc/sys/net/core/somaxconn`) to a very low value (32 for example, remember to reset this value after test).
2. set user max processes to a very low value (`ulimit -u 128`)
3. restart fe node
4. send much of load/query to fe concurrently.

### Expected behavior (Required)
fe should run normally, or exit if the resource is not available.

### Real behavior (Required)
load and query are failed, but there are no resource  unavailable logs.

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7972

## Problem Summary(Required) ：

Rewrite the execute() function of org.apache.thrift.server.TThreadPoolServer: We do not kill the server for any exception thrown by ExecutorService, just close the connection and print the error log. But TThreadPoolServer will kill the server, and any new connection will not be processed, it will cause the connections saturate the tcp backlog.

Because there are some private properties in TThreadPoolServer. So we create a new implementation of TServer, and copy the code of TThreadPoolServer, and just modify the error process of the execute function.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 6 (16.67%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/ThriftServer.java|1|6|16.67%|

**Review by meegoo — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java [hunk 1]
```diff
@@ -143,9 +143,15 @@ public void start() throws IOException {
         serverThread = new Thread(new Runnable() {
             @Override
             public void run() {
-                server.serve();
+                try {
+                    server.serve();
+                } catch (Throwable t) {
+                    LOG.error("thrift server accept daemon failed, will exit", t);
+                    System.exit(-1);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/common/ThriftServer.java:150]: The `System.exit()` should be avoided to call even if the case of emergency.
Instead, we should return an error.

**Review by chaoyli — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+        boolean shouldSleep = false;
+        while (true) {
+            try {
+                if (shouldSleep) {
+                    Thread.sleep(5000);
+                }
+                shouldSleep = true;
+
+                super.execute();
+            } catch (Throwable t) {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:30]: I honestly think catching all the Throwable and retry is a bad practice. If an unrecoverable Error is thrown, there is no use in trying, neither can the program recover from exiting the process and recover by Supervised. I suggest you only catch what you meant to catch and leave the rest raised.

File: fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+        while (true) {
+            try {
+                if (shouldSleep) {
+                    Thread.sleep(5000);
+                }
+                shouldSleep = true;
+
+                super.execute();
+            } catch (OutOfMemoryError error) {
+                LOG.error("thrift server accept failed, will retry", error);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:31]: The format is wrong, the error will not be printed.

Comment (chaoyli) [reply fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:31]: You are better to print the essential error. And give advice on how to handle it.
```
Failed to accept the connection. Error: {}
```

File: fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java (hunk 2 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:32]: 1. If some actual memory leak occurs, this process will still neither serve well nor can it exit. I suggest you override the function that checks the number of connections, raising a self-defined exception instead of OOM Error.
2. I don't see how other throwables can lead to an exit. There is no `raise` nor `break` in the loop.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:32]: 1. The Exception occurred is `java.lang.OutOfMemoryError : unable to create new native Thread`, the reason is the limit of user max process is reached, not the connection number. The exception thrown by JVM is a little confused, because it is not the memory problem. I will handle the exception according to the error message.  Only retry on `unable to create new native Thread`.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 10 / 20 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/MyTThreadPoolServer.java|8|18|44.44%|
|:large_blue_circle:|com/starrocks/common/ThriftServer.java|2|2|100.00%|

**Review by padmejin — COMMENTED** [review]
LGTM, though I still think it is redundant to catch OOM Error..

File: fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+
+                super.execute();
+            } catch (OutOfMemoryError error) {
+                if (error.getMessage() != null &&
+                        error.getMessage().toLowerCase().contains("unable to create new native thread")) {
+                    LOG.error("Fail to accept new connection, " +
+                            "please set the max user processes to a bigger value using `ulimit -u`. will retry", error);
+                } else {
+                    LOG.error("Fail to accept new connection, " +
+                            "please set the jvm heap size to a bigger value. will exit", error);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:37]: You have also reject the connection. The pressure will be reduced after a while. You throw the exception is enough.

File: fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+        super(args);
+    }
+
+    /**
+     * override the execute method, catch OutOfMemoryError and retry to avoid the accept thread exit unexpected
+     */
+    @Override
+    protected void execute() {
+        boolean shouldSleep = false;
+        while (true) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/common/MyTThreadPoolServer.java:22]: It's not necessary to retry because the lack of resource.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 76 / 158 (48.10%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/SRTThreadPoolServer.java|72|154|46.75%|
|:large_blue_circle:|com/starrocks/common/ThriftServer.java|4|4|100.00%|

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
https://github.com/Mergifyio backport branch-2.3

**Comment by gengjun-git** [comment]
https://github.com/Mergifyio backport branch-2.2

**Comment by gengjun-git** [comment]
@Mergifyio backport branch-2.1

**Comment by gengjun-git** [comment]
https://github.com/Mergifyio backport branch-2.0
