### PR TITLE
[BugFix] Fix null partition value missed bug after mv union rewrite

### LINKED ISSUE #21321: null partition value data is missed after mv union rewrite
### Steps to reproduce the behavior (Required)

**CREATE TABLE**
```sql
"create table test_base_part(c1 int, c2 bigint, c3 bigint, c4 bigint)" +
                " partition by range(c3) (" +
                " partition p1 values less than (\"100\")," +
                " partition p2 values less than (\"200\")," +
                " partition p3 values less than (\"1000\")," +
                " PARTITION p4 values less than (\"2000\")," +
                " PARTITION p5 values less than (\"3000\"))" +
                " distributed by hash(c1)" +
                " properties (\"replication_num\"=\"1\");
```

**create mv** 
```sql
CREATE MATERIALIZED VIEW `partial_mv_9`\n" +
                    "COMMENT \"MATERIALIZED_VIEW\"\n" +
                    "PARTITION BY (`c3`)\n" +
                    "DISTRIBUTED BY HASH(`c1`) BUCKETS 6\n" +
                    "REFRESH MANUAL\n" +
                    "PROPERTIES (\n" +
                    "\"replication_num\" = \"1\",\n" +
                    "\"storage_medium\" = \"HDD\"\n" +
                    ")\n" +
                    "AS SELECT `test_base_part`.`c1`, `test_base_part`.`c3`, sum(`test_base_part`.`c4`) AS `total`\n" +
                    "FROM `test_mv`.`test_base_part`\n" +
                    "WHERE `test_base_part`.`c3` < 1000\n" +
                    "GROUP BY `test_base_part`.`c3`, `test_base_part`.`c1`;
```

2. INSERT INTO 
 insert data with null partition values into test_base_part, and refresh mv

3. select data from query with mv rewrite enabled
select c1, c3, sum(c4) from test_base_part group by c1, c3

### Expected behavior (Required)
null partition data record are returned
### Real behavior (Required)
null partition data record are not returned
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #21321 

## Problem Summary(Required) ：

Fix null partition value missed bug after mv union rewrite. Fix it by compensating partition_column is null into predicate.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java [hunk 1]
```diff
@@ -266,24 +261,11 @@ private OptExpression rewriteForRollup(
     @Override
     protected OptExpression queryBasedRewrite(RewriteContext rewriteContext, ScalarOperator compensationPredicates,
                                               OptExpression queryExpression) {
-        // query predicate and (not viewToQueryCompensationPredicate) is the final query compensation predicate
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:269]: Why remove this ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 2]
```diff
@@ -178,7 +181,8 @@ public OptExpression rewrite() {
 
         ScalarOperator mvPredicate = MvUtils.rewriteOptExprCompoundPredicate(mvExpression, mvColumnRefRewriter);
 
-        if (materializationContext.getMvPartialPartitionPredicate() != null) {
+        if (materializationContext.getMvPartialPartitionPredicate() != null
+                && !(mvPredicate instanceof IsNullPredicateOperator)) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:185]: If non partition column has predicate `isNull`, it will do not add latest partition predicate to mv predicate?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 3]
```diff
@@ -872,6 +876,55 @@ protected OptExpression queryBasedRewrite(RewriteContext rewriteContext, ScalarO
                         new ReplaceColumnRefRewriter(queryExpression.getOp().getProjection().getColumnRefMap());
                 queryCompensationPredicate = rewriter.rewrite(queryCompensationPredicate);
             }
+            MaterializedView mv = mvRewriteContext.getMaterializationContext().getMv();
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:879]: put these in a function, and plz add some comment to desc what these does.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 4]
```diff
@@ -872,6 +876,55 @@ protected OptExpression queryBasedRewrite(RewriteContext rewriteContext, ScalarO
...
+                    IsNullPredicateOperator isNullPredicateOperator = new IsNullPredicateOperator(partitionColumnRef);
+                    IsNullPredicateOperator isNotNullPredicateOperator = new IsNullPredicateOperator(true, partitionColumnRef);
+                    List<ScalarOperator> predicates = Utils.extractConjuncts(queryCompensationPredicate);
+                    List<ScalarOperator> partitionRelatedPredicates = predicates.stream()
+                            .filter(predicate -> isRelatedPredicate(predicate, partitionColumns.get(0).getName()))
+                            .collect(Collectors.toList());
+                    predicates.removeAll(partitionRelatedPredicates);
+                    if (partitionRelatedPredicates.contains(isNullPredicateOperator)
+                            || partitionRelatedPredicates.contains(isNotNullPredicateOperator)) {
+                        if (partitionRelatedPredicates.size() != 1) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:913]: partititon column **is null**  and partititon column **is not null** ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:269]: refactor it by using base class's queryBasedRewrite. most logic is the same.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java]: if there is IsNullPredicateOperator for partition column, should not add mv partial partition predicate.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java]: done

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java]: when the compensation query predicate is isNotNullPredicateOperator, should add it back.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 5]
```diff
@@ -179,10 +182,15 @@ public OptExpression rewrite() {
         ScalarOperator mvPredicate = MvUtils.rewriteOptExprCompoundPredicate(mvExpression, mvColumnRefRewriter);
 
         if (materializationContext.getMvPartialPartitionPredicate() != null) {
-            // add latest partition predicate to mv predicate
-            ScalarOperator rewritten =
-                    mvColumnRefRewriter.rewrite(materializationContext.getMvPartialPartitionPredicate());
-            mvPredicate = MvUtils.canonizePredicate(Utils.compoundAnd(mvPredicate, rewritten));
+            List<ScalarOperator> partitionPredicates =
+                    getPartitionRelatedPredicates(mvPredicate, mvRewriteContext.getMaterializationContext().getMv());
+            if (partitionPredicates.stream().noneMatch(p -> p instanceof IsNullPredicateOperator)) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:187]: If partition column has predicate `isNull`, mv will lost partition predicate even if some partitions are outdated?

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:187]: no, if it has isNull predicate, the partition with null partition is updated, then the mv can not be used to rewrite. or the partial predicates are useless. so here do not add the partial predicates.

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 76 / 80 (95.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|3|4|75.00%|[270]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|73|76|96.05%|[936, 954, 1008]|

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
