### PR TITLE
[BugFix] Fix consistency problem

### LINKED ISSUE #8593: [sqlsmith] be crash
### Steps to reproduce the behavior (Required)
```
crash.log:
log4j:WARN No appenders could be found for logger (org.apache.hadoop.fs.FileSystem).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
==4731==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7f9c93a707c0; bottom 0x7f94206ff000; size: 0x0008733717c0 (36292728768)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
*** Check failure stack trace: ***
    @          0xb9ff52d  google::LogMessage::Fail()
    @          0xba0199f  google::LogMessage::SendToLog()
    @          0xb9ff07e  google::LogMessage::Flush()
    @          0xba01fa9  google::LogMessageFatal::~LogMessageFatal()
    @          0x684f889  starrocks::DataStreamRecvr::SenderQueue::add_chunks()
    @          0x685bda8  starrocks::DataStreamRecvr::add_chunks()
    @          0x67c7607  starrocks::DataStreamMgr::transmit_chunk()
    @          0xa5fd5d2  starrocks::PInternalServiceImplBase<>::transmit_chunk()
    @          0x72f01e6  doris::PBackendService::CallMethod()
    @          0xbb391de  brpc::policy::ProcessRpcRequest()
    @          0xbb2fc47  brpc::ProcessInputMessage()
    @          0xbb30af3  brpc::InputMessenger::OnNewMessages()
    @          0xbbd713e  brpc::Socket::ProcessEvent()
    @          0xbae593f  bthread::TaskGroup::task_runner()
    @          0xbc6d8c1  bthread_make_fcontext

```

```
it's very hard to reproduce. 
select  
  subq_0.c0 as c0, 
  ref_1.c2 as c1, 
  48 as c2
from 
  (select  
            ref_0.ib_upper_bound as c0
          from 
            sqlsmith.tpcds_100g_income_band as ref_0
          where ((true) 
              and (false)) 
            or (cast(null as VARCHAR) >= cast(null as VARCHAR))
          limit 149) as subq_0
      inner join sqlsmith.t2 as ref_1
      on (subq_0.c0 = ref_1.c1 )
    right join sqlsmith.es_ssb_10g_customer as ref_2
    on (subq_0.c0 = ref_2.c_custkey )
where ref_2.c_nation is NULL
limit 90;

Time is: 2022-07-12 08:49:38 and ERR_MSG: transmit chunk rpc failed:7ea2469b-017c-11ed-b3eb-00163e0025cc

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN 3212a0e |
+-------------------+

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8593

## Problem Summary(Required) ：

Considering we are processing two packets concurrently, and one of the time sequences are list as follows:

1. thread_1 receive packet, `prev_is_pipeline_level_shuffle = _is_pipeline_level_shuffle = false`
2. thread_2 receive packet `prev_is_pipeline_level_shuffle = _is_pipeline_level_shuffle = false`
3. thread_1 set `_is_pipeline_level_shuffle = true` and set `_is_pipeline_level_shuffle_init = true`
4. thread_2 set `_is_pipeline_level_shuffle = true`
5. thread_2 failed the check `!_is_pipeline_level_shuffle_init || (prev_is_pipeline_level_shuffle == _is_pipeline_level_shuffle)`

It can be recreated by the following demo program

```cpp
#include <iostream>
#include <thread>

int main() {
    while (true) {
        bool is_pipeline_level_shuffle = false;
        bool is_pipeline_level_shuffle_init = false;

        std::thread t1([&]() {
            bool prev_is_pipeline_level_shuffle = is_pipeline_level_shuffle;
            is_pipeline_level_shuffle = true;
            if (is_pipeline_level_shuffle_init && (prev_is_pipeline_level_shuffle != is_pipeline_level_shuffle)) {
                std::cout << "error" << std::endl;
                exit(1);
            }
            is_pipeline_level_shuffle_init = true;
        });
        std::thread t2([&]() {
            bool prev_is_pipeline_level_shuffle = is_pipeline_level_shuffle;
            is_pipeline_level_shuffle = true;
            if (is_pipeline_level_shuffle_init && (prev_is_pipeline_level_shuffle != is_pipeline_level_shuffle)) {
                std::cout << "error" << std::endl;
                exit(1);
            }
            is_pipeline_level_shuffle_init = true;
        });

        t1.join();
        t2.join();
    }
    return 0;
}
```

### CODE REVIEW

File: be/src/exec/pipeline/fragment_executor.cpp [hunk 1]
```diff
@@ -546,12 +546,7 @@ Status FragmentExecutor::_decompose_data_sink_to_operator(RuntimeState* runtime_
         if (sender->get_partition_type() == TPartitionType::HASH_PARTITIONED ||
             sender->get_partition_type() == TPartitionType::BUCKET_SHUFFLE_HASH_PARTITIONED) {
             dest_dop = t_stream_sink.dest_dop;
-
-            // UNPARTITIONED mode will be performed if both num of destination and dest dop is 1
-            // So we only enable pipeline level shuffle when num of destination or dest dop is greater than 1
-            if (sender->destinations().size() > 1 || dest_dop > 1) {
```
Comment (kangkaisen) [inline be/src/exec/pipeline/fragment_executor.cpp:552]: Why change this logic?

File: be/src/runtime/data_stream_recvr.cc [hunk 2]
```diff
@@ -150,7 +150,9 @@ class DataStreamRecvr::SenderQueue {
 
     typedef std::list<ChunkItem> ChunkQueue;
     ChunkQueue _chunk_queue;
+#ifdef DEBUG
```
Comment (kangkaisen) [inline be/src/runtime/data_stream_recvr.cc:153]: Why this variable is only used in debug mode?

File: be/src/runtime/data_stream_recvr.cc [hunk 3]
```diff
@@ -471,12 +473,21 @@ Status DataStreamRecvr::SenderQueue::add_chunks(const PTransmitChunkParams& requ
     ChunkQueue chunks;
     size_t total_chunk_bytes = 0;
     faststring uncompressed_buffer;
-    bool prev_is_pipeline_level_shuffle = _is_pipeline_level_shuffle;
+
+#ifdef DEBUG
+    {
+        std::lock_guard<std::mutex> l(_lock);
```
Comment (kangkaisen) [inline be/src/runtime/data_stream_recvr.cc:479]: Do we really need to keep so many codes only for debugging?

File: be/src/exec/pipeline/fragment_executor.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/fragment_executor.cpp:552]: This condition here is redundant, ExchangeSinkOperator's ctor will take care of both of them, including destination num and dest dop

```cpp
ExchangeSinkOperator::ExchangeSinkOperator(OperatorFactory* factory, int32_t id, int32_t plan_node_id,
                                           int32_t driver_sequence, const std::shared_ptr<SinkBuffer>& buffer,
                                           TPartitionType::type part_type,
                                           const std::vector<TPlanFragmentDestination>& destinations,
                                           bool is_pipeline_level_shuffle, const int32_t num_shuffles_per_channel,
                                           int32_t sender_id, PlanNodeId dest_node_id,
                                           const std::vector<ExprContext*>& partition_expr_ctxs,
                                           bool enable_exchange_pass_through, FragmentContext* const fragment_ctx,
                                           const std::vector<int32_t>& output_columns)
        : Operator(factory, id, "exchange_sink", plan_node_id, driver_sequence),
          _buffer(buffer),
          _part_type(part_type),
          _destinations(destinations),
          _num_shuffles_per_channel(num_shuffles_per_channel > 0 ? num_shuffles_per_channel : 1),
          _sender_id(sender_id),
          _dest_node_id(dest_node_id),
          _partition_expr_ctxs(partition_expr_ctxs),
          _fragment_ctx(fragment_ctx),
          _output_columns(output_columns) {
...
    _num_shuffles = _channels.size() * _num_shuffles_per_channel;

    _is_pipeline_level_shuffle = is_pipeline_level_shuffle && (_num_shuffles > 1);
}
```

File: be/src/runtime/data_stream_recvr.cc (hunk 3 above)
Comment (liuyehcf) [reply be/src/runtime/data_stream_recvr.cc:479]: These code is only for DCHECK, the logic of pipeline level shuffle is too implied and complex, and I think adding `DCHECK` can expose problems as soon as possible. Otherwise, once a change is introduced, it will be difficult to troubleshoot if there exist bugs

**Review by kangkaisen — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
