### PR TITLE
[BugFix] add MVActiveChecker for external table

### LINKED ISSUE #16742: MVActiveChecker should be kept for external tables.
### Steps to reproduce the behavior (Required)
MVActiveChecker is used to check mvs for external tables, which should be kept for correctness
MVActiveChecker is realized by async checking, which should be optimized later.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16742 

## Problem Summary(Required) ：

add MVActiveChecker for external table. external tables' metas are not persistent, 
so the check should be done every time when cache is refresh.
now it is done by async, which will be optimized later
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Youngwb — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVActiveChecker.java [hunk 1]
```diff
@@ -0,0 +1,78 @@
...
+                        continue;
+                    }
+                    MvId mvId = new MvId(db.getId(), mv.getId());
+                    table.addRelatedMaterializedView(mvId);
+                }
+            }
+        }
+
+        long duration = System.currentTimeMillis() - startMillis;
+        LOG.info("[MVActiveChecker] finish check all materialized view in {}ms", duration);
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/scheduler/mv/MVActiveChecker.java:76]: Remove the log if not meta changed? Otherwise it would print a lot of log

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 28 / 36 (77.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVActiveChecker.java|26|34|76.47%|[58, 59, 60, 61, 64, 65, 66, 67]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 23 / 33 (69.70%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/mv/MVActiveChecker.java|21|31|67.74%|[41, 42, 57, 58, 59, 60, 63, 64, 65, 66]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
