### PR TITLE
[BugFix] Fix key index out of bound in schema of _do_merge_horizontally.

### LINKED ISSUE #13935: [pk_sort_key]be crash when create pk table
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
 CREATE TABLE `test_primary_table` (
                `k1` date NOT NULL,
                `k2` datetime NOT NULL,
                `测试中文` varchar(20) NOT NULL,
                test_varchar_0cnsFnAWN8nDQIWFU2M7GtkMa40t02I2UwNGMr4UIblxrIJW2TQahpviZbKelvFD varchar(20) NOT NULL,
                `k5` boolean NOT NULL,
                `v1` tinyint NULL,
                `v2` smallint NULL,
                `v3` int NULL,
                `v4` bigint NULL,
                `v5` largeint NULL,
                `v6` float NULL,
                `v7` double NULL,
                `v8` decimal(27,9) NULL
            ) ENGINE=OLAP
            PRIMARY KEY(`k1`, `k2`)
            COMMENT "OLAP"
            DISTRIBUTED BY HASH(`k1`, `k2`) BUCKETS 2
            ORDER BY(`测试中文`, `test_varchar_0cnsFnAWN8nDQIWFU2M7GtkMa40t02I2UwNGMr4UIblxrIJW2TQahpviZbKelvFD`, `k5`)
            PROPERTIES (
                "replication_num" = "3",
                "storage_format" = "v2"
            );
```

### Expected behavior (Required)
create table success
### Real behavior (Required)
create table failed and be crash
```
I1123 15:14:07.698128 21128 BlockCache.cpp:589] Reset block cache
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
*** Aborted at 1669189152 (unix time) try "date -d @1669189152" if you are using GNU date ***
PC: @          0x3d51d99 starrocks::PrimaryKeyEncoder::is_supported()
*** SIGSEGV (@0x2d) received by PID 21128 (TID 0x7f04b2ffa700) from PID 45; stack trace: ***
    @          0x5785a82 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f0aefc47630 (unknown)
    @          0x3d51d99 starrocks::PrimaryKeyEncoder::is_supported()
    @          0x3d51ee6 starrocks::PrimaryKeyEncoder::create_column()
    @          0x3f2a80a starrocks::vectorized::RowsetMergerImpl<>::_do_merge_horizontally()
    @          0x3f2b612 starrocks::vectorized::RowsetMergerImpl<>::_do_merge_vertically()
    @          0x3f2d53d starrocks::vectorized::RowsetMergerImpl<>::do_merge()
    @          0x3f20c2f starrocks::vectorized::compaction_merge_rowsets()
    @          0x3df2b56 starrocks::TabletUpdates::_do_compaction()
    @          0x3df3bcc starrocks::TabletUpdates::compaction()
    @          0x3d5a653 starrocks::StorageEngine::_perform_update_compaction()
    @          0x3f9c58e starrocks::StorageEngine::_update_compaction_thread_callback()
    @          0x796b7c0 execute_native_thread_routine
    @     0x7f0aefc3fea5 start_thread
    @     0x7f0ae53258dd __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE 874512e |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13935

## Problem Summary(Required) ：

potential array index out of bound. should be an iota array of sort key indexes, not sort key indexes directly.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

File: be/src/storage/rowset_merger.cpp [hunk 1]
```diff
@@ -260,7 +260,9 @@ class RowsetMergerImpl : public RowsetMerger {
         std::vector<ColumnId> sort_key_idxes;
         if (schema.sort_key_idxes().size() > 1) {
             sort_key_idxes = schema.sort_key_idxes();
```
Comment (decster) [inline be/src/storage/rowset_merger.cpp:262]: is sort_key_idxes useful for another copy?

File: be/src/storage/rowset_merger.cpp [hunk 2]
```diff
@@ -260,7 +260,9 @@ class RowsetMergerImpl : public RowsetMerger {
...
-            if (!PrimaryKeyEncoder::create_column(schema, &sort_column, sort_key_idxes).ok()) {
+            std::vector<ColumnId> sort_key_iota_idxes(sort_key_idxes.size());
+            std::iota(sort_key_iota_idxes.begin(), sort_key_iota_idxes.end(), 0);
```
Comment (decster) [inline be/src/storage/rowset_merger.cpp:264]: why use idxes rather than  sort_key_dxes? I don't see the logic here

File: be/src/storage/rowset_merger.cpp [hunk 3]
```diff
@@ -260,7 +260,9 @@ class RowsetMergerImpl : public RowsetMerger {
         std::vector<ColumnId> sort_key_idxes;
         if (schema.sort_key_idxes().size() > 1) {
             sort_key_idxes = schema.sort_key_idxes();
-            if (!PrimaryKeyEncoder::create_column(schema, &sort_column, sort_key_idxes).ok()) {
+            std::vector<ColumnId> sort_key_iota_idxes(sort_key_idxes.size());
```
Comment (chaoyli) [inline be/src/storage/rowset_merger.cpp:263]: What is the meaning of iota?

File: be/src/storage/rowset_merger.cpp (hunk 1 above)
Comment (Linkerist) [reply be/src/storage/rowset_merger.cpp]: no, changed.

File: be/src/storage/rowset_merger.cpp (hunk 3 above)
Comment (Linkerist) [reply be/src/storage/rowset_merger.cpp]: Fills the range vector with sequentially increasing values, starting with value and repetitively evaluating ++value.

File: be/src/storage/rowset_merger.cpp (hunk 2 above)
Comment (Linkerist) [reply be/src/storage/rowset_merger.cpp]: refactored.

**Comment by Linkerist** [comment]
run starrocks_be_unittest

**Comment by Linkerist** [comment]
starrocks_fe_unittest

File: be/src/storage/rowset_merger.cpp [hunk 4]
```diff
@@ -43,6 +43,7 @@ struct MergeEntry {
     const vectorized::VectorizedSchema* encode_schema = nullptr;
     uint16_t order;
     std::vector<vectorized::RowSourceMask>* source_masks = nullptr;
+    static ColumnId first_sort_column_idx;
```
Comment (decster) [inline be/src/storage/rowset_merger.cpp:46]: There are multiple threads using this merger, you can not use static here

**Review by chaoyli — DISMISSED** [review]

**Review by decster — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
