### PR TITLE
[BugFix] Schema check error for restore (#21418)

### LINKED ISSUE #21418: [BugFix] Schema check error for restore
Problem:
When the restored table has existed, sr will check the schema between local table and snapshot table. But the check has some bugs and will cause some problem:
1. If local table and snapshot table has same columns with different nullable attribute, the check will success and it will cause crash because fe and be have different schema for nullable attribute.
2. Schema check include the value of schema hash, and this value will change when finishing schema change. If a local table finish schema change and get the same schema compare with the remote table, it will still fail in schema check because the schema hash is different, but it is no make sense.

Solution:
1. Check the BaseSchema between local and remote table.
2. skip the check for schema hash value if doing restore.

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #21418

## Problem Summary(Required) ：
Problem:
When the restored table has existed, sr will check the schema between the local and snapshot tables. But the check has some bugs and will cause some problems:
1. If the local table and snapshot table have the same columns with different nullable attributes, the check will succeed and it will cause a crash because FE and BE have different schemas for nullable attributes.
2. Schema check includes the schema hash value, which will change when the schema change is finished. If a local table finishes the schema change and gets the same schema compared with the remote table, it will still fail in the schema check because the schema hash is different, but it does not make sense.

Solution:
1. Check the BaseSchema between local and remote table.
2. skip the check for schema hash value if doing restore.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java [hunk 1]
```diff
@@ -1239,8 +1239,12 @@ public int getSignature(int signatureVersion, List<String> partNames) {
             LOG.debug("signature. index name: {}", indexName);
             MaterializedIndexMeta indexMeta = indexIdToMeta.get(indexId);
             // schema hash
-            adler32.update(indexMeta.getSchemaHash());
-            LOG.debug("signature. index schema hash: {}", indexMeta.getSchemaHash());
+            // schema hash will change after finish schema change. It is make no sense
+            // that check the schema hash here when doing restore
+            if (!isRestore) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/OlapTable.java:1244]: Under which circumstances, the schema change will happen during the backup and restore?

File: fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java [hunk 2]
```diff
@@ -509,14 +510,27 @@ private void checkAndPrepareMeta() {
                         return;
                     }
                     LOG.debug("get intersect part names: {}, job: {}", intersectPartNames, this);
-                    if (localOlapTbl.getSignature(BackupHandler.SIGNATURE_VERSION, intersectPartNames)
-                            != remoteOlapTbl.getSignature(BackupHandler.SIGNATURE_VERSION, intersectPartNames)) {
+                    if (localOlapTbl.getSignature(BackupHandler.SIGNATURE_VERSION, intersectPartNames, true)
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/backup/RestoreJob.java:513]: If there are some columns with different columns, is the data accessible by storage engine after restore?

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]
