### PR TITLE
[BugFix] Persist offsets of all kafka partitions in Routine load if few are altered

### LINKED ISSUE #7775: [BUG] fe start failed: The specified partition 0 is not in the consumed partitions
### Steps to reproduce the behavior (Required)
1. create routine load with kafka topic that has no new data.
2. after the routine load state changed to RUNNING, pause the routine load.
3. alter the routine load progress.

### Expected behavior (Required)
cluster is normal

### Real behavior (Required)
fe is down
```text
com.starrocks.common.DdlException: The specified partition 0 is not in the consumed partitions
        at com.starrocks.load.routineload.KafkaProgress.modifyOffset(KafkaProgress.java:131) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.KafkaRoutineLoadJob.modifyDataSourceProperties(KafkaRoutineLoadJob.java:530) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.RoutineLoadJob.modifyJob(RoutineLoadJob.java:1510) ~[starrocks-fe.jar:?]
        at com.starrocks.load.routineload.RoutineLoadManager.replayAlterRoutineLoadJob(RoutineLoadManager.java:571) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:798) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2499) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2286) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - all

### LINKED ISSUE #12221: Modify kafka offset of routine load multiple times right after created will end up crashed
### Steps to reproduce the behavior (Required)

1. create a routine load job with a topic of four partitions, wait until the progress is recorded, then pause the job.
```sql
CREATE TABLE test_table (i1 INT, s VARCHAR(100),i2 BIGINT) DISTRIBUTED BY HASH(s) BUCKETS 8;
CREATE ROUTINE LOAD test_load ON test_table COLUMNS TERMINATED BY ",", COLUMNS (i1, s, i2) FROM KAFKA(
   "kafka_broker_list" = "172.26.92.139:10042", "kafka_topic" = "jsl");

show all routine load \G
mysql> show all routine load \G
*************************** 1. row ***************************
                  Id: 18118
                Name: test_load
          CreateTime: 2022-10-17 17:15:31
           PauseTime: NULL
             EndTime: NULL
              DbName: test_kafka
           TableName: test_table
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 3
       JobProperties: {"partitions":"*","rowDelimiter":"\t","partial_update":"false","columnToColumnExpr":"i1,s,i2","maxBatchIntervalS":"10","whereExpr":"*","timezone":"Asia/Shanghai","format":"csv","columnSeparator":"','","json_root":"","strict_mode":"false","jsonpaths":"","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"false","currentTaskConcurrentNum":"3","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"jsl","currentKafkaPartitions":"0,1,2,3","brokerList":"172.26.92.139:10042"}
    CustomProperties: {}
           Statistic: {"receivedBytes":0,"errorRows":0,"committedTaskNum":0,"loadedRows":0,"loadRowsRate":0,"abortedTaskNum":0,"totalRows":0,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":1}
            Progress: {"0":"OFFSET_ZERO","1":"OFFSET_ZERO","2":"OFFSET_ZERO","3":"OFFSET_ZERO"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
1 row in set (0.00 sec)

mysql> PAUSE ROUTINE LOAD FOR test_load;
Query OK, 0 rows affected (0.01 sec)

```
2. alter the offsets of two partition in this routine load job, it will be succeed
```sql
ALTER ROUTINE LOAD FOR test_load FROM kafka ("kafka_partitions" = "0,2", "kafka_offsets" = "0,0");
```

3. alter the offsets of all of the partitions in this  routine load job, it will end up crashed.
```sql
mysql> ALTER ROUTINE LOAD FOR test_load FROM kafka ("kafka_partitions" = "0,1,2,3", "kafka_offsets" = "0,0,0,0");
ERROR 1064 (HY000): The specified partition 1 is not in the consumed partitions
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12221, actually fixes #7775 too..

## Problem Summary(Required) ：

1. Alter routine load when partitions are not initialized will be rejected by master.
2. Alter routine load by alter the offsets of some of the partitions will end up persist offsets of all kafka partitions.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaProgress.java|7|7|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java [hunk 1]
```diff
@@ -126,16 +126,22 @@ private void getReadableProgress(Map<Integer, String> showPartitionIdToOffset) {
...
         for (Pair<Integer, Long> pair : kafkaPartitionOffsets) {
-            if (!notInitialized && !partitionIdToOffset.containsKey(pair.first)) {
+            if (!partitionIdToOffset.containsKey(pair.first)) {
                 throw new DdlException("The specified partition " + pair.first + " is not in the consumed partitions");
             }
         }
         for (Pair<Integer, Long> pair : kafkaPartitionOffsets) {
             partitionIdToOffset.put(pair.first, pair.second);
         }
+        // update kafkaPartitionOffsets as well, so that the current partitonIdToOffset can be completely persisted
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java:137]: 1. Why change the kafkaPartitionOffsets in the parameter? I think the parameter should keep unchanged.
2. In commit message, add the solution and results besides the problem description.

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java:137]: 1. To make sure that the parameter is the same with the actual value so that the actual value can be persist.
2. I think I did. I have describe the behavior in my commit on all issues.
But I get your point, I'll add more comments here.

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java (hunk 1 above)
Comment (chaoyli) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java:145]: If kafkaPartitionOffsets is the same as partitionIdToOffset, why not copy it directly instead of a loop?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/load/routineload/KafkaProgress.java:145]: It's not. There's an example described in the comments.
```
    //   if current offset is {0:11, 1:22, 2:33, 3:55}, the parameter `kafkaPartitionOffsets` is {0: 22, 2:44}
    //   in this function, current offset is modified as {0: 22, 1: 22, 2:44, 3:55}
    //   so is the parameter `kafkaPartitionOffsets`.
```

**Review by nshangyiming — APPROVED** [review]

**Comment by nshangyiming** [comment]
run all

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/KafkaProgress.java|7|7|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4 branch-2.3 branch-2.2
¡Muchas gracias!

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.3 branch-2.2
¡Muchas gracias!

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3 branch-2.2

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4
