### PR TITLE
[BugFix] Change timezone cache miss log level from WARNING to VLOG

### LINKED ISSUE #65942: not found timezone
### Steps to reproduce the behavior (Required)
```
W20251125 19:01:08.521512 +0800 140034234809216 timezone_utils.cpp:93]  not found timezone:Africa/Casablanca
W20251125 19:01:08.536134 +0800 140034234809216 timezone_utils.cpp:93]  not found timezone:Africa/El_Aaiun
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhan7236**
## Why I'm doing:

During BE initialization, if some timezones listed in `timezone.dat` or `othertimezone.dat` are not available on the system (e.g., in minimal Docker images without complete tzdata), the current code logs WARNING messages like:

```text
W20251125 19:01:08.521512 +0800 timezone_utils.cpp:93] not found timezone:Africa/Casablanca
W20251125 19:01:08.536134 +0800 timezone_utils.cpp:93] not found timezone:Africa/El_Aaiun
```

These warnings are misleading because the system continues to work normally - timezone lookup has a fallback mechanism that dynamically loads timezones when needed.

## What I'm doing:

Change the log level from `LOG(WARNING)` to `VLOG(1)` for timezone pre-caching failures.

Fixes #65942

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

**Does this PR entail a change in behavior?**

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> Downgrades "not found timezone" pre-caching logs in `be/src/util/timezone_utils.cpp` from `WARNING` to `VLOG(1)`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 3772899ed1c23a89229c5c929fbeafaee020563b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/util/timezone_utils.cpp
Comment (murphyatwork) [inline be/src/util/timezone_utils.cpp:63]: is it necessary to update the `timezone.dat` to remove these two timezones
or upgrade the `cctz` to include these two timezone ?

Comment (kevincai) [reply be/src/util/timezone_utils.cpp:63]: do you know where to get the update-to-dated timezone.dat?

Comment (zhan7236) [reply be/src/util/timezone_utils.cpp:63]: > is it necessary to update the `timezone.dat` to remove these two timezones or upgrade the `cctz` to include these two timezone ?

Thanks for the question! After investigation:

`Africa/Casablanca` and `Africa/El_Aaiun` are valid IANA timezones - they exist in standard `tzdata` packages and are present in `zoneinfo` on most systems.

**The root cause:**
The user who reported the issue likely has an incomplete `tzdata` package installed (common in minimal Docker images). The `cctz` library reads timezone data from the system's `zoneinfo` directory, so if the system doesn't have these timezone files, `cctz` cannot load them.

**Why not remove from `timezone.dat`:**
These are legitimate timezones that should work on properly configured systems. Removing them would break functionality for users who do have complete `tzdata` installed.

**Why not upgrade `cctz`:**
`cctz` doesn't bundle timezone data - it relies on the system's `tzdata`. Upgrading from v2.3 to v2.5 won't add these timezones.

**The fix (changing `WARNING` to `VLOG`) is appropriate because:**
* The system continues to work even without these timezones pre-cached.
* `find_cctz_time_zone()` has a fallback mechanism that dynamically loads timezones when needed.
* The warning was just noise for users with minimal `tzdata` installations.

Comment (zhan7236) [reply be/src/util/timezone_utils.cpp:63]: > do you know where to get the update-to-dated timezone.dat?

The `timezone.dat` file in StarRocks appears to be manually curated based on the IANA timezone database. The source of truth is the **IANA Time Zone Database**.

However, for this specific issue, updating `timezone.dat` isn't necessary because `Africa/Casablanca` and `Africa/El_Aaiun` are already correctly listed in the `timezone.dat`. The problem is that some user environments don't have complete `tzdata` packages installed.

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/util/timezone_utils.cpp [hunk 1]
```diff
@@ -90,7 +92,9 @@ void TimezoneUtils::init_time_zones() {
         if (cctz::load_time_zone(timezone, &ctz)) {
             _s_cached_timezone.emplace(timezone, ctz);
         } else {
-            LOG(WARNING) << "not found timezone:" << timezone;
+            // LCOV_EXCL_START
```
Comment (kevincai) [inline be/src/util/timezone_utils.cpp]: remove this LCOV hack. not necessary.

**Review by kevincai — APPROVED** [review]

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by murphyatwork — APPROVED** [review]
