### PR TITLE
[BugFix] Fix BE crashed in shared_data mode

### LINKED ISSUE #28244: BE process crash in shared_data mode
Screen Shot 2023-07-30 at 13 13 37

### StarRocks version (Required)
 - branch-3.1 70ed32b7296ab8aa83aa16a16bdba2919cd471bc

### PR DESCRIPTION
**Pull request by sduzh**
The pointer `tablet` captured in the lambda function may point to an
already destroyed object.

Fixes #28244 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

File: be/src/storage/lake/tablet_manager.cpp [hunk 1]
```diff
@@ -782,22 +782,20 @@ StatusOr<TabletMetadataPtr> publish(TabletManager* tablet_mgr, Tablet* tablet, i
     auto clear_task = [=]() {
         // Delete txn logs
         auto st = tablet_mgr->delete_txn_log(tablet_id, txn_id);
-        LOG_IF(WARNING, !st.ok()) << "Fail to delete " << tablet->txn_log_location(txn_id) << ": " << st;
+        LOG_IF(WARNING, !st.ok()) << "Fail to delete " << tablet_mgr->txn_log_location(tablet_id, txn_id) << ": " << st;
```
Comment (sduzh) [inline be/src/storage/lake/tablet_manager.cpp:785]: The line of code fixes the problem.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/runtime/exec_env.cpp [hunk 2]
```diff
@@ -624,4 +624,8 @@ int32_t ExecEnv::calc_pipeline_dop(int32_t pipeline_dop) const {
     return std::max<int32_t>(1, _max_executor_threads / 2);
 }
 
+ThreadPool* ExecEnv::vacuum_thread_pool() {
```
Comment (imay) [inline be/src/runtime/exec_env.cpp:627]: I see some callers don't check if the return is nullptr.
How about returning an invalid thread pool rather than a nullptr to avoid a nullptr access exception?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — APPROVED** [review]

**Review by tracymacding — APPROVED** [review]

File: be/src/runtime/exec_env.cpp (hunk 2 above)
Comment (sduzh) [reply be/src/runtime/exec_env.cpp:627]: Hi @imay, for simplicity, I added NULL checks for the vacuum thread pool, PTAL.

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
