### PR TITLE
[BugFix] Modify title 'host' to 'ip'

### LINKED ISSUE #7696: Avoid interface errors caused by changing the ip to host when users use commands such as 'show frontends'
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7696 

## Problem Summary(Required) ：

Avoid interface errors caused by changing the ip to host when users use commands such as 'show frontends'

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/BrokerMgr.java [hunk 1]
```diff
@@ -51,7 +51,7 @@
  */
 public class BrokerMgr {
     public static final ImmutableList<String> BROKER_PROC_NODE_TITLE_NAMES = new ImmutableList.Builder<String>()
-            .add("Name").add("Host").add("Port").add("Alive")
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/BrokerMgr.java:54]: I'm afraid you can't change the title.
Because some old client code depend on this name.
If you change the name, their code will produce error.

Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/catalog/BrokerMgr.java:54]: A previous PR changed the ip to host, and then did find the problem you just mentioned, so this PR is to change the host back to ip

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]
