### PR TITLE
[BugFix] fix MemoryScratchSinkOperator set_cancelled issue

### LINKED ISSUE #59843: [BE] thrift thread hanging forever when doing starrocks::BackendServiceBase::get_next
### Steps to reproduce the behavior (Required)

Spark connector reads data from BE thrift interface `get_next()` after  a succeeded  `open_scanner()` call.

```
    0xe04778af9df8  (/usr/lib/aarch64-linux-gnu/libc.so.6+0x79df8)
    0xe04778afc8fc  pthread_cond_wait
         0xda7e320  std::condition_variable::wait(std::unique_lock<std::mutex>&)
         0x573de7c  starrocks::ResultQueueMgr::fetch_result(starrocks::TUniqueId const&, std::shared_ptr<arrow::RecordBatch>*, bool*)
         0x83dbe54  starrocks::BackendServiceBase::get_next(starrocks::TScanBatchResult&, starrocks::TScanNextBatchParams const&)
         0x863bfc4  starrocks::BackendServiceProcessor::process_get_next(int, apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, void*)
         0x863ed94  starrocks::BackendServiceProcessor::dispatchCall(apache::thrift::protocol::TProtocol*, apache::thrift::protocol::TProtocol*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void*)
         0x863f948  apache::thrift::TDispatchProcessor::process(std::shared_ptr<apache::thrift::protocol::TProtocol>, std::shared_ptr<apache::thrift::protocol::TProtocol>, void*)
         0x999f2b0  apache::thrift::server::TConnectedClient::run()
         0x99a00e4  apache::thrift::server::TThreadedServer::TConnectedClientRunner::run()
         0x99a27fc  apache::thrift::concurrency::Thread::threadMain(std::shared_ptr<apache::thrift::concurrency::Thread>)
         0x997dc3c  std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(std::shared_ptr<apache::thrift::concurrency::Thread>), std::shared_ptr<apache::thrift::concurrency::Thread> > > >::_M_run()
         0xdb005ec  execute_native_thread_routine
    0xe04778afd5c8  (/usr/lib/aarch64-linux-gnu/libc.so.6+0x7d5c8)
    0xe04778b65edc  (/usr/lib/aarch64-linux-gnu/libc.so.6+0xe5edc)
```

However the `open_scanner()` may fail in the middle causing the fragment execution cancelled, but the consumer from `get_next()` interface may not be able to be notified in the case, resulting hanging the thread forever.

### Expected behavior (Required)

No hanging, report error.

### Real behavior (Required)

Hanging.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kevincai**
## What I'm doing:

Fixes #59843

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

**Review by alvin-phoenix-ai — COMMENTED** [review]
could you explain the symptom for this bug and the reason to cause this bug?

**Review by alvin-phoenix-ai — DISMISSED** [review]

**Comment by kevincai** [comment]
> could you explain the symptom for this bug and the reason to cause this bug?

will open an issue describing the bug.

File: be/src/runtime/result_queue_mgr.cpp [hunk 1]
```diff
@@ -79,7 +79,12 @@ Status ResultQueueMgr::fetch_result(const TUniqueId& fragment_instance_id, std::
     } else {
         *eos = true;
     }
-    return Status::OK();
+    if (UNLIKELY(*result == nullptr)) {
+        // return the status of the queue, in case the status is updated during the blocking_get()
```
Comment (trueeyu) [inline be/src/runtime/result_queue_mgr.cpp:83]: Why add this judgment?

**Review by trueeyu — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]

File: be/src/runtime/result_queue_mgr.cpp (hunk 1 above)
Comment (kevincai) [reply be/src/runtime/result_queue_mgr.cpp:83]: there are two cases that the result can be `nullptr`, 1. Sunny case: the fragment execution done, no more data there in the queue. 2. raining case: execution failed, the fragment is canceled, nullptr is added into the result queue in order to wake up all the waiters.

In both cases, the result will be nullptr, but the queue's status will be different.
