### PR TITLE
[BugFix] safe processing simdjson unescape key and string

### LINKED ISSUE #58321: [Crash] BE crash in load json with jsonpaths
### Steps to reproduce the behavior (Required)

```
*** SIGABRT (@0x1f20000f50e) received by PID 62734 (TID 0x15225e7ff640) from PID 62734; stack trace: ***
    @     0x15230ca8ef38 __pthread_once_slow
    @          0x7d9f940 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x15230ca3e730 (/usr/lib64/libc.so.6+0x3e72f)
    @     0x15230ca8ba6c __pthread_kill_implementation
    @     0x15230ca3e686 __GI_raise
    @     0x15230ca28833 __GI_abort
    @          0x3328615 __gnu_cxx::__verbose_terminate_handler() [clone .cold]
    @          0xc47dc56 __cxxabiv1::__terminate(void (*)())
    @          0xc47dcc1 std::terminate()
    @          0xc47de14 __cxa_throw
    @          0x332a2f5 std::__throw_length_error(char const*)
    @          0x42c5b04 void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char const*>(char const*, char const*, std::forward_iterator_tag) [clone .constprop.0]
    @          0x42d0afe starrocks::Status starrocks::JsonReader::_read_rows<starrocks::JsonDocumentStreamParser>(starrocks::Chunk*, int, int*)
    @          0x42cbfe9 starrocks::JsonReader::read_chunk(starrocks::Chunk*, int)
    @          0x42cd324 starrocks::JsonScanner::get_next()
    @          0x6f5f1c1 starrocks::connector::FileDataSource::get_next(starrocks::RuntimeState*, std::shared_ptr<starrocks::Chunk>*)
    @          0x440c7e7 starrocks::ConnectorScanNode::_scanner_thread(starrocks::ConnectorScanner*)
    @          0x37eee3d starrocks::PriorityThreadPool::work_thread(int)
    @          0x7d5ee27 thread_proxy
    @     0x15230ca89d22 start_thread
    @     0x15230cb0ed40 __clone3
```

### Expected behavior (Required)

No crash

### Real behavior (Required)

BE crash

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kevincai**
* replace all simdjson unescape() and get_string() call to a safe version.
* potentially performance degradation due to temp faststring object used for the unescaping.

## What I'm doing:

Fixes #58321

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1

### CODE REVIEW

**Comment by kevincai** [comment]
More UT to be added.

File: be/src/util/simdjson_util.h [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+
+// A wrapper for simdjson::ondemand::value::get_string()
+//   simdjson's value.get_string() will copy the string into its underlying buffer and return the string_view
+// referring to the buffer. The buffer will be never rewound until the doc where this `value` is from is rewound.
+// Although the buffer capacity is a little bit larger than the raw input content. However, with repeatedly
+// reading from the value's string, the buffer is still possible advanced beyond the boundary and results a
+// heap-buffer-overflow. Fix it by unescaping the bytes on the buffer the caller provided.
+inline simdjson::simdjson_result<std::string_view> value_get_string_safe(simdjson::ondemand::value* value,
+                                                                         std::string* buffer) {
+    CHECK(value->type() == simdjson::ondemand::json_type::string);
```
Comment (alvin-celerdata) [inline be/src/util/simdjson_util.h:76]: We should avoid using CHECK, please use DCHECK instead.
It is not good to crash the whole process just because of an invalid parameter.

File: be/src/util/simdjson_util.h [hunk 2]
```diff
@@ -0,0 +1,82 @@
...
+// Although the buffer capacity is a little bit larger than the raw input content. However, with repeatedly
+// reading from the field's unescaped_key, the buffer is still possible advanced beyond the boundary and results
+// a heap-buffer-overflow.
+//   Fix: field.escaped_key() will return a string_view from the original json token, if this string_view passes
+// the free unescaped quote check which means it doesn't contain any escaped characters, return it directly.
+// Otherwise, unescaping the key on the buffer provided by the caller and return a string_view referring to the
+// parsed result.
+template <typename T>
+inline simdjson::simdjson_result<std::string_view> field_unescaped_key_safe(simdjson::simdjson_result<T> field,
+                                                                            std::string* buffer) {
```
Comment (alvin-celerdata) [inline be/src/util/simdjson_util.h:55]: Will you consider to use faststring instead of std::string as buffer, which will be more efficient as a buffer.

File: be/src/util/simdjson_util.h (hunk 1 above)
Comment (kevincai) [reply be/src/util/simdjson_util.h]: done

File: be/src/util/simdjson_util.h (hunk 2 above)
Comment (kevincai) [reply be/src/util/simdjson_util.h]: done

**Review by wyb — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by andyziye** [comment]
@Mergify rebase

**Review by luohaha — APPROVED** [review]

**Review by andyziye — APPROVED** [review]
