### PR TITLE
[BugFix] Fix analyze problem for dict_mapping function (#40897)

### LINKED ISSUE #40897: [BugFix] Fix dict_mapping problems
Problem:
1. Crash when using dict_mapping function with multiple key columns(In debug mode)
2. Crash if there is null value in key columns
3. Crash if there specify NOT bigint type value in value list for insert stmt
4. db not selected if dict_mapping function used in streamload with table name without dbname
5. Do not support type cast for dict_mapping function parameter automatically.
6. Boolean parameter's behavior which indicate return null or exception for dict_mapping if key is not found is unexpected.

Solution:
1. Reset key chunk row in dict_query_expr
2. return error if there is null value for key.
3. Fix the return type for DictQueryOperator
4. Add dbname when analyze load plan for streamload
5. Cast the type in expressionAnalyzer if it can be cast to target type.
6. Change boolean parameter's behavior, if it is false (default) return exception if key not found, if true, return null if key not found.

### PR DESCRIPTION
**Pull request by srlch**
No DB selected:
1. If we execute a streamload with dict_mapping like dict_mapping(dict_table) name
we sill get no db selected exception unless we use dict_mapping(db.dict_table).
It is because ConnectContext.get() is NULL when analyze dict_mapping expression.
2. Add a generated column with dict_mapping like dict_mapping(dict_table) with
get no db selected exception. It is because ConnectContext.get() is NULL
when analyze dict_mapping expression for generated column.

NPE problem:
If we specify a generated column with dict_mapping expression in create table stmt
with wrong column name, will get NPE problem
(See SQL-TEST test_dictmapping_generated_column_in_create_table)

Cast Type problem:
Support dict_table has INT key column, and we call dict_mapping(dict_table, 1) will
fail. Because 1 is tinyint by default.

Solution:

For No DB selected:
Construct a new ConnectContext to analyze

For NPE problem:
Check column is null or not

For Cast Type problem:
Cast the type to target key column type in anaylze phase

Fixes #40897

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java [hunk 1]
```diff
@@ -597,6 +599,16 @@ protected void runWaitingTxnJob() throws AlterCancelException {
                                                     new Field(col.getName(), col.getType(), tableName, null))
                                             .collect(Collectors.toList())));
 
+                            if (ConnectContext.get() == null) {
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java:602]: shouldn't be null?

File: fe/fe-core/src/main/java/com/starrocks/load/Load.java [hunk 2]
```diff
@@ -594,6 +602,23 @@ public static void initColumns(Table tbl, List<ImportColumnDesc> columnExprs,
             }
         }
 
+
+        if (dbName != "") {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/load/Load.java:606]:
```suggestion
        if (!dbName.isEmpty()) {
```

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java (hunk 1 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeJobV2.java:602]: This code path is only used for adding generated column. And if we analyze the expression of the generated column, we may need the ConnectContext to do it.

File: fe/fe-core/src/main/java/com/starrocks/load/Load.java [hunk 3]
```diff
@@ -594,6 +602,23 @@ public static void initColumns(Table tbl, List<ImportColumnDesc> columnExprs,
...
+                if (entry.getValue() != null && checDictQueryExpr(entry.getValue())) {
+                    if (ConnectContext.get() == null) {
+                        ConnectContext context = new ConnectContext();
+                        context.setGlobalStateMgr(GlobalStateMgr.getCurrentState());
+                        context.setCurrentUserIdentity(UserIdentity.ROOT);
+                        context.setCurrentRoleIds(Sets.newHashSet(PrivilegeBuiltinConstants.ROOT_ROLE_ID));
+                        context.setQualifiedUser(UserIdentity.ROOT.getUser());
+                        context.setThreadLocalInfo();
+                    }
+                    ConnectContext.get().setDatabase(dbName);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/load/Load.java:617]: break?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java [hunk 4]
```diff
@@ -484,6 +484,9 @@ public static void analyze(CreateTableStmt statement, ConnectContext context) {
                     if (slots.size() != 0) {
                         for (SlotRef slot : slots) {
                             Column refColumn = columnsMap.get(slot.getColumnName());
+                            if (refColumn == null) {
+                                throw new SemanticException("column:" + slot.getColumnName() + " does not existed");
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java:488]:
```suggestion
                                throw new SemanticException("column:" + slot.getColumnName() + " does not exist");
```

Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CreateTableAnalyzer.java]: done

File: fe/fe-core/src/main/java/com/starrocks/load/Load.java (hunk 3 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/load/Load.java:617]: Updated

File: fe/fe-core/src/main/java/com/starrocks/load/Load.java (hunk 2 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/load/Load.java]: done

File: fe/fe-core/src/main/java/com/starrocks/load/Load.java (hunk 3 above)
Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/load/Load.java:617]: done

**Review by nshangyiming — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Review by packy92 — APPROVED** [review]
