### PR TITLE
[BugFix] fix show mv npe after dropping table and upgrading from 3.1 to 3.2 for main

### LINKED ISSUE #34503: show materialized view throws npe when upgrade sr-3.1 from sr-3.2
### Steps to reproduce the behavior (Required)
install sr-3.1
create database test_mv_async_db_d8023c48_6bea_11ee_bca4_00163e0e489a
use test_mv_async_db_d8023c48_6bea_11ee_bca4_00163e0e489a
admin set frontend config("enable_experimental_mv" = "true");
CREATE TABLE `t1` (
                                    `k1` int,
                                    `k2` int,
                                    `k3` int
                                )
                                DUPLICATE KEY(`k1`)
                                COMMENT "OLAP"
                                DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC START('2023-10-16 14:11:38') EVERY (interval 10 second)
                             AS SELECT k1, k2
                             FROM t1;
INSERT INTO t1 VALUES (1,1,1);
analyze full table test_mv_async_db_d8023c48_6bea_11ee_bca4_00163e0e489a.mv1;

DROP TABLE t1;

then upgrade to sr-3.2, and execute:
show materialized views;

### Expected behavior (Required)
show materialized views succeed.
### Real behavior (Required)
show materialized views failed with npe:
2023-10-16 18:47:53,232 WARN (starrocks-mysql-nio-pool-1|289) [ShowExecutor.handleShowMaterializedView():527] listMaterializedViews failed:
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
        at com.starrocks.catalog.Database.getTable(Database.java:606) ~[starrocks-fe.jar:?]
        at com.starrocks.server.LocalMetastore.getTable(LocalMetastore.java:2650) ~[starrocks-fe.jar:?]
        at com.starrocks.server.MetadataMgr.lambda$getTable$5(MetadataMgr.java:314) ~[starrocks-fe.jar:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at com.starrocks.server.MetadataMgr.getTable(MetadataMgr.java:314) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.BaseTableInfo.getTableByName(BaseTableInfo.java:186) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.BaseTableInfo.getTable(BaseTableInfo.java:146) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.lambda$handleShowMaterializedView$0(ShowExecutor.java:483) ~[starrocks-fe.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
        at com.starrocks.qe.ShowExecutor.handleShowMaterializedView(ShowExecutor.java:482) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ShowExecutor.execute(ShowExecutor.java:279) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleShow(StmtExecutor.java:1416) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:658) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:377) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:569) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:847) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-3.1/Release/starrocks-3359d1b.tar.gz 
branch-3.2/Release/starrocks-f7bbadb.tar.gz

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #34503 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java [hunk 1]
```diff
@@ -993,4 +996,38 @@ public void testCreateMVWithDuplicateIndexOrDuplicateColumn() throws Exception {
                 UserException.class,
                 () -> starRocksAssert.withMaterializedView(mvSql2));
     }
+
+    @Test
+    public void testBaseTableInfo(@Mocked GlobalStateMgr globalStateMgr,
```
Comment (imay) [inline fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java:1001]: My question is why this UT is added to this file?
I think the UT should be added to [BaseTableInfo.java](https://github.com/StarRocks/starrocks/pull/34507/files#diff-735f3a6d5bd4e296e4d624e4dc3cac2ec744f48049f055ff56596cd483211632)

File: fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java [hunk 2]
```diff
@@ -183,6 +183,10 @@ public Table getTableByName() {
             LOG.warn("catalog {} not exist", catalogName);
             return null;
         }
+        // upgrade from 3.1 to 3.2, dbName/tableName maybe null after dbs or tables are dropped
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java:186]: another question is why this function is supported in this class. Having a function called global single instance in such a basic class is unreasonable. This will cause class dependence too messy and bug-prune.

File: fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java:1001]: this class is mv meta related, MaterializedViewTest is mv meta related test. So I add it here.

File: fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java:186]: it is a history problem. refactor is another problem. should I refactor it in another pr?

File: fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/test/java/com/starrocks/catalog/MaterializedViewTest.java:1001]: BaseTableInfoTest.java is another choice, I move the test to it.

File: fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java (hunk 2 above)
Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/catalog/BaseTableInfo.java:186]: Please refactor this later, the current implementation is error-prune.

**Review by imay — APPROVED** [review]

**Review by satanson — APPROVED** [review]
