### PR TITLE
[BugFix] Fix commit timestamp fallback & granularity

### LINKED ISSUE #5783: FE send publish out of order since commit timestamp precision
### Steps to reproduce the behavior (Required)
1. high frequency stream load

### Expected behavior (Required)
1. publish send with commit order

### Real behavior (Required)
截屏2022-05-06 14 56 19

transcation `1114` commit before `1107` but publish after it, cause there commit time are same
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5783

## Problem Summary(Required) ：

since we send publish order by commit timestamp so that we need handle timestamp `fallback` & same timestamp cause by currentTimeMillis() `granularity`

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -914,8 +918,20 @@ protected void unprotectedCommitTransaction(TransactionState transactionState, S
...
             return;
         }
+        // since we send publish order by commit timestamp
+        // so that we need handle timetamp fallback
+        // & same timestamp cause by granularity
+        // The probability of timestamp fallback after FE failover is small
+        // and it is not considered at present
+        long commitTs = System.currentTimeMillis();
+        if (commitTs <= lastCommitTs) {
+            commitTs = lastCommitTs + ++commitTsInc;
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:928]: How about the FE restart?
Is there necessary to persist the commitTsInc and the commitTs?

Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:928]: I have already commented
since the probability is low and not a fatal error, not necessary to persist

**Review by chaoyli — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_be_unittest

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by meegoo** [comment]
@Mergifyio backport branch-2.2

**Comment by meegoo** [comment]
@mergifyio backport branch-2.1

**Comment by meegoo** [comment]
@mergifyio backport branch-2.0
