### PR TITLE
[BugFix] fix union mv when the partitions is unaligned

### LINKED ISSUE #42949: Incorrect result for MV with UNION ALL
### Steps to reproduce the behavior (Required)

```sql
CREATE TABLE IF NOT EXISTS t1 (
    leg_id VARCHAR(100) NOT NULL,
    cabin_class VARCHAR(1) NOT NULL,
    observation_date DATE NOT NULL
)
DUPLICATE KEY(leg_id, cabin_class)
PARTITION BY date_trunc('day', observation_date)

CREATE TABLE IF NOT EXISTS t2 (
    leg_id VARCHAR(100) NOT NULL,
    cabin_class VARCHAR(1) NOT NULL,
    observation_date DATE NOT NULL
)
DUPLICATE KEY(leg_id, cabin_class)
PARTITION BY date_trunc('day', observation_date)


insert into t1 (leg_id, cabin_class, observation_date) values
('FL_123', 'Y', '2024-03-21'),
('FL_124', 'Y', '2024-03-21'),
('FL_125', 'Y', '2024-03-21'),
('FL_126', 'Y', '2024-03-21')

insert into t2 (leg_id, cabin_class, observation_date) values
('FL_123', 'Y', '2024-03-22'),
('FL_124', 'Y', '2024-03-22'),
('FL_125', 'Y', '2024-03-22'),
('FL_126', 'Y', '2024-03-22')


CREATE MATERIALIZED VIEW v1 
PARTITION BY date_trunc('day', observation_date)
DISTRIBUTED BY HASH(leg_id)
REFRESH ASYNC
AS 
SELECT
	t1.leg_id AS leg_id,
	t1.cabin_class AS cabin_class,
	t1.observation_date AS observation_date
FROM
	t1
UNION ALL
SELECT
	t2.leg_id AS leg_id,
	t2.cabin_class AS cabin_class,
	t2.observation_date AS observation_date
FROM
	t2
	
select count(*) from v1 acmv  -- 4, but should be 8
```

### Expected behavior (Required)

- return 8 rows

### Real behavior (Required)

- only generate partitions from t1 but not include t2

### StarRocks version (Required)
- main branch 20240321

### PR DESCRIPTION
**Pull request by murphyatwork**
## Why I'm doing:
- Union MV should merge partitions from all children, but not just the partitions from the first table
- The base tables of Union MV should align their partitions, like daily partitions or monthly partitions, otherwise they cannot be merged

## What I'm doing:

Fixes #42949

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by ABingHuang — DISMISSED** [review]

File: fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java [hunk 1]
```diff
@@ -746,4 +744,122 @@ public void testMaterializedViewPartitionTTL() throws Exception {
...
+                "PARTITION BY date_trunc('day', observation_date)\n" +
+                "DISTRIBUTED BY HASH(leg_id)\n" +
+                "REFRESH ASYNC\n" +
+                "AS \n" +
+                "SELECT * FROM mv_union_t1 t1\n" +
+                "UNION ALL\n" +
+                "SELECT * FROM mv_union_t2 t2\n");
+
+        {
+            Exception e = Assert.assertThrows(IllegalArgumentException.class, () ->
```
Comment (LiShuMing) [inline fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java:839]: 1. Is this a behavior change with previous version? what if refresh mv's all partitions rather than throwing exception?
2. Is that possible to throw exceptions in create mv rather than freshing mv?

Comment (mofeiatwork) [reply fe/fe-core/src/test/java/com/starrocks/analysis/RefreshMaterializedViewTest.java:839]: 1. yes and not. previous behavior is not correct, so we have to prohibit it
2. cannot support this scenario. for example, the union mv consists of two children, the first is `[20240102, 20240105)`, the second is `[20240103, 202408)`, you cannot get a correct partition schema for union mv
3. the good news is, it's not a common case, union mv should be used when the partition schemas of base tables are exactly same
4. It's better to check it when creating, I'll try to add a check

**Review by ABingHuang — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]
LGTM for meta part
