### PR TITLE
[BugFix] Fix the problem of identical analytic expressions

### LINKED ISSUE #7015: use more window function : Vectorized engine does not support the operator
image

```sql
CREATE TABLE `intelli_analysis_ds_day_6298558304d25a14fa546117` (
  `dim1` varchar(10) NOT NULL DEFAULT "" COMMENT "",
  `dim2` varchar(15) NOT NULL DEFAULT "" COMMENT "",
  `dim3` varchar(15) NOT NULL DEFAULT "" COMMENT "",
  `dim4` varchar(6) NOT NULL DEFAULT "" COMMENT "",
  `dim5` varchar(6) NOT NULL DEFAULT "" COMMENT "",
  `rowdata0` decimal128(26, 5) NULL COMMENT "",
  `rowdata1` decimal128(26, 5) NULL COMMENT "",
  `rowdata2` decimal128(26, 5) NULL COMMENT "",
  `metric1` decimal128(26, 5) NULL COMMENT "",
  `metric2` decimal128(26, 5) NULL COMMENT "",
  `metric3` decimal128(26, 5) NULL COMMENT ""
) ENGINE=OLAP 
UNIQUE KEY(`dim1`, `dim2`, `dim3`, `dim4`, `dim5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`dim1`, `dim2`, `dim3`, `dim4`, `dim5`) BUCKETS 1 
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

select
    sum(cur_rowdata2) over(partition by pre_date order by dim2,dim3,dim4,dim5 rows between unbounded preceding and current row) as tmp_metric1,
    sum(cur_rowdata2) over(partition by pre_date order by dim2,dim3,dim4,dim5 rows between unbounded preceding and current row) as tmp_metric2
from (
    select
        t1.dim1 as cur_date,
        t2.dim1 as pre_date,
        t1.dim2,t1.dim3,t1.dim4,t1.dim5,
        t1.rowdata2 as cur_rowdata2
    from (
        select
            dim1,dim2,dim3,dim4,dim5,
            rowdata0,rowdata1,rowdata2,
            metric1,metric2,metric3
        from
            intelli_analysis_ds_day_6298558304d25a14fa546117
        where
            dim1 = '2022-06-03'
            and dim2 <> '' and dim3 <> '' and dim4 <> '' and dim5 <> '' 
            
    ) t1
    left join (
        select
            dim1,dim2,dim3,dim4,dim5,
            rowdata0,rowdata1,rowdata2,
            metric1,metric2,metric3
        from
            intelli_analysis_ds_day_6298558304d25a14fa546117
        where
            dim1 < '2022-06-03'
            and dim2 <> '' and dim3 <> '' and dim4 <> '' and dim5 <> '' 
            
    ) t2
    on
        1 = 1
        and t1.dim2 = t2.dim2 and t1.dim3 = t2.dim3 and t1.dim4 = t2.dim4 and t1.dim5 = t2.dim5 
) t3
```

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7015

## Problem Summary(Required) ：

The root cause is the `AnalyticWindow` missing `hashCode` function, leading to `ExpressionMapping::hasExpression` failed to match the identical peers

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/WindowTransformer.java|4|4|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java [hunk 1]
```diff
@@ -246,8 +246,10 @@ public static List<WindowTransformer.PartitionGroup> reorderWindowOperator(
                         SqlToScalarOperatorTranslator.translate(analyticExpr, subOpt.getExpressionMapping());
                 ColumnRefOperator columnRefOperator =
                         columnRefFactory.create(agg.toString(), agg.getType(), agg.isNullable());
-                analyticCall.put(columnRefOperator, (CallOperator) agg);
-                subOpt.getExpressionMapping().put(analyticExpr, columnRefOperator);
+                if (agg instanceof CallOperator) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java:249]: why need this if conditions? when one analyticExpr is call operator?

Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java:249]: Yes, if there are two identical analyticExprs, then the second expr will be `ColumnRefOperator`

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java [hunk 2]
```diff
@@ -463,9 +465,7 @@ public WindowOperator(AnalyticExpr analyticExpr, List<Expr> partitionExprs,
         }
 
         public void addFunction(AnalyticExpr analyticExpr) {
-            if (!windowFunctions.contains(analyticExpr)) {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/WindowTransformer.java:466]: why delete if condition, windowFunction contains same analyticExpr is valid?

File: fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java [hunk 3]
```diff
@@ -376,6 +381,11 @@ public boolean equals(Object obj) {
                 && rightBoundaryEqual;
     }
 
+    @Override
+    public int hashCode() {
+        return Objects.hash(type_, leftBoundary_, rightBoundary_, toSqlString_);
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java:386]: need toSqlString_?  euqal method no toSqlString_.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java [hunk 4]
```diff
@@ -89,7 +89,7 @@ public static ColumnRefOperator findOrCreateColumnRefForExpr(Expr expression, Ex
                                                                  ColumnRefFactory columnRefFactory) {
         ColumnRefOperator columnRef;
         ScalarOperator scalarOperator = SqlToScalarOperatorTranslator.translate(expression, expressionMapping);
-        if (expressionMapping.hasExpression(expression) || scalarOperator.isColumnRef()) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java:92]: why change this?

File: fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java (hunk 3 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/analysis/AnalyticWindow.java:386]: sry, haven't notice that. I'll remove this field

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AnalyticWindow.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java (hunk 4 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java:92]: `ScalarOperator scalarOperator = SqlToScalarOperatorTranslator.translate(expression, expressionMapping);`
always returns `ColumnRefOperator` if test `expressionMapping.hasExpression(expression)` is positive.
Otherwise, the below cast expression will throw exception.

So the condition is redundant, and I removed it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/AnalyticWindow.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/SqlToScalarOperatorTranslator.java|1|1|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.3

**Comment by liuyehcf** [comment]
Fixed in `2.2.3`
