### PR TITLE
[BugFix] Unpack const column when in local exchange source operator

### LINKED ISSUE #42884: be node crash after execute a sql
### Steps to reproduce the behavior (Required)
1. execute the sql 
SELECT
base_query.*
FROM
(
SELECT
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) as i_v_xxx621_column_8cRm0F7LlVYKmR0BOw7E_1705645931677,
IF(
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) > 400,
count(
distinct xxx621_column_8cRm0F7LlVYKmR0BOw7E
) -400,
0
) as i_v_column88975_1705646119869,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
) as i_v_column88975_1705647714467,
IF(
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
) < 40,
40 - sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 3 then 1
else 0
end
),
0
) as i_v_column88975_1705653314373,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 2 then 1
else 0
end
) as i_v_column88975_1705647914706,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 1 then 1
else 0
end
) as i_v_column88975_1705647925854,
sum (
case
when xxx621_column_m3IUm0DqsDvPW3CvBZWb = 4 then 1
else 0
end
) as i_v_column88975_1705651769346,
xxx62789_e7345f93cd4081345351b83af60344e1.xxx621_column_9yuJpqD4RY71YXztBUCC as xxx621_column_9yuJpqD4RY71YXztBUCC,
grouping(xxx621_column_9yuJpqD4RY71YXztBUCC) as xxx621_column_9yuJpqD4RY71YXztBUCC_total_flag
from
xxx62789_e7345f93cd4081345351b83af60344e1
group by
grouping sets (
(),
(xxx621_column_9yuJpqD4RY71YXztBUCC)
)
) AS base_query
order by
xxx621_column_9yuJpqD4RY71YXztBUCC_total_flag desc,
base_query.xxx621_column_9yuJpqD4RY71YXztBUCC asc
LIMIT
6000 OFFSET 0

xxx62789_e7345f93cd4081345351b83af60344e1  this is a cte ( with multi table join ) 

### Expected behavior (Required)

normal return 

### Real behavior (Required)

be node down 

be.out trace 

*** Aborted at 1705967445 (unix time) try "date -d @1705967445" if you are using GNU date ***
PC: @          0x2d57320 starrocks::vectorized::FixedLengthColumnBase<>::append_selective()
*** SIGSEGV (@0x1000) received by PID 14905 (TID 0x7ffb0cafb700) from PID 4096; stack trace: ***
    @          0x5b97b22 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ffbd8c54630 (unknown)
    @          0x2d57320 starrocks::vectorized::FixedLengthColumnBase<>::append_selective()
    @          0x50cb458 starrocks::vectorized::NullableColumn::append_selective()
    @          0x50ae6ca starrocks::vectorized::Chunk::append_selective()
    @          0x324dfbe starrocks::pipeline::LocalExchangeSourceOperator::_pull_shuffle_chunk()
    @          0x324e897 starrocks::pipeline::LocalExchangeSourceOperator::pull_chunk()
    @          0x2d906c0 starrocks::pipeline::PipelineDriver::process()
    @          0x51add6a starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x4b968f2 starrocks::ThreadPool::dispatch_thread()
    @          0x4b9138a starrocks::Thread::supervise_thread()
    @     0x7ffbd8c4cea5 start_thread
    @     0x7ffbd8267b0d __clone
    @                0x0 (unknown)

### StarRocks version (Required)

2.5.10 9feb716

### PR DESCRIPTION
**Pull request by LiShuMing**
## Why I'm doing:
- BE may crash when local source exchange operator handle a const column because chunk#append_selective cannot handle const colulmn.
- And this  always happens when chunk is ouptuted by repeat node.

## What I'm doing:
- Introduce `unpack_and_duplicate_const_columns ` method in chunk.
- Apply unpack_and_duplicate_const_columns in local_exchange_source_operator before `chunk#append_selective `
- Consider grouping/grouping_id in `RewriteGroupingSetsByCTERule `
- Add more tests.

Fixes [#issue](https://github.com/StarRocks/starrocks/issues/42884)

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

**Review by ZiheLiu — DISMISSED** [review]

**Comment by trueeyu** [comment]
Better to implement one interface `append_selective_safety` which can handle ConstColumn

File: be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp [hunk 1]
```diff
@@ -41,6 +41,10 @@ Status LocalExchangeSourceOperator::add_chunk(ChunkPtr chunk, const std::shared_
     if (_is_finished) {
         return Status::OK();
     }
+
+    // unpack chunk's const column, since Chunk#append_selective cannot be const column
+    chunk->unpack_and_duplicate_const_columns();
```
Comment (Seaven) [inline be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp:46]: if other case return const_null, it will crash in here too...

**Review by Seaven — APPROVED** [review]

File: be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp (hunk 1 above)
Comment (LiShuMing) [reply be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp:46]: Yep. Later we may support const column in Chunk/Column's `append_selective` to fix this totally.

**Review by trueeyu — APPROVED** [review]
