### PR TITLE
[BugFix] Fix collect query detail bug

### LINKED ISSUE #9185: [BUG] API /api/query_detail can not get the forwarded stmt
### Steps to reproduce the behavior (Required)
execute the following stmt on a non-leader fe
```
show frontends;
```
execute the following cmd and the ip points to the non-leader fe
```
curl http://root:@ip:http_port/api/query_detail?event_time=0
```

### Expected behavior (Required)
the query_detail api should return the `show frontends` query detail.

### Real behavior (Required)
`show frontends` query detail dose not exist in the api's result

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9185

## Problem Summary(Required) ：

QueryDetail is added as a RUNNING event in the StmtExecutor.execute, and is added as a FINISH/FAIL event at the end of ConnectProcessor.handleQuery. But if the query is forward to leader, the query is only added as a Running event, because the process of forward stmt if another function in the ConnectProcessor. This will cause some statements (`show frontends` `show load`) to keep showing running on the Starrocks manager. To fix this bug, we should add the RUNNING event at the begin of ConnectProcessor.handleQuery. In this scenario, the QueryDetail will be recorded in the fe who received the query, and this is same to the record of audit log.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 19 (21.05%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/ConnectProcessor.java|4|19|21.05%|[243, 244, 246, 248, 249, 250, 253, 254, 255, 257, 259, 260, 261, 263, 264]|

**Review by padmejin — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java [hunk 1]
```diff
@@ -271,6 +302,12 @@ private void handleQuery() {
                 parsedStmt = stmts.get(i);
                 parsedStmt.setOrigStmt(new OriginStatement(originStmt, i));
 
+                // Only add the last running stmt for multi statement,
+                // because the audit log will only show the last stmt.
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java:306]: How to handle the failure of `show frontends`?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectProcessor.java:306]: The failure of stmt will also be recorded at the end of handleQuery, because it has catched all exceptions.

**Review by chaoyli — APPROVED** [review]

**Comment by gengjun-git** [comment]
https://github.com/Mergifyio backport branch-2.1 branch-2.2 branch-2.3
