### PR TITLE
[BugFix] Fix mv rewrite bug for aggregat with having expr

### LINKED ISSUE #27424: GroupBy + Having with Rollup can not be rewritten by MV
### Steps to reproduce the behavior (Required)
```
CREATE TABLE A_BRP_LARGE_AMT_TXN_DAY_STAT (
etl_dt date NULL,
party_id varchar(240) NULL,
debit_crdt_flag varchar(30) NULL,
open_acct_org_no varchar(60) NULL,
cvt_rmb_txn_amt decimal128(22, 2) NULL
) ENGINE=OLAP
DUPLICATE KEY(etl_dt, party_id)
-- PARTITION BY RANGE(etl_dt) (p20221230, p20230331)
DISTRIBUTED BY HASH(etl_dt, party_id) BUCKETS 1;



CREATE MATERIALIZED VIEW IF NOT EXISTS TEST_MV_1
--  PARTITION BY ETL_DT
DISTRIBUTED BY HASH(ETL_DT, party_id) BUCKETS 50
-- REFRESH ASYNC START('2023-07-15 08:00:00') EVERY (INTERVAL 1 DAY)
REFRESH MANUAL
as
  select
      debit_crdt_flag,
      party_id,
      ETL_DT,
      sum(cvt_rmb_txn_amt) as sum_amt
    from
      DMRBM_DATA.A_BRP_LARGE_AMT_TXN_DAY_STAT p1
    group by
      1, 2, 3

```

SQL should be rewritten by above mv:
```
 select
      party_id,
      sum(cvt_rmb_txn_amt) as sum_amt
    from
      DMRBM_DATA.A_BRP_LARGE_AMT_TXN_DAY_STAT p1
    where
      p1.debit_crdt_flag = '02'
      and p1.ETL_DT = "2023-03-31"
    group by
      1
      having sum(cvt_rmb_txn_amt) > 50000;
```
### Expected behavior (Required)
SQL should be rewritten by above mv.
### Real behavior (Required)
SQL is not rewritten by above mv.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #27424 

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|7|10|70.00%|[193, 194, 195]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 12 / 15 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|7|10|70.00%|[193, 194, 195]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MVColumnPruner.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 54 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[2122]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|2|3|66.67%|[423]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|20|25|80.00%|[200, 201, 209, 210, 211]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|21|23|91.30%|[153, 190]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 54 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[2122]|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStmt.java|2|3|66.67%|[423]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|20|25|80.00%|[200, 201, 209, 210, 211]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|21|23|91.30%|[153, 190]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 53 / 63 (84.13%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[2122]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|28|33|84.85%|[206, 207, 215, 216, 217]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|23|27|85.19%|[169, 206, 260, 1083]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java [hunk 1]
```diff
@@ -1086,7 +1086,7 @@ public void setEnableParallelMerge(boolean enableParallelMerge) {
     private String queryExcludingMVNames = "";
 
     @VarAttr(name = QUERY_INCLUDING_MV_NAMES, flag = VariableMgr.INVISIBLE)
-    private String queryincludingMVNames = "";
+    private String queryIncludingMVNames = "";
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:1089]: use includingMVNames directly？
query prefix is useless?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java [hunk 2]
```diff
@@ -93,21 +88,6 @@ public ScalarOperator getMvPruneConjunct() {
         return mvPruneConjunct;
     }
 
-    public List<ScalarOperator> getQueryJoinOnPredicates() {
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java:96]: why remove this?

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java [hunk 3]
```diff
@@ -194,6 +192,37 @@ protected OptExpression rewriteProjection(RewriteContext rewriteContext,
...
+                ScalarOperator rewritten = rewriteScalarOperator(entry.getValue(),
+                        queryExprToMvExprRewriter, rewriteContext.getOutputMapping(),
+                        originalColumnSet, aggregateFunctionRewriter);
+                if (rewritten == null) {
+                    logMVRewrite(mvRewriteContext, "Rewrite aggregate with having expr failed: %s", scalarOp.toString());
+                    return null;
+                }
+                queryColumnRefToScalarMap.put(entry.getKey(), rewritten);
+            }
+            ReplaceColumnRefRewriter rewriter = new ReplaceColumnRefRewriter(queryColumnRefToScalarMap);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:211]: why not use newQueryProjection as the argument, avoid reconstructing queryColumnRefToScalarMap?

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java (hunk 1 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:1089]: `queryIncludingMVNames ` indicates this query can use which mvs to rewrite.
`queryExcludingMVNames ` indicates this query can not use which mvs to rewrite.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java (hunk 2 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewriteContext.java:96]: Since join's on predicates have been checked in `computeCompatibility`, no need to check this any more?
```
            if (! ScalarOperator.isEquivalent(queryJoin.getOnPredicate(), (mvJoin.getOnPredicate()))) {
                logMVRewrite(mvRewriteContext, "join predicate is different {} != {}", queryJoin.getOnPredicate(),
                        mvJoin.getOnPredicate());
                return false;
            }
```

However maybe `ScalarOperator.isEquivalent` cannot handle some `Equivalent` operator, maybe we can optimize it later?

eg:
Q  : a left b on a.c1=b.c1 and a.c2 > 10
MV : a left b on a.c1=b.c1 and a.c2 >= 9

**Review by ABingHuang — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 53 / 63 (84.13%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|2|50.00%|[2126]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java|28|33|84.85%|[206, 207, 215, 216, 217]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|23|27|85.19%|[169, 206, 260, 1083]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewritePreprocessor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
