### PR TITLE
BugFix: Colocate table's tablet cannot be repaired after be is dropped

### LINKED ISSUE #5128: Colocate table's tablet cannot be repaired after be is dropped
If there is a redundant replica and the redundant replica has a missing version, it will go through the VERSION_INCOMPLETE process, and if this replica corresponds to a be that has been dropped, the repair will never be completed.

### Steps to reproduce the behavior (Required)
1. build a sr cluster with 3 be.
2. CREATE A CLOCATE Table with 3 replication number.
3. stop one of be and load some data to table.
4. drop the stopped be and add a new be.

### Expected behavior (Required)
The replica on the dropped be should be dropped.

### Real behavior (Required)
All the repair of table is pending on VERSION_INCOMPLETE state.
image

### StarRocks version (Required)
all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5128

## Problem Summary(Required) ：

We should not repair the replica that is not in the colocate backends set, this kind of replica should be dropped.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|2|100.00%|

**Comment by chaoyli** [comment]
Why the colocate tablet should be repaired after dropping the BE?

File: fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java [hunk 1]
```diff
@@ -573,6 +573,12 @@ public TabletStatus getColocateHealthStatus(long visibleVersion,
 
         // 2. check version completeness
         for (Replica replica : replicas) {
+            // do not check the replica that is not in the colocate backend set,
+            // this kind of replica should be drooped.
+            if (!backendsSet.contains(replica.getBackendId())) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:578]: Why the colocate tablet should be repaired after dropping the BE?

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:578]: The replica record in meta should be removed.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/catalog/LocalTablet.java:578]: The bug is: current sr will try to catch up the replica version of the dropped be, and it will never success.

**Review by padmejin — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
