### PR TITLE
[BugFix] fix memory UAF issue of parse_datetime function

### LINKED ISSUE #37814: stack-use-after-return
### Steps to reproduce the behavior (Required)
1. ./run-be-ut

### Expected behavior (Required)
All tests passed

### Real behavior (Required)
Many tests failed
```
^[[0;32m[ RUN      ] ^[[mParseDateTimeTest/ParseDateTimeTestFixture.parse_datetime/31
=================================================================
==1921919==ERROR: AddressSanitizer: stack-use-after-return on address 0x7fcd4a4ee840 at pc 0x000019a75c87 bp 0x7fff8558d450 sp 0x7fff8558d448
READ of size 8 at 0x7fcd4a4ee840 thread T0
I1226 16:49:32.667063 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:33.667169 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:34.667282 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:35.667383 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:36.667500 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:37.667598 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:38.667776 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
I1226 16:49:39.667884 1922089 load_channel_mgr.cpp:249] Memory consumption(bytes) limit=16333303615 current=0 peak=0
    #0 0x19a75c86 in starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12::operator()() const /home/alex/code/starrocks/be/src/runtime/datetime_value.cpp:340:21
    #1 0x19a75784 in bool std::__invoke_impl<bool, starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12&>(std::__invoke_other, starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61:14
    #2 0x19a75724 in std::enable_if<is_invocable_r_v<bool, starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12&>, bool>::type std::__invoke_r<bool, starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12&>(starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:114:9
    #3 0x19a7558c in std::_Function_handler<bool (), starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>)::$_12>::_M_invoke(std::_Any_data const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290:9
    #4 0xe1af352 in std::function<bool ()>::operator()() const /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590:9
    #5 0x19a53c4e in starrocks::joda::JodaFormat::parse(std::basic_string_view<char, std::char_traits<char>>, starrocks::DateTimeValue*) /home/alex/code/starrocks/be/src/runtime/datetime_value.cpp:515:14
    #6 0xd6fa8d1 in starrocks::ParseDateTimeTestFixture_parse_datetime_Test::TestBody() /home/alex/code/starrocks/be/test/runtime/datetime_value_test.cpp:1430:5
    #7 0x1e7c2a73 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2433:27
    #8 0x1e7c2a73 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2469:52
    #9 0x1e7b881d in testing::Test::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2508:50
    #10 0x1e7b881d in testing::Test::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2498:6
    #11 0x1e7b8984 in testing::TestInfo::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2684:14
    #12 0x1e7b8984 in testing::TestInfo::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2657:6
    #13 0x1e7b8a74 in testing::TestSuite::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2816:31
    #14 0x1e7b8a74 in testing::TestSuite::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2795:6
    #15 0x1e7b9035 in testing::internal::UnitTestImpl::RunAllTests() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:5338:47
    #16 0x1e7b9270 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2433:27
    #17 0x1e7b9270 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:2469:52
    #18 0x1e7b9270 in testing::UnitTest::Run() /home/alex/code/starrocks/thirdparty/src/googletest-release-1.10.0/googletest/src/gtest.cc:4925:55
    #19 0xa38cc10 in RUN_ALL_TESTS() /home/alex/code/starrocks/thirdparty/installed/include/gtest/gtest.h:2473:46
    #20 0xa3714d4 in starrocks::init_test_env(int, char**) /home/alex/code/starrocks/be/src/testutil/init_test_env.h:107:13
    #21 0xa371c61 in main /home/alex/code/starrocks/be/test/test_main.cpp:18:12
    #22 0x7fcd4c429d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #23 0x7fcd4c429e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #24 0xa2ad594 in _start (/home/alex/code/starrocks/be/ut_build_ASAN/test/starrocks_test_part1+0xa2ad594) (BuildId: fd70499e1eff87dba38fc1bf7706e3706d71ee23)

Address 0x7fcd4a4ee840 is located in stack of thread T0 at offset 64 in frame
    #0 0x19a4f24f in starrocks::joda::JodaFormat::prepare(std::basic_string_view<char, std::char_traits<char>>) /home/alex/code/starrocks/be/src/runtime/datetime_value.cpp:130

  This frame has 21 object(s):

```

### StarRocks version (Required)
 - 821fc7f51f17a32edcf651378c01f489fc4e7d26

### Compiler
- Clang 15.0.7

### PR DESCRIPTION
**Pull request by murphyatwork**
Why I'm doing:
- The `ptr` is a volatile pointer, which would be freed after the function, but captured by the lambda
- Function `parse_jodatime` would crash the BE 

What I'm doing:
- Make the lambda capture character value of `*ptr` 

Fixes #37814

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by stdpain — DISMISSED** [review]

File: be/src/runtime/datetime_value.cpp [hunk 1]
```diff
@@ -311,16 +312,16 @@ bool JodaFormat::prepare(std::string_view format) {
         }
         case joda::JodaFormatChar::CLOCKHOUR_OF_HALFDAY:
         case joda::JodaFormatChar::CLOCKHOUR_OF_DAY:
-            _token_parsers.emplace_back([&, repeat_count]() {
+            _token_parsers.emplace_back([&, ch, repeat_count]() {
```
Comment (imay) [inline be/src/runtime/datetime_value.cpp:315]: It is better to catch what you need not to catch all.

**Review by ZiheLiu — APPROVED** [review]

**Review by packy92 — APPROVED** [review]
