### PR TITLE
Provide matched num_rows when array's columns is empty

### LINKED ISSUE #4349: array_overlap(empty array) fail
### Steps to reproduce the behavior (Required)
1. 
```
CREATE TABLE `array_data_type` ( c1 int, c2 array<date>, c3 array<datetime>, c4 array<char(20)>, c5 array<varchar(20)>, c6 array<boolean>, c7 array<tinyint>, c8 array<smallint>, c9 array<int>, c10 array<bigint>, c11 array<largeint>, c12 array<float>, c13 array<double>, c14 array<decimal> ) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) buckets 1 PROPERTIES ("replication_num"="1")
```
2. 
```
insert into array_data_type (c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14)values (1, ['2012-01-02', '2012-01-01', '2012-01-04'], ['2012-01-04 01:01:01', '2012-01-03 01:01:01', '2013-01-01 01:01:01'], ['22', '33', '11'], ['222', null, '111'], [False, True, False], [2, 1, 3], [22, 11, 33], [null, null, null], [null, null, null], [3333, 4231, 1111], [11.2, 11.1, 10.1], [11.11, 8.99, 4.44], [1.561, 9.553, 4.682]), (2, ['2013-01-02', '2013-01-01', '2014-01-04'], ['2013-01-04 01:01:01', '2013-01-03 01:01:01', '2010-01-01 01:01:01'], ['22', '33', '11', '66'], ['222', null, null, '000'], [False, True, False], [2, 4, 3], [22, 11, 33], [222, 111, 333], [null, null, null], [3343, 4831, 1711], [11.3, 11.2, 10.2], [11.22, 8.77, 4.33], [3.531, 5.653, 8.882]);
```
3. 
```
select array_overlap([],c9) from array_data_type;
```

### Expected behavior (Required)
0
### Real behavior (Required)
ERROR 1064 (HY000): Index: 0, Size: 0
### StarRocks version (Required)
```
+------------------------------------------+
| current_version()                        |
+------------------------------------------+
| PIPELINE_SQLANCER_MASTER_RELEASE b61b70b |
+------------------------------------------+
```

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/4349 and https://github.com/StarRocks/starrocks/issues/4344

## Problem Summary(Required) ：

Provide right num_rows when array's columns is empty.

### CODE REVIEW

File: be/src/exprs/vectorized/array_expr.cpp [hunk 1]
```diff
@@ -21,6 +21,9 @@ class ArrayExpr final : public Expr {
         const size_t num_elements = _children.size();
 
         size_t num_rows = 1;
+        if (num_elements == 0 && chunk) {
```
Comment (kangkaisen) [inline be/src/exprs/vectorized/array_expr.cpp:24]: Don‘t get this logic.

Comment (Pslydhh) [reply be/src/exprs/vectorized/array_expr.cpp:24]: SQL like "select **array_overlap([],c9)** from array_data_type", [] can't generate more rows than 1, It can't match with c9's size. if num_elements == 0 we should give right num_rows.

Comment (kangkaisen) [reply be/src/exprs/vectorized/array_expr.cpp:24]: Add comments for it

Comment (Pslydhh) [reply be/src/exprs/vectorized/array_expr.cpp:25]: > Add comments for it

done

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by stdpain** [comment]
maybe we could remove 
```
num_rows = std::max(num_rows, col->size());
```
and add before fill array columns
```
        if (chunk) {
            num_rows = chunk->num_rows();
        }
```

**Review by satanson — APPROVED** [review]
