### PR TITLE
[BugFix] Fix INSERT OVERWRITE BY NAME Fails with SQL Unknown Error

### LINKED ISSUE #58762: INSERT OVERWRITE BY NAME Fails with SQL Unknown Error
### Steps to reproduce the behavior (Required)
1. CREATE 2 TABLES 

```
CREATE TABLE my_table (
    id VARCHAR(64) NOT NULL,
    uid BIGINT NOT NULL AUTO_INCREMENT
)
PRIMARY KEY (`id`);

CREATE TABLE my_other_table (
    id VARCHAR(64) NOT NULL,
    uid BIGINT NOT NULL AUTO_INCREMENT
)
PRIMARY KEY (`id`);
```

2. Insert into `my_other_table`:

```
INSERT INTO my_other_table (id) VALUES ("o1")
```

3. Insert Overwrite By name into the `my_table`: 

```
INSERT OVERWRITE my_table BY NAME
SELECT id FROM my_other_table;
```

### Expected behavior (Required)

The insertion should go throught. 

### Real behavior (Required)

Getting the following error from StarRocks:

```
SQL Error [1064] [42000]: Unknown error
```

### StarRocks version (Required)

```
current_version()|
-----------------+
3.4.2-c15ba7c    |
```

### Insert Overwrite Query Plan

Running:
```
EXPLAIN INSERT OVERWRITE my_table BY NAME
SELECT id FROM my_other_table;
```

Yields the following:

```
Explain String                                                                 |
-------------------------------------------------------------------------------+
PLAN FRAGMENT 0                                                                |
 OUTPUT EXPRS:1: id | 3: expr                                                  |
  PARTITION: RANDOM                                                            |
                                                                               |
  OLAP TABLE SINK                                                              |
    TABLE: my_table                                                            |
    TUPLE ID: 2                                                                |
    RANDOM                                                                     |
                                                                               |
  1:Project                                                                    |
  |  <slot 1> : 1: id                                                          |
  |  <slot 3> : NULL                                                           |
  |                                                                            |
  0:OlapScanNode                                                               |
     TABLE: my_other_table                                                     |
     PREAGGREGATION: ON                                                        |
     partitions=1/1                                                            |
     rollup: my_other_table                                                    |
     tabletRatio=16/16                                                         |
     tabletList=12008,12009,12010,12011,12012,12013,12014,12015,12016,12017 ...|
     cardinality=1                                                             |
     avgRowSize=3.0                                                            |
```

### PR DESCRIPTION
**Pull request by rohitrs1983**
Fixes #58762 

InsertAnalyzer.analyzeWithDeferredLock() is invoked 2 times, on first invocation targetcolumns is null and this check is success; and targetcols is updated with cols specified in select list. When InsertAnalyzer.analyzeWithDeferredLock() is invoked second time for InertOverwriteJob, targetcolumns is not null, it contains the colums from select list. so this check will fail.

mysql> CREATE TABLE my_table (id VARCHAR(64) NOT NULL, uid BIGINT NOT NULL AUTO_INCREMENT) PRIMARY KEY (`id`);
Query OK, 0 rows affected (0.03 sec)

mysql> CREATE TABLE my_other_table (id VARCHAR(64) NOT NULL, uid BIGINT NOT NULL AUTO_INCREMENT) PRIMARY KEY (`id`);
Query OK, 0 rows affected (0.22 sec)

mysql> INSERT INTO my_other_table (id) VALUES ("o1");
Query OK, 1 row affected (0.58 sec)
{'label':'insert_6bb693d9-3897-11f0-8111-fe188ababd24', 'status':'VISIBLE', 'txnId':'23087'}

mysql> INSERT OVERWRITE my_table BY NAME SELECT id FROM my_other_table;
Query OK, 1 row affected (0.27 sec)
{'label':'insert_74dad179-3897-11f0-8111-fe188ababd24', 'status':'VISIBLE', 'txnId':'23089'}

mysql> select * from my_table;
+------+------+
| id   | uid  |
+------+------+
| o1   |    1 |
+------+------+
1 row in set (0.02 sec)

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [X] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.5
  - [X] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java [hunk 1]
```diff
@@ -242,7 +242,9 @@ public static void analyzeWithDeferredLock(InsertStmt insertStmt, ConnectContext
                 }
             }
 
-            Preconditions.checkState(insertStmt.getTargetColumnNames() == null);
+            if (insertStmt.isOverwrite()) {
+                Preconditions.checkState(insertStmt.getTargetColumnNames() == null);
+            }
```
Comment (alvin-celerdata) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java:247]: Could you explain why this caused an Unknown Error before this change? 
It confuses me that the precondition of `insertStmt.getTargetColumnNames() == null` doesn't match.

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java:247]: @alvin-celerdata InsertAnalyzer.analyzeWithDeferredLock() is invoked 2 times, on first invocation targetcolumns is null and this check is success; when InsertAnalyzer.analyzeWithDeferredLock() is invoked second time for InertOverwriteJob, targetcolumns have the initialized the select columns. so this check will fail.

Comment (alvin-celerdata) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java:247]: If this is the case, I would suggest removing this state check directly.
By the way, could you include this explanation in the commit message?

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java]: @alvin-celerdata removed the state check.

Comment (alvin-celerdata) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java]: image

Hi @rohitrs1983 what I mean is to add the explanation here in the photo, so that everyone can know it.

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/InsertAnalyzer.java]: @alvin-celerdata updated.

**Comment by alvin-celerdata** [comment]
@mergify rebase

**Comment by alvin-celerdata** [comment]
@mergify rebase

**Review by alvin-phoenix-ai — APPROVED** [review]
