### PR TITLE
[Enhancement] fix status check for exchange

### LINKED ISSUE #27471: [Proposal] make sure each returned Status is handled explicitly
Status is not handled properly in many places in our code. It is easy to find such problems through error injection, such as #27033 , #27160 , and #26291.
Once this type of error occurs, it may lead to errors in subsequent data processing, and it is difficult to troubleshoot when problems occur.
So I propose to add the nodiscard keyword to Status to ensure that each returned Status can be clearly processed, otherwise a warning will be generated when compiling

https://github.com/StarRocks/starrocks/pull/27411 is the work I am doing, but there are a lot of changes, and it needs to be gradually split into multiple PRs.

### PR DESCRIPTION
**Pull request by before-Sunrise**
Fixes https://github.com/StarRocks/starrocks/issues/27471

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 12 (41.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[275, 276, 645]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.h|1|2|50.00%|[128]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.cpp|1|2|50.00%|[226]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.h|1|2|50.00%|[111]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.cpp|2|3|66.67%|[27]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 14 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[385, 388]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[275, 276, 645]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.h|1|2|50.00%|[128]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.cpp|1|2|50.00%|[226]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.h|1|2|50.00%|[111]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.cpp|2|3|66.67%|[27]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 5 / 14 (35.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[385, 388]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[275, 276, 645]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.h|1|2|50.00%|[128]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.cpp|1|2|50.00%|[226]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.h|1|2|50.00%|[111]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.cpp|2|3|66.67%|[27]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 4 / 12 (33.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[385, 388]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[143]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|2|00.00%|[273, 645]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.h|1|2|50.00%|[128]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.h|1|2|50.00%|[111]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.cpp|2|3|66.67%|[27]|

File: be/src/exec/pipeline/exchange/exchange_sink_operator.cpp [hunk 1]
```diff
@@ -270,9 +270,10 @@ Status ExchangeSinkOperator::Channel::send_one_chunk(RuntimeState* state, const
     return Status::OK();
 }
 
-Status ExchangeSinkOperator::Channel::send_chunk_request(RuntimeState* state, PTransmitChunkParamsPtr chunk_request,
-                                                         const butil::IOBuf& attachment,
-                                                         int64_t attachment_physical_bytes) {
+[[nodiscard]] Status ExchangeSinkOperator::Channel::send_chunk_request(RuntimeState* state,
```
Comment (silverbullet233) [inline be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:273]: this nodiscard can be removed, adding it where the function is declared is enough

File: be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp [hunk 2]
```diff
@@ -21,18 +21,18 @@ namespace starrocks::pipeline {
...
+        return;
     }
     size_t memory_usage = chunk->memory_usage();
     size_t num_rows = chunk->num_rows();
     _local_memory_usage += memory_usage;
     _full_chunk_queue.emplace(std::move(chunk));
     _memory_manager->update_memory_usage(memory_usage, num_rows);
 
-    return Status::OK();
+    return;
```
Comment (silverbullet233) [inline be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp:35]: this return can be removed since it already reaches the end of the whole funciton

Comment (before-Sunrise) [reply be/src/exec/pipeline/exchange/local_exchange_source_operator.cpp]: forgot to delete...

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 3 / 10 (30.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|2|00.00%|[383, 386]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[142]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|1|00.00%|[650]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange.h|1|2|50.00%|[128]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.cpp|1|2|50.00%|[27]|
|:large_blue_circle:|src/exec/pipeline/exchange/local_exchange_source_operator.h|1|2|50.00%|[111]|

**Review by silverbullet233 — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]
