### PR TITLE
[BugFix] Fix version check failed while appling replication txn with compaction enabled

### LINKED ISSUE #62741: Replication transaction fail to publish with error "mismatched version"
### Steps to reproduce the behavior (Required)
1. start replication job to migrate data to a shared-data cluster with version 3.3.8 onwards
2. enable compaction on the target cluster
3. keep replicating data continuesly

### Expected behavior (Required)

The replication transaction can process successfully.

### Real behavior (Required)
The replication transaction failed to publish with error message:

```W20250828 16:58:31.536241 140162112423680 txn_log_applier.cpp:333] Fail to apply replication log, mismatched version, snapshot version: 1654512, data version: 1654510, old version: 1654510, new version: 1654513```

### StarRocks version (Required)
 - 3.3.13

### PR DESCRIPTION
**Pull request by wxl24life**
## Why I'm doing:

In the current shared-nothing to shared-data cluster migration process, we've added support for enabling compaction on the target cluster.

However, a problem arises during this migration: when a compaction transaction happens concurrently with a replication transaction, the version check on the backend (BE) will fail when trying to publish the replication transaction. This failure causes the replication transaction to fail permanently.

## What I'm doing:

Fixes #62741

This fix addresses the issue by preventing replication transactions from being bundled with any other types of transactions. This ensures that replication transactions are processed separately, avoiding the version check conflicts that cause them to fail. By keeping them isolated, we guarantee that the replication process can complete successfully, even if other compaction transactions are occurring.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

File: be/src/storage/lake/txn_log_applier.cpp [hunk 1]
```diff
@@ -391,10 +391,10 @@ class PrimaryKeyTxnLogApplier : public TxnLogApplier {
                              << ", base version: " << txn_meta.visible_version() << ", new version: " << _new_version;
                 return Status::Corruption("mismatched snapshot version and new version");
             }
-        } else if (txn_meta.snapshot_version() - txn_meta.data_version() + txn_meta.visible_version() != _new_version) {
+        } else if (txn_meta.snapshot_version() - txn_meta.data_version() + _base_version != _new_version) {
```
Comment (smartlxh) [inline be/src/storage/lake/txn_log_applier.cpp:394]: `_base_version` is the same in a transactionStateBatch, either disable batch publish of replication transactionState or make a compatibility judgement so that batch publish still works.

Comment (wxl24life) [reply be/src/storage/lake/txn_log_applier.cpp:394]: have isolated replication transactionstate in FE while building batches of transactions.

Comment (smartlxh) [reply be/src/storage/lake/txn_log_applier.cpp:394]: May be we can add a `index` field to txnLogAppier so that we can judge the postition of replication transaction state in batch

**Review by xiangguangyxg — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 2]
```diff
@@ -947,6 +947,13 @@ public List<TransactionStateBatch> getReadyToPublishTxnListBatch() {
                         states = states.subList(0, Math.max(i, 1));
                         break;
                     }
+                    // Handle replication transaction singly
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java]:
```suggestion
                    // Handle replication transaction separately
```

**Review by kevincai — APPROVED** [review]

**Review by xiangguangyxg — APPROVED** [review]

**Comment by wxl24life** [comment]
backport branch-3.3 https://github.com/StarRocks/starrocks/pull/63226

**Comment by wxl24life** [comment]
backport branch-3.5 https://github.com/StarRocks/starrocks/pull/63227

**Comment by wxl24life** [comment]
backport branch-4.0 https://github.com/StarRocks/starrocks/pull/63228

**Comment by wxl24life** [comment]
backport branch-3.4 https://github.com/StarRocks/starrocks/pull/63229
