### PR TITLE
compatible with bitmap/hll/percentile append_value_multiple_times usage by using append_strings instead in default value column iterator.

### LINKED ISSUE #91: compatible with bitmap/hll/percentile append_value_multiple_times usage by using append_strings instead in default value column iterator.
As I mentioned in #9, if cast raw data directly as follows,
```
    _pool.emplace_back(*reinterpret_cast<T*>(slice->data));
```
will cause crash, as illustrated below
```SQL
create database alter_table_test_db_1630980262173;

use alter_table_test_db_1630980262173;

CREATE TABLE `aggregate_table_with_null` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` tinyint sum, `v2` smallint sum, `v3` int sum, `v4` bigint max, `v5` largeint max, `v6` float min, `v7` double min, `v8` decimal(27,9) sum ) ENGINE=OLAP AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```

```bash
$ curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/doris_daily_build/dorisdb-test/lib/../common/data/basic_types_data -XPUT -H label:stream_load_aggregate_table_with_null_1630980262 -H column_separator:	 http://172.26.92.141:8034/api/alter_table_test_db_1630980262173/aggregate_table_with_null/_stream_load
```

```SQL
select sum(cast(v1 as int)), sum(v2), sum(v3), max(v4), max(v5), min(v6), min(v7), sum(v8) from aggregate_table_with_null where k1 = '2020-06-23' and k2 <= '2020-06-23 18:11:00';

ALTER TABLE aggregate_table_with_null ADD COLUMN add_key BITMAP BITMAP_UNION AFTER v8;
```

```bash
$ curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/doris_daily_build/dorisdb-test/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1630980262326 -H column_separator:	 http://172.26.92.141:8034/api/alter_table_test_db_1630980262173/aggregate_table_with_null/_stream_load
```

```SQL
SHOW COLUMNS FROM aggregate_table_with_null
select sum(cast(v1 as int)), sum(v2), sum(v3), max(v4), max(v5), min(v6), min(v7), sum(v8) from aggregate_table_with_null where k1 = '2020-06-23' and k2 <= '2020-06-23 18:11:00';
```

```bash
$ curl --location-trusted -u root: -T /home/disk1/jenkins/workspace/doris_daily_build/dorisdb-test/lib/../case/system_case/test_ddl/test_alter_table/basic_types_data_add_key_bitmap -XPUT -H label:stream_load_1630980290588 -H columns:k1,k2,k3,k4,k5,v1,v2,v3,v4,v5,v6,v7,v8,add_key=to_bitmap(v1) -H column_separator:	 http://172.26.92.141:8034/api/alter_table_test_db_1630980262173/aggregate_table_with_null/_stream_load
```

```SQL
select count(distinct add_key) from aggregate_table_with_null;
```

```txt
crash:
*** Aborted at 1630980290 (unix time) try "date -d @1630980290" if you are using GNU date ***
PC: @          0x14e7794 std::_Rb_tree<>::_M_copy<>()
*** SIGSEGV (@0xffffffffffffff48) received by PID 154029 (TID 0x7fa598bbb700) from PID 18446744073709551432; stack trace: ***
    @          0x30ca922 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fa5be00b630 (unknown)
    @          0x14e7794 std::_Rb_tree<>::_M_copy<>()
    @          0x14f3886 starrocks::vectorized::ObjectColumn<>::append_value_multiple_times()
    @          0x14da184 starrocks::vectorized::NullableColumn::append_value_multiple_times()
    @          0x2ae0a6d starrocks::segment_v2::DefaultValueColumnIterator::next_batch()
    @          0x2a2bfa9 starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x2a302d1 starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x1e06f07 starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x1bb0cab starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1bfe695 starrocks::vectorized::UnionIterator::do_get_next()
    @          0x1bb0cab starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1c3205d starrocks::vectorized::AggregateIterator::do_get_next()
    @          0x1bb0cab starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x1bf1c0a starrocks::vectorized::Reader::do_get_next()
    @          0x2651fe4 starrocks::vectorized::OlapScanner::get_chunk()
    @          0x249352c starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x1e34077 starrocks::PriorityThreadPool::work_thread()
    @          0x307aa77 thread_proxy
    @     0x7fa5be003ea5 start_thread
    @     0x7fa5bc36e8dd __clone
```

this can be compatible with bitmap/hll/percentile append_value_multiple_times usage by using append_strings instead in default value column iterator.

### PR DESCRIPTION
**Pull request by Linkerist**
ATT, see #91

### CODE REVIEW

**Comment by Linkerist** [comment]
@Seaven @HangyuanLiu

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

File: be/src/storage/rowset/segment_v2/column_reader.cpp [hunk 1]
```diff
@@ -1101,7 +1101,17 @@ Status DefaultValueColumnIterator::next_batch(size_t* n, vectorized::Column* dst
         _current_rowid += *n;
         DCHECK(ok) << "cannot append null to non-nullable column";
     } else {
-        dst->append_value_multiple_times(_mem_value, *n);
+        if (_type_info->type() == OLAP_FIELD_TYPE_OBJECT || _type_info->type() == OLAP_FIELD_TYPE_HLL ||
+            _type_info->type() == OLAP_FIELD_TYPE_PERCENTILE) {
+            std::vector<Slice> slices;
+            slices.reserve(*n);
+            for (size_t i = 0; i < *n; i++) {
+                slices.emplace_back(*reinterpret_cast<const Slice*>(_mem_value));
```
Comment (imay) [inline be/src/storage/rowset/segment_v2/column_reader.cpp:1109]: I have a question. Why not deserialize it as _mem_value before and call 'append_value_multiple_times' here.

Comment (Linkerist) [reply be/src/storage/rowset/segment_v2/column_reader.cpp:1109]: append_strings and append_value_multiple_times on the same level, can instead it comprehensibly.
https://github.com/StarRocks/starrocks/blob/2c57789c16e0e3be00e69527969ba3eef8b8af70/be/src/column/object_column.cpp#L90-L111

this level can do not know about bitmap value implement according to least knowledge principle.

https://github.com/StarRocks/starrocks/blob/2c57789c16e0e3be00e69527969ba3eef8b8af70/be/src/storage/rowset/segment_v2/column_reader.cpp#L1051-L1058

https://github.com/StarRocks/starrocks/blob/5fa55b8199f3b50fbb06ad686f979ec9d87da37d/be/src/util/bitmap_value.h#L991

**Review by imay — APPROVED** [review]
