### PR TITLE
BugFix: stack overflow in copy_file

### LINKED ISSUE #4279: Stack overflow will be happen in some scenarios
### Steps to reproduce the behavior (Required)

```
Status copy_file(const string& src, const string& dest) {
    int src_fd = -1;
    int dest_fd = -1;
    char buf[1024 * 1024];  （we should not alloc large memory in stack, it may be overflow in same machine,)
    Status res = Status::OK();
    ...
```

ulimit -s 

stack size is 1MB

### Real behavior (Required)

crash or generate invalid segment, we should test it in test cluster

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4279

## Problem Summary(Required) ：

The stack memory limit set by the operating system can be changed using `ulimit -s` and allocate memoy greater or equal to the stack memory limit will cause be crash.

If  stack memory limit is no more than 1MB, be will crash because try to alloc 1MB stack memory in function `copy_files`.

We should not alloc large memory in stack, alloc memory from heap to solve this problem.

This code is duplicated with function `copy_file` in  utils/file_utils.cpp, merge the two copy_file function in utils/file_utils.cpp and storage/utils.cpp

### CODE REVIEW

File: be/src/storage/utils.cpp [hunk 1]
```diff
@@ -119,7 +119,7 @@ Status move_to_trash(const std::filesystem::path& file_path) {
 Status copy_file(const string& src, const string& dest) {
```
Comment (chaoyli) [inline be/src/storage/utils.cpp:119]: You can merge the two copy_file function in utils/file_utils.cpp and storage/utils.cpp

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: be/src/storage/utils.cpp (hunk 1 above)
Comment (sevev) [reply be/src/storage/utils.cpp]: done, change in https://github.com/StarRocks/starrocks/pull/4347/commits/f4f3970c240d154c4675605850fa37ac4b5a6e5e

**Review by imay — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
