### PR TITLE
[BugFix] Fix fail to get splits from morsel queue introduces crash of be

### LINKED ISSUE #62529: BE crash in shared-data mode cluster while `enable_lake_tablet_internal_parallel` is enabled
### Real behavior (Required)
```sh
*** Aborted at 1756294857 (unix time) try "date -d @1756294857" if you are using GNU date ***
PC: @     0x7f575be36387 __GI_raise
*** SIGABRT (@0x7) received by PID 7 (TID 0x7f55811a7700) from PID 7; stack trace: ***
    @     0x7f575d20620b __pthread_once_slow
    @          0x7f76540 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x7f575d20f630 (/usr/lib64/libpthread-2.17.so+0xf62f)
    @     0x7f575be36387 __GI_raise
    @     0x7f575be37a78 __GI_abort
    @          0x34366bb __gnu_cxx::__verbose_terminate_handler() [clone .cold]
    @          0xcc15746 __cxxabiv1::__terminate(void (*)())
    @          0xcc157b1 std::terminate()
    @          0xcc15904 __cxa_throw
    @          0x2f58540 starrocks::internal_statusor::ThrowBadStatusOrAccess(starrocks::Status)
    @          0x65743ca starrocks::lake::TabletReader::open(starrocks::TabletReaderParams const&)
    @          0x70f5cf0 starrocks::connector::LakeDataSource::init_tablet_reader(starrocks::RuntimeState*)
    @          0x70f64be starrocks::connector::LakeDataSource::open(starrocks::RuntimeState*)
    @          0x45bf044 starrocks::pipeline::ConnectorChunkSource::_open_data_source(starrocks::RuntimeState*, bool*)
    @          0x45bf7b9 starrocks::pipeline::ConnectorChunkSource::_read_chunk(starrocks::RuntimeState*, std::shared_ptr<starrocks::Chunk>*)
    @          0x48da0e8 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking(starrocks::RuntimeState*, unsigned long, starrocks::workgroup::WorkGroup const*)
    @          0x45ae7ed auto starrocks::pipeline::ScanOperator::_trigger_next_scan(starrocks::RuntimeState*, int)::{lambda(auto:1&)#1}::operator()<starrocks::workgroup::YieldContext>(starrocks::workgroup::YieldContext&) const [clone .constprop.0]
    @          0x46a9bbb starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x3ac9a53 starrocks::ThreadPool::dispatch_thread()
    @          0x3ac10d6 starrocks::Thread::supervise_thread(void*)
    @     0x7f575d207ea5 start_thread
    @     0x7f575befe96d __clone
```

### StarRocks version (Required)
 - 3.3.x

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

Fixes #62529

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

---

> [!NOTE]
> Adds error handling around `MorselQueue::try_get` in scan distribution and lake splitting, returning statuses and falling back to non-split to avoid crashes.
> 
> - **Execution Pipeline**:
>   - `be/src/exec/scan_node.cpp`: Change `uniform_distribute_morsels` to return `StatusOr<std::map<int, pipeline::MorselQueuePtr>>`; propagate failure from `morsel_queue->try_get()` and update caller with `ASSIGN_OR_RETURN`.
> - **Lake Storage**:
>   - `be/src/storage/lake/tablet_reader.cpp`: Safely handle `split_morsel_queue->try_get()` failures by logging, clearing `_split_tasks`, disabling `_need_split`, and `return init_collector(read_params)` to fallback to non-split mode.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 8dee91ebefd5ca7b35c5963b1984b6bd7b2a9e7d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: be/src/storage/lake/tablet_reader.cpp [hunk 1]
```diff
@@ -170,7 +170,18 @@ Status TabletReader::open(const TabletReaderParams& read_params) {
         split_morsel_queue->set_tablet_schema(_tablet_schema);
 
         while (true) {
-            auto split = split_morsel_queue->try_get().value();
+            auto split_status_or = split_morsel_queue->try_get();
```
Comment (kevincai) [inline be/src/storage/lake/tablet_reader.cpp:173]: need to fix the following lines in scan_node.cpp as well

```
        auto maybe_morsel = morsel_queue->try_get();
        DCHECK(maybe_morsel.ok());
```

DCHECK doesn't help in RELEASE build. will crash here anyway.

File: be/src/exec/scan_node.cpp [hunk 2]
```diff
@@ -96,15 +96,17 @@ Status ScanNode::prepare(RuntimeState* state) {
...
+    std::map<int, pipeline::MorselQueuePtr> queue_per_driver;
     std::map<int, pipeline::Morsels> morsels_per_driver;
     int driver_seq = 0;
     while (!morsel_queue->empty()) {
-        auto maybe_morsel = morsel_queue->try_get();
-        DCHECK(maybe_morsel.ok());
-        morsels_per_driver[driver_seq].push_back(std::move(maybe_morsel.value()));
+        auto maybe_morsel_status_or = morsel_queue->try_get();
+        if (UNLIKELY(!maybe_morsel_status_or.ok())) {
+            return queue_per_driver;
```
Comment (kevincai) [inline be/src/exec/scan_node.cpp]: I think the correct behavior, is to return a `StatusOr<std::map...>`, and the caller shall handle the non-OK status.

Current fix will silence the error and return to the caller incorrect result without even notice.

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/exec/scan_node.cpp (hunk 2 above)
Comment (wxl24life) [reply be/src/exec/scan_node.cpp]: done

**Review by kevincai — APPROVED** [review]

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by smartlxh — APPROVED** [review]
