### PR TITLE
[BugFix] Raise exception if image download fails

### LINKED ISSUE #7754: [BUG] Add new fe node failed: Can not find the key:1, fail to get journal cursor. will exit
### Steps to reproduce the behavior (Required)
1. Set a low jvm heap size to master node.
2. Add a new fe node, and start the node with `--helper master_node`

### Expected behavior (Required)
Add new fe node successfully.

### Real behavior (Required)
Add fe node failed.
```text
2022-06-24 14:46:42,744 WARN (main|1) [Storage.reload():118] image.4307152.part is not a validate meta file, ignore it
2022-06-24 14:46:42,744 INFO (main|1) [GlobalStateMgr.loadImage():1104] image does not exist: /home/disk1/sr/stability_master_01/fe/meta/image/image.0
2022-06-24 14:47:47,247 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():212] insufficient exception, refresh and setup again
com.sleepycat.je.rep.InsufficientLogException: (JE 7.3.7) 172.26.195.72_9012_1654089311673(-1):/home/disk1/sr/stability_master_01/fe/meta/bdb INSUFFICIENT_LOG: Log files at this node are obsolete. Environment is invalid and must be closed.
        at com.sleepycat.je.rep.impl.node.RepNode.findRestoreSuppliers(RepNode.java:1629) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.queryGroupForMembership(RepNode.java:1468) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.findMaster(RepNode.java:1306) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.startup(RepNode.java:897) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.joinGroup(RepNode.java:2157) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.joinGroup(RepImpl.java:610) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.joinGroup(ReplicatedEnvironment.java:560) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:621) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:179) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:271) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:890) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:845) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:109) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:64) [starrocks-fe.jar:?]
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():427] start to close log databases
2022-06-24 14:54:54,665 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():436] close log databases end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():439] start to close epoch database
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():448] close epoch database end
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():450] start to close replicated environment
2022-06-24 14:54:54,666 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.close():460] close replicated environment end
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():188] add helper[172.26.195.71:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,068 INFO (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [BDBEnvironment.setup():195] add self[172.26.195.72:9012] as ReplicationGroupAdmin
2022-06-24 14:54:55,082 WARN (UNKNOWN 172.26.195.72_9012_1654089311673(-1)|1) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: UNKNOWN
2022-06-24 14:54:55,113 WARN (RepNode 172.26.195.72_9012_1654089311673(-1)|77) [GlobalStateMgr.notifyNewFETypeTransfer():1590] notify new FE type transfer: FOLLOWER
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from INIT to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1694] finished to transfer FE type to UNKNOWN
2022-06-24 14:54:55,144 INFO (stateListener|90) [GlobalStateMgr$5.runOneCycle():1613] begin to transfer FE type from UNKNOWN to FOLLOWER
2022-06-24 14:54:55,148 INFO (replayer|91) [GlobalStateMgr.replayJournal():1711] replayed journal id is 0, replay to journal id is 4403970
2022-06-24 14:54:55,150 ERROR (replayer|91) [BDBJournalCursor.<init>():84] Can not find the key:1, fail to get journal cursor. will exit.

```

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7754

## Problem Summary(Required) ：

Fix these 2 cases.
1. No exception will throw on loading an empty image file.
2. No exception will throw when failing to download an image from the helper. For example, if the image dir is readable to the FE process but the image file is not.

Can't find a way to add unittest, just manually test the above cases.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -1100,7 +1100,7 @@ public void loadImage(String imageDir) throws IOException, DdlException {
         DataInputStream dis = new DataInputStream(new BufferedInputStream(new FileInputStream(curFile)));
 
         long checksum = 0;
-        long remoteChecksum = 0;
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1103]: When does an empty file occur

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1103]: We did not check validation after downloading image. If in some way, the image file is empty, the image will be download successfully, loaded into memory successfully. This is not a real case, but could be real.

**Review by gengjun-git — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.3 branch-2.2 branch-2.1 branch-2.0
