### PR TITLE
[BugFix] Unable to set storage_cooldown_time to maximum when creating MaterializedView.

### LINKED ISSUE #52082: Unable to set storage_cooldown_time to maximum when creating MaterializedView.
### Steps to reproduce the behavior (Required)
1. set property
```
ADMIN SET FRONTEND CONFIG ("tablet_sched_storage_cooldown_second" = "2592000");
``` 
2. CREATE TABLE 
```
CREATE TABLE table_range1 
(
    k1 DATE,
    k2 INT,
    k3 SMALLINT,
    v1 VARCHAR(2048),
    v2 DATETIME DEFAULT "2014-02-04 15:36:00"
)
ENGINE = olap
DUPLICATE KEY(k1, k2, k3)
PARTITION BY RANGE (k1)
(
    PARTITION p1 VALUES LESS THAN ("2014-01-01"),
    PARTITION p2 VALUES LESS THAN ("2014-06-01"),
    PARTITION p3 VALUES LESS THAN ("2014-12-01")
)
DISTRIBUTED BY HASH(k2)
PROPERTIES(
    "storage_medium" = "SSD",
    "dynamic_partition.time_unit" = "DAY",
    "dynamic_partition.start" = "-3",
    "dynamic_partition.end" = "3",
    "dynamic_partition.prefix" = "p",
    "storage_medium" = "SSD",
    "storage_cooldown_ttl" = "10 days"
);
```
3. create MATERIALIZED view
```
CREATE MATERIALIZED VIEW mv12
PARTITION BY (k1)
DISTRIBUTED BY HASH(k2)
REFRESH ASYNC START('2023-07-01 10:00:00') EVERY (interval 1 day)
PROPERTIES ( "auto_refresh_partitions_limit" = "3", "replicated_storage" = "true", "replication_num" = "1", "storage_medium" = "SSD","storage_cooldown_time" = "9999-12-31 23:59:59" ) 
AS select k1,k2,sum(k3) from table_range1 group by k1,k2;
```
4. show partitions
```
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
| PartitionId | PartitionName | VisibleVersion | VisibleVersionTime  | VisibleVersionHash | State  | PartitionKey | Range                                                                      | DistributionKey | Buckets | ReplicationNum | StorageMedium | CooldownTime        | LastConsistencyCheckTime | DataSize | IsInMemory | RowCount | DataVersion | VersionEpoch       | VersionTxnType |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
| 2362520     | p1            | 1              | 2024-10-18 14:16:41 | 0                  | NORMAL | k1           | [types: [DATE]; keys: [0000-01-01]; ..types: [DATE]; keys: [2014-01-01]; ) | k2              | 6       | 1              | SSD           | 2024-11-17 14:16:41 | NULL                     | 0B       | false      | 0        | 1           | 317499168866172928 | TXN_NORMAL     |
| 2362533     | p2            | 1              | 2024-10-18 14:16:41 | 0                  | NORMAL | k1           | [types: [DATE]; keys: [2014-01-01]; ..types: [DATE]; keys: [2014-06-01]; ) | k2              | 6       | 1              | SSD           | 2024-11-17 14:16:41 | NULL                     | 0B       | false      | 0        | 1           | 317499168868270080 | TXN_NORMAL     |
| 2362546     | p3            | 1              | 2024-10-18 14:16:41 | 0                  | NORMAL | k1           | [types: [DATE]; keys: [2014-06-01]; ..types: [DATE]; keys: [2014-12-01]; ) | k2              | 6       | 1              | SSD           | 2024-11-17 14:16:41 | NULL                     | 0B       | false      | 0        | 1           | 317499168868270081 | TXN_NORMAL     |
+-------------+---------------+----------------+---------------------+--------------------+--------+--------------+----------------------------------------------------------------------------+-----------------+---------+----------------+---------------+---------------------+--------------------------+----------+------------+----------+-------------+--------------------+----------------+
```

### Expected behavior (Required)
CooldownTime: 9999-12-31 23:59:59
### Real behavior (Required)
CooldownTime: 2024-11-17 14:16:41
### StarRocks version (Required)
 3.1/3.2/3.3

### PR DESCRIPTION
**Pull request by zhangheihei**
## What I'm doing:

Fixes #52082

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java [hunk 1]
```diff
@@ -1456,8 +1455,7 @@ public static Map<String, String> getPartitionProperties(MaterializedView materi
         partitionProperties.put("storage_medium", materializedView.getStorageMedium());
         String storageCooldownTime =
                 materializedView.getTableProperty().getProperties().get("storage_cooldown_time");
-        if (storageCooldownTime != null
-                && !storageCooldownTime.equals(String.valueOf(DataProperty.MAX_COOLDOWN_TIME_MS))) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:1460]: `MAX_COOLDOWN_TIME_MS`(9999-12-31 23:59:59) is an invalid cool down time, why needs to update it?

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:1460]: Seems fine. I found `OlapTable` does't check whether storage_cooldown_time property is MAX_COOLDOWN_TIME_MS or not either.

```
    public static DataProperty analyzeDataProperty(Map<String, String> properties,
                                                   DataProperty inferredDataProperty,
                                                   boolean isDefault)
```

**Review by LiShuMing — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
