### PR TITLE
Fix bdb RollbackException bug

### LINKED ISSUE #4977: Fe start failed with RollbackException: must rollback xxx total commits(xxx of which were durable) to the earliest point
### Steps to reproduce the behavior (Required)
Actually it is the transferring master that causes the result in the production environment.
But the cases that transfer master and remains log that not synchronized to other nodes is not easy to reproduce. So I just manually simulated a scenario with the same result. 

1. build a cluster with 3 fe(fe1, fe2, fe3).
2. cp fe1 and fe2 's meta dir to a new dir `meta.r` when fe1 and fe2 is running.
3. wait for 2 minutes.
4. stop fe1, fe2, fe3.
5. start fe1, fe2 with meta.r
6. after fe1 and fe2 started successfully, start fe3.

### Expected behavior (Required)
fe3 should be started successfully.

### Real behavior (Required)
```java
2021-09-26 17:13:04,734 ERROR (replayer|80) [BDBEnvironment.getDatabaseNames():346] bdb environment failure exception.
com.sleepycat.je.rep.RollbackException: (JE 7.3.7) Environment must be closed, caused by: com.sleepycat.je.rep.RollbackException: Environment invalid because
of previous exception: (JE 7.3.7) 172.26.92.154_29917_1632647567330(523):/home/disk1/gengjun/fe/meta/bdb Node 172.26.92.154_29917_1632647567330(523):/home/dis
k1/gengjun/fe/meta/bdb must rollback 1 total commits(1 of which were durable) to the earliest point indicated by transaction id=-1235545 time=2021-09-26 17:13
:00.145 vlsn=2,267,732 lsn=0x418/0x16d durable=false in order to rejoin the replication group. All existing ReplicatedEnvironment handles must be closed and r
einstantiated.  Log files were truncated to file 0x1047, offset 0x481, vlsn 2,267,730 HARD_RECOVERY: Rolled back past transaction commit or abort. Must run re
covery by re-opening Environment handles Environment is invalid and must be closed. Originally thrown by HA thread: REPLICA 172.26.92.154_29917_1632647567330(
523) Originally thrown by HA thread: REPLICA 172.26.92.154_29917_1632647567330(523) Environment invalid because of previous exception: (JE 7.3.7) 172.26.92.15
4_29917_1632647567330(523):/home/disk1/gengjun/fe/meta/bdb Node 172.26.92.154_29917_1632647567330(523):/home/disk1/gengjun/fe/meta/bdb must rollback 1 total c
ommits(1 of which were durable) to the earliest point indicated by transaction id=-1235545 time=2021-09-26 17:13:00.145 vlsn=2,267,732 lsn=0x418/0x16d durable
=false in order to rejoin the replication group. All existing ReplicatedEnvironment handles must be closed and reinstantiated.  Log files were truncated to fi
le 0x1047, offset 0x481, vlsn 2,267,730 HARD_RECOVERY: Rolled back past transaction commit or abort. Must run recovery by re-opening Environment handles Envir
onment is invalid and must be closed. Originally thrown by HA thread: REPLICA 172.26.92.154_29917_1632647567330(523) Originally thrown by HA thread: REPLICA 1
72.26.92.154_29917_1632647567330(523)
        at com.sleepycat.je.rep.RollbackException.wrapSelf(RollbackException.java:146) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.RollbackException.wrapSelf(RollbackException.java:62) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1775) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.checkOpen(Environment.java:2473) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.getDatabaseNames(Environment.java:2245) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.getDatabaseNames(BDBEnvironment.java:339) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:211) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.getMaxJournalId(EditLog.java:99) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.getMaxJournalId(Catalog.java:5018) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2427) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2232) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
Caused by: com.sleepycat.je.rep.RollbackException: Environment invalid because of previous exception: (JE 7.3.7) 172.26.92.154_29917_1632647567330(523):/home/disk1/gengjun/fe/meta/bdb Node 172.26.92.154_29917_1632647567330(523):/home/disk1/gengjun/fe/meta/bdb must rollback 1 total commits(1 of which were durable) to the earliest point indicated by transaction id=-1235545 time=2021-09-26 17:13:00.145 vlsn=2,267,732 lsn=0x418/0x16d durable=false in order to rejoin the replication group. All existing ReplicatedEnvironment handles must be closed and reinstantiated.  Log files were truncated to file 0x1047, offset 0x481, vlsn 2,267,730 HARD_RECOVERY: Rolled back past transaction commit or abort. Must run recovery by re-opening Environment handles Environment is invalid and must be closed. Originally thrown by HA thread: REPLICA 172.26.92.154_29917_1632647567330(523) Originally thrown by HA thread: REPLICA 172.26.92.154_29917_1632647567330(523)
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.setupHardRecovery(ReplicaFeederSyncup.java:680) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.verifyRollback(ReplicaFeederSyncup.java:372) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.stream.ReplicaFeederSyncup.execute(ReplicaFeederSyncup.java:157) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.Replica.initReplicaLoop(Replica.java:711) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoopInternal(Replica.java:474) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.Replica.runReplicaLoop(Replica.java:409) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.node.RepNode.run(RepNode.java:1873) ~[je-7.3.7.jar:7.3.7]
```

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4977

## Problem Summary(Required) ：

In bdb, after transferring the master, there may be logs in the old master that have not been synchronized to other nodes, and these logs need to be cleaned up. After cleaning these logs, the bdb environment will throw a RollbackException, and the environment should be rebuilt. So we should catch the RollbackException, and rebuild the bdb environment.

The current handling of InsufficientLogException is somewhat problematic; we should rebuild the bdb environment after synchronizing data from other nodes.

Since we handle the InsufficientLogException in the getDatabaseNames() function, there is no need to address the exception in the open() function, so remove the extra code.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java [hunk 1]
```diff
@@ -83,16 +84,28 @@
     private List<CloseSafeDatabase> openedDatabases;
 
     // mark whether environment is closing, if true, all calling to environment will fail
-    private boolean closing = false;
-
-    public BDBEnvironment() {
+    private volatile boolean closing = false;
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:87]: Please add more concise commit message about the problem and solution.

**Review by chaoyli — CHANGES_REQUESTED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 20 / 44 (45.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|8|30|26.67%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|12|14|85.71%|

**Review by chaoyli — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java [hunk 2]
```diff
@@ -196,15 +209,14 @@ public void setup(File envHome, String selfNodeName, String selfNodeHostPort,
...
-                restore.execute(insufficientLogEx, config);
+                LOG.warn("insufficient exception, refresh and setup again", insufficientLogEx);
+                refreshLog(insufficientLogEx);
+                close();
+            } catch (RollbackException exception) {
+                LOG.warn("rollback exception, setup again", exception);
+                close();
             } catch (DatabaseException e) {
+                LOG.warn("database exception", e);
                 if (i < RETRY_TIME - 1) {
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:220]: why remove this log?

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java [hunk 3]
```diff
@@ -394,7 +424,7 @@ public boolean close() {
                 try {
                     db.close();
                 } catch (DatabaseException exception) {
-                    LOG.error("Error closing db {}", db.getDb().getDatabaseName(), exception);
+                    LOG.error("Error closing db", exception);
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:427]: Why remove the db name when logging the exception?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:427]: +1

**Comment by chaoyli** [comment]
I had not found the issue have anything with the issue and the commit message.
The issue describes the problem about copy the meta from a running FE.
The commit message describes a transferring problem. It makes me confused.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java (hunk 3 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:427]: in some cases, getDatabaseName() will throws exception.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java [hunk 4]
```diff
@@ -265,67 +262,41 @@ public void close() {
...
-                    // But it is ok.
-                    System.exit(-1);
-                }
-                bdbEnvironment.setup(new File(environmentPath), selfNodeName, selfNodeHostPort,
-                        helperNode.first + ":" + helperNode.second, Catalog.getCurrentCatalog().isElectable());
-            }
+        List<Long> dbNames = bdbEnvironment.getDatabaseNames();
+        if (dbNames == null) {
+            LOG.error("fail to get dbNames while open bdbje journal. will exit");
+            System.exit(-1);
```
[the remark this answers is not in the document]
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:281]: That comment is for the case that close() is failed. But those code is removed, cause it is useless now, as I said in the third paragraph of the pr message.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java [hunk 5]
```diff
@@ -347,7 +370,14 @@ public List<Long> getDatabaseNames() {
                 names = replicatedEnvironment.getDatabaseNames();
                 break;
             } catch (InsufficientLogException e) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:372]: 1. What's the difference between InsufficientLogException and RollbackException?
2. Why does the pull request call setup() when encountering the InsufficientLogException?
3. Does it will throw InsufficientLogException and RollbackException if I remove some logs for only one FE?

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java (hunk 3 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:427]: The cases that bdb throws InsufficientLogException and RollbackException

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java (hunk 2 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:220]: I added this log, not removed.

**Comment by gengjun-git** [comment]
> I had not found the issue have anything with the commit message. The issue describes the problem about copy the meta from a running FE. The commit message describes a problem that results from transferring master. It makes me confused.

The cases that transfer master and remains log that not synchronized to other nodes is not easy to reproduce. So I just manually simulated a scenario with the same result in issue. But actually it is the transferring master that causes the result in the production environment.

**Comment by gengjun-git** [comment]
Glad to see so many comments.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java (hunk 5 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:372]: 1. InsufficientLogException and RollbackException are two unrelated exceptions.
2. I was in this PR by the way to fix the problem of processing InsufficientLogException. As I described in the 2 paragraphs of this pr message.
3. If the current FE has extra log, it will throws RollbackException. If the log is too far behind, it will throws InsufficientLogException.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 20 / 44 (45.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|8|30|26.67%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|12|14|85.71%|

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java (hunk 3 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java:426]: > 

How about only print out the id of the db? There should be some simpler and safer way to identify db. As an open source project that can be privatized deployed, I think our log on exception should be as detailed as possible because those logs are all we can get from the users.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBEnvironment.java]: Good, but we can only get the name through getDatabaseName() func. I have write a safe method to get the name in CloseSafeDatabase.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 20 / 47 (42.55%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/CloseSafeDatabase.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|8|30|26.67%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|12|14|85.71%|

**Review by padmejin — APPROVED** [review]
LGTM

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
