### PR TITLE
[BugFix] Clear bucketColumns if not all OlapScanNode use it 

### LINKED ISSUE #22462: COLOCATE JOIN bug
### Steps to reproduce the behavior (Required)
1.  
```sql
CREATE TABLE `t1`
(
    `store` string NULL,
    `matnr` string NULL,
    `amt` decimal128(27, 9) NULL
) ENGINE = OLAP UNIQUE KEY( `store`, `matnr`)
DISTRIBUTED BY HASH(`matnr`) BUCKETS 1
PROPERTIES (
    "enable_storage_cache" = "true",
    "storage_cache_ttl" = "2592000",
    "enable_async_write_back" = "false",
    "replication_num" = "1",
    "in_memory" = "false",
    "storage_format" = "DEFAULT",
    "enable_persistent_index" = "false",
    "compression" = "LZ4"
);

insert into t1 values ('s1', 'a', 35), ('s2', 'a', 35);

WITH tmp1 AS (SELECT * FROM t1),
     tmp2 as (SELECT store, matnr
            FROM t1
            GROUP BY store, matnr
            HAVING ( SUM(amt) >= 30))
  SELECT tmp1.*
  FROM tmp1
           JOIN  tmp2
                 ON (tmp1.store = tmp2.store AND tmp1.matnr = tmp2.matnr);
```

### Expected behavior (Required)
```
+-------+-------+--------------+
| store | matnr | amt          |
+-------+-------+--------------+
| s2    | a     | 35.000000000 |
| s1    | a     | 35.000000000 |
+-------+-------+--------------+
```

### Real behavior (Required)
```
+-------+-------+--------------+
| store | matnr | amt          |
+-------+-------+--------------+
+-------+-------+--------------+
```

### Other
Use the explain command to view the execution plan, two tables using a collocate join , If we change to using broadcast join by adding  [broadcast], can obtain the correct results. Other ways, If we SET disable_colocate_join = TRUE, can also obtain the correct result

image

### StarRocks version (Required)
2.5.4, 3.0-rc1

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #22462

## Problem Summary(Required) ：

Constraint: Either all OlapScanNodes use `bucketColumns` for local shuffle, or none of them do. 

When meeting the blocking aggregation executed on the single tablet, we only clear `bucketColumns` of the sub-fragment from this agg node, not the entire fragment, which causes only some of `OlapScanNode` uses `bucketColumns`

```
        //             HashJoin(Colocate)
        //      /                         \
        // OlapScanNode(NOT CLEAR)       BlockingAgg
        //                                |
        //                             OlapScanNode(CLEAR)
```

Therefore, I add a new conservative strategy during the finalizeFragment phase: we examine each fragment and clear the `bucketColumns` if only some of OlapScanNodes within the fragment use `bucketColumns`. 

BTW, add `LocalShuffleColumns` to OlapScanNode in the verbose explain.
```
| PLAN FRAGMENT 1(F00)                                                                                                          |
|                                                                                                                               |
|   Input Partition: RANDOM                                                                                                     |
|   OutPut Partition: UNPARTITIONED                                                                                             |
|   OutPut Exchange Id: 01                                                                                                      |
|                                                                                                                               |
|   0:OlapScanNode                                                                                                              |
|      table: customer, rollup: customer                                                                                        |
|      preAggregation: on                                                                                                       |
|      partitionsRatio=1/1, tabletsRatio=12/12                                                                                  |
|      tabletList=10804,10806,10808,10810,10812,10814,10816,10818,10820,10822 ...                                               |
|      actualRows=3000000, avgRowSize=84.88014                                                                                  |
|      LocalShuffleColumns:                                                                                                           |
|      - 1: c_custkey                                                                                                           |
|      cardinality: 3000000                                                                                                     |
+-------------------------------------------------------------------------------------------------------------------------------+
```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java [hunk 1]
```diff
@@ -71,6 +71,8 @@ public class FeConstants {
     public static int checkpoint_interval_second = 60; // 1 minutes
     // set to true to skip some step when running FE unit test
     public static boolean runningUnitTest = false;
+    // Set this flag to false to suppress showing local shuffle columns in verbose explain, when running FE unit tests.
+    public static boolean showLocalShuffleColumnsInExplain = true;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java:75]: Are session variables better?

File: fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java [hunk 2]
```diff
@@ -376,6 +385,7 @@ public void testCaseWhenWithoutCaseClause() throws Exception {
         };
         for (String[] tc : testCases) {
             String sql = tc[0];
+            System.out.println(sql);
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java:388]: remove it

File: fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java (hunk 1 above)
Comment (ZiheLiu) [reply fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java:75]: This is similar as `runningUnitTest`, just to avoid to modify too many test cases.

File: fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java (hunk 2 above)
Comment (ZiheLiu) [reply fe/fe-core/src/test/java/com/starrocks/analysis/SelectStmtWithCaseWhenTest.java]: Done.

File: fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/common/FeConstants.java:75]: can be always print it in `explain verbose/costs`?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 32 / 32 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/OlapScanNode.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/FeConstants.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/planner/PlanFragment.java|8|8|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3
