### PR TITLE
[Enhancement] Add cbo_materialized_view_rewrite_related_mvs_limit parameter to limit mv related mv number

### LINKED ISSUE #38881: Too many materialized views result in very slow SQL explain and SQL execution
### Steps to reproduce the behavior (Required)

First create 1000 mv(s):

```
$ cat create-mv1000.sh 
#!/bin/bash
array=$(seq 1 1000)
for i in ${array[@]}; do
  mysql -h 127.0.0.1 -P19030 -uroot -pxxx -e "CREATE MATERIALIZED view default_catalog.many_mv_test.mv$i PARTITION BY (lo_orderdate) DISTRIBUTED BY HASH(LO_ORDERDATE) REFRESH ASYNC EVERY(INTERVAL 30 DAY) PROPERTIES ( \"partition_ttl_number\" = \"1\", \"replication_num\" = \"1\") AS SELECT l.* FROM hive.hivessbtest.P_LINEORDER AS l inner join  hive.hivessbtest.part p on l.LO_PARTKEY = p.P_PARTKEY WHERE p.p_size = $i" 
done
```
execute create-mv1000.sh 

```
$ source create-mv1000.sh 
```

Wait for the MVs to be refreshed:
```
'root'@(none) Thu Jan 11 14:42:41 2024>select state, count(*) from default_catalog.information_schema.task_runs where create_time >= '2024-01-11 12:00:00' and `DATABASE` like '%many%' group by state;
+---------+----------+
| state   | count(*) |
+---------+----------+
| SUCCESS |      1000 |
+---------+----------+
1 row in set (0.33 sec)

```

view v821 defination:
```
'root'@(none) Thu Jan 11 14:06:02 2024>set new_planner_optimize_timeout=100000;
Query OK, 0 rows affected (0.00 sec)

'root'@(none) Thu Jan 11 14:06:37 2024>show create table default_catalog.hiveviewtestdb.v821\G
*************************** 1. row ***************************
                View: v821
         Create View: CREATE VIEW `v821` (`p_brand`, `LO_ORDERDATE`, `revenue_sum`) AS SELECT `hive`.`hivessbtest`.`p`.`p_brand`, `hive`.`hivessbtest`.`l`.`LO_ORDERDATE`, sum(`hive`.`hivessbtest`.`l`.`LO_REVENUE`) AS `revenue_sum`
FROM `hive`.`hivessbtest`.`P_LINEORDER` AS `l` LEFT OUTER JOIN `hive`.`hivessbtest`.`part` AS `p` ON `hive`.`hivessbtest`.`l`.`LO_PARTKEY` = `hive`.`hivessbtest`.`p`.`P_PARTKEY`
GROUP BY `hive`.`hivessbtest`.`p`.`p_brand`, `hive`.`hivessbtest`.`l`.`LO_ORDERDATE`;
character_set_client: utf8
collation_connection: utf8_general_ci
1 row in set (0.00 sec)

```

explain SQL is very slow:
```
'root'@(none) Thu Jan 11 14:08:57 2024>explain select    p_brand,    LO_ORDERDATE,    revenue_sum from    default_catalog.hiveviewtestdb.v821;
+-----------------------------------------------------------------------------------------------------+
| Explain String                                                                                      |
+-----------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                     |
|  OUTPUT EXPRS:23: p_brand | 18: lo_orderdate | 28: sum                                              |
|   PARTITION: UNPARTITIONED                                                                          |
|                                                                                                     |
|   RESULT SINK                                                                                       |
|                                                                                                     |
|   2:EXCHANGE                                                                                        |
|                                                                                                     |
| PLAN FRAGMENT 1                                                                                     |
|  OUTPUT EXPRS:                                                                                      |
|   PARTITION: RANDOM                                                                                 |
|                                                                                                     |
|   STREAM DATA SINK                                                                                  |
|     EXCHANGE ID: 02                                                                                 |
|     UNPARTITIONED                                                                                   |
|                                                                                                     |
|   1:Project                                                                                         |
|   |  <slot 18> : 3974: LO_ORDERDATE                                                                 |
|   |  <slot 23> : 3973: p_brand                                                                      |
|   |  <slot 28> : 3975: revenue_sum                                                                  |
|   |                                                                                                 |
|   0:OlapScanNode                                                                                    |
|      TABLE: mv8212                                                                                  |
|      PREAGGREGATION: ON                                                                             |
|      partitions=2406/2406                                                                           |
|      rollup: mv8212                                                                                 |
|      tabletRatio=24060/24060                                                                        |
|      tabletList=7515854,7515856,7515858,7515860,7515862,7515864,7515866,7515868,7515870,7515872 ... |
|      cardinality=2303931                                                                            |
|      avgRowSize=6.0                                                                                 |
|      MaterializedView: true                                                                         |
+-----------------------------------------------------------------------------------------------------+
31 rows in set (46.66 sec)

```
 
trace times mv:

```
'root'@(none) Thu Jan 11 14:09:56 2024>trace times mv select    p_brand,    LO_ORDERDATE,    revenue_sum from    default_catalog.hiveviewtestdb.v821;
|     0ms|-- Total[1] 46s973ms                                                                                                                                                                             |
|     0ms|    -- Analyzer[1] 2ms                                                                                                                                                                           |
|     3ms|    -- Transformer[1] 0                                                                                                                                                                          |
|     3ms|    -- Optimizer[1] 46s906ms                                                                                                                                                                     |
|     3ms|        -- preprocessMvs[979] 46s814ms                                                                                                                                                           |
| 46819ms|                            这里有很长的空格被我删了很多                                         -- RuleBaseOptimize[1] 10ms |
| 46830ms|                            这里有很长的空格被我删了很多                                         -- CostBaseOptimize[1] 78ms |
| 46909ms|                            这里有很长的空格被我删了很多                                         -- PhysicalRewrite[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                         -- PlanValidate[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                             -- InputDependenciesChecker[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                             -- TypeChecker[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                             -- CTEUniqueChecker[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                             -- ColumnReuseChecker[1] 0 |
| 46909ms|                            这里有很长的空格被我删了很多                                     -- ExecPlanBuild[1] 63ms |
| Tracer Cost: 2070us                                                                                                                                                                                      |
```

SQL execution is too slow:

```
'root'@(none) Thu Jan 11 14:36:59 2024>select    p_brand,    LO_ORDERDATE,    revenue_sum from    default_catalog.hiveviewtestdb.v821;
...
...
...
| MFGR#5425 |     19980318 |    14794872 |
| MFGR#5426 |     19980318 |    10766440 |
| MFGR#5428 |     19980318 |     2860272 |
| MFGR#5429 |     19980318 |    25364160 |
| MFGR#543  |     19980318 |    16178840 |
^C| MFGR#5431 |     19980318 |    37944028 |
| MFGR#5431 |     19980318 |    37944028 |
^C -- query aborted
+-----------+--------------+-------------+
2203395 rows in set (45.53 sec)
```

Even if I use a SQL which is not like the MV definition in the 1000 MVs, the SQL explain is still slow:

```
'root'@(none) Thu Jan 11 14:36:59 2024>explain  select    LO_SHIPMODE,    LO_ORDERDATE,    sum(LO_REVENUE) as revenue_sum  from    hive.hivessbtest.P_LINEORDER  group by    LO_SHIPMODE,    LO_ORDERDATE;
+-----------------------------------------------------------------------------------------------------+
| Explain String                                                                                      |
+-----------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                     |
|  OUTPUT EXPRS:16: lo_shipmode | 18: lo_orderdate | 19: sum                                          |
|   PARTITION: UNPARTITIONED                                                                          |
|                                                                                                     |
|   RESULT SINK                                                                                       |
|                                                                                                     |
|   2:EXCHANGE                                                                                        |
|                                                                                                     |
| PLAN FRAGMENT 1                                                                                     |
|  OUTPUT EXPRS:                                                                                      |
|   PARTITION: RANDOM                                                                                 |
|                                                                                                     |
|   STREAM DATA SINK                                                                                  |
|     EXCHANGE ID: 02                                                                                 |
|     UNPARTITIONED                                                                                   |
|                                                                                                     |
|   1:Project                                                                                         |
|   |  <slot 16> : 1546: LO_SHIPMODE                                                                  |
|   |  <slot 18> : 1547: LO_ORDERDATE                                                                 |
|   |  <slot 19> : 1548: revenue_sum                                                                  |
|   |                                                                                                 |
|   0:OlapScanNode                                                                                    |
|      TABLE: mv12                                                                                    |
|      PREAGGREGATION: ON                                                                             |
|      partitions=2406/2406                                                                           |
|      rollup: mv12                                                                                   |
|      tabletRatio=24060/24060                                                                        |
|      tabletList=7214094,7214096,7214098,7214100,7214102,7214104,7214106,7214108,7214110,7214112 ... |
|      cardinality=16842                                                                              |
|      avgRowSize=24.003563                                                                           |
|      MaterializedView: true                                                                         |
+-----------------------------------------------------------------------------------------------------+
31 rows in set (44.68 sec)

```

After setting enable_materialized_view_rewrite to false, explain and SQL execution is very fast.

```

'root'@(none) Thu Jan 11 14:33:15 2024>set enable_materialized_view_rewrite=false;
Query OK, 0 rows affected (0.00 sec)


'root'@(none) Thu Jan 11 14:33:26 2024>explain select    p_brand,    LO_ORDERDATE,    revenue_sum from    default_catalog.hiveviewtestdb.v821;
+--------------------------------------------------------------+
| Explain String                                               |
+--------------------------------------------------------------+
| PLAN FRAGMENT 0                                              |
|  OUTPUT EXPRS:23: p_brand | 18: lo_orderdate | 28: sum       |
|   PARTITION: UNPARTITIONED                                   |
|                                                              |
|   RESULT SINK                                                |
|                                                              |
|   8:EXCHANGE                                                 |
|                                                              |
| PLAN FRAGMENT 1                                              |
|  OUTPUT EXPRS:                                               |
|   PARTITION: HASH_PARTITIONED: 23: p_brand, 18: lo_orderdate |
|                                                              |
|   STREAM DATA SINK                                           |
|     EXCHANGE ID: 08                                          |
|     UNPARTITIONED                                            |
|                                                              |
|   7:AGGREGATE (merge finalize)                               |
|   |  output: sum(28: sum)                                    |
|   |  group by: 23: p_brand, 18: lo_orderdate                 |
|   |                                                          |
|   6:EXCHANGE                                                 |
|                                                              |
| PLAN FRAGMENT 2                                              |
|  OUTPUT EXPRS:                                               |
|   PARTITION: RANDOM                                          |
|                                                              |
|   STREAM DATA SINK                                           |
|     EXCHANGE ID: 06                                          |
|     HASH_PARTITIONED: 23: p_brand, 18: lo_orderdate          |
|                                                              |
|   5:AGGREGATE (update serialize)                             |
|   |  STREAMING                                               |
|   |  output: sum(12: lo_revenue)                             |
|   |  group by: 23: p_brand, 18: lo_orderdate                 |
|   |                                                          |
|   4:Project                                                  |
|   |  <slot 12> : 12: lo_revenue                              |
|   |  <slot 18> : 18: lo_orderdate                            |
|   |  <slot 23> : 23: p_brand                                 |
|   |                                                          |
|   3:HASH JOIN                                                |
|   |  join op: LEFT OUTER JOIN (BROADCAST)                    |
|   |  colocate: false, reason:                                |
|   |  equal join conjunct: 4: lo_partkey = 19: p_partkey      |
|   |                                                          |
|   |----2:EXCHANGE                                            |
|   |                                                          |
|   0:HdfsScanNode                                             |
|      TABLE: p_lineorder                                      |
|      partitions=2406/2406                                    |
|      cardinality=8358935                                     |
|      avgRowSize=6.0                                          |
|                                                              |
| PLAN FRAGMENT 3                                              |
|  OUTPUT EXPRS:                                               |
|   PARTITION: RANDOM                                          |
|                                                              |
|   STREAM DATA SINK                                           |
|     EXCHANGE ID: 02                                          |
|     UNPARTITIONED                                            |
|                                                              |
|   1:HdfsScanNode                                             |
|      TABLE: part                                             |
|      partitions=1/1                                          |
|      cardinality=1                                           |
|      avgRowSize=2.0                                          |
+--------------------------------------------------------------+
66 rows in set (0.02 sec)


'root'@(none) Thu Jan 11 14:34:15 2024>select    p_brand,    LO_ORDERDATE,    revenue_sum from    default_catalog.hiveviewtestdb.v821;
...
...
...
| MFGR#329  |     19950607 |     5097274 |
| MFGR#1411 |     19950607 |     2360390 |
| MFGR#1237 |     19950607 |     8927061 |
| MFGR#2337 |     19950125 |    28426406 |
| MFGR#5133 |     19951002 |     5192354 |
+-----------+--------------+-------------+
2203395 rows in set (1.12 sec)


```

### Expected behavior (Required)

Explain and SQL execution should be fast enough even if too many mv(s) are created. In my case, the last SQL is very different from the 1000 MVs but it is still affected. MVs which cannot be used to rewrite SQL should be pruned quickly during query execution plan phrase, which need MV definition index to accomplish this. I don't whether starrocks has this kind of MV metadata index or not.

The trace log mv output :

[trace_logs.log.gz](https://github.com/StarRocks/starrocks/files/13898542/trace_logs.log.gz)

### Real behavior (Required)
Explain and SQL execution are too slow if too many mv(s) are created.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

I complied branch-3.2(commit 8db6910) and replaced the whole fe/lib directory and restarted all FEs.

```
'root'@(none) Thu Jan 11 14:42:13 2024>select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.2.2-8db6910     |
+-------------------+
1 row in set (0.00 sec)

```

### PR DESCRIPTION
**Pull request by LiShuMing**
Why I'm doing:
- MvProprecssor may cost too much time if there are too many related mvs for a query.

What I'm doing:
```
    /**
     * To avoid MvRewriteProcessor cost too much optimizer time, reduce all related mvs to a limited size.
     * <h3>Why to Choose The Best Related MVs Strategy</h3>
     *
     * <p>Why still to choose limited related mvs from all active mvs?</p>
     *
     * <p>1. optimizer time cost. Even there is MVPlanCache to reduce mv optimizer plan time, but it still may cost
     * too much time for mv preprocessor, because mv optimizer plan costs too much time because of cold start when
     * MVPlanCache has no cache, or MVPlanCache has exceeded limited capacity which is 1000 by default.</p>
     *
     * <p>2. check mv's freshness for each mv will cost too much time if there are too many mvs.</p>
     *
     * <h3>How to Choose The Best Related MVs Strategy</h3>
     * <p>
     *     Choose the best related mvs from all active mvs as following order:
     *     1. find the max intersected table num between mv and query which means it's better for rewrite.
     *     2. find the latest fresh mv which means its freshness is better.
     * </p>
     *
     * <h3>More Information</h3>
     * <p>
     *  NOTE: there are still some limitations about this ordering algorithm:
     *  1. consider repeated tables in one mv later which one table can be used repeatedly in one mv.
     *  2. consider random factor so can cache and use more mvs.
     * </p>
     */
```
Fixes https://github.com/StarRocks/starrocks/issues/38881

```
Before:
    // MvPreProcessorWithSSBBench.testPartitionPredicate2: [measured 10 out of 11 rounds, threads: 1 (sequential)]
    // round: 2.93 [+- 0.10], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 51, GC.time: 1.21,
    // time.total: 33.49, time.warmup: 4.16, time.bench: 29.33


After:
    // MvPreProcessorWithSSBBench.testPartitionPredicate: [measured 10 out of 11 rounds, threads: 1 (sequential)]
    // round: 0.32 [+- 0.08], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], GC.calls: 4, GC.time: 0.05,
    // time.total: 4.40, time.warmup: 1.21, time.bench: 3.20



```

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 1]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+     * </p>
+     *
+     * <h3>More Information</h3>
+     * <p>
+     *  NOTE: there are still some limitations about this ordering algorithm:
+     *  1. consider repeated tables in one mv later which one table can be used repeatedly in one mv.
+     *  2. consider random factor so can cache and use more mvs.
+     * </p>
+     */
+    static class MVRelatedOrdering implements Comparator<MaterializedView> {
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:175]: make MaterializedViewWithOrder immutable
cache the results of getInteractedTablesNum,getBaseTablesNum, getBaseTablesNum use transient field

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 2]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+        private long getMVLastRefreshTime(MaterializedView mv) {
+            return mv.getLastRefreshTime();
+        }
+
+        @Override
+        public int compare(MaterializedView mv1, MaterializedView mv2) {
+            return Comparator.comparingLong(this::getInteractedTablesNum)
+                    .thenComparing(this::getBaseTablesNum)
+                    .thenComparing(this::getMVLastRefreshTime)
+                    .compare(mv1, mv2);
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:239]: compare(mv1, mv2) or compare(mv2, mv1), which is right?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 3]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+                    .map(t -> t.getName())
+                    .collect(Collectors.toSet());
+            this.queryScanOpNum = queryScanOpNum;
+            this.mvWithPlanContextCacheMap = mvPlanContextsMap;
+        }
+
+        /**
+         * Get mv and a query's interacted table num. Bigger is Better.
+         */
+        private long getInteractedTablesNum(MaterializedView mv) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:193]: intersected ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 4]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+                        if (Strings.isNullOrEmpty(baseTableName)) {
+                            return false;
+                        }
+                        return queryTableNames.contains(baseTableName);
+                    }).count();
+        }
+
+
+        /**
+         * Get mv's base tables' number and query scan op number's diff number. Bigger is Better.
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:207]: Does it make more sense to compare the intersected table number instead of NumBaseTable - NumScan ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 5]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+         */
+        private long getMVLastRefreshTime(MaterializedView mv) {
+            return mv.getLastRefreshTime();
+        }
+
+        @Override
+        public int compare(MaterializedView mv1, MaterializedView mv2) {
+            return Comparator.comparingLong(this::getInteractedTablesNum)
+                    .thenComparing(this::getBaseTablesNum)
+                    .thenComparing(this::getMVLastRefreshTime)
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:238]: Does it make more sense to compare the LastRefreshTime in reversed order ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 6]
```diff
@@ -256,99 +409,206 @@ private MaterializedView copyOnlyMaterializedView(MaterializedView mv) {
...
+        logMVPrepare(connectContext, "Choose {} valid mvs from {} after checking valid",
+                validMVs.size(), relatedMVs.size());
+
+        // 3. choose max config related mvs for mv rewrite to avoid too much optimize time
+        int maxRelatedMVsLimit = connectContext.getSessionVariable().getCboMaterializedViewRewriteRelatedMVsLimit();
+        if (maxRelatedMVsLimit < 1 && validMVs.size() <= maxRelatedMVsLimit) {
+            return validMVs;
+        }
+
+        Comparator<MaterializedView> ordering = new MVRelatedOrdering(queryTables, queryScanOpNum, mvWithPlanCacheMap);
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:557]: Relevance ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java (hunk 4 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: 1. intersected table numbers is better if it's larger.
2. but there are some cases that it's bad if we only considered instersected tables:
case1: If mv contains multi same tables
case2: If mv contains extra tables(with uk/fk constraints)

both in case1 and case2, we prefer a mv that has closest scan ops with query.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java (hunk 5 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: `LastRefreshTime ` is larger we think it's more possible to more refresh which can be rewritten?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 7]
```diff
@@ -100,27 +104,172 @@ public MvRewritePreprocessor(ConnectContext connectContext,
...
+            return mvPlanContext;
+        }
+    }
+
+    /**
+     * When {@link MvPlanContext} already existed, check the related mvs by using it
+     * in {@link #chooseBestRelatedMVs(Set, Set, OptExpression)}.
+     */
+    class MVWithPlanContextCache {
+        private final boolean isValidPlan;
```
[the remark this answers is not in the document]
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: I have not changed this just like  before. 


This is only to filter invalid mv plans before optimizing if it's in the cache to reduce optimizer time.

```
        // if mv is in plan cache(avoid building plan), check whether it's valid
        List<MvPlanContext> planContexts = CachingMvPlanContextBuilder.getInstance().getPlanContextFromCacheIfPresent(mv);
        if (planContexts != null && planContexts.stream().noneMatch(mvPlanContext -> mvPlanContext.isValidMvPlan())) {
            logMVPrepare(connectContext, mv, "MV has not a valid plan: {}", mv.getName());
            return false;
        }
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java [hunk 8]
```diff
@@ -256,99 +409,206 @@ private MaterializedView copyOnlyMaterializedView(MaterializedView mv) {
...
+            }
+        }
+        validMVs = validMVs.stream()
+                .filter(mv -> isMVValidToRewriteQuery(mv, queryTables, mvWithPlanCacheMap))
+                .collect(Collectors.toSet());
+        logMVPrepare(connectContext, "Choose {} valid mvs from {} after checking valid",
+                validMVs.size(), relatedMVs.size());
+
+        // 3. choose max config related mvs for mv rewrite to avoid too much optimize time
+        int maxRelatedMVsLimit = connectContext.getSessionVariable().getCboMaterializedViewRewriteRelatedMVsLimit();
```
[the remark this answers is not in the document]
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java:552]: I've added checks in `SetStmtAnalyzer` and tests.

But here I just kept it for protecting the codes.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java (hunk 1 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: As you suggests, I have added a class to cache the results like this:
```
    public static class MVCorrelation implements Comparable<MVCorrelation> {
        private final MaterializedView mv;
        private final long mvQueryIntersectedTablesNum;
        private final int mvQueryScanOpNumDiff;
        private final long mvRefreshTimestamp;

        public MVCorrelation(MaterializedView mv,
                             long mvQueryIntersectedTablesNum,
                             int mvQueryScanOpNumDiff,
                             long mvRefreshTimestamp) {
            this.mv = mv;
            this.mvQueryIntersectedTablesNum = mvQueryIntersectedTablesNum;
            this.mvQueryScanOpNumDiff = mvQueryScanOpNumDiff;
            this.mvRefreshTimestamp = mvRefreshTimestamp;
        }
}
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java (hunk 2 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/MvRewritePreprocessor.java]: Add more tests in `testChooseBestRelatedMVs3` and `testChooseBestRelatedMVs4`

**Review by satanson — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by evelynzhaojie** [comment]
@LiShuMing is this session variable visible to users, if yes, pls add it to doc https://github.com/StarRocks/starrocks/blob/main/docs/zh/reference/System_variable.md
