### PR TITLE
[BugFix] Fix bugs of vector index

### LINKED ISSUE #55009: Should not use vector index when order by function different from metric_type
### Steps to reproduce the behavior (Required)
```sql
ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "true");

CREATE TABLE t6 (
    id bigint(20) NOT NULL COMMENT "",
    vector ARRAY<FLOAT> NOT NULL COMMENT "",
    INDEX index_vector (vector) USING VECTOR (
        "index_type" = "hnsw", 
        "dim"="5", 
        "metric_type" = "cosine_similarity", 
        "is_vector_normed" = "false", 
        "M" = "16", 
        "efconstruction" = "40"
    )
) ENGINE=OLAP
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);

insert into t6 values 
    (1, [10,12,13,14,15]),
    (2, [1,2,3,4,5]),
    (3, [0.1,0.2,0.3,0.4,0.5]);


explain select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;

select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;
```

### Expected behavior (Required)
```
> explain select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;

|   0:OlapScanNode                                                                                |
|      TABLE: t6                                                                                  |
|      PREAGGREGATION: ON                                                                         |
|      VECTORINDEX: FALSE                                                                            |

> select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+
| id | vector                | approx_l2_distance([0.1, 0.2, 0.3, 0.4, 0.5], vector) | l2_distance([0.1, 0.2, 0.3, 0.4, 0.5], vector) | cosine_similarity([0.1, 0.2, 0.3, 0.4, 0.5], vector) |
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+
| 1  | [10,12,13,14,15]      | 0.9525018                                             | 793.75                                         | 0.9525017                                            |
| 2  | [1,2,3,4,5]           | 1.0                                                   |  44.55                                         | 1.0                                                  |
| 1  | [0.1,0.2,0.3,0.4,0.5] | 1.0                                                   |   0.0                                          | 0.9999999                                            |
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+

+----+-----------------------+--------------------------------------
```

### Real behavior (Required)

```
> explain select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;

|   0:OlapScanNode                                                                                |
|      TABLE: t6                                                                                  |
|      PREAGGREGATION: ON                                                                         |
|      VECTORINDEX: ON                                                                            |

> select id, vector, approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector), l2_distance([0.1,0.2,0.3,0.4,0.5], vector), cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_l2_distance([0.1,0.2,0.3,0.4,0.5], vector)  limit 1000;
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+
| id | vector                | approx_l2_distance([0.1, 0.2, 0.3, 0.4, 0.5], vector) | l2_distance([0.1, 0.2, 0.3, 0.4, 0.5], vector) | cosine_similarity([0.1, 0.2, 0.3, 0.4, 0.5], vector) |
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+
| 1  | [10,12,13,14,15]      | 0.9525018                                             | 793.75                                         | 0.9525017                                            |
| 2  | [1,2,3,4,5]           | 1.0                                                   |  44.55                                         | 1.0                                                  |
| 1  | [0.1,0.2,0.3,0.4,0.5] | 1.0                                                   |   0.0                                          | 0.9999999                                            |
+----+-----------------------+-------------------------------------------------------+------------------------------------------------+------------------------------------------------------+
```

### StarRocks version (Required)
main ada1be1

### LINKED ISSUE #55010: Pass vector index params when it shouldn't
### Steps to reproduce the behavior (Required)
Create table and prepare data.
```sql
ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "true");

CREATE TABLE t6 (
    id bigint(20) NOT NULL COMMENT "",
    vector ARRAY<FLOAT> NOT NULL COMMENT "",
    INDEX index_vector (vector) USING VECTOR (
        "index_type" = "hnsw", 
        "dim"="5", 
        "metric_type" = "cosine_similarity", 
        "is_vector_normed" = "false", 
        "M" = "16", 
        "efconstruction" = "40"
    )
) ENGINE=OLAP
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);

insert into t6 values 
    (1, [10,12,13,14,15]),
    (2, [1,2,3,4,5]),
    (3, [0.1,0.2,0.3,0.4,0.5]);
```

Query
```sql
-- case 1
-- order by approx_cosine_similarity, but without limit.
select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) DESC;

-- case 2
-- order by non-approx_cosine_similarity and select approx_cosine_similarity
select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by id limit 10

-- case 3
-- disable enable_experimental_vector and order by approx_cosine_similarity
ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "false");
select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) DESC limit 1000;


-- case 4
-- disable enable_experimental_vector and do not use approx_cosine_similarity
ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "false");
select * from t6;
```

### Real behavior (Required)
``` 
MySQL root> select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) DESC ;
(1064, "Internal error: [2025-01-13 15:35:24] /root/tenann/tenann/searcher/faiss_hnsw_ann_searcher.cc:304: Error: Error in virtual void faiss::IndexHNSW::search(faiss::Index::idx_t, const float*, faiss::Index::idx_t, float*, faiss::Index::idx_t*, const faiss::SearchParameters*) const at /var/local/thirdparty/src/faiss-1.7.3/faiss/IndexHNSW.cpp:291: Error: 'k > 0' failed\n: BE:10002")

MySQL root> select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by id limit 10
(1064, "Internal error: [2025-01-13 15:35:55] /root/tenann/tenann/searcher/faiss_hnsw_ann_searcher.cc:304: Error: Error in virtual void faiss::IndexHNSW::search(faiss::Index::idx_t, const float*, faiss::Index::idx_t, float*, faiss::Index::idx_t*, const faiss::SearchParameters*) const at /var/local/thirdparty/src/faiss-1.7.3/faiss/IndexHNSW.cpp:291: Error: 'k > 0' failed\n: BE:10002")


MySQL root> ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "false");
Query OK, 0 rows affected
Time: 0.001s

MySQL root> select id, vector, approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) from t6 order by approx_cosine_similarity([0.1,0.2,0.3,0.4,0.5], vector) DESC limit 1000;
(1064, "Internal error: [2025-01-13 15:36:26] /root/tenann/tenann/searcher/faiss_hnsw_ann_searcher.cc:304: Error: Error in virtual void faiss::IndexHNSW::search(faiss::Index::idx_t, const float*, faiss::Index::idx_t, float*, faiss::Index::idx_t*, const faiss::SearchParameters*) const at /var/local/thirdparty/src/faiss-1.7.3/faiss/IndexHNSW.cpp:291: Error: 'k > 0' failed\n: BE:10002")

MySQL root> select * from t6;
BE crashed.
*** Aborted at 1736753925 (unix time) try "date -d @1736753925" if you are using GNU date ***
PC: @     0x7f76384655b6 __memcpy_ssse3_back
*** SIGSEGV (@0x4) received by PID 16722 (TID 0x7f75ab921700) LWP(17299) from PID 4; stack trace: ***
    @     0x7f763a7da20b __pthread_once_slow
    @          0xaeef514 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x7f763a7e3630 (/usr/lib64/libpthread-2.17.so+0xf62f)
    @     0x7f76384655b6 __memcpy_ssse3_back
    @          0xd101613 faiss::NormalizationTransform::apply_noalloc(long, float const*, float*) const
    @          0xd10171f faiss::VectorTransform::apply(long, float const*) const
    @          0xd10fed2 faiss::IndexPreTransform::apply_chain(long, float const*) const
    @          0xd1fd916 tenann::FaissHnswAnnSearcher::AnnSearch(tenann::PrimitiveSeqView, long, long*, unsigned char*, tenann::IdFilter const*)
    @          0x701be3e starrocks::TenANNReader::search(tenann::PrimitiveSeqView, int, long*, unsigned char*, tenann::IdFilter*)
    @          0x6d31619 starrocks::SegmentIterator::_get_row_ranges_by_vector_index()
    @          0x6d3f1ad starrocks::SegmentIterator::_init()
    @          0x6d3fc94 starrocks::SegmentIterator::do_get_next(starrocks::Chunk*)
    @          0x7738115 starrocks::SegmentIteratorWrapper::do_get_next(starrocks::Chunk*)
    @          0x74de8fb starrocks::TimedChunkIterator::do_get_next(starrocks::Chunk*)
    @          0x6dfe269 starrocks::TabletReader::do_get_next(starrocks::Chunk*)
    @          0x4c551bd starrocks::pipeline::OlapChunkSource::_read_chunk_from_storage(starrocks::RuntimeState*, starrocks::Chunk*)
    @          0x4c55c9a starrocks::pipeline::OlapChunkSource::_read_chunk(starrocks::RuntimeState*, std::shared_ptr<starrocks::Chunk>*)
    @          0x4c486d0 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking(starrocks::RuntimeState*, unsigned long, starrocks::workgroup::WorkGroup const*)
    @          0x489236b auto starrocks::pipeline::ScanOperator::_trigger_next_scan(starrocks::RuntimeState*, int)::{lambda(auto:1&)#1}::operator()<starrocks::workgroup::YieldContext>(starrocks::workgroup::YieldContext&) const [clone .isra.0]
    @          0x49b3379 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x3c2a0ff starrocks::ThreadPool::dispatch_thread()
    @          0x3c20780 starrocks::Thread::supervise_thread(void*)
    @     0x7f763a7dbea5 start_thread
    @     0x7f763840cb0d __clone
```

### StarRocks version (Required)
main ada1be1

### LINKED ISSUE #55011: Order by non-vector column returns error
### Steps to reproduce the behavior (Required)
Create table and prepare data.
```sql
ADMIN SET FRONTEND CONFIG ("enable_experimental_vector" = "true");

CREATE TABLE t6 (
    id bigint(20) NOT NULL COMMENT "",
    vector ARRAY<FLOAT> NOT NULL COMMENT "",
    INDEX index_vector (vector) USING VECTOR (
        "index_type" = "hnsw", 
        "dim"="5", 
        "metric_type" = "cosine_similarity", 
        "is_vector_normed" = "false", 
        "M" = "16", 
        "efconstruction" = "40"
    )
) ENGINE=OLAP
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);

insert into t6 values 
    (1, [10,12,13,14,15]),
    (2, [1,2,3,4,5]),
    (3, [0.1,0.2,0.3,0.4,0.5]);
```

Query
```sql
select * from t6 order by id
```

### Real behavior (Required)
``` 
> select * from t6 order by id
(1064, 'Cannot invoke "com.starrocks.sql.optimizer.operator.Projection.getColumnRefMap()" because the return value of "com.starrocks.sql.optimizer.operator.logical.LogicalOlapScanOperator.getProjection()" is null')
```

### StarRocks version (Required)
main ada1be1

### LINKED ISSUE #55055: BE crashed when index_type is hnsw and M is 1
### Steps to reproduce the behavior (Required)
```sql
CREATE TABLE t_test_vector_table (
    id bigint(20) NOT NULL COMMENT "",
    vector ARRAY<FLOAT> NOT NULL COMMENT "",
    INDEX index_vector (vector) USING VECTOR (
        "index_type" = "hnsw", 
        "dim"="4", 
        "metric_type" = "l2_distance", 
        "is_vector_normed" = "false", 
        "M" = "1", -- If set to 2, then we will not encounter this issue.
        "efconstruction" = "2"
    )
) ENGINE=OLAP
DUPLICATE KEY(id)
DISTRIBUTED BY HASH(id) BUCKETS 1
PROPERTIES (
    "replication_num" = "1"
);

insert into t_test_vector_table values 
            (1, [1.0, 2.0, 3.0, 4.0]),
            (2, [1.1, 2.1, 3.1, 4.1]),
            (3, [1.2, 2.2, 3.2, 4.2]),
            (4, [10.0, 10.0, 10.0, 10.0]),
            (5, [10.1, 10.1, 10.1, 10.1]),
            (6, [10.2, 10.2, 10.2, 10.2]),
            (7, [5.0, 5.0, 5.0, 5.0]),
            (8, [5.1, 5.1, 5.1, 5.1]),
            (9, [0.5, 0.5, 0.5, 0.5]),
            (10, [0.6, 0.6, 0.6, 0.6]) ;
```

### Real behavior (Required)
The process of BE is killed by the system due to OOM, and tenann allocates large memory lots of times as follows.
```
W20250114 13:47:51.076904 140145512130304 mem_hook.cpp:103] large memory alloc, query_id:00000000-0000-0000-0000-000000000000 instance: 00000000-0000-0000-0000-000000000000 acquire:68719476736 bytes, stack:
    @          0x3dfb311  starrocks::get_stack_trace[abi:cxx11]()
    @          0x3d56164  malloc
    @          0xea90368  operator new(unsigned long)
    @          0xd6c866d  faiss::(anonymous namespace)::hnsw_add_vertices(faiss::IndexHNSW&, unsigned long, unsigned long, float const*, bool, bool)
    @          0xd5d463d  tenann::FaissIndexBuilder::AddImpl(std::vector<tenann::SeqView, std::allocator<tenann::SeqView> > const&, long const*, unsigned char const*)
    @          0xd5d3e63  tenann::FaissIndexBuilder::Add(std::vector<tenann::SeqView, std::allocator<tenann::SeqView> > const&, long const*, unsigned char const*, bool)
    @          0x793698a  starrocks::TenAnnIndexBuilderProxy::add(starrocks::Column const&)
    @          0x792f83a  starrocks::VectorIndexWriter::_append_data(starrocks::Column const&, unsigned long)
    @          0x79309f1  starrocks::VectorIndexWriter::append(starrocks::Column const&)
    @          0x78ef2a8  starrocks::ArrayColumnWriter::append(starrocks::Column const&)
    @          0x6f2dce9  starrocks::SegmentWriter::append_chunk(starrocks::Chunk const&)
    @          0x79590c8  starrocks::HorizontalRowsetWriter::_flush_chunk(starrocks::Chunk const&, starrocks::SegmentPB*)
    @          0x79592a8  starrocks::HorizontalRowsetWriter::flush_chunk(starrocks::Chunk const&, starrocks::SegmentPB*)
    @          0x6fe9d9a  starrocks::MemTableRowsetWriterSink::flush_chunk(starrocks::Chunk const&, starrocks::SegmentPB*, bool)
    @          0x70337d8  starrocks::MemTable::flush(starrocks::SegmentPB*, bool)
    @          0x6d5d63a  starrocks::FlushToken::_flush_memtable(starrocks::MemTable*, starrocks::SegmentPB*, bool)
    @          0x6d5ebdf  starrocks::MemtableFlushTask::run()
    @          0x3e22448  starrocks::ThreadPool::dispatch_thread()
    @          0x3e18780  starrocks::Thread::supervise_thread(void*)
    @     0x7f7649895ea5  start_thread
    @     0x7f76474c6b0d  __clone
```

### StarRocks version (Required)
main e446727

### PR DESCRIPTION
**Pull request by ZiheLiu**
## Why I'm doing:

Fix bugs of vector index.

## What I'm doing:

Fixes #55009 
Fixes #55011 
Fixes #55010
Fixes #55055

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: be/src/exec/pipeline/scan/olap_chunk_source.cpp [hunk 1]
```diff
@@ -562,8 +556,8 @@ Status OlapChunkSource::_init_global_dicts(TabletReaderParams* params) {
         if (iter != global_dict_map.end()) {
             auto& dict_map = iter->second.first;
             int32_t index;
-            if (_use_vector_index && !_use_ivfpq) {
-                index = _tablet_schema->field_index(slot->col_name(), _vector_distance_column_name);
+            if (_use_vector_index && !_use_ivfpq && slot->id() == _vector_slot_id) {
+                index = _tablet_schema->num_columns();
```
Comment (stdpain) [inline be/src/exec/pipeline/scan/olap_chunk_source.cpp:560]: Is it possiable have more than one vector index slot id?

Comment (ZiheLiu) [reply be/src/exec/pipeline/scan/olap_chunk_source.cpp:560]: No, one table can only have at most one vector index for now. Many places use this assumption.

```cpp
Status SegmentIterator::_init_ann_reader() {
    std::unordered_map<int32_t, TabletIndex> col_map_index;
    for (const auto& index : *_segment->tablet_schema().indexes()) {
        if (index.index_type() == VECTOR) {
            col_map_index.emplace(index.col_unique_ids()[0], index);
        }
    }
    
    std::vector<TabletIndex> hit_indexes;
    for (auto& field : _schema.fields()) {
        if (col_map_index.count(field->uid()) > 0) {
            hit_indexes.emplace_back(col_map_index.at(field->uid()));
        }
    }
    // TODO: Support more index in one segment iterator, only support one index for now
    DCHECK(hit_indexes.size() <= 1) << "Only support query no more than one index now";
    
    if (hit_indexes.empty()) {
        return Status::OK();
    }
    
    auto tablet_index_meta = std::make_shared<TabletIndex>(hit_indexes[0]);
    std::string index_path = IndexDescriptor::vector_index_file_path(_opts.rowset_path, _opts.rowsetid.to_string(),
                                                                     segment_id(), tablet_index_meta->index_id());
    return _init_reader_from_file(index_path, tablet_index_meta, _query_params);
}

```

**Review by Seaven — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]
