### PR TITLE
[BugFix] Set Content-Type to application/json when responding to stream load http requests

### LINKED ISSUE #61130: Content-Type in response header of stream load http interface is wrongly set to text/html
I am trying to use the HTTP Stream Load interface to load data into Starrocks as described in the [documentation](https://docs.starrocks.io/docs/loading/Stream_Load_transaction_interface/). I noticed that the content-type of the HTTP response is wrongly set to `text/html` instead of `application/json`  when a HTTP request is made to the `/api/transaction/begin` endpoint.

### Steps to reproduce the behavior (Required)
I noticed the described error, when running the all-in-one image, as described in the documentation [here](https://docs.starrocks.io/docs/quick_start/shared-nothing/#launch-starrocks)
1. Run `docker run -p 9030:9030 -p 8030:8030 -p 8040:8040 -itd --name quickstart starrocks/allin1-ubuntu:3.5.2`
2. Run `CREATE DATABASE IF NOT EXISTS app`
3. Run `CREATE TABLE test(test_column STRING)`
4. Run `curl -v --location-trusted -u "root:" -H "label:test" -H "Expect:100-continue" -H "db:app" -H "table:test" -XPOST http://127.0.0.1:8030/api/transaction/begin`

### Expected behavior (Required)
The response should have the correct Content-Type `application/json` set in its header.
```
> POST /api/transaction/begin HTTP/1.1
> Host: 127.0.0.1:8040
> Authorization: Basic cm9vdDo=
> User-Agent: curl/8.5.0
> Accept: */*
> label:test
> Expect:100-continue
> db:app
> table:test
> 
< HTTP/1.1 200 OK
< Date: Mon, 21 Jul 2025 18:42:42 GMT
< Content-Length: 107
< Content-Type: application/json; charset=ISO-8859-1
< 
{
    "Status": "OK",
    "Message": "",
    "Label": "test",
    "TxnId": 3029,
    "BeginTxnTimeMs": 1
* Connection #1 to host 127.0.0.1 left intact
}
```

### Real behavior (Required)
The Content-Type header of the HTTP response is set to `text/html`.
```
> POST /api/transaction/begin HTTP/1.1
> Host: 127.0.0.1:8040
> Authorization: Basic cm9vdDo=
> User-Agent: curl/8.5.0
> Accept: */*
> label:test
> Expect:100-continue
> db:app
> table:test
> 
< HTTP/1.1 200 OK
< Date: Mon, 21 Jul 2025 18:42:42 GMT
< Content-Length: 107
< Content-Type: text/html; charset=ISO-8859-1
< 
{
    "Status": "OK",
    "Message": "",
    "Label": "test",
    "TxnId": 3029,
    "BeginTxnTimeMs": 1
* Connection #1 to host 127.0.0.1 left intact
}
```

### StarRocks version (Required)
`3.5.2-69de616`

### PR DESCRIPTION
**Pull request by fatihcatalkaya**
## Why I'm doing:
When sending a request to the `/api/transaction/{begin,load,commit,...}` endpoints, the content type is wrongly set to `text/html` instead of `application/json`.

## What I'm doing:

Fixes #61130 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3

### CODE REVIEW

File: be/src/http/http_channel.h [hunk 1]
```diff
@@ -45,6 +46,8 @@ class HttpChannel {
 
     static void send_reply(HttpRequest* request, HttpStatus status, std::string_view content);
 
+    static void send_reply(HttpRequest* request, HttpStatus status, std::string_view content, std::optional<std::string_view> content_type);
```
Comment (kevincai) [inline be/src/http/http_channel.h]: what we can do here is to add a new interface `send_json_reply()` which automatically add `Content-Type: application/json` to the response header.

**Review by kevincai — COMMENTED** [review]
shall add UT to confirm the response contains application/json content type.

File: be/src/http/action/transaction_stream_load.cpp [hunk 2]
```diff
@@ -95,15 +95,15 @@ static void _send_reply(HttpRequest* req, const std::string& str) {
     if (config::enable_stream_load_verbose_log) {
         LOG(INFO) << "transaction streaming load response: " << str;
     }
-    HttpChannel::send_reply(req, str);
+    HttpChannel::send_reply(req, HttpStatus::OK, str, HttpHeaders::JsonType);
```
[the remark this answers is not in the document]
Comment (fatihcatalkaya) [reply be/src/http/action/transaction_stream_load.cpp]: `HttpStatus::OK` was the original behavior, which is why I did not change it.

File: be/src/http/action/transaction_stream_load.cpp [hunk 3]
```diff
@@ -95,15 +95,15 @@ static void _send_reply(HttpRequest* req, const std::string& str) {
...
 }
 
 void TransactionManagerAction::_send_error_reply(HttpRequest* req, const Status& st) {
     auto ctx = std::make_unique<StreamLoadContext>(_exec_env);
     ctx->label = req->header(HTTP_LABEL_KEY);
 
     auto str = ctx->to_resp_json(req->param(HTTP_TXN_OP_KEY), st);
-    HttpChannel::send_reply(req, str);
+    HttpChannel::send_reply(req, HttpStatus::OK, str, HttpHeaders::JsonType);
```
[the remark this answers is not in the document]
Comment (fatihcatalkaya) [reply be/src/http/action/transaction_stream_load.cpp]: The original behavior was to send `HttpStatus::OK` which is why I did not change it.

File: be/src/http/http_channel.h (hunk 1 above)
Comment (fatihcatalkaya) [reply be/src/http/http_channel.h]: I've added a new function `send_reply_json()` that adds the content type. By naming it this way, it will pop up on the auto-complete, when typing `send_reply`, which I thought would be a better DX. What do you think?

File: be/src/http/http_channel.cpp [hunk 4]
```diff
@@ -60,6 +66,10 @@ void HttpChannel::send_reply(HttpRequest* request, HttpStatus status, std::strin
 #endif
     auto evb = evbuffer_new();
     evbuffer_add(evb, content.data(), content.size());
+    if (content_type.has_value()) {
+        auto headers = evhttp_request_get_output_headers(request->get_evhttp_request());
+        evhttp_add_header(headers, HttpHeaders::CONTENT_TYPE, content_type->data());
```
[the remark this answers is not in the document]
Comment (fatihcatalkaya) [reply be/src/http/http_channel.cpp]: I've included this in my second commit.

**Comment by fatihcatalkaya** [comment]
@kevincai I am not really sure how to modify the `transaction_stream_load_test.cpp`. From my understanding, we are overwriting the send_reply function in lines 43-46, so we can just grab the body of the response without dealing with all the HTTP stuff. How would you approach this? 

Sorry again for asking so many questions, this is my first time working on such a big C++ project :sweat_smile:

**Review by kevincai — DISMISSED** [review]

**Comment by alvin-phoenix-ai** [comment]
@fatihcatalkaya 
Could you fix the clang-format check, you can refer to https://github.com/StarRocks/starrocks/actions/runs/16541726487/job/46824442006?pr=61144

**Comment by fatihcatalkaya** [comment]
@alvin-celerdata should be done, currently waiting for the pipeline. Thank you!

**Review by alvin-phoenix-ai — DISMISSED** [review]

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Comment by alvin-phoenix-ai** [comment]
https://github.com/cursor review

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: be/src/http/http_channel.cpp [hunk 5]
```diff
@@ -60,6 +70,10 @@ void HttpChannel::send_reply(HttpRequest* request, HttpStatus status, std::strin
 #endif
     auto evb = evbuffer_new();
     evbuffer_add(evb, content.data(), content.size());
+    if (content_type.has_value()) {
```
Comment (kevincai) [inline be/src/http/http_channel.cpp]: shall move fix to before line 65, so in case it is a UNIT TEST, the unit test can get the hijacked http request will the header of content-type set properly.

File: be/src/http/action/transaction_stream_load.cpp [hunk 6]
```diff
@@ -95,15 +95,15 @@ static void _send_reply(HttpRequest* req, const std::string& str) {
     if (config::enable_stream_load_verbose_log) {
         LOG(INFO) << "transaction streaming load response: " << str;
     }
-    HttpChannel::send_reply(req, str);
+    HttpChannel::send_reply_json(req, HttpStatus::OK, str);
```
Comment (kevincai) [inline be/src/http/action/transaction_stream_load.cpp:98]: action/stream_load.cpp shall have the same change.

**Comment by kevincai** [comment]
UT can be added after PR https://github.com/StarRocks/starrocks/pull/61390 get merged.

File: be/src/http/http_channel.cpp (hunk 5 above)
Comment (fatihcatalkaya) [reply be/src/http/http_channel.cpp]: I did not understood what you meant here, could you explain it a bit more in depth?

Comment (kevincai) [reply be/src/http/http_channel.cpp]: line 65-line70 is a hack code for unit test, s_injected_send_reply will be defined in unit test so it can directly get the response body and do the validation.

In order to let the unit test verify the http response headers, the evhttp_add_header() should be called before invoking `s_injected_send_reply()`

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
Pushed a new commit with the following changes:

* content-type is checked in unit test for both stream load and transactional stream load
* turn to `send_json_reply` in stream load api as well.

**Review by kevincai — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
