### PR TITLE
Remove root attribute of pipeline

### LINKED ISSUE #4883: Lose profile in pipeline mode
### Steps to reproduce the behavior (Required)
testcase: test_create_bitmap_index.TestCreateBitmapIndex.test_bitmap_index_for_char

query:
```sql
SELECT SUM(k7), SUM(k8), MAX(k9), MAX(k10)                  
FROM duplicate_table_with_null                  
WHERE k3 = 'guangzhou'
```

### Expected behavior (Required)
Utilize bitmap index to skip data.

### Real behavior (Required)
Profile loss, which appears not using bitmap index, but actually it indeed apply the bitmap index.

non-pipeline mode:
```yaml
              SCAN:(Active: 485.85us[485085ns], % non-child: 0.01%)
                 - CachedPagesNum: 0
                 - CompressedBytesRead: 42.25 KB
                 - CreateSegmentIter: 42.990us
                 - DictDecode: 891ns
                 - IOTime: 23.492us
                 - LateMaterialize: 227.220us
                 - PushdownPredicates: 1
                 - RawRowsRead: 5.522K (5522)
                 - ReadPagesNum: 7
                 - SegmentInit: 127.724us
                   - BitmapIndexFilter: 37.277us
                   - BitmapIndexFilterRows: 16.51K (16510)
                   - BloomFilterFilterRows: 0
                   - SegmentZoneMapFilterRows: 0
                   - ShortKeyFilterRows: 0
                   - ZoneMapIndexFilterRows: 0
                 - SegmentRead: 63.521us
                   - BlockFetch: 30.22us
                   - BlockFetchCount: 2
                   - BlockSeek: 30.485us
                   - BlockSeekCount: 2
                   - ChunkCopy: 0ns
                   - DecompressT: 13.377us
                   - DelVecFilterRows: 0
                   - IndexLoad: 0ns
                   - PredFilter: 0ns
                   - PredFilterRows: 0
                   - RowsetsReadCount: 2
                   - SegmentsReadCount: 1
                   - TotalColumnsDataPageCount: 14
                 - UncompressedBytesRead: 42.18 KB
```

pipeline mode:
```yaml
             - ScanTime: 8s849ms
               - __MAX_OF_ScanTime: 26s546ms
               - __MIN_OF_ScanTime: 922.232us
             - SegmentInit: 0ns
               - BitmapIndexFilter: 0ns
               - BitmapIndexFilterRows: 0
               - BloomFilterFilterRows: 0
               - ShortKeyFilterRows: 0
               - ZoneMapIndexFilterRows: 0
             - SegmentRead: 0ns
               - BlockFetch: 0ns
               - BlockFetchCount: 0
               - BlockSeek: 0ns
               - BlockSeekCount: 0
               - ChunkCopy: 0ns
               - DecompressT: 0ns
               - DelVecFilterRows: 0
               - IndexLoad: 0ns
               - PredFilter: 0ns
               - PredFilterRows: 0
               - RowsetsReadCount: 0
               - SegmentsReadCount: 0
               - TotalColumnsDataPageCount: 0
             - UncompressedBytesRead: 0.00 

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - commit `a561464`

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4883

## Problem Summary(Required) ：

Report exec state only when all pipeline drivers finished

### CODE REVIEW

File: be/src/exec/pipeline/pipeline_driver.cpp [hunk 1]
```diff
@@ -302,23 +302,13 @@ void PipelineDriver::finalize(RuntimeState* runtime_state, DriverState state) {
...
-    // some non-root drivers maybe has pending io io tasks hold the reference to
-    // object owned by FragmentContext.
-    if (is_root()) {
-        if (_fragment_ctx->count_down_root_drivers()) {
-            _fragment_ctx->finish();
-            auto status = _fragment_ctx->final_status();
-            _fragment_ctx->runtime_state()->exec_env()->driver_executor()->report_exec_state(_fragment_ctx, status,
-                                                                                             true);
-        }
-    }
```
Comment (ZiheLiu) [inline be/src/exec/pipeline/pipeline_driver.cpp:316]: If `is_report_success` is false, could we use the original logic, which reports as soon as root finished?

**Review by murphyatwork — APPROVED** [review]

File: be/src/exec/pipeline/pipeline_driver.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/pipeline_driver.cpp:316]: 「the elapsed time between root finished and all the drivers finished may be long」Is this conclusion based on tests? In my opinion, when root driver is finished, the other non-root drivers are doing the finishing jobs, theoretically, it won't take too long. 

Considering the extreme situation you point out, exec state will be sent as soon as root driver finished, while other non-root drivers are busy doing finishing jobs. The early return cannot actually release the resources it occupied (by non-root drivers), which means the next bunch of queries may not benefit from the early return in concurrency situations.

 I'll add some tests to performance decline.

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

File: be/src/exec/pipeline/pipeline_driver.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/pipeline_driver.cpp:316]: Test reporter: https://starrocks.feishu.cn/docs/doccnAPF6B71Nct1hql7tu3BtYb#
