### PR TITLE
[BugFix] Fix mysql client unable to change current catalog

### LINKED ISSUE #17993: mysql client execute " use 'catalog catalog_name' " failed
### Steps to reproduce the behavior (Required)
1. 
```
mysql -hxxx.xx.xx.xxx -P9232 -uroot
use 'catalog test_iceberg_type2';
use 'default_catalog.yn_db';
```
use mysql client and mariadb client

image

image

### Expected behavior (Required)
All clients executed successfully
### Real behavior (Required)
mariadb clients executed successfully
mysql client failed to execute
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.5-RELEASE c8ab2cd |
+----------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by letian-jiang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17993

## Problem Summary(Required) ：

`USE 'CATALOG catalog_name'` issued by mysql client will be dispatched to `handleQuery` function. In this case, the current implementation throws parse exception, thus fails to switch the catalog in use. 

The changes made are:
* change `useCatalogStatement : USE CATALOG identifierOrString ` to `useCatalogStatement : USE string;`
* add or update parser/analyzer/executor for useCatalogStatement
* update unit tests

Limitation:
Mysql client of version 5.7.31 would raise a benign error as follows. 
```
ERROR:
USE must be followed by a database name
```
But the catalog can be changed successfully.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/CatalogAnalyzer.java|8|9|88.89%|[88]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UseCatalogStmt.java|3|3|100.00%|[]|

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by Smith-Cruise** [comment]
So you mean we support using `use specific_catalog` to change catalog after this pr?

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
> So you mean we support using `use specific_catalog` to change catalog after this pr?

Yes. More specifically, `USE 'CATALOG specific_catalog'`

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/CatalogAnalyzer.java|8|9|88.89%|[88]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UseCatalogStmt.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java [hunk 1]
```diff
@@ -991,7 +991,8 @@ private void handleUseDbStmt() throws AnalysisException {
     private void handleUseCatalogStmt() throws AnalysisException {
         UseCatalogStmt useCatalogStmt = (UseCatalogStmt) parsedStmt;
         try {
-            context.getGlobalStateMgr().changeCatalog(context, useCatalogStmt.getCatalogName());
+            String catalogName = useCatalogStmt.getCatalogAndItsName().split("\\s+")[1];
```
Comment (Smith-Cruise) [inline fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java:994]: You can put split logic into `UseCatalogStmt`.

**Review by Smith-Cruise — COMMENTED** [review]
Advice： Put split & validation logic into `UseCatalogStmt`

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java [hunk 2]
```diff
@@ -80,5 +81,25 @@ public Void visitDropCatalogStatement(DropCatalogStmt statement, ConnectContext
 
             return null;
         }
+
+        @Override
+        public Void visitUseCatalogStatement(UseCatalogStmt statement, ConnectContext context) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java:86]: parse and set the catalog name to UseCatalogStmt in here and then you can use catalogName in StmtExecutor.

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java [hunk 3]
```diff
@@ -19,19 +19,19 @@
 import com.starrocks.sql.parser.NodePosition;
 
 public class UseCatalogStmt extends StatementBase {
-    private final String catalogName;
+    private final String catalogAndItsName;
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java:22]:
```suggestion
    private final String catalogParts;
```

Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java:22]: private String catalogName;

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java [hunk 4]
```diff
@@ -80,5 +81,25 @@ public Void visitDropCatalogStatement(DropCatalogStmt statement, ConnectContext
...
+            if (Strings.isNullOrEmpty(statement.getCatalogAndItsName())) {
+                throw new SemanticException("'catalog name' can not be null or empty");
+            }
+
+            String[] catalogAndItsName = statement.getCatalogAndItsName().split("\\s+");
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java:91]: set 's+' to static variable and use it.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java [hunk 5]
```diff
@@ -80,5 +81,25 @@ public Void visitDropCatalogStatement(DropCatalogStmt statement, ConnectContext
...
+            if (catalogAndItsName.length == 0 || !catalogAndItsName[0].equalsIgnoreCase("CATALOG")) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java:92]: ditto

File: fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java (hunk 1 above)
Comment (letian-jiang) [reply fe/fe-core/src/main/java/com/starrocks/qe/StmtExecutor.java]: done

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java (hunk 2 above)
Comment (letian-jiang) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java:90]: done

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java (hunk 4 above)
Comment (letian-jiang) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/CatalogAnalyzer.java]: done

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Review by Smith-Cruise — DISMISSED** [review]

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_fe_unittest

**Comment by letian-jiang** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java [hunk 6]
```diff
@@ -19,21 +19,31 @@
 import com.starrocks.sql.parser.NodePosition;
 
 public class UseCatalogStmt extends StatementBase {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/UseCatalogStmt.java:21]: add some comments

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_fe_unittest

**Review by stephen-shelby — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 25 (96.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/CatalogAnalyzer.java|7|8|87.50%|[92]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/AstVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UseCatalogStmt.java|6|6|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
run starrocks_admit_test

**Comment by letian-jiang** [comment]
@Mergifyio backport branch-2.5

**Comment by letian-jiang** [comment]
@Mergifyio backport branch-3.0

**Comment by dirtysalt** [comment]
Is there currently no way to keep the USE CATALOG syntax?

I see you have added a set catalog, can use catalog be used in the same way?

14051dbd-ee0d-4d31-a1be-002e534a811b


Without this syntax there are some problems with other mysql mock terminals, some customers could use use catalog before 2.5.1, but not now. This is not a big problem, just see if you can support both.

cc59a132-4464-4c39-bfb5-5b60e413be4d

**Comment by dirtysalt** [comment]
Intercept here at UseDatabaseStmt (this seems OK)

6216c043-f8c4-4549-a718-c72b56b70d5e


Or see if the rule can be raised to match first

4bef1e6e-73d0-4c9e-80b9-c45c67efdea0
