### PR TITLE
[BugFix] fix compaction score compare problem in lake compaction

### LINKED ISSUE #50284: [BUG] LakeCompaction IllegalArgumentException
### Steps to reproduce the behavior (Required)

```
2024-08-21 10:22:42,115 ERROR (COMPACTION_DISPATCH|263) [Daemon.run():109] daemon thread got exception. name: COMPACTION_DISPATCH
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:899) ~[?:1.8.0_74]
        at java.util.TimSort.mergeAt(TimSort.java:516) ~[?:1.8.0_74]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457) ~[?:1.8.0_74]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:1.8.0_74]
        at java.util.Arrays.sort(Arrays.java:1512) ~[?:1.8.0_74]
        at java.util.ArrayList.sort(ArrayList.java:1454) ~[?:1.8.0_74]
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387) ~[?:1.8.0_74]
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_74]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_74]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_74]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_74]
        at com.starrocks.lake.compaction.ScoreSorter.sort(ScoreSorter.java:30) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionMgr.choosePartitionsToCompact(CompactionMgr.java:125) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionMgr.choosePartitionsToCompact(CompactionMgr.java:120) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionScheduler.schedule(CompactionScheduler.java:187) ~[starrocks-fe.jar:?]
        at com.starrocks.lake.compaction.CompactionScheduler.runOneCycle(CompactionScheduler.java:105) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:107) ~[starrocks-fe.jar:?]
```

### StarRocks version (Required)

 - v3.2.4

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## What I'm doing:

Fixes #50284

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]
better to add comment

File: fe/fe-core/src/main/java/com/starrocks/lake/compaction/Quantiles.java [hunk 1]
```diff
@@ -64,14 +64,15 @@ public double getMax() {
 
     @Override
     public int compareTo(@NotNull Quantiles o) {
-        if (avg != o.avg) {
-            return avg > o.avg ? 1 : -1;
+        // must use Double.compare to avoid float type precision issue
+        if (Double.compare(avg, o.avg) != 0) {
+            return Double.compare(avg, o.avg) > 0 ? 1 : -1;
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/lake/compaction/Quantiles.java:69]:
```suggestion
        if (Double.compare(avg, o.avg) != 0) {
            return Double.compare(avg, o.avg);
```

**Review by kevincai — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by starrocks-xupeng** [comment]
https://github.com/StarRocks/starrocks/pull/50370, branch-3.1
