### PR TITLE
[BugFix] Fix apply output error when use table function

### LINKED ISSUE #6579: Apply output error when use table function
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes  #6579

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java|7|7|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java [hunk 1]
```diff
@@ -48,15 +48,23 @@ public class LogicalApplyOperator extends LogicalOperator {
      */
     private final boolean useSemiAnti;
 
+    private final boolean isTableFunction;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java:51]: needOutputRightChildColumns?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/RelationTransformer.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalApplyOperator.java|7|7|100.00%|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
