### PR TITLE
[SR-4261] Fix bug when create table using the schema of logical view

### LINKED ISSUE #356: create table like for view table is unsupported
### Steps to reproduce the behavior (Required)
0.CREATE TABLE lineitem ( l_orderkey    bigint NOT NULL,
                             l_linenumber  int not null,
                             l_shipdate    DATE NOT NULL,
                             l_partkey     int NOT NULL,
                             l_suppkey     int not null,
                             l_quantity    decimal(15, 2) NOT NULL,
                             l_extendedprice  decimal(15, 2) NOT NULL,
                             l_discount    decimal(15, 2) NOT NULL,
                             l_tax         decimal(15, 2) NOT NULL,
                             l_returnflag  CHAR(1) NOT NULL,
                             l_linestatus  CHAR(1) NOT NULL,
                             l_commitdate  DATE NOT NULL,
                             l_receiptdate DATE NOT NULL,
                             l_shipinstruct CHAR(25) NOT NULL,
                             l_shipmode     CHAR(10) NOT NULL,
                             l_comment      VARCHAR(44) NOT NULL)
ENGINE=OLAP
DUPLICATE KEY(`l_orderkey`, `l_linenumber`, `l_shipdate`)
COMMENT "OLAP"
PARTITION BY RANGE(`l_shipdate`)
(
   START ("1992-01-01") END ("1999-01-01") EVERY (INTERVAL 1 year)
)
DISTRIBUTED BY HASH(`l_orderkey`) BUCKETS 48
PROPERTIES (
    "replication_num" = "1",
    "in_memory" = "false",
    "storage_format" = "DEFAULT",
    "colocate_with" = "tpch1"
);
1. CREATE VIEW `revenue0` AS SELECT `l_suppkey` AS `supplier_no`, sum(`l_extendedprice` * (1 - `l_discount`)) AS `total_revenue` FROM `default_cluster:tpch`.`lineitem` WHERE (`l_shipdate` >= '1995-01-01') AND (`l_shipdate` < '1995-01-01' + INTERVAL '3' month) GROUP BY `l_suppkey`;
2. create table revenue0 like tpch.revenue0;

### Expected behavior (Required)
ERROR 1064 (HY000): Failed to execute CREATE TABLE LIKE revenue0. Reason: Create table like does not support view creation.
### Real behavior (Required)
Error 1064: Unexpected exception: org.apache.doris.analysis.CreateViewStmt cannot be cast to org.apache.doris.analysis.CreateTableStmt

### StarRocks version (Required)
1.19 & later

may be it will be supported in create view like ...

### PR DESCRIPTION
**Pull request by Astralidea**
For #356

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 1]
```diff
@@ -3045,13 +3046,18 @@ public void createTableLike(CreateTableLikeStmt stmt) throws DdlException {
...
-                    (CreateTableStmt) SqlParserUtils.parseAndAnalyzeStmt(createTableStmt.get(0), ConnectContext.get());
-            parsedCreateTableStmt.setTableName(stmt.getTableName());
-            if (stmt.isSetIfNotExists()) {
-                parsedCreateTableStmt.setIfNotExists();
+            StatementBase statementBase = SqlParserUtils.parseAndAnalyzeStmt(createTableStmt.get(0), ConnectContext.get());
+            if (statementBase instanceof CreateTableStmt) {
+                CreateTableStmt parsedCreateTableStmt =
+                        (CreateTableStmt) SqlParserUtils.parseAndAnalyzeStmt(createTableStmt.get(0), ConnectContext.get());
+                parsedCreateTableStmt.setTableName(stmt.getTableName());
+                if (stmt.isSetIfNotExists()) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:3054]: how about create view like table?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:3054]: create view like table is currently not supported.

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
