### PR TITLE
[BugFix] Fix replicated storage write hang when async writer fail

### LINKED ISSUE #16050: test_condition_update_not_support case fail
### Steps to reproduce the behavior (Required)
nosetests-3.4 -s --with-xunit --xunit-file=./result/test_stream_load_condition_update_py_TestStreamLoadConditionUpdate_test_condition_update_not_support.xml --verbose case/system_case/test_dml/test_stream_load/test_stream_load_condition_update.py:TestStreamLoadConditionUpdate.test_condition_update_not_support --nologcapture

### Expected behavior (Required)
success less than 10s

### Real behavior (Required)
fail more than 300s

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16050

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by imay — APPROVED** [review]

File: be/src/runtime/local_tablets_channel.cpp [hunk 1]
```diff
@@ -242,7 +242,7 @@ void LocalTabletsChannel::add_chunk(Chunk* chunk, const PTabletWriterAddChunkReq
     count_down_latch.wait();
 
     // We need wait all secondary replica commit before we close the channel
-    if (_is_replicated_storage && close_channel) {
+    if (_is_replicated_storage && close_channel && response->status().status_code() == TStatusCode::OK) {
```
Comment (chaoyli) [inline be/src/runtime/local_tablets_channel.cpp:245]: Why it will be hanged without this check?
As well, it's better to add a concise commit message in the pull request.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
