### PR TITLE
[Enhancement] Retry building ImmutableIndexShard if move_bucket failed

### LINKED ISSUE #4774: Retry building ImmutableIndexShard if find_buckets_to_move failed
## Enhancement
Currently, the find_buckets_to_move algorithm may fail in theory, and building ImmutableIndex will fail if a shard is very imbalanced. We need to prevent building index failure, when find_buckets_to_move failed, we can increase the number of pages and retry, until it works.

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #4774

## Problem Summary(Required) ：

Currently, move_bucket may fail even though we find a move solution, and building ImmutableIndex will fail if a shard is very imbalanced. We need to prevent building index failure, when move_bucket failed, we can increase the number of pages and retry, until it works.

### CODE REVIEW

**Comment by sevev** [comment]
run all

**Comment by sevev** [comment]
run starrocks_be_unittest

**Review by decster — COMMENTED** [review]
extract another function?

File: be/src/storage/persistent_index.cpp [hunk 1]
```diff
@@ -315,6 +319,20 @@ StatusOr<std::unique_ptr<ImmutableIndexShard>> ImmutableIndexShard::create(size_
...
+            continue;
+        }
+        return std::move(rs_create.value());
+    }
+    return Status::InternalError("failed to create immutable index shard");
+}
+
+StatusOr<std::unique_ptr<ImmutableIndexShard>> ImmutableIndexShard::try_create(size_t kv_size,
+                                                                               const std::vector<KVRef>& kv_refs,
+                                                                               size_t npage_hint) {
```
Comment (decster) [inline be/src/storage/persistent_index.cpp:335]: npage_hint -> npage

File: be/src/storage/persistent_index.cpp [hunk 2]
```diff
@@ -315,6 +319,20 @@ StatusOr<std::unique_ptr<ImmutableIndexShard>> ImmutableIndexShard::create(size_
...
+        // increase npage and retry
+        if (!rs_create.ok()) {
+            continue;
+        }
+        return std::move(rs_create.value());
+    }
+    return Status::InternalError("failed to create immutable index shard");
+}
+
+StatusOr<std::unique_ptr<ImmutableIndexShard>> ImmutableIndexShard::try_create(size_t kv_size,
```
Comment (decster) [inline be/src/storage/persistent_index.cpp:333]: try_create -> create

Comment (sevev) [reply be/src/storage/persistent_index.cpp:333]: > try_create -> create

There is already a `create` function. `create` function will call `try_create` with a fixed npage, if `try_create` failed, it will increase napge and retry

File: be/src/storage/persistent_index.cpp (hunk 1 above)
Comment (sevev) [reply be/src/storage/persistent_index.cpp]: > npage_hint -> npage

done

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
