### PR TITLE
[BugFix]: Change `enable_persistent_index` of primary table may cause be crash in ASAN mode

### LINKED ISSUE #7761: Be crash in ASAN mode
origin_img_v2_e196ecf5-ae7e-4c94-85ff-47034b200efg

This is caused by concurrency between apply and modify enable_persistent_index. The reference of primary index may not equal 1, so it will cause crash when call function `remove` in ASAN mode.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7761 

## Problem Summary(Required) ：

This is caused by concurrency between apply and modify enable_persistent_index. The reference of primary index may not equal 1, so it will cause crash when call function remove in ASAN mode.

### CODE REVIEW

File: be/src/agent/task_worker_pool.cpp [hunk 1]
```diff
@@ -943,7 +943,7 @@ void* TaskWorkerPool::_update_tablet_meta_worker_thread_callback(void* arg_this)
                     // because the primary index is available in cache
                     // But it will be remove from index cache after apply is finished
                     auto manager = StorageEngine::instance()->update_manager();
-                    manager->index_cache().remove_by_key(tablet->tablet_id());
+                    manager->index_cache().try_remove_by_key(tablet->tablet_id());
```
Comment (chaoyli) [inline be/src/agent/task_worker_pool.cpp:946]: If the try_remove_by key is false, when to remove the key?

Comment (sevev) [reply be/src/agent/task_worker_pool.cpp:946]: > If the try_remove_by key is false, when to remove the key?

It will be remove from index cache after apply is finished

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
