### PR TITLE
fix fail to prepare tablet reader bug

### LINKED ISSUE #1763: Query error
### Steps to reproduce the behavior (Required)
1. be service is Down.
2. restart be service
3. Query sql
```SQL
select count(1) from search_realtime_feas_online.search_pv_uv_realtime where dt='2021-12-01';
ERROR 1064 (HY000): [10.50.4.140] fail to prepare tablet reader 589905.1773548712.1e445327c295d148-1dbd7349cc3ff6aa: Internal error: fail to find rowset of version 0-7474
```
OR
1. be service is Down.
2. fe service is Down. 
3. restart be service
4. Query sql
```SQL
select count(1) from search_realtime_feas_online.search_pv_uv_realtime where dt='2021-12-01';
ERROR 1064 (HY000): [10.50.4.140] fail to prepare tablet reader 589905.1773548712.1e445327c295d148-1dbd7349cc3ff6aa: Internal error: fail to find rowset of version 0-7474
```

- StarRocks version
```sql
+-------------------+
| current_version() |
+-------------------+
| 1.19.1 65e87c3    |
+-------------------+
```

```bash
cat be.WARNING 
W1201 16:30:40.874563 145353 version_graph.cpp:421] fail to find path in version_graph. spec_version: 0-7503
W1201 16:30:40.874675 145353 tablet.cpp:557] status:-214, tablet:624827.415242323.7944a49434cf6d0c-d363913e2dd9f281, missed version for version:[0-7503]
W1201 16:30:40.874686 145353 tablet.cpp:1018] 624827.415242323.7944a49434cf6d0c-d363913e2dd9f281 has 3 missed version:[6698-6698],[6699-6699],[6700-6700],
W1201 16:30:40.874768 145353 version_graph.cpp:421] fail to find path in version_graph. spec_version: 0-21280
W1201 16:30:40.874912 145353 tablet.cpp:557] status:-214, tablet:688923.442687030.0f453e0dc2881070-9b65583b01eac482, missed version for version:[0-21280]
W1201 16:30:40.874924 145353 tablet.cpp:1018] 688923.442687030.0f453e0dc2881070-9b65583b01eac482 has 15 missed version:[20210-20210],[20211-20211],[20212-20212],[20213-20213],[20214-20214],[20215-20215],[20216-20216],[20217-20217],[20218-20218],[20219-20219],
W1201 16:30:40.875784 145353 version_graph.cpp:421] fail to find path in version_graph. spec_version: 0-155281
W1201 16:30:40.875852 145353 tablet.cpp:557] status:-214, tablet:624988.917250708.ac437e14f3f88ffc-774973ec493cc986, missed version for version:[0-155281]
W1201 16:30:40.875862 145353 tablet.cpp:1018] 624988.917250708.ac437e14f3f88ffc-774973ec493cc986 has 15 missed version:[154905-154905],[154906-154906],[154907-154907],[154908-154908],[154909-154909],[154910-154910],[154911-154911],[154912-154912],[154913-154913],[154914-154914],
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by DeepThinker666**
Now publish version will succeed when quorum succeeds. But the finished transaction will update the version of all replicas to a visible version, which will lead to query the unsuccessful replica and result in query failure. Fix the bug by skipping updating the unsuccessful replica's version when the transaction is finished.

### CODE REVIEW

**Comment by DeepThinker666** [comment]
fix #1763

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -669,6 +669,9 @@ public boolean canTxnFinished(TransactionState txn, Set<Long> errReplicas) {
                                 if (!errReplicas.contains(replica.getId()) && replica.getLastFailedVersion() < 0) {
                                     if (replica.getVersion() >= partitionCommitInfo.getVersion()) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:670]: The version of replica is updated through finish transaction or be report, and the result of canTxnFinished determines whether to execute finish transaction.
Load job maybe not able to finish normally when one backend is crash and quorum is satisfied.

**Review by decster — DISMISSED** [review]

File: be/src/storage/task/engine_publish_version_task.cpp [hunk 2]
```diff
@@ -119,9 +119,9 @@ OLAPStatus EnginePublishVersionTask::finish() {
                 }
             }
             partition_related_tablet_infos.erase(tablet_info);
-            VLOG(1) << "publish version successfully on tablet. tablet=" << tablet->full_name()
-                    << ", transaction_id=" << transaction_id << ", version=" << version.first
-                    << ", res=" << publish_status;
+            LOG(INFO) << "publish version successfully on tablet. tablet=" << tablet->full_name()
```
Comment (imay) [inline be/src/storage/task/engine_publish_version_task.cpp:122]: Why change this log level?

Comment (DeepThinker666) [reply be/src/storage/task/engine_publish_version_task.cpp:122]: I will reverse this log.
I just want to add the log in line 149

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java (hunk 1 above)
Comment (DeepThinker666) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:670]: yes, Now the mechanism of visibility depend on the report of replica. It can be optimized.

**Comment by DeepThinker666** [comment]
run starrocks_fe_unittest

File: be/src/storage/task/engine_publish_version_task.cpp [hunk 3]
```diff
@@ -146,8 +146,8 @@ OLAPStatus EnginePublishVersionTask::finish() {
         }
     }
 
-    VLOG(1) << "finish to publish version on transaction."
-            << "transaction_id=" << transaction_id << ", error_tablet_size=" << _error_tablet_ids->size();
+    LOG(INFO) << "finish to publish version on transaction."
```
Comment (imay) [inline be/src/storage/task/engine_publish_version_task.cpp:149]: Better to keep VLOG, this will generated too many log.

File: fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java [hunk 4]
```diff
@@ -105,11 +107,19 @@ private void publishVersion() throws UserException {
...
                     allTaskFinished = false;
+                    unfinishedBackends.add(publishVersionTask.getBackendId());
                 }
             }
             boolean shouldFinishTxn = true;
             if (!allTaskFinished) {
-                shouldFinishTxn = globalTransactionMgr.canTxnFinished(transactionState, publishErrorReplicaIds);
+                shouldFinishTxn = globalTransactionMgr.canTxnFinished(transactionState,
+                        publishErrorReplicaIds, unfinishedBackends);
+                if (shouldFinishTxn) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java:117]: This log better be removed.

Comment (DeepThinker666) [reply fe/fe-core/src/main/java/com/starrocks/transaction/PublishVersionDaemon.java]: done

File: be/src/storage/task/engine_publish_version_task.cpp (hunk 3 above)
Comment (DeepThinker666) [reply be/src/storage/task/engine_publish_version_task.cpp]: done

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]
