### PR TITLE
[BugFix] JDBC scanner encountered down_cast error while constcolumn is nullable

### LINKED ISSUE #20723: be crash when JDBC external table join olap table and jdbc external table has NULL values
### Steps to reproduce the behavior (Required)
1.mysql
create table t_test(
id int, 
name varchar(10),
money decimal(10,9) default NULL)
insert into t_leo (id, name) values(1,'a')
2. starrocks
create jdbc catalog
Create table sr.test_mysql select * from jdbc_catalog.test.t_test; 
create jdbc resource;
create jdbc external sr.test_mysql_externaltable;
 select a.id,b.money from sr.test_mysql a left join jdbc_catalog.test.t_test b on a.id=b.id;  -> be crash
 select a.id,b.money from sr.test_mysql a left join sr.test_mysql_externaltable b on a.id=b.id -> be crash

### Expected behavior (Required)
return correct result
### Real behavior (Required)
be crash
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zombee0**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20723

## Problem Summary(Required) ：

jdbc_sanner.cpp:_fill_chunk _cast_exprs evaluate may return constcolumn which is nullable, and when it is used later like copying into dst nullcolumn, nullable_column.cpp append_selective just check nullable and down_cast(src) which lead to error.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by DorianZheng** [comment]
Please add UT

**Comment by DorianZheng** [comment]
When there is nullable constcolumn

File: be/src/exec/jdbc_scanner.cpp [hunk 1]
```diff
@@ -424,7 +424,8 @@ Status JDBCScanner::_fill_chunk(jobject jchunk, size_t num_rows, ChunkPtr* chunk
         ColumnPtr& column = (*chunk)->get_column_by_slot_id(slot_desc->id());
         ASSIGN_OR_RETURN(auto result, _cast_exprs[col_idx]->evaluate(_result_chunk.get()));
         if (column->is_nullable() == result->is_nullable()) {
-            column = result;
+            // unpack const_nullable_column to avoid error down_cast
+            column = ColumnHelper::unpack_and_duplicate_const_column(num_rows, result);
```
Comment (Seaven) [inline be/src/exec/jdbc_scanner.cpp:428]: move it to line 425

Comment (zombee0) [reply be/src/exec/jdbc_scanner.cpp]: done

**Review by Seaven — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by stdpain** [comment]
why cast expr return a const nullable column?

**Comment by zombee0** [comment]
> why cast expr return a const nullable column?

we usually check if it is_nullable and then down_cast<NullableColumn>, but it may be a constcolumn, and then down cast lead to `be` crash.
