### PR TITLE
[Bugfix] support splitting chunk into multiple TFetchDataResults to avoid failures of thrift serialization

### LINKED ISSUE #5750: BE crash
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `ssb_100g_supplier` (
  `s_suppkey` int(11) NOT NULL COMMENT "",
  `s_name` varchar(26) NOT NULL COMMENT "",
  `s_address` varchar(26) NOT NULL COMMENT "",
  `s_city` varchar(11) NOT NULL COMMENT "",
  `s_nation` varchar(16) NOT NULL COMMENT "",
  `s_region` varchar(13) NOT NULL COMMENT "",
  `s_phone` varchar(16) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`s_suppkey`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`s_suppkey`) BUCKETS 1
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select   ref_0.s_nation as c0,   ref_0.s_city as c1,   96 as c2,   pi() as c3,   ref_0.s_region as c4,   ref_0.s_city as c5,   ref_0.s_nation as c6,   ref_0.s_region as c7,   ref_0.s_region as c8,   ref_0.s_suppkey as c9,   ref_0.s_city as c10,   case     when ref_0.s_nation = ref_0.s_phone then max(       cast(         case           when true then log(             cast(cast(null as DOUBLE) as DOUBLE),             cast(cast(null as DOUBLE) as DOUBLE)           )           else log(
         cast(cast(null as DOUBLE) as DOUBLE),             cast(cast(null as DOUBLE) as DOUBLE)           )         end as DOUBLE       )     ) over (       partition by ref_0.s_nation,       ref_0.s_phone,       ref_0.s_phone,       ref_0.s_phone,       ref_0.s_phone       order by         ref_0.s_name     )     else max(       cast(         case           when true then log(             cast(cast(null as DOUBLE) as DOUBLE),             cast(cast(null as DOUBLE) as DOUBLE)           )
   else log(             cast(cast(null as DOUBLE) as DOUBLE),             cast(cast(null as DOUBLE) as DOUBLE)           )         end as DOUBLE       )     ) over (       partition by ref_0.s_nation,       ref_0.s_phone,       ref_0.s_phone,       ref_0.s_phone,       ref_0.s_phone       order by         ref_0.s_name     )   end as c11,   ref_0.s_phone as c12,   repeat(     cast(ref_0.s_phone as VARCHAR),     cast(ref_0.s_suppkey as INT)   ) as c13,   ref_0.s_phone as c14,   case     when (
      cast(null as DOUBLE) > cast(         coalesce(           cast(             nullif(               cast(null as DOUBLE),               cast(null as DOUBLE)
      ) as DOUBLE           ),           cast(null as DOUBLE)         ) as DOUBLE       )     )     or (true) then ref_0.s_suppkey     else ref_0.s_suppkey   end as c15,   19 as c16,   rand() as c17,   ref_0.s_name as c18,   ref_0.s_address as c19,   ref_0.s_phone as c20 from  ssb_100g_supplier as ref_0 where   ref_0.s_city <> regexp_replace(     cast(ref_0.s_address as VARCHAR),     cast(       case         when (           (false)           and (ref_0.s_suppkey is not NULL)
 )         and (ref_0.s_region is not NULL) then ref_0.s_name         else ref_0.s_name       end as VARCHAR     ),     cast(ref_0.s_phone as VARCHAR)   );
3. Execute the above SQL multiple times

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
tcmalloc: large alloc 3015540736 bytes == 0x196f0000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 3057025024 bytes == 0xcd4cc000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 3033980928 bytes == 0x1848b4000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 2919645184 bytes == 0x2397a8000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 2989694976 bytes == 0x2e78f0000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 3004448768 bytes == 0x39a42c000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 2978373632 bytes == 0x44d590000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 3057025024 bytes == 0xcd35a000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
tcmalloc: large alloc 2978373632 bytes == 0x39a42c000 @  0x546eeaf 0x570071c 0x1eb469a 0x5650995 0x336a67f 0x30422ac 0x2aeccfc 0x25f56c2 0x261ccbd 0x261365d 0x1f55909 0x1f514ba 0x7f07ce299e65
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1651741420 (unix time) try "date -d @1651741420" if you are using GNU date ***
PC: @     0x7f07cd7ec337 __GI_raise
*** SIGABRT (@0x3e80000720a) received by PID 29194 (TID 0x7f0768137700) from PID 29194; stack trace: ***
    @          0x3c927d2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f07ce2a15f0 (unknown)
    @     0x7f07cd7ec337 __GI_raise
    @     0x7f07cd7eda28 __GI_abort
    @          0x17af44d _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x5650446 __cxxabiv1::__terminate()
    @          0x56504b1 std::terminate()
    @          0x5650604 __cxa_throw
    @          0x17af354 _Znwm.cold
    @          0x1a13f2d std::__cxx11::basic_string<>::_M_mutate()
    @          0x1f28776 starrocks::MysqlRowBuffer::_push_string_normal()
    @          0x3193914 starrocks::MysqlResultWriter::process_chunk()
    @          0x25fbb76 starrocks::pipeline::ResultSinkOperator::push_chunk()
    @          0x261ccbd starrocks::pipeline::PipelineDriver::process()
    @          0x261365d starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x1f55909 starrocks::ThreadPool::dispatch_thread()
    @          0x1f514ba starrocks::Thread::supervise_thread()
    @     0x7f07ce299e65 start_thread
    @     0x7f07cd8b488d __clone
    @                0x0 (unknown)
(END)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 release afbb3bc

### PR DESCRIPTION
**Pull request by silverbullet233**
1. support splitting chunk into multiple TFetchDataResults to avoid failures of thrift serialization;
 
2. try to catch std::bad_alloc in different operators

## What type of PR is this：
- [x] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5750 #5804

## Problem Summary(Required) ：

The direct reason of these coredumps is that the std::bad_alloc exception is not handled in somewhere, so I add some checks in the related logics.

In addition, I also encountered such errors when testing although I set a large enough memory limit:
```
ERROR 1064 (HY000): Couldn't serialize thrift object:
Internal buffer size overflow
```
This is because thrift has a limit on the size of the mem buffer used during serialization. It can be found in `thrift/transport/TBufferTransports.h`

image

In order to avoid serialization failure, I try to split the chunk into multiple TFetchDataResults during `MysqlResultWriter::process_chunk`, make sure that the row buffer of a single TFetchDataResult will not exceed 1GB

### CODE REVIEW

**Comment by silverbullet233** [comment]
@Mergifyio backport branch-2.2

**Comment by kangkaisen** [comment]
please run daily test.

**Comment by kangkaisen** [comment]
Please ensure no performance regression

File: be/src/runtime/statistic_result_writer.cpp [hunk 1]
```diff
@@ -60,13 +60,13 @@ Status StatisticResultWriter::append_chunk(vectorized::Chunk* chunk) {
 
     int version = down_cast<Int32Column*>(ColumnHelper::get_data_column(result_columns[0].get()))->get_data()[0];
 
-    auto* result = new (std::nothrow) TFetchDataResult();
+    std::unique_ptr<TFetchDataResult> result(new (std::nothrow) TFetchDataResult());
```
Comment (mofeiatwork) [inline be/src/runtime/statistic_result_writer.cpp:63]: Do the following code handle the `std::nothrow` strategy

File: be/src/runtime/statistic_result_writer.cpp [hunk 2]
```diff
@@ -79,7 +79,6 @@ Status StatisticResultWriter::append_chunk(vectorized::Chunk* chunk) {
     }
 
     LOG(WARNING) << "Append statistic result to sink failed.";
-    delete result;
```
Comment (mofeiatwork) [inline be/src/runtime/statistic_result_writer.cpp:82]: Is previous code exception-safe? Does all code path release the `result` ?

File: be/src/exec/pipeline/result_sink_operator.h [hunk 3]
```diff
@@ -63,7 +63,7 @@ class ResultSinkOperator final : public Operator {
     std::atomic<int64_t>& _num_written_rows;
 
     std::shared_ptr<ResultWriter> _writer;
-    mutable TFetchDataResultPtr _fetch_data_result;
+    mutable TFetchDataResultPtrs _fetch_data_result;
```
Comment (mofeiatwork) [inline be/src/exec/pipeline/result_sink_operator.h:66]: Why change it to a vector?

File: be/src/runtime/buffer_control_block.cpp [hunk 4]
```diff
@@ -107,19 +107,53 @@ Status BufferControlBlock::add_batch(TFetchDataResult* result) {
...
-        ctx->on_data(result, _packet_num);
-        delete result;
+        ctx->on_data(result.get(), _packet_num);
         _packet_num++;
     }
     return Status::OK();
 }
 
-StatusOr<bool> BufferControlBlock::try_add_batch(TFetchDataResult* result) {
+Status BufferControlBlock::add_batch(std::vector<std::unique_ptr<TFetchDataResult>>& results) {
```
Comment (mofeiatwork) [inline be/src/runtime/buffer_control_block.cpp:121]: Could this method share some code with the other `add_batch` ?

File: be/src/runtime/mysql_result_writer.cpp [hunk 5]
```diff
@@ -116,40 +110,65 @@ StatusOr<TFetchDataResultPtr> MysqlResultWriter::process_chunk(vectorized::Chunk
...
             size_t len = _row_buffer->length();
-            _row_buffer->move_content(&result_rows[i]);
+
+            if (UNLIKELY(current_bytes + len >= max_row_buffer_size)) {
+                result_rows.resize(current_rows);
+                results.emplace_back(std::move(result));
+
+                result = std::make_unique<TFetchDataResult>();
+                result_rows = result->result_batch.rows;
+                result_rows.resize(num_rows - current_rows);
```
Comment (ZiheLiu) [inline be/src/runtime/mysql_result_writer.cpp:135]: Maybe resize to `num_rows-i`? since the number of the rest rows is less than `num_rows - current_rows`.

File: be/src/runtime/mysql_result_writer.h [hunk 6]
```diff
@@ -71,6 +74,8 @@ class MysqlResultWriter final : public ResultWriter {
     RuntimeProfile::Counter* _result_send_timer = nullptr;
     // number of sent rows
     RuntimeProfile::Counter* _sent_rows_counter = nullptr;
+
+    const size_t max_row_buffer_size = 1024 * 1024 * 1024;
```
Comment (ZiheLiu) [inline be/src/runtime/mysql_result_writer.h:78]:
```suggestion
    const size_t _max_row_buffer_size = 1024 * 1024 * 1024;
```

File: be/src/runtime/mysql_result_writer.cpp (hunk 5 above)
Comment (silverbullet233) [reply be/src/runtime/mysql_result_writer.cpp:135]: > Maybe resize to `num_rows-i`? since the number of the rest rows is less than `num_rows - current_rows`.

yes……this is a mistake, I will fix it.

File: be/src/exec/pipeline/result_sink_operator.h (hunk 3 above)
Comment (silverbullet233) [reply be/src/exec/pipeline/result_sink_operator.h:66]: > Why change it to a vector?

before my change,  `MysqlResultWriter::process_chunk` will return only one TFetchDataResultPtr, but now It may return multiple

File: be/src/runtime/statistic_result_writer.cpp (hunk 1 above)
Comment (silverbullet233) [reply be/src/runtime/statistic_result_writer.cpp:63]: > Do the following code handle the `std::nothrow` strategy

I'm afraid it doesn't, so I add a check before use it

File: be/src/runtime/buffer_control_block.cpp (hunk 4 above)
Comment (silverbullet233) [reply be/src/runtime/buffer_control_block.cpp:112]: > Could this method share some code with the other `add_batch` ?

I think it can, I add a new method `_process_batch_without_lock`.

File: be/src/runtime/statistic_result_writer.cpp (hunk 2 above)
Comment (silverbullet233) [reply be/src/runtime/statistic_result_writer.cpp:82]: > Is previous code exception-safe? Does all code path release the `result` ?

In previous logic, `result` will be released if it's added into `_sinker` successfully, otherwise, it should be deleted here. I think using raw pointer is not convenient, so I change it to unique_ptr.

**Comment by silverbullet233** [comment]
@Mergifyio rebase

File: be/src/runtime/buffer_control_block.h [hunk 7]
```diff
@@ -67,9 +67,12 @@ class BufferControlBlock {
     ~BufferControlBlock();
 
     Status init();
-    Status add_batch(TFetchDataResult* result);
+    Status add_batch(std::unique_ptr<TFetchDataResult>& result);
+    Status add_batch(std::vector<std::unique_ptr<TFetchDataResult>>& results);
+
     // non-blocking version of add_batch
-    StatusOr<bool> try_add_batch(TFetchDataResult* result);
+    StatusOr<bool> try_add_batch(std::unique_ptr<TFetchDataResult>& result);
```
Comment (kangkaisen) [inline be/src/runtime/buffer_control_block.h:74]: would better only change `try_add_batch` method for pipeline engine.  needn't change for non-pipeline engine.

Comment (silverbullet233) [reply be/src/runtime/buffer_control_block.h:74]: > would better only change `try_add_batch` method for pipeline engine. needn't change for non-pipeline engine.

I think the serialization issue exists in both pipeline and non-pipeline engine, if we don't change `add_batch`, it can't be avoided in non-pipeline engine.

**Review by kangkaisen — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Comment by silverbullet233** [comment]
@Mergifyio backport branch-2.2
