### PR TITLE
[BugFix] fix storage volume parameters validation

### LINKED ISSUE #46658: [shared-data] clean garbage tablets due to builtin storage volume configuration error
When configuring shared-data with storage volume info in `fe.conf`, if some of the configuration items are misconfigured, it will produce an incorrect builtin storage volume, and FE will use this incorrect storage volume for `_statistics_` system database.

### Expected behavior (Required)
The tables in `_statistics_` database can't be created successfully, those intermittent tablets will be cleaned automatically.

### Real behavior (Required)

Those garbage tablets will not be cleaned at all due to incorrect storage volume used. the `delete_tablet` in BE/CN side will never success and hence the FE won't clean the metadata and keep retry and retry.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

Affects all existing shared-data version, 3.0/3.1/3.2/3.3

### PR DESCRIPTION
**Pull request by kevincai**
## What I'm doing:

Fixes #46658

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.3
  - [X] 3.2
  - [X] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by kevincai** [comment]
In blacklist, will retrigger the ci flow after cleaning up.

**Review by starrocks-xupeng — APPROVED** [review]

**Review by tracymacding — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java [hunk 1]
```diff
@@ -356,14 +352,35 @@ protected List<List<Long>> getBindingsOfBuiltinStorageVolume() {
...
+    private static URI normalizeConfigPath(String uriStr, String defaultScheme, String configNameInErrMsg, boolean matchScheme)
+            throws InvalidConfException {
+        try {
+            URI uri = new URI(uriStr);
+            if (!uri.isAbsolute()) {
+                uri = new URI(defaultScheme + "://" + uriStr);
+            }
+            if (Strings.isNullOrEmpty(uri.getAuthority()) || uri.getPort() != -1) {
+                // no bucket or bucket name contains ':'
+                throw new InvalidConfException("");
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java:364]: no message?

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java:364]: intended, just fallback to the catch block, and rethrow a new InvalidConfException with detailed message.

**Review by wyb — APPROVED** [review]

**Review by imay — APPROVED** [review]
