### PR TITLE
[Enhancement] optimize distinct agg

### LINKED ISSUE #25641: In the case of large data, the performance of distinct operator is very low, can it be optimized?
## Enhancement
In the default configuration, when new_planner_agg_stage = 0, queries fail due to timeout
image

explain:
+------------------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                                 |
+------------------------------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F02)                                                                                                                           |
|   Output Exprs:1: dt | 69: count                                                                                                               |
|   Input Partition: UNPARTITIONED                                                                                                               |
|   RESULT SINK                                                                                                                                  |
|                                                                                                                                                |
|   4:EXCHANGE                                                                                                                                   |
|      cardinality: 1                                                                                                                            |
|                                                                                                                                                |
| PLAN FRAGMENT 1(F01)                                                                                                                           |
|                                                                                                                                                |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                                                     |
|   OutPut Partition: UNPARTITIONED                                                                                                              |
|   OutPut Exchange Id: 04                                                                                                                       |
|                                                                                                                                                |
|   3:AGGREGATE (merge finalize)                                                                                                                 |
|   |  aggregate: multi_distinct_count[([69: count, VARBINARY, false]); args: CHAR; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                                             |
|   |  cardinality: 1                                                                                                                            |
|   |  column statistics:                                                                                                                        |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|   |  * count-->[0.0, 8.085873079E9, 0.0, 8.0, 1.0] ESTIMATE                                                                                    |
|   |                                                                                                                                            |
|   2:EXCHANGE                                                                                                                                   |
|      distribution type: SHUFFLE                                                                                                                |
|      partition exprs: [1: dt, DATE, true]                                                                                                      |
|      cardinality: 1                                                                                                                            |
|                                                                                                                                                |
| PLAN FRAGMENT 2(F00)                                                                                                                           |
|                                                                                                                                                |
|   Input Partition: RANDOM                                                                                                                      |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                                                    |
|   OutPut Exchange Id: 02                                                                                                                       |
|                                                                                                                                                |
|   1:AGGREGATE (update serialize)                                                                                                               |
|   |  STREAMING                                                                                                                                 |
|   |  aggregate: multi_distinct_count[([4: i, VARCHAR, true]); args: CHAR; result: VARBINARY; args nullable: true; result nullable: false]      |
|   |  group by: [1: dt, DATE, true]                                                                                                             |
|   |  cardinality: 1                                                                                                                            |
|   |  column statistics:                                                                                                                        |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|   |  * count-->[0.0, 5647.0, 0.0, 0.27444, 1.0] ESTIMATE                                                                                       |
|   |                                                                                                                                            |
|   0:OlapScanNode                                                                                                                               |
|      table: test01, rollup: test01                                                                                                             |
|      preAggregation: on                                                                                                                        |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                                               |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                                            |
|      actualRows=8085873079, avgRowSize=4.27444                                                                                                 |
|      cardinality: 8085873079                                                                                                                   |
|      column statistics:                                                                                                                        |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                                                   |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                                                |

When executing 'set new_planner_agg_stage = 4;', the query can run successfully, but the performance is still slow.
image

explain:
+----------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F02)                                                                                                       |
|   Output Exprs:1: dt | 69: count                                                                                           |
|   Input Partition: UNPARTITIONED                                                                                           |
|   RESULT SINK                                                                                                              |
|                                                                                                                            |
|   5:EXCHANGE                                                                                                               |
|      cardinality: 1                                                                                                        |
|                                                                                                                            |
| PLAN FRAGMENT 1(F01)                                                                                                       |
|                                                                                                                            |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                                 |
|   OutPut Partition: UNPARTITIONED                                                                                          |
|   OutPut Exchange Id: 05                                                                                                   |
|                                                                                                                            |
|   4:AGGREGATE (update finalize)                                                                                            |
|   |  aggregate: count[([4: i, VARCHAR, true]); args: VARCHAR; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                         |
|   |  cardinality: 1                                                                                                        |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * count-->[0.0, 8.085873079E9, 0.0, 8.0, 1.0] ESTIMATE                                                                |
|   |                                                                                                                        |
|   3:AGGREGATE (merge serialize)                                                                                            |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                  |
|   |  cardinality: 3176                                                                                                     |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |
|   |                                                                                                                        |
|   2:EXCHANGE                                                                                                               |
|      distribution type: SHUFFLE                                                                                            |
|      partition exprs: [1: dt, DATE, true]                                                                                  |
|      cardinality: 3176                                                                                                     |
|                                                                                                                            |
| PLAN FRAGMENT 2(F00)                                                                                                       |
|                                                                                                                            |
|   Input Partition: RANDOM                                                                                                  |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                                |
|   OutPut Exchange Id: 02                                                                                                   |
|                                                                                                                            |
|   1:AGGREGATE (update serialize)                                                                                           |
|   |  STREAMING                                                                                                             |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                  |
|   |  cardinality: 3176                                                                                                     |
|   |  column statistics:                                                                                                    |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |
|   |                                                                                                                        |
|   0:OlapScanNode                                                                                                           |
|      table: test01, rollup: test01                                                                                         |
|      preAggregation: on                                                                                                    |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                           |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                        |
|      actualRows=8085873079, avgRowSize=4.27444                                                                             |
|      cardinality: 8085873079                                                                                               |
|      column statistics:                                                                                                    |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                               |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                            |

After rewriting the DISTINCT, the performance has improved. Here is the code:
image

explain:
+--------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0(F03)                                                                                                     |
|   Output Exprs:1: dt | 69: count                                                                                         |
|   Input Partition: UNPARTITIONED                                                                                         |
|   RESULT SINK                                                                                                            |
|                                                                                                                          |
|   8:EXCHANGE                                                                                                             |
|      cardinality: 1                                                                                                      |
|                                                                                                                          |
| PLAN FRAGMENT 1(F02)                                                                                                     |
|                                                                                                                          |
|   Input Partition: HASH_PARTITIONED: 1: dt                                                                               |
|   OutPut Partition: UNPARTITIONED                                                                                        |
|   OutPut Exchange Id: 08                                                                                                 |
|                                                                                                                          |
|   7:AGGREGATE (merge finalize)                                                                                           |
|   |  aggregate: count[([69: count, BIGINT, false]); args: ; result: BIGINT; args nullable: true; result nullable: false] |
|   |  group by: [1: dt, DATE, true]                                                                                       |
|   |  cardinality: 1                                                                                                      |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * count-->[0.0, 3176.4375, 0.0, 8.0, 1.0] ESTIMATE                                                                  |
|   |                                                                                                                      |
|   6:EXCHANGE                                                                                                             |
|      distribution type: SHUFFLE                                                                                          |
|      partition exprs: [1: dt, DATE, true]                                                                                |
|      cardinality: 1                                                                                                      |
|                                                                                                                          |
| PLAN FRAGMENT 2(F01)                                                                                                     |
|                                                                                                                          |
|   Input Partition: HASH_PARTITIONED: 1: dt, 4: i                                                                         |
|   OutPut Partition: HASH_PARTITIONED: 1: dt                                                                              |
|   OutPut Exchange Id: 06                                                                                                 |
|                                                                                                                          |
|   5:AGGREGATE (update serialize)                                                                                         |
|   |  STREAMING                                                                                                           |
|   |  aggregate: count[(*); args: ; result: BIGINT; args nullable: false; result nullable: false]                         |
|   |  group by: [1: dt, DATE, true]                                                                                       |
|   |  cardinality: 1                                                                                                      |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * count-->[0.0, 3176.4375, 0.0, 8.0, 1.0] ESTIMATE                                                                  |
|   |                                                                                                                      |
|   4:Project                                                                                                              |
|   |  output columns:                                                                                                     |
|   |  1 <-> [1: dt, DATE, true]                                                                                           |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |                                                                                                                      |
|   3:AGGREGATE (merge finalize)                                                                                           |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                          |
|   |                                                                                                                      |
|   2:EXCHANGE                                                                                                             |
|      distribution type: SHUFFLE                                                                                          |
|      partition exprs: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                         |
|      cardinality: 3176                                                                                                   |
|                                                                                                                          |
| PLAN FRAGMENT 3(F00)                                                                                                     |
|                                                                                                                          |
|   Input Partition: RANDOM                                                                                                |
|   OutPut Partition: HASH_PARTITIONED: 1: dt, 4: i                                                                        |
|   OutPut Exchange Id: 02                                                                                                 |
|                                                                                                                          |
|   1:AGGREGATE (update serialize)                                                                                         |
|   |  STREAMING                                                                                                           |
|   |  group by: [1: dt, DATE, true], [4: i, VARCHAR, true]                                                                |
|   |  cardinality: 3176                                                                                                   |
|   |  column statistics:                                                                                                  |
|   |  * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|   |  * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE                                                          |
|   |                                                                                                                      |
|   0:OlapScanNode                                                                                                         |
|      table: test01, rollup: test01                                                                                       |
|      preAggregation: on                                                                                                  |
|      partitionsRatio=5/8, tabletsRatio=5120/5120                                                                         |
|      tabletList=1024918,1024921,1024924,1024927,1024930,1024933,1024936,1024939,1024942,1024945 ...                      |
|      actualRows=8085873079, avgRowSize=4.27444                                                                           |
|      cardinality: 8085873079                                                                                             |
|      column statistics:                                                                                                  |
|      * dt-->[1.686672E9, 1.686672E9, 0.0, 4.0, 1.0] ESTIMATE                                                             |
|      * i-->[-Infinity, Infinity, 0.0, 0.27444, 5647.0] ESTIMATE

### PR DESCRIPTION
**Pull request by packy92**
Fixes #25641

## Problem
According to the problems reported by clients, a similar test was carried out on the development machine, and the results are as follows:
```
mysql>  select count(distinct c2), count(distinct c5), count(*) from skew_agg;
+--------------------+--------------------+----------+
| count(DISTINCT c2) | count(DISTINCT c5) | count(*) |
+--------------------+--------------------+----------+
|                  8 |           30460361 | 39359561 |
+--------------------+--------------------+----------+

mysql>   select count(distinct c1,c5), count(c4) from skew_agg group by c2;
8 rows in set (1 min 22.50 sec)

mysql> select count(*), sum(cnt) from (select c1, c5, c2, count(c4) cnt from skew_agg group by c1, c2,c5) t group by c2;
8 rows in set (10.23 sec)

mysql> explain logical select count(distinct c1,c5), count(c4) from skew_agg group by c2;
+----------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                             |
+----------------------------------------------------------------------------------------------------------------------------+
| - Output => [7:count, 8:count]                                                                                             |
|     - AGGREGATE(GLOBAL) [3:c2] => [7:count, 8:count]                                                                       |
|         - AGGREGATE(DISTINCT_GLOBAL) [2:c1, 3:c2, 6:c5]                                                                    |
|             - EXCHANGE(SHUFFLE) [3]                                                                                  |
|                 - AGGREGATE(LOCAL) [2:c1, 3:c2, 6:c5]                                                                      |
|                     - SCAN [skew_agg] => [2:c1, 3:c2, 6:c5, 9:c4]                                                          |
+----------------------------------------------------------------------------------------------------------------------------+
16 rows in set (0.00 sec)
```
Due to c2 is a low cardinality col, the DISTINCT_GLOBAL aggregation process cannot fully leverage the advantages of parallel computing.
Besides, c5 is a high cardinality col, it leads to a much lower efficiency in the final aggregation result compared to splitting it into two stages.

The Skew hint can solve similar problems in certain scenarios, such as `SELECT COUNT(DISTINCT c5), c2 FROM skew_agg GROUP BY c2`. However, 
it cannot handle distinct multiple cols or select list contains other aggregate functions.

## Main work
This PR optimizes the execution plan of the original three-stage aggregation by modifying the SplitAggregateRule. 
The main modifications are as follows:

1. Set the `partitionByCols` of `DISTINCT_GLOBAL` when necessary. If the cardinality of the original `groupBy keys` is high enough for parallel processing, use the `groupBy keys`; otherwise, use group by `key + distinct columns`. When there are no statistics available, the default is to use group by key + distinct columns.
2. If use grouping keys and distinct cols to distribute data, we need to continue split the final global agg.
3. The new plan may exist `LOCAL` agg with distinct agg func in update phase but other agg func in merge phase, the corresponding properties need to be set correctly in the build fragment phase.

After this PR:
```
mysql>  select count(distinct c1,c5), count(c4) from skew_agg group by c2;
8 rows in set (11.81 sec)

mysql> explain logical select count(distinct c1,c5), count(c4) from skew_agg group by c2;
+------------------------------------------------------------------------------------------------------------------------------------+
| Explain String                                                                                                                     |
+------------------------------------------------------------------------------------------------------------------------------------+
| - Output => [7:count, 8:count]                                                                                                     |
|     - AGGREGATE(GLOBAL) [3:c2] => [7:count, 8:count]                                                                               |
|         - EXCHANGE(SHUFFLE) [3]                                                                                                    |
|             - AGGREGATE(LOCAL) [3:c2]                                                                                              |
|                 - AGGREGATE(DISTINCT_GLOBAL) [2:c1, 3:c2, 6:c5]                                                                    |
|                     - EXCHANGE(SHUFFLE) [2, 3, 6]                                                                                  |
|                         - AGGREGATE(LOCAL) [2:c1, 3:c2, 6:c5]                                                                      |
|                             - SCAN [skew_agg] => [2:c1, 3:c2, 6:c5, 9:c4]                                                          |
+------------------------------------------------------------------------------------------------------------------------------------+
```

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 46 (97.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|2|50.00%|[5568]|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/TypeChecker.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java|28|28|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|8|8|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java [hunk 1]
```diff
@@ -262,7 +265,6 @@ public LogicalAggregationOperator build() {
             Preconditions.checkNotNull(builder.aggregations);
             Preconditions.checkNotNull(builder.groupingKeys);
             Preconditions.checkNotNull(builder.partitionByColumns);
-            builder.isSplit = !builder.type.isGlobal() || builder.isSplit;
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalAggregationOperator.java:265]: why remove the code?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java [hunk 2]
```diff
@@ -152,23 +152,51 @@ private void checkDistinctAgg(List<CallOperator> distinctAggCallOperator) {
...
             return true;
         }
         return false;
     }
 
+
+    // True means good cases for parallel deduplication. It requires group by keys have a relatively high
+    // cardinality (number of distinct value > 1000) to distribute data across multiple cores which helps
+    // parallel deduplication in the distinct global stage.
+    private boolean isSuitableForParallelization(OptExpression input) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: not `number of distinct value > 1000`  which is `deduplication rate``?

`inputRowCount / StatisticsEstimateCoefficient.LOW_AGGREGATE_EFFECT_COEFFICIENT < rowCount` means outputRows/inputRowCount > 1/1000。

**Comment by Seaven** [comment]
we have tree rule to optimize sepecial aggregate, we can move there rule to a special transform rule in CBO，and don't split aggregate node to multi-phase？

`SplitAggregate` is too complex now

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java (hunk 2 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: Yes, just use the exist statistic info to evaluate the deduplication rate.

**Comment by packy92** [comment]
Do you

> we have tree rule to optimize sepecial aggregate, we can move there rule to a special transform rule in CBO，and don't split aggregate node to multi-phase？
> 
> `SplitAggregate` is too complex now

Do you mean use special rules to process different `distinct agg` scenes?

**Comment by Seaven** [comment]
> Do you
> 
> > we have tree rule to optimize sepecial aggregate, we can move there rule to a special transform rule in CBO，and don't split aggregate node to multi-phase？
> > `SplitAggregate` is too complex now
> 
> Do you mean use special rules to process different `distinct agg` scenes?

Yeah, sr has `skew`/`RewriteCountDistinct` logical rule to resolve `distinct agg`, they are depend on special cardinality or cost, and split to multi-agg, it's similar to your optimize. I think we can support a speical rule to resolve it in MEMO, not case by case to handle

**Review by Seaven — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java [hunk 3]
```diff
@@ -5564,6 +5564,10 @@ public ParseNode visitAggregationFunctionCall(StarRocksParser.AggregationFunctio
             isDistinct = context.aggregationFunction().setQuantifier().DISTINCT() != null;
         }
 
+        if (isDistinct && CollectionUtils.isEmpty(context.aggregationFunction().expression())) {
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:5567]: distinct agg func has empty args? can this happen?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java [hunk 4]
```diff
@@ -150,20 +150,24 @@ private void checkFuncCall(Map<ColumnRefOperator, CallOperator> functionCalls) {
...
             for (Map.Entry<ColumnRefOperator, CallOperator> entry : aggregations.entrySet()) {
                 index++;
                 ColumnRefOperator outputCol = entry.getKey();
                 CallOperator aggCall = entry.getValue();
                 boolean isMergeAggFn = false;
-                if (aggType.isGlobal() || (aggType.isLocal() && !isSplit)) {
-                    if (singleDistinctFunctionPos != -1 && index != singleDistinctFunctionPos) {
+                switch (aggType) {
+                    case LOCAL:
+                        isMergeAggFn = isSplit && hasSingleDistinct && (index != singleDistinctFunctionPos);
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java:161]: LOCAL should always be update mode
1.  LOGAL AGG -> RESULT update mode
2.  LOGAL AGG -> AGG-> ... > RESULT update mode
GLOBAL should be merge mode excluding one-phase global agg.
2.  AGG->...> GLOBAL->RESULT  merge mode
3.  Shuffle-> GLOBAL->RESULT update mode
DISTINCT_GLOBAL and DISTINCT_LOCAL  should always be merge mode.
AGG->...->DISTINCT_GLOBAL/DISTINCT_LOCAL->...->  merge mode

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java (hunk 2 above)
Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: the function name is confusing, suggest to use deduplication or parallelDeduplication

**Review by liuyehcf — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java (hunk 2 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: why is this in reference to the concept `deduplication`?

**Comment by liuyehcf** [comment]
> Due to c2 is a low cardinality col, the DISTINCT_GLOBAL aggregation process cannot fully leverage the advantages of parallel computing.

I think the actual reason is data_skew but not cardinality? Both high or low cardinality with skewed can lead to poor performance.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java (hunk 2 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: What about high cardinality but with data skew?

Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: If the cardinality is 128, and without skew, so data can be evenly shuffled. In this situation, this pr may lead to performance reduction?

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java (hunk 3 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:5567]: ```| COUNT '(' (setQuantifier bracketHint?)? (expression (',' expression)*)? ')'```
This lead `count(distinct )` is a valid clause but actually not.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java (hunk 4 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/validate/TypeChecker.java:161]: Because we may split the top global agg into a two phase agg, so local may also has update mode. Like
```
LOCAL -> DSITINCT_GLOBAL -> GLOBAL
```
to
```
LOCAL -> DSITINCT_GLOBAL -> LOCAL -> GLOBAL
```

**Review by liuyehcf — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java (hunk 2 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java:186]: You're right. For scenes like high cardinality but still with data skew`, this pr help nothing. We may need to add other key to scatter the data and split the agg into more phases.
For the performace degradation problem, the new added cost exists two place. One is calculating hash value when exchange data, the other is split the top global agg into two phase agg. The first cost is really small according my test result. The second may lead some degradation when dataset is samller but may gain some profit when dataset is larger because the local streaming agg.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 50 / 50 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/validate/TypeChecker.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/SplitAggregateRule.java|28|28|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|12|12|100.00%|[]|

**Review by satanson — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]
