### PR TITLE
[BugFix] initilize editLog in StarOSBDBJEJournalSystem

### LINKED ISSUE #44832: got exception when replay star mgr journal
### Steps to reproduce the behavior (Required)

1. Use the main branch to build FE
2. start to run SR In shared-data mode
3. do some SQL operation
4. restart FE and check the fe.warn.log.

### Expected behavior (Required)

there is no logs in fe.warn.log

### Real behavior (Required)

```
2024-04-26 00:17:21.299+08:00 ERROR (star mgr LeaderCheckpointer|112) [Checkpoint.replayAndGenerateStarMgrImage():236] Exception when generate new star mgr image file, null.
```

### StarRocks version (Required)
 - main
 - branch-3.3

### PR DESCRIPTION
**Pull request by yandongxiao**
## Why I'm doing:

Got the following error:
```
2024-04-26 00:17:21.299+08:00 ERROR (star mgr LeaderCheckpointer|112) [Checkpoint.replayAndGenerateStarMgrImage():236] Exception when generate new star mgr image file, null.
```

Fixes #44832

## What I'm doing:

1. Fix some error log statement to print stack trace.
2. Initilize editLog field in StarOSBDBJEJournalSystem.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java [hunk 1]
```diff
@@ -233,7 +233,7 @@ private boolean replayAndGenerateStarMgrImage(long logVersion) {
         try {
             return starMgrServer.replayAndGenerateImage(imageDir, logVersion);
         } catch (Exception e) {
-            LOG.error("Exception when generate new star mgr image file, {}.", e.getMessage());
+            LOG.error("Exception when generate new star mgr image file", e);
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java:236]: intend to do the `{}, e.getMessage()` to avoid printing long long stack trace.

File: fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java [hunk 2]
```diff
@@ -185,6 +187,7 @@ public void replayTo(long journalId) throws StarException {
             Util.stdoutWithTime(e.getMessage());
             System.exit(-1);
         } catch (Exception e) {
+            LOG.warn("got exception when replay star mgr journal", e);
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java:190]: it is a replay code path, no need to print the detailed stack trace.

File: fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java [hunk 3]
```diff
@@ -205,7 +208,7 @@ private boolean replayJournal(JournalCursor cursor)
                 break;
             }
 
-            editLog.loadJournal(null /* GlobalStateMgr */, entity);
+            editLog.loadJournal(GlobalStateMgr.getCurrentState(), entity);
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java:211]: check where does the `replayTo` called, I remember it used in two places 1. leader restart, replay the journal before serving. 2. leader creates a new image in checkpoint thread.

In the second case, `GlobalStateMgr.getCurrentState()` may be not correct.

**Review by HangyuanLiu — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java (hunk 2 above)
Comment (yandongxiao) [reply fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java:190]: When I encountered this issue, there was little useful information in fe.warn.log, with only a null present. This is not conducive to troubleshooting the problem.

File: fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java (hunk 1 above)
Comment (yandongxiao) [reply fe/fe-core/src/main/java/com/starrocks/leader/Checkpoint.java:236]: When I encountered this issue, there was little useful information in fe.warn.log, with only a null present. This is not conducive to troubleshooting the problem.

File: fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java (hunk 2 above)
Comment (yandongxiao) [reply fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java:190]: Additionally, due to the fact that StarException in `throw new StarException(ExceptionCode.JOURNAL, e.getMessage());` does not support passing the `e` type as a parameter, this leads to incomplete stack trace information. This is also the reason for the proactive invocation of `LOG.warn`.

File: fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java (hunk 3 above)
Comment (yandongxiao) [reply fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java:211]: In `editLog.loadJournal`, Only the following branch will be executed. So it is ok to pass null or GlobalStateMgr.getCurrentState().

```
                case OperationType.OP_STARMGR: {
                    StarMgrJournal j = (StarMgrJournal) journal.getData();
                    StarMgrServer.getCurrentState().getStarMgr().replay(j.getJournal());
                    break;
                }
```

In the `GlobalStateMgr.getCurrentState()`, we can safely get an instance.

To ensure safety, I think I'd better reset it to null value.

Comment (yandongxiao) [reply fe/fe-core/src/main/java/com/starrocks/staros/StarOSBDBJEJournalSystem.java]: done

**Review by kevincai — APPROVED** [review]
introduced in PR #43093

**Review by HangyuanLiu — APPROVED** [review]
