### PR TITLE
[BugFix] With a high streamload frequency and too many tablets involved, TabletCommitInfos will take up too much memory.

### LINKED ISSUE #53330: [BugFix] With a high streamload frequency and too many tablets involved, TabletCommitInfos will take up too much memory.
### Steps to reproduce the behavior (Required)
企业微信截图_17327821561040
Upgrading from 3.1.2 to 3.1.15, the memory grows too fast.
### Expected behavior (Required)
Before the upgrade, the FE's memory was stable at 2G
### Real behavior (Required)
label_clean_interval_second=3600*4: Memory grew to 80G.
label_clean_interval_second=3600: Memory grows to 20G.
label_clean_interval_second=1200: memory grows to 7G.
### StarRocks version (Required)
3.1.2

### PR DESCRIPTION
**Pull request by zhangheihei**
## Why I'm doing:
Upgrading from 3.1.2 to 3.1.15, the memory grows too fast.
Version 3.1.2 memory didn't grow too fast because of [35115](https://github.com/StarRocks/starrocks/pull/35115) refactoring here.
dump info:
Clipboard_Screenshot_1732785322
企业微信截图_4fe6b993-d882-4695-bf36-b232d3856a8f
企业微信截图_dd7af068-781e-43fb-a5c8-5f4f51bd0528

## What I'm doing:
Fixes #53330

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by trueeyu — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -1177,6 +1177,7 @@ public void finishTransaction(long transactionId, Set<Long> errorReplicaIds) thr
                     transactionState.clearErrorMsg();
                     transactionState.setTransactionStatus(TransactionStatus.VISIBLE);
                     unprotectUpsertTransactionState(transactionState, false);
+                    transactionState.resetTabletCommitInfos();
```
Comment (luohaha) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:1180]: You can't clean it now. In `applyVisibleLog` , we still need `tabletCommitInfos`, you can move it to `applyVisibleLog`

Comment (luohaha) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:1180]: You can reset it now, after that in `applyVisibleLog`, we still need `tabletCommitInfos`, you can move it to `applyVisibleLog`.

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java]: tks reveiw.

**Review by luohaha — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify rebbase

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Review by gengjun-git — APPROVED** [review]
