### PR TITLE
[Enhancement] Refine profile to support visualization refactor(4)

### LINKED ISSUE #31558: [Bug] Wrong statistics of BytesUnsent
```
EXCHANGE_SINK (plan_node_id=2):
          CommonMetrics:
             - CloseTime: 500ns
               - __MAX_OF_CloseTime: 7.181us
               - __MIN_OF_CloseTime: 132ns
             - OperatorAllocatedMemoryUsage: 432.148 GB
               - __MAX_OF_OperatorAllocatedMemoryUsage: 931.708 MB
               - __MIN_OF_OperatorAllocatedMemoryUsage: 907.698 MB
             - OperatorDeallocatedMemoryUsage: 269.998 GB
               - __MAX_OF_OperatorDeallocatedMemoryUsage: 693.135 MB
               - __MIN_OF_OperatorDeallocatedMemoryUsage: 451.836 MB
             - OperatorPeakMemoryUsage: 345.927 MB
               - __MAX_OF_OperatorPeakMemoryUsage: 475.806 MB
               - __MIN_OF_OperatorPeakMemoryUsage: 224.035 MB
             - OperatorTotalTime: 5s320ms
               - __MAX_OF_OperatorTotalTime: 5s947ms
               - __MIN_OF_OperatorTotalTime: 4s818ms
             - PrepareTime: 51.287us
               - __MAX_OF_PrepareTime: 94.514us
               - __MIN_OF_PrepareTime: 36.622us
             - PullChunkNum: 0
             - PullRowNum: 0
             - PullTotalTime: 0ns
             - PushChunkNum: 1.103M (1103145)
               - __MAX_OF_PushChunkNum: 2.329K (2329)
               - __MIN_OF_PushChunkNum: 2.264K (2264)
             - PushRowNum: 4.509B (4509033509)
               - __MAX_OF_PushRowNum: 9.526M (9525873)
               - __MIN_OF_PushRowNum: 9.251M (9250922)
             - PushTotalTime: 5s64ms
               - __MAX_OF_PushTotalTime: 5s635ms
               - __MIN_OF_PushTotalTime: 4s582ms
             - SetFinishedTime: 98ns
               - __MAX_OF_SetFinishedTime: 607ns
               - __MIN_OF_SetFinishedTime: 24ns
             - SetFinishingTime: 255.851ms
               - __MAX_OF_SetFinishingTime: 345.012ms
               - __MIN_OF_SetFinishingTime: 191.577ms
          UniqueMetrics:
             - ChannelNum: 20
             - DestFragments: 55f4b67f55e011ee-8acf0af38bb648ce, 55f4b67f55e011ee-8acf0af38bb648cf, 55f4b67f55e011ee-8acf0af38bb648d0, 55f4b67f55e011ee-8acf0af38bb648d1, 55f4b67f55e011ee-8acf0af38bb648d2, 55f4b67f55e011ee-8acf0af38bb648d3, 55f4b67f55e011ee-8acf0af38bb648d4, 55f4b67f55e011ee-8acf0af38bb648d5, 55f4b67f55e011ee-8acf0af38bb648d6, 55f4b67f55e011ee-8acf0af38bb648d7, 55f4b67f55e011ee-8acf0af38bb648d8, 55f4b67f55e011ee-8acf0af38bb648d9, 55f4b67f55e011ee-8acf0af38bb648da, 55f4b67f55e011ee-8acf0af38bb648db, 55f4b67f55e011ee-8acf0af38bb648dc, 55f4b67f55e011ee-8acf0af38bb648dd, 55f4b67f55e011ee-8acf0af38bb648de, 55f4b67f55e011ee-8acf0af38bb648df, 55f4b67f55e011ee-8acf0af38bb648e0, 55f4b67f55e011ee-8acf0af38bb648e1
             - DestID: 2
             - PartType: HASH_PARTITIONED
             - PipelineLevelShuffle: Yes
             - ShuffleNumPerChannel: 24
             - TotalShuffleNum: 480
             - BytesPassThrough: 9.596 GB
               - __MAX_OF_BytesPassThrough: 20.860 MB
               - __MIN_OF_BytesPassThrough: 20.041 MB
             - BytesSent: 95.711 GB
               - __MAX_OF_BytesSent: 4.835 GB
               - __MIN_OF_BytesSent: 4.726 GB
             - BytesUnsent: 4.951 GB
               - __MAX_OF_BytesUnsent: 578.287 MB
               - __MIN_OF_BytesUnsent: 1020.541 KB
             - CompressTime: 0ns
             - NetworkBandwidth: 2.302 TB/sec
               - __MAX_OF_NetworkBandwidth: 243.591 GB/sec
               - __MIN_OF_NetworkBandwidth: 7.840 GB/sec
             - NetworkTime: 184.794ms
               - __MAX_OF_NetworkTime: 607.521ms
               - __MIN_OF_NetworkTime: 19.756ms
             - OverallThroughput: 3.882 GB/sec
               - __MAX_OF_OverallThroughput: 204.659 MB/sec
               - __MIN_OF_OverallThroughput: 190.966 MB/sec
             - OverallTime: 24s664ms
               - __MAX_OF_OverallTime: 25s596ms
               - __MIN_OF_OverallTime: 24s142ms
             - RequestSent: 350.030K (350030)
               - __MAX_OF_RequestSent: 17.681K (17681)
               - __MIN_OF_RequestSent: 17.357K (17357)
             - RequestUnsent: 18.216K (18216)
               - __MAX_OF_RequestUnsent: 2.086K (2086)
               - __MIN_OF_RequestUnsent: 11
             - RpcAvgTime: 976.151us
               - __MAX_OF_RpcAvgTime: 1.427ms
               - __MIN_OF_RpcAvgTime: 794.308us
             - RpcCount: 378.549K (378549)
               - __MAX_OF_RpcCount: 19.128K (19128)
               - __MIN_OF_RpcCount: 18.757K (18757)
             - SerializeChunkTime: 1s298ms
               - __MAX_OF_SerializeChunkTime: 1s557ms
               - __MIN_OF_SerializeChunkTime: 1s194ms
             - ShuffleHashTime: 339.115ms
               - __MAX_OF_ShuffleHashTime: 468.048ms
               - __MIN_OF_ShuffleHashTime: 268.847ms
             - UncompressedBytes: 95.711 GB
               - __MAX_OF_UncompressedBytes: 207.317 MB
               - __MIN_OF_UncompressedBytes: 200.857 MB
             - WaitTime: 19s783ms
               - __MAX_OF_WaitTime: 20s798ms
               - __MIN_OF_WaitTime: 18s881ms
```

```
EXCHANGE_SOURCE (plan_node_id=2):
          CommonMetrics:
             - CloseTime: 799ns
               - __MAX_OF_CloseTime: 3.166us
               - __MIN_OF_CloseTime: 239ns
             - JoinRuntimeFilterEvaluate: 0
             - JoinRuntimeFilterHashTime: 0ns
             - JoinRuntimeFilterInputRows: 0
             - JoinRuntimeFilterOutputRows: 0
             - JoinRuntimeFilterTime: 0ns
             - OperatorAllocatedMemoryUsage: 271.038 GB
               - __MAX_OF_OperatorAllocatedMemoryUsage: 646.475 MB
               - __MIN_OF_OperatorAllocatedMemoryUsage: 545.365 MB
             - OperatorDeallocatedMemoryUsage: 284.233 GB
               - __MAX_OF_OperatorDeallocatedMemoryUsage: 894.644 MB
               - __MIN_OF_OperatorDeallocatedMemoryUsage: 425.764 MB
             - OperatorPeakMemoryUsage: 7.348 MB
               - __MAX_OF_OperatorPeakMemoryUsage: 214.418 MB
               - __MIN_OF_OperatorPeakMemoryUsage: 0.000 B
             - OperatorTotalTime: 309.433ms
               - __MAX_OF_OperatorTotalTime: 382.553ms
               - __MIN_OF_OperatorTotalTime: 274.698ms
             - PrepareTime: 21.378us
               - __MAX_OF_PrepareTime: 394.949us
               - __MIN_OF_PrepareTime: 4.398us
             - PullChunkNum: 1.160M (1160022)
               - __MAX_OF_PullChunkNum: 2.880K (2880)
               - __MIN_OF_PullChunkNum: 2.400K (2400)
             - PullRowNum: 4.509B (4509033509)
               - __MAX_OF_PullRowNum: 10.412M (10411761)
               - __MIN_OF_PullRowNum: 8.875M (8874952)
             - PullTotalTime: 309.423ms
               - __MAX_OF_PullTotalTime: 382.547ms
               - __MIN_OF_PullTotalTime: 274.692ms
             - PushChunkNum: 0
             - PushRowNum: 0
             - PushTotalTime: 0ns
             - RuntimeBloomFilterNum: 0
             - RuntimeInFilterNum: 0
             - SetFinishedTime: 138ns
               - __MAX_OF_SetFinishedTime: 481ns
               - __MIN_OF_SetFinishedTime: 26ns
             - SetFinishingTime: 8.473us
               - __MAX_OF_SetFinishingTime: 91.275us
               - __MIN_OF_SetFinishingTime: 676ns
          UniqueMetrics:
             - BufferUnplugCount: 1.155K (1155)
               - __MAX_OF_BufferUnplugCount: 111
               - __MIN_OF_BufferUnplugCount: 31
             - BytesPassThrough: 9.596 GB
               - __MAX_OF_BytesPassThrough: 498.201 MB
               - __MIN_OF_BytesPassThrough: 483.410 MB
             - BytesReceived: 95.711 GB
               - __MAX_OF_BytesReceived: 4.815 GB
               - __MIN_OF_BytesReceived: 4.741 GB
             - ClosureBlockCount: 359.818K (359818)
               - __MAX_OF_ClosureBlockCount: 18.419K (18419)
               - __MIN_OF_ClosureBlockCount: 17.231K (17231)
             - ClosureBlockTime: 4h35m
               - __MAX_OF_ClosureBlockTime: 5h44m
               - __MIN_OF_ClosureBlockTime: 2h50m
             - DecompressChunkTime: 0ns
             - DeserializeChunkTime: 6s152ms
               - __MAX_OF_DeserializeChunkTime: 6s289ms
               - __MIN_OF_DeserializeChunkTime: 5s914ms
             - PeakBufferMemoryBytes: 6.438 GB
               - __MAX_OF_PeakBufferMemoryBytes: 390.208 MB
               - __MIN_OF_PeakBufferMemoryBytes: 250.404 MB
             - ReceiverProcessTotalTime: 1s405ms
               - __MAX_OF_ReceiverProcessTotalTime: 1s484ms
               - __MIN_OF_ReceiverProcessTotalTime: 1s307ms
             - RequestReceived: 378.341K (378341)
               - __MAX_OF_RequestReceived: 19.178K (19178)
               - __MIN_OF_RequestReceived: 18.754K (18754)
             - SenderTotalTime: 1s402ms
               - __MAX_OF_SenderTotalTime: 1s480ms
               - __MIN_OF_SenderTotalTime: 1s304ms
             - SenderWaitLockTime: 110ns
               - __MAX_OF_SenderWaitLockTime: 192ns
               - __MIN_OF_SenderWaitLockTime: 65ns
```

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by liuyehcf**
This pr is an continuation work of #29063, #30381 and #30975, and the main objectives of this pr are:

1. Using groups of metrics that each group will attach to individual ExchangeSourceOperator, so the time, like `DecompressChunkTime` and `DeserializeChunkTime`, can be treated as wall time after thir pr instead of cumulative time.
2. Support MV lables for `HitMaterializedViews` in text-based profile analysis.
3. Adjust the output numbers of ExchangeNode working in `broadcast` mode.
4. Add `ShuffleChunkAppendTime`
5. Fix the bug for metrics `BytesUnsent` and `RequestUnsent`(Fixes https://github.com/StarRocks/starrocks/issues/31558), this issue is introduced by runtime profiling, when the query is still under processing, there may be some requests in the sender's buffer, so the metrics `BytesUnsent` and `RequestUnsent` is updated. But when the query is finished, the sender's buffer is emtpy, and it won't update the metrics `BytesUnsent` and `RequestUnsent`, so the final profile will show the previous value, which lead to the problem.
6. Text-baed profile will show the subordinatory operators.

## Result

3be,1fe tpch-1g,

```sql
explain analyze select * from lineitem a join lineitem b on a.L_ORDERKEY=b.L_ORDERKEY;
```

Before this pr:

```
          UniqueMetrics:
             - BufferUnplugCount: 1
             - BytesPassThrough: 2.099 GB
             - BytesReceived: 1.710 GB
             - ClosureBlockCount: 5.367K (5367)
             - ClosureBlockTime: 1h11m
             - DecompressChunkTime: 0ns
             - DeserializeChunkTime: 1s435ms
             - PeakBufferMemoryBytes: 337.983 MB
             - ReceiverProcessTotalTime: 376.063ms
             - RequestReceived: 7.230K (7230)
             - SenderTotalTime: 374.950ms
             - SenderWaitLockTime: 182ns
```

After this pr:

```
            UniqueMetrics:
             - BufferUnplugCount: 1
               - __MAX_OF_BufferUnplugCount: 1
               - __MIN_OF_BufferUnplugCount: 0
             - BytesPassThrough: 2.099 GB
               - __MAX_OF_BytesPassThrough: 323.068 MB
               - __MIN_OF_BytesPassThrough: 210.815 MB
             - BytesReceived: 1.710 GB
               - __MAX_OF_BytesReceived: 221.580 MB
               - __MIN_OF_BytesReceived: 214.748 MB
             - ClosureBlockCount: 5.371K (5371)
               - __MAX_OF_ClosureBlockCount: 676
               - __MIN_OF_ClosureBlockCount: 665
             - ClosureBlockTime: 6m31s
               - __MAX_OF_ClosureBlockTime: 7m39s
               - __MIN_OF_ClosureBlockTime: 5m27s
             - DecompressChunkTime: 0ns
             - DeserializeChunkTime: 175.463ms
               - __MAX_OF_DeserializeChunkTime: 181.618ms
               - __MIN_OF_DeserializeChunkTime: 168.038ms
             - PeakBufferMemoryBytes: 499.565 MB
               - __MAX_OF_PeakBufferMemoryBytes: 100.848 MB
               - __MIN_OF_PeakBufferMemoryBytes: 7.883 MB
             - ReceiverProcessTotalTime: 47.307ms
               - __MAX_OF_ReceiverProcessTotalTime: 49.546ms
               - __MIN_OF_ReceiverProcessTotalTime: 45.226ms
             - RequestReceived: 7.239K (7239)
               - __MAX_OF_RequestReceived: 905
               - __MIN_OF_RequestReceived: 904
             - SenderTotalTime: 47.138ms
               - __MAX_OF_SenderTotalTime: 49.343ms
               - __MIN_OF_SenderTotalTime: 45.070ms
             - SenderWaitLockTime: 12ns
               - __MAX_OF_SenderWaitLockTime: 100ns
               - __MIN_OF_SenderWaitLockTime: 0ns
```

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|6|00.00%|[276, 277, 278, 279, 280, 281]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|6|00.00%|[276, 277, 278, 279, 280, 281]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 30 / 42 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|27|39|69.23%|[201, 218, 258, 259, 260, 261, 262, 263, 266, 830, 834, 845]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|6|00.00%|[276, 277, 278, 279, 280, 281]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 30 / 42 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|27|39|69.23%|[201, 218, 258, 259, 260, 261, 262, 263, 266, 830, 834, 845]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|6|00.00%|[276, 277, 278, 279, 280, 281]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 30 / 42 (71.43%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|27|39|69.23%|[201, 218, 258, 259, 260, 261, 262, 263, 266, 830, 834, 845]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 6 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|6|00.00%|[276, 277, 278, 279, 280, 281]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 96 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 99 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 90 / 105 (85.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|87|102|85.29%|[216, 233, 252, 275, 276, 277, 278, 280, 281, 284, 687, 689, 691, 693, 909]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 9 / 119 (07.56%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|6|116|05.17%|[70, 192, 218, 235, 252, 254, 257, 261, 262, 264, 265, 266, 267, 268, 275, 276, 277, 278, 279, 280, 282, 283, 286, 296, 297, 298, 299, 300, 301, 302, 303, 305, 306, 307, 309, 310, 636, 638, 660, 692, 694, 706, 708, 710, 712, 735, 736, 737, 739, 740, 741, 742, 743, 744, 745, 747, 748, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 761, 763, 764, 765, 766, 767, 770, 771, 772, 773, 908, 909, 910, 912, 913, 915, 916, 917, 919, 920, 921, 923, 924, 926, 928, 934, 935, 937, 982, 983, 984, 986, 987, 989, 990, 1141, 1197, 1202, 1207, 1221, 1223, 1259, 1286]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 73 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|2|00.00%|[27, 28]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|1|00.00%|[30]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|20|00.00%|[67, 92, 178, 183, 198, 199, 201, 202, 204, 206, 207, 209, 210, 211, 215, 216, 217, 246, 247, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 61, 62]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|2|00.00%|[203, 204]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|37|00.00%|[98, 101, 109, 118, 203, 214, 226, 231, 285, 312, 403, 406, 442, 467, 476, 496, 506, 512, 522, 524, 554, 568, 577, 585, 597, 605, 637, 657, 669, 681, 682, 683, 713, 766, 782, 805, 833]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 73 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|2|00.00%|[27, 28]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|1|00.00%|[30]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|20|00.00%|[67, 92, 178, 183, 198, 199, 201, 202, 204, 206, 207, 209, 210, 211, 215, 216, 217, 246, 247, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 61, 62]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|2|00.00%|[203, 204]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|37|00.00%|[98, 101, 109, 118, 203, 214, 226, 231, 285, 312, 403, 406, 442, 467, 476, 496, 506, 512, 522, 524, 554, 568, 577, 585, 597, 605, 637, 657, 669, 681, 682, 683, 713, 766, 782, 805, 833]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:disappointed: **fail** : 0 / 119 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|0|3|00.00%|[97, 143, 144]|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|0|116|00.00%|[70, 115, 116, 117, 118, 121, 125, 192, 218, 235, 252, 254, 257, 261, 262, 264, 265, 266, 267, 268, 275, 276, 277, 278, 279, 280, 282, 283, 286, 296, 297, 298, 299, 300, 301, 302, 303, 305, 306, 307, 309, 310, 636, 638, 660, 692, 694, 706, 708, 710, 712, 735, 736, 737, 739, 740, 741, 742, 743, 744, 745, 747, 748, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 761, 763, 764, 765, 766, 767, 770, 771, 772, 773, 908, 909, 910, 912, 913, 915, 916, 917, 919, 920, 921, 923, 924, 926, 928, 934, 935, 937, 982, 983, 984, 986, 987, 989, 990, 1141, 1197, 1202, 1207, 1221, 1223, 1259, 1286]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 109 / 124 (87.90%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|106|121|87.60%|[219, 236, 255, 278, 279, 280, 281, 283, 284, 287, 715, 717, 719, 721, 937]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|29|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 244, 245, 246, 247, 253, 255]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|3|00.00%|[204, 205, 451]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|

File: be/src/exec/pipeline/exchange/exchange_sink_operator.cpp [hunk 1]
```diff
@@ -200,7 +200,10 @@ Status ExchangeSinkOperator::Channel::add_rows_selective(Chunk* chunk, int32_t d
         _chunks[driver_sequence]->set_num_rows(0);
     }
 
-    _chunks[driver_sequence]->append_selective(*chunk, indexes, from, size);
+    {
+        SCOPED_TIMER(_parent->_shuffle_chunk_append_timer);
```
Comment (LiShuMing) [inline be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:204]: Can add a counter to calculate call the  `add_rows_selective ` times?

File: be/src/exec/pipeline/exchange/sink_buffer.cpp [hunk 2]
```diff
@@ -157,12 +157,10 @@ void SinkBuffer::update_profile(RuntimeProfile* profile) {
...
-    if (_bytes_enqueued - _bytes_sent > 0) {
-        auto* bytes_unsent_counter = ADD_COUNTER(profile, "BytesUnsent", TUnit::BYTES);
-        auto* request_unsent_counter = ADD_COUNTER(profile, "RequestUnsent", TUnit::UNIT);
-        COUNTER_SET(bytes_unsent_counter, _bytes_enqueued - _bytes_sent);
-        COUNTER_SET(request_unsent_counter, _request_enqueued - _request_sent);
-    }
+    auto* bytes_unsent_counter = ADD_COUNTER(profile, "BytesUnsent", TUnit::BYTES);
+    auto* request_unsent_counter = ADD_COUNTER(profile, "RequestUnsent", TUnit::UNIT);
+    COUNTER_SET(bytes_unsent_counter, _bytes_enqueued - _bytes_sent);
+    COUNTER_SET(request_unsent_counter, _request_enqueued - _request_sent);
```
Comment (fzhedu) [inline be/src/exec/pipeline/exchange/sink_buffer.cpp:163]: would them < 0?

File: be/src/runtime/data_stream_recvr.h [hunk 3]
```diff
@@ -158,6 +157,9 @@ class DataStreamRecvr {
     // total buffer limit.
     bool exceeds_limit(int chunk_size) { return _num_buffered_bytes + chunk_size > _total_buffer_limit; }
 
+    // Return a metrics for current rpc in round-robin manner.
+    Metrics& get_metrics_round_robin() { return _metrics[_rpc_round_roubin_index++ % _metrics.size()]; }
```
Comment (fzhedu) [inline be/src/runtime/data_stream_recvr.h:161]: should it overflow so get negative value, resulting crash.

**Review by fzhedu — COMMENTED** [review]
when upgrading or downgrading, the profile works ok?

**Review by satanson — DISMISSED** [review]

File: be/src/runtime/data_stream_recvr.h (hunk 3 above)
Comment (liuyehcf) [reply be/src/runtime/data_stream_recvr.h:161]: `-1 % 5` is `-1`, I thought it woud be `1`. I'll update.

File: be/src/exec/pipeline/exchange/sink_buffer.cpp (hunk 2 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/exchange/sink_buffer.cpp:163]: Not possible, if it has, then it's a bug.

**Comment by liuyehcf** [comment]
> when upgrading or downgrading, the profile works ok?

If some nodes are upgraded and others remain unchanged, then metrics like `DeserializeChunkTime` with different meaning may merge together.

And I don't think we should add compatible code to handle this. it's acceptable to me.

File: be/src/exec/pipeline/exchange/exchange_sink_operator.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:204]: added

File: be/src/runtime/data_stream_recvr.cpp [hunk 4]
```diff
@@ -237,17 +241,18 @@ Status DataStreamRecvr::add_chunks(const PTransmitChunkParams& request, ::google
     MemTracker* prev_tracker = tls_thread_status.set_mem_tracker(_instance_mem_tracker.get());
     DeferOp op([&] { tls_thread_status.set_mem_tracker(prev_tracker); });
 
-    SCOPED_TIMER(_process_total_timer);
-    SCOPED_TIMER(_sender_total_timer);
-    COUNTER_UPDATE(_request_received_counter, 1);
+    auto& metrics = get_metrics_round_robin();
+    SCOPED_TIMER(metrics.process_total_timer);
+    SCOPED_TIMER(metrics.sender_total_timer);
```
Comment (silverbullet233) [inline be/src/runtime/data_stream_recvr.cpp:246]: can we remove one of these two timers? it seems that these two values are always same

Comment (liuyehcf) [reply be/src/runtime/data_stream_recvr.cpp:246]: yes, I'll remove sender_total_timer.

**Review by silverbullet233 — APPROVED** [review]

**Review by fzhedu — APPROVED** [review]

File: be/src/runtime/data_stream_recvr.h (hunk 3 above)
Comment (liuyehcf) [reply be/src/runtime/data_stream_recvr.h:161]: I've changed the type of _rpc_round_roubin_index from `int32_t` to `size_t`

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]

:heart_eyes: **pass** : 109 / 124 (87.90%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ExplainAnalyzer.java|106|121|87.60%|[219, 236, 255, 278, 279, 280, 281, 283, 284, 287, 715, 717, 719, 721, 937]|
|:large_blue_circle:|com/starrocks/common/util/ProfilingExecPlan.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]

:disappointed: **fail** : 0 / 103 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_parallel_merge_source_operator.cpp|0|4|00.00%|[27, 28, 86, 91]|
|:large_blue_circle:|src/exec/exchange_node.cpp|0|3|00.00%|[89, 90, 102]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_merge_sort_source_operator.cpp|0|2|00.00%|[30, 31]|
|:large_blue_circle:|src/exec/pipeline/exchange/sink_buffer.cpp|0|4|00.00%|[160, 161, 162, 163]|
|:large_blue_circle:|src/runtime/data_stream_recvr.cpp|0|27|00.00%|[67, 92, 178, 183, 190, 198, 199, 200, 201, 202, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 243, 244, 245, 251, 253]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_source_operator.cpp|0|4|00.00%|[26, 27, 54, 61]|
|:large_blue_circle:|src/runtime/data_stream_mgr.cpp|0|1|00.00%|[68]|
|:large_blue_circle:|src/exec/pipeline/exchange/exchange_sink_operator.cpp|0|5|00.00%|[204, 205, 206, 452, 453]|
|:large_blue_circle:|src/runtime/sender_queue.cpp|0|52|00.00%|[98, 101, 109, 118, 152, 159, 203, 207, 214, 216, 222, 226, 231, 271, 285, 290, 312, 323, 403, 406, 442, 458, 467, 476, 496, 506, 512, 516, 518, 524, 554, 562, 568, 577, 585, 597, 605, 646, 657, 669, 678, 683, 693, 713, 739, 766, 782, 791, 799, 805, 819, 833]|
|:large_blue_circle:|src/runtime/data_stream_recvr.h|0|1|00.00%|[161]|
