### PR TITLE
Fix end of file reached before reading fully for csv scanner and only process scan range with offset 0

### LINKED ISSUE #2668: Query from hive external table with CSV format return error
### Steps to reproduce the behavior (Required)
1. create hive table and insert:
 ```
create table hive_hdfs_csv(
  col_tinyint tinyint comment "column tinyint"
 ,col_smallint smallint comment "column smallint"
 ,col_int int comment "column int"
 ,col_integer integer comment "column integer"
 ,col_bigint bigint comment "column bigint"
 ,col_float float comment "column float"
 ,col_double double comment "column double"
 ,col_double_precision double precision comment "column double precision"
 ,col_decimal decimal comment "column decimal"
 ,col_timestamp timestamp comment "column timestamp"
 ,col_date date comment "column date"
 ,col_string string comment "column string"
 ,col_varchar varchar(100) comment "column varchar"
 ,col_binary binary comment "column binary"
 ,col_char char(100) comment "column char"
 ,col_boolean boolean comment "column boolean"
 ,col_array array<int> comment "column array"
 )
 clustered by(col_int) sorted by(col_int) into 32 buckets
 row format delimited fields terminated by ','
 stored as textfile;
 insert into hive_hdfs_csv select 1,1,1,1,1,1.001,10.1,110.1,1110.1,'2021-10-30 12:10:23','2021-10-30','hello world','hi hello','1110001010101011001001','nihao',true,array(1,10,100);
 insert into hive_hdfs_csv select 2,2,2,2,2,2.001,20.1,210.1,2110.2,'2021-02-01 12:10:23','2021-02-01','hello world','hi hello','1110001010101011001001','nihao',true,array(2,20,200);
```

2. create hive external table in starrocks cluster:
```
create external table ex_hive_tbl0 (
col_tinyint tinyint null)
ENGINE=hive
properties ("resource" = "hive_resource_1637373685679","table" = "hive_hdfs_csv","database" = "tn_test");
```

3. select from hive external table:
```
mysql> select * from ex_hive_tbl0;
ERROR 1064 (HY000): fail to hdfsPreadFully file, file=hdfs://172.26.92.141:9002/user/hive/warehouse/tn_test.db/hive_hdfs_csv/000010_0_copy_9, error=error=Error(255): Unknown error 255, root_cause=EOFException: End of file reached before reading fully.
```

### Expected behavior (Required)
query return the right result

### Real behavior (Required)
query return error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER e57b900 |
+------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by caneGuy**
close #2668 
we should not use hdfsPreadFully for CSV scanner since it will always return error below
```
WARN (starrocks-mysql-nio-pool-0|136) [Coordinator.getNext():748] query failed: fail to hdfsPreadFully file, file=hdfs://emr-header-1.cluster-259859:9000/user/hive/warehouse/countries_list_yuzhou/000000_0, error=error=Error(255): Unknown error 255, root_cause=EOFException: End of file reached before reading fully.
```
by the way, we should only process scan range with offset 0 for text file.
we can also send scan range to be used getSplits of input format later

### CODE REVIEW

**Comment by caneGuy** [comment]
@imay @dirtysalt could you help review this? thanks

File: be/src/exec/vectorized/hdfs_scanner_text.cpp [hunk 1]
```diff
@@ -64,6 +73,10 @@ void HdfsTextScanner::do_close(RuntimeState* runtime_state) noexcept {
 }
 
 Status HdfsTextScanner::do_get_next(RuntimeState* runtime_state, ChunkPtr* chunk) {
+    if (_scanner_params.scan_ranges[0]->offset != 0) {
```
Comment (dirtysalt) [inline be/src/exec/vectorized/hdfs_scanner_text.cpp:76]: If we require `offset = 0`, then we may lose capabilty of reading csv file in chunks, right?

Comment (caneGuy) [reply be/src/exec/vectorized/hdfs_scanner_text.cpp]: yes , i have changed the implementation. skip first record for all the scan range which has non-zero offset value.

**Review by dirtysalt — DISMISSED** [review]

File: be/src/exec/vectorized/hdfs_scanner_text.cpp [hunk 2]
```diff
@@ -44,8 +60,13 @@ Status HdfsTextScanner::do_init(RuntimeState* runtime_state, const HdfsScannerPa
 }
 
 Status HdfsTextScanner::do_open(RuntimeState* runtime_state) {
+    const THdfsScanRange* scan_range = _scanner_params.scan_ranges[0];
     _reader = std::make_unique<HdfsScannerCSVReader>(_scanner_params.fs, _record_delimiter, _field_delimiter,
-                                                     _scanner_params.scan_ranges[0]->offset);
+                                                     scan_range->offset, scan_range->length, scan_range->file_length);
+    if (scan_range->offset != 0) {
```
Comment (imay) [inline be/src/exec/vectorized/hdfs_scanner_text.cpp:66]: Give some comments here.

File: be/src/exec/vectorized/hdfs_scanner_text.cpp [hunk 3]
```diff
@@ -32,6 +42,12 @@ Status HdfsTextScanner::HdfsScannerCSVReader::_fill_buffer() {
         // is valid, according the RFC, add the record delimiter ourself.
         _buff.append(_record_delimiter);
     }
+
+    if ((_remain_length < 0 && _buff.find(_record_delimiter, 0) != nullptr)
+        || (_offset >= _file_length)) {
```
Comment (imay) [inline be/src/exec/vectorized/hdfs_scanner_text.cpp:47]: 1. would you mind add some comment for this logic?

If only offset 0 is supported, the remain_length will be the same with file_length? Otherwise some data won't be read

**Comment by imay** [comment]
End of file is normal case means to reach the end. The reader should treat it differently with other error.

File: be/src/exec/vectorized/hdfs_scanner_text.cpp (hunk 3 above)
Comment (caneGuy) [reply be/src/exec/vectorized/hdfs_scanner_text.cpp:47]: > 
> If only offset 0 is supported, the remain_length will be the same with file_length? Otherwise some data won't be read

assume that we have only one  scan range:
123,123,xxx
this record will read by logic before here. should_stop_scan will be set, then in the next round the reader will return eof status. so i think no data will be missed.

**Review by imay — DISMISSED** [review]

**Review by dirtysalt — APPROVED** [review]

**Review by imay — APPROVED** [review]
