### PR TITLE
[BugFix]Recursive merge groups when optimizer MEMO have same group expression.

### LINKED ISSUE #5746: Query returns Unknown error
### Steps to reproduce the behavior (Required)
1.  CREATE TABLE `tpcds_100g_call_center` (
  `cc_call_center_sk` int(11) NOT NULL COMMENT "",
  `cc_call_center_id` char(16) NOT NULL COMMENT "",
  `cc_rec_start_date` date NULL COMMENT "",
  `cc_rec_end_date` date NULL COMMENT "",
  `cc_closed_date_sk` int(11) NULL COMMENT "",
  `cc_open_date_sk` int(11) NULL COMMENT "",
  `cc_name` varchar(50) NULL COMMENT "",
  `cc_class` varchar(50) NULL COMMENT "",
  `cc_employees` int(11) NULL COMMENT "",
  `cc_sq_ft` int(11) NULL COMMENT "",
  `cc_hours` char(20) NULL COMMENT "",
  `cc_manager` varchar(40) NULL COMMENT "",
  `cc_mkt_id` int(11) NULL COMMENT "",
  `cc_mkt_class` char(50) NULL COMMENT "",
  `cc_mkt_desc` varchar(100) NULL COMMENT "",
  `cc_market_manager` varchar(40) NULL COMMENT "",
  `cc_division` int(11) NULL COMMENT "",
  `cc_division_name` varchar(50) NULL COMMENT "",
  `cc_company` int(11) NULL COMMENT "",
  `cc_company_name` char(50) NULL COMMENT "",
  `cc_street_number` char(10) NULL COMMENT "",
  `cc_street_name` varchar(60) NULL COMMENT "",
  `cc_street_type` char(15) NULL COMMENT "",
  `cc_suite_number` char(10) NULL COMMENT "",
  `cc_city` varchar(60) NULL COMMENT "",
  `cc_county` varchar(30) NULL COMMENT "",
  `cc_state` char(2) NULL COMMENT "",
  `cc_zip` char(10) NULL COMMENT "",
  `cc_country` varchar(20) NULL COMMENT "",
  `cc_gmt_offset` decimal64(5, 2) NULL COMMENT "",
  `cc_tax_percentage` decimal64(5, 2) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`cc_call_center_sk`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`cc_call_center_sk`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. CREATE EXTERNAL TABLE `es_ssb_10g_dates` (
  `d_datekey` int(11) NOT NULL COMMENT "",
  `d_date` varchar(20) NOT NULL COMMENT "",
  `d_dayofweek` varchar(10) NOT NULL COMMENT "",
  `d_month` varchar(11) NOT NULL COMMENT "",
  `d_year` int(11) NOT NULL COMMENT "",
  `d_yearmonthnum` int(11) NOT NULL COMMENT "",
  `d_yearmonth` varchar(9) NOT NULL COMMENT "",
  `d_daynuminweek` int(11) NOT NULL COMMENT "",
  `d_daynuminmonth` int(11) NOT NULL COMMENT "",
  `d_daynuminyear` int(11) NOT NULL COMMENT "",
  `d_monthnuminyear` int(11) NOT NULL COMMENT "",
  `d_weeknuminyear` int(11) NOT NULL COMMENT "",
  `d_sellingseason` varchar(14) NOT NULL COMMENT "",
  `d_lastdayinweekfl` int(11) NOT NULL COMMENT "",
  `d_lastdayinmonthfl` int(11) NOT NULL COMMENT "",
  `d_holidayfl` int(11) NOT NULL COMMENT "",
  `d_weekdayfl` int(11) NOT NULL COMMENT ""
) ENGINE=ELASTICSEARCH
COMMENT "ELASTICSEARCH"
PROPERTIES (
"hosts" = "http://172.26.92.141:9200",
"user" = "root",
"password" = "123456",
"index" = "dates",
"type" = "_doc",
"transport" = "http",
"enable_docvalue_scan" = "true",
"max_docvalue_fields" = "20",
"enable_keyword_sniff" = "true"
);
3. CREATE TABLE `tpcds_100g_catalog_page` (
  `cp_catalog_page_sk` int(11) NOT NULL COMMENT "",
  `cp_catalog_page_id` char(16) NOT NULL COMMENT "",
  `cp_start_date_sk` int(11) NULL COMMENT "",
  `cp_end_date_sk` int(11) NULL COMMENT "",
  `cp_department` varchar(50) NULL COMMENT "",
  `cp_catalog_number` int(11) NULL COMMENT "",
  `cp_catalog_page_number` int(11) NULL COMMENT "",
  `cp_description` varchar(100) NULL COMMENT "",
  `cp_type` varchar(100) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`cp_catalog_page_sk`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`cp_catalog_page_sk`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
4.  CREATE EXTERNAL TABLE `hive_ssb_100g_parquet_part` (
  `p_partkey` int(11) NULL COMMENT "",
  `p_name` varchar(23) NULL COMMENT "",
  `p_mfgr` varchar(7) NULL COMMENT "",
  `p_category` varchar(8) NULL COMMENT "",
  `p_brand` varchar(10) NULL COMMENT "",
  `p_color` varchar(12) NULL COMMENT "",
  `p_type` varchar(26) NULL COMMENT "",
  `p_size` int(11) NULL COMMENT "",
  `p_container` varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_100g_parquet_zlib",
"table" = "part",
"resource" = "hive_resource_emr",
"hive.metastore.uris"  =  "thrift://172.26.194.238:9083"
);
5. CREATE EXTERNAL TABLE `es_without_null` (
  `id_int` int(11) NOT NULL COMMENT "",
  `id_int1000` int(11) NOT NULL COMMENT "",
  `id_tinyint` tinyint(4) NOT NULL COMMENT "",
  `id_smallint` smallint(6) NOT NULL COMMENT "",
  `id_float` float NOT NULL COMMENT "",
  `id_double` double NOT NULL COMMENT "",
  `id_char` char(255) NOT NULL COMMENT "",
  `id_varchar` varchar(65533) NOT NULL COMMENT "",
  `id_varchar_int` varchar(65533) NOT NULL COMMENT "",
  `id_varchar_date` varchar(65533) NOT NULL COMMENT "",
  `id_varchar_datetime` varchar(65533) NOT NULL COMMENT "",
  `id_date` date NOT NULL COMMENT "",
  `id_datatime` datetime NOT NULL COMMENT "",
  `id_decimal` varchar(65533) NOT NULL COMMENT "",
  `id_decimal10` varchar(65533) NOT NULL COMMENT "",
  `id_boolean` boolean NOT NULL COMMENT ""
) ENGINE=ELASTICSEARCH
COMMENT "ELASTICSEARCH"
PROPERTIES (
"hosts" = "http://172.26.92.141:9200",
"user" = "root",
"password" = "",
"index" = "doris_external_data_not_null",
"type" = "_doc",
"transport" = "http",
"enable_docvalue_scan" = "true",
"max_docvalue_fields" = "20",
"enable_keyword_sniff" = "true"
);
6. select   subq_0.c0 as c0,   ref_2.d_yearmonth as c1,   ref_2.d_dayofweek as c2,   esquery(     cast(ref_1.cc_call_center_id as VARCHAR),     cast(ref_1.cc_mkt_desc as VARCHAR)   ) as c3 from   (     select       88 as c0     from     es_without_null as ref_0     where       false   ) as subq_0   inner join tpcds_100g_call_center as ref_1 on (subq_0.c0 = ref_1.cc_call_center_sk)   inner join es_ssb_10g_dates as ref_2 on (subq_0.c0 = ref_2.d_datekey)   inner join tpcds_100g_catalog_page as ref_3 on (     ref_2.d_weeknuminyear = ref_3.cp_catalog_page_sk   )   inner join hive_ssb_100g_parquet_part as ref_4 on (ref_2.d_sellingseason = ref_4.p_name) where   (     space(cast(ref_4.p_partkey as INT)) <= ref_4.p_category   )   or (     ref_1.cc_gmt_offset = tan(cast(ref_1.cc_tax_percentage as DOUBLE))   ) limit   111;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
2022-05-05 16:47:05,861 WARN (starrocks-mysql-nio-pool-11|367) [StmtExecutor.execute():470] execute Exception, sql select   subq_0.c0 as c0,   ref_2.d_yearmonth as c1,   ref_2.d_dayofweek as c2,   esquery(     cast(ref_1.cc_call_center_id as VARCHAR),     cast(ref_1.cc_mkt_desc as VARCHAR)   ) as c3 from   (     select       88 as c0     from       sqlsmith.es_without_null as ref_0     where       false   ) as subq_0   inner join sqlsmith.tpcds_100g_call_center as ref_1 on (subq_0.c0 = ref_1.cc_call_center_sk)   inner join sqlsmith.es_ssb_10g_dates as ref_2 on (subq_0.c0 = ref_2.d_datekey)   inner join sqlsmith.tpcds_100g_catalog_page as ref_3 on (     ref_2.d_weeknuminyear = ref_3.cp_catalog_page_sk   )   inner join sqlsmith.hive_ssb_100g_parquet_part as ref_4 on (ref_2.d_sellingseason = ref_4.p_name) where   (     space(cast(ref_4.p_partkey as INT)) <= ref_4.p_category   )   or (     ref_1.cc_gmt_offset = tan(cast(ref_1.cc_tax_percentage as DOUBLE))   ) limit   111
java.lang.StackOverflowError: null
        at java.util.Arrays.hashCode(Arrays.java:4146) ~[?:1.8.0_292]
        at java.util.Objects.hash(Objects.java:128) ~[?:1.8.0_292]
        at com.starrocks.sql.optimizer.base.OrderSpec.hashCode(OrderSpec.java:36) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.base.SortProperty.hashCode(SortProperty.java:41) ~[starrocks-fe.jar:?]
        at java.util.Arrays.hashCode(Arrays.java:4146) ~[?:1.8.0_292]
        at java.util.Objects.hash(Objects.java:128) ~[?:1.8.0_292]
        at com.starrocks.sql.optimizer.base.PhysicalPropertySet.hashCode(PhysicalPropertySet.java:64) ~[starrocks-fe.jar:?]
        at java.util.HashMap.hash(HashMap.java:339) ~[?:1.8.0_292]
        at java.util.HashMap.containsKey(HashMap.java:596) ~[?:1.8.0_292]
        at com.starrocks.sql.optimizer.Group.hasBestExpression(Group.java:194) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Group.getBestExpression(Group.java:187) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:259) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 release afbb3bc

### PR DESCRIPTION
**Pull request by Youngwb**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5746 

## Problem Summary(Required) ：

At Memo group merge phase，it may generate same group expression when src group merge to dst group, if they are not in the same group, we should merge these group recursively. Main change is line 232 of Memo.java.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 13 / 20 (65.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Group.java|3|8|37.50%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Memo.java|10|12|83.33%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 1]
```diff
@@ -215,22 +229,19 @@ private void mergeGroup(Group srcGroup, Group dstGroup) {
...
-            removeOneGroup(group);
-        }
+
+        needMergeGroup.forEach(this::mergeGroupImpl);
     }
 
-    private List<Group> getAllEmptyGroups() {
-        List<Group> groups = Lists.newArrayList();
+    private Set<Group> getAllEmptyGroups() {
+        Set<Group> groups = Sets.newHashSet();
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:244]: why need set?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 2]
```diff
@@ -215,22 +229,19 @@ private void mergeGroup(Group srcGroup, Group dstGroup) {
                     reinsertExpression.getGroup().replaceBestExpression(reinsertExpression, existGroupExpression);
                     // existingGroupExpression merge the state of groupExpression
                     existGroupExpression.mergeGroupExpression(reinsertExpression);
+                } else {
+                    reinsertExpression.getGroup().deleteBestExpression(reinsertExpression);
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:233]: reinsertExpression.getGroup() will be merged, why need to delete the best expression

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 3]
```diff
@@ -215,22 +229,19 @@ private void mergeGroup(Group srcGroup, Group dstGroup) {
...
+                    needMergeGroup.put(reinsertExpression.getGroup(), existGroupExpression.getGroup());
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:234]:
```suggestion
                    existGroupExpression.getGroup().deleteBestExpression(reinsertExpression);
                    mergeGroupImpl(reinsertExpression.getGroup(), existGroupExpression.getGroup());
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 4]
```diff
@@ -215,22 +229,19 @@ private void mergeGroup(Group srcGroup, Group dstGroup) {
                     reinsertExpression.getGroup().replaceBestExpression(reinsertExpression, existGroupExpression);
                     // existingGroupExpression merge the state of groupExpression
                     existGroupExpression.mergeGroupExpression(reinsertExpression);
+                } else {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:232]: add more comment for this else branch.

**Comment by kangkaisen** [comment]
need add UT cover this bug.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java (hunk 1 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:244]: List could has same group

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java (hunk 2 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:233]: Because the best expression will also be merged, it need to be clear first

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java (hunk 3 above)
Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:234]: 1. Why delete existGroupExpression best expression？
2. We need do dstGroup.mergeGroup(srcGroup) first

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 13 / 20 (65.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Group.java|3|8|37.50%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Memo.java|10|12|83.33%|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by Youngwb** [comment]
@Mergifyio backport branch-2.2
