### PR TITLE
[BugFix] multiple sys_log_to_console=true entry in fe.conf every time…

### LINKED ISSUE #45850: [BugFix] multiple sys_log_to_console=true entry in fe.conf every time fe is started with --logconsole option
### Steps to reproduce the behavior (Required)
start fe with with --logconsole command line option

### Expected behavior (Required)
sys_log_to_console = true     should appear only once in fe.conf file

### Real behavior (Required)
sys_log_to_console = true is appended to fe.conf file every time fe is started with --logconsole option, so there are multiple duplicate entry in fe.confg
image

### StarRocks version (Required)
main

### PR DESCRIPTION
**Pull request by rohitrs1983**
## Why I'm doing:
multiple sys_log_to_console=true entry in fe.conf every time fe is started with --logconsole option

## What I'm doing:
fe.conf should have only single entry sys_log_to_console=true 

Fixes #45850 

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: bin/start_fe.sh [hunk 1]
```diff
@@ -199,7 +199,9 @@ if [ ${RUN_LOG_CONSOLE} -eq 1 ] ; then
         cp $STARROCKS_HOME/conf/fe.conf.readonly $STARROCKS_HOME/conf/fe.conf
     fi
     # force sys_log_to_console = true
-    echo -e "\nsys_log_to_console = true" >> $STARROCKS_HOME/conf/fe.conf
+    if ! grep sys_log_to_console $STARROCKS_HOME/conf/fe.conf | tr -d ' ' | grep -v "#sys_log_to_console"  &>/dev/null; then
```
Comment (kevincai) [inline bin/start_fe.sh:202]: actually I am thinking about using environment variable instead of fe.conf configvar to control this behavior, so we don't have to make changes to fe.conf at all.

Comment (kevincai) [reply bin/start_fe.sh:202]: this is also a small step forward to allow running starrocks in a readonly filesystem container environment.

Comment (rohitrs1983) [reply bin/start_fe.sh]: fixed

File: fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java [hunk 2]
```diff
@@ -309,7 +309,8 @@ private static String generateXmlConfTemplate() {
         }
 
         String newXmlConfTemplate = APPENDER_TEMPLATE;
-        newXmlConfTemplate += Config.sys_log_to_console ? CONSOLE_LOGGER_TEMPLATE : FILE_LOGGER_TEMPLATE;
+        newXmlConfTemplate += System.getenv("SYS_LOG_TO_CONSOLE").trim().equals("1")
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java:312]: probably the configvar is still kept. but the default value can be changed via the env var. so end-user can still use fe.conf configvar to overwrite the config, and in container env, suppose the user doesn't have the configvar in fe.conf, our env var will overwrite the default value and turn on/off the log to console. What do you think?

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java:312]: @kevincai, i feel having multiple ways to handle one behavior leads to confusion, rather we should have one method. either config or env variable. there can come situations where user may by mistake configure both, then which will take precedence, config or env var; one user may feel config should take precedence other may be env variable should take precedence. what is your opinion?

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java:312]: the configvar is always the canonical one to control the behavior, the env var is just changing the default value of the configvar. if the configvar is explicitly set in fe.conf, then the default value will not be used.

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java]: @kevincai i have updated as per our review discussion.

File: fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java [hunk 3]
```diff
@@ -309,7 +309,8 @@ private static String generateXmlConfTemplate() {
         }
 
         String newXmlConfTemplate = APPENDER_TEMPLATE;
-        newXmlConfTemplate += Config.sys_log_to_console ? CONSOLE_LOGGER_TEMPLATE : FILE_LOGGER_TEMPLATE;
+        newXmlConfTemplate += (Config.sys_log_to_console || System.getenv("SYS_LOG_TO_CONSOLE").trim().equals("1"))
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java:312]: I mean, if we can make the change in Config.java, something like

```
public static boolean sys_log_to_console = System.getenv("SYS_LOG_TO_CONSOLE").trim().equals("1");
```

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Log4jConfig.java]: updated

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 4]
```diff
@@ -96,7 +96,7 @@ public class Config extends ConfigBase {
      * Log to file by default. set to `true` if you want to log to console
      */
     @ConfField
-    public static boolean sys_log_to_console = false;
+    public static boolean sys_log_to_console = System.getenv("SYS_LOG_TO_CONSOLE").trim().equals("1");
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:99]: looks like it doesn't work for this way to init the `sys_log_to_console`, need to take a look how to make it work or find an alternative way to do it.

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:99]: `System.getenv("SYS_LOG_TO_CONSOLE")` can be `null` if the env is not set.

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: @kevincai fixed the issue. 
verified the following test cases
1)SYS_LOG_TO_CONSOLE env variable not set, sys_log_to_console=false
2)SYS_LOG_TO_CONSOLE env variable is present, start fe without --logconsole, sys_log_to_console=false
3)SYS_LOG_TO_CONSOLE env variable is present, start fe with --logconsole, sys_log_to_console=true
4)SYS_LOG_TO_CONSOLE not set from start_fe.sh, SYS_LOG_TO_CONSOLE=1 ./start_fe.sh, sys_log_to_console=true
5)SYS_LOG_TO_CONSOLE not set from start_fe.sh, SYS_LOG_TO_CONSOLE=0 ./start_fe.sh, sys_log_to_console=false
6)SYS_LOG_TO_CONSOLE not set from start_fe.sh, export SYS_LOG_TO_CONSOLE=1; ./start_fe.sh, sys_log_to_console=true
7)SYS_LOG_TO_CONSOLE not set from start_fe.sh, export SYS_LOG_TO_CONSOLE=0; ./start_fe.sh, sys_log_to_console=false

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: looks like not make sense to me for case 2) 3) 4) 6).

From the code, it always `export SYS_LOG_TO_CONSOLE=${RUN_LOG_CONSOLE}`, if --logconsole is not provided, it will be always `export SYS_LOG_TO_CONSOLE=0` which overwrites the outside `SYS_LOG_TO_CONSOLE` env var before running the `start_fe.sh`

Maybe we should consider

```bash
RUN_LOG_CONSOLE=${SYS_LOG_TO_CONSOLE:-0}
```

in line 38?

Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: what i did was comment the setting in start_fe.sh and run the test
commented this line in start_fe.sh and run the test
#export SYS_LOG_TO_CONSOLE=${RUN_LOG_CONSOLE}

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: but we have to put all together and do the testing, can't expect the user to manually comment out the line from `start_fe.sh`

**Comment by kevincai** [comment]
@rohitrs1983 do you have time to update this PR?

**Comment by kevincai** [comment]
@mergifyio rebase

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 4 above)
Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: @kevincai i have fixed this.

**Review by kevincai — DISMISSED** [review]

**Comment by rohitrs1983** [comment]
@nshangyiming can you please reivew the PR.

**Comment by kevincai** [comment]
@mergifyio rebase

**Comment by kevincai** [comment]
@rohitrs1983 automatic rebase doesn't work, can you manual rebase this PR to latest main branch?

**Comment by rohitrs1983** [comment]
> @rohitrs1983 automatic rebase doesn't work, can you manual rebase this PR to latest main branch?

@kevincai rebased to latest main.

**Review by kevincai — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
