### PR TITLE
[BugFix] Fix statistics related mv bug

### LINKED ISSUE #21182: mv rewritten plan can not be picked because of invalid statistics calculation
now, in some join mv rewrite and union mv rewrite, the rewritten mv plan can not be picked because the plan's cost calculation is wrong.

### Expected behavior (Required)
pick the mv rewritten plan
### Real behavior (Required)
the mv rewritten plan is not picked
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #21182 

## Problem Summary(Required) ：

Fix statistics related mv bug. the reasons are:
1. fix the scan mv operator cost
2. normalized the union rewritten result predicates to reduce cost
3. fix distribution shuffle columns to reduce distribution cost
4. modify join cost to make it more reasonable in mv rewrite

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java [hunk 1]
```diff
@@ -99,7 +102,10 @@ public double getCpuCost() {
                 buildCost = rightOutput;
                 probeCost = leftOutput;
         }
-        return buildCost + probeCost;
+        double joinCost = buildCost + probeCost;
+        // should add output cost
+        joinCost += joinStatistics.getComputeSize();
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java:107]: would it affect existing cases ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java [hunk 2]
```diff
@@ -120,12 +124,22 @@ public OptExpression visitLogicalTableScan(OptExpression optExpression, Void con
             ImmutableMap<Column, ColumnRefOperator> newColumnMetaToColRefMap = columnMetaToColRefMapBuilder.build();
             scanBuilder.setColumnMetaToColRefMap(newColumnMetaToColRefMap);
 
+            // process HashDistributionSpec
+            if (optExpression.getOp() instanceof LogicalOlapScanOperator) {
+                LogicalOlapScanOperator olapScan = (LogicalOlapScanOperator) optExpression.getOp();
+                HashDistributionSpec newHashDistributionSpec =
+                        processHashDistributionSpec(olapScan.getDistributionSpec(), columnRefFactory, columnMapping);
+                LogicalOlapScanOperator.Builder olapScanBuilder = (LogicalOlapScanOperator.Builder) scanBuilder;
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java:132]: what if it's not a OlapScan

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java [hunk 3]
```diff
@@ -95,6 +96,25 @@ public ColumnRefSet getUsedColumns() {
         return usedColumns;
     }
 
+    @Override
+    public boolean equals(Object o) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java:100]: why needs this ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java [hunk 4]
```diff
@@ -40,6 +41,7 @@ public class ExpressionContext {
     private final List<LogicalProperty> childrenProperty = Lists.newArrayList();
 
     private Statistics statistics;
+    private Map<GroupExpression, Statistics> groupExtraStatistics;
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java:44]: Add comments  to desc this

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 5]
```diff
@@ -866,6 +866,12 @@ protected OptExpression queryBasedRewrite(RewriteContext rewriteContext, ScalarO
                 Utils.compoundAnd(
                         rewriteContext.getQueryPredicateSplit().toScalarOperator(),
                         CompoundPredicateOperator.not(compensationPredicates)));
+        List<ScalarOperator> predicates = Utils.extractConjuncts(queryCompensationPredicate);
+        predicates.removeAll(mvRewriteContext.getOnPredicates());
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:870]: why remove

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java [hunk 6]
```diff
@@ -244,6 +258,55 @@ public OptExpression visit(OptExpression optExpression, Void context) {
             return null;
         }
 
+        private HashDistributionSpec processHashDistributionSpec(
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java:261]: add comment to describe what this function does

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java:107]: yes, it changes some ut plans. But I think it is reasonable.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java:132]: there is a check of optExpression.getOp() instanceof LogicalOlapScanOperator

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/Statistics.java:100]: used to judge whether Statistics has changed

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:870]: because onPredicate is kept in Join, not necessary to add it again.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java [hunk 7]
```diff
@@ -50,6 +50,11 @@ public class Group {
     private boolean isExplored;
 
     private Statistics statistics;
+
+    // used by mv rewrite
+    // GroupExpression's statistics generated by mv rewrite is different from group's statistics
+    private final Map<GroupExpression, Statistics> extraStatistics;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Group.java:56]: why name is extra, not MV?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java [hunk 8]
```diff
@@ -61,6 +63,27 @@ public void execute() {
...
+                            scan.getSelectedPartitionId(),
+                            scan.getSelectedTabletId(),
+                            scan.getPrunedPartitionPredicates(),
+                            scan.getProjection());
+                    GroupExpression newGroupExpression = new GroupExpression(physicalOlapScan, groupExpression.getInputs());
+                    groupExpression.getGroup().setGroupExpressionStatistics(newGroupExpression,
+                            expressionContext.getStatistics());
+                }
+            }
+        }
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java:86]: the way can work when the scan operator has new optimize?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java [hunk 9]
```diff
@@ -61,6 +63,27 @@ public void execute() {
...
+                            scan.getTable(),
+                            scan.getColRefToColumnMetaMap(),
+                            scan.getDistributionSpec(),
+                            scan.getLimit(),
+                            scan.getPredicate(),
+                            scan.getSelectedIndexId(),
+                            scan.getSelectedPartitionId(),
+                            scan.getSelectedTabletId(),
+                            scan.getPrunedPartitionPredicates(),
+                            scan.getProjection());
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java:80]: save table id is enough?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java (hunk 1 above)
Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java:107]: What is the reason for increasing the cost of this part? Is the cost is a linear relationship with outputsize? If the join output result is too large, the overall cost may increase too much and affect the plan selection.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 5 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:870]: a bit wried, why just remove on-predicates here.. Some cases `onPredicate ` are not kept in Join which can be pushed down to children. How about this?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 10]
```diff
@@ -866,6 +866,12 @@ protected OptExpression queryBasedRewrite(RewriteContext rewriteContext, ScalarO
                 Utils.compoundAnd(
                         rewriteContext.getQueryPredicateSplit().toScalarOperator(),
                         CompoundPredicateOperator.not(compensationPredicates)));
+        List<ScalarOperator> predicates = Utils.extractConjuncts(queryCompensationPredicate);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:869]: `Utils.extractConjuncts`  is a little expensive, how about not ` Utils.compoundAnd` for `queryCompensationPredicate `.


```
 // query predicate and (not viewToQueryCompensationPredicate) is the final query compensation predicate
        ScalarOperator queryCompensationPredicate = MvUtils.canonizePredicate(
                Utils.compoundAnd(
                        rewriteContext.getQueryPredicateSplit().toScalarOperator(),
                        CompoundPredicateOperator.not(compensationPredicates)));
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java [hunk 11]
```diff
@@ -368,7 +371,7 @@ public CostEstimate visitPhysicalHashJoin(PhysicalHashJoinOperator join, Express
 
             Preconditions.checkState(!(join.getJoinType().isCrossJoin() || eqOnPredicates.isEmpty()),
                     "should be handled by nestloopjoin");
-            HashJoinCostModel joinCostModel = new HashJoinCostModel(context, inputProperties, eqOnPredicates);
+            HashJoinCostModel joinCostModel = new HashJoinCostModel(context, inputProperties, eqOnPredicates, statistics);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java:374]: What's the meaning of `statistics `?

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java:374]:
```
    public Statistics getStatisticsForGroupExpression(GroupExpression groupExpression) {
        return extraStatistics.get(groupExpression);
    }
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/HashJoinCostModel.java:107]: because after mv rewrite, join may be rewritten as a mv scan operator. the join's cost should compare with rewritten scan mv operator, which should consider the output size of join.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/ExpressionContext.java:46]: done

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 10 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:869]: the predicates should be removed after canonized. I think it is ok.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:870]: the core logical is that do not add repeat join on predicate into compensation query predicates. just consider the not-pushdown on predicates. Pushdown onPredicates is not necessary.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java (hunk 6 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java:263]: done

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java (hunk 9 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/DeriveStatsTask.java:80]: no, one mv can be used in different groups, so should use GroupExpression as key

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java (hunk 11 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/cost/CostModel.java:374]: statistics is statistics of join.

**Review by LiShuMing — DISMISSED** [review]
LGTM~

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 94 / 107 (87.85%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/Statistics.java|5|8|62.50%|[102, 105, 115]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java|27|37|72.97%|[289, 290, 291, 292, 293, 294, 304, 305, 306, 307]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/DeriveStatsTask.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Group.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/HashJoinCostModel.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/DistributionSpec.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewriteContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/ExpressionContext.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 91 / 104 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/Statistics.java|5|8|62.50%|[102, 105, 115]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/OptExpressionDuplicator.java|27|37|72.97%|[289, 290, 291, 292, 293, 294, 304, 305, 306, 307]|
|:large_blue_circle:|com/starrocks/sql/optimizer/task/DeriveStatsTask.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Group.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/HashJoinCostModel.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalOlapScanOperator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/DistributionSpec.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewriteContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/ExpressionContext.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|14|14|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/cost/CostModel.java|1|1|100.00%|[]|

**Review by Youngwb — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
