### PR TITLE
Fix crash when use hyperscan

### LINKED ISSUE #2830: Query with like empty string condition crash in ASAN mode
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `test_limit` ( `k1`  varchar(25)) ENGINE=OLAP DUPLICATE KEY(`k1`) COMMENT "OLAP" DISTRIBUTED                         BY HASH(`k1`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
2. insert into test_limit values("");
3. select * from test_limit where k1 like "";

```
crash.log:
*** Check failure stack trace: ***
    @          0x8dac67d  google::LogMessage::Fail()
    @          0x8dae959  google::LogMessage::SendToLog()
    @          0x8dac1f9  google::LogMessage::Flush()
    @          0x8daef59  google::LogMessageFatal::~LogMessageFatal()
    @          0x87ccb90  starrocks::vectorized::LikePredicate::regex_match_full()
    @          0x87cc43b  starrocks::vectorized::LikePredicate::regex_match()
    @          0x87cab0b  starrocks::vectorized::LikePredicate::like_fn()
    @          0x87c9bd5  starrocks::vectorized::LikePredicate::like()
    @          0x80f1cd5  starrocks::vectorized::VectorizedFunctionCallExpr::evaluate()
    @          0x768994c  starrocks::ExprContext::evaluate()
    @          0x76896fd  starrocks::ExprContext::evaluate()
    @          0x4b76075  starrocks::vectorized::ColumnExprPredicate::evaluate()
    @          0x459be0a  starrocks::vectorized::ColumnPredicateRewriter::_rewrite_expr_predicate()
    @          0x4599e8f  starrocks::vectorized::ColumnPredicateRewriter::_rewrite_predicate()
    @          0x4595a14  starrocks::vectorized::ColumnPredicateRewriter::rewrite_predicate()
    @          0x435a73e  starrocks::vectorized::SegmentIterator::_rewrite_predicates()
    @          0x434e9c9  starrocks::vectorized::SegmentIterator::_init()
    @          0x4355026  starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x41ca574  starrocks::vectorized::ChunkIterator::get_next()
    @          0x4dc0581  starrocks::SegmentIteratorWrapper::do_get_next()
    @          0x41ca574  starrocks::vectorized::ChunkIterator::get_next()
    @          0x44d73c8  starrocks::vectorized::TimedChunkIterator::do_get_next()
    @          0x41ca574  starrocks::vectorized::ChunkIterator::get_next()
    @          0x44cd353  starrocks::vectorized::TabletReader::do_get_next()
    @          0x41ca574  starrocks::vectorized::ChunkIterator::get_next()
    @          0x6aa044e  starrocks::vectorized::TabletScanner::get_chunk()
    @          0x6019665  starrocks::vectorized::OlapScanNode::_scanner_thread()
    @          0x602007a  _ZZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS0_13TabletScannerEbENKUlvE_clEv
    @          0x602498a  _ZSt13__invoke_implIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x602482b  _ZSt10__invoke_rIvRZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS1_13TabletScannerEbEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @          0x6024693  _ZNSt17_Function_handlerIFvvEZN9starrocks10vectorized12OlapScanNode15_submit_scannerEPNS2_13TabletScannerEbEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x3dc8064  std::function<>::operator()()

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_MASTER_ASAN 4987435 |
+------------------------------+

### PR DESCRIPTION
**Pull request by Pslydhh**
- Because we can't transfer nullptr to hs_scan as data pointer, So we use a Pointer that will not be read.
- In the case that empyt string, It's size is 0 and data pointer is undefined(maybe nullptr or not), so we can't use data pointer  in this case.

Fix https://github.com/StarRocks/starrocks/issues/2830

### CODE REVIEW

**Comment by kangkaisen** [comment]
please add a UT

File: be/src/exprs/vectorized/like_predicate.h [hunk 1]
```diff
@@ -139,6 +139,8 @@ class LikePredicate {
     static void remove_escape_character(std::string* search_string);
 
 private:
+    static inline char _DUMMY_STRING_USE_WITH_HS_SCAN = 'A';
```
Comment (satanson) [inline be/src/exprs/vectorized/like_predicate.h:142]: add some comment to explain motivation why introducing this variable.

File: be/src/exprs/vectorized/like_predicate.cpp [hunk 2]
```diff
@@ -339,42 +339,57 @@ ColumnPtr LikePredicate::regex_match(FunctionContext* context, const starrocks::
...
 
     // pattern is constant value, use context's regex
     if (context->is_constant_column(1)) {
-        auto state = reinterpret_cast<LikePredicateState*>(context->get_function_state(FunctionContext::THREAD_LOCAL));
-
-        hs_scratch_t* scratch = nullptr;
-        if (hs_clone_scratch(state->scratch, &scratch) != HS_SUCCESS) {
-            CHECK(false) << "ERROR: Unable to clone scratch space.";
-        }
+        if (!pattern_column->is_nullable()) {
```
Comment (stdpain) [inline be/src/exprs/vectorized/like_predicate.cpp:349]:
```suggestion
        if (pattern_column->only_null) {
            return ColumnHelper::create_const_null_column(value_column->size());
        }
```

File: be/src/exprs/vectorized/like_predicate.cpp [hunk 3]
```diff
@@ -406,42 +421,57 @@ ColumnPtr LikePredicate::regex_match_full(FunctionContext* context, const starro
...
+                        value_size, 0, scratch,
+                        [](unsigned int id, unsigned long long from, unsigned long long to, unsigned int flags,
+                           void* ctx) -> int {
+                            *((bool*)ctx) = true;
+                            return 1;
+                        },
+                        &v);
+
+                DCHECK(status == HS_SUCCESS || status == HS_SCAN_TERMINATED) << " status: " << status;
+                result.append(v);
```
Comment (satanson) [inline be/src/exprs/vectorized/like_predicate.cpp:461]: line 431~468,  a new function name _predicate_const_regex function may be introduced to simplify the code and make the code clear and understandable.

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
