### PR TITLE
[BugFix] Fix block_compresssion Werror complier bug

### LINKED ISSUE #8224: [BugFix] Fix block_compresssion Werror complier bug

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8224

## Problem Summary(Required) ：

Fix block_compresssion Werror complier bug

### CODE REVIEW

File: be/src/util/compression/block_compression.cpp [hunk 1]
```diff
@@ -742,7 +742,7 @@ class ZstdBlockCompression final : public BlockCompressionCodec {
         ZSTD_CCtx* ctx = context->ctx;
 
         [[maybe_unused]] faststring* compression_buffer = nullptr;
-        [[maybe_unused]] size_t max_len;
```
Comment (imay) [inline be/src/util/compression/block_compression.cpp:745]: why not put these variable in `if (use_compression_buffer) {` code block?

Comment (xiaoyong-z) [reply be/src/util/compression/block_compression.cpp:745]: max_len will be used lator
image

Comment (imay) [reply be/src/util/compression/block_compression.cpp:745]: I see that all usage happens in the if(use_compression_buffer) block. so I think it is OK to defined in this code block.

**Review by imay — APPROVED** [review]
