### PR TITLE
[BugFix] fix output column of anti join

### LINKED ISSUE #13643: [sqlancer] be crash
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
DROP DATABASE IF EXISTS n0;
CREATE DATABASE n0;
USE n0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NOT NULL,c_0_1 BOOLEAN NOT NULL,c_0_2 VARCHAR(11) NOT NULL) PRIMARY KEY (c_0_0) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 110 day)) DISTRIBUTED BY HASH (c_0_0) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_0_2") ;
CREATE TABLE t1 (c_1_0 DATE NULL ,c_1_1 DECIMAL(31, 17)  NULL ,c_1_2 TINYINT NOT NULL ,c_1_3 DECIMAL(17, 14)  NOT NULL ,c_1_4 CHAR(1) NOT NULL ,c_1_5 LARGEINT NULL ,c_1_6 LARGEINT NULL ,c_1_7 DECIMAL(23, 2)  NULL ,c_1_8 CHAR(1) NOT NULL ,c_1_9 DECIMAL(23, 3)  NOT NULL ,c_1_10 DATE REPLACE_IF_NOT_NULL NOT NULL ,c_1_11 DECIMAL(34, 13)  MIN NOT NULL ,c_1_12 DECIMAL(35, 20)  MIN NOT NULL ,c_1_13 DATE MAX NULL ,c_1_14 HLL HLL_UNION NULL ,c_1_15 DATETIME REPLACE_IF_NOT_NULL NOT NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9) PARTITION BY RANGE(c_1_0) (START ("2010-01-01") END ("2022-12-31") EVERY (INTERVAL 175 day)) DISTRIBUTED BY HASH (c_1_3,c_1_5,c_1_8,c_1_0,c_1_6,c_1_1,c_1_9,c_1_4,c_1_7) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_1_8") ;
INSERT INTO t0 VALUES ('2010-01-12', false, ''), ('2010-01-13', true, 'YG'), ('2010-01-20', true, 'J');
INSERT INTO t1 VALUES ('2010-01-02', 0.00038071900061008, 7, 6.48E-12, '', -1489812760, -2015176792, 6844332737565889677.47, '', 44484179557289285.947, '2010-01-14', 22803165.0866768360922, 0.00000454080185519847, '2010-01-10', hll_hash(''), '2009-12-31 08:00:14'), ('2010-01-14', 0.00008912125358541, 2, 9.26E-12, '', NULL, NULL, 2476220961855235769.56, '', 8074505406139362.071, '2010-01-28', 75993807.3118583061278, 6.9629069253387E-7, NULL, hll_hash('p'), NULL);
INSERT INTO t1 VALUES ('2010-01-23', 0.00028627700043600, 4, 7.34E-12, '', -1823657297, NULL, 4420872457456743053.12, '', 56284575401576682.000, '2010-01-24', 18493430.5406257075178, 0.00000653675555835963, '2010-01-16', hll_hash('7T'), '2010-01-06 08:00:14');
INSERT INTO t0 VALUES ('2010-01-03', true, 'R'), ('2010-01-20', true, 'KmOc3gj2E');
INSERT INTO t0 VALUES ('2010-01-31', true, 'ao6');
INSERT INTO t1 VALUES ('2010-01-02', 0.00037364572433312, 4, 7.83E-12, '', -1823657297, -1313682481, 4897557455232719444.40, '', 71663807918843268.113, '2010-01-08', 50336672.1965286302558, 0.00000697244281230849, '2010-01-20', hll_hash('kmS'), '2010-01-25 08:00:14'), ('2010-01-08', 0.00095426007273629, 4, 1.90E-12, '', -2015176792, NULL, 4176663762905990424.53, '', 96444295204833714.898, '2010-01-25', 8135161.5189941243582, 0.00000459571845395389, '2010-01-24', hll_hash('r'), '2010-01-28 08:00:14');
INSERT INTO t0 VALUES ('2010-01-26', false, 'gFm'), ('2010-01-01', false, 'LdHR');
INSERT INTO t0 VALUES ('2010-01-07', true, ''), ('2010-01-11', false, 'd'), ('2010-01-27', false, 'ZWECfHZ4');
DELETE FROM t1 WHERE c_1_1=0.00067497161439032 AND c_1_8='';
INSERT INTO t0 VALUES ('2010-01-02', true, 'OA4');
INSERT INTO t0 VALUES ('2010-01-22', true, '');
INSERT INTO t1 VALUES ('2010-01-04', 0.00075157127966935, 0, 2.04E-12, '', NULL, -1489812760, 9257196513941754003.48, '', 36640953604185874.561, '2010-01-04', 29928312.2210671984689, 0.00000239660386367353, '2010-01-07', hll_hash(''), '2010-01-06 08:00:14');
INSERT INTO t0 VALUES ('2010-01-31', false, 'hQu'), ('2010-01-30', false, 'enqtTp');
INSERT INTO t0 VALUES ('2010-01-13', true, 'kv'), ('2009-12-31', false, 'SC');
INSERT INTO t0 VALUES ('2010-01-02', true, ''), ('2010-01-18', false, 's');
INSERT INTO t1 VALUES ('2010-01-14', 0.00083389792109264, 4, 2.47E-12, '', -265717385, 267921096, 7016095256186366679.07, '', 66277952878668153.699, '2010-01-08', 23175217.0549655648601, 0.00000342488294848909, '2010-01-20', hll_hash(''), '2010-01-08 08:00:14');
INSERT INTO t0 VALUES ('2010-01-12', true, 'm1mcO'), ('2010-01-31', false, 'dd');
CREATE VIEW v0 AS SELECT t1_3.c_1_0, t1_3.c_1_1, t1_3.c_1_2, t1_3.c_1_3, t1_3.c_1_4, t1_3.c_1_5, t1_3.c_1_6, t1_3.c_1_7, t1_3.c_1_8, t1_3.c_1_9, t1_3.c_1_10, t1_3.c_1_11, t1_3.c_1_12, t1_3.c_1_13, t1_3.c_1_14, t1_3.c_1_15, t0_2.c_0_0, t0_2.c_0_1, t0_2.c_0_2 FROM t1 AS t1_3, t0 AS t0_2 WHERE true ORDER BY t0_2.c_0_1, t1_3.c_1_3, t1_3.c_1_2;
INSERT INTO t0 VALUES ('2010-01-22', true, 'D');

WITH with_t_0 as (SELECT v0_9.c_1_0, v0_9.c_1_1, v0_9.c_1_2, v0_9.c_1_3, v0_9.c_1_4, v0_9.c_1_5, v0_9.c_1_6, v0_9.c_1_7, v0_9.c_1_8, v0_9.c_1_9, v0_9.c_1_10, v0_9.c_1_11, v0_9.c_1_12, v0_9.c_1_13, v0_9.c_1_15, v0_9.c_0_0, v0_9.c_0_1, v0_9.c_0_2 FROM v0 AS v0_9 WHERE true) SELECT SUM(count) FROM (SELECT CAST((CAST(false AS BOOLEAN) = true) AND (CAST(false AS BOOLEAN) IS NOT NULL) AS INT) as count FROM with_t_0,   t0 AS t0_7 RIGHT ANTI JOIN v0 AS v0_9 ON t0_7.c_0_1 = v0_9.c_1_7 AND CASE  WHEN false THEN true  WHEN false THEN t0_7.c_0_1 ELSE true END != 3390866678671217230.63 AND t0_7.c_0_0 >= v0_9.c_1_13 AND t0_7.c_0_0 != v0_9.c_1_13 AND t0_7.c_0_1 < v0_9.c_1_7 AND false > v0_9.c_1_7) t;
```

seems not stably reproduced, please execute several times, and check

### Expected behavior (Required)
no error

### Real behavior (Required)
there is crash in be

starrocks_be: /root/starrocks/be/src/gutil/casts.h:100: To down_cast(From&) [with To = const starrocks::vectorized::FixedLengthColumnBase<starrocks::vectorized::DateValue>&; From = const starrocks::vectorized::Column]: Assertion `dynamic_cast<ToAsPointer>(&f) != __null' failed.

*** Aborted at 1668739924 (unix time) try "date -d @1668739924" if you are using GNU date ***
PC: @     0x7f85c1a6b337 __GI_raise
*** SIGABRT (@0x3e800005ab5) received by PID 23221 (TID 0x7f854a910700) from PID 23221; stack trace: ***
    @         0x1127d0b2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f85cc4555f0 (unknown)
    @     0x7f85c1a6b337 __GI_raise
    @     0x7f85c1a6ca28 __GI_abort
    @     0x7f85c1a64156 __assert_fail_base
    @     0x7f85c1a64202 __GI___assert_fail
    @          0x90807c8 down_cast<>()
    @          0x905c287 starrocks::vectorized::FixedLengthColumnBase<>::append()
    @          0x8e4d132 starrocks::vectorized::Column::append()
    @          0xa29fa2a starrocks::pipeline::NLJoinProbeOperator::_permute_probe_row()
    @          0xa29f2ec starrocks::pipeline::NLJoinProbeOperator::_permute_chunk()
    @          0xa2a2014 starrocks::pipeline::NLJoinProbeOperator::pull_chunk()
    @          0x919ae38 starrocks::pipeline::PipelineDriver::process()
    @         0x10099a40 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @         0x1009842a _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE2_clEv
    @         0x100a090c _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_JEET_St14__invoke_otherOT0_DpOT1_
    @         0x100a000b _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @         0x1009f42f _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE2_E9_M_invokeERKSt9_Any_data
    @          0x8e520de std::function<>::operator()()
    @          0xf0f2a32 starrocks::FunctionRunnable::run()
    @          0xf0ef834 starrocks::ThreadPool::dispatch_thread()
    @          0xf10b440 std::__invoke_impl<>()
    @          0xf10ad99 std::__invoke<>()
    @          0xf10a190 _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0xf108af2 std::_Bind<>::operator()<>()
    @          0xf105b56 std::__invoke_impl<>()
    @          0xf1034ba _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0xf0ff523 std::_Function_handler<>::_M_invoke()
    @          0x8e520de std::function<>::operator()()
    @          0xf0d9eed starrocks::Thread::supervise_thread()
    @     0x7f85cc44de65 start_thread
    @     0x7f85c1b3388d __clone

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN 7fa12d8 |
+-------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

https://github.com/StarRocks/StarRocksTest/issues/1463
Fixes https://github.com/StarRocks/starrocks/issues/13643

## Problem Summary(Required) ：

1. Bug 1: Pruning project columns for LEFT SEMI/ANTI JOIN must output left side columns
3. Bug 2: Left anti join in NLJ should make right side column nullable

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

### CODE REVIEW

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.4 branch-2.5

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 23 / 24 (95.83%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/ColumnRefSet.java|0|1|00.00%|[156]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/Utils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PruneProjectColumnsRule.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java [hunk 1]
```diff
@@ -109,6 +113,20 @@ public ColumnRefSet getRequiredChildInputColumns() {
         return result;
     }
 
+    @Override
+    public ColumnRefOperator getSmallestColumns(ColumnRefFactory columnRefFactory, OptExpression expr) {
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java:117]: I get your bug, but may we fix LogicalJoinOperator.getOutputColumns is better?

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java [hunk 2]
```diff
@@ -31,6 +34,12 @@ public boolean isLogical() {
 
     public abstract ColumnRefSet getOutputColumns(ExpressionContext expressionContext);
 
+    public ColumnRefOperator getSmallestColumns(ColumnRefFactory columnRefFactory, OptExpression opt) {
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java:37]: getSmallestColumns->getSmallestColumn

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java [hunk 3]
```diff
@@ -50,12 +48,14 @@ public List<OptExpression> transform(OptExpression input, OptimizerContext conte
...
 
-            LogicalOperator logicalOperator = (LogicalOperator) input.inputAt(0).getOp();
+            OptExpression child = input.inputAt(0);
+            LogicalOperator logicalOperator = (LogicalOperator) child.getOp();
 
-            ColumnRefOperator smallestColumn = Utils.findSmallestColumnRef(
-                    logicalOperator.getOutputColumns(new ExpressionContext(input.inputAt(0))).getStream().
-                            mapToObj(context.getColumnRefFactory()::getColumnRef).collect(Collectors.toList()));
-            projectMap.put(smallestColumn, smallestColumn);
+            ColumnRefOperator smallestColumn =
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java:54]: What does it mean by `smallestColumn`?

File: be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp [hunk 4]
```diff
@@ -182,9 +182,14 @@ ChunkPtr NLJoinProbeOperator::_init_output_chunk(RuntimeState* state) const {
         SlotDescriptor* slot = _col_types[i];
         bool is_probe = i < _probe_column_count;
         bool nullable = _col_types[i]->is_nullable();
+        // OUTER JOIN must be nullable
         if ((is_probe && _is_right_join()) || (!is_probe && _is_left_join())) {
             nullable = true;
         }
+        // Right side of LEFT SEMI/ANTI JOIN must be nullable
+        if (!is_probe && (_is_left_anti_join() || _is_left_semi_join())) {
```
[the remark this answers is not in the document]
Comment (mofeiatwork) [reply be/src/exec/pipeline/nljoin/nljoin_probe_operator.cpp:190]: 1. In logical plan: `LEFT ANTI/SEMI` join only output left side, but not right side
2. In physical plan: 
    1. The `Project Operator` is used to prune left side
    2. NLJ output both left and right, but the right side is only null, cause it's useless
    3. So the right side must be `nullable`
3. Why `NLJ` output both side and `Project` output left side?
    1. It's a convention used by `CrossJoin`, `NestloopJoin` and `HashJoin`
    2. In theory it's not necessary

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java (hunk 1 above)
Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalJoinOperator.java:117]: That's more clear.

But this way would cause a lot of failed test cases, I guess changing the `getOutputColumns` semantic is dangerous.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java (hunk 3 above)
Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PruneProjectRule.java:54]: For `Project Operator`, if its output columns are empty, we need to find a smallest column for it, since our plan node could not output empty.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java (hunk 2 above)
Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/logical/LogicalOperator.java:37]: fixed

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by mofeiatwork** [comment]
run starrocks_be_unittest

**Comment by mofeiatwork** [comment]
run starrocks_clang-tidy

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by mofeiatwork** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.5
