### PR TITLE
[BugFix]Dictionary drop operations and refresh operations collide, resulting in inconsistent metadata.

### LINKED ISSUE #53549: Dictionary drop operations and refresh operations collide, resulting in inconsistent metadata.
### Steps to reproduce the behavior (Required)
Clipboard_Screenshot_1733305087
dict_uid_hash/dict_uid has been deleted.
### Expected behavior (Required)
show result  can't dispaly dict_uid_hash/dict_uid
### Real behavior (Required)
show result still display  dict_uid_hash/dict_uid
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhangheihei**
## What I'm doing:

Fixes #53549

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Comment by gengjun-git** [comment]
@stdpain PTAL

**Review by srlch — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java [hunk 1]
```diff
@@ -501,7 +501,12 @@ public void replayModifyDictionaryMgr(DictionaryMgrInfo info) {
             try {
                 for (Dictionary dictionary : dictionaries) {
                     // update dictionary object state
-                    dictionariesMapById.put(dictionary.getDictionaryId(), dictionary);
+                    if (dictionariesMapById.containsKey(dictionary.getDictionaryId())) {
+                        dictionariesMapById.put(dictionary.getDictionaryId(), dictionary);
+                    } else {
+                        LOG.warn("dictionary {}, id {} has been deleted",
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/catalog/DictionaryMgr.java:507]: Is the log useless?

**Review by trueeyu — APPROVED** [review]

**Comment by gengjun-git** [comment]
@srlch PTAL

**Review by gengjun-git — APPROVED** [review]
