### PR TITLE
[Enhancement] Add logic to cancel export job when be has crashed before

### LINKED ISSUE #10704: When an export job is in the exporting phase, if a be crashs, then the job needs to be canceled
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [ ] bugfix
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10704 

## Problem Summary(Required) ：

Fe cannot perceive rebooting BE. So that the export task thread is stuck and the overall task progress is stuck at 99%.
This PR uses lastStartTime to determine if the backend has restarted, and if it has, it will cancel the corresponding job.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 2 / 29 (06.90%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportChecker.java|0|23|00.00%|[142, 143, 144, 159, 160, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 173, 174, 176, 177, 178, 179, 180, 182]|
|:large_blue_circle:|com/starrocks/task/ExportPendingTask.java|0|1|00.00%|[120]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|1|4|25.00%|[413, 414, 417]|
|:large_blue_circle:|com/starrocks/load/ExportFailMsg.java|1|1|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 25 / 31 (80.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/ExportPendingTask.java|0|1|00.00%|[120]|
|:large_blue_circle:|com/starrocks/load/ExportChecker.java|20|25|80.00%|[142, 143, 144, 179, 180]|
|:large_blue_circle:|com/starrocks/load/ExportFailMsg.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|4|4|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java [hunk 1]
```diff
@@ -147,4 +153,34 @@ private void runExportingJobs() {
             }
         }
     }
+
+    private boolean checkBeStatus(ExportJob job) {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java:157]: This function is a little misleading, it says check status, but also change the job status.

File: fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java [hunk 2]
```diff
@@ -117,6 +117,7 @@ private Status makeSnapshots() {
                 if (!GlobalStateMgr.getCurrentSystemInfo().checkBackendAvailable(backendId)) {
                     return Status.CANCELLED;
                 }
+                this.job.setBeStartTime(backendId, backend.getLastStartTime());
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/task/ExportPendingTask.java:120]: Is it enough to update the be's start time when making snapshot? Be may be restarted after the task is sent to be.

File: fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java [hunk 3]
```diff
@@ -147,4 +153,34 @@ private void runExportingJobs() {
...
+
+        boolean beHasErr = false;
+        String errMsg = "";
+        for (Long beId : job.getBeStartTimeMap().keySet()) {
+            Backend be = GlobalStateMgr.getCurrentSystemInfo().getBackend(beId);
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java:162]: Will there be any periodic reports between the BE and the FE about an export job? I think checking for the execution status of BE about the export job will cover more cases, for example when BE is alive but get stuck.

File: fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java (hunk 1 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java]: done

File: fe/fe-core/src/test/java/com/starrocks/load/ExportCheckerTest.java [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+        Object obj = field.get(ExportChecker.class);
+        
+        Map<JobState, ExportChecker> map = (Map<JobState, ExportChecker>) obj;
+        ExportChecker checker = map.get(JobState.EXPORTING);
+        Method method = ExportChecker.class.getDeclaredMethod("checkBeStatus", ExportJob.class);
+        method.setAccessible(true);
+
+        ExportJob job = new ExportJob();
+        job.setBeStartTime(1, 1000L);
+        boolean cancalled = (boolean) method.invoke(checker, job);
```
[the remark this answers is not in the document]
Comment (waittttting) [reply fe/fe-core/src/test/java/com/starrocks/load/ExportCheckerTest.java]: done

File: fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java (hunk 3 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/load/ExportChecker.java:162]: Yes u are right，this PR just handle a case that be restarted. I think if we want to handle all bad caes, like backend stuck, backend be dropped, and so on, we need to modify export's scheduling framework. This may be a big change, not quite sure if it needs to be done now. For now, I want to fix this bad case firstly

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 30 / 36 (83.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/ExportPendingTask.java|0|1|00.00%|[120]|
|:large_blue_circle:|com/starrocks/load/ExportChecker.java|25|30|83.33%|[142, 143, 144, 187, 188]|
|:large_blue_circle:|com/starrocks/load/ExportFailMsg.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|4|4|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test
