### PR TITLE
Fix ASAN check crash since selected column order not match

### LINKED ISSUE #5137: be crash on asan version
### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
*** Check failure stack trace: ***
    @          0xadda70d  google::LogMessage::Fail()
    @          0xaddcb7f  google::LogMessage::SendToLog()
    @          0xadda25e  google::LogMessage::Flush()
    @          0xaddd189  google::LogMessageFatal::~LogMessageFatal()
    @          0x556598f  starrocks::vectorized::AggregateIterator::AggregateIterator()
    @          0x5568fa8  __gnu_cxx::new_allocator<>::construct<>()
    @          0x5568c5a  std::allocator_traits<>::construct<>()
    @          0x55687c8  std::_Sp_counted_ptr_inplace<>::_Sp_counted_ptr_inplace<>()
    @          0x5567f57  std::__shared_count<>::__shared_count<>()
    @          0x5567aec  std::__shared_ptr<>::__shared_ptr<>()
    @          0x55677f1  std::shared_ptr<>::shared_ptr<>()
    @          0x5567561  std::allocate_shared<>()
    @          0x5567249  std::make_shared<>()
    @          0x5563a5e  starrocks::vectorized::new_aggregate_iterator()
    @          0x5008f7d  starrocks::vectorized::TabletReader::_init_collector()
    @          0x5005c6a  starrocks::vectorized::TabletReader::open()
    @          0x4fd3edd  starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2_normal()
    @          0x4fd1357  starrocks::vectorized::SchemaChangeHandler::_do_process_alter_tablet_v2()
    @          0x4fcecb8  starrocks::vectorized::SchemaChangeHandler::process_alter_tablet_v2()
    @          0x9e902a7  starrocks::EngineAlterTabletTask::execute()
    @          0x4ae0001  starrocks::StorageEngine::execute_task()
    @          0x6ca91d8  starrocks::TaskWorkerPool::_alter_tablet()
    @          0x6ca88bb  starrocks::TaskWorkerPool::_alter_tablet_worker_thread_callback()
    @          0x6cd3c2c  std::__invoke_impl<>()
    @          0x6cd3b54  std::__invoke<>()
    @          0x6cd3ac5  _ZNSt6thread8_InvokerISt5tupleIJPFPvS2_EPN9starrocks14TaskWorkerPoolEEEE9_M_invokeIJLm0ELm1EEEES2_St12_Index_tupleIJXspT_EEE
    @          0x6cd3a80  std::thread::_Invoker<>::operator()()
    @          0x6cd396a  std::thread::_State_impl<>::_M_run()
    @          0xc983df0  execute_native_thread_routine
    @     0x7fb273335ea5  start_thread
    @     0x7fb2729508dd  __clone
    @              (nil)  (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`MASTER_ASAN ASAN (build 97cf24f)`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5137

### CODE REVIEW

File: be/src/storage/schema_change.cpp [hunk 1]
```diff
@@ -1679,6 +1660,14 @@ Status SchemaChangeHandler::_parse_request(
         }
     }
 
+    auto selected_column_indexs = chunk_changer->get_mutable_selected_column_indexs();
+    int32_t index = 0;
+    for (const auto& iter : base_to_new) {
```
Comment (imay) [inline be/src/storage/schema_change.cpp:1665]: Nit: it will be easier to understand with 
```
for (int i = 0; i < base_to_new.size(); ++i)
```

**Review by chaoyli — DISMISSED** [review]

**Review by sevev — DISMISSED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
