### PR TITLE
[BugFix] Fixed stats not parsing date literals of "0000-01-01" correctly

### LINKED ISSUE #9866: 【statistics】histogram statistics error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `duplicate_table_with_null` (
  `k1` date NULL COMMENT "",
  `k2` datetime NULL COMMENT "",
  `k3` char(20) NULL COMMENT "",
  `k4` varchar(20) NULL COMMENT "",
  `k5` boolean NULL COMMENT "",
  `k6` tinyint(4) NULL COMMENT "",
  `k7` smallint(6) NULL COMMENT "",
  `k8` int(11) NULL COMMENT "",
  `k9` bigint(20) NULL COMMENT "",
  `k10` largeint(40) NULL COMMENT "",
  `k11` float NULL COMMENT "",
  `k12` double NULL COMMENT "",
  `k13` decimal128(27, 9) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "V2",
"enable_persistent_index" = "false"
);
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1660094546355 http://ip:port/api/db/duplicate_table_with_null/_stream_load
```
3. SELECT  '....'
ANALYZE TABLE table UPDATE HISTOGRAM ON k1
### Expected behavior (Required)
histogram statistics success
### Real behavior (Required)
histogram statistics error
jcndANpGTv

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE c991187 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9866

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java [hunk 1]
```diff
@@ -167,7 +167,8 @@ private void analyzeAnalyzeTypeDesc(ConnectContext session, AnalyzeStmt statemen
                     Column column = analyzeTable.getColumn(columnName);
                     if (column.getType().isComplexType()
                             || column.getType().isJsonType()
-                            || column.getType().isOnlyMetricType()) {
+                            || column.getType().isOnlyMetricType()
+                            || column.getType().isChar() || column.getType().isVarchar()) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java:171]: Why varchar couldn't support histogram?

**Review by liuyehcf — DISMISSED** [review]

**Review by Youngwb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java (hunk 1 above)
Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java:171]: Because our statistical information calculation formulas currently convert the value to double for comparison.
`    public static Statistics estimateColumnToConstantComparison(Optional<ColumnRefOperator> columnRefOperator,
                                                                ColumnStatistic columnStatistic,
                                                                BinaryPredicateOperator predicate,
                                                                OptionalDouble constant,
                                                                Statistics statistics)`

The framework of statistical information estimation needs to be modified. This is the next step. Before this step is completed, the string type should be disabled.

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 29 / 35 (82.86%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnHistogramStatsCacheLoader.java|6|12|50.00%|[144, 145, 146, 147, 178, 179]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyzeStmtAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/statistic/HistogramStatisticsCollectJob.java|9|9|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/statistics/ColumnBasicStatsCacheLoader.java|4|4|100.00%|[]|

**Comment by HangyuanLiu** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
