### PR TITLE
Temporary solution for memory explosion when drop a large number of t…

### LINKED ISSUE #3838: The memory usage of the tablet deletion task is too high.
### Steps to reproduce the behavior (Required)
drop tablet.
The memory usage of the tablet deletion task is 40G, all memory for be is 50G, it's too high. 
### Expected behavior (Required)
reasonable bounds.
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

### PR DESCRIPTION
**Pull request by Astralidea**
…ablets on FE

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3838 #3831

## Problem Summary(Required) ：

This problem is alleviated by splitting the large batch of tasks into small batches by a parameter

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 12 / 37 (32.43%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|11|31|35.48%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 1]
```diff
@@ -7335,23 +7336,55 @@ public void onEraseOlapTable(OlapTable olapTable, boolean isReplay) {
...
+                AgentBatchTask originTasks = entry.getValue();
+                if (originTasks.getTaskNum() > numDropTaskPerBe) {
+                    AgentBatchTask partTask = new AgentBatchTask();
+                    List<AgentTask> allTasks = originTasks.getAllTasks();
+                    int curTask = 1;
+                    for (AgentTask task : allTasks) {
+                        partTask.addTask(task);
+                        if (curTask++ > numDropTaskPerBe) {
+                            AgentTaskExecutor.submit(partTask);
+                            ThreadUtil.sleepAtLeastIgnoreInterrupts(1000);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:7375]: `onEraseOlapTable` is used in `CatalogRecycleBin.eraseTable` which is a synchronized method and this will block a lot of other operations.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 24 / 56 (42.86%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|14|34|41.18%|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|9|16|56.25%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java [hunk 2]
```diff
@@ -691,6 +691,7 @@ private static void deleteFromBackend(Map<Long, TTablet> backendTablets,
                                           long backendId) {
         int deleteFromBackendCounter = 0;
         int addToMetaCounter = 0;
+        int maxTaskSendPerBe = Config.max_agent_task_threads_num;
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/master/ReportHandler.java:694]:
```suggestion
        int maxTaskSendPerBe = Config. max_agent_tasks_send_per_be;
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 3]
```diff
@@ -5000,7 +5001,10 @@ public boolean unprotectDropTable(Database db, long tableId, boolean isForceDrop
 
         db.dropTable(table.getName());
         if (!isForceDrop) {
-            Catalog.getCurrentRecycleBin().recycleTable(db.getId(), table);
+            Table oldTable = Catalog.getCurrentRecycleBin().recycleTable(db.getId(), table);
+            if (oldTable != null && oldTable.getType() == TableType.OLAP) {
+                Catalog.getCurrentCatalog().onEraseOlapTable((OlapTable) oldTable, false);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:5006]: `unprotectDropTable` is called by `dropTable` with the database write lock.
This will block almost all operations in the database.

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 4]
```diff
@@ -7335,23 +7339,55 @@ public void onEraseOlapTable(OlapTable olapTable, boolean isReplay) {
...
                             } // end for replicas
                         }
                     } // end for tablets
                 } // end for indices
             } // end for partitions
-            AgentTaskExecutor.submit(batchTask);
-        }
 
+            int numDropTaskPerBe = Config.max_agent_tasks_send_per_be;
+            for (Map.Entry<Long, AgentBatchTask> entry : batchTaskMap.entrySet()) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:7368]: Drop replica tasks can be executed parallel between backends and this can be a little faster.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 37 / 82 (45.12%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/AgentBatchTask.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|27|55|49.09%|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|9|16|56.25%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 5]
```diff
@@ -692,6 +688,18 @@ protected void runAfterCatalogReady() {
 
     }
 
+    private void postProcessEraseTable(List<RecycleTableInfo> tableToRemove) {
+        for (RecycleTableInfo tableInfo : tableToRemove) {
+            Table table = tableInfo.getTable();
+            long tableId = table.getId();
+            if (table.getType() == TableType.OLAP) {
+                HashMap<Long, AgentBatchTask> batchTaskMap =
+                        Catalog.getCurrentCatalog().onEraseOlapTable((OlapTable) table, false);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:697]: Need to call `sendDropTabletTasks`.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 38 / 83 (45.78%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/AgentBatchTask.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|28|55|50.91%|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|9|17|52.94%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java [hunk 6]
```diff
@@ -4979,37 +4995,67 @@ public void dropTable(DropTableStmt stmt) throws DdlException {
...
         }
 
         table.onDrop();
 
         db.dropTable(table.getName());
         if (!isForceDrop) {
-            Catalog.getCurrentRecycleBin().recycleTable(db.getId(), table);
+            Table oldTable = Catalog.getCurrentRecycleBin().recycleTable(db.getId(), table);
+            if (oldTable != null && oldTable.getType() == TableType.OLAP) {
+                batchTaskMap = Catalog.getCurrentCatalog().onEraseOlapTable((OlapTable) oldTable, false);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:5048]: should not erase table here.

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/Catalog.java:5048]: this logic is move from recycleTable when eraseTableWithSameName remove oldTable send batch task.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 37 / 83 (44.58%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/task/AgentBatchTask.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/master/ReportHandler.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/catalog/Catalog.java|27|55|49.09%|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|9|17|52.94%|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
