### PR TITLE
[BugFix]Fix Tableau `Table` missing

### LINKED ISSUE #55626: tableau is broken
starrocks 3.4

using jdbc connection
Tableau looks for tables in database
```
SELECT TABLE_SCHEMA AS TABLE_CAT, NULL AS TABLE_SCHEM, TABLE_NAME, CASE WHEN TABLE_TYPE='BASE TABLE' THEN CASE WHEN TABLE_SCHEMA='mysql' OR TABLE_SCHEMA='performance_schema' OR TABLE_SCHEMA='sys' THEN 'SYSTEM TABLE' ELSE 'TABLE' END WHEN TABLE_TYPE='TEMPORARY' THEN 'LOCAL_TEMPORARY' ELSE TABLE_TYPE END AS TABLE_TYPE, TABLE_COMMENT AS REMARKS, NULL AS TYPE_CAT, NULL AS TYPE_SCHEM, NULL AS TYPE_NAME, NULL AS SELF_REFERENCING_COL_NAME, NULL AS REF_GENERATION FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'eshishkin' HAVING TABLE_TYPE IN ('LOCAL TEMPORARY','TABLE','VIEW',null,null) ORDER BY TABLE_TYPE, TABLE_SCHEMA, TABLE_NAME
```
and gets nothing

because we now return `TABLE_TYPE: BASE TABLE`

### PR DESCRIPTION
**Pull request by Zac-saodiseng**
## Why I'm doing:
When Tableau joins StarRocks, some tables are missing.
## What I'm doing:

Fixes #55626 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java [hunk 1]
```diff
@@ -59,19 +59,20 @@ public void setUp() {
 
     @Test
     public void testGetMysqlType() {
-        Assert.assertEquals("BASE TABLE", new Table(TableType.OLAP).getMysqlType());
-        Assert.assertEquals("BASE TABLE", new Table(TableType.OLAP_EXTERNAL).getMysqlType());
-        Assert.assertEquals("BASE TABLE", new Table(TableType.CLOUD_NATIVE).getMysqlType());
+        String mysqlTableType = Table.getTableTypeForMysql();
```
Comment (Astralidea) [inline fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java:62]: This test seems to be more or less equivalent to not testing at all. It would be better to show what it should look like when `GlobalVariable.version` is set to 5, and what it should look like when it's set to 8.

For example, if we made a mistake in the code and returned `ABC` instead of the `BASE TABLE`, your test would still pass, but that would actually be incorrect.

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/Table.java [hunk 2]
```diff
@@ -603,11 +604,25 @@ public String getMysqlType() {
...
                 return "SYSTEM VIEW";
             default:
-                // external table also returns "BASE TABLE" for BI compatibility
-                return "BASE TABLE";
+                // external table also returns "BASE TABLE" or "TABLE" for BI compatibility
+                return getTableTypeForMysql();
         }
     }
 
+    public static String getTableTypeForMysql() {
```
Comment (alvin-celerdata) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Table.java:612]: Please add some comments for the function, to tell others why this function is needed.

File: fe/fe-core/src/main/java/com/starrocks/catalog/Table.java [hunk 3]
```diff
@@ -603,11 +604,25 @@ public String getMysqlType() {
...
+        String version = GlobalVariable.version;
+        if (version == null || version.isEmpty()) {
+            return "BASE TABLE";
+        }
+        if (version.startsWith("5")) {
+            return "BASE TABLE";
+        } else if (version.startsWith("8")) {
+            // compatibility for mysql8.0+
+            return "TABLE";
+        }
```
Comment (alvin-celerdata) [inline fe/fe-core/src/main/java/com/starrocks/catalog/Table.java:622]: It is not a good way to compare version with String. 
Suppose that when there are versions like "50.1" or "80.2", the code won't work at that time.
Please parse the version into major versions and then compare the major version by Integer

File: fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java [hunk 4]
```diff
@@ -58,7 +59,8 @@ public void setUp() {
     }
 
     @Test
-    public void testGetMysqlType() {
+    public void testGetMysqlType_Version5() {
+        GlobalVariable.version = "5.7.0";
```
Comment (alvin-celerdata) [inline fe/fe-core/src/test/java/com/starrocks/catalog/TableTest.java:63]: Also you need to handle invalid version situation, in which the version is given a invalid version like "a.b.c", the process should work in a defined way.

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
