### PR TITLE
[BugFix] Fix FE publish timeout when BE publish succeeds but fails to send a response to FE

### LINKED ISSUE #5659: FE publish timeout when BE publish succeeds but fails to send a response to FE
### Steps to reproduce the behavior (Required)
1. mock BE not relay publish request
2. `insert into` t values(xxx)
3. select * from t

### Expected behavior (Required)
xxx
 
### Real behavior (Required)
empty result

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5659

## Problem Summary(Required) ：

BE publish succeeds but fails to send a response to FE, FE will never success

### CODE REVIEW

**Comment by meegoo** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|2|50.00%|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by imay — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java [hunk 1]
```diff
@@ -700,6 +700,10 @@ public boolean canTxnFinished(TransactionState txn, Set<Long> errReplicas, Set<L
                                             && (unfinishedBackends == null
                                             || !unfinishedBackends.contains(replica.getBackendId()))) {
                                         ++successHealthyReplicaNum;
+                                    // replica report version has greater cur transaction commit version
+                                    // This can happen when the BE publish succeeds but fails to send a response to FE
+                                    } else if (replica.getVersion() >= partitionCommitInfo.getVersion()) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:705]: There has a same version check following.
I think it is better to move the check to front, rather than adding new one.

Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:705]: the difference is `!errReplicas.contains(replica.getId())` condition, if it not true, it will execute `errReplicas.remove(replica.getId())`, otherwise all the way need to judge this condition

Comment (wyb) [reply fe/fe-core/src/main/java/com/starrocks/transaction/DatabaseTransactionMgr.java:705]: if replica version >= commit info version, the replica is healthy and is reasonable to remove it from `errReplicas`.

**Review by wyb — APPROVED** [review]

**Comment by meegoo** [comment]
https://github.com/Mergifyio backport branch-2.1

**Comment by meegoo** [comment]
@Mergifyio backport branch-2.1

**Comment by meegoo** [comment]
https://github.com/Mergifyio backport branch-2.2

**Comment by meegoo** [comment]
@Mergifyio backport branch-2.2

**Comment by meegoo** [comment]
@Mergifyio backport branch-2.0

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/DatabaseTransactionMgr.java|1|2|50.00%|
