### PR TITLE
[BugFix] Fix the failure of querying extenal table that contains struc columns

### LINKED ISSUE #9020: Select from external hive table failed when original table contains map and struct
### Steps to reproduce the behavior (Required)
- create hive table:
```
CREATE EXTERNAL TABLE `surface_tracking_enriched_events`(`rheosheader` struct<eventcreatetimestamp:bigint,eventsenttimestamp:bigint,schemaid:int,eventid:string,producerid:string> COMMENT '', `datasrc` string COMMENT '', `bizdtl` map<string,string> COMMENT '', `trackableid` string COMMENT '', `itemdtl` map<string,string> COMMENT '')
PARTITIONED BY (`session_start_dt` string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe'
WITH SERDEPROPERTIES (
  'serialization.format' = '1'
)
STORED AS
  INPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat'
  OUTPUTFORMAT 'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
TBLPROPERTIES (
  'PARQUET.COMPRESS' = 'SNAPPY'
)
```
- insert data:
```
INSERT INTO surface_tracking_enriched_events PARTITION(session_start_dt="2022-07-15") select NAMED_STRUCT('eventcreatetimestamp',100L,'eventsenttimestamp',200L,'schemaid',300,'eventid','EVENTID1','producerid','PRODUCERID') as rheosheader, "datasrc", map("Mathematics","78"), "trackableid", map("Mathematics","78");
```
- create external table:
```
CREATE EXTERNAL TABLE `surface_tracking_enriched_events_external_v2` (
  `trackableid` varchar(65533) NULL COMMENT "",
  `session_start_dt` varchar(65533) NULL COMMENT ""
) ENGINE=HIVE 
COMMENT "PARTITION BY (session_start_dt)"
PROPERTIES (
"database" = "myhive",
"table" = "surface_tracking_enriched_events",
"resource" = "hive0"
);
```

- select from external table

### Expected behavior (Required)
return result

### Real behavior (Required)
```
MySQL [myhive]> select * from surface_tracking_enriched_events_external_v2;
ERROR 1064 (HY000): failed to find shared buffer based on offset
```

### StarRocks version (Required)
main branch

### PR DESCRIPTION
**Pull request by GavinMar**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9020

## Problem Summary(Required) ：

For map or struct columns, parquet reader parses the column meta to a flat vector,
each column meta should be located by physical_column_index rather than col_idx_in_parquet.
The current code uses col_idx_in_parquet when setting io ranges, while uses physical_column_index when reading column data, resulting in incorrect column meta information and mismatched data offset.

### CODE REVIEW

**Review by DorianZheng — DISMISSED** [review]
LGTM

File: be/src/formats/parquet/group_reader.cpp [hunk 1]
```diff
@@ -214,7 +214,8 @@ vectorized::ChunkPtr GroupReader::_create_read_chunk(const std::vector<int>& col
 void GroupReader::collect_io_ranges(std::vector<SharedBufferedInputStream::IORange>* ranges, int64_t* end_offset) {
     int64_t end = 0;
     for (const auto& column : _param.read_cols) {
-        auto& rg = _row_group_metadata->columns[column.col_idx_in_parquet].meta_data;
+        auto schema_node = _param.file_metadata->schema().get_stored_column_by_idx(column.col_idx_in_parquet);
```
Comment (imay) [inline be/src/formats/parquet/group_reader.cpp:217]: Better to add some comments to explain why get metadata from row_group_meta rather than file_meta.

Comment (GavinMar) [reply be/src/formats/parquet/group_reader.cpp:217]: > Better to add some comments to explain why get metadata from row_group_meta rather than file_meta.

Because we need some row group meta (such as data_page_offset and total_compressed_size) to make up the shared buffer range of this group. If use file meta, we still need to locate row group by the group index, it is unnecessary.

Comment (imay) [reply be/src/formats/parquet/group_reader.cpp:217]: yeah, better to write this to the code and make others know

Comment (GavinMar) [reply be/src/formats/parquet/group_reader.cpp:221]: > yeah, better to write this to the code and make others know

OK

**Review by imay — DISMISSED** [review]

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test

**Review by dirtysalt — DISMISSED** [review]

File: be/src/formats/parquet/group_reader.cpp [hunk 2]
```diff
@@ -214,21 +214,44 @@ vectorized::ChunkPtr GroupReader::_create_read_chunk(const std::vector<int>& col
...
     for (const auto& column : _param.read_cols) {
-        auto& rg = _row_group_metadata->columns[column.col_idx_in_parquet].meta_data;
-        int64_t offset = 0;
-        if (rg.__isset.dictionary_page_offset) {
-            offset = rg.dictionary_page_offset;
+        // 1. We collect column io ranges for each row group to make up the shared buffer, so we get column
+        // metadata (such as page offset and compressed_size) from _row_group_meta directly rather than file_metadata.
+        // 2. For map or struct columns, the physical_column_index indicates the real column index in rows group meta,
+        // and it may not be equal to col_idx_in_chunk.
+        // 3. For array type, the physical_column_index is 0, we need to iterator the children and
```
Comment (DorianZheng) [inline be/src/formats/parquet/group_reader.cpp:221]: typo: iterator -> iterate

**Review by DorianZheng — DISMISSED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by GavinMar** [comment]
run starrocks_admit_test
