### PR TITLE
[BugFix] Unify the logic of Function and Global Function and modify it to use FunctionId as the unique identifier

### LINKED ISSUE #19554: after drop function and create a new one which has same name still had permission
### Steps to reproduce the behavior (Required)
````sql
CREATE GLOBAL FUNCTION Echoint(int)
                            RETURNS int
                            properties
                            (
                                "symbol" = "Echoint",
                                "type" = "StarrocksJar",
                                "file" = "Echoint.jar"
                            );
GRANT USAGE ON GLOBAL FUNCTION Echoint(int) TO USER jack;
drop global function echoint(int);
CREATE GLOBAL FUNCTION Echoint(int)
                            RETURNS int
                            properties
                            (
                                "symbol" = "Echoint",
                                "type" = "StarrocksJar",
                                "file" = "Echoint.jar"
                            );
````
switch to user jack
````sql
select echoint(1);
````
### Expected behavior (Required)
`ERROR 1064 (HY000): Access denied. Found UDF: __global_udf_db__.echoint and need the USAGE privilege for GLOBAL FUNCTION`
### Real behavior (Required)
`query ok`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`BRANCH-3.0-RELEASE-7aa19b1`

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19554
#19552
#19541
#19777 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeBuiltinConstants.java [hunk 1]
```diff
@@ -39,4 +40,16 @@ public class PrivilegeBuiltinConstants {
...
+
+    public static final long ALL_CATALOGS_ID = -1; // -1 represent all catalogs
+
+    public static final String ALL_DATABASES_UUID = "ALL_DATABASES_UUID"; // represent all databases
+    public static final long ALL_DATABASE_ID = -2; // -2 represent all databases
+
+    public static final String ALL_TABLES_UUID = "ALL_TABLES_UUID"; // represent all tables
+
+    public static final long ALL_FUNCTIONS_ID = -3; // -3 represent all functions
+    public static final long GLOBAL_FUNCTION_DEFAULT_DATABASE_ID = -4; // global function default database id
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeBuiltinConstants.java:52]: this will put global function before fuzzy matching non-global function, and we have "short circuit" logic when checking, this may cause wrong checking result.
image

Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/privilege/PrivilegeBuiltinConstants.java:52]: we can modify the compareTo api in FunctionPEntryObject

File: fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationManager.java [hunk 2]
```diff
@@ -247,12 +247,27 @@ private void initPrivilegeCollectionAllObjects(
...
 
+            case FUNCTION:
+                objects.add(provider.generateFunctionObject(objectType,
+                        PrivilegeBuiltinConstants.ALL_DATABASE_ID,
+                        PrivilegeBuiltinConstants.ALL_FUNCTIONS_ID,
+                        globalStateMgr));
+                collection.grant(objectType, actionList, objects, false);
+                break;
+
+            case GLOBAL_FUNCTION:
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/privilege/AuthorizationManager.java:263]: why still keep this

**Review by nshangyiming — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
