### PR TITLE
[BugFix] Remove colocated index from memory

### LINKED ISSUE #5681: remove the colocate_with attribute on the tb_kpi_timeliness  table, run the show proc '/colocation_group/'; Command can still query the table
### Steps to reproduce the behavior (Required)
1.执行 ALTER TABLE tb_kpi_timeliness SET ("colocate_with" = "");命令
2. show create table 查看表的colocate_with属性已经移除
image

### Expected behavior (Required)
 show proc '/colocation_group' 查询不到该表
### Real behavior (Required)
 show proc '/colocation_group' 仍然可以查询的到该表
image

### StarRocks version (Required)
2.0.4

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #5681

## Problem Summary(Required) ：

This is a legacy bug that will keep colocated groups in memory FOREVER.
The root cause is probably that we intended to skip change `TabletInvertedIndex` when making a checkpoint. Since `table.delete()` will call `invertedIndex.deleteTablet()` function that will eventually change `TabletInvertedIndex`, we won't call `table.delete()` in checkpointer. Unfortunately, this function is also responsible for removing colocated groups from memory. As a result, when making a checkpoint, the colocate group index will stay in the final image and never be removed.

1. Call `table.delete()` when replaying a journal of erasing table.
2. Add an extra function `cleanupInvalidDbOrTable` to clean all the invalid colocated groups of which table or database is not found. We should clean up every time an image is loaded so that all legacy colocated groups can clean up at once.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java [hunk 1]
```diff
@@ -114,7 +114,7 @@ public String toString() {
     }
 
     // group_name -> group_id
-    private Map<String, GroupId> groupName2Id = Maps.newHashMap();
+    protected Map<String, GroupId> groupName2Id = Maps.newHashMap();
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:117]:
```suggestion
    private Map<String, GroupId> groupName2Id = Maps.newHashMap();
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 22 / 23 (95.65%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ColocateTableIndex.java|20|21|95.24%|[746]|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|2|2|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 2]
```diff
@@ -373,10 +373,8 @@ public synchronized void replayEraseTable(long tableId) {
                 Runnable runnable = null;
                 Table table = tableInfo.getTable();
                 nameToTableInfo.remove(dbId, table.getName());
-                if (!isCheckpointThread()) {
-                    runnable = table.delete(true);
-                }
-                if (runnable != null) {
+                runnable = table.delete(true);
```
Comment (sduzh) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:376]: I'm not familiar with the code logic here, so it's safe to call `table.delete()` from  checkpoint thread now?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:376]: I think so. As I wrote in the description of this PR, it eventually call `TabletInvertedIndex#deleteTablet` function which will do nothing if current thread is checkpoint thread. So there is no need to check it here.

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java [hunk 3]
```diff
@@ -849,4 +851,34 @@ public void replayModifyTableColocate(TablePropertyInfo info) {
...
+            if (database == null) {
+                LOG.warn("cannot find db {}, will remove invalid table {} from group {}",
+                        dbId, tableId, entry.getValue());
+            } else {
+                Table table = globalStateMgr.getTableIncludeRecycleBin(database, tableId);
+                if (table != null) {
+                    // this is a valid table/database, do nothing
+                    continue;
+                }
+                LOG.warn("cannot find table {} in db {}, will remove invalid table {} from group {}",
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:874]: The table is not found in normal cases. So the warning log is useless and misunderstood.

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java [hunk 4]
```diff
@@ -849,4 +851,34 @@ public void replayModifyTableColocate(TablePropertyInfo info) {
...
+                        tableId, dbId, tableId, entry.getValue());
+            }
+            badTableIds.add(tableId);
+        }
+        LOG.warn("remove {} invalid tableid: {}", badTableIds.size(), badTableIds);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:879]: The same useless log.

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java (hunk 2 above)
Comment (sduzh) [reply fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:376]: Got it, thx.

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java [hunk 5]
```diff
@@ -849,4 +851,34 @@ public void replayModifyTableColocate(TablePropertyInfo info) {
...
+     * for legacy reason, all the colocate group index cannot be properly removed
+     * we have to add a cleanup function on start when loading image
+     */
+    protected void cleanupInvalidDbOrTable(GlobalStateMgr globalStateMgr) {
+        List<Long> badTableIds = new ArrayList<>();
+        for (Map.Entry<Long, GroupId> entry : table2Group.entrySet()) {
+            long dbId = entry.getValue().dbId;
+            long tableId = entry.getKey();
+            Database database = globalStateMgr.getDbIncludeRecycleBin(dbId);
+            if (database == null) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:865]: Where to remove the dbId?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:865]: Normally database is removed by the CatalogRecycleBin and CatalogRecycle will remove the colocate index from memory as well. But for those who have just upgraded from an older version, we should provide a mechanism to remove colocate index that remains in memory because of this bug. So I use this function to do this one-time job when loading an image.

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java (hunk 3 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:874]: This is not a normal cases. It should only happen after upgraded from an older version.

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by padmejin** [comment]
@Mergifyio backport branch-2.4 branch-2.3 branch-2.2 branch-2.1 branch-2.0
Lo siento, ¡tenemos demasiadas ramas!
