### PR TITLE
[BugFix] fix the extractPath of asyncProfiler

### LINKED ISSUE #64502: ProfileCollector compatibility issue on ARM
### Steps to reproduce the behavior (Required)

The ProfileCollector doesn't work on ARM platform.
```
java.lang.UnsatisfiedLinkError: /tmp/libasyncProfiler-339356926318411770.so: /tmp/libasyncProfiler-339356926318411770.so: failed to map segment from shared object
	at jdk.internal.loader.NativeLibraries.load(Native Method) ~[?:?]
	at jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232) ~[?:?]
	at jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174) ~[?:?]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394) ~[?:?]
	at java.lang.Runtime.load0(Runtime.java:755) ~[?:?]
	at java.lang.System.load(System.java:1970) ~[?:?]
	at one.profiler.AsyncProfiler.getInstance(AsyncProfiler.java:45) ~[async-profiler-4.0.jar:?]
	at one.profiler.AsyncProfiler.getInstance(AsyncProfiler.java:26) ~[async-profiler-4.0.jar:?]
	at com.starrocks.memory.ProcProfileCollector.collectCPUProfile(ProcProfileCollector.java:88) ~[starrocks-fe.jar:?]
	at com.starrocks.memory.ProcProfileCollector.runAfterCatalogReady(ProcProfileCollector.java:58) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.FrontendDaemon.runOneCycle(FrontendDaemon.java:72) ~[starrocks-fe.jar:?]
	at com.starrocks.common.util.Daemon.run(Daemon.java:98) ~[starrocks-fe.jar:?]
```

### StarRocks version (Required)
- 3.5.6
- ARM platform

### PR DESCRIPTION
**Pull request by murphyatwork**
## What I'm doing:

Fixes #64502

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> Set AsyncProfiler extract path to a safe location and add a unit test for ProcProfileCollector profiling output.
> 
> - **Profiling setup**:
>   - Set `one.profiler.extractPath` to `Config.STARROCKS_HOME_DIR + "/bin/"` in `prepareLibrary()` when unset, avoiding failures on noexec `/tmp`.
>   - Invoke `prepareLibrary()` in `runAfterCatalogReady()`.
> - **API**:
>   - Add `getProfileLogDir()` to expose the profile output directory.
> - **Tests**:
>   - Add `ProcProfileCollectorTest` to verify profile directory creation and that CPU profile `.tar.gz` files increase after runs.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit dfc6daf35cc07df165eb99f6d477f97dba60a4c5. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java [hunk 1]
```diff
@@ -65,6 +67,21 @@ protected void runAfterCatalogReady() {
...
+    // However, if /tmp is mounted with the "noexec" option, loading the library will fail.
+    // To avoid this issue, we explicitly set 'one.profiler.extractPath' to a directory with execute permissions.
+    // See prepareLibrary() for how the extraction path is set to a safer default under STARROCKS_HOME.
+    // See https://github.com/StarRocks/starrocks/issues/64502
+    private void prepareLibrary() {
+        final String libPathProperty = "one.profiler.extractPath";
+        String value = System.getProperty(libPathProperty);
+        if (StringUtils.isEmpty(value)) {
+            String path = Config.STARROCKS_HOME_DIR + "/bin/";
+            System.setProperty(libPathProperty, path);
```
[the remark this answers is not in the document]
Comment (murphyatwork) [reply fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java]: it's guaranteed to be NotNull

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java [hunk 2]
```diff
@@ -65,6 +67,28 @@ protected void runAfterCatalogReady() {
         deleteExpiredFiles();
     }
 
+    public String getProfileLogDir() {
+        return profileLogDir;
+    }
+
+    // AsyncProfiler depends on the native library libasyncProfiler.so, which is bundled inside the JAR.
+    // By default, it extracts this library to the /tmp directory in order to load it.
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java:75]: zstd-jni-1.5.4-2.jar/netty-transport-native-epoll-4.1.128.Final-linux-x86_64.jar on BE side has embedded .so inside the jar, will it have the same issue?

**Comment by alvin-phoenix-ai** [comment]
@mergify rebase

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java (hunk 2 above)
Comment (murphyatwork) [reply fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java:75]: i think so, if it's using a `.so` library

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java (hunk 2 above)
Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java:75]: so the same fix shall applied to Backend as well?

Comment (murphyatwork) [reply fe/fe-core/src/main/java/com/starrocks/memory/ProcProfileCollector.java:75]: I think so, but it's not urgent.

**Review by kevincai — APPROVED** [review]
