### PR TITLE
[BugFix] Fix bug submit insert not work and add more defensive check

### LINKED ISSUE #2328: Replace std::bitset<16> in ColumnReader with uint16_t
I thought the size of `std::bitset<16>` is 2 bytes, but it turns out it's 8 bytes
```
#include <bitset>
#include <iostram>

int main() {
    std::cout << sizeof(std::bitset<2>) << std::endl;
    std::cout << sizeof(std::bitset<8>) << std::endl;
    std::cout << sizeof(std::bitset<16>) << std::endl;
    std::cout << sizeof(std::bitset<32>) << std::endl;
    std::cout << sizeof(std::bitset<64>) << std::endl;
    std::cout << sizeof(std::bitset<128>) << std::endl;
    return 0;
}
```
Output:
```
8
8
8
8
8
16
```

So using `uint16_t` instead of `std::bitset<16>` can give us a smaller `ColumnReader`

https://github.com/StarRocks/starrocks/blob/a0343a78460c9f878ee424a857d44dc9f67a4543/be/src/storage/rowset/segment_v2/column_reader.h#L255

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/StarRocksTest/issues/2328

## Problem Summary(Required) ：

Fix some issues introduced by #20610.
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 20 / 31 (64.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/Task.java|0|1|00.00%|[202]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|1|6|16.67%|[586, 587, 633, 634, 635]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRun.java|1|2|50.00%|[284]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|6|9|66.67%|[46, 47, 52]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|9|10|90.00%|[267]|
|:large_blue_circle:|com/starrocks/scheduler/Constants.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeActions.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 1]
```diff
@@ -582,6 +582,10 @@ public TGetTaskInfoResult getTasks(TGetTasksParams params) throws TException {
         List<Task> taskList = taskManager.showTasks(null);
 
         for (Task task : taskList) {
+            if (task.getDbName() == null) {
+                LOG.warn("Ignore the task db information is incorrect: " + task);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java:586]:
```suggestion
                LOG.warn("Ignore the task because db information is incorrect: " + task);
```

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 2]
```diff
@@ -626,6 +630,10 @@ public TGetTaskRunInfoResult getTaskRuns(TGetTasksParams params) throws TExcepti
         List<TaskRunStatus> taskRunList = taskManager.showTaskRunStatus(null);
 
         for (TaskRunStatus status : taskRunList) {
+            if (status.getDbName() == null) {
+                LOG.warn("Ignore the task status db information is incorrect: " + status);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java:634]:
```suggestion
                LOG.warn("Ignore the task status because db information is incorrect: " + status);
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 20 / 31 (64.52%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/Task.java|0|1|00.00%|[202]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|1|6|16.67%|[586, 587, 633, 634, 635]|
|:large_blue_circle:|com/starrocks/scheduler/TaskRun.java|1|2|50.00%|[284]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|6|9|66.67%|[46, 47, 52]|
|:large_blue_circle:|com/starrocks/sql/analyzer/Analyzer.java|9|10|90.00%|[267]|
|:large_blue_circle:|com/starrocks/scheduler/Constants.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeActions.java|1|1|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
