### PR TITLE
Fix cross join on-predicate bugs

### LINKED ISSUE #2606: CTE query result unstable
### Steps to reproduce the behavior (Required)
1. CREATE TABLE:
```
CREATE TABLE `duplicate_tbl` (
                    `k1`  date,
                    `k2`  datetime,
                    `k3`  char(20),
                    `k4`  varchar(20),
                    `k5`  boolean,
                    `k6`  tinyint,
                    `k7`  smallint,
                    `k8`  int,
                    `k9`  bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9)
                ) ENGINE=OLAP
                DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3
                PROPERTIES ("replication_num" = "1");
CREATE TABLE `unique_tbl` (
                     `k1` date,
                     `k2` datetime,
                     `k3` char(20),
                     `k4` varchar(20),
                     `k5` boolean,
                     `k6` tinyint,
                     `k7` smallint,
                     `k8` int,
                     `k9` bigint,
                     `k10` largeint,
                     `k11` float,
                     `k12` double,
                     `k13` decimal(27,9)
                 ) ENGINE=OLAP
                 UNIQUE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                 DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                 PROPERTIES ("replication_num" = "1");
CREATE TABLE `aggregate_tbl` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint sum,
                    `k7` smallint sum,
                    `k8` int sum,
                    `k9` bigint max,
                    `k10` largeint max,
                    `k11` float min,
                    `k12` double min,
                    `k13` decimal(27,9) sum
                ) ENGINE=OLAP
                AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                PROPERTIES ("replication_num" = "1");
CREATE TABLE `duplicate_par_tbl` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint,
                    `k7` smallint,
                    `k8` int,
                    `k9` bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9)
                ) ENGINE=OLAP
                DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                PARTITION BY RANGE(`k1`)
                (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                )
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                PROPERTIES ("replication_num" = "1");
CREATE TABLE `unique_par_tbl` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint,
                    `k7` smallint,
                    `k8` int,
                    `k9` bigint,
                    `k10` largeint,
                    `k11` float,
                    `k12` double,
                    `k13` decimal(27,9)
                ) ENGINE=OLAP
                UNIQUE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                COMMENT "OLAP"
                PARTITION BY RANGE(`k1`)
                (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                )
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                PROPERTIES ("replication_num" = "1");
CREATE TABLE `aggregate_par_tbl` (
                    `k1` date,
                    `k2` datetime,
                    `k3` char(20),
                    `k4` varchar(20),
                    `k5` boolean,
                    `k6` tinyint sum,
                    `k7` smallint sum,
                    `k8` int sum,
                    `k9` bigint max,
                    `k10` largeint max,
                    `k11` float min,
                    `k12` double min,
                    `k13` decimal(27,9) sum
                ) ENGINE=OLAP
                AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
                COMMENT "OLAP"
                PARTITION BY RANGE(`k1`)
                (
                    PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                    PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                    PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
                )
                DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
                PROPERTIES ("replication_num" = "1");
CREATE TABLE `primary_tbl` (
                `k1` date NOT NULL,
                `k2` datetime NOT NULL,
                `k3` string NOT NULL,
                `k4` string NOT NULL,
                `k5` boolean NOT NULL,
                `k6` tinyint,
                `k7` smallint,
                `k8` int,
                `k9` bigint,
                `k10` largeint,
                `k11` float,
                `k12` double,
                `k13` decimal(27,9)
            ) ENGINE=OLAP
            PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
            COMMENT "OLAP"
            DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
            PROPERTIES ("replication_num" = "3");
CREATE TABLE `primary_par_tbl` (
                `k1` date not null,
                `k2` datetime not null,
                `k3` varchar(20) not null,
                `k4` varchar(20) not null,
                `k5` boolean not null,
                `k6` tinyint,
                `k7` smallint,
                `k8` int,
                `k9` bigint,
                `k10` largeint,
                `k11` float,
                `k12` double,
                `k13` decimal(27,9)
            ) ENGINE=OLAP
            PRIMARY KEY(`k1`, `k2`, `k3`, `k4`, `k5`)
            COMMENT "OLAP"
            PARTITION BY RANGE(`k1`)
            (
                PARTITION `p202006` VALUES LESS THAN ("2020-07-01"),
                PARTITION `p202007` VALUES LESS THAN ("2020-08-01"),
                PARTITION `p202008` VALUES LESS THAN ("2020-09-01")
            )
            DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3
            PROPERTIES (
                "replication_num" = "3");
```

2. STREAM LOAD DATA INTO EACH TABLE:
```
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297071338 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/duplicate_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297071534 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/duplicate_par_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297071678 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/unique_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297071817 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/unique_par_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297071968 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/aggregate_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1641297072112 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/aggregate_par_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data_value_null -XPUT -H label:stream_load_1641297072259 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/primary_tbl/_stream_load
curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/StarRocksTest/lib/../common/data/basic_types_data_value_null -XPUT -H label:stream_load_1641297072568 http://***.***.***.***:8434/api/test_multi_cte_1641297071282/primary_par_tbl/_stream_load
```

3. SELECT:
```
select a.k3,a.k4,b.k6,b.k8,b.k10 from unique_par_tbl partition(p202007,p202006) a
        right join primary_tbl b
        on a.k10 = b.k10
        and a.k6 = b.k6
        where exists(
        with tbl1 as
        (select case t1.k5 when true then 'YES' when false then 'NO' else 'UNKNOWN' end as flag,t2.k3,t2.k4,t1.k1,t1.k6,t2.k8,t2.k9 from duplicate_tbl t1
         cross join (with tbl2 as
          (select * from unique_tbl where k1 != (with tbl3 as
           (select distinct k1 from duplicate_tbl where k5 is not null and k13 > 30)
           select k1 from tbl3 order by 1 desc limit 1)
          ) select * from tbl2) t2
          on t1.k13 = t2.k13 and t1.k1 = t2.k1)
        select * from tbl1)
        and a.k3 != 'beijing'
        and b.k1 is not null;
```

### Expected behavior (Required)
stable result

### Real behavior (Required)
query return unstable result:
23552 rows in set
or
Empty set

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER 38500d0 |
+------------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #2606

## Problem Summary(Required) ：

There contains three bugs：

1. on-predicate of cross join will repeat add in PlanFragementBuilder, like:
```
select * from t1 cross join t2 on t1.v1 != t2.v2 and t1.v2 != t2.v2
```

will produce plan:
```
|   2:CROSS JOIN                                                                                |
|   |  cross join:                                                                              |
|   |  predicates: (1: v1 != 4: v1) AND (2: v2 != 5: v2), (1: v1 != 4: v1) AND (2: v2 != 5: v2)
```

2. cross join with on-predicate can't transform to inner join, like
```
select * from t1 cross join t2 on t1.v1 = t2.v2
```

the plan:
```
|   2:CROSS JOIN                                                                                |
|   |  cross join:                                                                              |
|   |  predicates: 1: v1 = 4: v1
```

3. cross join with on-predicate will push down limit, will return error result

### CODE REVIEW

**Comment by Seaven** [comment]
run starrocks_be_unittest

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownLimitJoinRule.java [hunk 1]
```diff
@@ -44,6 +44,14 @@ public boolean check(OptExpression input, OptimizerContext context) {
             return Lists.newArrayList(child);
         }
 
+        if (joinType.isSemiAntiJoin()) {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownLimitJoinRule.java:47]: This judgment does not seem to go, because there is an if (joinType.isInnerJoin() || joinType.isSemiAntiJoin()) before, and return ends the function

Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownLimitJoinRule.java:47]: semi anti join and inner join has checked before, can not run here

**Review by Youngwb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
