### PR TITLE
[BugFix] Fix retry upload failure when backup files using HDFS filesystem interface

### LINKED ISSUE #53631: Backup bug: Cannot truncate a file by hdfs writer
### Steps to reproduce the behavior (Required)
We ran into this error when backup on azure blobstore. (only on azure, not aws)

The State of backup is always UPLOADING for a few hours already.
The db size is just 2TiB
be.log
```
W20241204 22:07:13.767381 124338109929024 agent_task.cpp:645] 
Fail to upload job id=422199148 msg=Cannot truncate a file by hdfs writer, 
path=wasbs://container@accountname.blob.core.windows.net/backup/celostar/__starrocks_repository_celostar/__ss_ae941e934_6b1b_48d1_b477_deb6c6a2acc7_e3b880fe_42b5_4d3d_8632_d64e89cdc175_ff50afd8_a85e_4502_aaf4_e40bcf4b8da8/__ss_content/__db_422081644/__tbl_422096351/__part_422096350/__idx_422096352/__422106043/020000000014a83a004a567778ccaf8e6dd12dd774b579a7_0_114_0.cols.part

I20241204 22:07:13.767730 124338109929024 agent_task.cpp:663] Uploaded task signature=422202665 job id=422199148
```

### Expected behavior (Required)
no error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by srlch**
## Why I'm doing:
HDFS filesystem interface does not support file mode with CREATE_OR_OPEN_WITH_TRUNCATE. If we want to new writable file but it has already existed, it will fail in this case. It means that it is impossible to retry upload in many cases in backup process.

## What I'm doing:
Use `O_WRONLY` flag for `hdfsOpenFile` which implies `O_TRUNCAT`.

Fixes #53631

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: be/src/fs/hdfs/fs_hdfs.cpp [hunk 1]
```diff
@@ -572,7 +584,8 @@ StatusOr<std::unique_ptr<WritableFile>> HdfsFileSystem::new_writable_file(const
     RETURN_IF_ERROR(HdfsFsCache::instance()->get_connection(namenode, hdfs_client, _options));
     int flags = O_WRONLY;
     if (opts.mode == FileSystem::CREATE_OR_OPEN_WITH_TRUNCATE) {
-        if (auto st = _path_exists(hdfs_client->hdfs_fs, path); st.ok()) {
+        if (auto st = _path_exists(hdfs_client->hdfs_fs, path);
```
Comment (kevincai) [inline be/src/fs/hdfs/fs_hdfs.cpp:587]: https://github.com/apache/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs-native-client/src/main/native/libhdfs/include/hdfs/hdfs.h#L439

```
     * @param flags - an | of bits/fcntl.h file flags - supported flags are O_RDONLY, O_WRONLY (meaning create or overwrite i.e., implies O_TRUNCAT), 
     * O_WRONLY|O_APPEND. Other flags are generally ignored other than (O_RDWR || (O_EXCL & O_CREAT)) which return NULL and set errno equal ENOTSUP.
```

**Review by kevincai — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by luohaha — APPROVED** [review]

**Comment by srlch** [comment]
https://github.com/Mergifyio backport branch-3.2
