### PR TITLE
[Enhancement] Optimizer plan timeout

### LINKED ISSUE #6095: StarRocks planner use long time 3000 ms.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE DATABASE v0;
USE v0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DATE NULL ,c_0_1 DECIMAL(35, 20)  NOT NULL ,c_0_2 INT NULL ,c_0_3 DATETIME NOT NULL ,c_0_4 TINYINT NOT NULL ,c_0_5 DECIMAL(34, 12)  NOT NULL ,c_0_6 CHAR(31) NULL ,c_0_7 BOOLEAN NULL ,c_0_8 FLOAT REPLACE NULL , INDEX index1_c_0_4(`c_0_4`) USING BITMAP) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 97 day)) DISTRIBUTED BY HASH (c_0_0,c_0_4,c_0_2,c_0_6,c_0_5) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATE NOT NULL,c_1_1 ARRAY<STRING> NOT NULL) PRIMARY KEY (c_1_0) DISTRIBUTED BY HASH (c_1_0) BUCKETS 3 properties("replication_num"="3") ;
DELETE FROM t0 WHERE c_0_1=0.00000490447953788646 AND c_0_2=823279980 AND c_0_3="1969-12-25 22:14:26";
INSERT INTO t1 VALUES ("2010-01-23", ["", "oF", "4u", "JN", "O5bk", "L1o", "G"]), ("2010-01-11", ["JglRSV9K", "479", "", "", "", "n", "R", "V", "U", "", "", "Qdbk9Vi"]);
INSERT INTO t0 VALUES (NULL, 0.00000456701652120433, 7, "2010-01-23 08:00:14", 6, 1872325264.453762283627, "", true, 0.7342448670957158);
INSERT INTO t0 VALUES ("2010-01-02", 0.00000970332763879900, 18, "2010-01-05 08:00:14", 1, 1508374250.404986739222, "r", true, -5.53533237E8);
INSERT INTO t1 VALUES ("2010-01-22", ["", "dPY3pOLv", "Dyh", "l4", "Ny", "Dj", "QQg", "j", "gkBLqPB", "7", "Kg"]), ("2010-01-30", ["dfR", "", "tZ2hufXiJ", "MrIz", "", "", "EumWeAVw", "", "2FjMhiLP", "J", "1", "O", "6QG7ep", "v"]);
CREATE VIEW v0 AS WITH with_t_0 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) , with_t_1 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0;
CREATE VIEW v1 AS WITH with_t_0 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) , with_t_1 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE ((subwith_t_0.c_1_0) IS NULL);
CREATE VIEW v2 AS WITH with_t_0 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) , with_t_1 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE (NOT (((subwith_t_0.c_1_0) IS NULL)));
CREATE VIEW v3 AS WITH with_t_0 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) , with_t_1 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE ((((subwith_t_0.c_1_0) IS NULL)) IS NULL);
CREATE VIEW v4 AS WITH with_t_0 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) , with_t_1 as (SELECT t1_3.c_1_0 FROM t1 AS t1_3) SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE ((subwith_t_0.c_1_0) IS NULL) UNION ALL SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE (NOT (((subwith_t_0.c_1_0) IS NULL))) UNION ALL SELECT t1_3.c_1_0 FROM with_t_1 AS with_t_1,  t1 AS t1_3  LEFT JOIN (SELECT with_t_0.c_1_0 FROM with_t_0 AS with_t_0 ORDER BY with_t_0.c_1_0 DESC) subwith_t_0 ON t1_3.c_1_0 = subwith_t_0.c_1_0 AND subwith_t_0.c_1_0 >= t1_3.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 AND t1_3.c_1_0 != subwith_t_0.c_1_0 WHERE ((((subwith_t_0.c_1_0) IS NULL)) IS NULL);
CREATE VIEW v5 AS WITH with_t_0 as (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE true) , with_t_1 as (SELECT v0_24.c_1_0 FROM v0 AS v0_24 WHERE true) SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0;
CREATE VIEW v6 AS WITH with_t_0 as (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE true) , with_t_1 as (SELECT v0_24.c_1_0 FROM v0 AS v0_24 WHERE true) SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (NOT ((NOT (true))));
CREATE VIEW v36 AS WITH with_t_0 as (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE true) , with_t_1 as (SELECT v0_24.c_1_0 FROM v0 AS v0_24 WHERE true) SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (NOT ((NOT ((NOT (true))))));
CREATE VIEW v7 AS WITH with_t_0 as (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE true) , with_t_1 as (SELECT v0_24.c_1_0 FROM v0 AS v0_24 WHERE true) SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (((NOT ((NOT (true))))) IS NULL);
CREATE VIEW v8 AS WITH with_t_0 as (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE true) , with_t_1 as (SELECT v0_24.c_1_0 FROM v0 AS v0_24 WHERE true) SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (NOT ((NOT (true)))) UNION ALL SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (NOT ((NOT ((NOT (true)))))) UNION ALL SELECT v0_24.c_1_0 FROM with_t_0 AS with_t_0, with_t_1 AS with_t_1,  v0 AS v0_24 LEFT SEMI JOIN (SELECT t1_23.c_1_0 FROM t1 AS t1_23 WHERE false) subt1 ON v0_24.c_1_0 = subt1.c_1_0 AND v0_24.c_1_0 >= subt1.c_1_0 WHERE (((NOT ((NOT (true))))) IS NULL);
CREATE VIEW v9 AS SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0;
CREATE VIEW v10 AS SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE true;
CREATE VIEW v11 AS SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE (NOT (true));
CREATE VIEW v12 AS SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE ((true) IS NULL);
CREATE VIEW v13 AS SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE true UNION ALL SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE (NOT (true)) UNION ALL SELECT subv36.c_1_0 FROM v3 AS v3_72, t0 AS t0_67, t1 AS t1_68, v0 AS v0_69, v2 AS v2_71,  (SELECT v5_75.c_1_0 FROM v5 AS v5_75) subv5 RIGHT SEMI JOIN (SELECT v36_73.c_1_0 FROM v36 AS v36_73 ORDER BY 823279980) subv36 ON subv5.c_1_0 = subv36.c_1_0 AND subv5.c_1_0 < CASE  WHEN true THEN subv36.c_1_0  WHEN false THEN subv36.c_1_0  WHEN true THEN subv36.c_1_0 END AND subv5.c_1_0 != subv36.c_1_0 AND MICROSECONDS_SUB("1970-01-10 20:41:19", -1397228483)  >= subv36.c_1_0,  (SELECT v7_77.c_1_0 FROM v7 AS v7_77) subv7  LEFT JOIN v4 AS v4_74 ON subv7.c_1_0 = v4_74.c_1_0 AND subv7.c_1_0 <= v4_74.c_1_0 AND subv7.c_1_0 != v4_74.c_1_0 AND subv7.c_1_0 >= v4_74.c_1_0,  v1 AS v1_70 FULL JOIN v8 AS v8_78 ON v1_70.c_1_0 = v8_78.c_1_0 AND v1_70.c_1_0 != v8_78.c_1_0 AND v1_70.c_1_0 >= v8_78.c_1_0 AND v1_70.c_1_0 = v8_78.c_1_0 WHERE ((true) IS NULL);
CREATE VIEW v14 AS SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10";
CREATE VIEW v15 AS SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE  ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 ) ;
CREATE VIEW v16 AS SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE (NOT ( ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 ) ));
CREATE VIEW v17 AS SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE (( ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 ) ) IS NULL);
CREATE VIEW v18 AS SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE  ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 )  UNION ALL SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE (NOT ( ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 ) )) UNION ALL SELECT subv0.c_1_0 FROM t1 AS t1_138, v7 AS v7_151, t0 AS t0_137, v12 AS v12_143, v3 AS v3_146,  (SELECT v0_139.c_1_0 FROM v0 AS v0_139 ORDER BY v0_139.c_1_0 DESC) subv0 LEFT ANTI JOIN (SELECT v6_150.c_1_0 FROM v6 AS v6_150) subv6 ON subv0.c_1_0 = subv6.c_1_0 AND CAST(subv0.c_1_0 AS DATE )  = subv6.c_1_0,  v36 AS v36_147 RIGHT SEMI JOIN v4 AS v4_148 ON v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 > v4_148.c_1_0 AND v36_147.c_1_0 = v4_148.c_1_0 AND v36_147.c_1_0 < v4_148.c_1_0,  v11 AS v11_142 RIGHT ANTI JOIN v5 AS v5_149 ON v11_142.c_1_0 = v5_149.c_1_0 AND v11_142.c_1_0 >= v5_149.c_1_0 AND v11_142.c_1_0 < v5_149.c_1_0 AND CAST(v5_149.c_1_0 AS DATE )  < "1969-12-10" WHERE (( ( v4_148.c_1_0 ) <= ( v4_148.c_1_0 ) ) IS NULL);
CREATE VIEW v19 AS SELECT subv6.c_1_0 FROM v9 AS v9_253, v7 AS v7_251, v18 AS v18_244, v11 AS v11_237, v4 AS v4_248, t1 AS t1_233, v5 AS v5_249,  v0 AS v0_234 RIGHT ANTI JOIN (SELECT v6_250.c_1_0 FROM v6 AS v6_250 WHERE CAST("1969-12-10" AS BOOLEAN ) ) subv6 ON v0_234.c_1_0 = subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 AND v0_234.c_1_0 >= subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0;
CREATE VIEW v20 AS SELECT subv6.c_1_0 FROM v9 AS v9_253, v7 AS v7_251, v18 AS v18_244, v11 AS v11_237, v4 AS v4_248, t1 AS t1_233, v5 AS v5_249,  v0 AS v0_234 RIGHT ANTI JOIN (SELECT v6_250.c_1_0 FROM v6 AS v6_250 WHERE CAST("1969-12-10" AS BOOLEAN ) ) subv6 ON v0_234.c_1_0 = subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 AND v0_234.c_1_0 >= subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 WHERE false;
CREATE VIEW v21 AS SELECT subv6.c_1_0 FROM v9 AS v9_253, v7 AS v7_251, v18 AS v18_244, v11 AS v11_237, v4 AS v4_248, t1 AS t1_233, v5 AS v5_249,  v0 AS v0_234 RIGHT ANTI JOIN (SELECT v6_250.c_1_0 FROM v6 AS v6_250 WHERE CAST("1969-12-10" AS BOOLEAN ) ) subv6 ON v0_234.c_1_0 = subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 AND v0_234.c_1_0 >= subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 WHERE (NOT (false));
CREATE VIEW v22 AS SELECT subv6.c_1_0 FROM v9 AS v9_253, v7 AS v7_251, v18 AS v18_244, v11 AS v11_237, v4 AS v4_248, t1 AS t1_233, v5 AS v5_249,  v0 AS v0_234 RIGHT ANTI JOIN (SELECT v6_250.c_1_0 FROM v6 AS v6_250 WHERE CAST("1969-12-10" AS BOOLEAN ) ) subv6 ON v0_234.c_1_0 = subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 AND v0_234.c_1_0 >= subv6.c_1_0 AND v0_234.c_1_0 < subv6.c_1_0 WHERE ((false) IS NULL);
```
2. INSERT INTO '....'
3. SELECT  '....'
```
SELECT * FROM v20 UNION ALL SELECT * FROM v21 UNION ALL SELECT * FROM v22;
```
### Real behavior (Required)
```
mysql> SELECT * FROM v20 UNION ALL SELECT * FROM v21 UNION ALL SELECT * FROM v22;
ERROR 1064 (HY000): StarRocks planner use long time 3000 ms, This probably because 1. FE Full GC, 2. Hive external table fetch metadata took a long time, 3. The SQL is very complex. You could 1. adjust FE JVM config, 2. try query again, 3. enlarge new_planner_optimize_timeout session variable
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - BRANCH-2.2-RELEASE dffad40

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6095

## Problem Summary(Required) ：

500 join case, 30s -> 3s

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 9 / 9 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Memo.java|5|5|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Memo.java|5|5|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 1]
```diff
@@ -305,12 +304,14 @@ public void removeUnreachableGroup() {
...
-        List<Group> groupsCopy = new ArrayList<>(groups);
-        for (Group group : groupsCopy) {
-            if (!touch.contains(group.getId())) {
-                removeOneGroup(group);
-            }
+        // only used in logical rewrite phase, logical expression must only one in a group,
+        // and remove groupExpression one by one is too slow, so rebuild directly
+        for (Group group : groups) {
+            group.getLogicalExpressions().forEach(l -> groupExpressions.put(l, l));
+            group.getPhysicalExpressions().forEach(p -> groupExpressions.put(p, p));
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:314]: If only used in logical rewrite phase，group doesn't have Physical Expression

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java [hunk 2]
```diff
@@ -305,12 +304,14 @@ public void removeUnreachableGroup() {
...
         deepSearchGroup(rootGroup, touch);
+        groups.removeIf(g -> !touch.contains(g.getId()));
+        groupExpressions.clear();
 
-        List<Group> groupsCopy = new ArrayList<>(groups);
-        for (Group group : groupsCopy) {
-            if (!touch.contains(group.getId())) {
-                removeOneGroup(group);
-            }
+        // only used in logical rewrite phase, logical expression must only one in a group,
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Memo.java:310]: I think if this function can only be used in logical rewrite phase, we should add  some comment for this function to avoid wrong use.

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by Seaven** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 7 / 7 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/Memo.java|4|4|100.00%|

**Review by murphyatwork — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]
