### PR TITLE
Optimize the scenario upon adding/deleting a large number of tables

### LINKED ISSUE #2358: Frequent high concurrency create&delete db or table failure, report failed to acquire catalog lock.
### Steps to reproduce the behavior (Required)
```
fe.log:
2021-12-22 11:21:40,370 ERROR (colocate group clone checker|95) [Daemon.run():121] daemon thread got exception. name: colocate group clone checker
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_252]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:929) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.relocateAndBalanceGroup(ColocateTableBalancer.java:142) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.runAfterCatalogReady(ColocateTableBalancer.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
2021-12-22 11:21:44,205 WARN (starrocks-mysql-nio-pool-36|298) [StmtExecutor.execute():451] execute Exception, sql SELECT ALL * FROM tab2 AS cor0 LEFT OUTER JOIN tab1 AS cor1 ON 
NULL IS NULL
java.lang.NullPointerException: null
2021-12-22 11:21:55,022 WARN (Thread-43|103) [ReportHandler$ReportTask.exec():234] out of date report version 16401410827811 from backend[10004]. current report version[164014108
27815]
2021-12-22 11:22:06,089 WARN (starrocks-mysql-nio-pool-40|302) [StmtExecutor.handleDdlStmt():908] DDL statement(CREATE TABLE t_9885 (
                                `id` int(18),
                                `value` varchar(20)
                            )
                            ENGINE=OLAP
                            DUPLICATE KEY(`id`)
                            COMMENT "OLAP"
                            DISTRIBUTED BY HASH(`id`) BUCKETS 3
                            PROPERTIES (
                                "replication_num" = "1",
                                "storage_format" = "v2",
                                "colocate_with" = "group_9885"
                            );) process failed.
com.starrocks.common.DdlException: Failed to acquire catalog lock. Try again
        at com.starrocks.catalog.Catalog.createOlapTable(Catalog.java:4088) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.createTable(Catalog.java:3037) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DdlExecutor.execute(DdlExecutor.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:900) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:265) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:412) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:648) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - master release
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| MASTER_RELEASE 2d0fcb9 |
+------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
In an actual concurrent environment, a memory operation takes about 5~7ms, and it takes about 90s to delete 10,000 tables.
We limit an operation to a maximum of 500 to control the execution time of this lock.

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 1]
```diff
@@ -56,6 +56,9 @@
     // erase meta at least after minEraseLatency milliseconds
     // to avoid erase log ahead of drop log
     private static final long minEraseLatency = 10 * 60 * 1000;  // 10 min
+    // Maximum value of a batch of operations for actually delete database(table/partition)
+    // The erase operation will be locked, so one batch can not be too many.
+    private static final int max_erase_operation_per_cycle = 500;
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:61]:
```suggestion
    private static final int MAX_ERASE_OPERATIONS_PER_CYCLE = 500;
```

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
