### PR TITLE
[BugFix] fix incorrect mysql binary resultset packet

### LINKED ISSUE #45072: Malformed packet or encoding issue with date over binary protocol
It seems like the official MySQL Python Connector (and at least one other driver) is having trouble parsing dates sent from StarRocks over binary protocol. 

### Steps to reproduce the behavior (Required)

```sql
CREATE DATABASE example_db;
USE example_db;

CREATE TABLE date_example (dt DATE);

INSERT INTO date_example
VALUES ('2024-01-01'),
       ('2024-01-02'),
       ('2024-01-03')
       ('2024-01-04');
```

**BAD (`prepared=True`)**

```python
import mysql.connector

db = mysql.connector(
  host="...", 
  user="root", 
  password="...", 
  port=9030, 
  database="example_db"
)

sql = "SELECT dt FROM example"

cursor = db.cursor(prepared=True)
cursor.execute(sql, [])

result = cursor.fetchall()
print(result)

# => [(None,), (None,), (None,), (None,)]
```

**GOOD (`prepared=False`)**

```python
import mysql.connector

db = mysql.connector(
  host="...", 
  user="root", 
  password="...", 
  port=9030, 
  database="example_db"
)

sql = "SELECT dt FROM example"

cursor = db.cursor(prepared=False)
cursor.execute(sql, [])

result = cursor.fetchall()

print(result)

# => [(datetime.date(2024, 4, 1),), (datetime.date(2024, 4, 2),), (datetime.date(2024, 4, 3),), (datetime.date(2024, 4, 4),)]
```

Here is a screenshot of Wireshark packet capture where StarRocks is responding to request execute statement.

Screenshot 2024-05-04 at 1 45 09 PM

I don't think this is a Python/Python library issue, because I can replicate the issue in at least one other language/library.

### Expected behavior (Required)

Dates are encoded properly in binary protocol.

### Real behavior (Required)

Packets with dates in binary protocol are incorrectly encoded or the packet itself is malformed.

### StarRocks version (Required)

`3.2.4-613f0b5`

### PR DESCRIPTION
**Pull request by packy92**
## Why I'm doing:
fix #45072
According to https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_binary_resultset.html
There are two differences between binary resultset and text resultset:
1. The binary resultset requires a null bitmap to indicate which column is null.
2. Columns of number, date, and datetime types in binary resultset require different encoding formats.

## What I'm doing:
according to the standard to return the correct packet.
In order to ensure that the binary resultset of array, map, and struct is legal, two main changes have been made:
1. Move the update `_field_pos` operation in the null bitmap to traversal column in `process_chunk` to ensure that `_field_pos` will not be updated repeatedly when processing the element column like `array<date>`.
2.  adds the `is_binary_protocol` parameter in `put_mysql_row_buffer` method, which is used to indicate whether the binary protocol resultset is required to encode the value. For example, the element column in `array<date>` does not need to use the binary protocol, but the `date` column requires the binary protocol.
Fixes #issue

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by kevincai — DISMISSED** [review]

File: test/sql/test_preparestatement/T/test_driver_prepare [hunk 1]
```diff
@@ -16,4 +16,9 @@ insert into prepare_stmt values (1, 2, 3, 4, '2', true, '1');
...
 function: assert_prepare_execute('test_driver_prepare', 'select 1')
 function: assert_prepare_execute('test_driver_prepare', 'select * from prepare_stmt where k1 > 0')
-function: assert_prepare_execute('test_driver_prepare', 'select * from prepare_stmt where k5 = ?', ['2'])
\ No newline at end of file
+function: assert_prepare_execute('test_driver_prepare', 'select * from prepare_stmt where k5 = ?', ['2'])
+function: assert_prepare_execute('test_driver_prepare', "select cast('2021-01-01' as date) from prepare_stmt where k1 > 0")
+function: assert_prepare_execute('test_driver_prepare', "select cast('2021-01-01' as datetime) from prepare_stmt where k5 = ?", ['2'])
+function: assert_prepare_execute('test_driver_prepare', "select cast('2021-01-01 12:12:12.123456' as datetime) from prepare_stmt where k5 = ?", ['2'])
+function: assert_prepare_execute('test_driver_prepare', "select cast('2021-01-01 12:12:12' as datetime) from prepare_stmt where k5 = ?", ['2'])
+function: assert_prepare_execute('test_driver_prepare', "select cast('2021-01-01 12:12:12.123' as datetime), cast('2021-01-01' as date), * from prepare_stmt where k5 = ?", ['2'])
```
Comment (stdpain) [inline test/sql/test_preparestatement/T/test_driver_prepare:24]: add a case for select array<date>?

**Review by stdpain — DISMISSED** [review]

**Review by satanson — DISMISSED** [review]

**Review by dirtysalt — DISMISSED** [review]

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]

File: be/src/column/array_column.cpp [hunk 2]
```diff
@@ -498,7 +498,7 @@ int64_t ArrayColumn::xor_checksum(uint32_t from, uint32_t to) const {
     return (xor_checksum ^ _elements->xor_checksum(element_from, element_to));
 }
 
-void ArrayColumn::put_mysql_row_buffer(MysqlRowBuffer* buf, size_t idx) const {
+void ArrayColumn::put_mysql_row_buffer(MysqlRowBuffer* buf, size_t idx, bool is_binary_protocol) const {
```
Comment (kevincai) [inline be/src/column/array_column.cpp:501]:
```
   MysqlRowBuffer newBuffer(false);

    newBuffer->begin_push_array();
    Column* elements = _elements.get();
    if (array_size > 0) {
        elements->put_mysql_row_buffer(buf, offset);
    }
    for (size_t i = 1; i < array_size; i++) {
        newBuffer->separator(',');
        elements->put_mysql_row_buffer(newBuffer, offset + i);
    }
    newBuffer->finish_push_array();

    buf->put_mysql_row_buffer(newbuffer->data());
```

**Review by kangkaisen — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
