### PR TITLE
[BugFix] Fix thread running out for avro import

### LINKED ISSUE #21152: [avro]after stop schema-registry create routine load then start schema-registry, routine load task failed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create database routine_load_test_db_add_partition2;
use routine_load_test_db_add_partition2
 CREATE TABLE `duplicate_table_with_null` (`k1` int null, `k2` bigint null, `k3` boolean null, `v1` float null, `v2` double null, `v3` string null, `v4` string null, `v5` string null ) DUPLICATE KEY(`k1`, `k2`, `k3`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
stop schema-registry

```
CREATE ROUTINE LOAD routine_load_basic_types_ab332e52_cdd9_11ed_820d_00163e0e550c on duplicate_table_with_null PROPERTIES ("desired_concurrent_number"="1","max_error_number"="1000","max_batch_interval"="5","format"="avro") FROM KAFKA ("confluent.schema.registry.url"="http://xxx.xx.xxx.xxx:8081/","kafka_broker_list"="http://xxx.xx.xxx.xxx:9092/","property.kafka_default_offsets"="OFFSET_BEGINNING","kafka_topic"="avro-topic-add-partitions2");
```
start schema-registry

### Expected behavior (Required)
routine load task successfuly
### Real behavior (Required)
routine load task failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zaorangyang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #21152

## Problem Summary(Required) ：

When the confluent schema registry server is not started, the consuming thread returns an error, but then the consuming thread blocks on the destructor of rdkafka consumer, see https://github.com/confluentinc/librdkafka/issues/3143. This PR fixes the problem.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/runtime/routine_load/data_consumer_group.cpp [hunk 1]
```diff
@@ -248,13 +248,15 @@ Status KafkaDataConsumerGroup::start_all(StreamLoadContext* ctx) {
                         if (err) {
                             auto err_msg = strings::Substitute("serdes deserialize avro failed: $0", errstr);
                             LOG(ERROR) << err_msg;
+                            delete msg;
```
Comment (rickif) [inline be/src/runtime/routine_load/data_consumer_group.cpp:251]: How about using a smart pointer to resolve this?

Comment (zaorangyang) [reply be/src/runtime/routine_load/data_consumer_group.cpp]: updated

**Review by rickif — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
