### PR TITLE
[BugFix] Add valid source of boost

### LINKED ISSUE #38647: [be-build] The boost download source in vars.sh seems to be invalid
### Steps to reproduce the behavior (Required)
Execute build script on ubuntu os:
```build.sh --be```

### Expected behavior (Required)
Build successfully.

### Real behavior (Required)
Throw an error message: `boost_1_80_0.tar.gz md5sum check failed`
Then I download from another source and put it in directory `thrityparty/src/`, and it works.

### StarRocks version (Required)
lastest version.

### PR DESCRIPTION
**Pull request by lingtaolf**
Why I'm doing:

What I'm doing:

Fixes #38647

## What type of PR is this:

- [x] BugFix

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: thirdparty/vars.sh [hunk 1]
```diff
@@ -181,7 +181,7 @@ RE2_SOURCE=re2-2022-12-01
 RE2_MD5SUM="f25d7b06a3e7747ecbb2f12d48be61cd"
 
 # boost
-BOOST_DOWNLOAD="https://boostorg.jfrog.io/artifactory/main/release/1.80.0/source/boost_1_80_0.tar.gz"
+BOOST_DOWNLOAD="https://sourceforge.net/projects/boost/files/boost/1.80.0/boost_1_80_0.tar.gz"
```
Comment (kevincai) [inline thirdparty/vars.sh:184]: should use the link from boost official site: https://archives.boost.io/release/1.80.0/source/boost_1_80_0.tar.gz

**Review by kevincai — APPROVED** [review]

File: thirdparty/vars.sh (hunk 1 above)
Comment (lingtaolf) [reply thirdparty/vars.sh]: Done!

**Review by kevincai — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by kevincai** [comment]
@mergifyio backport branch-3.1
