### PR TITLE
[BugFix] didn't catch the exception in getAuthorizationInfo

### LINKED ISSUE #47636: check authority abnormal in streamload http request
### Steps to reproduce the behavior (Required)
```
curl -i --location --request PUT 'http://127.0.0.1:7030/api/database_test/tb_test/_stream_load' \
--header 'jsonpaths: ["$.id", "$.name", "$.dt"]' \
--header 'format: json' \
--header 'columns: id, name, dt, __op ='\''upsert'\''' \
--header 'strict_mode: true' \
--header 'Expect: 100-continue' \
--header 'Content-Type: text/plain' \
--header 'Authorization: Basic xxx' \
--data '{
    "id": "101",
    "name": "xhl",
    "dt": "2024-06-25"
}
{
    "id": "102",
    "name": "ly",
    "dt": "2024-06-25"
}'
```

### Expected behavior (Required)
```
{"status":"FAILED","msg":"Need auth information."}
```

### Real behavior (Required)
```
curl: (52) Empty reply from server
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by blanklin030**
+ the demo like below:
```
curl -i --location --request PUT 'http://127.0.0.1:7030/api/database_test/tb_test/_stream_load' \
--header 'jsonpaths: ["$.id", "$.name", "$.dt"]' \
--header 'format: json' \
--header 'columns: id, name, dt, __op ='\''upsert'\''' \
--header 'strict_mode: true' \
--header 'Expect: 100-continue' \
--header 'Content-Type: text/plain' \
--header 'Authorization: Basic xxx' \
--data '{
    "id": "101",
    "name": "xhl",
    "dt": "2024-06-25"
}
{
    "id": "102",
    "name": "ly",
    "dt": "2024-06-25"
}'
```
+ the response like below:
```
curl: (52) Empty reply from server
```
## What I'm doing:
make the normal http resonse for all http api, like below
```
{"status":"FAILED","msg":"Need auth information."}
```
Fixes #47636

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/http/BadHttpRequestTest.java [hunk 1]
```diff
@@ -60,6 +60,21 @@ public void testStreamLoadWithNormalRequest() throws IOException {
...
+        Request.Builder requestBuilder = new Request.Builder()
+                .url(String.format(STREAM_LOAD_URL_FORMAT, DB_NAME, TABLE_NAME))
+                .put(body)
+                .addHeader("Authorization", "Basic xxx")
+                .addHeader("columns", genColumnNameList(Config.http_max_header_size))
+                .addHeader("label", UUID.randomUUID().toString())
+                .addHeader("Expect", "100-continue");
+        Request request = requestBuilder.build();
+        Response response = networkClient.newCall(request).execute();
+        Assert.assertEquals(200, response.code());
```
Comment (kevincai) [inline fe/fe-core/src/test/java/com/starrocks/http/BadHttpRequestTest.java:75]: need to fix this UT, and should expect HTTP 401 error for auth fail.

Comment (blanklin030) [reply fe/fe-core/src/test/java/com/starrocks/http/BadHttpRequestTest.java]: @kevincai hello kevin, i had fixed the ut issue, please help me to review the code again~thank you~

**Review by kevincai — APPROVED** [review]

**Review by tracymacding — APPROVED** [review]

**Review by wyb — APPROVED** [review]
