### PR TITLE
[BugFix] Fix set password mistake use userIdentity cause equal fail bug

### LINKED ISSUE #17817: [access control]set password = 'xxx' error: access denied
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create user aaa identified by '123456';
mysql -hxxx.xx.xx.xxx -P9232 -uaaa -p123456
set password='*2727EA229A9F2F2D696375270574BF7E658136DD';
```

image

### Expected behavior (Required)
set success
### Real behavior (Required)
Access denied; you need (at least one of) the GRANT privilege(s) for this operation

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 2b32b43 |
+----------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17817 

## Problem Summary(Required) ：

The original code mixed getUserIdentity and getCurrentUserIdentity. getUserIdentity itself is a confusing name, so I deleted this function directly
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java [hunk 1]
```diff
@@ -1578,6 +1578,16 @@ public void testSetStmt() throws Exception {
         String sql = "SET PASSWORD FOR 'jack'@'192.%' = PASSWORD('123456');";
         String expectError = "Access denied; you need (at least one of) the GRANT privilege(s) for this operation";
         verifyNODEAndGRANT(sql, expectError);
+
+        ctxToTestUser();
+        // user 'test' not has GRANT/NODE privilege
+        sql = "set password = PASSWORD('123456')";
+        StatementBase statement = UtFrameUtils.parseStmtWithNewParser(sql, starRocksAssert.getCtx());
+        PrivilegeCheckerV2.check(statement, starRocksAssert.getCtx());
```
Comment (nshangyiming) [inline fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java:1586]: if user 'test' doesn't have grant privilege on system, it will throw exception here?

**Review by nshangyiming — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 13 / 18 (72.22%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|3|00.00%|[252, 314, 362]|
|:large_blue_circle:|com/starrocks/service/InformationSchemaDataSource.java|0|1|00.00%|[81]|
|:large_blue_circle:|com/starrocks/common/PatternMatcher.java|1|2|50.00%|[165]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeCheckerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/UserIdentity.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/UserAuthenticationInfo.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/PrivilegeStmtAnalyzerV2.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ExpressionAnalyzer.java|3|3|100.00%|[]|

File: fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java (hunk 1 above)
Comment (HangyuanLiu) [reply fe/fe-core/src/test/java/com/starrocks/sql/analyzer/PrivilegeCheckerV2Test.java:1586]: no, set your own password, no permission is required, here you can pass check

**Review by Astralidea — APPROVED** [review]
