### PR TITLE
[BugFix]Fix Grant CaseSensibility

### LINKED ISSUE #55613: INFORMATION_SCHEMA grant case sensitivity
starrocks 3.4
catalog iceberg

we had ```grant select on all tables in database information_schema to role 'xxx'```
after upgrade from 3.3 we have trouble connecting with tableau 
turns out tableau runs all caps lock query with `INFORMATION_SCHEMA` and gets permission exception

fixed by separate grant to INFORMATION_SCHEMA

### PR DESCRIPTION
**Pull request by Zac-saodiseng**
## Why I'm doing:
We had grant select on all tables in database `information_schema` to role 'xxx'
after upgrade from 3.3 we have trouble connecting with tableau
turns out tableau runs all caps lock query with INFORMATION_SCHEMA and gets permission exception
## What I'm doing:

Fixes #55613 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/common/CaseSensibility.java [hunk 1]
```diff
@@ -19,7 +19,7 @@
 
 public enum CaseSensibility {
     CLUSTER(true),
-    DATABASE(true),
+    DATABASE(false),
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/common/CaseSensibility.java:22]: After this change, the internal tables have become case-insensitive, which has a significant impact.  
It would be better if only queries to system tables were case-insensitive.  
See if there’s any other way to modify it.

File: fe/fe-core/src/main/java/com/starrocks/authorization/TablePEntryObject.java [hunk 2]
```diff
@@ -97,6 +97,13 @@ public static TablePEntryObject generate(List<String> tokens) throws PrivilegeEx
                 throw new PrivObjNotFoundException("cannot find catalog: " + catalogName);
             }
             catalogId = catalog.getId();
+            // As a system database, `information_schema` is case-insensitive
+            // across both internal and external catalogs. Queries can access it
+            // regardless of letter case (e.g. `information_schema`, `INFORMATION_SCHEMA`, `Information_Schema`).
+            if (tokens.size() == 2 && "information_schema".equalsIgnoreCase(tokens.get(0))) {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/authorization/TablePEntryObject.java:103]: Can we consider unifying the logical differences between the outer table and the inner table at the match position?

**Review by HangyuanLiu — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
