### PR TITLE
[BugFix] ALTER MATERIALIZED VIEW statement will change

### LINKED ISSUE #11632: ALTER MATERIALIZED VIEW statement will change
### Steps to reproduce the behavior (Required)
1.
CREATE TABLE goods(
    item_id1          INT,
    item_name         STRING,
    price             FLOAT
) DISTRIBUTED BY HASH(item_id1)
PROPERTIES (
 "replication_num" = "1"
);

CREATE TABLE order_list(
    order_id          INT,
    client_id         INT,
    item_id2          INT,
    order_date        DATE
) DISTRIBUTED BY HASH(order_id)
PROPERTIES (
 "replication_num" = "1"
);

2.
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(`order_id`) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 1 day)
AS SELECT
    order_list.order_id,
    sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

3.
图片

4.
ALTER MATERIALIZED VIEW order_mv REFRESH ASYNC EVERY(INTERVAL 2 DAY);

5.
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Expected behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:03:00') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### Real behavior (Required)
MySQL [test]> show create table order_mv;
CREATE MATERIALIZED VIEW order_mv
DISTRIBUTED BY HASH(order_id) BUCKETS 12
REFRESH ASYNC START('2022-09-26 11:09:23') EVERY (interval 2 day)
AS SELECT
order_list.order_id,
sum(goods.price) as total
FROM order_list INNER JOIN goods ON goods.item_id1 = order_list.item_id2
GROUP BY order_id;

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.4

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11632 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java [hunk 1]
```diff
@@ -290,4 +290,21 @@ public static long convertTimeUnitValueToSecond(long value, TimeUnit unit) {
                 return 0;
         }
     }
+
+    public static long getNextValidTimeSecond(long timeSecond, long targetTimeSecond,
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java:294]: nit: better use startTimeSecond instead of timeSecond

File: fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java [hunk 2]
```diff
@@ -290,4 +290,21 @@ public static long convertTimeUnitValueToSecond(long value, TimeUnit unit) {
...
+                                              long period, TimeUnit timeUnit) throws DdlException {
+        long interval = convertTimeUnitValueToSecond(period, timeUnit);
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java:296]: nit: better use intervalSecond instead of interval

**Review by Astralidea — DISMISSED** [review]

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java [hunk 3]
```diff
@@ -290,4 +290,21 @@ public static long convertTimeUnitValueToSecond(long value, TimeUnit unit) {
                 return 0;
         }
     }
+
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java:293]: could you add some comment?

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 19 / 21 (90.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|2|3|66.67%|[295]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|9|10|90.00%|[87]|
|:large_blue_circle:|com/starrocks/common/util/TimeUtils.java|8|8|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by Astralidea — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java [hunk 4]
```diff
@@ -290,4 +290,32 @@ public static long convertTimeUnitValueToSecond(long value, TimeUnit unit) {
...
+        }
+        long intervalSecond = convertTimeUnitValueToSecond(period, timeUnit);
+        if (intervalSecond < 1) {
+            throw new DdlException("Can not get next valid time second," +
+                    "startTimeSecond:" + startTimeSecond +
+                    " period:" + period +
+                    " timeUnit:" + timeUnit);
+        }
+        long difference = targetTimeSecond - startTimeSecond;
+        long step = difference / intervalSecond + 1;
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java:318]: what if difference is divisible by intervalSecond, is it necessary to add one?

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java (hunk 4 above)
Comment (blackstar-baba) [reply fe/fe-core/src/main/java/com/starrocks/common/util/TimeUtils.java:318]: Because we need to get second bigger than target time second.

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 19 / 21 (90.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/Alter.java|2|3|66.67%|[295]|
|:large_blue_circle:|com/starrocks/scheduler/TaskBuilder.java|9|10|90.00%|[87]|
|:large_blue_circle:|com/starrocks/common/util/TimeUtils.java|8|8|100.00%|[]|
