### PR TITLE
[BugFix] Fix create table in schema db error message

### LINKED ISSUE #20509: Creating a table in the system database prompts an error.
### Steps to reproduce the behavior (Required)
1. use information_schema
2. CREATE TABLE goods(
    item_id1          INT,
    item_name         STRING,
    price             FLOAT
) DISTRIBUTED BY HASH(item_id1)
PROPERTIES("replication_num" = "1");

### Expected behavior (Required)
Can't create table 'goods' (errno: access denied)
### Real behavior (Required)
Can't create table 'goods' (errno: table already exists)
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20509

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java [hunk 1]
```diff
@@ -555,7 +555,9 @@ public Table createTable(LocalMetastore metastore, Database db, CreateTableStmt
                 }
                 createTblSuccess = db.createTableWithLock(table, false);
                 if (!createTblSuccess) {
-                    if (!stmt.isSetIfNotExists()) {
+                    if (db.isInfoSchemaDb()) {
+                        ErrorReport.reportDdlException(ErrorCode.ERR_CANT_CREATE_TABLE, tableName, "access denied");
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java:559]:
```suggestion
                        ErrorReport.reportDdlException(ErrorCode.ERR_CANT_CREATE_TABLE, tableName, "create denied");
```

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/server/OlapTableFactory.java:559]: ?

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
