### PR TITLE
[Enhancement] support s3 path style in shared-data cluster

### LINKED ISSUE #61590: 使用存算分离的自动化集群快照，快照无法上传至minio
### Steps to reproduce the behavior (Required)
1. 创建快照存储卷
```sql
CREATE STORAGE VOLUME IF NOT EXISTS snapshot_volumn
TYPE = S3
LOCATIONS = ('s3://data-test/cn-test/snapshot')
COMMENT '集群快照存储卷' 
PROPERTIES
(
"enabled" = "true",
"aws.s3.region" = "cn-xiamen",
"aws.s3.enable_path_style_access" = "true",
"aws.s3.endpoint" = "http://s3-minio.test.com",
"aws.s3.access_key" = "changeme",
"aws.s3.secret_key" = "changeme"
)
```
2. 启用集群快照
```sql
ADMIN SET AUTOMATED CLUSTER SNAPSHOT ON STORAGE VOLUME snapshot_volumn;
```

### Expected behavior (Required)
快照上传成功
### Real behavior (Required)
- 快照上传失败：
| automated_cluster_snapshot_1754357144500 |  11516 | 2025-08-05 09:25:44 | NULL          | ERROR |             | upload image failed, err msg: Failed to copy local /opt/starrocks/fe/meta/image to s3://ydata-test/cn-test/snapshot/0c310443-d94d-4019-9d99-6bfef320b506/meta/image/automated_cluster_snapshot_1754357144500 |
- 报错：Caused by: java.net.UnknownHostException: data-test.s3-minio.test.com
- 配置"aws.s3.enable_path_style_access" = "true" 对存储卷来说不生效，BE是自动检测，而FE没有自动检测，导致上传路径是错的
### StarRocks version (Required)
 - 3.4.5

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## What I'm doing:

Fixes #61590

support `"aws.s3.enable_path_style_access" = "true"` when create storage volume

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Comment by alvin-phoenix-ai** [comment]
@starrocks-xupeng if this is a new configuration, you should change the document accordingly

**Comment by starrocks-xupeng** [comment]
ok

File: fe/fe-core/src/test/java/com/starrocks/storagevolume/StorageVolumeTest.java [hunk 1]
```diff
@@ -130,6 +132,7 @@ public void testAWSSimpleCredential() throws AnalysisException, DdlException {
         Assertions.assertTrue(fileStore.hasS3FsInfo());
         S3FileStoreInfo s3FileStoreInfo = fileStore.getS3FsInfo();
         Assertions.assertTrue(s3FileStoreInfo.getCredential().hasSimpleCredential());
+        Assertions.assertEquals(s3FileStoreInfo.getPathStyleAccess(), true);
```
Comment (kevincai) [inline fe/fe-core/src/test/java/com/starrocks/storagevolume/StorageVolumeTest.java]: fix the unit test

File: fe/fe-core/src/main/java/com/starrocks/credential/aws/AwsCloudConfiguration.java [hunk 2]
```diff
@@ -32,7 +32,7 @@ public class AwsCloudConfiguration extends CloudConfiguration {
 
     private final AwsCloudCredential awsCloudCredential;
 
-    private boolean enablePathStyleAccess = false;
+    private Boolean enablePathStyleAccess = null;
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/credential/aws/AwsCloudConfiguration.java:38]: add comprehensive comments to explain why change to this way.

File: docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md [hunk 3]
```diff
@@ -54,6 +54,7 @@ import Beta from '../../../../_assets/commonMarkdown/_beta.mdx'
 | aws.s3.iam_role_arn                 | 有访问 S3 存储空间权限 IAM Role 的 ARN。                     |
 | aws.s3.external_id                  | 用于跨 AWS 账户访问 S3 存储空间的外部 ID。                   |
 | aws.s3.enable_ssl                   | 指定是否启用 SSL 连接。<br />有效值：`true` 和 `false`。默认值：`true`。                   |
+| aws.s3.enable_path_style_access     | 指定是否使用 path style 方式访问 S3。<br />有效值：`true` 和 `false`。默认值：`false`。                   |
```
Comment (kevincai) [inline docs/zh/sql-reference/sql-statements/cluster-management/storage_volume/CREATE_STORAGE_VOLUME.md]: `aws.s3.enable_ssl` is not supported in storage volume property. Need another PR to fix the doc.

File: fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java [hunk 4]
```diff
@@ -292,6 +292,13 @@ public static Map<String, String> getParamsFromFileStoreInfo(FileStoreInfo fsInf
                     params.put(CloudConfigurationConstants.AWS_S3_NUM_PARTITIONED_PREFIX,
                             Integer.toString(s3FileStoreInfo.getNumPartitionedPrefix()));
                 }
+                if (s3FileStoreInfo.getPathStyleAccess() == 1) {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java:295]: please open another PR to fix the `enable_ssl` configuration here, be able to auto translate the `enable_ssl` configuration from the endpoint in storage volume.

File: fe/fe-core/src/main/java/com/starrocks/credential/aws/AwsCloudConfiguration.java (hunk 2 above)
Comment (starrocks-xupeng) [reply fe/fe-core/src/main/java/com/starrocks/credential/aws/AwsCloudConfiguration.java:38]: done

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java (hunk 4 above)
Comment (starrocks-xupeng) [reply fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java:295]: later

File: fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java [hunk 5]
```diff
@@ -292,6 +292,13 @@ public static Map<String, String> getParamsFromFileStoreInfo(FileStoreInfo fsInf
...
+                    params.put(CloudConfigurationConstants.AWS_S3_ENABLE_PATH_STYLE_ACCESS,
+                            Boolean.toString(true));
+                } else { // if 0 or 2, use virtual style
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java]: shall put false only when `getPathStyleAccess() ==2`, it will be up to the CloudConfiguration's implementation details to determine what the default value is when the `aws.s3.enable_path_style` is not provided.

Comment (starrocks-xupeng) [reply fe/fe-core/src/main/java/com/starrocks/storagevolume/StorageVolume.java]: done

**Review by kevincai — DISMISSED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Review by kevincai — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]
