### PR TITLE
[BugFix] Setting max_compaction_concurrency to -1/0 via dynamic parameter is not as expected.

### LINKED ISSUE #50876: Setting max_compaction_concurrency to -1/0 via dynamic parameter is not as expected.
### Steps to reproduce the behavior (Required)
```
curl http://172.20.176.55:8038/api/update_config?max_compaction_concurrency=-1
```

### Expected behavior (Required)
 -1 means no limit, and the max concurrency will be:
      C = (cumulative_compaction_num_threads_per_disk + base_compaction_num_threads_per_disk) * dir_num
### Real behavior (Required)
1 max_compaction_concurrency=-1.
2 the real max_compaction_concurrency is actually unchanged.

### PR DESCRIPTION
**Pull request by zhangheihei**
## What I'm doing:

Fixes #50876

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: be/src/storage/compaction_manager.cpp [hunk 1]
```diff
@@ -561,8 +561,34 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+
 Status CompactionManager::update_max_threads(int max_threads) {
     if (_compaction_pool != nullptr) {
+        if (max_threads == -1) {
+            std::lock_guard lg(_tasks_mutex);
+            _max_task_num = compute_max_compaction_concurrency();
+            return _compaction_pool->update_max_threads(std::max(1, max_task_num()));
+        }
+        if (max_threads == 0) {
+            //Just to pass the admit test, it doesn't make sense to set max_compaction_concurrency=0 via a dynamic parameter.
```
Comment (kevincai) [inline be/src/storage/compaction_manager.cpp:585]: maybe it is a way to disable the compaction temporarily.

File: be/src/storage/compaction_manager.cpp [hunk 2]
```diff
@@ -561,8 +561,34 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
     return res;
 }
 
+int32_t CompactionManager::compute_max_compaction_concurrency() {
```
Comment (kevincai) [inline be/src/storage/compaction_manager.cpp:564]: where is this calculation logic from?

File: be/src/storage/compaction_manager.h [hunk 3]
```diff
@@ -112,6 +112,8 @@ class CompactionManager {
 
     Status update_max_threads(int max_threads);
 
+    int32_t compute_max_compaction_concurrency();
```
Comment (kevincai) [inline be/src/storage/compaction_manager.h:115]:
```suggestion
    int32_t compute_max_compaction_concurrency() const;
```

**Review by kevincai — COMMENTED** [review]
unit test is expected to test against the `update_max_thread` interface, make sure -1/0/... are all processed as expected.

File: be/src/storage/compaction_manager.cpp (hunk 2 above)
Comment (zhangheihei) [reply be/src/storage/compaction_manager.cpp]: I've refactored the logic here

File: be/src/storage/compaction_manager.cpp [hunk 4]
```diff
@@ -561,8 +560,32 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
     return res;
 }
 
+int32_t CompactionManager::compute_max_compaction_concurrency() const {
+    int32_t max_task_num = 0;
+    // new compaction framework
+    if (config::base_compaction_num_threads_per_disk >= 0 && config::cumulative_compaction_num_threads_per_disk >= 0) {
```
Comment (kevincai) [inline be/src/storage/compaction_manager.cpp:566]: In original olap_server code, it is initialized in main thread, there is no concurrency issue. However, now moved to CompactionManager to support dynamic configvar change.

So direct reference to `config::max_compaction_concurrency` and `config::cumulative_compaction_num_threads_per_disk` and `config::base_compaction_num_threads_per_disk` is in a risk, if they are mutable.

A better approach is to define a local var to capture its value and use the local var to do the subsequent calculation.

File: be/src/storage/compaction_manager.cpp [hunk 5]
```diff
@@ -561,8 +560,32 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+        max_task_num = config::max_compaction_concurrency;
+    }
+
+    return max_task_num;
+}
+
 Status CompactionManager::update_max_threads(int max_threads) {
     if (_compaction_pool != nullptr) {
+        if (max_threads == -1) {
+            std::lock_guard lg(_tasks_mutex);
```
Comment (kevincai) [inline be/src/storage/compaction_manager.cpp:585]: reminder me again why this lock is required? protect the modification of _max_task_num?

is it ok to run the update_max_threads() out of the lock scope?

File: be/src/storage/compaction_manager.cpp (hunk 4 above)
Comment (zhangheihei) [reply be/src/storage/compaction_manager.cpp:566]: tks review,I've optimized it here.
But config::cumulative_compaction_num_threads_per_disk and config::base_compaction_num_threads_per_disk 
don't support dynamic update.

File: be/src/storage/compaction_manager.cpp (hunk 5 above)
Comment (zhangheihei) [reply be/src/storage/compaction_manager.cpp]: Sorry, I used the wrong lock.

File: be/src/storage/compaction_manager.h [hunk 6]
```diff
@@ -174,6 +178,9 @@ class CompactionManager {
 
     std::unique_ptr<ThreadPool> _compaction_pool = nullptr;
     std::thread _scheduler_thread;
+
+    std::mutex _compact_threads_mutex;
```
Comment (kevincai) [inline be/src/storage/compaction_manager.h:182]:
```suggestion
    mutable std::mutex _compact_threads_mutex;
```

Add `mutable` to the mutex so it can be used in a `const` member function.

File: be/src/storage/compaction_manager.cpp [hunk 7]
```diff
@@ -561,8 +560,51 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+        if (max_threads == -1) {
+            _max_task_num = compute_max_compaction_concurrency();
+            return _compaction_pool->update_max_threads(std::max(1, _max_task_num));
+        }
+        if (max_threads == 0) {
+            Status st = _compaction_pool->update_max_threads(0);
+            if (!st.ok()) {
+                return st;
+            }
+            return Status::OK();
```
Comment (kevincai) [inline be/src/storage/compaction_manager.cpp:603]:
```suggestion
            return _compaction_pool->update_max_threads(0);
```

Haven't done any specific error handling regarding to the return Status value, so just return the status to the caller directly.

**Review by kevincai — COMMENTED** [review]
It will awesome to add some more unit test to cover the function behavior change.

**Review by kevincai — DISMISSED** [review]

File: be/src/storage/compaction_manager.cpp [hunk 8]
```diff
@@ -575,8 +574,47 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+void CompactionManager::set_max_compaction_concurrency(int threads_num) {
+    std::lock_guard lg(_compact_threads_mutex);
+    _max_compaction_concurrency = threads_num;
+}
+
 Status CompactionManager::update_max_threads(int max_threads) {
     if (_compaction_pool != nullptr) {
+        set_max_compaction_concurrency(max_threads);
+        if (max_threads == -1) {
+            _max_task_num = compute_max_compaction_concurrency();
```
Comment (starrocks-xupeng) [inline be/src/storage/compaction_manager.cpp:609]: should change this function to compute_max_compaction_task_num? since max_compaction_concurrency is already set above

File: be/src/storage/compaction_manager.cpp [hunk 9]
```diff
@@ -575,8 +574,47 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+        if (max_threads == -1) {
+            _max_task_num = compute_max_compaction_task_num();
+            return _compaction_pool->update_max_threads(std::max(1, _max_task_num));
+        }
+        if (max_threads == 0) {
+            return _compaction_pool->update_max_threads(0);
+        }
+        if (max_threads >= _max_task_num) {
+            max_threads = _max_task_num;
+        }
```
Comment (starrocks-xupeng) [inline be/src/storage/compaction_manager.cpp:617]: need some log here to let caller know the actual thread number?

File: be/src/storage/compaction_manager.cpp [hunk 10]
```diff
@@ -575,8 +574,47 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
+        std::lock_guard lg(_compact_threads_mutex);
+        if (_max_compaction_concurrency > 0 && _max_compaction_concurrency < max_task_num) {
+            max_task_num = _max_compaction_concurrency;
+        }
+    }
+
+    return max_task_num;
+}
+
+void CompactionManager::set_max_compaction_concurrency(int threads_num) {
```
Comment (starrocks-xupeng) [inline be/src/storage/compaction_manager.cpp:600]: this function seems useless, since both `_max_compaction_concurrency` and `_max_task_num` come from `max_threads`

Comment (zhangheihei) [reply be/src/storage/compaction_manager.cpp:600]: 1 max_threads is come from config::max_compaction_concurrency，_max_compaction_concurrency record the config, hherefore _max_compaction_concurrency must be set in the current context.
```
set_max_compaction_concurrency(max_threads)
```
2 _max_task_num is come form compute_max_compaction_concurrency

3 In original olap_server code, _max_task_num is initialized in main thread, there is no concurrency issue。Now, it need set_max_compaction_concurrency to avoid concurrency issue.

File: be/src/storage/compaction_manager.cpp (hunk 9 above)
Comment (zhangheihei) [reply be/src/storage/compaction_manager.cpp:614]: tks reveiw.
No need to add logs, I optimized the logic here.

File: be/src/storage/compaction_manager.cpp [hunk 11]
```diff
@@ -575,9 +574,47 @@ std::unordered_set<CompactionTask*> CompactionManager::get_running_task(const Ta
...
 Status CompactionManager::update_max_threads(int max_threads) {
     if (_compaction_pool != nullptr) {
-        return _compaction_pool->update_max_threads(max_threads);
+        set_max_compaction_concurrency(max_threads);
+        if (max_threads == 0) {
+            Status st = _compaction_pool->update_max_threads(0);
+            if (!st.ok()) {
+                return st;
+            }
+            return Status::OK();
```
Comment (wyb) [inline be/src/storage/compaction_manager.cpp:613]:
```suggestion
            return _compaction_pool->update_max_threads(0);
```

Comment (wyb) [reply be/src/storage/compaction_manager.cpp:613]: https://github.com/StarRocks/starrocks/blob/main/be/src/storage/compaction_manager.cpp#L49
`_min_threads` of `_compaction_pool` is 1, `update_max_threads(0)` will fail.

**Review by wyb — DISMISSED** [review]

**Review by wyb — DISMISSED** [review]

File: be/src/storage/compaction_manager.h [hunk 12]
```diff
@@ -128,6 +135,8 @@ class CompactionManager {
 
     int get_waiting_task_num();
 
+    ThreadPool* get_compaction_thread_pool() { return _compaction_pool.get(); }
```
Comment (kevincai) [inline be/src/storage/compaction_manager.h:138]:
```suggestion
    ThreadPool* TEST_get_compaction_thread_pool() { return _compaction_pool.get(); }
```

This interface is added just for TEST purpose.

or more specifically
```
int32_t TEST_get_compaction_thread_pool_max_threads() const { return _compaction_pool->max_threads(); }
```

File: be/src/storage/olap_server.cpp [hunk 13]
```diff
@@ -180,21 +180,8 @@ Status StorageEngine::start_bg_threads() {
...
-                                                 config::base_compaction_num_threads_per_disk));
-        } else {
-            // When cumulative_compaction_num_threads_per_disk or config::base_compaction_num_threads_per_disk is less than 0,
-            // there is no limit to _max_task_num if max_compaction_concurrency is also less than 0, and here we set maximum value to be 20.
-            max_task_num = std::min(20, static_cast<int32_t>(StorageEngine::instance()->get_store_num() * 5));
-        }
-        if (config::max_compaction_concurrency > 0 && config::max_compaction_concurrency < max_task_num) {
-            max_task_num = config::max_compaction_concurrency;
-        }
+        _compaction_manager->set_max_compaction_concurrency(config::max_compaction_concurrency);
```
[the remark this answers is not in the document]
Comment (zhangheihei) [reply be/src/storage/olap_server.cpp:183]: To avoid concurrency issues and to make the code logic clearer.

**Review by kevincai — DISMISSED** [review]

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by kevincai** [comment]
too many conflicts, give up backport to branch-3.1
