### PR TITLE
[Enhancement] Support transaction_read_only compatible with mysql

### LINKED ISSUE #37243: dbeaver + msyql driver 8 connects to SR and encounters this error when executing
### Steps to reproduce the behavior (Required)
no more information.

### Expected behavior (Required)
query success.

### Real behavior (Required)
SQL Error [1064] [42000]: Getting analyzing error. Detail message: Unknown system variable 'transaction_read_only', the most similar variables are {'transaction_isolation', 'innodb_read_only', 'scan_or_to_union_threshold'}

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.1

### PR DESCRIPTION
**Pull request by Astralidea**
Why I'm doing:
The transaction_read_only parameter was introduced in mysql version 5.7.20. When users set mysql to a higher version, some BI may report an error.

What I'm doing:
add transaction_read_only and tx_read_only.

Fixes #37243

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java [hunk 1]
```diff
@@ -735,6 +737,10 @@ public static MaterializedViewRewriteMode parse(String str) {
     // this is used to compatible mysql 5.8
     @VariableMgr.VarAttr(name = TRANSACTION_ISOLATION)
     private String transactionIsolation = "REPEATABLE-READ";
+    @VariableMgr.VarAttr(name = TRANSACTION_READ_ONLY)
+    private String transactionReadOnly = "OFF";
+    @VariableMgr.VarAttr(name = TX_READ_ONLY)
+    private String txReadOnly = "OFF";
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:743]: can you make them as one field with alias?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java]: ok

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
