### PR TITLE
[BugFix] Fix be crash in ASAN mode

### LINKED ISSUE #8244: be crash because of compaction.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
start time: Sun Jul 3 23:07:58 CST 2022
*** Check failure stack trace: ***
    @          0xb658aed  google::LogMessage::Fail()
    @          0xb65af5f  google::LogMessage::SendToLog()
    @          0xb65863e  google::LogMessage::Flush()
    @          0xb65b569  google::LogMessageFatal::~LogMessageFatal()
    @          0x62a8d90  starrocks::ArrayColumnIterator::next_batch()
    @          0x528d12e  starrocks::vectorized::SegmentIterator::ScanContext::read_columns()
    @          0x528e434  starrocks::vectorized::SegmentIterator::_read()
    @          0x5274126  starrocks::vectorized::SegmentIterator::_do_get_next()
    @          0x5272830  starrocks::vectorized::SegmentIterator::do_get_next()
    @          0x5118730  starrocks::vectorized::ChunkIterator::get_next()
    @          0x5c5c527  starrocks::vectorized::MaskMergeIterator::fill()
    @          0x5c57d08  starrocks::vectorized::MergeIterator::init()
    @          0x5c5ac28  starrocks::vectorized::MaskMergeIterator::do_get_next()
    @          0x5465863  starrocks::vectorized::ChunkIterator::get_next()
    @          0x54bb94f  starrocks::vectorized::RowsetMergerImpl<>::_do_merge_vertically()
    @          0x54b25fc  starrocks::vectorized::RowsetMergerImpl<>::do_merge()
    @          0x54a6eb2  starrocks::vectorized::compaction_merge_rowsets()
    @          0x50d7d81  starrocks::TabletUpdates::_do_compaction()
    @          0x50e8ec6  starrocks::TabletUpdates::compaction()
    @          0x4f42a5c  starrocks::StorageEngine::_perform_update_compaction()
    @          0x55c0c52  starrocks::StorageEngine::_update_compaction_thread_callback()
    @          0x55bca52  _ZZN9starrocks13StorageEngine16start_bg_threadsEvENKUlvE7_clEv
    @          0x55cc96e  _ZSt13__invoke_implIvZN9starrocks13StorageEngine16start_bg_threadsEvEUlvE7_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x55cc504  _ZSt8__invokeIZN9starrocks13StorageEngine16start_bg_threadsEvEUlvE7_JEENSt15__invoke_resultIT_JDpT0_EE4typeEOS4_DpOS5_
    @          0x55cc200  _ZNSt6thread8_InvokerISt5tupleIJZN9starrocks13StorageEngine16start_bg_threadsEvEUlvE7_EEE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @          0x55cc038  _ZNSt6thread8_InvokerISt5tupleIJZN9starrocks13StorageEngine16start_bg_threadsEvEUlvE7_EEEclEv
    @          0x55cbe88  _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN9starrocks13StorageEngine16start_bg_threadsEvEUlvE7_EEEEE6_M_runEv
    @          0xd246230  execute_native_thread_routine
    @     0x7fa1195cce65  start_thread
    @     0x7fa118be788d  __clone
    @              (nil)  (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - MAIN-ASAN-8d5e750

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8244

## Problem Summary(Required) ：

If element of ArrayColumn is empty, we don't need to read data from `data_column` of ArrayColumn because data is empty. 
So we don't add an empty read_range into `element_read_ranges`, which will cause inconsistency between the begin of `element_read_range` and `element_ordinal` of element_iterator. That's why be crash in ASAN mode.

### CODE REVIEW

File: be/src/storage/rowset/array_column_iterator.cpp [hunk 1]
```diff
@@ -153,6 +153,11 @@ Status ArrayColumnIterator::next_batch(const vectorized::SparseRange& range, vec
 
         RETURN_IF_ERROR(_array_size_iterator->seek_to_ordinal_and_calc_element_ordinal(r.begin()));
         size_t element_ordinal = _array_size_iterator->element_ordinal();
+        // if array column in nullable or element of array is empty, element_read_range may be empty.
+        // so we should reseek the element_ordinal
```
Comment (chaoyli) [inline be/src/storage/rowset/array_column_iterator.cpp:157]: If we can add a test case to the integration case to avoid the problem.

**Review by chaoyli — APPROVED** [review]

File: be/src/storage/rowset/array_column_iterator.cpp (hunk 1 above)
Comment (sevev) [reply be/src/storage/rowset/array_column_iterator.cpp:157]: I will add some test cases into StarrocksTest after this pr is merged

**Review by imay — APPROVED** [review]
