### PR TITLE
Fix the bug that the state of replica is always in decommission

### LINKED ISSUE #1976: Single replication of the tablet is always in the decommission state
### Steps to reproduce the behavior (Required)
1. Create a table on a cluster with 3 be
```sql
CREATE TABLE `lineorder_flat` (
  `LO_ORDERKEY` int(11) NOT NULL COMMENT "",
  `LO_ORDERDATE` date NOT NULL COMMENT "",
  `LO_LINENUMBER` tinyint(4) NOT NULL COMMENT "",
  `LO_CUSTKEY` int(11) NOT NULL COMMENT "",
  `LO_PARTKEY` int(11) NOT NULL COMMENT "",
  `LO_SUPPKEY` int(11) NOT NULL COMMENT "",
  `LO_ORDERPRIORITY` varchar(100) NOT NULL COMMENT "",
  `LO_SHIPPRIORITY` tinyint(4) NOT NULL COMMENT "",
  `LO_QUANTITY` tinyint(4) NOT NULL COMMENT "",
  `LO_EXTENDEDPRICE` int(11) NOT NULL COMMENT "",
  `LO_ORDTOTALPRICE` int(11) NOT NULL COMMENT "",
  `LO_DISCOUNT` tinyint(4) NOT NULL COMMENT "",
  `LO_REVENUE` int(11) NOT NULL COMMENT "",
  `LO_SUPPLYCOST` int(11) NOT NULL COMMENT "",
  `LO_TAX` tinyint(4) NOT NULL COMMENT "",
  `LO_COMMITDATE` date NOT NULL COMMENT "",
  `LO_SHIPMODE` varchar(100) NOT NULL COMMENT "",
  `C_NAME` varchar(100) NOT NULL COMMENT "",
  `C_ADDRESS` varchar(100) NOT NULL COMMENT "",
  `C_CITY` varchar(100) NOT NULL COMMENT "",
  `C_NATION` varchar(100) NOT NULL COMMENT "",
  `C_REGION` varchar(100) NOT NULL COMMENT "",
  `C_PHONE` varchar(100) NOT NULL COMMENT "",
  `C_MKTSEGMENT` varchar(100) NOT NULL COMMENT "",
  `S_NAME` varchar(100) NOT NULL COMMENT "",
  `S_ADDRESS` varchar(100) NOT NULL COMMENT "",
  `S_CITY` varchar(100) NOT NULL COMMENT "",
  `S_NATION` varchar(100) NOT NULL COMMENT "",
  `S_REGION` varchar(100) NOT NULL COMMENT "",
  `S_PHONE` varchar(100) NOT NULL COMMENT "",
  `P_NAME` varchar(100) NOT NULL COMMENT "",
  `P_MFGR` varchar(100) NOT NULL COMMENT "",
  `P_CATEGORY` varchar(100) NOT NULL COMMENT "",
  `P_BRAND` varchar(100) NOT NULL COMMENT "",
  `P_COLOR` varchar(100) NOT NULL COMMENT "",
  `P_TYPE` varchar(100) NOT NULL COMMENT "",
  `P_SIZE` tinyint(4) NOT NULL COMMENT "",
  `P_CONTAINER` varchar(100) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`LO_ORDERKEY`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`LO_ORDERKEY`) BUCKETS 192
PROPERTIES (
"replication_num" = "1",
"colocate_with" = "x23123fel",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```
2. Restart be frequently

### Real behavior (Required)
Some replica in this table stays in DECOMMISSION state, Query on this table failed.
image

### StarRocks version (Required)
 - All version

### PR DESCRIPTION
**Pull request by gengjun-git**
To remove the redundant replica, proceed as follows.
1. Select the replica to be dropped according to the following priority
   1). replica on the backend, which was dropped.
   2). replica state is bad
   3). replica is unavailable
   4). replica' state is under clone or decommission.
   5). replica with failed version.
   6). replica with a lower version.
   7). replica on the same host.
   8). replica as the balance source.
   9). replica stored on high load backend.
2. Set the replica state to decommission, find the current largest txn number and return the TabletSchedCtx to the scheduling queue.
3. All the txn smaller than the found txn number is finished. FE can drop this replica.

But the second and third steps may be separated by a long time. Another replica sees the problem, like the version incomplete or backend unavailable during this period. The scheduler may go through other repair processes or select another replica to decommission if this happens. The replica state will stay as decommissioned and not be scheduled.

To fix this problem, reset the decommissioned replica state when
1. Scheduler chooses another replica to decommission.
2. TabletSchedCtx is finished.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java [hunk 1]
```diff
@@ -705,6 +708,19 @@ private void reset(boolean reserveTablet) {
         }
     }
 
+    public void resetDecommissionReplicaState() {
+        if (decommissionedReplica != null
+                && decommissionedReplica.getState() == ReplicaState.DECOMMISSION
+                && decommissionedReplicaPreviousState != null) {
+            decommissionedReplica.setState(decommissionedReplicaPreviousState);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java:715]: Could we revert the state if the previous state is not a NORMAL state?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/clone/TabletSchedCtx.java:715]: Yes, and we must do it. If the previous state is clone, we should reset the state to clone so that it can be correctly scheduled. Replica in schema change state will never be choose to repair or balance.

**Comment by gengjun-git** [comment]
close #1976

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
