### PR TITLE
[Bugfix] Try catch runtime_error in TRY_CATCH_BAD_ALLOC

### LINKED ISSUE #10265: BE crash even if already TRY_CATCH_BAD_ALLOC
### Steps to reproduce the behavior (Required)
- Dataset: SSB with 100GB scale.
- Query:
```sql
with 
	t1 as (select 1 as x, bitmap_union(to_bitmap(lo_orderkey)) as key_bitmap from lineorder_flat),
	t2 as (select 1 as x, lo_orderkey from lineorder_flat)
select lo_orderkey
from t2 left join t1 using(x)
where bitmap_contains(t1.key_bitmap, lo_orderkey);
```

### Expected behavior (Required)
Return results normally, or report an error to the client.

### Real behavior (Required)
BE crashed, and the error stack is as follows:
```
terminate called after throwing an instance of 'std::runtime_error'
terminate called recursively
  what():  *** Aborted at 1660987693 (unix time) try "date -d @1660987693" if you are using GNU date ***
failed memory alloc in constructorterminate called recursively
terminate called recursively
terminate called recursively

terminate called recursively
terminate called recursively
terminate called recursively
PC: @     0x7fb6d6ccf337 __GI_raise
*** SIGABRT (@0x3e800003cb7) received by PID 15543 (TID 0x7fb67a148700) from PID 15543; stack trace: ***
    @          0x4675472 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb6d77845f0 (unknown)
    @     0x7fb6d6ccf337 __GI_raise
    @     0x7fb6d6cd0a28 __GI_abort
    @          0x6047442 __gnu_cxx::__verbose_terminate_handler()
    @          0x6045ee6 __cxxabiv1::__terminate()
    @          0x6045f51 std::terminate()
    @          0x60460f9 __cxa_rethrow
    @          0x1a381b2 _ZNSt8_Rb_treeIjSt4pairIKj7RoaringESt10_Select1stIS3_ESt4lessIjESaIS3_EE7_M_copyINS9_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS3_EPKSD_PSt18_Rb_tree_node_baseRT_.isra.0.cold
    @          0x257238b starrocks::BitmapValue::BitmapValue()
    @          0x2a13dfb starrocks::vectorized::ObjectColumn<>::append()
    @          0x2a14085 starrocks::vectorized::ObjectColumn<>::append_selective()
    @          0x2a075e3 starrocks::vectorized::NullableColumn::append_selective()
    @          0x2bb34c3 starrocks::vectorized::JoinHashMap<>::_copy_build_nullable_column()
    @          0x2bb3826 starrocks::vectorized::JoinHashMap<>::_build_output()
    @          0x2c1bd19 starrocks::vectorized::JoinHashMap<>::probe()
    @          0x2b9f1c3 starrocks::vectorized::JoinHashTable::probe()
    @          0x2e8111d starrocks::vectorized::HashJoiner::_pull_probe_output_chunk()
    @          0x2e81872 starrocks::vectorized::HashJoiner::pull_chunk()
    @          0x2e16a79 starrocks::pipeline::HashJoinProbeOperator::pull_chunk()
    @          0x2dc80a3 starrocks::pipeline::PipelineDriver::process()
    @          0x2dbe8e3 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x261bfc5 starrocks::ThreadPool::dispatch_thread()
    @          0x26174ea starrocks::Thread::supervise_thread()
    @     0x7fb6d777ce65 start_thread
    @     0x7fb6d6d9788d __clone
    @                0x0 (unknown)
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10265.

## Problem Summary(Required) ：

Some third-party libraries throw `std::runtime_error` instead of `std::bad_alloc`, when it fails to allocate memory.

This will occur more frequently, when we use `TRY_CATCH_BAD_ALLOC`. The reason is that, 
- if we don't use `TRY_CATCH_BAD_ALLOC`, the system will try its best to allocate memory.
- If we use `TRY_CATCH_BAD_ALLOC`, we check whether it exceed `mem_limit` before really allocating memory, and  return `nullptr` to indicate failing to allocate memory.

Therefore, also try catch `runtime_error` in `TRY_CATCH_BAD_ALLOC`.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_admit_test

**Comment by ZiheLiu** [comment]
@Mergifyio backport branch-2.2 branch-2.3 branch-2.4

**Review by murphyatwork — APPROVED** [review]

File: be/src/runtime/current_thread.h [hunk 1]
```diff
@@ -245,23 +245,15 @@ class CurrentThreadCatchSetter {
         } else {                                                                                                       \
             return Status::MemoryLimitExceeded("Mem usage has exceed the limit of BE");                                \
         }                                                                                                              \
+    }                                                                                                                  \
+    catch (std::runtime_error const& e) {                                                                              \
```
Comment (kangkaisen) [inline be/src/runtime/current_thread.h:249]: Don't all std::runtime_error meaning bad alloc, why we could handle it by this way?

Comment (ZiheLiu) [reply be/src/runtime/current_thread.h:249]: Although it could throw `std:: runtime_error` by other reasons, it is OK to try catch it and return an error status to FE. The reason is that, the codes using `TRY_CATCH_BAD_ALLOC` is expcetion-safe, and FE will receive an error status.

`ExprContext::evaluate` also try catch `std:: runtime_error`, when string function generate a large column.

**Review by kangkaisen — APPROVED** [review]
