### PR TITLE
[Enhancement] Remove DCHECK in es_predicate.cpp to avoid BE crashed in ASAN mode

### LINKED ISSUE #30391: [DailyASAN] ES predicate push down creash
### Steps to reproduce the behavior (Required)

```
nosetests-3.4 -s --with-xunit --xunit-file=./result/${CLUSTER_ID}/test_es_catalog_select_py_TestEsConnectorSelect_test_es_catalog_select_predicate.xml --verbose case/system_case/test_ddl/test_es_connector/test_es_catalog_select.py:TestEsConnectorSelect.test_es_catalog_select_predicate --nologcaptur
select * from `nested-type-test` where k2 not in('{"k21": "v21", "k22": "v21"}', '{"k21": "v21", "k22": "v23"}');
```

```
*** Aborted at 1692017054 (unix time) try "date -d @1692017054" if you are using GNU date ***
PC: @     0x7f79f6e24387 __GI_raise
*** SIGABRT (@0x3f00002cf79) received by PID 184185 (TID 0x7f7965756700) from PID 184185; stack trace: ***
    @         0x14154952 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f79f71cb630 (unknown)
    @     0x7f79f6e24387 __GI_raise
    @     0x7f79f6e25a78 __GI_abort
    @          0x9943dc3 starrocks::failure_function()
    @         0x1414832d google::LogMessage::Fail()
    @         0x1414a79f google::LogMessage::SendToLog()
    @         0x14147e7e google::LogMessage::Flush()
    @         0x1414ada9 google::LogMessageFatal::~LogMessageFatal()
    @         0x1304c81d starrocks::EsPredicate::_build_in_predicate()
    @         0x13046aca starrocks::EsPredicate::_vec_build_disjuncts_list()
    @         0x130465ca starrocks::EsPredicate::build_disjuncts_list()
    @         0x12fe02a2 starrocks::connector::ESDataSource::_build_conjuncts()
    @         0x12fdf55a starrocks::connector::ESDataSource::open()
    @          0xc177d42 starrocks::pipeline::ConnectorChunkSource::_open_data_source()
    @          0xc1783cb starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0xd10fbd8 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking()
    @          0xc11bdc2 _ZZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS_12RuntimeStateEiENKUlvE_clEv
    @          0xc121640 _ZSt13__invoke_implIvRZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS0_12RuntimeStateEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0xc1214ee _ZSt10__invoke_rIvRZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS0_12RuntimeStateEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES8_E4typeEOS9_DpOSA_
    @          0xc121363 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x9832480 std::function<>::operator()()
    @          0xc653933 starrocks::workgroup::ScanExecutor::worker_thread()
    @          0xc653158 _ZZN9starrocks9workgroup12ScanExecutor10initializeEiENKUlvE_clEv
    @          0xc65510e _ZSt13__invoke_implIvRZN9starrocks9workgroup12ScanExecutor10initializeEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0xc654cdd _ZSt10__invoke_rIvRZN9starrocks9workgroup12ScanExecutor10initializeEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @          0xc65467a _ZNSt17_Function_handlerIFvvEZN9starrocks9workgroup12ScanExecutor10initializeEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x9832480 std::function<>::operator()()
    @          0xa27d34c starrocks::FunctionRunnable::run()
    @          0xa279e0b starrocks::ThreadPool::dispatch_thread()
    @          0xa296c3e std::__invoke_impl<>()
    @          0xa296729 std::__invoke<>()
F0814 20:44:14.731554 184522 es_predicate.cpp:427] Check failed: false unsupported type:54
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Fixes https://github.com/StarRocks/starrocks/issues/30391

We don't support pushdown JSON's in_predicate into es now.

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

File: be/src/exec/es/es_predicate.cpp [hunk 1]
```diff
@@ -424,7 +424,7 @@ Status EsPredicate::_build_in_predicate(const Expr* conjunct, bool* handled) {
             BUILD_INPRED_VALUES(TYPE_CHAR)
             BUILD_INPRED_VALUES(TYPE_VARCHAR)
         default:
-            DCHECK(false) << "unsupported type:" << expr->type().type;
+            // We don't support pushdown json type's in_predicates to ES now.
```
Comment (trueeyu) [inline be/src/exec/es/es_predicate.cpp:427]: Add the comment for fallback logic?

Comment (Smith-Cruise) [reply be/src/exec/es/es_predicate.cpp:427]: added

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by trueeyu — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
