### PR TITLE
[BugFix] Fix auth upgrade failure when replaying old auth journal

### LINKED ISSUE #17451: [BugFix] auth upgrade failed when replaying old auth journal
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### Real behavior (Required)
```
2023-02-06 20:01:22,545 WARN (replayer|93) [GlobalStateMgr.replayJournalInner():1949] catch exception when replaying 102485,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 62
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1011) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1938) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1795) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1860) [starrocks-fe.jar:?]
Caused by: java.lang.NullPointerException
        at com.starrocks.server.GlobalStateMgr.replayOldAuthJournal(GlobalStateMgr.java:3474) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:505) ~[starrocks-fe.jar:?]
        ... 4 more
2023-02-06 20:01:22,549 WARN (replayer|93) [GlobalStateMgr$5.runOneCycle():1798] got interrupt exception or inconsistent exception when replay journal 102485, will exit,
com.starrocks.journal.JournalInconsistentException: failed to load journal type 62
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:1011) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.replayJournalInner(GlobalStateMgr.java:1938) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.runOneCycle(GlobalStateMgr.java:1795) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:115) [starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr$5.run(GlobalStateMgr.java:1860) [starrocks-fe.jar:?]
Caused by: java.lang.NullPointerException
        at com.starrocks.server.GlobalStateMgr.replayOldAuthJournal(GlobalStateMgr.java:3474) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:505) ~[starrocks-fe.jar:?]
        ... 4 more
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17451 

## Problem Summary(Required) ：

For follower/observer, defer setting auth to null when we have replayed all the journal,
because we may encounter old auth journal when replaying log in which case we still
need the auth object. This problem can happend in the following senario:
1. start 3fe cluster with old auth version
2. create some users
3. upgrade to new privilege framework
4. rollback to old auth version
5. create some user
6. upgrade again

Signed-off-by: Dejun Xia <xiadejun@starrocks.com>

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|2|00.00%|[1854, 1856]|

**Comment by nshangyiming** [comment]
run starrocks_fe_unittest

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|7|71.43%|[1855, 1857]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -1851,6 +1848,14 @@ private void setCanRead(boolean hasLog, boolean err) {
                 } else {
                     canRead.set(true);
                     isReady.set(true);
+
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1851]: I think better not add the process logic here, you can add the logic in the GlobalStateMgr.waitForReady();

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 2]
```diff
@@ -3525,9 +3530,11 @@ public void replayOldAuthJournal(short code, Writable data) throws DdlException
     }
 
     public void replayAuthUpgrade(AuthUpgradeInfo info) throws AuthUpgrader.AuthUpgradeUnrecoverableException {
-        if (GlobalStateMgr.getCurrentState().needUpgradedToNewPrivilege()) {
+        GlobalStateMgr globalStateMgr = GlobalStateMgr.getCurrentState();
+        if (!globalStateMgr.isUsingNewPrivilege() || globalStateMgr.needUpgradedToNewPrivilege()) {
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:3534]: When globalStateMgr.isUsingNewPrivilege is False?

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java (hunk 1 above)
Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1851]: good point, fixed

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|7|71.43%|[1855, 1857]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|1|1|100.00%|[]|

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 7 / 8 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|6|7|85.71%|[1020]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|1|1|100.00%|[]|

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 23 (91.30%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/ResourceGroupMgr.java|0|1|00.00%|[174]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|17|18|94.44%|[1020]|
|:large_blue_circle:|com/starrocks/mysql/privilege/AuthUpgrader.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/privilege/PrivilegeManager.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/authentication/AuthenticationManager.java|1|1|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
