### PR TITLE
Fix show tablet failed when drop be

### LINKED ISSUE #160: Show tablet detail failed
Show tablet detail using the DetailCmd from `show tablet tablet_id` throws NullPointerException.
image

### PR DESCRIPTION
**Pull request by gengjun-git**
Fix #160

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicasProcNode.java [hunk 1]
```diff
@@ -93,5 +93,19 @@ public ProcResult fetchResult() {
         }
         return result;
     }
+
+    private String getBackendHost(ImmutableMap<Long, Backend> backendMap, long backendId) {
+        if (backendMap.containsKey(backendId)) {
+            return backendMap.get(backendId).getHost();
+        }
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/common/proc/ReplicasProcNode.java:100]: I prefer getting from map and checking if the return value is null.

**Review by imay — APPROVED** [review]
