### PR TITLE
[BugFix] StreamLoad not working for URL encoded chinese characters

### LINKED ISSUE #59721: [BUG] StreamLoad not working for URL encoded chinese characters
### Steps to reproduce the behavior (Required)
create table testStreamLoad桌 (c1 int(10), c2 varchar(100)) engine=olap PROPERTIES("replication_num"="1");

insert data through stream load
curl -v -k --location-trusted -uroot -H "label:table1" -H "column_separator:," -T data.csv http://127.0.0.1:8030/api/mydb/testStreamLoad%E6%A1%8C/_stream_load

### Expected behavior (Required)
stream load should be success

### Real behavior (Required)
curl -v -k --location-trusted -uroot -H "label:table1" -H "column_separator:," -T data.csv http://127.0.0.1:8030/api/mydb/testStreamLoad%E6%A1%8C/_stream_load

Image

mysql> select * from testStreamLoad桌;
Empty set (0.01 sec)

### StarRocks version (Required)
 main-2bc7dcf

### PR DESCRIPTION
**Pull request by rohitrs1983**
RestBaseAction.java redirectTo() incorrectly processes the table name, should use resultUriObj.toASCIIString() instead of resultUriObj.toString()

Fixes #59721

curl -v -k --location-trusted -uroot -H "label:table1" -H "column_separator:," -T data.csv http://127.0.0.1:8030/api/mydb/testStreamLoad%E6%A1%8C/_stream_load
image

image

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.5
  - [X] 3.4
  - [X] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: be/test/util/url_coding_test.cpp [hunk 1]
```diff
@@ -0,0 +1,45 @@
+#include "util/url_coding.h"
```
Comment (alvin-phoenix-ai) [inline be/test/util/url_coding_test.cpp:18]: A license header is needed.

File: be/src/util/url_coding.h [hunk 2]
```diff
@@ -32,4 +32,8 @@ bool base64_decode(const std::string& in, std::string* out);
 // refers to https://stackoverflow.com/questions/154536/encode-decode-urls-in-c
 std::string url_encode(const std::string& decoded);
 
+// Utility method to decode a string that was URL-encoded. Returns
+// true unless the string could not be correctly decoded.
```
Comment (alvin-phoenix-ai) [inline be/src/util/url_coding.h:38]: An example in comment will help a lot

File: be/src/util/url_coding.h [hunk 3]
```diff
@@ -32,4 +32,8 @@ bool base64_decode(const std::string& in, std::string* out);
...
+bool url_decode(const std::string& in, std::string* out);
```
Comment (alvin-phoenix-ai) [inline be/src/util/url_coding.h]:
```suggestion
StatusOr<std::string>  url_decode(const std::string& in);
```
With StatusOr as return type, invalid details can be returned.

File: be/src/http/action/stream_load.cpp [hunk 4]
```diff
@@ -231,8 +232,8 @@ int StreamLoadAction::on_header(HttpRequest* req) {
     ctx->load_type = TLoadType::MANUAL_LOAD;
     ctx->load_src_type = TLoadSourceType::RAW;
 
-    ctx->db = req->param(HTTP_DB_KEY);
-    ctx->table = req->param(HTTP_TABLE_KEY);
+    url_decode(req->param(HTTP_DB_KEY), &ctx->db);
+    url_decode(req->param(HTTP_TABLE_KEY), &ctx->table);
```
Comment (alvin-phoenix-ai) [inline be/src/http/action/stream_load.cpp]: The return value should be checked in case of invalid inputs.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java [hunk 5]
```diff
@@ -210,7 +210,7 @@ public void redirectTo(BaseRequest request, BaseResponse response, TNetworkAddre
             LOG.warn(e.getMessage(), e);
             throw new DdlException(e.getMessage());
         }
-        response.updateHeader(HttpHeaderNames.LOCATION.toString(), resultUriObj.toString());
+        response.updateHeader(HttpHeaderNames.LOCATION.toString(), resultUriObj.toASCIIString());
```
Comment (alvin-phoenix-ai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java:213]: Could you add a UT to cover this case?

**Comment by alvin-phoenix-ai** [comment]
First of all, thanks for your contribution.  @rohitrs1983 
We have just upgraded the backport. policy; versions previous to 3.3reeze mode; code won't be cherry-picked into them unless severe CVE issues are found. For more information, refer to https://docs.starrocks.io/docs/developers/versions/.

File: be/src/util/url_coding.h (hunk 2 above)
Comment (rohitrs1983) [reply be/src/util/url_coding.h:38]: updated.

File: be/test/util/url_coding_test.cpp (hunk 1 above)
Comment (rohitrs1983) [reply be/test/util/url_coding_test.cpp:18]: updated.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java (hunk 5 above)
Comment (rohitrs1983) [reply fe/fe-core/src/main/java/com/starrocks/http/rest/RestBaseAction.java:213]: added UT for this case.

File: be/src/util/url_coding.h (hunk 3 above)
Comment (rohitrs1983) [reply be/src/util/url_coding.h]: updated.

File: be/src/http/action/stream_load.cpp (hunk 4 above)
Comment (rohitrs1983) [reply be/src/http/action/stream_load.cpp]: updated.

**Review by alvin-phoenix-ai — DISMISSED** [review]

**Review by meegoo — DISMISSED** [review]

File: be/src/util/url_coding.cpp [hunk 6]
```diff
@@ -162,4 +163,37 @@ std::string url_encode(const std::string& decoded) {
     return result;
 }
 
+// Adapted from
+// http://www.boost.org/doc/libs/1_40_0/doc/html/boost_asio/
+//   example/http/server3/request_handler.cpp
+// See http://www.boost.org/LICENSE_1_0.txt for license for this method.
+StatusOr<std::string> url_decode(const std::string& in) {
```
Comment (kevincai) [inline be/src/util/url_coding.cpp:166]: possibly leverage https://curl.se/libcurl/c/curl_easy_unescape.html instead of hand-made decoding? the same way as the `url_encode()` implementation.

**Review by kevincai — DISMISSED** [review]

File: be/src/util/url_coding.cpp (hunk 6 above)
Comment (rohitrs1983) [reply be/src/util/url_coding.cpp:166]: updated.

File: be/test/util/url_coding_test.cpp [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+
+#include "util/url_coding.h"
+
+#include <gtest/gtest.h>
+
+#include <string>
+
+namespace starrocks {
+
+TEST(UrlCodingTest, UrlDecodeBasic) {
```
Comment (kevincai) [inline be/test/util/url_coding_test.cpp:26]: add a case to explicit that '+' will not be unescaped to ' '

Comment (rohitrs1983) [reply be/test/util/url_coding_test.cpp:26]: @kevincai thanks for the review. added test case.

**Review by kevincai — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
