### PR TITLE
[BugFix] Fix the data race of event_bases and event_https

### LINKED ISSUE #7792: start be failed.
### Steps to reproduce the behavior (Required)
./start_be.sh --daemon
### Expected behavior (Required)
start be successfully.
### Real behavior (Required)
```
start time: Fri Jun 24 17:54:43 CST 2022
*** Aborted at 1656064496 (unix time) try "date -d @1656064496" if you are using GNU date ***
PC: @          0x24abfcb std::vector<>::_M_realloc_insert<>()
*** SIGSEGV (@0x7ba3f0) received by PID 20921 (TID 0x7f609403d700) from PID 8102896; stack trace: ***
    @          0x4000ad2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f616ce41630 (unknown)
    @          0x24abfcb std::vector<>::_M_realloc_insert<>()
    @          0x24a9efb _ZZN9starrocks12EvHttpServer5startEvENKUlvE_clEv
    @          0x5a7e410 execute_native_thread_routine
    @     0x7f616ce39ea5 start_thread
    @     0x7f616c4548dd __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 7d9ebcb |
+----------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by chaoyli**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7792

### CODE REVIEW

**Review by decster — DISMISSED** [review]

File: be/src/http/ev_http_server.cpp [hunk 1]
```diff
@@ -105,15 +105,20 @@ Status EvHttpServer::start() {
                 LOG(WARNING) << "Couldn't create an event_base.";
                 return;
             }
+            pthread_rwlock_rdlock(&_rw_lock);
```
Comment (imay) [inline be/src/http/ev_http_server.cpp:108]: why rdlock? should be rwlock?

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run all

**Review by decster — APPROVED** [review]
