### PR TITLE
[BugFix] fix rpc closure unexpected delete (#19235)

### LINKED ISSUE #19235: response in multi_get rpc been deleted at callback
expect delete in `DeferOp` at end of function.

### PR DESCRIPTION
**Pull request by liuyufei9527**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: be/src/storage/table_reader.cpp [hunk 1]
```diff
@@ -264,6 +264,7 @@ Status TableReader::_tablet_multi_get_rpc(doris::PBackendService_Stub* stub, int
         closure->cntl.set_timeout_ms(_params->timeout_ms);
     }
     stub->local_tablet_reader_multi_get(&closure->cntl, &request, &closure->result, closure);
+    closure->ref();
```
Comment (imay) [inline be/src/storage/table_reader.cpp:267]: This closure is `referenced` in 256, which means this closure can not be deleted in this function.
So why do you add a new ref here?

Comment (liuyufei9527) [reply be/src/storage/table_reader.cpp:267]: @imay 
At 
 [ref_count_closure.h#L41](https://github.com/StarRocks/starrocks/blob/45f45d98e1be6f1c0f449047bd759c3428983c26/be/src/util/ref_count_closure.h#L41), will count down ref count when rpc return, ater `closure->join()`, 'closure' was deleted.
Expected behavior is delete at end of function, ref twice, callback unref once, end of function unref and delete.

Comment (alvin-phoenix-ai) [inline be/src/storage/table_reader.cpp]:
```suggestion
    closure->ref();
    stub->local_tablet_reader_multi_get(&closure->cntl, &request, &closure->result, closure);
```

**Comment by alvin-phoenix-ai** [comment]
@mergify rebase
