### PR TITLE
[BugFix] BE crash when invoke list_rowsets() in non shared mode

### LINKED ISSUE #57461: [Bug] BE crash when invoke list_rowsets() in non shared mode
#0  starrocks::lake::TabletManager::get_tablet_metadata (this=this@entry=0x0, tablet_id=24015, version=10, fill_cache=fill_cache@entry=true, expected_gtid=expected_gtid@entry=0, fs=...) at be/src/storage/lake/tablet_manager.cpp:321
#1  0x000000000acda809 in starrocks::ListRowsets::process (this=<optimized out>, runtime_state=<optimized out>, base_state=0x7a3ecf398f60) at be/src/exprs/table_function/list_rowsets.cpp:121
#2  0x000000000acb69f7 in starrocks::pipeline::TableFunctionOperator::_process_table_function (this=0x7a405d897e10, state=0x7a3ecf468c00) at be/src/exec/pipeline/table_function_operator.cpp:185
#3  0x000000000acb73b6 in starrocks::pipeline::TableFunctionOperator::pull_chunk (this=0x7a405d897e10, state=0x7a3ecf468c00) at be/src/exec/pipeline/table_function_operator.cpp:117
#4  0x000000000774b7e9 in starrocks::pipeline::PipelineDriver::process (this=0x7a3e6924a610, runtime_state=0x7a3ecf468c00, worker_id=<optimized out>) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#5  0x000000000acf3aee in starrocks::pipeline::GlobalDriverExecutor::_worker_thread (this=0x7a40630a8120) at be/src/exec/pipeline/pipeline_driver_executor.cpp:156
#6  0x000000000b1eb6d3 in starrocks::ThreadPool::dispatch_thread (this=0x7a4062fcdd00) at /usr/include/c++/11/bits/shared_ptr_base.h:1295
#7  0x000000000b1e2709 in std::function<void ()>::operator()() const (this=0x7a40635ff718) at /usr/include/c++/11/bits/std_function.h:590
#8  starrocks::Thread::supervise_thread (arg=0x7a40635ff700) at be/src/util/thread.cpp:366
#9  0x00007a407289caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#10 0x00007a4072929c3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

### Steps to reproduce the behavior (Required)
mysql> select * from TABLE(list_rowsets(24015, 10));

### Expected behavior (Required)
BE should not crash

### StarRocks version (Required)
-main-2bbc265

### PR DESCRIPTION
**Pull request by rohitrs1983**
Fixes #57461

mysql> select * from TABLE(list_rowsets(24015, 10));
ERROR 1064 (HY000): Only works for tablets in the cloud-native table: BE:11001

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

**Comment by wyb** [comment]
Please add UT or sql test

**Comment by rohitrs1983** [comment]
> Please add UT or sql test

@wyb updated. added sql test. thanks.

**Review by wyb — DISMISSED** [review]

File: be/src/exprs/table_function/list_rowsets.cpp [hunk 1]
```diff
@@ -89,6 +89,10 @@ std::pair<Columns, UInt32Column::Ptr> ListRowsets::process(RuntimeState* runtime
     }
 
     auto tablet_mgr = ExecEnv::GetInstance()->lake_tablet_manager();
+    if (UNLIKELY(tablet_mgr == nullptr)) {
```
Comment (wyb) [inline be/src/exprs/table_function/list_rowsets.cpp:92]: `lake_tablet_manager` is not `nullptr` because `--enable-shared-data` is `ON` by default in the release build.

Comment (rohitrs1983) [reply be/src/exprs/table_function/list_rowsets.cpp:92]: @wyb added unit test case.

**Review by wyb — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
