### PR TITLE
[BugFix] some bug fix for auto increment (#20575)

### LINKED ISSUE #20575: [BugFix] some bug fix for auto increment
Problem 1:
Currently, auto increment column does not support modify a column into a AUTO_INCREMENT column. But it is possible that modify a AUTO_INCREMENT column into a normal column. This should be abort.

Problem 2:
There is no mechanism to handle the overflow of the auto increment id counter, which will cause be crash.

Problem 3:
The planning for insert into is not feasible when the auto increment is not specified and defined before other normal column.

Problem 4:
When we recover a table, the auto increment id will restart from 0, which is a problem.

Solution:
1. Abort the case that we modify a AUTO_INCREMENT column into a normal column.
2. Throw an exception when the id counter is overflow.
3. Fix the planning problem for insert statement.
4. remove the auto increment id when truly erase the table.

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20575

## Problem Summary(Required) ：
Problem 1:
Currently, the auto-increment column does not support modifying a column into an AUTO_INCREMENT column. But it is possible that modify an AUTO_INCREMENT column into a normal column. This should be aborted.

Problem 2:
There is no mechanism to handle the overflow of the auto-increment id counter, which will cause be crash.

Problem 3:
The planning for inserting into is not feasible when the auto-increment is not specified and defined before another normal column.

Problem 4:
When we recover a table, the auto-increment id will restart from the beginning, which is a problem.

Solution:
1. Abort the case that we modify an AUTO_INCREMENT column into a normal column.
2. Throw an exception when the id counter is overflowing.
3. Fix the planning problem for the insert statement.
4. remove the auto increment id when truly erasing the table.5. 
5. add some test case for auto increment.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/storage/storage_engine.cpp [hunk 1]
```diff
@@ -1199,7 +1199,12 @@ Status StorageEngine::get_next_increment_id_interval(int64_t tableid, size_t num
         auto st = _get_remote_next_increment_id_interval(alloc_params, &alloc_result);
 
         if (!st.ok() || alloc_result.status.status_code != TStatusCode::OK) {
-            return Status::InternalError("auto increment allocate failed");
+            std::string err_msg;
```
Comment (imay) [inline be/src/storage/storage_engine.cpp:1202]: need to use std::stringstream to reduce copy

File: be/src/storage/storage_engine.cpp [hunk 2]
```diff
@@ -1199,7 +1199,12 @@ Status StorageEngine::get_next_increment_id_interval(int64_t tableid, size_t num
...
+            for (auto msg : alloc_result.status.error_msgs) {
```
Comment (imay) [inline be/src/storage/storage_engine.cpp:1203]:
```suggestion
            for (auto& msg : alloc_result.status.error_msgs) {
```
use reference to reduce copy

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java [hunk 3]
```diff
@@ -380,6 +380,11 @@ private void processModifyColumn(ModifyColumnClause alterClause, OlapTable olapT
         }
 
         Column oriColumn = schemaForFinding.get(modColIndex);
+
+        if (oriColumn.isAutoIncrement()) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java:384]: should add UT/sql-test to cover this case

**Review by imay — COMMENTED** [review]
You need to add UT to cover this fixes.

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 4]
```diff
@@ -1584,6 +1585,17 @@ public TAllocateAutoIncrementIdResult allocAutoIncrementId(TAllocateAutoIncremen
             result.setAllocated_rows(0);
 
             TStatus status = new TStatus(TStatusCode.INTERNAL_ERROR);
+            status.setError_msgs(Lists.newArrayList(e.getMessage()));
+            result.setStatus(status);
+            return result;
+        }
+
+        if (nextId == null) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java:1593]: When the nextId == null?

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 5]
```diff
@@ -308,6 +308,11 @@ protected synchronized void eraseDatabase(long currentTimeMs) {
             RecycleDatabaseInfo dbInfo = entry.getValue();
             Database db = dbInfo.getDb();
             if (canErase(db.getId(), currentTimeMs)) {
+                List<Table> tables = db.getTables();
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:311]: There is no need to delete the table's incrementId for erase db. Because the db's table has been put to idToTableInfo, it will be erased on the eraseTable function.

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 6]
```diff
@@ -340,6 +345,13 @@ private synchronized void eraseDatabaseWithSameName(String dbName) {
     }
 
     public synchronized void replayEraseDatabase(long dbId) {
+        RecycleDatabaseInfo dbInfo = idToDatabase.get(dbId);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:348]: same to above.

**Review by gengjun-git — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
