### PR TITLE
[Bugfix] clear rowsets before load

### LINKED ISSUE #9192: [Bug] no delete vector found error after schemachange
### Real behavior (Required)
```
I0715 17:36:28.954669 701991 task_worker_pool.cpp:262] success to submit task. type=ALTER, signature=[614618], task_count_in_queue=1
I0715 17:36:28.958511 532736 task_worker_pool.cpp:463] get alter table task, signature: 614618
I0715 17:36:28.958963 532736 schema_change.cpp:919] begin to do request alter tablet: base_tablet_id=614608, base_schema_hash=608225881, new_tablet_id=614618, new_schema_hash=579097252, alter_version=17
I0715 17:36:28.958971 532736 schema_change.cpp:968] finish to validate alter tablet request. begin to convert data from base tablet to new tablet base_tablet=614608.608225881.f44513bfe6d6dfa9-73edf510c84ba08a new_tablet=614618.579097252.754d67638a326592-a025682ad16e59bc
I0715 17:36:28.959028 532736 tablet_updates.cpp:1907] link_from start tablet:614618 #pending:0 base_tablet:614608 request_version:17
I0715 17:36:28.989811 532736 primary_index.cpp:860] unload primary index tablet:614618 size:20345 capacity:32752 memory: 425776
E0715 17:36:29.209848 532736 tablet_updates.cpp:240] _load_from_pb get_del_vector failed: Not found: no delete vector found tablet:614618 segment:15 version:9223372036854775807
I0715 17:36:29.210184 532736 tablet_updates.cpp:2026] link_from finish tablet:614618 version:17 base tablet:614608 #pending:0 time:0.251161s #rowset:3 #file:3 #row:20345 bytes:7292231
I0715 17:36:29.210273 532736 task_worker_pool.cpp:532] alter finished. signature: 614618
I0715 17:36:29.210276 532736 tablet_manager.cpp:787] Reporting tablet info. tablet_id=614618
I0715 17:36:29.210281 532736 task_worker_pool.cpp:557] alter success. signature: 614618

```
### StarRocks version (Required)
2.1 2.2 2.3

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9192

## Problem Summary(Required) ：

SchemaChange will call _load_from_pb to reload metadata, but _load_from_pb forgets to reset `_rowsets` vector, so some old rowsets may still be stored in `_rowsets`, causing `no delvec found error`, because the delvec corresponds to the old rowset is already removed. This PR clears `_rowsets` vector before load new rowsets from meta.

### CODE REVIEW

File: be/src/storage/tablet_updates.cpp [hunk 1]
```diff
@@ -164,6 +164,7 @@ Status TabletUpdates::_load_from_pb(const TabletUpdatesPB& tablet_updates_pb) {
     // Load all rowsets of this tablet into memory.
     // NOTE: This may change in a near future, e.g, manage rowsets in a separate module and load
     // them on demand.
+    _rowsets.clear();
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:167]: It's better to add commit message to describe the problem and solution

Comment (decster) [reply be/src/storage/tablet_updates.cpp:167]: updated

**Review by sevev — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
