### PR TITLE
Modify the statistical method of WaitTime of Exchange

### LINKED ISSUE #4740: Crash when ScanOperator::close
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
CREATE TABLE `t1` (
  `rowid` bigint(20) NULL COMMENT "",
  `a` bigint(20) NULL COMMENT "",
  `x` varchar(255) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`rowid`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`rowid`) BUCKETS 10
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

data:
```sql
+---------------------+----+----------------------------------+
| rowid               | a  | x                                |
+---------------------+----+----------------------------------+
| 32767               | 19 | 0000000000007fff                 |
| 1                   | 21 | 0000000000000001                 |
| -134217729          | 10 | fffffffffffffffffffffffff7ffffff |
| 15                  | 17 | 000000000000000f                 |
| -129                | 16 | ffffffffffffffffffffffffffffff7f |
| -8388608            | 25 | ffffffffffffffffffffffffff800000 |
| 524288              | 6  | 0000000000080000                 |
| -140737488355329    | 15 | ffffffffffff7fffffff7fffffffffff |
| -549755813888       | 7  | ffffffffffffff80ffffff8000000000 |
| 549755813888        | 23 | 000000808000000000               |
| 8388608             | 12 | 0000000000800000                 |
| 576460752303423488  | 18 | 08000000800000000000000          |
| 134217727           | 22 | 0000000007ffffff                 |
| 9223372036854775807 | 3  | 7fffffff7fffffffffffffff         |
| -32768              | 11 | ffffffffffffffffffffffffffff8000 |
| -524288             | 13 | fffffffffffffffffffffffffff80000 |
| -36028797018963968  | 1  | ffffffffff800000ff80000000000000 |
| -17                 | 5  | ffffffffffffffffffffffffffffffef |
| 140737488355327     | 9  | 00007fff7fffffffffff             |
| 2147483647          | 24 | 000000007fffffff                 |
| -8796093022208      | 2  | fffffffffffff800fffff80000000000 |
```

query:
```sql
SELECT rowid, a FROM t1 WHERE rowid > 8796093022208.0 and rowid is not null ORDER BY rowid
```

### Real behavior (Required)
Crashed.

```
*** Check failure stack trace: ***
    @          0x8d035fd  google::LogMessage::Fail()
    @          0x8d058d9  google::LogMessage::SendToLog()
    @          0x8d03179  google::LogMessage::Flush()
    @          0x8d05ed9  google::LogMessageFatal::~LogMessageFatal()
    @          0x7f7bcc1  starrocks::RuntimeProfile::add_counter()
    @          0x7f7c68e  starrocks::RuntimeProfile::copy_all_counters_from()
    @          0x6ab78dc  starrocks::pipeline::ScanOperator::_merge_chunk_source_profiles()
    @          0x6ab6032  starrocks::pipeline::ScanOperator::close()
    @          0x6afb2be  starrocks::pipeline::PipelineDriver::_mark_operator_closed()
    @          0x6af9601  starrocks::pipeline::PipelineDriver::_close_operators()
    @          0x6af97ec  starrocks::pipeline::PipelineDriver::finalize()
    @          0x6ae3d65  starrocks::pipeline::GlobalDriverExecutor::_finalize_driver()
    @          0x6ae4309  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x6ae3b19  _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE_clEv
    @          0x6ae6a74  _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x6ae66c0  _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @          0x6ae6390  _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x5f752ac  std::function<>::operator()()
    @          0x800228a  starrocks::FunctionRunnable::run()
    @          0x8000ca5  starrocks::ThreadPool::dispatch_thread()
    @          0x800d472  std::__invoke_impl<>()
    @          0x800cf19  std::__invoke<>()
    @          0x800c7b6  _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
```

### StarRocks version (Required)
- main

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4740

### Modify the statistical method of WaitTime

Update the statistical method of WaitTime, which can be considered as the time that the piepeline where the Exchange is located waits for the SinkBuffer, including two situations: 

* buffer is full, then pipeline will be moved to waitting queue
* pending finish, pipeline wait SinkBuffer to finish all remaining brpc calls

### BugFix

if all root pipeline drivers have finished, then state report process will be triggered, while some pipeline drivers are doing finishing jobs, such as invoke operators' close method. So the following two things may happen simultaneously

1. profile prune, which will remove some of the metrics (when pipeline_profile_level=0)
       `_unique_metrics->copy_all_counters_from(merged_profile);`
2. scan operator update metrics
       `unique_metrics->remove_counters(xxx)`

`RuntimeProfile::copy_all_counters_from` do not set the counter lock, during which `unique_metrics->remove_counters` may be executed, then some constraints are broken (if you add some counter to a specified parent counter, then the parent counter must be existed)

Solution is simple, make those two processes seiralized

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
Can't set status; build succeeded.

**Comment by liuyehcf** [comment]
run starrocks_clang-format

File: be/src/util/runtime_profile.cpp [hunk 1]
```diff
@@ -103,16 +103,17 @@ void RuntimeProfile::merge(RuntimeProfile* other) {
             dst_iter = _counter_map.find(src_iter->first);
 
             if (dst_iter == _counter_map.end()) {
-                _counter_map[src_iter->first] =
-                        _pool->add(new Counter(src_iter->second->type(), src_iter->second->value()));
+                _counter_map[src_iter->first] = std::make_pair(
+                        _pool->add(new Counter(src_iter->second.first->type(), src_iter->second.first->value())),
```
Comment (mofeiatwork) [inline be/src/util/runtime_profile.cpp:107]: When will it be released?

**Review by murphyatwork — APPROVED** [review]

File: be/src/util/runtime_profile.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/src/util/runtime_profile.cpp:107]: It's lifecycle is managed by `ObjectPool`, so when query finished, `ObjectPool` will be released, as well as all the objects in the pool

File: be/src/util/runtime_profile.h [hunk 2]
```diff
@@ -491,9 +492,9 @@ class RuntimeProfile {
     /// All counters in this profile must be of unit AveragedCounter.
     bool _is_averaged_profile;
 
-    // Map from counter names to counters.  The profile owns the memory for the
-    // counters.
-    typedef std::map<std::string, Counter*> CounterMap;
+    // Map from counter names to counters and parent counter names.
+    // The profile owns the memory for the counters.
+    typedef std::map<std::string, std::pair<Counter*, std::string>> CounterMap;
```
Comment (kangkaisen) [inline be/src/util/runtime_profile.h:497]: Why need this change?

Comment (liuyehcf) [reply be/src/util/runtime_profile.h:497]: For profile prune. `RuntimeProfile::remove_counters` will remove all the counters except the `saved_counter_names`, and we need find all it's parent counters of those `saved_counter_names`

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
