### PR TITLE
[Enhancement] Improve subfield partial load for complex type column

### LINKED ISSUE #17808: FE unknown error for common used map_from_arrays([],[])
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'
```
mysql> select  map_values(col_map), map_keys(col_map) from (select map_from_arrays([],[]) as col_map)A;
ERROR 1064 (HY000): Unknown error
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by Smith-Cruise**
Signed-off-by: Smith Cruise <chendingchao1@126.com>

## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17808

Improve complex type prune behavior, before this pr, we don't support prune complex types when SQL contains window function, now we support it and also improve the prune framework.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 174 / 181 (96.13%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[774]|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|10|11|90.91%|[72]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|101|106|95.28%|[39, 83, 174, 175, 190]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPath.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPathType.java|5|5|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 1]
```diff
@@ -0,0 +1,262 @@
...
+            accessGroups.get(columnRefOperator).add(accessPaths);
+        }
+
+        // Merge upper PhysicalNode's Context
+        public void addUpperContext(Context upperContext) {
+            setEnablePruneComplexTypes(upperContext.getEnablePruneComplexTypes());
+            if (!enablePruneComplexTypes) {
+                return;
+            }
+            Map<ColumnRefOperator, List<ImmutableList<ComplexTypeAccessPath>>> upperGroups = upperContext.getAccessGroups();
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:85]: getContext alread merge the AccessGroup, why do it again?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 2]
```diff
@@ -0,0 +1,262 @@
...
+        }
+
+        public void addAccessPaths(ColumnRefOperator columnRefOperator,
+                                   ImmutableList<ComplexTypeAccessPath> accessPaths) {
+            accessGroups.putIfAbsent(columnRefOperator, new ArrayList<>());
+            accessGroups.get(columnRefOperator).add(accessPaths);
+        }
+
+        // Merge upper PhysicalNode's Context
+        public void addUpperContext(Context upperContext) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:80]: Upper is weied, how about mergeContext, and this function is uesd to generate a new context from curContext

**Comment by Youngwb** [comment]
Add som comment to describe the what case this PR can improve

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java (hunk 1 above)
Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java]: This function only used by globalContext, used to merge all operator's context into a globalContext. So that we can prune ColumnRefOperator by global unique id.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 175 / 182 (96.15%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[782]|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|11|12|91.67%|[72]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|101|106|95.28%|[39, 84, 175, 176, 191]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPath.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPathType.java|5|5|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 3]
```diff
@@ -0,0 +1,263 @@
...
+    // --- Access path 2: ComplexTypeAccessPath(STRUCT_SUBFIELD, "b")
+    // --- Access path 3: ComplexTypeAccessPath(STRUCT_SUBFIELD, "d")
+    // So it's access paths is: [Access path 1, Access path 2, Access path 3]
+    // map_keys(col) has one access paths:
+    // --- Access path 4: ComplexTypeAccessPath(MAP_KEYS)
+    // So it's access paths is: [Access path 4]
+    // Summary: ColumnRefOperator(col) has two access paths, we use access group to represent it.
+    // ColumnRefOperator(col):
+    // --- Access group: [[Access path 1, Access path 2, Access path 3], [Access path 4]]
+    protected static class Context {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:54]: AccessGroupContext ？

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 4]
```diff
@@ -0,0 +1,263 @@
...
+            return accessGroups;
+        }
+    }
+
+    /**
+     * Get context for specific ScalarOperator
+     * If specific ScalarOperator has upper access group, we should merge it.
+     */
+    public static Context getContext(ScalarOperator scalarOperator,
+                                     List<ImmutableList<ComplexTypeAccessPath>> upperAccessGroup) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:108]: visitedAccessGroup

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java (hunk 2 above)
Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java]: rewrite it already.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java (hunk 4 above)
Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java]: fixed

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 5]
```diff
@@ -0,0 +1,253 @@
...
+            int size = visitedAccessGroup.size();
+            // We should we below loop to avoid ConcurrentModificationException
+            for (int i = 0; i < size; i++) {
+                addAccessPaths(columnRefOperator, concatAccessPaths(visitedAccessGroup.get(i), curAccessPaths));
+            }
+        }
+
+        public void add(ColumnRefOperator outputColumnRefOperator, ScalarOperator scalarOperator) {
+            List<ImmutableList<ComplexTypeAccessPath>> visitedAccessGroup = null;
+            if (outputColumnRefOperator != null) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:91]: when outputColumnRefOperator could be null?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 148 / 155 (95.48%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[785]|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|11|12|91.67%|[72]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|89|94|94.68%|[39, 114, 115, 166, 172]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|27|27|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPath.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPathType.java|5|5|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 6]
```diff
@@ -0,0 +1,253 @@
...
+            accessGroups.get(columnRefOperator).add(accessPaths);
+        }
+
+        public void addAccessPaths(ColumnRefOperator columnRefOperator,
+                                   ImmutableList<ComplexTypeAccessPath> curAccessPaths,
+                                   List<ImmutableList<ComplexTypeAccessPath>> visitedAccessGroup) {
+            int size = visitedAccessGroup.size();
+            // We should we below loop to avoid ConcurrentModificationException
+            for (int i = 0; i < size; i++) {
+                addAccessPaths(columnRefOperator, concatAccessPaths(visitedAccessGroup.get(i), curAccessPaths));
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:85]: Why add access path for each of the visitedAccessGroup

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java (hunk 5 above)
Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:91]: Like `Predicate` in `Operator`, it has no output columnRefOperator, it only has a `ScalarOperator` (Base class of `Predicate`).

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java [hunk 7]
```diff
@@ -0,0 +1,253 @@
...
+            return accessGroups.get(columnRefOperator);
+        }
+    }
+
+    private static ImmutableList<ComplexTypeAccessPath> concatAccessPaths(
+            ImmutableList<ComplexTypeAccessPath> visitedAccessPaths,
+            ImmutableList<ComplexTypeAccessPath> curAccessPaths) {
+        ImmutableList.Builder<ComplexTypeAccessPath> builder = new ImmutableList.Builder<>();
+        for (ComplexTypeAccessPath accessPath : visitedAccessPaths) {
+            builder.add(accessPath);
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java:111]: you can use addAll

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 161 / 166 (96.99%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[785]|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|11|12|91.67%|[72]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|88|91|96.70%|[40, 165, 171]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessGroup.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|27|27|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPath.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPathType.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPaths.java|7|7|100.00%|[]|

**Review by Youngwb — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java [hunk 8]
```diff
@@ -324,53 +150,32 @@ public Void visitPhysicalScan(OptExpression optExpression, Context context) {
...
-            List<ImmutableList<Integer>> listGroup = context.getPath(columnRefOperator);
-            if (listGroup == null) {
+        private static void pruneForColumnRefMap(Map<ColumnRefOperator, ScalarOperator> map,
+                                                 PruneComplexTypeUtil.Context context) {
+            for (Map.Entry<ColumnRefOperator, ScalarOperator> entry : map.entrySet()) {
+                if (entry.getKey().getType().isComplexType()) {
+                    if (!entry.getKey().getType().equals(entry.getValue().getType())) {
+                        context.setEnablePruneComplexTypes(false);
+                        LOGGER.warn("ColumnRefOperator and ScalarOperator should has the same type.");
+                        return;
```
Comment (zombee0) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java:160]: some node may have been pruned

Comment (Smith-Cruise) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java]: solved

**Review by zombee0 — APPROVED** [review]

**Comment by Smith-Cruise** [comment]
run starrocks_fe_unittest

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 168 / 172 (97.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|[788]|
|:large_blue_circle:|com/starrocks/catalog/MapType.java|11|12|91.67%|[72]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneComplexTypeUtil.java|99|101|98.02%|[41, 193]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessGroup.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/StructType.java|7|7|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/tree/PruneSubfieldsForComplexType.java|23|23|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPath.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPathType.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/ComplexTypeAccessPaths.java|7|7|100.00%|[]|

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Comment by Smith-Cruise** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by Youngwb** [comment]
run starrocks_admit_test

**Review by Youngwb — APPROVED** [review]
