### PR TITLE
[BugFix] Transform all exception for some operation in HdfsFsMgr into StarRocksException to prevent Exception leak for the caller

### LINKED ISSUE #59770: Automated Cluster Snapshot can not set off because of network failure
### Steps to reproduce the behavior (Required)
1. Turn on automated cluster snapshot
2. Turn off automated cluster snapshot if network has some problem.

### Expected behavior (Required)
Set off successfully

### Real behavior (Required)
Get exception and fail

### StarRocks version (Required)
3.4.2

### PR DESCRIPTION
**Pull request by srlch**
## Why I'm doing:
Some operation in HdfsFsMgr does not catch all kinds of exception which cause some non-StarRocksException will be throw for the caller. But the caller usually only catch StarRocksException and lead Exception leak

## What I'm doing:
Make sure all exception will be transformed into StarRocksException

Fixes #59770

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java [hunk 1]
```diff
@@ -1314,6 +1314,9 @@ public void deletePath(String path, Map<String, String> loadProperties) throws S
         } catch (IOException e) {
             LOG.error("errors while delete path " + path, e);
             throw new StarRocksException("delete path " + path + "error", e);
+        } catch (Exception e) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java:1314]: directly replace above `IOException` with `Exception`？

Comment (srlch) [reply fe/fe-core/src/main/java/com/starrocks/fs/hdfs/HdfsFsManager.java:1314]: Fixed

**Review by wyb — APPROVED** [review]

**Review by hongkunxu — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
