### PR TITLE
[BugFix] Fix bdb disk expand bug

### LINKED ISSUE #6634: [BUG] fe bdb disk expands and cannot recovery
### Steps to reproduce the behavior (Required)
Have not found

### Expected behavior (Required)
System runs normally

### Real behavior (Required)
After running for a while, the disk usage of bdb keeps rising.

### StarRocks version (Required)
 - after (include) 2.0.4, after (include) 2.1.5, 2.2.0

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6634

## Problem Summary(Required) ：

Finding the root cause and fixing the bug of disk expand take a long time, so we downgrade the bdb-je version first.
Add shutdown hook to avoid the bug of vlsn mismatch as much as possible.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 25 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|0|4|00.00%|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|21|00.00%|

**Comment by chaoyli** [comment]
Please obey the rule about issue and commit about the title

**Review by Astralidea — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java [hunk 1]
```diff
@@ -302,4 +307,38 @@ private static boolean createAndLockPidFile(String pidFilePath) {
 
         return false;
     }
+
+    // NOTE: To avoid dead lock
+    //      1. never call System.exit in shutdownHook
+    //      2. shutdownHook cannot have lock conflict with the function calling System.exit
+    private static void addShutdownHook() {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:314]: If someone finds FE is stuck in line 337 after being killed, he may kill FE once again. Better add a mechanism to avoid shutdown hook called multiple times, for example, add an independent lock to `flushVLSNMapping()` and set `replicatedEnvironment` null after flush.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:314]: shutdown hook can only be call once, this is guaranteed by jdk.

**Review by padmejin — APPROVED** [review]

**Review by wyb — APPROVED** [review]
