### PR TITLE
BugFix: fix the wrong checksum between different replicas

### LINKED ISSUE #3438: checksum is not consistent between three replicas
The checksum algorithm(crc32) reads data rowsets one by one. There are some problems.
1. If there are three replicas A, B, C. The compaction progress is not consistent.
     If A has three rowset, B has two rowsets, C has one rowset. The checksum will be different.
2. The chunk size between different replicas are not the same. A may set the chunk_size to be 4096, B is 2048, C is 1024.
    Crc32 disobey associativity. So the checksum is not consistent between replicas.

### PR DESCRIPTION
**Pull request by chaoyli**
## What type of PR is this：
- [x] bug
- [ ] feature
- [x] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3438 

## Problem Summary(Required) ：

    
StarRocks uses the CRC algorithm to get the checksums to check the consistency between replicas.
There are two problems. Firstly, the size of chunks between different replicas is not the same.
Secondly, the order of data is not the same because of the out-of-step compaction procedures.

To solve the problem, I change the checksum algorithm to XOR. The result will be stored as a 64-bit integer.
Since the data between replicas is not the same, the checksum will reflect this problem, and the error probability is 1/(2^64).
XOR also obeys the commutative law. I can calculate the checksum Rowset by Rowset. XOR will improve performance and reduce memory consumption. 
    
Using the lineorder table(TPC-H), I test it with 100 million rows and 20 rowsets.
The test indicates that the memory consumption reduced from 500MB to 140MB. And the time is reduced from 24s to 9s.
As the number of rowsets grows, the performance improvement effect will be more obvious.

### CODE REVIEW

**Review by DeepThinker666 — CHANGES_REQUESTED** [review]

File: be/src/storage/task/engine_checksum_task.cpp [hunk 1]
```diff
@@ -121,11 +120,14 @@ Status EngineChecksumTask::_compute_checksum() {
...
-            column->crc32_hash(hash_codes, 0, num_rows);
-            for (int i = 0; i < num_rows; ++i) {
-                checksum ^= hash_codes[i];
-            }
+        // The size of chunk between different replicas are not the same.
+        // So, calculate the checksum as a unit of row is necessary.
+        // TODO: MayBe there are better algorithms can calculate the checksum
+        //       instead of crc32.
+        for (int i = 0; i < num_rows; ++i) {
+            std::string row = chunk->debug_row(i);
```
Comment (meegoo) [inline be/src/storage/task/engine_checksum_task.cpp:128]: the performance is pretty low when use debug_row

File: be/src/storage/vectorized/tablet_reader.cpp [hunk 2]
```diff
@@ -133,7 +133,7 @@ Status TabletReader::_init_collector(const TabletReaderParams& params) {
 
     if (seg_iters.empty()) {
         _collect_iter = new_empty_iterator(_schema, params.chunk_size);
-    } else if (is_compaction(params.reader_type) && keys_type == DUP_KEYS) {
+    } else if ((is_compaction(params.reader_type) || is_checksum(params.reader_type)) && keys_type == DUP_KEYS) {
```
[the remark this answers is not in the document]
Comment (chaoyli) [reply be/src/storage/vectorized/tablet_reader.cpp:136]: Because the checksum should guarantee the merge-read.

File: be/src/storage/task/engine_checksum_task.cpp (hunk 1 above)
[the remark this answers is not in the document]
Comment (chaoyli) [reply be/src/storage/task/engine_checksum_task.cpp:128]: The memory will not exceed the chunk itself.

[the remark this answers is not in the document]
Comment (chaoyli) [reply be/src/storage/task/engine_checksum_task.cpp]: I change it to column by column

Comment (chaoyli) [reply be/src/storage/task/engine_checksum_task.cpp]: I change it column by column

File: be/src/column/array_column.cpp [hunk 3]
```diff
@@ -384,6 +384,13 @@ void ArrayColumn::crc32_hash(uint32_t* hash, uint32_t from, uint32_t to) const {
     }
 }
 
+int64_t ArrayColumn::xor_checksum() const {
+    // The XOR of ArrayColumn
+    // XOR the offsets column and elements column
+    int64_t xor_checksum = _offsets->xor_checksum();
```
Comment (trueeyu) [inline be/src/column/array_column.cpp:390]: offset record the position of items in chunk, if the chunk size is not consistency, the result is wrong.

Comment (chaoyli) [reply be/src/column/array_column.cpp:390]: Yes, this is an error. I change it to XOR the size of every array.

File: be/src/storage/task/engine_checksum_task.cpp [hunk 4]
```diff
@@ -122,10 +120,7 @@ Status EngineChecksumTask::_compute_checksum() {
 
         num_rows = chunk->num_rows();
         for (auto& column : chunk->columns()) {
-            column->crc32_hash(hash_codes, 0, num_rows);
```
Comment (trueeyu) [inline be/src/storage/task/engine_checksum_task.cpp:125]: The current algorithm cannot detect the problem of out-of-order rows

File: be/src/column/binary_column.cpp [hunk 5]
```diff
@@ -441,6 +441,49 @@ void BinaryColumn::crc32_hash(uint32_t* hashes, uint32_t from, uint32_t to) cons
...
+
+        while (num >= step) {
+            const __m256i left = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(src));
+            avx2_checksum = _mm256_xor_si256(left, avx2_checksum);
+            src += step;
+            num -= step;
+        }
+        int64_t* checksum_vec = reinterpret_cast<int64_t*>(&avx2_checksum);
+        size_t eight_byte_step = step / 8;
+        for (size_t i = 0; i < eight_byte_step; ++i) {
```
Comment (trueeyu) [inline be/src/column/binary_column.cpp:469]: size_t eight_bytes_step = sizeof(__m256i) / sizeof(int64_t); ?

File: be/src/column/decimalv3_column.cpp [hunk 6]
```diff
@@ -81,7 +81,49 @@ void DecimalV3Column<T>::crc32_hash(uint32_t* hash, uint32_t from, uint32_t to)
...
+        src += step;
+        num -= step;
+    }
+    T* checksum_vec = reinterpret_cast<T*>(&avx2_checksum);
+    for (size_t i = 0; i < step; ++i) {
+        if constexpr (std::is_same_v<T, int128_t>) {
+            xor_checksum ^= (checksum_vec[i] >> 64);
+            xor_checksum ^= (checksum_vec[i] & ULLONG_MAX);
+        } else {
+            xor_checksum ^= checksum_vec[i];
```
Comment (trueeyu) [inline be/src/column/decimalv3_column.cpp:109]: if T is int32_t, only xor the low value?

**Review by trueeyu — DISMISSED** [review]

**Review by trueeyu — DISMISSED** [review]

File: be/src/column/binary_column.cpp [hunk 7]
```diff
@@ -441,6 +441,49 @@ void BinaryColumn::crc32_hash(uint32_t* hashes, uint32_t from, uint32_t to) cons
...
+
+        while (num >= step) {
+            const __m256i left = _mm256_loadu_si256(reinterpret_cast<const __m256i*>(src));
+            avx2_checksum = _mm256_xor_si256(left, avx2_checksum);
+            src += step;
+            num -= step;
+        }
+        int64_t* checksum_vec = reinterpret_cast<int64_t*>(&avx2_checksum);
+        size_t eight_byte_step = sizeof(__m256i) / sizeof(int64_t);
+        for (size_t i = 0; i < eight_byte_step; ++i) {
```
Comment (DeepThinker666) [inline be/src/column/binary_column.cpp:469]:
```suggestion
        for (size_t j = 0; j < eight_byte_step; ++j) {
```

File: be/src/storage/task/engine_checksum_task.cpp [hunk 8]
```diff
@@ -102,10 +102,7 @@ Status EngineChecksumTask::_compute_checksum() {
         return st;
     }
 
-    uint32_t checksum = 0;
-    uint32_t num_rows = 0;
-    uint32_t hash_codes[config::vector_chunk_size];
-    memset(hash_codes, 0, sizeof(uint32_t) * config::vector_chunk_size);
+    int64_t checksum = 0;
```
Comment (DeepThinker666) [inline be/src/storage/task/engine_checksum_task.cpp:105]: where to judge the tablet is not unique and should be skipped?

Comment (DeepThinker666) [reply be/src/storage/task/engine_checksum_task.cpp:105]: In line 86, it seems that checksum is calculated by 0-v, not by each rowset

**Review by sduzh — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by DeepThinker666 — APPROVED** [review]
LGTM

**Comment by stdpain** [comment]
I'm not sure the implemnts for NullableColumn and BinaryColumn. please check it.
because if null_data[1] was 1, data_column[i] value may be random.
eg:
col1 = NullColumn(nulldata=[1,1,0,0], data=[0,0,2,3])
col2 = NullColumn(nulldata=[0,1,0,0], data=[1,0,4,5])

col3 = col1 + col2 was NullColumn(nulldata=[1,1,0,0], data=[1,0,6,8]).
col4 = NullColumn(nulldata=[1,1,0,0], data=[0,0,6,8]).

but checksum for col3 was not equals to col4

**Comment by stdpain** [comment]
BinaryColumn may has the same problem.
col1= BinaryColumn(offsets=[0,1,2,3],'aaa')
col2 = BinaryColumn(offsets=[1,2,3,4],'aaaa')

(but it seems we don't have such case)
