### PR TITLE
[BugFix] Fix colocate balancer not handling bad replica case

### LINKED ISSUE #12461: ColocateBalancer should also work when replia is set to bad state
### Steps to reproduce the behavior (Required)
1. create colocate table
2. admin set replica status bad
3. observe the behavior of colocate balancer

### Expected behavior (Required)
bad replica is repaired

### Real behavior (Required)
bad replica stay unchanged

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12461

## Problem Summary(Required) ：

If a replica is marked bad, we need to migrate it and all the other replicas corresponding to the same bucket
index in the colocate group to another backend, but the backend where the bad replica sits on may still be
available, so the backend set won't be changed by ColocateBalancer, so we need to learn this state and update
the backend set to replace the backend that has the bad replica. In order to be in consistent with the current
logic, we return COLOCATE_MISMATCH not REPLICA_MISSING in `getColocateHealthStatus()`.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 44 / 48 (91.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|42|46|91.30%|[761, 766, 805, 806]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|2|100.00%|[]|

**Comment by nshangyiming** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 1]
```diff
@@ -329,6 +332,12 @@ private void matchGroup() {
                                                     tablet.getId(),
                                                     st);
 
+                                            // If tablet has bad replica, `getColocateHealthStatus()` will also return
+                                            // COLOCATE_MISMATCH, we need to replace the backend which owns the bad
+                                            // replica.
+                                            adjustBackendSetIfReplicaBad(idx, tablet, st, groupId,
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:338]: I think that a bad replica causes all the tablet to be migrated is a bit rough. How about just remove the replica on that be and copy a new replica? like tablet FORCE_REDUNDANT state.

Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:338]: I think the current handling is ok because bad replica is relatively a rare case, this won't cause too much performance problem. And currently we only have COLOCATE_MISMATCH state to clone a replica for colocate tablet, if we don't change the backend set, new replica cannot be cloned based on the current scheduler logic. Of course we can add extra logic to handle this situation, but this will complicate the scheduler. Taken together, i prefer keeping this pr unchanged.

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run all

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 45 / 48 (93.75%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|43|46|93.48%|[766, 805, 806]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 47 / 51 (92.16%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|45|49|91.84%|[761, 766, 808, 809]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test
