### PR TITLE
[BugFix] Fix duplicate entries in be_logs; Add reset_delvec in script; Add BE id in error message when query failed

### LINKED ISSUE #51190: Search BE log returns repeated entries
### Steps to reproduce the behavior (Required)
```
mysql> select * from information_schema.be_logs where log regexp '.*task_worker.*' limit 10;
+-------+-------+-----------+------+---------------------------------------------------------------------------------------------------------------------------------+
| BE_ID | LEVEL | TIMESTAMP | TID  | LOG                                                                                                                             |
+-------+-------+-----------+------+---------------------------------------------------------------------------------------------------------------------------------+
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
| 10002 | I     |         0 |    0 | I20240920 11:00:45.994916 138165742470848 task_worker_pool.cpp:716] Report tablets successfully, report version: 17268011750000 |
+-------+-------+-----------+------+---------------------------------------------------------------------------------------------------------------------------------+
10 rows in set (0.04 sec)

```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
## Why I'm doing:

Their are duplicate entries when using be_logs with '.*' parttern.
There is no be ID in error message when query failed.

## What I'm doing:

Fix regex match bug in greplog;
Add BE id in error message;
Add a tool to fix corrupted metadata causing "no delete vector found" error;

Fixes #51190

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: be/src/common/greplog.cpp [hunk 1]
```diff
@@ -33,16 +33,17 @@ namespace starrocks {
 static std::vector<string> list_log_files_in_dir(const string& log_dir, char level) {
     std::vector<string> files;
     // if level in WARNING, ERROR, FATAL, use logging logs, else use info logs
-    const std::string pattern = string("WEF").find(level) == string::npos ? "be.INFO.log." : "be.WARNING.log.";
+    const std::string pattern = string("WEF").find(level) == string::npos ? ".INFO.log." : ".WARNING.log.";
```
Comment (kevincai) [inline be/src/common/greplog.cpp:36]: share define a global variable to indicate the current process is a compute node or backend node, and process the log in a more accurate way.

File: be/src/exec/pipeline/pipeline_driver_executor.cpp [hunk 2]
```diff
@@ -167,6 +168,9 @@ void GlobalDriverExecutor::_worker_thread() {
             }
 
             if (!status.ok()) {
+                auto o_id = get_backend_id();
+                int64_t be_id = o_id.has_value() ? o_id.value() : 0;
```
Comment (kevincai) [inline be/src/exec/pipeline/pipeline_driver_executor.cpp:172]: maybe `-1` for invalid/unknown be id?

File: be/src/http/action/greplog_action.cpp [hunk 3]
```diff
@@ -66,7 +66,7 @@ void GrepLogAction::handle(HttpRequest* req) {
         return;
     }
 
-    auto ret = grep_log_as_string(start_ts, end_ts, std::toupper(level[0]), pattern, limit);
+    auto ret = grep_log_as_string(start_ts, end_ts, level, pattern, limit);
```
Comment (kevincai) [inline be/src/http/action/greplog_action.cpp:69]: before the change, suppose level can be lower case, the function is still correct because of toupper. After this change, is it still true? I didn't see the case conversion or case-insensitive search.

File: be/src/exec/pipeline/pipeline_driver_executor.cpp (hunk 2 above)
Comment (decster) [reply be/src/exec/pipeline/pipeline_driver_executor.cpp]: done

File: be/src/common/greplog.cpp (hunk 1 above)
Comment (decster) [reply be/src/common/greplog.cpp]: done

File: be/src/http/action/greplog_action.cpp (hunk 3 above)
Comment (decster) [reply be/src/http/action/greplog_action.cpp:69]: done

**Review by kevincai — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]
