### PR TITLE
[BugFix] Fix get hdfs filestatus error when path has illegal character

### LINKED ISSUE #15671: get hive partition meta data failed: Illegal character in path
### Steps to reproduce the behavior (Required)
1. hive table
create table hdfs_par(id int,name string) partitioned by(dt string) stored as orc;
2. insert into hive table
insert into hdfs_par partition(dt=' 2020-19-30') values(1,'aa');
3. sr
create external catalog hive_catalog  properties("type"="hive","hive.metastore.uris"="thrift://xxx:9083");
4.select 
 select * from hive_catalog.test.hdfs_par;
### Expected behavior (Required)
return correct result 
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
MySQL [(none)]> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 2.3.3 164799c     |
+-------------------+

### PR DESCRIPTION
**Pull request by leoyy0316**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15671

## Problem Summary(Required) ：

when hdfs path has empty space, can not get hdfs filesystem, we need to solve it

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java [hunk 1]
```diff
@@ -668,7 +668,7 @@ public TextFileFormatDesc getTextFileFormatDesc(StorageDescriptor sd) {
 
     public List<HdfsFileDesc> getHdfsFileDescs(String dirPath, boolean isSplittable,
                                                StorageDescriptor sd) throws Exception {
-        URI uri = new URI(dirPath);
+        URI uri = new Path(dirPath).toUri();
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:671]: I think you'd better find the core part of URI source code

Comment (leoyy0316) [reply fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:671]: @stephen-shelby 【new Path(dirPath)】will replace space character  with "%20" 
detail function at: java.net.URI#appendEscape

**Review by stephen-shelby — APPROVED** [review]

**Comment by leoyy0316** [comment]
run starrocks_tscancode
