### PR TITLE
[BugFix] fix missing rows when doing broker load

### LINKED ISSUE #47455: Rows are missing when broker load files in json
Described in this forum: https://forum.mirrorship.cn/t/topic/13206

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by dirtysalt**
## Why I'm doing:

Rows are missing when ingesting from broker load

## What I'm doing:

Scanner is supposed to read multiple files, but it exits when rows % chunk_size = 0, and leave some unread files.

Fixes #47455 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

**Review by meegoo — APPROVED** [review]

File: be/src/exec/json_scanner.cpp [hunk 1]
```diff
@@ -105,7 +105,9 @@ StatusOr<ChunkPtr> JsonScanner::get_next() {
 
     if (src_chunk->num_rows() == 0) {
         if (status.is_end_of_file()) {
-            return Status::EndOfFile("EOF of reading json file, nothing read");
+            // NOTE: can not stop right here because could be more files to read.
+            // return Status::EndOfFile("EOF of reading json file, nothing read");
```
Comment (wyb) [inline be/src/exec/json_scanner.cpp:109]: remove line 109?

Comment (dirtysalt) [reply be/src/exec/json_scanner.cpp:109]: I want to keep this line here for comment.  let more people know here could be a big mistake.

**Review by wyb — APPROVED** [review]
