### PR TITLE
[BugFix] Fix BE decommission failed after drop database force

### LINKED ISSUE #10918: [BUG] BE decommission failed after drop database force
### Steps to reproduce the behavior (Required)
1. create database test;
2. create table t1...
3. drop table t1;
4. drop database test force;

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #10918

## Problem Summary(Required) ：

If database is dropped force, the table or partition of that database in the recycle bin will never be reached by TabletChecker, so the tablets of those table or partition cannot be relocated.
To fix this bug, erase table if database has been dropped force, erase partition if table or database has been dropped force.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 1]
```diff
@@ -279,6 +279,38 @@ private synchronized boolean canErase(long id, long currentTimeMs) {
...
     }
 
+
+    private synchronized boolean canEraseTable(RecycleTableInfo tableInfo, long currentTimeMs) {
+        if (timeExpired(tableInfo.getTable().getId(), currentTimeMs)) {
+            return true;
+        }
+
+        // database is force dropped, the table can not be recovered, erase it.
+        if (GlobalStateMgr.getCurrentState().getDbIncludeRecycleBin(tableInfo.getDbId()) == null) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:289]: If the table is dropped forced, why does it exist in the recycle bin?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:289]: If database is dropped force, table that dropped before can exist in the recycle bin.

**Review by Astralidea — DISMISSED** [review]

**Comment by gengjun-git** [comment]
@mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 15 / 17 (88.24%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/CatalogRecycleBin.java|15|17|88.24%|[303, 308]|

**Review by Astralidea — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3
