### PR TITLE
[pipeline] fix: exchange sink should send EOS after all channels of a fragment are EOS

### LINKED ISSUE #1311: [pipeline] should send EOS after all channels of a fragment are EOS.
### Steps to reproduce the behavior (Required)
```sql
set enable_pipeline_engine=true;
set parallel_fragment_exec_instance_num=1;
set pipeline_dop=1;

CREATE TABLE `orders` (
  `O_ORDERKEY` int(11) NOT NULL COMMENT "",
  `O_CUSTKEY` int(11) NOT NULL COMMENT "",
  `O_ORDERSTATUS` char(1) NOT NULL COMMENT "",
  `O_TOTALPRICE` decimal64(15, 2) NOT NULL COMMENT "",
  `O_ORDERDATE` date NOT NULL COMMENT "",
  `O_ORDERPRIORITY` char(15) NOT NULL COMMENT "",
  `O_CLERK` char(15) NOT NULL COMMENT "",
  `O_SHIPPRIORITY` int(11) NOT NULL COMMENT "",
  `O_COMMENT` varchar(79) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`O_ORDERKEY`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`O_ORDERKEY`) BUCKETS 12
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

CREATE TABLE `lineitem` (
  `L_ORDERKEY` int(11) NOT NULL COMMENT "",
  `L_PARTKEY` int(11) NOT NULL COMMENT "",
  `L_SUPPKEY` int(11) NOT NULL COMMENT "",
  `L_LINENUMBER` int(11) NOT NULL COMMENT "",
  `L_QUANTITY` decimal64(15, 2) NOT NULL COMMENT "",
  `L_EXTENDEDPRICE` decimal64(15, 2) NOT NULL COMMENT "",
  `L_DISCOUNT` decimal64(15, 2) NOT NULL COMMENT "",
  `L_TAX` decimal64(15, 2) NOT NULL COMMENT "",
  `L_RETURNFLAG` char(1) NOT NULL COMMENT "",
  `L_LINESTATUS` char(1) NOT NULL COMMENT "",
  `L_SHIPDATE` date NOT NULL COMMENT "",
  `L_COMMITDATE` date NOT NULL COMMENT "",
  `L_RECEIPTDATE` date NOT NULL COMMENT "",
  `L_SHIPINSTRUCT` char(25) NOT NULL COMMENT "",
  `L_SHIPMODE` char(10) NOT NULL COMMENT "",
  `L_COMMENT` varchar(44) NOT NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`L_ORDERKEY`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`L_ORDERKEY`) BUCKETS 192
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

-- Insert som rows.
-- ....

select
    l_orderkey
from
    orders, lineitem
where
    l_orderkey = o_orderkey
group by
    l_orderkey;
```

### Expected behavior (Required)
The result is same as that of non-pipeline engine.

### Real behavior (Required)
The result is very unstable. Every execution of this query gets different result.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 004a0662  |
+-------------------+
```

### Reason
In the pipeline engine, we send EOS to channel if all the sinkers of this channel are EOS.
However, as for the `BUCKET_SHFFULE_HASH_PARTITIONED`, multiple channels is related to **one** Exchange Source Fragment Instance. Therefore, it will cause the Exchange Source receives EOS earlier than expected.

```C++
void _send_rpc(TransmitChunkInfo& request) {
        if (request.params->eos()) {
            // Only the last eos is sent to ExchangeSourceOperator. it must be guaranteed that
            // eos is the last packet to send to finish the input stream of the corresponding of
            // ExchangeSourceOperator and eos is sent exactly-once.
            if (--_num_sinkers_per_channel[request.channel_id] > 0) { {
                if (request.params->chunks_size() == 0) {
                    return;
                } else {
                    request.params->set_eos(false);
                }
            }
        }
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
In the pipeline engine, we send EOS to channel if all the sinkers of this channel are EOS.
However, as for the `BUCKET_SHFFULE_HASH_PARTITIONED`, multiple channels is related to **one** Exchange Source Fragment Instance, which causes the Exchange Source receives EOS earlier than expected.
Therefore, we should use `fragment_instance_id` of the destination as the key of destination instead of `channel_id`.

Fix #1311

### CODE REVIEW

**Review by liuyehcf — DISMISSED** [review]

File: be/src/exec/pipeline/exchange/sink_buffer.h [hunk 1]
```diff
@@ -18,35 +18,47 @@ namespace starrocks::pipeline {
 using PTransmitChunkParamsPtr = std::shared_ptr<PTransmitChunkParams>;
 
 struct TransmitChunkInfo {
-    size_t channel_id;
+    TUniqueId fragment_instance_id;
```
Comment (kangkaisen) [inline be/src/exec/pipeline/exchange/sink_buffer.h:21]: Comment here why use fragment_instance_id not channel_id

**Review by kangkaisen — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]
