### PR TITLE
[BugFix] Fix multi edge order bug by refactor version_graph using vertex directly instead of vertex index

### LINKED ISSUE #5560: Version already been compacted.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create database starrocks_analyze_test_e2026018_c599_11ec_8e0d_00163e0e489a;
use starrocks_analyze_test_e2026018_c599_11ec_8e0d_00163e0e489a;
 CREATE TABLE `duplicate_table_with_null` ( `k1`  date, `k2`  datetime, `k3`  char(20), `k4`  varchar(20), `k5`  boolean, `k6`  tinyint, `k7`  smallint, `k8`  int, `k9`  bigint, `k10` largeint, `k11` float, `k12` double, `k13` decimal(27,9) ) ENGINE=OLAP DUPLICATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`) BUCKETS 3 PROPERTIES ( "replication_num" = "1", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
insert into starrocks_analyze_test_e2026018_c599_11ec_8e0d_00163e0e489a.duplicate_table_with_null values ('2020-06-25', '2020-06-25 00:16:23', 'beijing', 'haidian', 0, 87, -31785, -2147482665, -9223372036854774825, -18446744073709550633, 25.2, 2.69, -2.18);
```
3. SELECT  '....'
```
select count(*) from starrocks_analyze_test_e2026018_c599_11ec_8e0d_00163e0e489a.duplicate_table_with_null ;
analyze full table duplicate_table_with_null;
select count(*) from _statistics_.table_statistic_v1 where table_name like 'starrocks_analyze_test_e2026018_c599_11ec_8e0d_00163e0e489a.duplicate_table_with_null';
```
### Expected behavior (Required)
```
+----------+
| count(*) |
+----------+
|       13 |
+----------+
1 row in set (0.03 sec)
```
### Real behavior (Required)
ERROR 1064 (HY000): version already been compacted. tablet_id: 159687885, version: 5969
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - MAIN-RELEASE 34fcc18

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5560

## Problem Summary(Required) ：

The previous implementation used _version_graph, _version_index_map as two structures to implement the adjacency graph. Vertex edge was index of vertex, not vertex. use set sort will make mistake.
It is not necessary to use the two structures to implement the adjacency graph in this case, The benefits of compact memory are not comparable to the cost of sorting through vertex index each time.

### CODE REVIEW

File: be/src/storage/version_graph.cpp [hunk 1]
```diff
@@ -239,66 +232,60 @@ void VersionGraph::construct_version_graph(const std::vector<RowsetMetaSharedPtr
...
+    auto end_edges_iter = end_iter->second->edges.find(start_vertex_value);
+    if (end_edges_iter != end_iter->second->edges.end()) {
+        end_iter->second->edges.erase(end_edges_iter);
     }
 
     return Status::OK();
 }
 
-int64_t VersionGraph::_add_vertex_to_graph(int64_t vertex_value) {
+std::shared_ptr<Vertex>& VersionGraph::_add_vertex_to_graph(int64_t vertex_value) {
```
Comment (imay) [inline be/src/storage/version_graph.cpp:278]: Is this version graph protected by lock? If so, I think std::unique_ptr is enough.
We should only use std::shared_ptr when they are shared by multi-threads. Otherwise I think we should use std::unique_ptr first.

Because std::shared_ptr will introduce atomic operation, and take more memory than std::unique_ptr

Comment (meegoo) [reply be/src/storage/version_graph.cpp:278]: use reference of shared_ptr will estimate the atomic operation?

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
