### PR TITLE
[Enhancement] Optimizing partition statistics lock competition.

### LINKED ISSUE #61042: Partition statistics hold locks for long periods of time.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhangheihei**
## Why I'm doing:
Partition statistics uses synchronized access to Caffeine, resulting in holding DB locks for long periods of time.
## What I'm doing:

Fixes #61042
Modifying partition statistics to use asynchronous access to Caffeine.
## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java [hunk 1]
```diff
@@ -401,27 +403,33 @@ public List<ColumnStatistic> getColumnStatistics(Table table, List<String> colum
...
+            if (resultFuture.isDone()) {
+                Map<ColumnStatsCacheKey, Optional<PartitionStats>> result = resultFuture.get();
+                return columns.stream()
+                        .collect(Collectors.toMap(
+                                column -> column,
+                                column -> result.getOrDefault(new ColumnStatsCacheKey(table.getId(), column), Optional.empty())
+                                        .orElse(null)
+                        ));
+            } else {
+                return Collections.emptyMap();
```
Comment (murphyatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java]: in this way, the first access to the cache would always be empty ? that would make the query behavior unstable

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java]: Use the synchronized get interface, add a timeout of 5 seconds, or a timeout of new_planner_optimize_timeout？

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java [hunk 2]
```diff
@@ -401,27 +405,34 @@ public List<ColumnStatistic> getColumnStatistics(Table table, List<String> colum
...
-            Map<String, PartitionStats> columnStatistics = Maps.newHashMap();
-            for (String column : columns) {
-                Optional<PartitionStats> columnStatistic = result.get(new ColumnStatsCacheKey(tableId, column));
-                columnStatistics.put(column, columnStatistic.orElse(null));
-            }
-            return columnStatistics;
+            CompletableFuture<Map<ColumnStatsCacheKey, Optional<PartitionStats>>> resultFuture =
+                    partitionStatistics.getAll(cacheKeys);
+
+            Map<ColumnStatsCacheKey, Optional<PartitionStats>> result = resultFuture.get(5, TimeUnit.SECONDS);
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/statistics/CachedStatisticStorage.java:418]: I think there is no need to wait 5 secs here. just follow other interface behavior like `getColumnStatistics`

**Comment by wangsimo0** [comment]
ignore backport check: 3.3.17
