### PR TITLE
[pipeline] fix: ExchangeSinkOperator should consider RANDOM partition type

### LINKED ISSUE #1148: [pipeline] ExchangeSinkOperator should consider RANDOM partition type
### Steps to reproduce the behavior (Required)

```sql

set enable_pipeline_engine=true;

CREATE TABLE if not exists t0
(
  dt DATETIME NOT NULL,
  id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  price DECIMAL64(7, 2) NOT NULL,
  tax DECIMAL64(7, 2) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`dt`, `id`, `name`)
COMMENT "OLAP"
PARTITION BY RANGE(`dt`) (
  START ("2021-01-01") END ("2021-02-01") EVERY (INTERVAL 1 day) 
)
DISTRIBUTED BY HASH(`id`, `name`) BUCKETS 10
PROPERTIES(
  "replication_num" = "1",
  "in_memory" = "false",
  "storage_format" = "DEFAULT"
);

SELECT id, quantity, id + 2, quantity + 2, name
FROM t0 
WHERE t0.dt BETWEEN "2022-01-20" AND "2022-01-21" 
UNION ALL 
SELECT id, quantity, id + 2, id + 3, name 
FROM t0 WHERE t0.dt BETWEEN "2021-01-26" AND "2021-01-27" AND price BETWEEN 111.00 AND 112.00

```

### Expected behavior (Required)
Output data.

### Real behavior (Required)
There is no Backend.

### StarRocks version (Required)
 Commit `0f3ff8a` on the main branch.

### Reason

The partition type of exchange sink is RANDOM for fragment 2 and 3, but `ExchangeSinkOperator` didn't consider this partition type.

```C++
OperatorPtr ExchangeSinkOperatorFactory::create(int32_t degree_of_parallelism, int32_t driver_sequence) {
    if (_part_type == TPartitionType::UNPARTITIONED || _destinations.size() == 1) {
        return std::make_shared<ExchangeSinkOperator>(_id, _plan_node_id, _buffer, _part_type, _destinations,
                                                      _sender_id, _dest_node_id, _partition_expr_ctxs);
    } else if (_part_type == TPartitionType::HASH_PARTITIONED ||
               _part_type == TPartitionType::BUCKET_SHFFULE_HASH_PARTITIONED) {
        return std::make_shared<ExchangeSinkOperator>(_id, _plan_node_id, _buffer, _part_type, _destinations,
                                                      _sender_id, _dest_node_id, _partition_expr_ctxs);
    } else {
        // If _part_type is RANDOM, crash here.
        DCHECK(false) << " Shouldn't reach here!";
        return nullptr;
    }
}
```

```
+--------------------------------------------------------------------------------------+
| Explain String                                                                       |
+--------------------------------------------------------------------------------------+
| WORK ON CBO OPTIMIZER                                                                |
| PLAN FRAGMENT 0                                                                      |
|  OUTPUT EXPRS:9: id | 10: quantity | 11: expr | 12: expr | 13: name                  |
|   PARTITION: UNPARTITIONED                                                           |
|                                                                                      |
|   RESULT SINK                                                                        |
|                                                                                      |
|   7:EXCHANGE                                                                         |
|      use vectorized: true                                                            |
|                                                                                      |
| PLAN FRAGMENT 1                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: RANDOM                                                                  |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 07                                                                  |
|     UNPARTITIONED                                                                    |
|                                                                                      |
|   0:UNION                                                                            |
|   |  use vectorized: true                                                            |
|   |                                                                                  |
|   |----6:EXCHANGE                                                                    |
|   |       use vectorized: true                                                       |
|   |                                                                                  |
|   3:EXCHANGE                                                                         |
|      use vectorized: true                                                            |
|                                                                                      |
| PLAN FRAGMENT 2                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: RANDOM                                                                  |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 06                                                                  |
|     RANDOM                                                                           |
|                                                                                      |
|   5:Project                                                                          |
|   |  <slot 15> : 15: id                                                              |
|   |  <slot 16> : 16: name                                                            |
|   |  <slot 17> : 17: quantity                                                        |
|   |  <slot 20> : 22: cast + 2                                                        |
|   |  <slot 21> : 22: cast + 3                                                        |
|   |  common expressions:                                                             |
|   |  <slot 22> : CAST(15: id AS BIGINT)                                              |
|   |  use vectorized: true                                                            |
|   |                                                                                  |
|   4:OlapScanNode                                                                     |
|      TABLE: t1                                                                       |
|      PREAGGREGATION: ON                                                              |
|      PREDICATES: 14: dt <= '2021-01-27 00:00:00', 18: price >= 111, 18: price <= 112 |
|      partitions=2/31                                                                 |
|      rollup: t1                                                                      |
|      tabletRatio=20/20                                                               |
|      tabletList=16847,16849,16851,16853,16855,16857,16859,16861,16863,16865 ...      |
|      cardinality=500086                                                              |
|      avgRowSize=7.0                                                                  |
|      numNodes=0                                                                      |
|      use vectorized: true                                                            |
|                                                                                      |
| PLAN FRAGMENT 3                                                                      |
|  OUTPUT EXPRS:                                                                       |
|   PARTITION: RANDOM                                                                  |
|                                                                                      |
|   STREAM DATA SINK                                                                   |
|     EXCHANGE ID: 03                                                                  |
|     RANDOM                                                                           |
|                                                                                      |
|   2:Project                                                                          |
|   |  <slot 2> : 2: id                                                                |
|   |  <slot 3> : 3: name                                                              |
|   |  <slot 4> : 4: quantity                                                          |
|   |  <slot 7> : CAST(2: id AS BIGINT) + 2                                            |
|   |  <slot 8> : CAST(4: quantity AS BIGINT) + 2                                      |
|   |  use vectorized: true                                                            |
|   |                                                                                  |
|   1:OlapScanNode                                                                     |
|      TABLE: t1                                                                       |
|      PREAGGREGATION: ON                                                              |
|      PREDICATES: 1: dt >= '2022-01-20 00:00:00', 1: dt <= '2022-01-21 00:00:00'      |
|      partitions=0/31                                                                 |
|      rollup: t1                                                                      |
|      tabletRatio=0/0                                                                 |
|      tabletList=                                                                     |
|      cardinality=0                                                                   |
|      avgRowSize=6.0                                                                  |
|      numNodes=0                                                                      |
|      use vectorized: true                                                            |
+--------------------------------------------------------------------------------------+
86 rows in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by ZiheLiu**
close #1148.

### CODE REVIEW

File: be/src/exec/pipeline/exchange/exchange_sink_operator.cpp [hunk 1]
```diff
@@ -495,17 +519,11 @@ ExchangeSinkOperatorFactory::ExchangeSinkOperatorFactory(int32_t id, int32_t pla
...
-                                                      _sender_id, _dest_node_id, _partition_expr_ctxs);
-    } else if (_part_type == TPartitionType::HASH_PARTITIONED ||
-               _part_type == TPartitionType::BUCKET_SHFFULE_HASH_PARTITIONED) {
-        return std::make_shared<ExchangeSinkOperator>(_id, _plan_node_id, _buffer, _part_type, _destinations,
-                                                      _sender_id, _dest_node_id, _partition_expr_ctxs);
-    } else {
-        DCHECK(false) << " Shouldn't reach here!";
-        return nullptr;
-    }
+    DCHECK(_part_type == TPartitionType::UNPARTITIONED || _destinations.size() == 1 ||
```
Comment (kangkaisen) [inline be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:522]: Could remove this DCHECK, There is no meaning. Before there is  no random partition type in BE, currently, BE could have all partition types

Comment (ZiheLiu) [reply be/src/exec/pipeline/exchange/exchange_sink_operator.cpp:522]: @kangkaisen There is an `RANGE_PARTITIONED` partition type we doesn't consider. Is `RANGE_PARTITIONED` deprecated?

**Review by satanson — DISMISSED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
