### PR TITLE
skip filtering unused column if outputColumns of ScanOperator is empty

### LINKED ISSUE #5176: BE crash in ASAN mode
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `tpcds_100g_web_returns` (
  `wr_item_sk` int(11) NOT NULL COMMENT "",
  `wr_order_number` int(11) NOT NULL COMMENT "",
  `wr_returned_date_sk` int(11) NULL COMMENT "",
  `wr_returned_time_sk` int(11) NULL COMMENT "",
  `wr_refunded_customer_sk` int(11) NULL COMMENT "",
  `wr_refunded_cdemo_sk` int(11) NULL COMMENT "",
  `wr_refunded_hdemo_sk` int(11) NULL COMMENT "",
  `wr_refunded_addr_sk` int(11) NULL COMMENT "",
  `wr_returning_customer_sk` int(11) NULL COMMENT "",
  `wr_returning_cdemo_sk` int(11) NULL COMMENT "",
  `wr_returning_hdemo_sk` int(11) NULL COMMENT "",
  `wr_returning_addr_sk` int(11) NULL COMMENT "",
  `wr_web_page_sk` int(11) NULL COMMENT "",
  `wr_reason_sk` int(11) NULL COMMENT "",
  `wr_return_quantity` int(11) NULL COMMENT "",
  `wr_return_amt` decimal64(7, 2) NULL COMMENT "",
  `wr_return_tax` decimal64(7, 2) NULL COMMENT "",
  `wr_return_amt_inc_tax` decimal64(7, 2) NULL COMMENT "",
  `wr_fee` decimal64(7, 2) NULL COMMENT "",
  `wr_return_ship_cost` decimal64(7, 2) NULL COMMENT "",
  `wr_refunded_cash` decimal64(7, 2) NULL COMMENT "",
  `wr_reversed_charge` decimal64(7, 2) NULL COMMENT "",
  `wr_account_credit` decimal64(7, 2) NULL COMMENT "",
  `wr_net_loss` decimal64(7, 2) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`wr_item_sk`, `wr_order_number`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`wr_item_sk`, `wr_order_number`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. select   * from   (     select       51 as c0     from       tpcds_100g_web_returns as ref_0     where       ref_0.wr_account_credit is NULL     limit       172   ) as subq_0 where   cast(coalesce(subq_0.c0, subq_0.c0) as INT) >= subq_0.c0;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
*** Check failure stack trace: ***
*** Check failure stack trace: ***
    @          0xa00eee4  google::LogMessage::Fail()
    @          0xa00eee4  google::LogMessage::Fail()
    @          0xa00ee43  google::LogMessage::SendToLog()
    @          0xa00ee43  google::LogMessage::SendToLog()
    @          0xa00e80c  google::LogMessage::Flush()
    @          0xa00e80c  google::LogMessage::Flush()
    @          0xa011ad8  google::LogMessageFatal::~LogMessageFatal()
    @          0xa011ad8  google::LogMessageFatal::~LogMessageFatal()
    @          0x48ec794  starrocks::vectorized::ChunkIterator::init_output_schema()
    @          0x48ec794  starrocks::vectorized::ChunkIterator::init_output_schema()
    @          0x74e886d  starrocks::pipeline::OlapChunkSource::_init_olap_reader()
    @          0x74e886d  starrocks::pipeline::OlapChunkSource::_init_olap_reader()
    @          0x74df705  starrocks::pipeline::OlapChunkSource::prepare()
    @          0x74df705  starrocks::pipeline::OlapChunkSource::prepare()
    @          0x6fe9f23  starrocks::pipeline::ScanOperator::_pickup_morsel()
    @          0x6fe9f23  starrocks::pipeline::ScanOperator::_pickup_morsel()
    @          0x6fe8246  starrocks::pipeline::ScanOperator::_try_to_trigger_next_scan()
    @          0x6fe8246  starrocks::pipeline::ScanOperator::_try_to_trigger_next_scan()
    @          0x6fe77b1  starrocks::pipeline::ScanOperator::pull_chunk()
    @          0x6fe77b1  starrocks::pipeline::ScanOperator::pull_chunk()
    @          0x704d955  starrocks::pipeline::PipelineDriver::process()
    @          0x704d955  starrocks::pipeline::PipelineDriver::process()
    @          0x7026132  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x702540c  _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE_clEv
    @          0x7026132  starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x702b9d6  _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x702540c  _ZZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiENKUlvE_clEv
    @          0x702b4a4  _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @          0x702b9d6  _ZSt13__invoke_implIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEET_St14__invoke_otherOT0_DpOT1_
    @          0x702aefe  _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x702b4a4  _ZSt10__invoke_rIvRZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_JEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EES6_E4typeEOS7_DpOS8_
    @          0x702aefe  _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline20GlobalDriverExecutor10initializeEiEUlvE_E9_M_invokeERKSt9_Any_data
    @          0x43a42c2  std::function<>::operator()()
    @          0x43a42c2  std::function<>::operator()()
    @          0x59c4c22  starrocks::FunctionRunnable::run()
    @          0x59c4c22  starrocks::FunctionRunnable::run()
    @          0x59c1756  starrocks::ThreadPool::dispatch_thread()
    @          0x59c1756  starrocks::ThreadPool::dispatch_thread()
    @          0x59ded4a  std::__invoke_impl<>()
    @          0x59ded4a  std::__invoke_impl<>()
    @          0x59de62d  std::__invoke<>()
    @          0x59de62d  std::__invoke<>()
    @          0x59dda44  _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x59dda44  _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @          0x59dc5b0  std::_Bind<>::operator()<>()
    @          0x59dc5b0  std::_Bind<>::operator()<>()
    @          0x59d9496  std::__invoke_impl<>()
    @          0x59d9496  std::__invoke_impl<>()
    @          0x59d745e  _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0x59d745e  _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
    @          0x59d2bf9  std::_Function_handler<>::_M_invoke()
    @          0x59d2bf9  std::_Function_handler<>::_M_invoke()
    @          0x43a42c2  std::function<>::operator()()
    @          0x43a42c2  std::function<>::operator()()
    @          0x59abcd9  starrocks::Thread::supervise_thread()
    @     0x7fe2927fae65  start_thread
    @     0x7fe291e1588d  __clone
    @          0x59abcd9  starrocks::Thread::supervise_thread()
    @              (nil)  (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
branch-2.2 ASAN 2f51014

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5176

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|1|2|50.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java [hunk 1]
```diff
@@ -270,6 +270,10 @@ private void setUnUsedOutputColumns(PhysicalOlapScanOperator node, OlapScanNode
                                             List<ScalarOperator> predicates, OlapTable referenceTable) {
             if (ConnectContext.get().getSessionVariable().isAbleFilterUnusedColumnsInScanStage()) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/plan/PlanFragmentBuilder.java:271]:
```
if (!ConnectContext.get().getSessionVariable().isAbleFilterUnusedColumnsInScanStage()) {
    return;
}
```
I think this will make code easier to read.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 33 / 34 (97.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/plan/PlanFragmentBuilder.java|33|34|97.06%|

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by silverbullet233** [comment]
@Mergifyio backport branch-2.2
