### PR TITLE
[BugFix] Fix the overflow when calculating the max_rows_per_segment

### LINKED ISSUE #5610: overflow occurs when calculating the max_rows_per_segment #5609
When the input_rows of compaction is larger, the multiplication between config::max_segments_file_size and input_row_num will overflow. Because of the overflow, the segment will be limited to one row. The file descriptors will be reached because of the so small segments.

```
I0428 00:12:07.176318 11782 compaction.cpp:86] start base compaction. tablet=940828, output version is=0-138715, max rows per segment=1, segment iterator num=100, algo
rithm=VERTICAL_COMPACTION, column group size=23, columns per group=5
W0428 00:12:35.023933 11782 compaction.cpp:106] fail to do base compaction. res=IO error: /home/disk8/starrocks/storage/be-c6e29739-05e6-4286-b850-33c5d97c8f8a/data/54
/940828/1092789729/0200000000000701e04e325abb82380c536e56bffe78afae_65040.dat: Too many open files
```

### PR DESCRIPTION
**Pull request by chaoyli**
When the input_rows is larger, the overflow occurs when calculating the output rows of every segment.
Because of the overflow, the row in every segment will be one. It will generate thousands of files and reach the limit of the file descriptors.
```
I0428 00:12:07.176318 11782 compaction.cpp:86] start base compaction. tablet=940828, output version is=0-138715, max rows per segment=1, segment iterator num=100, algo
rithm=VERTICAL_COMPACTION, column group size=23, columns per group=5
W0428 00:12:35.023933 11782 compaction.cpp:106] fail to do base compaction. res=IO error: /home/disk8/starrocks/storage/be-c6e29739-05e6-4286-b850-33c5d97c8f8a/data/54
/940828/1092789729/0200000000000701e04e325abb82380c536e56bffe78afae_65040.dat: Too many open files
```
As well, config::max_segments_file_size is redesigned as a integer. This is the max size of a segment is 2GB and enough for all the cases.

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5610

### CODE REVIEW

File: be/src/storage/compaction_utils.cpp [hunk 1]
```diff
@@ -68,15 +68,12 @@ Status CompactionUtils::construct_output_rowset_writer(Tablet* tablet, uint32_t
...
                                                int64_t input_size) {
-    // max segment rows
-    int64_t max_segment_rows = max_segment_file_size * input_row_num / (input_size + 1);
-    // default value in RowsetWriterContext is INT32_MAX.
-    // segment file use uint32 to represent row number,
-    // and use INT32_MAX to avoid overflow issue when casting from uint32_t to int.
+    // The max of config::max_segments_file_size is INT_MAX
+    // The max of input_row_num is UINT32_MAX
+    // Using division before multiplication can avoid the overflow
+    int64_t max_segment_rows = max_segment_file_size * (input_row_num / input_size + 1);
```
Comment (imay) [inline be/src/storage/compaction_utils.cpp:74]: Why not use double to compute this number?
```suggestion
    int64_t max_segment_rows = 1.0 * max_segment_file_size * input_row_num / (input_size + 1);
```

Comment (ABingHuang) [inline be/src/storage/compaction_utils.cpp:74]: what if input_row_num == 1, and input_size == max_segment_file_size, the max_segment_rows will be 0?
And more, better to add ut for this boundary.

**Review by ABingHuang — CHANGES_REQUESTED** [review]

File: be/src/storage/compaction_utils.cpp [hunk 2]
```diff
@@ -68,15 +68,12 @@ Status CompactionUtils::construct_output_rowset_writer(Tablet* tablet, uint32_t
...
-    // max segment rows
-    int64_t max_segment_rows = max_segment_file_size * input_row_num / (input_size + 1);
-    // default value in RowsetWriterContext is INT32_MAX.
-    // segment file use uint32 to represent row number,
-    // and use INT32_MAX to avoid overflow issue when casting from uint32_t to int.
-    if (max_segment_rows > INT32_MAX) {
+    // The range of config::max_segments_file_size is between [1, INT64_MAX]
+    // If the configuration is set wrong, the config::max_segments_file_size will be a negtive value.
+    // Using division instead multiplication can avoid the overflow
+    int64_t max_segment_rows = max_segment_file_size / (input_size / (input_row_num + 1) + 1);
```
Comment (trueeyu) [inline be/src/storage/compaction_utils.cpp:74]: can we check it on be start ? Otherwise, it is a silent behavior that the user cannot perceive

Comment (trueeyu) [reply be/src/storage/compaction_utils.cpp:74]: It is better to have a unified entry Check these configurations, rather than doing implicit processing where they are used.

File: be/src/storage/compaction_utils.cpp [hunk 3]
```diff
@@ -68,15 +68,12 @@ Status CompactionUtils::construct_output_rowset_writer(Tablet* tablet, uint32_t
...
+    if (max_segment_rows > INT32_MAX || max_segment_rows < 0) {
```
Comment (wyb) [inline be/src/storage/compaction_utils.cpp:75]:
```suggestion
    if (max_segment_rows > INT32_MAX || max_segment_rows <= 0) {
```

File: be/src/storage/compaction_utils.cpp (hunk 2 above)
Comment (trueeyu) [inline be/src/storage/compaction_utils.cpp:74]: better use double, the input size is the size in disk, may be less than input_row_num，the input_size / (input_row_num+1) may be equal to zero.

Comment (trueeyu) [reply be/src/storage/compaction_utils.cpp:74]: If the compression rate is high, there may be many small files

**Review by wyb — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

File: be/src/storage/compaction_utils.cpp (hunk 2 above)
Comment (trueeyu) [reply be/src/storage/compaction_utils.cpp:74]: It is best to give an upper limit on the number of rows (4 billion rows), otherwise there may be problems with the processing of the storage layer.
