### PR TITLE
[Enhancement] Compatibility fix for RecyclePartitionInfo and AlterJobV2

### LINKED ISSUE #49680: [Downgrade] Fail to downgrade from v3.3 to v3.2 due to LakeTableFastSchemaEvolutionJob and RecycleLakeRangePartitionInfo
### Steps to reproduce the behavior (Required)

```
2024-05-06 16:41:09.651+08:00 ERROR (UNKNOWN 172.26.80.37_9010_1714969793805(-1)|1) [StarRocksFE.start():193] StarRocksFE start failed
com.google.gson.JsonParseException: cannot deserialize class com.starrocks.alter.AlterJobV2 subtype named LakeTableFastSchemaEvolutionJob; did you forget to register a subtype?
        at com.starrocks.persist.gson.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:383) ~[starrocks-fe.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.persist.metablock.SRMetaBlockReader.readJson(SRMetaBlockReader.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.alter.AlterJobMgr.load(AlterJobMgr.java:1014) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1641) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1168) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
```

```
2024-07-26 13:03:12.953+08:00 ERROR (UNKNOWN 10.140.54.176_9010_1719200246894(-1)|1) [StarRocksFE.start():193] StarRocksFE start failed
com.google.gson.JsonParseException: cannot deserialize class com.starrocks.catalog.CatalogRecycleBin$RecyclePartitionInfoV2 subtype named RecycleLakeRangePartitionInfo; did you forget to register a subtype?
        at com.starrocks.persist.gson.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:383) ~[starrocks-fe.jar:?]
        at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:963) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[spark-dpp-1.0.0.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.persist.metablock.SRMetaBlockReader.readJson(SRMetaBlockReader.java:90) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.CatalogRecycleBin.load(CatalogRecycleBin.java:1358) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1644) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1171) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:136) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:84) ~[starrocks-fe.jar:?]
```

### Expected behavior (Required)

Downgrade from v3.3 to v3.2 latest with no error.

### Real behavior (Required)

FE can't start success with  unknown type`LakeTableFastSchemaEvolutionJob` or `RecycleLakeRangePartitionInfo`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kevincai**
## What I'm doing:

* `RuntimeTypeAdapterFactory` allows registering a subtype as the fallback
  type if a class can't be recognized during deserialization
* `ForwardCompatibleRecyclePartitionInfoV2` is added as the fallback
  subtype for `RecyclePartitionInfoV2`
* `ForwardCompatibleAlterJobV2Object` is added as the fallback subtype for
  `AlterJobV2`
* Update `AlterJobMgr/CatalogRecycleBin` accordingly to ignore the
  ForwardCompatible objects

Fixes #49680

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [x] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

## Documentation PRs only:

If you are submitting a PR that adds or changes English documentation and have not
included Chinese documentation, then you can check the box to request GPT to translate the
English doc to Chinese. Please ensure to uncheck the **Do not translate** box if translation is needed.
The workflow will generate a new PR with the Chinese translation after this PR is merged.

- [ ] Yes, translate English markdown files with GPT
- [x] Do not translate

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/persist/gson/RuntimeTypeAdapterFactory.java [hunk 1]
```diff
@@ -379,6 +398,9 @@ public R read(JsonReader in) throws IOException {
 
                 @SuppressWarnings("unchecked") // registration requires that subtype extends T
                 TypeAdapter<R> delegate = (TypeAdapter<R>) labelToDelegate.get(label);
+                if (delegate == null && fallbackLabel != null) {
+                    delegate = (TypeAdapter<R>) labelToDelegate.get(fallbackLabel);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/persist/gson/RuntimeTypeAdapterFactory.java:402]: Better to print the log in this case.

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/persist/gson/RuntimeTypeAdapterFactory.java:406]: done

**Review by gengjun-git — DISMISSED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

**Review by wyb — APPROVED** [review]
