### PR TITLE
[BugFix] Update Statement fail when SET a column using DEFAULT key word(#15181)

### LINKED ISSUE #15181: [BugFix] Update Statement fail when SET a column using DEFAULT key word
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `t` (
  `id` bigint(20) NOT NULL COMMENT "",
  `name` bigint(20) NOT NULL COMMENT "",
  `job1` bigint(20) NOT NULL DEFAULT "99" COMMENT "",
  `job2` bigint(20) NOT NULL COMMENT ""
) ENGINE=OLAP 
PRIMARY KEY(`id`, `name`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`) BUCKETS 7 
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT",
"enable_persistent_index" = "false",
"compression" = "LZ4"
);

2. insert into t (id,name,job1,job2) values (1,1,1,1);3. 
3. update t set job1 = default,job2 = null where id = 1 and name = 1;
### Expected behavior (Required)
success
### Real behavior (Required)
unknown error
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 8a29ddc8c |
+-------------------+

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15181

## Problem Summary(Required) ：
Problem:
When we Update a column which is defined the default value, if we use set = default in update statement, we will get unknow error because the DefaultValueExpr is not handled properly.

Solution:
Add the some code to cast the DefaultValueExpr to corresponding Literal type.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnAssignment.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java [hunk 1]
```diff
@@ -81,6 +83,11 @@ public static void analyze(UpdateStmt updateStmt, ConnectContext session) {
                     throw new SemanticException("primary key column cannot be updated: " + col.getName());
                 }
 
+                if (assign.getExpr() instanceof DefaultValueExpr) {
+                    assign.setExpr(new StringLiteral(col.calculatedDefaultValue()));
+                    assign.setExpr(TypeManager.addCastExpr(assign.getExpr(), col.getType()));
```
Comment (decster) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/UpdateAnalyzer.java:88]: `TypeManager.addCastExpr(new StringLiteral(col.calculatedDefaultValue()), col.getType())`

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 4 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/ast/ColumnAssignment.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/UpdateAnalyzer.java|2|2|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2
