### PR TITLE
[BugFix] keep PhysicalOperator equals with their LogicalOperator

### LINKED ISSUE #6362: Query returns Unknown error
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `primary_table` (
  `k1` datetime NOT NULL COMMENT "",
  `k2` varchar(65533) NOT NULL COMMENT "",
  `k3` varchar(65533) NOT NULL COMMENT "",
  `k4` boolean NOT NULL COMMENT "",
  `v1` tinyint(4) NOT NULL COMMENT "",
  `v2` smallint(6) NOT NULL COMMENT "",
  `v3` int(11) NOT NULL COMMENT "",
  `v4` double NOT NULL COMMENT "",
  `v5` decimal128(27, 9) NOT NULL COMMENT ""
) ENGINE=OLAP
PRIMARY KEY(`k1`, `k2`, `k3`, `k4`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`) BUCKETS 3
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. CREATE EXTERNAL TABLE `hive_ssb_100g_csv_supplier` (
  `s_suppkey` int(11) NULL COMMENT "",
  `s_name` varchar(26) NULL COMMENT "",
  `s_address` varchar(26) NULL COMMENT "",
  `s_city` varchar(11) NULL COMMENT "",
  `s_nation` varchar(16) NULL COMMENT "",
  `s_region` varchar(13) NULL COMMENT "",
  `s_phone` varchar(16) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_100g_csv",
"table" = "supplier",
"resource" = "hive_resource_emr",
"hive.metastore.uris"  =  "thrift://172.26.194.238:9083"
);
3. CREATE TABLE `tpcds_100g_web_page` (
  `wp_web_page_sk` int(11) NOT NULL COMMENT "",
  `wp_web_page_id` char(16) NOT NULL COMMENT "",
  `wp_rec_start_date` date NULL COMMENT "",
  `wp_rec_end_date` date NULL COMMENT "",
  `wp_creation_date_sk` int(11) NULL COMMENT "",
  `wp_access_date_sk` int(11) NULL COMMENT "",
  `wp_autogen_flag` char(1) NULL COMMENT "",
  `wp_customer_sk` int(11) NULL COMMENT "",
  `wp_url` varchar(100) NULL COMMENT "",
  `wp_type` char(50) NULL COMMENT "",
  `wp_char_count` int(11) NULL COMMENT "",
  `wp_link_count` int(11) NULL COMMENT "",
  `wp_image_count` int(11) NULL COMMENT "",
  `wp_max_ad_count` int(11) NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`wp_web_page_sk`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`wp_web_page_sk`) BUCKETS 5
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
4. CREATE EXTERNAL TABLE `es_ssb_10g_supplier` (
  `s_suppkey` int(11) NOT NULL COMMENT "",
  `s_name` varchar(26) NOT NULL COMMENT "",
  `s_address` varchar(26) NOT NULL COMMENT "",
  `s_city` varchar(11) NOT NULL COMMENT "",
  `s_nation` varchar(16) NOT NULL COMMENT "",
  `s_region` varchar(13) NOT NULL COMMENT "",
  `s_phone` varchar(16) NOT NULL COMMENT ""
) ENGINE=ELASTICSEARCH
COMMENT "ELASTICSEARCH"
PROPERTIES (
"hosts" = "http://172.26.92.141:9200",
"user" = "root",
"password" = "123456",
"index" = "supplier",
"type" = "_doc",
"transport" = "http",
"enable_docvalue_scan" = "true",
"max_docvalue_fields" = "20",
"enable_keyword_sniff" = "true"
);

5. select     subq_0.c2 as c0,    subq_0.c2 as c1,    subq_0.c2 as c2,    subq_0.c5 as c3,    subq_0.c5 as c4 from    (select           ref_2.wp_image_count as c0,          ref_1.s_phone as c1,          96 as c2,          ref_1.s_suppkey as c3,          ref_1.s_phone as c4,          ref_1.s_phone as c5       from        primary_table as ref_0
     inner join hive_ssb_100g_csv_supplier as ref_1               on (ref_0.k4 = ref_1.s_suppkey )             inner join tpcds_100g_web_page as ref_2             on (ref_0.v1 = ref_2.wp_web_page_sk )           right join es_ssb_10g_supplier as ref_3           on (ref_1.s_address = ref_3.s_name )       where (ref_0.v4 > ref_0.v4)          and (ref_2.wp_web_page_id <= ref_1.s_name)) as subq_0 where case when (subq_0.c4 is not NULL)        and (subq_0.c3 is not NULL) then subq_0.c3 else subq_0.c3 end      <> subq_0.c2;

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
2022-05-20 15:10:57,508 WARN (starrocks-mysql-nio-pool-2|752) [StmtExecutor.execute():470] execute Exception, sql select     subq_0.c2 as c0,    subq_0.c2 as c1,    subq_0.c2 as c2,    subq_0.c5 as c3,    subq_0.c5 as c4 from    (select           ref_2.wp_image_count as c0,          ref_1.s_phone as c1,          96 as c2,          ref_1.s_suppkey as c3,          ref_1.s_phone as c4,          ref_1.s_phone as c5       from          sqlsmith.primary_table as ref_0               inner join sqlsmith.hive_ssb_100g_csv_supplier as ref_1               on (ref_0.k4 = ref_1.s_suppkey )             inner join sqlsmith.tpcds_100g_web_page as ref_2             on (ref_0.v1 = ref_2.wp_web_page_sk )           right join sqlsmith.es_ssb_10g_supplier as ref_3           on (ref_1.s_address = ref_3.s_name )       where (ref_0.v4 > ref_0.v4)          and (ref_2.wp_web_page_id <= ref_1.s_name)) as subq_0 where case when (subq_0.c4 is not NULL)        and (subq_0.c3 is not NULL) then subq_0.c3 else subq_0.c3 end      <> subq_0.c2
java.lang.NullPointerException: null
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:260) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.extractBestPlan(Optimizer.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:96) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:84) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:309) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
BRANCH-2.2-RELEASE-671149f

### PR DESCRIPTION
**Pull request by Seaven**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6362

## Problem Summary(Required) ：

All table data is empty.
The bug sql:
```
SELECT *
FROM (
    SELECT ref_1.s_suppkey AS c3
    FROM (select * from primary_table where false) ref_0
        INNER JOIN hive_ssb_100g_csv_supplier ref_1 ON ref_0.k4 = ref_1.s_suppkey
        INNER JOIN tpcds_100g_web_page ref_2 ON ref_0.v1 = ref_2.wp_web_page_sk
        RIGHT JOIN es_ssb_10g_supplier ref_3 ON ref_1.s_address = ref_3.s_name
    WHERE ref_2.wp_web_page_id <= ref_1.s_name
) subq_0
WHERE subq_0.c3 = 96;
```

but I test sql is normal
```
SELECT *
FROM (
    SELECT ref_1.s_suppkey AS c3
    FROM (select * from primary_table where true) ref_0
        INNER JOIN hive_ssb_100g_csv_supplier ref_1 ON ref_0.k4 = ref_1.s_suppkey
        INNER JOIN tpcds_100g_web_page ref_2 ON ref_0.v1 = ref_2.wp_web_page_sk
        RIGHT JOIN es_ssb_10g_supplier ref_3 ON ref_1.s_address = ref_3.s_name
    WHERE ref_2.wp_web_page_id <= ref_1.s_name
) subq_0
WHERE subq_0.c3 = 96;
```

I guess the reason is copy `ValueOperator` into memo happend wrong, so I find the `equals` method of `PhyiscalValueOperator` is different with `LogicalValueOperator`.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 3 / 6 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalFilterOperator.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalLimitOperator.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/physical/PhysicalValuesOperator.java|1|2|50.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalLimitOperator.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalFilterOperator.java [hunk 1]
```diff
@@ -22,6 +22,11 @@ public ScalarOperator getPredicate() {
         return predicate;
     }
 
+    @Override
+    public boolean equals(Object o) {
+        return this == o;
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalFilterOperator.java:27]: What's the difference with `==` ?

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalFilterOperator.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/physical/PhysicalFilterOperator.java:27]: None difference, the purpose is to check the object, may be same duplicate operators in memo,  will find wrong if use value eqauls check
