### PR TITLE
[BugFix] add `es_index_max_result_window` config value to limit fetch batch size

### LINKED ISSUE #5994: Failed to connect to ES server.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
mysql> create external table es_null_fields (`id_date` datetime NULL ) engine=ELASTICSEARCH properties ("hosts" = "http://xxx:9200", "user" = "root", "password" = "root", "index" = "datey", "type" = "doc");
```
2. INSERT INTO '....'
3. SELECT  '....'
```
select count(*) from es_null_fields;
```
### Expected behavior (Required)
```
mysql> select count(*) from es_null_fields;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.01 sec)
```
### Real behavior (Required)
ERROR 1064 (HY000): Failed to connect to ES server, errmsg is: The requested URL returned error: 400
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - MAIN-RELEASE 8e5b859

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [X] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5994

## Problem Summary(Required) ：

if request batch size exceeds `index.max_result_window`, ES will return bad request(400)

see also https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html

### CODE REVIEW

File: be/src/common/config.h [hunk 1]
```diff
@@ -505,6 +505,11 @@ CONF_String(es_scroll_keepalive, "5m");
 // HTTP connection timeout for es.
 CONF_Int32(es_http_timeout_ms, "5000");
 
+// es index max result window, and this value affects batch size.
+// if request batch size exceeds this value, ES will return bad request(400)
+// https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html
+CONF_Int32(es_index_max_result_window, "10000");
```
Comment (imay) [inline be/src/common/config.h:511]: I think it is better to make it as a const value rather than a configuration?
Because we don't want users to change this configure

**Review by DorianZheng — APPROVED** [review]
LGTM

File: be/src/common/config.h (hunk 1 above)
Comment (dirtysalt) [reply be/src/common/config.h:511]: No, because different es maybe have different values.

Comment (imay) [reply be/src/common/config.h:511]: What's the default value for ES?

Comment (DorianZheng) [reply be/src/common/config.h:511]: default value is 10000

Comment (DorianZheng) [reply be/src/common/config.h:511]: image

Comment (imay) [reply be/src/common/config.h:511]: Thanks @DorianZheng That's fine for me.

**Review by imay — APPROVED** [review]
