### PR TITLE
[Bugfix] InSubQuery with aggregate and predicate

### LINKED ISSUE #6463: [sqlancer] unknow error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS d10;
CREATE DATABASE d10;
USE d10;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NULL ,c_0_1 CHAR(1) NULL ,c_0_2 DATE NOT NULL ,c_0_3 CHAR(21) NOT NULL ,c_0_4 BOOLEAN NOT NULL ,c_0_5 VARCHAR(11) NOT NULL ,c_0_6 DECIMAL(22, 19)  NOT NULL ,c_0_7 DECIMAL(21, 13)  NULL ,c_0_8 DECIMAL(15, 5)  NULL ,c_0_9 BOOLEAN NULL ,c_0_10 BOOLEAN NOT NULL ,c_0_11 ARRAY<STRING> NOT NULL ,c_0_12 ARRAY<STRING> NULL , INDEX index1_c_0_0(`c_0_0`) USING BITMAP) DUPLICATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4,c_0_5,c_0_6,c_0_7,c_0_8,c_0_9,c_0_10) PARTITION BY RANGE(c_0_0) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 168 day)) DISTRIBUTED BY HASH (c_0_10,c_0_3,c_0_6,c_0_7,c_0_2,c_0_4,c_0_8) BUCKETS 3 properties("replication_num"="3", "bloom_filter_columns"="c_0_3") ;
CREATE TABLE t1 (c_1_0 DECIMAL(8, 7)  NULL ,c_1_1 DATE NULL ,c_1_2 DECIMAL(18, 11)  NOT NULL ,c_1_3 DATE NOT NULL ,c_1_4 TINYINT NULL ,c_1_5 LARGEINT NOT NULL ,c_1_6 BOOLEAN NULL ,c_1_7 TINYINT NULL ,c_1_8 DATE NULL ,c_1_9 BOOLEAN NULL ,c_1_10 BOOLEAN NOT NULL ,c_1_11 ARRAY<STRING> NOT NULL ,c_1_12 ARRAY<INT> NULL ,c_1_13 FLOAT NOT NULL ,c_1_14 BOOLEAN NOT NULL ,c_1_15 LARGEINT NULL ,c_1_16 SMALLINT NULL ,c_1_17 LARGEINT NULL , INDEX index1_c_1_7(`c_1_7`) USING BITMAP) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8) PARTITION BY RANGE(c_1_1) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 230 day)) DISTRIBUTED BY HASH (c_1_5,c_1_6,c_1_8,c_1_3,c_1_2,c_1_0,c_1_4,c_1_1) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES (NULL, '', '2010-01-31', 'V5UzHY1', false, 'vHwUV', 3.50E-17, 0.0000046133268, 16660.64045, false, true, ["Q", "D", "", "Dv6yXdoDK", "2qZToFVJk"], ["BSa", "1zS", "", "PD", "wCc89G3ZH", "Ch1", "P", "R", "Pq", "", ""]);
INSERT INTO t1 VALUES (8E-7, '2010-01-27', 0.00002956324, '2010-01-21', 6, 381189902, false, 4, '2010-01-06', true, false, ["o73CBzS", "", "f", "Uxjy5hLx", "rWAbpHxa7", "ZP", "KD", "0", "3ssn1Ka", "lIsm1wD", "fG", "RN9c8VQv", "1JC", "rxt"], [283075161, -58973551, -589926699, -589926699, 170316992, 381189902, 283075161, 2006449036, 283075161, -887406492, -1765838867, -1316039861], 0.16062476370913792, true, 1821693876, 11, -1231056200);
INSERT INTO t0 VALUES ('2010-01-01 08:00:14', '', '2010-01-31', '', false, 'lIAT', 2.92E-17, 0.0000066036431, 62008.33418, true, true, ["", "QYp", "6", "Y", "YT1Oxp8j", "W", "CG", "", ""], ["MKUdC8A6"]), ('2010-01-19 08:00:14', '', '2009-12-31', 'VrnU', false, 'j', 6.34E-17, 0.0000050848699, 95830.53273, true, false, ["iy", "huE8uzMi8", "SR", "sl0SRK", "azc", "9us", "", "", "6eA", "wAD", ""], ["K"]), ('2010-01-05 08:00:14', '', '2010-01-24', 'j', false, '', 7.10E-17, 0.0000070756606, NULL, true, true, ["", "", "93f", "uIJDd", "hre", "P", "1Ep", "", "F7vjsgSg9", "TMZw59wwW", "zD", "6MhklB", "0aJsKV0G", "cY"], ["m", "I1f", "e5419Kwo", "LGlqfb", "w", "s", "U", "wVvVErSPf", "", "N", "", "ajpr", "", "", "cS22IBofU"]);
INSERT INTO t0 VALUES ('2010-01-05 08:00:14', '', '2010-01-01', 'SCp0gv', true, '3V', 6.29E-17, NULL, 98693.46126, true, false, ["X", "NQ", "", "Nx", "uvixY", "", "j", "0k4VFm8u", "1XUMpxR9i"], ["u7v", "t9GLq", "DO", "IfVgwA", "en", "", "N", "jM", "Ij93IeYH", "xs74S", "W", "yHsue", "j3wBF", "gFB", "3e8I"]);
INSERT INTO t1 VALUES (3E-7, '2010-01-01', 0.00000309455, '2010-01-14', 0, -829203278, false, 1, '2010-01-05', NULL, true, ["RgoUJ", "4v", "A", "Bpby2", "", "", "E4", "", ""], [1201417464, 1308031441, -887406492, -829203278, -452693659, -440510001, -1316039861, -440510001, -1293655213, -1293655213, -1096160345], 0.16062476370913792, true, -1146868963, 1, -887406492), (1E-7, '2010-01-15', 0.00002895763, '2010-01-25', 1, 381189902, NULL, NULL, '2010-01-12', true, false, ["kw3ktZ7Fi", "3"], [-36251280, -1395902478, 2006449036, 969714863], 0.9124516641635391, true, 338189836, 8, 143644528), (8E-7, NULL, 0.00004195996, '2010-01-23', 7, -844768080, false, 0, NULL, true, true, ["xtFDZ7"], [-1224636445, 1316804321, 1491072512, 969714863, -318789337, 1648068707, 1578202062, 2084922358, 1316804321, -1307286904, 338189836], 0.8493875243956446, true, -1137133826, 14, 381189902);
INSERT INTO t1 VALUES (3E-7, '2010-01-29', 0.00004746849, '2010-01-12', 5, 1821693876, false, 6, '2010-01-12', true, true, ["y", "H9", "K8mlwiBY", "z2hGxe", "Jm", "xd", "", "dSrjiniAw"], [283075161, -1224636445, -1293655213, -178017473, 2006449036, -475875882, -896187320, 1775679335], 0.48437964461536354, false, -1267834407, 13, -354705935), (6E-7, '2010-01-31', 0.00009030369, '2010-01-20', 4, -617433199, false, 1, '2010-01-20', false, false, ["QF1j", "f6", "60d", "vrUD", "wys8fef", ""], [603609140, -33069050, -475875882, -9223372036854775808, -564423652, -1485332306], 0.48437964461536354, true, -620576501, 4, 1230389825), (3E-7, '2010-01-10', 0.00004538895, '2010-01-18', 1, -408239763, false, 3, NULL, true, false, ["", "ElrbsvldI", "U7Rq", "", "nGuW", "JBqvtv", "z", "h2", "mkwz3imj"], [-1765838867, -1619772622, 231160815], 0.5080116090757605, false, -363328017, 10, NULL);
INSERT INTO t0 VALUES ('2010-01-21 08:00:14', '', '2010-01-03', '', false, '4Y7ycdr', 4.02E-17, 0.0000019468521, 30887.47422, true, false, ["l5", "JC3BlnFyK", "2pXvpR"], ["B", "", "mal", "U5", "J89"]);
INSERT INTO t0 VALUES ('2010-01-12 08:00:14', '', '2010-01-24', '7', true, '', 1.47E-17, 0.0000024958093, 97038.37235, NULL, false, ["Wd", "", "3hPREI", "6tXjW5", "DrH", "zm", "REf"], ["fZjn", "gihoebc", "OlOJQyG", "3f1fd", "y", "eRkH5j8E", "", "", "LCNxosSck", "D", "", "4lMu5JX", "GBEJZC", "e", "fsz"]), ('2010-01-28 08:00:14', '', '2010-01-14', 'Kpvu', true, 'w', 3.18E-17, 0.0000035135216, 50115.20808, NULL, true, [""], ["OIBpF", "O", "xiEbXL", "Ql7L", "P", "wICR", "", "k", ""]), (NULL, '', '2010-01-04', '0GgEO', false, '', 2.62E-17, 0.0000020238112, NULL, false, true, ["A", "f", "ARemxlyO", "y1", "3u", "n", "23U", "QPnju2", "", "ekQq8", ""], ["fctKc35D", "F", "X", "47LQQIcQ", "", ""]);
INSERT INTO t1 VALUES (6E-7, '2010-01-01', 0.00008285702, '2010-01-01', 5, 1606173237, false, 0, '2010-01-19', false, true, ["q0", "Art", "", "0F3k4Fn", "ybE", "ACyxXh7Nh", "YOE", "IGznd", "Dfdc", "J9Y", ""], [231160815, 1568338008, -2123069981, 1172806012, 231160815, 381189902, 708620132], 0.15276182794359916, true, -1066434344, 7, 170316992), (4E-7, '2010-01-10', 0.00009598352, '2010-01-25', 3, -320000402, false, 4, '2010-01-18', true, true, ["x", "3n", "", "TqeTK", "vyAW2hNQj", "", "65", "Phr26JK"], [-2063869369, 709974762, 440998483, -1868695626, -5721333], 1.201417464E9, false, 1459756800, NULL, NULL);
INSERT INTO t0 VALUES ('2010-01-04 08:00:14', '', '2010-01-03', 'dS', true, '', 3.91E-17, 0.0000057689510, 69110.19473, false, true, ["oBYo", "T", "S", "", "io", "Omu9", "sZYZe06", "c", "", "1", "Ybq4BEiP", "mCI", ""], ["", "i5mXd", "qIfcj1Q2S", "gd", "dX", "", "", "jVl"]), ('2010-01-31 08:00:14', '', '2010-01-02', '', false, 'r', 2.94E-17, NULL, 97408.43683, true, false, ["", "jLkimT"], ["O", "Gn", "", "qaZRE4", "", "3o4", "", "Z", "", ""]);
CREATE MATERIALIZED VIEW v0 AS SELECT t1_70.c_1_0, t1_70.c_1_1, t1_70.c_1_2, t1_70.c_1_3, t1_70.c_1_4, t1_70.c_1_6, t1_70.c_1_7, t1_70.c_1_10, t1_70.c_1_14, t1_70.c_1_17, COUNT(t1_70.c_1_5) , MAX(t1_70.c_1_8) , MIN(t1_70.c_1_9) , MIN(t1_70.c_1_13) , COUNT(t1_70.c_1_15) , COUNT(t1_70.c_1_16)  FROM t1 AS t1_70 GROUP BY t1_70.c_1_0, t1_70.c_1_1, t1_70.c_1_2, t1_70.c_1_3, t1_70.c_1_4, t1_70.c_1_6, t1_70.c_1_7, t1_70.c_1_10, t1_70.c_1_14, t1_70.c_1_17 ORDER BY t1_70.c_1_0 DESC, t1_70.c_1_1 DESC, t1_70.c_1_2, t1_70.c_1_3 ASC, t1_70.c_1_4, t1_70.c_1_6 ASC, t1_70.c_1_7 ASC, t1_70.c_1_10 DESC, t1_70.c_1_14, t1_70.c_1_17 DESC;
CREATE MATERIALIZED VIEW v0 AS SELECT t0_71.c_0_0, t0_71.c_0_2, t0_71.c_0_3, t0_71.c_0_4, t0_71.c_0_5, t0_71.c_0_6, t0_71.c_0_7, t0_71.c_0_8, t0_71.c_0_9, t0_71.c_0_10, MAX(t0_71.c_0_1)  FROM t0 AS t0_71 GROUP BY t0_71.c_0_0, t0_71.c_0_2, t0_71.c_0_3, t0_71.c_0_4, t0_71.c_0_5, t0_71.c_0_6, t0_71.c_0_7, t0_71.c_0_8, t0_71.c_0_9, t0_71.c_0_10 ORDER BY t0_71.c_0_0, t0_71.c_0_2 ASC, t0_71.c_0_3 DESC, t0_71.c_0_4 DESC, t0_71.c_0_5 ASC, t0_71.c_0_6 ASC, t0_71.c_0_7, t0_71.c_0_8 ASC, t0_71.c_0_9 DESC, t0_71.c_0_10;
INSERT INTO t0 VALUES ('2010-01-08 08:00:14', '', '2010-01-10', 'ZpBoM', true, '', 4.55E-17, 0.0000065845274, NULL, true, true, ["SwgBXkE", "baquA", "AS", "h", "fi", "", "TO", "7kHV", "nIg62", "", "17G", "0"], ["0NHP", "9ba", "UV", "jkX8TbYZ0", "", "F", "yDGn", "vg", "Moun", "x", "838", ""]), ('2010-01-30 08:00:14', '', '2010-01-08', 'WUO', false, 'tQsu', 7.42E-17, 0.0000024159543, 88446.78453, true, false, ["k", "je", "02jW", "Sl", "oAhimyke", "", "IW", "ppg6", "", "GfG3hahDg", "XDlrj9J", "", "zj"], ["YbJ", "d0m9hMd", "", "0", "", "3h", "uYU", "DQHC7", "E", "", "", "yLymMaLc"]);
INSERT INTO t0 VALUES ('2010-01-02 08:00:14', '', '2010-01-01', 'oK', false, '', 5.53E-17, 0.0000047236447, 51964.54544, false, false, ["3oaDwWM9", "0", "", "k", "nt", "ZT", "i", "xNE2V", "CaWRa2", "", "GBYX", "", ""], ["", "AK", "EE", "F", "kE", "7mpHWhHb", "COLI", "wVzuj54cY", "yu", "", "5ST1CpU", "jSB9", "SKD"]), ('2010-01-02 08:00:14', '', '2010-01-11', 'Wae', true, 'j5k', 4.13E-17, 0.0000039835002, 64479.16823, true, false, [""], ["e", "NGTw4", "", "", "m", "DU6yn0jtB", "99WJhmK"]);
SELECT DISTINCT * FROM (WITH with_t_0 as (SELECT t1_76.c_1_0, t1_76.c_1_1, t1_76.c_1_2, t1_76.c_1_3, t1_76.c_1_4, t1_76.c_1_5, t1_76.c_1_6, t1_76.c_1_7, t1_76.c_1_8, t1_76.c_1_9, t1_76.c_1_10, t1_76.c_1_13, t1_76.c_1_14, t1_76.c_1_15, t1_76.c_1_16, t1_76.c_1_17 FROM t1 AS t1_76 WHERE false) SELECT DISTINCT 3E-7 FROM  (SELECT t1_76.c_1_0, t1_76.c_1_1, t1_76.c_1_2, t1_76.c_1_3, t1_76.c_1_4, t1_76.c_1_5, t1_76.c_1_6, t1_76.c_1_7, t1_76.c_1_8, t1_76.c_1_9, t1_76.c_1_10, t1_76.c_1_13, t1_76.c_1_14, t1_76.c_1_15, t1_76.c_1_16, t1_76.c_1_17 FROM t1 AS t1_76 WHERE  ( t1_76.c_1_17 ) <= ( ((1568338008)-(-2017374972)) ) ) subt1 LEFT ANTI JOIN (SELECT with_t_0.c_1_0, with_t_0.c_1_1, with_t_0.c_1_2, with_t_0.c_1_3, with_t_0.c_1_4, with_t_0.c_1_5, with_t_0.c_1_6, with_t_0.c_1_7, with_t_0.c_1_8, with_t_0.c_1_9, with_t_0.c_1_10, with_t_0.c_1_13, with_t_0.c_1_14, with_t_0.c_1_15, with_t_0.c_1_16, with_t_0.c_1_17 FROM with_t_0 AS with_t_0 WHERE true) subwith_t_0 ON subt1.c_1_4 = subwith_t_0.c_1_14 AND subt1.c_1_4 >= subwith_t_0.c_1_14 WHERE (subt1.c_1_17) IN ((SELECT t0_75.c_0_0 FROM t0 AS t0_75 WHERE NULL) )  UNION ALL SELECT DISTINCT 3E-7 FROM  (SELECT t1_76.c_1_0, t1_76.c_1_1, t1_76.c_1_2, t1_76.c_1_3, t1_76.c_1_4, t1_76.c_1_5, t1_76.c_1_6, t1_76.c_1_7, t1_76.c_1_8, t1_76.c_1_9, t1_76.c_1_10, t1_76.c_1_13, t1_76.c_1_14, t1_76.c_1_15, t1_76.c_1_16, t1_76.c_1_17 FROM t1 AS t1_76 WHERE  ( t1_76.c_1_17 ) <= ( ((1568338008)-(-2017374972)) ) ) subt1 LEFT ANTI JOIN (SELECT with_t_0.c_1_0, with_t_0.c_1_1, with_t_0.c_1_2, with_t_0.c_1_3, with_t_0.c_1_4, with_t_0.c_1_5, with_t_0.c_1_6, with_t_0.c_1_7, with_t_0.c_1_8, with_t_0.c_1_9, with_t_0.c_1_10, with_t_0.c_1_13, with_t_0.c_1_14, with_t_0.c_1_15, with_t_0.c_1_16, with_t_0.c_1_17 FROM with_t_0 AS with_t_0 WHERE true) subwith_t_0 ON subt1.c_1_4 = subwith_t_0.c_1_14 AND subt1.c_1_4 >= subwith_t_0.c_1_14 WHERE (NOT ((subt1.c_1_17) IN ((SELECT t0_75.c_0_0 FROM t0 AS t0_75 WHERE NULL) ) )) UNION ALL SELECT DISTINCT 3E-7 FROM  (SELECT t1_76.c_1_0, t1_76.c_1_1, t1_76.c_1_2, t1_76.c_1_3, t1_76.c_1_4, t1_76.c_1_5, t1_76.c_1_6, t1_76.c_1_7, t1_76.c_1_8, t1_76.c_1_9, t1_76.c_1_10, t1_76.c_1_13, t1_76.c_1_14, t1_76.c_1_15, t1_76.c_1_16, t1_76.c_1_17 FROM t1 AS t1_76 WHERE  ( t1_76.c_1_17 ) <= ( ((1568338008)-(-2017374972)) ) ) subt1 LEFT ANTI JOIN (SELECT with_t_0.c_1_0, with_t_0.c_1_1, with_t_0.c_1_2, with_t_0.c_1_3, with_t_0.c_1_4, with_t_0.c_1_5, with_t_0.c_1_6, with_t_0.c_1_7, with_t_0.c_1_8, with_t_0.c_1_9, with_t_0.c_1_10, with_t_0.c_1_13, with_t_0.c_1_14, with_t_0.c_1_15, with_t_0.c_1_16, with_t_0.c_1_17 FROM with_t_0 AS with_t_0 WHERE true) subwith_t_0 ON subt1.c_1_4 = subwith_t_0.c_1_14 AND subt1.c_1_4 >= subwith_t_0.c_1_14 WHERE (((subt1.c_1_17) IN ((SELECT t0_75.c_0_0 FROM t0 AS t0_75 WHERE NULL) ) ) IS NULL)) t;


```

```
fe.log:
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:494) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:112) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr$Formatter.visitVariableReference(ScalarOperatorToExpr.java:97) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator.accept(ColumnRefOperator.java:99) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.ScalarOperatorToExpr.buildExecExpression(ScalarOperatorToExpr.java:73) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.lambda$visitPhysicalDistribution$1(PlanFragmentBuilder.java:1391) ~[starrocks-fe.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_252]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_252]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_252]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_252]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_252]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1393) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:44) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEAnchor(PlanFragmentBuilder.java:2356) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalCTEAnchor(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalCTEAnchorOperator.accept(PhysicalCTEAnchorOperator.java:28) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:138) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.buildSetOperation(PlanFragmentBuilder.java:2133) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:2178) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalUnion(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalUnionOperator.accept(PhysicalUnionOperator.java:37) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:1362) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalDistribution(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalDistributionOperator.accept(PhysicalDistributionOperator.java:44) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:1129) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visitPhysicalHashAggregate(PlanFragmentBuilder.java:255) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.optimizer.operator.physical.PhysicalHashAggregateOperator.accept(PhysicalHashAggregateOperator.java:138) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder$PhysicalPlanTranslator.visit(PlanFragmentBuilder.java:264) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.plan.PlanFragmentBuilder.createPhysicalPlan(PlanFragmentBuilder.java:151) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:134) ~[starrocks-fe.jar:?]
        at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:82) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:319) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:290) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:438) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:674) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE ca91785 |
+----------------------+
- cluster: sqlancer_01_release

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6463

## Problem Summary(Required) ：

For the following query

```sql
SELECT DISTINCT(t1d)
FROM test_all_type
WHERE (t1a IN 
   (
      SELECT v1
      FROM t0
   )
)IS NULL
```

The in sub-query will be optimized (refer to #6274 for details) as

```
                                        CTEAnchor
                                       /        \   
                                  LeftChild    rightChild
 ```

Plus aggregation, it becomes

```
                                         Agg
                                          |
                                        Project
                                          |
                                        CTEAnchor
                                       /        \   
                                  LeftChild    RightChild
```

We add a rule `PushDownProjectToCTEAnchorRule` to push Project to CTEAnchor's right child

After the rule is applied, it becomes

```
                                         Agg
                                          |
                                        CTEAnchor
                                       /        \   
                                  LeftChild    Project
                                                     \
                                                  RightChild
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 33 / 33 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java|29|29|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java [hunk 1]
```diff
@@ -191,6 +193,7 @@ void logicalRuleRewrite(Memo memo, TaskContext rootTaskContext) {
 
         ruleRewriteIterative(memo, rootTaskContext, RuleSetType.MULTI_DISTINCT_REWRITE);
         ruleRewriteIterative(memo, rootTaskContext, RuleSetType.SUBQUERY_REWRITE);
+        ruleRewriteIterative(memo, rootTaskContext, new PushDownProjectionToCTEAnchorRule());
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java:196]: move the rule to RuleSet.PRUNE_PROJECT is enough？

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+public class PushDownProjectionToCTEAnchorRule extends TransformationRule {
+
+    public PushDownProjectionToCTEAnchorRule() {
+        super(RuleType.TF_PUSH_DOWN_PROJECT_TO_CTE_ANCHOR,
+                Pattern.create(OperatorType.LOGICAL_PROJECT).addChildren(
+                        Pattern.create(OperatorType.LOGICAL_FILTER)
+                                .addChildren(Pattern.create(OperatorType.LOGICAL_CTE_ANCHOR)
+                                        .addChildren(Pattern.create(OperatorType.PATTERN_LEAF))
+                                        .addChildren(Pattern.create(OperatorType.LOGICAL_PROJECT,
+                                                OperatorType.PATTERN_LEAF)))
```
[the remark this answers is not in the document]
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java:30]: The following sql ( the difference is that there is no is null predicate ), the two projectOperation will be optimized by `MergeTwoProjectRule` before `QuantifiedApply2OuterJoinRule` applied, so this sql works fine without this pr

```sql
SELECT DISTINCT(t1d)
FROM test_all_type
WHERE t1a IN 
   (
      SELECT v1
      FROM t0
   )
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java:196]: Exactly

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+import com.starrocks.sql.optimizer.operator.logical.LogicalProjectOperator;
+import com.starrocks.sql.optimizer.operator.pattern.Pattern;
+import com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ScalarOperator;
+import com.starrocks.sql.optimizer.rule.RuleType;
+
+import java.util.List;
+import java.util.Map;
+
+public class PushDownProjectionToCTEAnchorRule extends TransformationRule {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java:21]: Comment the before tree and after tree

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java:30]: I means the rule is an common rule, only need pattern `project-anchor`, don't need consider `filter`, and if you only pattern `project-filter-anchor`, maybe will trigger the bug when the plan only contains `project-anchor`

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java (hunk 1 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Optimizer.java:196]: move it after modify the pattern

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java]: Updated

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 26 / 26 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownProjectionToCTEAnchorRule.java|23|23|100.00%|

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 19 / 19 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/Optimizer.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/RuleType.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownProjectToCTEAnchorRule.java|16|16|100.00%|

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
