### PR TITLE
[Enhancement] Add uuid support for the postgres jdbc catalog

### LINKED ISSUE #58010: UUID column type no supported with JDBC PostgreSQL driver
Hi,

I tried to use the external jdbc catalog but faced with problem get uuid columns.

### Steps to reproduce the behavior (Required)

```sql
CREATE EXTERNAL CATALOG jdbc0
PROPERTIES
(
  'type' = 'jdbc', 
  'user' = 'dbtest',
  'password' = 'pass',
  'jdbc_uri' = 'jdbc:postgresql://dbhost:5432/test',
  'driver_url' = 'https://repo1.maven.org/maven2/org/postgresql/postgresql/42.3.3/postgresql-42.3.3.jar',
  'driver_class' = 'org.postgresql.Driver'
);

SELECT id, name FROM jdbc0.public.test;
```

### Expected behavior (Required)

```
id,name
165e8ffe-d036-433f-815d-89bb4ab6622f,Test
```

### Real behavior (Required)

```
SQL Error [1064] [42000]: Getting analyzing error. Detail message: Datatype of external table column [id] is not supported!.
```

### StarRocks version (Required)

3.4.1-2f78e09

### PR DESCRIPTION
**Pull request by artemklevtsov**
## Why I'm doing:

I tried to use external catalog with the postgres database. I faced with errors when fetch uuid columns (unsupported type). This PR fix this issue (tested on the dev-environment).

## What I'm doing:

Fixes #58010

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [x] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java [hunk 1]
```diff
@@ -129,6 +129,10 @@ public Type convertColumnType(int dataType, String typeName, int columnSize, int
                 break;
         }
 
+        if (typeName.equalsIgnoreCase("uuid")) {
+            return ScalarType.createVarcharType(36);
+        }
```
Comment (alvin-celerdata) [inline fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:134]: Could you add a UT case to cover it?

Comment (artemklevtsov) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:134]: Added column to the `PostgresSchemaResolverTest` with uuid type [84ed118](https://github.com/StarRocks/starrocks/pull/58326/commits/84ed1181c62352af7bc2595478dc8c09aaf836e4).

File: fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java [hunk 2]
```diff
@@ -129,6 +129,10 @@ public Type convertColumnType(int dataType, String typeName, int columnSize, int
                 break;
         }
 
+        if (typeName.equalsIgnoreCase("uuid")) {
+            return ScalarType.createVarcharType(36);
```
Comment (zombee0) [inline fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: Hi, Thanks for contribution.
I'm curious why you want to convert UUID to Varchar(36). In Iceberg we convert it to VARBINARY, and from https://www.postgresql.org/docs/current/datatype-uuid.html, I think the length should be 128-bit(16Bytes), could you confirm that?

Comment (artemklevtsov) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: I noticed that Apache Doris [converts](https://github.com/apache/doris/blob/3.0.5-rc01/fe/fe-core/src/main/java/org/apache/doris/datasource/jdbc/client/JdbcPostgreSQLClient.java#L167) uuid to string.
With current commit it looks like this:

```
MySQL [(none)]> select id from dwh.public.districts limit 2;
+--------------------------------------+
| id                                   |
+--------------------------------------+
| 8c1c7663-4cf4-11e6-80b8-fd42e350b981 |
| 7fd3aee6-4cf4-11e6-80b8-fd42e350b981 |
+--------------------------------------+
2 rows in set (0.056 sec)
```

Comment (zombee0) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: so what will happen if you create a olap table in StarRocks with binary type and insert into xxx select xxx from pg_table?

Comment (zombee0) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: Or maybe you need tread UUID in StarRocks as VarChar that what u have done in this pr

Comment (zombee0) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: Consider the definition, we'd better always treat UUID as 128-bit binary, so users can have a consistent approach in different systems.

Comment (wangsimo0) [reply fe/fe-core/src/main/java/com/starrocks/connector/jdbc/PostgresSchemaResolver.java:133]: Hi Thanks for the contribution! Amazing work!
Could you pls convert it into varbinary as the iceberg catalog? so the same type will be converted into same type in StarRocks and won't cause confusion. Does this make sense to you?

**Review by dirtysalt — APPROVED** [review]

**Review by zombee0 — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]

**Comment by dirtysalt** [comment]
@artemklevtsov looks like line 136 is not covered, which is the most important of this PR.

**Comment by huukhuongnguyen** [comment]
I noticed that the FE has already converted UUID to VARBINARY, but it seems the BE still has this issue.
I'm getting the following error:
SQL Error [1064] [42000]: JDBC result type of column [id] is [java.util.UUID], StarRocks does not recognize it, please set the type of this column to varchar to avoid information loss.: BE:12002
I'm currently using postgresql-42.7.2.jar.

**Comment by dirtysalt** [comment]
@huukhuongnguyen can you create a issue ticket for that? 
BTW, @artemklevtsov do you have this problem?
