### PR TITLE
Capture row sets of tablet in the preparation of ScanOperawtor

### LINKED ISSUE #3689: Query error when loading data to left table at building the right table
### Steps to reproduce the behavior (Required)
The BE config:
```ini
cumulative_compaction_skip_window_seconds=1
tablet_rowset_stale_sweep_time_sec=1
# Delete the unused stale row sets as soon as possible.
min_garbage_sweep_interval=1
max_garbage_sweep_interval=1
```

1. Use tpcds_1g dataset, run the following query:
```sql
select * 
from 
  customer c 
  INNER JOIN [bucket] store_sales ss 
ON ss.ss_customer_sk=c.c_customer_sk 
```

2. When the right table is building the hash table, use stream load to load data into the table `customer` 100 times.

```bash
for i in {0..99}
do

curl --location-trusted   \
    -u root:    \
    -T customer-head.dat    \
    -H "column_separator:|"     http://<ip>:<port>/api/tpcds/customer/_stream_load

done
```

The load file `customer-head.dat` is as follows:
```
1|AAAAAAAABAAAAAAA|980124|7135|32946|2452238|2452208|Mr.|Javier|Lewis|Y|9|12|1936|CHILE|\N|Javier.Lewis@VFAxlnZEvOx.org|2452508
2|AAAAAAAACAAAAAAA|819667|1461|31655|2452318|2452288|Dr.|Amy|Moses|Y|9|4|1966|TOGO|\N|Amy.Moses@Ovk9KjHH.com|2452318
3|AAAAAAAADAAAAAAA|1473522|6247|48572|2449130|2449100|Miss|Latisha|Hamilton|N|18|9|1979|NIUE|\N|Latisha.Hamilton@V.com|2452313
4|AAAAAAAAEAAAAAAA|1703214|3986|39558|2450030|2450000|Dr.|Michael|White|N|7|6|1983|MEXICO|\N|Michael.White@i.org|2452361
5|AAAAAAAAFAAAAAAA|953372|4470|36368|2449438|2449408|Sir|Robert|Moran|N|8|5|1956|FIJI|\N|Robert.Moran@Hh.edu|2452469
6|AAAAAAAAGAAAAAAA|213219|6374|27082|2451883|2451853|Ms.|Brunilda|Sharp|N|4|12|1925|SURINAME|\N|Brunilda.Sharp@T3pylZEUQjm.org|2452430
7|AAAAAAAAHAAAAAAA|68377|3219|44814|2451438|2451408|Ms.|Fonda|Wiles|Y|24|4|1985|GAMBIA|\N|Fonda.Wiles@S9KnyEtz9hv.org|2452360
8|AAAAAAAAIAAAAAAA|1215897|2471|16598|2449406|2449376|Sir|Ollie|Shipman|N|26|12|1938|KOREA, REPUBLIC OF|\N|Ollie.Shipman@be.org|2452334
9|AAAAAAAAJAAAAAAA|1168667|1404|49388|2452275|2452245|Sir|Karl|Gilbert|N|26|10|1966|MONTSERRAT|\N|Karl.Gilbert@Crg5KyP2IxX9C4d6.edu|245245410|AAAAAAAAKAAAAAAA|1207553|5143|19580|2451353|2451323|Ms.|Albert|Brunson|N|15|10|1973|JORDAN|\N|Albert.Brunson@62.com|2452641
```

### Expected behavior (Required)
The query could output result normally.

### Real behavior (Required)
```
Cannot run query select * from customer c INNER JOIN [bucket] store_sales ss ON ss.ss_customer_sk=c.c_customer_sk 
ERROR : version already been compacted. tablet_id: 45139, version: 6263
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
1e2c9b35c052348f9780d63091bd08df50796f76

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3689.

## Problem Summary(Required) ：
The row sets of tablets will become stale and be deleted, if compaction occurs and these row sets aren't referenced, which will typically happen when the tablets of the left table are compacted at building the right hash table. 

Therefore, reference  the row sets into _tablet_rowsets in the preparation phase to avoid the row sets being deleted.

### CODE REVIEW

File: be/src/exec/pipeline/scan_operator.h [hunk 1]
```diff
@@ -58,12 +63,20 @@ class ScanOperator final : public SourceOperator {
...
     RuntimeState* _state = nullptr;
 
     bool _is_finished = false;
     int32_t _io_task_retry_cnt = 0;
 
+    // The row sets of tablets will become stale and be deleted, if compaction occurs
+    // and these row sets aren't referenced, which will typically happen when the tablets
+    // of the left table are compacted at building the right hash table. Therefore, reference
+    // the row sets into _tablet_rowsets in the preparation phase to avoid the row sets being deleted.
+    std::vector<std::vector<RowsetSharedPtr>> _tablet_rowsets;
```
Comment (kangkaisen) [inline be/src/exec/pipeline/scan_operator.h:79]: should put this code to olap scan operator.

**Comment by kangkaisen** [comment]
This pr is double capture. What's the performance effect?

File: be/src/exec/pipeline/scan_operator.cpp [hunk 2]
```diff
@@ -255,6 +259,39 @@ Status ScanOperator::_pickup_morsel(RuntimeState* state, int chunk_source_index)
     return Status::OK();
 }
 
+Status ScanOperator::_capture_tablet_rowsets() {
```
Comment (satanson) [inline be/src/exec/pipeline/scan_operator.cpp:262]: put this function into ScanOperatorFactory and invoke it in ScanOperatorFactory::prepare, would be better?

File: be/src/exec/pipeline/scan_operator.h (hunk 1 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/scan_operator.h:79]: There isn't  class `OlapScanOperator`. `ScanOperator` just  corresponds to olap scan node.

**Comment by ZiheLiu** [comment]
> This pr is double capture. What's the performance effect?

This PR double capture `RowSetPtr`, which is a `std::shared_ptr`. It will

File: be/src/exec/pipeline/scan_operator.cpp (hunk 2 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/scan_operator.cpp:262]: `ScanOperatorFactory` doesn't own morsels, and each `ScanOperator` instance has its own different morsels.

**Comment by mofeiatwork** [comment]
Sounds like a serious and fundamental bug...

File: be/src/exec/pipeline/scan_operator.h (hunk 1 above)
Comment (kangkaisen) [reply be/src/exec/pipeline/scan_operator.h:79]: OK. we need to rename `ScanOperator` to `OlapScanOperator` in next PR

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]
