### PR TITLE
[BugFix] BE blocked in starrocks::KafkaDataConsumer::get_partition_offset

### LINKED ISSUE #8947: BE blocked in `starrocks::KafkaDataConsumer::get_partition_offset`
### Steps to reproduce the behavior (Required)
1. Create routine load
2. Stop all kafka brokers

### Expected behavior (Required)
The SR runs well.

### Real behavior (Required)
The SR would become slow. Many bthreads are blocked.
```
#0  0x00007f50ff200de2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000613e9a9 in cnd_timedwait (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#2  0x000000000613ed53 in cnd_timedwait_abs (cnd=cnd@entry=0x214c76398, mtx=mtx@entry=0x214c76370, tspec=tspec@entry=0x7f4fb64ea910) at tinycthread_extra.c:106
#3  0x00000000060ec997 in rd_kafka_q_serve (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#4  0x00000000060b59ae in rd_kafka_query_watermark_offsets (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#5  0x0000000003afe143 in starrocks::KafkaDataConsumer::get_partition_offset (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#6  0x0000000003b0b91a in starrocks::RoutineLoadTaskExecutor::get_kafka_partition_offset (this=0xff8dc00, request=..., Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#7  0x0000000003b6b925 in starrocks::PInternalServiceImpl<doris::PBackendService>::get_info (this=0x1318a5e0, controller=<optimized out>, request=0x592b7bb90, response=0x1bdc2a740, done=<optimized out>) at /home/disk1/chaoyli/starrocks/be/../gensrc/build/gen_cpp/internal_service.pb.h:11970
#8  0x0000000004b5348e in brpc::policy::ProcessRpcRequest (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#9  0x0000000004b45727 in brpc::ProcessInputMessage (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#10 0x0000000004b465d3 in brpc::RunLastMessage::operator() (last_msg=0xba94200, this=<synthetic pointer>) at /home/disk2/wyb/workspace/wyb/starrocks/thirdparty/src/incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:141
#11 std::unique_ptr<brpc::InputMessageBase, brpc::RunLastMessage>::~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /home/disk1/doris-deps/toolchain/installed/gcc-10.3.0/include/c++/10.3.0/bits/unique_ptr.h:361
#12 brpc::InputMessenger::OnNewMessages (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#13 0x0000000004bfba2e in brpc::Socket::ProcessEvent (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#14 0x0000000004a91a5f in bthread::TaskGroup::task_runner (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#15 0x0000000004a7ca21 in bthread_make_fcontext ()
#16 0x0000000000000000 in ?? ()
```

### StarRocks version (Required)
main@7ee482, 2.3-rc02, 2.2.3, 2.1.8

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/8947

## Problem Summary(Required) ：

The FE gets Kafka partition offset by calling RPC of BE.`starrocks::KafkaDataConsumer::get_partition_offset` on BE queries the partition offset from kafka.
The previous implementation would block many bthreads in `starrocks::KafkaDataConsumer::get_partition_offset` when all brokers of Kafka are down, which is led by the pthread lock in librdkafka. The blocked bthread cannot be scheduled, and the other operation like query would be influenced.
This PR makes the `get_info` an asynchronised call, which is executed in the specific thread pool. In this way, the pthread lock in librdkafka would not block the bthread, and other operations would not be influenced.

### CODE REVIEW

File: be/src/service/internal_service.cpp [hunk 1]
```diff
@@ -382,6 +386,26 @@ template <typename T>
 void PInternalServiceImplBase<T>::get_info(google::protobuf::RpcController* controller, const PProxyRequest* request,
                                            PProxyResult* response, google::protobuf::Closure* done) {
     ClosureGuard closure_guard(done);
+
+    GenericCountDownLatch<bthread::Mutex, bthread::ConditionVariable> latch(1);
+
+    if (!_async_thread_pool.try_offer([&]() { _get_info_impl(request, response, &latch); })) {
+        Status::ServiceUnavailable(
```
Comment (meegoo) [inline be/src/service/internal_service.cpp:393]: BE's `routine_load_kafka_timeout_second` must recalculate as time between request finish and add to queue.
because FE also has `routine_load_kafka_timeout_second` which just little bit large then BE's config.

**Review by meegoo — CHANGES_REQUESTED** [review]

File: be/src/service/internal_service.cpp [hunk 2]
```diff
@@ -50,7 +50,11 @@ using PromiseStatus = std::promise<Status>;
 using PromiseStatusSharedPtr = std::shared_ptr<PromiseStatus>;
 
 template <typename T>
-PInternalServiceImplBase<T>::PInternalServiceImplBase(ExecEnv* exec_env) : _exec_env(exec_env) {}
+PInternalServiceImplBase<T>::PInternalServiceImplBase(ExecEnv* exec_env)
+        : _exec_env(exec_env),
+          // Now, only get_info is processed by _async_thread_pool, and only needs a small number of threads.
+          _async_thread_pool("async_thread_pool", config::internal_service_async_thread_num,
```
Comment (trueeyu) [inline be/src/service/internal_service.cpp:56]: Is the queue length a bit small?

**Review by trueeyu — DISMISSED** [review]

File: be/src/service/internal_service.cpp (hunk 1 above)
Comment (rickif) [reply be/src/service/internal_service.cpp:403]: Updated. The `get_info`'s timeout is now depend on the FE request and the interval duaring the queue waitting is counted. Besides, the timeout would be recaculated when the call consists several step.

File: be/src/service/internal_service.cpp (hunk 2 above)
Comment (rickif) [reply be/src/service/internal_service.cpp:56]: The default value of `internal_service_async_thread_num` is changed to 10.

**Review by trueeyu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|1|1|100.00%|[]|

**Comment by rickif** [comment]
@megifyio rebase

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|1|1|100.00%|[]|

File: be/src/service/internal_service.cpp [hunk 3]
```diff
@@ -382,10 +386,40 @@ template <typename T>
...
+
+    int timeout = request->has_timeout() ? request->timeout() : config::routine_load_kafka_timeout_second;
+
+    // watch estimates the interval before the task is actually executed.
+    MonotonicStopWatch watch;
+    watch.start();
+
+    if (!_async_thread_pool.try_offer([&]() {
+            watch.stop();
+            timeout -= watch.elapsed_time() / 1000 / 1000;
```
Comment (meegoo) [inline be/src/service/internal_service.cpp:400]: if timeout < 0, we can direct return timeout?

File: be/src/service/internal_service.cpp [hunk 4]
```diff
@@ -382,6 +386,26 @@ template <typename T>
 void PInternalServiceImplBase<T>::get_info(google::protobuf::RpcController* controller, const PProxyRequest* request,
                                            PProxyResult* response, google::protobuf::Closure* done) {
     ClosureGuard closure_guard(done);
+
+    GenericCountDownLatch<bthread::Mutex, bthread::ConditionVariable> latch(1);
+
+    if (!_async_thread_pool.try_offer([&]() { _get_info_impl(request, response, &latch); })) {
```
[the remark this answers is not in the document]
Comment (rickif) [reply be/src/service/internal_service.cpp]: No, the `_get_info_imple` is executed by the `_async_thread_pool` and would not block the bthread.

File: be/src/util/priority_thread_pool.hpp [hunk 5]
```diff
@@ -93,6 +93,11 @@ class PriorityThreadPool {
         return _work_queue.blocking_put(std::move(task));
     }
 
+    bool try_offer(WorkFunction func) {
```
[the remark this answers is not in the document]
Comment (rickif) [reply be/src/util/priority_thread_pool.hpp:96]: The `PriorityThreadPool::offer()` would also block the bthread when the task queue is full.

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by rickif** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 2 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/KafkaUtil.java|0|1|00.00%|[176]|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadTaskScheduler.java|1|1|100.00%|[]|

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run starrocks_be_unittest

**Comment by rickif** [comment]
run all

**Comment by rickif** [comment]
@mergifyio rebase

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Comment by rickif** [comment]
run starrocks_fe_unittest

**Review by trueeyu — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
