### PR TITLE
[Bugfix] Fix to detach chunk sources

### LINKED ISSUE #10439: [Bug] Query hang with pipeline engine
### Steps to reproduce the behavior (Required)
1. use a big table test_all_type_select0_8_buckets
2.
```
set enable_pipeline_engine = true;
set pipeline_dop = 0;
```
3. execute 
```
select count(id_int) from (select id_int from test_all_type_select0_8_buckets limit 2000000) t;
```

### Real behavior (Required)
no response. hang

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/10439

## Problem Summary(Required) ：

For sql like
```
select id_int from test_all_type_select_for_stuck limit 10000000;
```
when execute with pipeline engine and dop = 0, if a pipeline_driver's input datas is consumed, but limit is not enough(less than 10000000), so this pipeline_driver will blocked in poller queue, and it will blocked forever by shared_chunk_source.
**So we should detach chunk sources early.**
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by silverbullet233** [comment]
run starrocks_admit_test

**Review by silverbullet233 — DISMISSED** [review]

**Review by murphyatwork — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: be/src/exec/pipeline/scan/scan_operator.cpp [hunk 1]
```diff
@@ -141,7 +141,19 @@ bool ScanOperator::has_output() const {
         }
     }
 
-    return num_buffered_chunks() > 0;
+    const auto has_chunks = num_buffered_chunks() > 0;
+    // Avoid miss detach_chunk_source.
+    if (!has_chunks && _num_running_io_tasks == 0) {
```
Comment (kangkaisen) [inline be/src/exec/pipeline/scan/scan_operator.cpp:146]: why the condition is   num_buffered_chunks() == 0 && _num_running_io_tasks == 0?

**Comment by ZiheLiu** [comment]
A chunk source could be detached by io tasks or exec threads.
- When the scan operator closing, it will detach the chunk source which is not running in io task.
- When the io task finished, it will detach the chunk source if the chunk source not able to produce chunks anymore.

Therefore,

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: be/src/exec/pipeline/scan/scan_operator.cpp (hunk 1 above)
Comment (Pslydhh) [reply be/src/exec/pipeline/scan/scan_operator.cpp:146]: > why the condition is num_buffered_chunks() == 0 && _num_running_io_tasks == 0?

Because only when there is no more chunks, and there is no more io_tasks, this scan_operator's task is done, we should detach_shared_input to notic is_finished to finish.

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by ZiheLiu — APPROVED** [review]

File: be/src/exec/pipeline/scan/scan_operator.cpp (hunk 1 above)
Comment (Pslydhh) [reply be/src/exec/pipeline/scan/scan_operator.cpp]: > why the condition is num_buffered_chunks() == 0 && _num_running_io_tasks == 0?

This is unneeded, have removed.

File: be/src/exec/pipeline/scan/connector_scan_operator.cpp [hunk 2]
```diff
@@ -57,15 +57,13 @@ void ConnectorScanOperator::attach_chunk_source(int32_t source_index) {
     auto* factory = down_cast<ConnectorScanOperatorFactory*>(_factory);
     auto& active_inputs = factory->get_active_inputs();
     auto key = std::make_pair(_driver_sequence, source_index);
-    DCHECK(!active_inputs.contains(key));
```
Comment (fzhedu) [inline be/src/exec/pipeline/scan/connector_scan_operator.cpp:60]: why delete the `DCHECK`?

Comment (Pslydhh) [reply be/src/exec/pipeline/scan/connector_scan_operator.cpp:60]: Because we detach chunk source early, so may violate these constraints.

**Review by kangkaisen — APPROVED** [review]
