### PR TITLE
[BugFix] Fix time_slice function unstable result since interval type not match

### LINKED ISSUE #18450: time_slice function unstable result
### Steps to reproduce the behavior (Required)
1. CREATE TABLE
```
CREATE TABLE ss_month( event_day DATETIME, pv BIGINT) DUPLICATE KEY(event_day) PARTITION BY time_slice(event_day, interval 4 month) DISTRIBUTED BY HASH(event_day) BUCKETS 8 PROPERTIES("replication_num" = "3");
```
2. INSERT INTO '....'
```
insert into ss_month values('2023-06-14 12:31:07', 2);
```

### Expected behavior (Required)
success

### Real behavior (Required)
fail

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18450

## Problem Summary(Required) ：

`time_slice` second parameter is const int value which using IntLiteral,  IntLiteral has TINYINT/SMALLINT/INT/BIGINT type, but time_slice only support `INT` type when executed in BE

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java [hunk 1]
```diff
@@ -4717,7 +4717,13 @@ public ParseNode visitOdbcFunctionCallExpression(StarRocksParser.OdbcFunctionCal
     private static List<Expr> getArgumentsForTimeSlice(Expr time, Expr value, String ident, String boundary) {
         List<Expr> exprs = Lists.newLinkedList();
         exprs.add(time);
-        exprs.add(value);
+        // IntLiteral may generate TINYINT/SMALLINT/INT/LARGEINT
+        // but time_slice only support INT type when executed in BE
+        if (value instanceof IntLiteral) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:4722]: You‘d better test this is a const value, then test if it can be computed in Frontend.
And if the value can be cast to an intvalue.
Like time_slice(""xxxx, 1 + 1);

Comment (meegoo) [reply fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:4722]: Already check in analyzer
```
            } else if (fnName.equals(FunctionSet.TIME_SLICE) || fnName.equals(FunctionSet.DATE_SLICE)) {
                // This must before test for DecimalV3.
                if (!(node.getChild(1) instanceof IntLiteral)) {
                    throw new SemanticException(
                            fnName + " requires second parameter must be a constant interval");
                }
                if (((IntLiteral) node.getChild(1)).getValue() <= 0) {
                    throw new SemanticException(
                            fnName + " requires second parameter must be greater than 0");
                }
```

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/parser/AstBuilder.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
