### PR TITLE
bug fix: Large number handling error in conv_string function(#2930)

### LINKED ISSUE #2930: CONV函数不准确
https://forum.starrocks.com/t/topic/1256
### Steps to reproduce the behavior (Required)
mysql> select CONV(‘8ac7230489e80000’, 16, 10);
±---------------------------------+
| conv(‘8ac7230489e80000’, 16, 10) |
±---------------------------------+
| 18446744073709551615 |
±---------------------------------+
1 row in set (0.01 sec)
实际结果应为：
image

测试下来发现，16进制转为10进制 ，大于10^18次方后 就不准确了，如上

### StarRocks version (Required)
1.19.5

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #2930;

## Problem Summary(Required) ：

I  found some problems with the current implementation of `conv_int/conv_string` function:
1. Incorrect handling of negative src_base in both `conv_int` and `conv_string`:  if the number is greater than 0 and src_base is nagative, it will return NULL directly which is expected to be an integer. For example, `conv(10, -2, 10)=NULL(but 2 is expected)`
2. Incorrent handle of large number: when the number is too large, error result will return. For example, `conv(99999999, 16, 10)=18446744073709551615(but 2576980377 is expected)`, `conv('8ac7230489e80000', 16, 10)=18446744073709551615(but 10000000000000000000 is expected)`;
3. Incompatibility with MySQL on overflow, For example, `conv('-18446744073709551616', 10, 10)=18446744073709551615(but 0 is expected)`,`conv('-18446744073709551616', 10, -10)=-1(but 0 is expected)`

In this PR, I have fixed correctness and compatibility issues to make it behave closer to MySQL.

### CODE REVIEW

File: be/src/exprs/vectorized/math_functions.cpp [hunk 1]
```diff
@@ -441,20 +441,23 @@ ColumnPtr MathFunctions::conv_string(FunctionContext* context, const starrocks::
...
-
         if (src_base_value < 0 && decimal_num >= 0) {
             result.append_null();
             continue;
         }
-
-        if (!handle_parse_result(dest_base_value, &decimal_num, parse_res)) {
+        int64_t decimal64_num = static_cast<int64_t>(decimal_num);
+        // recheck overflow
+        if (parse_res == StringParser::PARSE_SUCCESS && decimal_num > std::numeric_limits<uint64_t>::max()) {
```
Comment (liuyehcf) [inline be/src/exprs/vectorized/math_functions.cpp:452]: Why use `std::numeric_limits<uint64_t>::max()` but not `std::numeric_limits<int64_t>::max()`

Comment (silverbullet233) [reply be/src/exprs/vectorized/math_functions.cpp:452]: According to the description of [mysql doc](https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html#function_conv), input value can be treated as unsigned if src_base is positive number, so we can't simply judge a value in range[INT64_MAX,UINT64_MAX] as overflow.

**Review by liuyehcf — DISMISSED** [review]

File: be/src/exprs/vectorized/math_functions.cpp [hunk 2]
```diff
@@ -441,20 +441,23 @@ ColumnPtr MathFunctions::conv_string(FunctionContext* context, const starrocks::
         }
 
         StringParser::ParseResult parse_res;
-        int64_t decimal_num = StringParser::string_to_int<int64_t>(reinterpret_cast<char*>(string_value.data),
+        int128_t decimal_num = StringParser::string_to_int<int128_t>(reinterpret_cast<char*>(string_value.data),
                                                                    string_value.size, src_base_value, &parse_res);
-
         if (src_base_value < 0 && decimal_num >= 0) {
             result.append_null();
             continue;
```
Comment (ZiheLiu) [inline be/src/exprs/vectorized/math_functions.cpp:448]: Why this condition returns `null`? `decimal_num` is a signed number when `src_base_value` is negative, so maybe `decimal_num >= 0`  is legal?

File: be/src/exprs/vectorized/math_functions.cpp (hunk 1 above)
Comment (ZiheLiu) [reply be/src/exprs/vectorized/math_functions.cpp:452]: @silverbullet233 Could we judge `dest_base_value > 0 && decimal_num > std::numeric_limits<uint64_t>::max() || dest_base_value < 0 && decimal_num > std::numeric_limits<int64_t>::max()`?

File: be/src/exprs/vectorized/math_functions.cpp (hunk 2 above)
Comment (silverbullet233) [reply be/src/exprs/vectorized/math_functions.cpp:442]: This condition seems unreasonable and will cause the results to be inconsistent with MySQL, I have fixed it @ZiheLiu

**Comment by silverbullet233** [comment]
I have updated my change, fixed more correctness and compatibility issues, you can see more details in the description, plz review again, thx~ @liuyehcf @ZiheLiu

File: be/src/exprs/vectorized/math_functions.cpp [hunk 3]
```diff
@@ -439,22 +434,46 @@ ColumnPtr MathFunctions::conv_string(FunctionContext* context, const starrocks::
...
+        if (parse_res == StringParser::PARSE_SUCCESS) {
+            if (is_signed) {
+                if (negative && decimal64_num > 0ull - std::numeric_limits<int64_t>::min()) {
+                    decimal64_num = 0ull - std::numeric_limits<int64_t>::min();
+                }
+                if (!negative && decimal64_num > std::numeric_limits<int64_t>::max()) {
+                    decimal64_num = std::numeric_limits<int64_t>::max();
+                }
+            }
+        } else if (parse_res == StringParser::PARSE_FAILURE) {
```
Comment (liuyehcf) [inline be/src/exprs/vectorized/math_functions.cpp:459]: Could this branch merge with the branch `else if (parse_res == StringParser::PARSE_OVERFLOW)` if type of decimal64_num is `int64_t`?

**Review by ZiheLiu — APPROVED** [review]

File: be/src/exprs/vectorized/math_functions.cpp (hunk 3 above)
Comment (silverbullet233) [reply be/src/exprs/vectorized/math_functions.cpp:459]: Yes, these two branches are both dealing with the overflow problem, but merging them will not make the implementation more concise because we can't merge the overflow check condition, so I'd prefer to keep the status quo. what do you think? @liuyehcf

**Review by liuyehcf — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by satanson — APPROVED** [review]
