### PR TITLE
[BugFix] fix #6319: dangling pointer at chunk_source

### LINKED ISSUE #6316: [sqlancer] BE crash
### Steps to reproduce the behavior (Required)
I will add it here after I find reproduced sql

### Expected behavior (Required)
Query returns correctly

### Real behavior (Required)
```
start time: Sun May 15 23:35:25 CST 2022
==130805==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fdaecc6b900; bottom 0x7fdabcd11000; size: 0x00002ff5a900
 (804628736)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189
=================================================================
==130805==ERROR: AddressSanitizer: heap-use-after-free on address 0x6020000afed4 at pc 0x0000056d2654 bp 0x7ffd8a5d57d0 sp 0x7ffd8a5d57c8
WRITE of size 4 at 0x6020000afed4 thread T0
start time: Mon May 16 00:36:35 CST 2022
    #0 0x56d2653 in std::__atomic_base<int>::operator-=(int) /usr/include/c++/10.3.0/bits/atomic_base.h:350
    #1 0x6f1cfef in starrocks::pipeline::DriverLimiter::Token::~Token() /root/starrocks/be/src/exec/pipeline/driver_limiter.h:19
    #2 0x6f2e9e1 in std::default_delete<starrocks::pipeline::DriverLimiter::Token>::operator()(starrocks::pipeline::DriverLimiter::Token*) co
nst /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #3 0x6f2745e in std::unique_ptr<starrocks::pipeline::DriverLimiter::Token, std::default_delete<starrocks::pipeline::DriverLimiter::Token>
 >::~unique_ptr() /usr/include/c++/10.3.0/bits/unique_ptr.h:361
    #4 0x6f22052 in starrocks::pipeline::FragmentContext::~FragmentContext() /root/starrocks/be/src/exec/pipeline/fragment_context.h:33
    #5 0x6f3020d in std::default_delete<starrocks::pipeline::FragmentContext>::operator()(starrocks::pipeline::FragmentContext*) const /usr/i
nclude/c++/10.3.0/bits/unique_ptr.h:85
    #6 0x6f4ec98 in std::_Sp_counted_deleter<starrocks::pipeline::FragmentContext*, std::default_delete<starrocks::pipeline::FragmentContext>
, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:474
    #7 0x4314e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #8 0x4311daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #9 0x55c7d5d in std::__shared_ptr<starrocks::pipeline::FragmentContext, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.
3.0/bits/shared_ptr_base.h:1183
    #10 0x55c7d79 in std::shared_ptr<starrocks::pipeline::FragmentContext>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #11 0x7026f55 in std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >::~pair() /usr/include/c++/
10.3.0/bits/stl_pair.h:211
    #12 0x7026f81 in void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks:
:pipeline::FragmentContext> >, true> >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >
 >(std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #13 0x7026a3b in void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >(std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> >&, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #14 0x7026102 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2053
    #15 0x703088b in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::_M_deallocate_nodes(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2075
    #16 0x702f039 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear() /usr/include/c++/10.3.0/bits/hashtable.h:2030
    #17 0x702de8b in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() /usr/include/c++/10.3.0/bits/hashtable.h:1387
    #18 0x702dd13 in std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::FragmentContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > > >::~unordered_map() /usr/include/c++/10.3.0/bits/unordered_map.h:102
    #19 0x702f1bf in starrocks::pipeline::FragmentContextManager::~FragmentContextManager() /root/starrocks/be/src/exec/pipeline/fragment_context.h:155
    #20 0x702f1e5 in std::default_delete<starrocks::pipeline::FragmentContextManager>::operator()(starrocks::pipeline::FragmentContextManager*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #21 0x702f295 in std::__uniq_ptr_impl<starrocks::pipeline::FragmentContextManager, std::default_delete<starrocks::pipeline::FragmentContextManager> >::reset(starrocks::pipeline::FragmentContextManager*) /usr/include/c++/10.3.0/bits/unique_ptr.h:182
    #22 0x702e11a in std::unique_ptr<starrocks::pipeline::FragmentContextManager, std::default_delete<starrocks::pipeline::FragmentContextManager> >::reset(starrocks::pipeline::FragmentContextManager*) /usr/include/c++/10.3.0/bits/unique_ptr.h:456
    #23 0x7028579 in starrocks::pipeline::QueryContext::~QueryContext() /root/starrocks/be/src/exec/pipeline/query_context.cpp:31
    #24 0x703728f in void __gnu_cxx::new_allocator<starrocks::pipeline::QueryContext>::destroy<starrocks::pipeline::QueryContext>(starrocks::pipeline::QueryContext*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #25 0x7037218 in void std::allocator_traits<std::allocator<starrocks::pipeline::QueryContext> >::destroy<starrocks::pipeline::QueryContext>(std::allocator<starrocks::pipeline::QueryContext>&, starrocks::pipeline::QueryContext*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #26 0x703701a in std::_Sp_counted_ptr_inplace<starrocks::pipeline::QueryContext, std::allocator<starrocks::pipeline::QueryContext>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #27 0x4314e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #28 0x4311daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #29 0x55c7433 in std::__shared_ptr<starrocks::pipeline::QueryContext, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #30 0x55c744f in std::shared_ptr<starrocks::pipeline::QueryContext>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #31 0x7035ccb in std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >::~pair() /usr/include/c++/10.3.0/bits/stl_pair.h:211
    #32 0x7035cf7 in void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >(std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #33 0x703519a in void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> > >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >(std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> >&, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #34 0x7033fac in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2053
    #35 0x7036323 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> > >::_M_deallocate_nodes(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2075
    #36 0x7035b0d in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear() /usr/include/c++/10.3.0/bits/hashtable.h:2030
    #37 0x7034f85 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() /usr/include/c++/10.3.0/bits/hashtable.h:1387
    #38 0x70339d5 in std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >::~unordered_map() /usr/include/c++/10.3.0/bits/unordered_map.h:102
    #39 0x70339f0 in void std::_Destroy<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > > >(std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #40 0x7032393 in void std::_Destroy_aux<false>::__destroy<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*>(std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*, std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #41 0x7030d7a in void std::_Destroy<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*>(std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*, std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #42 0x702f676 in void std::_Destroy<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*, std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > > >(std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*, std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*, std::allocator<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > > >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #43 0x7030814 in std::vector<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >, std::allocator<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > > > >::_M_erase_at_end(std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >*) /usr/include/c++/10.3.0/bits/stl_vector.h:1796
    #44 0x702eff4 in std::vector<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >, std::allocator<std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > > > >::clear() /usr/include/c++/10.3.0/bits/stl_vector.h:1499
    #45 0x702bd25 in starrocks::pipeline::QueryContextManager::clear() /root/starrocks/be/src/exec/pipeline/query_context.cpp:257
    #46 0x702a915 in starrocks::pipeline::QueryContextManager::~QueryContextManager() /root/starrocks/be/src/exec/pipeline/query_context.cpp:143
    #47 0x545b5eb in starrocks::ExecEnv::_destroy() /root/starrocks/be/src/runtime/exec_env.cpp:468
    #48 0x545baa7 in starrocks::ExecEnv::destroy(starrocks::ExecEnv*) /root/starrocks/be/src/runtime/exec_env.cpp:507
    #49 0x4308021 in main /root/starrocks/be/src/service/starrocks_main.cpp:302
    #50 0x7fdba2271504 in __libc_start_main (/lib64/libc.so.6+0x22504)
    #51 0x423f48d  (/home/disk1/sr/sqlancer_branch_asan/be/lib/starrocks_be+0x423f48d)

0x6020000afed4 is located 4 bytes inside of 8-byte region [0x6020000afed0,0x6020000afed8)
freed by thread T0 here:
    #0 0x42c7a97 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x545aa3d in starrocks::ExecEnv::_destroy() /root/starrocks/be/src/runtime/exec_env.cpp:386
    #2 0x545baa7 in starrocks::ExecEnv::destroy(starrocks::ExecEnv*) /root/starrocks/be/src/runtime/exec_env.cpp:507
    #3 0x4308021 in main /root/starrocks/be/src/service/starrocks_main.cpp:302
    #4 0x7fdba2271504 in __libc_start_main (/lib64/libc.so.6+0x22504)

previously allocated by thread T0 here:
    #0 0x42c6c77 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x5454f3a in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:181
    #2 0x54533d7 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:123
    #3 0x4306c2b in main /root/starrocks/be/src/service/starrocks_main.cpp:214
    #4 0x7fdba2271504 in __libc_start_main (/lib64/libc.so.6+0x22504)

SUMMARY: AddressSanitizer: heap-use-after-free /usr/include/c++/10.3.0/bits/atomic_base.h:350 in std::__atomic_base<int>::operator-=(int)
Shadow bytes around the buggy address:
  0x0c048000df80: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048000df90: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fa fa
  0x0c048000dfa0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048000dfb0: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c048000dfc0: fa fa fd fd fa fa fa fa fa fa fd fd fa fa fd fd
=>0x0c048000dfd0: fa fa fd fa fa fa fd fd fa fa[fd]fa fa fa fd fd
  0x0c048000dfe0: fa fa fd fa fa fa fd fd fa fa fa fa fa fa fa fa
  0x0c048000dff0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000e000: fa fa fd fd fa fa fd fd fa fa fa fa fa fa fa fa
  0x0c048000e010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c048000e020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==130805==ABORTING
start time: Mon May 16 23:46:25 CST 2022
*** Check failure stack trace: ***
    @          0x9f838ad  google::LogMessage::Fail()
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
BRANCH-2.2-ASAN-6d46266

### LINKED ISSUE #6319: [sqlancer] BE crash
### Steps to reproduce the behavior (Required)
I will add it here after I find reproduced sql

```
=================================================================
==30199==ERROR: AddressSanitizer: heap-use-after-free on address 0x60b00441c710 at pc 0x000005249e25 bp 0x7f9d05983680 sp 0x7f9d05983678
READ of size 8 at 0x60b00441c710 thread T249 (pip_executor)
    #0 0x5249e24 in operator() /root/starrocks/be/src/storage/vectorized/column_expr_predicate.cpp:229
    #1 0x524bbe5 in ~DeferOp /root/starrocks/be/src/util/defer_op.h:35
    #2 0x524b87b in operator() /root/starrocks/be/src/common/object_pool.h:49
    #3 0x524b8ac in _FUN /root/starrocks/be/src/common/object_pool.h:49
    #4 0x48892c9 in starrocks::ObjectPool::clear() /root/starrocks/be/src/common/object_pool.h:56
    #5 0x4aacfd6 in starrocks::vectorized::TabletReader::close() /root/starrocks/be/src/storage/vectorized/tablet_reader.cpp:51
    #6 0x4a83618 in starrocks::vectorized::TabletReader::~TabletReader() /root/starrocks/be/src/storage/vectorized/tablet_reader.h:26
    #7 0x72ed497 in void __gnu_cxx::new_allocator<starrocks::vectorized::TabletReader>::destroy<starrocks::vectorized::TabletReader>(starrocks::vectorized::TabletReader*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #8 0x72ed46a in void std::allocator_traits<std::allocator<starrocks::vectorized::TabletReader> >::destroy<starrocks::vectorized::TabletReader>(std::allocator<starrocks::vectorized::TabletReader>&, starrocks::vectorized::TabletReader*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #9 0x72ed288 in std::_Sp_counted_ptr_inplace<starrocks::vectorized::TabletReader, std::allocator<starrocks::vectorized::TabletReader>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #10 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #11 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #12 0x6fb9561 in std::__shared_ptr<starrocks::vectorized::TabletReader, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #13 0x6fb957d in std::shared_ptr<starrocks::vectorized::TabletReader>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #14 0x6fb9614 in starrocks::pipeline::OlapChunkSource::~OlapChunkSource() /root/starrocks/be/src/exec/pipeline/olap_chunk_source.h:36
    #15 0x6fb9753 in void __gnu_cxx::new_allocator<starrocks::pipeline::OlapChunkSource>::destroy<starrocks::pipeline::OlapChunkSource>(starrocks::pipeline::OlapChunkSource*) (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6fb9753)
    #16 0x6fb94f4 in void std::allocator_traits<std::allocator<starrocks::pipeline::OlapChunkSource> >::destroy<starrocks::pipeline::OlapChunkSource>(std::allocator<starrocks::pipeline::OlapChunkSource>&, starrocks::pipeline::OlapChunkSource*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #17 0x6fb90b2 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::OlapChunkSource, std::allocator<starrocks::pipeline::OlapChunkSource>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #18 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #19 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #20 0x6faeea9 in std::__shared_ptr<starrocks::pipeline::ChunkSource, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #21 0x6faeec5 in std::shared_ptr<starrocks::pipeline::ChunkSource>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #22 0x6fb2c40 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource> >(std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #23 0x6fb27a9 in void std::_Destroy_aux<false>::__destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*>(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #24 0x6fb1f36 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*>(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #25 0x6fb0c6e in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource> >(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::allocator<std::shared_ptr<starrocks::pipeline::ChunkSource> >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #26 0x6faf759 in std::vector<std::shared_ptr<starrocks::pipeline::ChunkSource>, std::allocator<std::shared_ptr<starrocks::pipeline::ChunkSource> > >::~vector() /usr/include/c++/10.3.0/bits/stl_vector.h:680
    #27 0x6fb686c in starrocks::pipeline::ScanOperator::~ScanOperator() /root/starrocks/be/src/exec/pipeline/scan_operator.h:20
    #28 0x6fb8f50 in starrocks::pipeline::OlapScanOperator::~OlapScanOperator() /root/starrocks/be/src/exec/pipeline/olap_scan_operator.h:33
    #29 0x6fb9781 in void __gnu_cxx::new_allocator<starrocks::pipeline::OlapScanOperator>::destroy<starrocks::pipeline::OlapScanOperator>(starrocks::pipeline::OlapScanOperator*) (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6fb9781)
    #30 0x6fb9534 in void std::allocator_traits<std::allocator<starrocks::pipeline::OlapScanOperator> >::destroy<starrocks::pipeline::OlapScanOperator>(std::allocator<starrocks::pipeline::OlapScanOperator>&, starrocks::pipeline::OlapScanOperator*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #31 0x6fb9312 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::OlapScanOperator, std::allocator<starrocks::pipeline::OlapScanOperator>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #32 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #33 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #34 0x6f2a7b3 in std::__shared_ptr<starrocks::pipeline::Operator, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #35 0x6f2a7cf in std::shared_ptr<starrocks::pipeline::Operator>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #36 0x6f47522 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::Operator> >(std::shared_ptr<starrocks::pipeline::Operator>*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #37 0x6f43fd3 in void std::_Destroy_aux<false>::__destroy<std::shared_ptr<starrocks::pipeline::Operator>*>(std::shared_ptr<starrocks::pipeline::Operator>*, std::shared_ptr<starrocks::pipeline::Operator>*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #38 0x6f3fd47 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::Operator>*>(std::shared_ptr<starrocks::pipeline::Operator>*, std::shared_ptr<starrocks::pipeline::Operator>*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #39 0x6f38f8a in void std::_Destroy<std::shared_ptr<starrocks::pipeline::Operator>*, std::shared_ptr<starrocks::pipeline::Operator> >(std::shared_ptr<starrocks::pipeline::Operator>*, std::shared_ptr<starrocks::pipeline::Operator>*, std::allocator<std::shared_ptr<starrocks::pipeline::Operator> >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #40 0x6f31a77 in std::vector<std::shared_ptr<starrocks::pipeline::Operator>, std::allocator<std::shared_ptr<starrocks::pipeline::Operator> > >::~vector() /usr/include/c++/10.3.0/bits/stl_vector.h:680
    #41 0x7013ad8 in starrocks::pipeline::PipelineDriver::~PipelineDriver() /root/starrocks/be/src/exec/pipeline/pipeline_driver.cpp:18
    #42 0x6f5b73f in void __gnu_cxx::new_allocator<starrocks::pipeline::PipelineDriver>::destroy<starrocks::pipeline::PipelineDriver>(starrocks::pipeline::PipelineDriver*) (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6f5b73f)
    #43 0x6f5afea in void std::allocator_traits<std::allocator<starrocks::pipeline::PipelineDriver> >::destroy<starrocks::pipeline::PipelineDriver>(std::allocator<starrocks::pipeline::PipelineDriver>&, starrocks::pipeline::PipelineDriver*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #44 0x6f5a6e0 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::PipelineDriver, std::allocator<starrocks::pipeline::PipelineDriver>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6f5a6e0)
    #45 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #46 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #47 0x6f2d41b in std::__shared_ptr<starrocks::pipeline::PipelineDriver, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #48 0x6f2d437 in std::shared_ptr<starrocks::pipeline::PipelineDriver>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #49 0x6f4877a in void std::_Destroy<std::shared_ptr<starrocks::pipeline::PipelineDriver> >(std::shared_ptr<starrocks::pipeline::PipelineDriver>*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #50 0x6f44acd in void std::_Destroy_aux<false>::__destroy<std::shared_ptr<starrocks::pipeline::PipelineDriver>*>(std::shared_ptr<starrocks::pipeline::PipelineDriver>*, std::shared_ptr<starrocks::pipeline::PipelineDriver>*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #51 0x6f40e0d in void std::_Destroy<std::shared_ptr<starrocks::pipeline::PipelineDriver>*>(std::shared_ptr<starrocks::pipeline::PipelineDriver>*, std::shared_ptr<starrocks::pipeline::PipelineDriver>*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #52 0x6f3a8a4 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::PipelineDriver>*, std::shared_ptr<starrocks::pipeline::PipelineDriver> >(std::shared_ptr<starrocks::pipeline::PipelineDriver>*, std::shared_ptr<starrocks::pipeline::PipelineDriver>*, std::allocator<std::shared_ptr<starrocks::pipeline::PipelineDriver> >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #53 0x6f3ab69 in std::vector<std::shared_ptr<starrocks::pipeline::PipelineDriver>, std::allocator<std::shared_ptr<starrocks::pipeline::PipelineDriver> > >::_M_erase_at_end(std::shared_ptr<starrocks::pipeline::PipelineDriver>*) /usr/include/c++/10.3.0/bits/stl_vector.h:1796
    #54 0x6f33530 in std::vector<std::shared_ptr<starrocks::pipeline::PipelineDriver>, std::allocator<std::shared_ptr<starrocks::pipeline::PipelineDriver> > >::clear() /usr/include/c++/10.3.0/bits/stl_vector.h:1499
    #55 0x6f2dbf0 in starrocks::pipeline::FragmentContext::~FragmentContext() /root/starrocks/be/src/exec/pipeline/fragment_context.h:35
    #56 0x6f3bec5 in std::default_delete<starrocks::pipeline::FragmentContext>::operator()(starrocks::pipeline::FragmentContext*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #57 0x6f5a950 in std::_Sp_counted_deleter<starrocks::pipeline::FragmentContext*, std::default_delete<starrocks::pipeline::FragmentContext>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:474
    #58 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #59 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #60 0x55cd677 in std::__shared_ptr<starrocks::pipeline::FragmentContext, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #61 0x55cd693 in std::shared_ptr<starrocks::pipeline::FragmentContext>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #62 0x7032e13 in std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >::~pair() /usr/include/c++/10.3.0/bits/stl_pair.h:211
    #63 0x7032e3f in void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >(std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #64 0x70328f9 in void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >(std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> >&, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #65 0x7031fc0 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2053
    #66 0x703c749 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true> > >::_M_deallocate_nodes(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2075
    #67 0x703aef7 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear() /usr/include/c++/10.3.0/bits/hashtable.h:2030
    #68 0x7039d49 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable() /usr/include/c++/10.3.0/bits/hashtable.h:1387
    #69 0x7039bd1 in std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::FragmentContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::FragmentContext> > > >::~unordered_map() /usr/include/c++/10.3.0/bits/unordered_map.h:102
    #70 0x703b07d in starrocks::pipeline::FragmentContextManager::~FragmentContextManager() /root/starrocks/be/src/exec/pipeline/fragment_context.h:155
    #71 0x703b0a3 in std::default_delete<starrocks::pipeline::FragmentContextManager>::operator()(starrocks::pipeline::FragmentContextManager*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #72 0x703b153 in std::__uniq_ptr_impl<starrocks::pipeline::FragmentContextManager, std::default_delete<starrocks::pipeline::FragmentContextManager> >::reset(starrocks::pipeline::FragmentContextManager*) /usr/include/c++/10.3.0/bits/unique_ptr.h:182
    #73 0x7039fd8 in std::unique_ptr<starrocks::pipeline::FragmentContextManager, std::default_delete<starrocks::pipeline::FragmentContextManager> >::reset(starrocks::pipeline::FragmentContextManager*) /usr/include/c++/10.3.0/bits/unique_ptr.h:456
    #74 0x7034437 in starrocks::pipeline::QueryContext::~QueryContext() /root/starrocks/be/src/exec/pipeline/query_context.cpp:31
    #75 0x704314d in void __gnu_cxx::new_allocator<starrocks::pipeline::QueryContext>::destroy<starrocks::pipeline::QueryContext>(starrocks::pipeline::QueryContext*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #76 0x70430d6 in void std::allocator_traits<std::allocator<starrocks::pipeline::QueryContext> >::destroy<starrocks::pipeline::QueryContext>(std::allocator<starrocks::pipeline::QueryContext>&, starrocks::pipeline::QueryContext*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #77 0x7042ed8 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::QueryContext, std::allocator<starrocks::pipeline::QueryContext>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #78 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #79 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #80 0x55ccd4d in std::__shared_ptr<starrocks::pipeline::QueryContext, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #81 0x55ccd69 in std::shared_ptr<starrocks::pipeline::QueryContext>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #82 0x7041b89 in std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >::~pair() /usr/include/c++/10.3.0/bits/stl_pair.h:211
    #83 0x7041bb5 in void __gnu_cxx::new_allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >(std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >*) /usr/include/c++/10.3.0/ext/new_allocator.h:156
    #84 0x7041058 in void std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> > >::destroy<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >(std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> >&, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #85 0x703fe6a in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true> > >::_M_deallocate_node(std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable_policy.h:2053
    #86 0x703e818 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_erase(unsigned long, std::__detail::_Hash_node_base*, std::__detail::_Hash_node<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, true>*) /usr/include/c++/10.3.0/bits/hashtable.h:1888
    #87 0x703cf13 in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::erase(std::__detail::_Node_const_iterator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, false, true>) /usr/include/c++/10.3.0/bits/hashtable.h:1863
    #88 0x703b88c in std::_Hashtable<starrocks::TUniqueId, std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > >, std::__detail::_Select1st, std::equal_to<starrocks::TUniqueId>, std::hash<starrocks::TUniqueId>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::erase(std::__detail::_Node_iterator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, false, true>) /usr/include/c++/10.3.0/bits/hashtable.h:807
    #89 0x703a64e in std::unordered_map<starrocks::TUniqueId, std::shared_ptr<starrocks::pipeline::QueryContext>, std::hash<starrocks::TUniqueId>, std::equal_to<starrocks::TUniqueId>, std::allocator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> > > >::erase(std::__detail::_Node_iterator<std::pair<starrocks::TUniqueId const, std::shared_ptr<starrocks::pipeline::QueryContext> >, false, true>) /usr/include/c++/10.3.0/bits/unordered_map.h:797
    #90 0x70378d1 in starrocks::pipeline::QueryContextManager::remove(starrocks::TUniqueId const&) /root/starrocks/be/src/exec/pipeline/query_context.cpp:239
    #91 0x701b271 in starrocks::pipeline::PipelineDriver::finalize(starrocks::RuntimeState*, starrocks::pipeline::DriverState) /root/starrocks/be/src/exec/pipeline/pipeline_driver.cpp:319
    #92 0x6fe8b99 in starrocks::pipeline::GlobalDriverExecutor::_finalize_driver(starrocks::pipeline::PipelineDriver*, starrocks::RuntimeState*, starrocks::pipeline::DriverState) /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:73
    #93 0x6fe917f in starrocks::pipeline::GlobalDriverExecutor::_worker_thread() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:111
    #94 0x6fe808d in operator() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:57
    #95 0x6fefc59 in __invoke_impl<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:60
    #96 0x6fef358 in __invoke_r<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:110
    #97 0x6fee78a in _M_invoke /usr/include/c++/10.3.0/bits/std_function.h:291
    #98 0x433f4c1 in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #99 0x59663cd in starrocks::FunctionRunnable::run() /root/starrocks/be/src/util/threadpool.cpp:45
    #100 0x5962f01 in starrocks::ThreadPool::dispatch_thread() /root/starrocks/be/src/util/threadpool.cpp:514
    #101 0x59804f5 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:73
    #102 0x597fdd8 in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:95
    #103 0x597f1ef in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/include/c++/10.3.0/functional:416
    #104 0x597dd5b in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /usr/include/c++/10.3.0/functional:499
    #105 0x597ac41 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:60
    #106 0x5978c09 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:110
    #107 0x59743a4 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /usr/include/c++/10.3.0/bits/std_function.h:291
    #108 0x433f4c1 in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #109 0x594d484 in starrocks::Thread::supervise_thread(void*) /root/starrocks/be/src/util/thread.cpp:327
    #110 0x7f9d70125e64 in start_thread (/lib64/libpthread.so.0+0x7e64)
    #111 0x7f9d6f74088c in clone (/lib64/libc.so.6+0xfe88c)

0x60b00441c710 is located 32 bytes inside of 104-byte region [0x60b00441c6f0,0x60b00441c758)
freed by thread T249 (pip_executor) here:
    #0 0x42cca97 in operator delete(void*, unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:172
    #1 0x52464be in starrocks::vectorized::ColumnExprPredicate::~ColumnExprPredicate() /root/starrocks/be/src/storage/vectorized/column_expr_predicate.cpp:31
    #2 0x67eccca in std::default_delete<starrocks::vectorized::ColumnPredicate>::operator()(starrocks::vectorized::ColumnPredicate*) const /usr/include/c++/10.3.0/bits/unique_ptr.h:85
    #3 0x67de9a6 in std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >::~unique_ptr() /usr/include/c++/10.3.0/bits/unique_ptr.h:361
    #4 0x6fb998a in void std::_Destroy<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> > >(std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #5 0x6fb9968 in void std::_Destroy_aux<false>::__destroy<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*>(std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*, std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #6 0x6fb992b in void std::_Destroy<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*>(std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*, std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #7 0x6fb98e9 in void std::_Destroy<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*, std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> > >(std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*, std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >*, std::allocator<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> > >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #8 0x6fb9803 in std::vector<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >, std::allocator<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> > > >::~vector() /usr/include/c++/10.3.0/bits/stl_vector.h:680
    #9 0x6fb95de in starrocks::pipeline::OlapChunkSource::~OlapChunkSource() /root/starrocks/be/src/exec/pipeline/olap_chunk_source.h:36
    #10 0x6fb9753 in void __gnu_cxx::new_allocator<starrocks::pipeline::OlapChunkSource>::destroy<starrocks::pipeline::OlapChunkSource>(starrocks::pipeline::OlapChunkSource*) (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6fb9753)
    #11 0x6fb94f4 in void std::allocator_traits<std::allocator<starrocks::pipeline::OlapChunkSource> >::destroy<starrocks::pipeline::OlapChunkSource>(std::allocator<starrocks::pipeline::OlapChunkSource>&, starrocks::pipeline::OlapChunkSource*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #12 0x6fb90b2 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::OlapChunkSource, std::allocator<starrocks::pipeline::OlapChunkSource>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #13 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #14 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #15 0x6faeea9 in std::__shared_ptr<starrocks::pipeline::ChunkSource, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183
    #16 0x6faeec5 in std::shared_ptr<starrocks::pipeline::ChunkSource>::~shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr.h:121
    #17 0x6fb2c40 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource> >(std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:140
    #18 0x6fb27a9 in void std::_Destroy_aux<false>::__destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*>(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:152
    #19 0x6fb1f36 in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*>(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*) /usr/include/c++/10.3.0/bits/stl_construct.h:185
    #20 0x6fb0c6e in void std::_Destroy<std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource> >(std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::shared_ptr<starrocks::pipeline::ChunkSource>*, std::allocator<std::shared_ptr<starrocks::pipeline::ChunkSource> >&) /usr/include/c++/10.3.0/bits/alloc_traits.h:738
    #21 0x6faf759 in std::vector<std::shared_ptr<starrocks::pipeline::ChunkSource>, std::allocator<std::shared_ptr<starrocks::pipeline::ChunkSource> > >::~vector() /usr/include/c++/10.3.0/bits/stl_vector.h:680
    #22 0x6fb686c in starrocks::pipeline::ScanOperator::~ScanOperator() /root/starrocks/be/src/exec/pipeline/scan_operator.h:20
    #23 0x6fb8f50 in starrocks::pipeline::OlapScanOperator::~OlapScanOperator() /root/starrocks/be/src/exec/pipeline/olap_scan_operator.h:33
    #24 0x6fb9781 in void __gnu_cxx::new_allocator<starrocks::pipeline::OlapScanOperator>::destroy<starrocks::pipeline::OlapScanOperator>(starrocks::pipeline::OlapScanOperator*) (/home/disk1/sr/sqlancer_master_asan/be/lib/starrocks_be+0x6fb9781)
    #25 0x6fb9534 in void std::allocator_traits<std::allocator<starrocks::pipeline::OlapScanOperator> >::destroy<starrocks::pipeline::OlapScanOperator>(std::allocator<starrocks::pipeline::OlapScanOperator>&, starrocks::pipeline::OlapScanOperator*) /usr/include/c++/10.3.0/bits/alloc_traits.h:531
    #26 0x6fb9312 in std::_Sp_counted_ptr_inplace<starrocks::pipeline::OlapScanOperator, std::allocator<starrocks::pipeline::OlapScanOperator>, (__gnu_cxx::_Lock_policy)2>::_M_dispose() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:560
    #27 0x4319e40 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:158
    #28 0x4316daf in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:733
    #29 0x6f2a7b3 in std::__shared_ptr<starrocks::pipeline::Operator, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr() /usr/include/c++/10.3.0/bits/shared_ptr_base.h:1183

previously allocated by thread T243 (pip_executor) here:
    #0 0x42cbc77 in operator new(unsigned long) ../../.././libsanitizer/asan/asan_new_delete.cpp:99
    #1 0x527af00 in starrocks::vectorized::PredicateParser::parse_expr_ctx(starrocks::SlotDescriptor const&, starrocks::RuntimeState*, starrocks::ExprContext*) const /root/starrocks/be/src/storage/vectorized/predicate_parser.cpp:76
    #2 0x67b5078 in starrocks::vectorized::OlapScanConjunctsManager::get_column_predicates(starrocks::vectorized::PredicateParser*, std::vector<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> >, std::allocator<std::unique_ptr<starrocks::vectorized::ColumnPredicate, std::default_delete<starrocks::vectorized::ColumnPredicate> > > >*) /root/starrocks/be/src/exec/vectorized/olap_scan_prepare.cpp:643
    #3 0x74b8965 in starrocks::pipeline::OlapChunkSource::_init_reader_params(std::vector<starrocks::OlapScanRange*, std::allocator<starrocks::OlapScanRange*> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&, std::vector<unsigned int, std::allocator<unsigned int> >&) /root/starrocks/be/src/exec/pipeline/olap_chunk_source.cpp:194
    #4 0x74bb39a in starrocks::pipeline::OlapChunkSource::_init_olap_reader(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/olap_chunk_source.cpp:292
    #5 0x74b2b86 in starrocks::pipeline::OlapChunkSource::prepare(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/olap_chunk_source.cpp:80
    #6 0x6faaf18 in starrocks::pipeline::ScanOperator::_pickup_morsel(starrocks::RuntimeState*, int) /root/starrocks/be/src/exec/pipeline/scan_operator.cpp:283
    #7 0x6fa86c1 in starrocks::pipeline::ScanOperator::_try_to_trigger_next_scan(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/scan_operator.cpp:174
    #8 0x6fa7ba6 in starrocks::pipeline::ScanOperator::pull_chunk(starrocks::RuntimeState*) /root/starrocks/be/src/exec/pipeline/scan_operator.cpp:141
    #9 0x70178ac in starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*, int) /root/starrocks/be/src/exec/pipeline/pipeline_driver.cpp:142
    #10 0x6fe91e8 in starrocks::pipeline::GlobalDriverExecutor::_worker_thread() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:115
    #11 0x6fe808d in operator() /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:57
    #12 0x6fefc59 in __invoke_impl<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:60
    #13 0x6fef358 in __invoke_r<void, starrocks::pipeline::GlobalDriverExecutor::initialize(int)::<lambda()>&> /usr/include/c++/10.3.0/bits/invoke.h:110
    #14 0x6fee78a in _M_invoke /usr/include/c++/10.3.0/bits/std_function.h:291
    #15 0x433f4c1 in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #16 0x59663cd in starrocks::FunctionRunnable::run() /root/starrocks/be/src/util/threadpool.cpp:45
    #17 0x5962f01 in starrocks::ThreadPool::dispatch_thread() /root/starrocks/be/src/util/threadpool.cpp:514
    #18 0x59804f5 in void std::__invoke_impl<void, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(std::__invoke_memfun_deref, void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:73
    #19 0x597fdd8 in std::__invoke_result<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>::type std::__invoke<void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&>(void (starrocks::ThreadPool::*&)(), starrocks::ThreadPool*&) /usr/include/c++/10.3.0/bits/invoke.h:95
    #20 0x597f1ef in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::__call<void, , 0ul>(std::tuple<>&&, std::_Index_tuple<0ul>) /usr/include/c++/10.3.0/functional:416
    #21 0x597dd5b in void std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>::operator()<, void>() /usr/include/c++/10.3.0/functional:499
    #22 0x597ac41 in void std::__invoke_impl<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::__invoke_other, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:60
    #23 0x5978c09 in std::enable_if<is_invocable_r_v<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>, void>::type std::__invoke_r<void, std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&>(std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()>&) /usr/include/c++/10.3.0/bits/invoke.h:110
    #24 0x59743a4 in std::_Function_handler<void (), std::_Bind<void (starrocks::ThreadPool::*(starrocks::ThreadPool*))()> >::_M_invoke(std::_Any_data const&) /usr/include/c++/10.3.0/bits/std_function.h:291
    #25 0x433f4c1 in std::function<void ()>::operator()() const /usr/include/c++/10.3.0/bits/std_function.h:622
    #26 0x594d484 in starrocks::Thread::supervise_thread(void*) /root/starrocks/be/src/util/thread.cpp:327
    #27 0x7f9d70125e64 in start_thread (/lib64/libpthread.so.0+0x7e64)

Thread T249 (pip_executor) created by T0 here:
    #0 0x4275972 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x594c8d8 in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.cpp:282
    #2 0x596aa32 in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.h:55
    #3 0x5964161 in starrocks::ThreadPool::create_thread() /root/starrocks/be/src/util/threadpool.cpp:564
    #4 0x5960d0e in starrocks::ThreadPool::do_submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPoolToken*) /root/starrocks/be/src/util/threadpool.cpp:414
    #5 0x595fb1e in starrocks::ThreadPool::submit(std::shared_ptr<starrocks::Runnable>) /root/starrocks/be/src/util/threadpool.cpp:331
    #6 0x595fcb7 in starrocks::ThreadPool::submit_func(std::function<void ()>) /root/starrocks/be/src/util/threadpool.cpp:335
    #7 0x6fe84d1 in starrocks::pipeline::GlobalDriverExecutor::initialize(int) /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:57
    #8 0x545a84a in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:179
    #9 0x5458cf1 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:123
    #10 0x430bc2b in main /root/starrocks/be/src/service/starrocks_main.cpp:214
    #11 0x7f9d6f664504 in __libc_start_main (/lib64/libc.so.6+0x22504)

Thread T243 (pip_executor) created by T0 here:
    #0 0x4275972 in __interceptor_pthread_create ../../.././libsanitizer/asan/asan_interceptors.cpp:214
    #1 0x594c8d8 in starrocks::Thread::start_thread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()> const&, unsigned long, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.cpp:282
    #2 0x596aa32 in starrocks::Status starrocks::Thread::create<void (starrocks::ThreadPool::*)(), starrocks::ThreadPool*>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void (starrocks::ThreadPool::* const&)(), starrocks::ThreadPool* const&, scoped_refptr<starrocks::Thread>*) /root/starrocks/be/src/util/thread.h:55
    #3 0x5964161 in starrocks::ThreadPool::create_thread() /root/starrocks/be/src/util/threadpool.cpp:564
    #4 0x5960d0e in starrocks::ThreadPool::do_submit(std::shared_ptr<starrocks::Runnable>, starrocks::ThreadPoolToken*) /root/starrocks/be/src/util/threadpool.cpp:414
    #5 0x595fb1e in starrocks::ThreadPool::submit(std::shared_ptr<starrocks::Runnable>) /root/starrocks/be/src/util/threadpool.cpp:331
    #6 0x595fcb7 in starrocks::ThreadPool::submit_func(std::function<void ()>) /root/starrocks/be/src/util/threadpool.cpp:335
    #7 0x6fe84d1 in starrocks::pipeline::GlobalDriverExecutor::initialize(int) /root/starrocks/be/src/exec/pipeline/pipeline_driver_executor.cpp:57
    #8 0x545a84a in starrocks::ExecEnv::_init(std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:179
    #9 0x5458cf1 in starrocks::ExecEnv::init(starrocks::ExecEnv*, std::vector<starrocks::StorePath, std::allocator<starrocks::StorePath> > const&) /root/starrocks/be/src/runtime/exec_env.cpp:123
    #10 0x430bc2b in main /root/starrocks/be/src/service/starrocks_main.cpp:214
    #11 0x7f9d6f664504 in __libc_start_main (/lib64/libc.so.6+0x22504)

SUMMARY: AddressSanitizer: heap-use-after-free /root/starrocks/be/src/storage/vectorized/column_expr_predicate.cpp:229 in operator()
Shadow bytes around the buggy address:
  0x0c168087b890: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b8a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b8b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b8c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b8d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fd fd
=>0x0c168087b8e0: fd fd[fd]fd fd fd fd fd fd fd fd fa fa fa fa fa
  0x0c168087b8f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b910: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c168087b930: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==30199==ABORTING
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
BRANCH-2.2-ASAN-6d46266

### LINKED ISSUE #6405: [sqlsmith] query crash in asan mode
### Steps to reproduce the behavior (Required)
```
crash.log:
*** Check failure stack trace: ***
    @          0xb018aed  google::LogMessage::Fail()
    @          0xb01af5f  google::LogMessage::SendToLog()
    @          0xb01863e  google::LogMessage::Flush()
    @          0xb01b569  google::LogMessageFatal::~LogMessageFatal()
    @          0x8cfbccc  starrocks::ExprContext::~ExprContext()
    @          0x58d636e  _ZZN9starrocks10ObjectPool3addINS_11ExprContextEEEPT_S4_ENKUlPvE_clES5_
    @          0x58d639f  _ZZN9starrocks10ObjectPool3addINS_11ExprContextEEEPT_S4_ENUlPvE_4_FUNES5_
    @          0x4ee60d2  starrocks::ObjectPool::clear()
    @          0x4ee5ee4  starrocks::ObjectPool::~ObjectPool()
    @          0x6239d03  std::_Sp_counted_ptr<>::_M_dispose()
    @          0x493e947  std::_Sp_counted_base<>::_M_release()
    @          0x493bf5c  std::__shared_count<>::~__shared_count()
    @          0x622d252  std::__shared_ptr<>::~__shared_ptr()
    @          0x622d26e  std::shared_ptr<>::~shared_ptr()
    @          0x6225a91  starrocks::RuntimeState::~RuntimeState()
    @          0x7eedb72  std::default_delete<>::operator()()
    @          0x7f0c33f  std::_Sp_counted_deleter<>::_M_dispose()
    @          0x493e947  std::_Sp_counted_base<>::_M_release()
    @          0x493bf5c  std::__shared_count<>::~__shared_count()
    @          0x604f19a  std::__shared_ptr<>::~__shared_ptr()
    @          0x604f1b6  std::shared_ptr<>::~shared_ptr()
    @          0x7ee2d1d  starrocks::pipeline::FragmentContext::~FragmentContext()
    @          0x7f0cc64  __gnu_cxx::new_allocator<>::destroy<>()
    @          0x7f0c705  std::allocator_traits<>::destroy<>()
    @          0x7f0b9af  std::_Sp_counted_ptr_inplace<>::_M_dispose()
    @          0x493e947  std::_Sp_counted_base<>::_M_release()
    @          0x493bf5c  std::__shared_count<>::~__shared_count()
    @          0x614b822  std::__shared_ptr<>::~__shared_ptr()
    @          0x614b83e  std::shared_ptr<>::~shared_ptr()
    @          0x7ff3c38  std::pair<>::~pair()
    @          0x7ff3c64  __gnu_cxx::new_allocator<>::destroy<>()
    @          0x7ff3704  std::allocator_traits<>::destroy<>()

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| MAIN-ASAN ebb36c3 |
+-------------------+
- cluster: sr@daily04: /home/disk1/sr/sqlsmith_01_asan/be/sqlsmith_01_asan/core.6522

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6319
Fixed #6316
Fixed #6405

## Problem Summary(Required) ：

In `OlapChunkSource`, the `_tablet_reader` would reference  object in `_predicate_free_pool`, so either manually call `OlapChunkSource::close` to ensure the release order, or ensure the release order in `~OlapChunkSource`.

And the other issue is `ColumnExprPredicate::try_to_rewrite_for_zone_map_filter`, the code construct a `DeferOp` to ensure the  `ExprContext::close`, which is unnecessary. We change it to call the `close` method if not closed.

### CODE REVIEW

**Comment by mofeiatwork** [comment]
@Mergifyio backport branch-2.2

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 3 / 3 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/planner/CrossJoinNode.java|3|3|100.00%|

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by mofeiatwork** [comment]
@Mergifyio rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/exprs/expr_context.cpp [hunk 1]
```diff
@@ -42,8 +42,9 @@ ExprContext::ExprContext(Expr* root)
         : _fn_contexts_ptr(nullptr), _root(root), _is_clone(false), _prepared(false), _opened(false), _closed(false) {}
 
 ExprContext::~ExprContext() {
-    DCHECK(!_prepared || _closed) << ". expr context address = " << this;
+    // DCHECK(!_prepared || _closed) << ". expr context address = " << this;
```
Comment (stdpain) [inline be/src/exprs/expr_context.cpp:45]: why we remove this check

File: be/src/exprs/expr_context.cpp [hunk 2]
```diff
@@ -79,10 +80,10 @@ Status ExprContext::open(std::vector<ExprContext*> evals, RuntimeState* state) {
 }
 
 void ExprContext::close(RuntimeState* state) {
-    if (_closed) {
+    bool expected = false;
+    if (!_closed.compare_exchange_strong(expected, true)) {
```
Comment (stdpain) [inline be/src/exprs/expr_context.cpp:84]: Why Exprcontext::close is called concurrently

File: be/src/storage/column_expr_predicate.cpp [hunk 3]
```diff
@@ -31,6 +31,22 @@ ColumnExprPredicate::~ColumnExprPredicate() {
...
+    for (auto& expr : expr_ctxs) {
+        _add_expr_ctx(expr);
+    }
+}
+
+void ColumnExprPredicate::_add_expr_ctx(std::unique_ptr<ExprContext> expr_ctx) {
+    if (expr_ctx != nullptr) {
+        DCHECK(expr_ctx->opened());
+        // Transfer the ownership to object pool
+        auto* ctx = _state->obj_pool()->add(expr_ctx.release());
```
Comment (stdpain) [inline be/src/storage/column_expr_predicate.cpp:44]: when do we call close for expr_ctx

File: be/src/exprs/expr_context.cpp (hunk 1 above)
Comment (mofeiatwork) [reply be/src/exprs/expr_context.cpp:45]: This check is no reasonable. It implies the `ExprContext` must be closed before deconstruct. But some local variable, this requirement is very hard to meet.

The example is `be/src/storage/column_expr_predicate.cpp`.

File: be/src/storage/column_expr_predicate.cpp [hunk 4]
```diff
@@ -224,16 +238,14 @@ Status ColumnExprPredicate::try_to_rewrite_for_zone_map_filter(starrocks::Object
...
+
         ColumnExprPredicate* new_pred =
-                pool->add(new ColumnExprPredicate(_type_info, _column_id, _state, ctx, _slot_desc));
-        // copy other cast exprs
-        for (size_t i = 1; i < _expr_ctxs.size(); i++) {
-            new_pred->_add_expr_ctx(_expr_ctxs[i]);
-        }
+                pool->add(new ColumnExprPredicate(_type_info, _column_id, _state, nullptr, _slot_desc));
+        new_pred->_add_expr_ctx(std::move(expr_rewrite));
+        new_pred->_add_expr_ctxs(_expr_ctxs);
```
Comment (stdpain) [inline be/src/storage/column_expr_predicate.cpp:248]: _exprs_ctxs is '=' '>' '<' we only need add '>=' and '<='

File: be/src/exprs/expr_context.cpp (hunk 2 above)
Comment (mofeiatwork) [reply be/src/exprs/expr_context.cpp:84]: Previous multiple ScanOperator could close it concurrent.

File: be/src/exprs/expr_context.cpp (hunk 1 above)
Comment (stdpain) [reply be/src/exprs/expr_context.cpp:45]: I think it is necessary to call close manually

Comment (stdpain) [reply be/src/exprs/expr_context.cpp:45]: if we create a state in state in prepare state we should close it in FRAGMENT_LOCAL STAGE

Comment (mofeiatwork) [reply be/src/exprs/expr_context.cpp:45]: Why call the `close` manually? If we could make sure the memory would not leak.

Could you give me some more reason?

File: be/src/storage/column_expr_predicate.cpp (hunk 4 above)
Comment (mofeiatwork) [reply be/src/storage/column_expr_predicate.cpp:248]: fixed

File: be/src/exprs/expr_context.cpp [hunk 5]
```diff
@@ -42,7 +42,10 @@ ExprContext::ExprContext(Expr* root)
         : _fn_contexts_ptr(nullptr), _root(root), _is_clone(false), _prepared(false), _opened(false), _closed(false) {}
 
 ExprContext::~ExprContext() {
-    DCHECK(!_prepared || _closed) << ". expr context address = " << this;
+    // DCHECK(!_prepared || _closed) << ". expr context address = " << this;
+    if (_prepared) {
+        close(_runtime_state);
```
Comment (stdpain) [inline be/src/exprs/expr_context.cpp:47]: is it possiable access memory alloced in _pool or _fn_contexts

**Review by kangkaisen — APPROVED** [review]

File: be/src/exprs/expr_context.cpp (hunk 1 above)
Comment (stdpain) [reply be/src/exprs/expr_context.cpp:45]: when we will alloc object in regex_prepare and free it in regex_close

**Review by ZiheLiu — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

**Review by stdpain — APPROVED** [review]
