### PR TITLE
[BugFix] fix rpc error for partitions_meta when partitions are too many

### LINKED ISSUE #52254: query statement get ERROR:MaxMessageSize reached
### Steps to reproduce the behavior (Required)
1. Use the SDM(starrocks-cluster-sync) tool to synchronize data from the shared-nothing cluster to the shared-data cluster.
2. The data volume after synchronization is as follows:
hdfs dfs -du -h /data
51.5 T  154.4 T  /data/dcsr

3. Start Compaction ,the config params is as follows:
FE:
lake_compaction_max_tasks=-1
lake_autovacuum_parallel_partitions=32
BE:
compact_threads = 64
compact_thread_pool_queue_size = 1000
max_cumulative_compaction_num_singleton_deltas=100

5. Execute the query statement.
select * from information_schema.partitions_meta pm  where PARTITION_ID = '5054238';
ERROR 1064 (HY000): FE RPC failure, address=TNetworkAddress(hostname=10.xxx.xx.12, port=9020), reason=MaxMessageSize reached, host: unknown
select count(*) from information_schema.partitions_meta pm  ;
ERROR 1064 (HY000): FE RPC failure, address=TNetworkAddress(hostname=10.xxx.xx.12, port=9020), reason=MaxMessageSize reached, host: unknown

### StarRocks version (Required)
StarRocks 3.3.4-56bcf6f run_mode = shared_data
3fe/12be

### PR DESCRIPTION
**Pull request by starrocks-xupeng**
## Why I'm doing:
fix https://github.com/StarRocks/starrocks/issues/52254

## What I'm doing:
```
FE RPC failure, address=TNetworkAddress(hostname=[XXX](XXX), port=XXX), reason=MaxMessageSize reached
```
introduce Config.max_get_partitions_meta_result_count, user reports over 700000 partitions when error happens, so 100000 is a safe default value.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp [hunk 1]
```diff
@@ -79,12 +79,25 @@ Status SchemaPartitionsMetaScanner::start(RuntimeState* state) {
...
     // init schema scanner state
     RETURN_IF_ERROR(SchemaScanner::init_schema_scanner_state(state));
-    RETURN_IF_ERROR(SchemaHelper::get_partitions_meta(_ss_state, partitions_meta_req, &_partitions_meta_response));
+    int64_t table_id_offset = 0;
+    while (true) {
+        TGetPartitionsMetaRequest partitions_meta_req;
+        partitions_meta_req.__set_auth_info(auth_info);
+        partitions_meta_req.__set_start_table_id_offset(table_id_offset);
+        TGetPartitionsMetaResponse partitions_meta_response;
+        RETURN_IF_ERROR(SchemaHelper::get_partitions_meta(_ss_state, partitions_meta_req,
```
Comment (murphyatwork) [inline be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:91]: it can be streamlined during the execution, which can also reduce peak memory usage

Comment (murphyatwork) [inline be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:91]: it can be implemented in streaming style, which can reduce the peak memory consumption

Comment (starrocks-xupeng) [reply be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:91]: wait for you to try it on mv

File: be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp [hunk 2]
```diff
@@ -79,12 +79,25 @@ Status SchemaPartitionsMetaScanner::start(RuntimeState* state) {
...
+                                                          &partitions_meta_response));
+        _partitions_meta_vec.insert(_partitions_meta_vec.end(),
+                                    partitions_meta_response.partitions_meta_infos.begin(),
+                                    partitions_meta_response.partitions_meta_infos.end());
+        table_id_offset = partitions_meta_response.next_table_id_offset;
+        if (!table_id_offset) {
```
Comment (kevincai) [inline be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:97]: check `partitions_meta_response.__isset.next_table_id_offset`?

File: fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java [hunk 3]
```diff
@@ -256,63 +259,90 @@ public static TGetPartitionsMetaResponse generatePartitionsMetaResponse(TGetPart
...
-                                    partitionMetaInfo, false /* isTemp */);
-                            pList.add(partitionMetaInfo);
-                        }
+            List<Table> tables = GlobalStateMgr.getCurrentState().getLocalMetastore().getTables(db.getId());
+            for (Table table : tables) {
+                sortedElements.add(new Element(dbName, db.getId(), table));
+            }
+        }
+
+        long startTableIdOffset = request.isSetStart_table_id_offset() ? request.getStart_table_id_offset() : 0;
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/service/InformationSchemaDataSource.java:287]: shall move this condition before TreeSet, so in line 283, it is easy to determine if the table needs to be added into TreeSet or not.

**Review by kevincai — COMMENTED** [review]
UT please! cover the pagination and sorted capability of the interface

File: be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp (hunk 2 above)
Comment (starrocks-xupeng) [reply be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:97]: if not set, it will be zero

Comment (kevincai) [reply be/src/exec/schema_scanner/schema_partitions_meta_scanner.cpp:95]: explicit check isset instead of using the default value.

**Review by kevincai — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by wangruin — APPROVED** [review]

**Comment by starrocks-xupeng** [comment]
https://github.com/StarRocks/starrocks/pull/56247
3.3

**Comment by starrocks-xupeng** [comment]
https://github.com/StarRocks/starrocks/pull/56249
3.4
