### PR TITLE
BugFix: throw exception when hdfs file is deleted

### LINKED ISSUE #4542: NPE in HDFSBackendSelector.computeScanRangeAssignment
```
java.lang.NullPointerException: null
        at com.starrocks.qe.Coordinator$HDFSBackendSelector.computeScanRangeAssignment(Coordinator.java:2463) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.computeScanRangeAssignment(Coordinator.java:1491) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.Coordinator.exec(Coordinator.java:412) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:713) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:395) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:277) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:424) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:660) ~[starrocks-fe.jar:?]
```

```
sql select
  ref_1.teacherId as c0,
  subq_0.c0 as c1,
  ref_2.p_category as c2,
  subq_0.c1 as c3,
  ref_1.analysisResult as c4,
  subq_0.c0 as c5
from
  (select
            ref_0.w_state as c0,
            ref_0.w_warehouse_sk as c1
          from
            test.warehouse_9 as ref_0
          where (ref_0.w_warehouse_sk >= ref_0.w_warehouse_sk)
            or (true)
          limit 109) as subq_0
      left join test.room_analysis_result_mysql as ref_1
      on (subq_0.c0 = ref_1.analysisResult )
    inner join test.ssb_orc_1t_part as ref_2
    on (subq_0.c0 = ref_2.p_name )
where ref_1.roomId = ref_2.p_size
limit 147
```

```
CREATE EXTERNAL TABLE `room_analysis_result_mysql` (
  `id` bigint(20) NULL COMMENT "",
  `roomId` bigint(20) NULL COMMENT "",
  `analysisResult` varchar(1024) NULL COMMENT "",
  `createTime` datetime NULL COMMENT "",
  `extInfo` varchar(1024) NULL COMMENT "",
  `teacherId` bigint(20) NULL COMMENT "",
  `score` int(11) NULL COMMENT "",
  `userId` bigint(20) NULL COMMENT "",
  `userType` int(11) NULL COMMENT "",
  `audioRecordDevice` int(11) NULL COMMENT "",
  `product` int(11) NULL COMMENT "",
  `lpc` int(11) NULL COMMENT ""
) ENGINE=MYSQL
COMMENT "MYSQL"
PROPERTIES (
"host" = "172.26.92.139",
"port" = "8880",
"user" = "xxx",
"password" = "",
"database" = "test",
"table" = "room_analysis_result_mysql2"
);
```

```
CREATE EXTERNAL TABLE `ssb_orc_1t_part` (
  `p_partkey` int(11) NULL COMMENT "",
  `p_name` varchar(23) NULL COMMENT "",
  `p_mfgr` varchar(7) NULL COMMENT "",
  `p_category` varchar(8) NULL COMMENT "",
  `p_brand` varchar(10) NULL COMMENT "",
  `p_color` varchar(12) NULL COMMENT "",
  `p_type` varchar(26) NULL COMMENT "",
  `p_size` int(11) NULL COMMENT "",
  `p_container` varchar(11) NULL COMMENT ""
) ENGINE=HIVE
COMMENT "PARTITION BY ()"
PROPERTIES (
"database" = "ssb_orc_1t",
"table" = "part",
"resource" = "hive_resource_stability",
"hive.metastore.uris"  =  "thrift://172.26.194.118:9083"
);
```

commit： 02a4ab1ff39

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [X] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4542 #4543

## Problem Summary(Required) ：

catch the case that hdfs file is deleted as early as possible, to avoid confusing error message.

Right now, the error message is like following

```
ERROR 1064 (HY000): hdfs file block has no host. file = hdfs://xxxx/stability_data/ssb/orc/part/part-00000-cffe36b9-0225-4ccf-8ea0-71b9c4586233-c000.snappy.orc
```

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/RemoteScanRangeLocations.java|0|13|00.00%|

File: fe/fe-core/src/main/java/com/starrocks/external/RemoteScanRangeLocations.java [hunk 1]
```diff
@@ -90,12 +88,18 @@ private void createScanRangeLocationsForSplit(long partitionId,
...
+        hdfsScanRange.setFile_format(partition.getFormat().toThrift());
         hdfsScanRange.setText_file_desc(fileDesc.getTextFileFormatDesc().toThrift());
         TScanRange scanRange = new TScanRange();
         scanRange.setHdfs_scan_range(hdfsScanRange);
         scanRangeLocations.setScan_range(scanRange);
 
+        if (blockDesc.getReplicaHostIds().length == 0) {
+            String message = String.format("hdfs file block has no host. file = %s/%s",
+                    partition.getFullPath(), fileDesc.getFileName());
+            throw new RuntimeException(message);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/external/RemoteScanRangeLocations.java:100]: why throw RuntimeException?

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/external/RemoteScanRangeLocations.java:100]: Because there is no machine to host that block, and there is no way to scan that block. What's your suggestion?

Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/external/RemoteScanRangeLocations.java:100]: RuntimeException may be ignored, I suggest throw another Exception which should be catch explicitly.

Comment (dirtysalt) [reply fe/fe-core/src/main/java/com/starrocks/external/RemoteScanRangeLocations.java:100]: Nono, that's what I expect. I expect that this exception can throw out and display error mesage like

```
ERROR 1064 (HY000): hdfs file block has no host. file = hdfs://xxxx/stability_data/ssb/orc/part/part-00000-cffe36b9-0225-4ccf-8ea0-71b9c4586233-c000.snappy.orc
```

Otherwise we get error "Unknown error".

**Review by imay — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]
