### PR TITLE
Be crash caused by invalid json root

### LINKED ISSUE #4727: BE crash in TestStreamLoadJson.test_stream_load_json_with_error_json_root
### Steps to reproduce the behavior (Required)
```
----------------------current_case_index:1 / 1 of case_1.txt------------------
test_stream_load_json.TestStreamLoadJson.test_stream_load_json_with_error_json_root ... create database stream_load_test_db_0463df20_b1cb_11ec_91a8_00163e0e550b
use stream_load_test_db_0463df20_b1cb_11ec_91a8_00163e0e550b
CREATE TABLE `test_nonsense_columns` (
                    `category` varchar(100) NOT NULL COMMENT "",
                    `author` varchar(100) NOT NULL COMMENT "",
                    `title` varchar(100) NOT NULL DEFAULT "0" COMMENT "",
                    `price` double NOT NULL DEFAULT "0" COMMENT ""
                  ) ENGINE=OLAP
                  UNIQUE KEY(`category`)
                  COMMENT "OLAP"
                  DISTRIBUTED BY HASH(`category`) BUCKETS 10
                  PROPERTIES (
                  "replication_num" = "1"
                  );
curl --location-trusted -u root: -T /home/disk5/fuwei/code/work/StarRocksTest/lib/../common/data/stream_load/data_for_json_root -XPUT -H label:stream_load_1648824605189 -H format:json -H columns:category, author, title, price -H json_root:["$.RECORDS"] -H strip_outer_array:true http://172.26.92.139:8072/api/stream_load_test_db_0463df20_b1cb_11ec_91a8_00163e0e550b/test_nonsense_columns/_stream_load
drop database stream_load_test_db_0463df20_b1cb_11ec_91a8_00163e0e550b
FAIL

======================================================================
FAIL: test_stream_load_json.TestStreamLoadJson.test_stream_load_json_with_error_json_root
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/disk5/fuwei/code/work/StarRocksTest/case/system_case/test_dml/test_stream_load/test_stream_load_json.py", line 921, in test_stream_load_json_with_error_json_root
    eq_(res["Status"], "Fail", res["Message"])
AssertionError:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0   252    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

100   252    0     0  100   252      0   4221 --:--:-- --:--:-- --:--:--  4221
curl: (52) Empty reply from server


----------------------------------------------------------------------
XML: /home/disk5/fuwei/code/work/StarRocksTest/result/TestStreamLoadJson_test_stream_load_json_with_error_json_root.xml
----------------------------------------------------------------------
Ran 1 test in 0.086s

FAILED (failures=1)
1
--------------------------------------------------------------------------------------------------------------
0
```

### Expected behavior (Required)
Test Success.
### Real behavior (Required)
BE crashes.
```
*** Aborted at 1648824605 (unix time) try "date -d @1648824605" if you are using GNU date ***
PC: @          0x250e013 starrocks::vectorized::ExpandedJsonArrayParserWithRoot::parse()
*** SIGSEGV (@0x0) received by PID 197258 (TID 0x7fe5dec9e700) from PID 0; stack trace: ***
    @          0x3678dd2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fe7158e0400 (unknown)
    @          0x250e013 starrocks::vectorized::ExpandedJsonArrayParserWithRoot::parse()
    @          0x2511dab starrocks::vectorized::JsonReader::_read_and_parse_json()
    @          0x2514115 starrocks::vectorized::JsonReader::read_chunk()
    @          0x2514374 starrocks::vectorized::JsonScanner::get_next()
    @          0x2500ca7 starrocks::vectorized::FileScanNode::_scanner_scan()
    @          0x2501e4f starrocks::vectorized::FileScanNode::_scanner_worker()
    @          0x50ab300 execute_native_thread_routine
    @     0x7fe715695ea5 start_thread
    @     0x7fe7159a8b0d __clone
    @                0x0 (unknown)
### StarRocks version (Required)
branch-2.1

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4727

## Problem Summary(Required) ：

This fix the crash problem caused by invalid json root. Because the JsonPath is refactored in version 2.2, this bug only happens in branch-2.1.
Nevertheless, this fix should be merged to version >= 2.2 to make it more robust.

### CODE REVIEW

**Review by murphyatwork — DISMISSED** [review]

File: be/src/exprs/vectorized/json_functions.cpp [hunk 1]
```diff
@@ -137,23 +145,32 @@ Status JsonFunctions::extract_from_object(simdjson::ondemand::object& obj, const
...
+                        fmt::format("failed to get array size, field: {}, err: {}", col, simdjson::error_message(err)));
+            }
 
-                if (idx++ == index) {
-                    a.get(tvalue);
-                    break;
-                }
+            if (index >= sz) {
+                return Status::InvalidArgument(
+                        fmt::format("the acquired index is beyond array size, field: {}, index: {}, array size: {}",
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/json_functions.cpp:165]: In standard JSONPath, that could return a null ? instead of report error?
Anyway, we should try best to keep compatible with JSONPath?

Comment (rickif) [reply be/src/exprs/vectorized/json_functions.cpp]: This has been changed to `Status::NotFound`, which is the same as json path not found.

**Review by murphyatwork — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
