### PR TITLE
[BugFix] NPE threw when getting stream load tasks from information_schema table

### LINKED ISSUE #37357: Query for information_schema.stream_loads table threw NullPointerException when no label is specified
This bug is related to https://github.com/StarRocks/starrocks/pull/23649

### Steps to reproduce the behavior (Required)

1. create a stream load task
2. execute a query from information_schema.stream_loads

### Real behavior (Required)

image

```
2023-12-19 16:37:40,800 WARN (thrift-server-pool-355|1202) [FrontendServiceImpl.getStreamLoads():2604] Failed to getStreamLoads
java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[?:?]
	at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:964) ~[?:?]
	at com.starrocks.load.streamload.StreamLoadMgr.getTaskByName(StreamLoadMgr.java:550) ~[starrocks-fe.jar:?]
	at com.starrocks.service.FrontendServiceImpl.getStreamLoads(FrontendServiceImpl.java:2596) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$getStreamLoads.getResult(FrontendService.java:3641) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$getStreamLoads.getResult(FrontendService.java:3621) ~[starrocks-fe.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38) ~[libthrift-0.13.0.jar:0.13.0]
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
```

### StarRocks version (Required)
 - main branch

### PR DESCRIPTION
**Pull request by wxl24life**
Why I'm doing:

What I'm doing:

Fixes #37357

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [x] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by jaogoy — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java [hunk 1]
```diff
@@ -546,14 +546,19 @@ public StreamLoadTask getTaskById(long id) {
...
+    // return all tasks if label is null
     public List<StreamLoadTask> getTaskByName(String label) {
         List<StreamLoadTask> result = Lists.newArrayList();
         readLock();
         try {
-            for (Map<String, StreamLoadTask> labelToStreamLoadTask : dbToLabelToStreamLoadTask.values()) {
-                if (labelToStreamLoadTask.containsKey(label)) {
-                    result.add(labelToStreamLoadTask.get(label));
+            if (label != null) {
+                StreamLoadTask task = idToStreamLoadTask.get(label);
```
Comment (jaogoy) [inline fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java:555]: 1. what's the difference between `dbToLabelToStreamLoadTask` and `idToStreamLoadTask`? 
2. can we use `where label like 'abc%' to search? and `where db_name = 'xxx'` to filter?

**Review by jaogoy — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java (hunk 1 above)
Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/load/streamload/StreamLoadMgr.java:555]: 1. Both of them are map structure, but with different key/value, `idToStreamLoadTask`'s key is task id, and `dbToLabelToStreamLoadTask`'s key is db id
2. They should both be supported, but for now it looks both are missed, maybe we can try to fix them in this pr.

**Review by meegoo — APPROVED** [review]

**Comment by cheny1994** [comment]
What is the situation now? When can I merge into the released version?
