### PR TITLE
[BugFix]Fix transaction stream load can not find the coordinator node.

### LINKED ISSUE #59436: FE   TransactionLoadAction class  txnNodeMap field  is not thread-safe and has a memory leak issue
The txnNodeMap in the TransactionLoadAction class of the FE process is not thread-safe and has a memory leak issue. When the accessOrder parameter of the LinkedHashMap is set to true, the get method not only retrieves values but also updates the internal linked list order, performing a write operation.

In the code, txnNodeMap.get(label) is protected by a read lock, while txnNodeMap.put(label, chosenNodeId) is protected by a write lock, which introduces a thread safety issue.

```java
    private final Map<String, Long> txnNodeMap = new LinkedHashMap<>(512, 0.75f, true) {
        @Override
        protected boolean removeEldestEntry(Map.Entry<String, Long> eldest) {
            return size() > (GlobalStateMgr.getCurrentState().getNodeMgr().getClusterInfo().getTotalBackendNumber() +
                    GlobalStateMgr.getCurrentState().getNodeMgr().getClusterInfo().getTotalComputeNodeNumber()) * 512;
        }
    };
    
    private Long getNodeId(TransactionOperation txnOperation, String label, String warehouseName) throws UserException {
        Long nodeId;
        // save label->be hashmap when begin transaction, so that subsequent operator can send to same BE
        if (TXN_BEGIN.equals(txnOperation)) {
            List<Long> nodeIds = LoadAction.selectNodes(warehouseName);
            Long chosenNodeId = nodeIds.get(0);
            nodeId = chosenNodeId;
            // txnNodeMap is LRU cache, it atomic remove unused entry
            accessTxnNodeMapWithWriteLock(txnNodeMap -> txnNodeMap.put(label, chosenNodeId));
        } else {
            nodeId = accessTxnNodeMapWithReadLock(txnNodeMap -> txnNodeMap.get(label));
        }

        if (nodeId == null) {
            throw new UserException(String.format(
                    "Transaction with op[%s] and label[%s] has no node.", txnOperation.getValue(), label));
        }

        return nodeId;
    }
    
    private <T> T accessTxnNodeMapWithReadLock(Function<Map<String, Long>, T> function) {
        txnNodeMapAccessLock.readLock().lock();
        try {
            return function.apply(txnNodeMap);
        } finally {
            txnNodeMapAccessLock.readLock().unlock();
        }
    }

    private <T> T accessTxnNodeMapWithWriteLock(Function<Map<String, Long>, T> function) {
        txnNodeMapAccessLock.writeLock().lock();
        try {
            return function.apply(txnNodeMap);
        } finally {
            txnNodeMapAccessLock.writeLock().unlock();
        }
    }
```

Upon dumping the FE's memory, I found that the memory usage of txnNodeMap continuously increases, and the next pointer of the head node is null.

### Steps to reproduce the behavior (Required)
dumping the FE's memory

Image

Image

after time dumping the FE's memory

Image

Image

### Expected behavior (Required)
has 3 be , txnNodeMap size shoud <= 1536

### Real behavior (Required)
txnNodeMap size continuously increasing

### StarRocks version (Required)
 - 3.4.3

### LINKED ISSUE #60155: Unable to find the node corresponding to the running label
Label bylink_event_56-event_ros_56-4-14 state transfrom to prepared after load, report err message:"**Transaction with op[prepare] and label[bylink_event_56-event_ros_56-4-14] has no node.**";

```
2025-06-18 18:50:30.096+08:00 INFO (nioEventLoopGroup-6-17|501) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:50:30.096+08:00 INFO (nioEventLoopGroup-6-17|501) [TransactionLoadAction.executeTransaction():239] Redirect transaction action to destination=TNetworkAddress(hostname:10.73.3.127, port:8040), db: rawdata, table: event_ros_56, op: TXN_BEGIN, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:50:30.101+08:00 INFO (thrift-server-pool-59635|346898) [FrontendServiceImpl.loadTxnBegin():1189] receive txn begin request, db: rawdata, tbl: event_ros_56, label: bylink_event_56-event_ros_56-4-14, backend: 10.73.3.127
2025-06-18 18:50:30.101+08:00 INFO (thrift-server-pool-59635|346898) [DatabaseTransactionMgr.beginTransaction():187] begin transaction: txn_id: 2569377 with label bylink_event_56-event_ros_56-4-14 from coordinator FE: 10.73.3.18, listner id: 6153481
2025-06-18 18:50:30.101+08:00 INFO (thrift-server-pool-59635|346898) [StreamLoadTask.beginTxn():317] stream load bylink_event_56-event_ros_56-4-14 channel_id 0 begin. db: rawdata, tbl: event_ros_56, txn_id: 2569377
2025-06-18 18:50:30.115+08:00 INFO (nioEventLoopGroup-6-21|653) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:50:30.115+08:00 INFO (nioEventLoopGroup-6-21|653) [TransactionLoadAction.executeTransaction():239] Redirect transaction action to destination=TNetworkAddress(hostname:10.73.3.127, port:8040), db: rawdata, table: event_ros_56, op: TXN_LOAD, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:50:30.236+08:00 INFO (nioEventLoopGroup-6-33|756) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:50:30.236+08:00 WARN (nioEventLoopGroup-6-33|756) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[prepare] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 18:54:43.670+08:00 INFO (nioEventLoopGroup-6-44|859) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:54:43.671+08:00 WARN (nioEventLoopGroup-6-44|859) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[rollback] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 18:54:51.812+08:00 INFO (nioEventLoopGroup-6-125|1515) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:54:51.812+08:00 WARN (nioEventLoopGroup-6-125|1515) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[rollback] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 18:54:58.399+08:00 INFO (nioEventLoopGroup-6-63|1004) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:54:58.400+08:00 WARN (nioEventLoopGroup-6-63|1004) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[rollback] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 18:58:49.153+08:00 INFO (nioEventLoopGroup-6-37|783) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:58:49.153+08:00 WARN (nioEventLoopGroup-6-37|783) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[rollback] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 18:58:57.095+08:00 INFO (nioEventLoopGroup-6-33|756) [TransactionWithoutChannelHandler.handle():65] Handle transaction without channel info, label: bylink_event_56-event_ros_56-4-14
2025-06-18 18:58:57.095+08:00 WARN (nioEventLoopGroup-6-33|756) [TransactionLoadAction.executeWithoutPassword():202] com.starrocks.common.UserException: Transaction with op[rollback] and label[bylink_event_56-event_ros_56-4-14] has no node.
2025-06-18 19:00:41.327+08:00 INFO (txnTimeoutChecker|129) [DatabaseTransactionMgr.abortTransaction():570] transaction:[TransactionState. txn_id: 2569377, label: bylink_event_56-event_ros_56-4-14, db id: 602275, table id list: 5903488, callback id: 6153481, coordinator: FE: 10.73.3.18, transaction status: ABORTED, error replicas num: 0, replica ids: , prepare time: 1750243830101, write end time: -1, allow commit time: -1, commit time: -1, finish time: 1750244441325, total cost: 611224ms, reason: timeout by txn manager, partition commit info:[]] successfully rollback
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhangheihei**
## Why I'm doing:
TransactionLoadAction class txnNodeMap field is not thread-safe, accessTxnNodeMapWithReadLock will concurrently update the Eldest Entry when holding a readLock, leading to data race. This can lead to memory leaks #59436  and cache invalidation #60155 
## What I'm doing:
Refactor the code to use caffeine instead of LinkedHashMap.
If the cache is invalid, get the backendId corresponding to the label from TransactionState.
Fixes #60155
Fixes #59436

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Comment by banmoy** [comment]
@zhangheihei Could you explain the reasons in detail?

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 1]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
     }
 
+    public static class TransactionLoadLabelCache  {
+        private final Cache<String, Long> cache;
+
+        public TransactionLoadLabelCache() {
+            Caffeine<Object, Object> builder = Caffeine.newBuilder();
+            cache = builder.initialCapacity(512).maximumWeight(getMaxCapacity())
+                    .weigher((key, value) -> 1)
+                    .expireAfterAccess((long) Config.prepared_transaction_default_timeout_second + 100, TimeUnit.SECONDS)
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: `Config.prepared_transaction_default_timeout_second` is a mutable configuration, once the configuration is changed to a much longer time in runtime than the one `TransactionLoadLabelCache` is initialized here, it will cause the cache expired unexpectedly due to the fixed expiration here.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 2]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
+            cache.policy().eviction().ifPresent(eviction -> {
+                if (eviction.getMaximum() != getMaxCapacity()) {
+                    eviction.setMaximum(getMaxCapacity());
+                }
+            });
+        }
+
+        public void put(String key, Long value) {
+            cache.put(key, value);
+            refreshCapacity();
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: shall refresh the capacity for a time based, instead of for every put(), although `getMaxCapacity()` is relatively lightweight, but not that trivial.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 3]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
+                            LOG.error("Failed to get backend node id for ip: {}, backends: {}", nodeIp, backends);
+                        }
+                    }
+                }
+            }
+
+            return nodeId;
+        }
+
+        public String getTxnCoordinator(String dbName, String label) {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: make it private if used inside this TransactionLoadAction only.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 4]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
+        }
+
+        public Long get(String key, String dbName, String label) {
+            Long nodeId = cache.getIfPresent(key);
+            if (nodeId == null) {
+                String nodeIp = getTxnCoordinator(dbName, label);
+                if (nodeIp != null) {
+                    if (RunMode.isSharedDataMode()) {
+                        List<ComputeNode> computeNodes =
+                                GlobalStateMgr.getCurrentState().getNodeMgr().getClusterInfo().getComputeNodeOnlyWithHost(nodeIp);
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: this is not correct, in a shared data cluster, BE can be still used the same way as the compute node, so in shared data mode, both compute nodes and backends should be checked.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 5]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
+            }
+
+            return nodeId;
+        }
+
+        public String getTxnCoordinator(String dbName, String label) {
+            GlobalStateMgr globalStateMgr = GlobalStateMgr.getCurrentState();
+            Database db = globalStateMgr.getLocalMetastore().getDb(dbName);
+            if (db == null) {
+                LOG.error("unknown database, database=" + dbName);
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: these logs may be useless, it is up to the caller how to deal with the null return value. An alternative way is to throw exception with exception message, and the caller just need to catch the exception and determine whether need to log the exception message.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 6]
```diff
@@ -114,20 +116,105 @@ public class TransactionLoadAction extends RestBaseAction {
...
+        }
+
+        public void put(String key, Long value) {
+            cache.put(key, value);
+            refreshCapacity();
+        }
+
+        public Long get(String key, String dbName, String label) {
+            Long nodeId = cache.getIfPresent(key);
+            if (nodeId == null) {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: this implementation has syntax issue.

txnMap.exists() checks cache.getIfPresent().
txnMap.get() always get the the result even if the label doesn't exist in the cache.

So put together, there is a case that txnMap.exists() == false, txnMap.get() can still return a valid result.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java (hunk 2 above)
Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: Here is to be consistent with the LinkedHashMap.removeEldestEntry behavior, but refresh the capacity for a time based is better.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 7]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
         super(controller);
         initMetrics();
     }
 
+    @VisibleForTesting
+    public TransactionLoadLabelCache getTxnNodeMap() {
+        return txnNodeMap;
+    }
+
+    public static class TransactionLoadLabelCache {
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: could put this class in a separate java file, and add test for it which do not dependent on transaction stream load. Maybe this cache can be reused by other scenarios in the future.

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: tks review.I'll update here later.

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 8]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
 
-    private final ReadWriteLock txnNodeMapAccessLock = new ReentrantReadWriteLock();
-    private final Map<String, Long> txnNodeMap = new LinkedHashMap<>(512, 0.75f, true) {
-        @Override
-        protected boolean removeEldestEntry(Map.Entry<String, Long> eldest) {
-            return size() > (GlobalStateMgr.getCurrentState().getNodeMgr().getClusterInfo().getTotalBackendNumber() +
-                    GlobalStateMgr.getCurrentState().getNodeMgr().getClusterInfo().getTotalComputeNodeNumber()) * 512;
-        }
-    };
+    private final TransactionLoadLabelCache txnNodeMap = new TransactionLoadLabelCache();
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]:
```suggestion
    private final TransactionLoadLabelCache txnLabelCache = new TransactionLoadLabelCache();
```

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 9]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
+        return txnNodeMap;
+    }
+
+    public static class TransactionLoadLabelCache {
+        private final Cache<String, Long> cache;
+        private final ScheduledExecutorService scheduler;
+
+        public TransactionLoadLabelCache() {
+            Caffeine<Object, Object> builder = Caffeine.newBuilder();
+            cache = builder.initialCapacity(512).maximumWeight(getMaxCapacity())
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: why not use `maximumSize` instead of `maximumWeight`

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 10]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
+                        LOG.debug("Evicted transaction label node mapping: {}->{} ({})", key, value, cause);
+                    })
+                    .recordStats()
+                    .build();
+
+            scheduler = Executors.newSingleThreadScheduledExecutor(
+                    new ThreadFactoryBuilder().setNameFormat("LabelCacheRefresh-%d").build());
+            scheduler.scheduleAtFixedRate(() -> {
+                try {
+                    refreshCapacity();
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: 1. suggest to introduce separate configurations to control capacity and expire time
    * `transaction_load_label_cache_capacity`: decouple the capacity with the number of nodes. I think the default value can be 4096 which should be enough for most cases
    * `transaction_load_label_cache_expire_time_second`: the default value can be 900s which is slightly larger than `stream_load_default_timeout_second` which is 600s
 2. these configurations can be mutable, and update the Cache via `ConfigRefreshListener` instead of using a separate schedule thread
 3. add metrics for caffeine's`CacheStats` so that we can know whether to need tune configurations

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java (hunk 7 above)
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: add comment to explain what it does

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 11]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
+        }
+
+        public void refreshExpireTime() {
+            cache.policy().expireAfterAccess().ifPresent(expireAfterAccess -> {
+                expireAfterAccess.setExpiresAfter(
+                        (long) Config.prepared_transaction_default_timeout_second + 100, TimeUnit.SECONDS);
+            });
+        }
+
+        public void put(String key, Long value) {
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]:
```suggestion
        public void put(String label, Long nodeId) {
```

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 12]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
+            cache.put(key, value);
+        }
+
+        public Long get(String key) {
+            return cache.getIfPresent(key);
+        }
+
+        public Long getOrResolveCoordinator(String key, String dbName, String label) throws StarRocksException {
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]:
```suggestion
        public Long get(String dbName, String label) throws StarRocksException {
```

File: fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java [hunk 13]
```diff
@@ -114,20 +122,141 @@ public class TransactionLoadAction extends RestBaseAction {
...
+                expireAfterAccess.setExpiresAfter(
+                        (long) Config.prepared_transaction_default_timeout_second + 100, TimeUnit.SECONDS);
+            });
+        }
+
+        public void put(String key, Long value) {
+            cache.put(key, value);
+        }
+
+        public Long get(String key) {
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: no need to wrap `cache.getIfPresent` with an extra function ?

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/http/rest/TransactionLoadAction.java]: This is mainly for the test class

**Comment by kevincai** [comment]
@Mergifyio rebase

**Comment by banmoy** [comment]
@zhangheihei can you complete the `Why I'm doing` and `What I'm doing`

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 14]
```diff
@@ -1054,6 +1054,13 @@ public class Config extends ConfigBase {
     @ConfField(mutable = true)
     public static int max_stream_load_timeout_second = 259200; // 3days
 
+    @ConfField(mutable = true, comment =
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1057]: add document for those configurations

Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1057]: I will add doc later

**Comment by DanJing-coder** [comment]
您好，您的邮件已收到，我会尽快给你回复。

**Review by banmoy — APPROVED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
