### PR TITLE
[Enhancement] Support ZSTD in kafka

### LINKED ISSUE #32945: Ingesting kafka messages with ZSTD compression fails
### Steps to reproduce the behavior (Required)
Created routine load from kafka into a table:
```
CREATE ROUTINE LOAD poc.ingest_mytable ON mytable  
PROPERTIES  
(  
    "format" = "avro"  
)  
FROM KAFKA  
(  
    "kafka_broker_list" = "kafka-broker:9092",
    "confluent.schema.registry.url" = "http://schema-registry:8081",  
    "kafka_topic" = "mytopic-avro",
    "kafka_partitions" = "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11",
    "kafka_offsets" = "OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING, OFFSET_BEGINNING"
);
```

Messages are produced with `zstd` compression.

### Expected behavior (Required)
Messages successfully ingested.

### Real behavior (Required)
No messages appear in the table.

`show routine load` show job as running: `State: RUNNING`

From be.log:
```
I1017 07:07:15.687845   390 data_consumer.cpp:73] init kafka consumer with group id: ingest_mytable_5af7f14e-9bcd-4173-90ea-b4f52b515f5f
I1017 07:07:15.763624   641 routine_load_task_executor.cpp:322] submit a new routine load task: id=5cdac73ac89c4f6a-9ad1f776f5bab9f6, job_id=16512, txn_id: 95, label=ingest_mytable-16512-5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6, db=poc, current tasks num: 1
I1017 07:07:15.763726  4496 routine_load_task_executor.cpp:339] begin to execute routine load task: id=5cdac73ac89c4f6a-9ad1f776f5bab9f6, job_id=16512, txn_id: 95, label=ingest_mytable-16512-5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6, db=poc
I1017 07:07:15.764482  4496 data_consumer.cpp:73] init kafka consumer with group id: ingest_mytable_5af7f14e-9bcd-4173-90ea-b4f52b515f5f
I1017 07:07:15.764892  4496 data_consumer.cpp:73] init kafka consumer with group id: ingest_mytable_5af7f14e-9bcd-4173-90ea-b4f52b515f5f
I1017 07:07:15.765444  4496 data_consumer_pool.cpp:106] get consumer group d04f6a0473680edf-b341277f9999b888 with 3 consumers
I1017 07:07:15.765483  4496 data_consumer.cpp:171] consumer: a34991924d1adf98-d1e31225af84d181, grp: d04f6a0473680edf-b341277f9999b888 assign topic partitions: mytopic-avro, [0: 6592338] [3: 6393752] [6: 14267542] [9: 19384171] 
I1017 07:07:15.765662  4496 data_consumer.cpp:171] consumer: 99497c61ac6e9f02-cac3b7e4b81d658b, grp: d04f6a0473680edf-b341277f9999b888 assign topic partitions: mytopic-avro, [1: 6991806] [4: 15269528] [7: 6352721] [10: 6723215] 
I1017 07:07:15.765861  4496 data_consumer.cpp:171] consumer: 7c4601a90070e068-5df130e98935cf8c, grp: d04f6a0473680edf-b341277f9999b888 assign topic partitions: mytopic-avro, [2: 6245490] [5: 15089544] [8: 6507260] [11: 6636134] 
I1017 07:07:15.766003  4496 stream_load_executor.cpp:67] begin to execute job. label=ingest_mytable-16512-5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6, txn_id: 95, query_id=5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6
I1017 07:07:15.766058  4496 plan_fragment_executor.cpp:83] Prepare(): query_id=5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6 fragment_instance_id=5cdac73a-c89c-4f6a-9ad1-f776f5bab9f7 backend_num=0
I1017 07:07:15.767275   373 plan_fragment_executor.cpp:185] Open(): fragment_instance_id=5cdac73a-c89c-4f6a-9ad1-f776f5bab9f7
I1017 07:07:15.767805  4496 data_consumer_group.cpp:115] start consumer group: d04f6a0473680edf-b341277f9999b888. max time(ms): 15000, batch size: 4294967296. id=5cdac73ac89c4f6a-9ad1f776f5bab9f6, job_id=16512, txn_id: 95, label=ingest_mytable-16512-5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6, db=poc
I1017 07:07:15.767872  4498 data_consumer.cpp:194] start kafka consumer: a34991924d1adf98-d1e31225af84d181, grp: d04f6a0473680edf-b341277f9999b888, max running time(ms): 15000
I1017 07:07:15.767938  4499 data_consumer.cpp:194] start kafka consumer: 99497c61ac6e9f02-cac3b7e4b81d658b, grp: d04f6a0473680edf-b341277f9999b888, max running time(ms): 15000
I1017 07:07:15.768134  4497 data_consumer.cpp:194] start kafka consumer: 7c4601a90070e068-5df130e98935cf8c, grp: d04f6a0473680edf-b341277f9999b888, max running time(ms): 15000
I1017 07:07:15.768255   501 local_tablets_channel.cpp:569] LocalTabletsChannel txn_id: 95 load_id: 5cdac73a-c89c-4f6a-9ad1-f776f5bab9f6 open 2 delta writer: [16508:1][16506:1] 0 failed_tablets:  _num_remaining_senders: 1
W1017 07:07:15.768991  4498 data_consumer.cpp:267] kafka consume failed: a34991924d1adf98-d1e31225af84d181, msg: Decompression (codec 0x4) of message at 19384171 of 1152 bytes failed: Local: Not implemented
I1017 07:07:15.769016  4498 data_consumer.cpp:279] kafka consume done: a34991924d1adf98-d1e31225af84d181, grp: d04f6a0473680edf-b341277f9999b888. cancelled: 0, left time(ms): 14999, total cost(ms): 1, consume cost(ms): 1, received rows: 0, put rows: 0
W1017 07:07:15.790205  4499 data_consumer.cpp:267] kafka consume failed: 99497c61ac6e9f02-cac3b7e4b81d658b, msg: Decompression (codec 0x4) of message at 6991806 of 1167 bytes failed: Local: Not implemented
I1017 07:07:15.790311  4499 data_consumer.cpp:279] kafka consume done: 99497c61ac6e9f02-cac3b7e4b81d658b, grp: d04f6a0473680edf-b341277f9999b888. cancelled: 0, left time(ms): 14978, total cost(ms): 22, consume cost(ms): 22, received rows: 0, put rows: 0
W1017 07:07:15.790802  4497 data_consumer.cpp:267] kafka consume failed: 7c4601a90070e068-5df130e98935cf8c, msg: Decompression (codec 0x4) of message at 6245490 of 1240 bytes failed: Local: Not implemented
I1017 07:07:15.790853  4497 data_consumer.cpp:279] kafka consume done: 7c4601a90070e068-5df130e98935cf8c, grp: d04f6a0473680edf-b341277f9999b888. cancelled: 0, left time(ms): 14978, total cost(ms): 22, consume cost(ms): 22, received rows: 0, put rows: 0
I1017 07:07:15.790867  4497 data_consumer_group.cpp:94] all consumers are finished. shutdown queue. group id: d04f6a0473680edf-b341277f9999b888
I1017 07:07:15.790932  4496 data_consumer_group.cpp:144] consumer group done: d04f6a0473680edf-b341277f9999b888. consume time(ms)=23, received rows=0, received bytes=0, eos: 1, left_time: 14977, left_bytes: 4294967296, blocking get time(us): 23084, blocking put time(us): 0
```

### StarRocks version (Required)
3.1.3-384ba23554

### PR DESCRIPTION
**Pull request by imay**
Fixes #32945

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:

- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

File: thirdparty/build-thirdparty.sh [hunk 1]
```diff
@@ -593,7 +593,7 @@ build_librdkafka() {
 
     $CMAKE_CMD -DCMAKE_LIBRARY_PATH=$TP_INSTALL_DIR/lib -DCMAKE_INCLUDE_PATH=$TP_INSTALL_DIR/include \
         -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR -DRDKAFKA_BUILD_STATIC=ON -DWITH_SASL=ON -DWITH_SASL_SCRAM=ON \
-        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DCMAKE_INSTALL_LIBDIR=lib
+        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DCMAKE_INSTALL_LIBDIR=lib -DWITH_ZSTD=ON
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:596]: our zstd library is not built separately, it was part of the arrow build which is after this librdkafka build, this change won't work won't adjusting the build order.

Comment (imay) [reply thirdparty/build-thirdparty.sh:596]: good catch, I will change the order

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

File: thirdparty/build-thirdparty.sh [hunk 2]
```diff
@@ -591,9 +591,10 @@ build_librdkafka() {
 
     cd $TP_SOURCE_DIR/$LIBRDKAFKA_SOURCE
 
+    mkdir -p sr_build && cd sr_build
     $CMAKE_CMD -DCMAKE_LIBRARY_PATH=$TP_INSTALL_DIR/lib -DCMAKE_INCLUDE_PATH=$TP_INSTALL_DIR/include \
         -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR -DRDKAFKA_BUILD_STATIC=ON -DWITH_SASL=ON -DWITH_SASL_SCRAM=ON \
-        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DCMAKE_INSTALL_LIBDIR=lib
+        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DWITH_ZSTD=ON -DCMAKE_INSTALL_LIBDIR=lib ..
```
Comment (kevincai) [inline thirdparty/build-thirdparty.sh:597]:
```
--- a/thirdparty/build-thirdparty.sh
+++ b/thirdparty/build-thirdparty.sh
@@ -593,7 +593,7 @@ build_librdkafka() {
 
     $CMAKE_CMD -DCMAKE_LIBRARY_PATH=$TP_INSTALL_DIR/lib -DCMAKE_INCLUDE_PATH=$TP_INSTALL_DIR/include \
         -DBUILD_SHARED_LIBS=0 -DCMAKE_INSTALL_PREFIX=$TP_INSTALL_DIR -DRDKAFKA_BUILD_STATIC=ON -DWITH_SASL=ON -DWITH_SASL_SCRAM=ON \
-        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DCMAKE_INSTALL_LIBDIR=lib
+        -DRDKAFKA_BUILD_EXAMPLES=OFF -DRDKAFKA_BUILD_TESTS=OFF -DWITH_SSL=ON -DWITH_ZSTD=ON -DCMAKE_INSTALL_LIBDIR=lib -DZSTD_INCLUDE_DIR=$TP_INSTALL_DIR/include/zstd
 
     ${BUILD_SYSTEM} -j$PARALLEL
     ${BUILD_SYSTEM} install
```

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

File: thirdparty/build-thirdparty.sh (hunk 2 above)
Comment (imay) [reply thirdparty/build-thirdparty.sh:598]: Thank you so much Kevin for pointing it out.
I fixed it in the newest version and also I let librdkafka use the LZ4 in our version rather than its own.

**Comment by wanpengfei-git** [comment]
#### [FE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [BE Incremental Coverage Report]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by kevincai — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.2

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
