### PR TITLE
[SR-4535] Fix information_schema.CHARACTER_MAXIMUM_LENGTH & CHARACTER_OCTET_LENGTH

### LINKED ISSUE #195: trino connect starrocks success ，but get none table in my created schema
### Steps to reproduce the behavior (Required)
1. i try to connect starrocks use  trino-server-355
2. this is the file content i put into trino catalog directory ，file name is doris.properties 
      connector.name=mysql
      connection-url=jdbc:mysql://10.1.8.143:9030
      connection-user=root
      connection-password=
      case-insensitive-name-matching=true

3. i get this with command “show catalogs”  and  it show my starrocks's catalag “doris”
      trino:dw> show catalogs;
     Catalog   
      ------------
         clickhouse 
         doris      
         hive       
         hive1      
         iceberg    
         jmx        
         kudu       
         oracle     
         system     
        (9 rows)
     Query 20210913_063107_00042_yjd54, FINISHED, 3 nodes
     Splits: 53 total, 53 done (100.00%)
     0.23 [0 rows, 0B] [0 rows/s, 0B/s]

4.  then i get this result with command “show   shcemas from doris ;” 

     trino:dw> show schemas from doris;
       Schema       
       --------------------
        _statistics_       
        dw                 
        example_db         
        information_schema 
        tests              
       (5 rows)

     Query 20210913_063315_00043_yjd54, FINISHED, 4 nodes
     Splits: 53 total, 53 done (100.00%)
     0.25 [5 rows, 72B] [19 rows/s, 287B/s]

5.  when i want to see table ,i  exec this command "show tables from doris.dw" ,but it show nothing。

        trino:dw> show tables from doris.dw;
        Table 
       -------
       (0 rows)

       Query 20210913_063526_00045_yjd54, FINISHED, 4 nodes
       Splits: 53 total, 53 done (100.00%)
       0.26 [0 rows, 0B] [0 rows/s, 0B/s]

6. this is the table when i  use mysql client to exec  commend  “show tables from dw;”
      MySQL [(none)]> show tables from dw;
     +----------------------------------+
     | Tables_in_dw                     |
     +----------------------------------+
     | DICTIONARY_DORIS                 |
     | GLOG_DEPOSIT                     |
     | GLOG_LOGIN                       |
     | GLOG_LOGIN_BITMAP_MID            |
     | GLOG_LOGIN_RATIO                 |
     | GLOG_LOGOUT_AVGTIME              |
     | GLOG_LTV                         |
     | GLOG_M_LOGIN_RT                  |
     | GLOG_M_RETAIN_RT                 |
     | GLOG_NEWLOGIN                    |
     | GLOG_NEWLOGIN_RETAIN             |
     | GLOG_OLNUM                       |
     | ZZ_LOGIN                         |
     | ZZ_LOGIN_T                       |
     ......
    +----------------------------------+
     46 rows in set (0.01 sec)

### Real behavior (Required)
     i'm disturbed why trino can connect starrocks, but cant get  my tables in schema "dw" ,  also cant query table in starrocks.
     before this i update the version from 1.17 to 1.18.2  , detail step is ：
        1）replace  /fe/ bin，/fe/lib， /fe/spark-dpp  this three directory
        2）replace  /be/bin，/be/lib，/be/www  this three directory
### StarRocks version (Required)
  StarRocks-1.18.2

### PR DESCRIPTION
**Pull request by Astralidea**
As mysql dev doc
https://dev.mysql.com/doc/refman/5.7/en/information-schema-columns-table.html
CHARACTER_MAXIMUM_LENGTH should set current length.
CHARACTER_OCTET_LENGTH because of UTF-8 should * 3.

### CODE REVIEW

**Review by imay — DISMISSED** [review]

**Comment by Astralidea** [comment]
run starrocks_be_unittest

File: be/src/exec/schema_scanner/schema_columns_scanner.cpp [hunk 1]
```diff
@@ -271,15 +271,28 @@ Status SchemaColumnsScanner::fill_one_row(Tuple* tuple, MemPool* pool) {
...
+    }
     // CHARACTER_OCTET_LENGTH
     {
         int data_type = _desc_result.columns[_column_index].columnDesc.columnType;
         if (data_type == TPrimitiveType::VARCHAR || data_type == TPrimitiveType::CHAR) {
             void* slot = tuple->get_slot(_tuple_desc->slots()[9]->tuple_offset());
             int64_t* str_slot = reinterpret_cast<int64_t*>(slot);
             if (_desc_result.columns[_column_index].columnDesc.__isset.columnLength) {
-                *str_slot = _desc_result.columns[_column_index].columnDesc.columnLength;
+                *str_slot = _desc_result.columns[_column_index].columnDesc.columnLength * 3;
```
Comment (starrocks-xueli) [inline be/src/exec/schema_scanner/schema_columns_scanner.cpp:295]: It's better to add some comment why 3 is multiplied here.

**Comment by Astralidea** [comment]
run starrocks_tscancode

**Review by starrocks-xupeng — APPROVED** [review]

**Review by imay — APPROVED** [review]
