### PR TITLE
[BugFix] Do not register load reporting tasks to ProfileReportWorker for stream load

### LINKED ISSUE #15918: stream load shouldn't register to ProfileReportWorker
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. CREATE a stream load

### Expected behavior (Required)
stream load not register to ProfileReportWorker
### Real behavior (Required)
stream load register to ProfileReportWorker
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
bfdcacf

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Current we don't support stream load's progress report, and shouldn't register it into ProfileReportWorker.
To achieve this, we set their query option's load job type in FE, then plan_fragment_executor.cpp will not
register them in open function.
Besides, in this pr, we will unregister the load_task when exists error during process of report.

Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15918

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 1 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[720]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[720]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1312]|

**Review by meegoo — DISMISSED** [review]

File: be/src/exec/pipeline/query_context.cpp [hunk 1]
```diff
@@ -464,11 +468,15 @@ void QueryContextManager::report_fragments(
             FragmentContext* fragment_ctx = need_report_fragment_context[i].get();
 
             if (fragment_ctx->all_pipelines_finished()) {
```
Comment (chaoyli) [inline be/src/exec/pipeline/query_context.cpp:470]: Why unregister the profile when the pipeline finished?

File: be/src/runtime/fragment_mgr.cpp [hunk 2]
```diff
@@ -591,12 +591,16 @@ void FragmentMgr::report_fragments_with_same_host(
 
             if (executor->is_done()) {
                 reported[i] = true;
```
Comment (chaoyli) [inline be/src/runtime/fragment_mgr.cpp:593]: Why unregister the profile when the executor done?

Comment (xiaoyong-z) [reply be/src/runtime/fragment_mgr.cpp:593]: At the end of fragment instance execution( function '_open_internal_vectorized'), BE will send_report to FE through coordinator_callback function. 
ProfileReportWorker is not necessary to send report to FE at the end of fragment instance.

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 2 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/routineload/RoutineLoadJob.java|0|1|00.00%|[720]|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|1|00.00%|[1312]|

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by trueeyu** [comment]
https://github.com/Mergifyio backport branch-2.5
