### PR TITLE
[BugFix] Maintaining consistency in BE and FE for the parameter validtion in LEAD/LAG function

### LINKED ISSUE #22945: lead/lag fucntion may lead be crash
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `common_duplicate` (
  `c0` int(11) NOT NULL COMMENT "",
  `c1` int(11) NOT NULL COMMENT "",
  `c2` varchar(500) NOT NULL COMMENT "",
  `c3` varchar(500) NULL COMMENT "",
  `c4` float NULL COMMENT "",
  `c5` decimal128(38, 20) NOT NULL COMMENT "",
  `c6` date NOT NULL COMMENT "",
  INDEX index1_c0 (`c0`) USING BITMAP
) ENGINE=OLAP
DUPLICATE KEY(`c0`, `c1`, `c2`)
COMMENT "OLAP"
PARTITION BY RANGE(`c1`)
(PARTITION p0 VALUES [("0"), ("500000")),
PARTITION p500000 VALUES [("500000"), ("1000000")))
DISTRIBUTED BY HASH(`c0`, `c1`, `c2`) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"bloom_filter_columns" = "c3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

insert into common_duplicate values (1, 1, 'a', 'b', 1.23, 3.33, '2021-11-11'),(2, 600000, 'aa', 'bb', 2.23, 4.33, '2022-12-11'),(3, 400000, 'aaa', 'bbb', 3.23, 5.33, '2022-06-11');

select c0, lead(c0, 5, abs(1000)) over() from common_duplicate;


```

### Expected behavior (Required)
ERROR 1064 (HY000): Getting analyzing error. Detail message: The type of the third parameter of LEAD/LAG not match the type FLOAT.
### Real behavior (Required)
BE crash when BE package is debug mode.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by packy92**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #22945

## Problem Summary(Required):

The root cause of the problem is that the BE sets the corresponding column based on the `isConst` and `isNullable` information of the third parameter of the lead/lag function passed by the FE. If `isNullable=true`, a const null column will be set. However, the `isNullable` information provided by the FE is not always accurate, and it may mistakenly set a non-null column as nullable. This causes the column set by the BE for the third parameter to not match the actual input column in the chunk, leading to a BE crash. Considering that FE is currently unable to accurately set the isNullable information, the only option is to temporarily disable the cases when `isNullable=true`.

```
for (size_t j = 0; j < _agg_expr_ctxs[i].size(); ++j) {
            // Currently, only lead and lag window function have multi args.
            // For performance, we do this special handle.
            // In future, if need, we could remove this if else easily.
            if (j == 0) {
                _agg_intput_columns[i][j] =
                        ColumnHelper::create_column(_agg_expr_ctxs[i][j]->root()->type(), is_input_nullable);
            } else {
                _agg_intput_columns[i][j] = ColumnHelper::create_column(_agg_expr_ctxs[i][j]->root()->type(),
                                                                        _agg_expr_ctxs[i][j]->root()->is_nullable(),
                                                                        _agg_expr_ctxs[i][j]->root()->is_constant(), 0);
            }
        }


ColumnPtr ColumnHelper::create_column(const TypeDescriptor& type_desc, bool nullable, bool is_const, size_t size,
                                      bool use_adaptive_nullable_column) {
    auto type = type_desc.type;
    if (is_const && (nullable || type == TYPE_NULL)) {
        return ColumnHelper::create_const_null_column(size);
    } else if (type == TYPE_NULL) {
        if (use_adaptive_nullable_column) {
            return AdaptiveNullableColumn::create(BooleanColumn::create(size), NullColumn::create(size, DATUM_NULL));
        } else {
            return NullableColumn::create(BooleanColumn::create(size), NullColumn::create(size, DATUM_NULL));
        }
    }
```

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 22 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|13|14|92.86%|[119]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/WindowTransformer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 21 / 22 (95.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/AnalyticAnalyzer.java|13|14|92.86%|[119]|
|:large_blue_circle:|com/starrocks/sql/optimizer/transformer/WindowTransformer.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/FunctionAnalyzer.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/InsertPlanner.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java [hunk 1]
```diff
@@ -89,14 +90,33 @@ public static void verifyAnalyticExpression(AnalyticExpr analyticExpr) {
...
+                } catch (AnalysisException e) {
+                    throw new SemanticException("The third parameter of LEAD/LAG can't convert to " + firstType,
+                            analyticFunction.getChild(2).getPos());
                 }
+
+                // When the parameter is const and nullable in lead/lag, BE use create_const_null_column to store it.
+                // but the nullable info in FE is a more relax than BE (such as the nullable info in upper('a') is true,
+                // but the actually derived column in BE is not nullableColumn)
+                // which make the input colum in chunk not match the _agg_input_column in BE. so add this check in FE.
+                if (!analyticFunction.getChild(2).isLiteral() && analyticFunction.getChild(2).isNullable()) {
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java:114]: third param can be non-literal?

Comment (packy92) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/AnalyticAnalyzer.java:114]: Yes, our BE had supported const function call if it's a non-nullable. Such as `select c0, lead(c2, 5, day('2021-01-02')) over() from common_duplicate;`

**Review by Seaven — APPROVED** [review]

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
