### PR TITLE
[BugFix] Fix multiple be export empty file to oss without broker bug

### LINKED ISSUE #9999: [BugFix] fix multiple be export empty file to oss without broker bug
If there are 3 BE, and only 1 BE has data, export will generate 2 empty temp file and 1 temp file with data on remote export path.
Howerver, in current implementation, for empty file, S3OutputStream will skip it, and finally only generate 1 temp file with data, which leads to moveTmpFiles() in FE can not find the temp file.

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9999

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

If there are 3 BE, and only 1 BE has data, export will generate 2 empty temp file and 1 temp file with data on remote export path.
Howerver, in current implementation, for empty file, S3OutputStream will skip it, and finally only generate 1 temp file with data, which leads to moveTmpFiles() in FE can not find the temp file.

### CODE REVIEW

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|1|00.00%|[651]|
|:large_blue_circle:|com/starrocks/task/ExportExportingTask.java|0|11|00.00%|[139, 233, 234, 235, 236, 237, 246, 247, 248, 249, 250]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|1|00.00%|[854]|

**Comment by xiaoyong-z** [comment]
run starrocks_be_build

File: be/src/io/s3_output_stream.cpp [hunk 1]
```diff
@@ -90,9 +90,6 @@ Status S3OutputStream::create_multipart_upload() {
 Status S3OutputStream::singlepart_upload() {
     VLOG(12) << "Uploading s3://" << _bucket << "/" << _object << " via singlepart upload";
     DCHECK(_upload_id.empty());
-    if (_buffer.empty()) {
```
Comment (chaoyli) [inline be/src/io/s3_output_stream.cpp:93]: Why create a file when the file is empty?

**Review by chaoyli — DISMISSED** [review]

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java [hunk 2]
```diff
@@ -290,8 +290,11 @@ private void plan(ExportStmt stmt) throws UserException {
 
                     Long assignedBytes = bytesPerBe.get(backendId);
                     if (assignedBytes == null || assignedBytes < maxBytesPerBe) {
-                        taskTabletLocations.add(scanRangeLocations);
-                        bytesPerBe.put(backendId, assignedBytes != null ? assignedBytes + dataSize : dataSize);
+                        // if dataSize == 0, skip this scanRange
+                        if (dataSize > 0) {
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java:294]: dataSize depend on BE report, may be inconsistent with actual size.

**Review by dirtysalt — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java (hunk 2 above)
Comment (xiaoyong-z) [reply fe/fe-core/src/main/java/com/starrocks/load/ExportJob.java]: In some bad cases this may be a bug, i maintain the behaviour as the original export, it still export the empty file.
In most cases, a tablet will not be empty, the cost of exporting empty file can be ignored

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by xiaoyong-z** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/load/ExportJob.java|0|1|00.00%|[651]|
|:large_blue_circle:|com/starrocks/task/ExportExportingTask.java|0|11|00.00%|[139, 233, 234, 235, 236, 237, 246, 247, 248, 249, 250]|
|:large_blue_circle:|com/starrocks/fs/hdfs/HdfsFsManager.java|0|1|00.00%|[854]|

**Review by chaoyli — APPROVED** [review]

**Review by meegoo — APPROVED** [review]
