### PR TITLE
[Enhancement]Optimize `find_buckets_to_move` to make sure find a move solution

### LINKED ISSUE #7577: query error from primary table when enable_persistent_index = true
### Steps to reproduce the behavior (Required)
1. create primary table with enable_persistent_index = true:
```
create table customer_demographics
(
    cd_demo_sk                integer               not null,
    cd_gender                 char(1)                       ,
    cd_marital_status         char(1)                       ,
    cd_education_status       char(20)                      ,
    cd_purchase_estimate      integer                       ,
    cd_credit_rating          char(10)                      ,
    cd_dep_count              integer                       ,
    cd_dep_employed_count     integer                       ,
    cd_dep_college_count      integer
)
primary key (cd_demo_sk)
distributed by hash(cd_demo_sk) buckets 5
properties(
    "replication_num"="1","enable_persistent_index" = "true"
);
```
2. stream load:
```
[tiannan@starrocks-sandbox04 tn_StarRocksTest]$ curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/tn_StarRocksTest/lib/../common/data/tpcds/customer_demographics.dat -XPUT -H "label:tpcds_load_label_87383b4e_f14a_11ec_8896_00163e0e551" -H "column_separator:|" http://***。***。***。***:8434/api/persistent_idx_sqlset_74eb6f88_f14a_11ec_8896_00163e0e550b/customer_demographics/_stream_load
{
    "TxnId": 412614,
    "Label": "tpcds_load_label_87383b4e_f14a_11ec_8896_00163e0e551",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 1920800,
    "NumberLoadedRows": 1920800,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 78739296,
    "LoadTimeMs": 1185,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 0,
    "ReadDataTimeMs": 610,
    "WriteDataTimeMs": 1168,
    "CommitAndPublishTimeMs": 14
```

3. query error when select count(*) from table:
```
mysql> select count(*) from customer_demographics;
ERROR 1064 (HY000): get_applied_rowsets failed, tablet updates is in error state: tablet:7938844 primary index commit failed: Internal error: move_buckets failed
/root/starrocks/be/src/storage/persistent_index.cpp:1585 writer.write_shard(_key_size, value_size, npage_hint, kvs)
/root/starrocks/be/src/storage/persistent_index.cpp:1627 _flush_l0()
/root/starrocks/be/src/storage/persistent_index.cpp:1374 _check_and_flush_l0()
```

### Expected behavior (Required)
query ok when enable_persistent_index = false:
image

### Real behavior (Required)
query error when enable_persistent_index = true:
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 9ad21f1 |
+----------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7577 #4775

## Problem Summary(Required) ：

Currently, find_buckets_to_move using a brute force search algorithm to search buckets to move, only search 1/2/3 bucket movements which may can't find a solution.

### CODE REVIEW

**Comment by sevev** [comment]
run all

**Comment by sevev** [comment]
run starrocks_be_unittest

File: be/src/storage/persistent_index.cpp [hunk 1]
```diff
@@ -185,83 +185,113 @@ struct MoveDest {
     bool operator<(const MoveDest& rhs) const { return npack < rhs.npack; }
 };
 
-static Status find_buckets_to_move(uint32_t pageid, size_t min_pack_to_move, const uint8_t* bucket_packs_in_page,
-                                   std::vector<BucketToMove>* buckets_to_move) {
+static Status get_move_buckets(size_t target, const uint8_t* bucket_packs_in_page, std::vector<int32_t>* res) {
```
Comment (decster) [inline be/src/storage/persistent_index.cpp:188]:
```
static std::vector<int8_t> get_move_buckets2(size_t target, const uint8_t* bucket_packs_in_page) {
    vector<int8_t> idxes;
    idxes.reserve(bucket_per_page);
    int32_t total_buckets = 0;
    for (int8_t i=0;i<bucket_per_page;i++) {
        if (bucket_packs_in_page[i]>0) {
            idxes.push_back(i);
        }
        total_buckets+=bucket_packs_in_page[i];
    }
    std::sort(idxes.begin(), idxes.end(), [&](int8_t lhs, int8_t rhs) { return bucket_packs_in_page[lhs] < bucket_packs_in_page[rhs]; });
    // store idx if this sum value uses bucket_packs_in_page[idx], or -1
    std::vector<int8_t> dp(total_buckets + 1, -1);
    dp[0] = bucket_per_page; // assign an id that will never be used but >= 0
    int32_t valid_sum = total_buckets; // total_buckets is already a valid solution
    auto get_list_from_dp = [&] {
        vector<int8_t> ret;
        ret.reserve(16);
        while (valid_sum > 0) {
            ret.emplace_back(dp[valid_sum]);
            valid_sum -= bucket_packs_in_page[dp[valid_sum]];
        }
        return ret;
    };
    int32_t max_sum = 0; // current max sum
    for (int8_t idx = 0; idx < idxes.size(); idx++) {
        int8_t i = idxes[idx];
        for (int32_t v = 0; v <= max_sum; v++) {
            if (dp[v] < 0 || dp[v] == i) {
                continue;
            }
            int32_t nv = v + bucket_packs_in_page[i];
            if (dp[nv] >= 0) {
                continue;
            }
            dp[nv] = i;
            if (nv > max_sum) {
                max_sum = nv;
            }
            if (nv >= target) {
                valid_sum = std::min(valid_sum, nv);
                if (valid_sum == target) {
                    return get_list_from_dp();
                }
            }
        }
    }
    return get_list_from_dp();
}

```

**Review by decster — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
