### PR TITLE
[BugFix] fix follower starlet port not synced issue

### LINKED ISSUE #19250: [StarOS] 'Build Exec OlapScanNode fail, scan info is invalid' after upgrade cluster
### Steps to reproduce the behavior (Required)
````sql
mysql> select * from t2;
ERROR 1064 (HY000): Build Exec OlapScanNode fail, scan info is invalid,Failed to get scan range, no queryable replica found in tablet: 358365
````

### Expected behavior (Required)
select execute success

### Real behavior (Required)
error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN a69a535fa |
+-------------------+
1 row in set (0.20 sec)
```

### PR DESCRIPTION
**Pull request by kevincai**
* FE follower can't get starlet port from loaded image because it is not added. Can't directly append the port into the image section because of image backward compatibility.
* fix it by searching with worker's heartbeat port again

## What type of PR is this：
- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19250

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto backported to target branch
  - [X] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java [hunk 1]
```diff
@@ -448,8 +449,23 @@ public Set<Long> getBackendIdsByShard(long shardId) throws UserException {
                             .getBackendIdWithStarletPort(pair[0], Integer.parseInt(pair[1]));
 
                     if (backendId == -1L) {
-                        LOG.warn("backendId for {} is -1", workerAddr);
-                        continue;
+                        LOG.info("can't find backendId with starletPort for {}.", workerAddr);
```
Comment (starrocks-xupeng) [inline fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java:452]: print starletPort?

**Review by starrocks-xupeng — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java (hunk 1 above)
Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java:452]: starletport is parsed from workerAddr which is already logged.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/lake/StarOSAgent.java|10|10|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java (hunk 1 above)
Comment (starrocks-xupeng) [reply fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java:452]: bePort is printed

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/lake/StarOSAgent.java:452]: i know, beport is not implied in `workerAddr`, so need to be printed in log, starletPort is already implied in workerAddr, no need to print again. 

`can't find backendId with starletPort` means it can't find the BE node with given host and starletPort, not necessary mean "here is the starletPort I used to search`.

**Review by sduzh — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Comment by tracymacding** [comment]
run starrocks_admit_test

**Comment by tracymacding** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
