### PR TITLE
[BugFix] Fix bug inconsistent metadata when out-of-order

### LINKED ISSUE #11066: Task inconsistent metadata when executing too fast
### Steps to reproduce the behavior (Required)
drop database test_insert_overwrite_8bca906e_2f50_11ed_9055_00163e0e489a;
create database test_insert_overwrite_8bca906e_2f50_11ed_9055_00163e0e489a;
use test_insert_overwrite_8bca906e_2f50_11ed_9055_00163e0e489a;
admin set frontend config("enable_experimental_mv" = "true");
CREATE TABLE `t1` (
                    `k1` int,
                    `k2` int
                ) ENGINE=OLAP
                DUPLICATE KEY(`k1`)
                COMMENT "OLAP"
                DISTRIBUTED BY HASH(`k1`) BUCKETS 3
                                                PROPERTIES (
"replication_num" = "1"
)
                CREATE TABLE `t2` (
                    `k1` int,
                    `k2` int
                ) ENGINE=OLAP
                DUPLICATE KEY(`k1`)
                COMMENT "OLAP"
                DISTRIBUTED BY HASH(`k1`) BUCKETS 3
                                                PROPERTIES (
"replication_num" = "1"
)
CREATE MATERIALIZED VIEW mv1
                 DISTRIBUTED BY HASH(k1) BUCKETS 10
                 REFRESH ASYNC
                 AS SELECT k1,k2 FROM t2;
INSERT INTO t2 VALUES (1,1);
SELECT * FROM INFORMATION_SCHEMA.task_runs
                       WHERE query_id='t1f5b858b-3028-11ed-b061-0242f64e6f65'

### Expected behavior (Required)
3 FE query is same
### Real behavior (Required)
leader is ok but follower not
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11066

## Problem Summary(Required) ：

This is because Task scheduling may form 2 CREATEs followed by 4 updates. The update order of the master may be different from the update order of the follower, so the disorder should be dealt with during playback.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 13 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|13|00.00%|[501, 502, 503, 504, 505, 507, 508, 509, 510, 511, 512, 514, 515]|

File: fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java [hunk 1]
```diff
@@ -497,7 +497,23 @@ public void replayUpdateTaskRun(TaskRunStatusChange statusChange) {
                 return;
             }
 
-            TaskRun pendingTaskRun = taskRunQueue.poll();
+            // It is possible to update out of order for priority queue.
+            Map<String, TaskRun> pendingIndex = Maps.newHashMap();
+            while (!taskRunQueue.isEmpty()) {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/scheduler/TaskManager.java:502]: I think you can judge the queryID here.

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 14 (78.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|11|14|78.57%|[515, 516, 517]|

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4
