### PR TITLE
[SR-4368] Disable cast statements when creating materialized views

### LINKED ISSUE #115: using a cast expression when creating a materialized view may result in a be null pointer error
using a cast expression when creating a materialized view may result in a be null pointer error

as illustrated below

``` 
-- create table
CREATE TABLE `test`.`demo_spark_load_tbl` (
`k1`  varchar(50) NULL  COMMENT "",
`v1`  String      NULL  COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`k1` )
COMMENT "OLAP"
DISTRIBUTED BY HASH(`v1` ) BUCKETS 3
PROPERTIES (
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
```

```
-- create materialized views
create materialized view groupk1
as
select k1, sum(cast(v1 as double))
from demo_spark_load_tbl
group by k1 
order by k1;
```

this will cause a null point error in be

```
crash
cProgram terminated with signal SIGSEGV, Segmentation fault.
#0 0x0000000003ab9a36 in doris::AggregateInfo::update (this=0x0, dst=0x7fcf215281801 src=..., mem_pool=0x0) at /home/disk2/StarRocks/be/src/olap/aggregate_func.h:69 69 _update_fn(dst, src, mem_pool);
[Current thread is 1 (Thread 0x7fcf2152e700 (LWP 163957))] 
(gdb) bt
#0 0x0000000003ab9a36 in doris::AggregateInfo::update (this=0x0, dst=0x7fcf21528180, src=..., mem_pool=0x0) at /home/disk2/StarRocks/be/src/olap/aggregate_func.h:69
 #1 0x0000000003ab9ab6 xllb04bdx/fcf21528180, src=..., mem_pool=0x0) at /home/disk2/StarRocks/be/src/olap/field.h:94
#2 0x0000000004el05dc in doris::agg_update_row<doris::RowCursor, doris::RowCursor> (dst=0x7fcf21528200, src=..., mem_pool=0x0) at /home/disk2/StarRocks/be/src/olap/row.h:155
#3 0x0000000004e03fa0 in doris::RowBlockMerger::merge (this=0x7fcf215284a0, row_block_arr=..., rowset_writer=0xb217c00, merged_rows=0x7fcf215284e8) at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:964
#4 0x0000000004e07853 in doris::SchemaChangeWithSorting::_internal_sorting (this=0xllafe460, row_block_arr=..., version=..., version_hash=8594233787343111260, new_tablet=...,
new_rowset_type=doris::BETA_ROWSET, segments_overlap=doris::NONOVERLAPPING, rowset=0x7fcf215286e0) at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:1453
#5 0x0000000004e068b7 in doris::SchemaChangeWithSorting::process (this=0xllafe460, rowset_reader=..., new_rowset_writer=0xb217a40, new_tablet=..., base_tablet=...)
at /home/disk2/StarRocks/be/src/olap/schema_change・cpp:1356
#6 0x0000000004e0a9f6 in doris::SchemaChangeHandler::_convert_historical_rowsets (sc_params=...) at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:1859
#7 0x0000000004e096fd in doris::SchemaChangeHandler::_do_process_alter_tablet_v2_normal (this=0x7fcf215296f0, request=..., base_tablet=..., new_tablet=...)
at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:1724
#8 0x0000000004e08833 in doris::SchemaChangeHandler::_do_process_alter_tablet_v2 (this=0x7fcf215296f0, request=...) at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:1568 in 
#9 0x0000000004e0815b doris::SchemaChangeHandler::process_alter_tablet_v2 (this=0x7fcf215296f0, request=...) at /home/disk2/StarRocks/be/src/olap/schema_change.cpp:1506
#10 0x0000000004d62dce in doris::EngineAlterTabletTask::execute (this=0x7fcf215299b0) at /home/disk2/StarRocks/be/src/olap/task/engine_alter_tablet_task.cpp:43
#11 0x000000000384f896 in doris::StorageEngine::execute_task (this=0xa638840, task=0x7fcf215299b0) at /home/disk2/StarRocks/be/src/olap/storage_engine.cpp:916
#12 0x0000000004263abb in doris::TaskWorkerPool::_alter_tablet (this=0xa63a5a0, worker_pool_this=0xa63a5a0, agent_task_req=..., signature=10168, task_type=doris::TTaskType::ALTER, finish_task_request= /home/disk2/StarRocks/be/src/agent/task_worker_pool.cpp:508

```

The reason is that fe ignore `cast`  when creating the materialized view.  So be will try to perform `sum` aggregation for `k1` whose type is `string`,  but be does not support sum aggregation for string types

### PR DESCRIPTION
**Pull request by sevev**
Disable cast when creating materialized views

### CODE REVIEW

**Comment by Linkerist** [comment]
As mentioned before, we use github issue to manage PRs now, so describe the background of PR on issue, and then create PR to resolve this issue.

**Comment by sevev** [comment]
ATT，see https://github.com/StarRocks/starrocks/issues/115

File: fe/fe-core/src/main/java/com/starrocks/analysis/MVColumnOneChildPattern.java [hunk 1]
```diff
@@ -42,6 +42,9 @@ public boolean match(Expr expr) {
         if (functionCallExpr.getChildren().size() != 1) {
             return false;
         }
+        if (functionCallExpr.getChild(0) instanceof CastExpr) {
+            return false;
+        }
         if (functionCallExpr.getChild(0).unwrapSlotRef() == null) {
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/analysis/MVColumnOneChildPattern.java:48]: if FE upgrade to new version & user use cast create materialized view.
it will replay log OP_ALTER_JOB_V2 and run to CreateMaterializedViewStmt cause FE can not startup any more.

Comment (sevev) [reply fe/fe-core/src/main/java/com/starrocks/analysis/MVColumnOneChildPattern.java]: https://github.com/StarRocks/starrocks/pull/78/commits/5a906371b4af4bc2cade49c0ad24e085c1f5d415

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
