### PR TITLE
[Enhancement] optimize mv union rewrite

### LINKED ISSUE #23028: mv not work when query with agg
<!-- (At least include the following, feel free to add if you have more content) -->

`explain verbose  select count(event_id) from event.event1`  will not rewrite by `olap_mv1`   

and  `explain verbose  select count(event_type) from event.event1` work well

I think `query output column` no  `mv's predicate  column`

### Steps to reproduce the behavior (Required)
```
MySQL [event]> select * from event1;
+----------+------------+---------------------+
| event_id | event_type | event_time          |
+----------+------------+---------------------+
|      129 | click1     | 2023-01-06 12:12:23 |
|      128 | click      | 2023-01-06 18:12:23 |
|      128 | click      | 2023-01-05 12:12:23 |
+----------+------------+---------------------+
3 rows in set (0.02 sec)

MySQL [event]> show create table olap_mv1;
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Materialized View | Create Materialized View                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| olap_mv1          | CREATE MATERIALIZED VIEW `olap_mv1`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`event_time`)
DISTRIBUTED BY HASH(`event_id`) BUCKETS 1
REFRESH ASYNC START("2023-05-06 18:00:00") EVERY(INTERVAL 1 DAY)
PROPERTIES (
"replication_num" = "1",
"storage_medium" = "HDD",
"partition_refresh_number" = "1",
"force_external_table_query_rewrite" = "true",
"prefer_compute_node" = "false",
"compute_node_selector" = ""
)
AS SELECT `event1`.`event_id`, `event1`.`event_type`, `event1`.`event_time`
FROM `event`.`event1`
WHERE `event1`.`event_type` = 'click'; |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### Expected behavior (Required)

`explain verbose  select count(event_id) from event.event1`  can be rewrited by `olap_mv1`

### Real behavior (Required)

### StarRocks version (Required)
 -  `2.5`

### PR DESCRIPTION
**Pull request by ABingHuang**
Enhance union rewrite, to support compensated predicates reference columns not in query's outputs.

Fixes #23028

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 113 / 118 (95.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|64|69|92.75%|[1358, 1422, 1940, 1941, 1942]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java|46|46|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewriteContext.java|3|3|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 113 / 118 (95.76%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|64|69|92.75%|[1358, 1422, 1940, 1941, 1942]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java|46|46|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewriteContext.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 1]
```diff
@@ -1393,18 +1405,61 @@ private OptExpression tryUnionRewrite(RewriteContext rewriteContext,
...
+        }
+        // check every columns to enforce should be in the Scan Operator
+        for (ColumnRefOperator column : columns) {
+            if (queryRefFactory.getRelationId(column.getId()) == -1) {
+                return null;
+            }
+        }
+        ColumnEnforcer columnEnforcer = new ColumnEnforcer(query, columns);
+        OptExpression newQuery = columnEnforcer.enforce();
+        mvRewriteContext.setEnforcedColumns(columnEnforcer.getEnforcedColumns());
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1427]: what if enforce failed ?

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1427]: first, it has been checked in line 1420-1424.
secondly, if enforce failed, rewrite predicate will fail again, it will lead to rewrite failure.

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java [hunk 2]
```diff
@@ -0,0 +1,109 @@
...
+import com.starrocks.sql.optimizer.operator.Projection;
+import com.starrocks.sql.optimizer.operator.logical.LogicalOperator;
+import com.starrocks.sql.optimizer.operator.logical.LogicalScanOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ColumnRefOperator;
+import com.starrocks.sql.optimizer.operator.scalar.ScalarOperator;
+
+import java.util.List;
+import java.util.Map;
+
+public class ColumnEnforcer {
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:33]: please add some comments

**Review by packy92 — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 3]
```diff
@@ -1351,29 +1351,41 @@ private OptExpression tryUnionRewrite(RewriteContext rewriteContext,
         ScalarOperator mvOtherPreds = MvUtils.canonizePredicate(Utils.compoundAnd(
                 mvCompensationToQuery.getRangePredicates(),
                 mvCompensationToQuery.getResidualPredicates()));
+        List<ScalarOperator> rewrittenFailedPredicates = Lists.newArrayList();
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1354]: Can we move `rewrittenFailedPredicates `  to `EquationRewriter` as `AggregateFunctionRewriter`, so can simplify this retry policy?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java [hunk 4]
```diff
@@ -0,0 +1,109 @@
...
+    private class ColumnEnforcerVisitor extends OptExpressionVisitor<OptExpression, EnforceContext> {
+        @Override
+        public OptExpression visitLogicalTableScan(OptExpression optExpression, EnforceContext context) {
+            LogicalScanOperator scanOperator = optExpression.getOp().cast();
+            LogicalScanOperator.Builder builder = OperatorBuilderFactory.build(scanOperator);
+            builder.withOperator(scanOperator);
+            Map<ColumnRefOperator, Column> columnRefOperatorColumnMap = Maps.newHashMap(scanOperator.getColRefToColumnMetaMap());
+            for (ColumnRefOperator columnRef : columnsToEnforce) {
+                for (Map.Entry<Column, ColumnRefOperator> entry : scanOperator.getColumnMetaToColRefMap().entrySet()) {
+                    if (entry.getValue().equals(columnRef)) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:72]: how about use `scanOperator.getColRefToColumnMetaMap()` to check ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java [hunk 5]
```diff
@@ -0,0 +1,109 @@
...
+
+import java.util.List;
+import java.util.Map;
+
+public class ColumnEnforcer {
+    private OptExpression optExpression;
+    private List<ColumnRefOperator> columnsToEnforce;
+    private EnforceContext enforceContext;
+
+    public ColumnEnforcer(
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:38]: `ColumnEnforcer ` will generate a new `OptExpression ` which its scan operator will only use the `columnsToEnforce` map and other operator is the same as old expression?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java [hunk 6]
```diff
@@ -0,0 +1,109 @@
...
+
+            if (optExpression.getOp().getProjection() != null) {
+                Map<ColumnRefOperator, ScalarOperator> columnRefMap =
+                        Maps.newHashMap(optExpression.getOp().getProjection().getColumnRefMap());
+                for (ColumnRefOperator columnRef : localContext.enforcedColumns) {
+                    columnRefMap.put(columnRef, columnRef);
+                }
+                builder.setProjection(new Projection(columnRefMap));
+            }
+            OptExpression newOptExpression = OptExpression.create(builder.build(), inputs);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:103]: how can we ensure all the `columnRefMap ` is valid from ScanOperator's `columnsToEnforce`? Is that possible `columnRefMap` refers non-existed column from the new ScanOperator's?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1354]: yes, but scan operator will add columnsToEnforce into getColRefToColumnMetaMap, not only use columnsToEnforce.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:72]: first, it has been checked in line 1420-1424.
secondly, if enforce failed, rewrite predicate will fail again, it will lead to rewrite failure

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:38]: yes, but scan operator will add columnsToEnforce into getColRefToColumnMetaMap, not only use columnsToEnforce.

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:38]: should generator a new OptExpression instead of modifying it locally.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java (hunk 6 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java:103]: it has been checked in line 1420-1424.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1354]: here I just collect rewrittenFailedPredicates for union rewrite and try to rewrite it in tryRewritePredicates.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 124 / 132 (93.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|68|76|89.47%|[1358, 1371, 1373, 1422, 1444, 1950, 1951, 1952]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/scalar/FilterSelectivityEvaluator.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnEnforcer.java|46|46|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/MvRewriteContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ColumnRefOperator.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Review by packy92 — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
