### PR TITLE
[Enhancement] defensive strategy on on large mem allocation

### LINKED ISSUE #56906: [Enhancement] Defensive memory allocation policy, reject unreasonable large amount of memory allocation in mem_hook
#### Problem Statement

```
// malloc
void* my_malloc(size_t size) __THROW {
    STARROCKS_REPORT_LARGE_MEM_ALLOC(size);
    if (IS_BAD_ALLOC_CATCHED()) {
        FAIL_POINT_INJECT_MEM_ALLOC_ERROR(nullptr);
        // NOTE: do NOT call `tc_malloc_size` here, it may call the new operator, which in turn will
        // call the `my_malloc`, and result in a deadloop.
        TRY_MEM_CONSUME(STARROCKS_NALLOX(size, 0), nullptr);
        void* ptr = STARROCKS_MALLOC(size);
        if (UNLIKELY(ptr == nullptr)) {
            SET_EXCEED_MEM_TRACKER();
            MEMORY_RELEASE_SIZE(STARROCKS_NALLOX(size, 0));
        }
        return ptr;
    } else {
        void* ptr = STARROCKS_MALLOC(size);
        // NOTE: do NOT call `tc_malloc_size` here, it may call the new operator, which in turn will
        // call the `my_malloc`, and result in a deadloop.
        if (LIKELY(ptr != nullptr)) {
            MEMORY_CONSUME_SIZE(STARROCKS_NALLOX(size, 0));
        }
        return ptr;
    }
}
```

`my_malloc` is the hook function for all the memory allocation in backend process. Sometimes, there will be unreasonable large amount of memory allocation acquired. Although `vm.overcommit_memory = 1` means the process can allocate large amount of memory than the physical available memories, but it comes with prices, e.g., overhead in jemalloc metadata management, `vm.max_map_count` may also be exhausted, which leads other serious problems, such as thread creation fail, std::bad_alloc everywhere.

#### Suggested Enhancement

1. in `STARROCKS_REPORT_LARGE_MEM_ALLOC`, record the `IS_BAD_ALLOC_CATCHED` flag, LOG error if the large allocation is acquired without try...catch std::bad_alloc, it is an unknown risky code path, raise the log level to ERROR to draw attention
2. in `STARROCKS_REPORT_LARGE_MEM_ALLOC`, add a metrics to count the occurrence of large memory allocation without IS_BAD_ALLOC_CATCHED flag set to true. Take it as an indicator of potential memory problem in the system
3.  in`my_malloc`, if the `IS_BAD_ALLOC_CATCHED` is not true, and the acquired `size` is large than a certain threshold (could be the Backend process `mem_limit`), return nullptr or crash directly (whether crash or not, can be configurable). To avoid the actual memory allocation passed down to the jemalloc, and possibly exhausting the `vm.max_map_count` and causes more unexpected behavior.

### PR DESCRIPTION
**Pull request by kevincai**
## What I'm doing:

* check and reject large mem allocation if the upper level running without TRY_CATCH_BAD_ALLOC
* configurable parameter to return nullptr or crash directly
* don't bother turn on this check if available mem is less than 1GB

Fixes #56906

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [x] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [ ] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Comment by kevincai** [comment]
ignore merge branch-3.5

File: be/src/common/config.h [hunk 1]
```diff
@@ -83,6 +83,10 @@ CONF_String(mem_limit, "90%");
 // Enable the jemalloc tracker, which is responsible for reserving memory
 CONF_Bool(enable_jemalloc_memory_tracker, "true");
 
+// Whether crash if detecting a large memory allocation acquired
+// larger than physical memory without but not wrapping with TRY_CATCH_BAD_ALLOC
+CONF_mBool(abort_on_large_memory_allocation, "false");
```
Comment (trueeyu) [inline be/src/common/config.h:88]: Default set to true?

**Review by trueeyu — DISMISSED** [review]

**Review by trueeyu — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]
