### PR TITLE
[BugFix] Schema change failed because rowsets are compacted

### LINKED ISSUE #3397: schema change will fail because rowsets are compacted
### Steps to reproduce the behavior (Required)
No, I find the bug from code review.

### Expected behavior (Required)
schema change will not failed because of tablet compaction
### Real behavior (Required)
schema change will failed because rowsets may be compacted
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by DeepThinker666**
## What type of PR is this：
- [X] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #3397 

## Problem Summary(Required) ：

schema change may fail because that rowsets to change may be compacted. Fix this bug by preparing tablet reader ahead inside tablet meta lock.

### CODE REVIEW

**Review by sevev — APPROVED** [review]

**Comment by DeepThinker666** [comment]
run starrocks_be_unittest

**Comment by DeepThinker666** [comment]
run starrocks_be_unittest

File: be/src/storage/vectorized/schema_change.cpp [hunk 1]
```diff
@@ -1016,8 +1017,14 @@ Status SchemaChangeHandler::_do_process_alter_tablet_v2_normal(const TAlterTable
             return status;
         }
         LOG(INFO) << "versions to be changed size:" << versions_to_be_changed.size();
+        Schema base_schema = ChunkHelper::convert_schema_to_format_v2(base_tablet->tablet_schema());
         for (auto& version : versions_to_be_changed) {
             rowsets_to_change.push_back(base_tablet->get_rowset_by_version(version));
+            // prepare tablet reader to prevent rowsets being compacted
+            std::unique_ptr<vectorized::TabletReader> tablet_reader =
+                    std::make_unique<TabletReader>(base_tablet, version, base_schema);
+            RETURN_IF_ERROR(tablet_reader->prepare());
```
Comment (chaoyli) [inline be/src/storage/vectorized/schema_change.cpp:1026]: Why to prepare() so many times?

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]
