### PR TITLE
[BugFix] Null date and datetime value for spark load is not consistent

### LINKED ISSUE #9496: Error query result
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
CREATE TABLE `aggregate_table_with_null2` ( `k1` date, `k2` datetime, `k3` char(20), `k4` varchar(20), `k5` boolean, `v1` bigint sum, `v2` bigint sum, `v3` bigint sum, `v4` bigint max, `v5` largeint max, `v6` float min, `v7` double min, `v8` decimal(27,9) sum ) ENGINE=OLAP AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) BUCKETS 3 PROPERTIES ( "replication_num" = "3", "storage_format" = "v2" );
```
2. INSERT INTO '....'
```
curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_16 http://ip:port/api/lcy/aggregate_table_with_null2/_stream_load

LOAD LABEL lcy.aggregate_table_with_null2 (DATA INFILE("hdfs://ip:port/user/nose-ut-data/data") INTO TABLE `aggregate_table_with_null2` (k1,k2,k3,k4,k5,v1,v2,v3,v4,v5,v6,v7,v8) ) WITH RESOURCE test_spark_resource_8beb613a_1232_11ed_8b93_00163e0e550b PROPERTIES("timeout"="300","max_filter_ratio"="0.5");
```
3. SELECT  '....'
```
select count(*),count(k1) from aggregate_table_with_null;
select count(*) from aggregate_table_with_null where k1 is null;
```
image

### Expected behavior (Required)
The query result is consistent with the actual one 2
### Real behavior (Required)
Error query result
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 12c19a2 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9496

## Problem Summary(Required) ：

For broker/stream load, null value for date and datetime is DefaultValueGenerator<DateValue/TimestampValue>, however, for spark load, it is not so.

So when we create a aggregate table, we first perform broker load, and then perform spark load on the same data
(here assuming the data has null value), and query by select count(*) from table, the result will contain two null value.

In this pr, we let the null date and datetime value for spark load to be consistent with broker/stream load

### CODE REVIEW

**Review by chaoyli — DISMISSED** [review]

File: be/src/exec/vectorized/arrow_to_starrocks_converter.cpp [hunk 1]
```diff
@@ -580,7 +580,14 @@ struct ArrowConverter<AT, PT, is_nullable, is_strict, DateOrDateTimeATGuard<AT>,
                                    [[maybe_unused]] int divisor) {
         for (int i = 0; i < num_elements; ++i) {
             if constexpr (is_nullable) {
-                if (null_data[i] == DATUM_NULL) continue;
+                if (null_data[i] == DATUM_NULL) {
+                    if constexpr (pt_is_date<PT>) {
+                        data[i] = DefaultValueGenerator<DateValue>::next_value();
```
Comment (kangkaisen) [inline be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:585]: if the data is null, i think the real data value could be any value, why do we need to set it to default value explicitly.

Comment (LiShuMing) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:585]: Yep.  This behavior is a bit strange.  Maybe others can meet the problem again latter.

Add some comments or explanations?

Comment (xiaoyong-z) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:585]: for nullable column, aggregation will first compare null flag, then compare the data
```c++
    Status do_visit(const vectorized::NullableColumn& column) {
        // TODO: maybe could skip compare rows that contains null
        // 1. Compare the null flag
        // 2. Compare the value if both are not null. Since value for null is just default value,
        //    which are equal, so just compare the value directly
        const NullData& null_data = column.immutable_null_column_data();
        for (size_t i = 1; i < column.size(); i++) {
            (*_tie)[i] &= (null_data[i - 1] == null_data[i]);
        }

        build_tie_for_column(column.data_column(), _tie);
        return Status::OK();
    }

    template <typename T>
    Status do_visit(const vectorized::BinaryColumnBase<T>& column) {
        auto& data = column.get_data();
        for (size_t i = 1; i < column.size(); i++) {
            (*_tie)[i] &= SorterComparator<Slice>::compare(data[i - 1], data[i]) == 0;
        }
        return Status::OK();
    }
```

Comment (xiaoyong-z) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:585]: For broker/stream load, null date/datetime'sdefault value is set to DefaultValueGenerator<DateValue/TimestampValue>

Comment (xiaoyong-z) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:585]: i will add some comments here

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

File: be/src/exec/vectorized/arrow_to_starrocks_converter.cpp (hunk 1 above)
Comment (kangkaisen) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:590]: > for nullable column, aggregation will first compare null flag, then compare the data
> 
> ```c++
>     Status do_visit(const vectorized::NullableColumn& column) {
>         // TODO: maybe could skip compare rows that contains null
>         // 1. Compare the null flag
>         // 2. Compare the value if both are not null. Since value for null is just default value,
>         //    which are equal, so just compare the value directly
>         const NullData& null_data = column.immutable_null_column_data();
>         for (size_t i = 1; i < column.size(); i++) {
>             (*_tie)[i] &= (null_data[i - 1] == null_data[i]);
>         }
> 
>         build_tie_for_column(column.data_column(), _tie);
>         return Status::OK();
>     }
> 
>     template <typename T>
>     Status do_visit(const vectorized::BinaryColumnBase<T>& column) {
>         auto& data = column.get_data();
>         for (size_t i = 1; i < column.size(); i++) {
>             (*_tie)[i] &= SorterComparator<Slice>::compare(data[i - 1], data[i]) == 0;
>         }
>         return Status::OK();
>     }
> ```

I think the aggregation comparison logic isn't reasonable, we shouldn't relay on data column content is default value if which is null.

Comment (xiaoyong-z) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:590]: i am not sure if there exist other place use the null value's data

Comment (xiaoyong-z) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:590]: @kangkaisen maybe we can modify both?
1. let the data for null value to be consistent
2. let the aggregation not check the data for null value?

**Review by chaoyli — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

File: be/src/exec/vectorized/arrow_to_starrocks_converter.cpp (hunk 1 above)
Comment (kangkaisen) [reply be/src/exec/vectorized/arrow_to_starrocks_converter.cpp:590]: OK

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
