### PR TITLE
[BugFix] Fix nested mv rewrite bugs

### LINKED ISSUE #40261: [Bug] nested mv cannot be used to rewrite a agg-then-join SQL
### Steps to reproduce the behavior (Required)
An example of StarRocks doc： https://docs.starrocks.io/zh/docs/using_starrocks/troubleshooting_asynchronous_materialized_views/   I tried to create a nested mv to rewrite the whole SQL but failed. In the below case, I created a MV for each subquery and then created a nested MV on the two MVs. The whole query could be rewrited by the two subquery MVs but cannot be rewritten by the nested MV.

Example 2: The materialized view mv2 uses join plus aggregation. Thus, it cannot be used to rewrite queries. To solve this problem, you can create a materialized view with aggregation, and then a nested materialized view with join based on the previous one.

```
CREATE MATERIALIZED VIEW mv2 REFRESH ASYNC AS
select *
from (
    select lo_orderkey, lo_custkey, p_partkey, p_name
    from lineorder
    join part on lo_partkey = p_partkey
) lo
join (
    select c_custkey
    from customer
    group by c_custkey
) cust
on lo.lo_custkey = cust.c_custkey;
``` 

Reproduce step:
```
'root'@hivessbtest Wed Jan 17 16:32:47 2024>CREATE MATERIALIZED VIEW default_catalog.testviewdb.mv2_subquery_1 REFRESH ASYNC every (interval 10 minute) AS
    ->     select lo_orderkey, lo_custkey, p_partkey, p_name
    ->     from lineorder
    ->     join part on lo_partkey = p_partkey;
Query OK, 0 rows affected (0.01 sec)

'root'@hivessbtest Wed Jan 17 16:34:08 2024>CREATE MATERIALIZED VIEW default_catalog.testviewdb.mv2_subquery_2 REFRESH ASYNC every (interval 10 minute) AS
    ->     select c_custkey
    ->     from customer
    ->     group by c_custkey;
Query OK, 0 rows affected (0.01 sec)

'root'@hivessbtest Wed Jan 17 16:34:45 2024>CREATE MATERIALIZED VIEW default_catalog.testviewdb.mv2_2 REFRESH ASYNC every (interval 10 minute) AS
    -> select *
    -> from default_catalog.testviewdb.mv2_subquery_1 lo
    -> join default_catalog.testviewdb.mv2_subquery_2 cust
    -> on lo.lo_custkey = cust.c_custkey;
Query OK, 0 rows affected (0.01 sec)
```

The three materialized MVs were refreshed successfully, but only mv2_subquery_1 and mv2_subquery_2 can be used to rewrite the query. mv2_2 should have been used to rewrite the query.
```
'root'@testviewdb Wed Jan 17 16:46:19 2024>set catalog hive;
Query OK, 0 rows affected (0.00 sec)

'root'@testviewdb Wed Jan 17 16:48:19 2024>use hivessbtest;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A


Database changed
'root'@hivessbtest Wed Jan 17 16:48:34 2024>explain
    -> select *
    -> from (
    ->     select lo_orderkey, lo_custkey, p_partkey, p_name
    ->     from lineorder
    ->     join part on lo_partkey = p_partkey
    -> ) lo
    -> join (
    ->     select c_custkey
    ->     from customer
    ->     group by c_custkey
    -> ) cust
    -> on lo.lo_custkey = cust.c_custkey;
+-----------------------------------------------------------------------------------------------------------+
| Explain String                                                                                            |
+-----------------------------------------------------------------------------------------------------------+
| PLAN FRAGMENT 0                                                                                           |
|  OUTPUT EXPRS:1: lo_orderkey | 3: lo_custkey | 19: p_partkey | 20: p_name | 28: c_custkey                 |
|   PARTITION: UNPARTITIONED                                                                                |
|                                                                                                           |
|   RESULT SINK                                                                                             |
|                                                                                                           |
|   7:EXCHANGE                                                                                              |
|                                                                                                           |
| PLAN FRAGMENT 1                                                                                           |
|  OUTPUT EXPRS:                                                                                            |
|   PARTITION: HASH_PARTITIONED: 3: lo_custkey                                                              |
|                                                                                                           |
|   STREAM DATA SINK                                                                                        |
|     EXCHANGE ID: 07                                                                                       |
|     UNPARTITIONED                                                                                         |
|                                                                                                           |
|   6:HASH JOIN                                                                                             |
|   |  join op: INNER JOIN (PARTITIONED)                                                                    |
|   |  colocate: false, reason:                                                                             |
|   |  equal join conjunct: 3: lo_custkey = 28: c_custkey                                                   |
|   |                                                                                                       |
|   |----5:EXCHANGE                                                                                         |
|   |                                                                                                       |
|   2:EXCHANGE                                                                                              |
|                                                                                                           |
| PLAN FRAGMENT 2                                                                                           |
|  OUTPUT EXPRS:                                                                                            |
|   PARTITION: RANDOM                                                                                       |
|                                                                                                           |
|   STREAM DATA SINK                                                                                        |
|     EXCHANGE ID: 05                                                                                       |
|     HASH_PARTITIONED: 28: c_custkey                                                                       |
|                                                                                                           |
|   4:Project                                                                                               |
|   |  <slot 28> : 39: c_custkey                                                                            |
|   |                                                                                                       |
|   3:OlapScanNode                                                                                          |
|      TABLE: mv2_subquery_2                                                                                |
|      PREAGGREGATION: ON                                                                                   |
|      partitions=1/1                                                                                       |
|      rollup: mv2_subquery_2                                                                               |
|      tabletRatio=10/10                                                                                    |
|      tabletList=16505545,16505547,16505549,16505551,16505553,16505555,16505557,16505559,16505561,16505563 |
|      cardinality=1                                                                                        |
|      avgRowSize=1.0                                                                                       |
|      MaterializedView: true                                                                               |
|                                                                                                           |
| PLAN FRAGMENT 3                                                                                           |
|  OUTPUT EXPRS:                                                                                            |
|   PARTITION: RANDOM                                                                                       |
|                                                                                                           |
|   STREAM DATA SINK                                                                                        |
|     EXCHANGE ID: 02                                                                                       |
|     HASH_PARTITIONED: 3: lo_custkey                                                                       |
|                                                                                                           |
|   1:Project                                                                                               |
|   |  <slot 1> : 51: lo_orderkey                                                                           |
|   |  <slot 3> : 52: lo_custkey                                                                            |
|   |  <slot 19> : 53: p_partkey                                                                            |
|   |  <slot 20> : 54: p_name                                                                               |
|   |                                                                                                       |
|   0:OlapScanNode                                                                                          |
|      TABLE: mv2_subquery_1                                                                                |
|      PREAGGREGATION: ON                                                                                   |
|      partitions=1/1                                                                                       |
|      rollup: mv2_subquery_1                                                                               |
|      tabletRatio=10/10                                                                                    |
|      tabletList=16505493,16505495,16505497,16505499,16505501,16505503,16505505,16505507,16505509,16505511 |
|      cardinality=1                                                                                        |
|      avgRowSize=5.0                                                                                       |
|      MaterializedView: true                                                                               |
+-----------------------------------------------------------------------------------------------------------+
71 rows in set (0.21 sec)
```

### Expected behavior (Required)

The query can be rewriten by mv2_2.

### Real behavior (Required)

The query cannot be rewriten by mv2_2.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```
select current_version()
    -> ;
+-------------------+
| current_version() |
+-------------------+
| 3.2.2-269e832     |
+-------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by LiShuMing**
Why I'm doing:

MV nested with MV does not worked as expected:
```
    @Test
    public void testNestedMVRewriteWithSSB() {
        String mv1 = "CREATE MATERIALIZED VIEW mv1 REFRESH ASYNC every (interval 10 minute) AS\n" +
                "select lo_orderkey, lo_custkey, p_partkey, p_name\n" +
                "from lineorder join part on lo_partkey = p_partkey;";
        String mv2 = "CREATE MATERIALIZED VIEW mv2 REFRESH ASYNC every (interval 10 minute) AS\n" +
                "select c_custkey from customer group by c_custkey;";
        String mv3 = "CREATE MATERIALIZED VIEW mv3 REFRESH ASYNC every (interval 10 minute) AS\n" +
                "select * from mv1 lo join mv2 cust on lo.lo_custkey = cust.c_custkey;";

        setTracLogModule("MV");
        connectContext.getSessionVariable().setQueryIncludingMVNames("mv1,mv2,mv3");
        starRocksAssert.withMaterializedViews(ImmutableList.of(mv1, mv2, mv3), (obj) -> {
            List<String> mvNames = (List<String>) obj;
            String query = "select *\n" +
                    "from (\n" +
                    "    select lo_orderkey, lo_custkey, p_partkey, p_name\n" +
                    "    from lineorder\n" +
                    "    join part on lo_partkey = p_partkey\n" +
                    ") lo\n" +
                    "join (\n" +
                    "    select c_custkey\n" +
                    "    from customer\n" +
                    "    group by c_custkey\n" +
                    ") cust\n" +
                    "on lo.lo_custkey = cust.c_custkey;";
            sql(query).contains("mv3");
        });
        connectContext.getSessionVariable().setQueryIncludingMVNames("");
    }
```

The root cause is this:

```
        // For logic scan to physical scan, we only need to match once
        if (pattern.children().size() == 0 && groupExpressionIndex.get(0) > 0) {
        ...
       }
```
`PATTERN_MULTIJOIN`'s children is 0.

What I'm doing:
- Fix the bug above.
- Optimize some codes.

Fixes [#issue](https://github.com/StarRocks/starrocks/issues/40261)

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java [hunk 1]
```diff
@@ -115,12 +115,15 @@ public void execute() {
             }
 
             GroupExpression newGroupExpression = result.second;
-            if (sessionVariable.isEnableMaterializedViewForceRewrite()) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java:118]: why ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java [hunk 2]
```diff
@@ -96,7 +96,7 @@ public List<OptExpression> transform(OptExpression queryExpression, OptimizerCon
         try {
             return doTransform(queryExpression, context);
         } catch (Exception e) {
-            String errMsg = ExceptionUtils.getMessage(e);
+            String errMsg = ExceptionUtils.getStackTrace(e);
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java:99]: That would generate a huge error message, which may make it un-readable ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java [hunk 3]
```diff
@@ -233,13 +234,15 @@ private boolean isMultiJoinRecursive(GroupExpression ge) {
...
         private boolean hasRewrittenMvScan(Group g) {
-            for (GroupExpression ge : g.getLogicalExpressions()) {
-                if ((ge.getOp().getOpType() == OperatorType.LOGICAL_OLAP_SCAN)) {
-                    return true;
-                }
-            }
-            return false;
+            return g.getLogicalExpressions().stream()
+                    .skip(1) // since first logical expression has already been checked.
+                    .anyMatch(ge -> ge.getOp().getOpType() == OperatorType.LOGICAL_OLAP_SCAN && ge.hasAppliedMVRules());
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java:245]: Previous code will generate false positive, but not wrong result, what's the benefit of changing it ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java [hunk 4]
```diff
@@ -66,7 +66,8 @@ public Binder(Pattern pattern, GroupExpression groupExpression) {
      */
     public OptExpression next() {
         // For logic scan to physical scan, we only need to match once
-        if (pattern.children().size() == 0 && groupExpressionIndex.get(0) > 0) {
+        if ((!pattern.isPatternMultiJoin() && pattern.children().size() == 0) &&
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java:69]: does it mean, for MULTI_JOIN, it can match a tree whose node is JOIN but without any children ?

**Review by ABingHuang — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java (hunk 3 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/Binder.java]: I think `anyMatch(ge -> ge.getOp().getOpType() == OperatorType.LOGICAL_OLAP_SCAN && ge.hasAppliedMVRules())` also will return right result and no false positive?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java (hunk 2 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java:99]: This should not happen and  trace log could help for trace the root cause?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java (hunk 1 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/task/ApplyRuleTask.java:118]: `appliedRules ` is used in `force rewrite` before, but we can use it for `Binder` too since it's trivial to record which rules are applied?

**Review by Seaven — APPROVED** [review]

**Review by murphyatwork — APPROVED** [review]
