### PR TITLE
[Bugfix] Check if tablet deleted after acquiring tabletupdates' lock

### LINKED ISSUE #7293: 【primary key】be core when straem load delete
### Steps to reproduce the behavior (Required)
1. curl --location-trusted -u root: -T /home/disk4/lvchenyang/code/StarRocksTest/lib/../common/data/basic_types_data -XPUT -H label:stream_load_1655288589703 -H partitions:p202006, p202007777777 -H max_filter_ratio:0.9 -H columns:__op='delete' http://ip:port/api/primary_table_csv26fe67b2_ec95_11ec_8d67_00163e0e550b/primary_table_with_null_partition/_stream_load

### Expected behavior (Required)
straem load success
### Real behavior (Required)
be core when straem load delete
```
*** Aborted at 1655286911 (unix time) try "date -d @1655286911" if you are using GNU date ***
PC: @          0x1a6f2cc starrocks::TabletUpdates::_debug_version_info()
*** SIGSEGV (@0x0) received by PID 5538 (TID 0x7ff9db8a8700) from PID 0; stack trace: ***
    @          0x3f6fad2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7ffa892a0630 (unknown)
    @          0x1a6f2cc starrocks::TabletUpdates::_debug_version_info()
    @          0x1a79d23 starrocks::TabletUpdates::remove_expired_versions()
    @          0x1a43950 starrocks::TabletManager::start_trash_sweep()
    @          0x1a15267 starrocks::StorageEngine::_start_trash_sweep()
    @          0x1bf4e79 starrocks::StorageEngine::_garbage_sweeper_thread_callback()
    @          0x59ed4d0 execute_native_thread_routine
    @     0x7ffa89298ea5 start_thread
    @     0x7ffa888b38dd __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 ```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 93b7fe8 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7293

## Problem Summary(Required) ：

When deleting a primary key tablet, clear_meta will be called and _edit_version_infos will be cleared, this makes all other concurrent operations invalid, so these operations running in other threads should check state validity after acquiring lock.

### CODE REVIEW

File: be/src/storage/tablet_updates.cpp [hunk 1]
```diff
@@ -700,9 +720,14 @@ void TabletUpdates::_stop_and_wait_apply_done() {
     }
 }
 
-void TabletUpdates::get_latest_applied_version(EditVersion* latest_applied_version) {
+Status TabletUpdates::get_latest_applied_version(EditVersion* latest_applied_version) {
     std::lock_guard l(_lock);
+    if (_edit_version_infos.empty()) {
+        LOG(WARNING) << "tablet deleted when get_latest_applied_version tablet:" << _tablet.tablet_id();
+        return Status::InternalError("get_latest_applied_version tablet deleted");
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:727]: Add the tablet_id in the Status.

File: be/src/storage/tablet_updates.cpp [hunk 2]
```diff
@@ -1114,6 +1138,10 @@ Status TabletUpdates::_commit_compaction(std::unique_ptr<CompactionInfo>* pinfo,
         return status;
     }
     std::lock_guard wl(_lock);
+    if (_edit_version_infos.empty()) {
+        LOG(WARNING) << "tablet deleted when commit compaction tablet:" << _tablet.tablet_id();
+        return Status::InternalError("tablet deleted");
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:1143]: Add the tablet_id in the Status

File: be/src/storage/tablet_updates.cpp [hunk 3]
```diff
@@ -1574,6 +1613,10 @@ Status TabletUpdates::compaction(MemTracker* mem_tracker) {
     vector<uint32_t> rowsets;
     {
         std::lock_guard rl(_lock);
+        if (_edit_version_infos.empty()) {
+            LOG(WARNING) << "tablet deleted when compaction tablet:" << _tablet.tablet_id();
+            return Status::InternalError("tablet deleted");
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:1618]: Add the tablet_id in the Status

File: be/src/storage/tablet_updates.cpp [hunk 4]
```diff
@@ -2810,6 +2887,9 @@ Status TabletUpdates::get_rowsets_for_incremental_snapshot(const std::vector<int
     vector<uint32_t> rowsetids;
     {
         std::lock_guard lg(_lock);
+        if (_edit_version_infos.empty()) {
+            return Status::InternalError("tablet deleted when get_rowsets_for_incremental_snapshot");
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:2891]: Add the tablet_id in the Status

File: be/src/storage/tablet_updates.cpp [hunk 5]
```diff
@@ -2745,6 +2818,10 @@ Status TabletUpdates::prepare_partial_update_states(Tablet* tablet, const std::v
     {
         // get next_rowset_id and read_version to identify conflict
         std::lock_guard wl(_lock);
+        if (_edit_version_infos.empty()) {
+            LOG(WARNING) << "tablet delete when call prepare_partial_update_states tablet:" << _tablet.tablet_id();
+            return Status::InternalError("tablet deleted when prepare_partial_update_states");
```
Comment (chaoyli) [inline be/src/storage/tablet_updates.cpp:2823]: Add the tablet_id in the Status

**Review by chaoyli — APPROVED** [review]

**Review by imay — APPROVED** [review]
