### PR TITLE
Fix missing Project on join due to AssertRowNode push down project 

### LINKED ISSUE #5041: SemiReorderRule  unknow error
### Steps to reproduce the behavior (Required)
```
DROP DATABASE IF EXISTS n10;
CREATE DATABASE n10;
USE n10;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 DATETIME NOT NULL ,c_0_1 DATE NOT NULL ,c_0_2 FLOAT NOT NULL ,c_0_3 DOUBLE NOT NULL ,c_0_4 DATE NULL ,c_0_5 FLOAT NULL ,c_0_6 SMALLINT NULL ,c_0_7 DATE NOT NULL ,c_0_8 ARRAY<INT> NULL ,c_0_9 LARGEINT NOT NULL ,c_0_10 CHAR(1) NOT NULL ,c_0_11 BOOLEAN NOT NULL ,c_0_12 BOOLEAN NOT NULL ,c_0_13 CHAR(11) NOT NULL ,c_0_14 FLOAT NOT NULL ) UNIQUE KEY (c_0_0,c_0_1) PARTITION BY RANGE(c_0_1) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 243 day)) DISTRIBUTED BY HASH (c_0_1,c_0_0) BUCKETS 3 properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DATETIME NULL ,c_1_1 BOOLEAN NOT NULL ,c_1_2 DATETIME NOT NULL ,c_1_3 DATETIME NULL ,c_1_4 BIGINT NOT NULL ,c_1_5 SMALLINT NULL ,c_1_6 LARGEINT NOT NULL ,c_1_7 BOOLEAN NOT NULL ,c_1_8 BOOLEAN NULL ,c_1_9 BOOLEAN NULL ,c_1_10 DECIMAL(21, 16)  NULL ,c_1_11 DECIMAL(12, 2)  NULL ,c_1_12 CHAR(31) NOT NULL ) UNIQUE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7,c_1_8,c_1_9,c_1_10,c_1_11) PARTITION BY RANGE(c_1_2) (START ("2010-01-01") END ("2021-12-31") EVERY (INTERVAL 243 day)) DISTRIBUTED BY HASH (c_1_5,c_1_9,c_1_3) BUCKETS 3 properties("replication_num"="3") ;
INSERT INTO t0 VALUES ("2010-01-06 08:00:14", "2010-01-29", 0.5844116279382997, 0.5844116279382997, "2010-01-07", 0.00879936834884354, 2, "2010-01-17", [-662712760, 340608345, -1068484367, -66772440, -1068484367, -1068484367, -719201007, -1515874004, 605134629, -988026424, -1165415996, 1748638094, -2090882171, 742487638, 1674838945], 1645405404, "", false, true, "6Nk", 1.645405404E9);
INSERT INTO t1 VALUES ("2010-01-30 08:00:14", true, "2010-01-05 08:00:14", "2010-01-28 08:00:14", 1021445574, 2, 2080893706, true, true, false, 5.901E-13, 80032867.20, "6"), ("2010-01-03 08:00:14", false, "2010-01-09 08:00:14", "2010-01-28 08:00:14", 851223090, 2, -988026424, false, false, false, 3.337E-13, 44506025.61, ""), ("2010-01-13 08:00:14", true, "2010-01-18 08:00:14", "2010-01-12 08:00:14", -59810167, 2, -66772440, true, false, true, 6.1809E-12, 57433975.82, "3itwML");
INSERT INTO t0 VALUES ("2010-01-17 08:00:14", "2010-01-05", 0.45122456989818116, 0.016979697518900605, "2010-01-08", 0.06027108655695457, 6, "2010-01-01", [-122499527, 23181007, 1645405404, 647416142, 1553148834, -59810167, 694032202, 1276183651, -135769301, -518124930, -193619941, 2007184519, -1251270351, 742487638], 2066033792, "", false, true, "Gs", -5.1812493E8), ("2010-01-17 08:00:14", "2010-01-06", -5.9810167E7, 0.2548232287844284, "2010-01-17", 1.021445574E9, 12, "2010-01-16", [-135769301, 1530339787, 694032202, 1212322363, 742487638, -1829765868, -1423156626, -2017400084, 1645405404], 287759108, "", true, false, "pGN", 0.7219170957890216), ("2010-01-20 08:00:14", "2010-01-20", -7.19201007E8, -7.19201007E8, "2009-12-31", 0.5832237392418121, 1, "2010-01-23", [-135769301, -925696001, -272857499, -1075658613, 1674838945, 1, 211457387, 211457387, 211457387, -1829765868, 1250472244], -100647205, "", true, true, "TK5", 0.6690407876267875);
INSERT INTO t0 VALUES ("2010-01-20 08:00:14", "2010-01-06", 0.42320182425655306, 0.5844116279382997, "2010-01-21", 0.2548232287844284, NULL, "2010-01-15", [2007184519, -2002422885, 1530339787, -750475185, 1645405404, -837306446], 1366720923, "", false, true, "gl6IF6U", 0.6690407876267875), ("2010-01-20 08:00:14", "2010-01-16", 1.366720923E9, 0.31944577193078594, "2010-01-07", 0.31944577193078594, 12, "2009-12-31", [851223090, -1395192523, -1020132533, 1468298690, 2066033792, 2007184519, -1395192523], -258576528, "", true, true, "", 0.2548232287844284), ("2010-01-09 08:00:14", "2009-12-31", 0.6725882451658415, 0.23738489448175226, "2010-01-31", 0.0036087027157150064, 8, "2010-01-29", [-1075658613, 1645405404, -901327862, -402092833, 1530339787, -1935384349, -1272569770, -1423156626, -151012, -381597699], -804106068, "", false, true, "", 0.016979697518900605);
INSERT INTO t1 VALUES (NULL, true, "2010-01-10 08:00:14", "2010-01-08 08:00:14", -527951370, 10, 1795061437, false, false, false, 8.3752E-12, 60611705.42, "8"), ("2010-01-21 08:00:14", false, "2010-01-23 08:00:14", "2010-01-05 08:00:14", -1133173124, 15, -1423156626, true, true, true, 1.800E-13, 14356032.30, "y4");
INSERT INTO t0 VALUES ("2010-01-13 08:00:14", "2010-01-02", 0.6952402633045526, 0.7416959381192503, NULL, 0.48746185241959095, 10, "2010-01-15", [-1109940388, 719508097, -454787538, 256282546], -719201007, "", true, true, "", 0.05731915065603088), ("2010-01-08 08:00:14", "2010-01-18", 0.5683557051074468, 2.007184519E9, "2010-01-19", 0.5006984036506364, NULL, "2010-01-02", [1856360854, -59810167, -122499527, 313668984, -1068484367, -178722785, 1664850013, 926282103, 1038121213, 23181007, 1602035168, 2025677472, -2139509479, 1818171766], 137845912, "", false, true, "", 0.06795826874338462);
INSERT INTO t0 VALUES ("2010-01-31 08:00:14", "2010-01-12", 0.5870833422208329, 1.602035168E9, "2010-01-18", 0.5844116279382997, NULL, "2010-01-07", [491323047, -1281252590], -1399442961, "", false, false, "D", 0.3610871542627424);
INSERT INTO t0 VALUES ("2009-12-31 08:00:14", "2010-01-08", 2.56282546E8, 0.6032495727239654, "2010-01-16", -1.829765868E9, 2, "2010-01-17", [23181007, -328731934, 1578575166, 1732190520, -925696001, 1856360854, 571691175, -1515874004, 1471919863, 2080893706, 846963922, -1829765868, -878120868], -626954155, "", false, false, "izmFyrfDg", 0.5006984036506364), ("2010-01-07 08:00:14", "2010-01-01", 0.0697840328899344, 0.8484348252751962, "2010-01-10", 0.7008035160042353, 1, "2010-01-02", [1475833481, 529270242, -1560284320, -527951370, 1121133603, -151012, -328731934, -1423156626, 736866521], 353808315, "", false, false, "4", 0.2809687696755566);
INSERT INTO t0 VALUES ("2010-01-21 08:00:14", "2010-01-11", 7.36866521E8, -9.01327862E8, "2010-01-10", 0.06430601711141715, 2, "2010-01-15", [-812512809, -1707496387, 137845912, 1366720923], 1846667840, "", false, true, "", 0.7906679576130196), ("2010-01-04 08:00:14", "2010-01-29", -0.0, 0.24966759326849475, "2009-12-31", 0.16086360189659066, 12, "2010-01-29", [1058716866, 1475833481, -1051882291, 1178937947, -1727206550, -1060939496, 1578575166, -1272569770, 66347636, -2139509479, -2002422885, -956186445, -1044901264, -696342376], 1008900215, "", true, false, "13", 0.2940860844899934);
INSERT INTO t1 VALUES ("2010-01-27 08:00:14", true, "2010-01-27 08:00:14", "2010-01-16 08:00:14", 851223090, 14, 926282103, false, true, false, 1.7642E-12, 3617170.09, ""), ("2010-01-04 08:00:14", false, "2010-01-19 08:00:14", "2010-01-22 08:00:14", -525861377, 14, 473687934, false, true, true, 7.5726E-12, 71063825.18, ""), ("2010-01-14 08:00:14", true, "2010-01-01 08:00:14", "2010-01-25 08:00:14", 313668984, 11, -1116720943, true, true, false, NULL, 21198410.43, "Tl");
INSERT INTO t0 VALUES ("2010-01-28 08:00:14", "2010-01-25", 0.8824791817220621, 0.3610871542627424, "2010-01-05", 0.38300683295966687, NULL, "2010-01-30", [-151012, -346106213, -719201007, -2017400084], 1535063657, "", true, true, "91nS6", 0.3596499834773832), ("2010-01-08 08:00:14", "2010-01-02", 0.9327283833583765, 0.852517148058398, "2010-01-21", 0.09216695384962303, 9, "2010-01-01", [503568402, 1364428275], -653108130, "", false, false, "4", 0.02421500620666317), ("2010-01-02 08:00:14", "2010-01-23", 0.6512849036445338, 0.38300683295966687, "2010-01-02", 0.04872200737077925, 9, "2010-01-20", [2070574603], 645041559, "", true, true, "YJIq", -1.22499527E8);
INSERT INTO t0 VALUES ("2010-01-10 08:00:14", "2010-01-16", 0.6316400379838368, 0.2822989846705797, "2010-01-13", NULL, 14, "2010-01-01", [-498733359, 647416142, 121447783, 837133631, -875647107, -1060939496, -2001388316, -750475185, 1791012885, -2104707639, 313668984, -454787538], -454787538, "", true, true, "YZ", 0.734100767099137);
DELETE FROM t0 WHERE c_0_0="1969-12-20 12:37:47";
INSERT INTO t1 VALUES ("2010-01-04 08:00:14", true, "2010-01-06 08:00:14", "2010-01-07 08:00:14", 1022011187, 10, -1935384349, true, false, false, 7.068E-13, NULL, "X"), ("2010-01-11 08:00:14", false, "2010-01-08 08:00:14", "2010-01-23 08:00:14", 658817399, 4, -1468953128, true, false, false, 9.9728E-12, 10393735.05, "4rZ7");
INSERT INTO t1 VALUES ("2010-01-15 08:00:14", true, "2009-12-31 08:00:14", "2009-12-31 08:00:14", 204319699, 3, -1532886693, true, false, true, 1.8349E-12, 29957226.02, "");
INSERT INTO t0 VALUES ("2010-01-13 08:00:14", "2010-01-04", -2.139509479E9, 0.20907430312307518, "2010-01-17", 0.5623692660868146, 10, "2010-01-22", [1276183651, -804106068, -1935384349, -223654138, -456982479, -1629969522, -23549044, -1186410291, 1805630456, 1804400845, -47937927, 457349419, -1281252590, -1029907030], 211457387, "", false, true, "", 0.4233633018359001), ("2010-01-25 08:00:14", "2010-01-08", 0.5844116279382997, -1.7976931348623157E308, "2010-01-22", 0.4734259049031122, 3, "2010-01-20", [-1020132533, -1224526605, -1604748208, -1647368293, -1166276811, -491871037, -1455788783, -122499527], 1941566895, "", true, true, "d7", 0.484708846968847);
INSERT INTO t1 VALUES ("2010-01-03 08:00:14", true, "2010-01-27 08:00:14", "2010-01-20 08:00:14", 137689185, NULL, -901327862, true, NULL, NULL, 7.0560E-12, 34113070.74, "q"), ("2010-01-25 08:00:14", false, "2010-01-26 08:00:14", "2010-01-18 08:00:14", -1614009680, 4, 587132239, false, NULL, NULL, 8.1732E-12, 31370064.62, "IG"), ("2010-01-28 08:00:14", false, "2010-01-24 08:00:14", "2010-01-17 08:00:14", 1370005390, 14, -345759465, true, false, NULL, 7.3289E-12, 6957095.04, "orZ");
INSERT INTO t0 VALUES ("2010-01-20 08:00:14", "2010-01-16", 5.71691175E8, 0.23587198999079428, "2010-01-16", 0.4388301722126289, 7, "2010-01-18", [1027378313, 1276183651, -190515220], 313668984, "", false, true, "", 0.6312920645297723), ("2010-01-09 08:00:14", "2010-01-12", 0.38519664286825794, -1.7976931348623157E308, "2010-01-14", 0.9327283833583765, 14, "2010-01-26", [647124858, 529270242, -626954155, -1746455994], -1963357854, "", false, false, "l", 0.21546361724484353);
CREATE VIEW v0 AS SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_9, t0.c_0_10, t0.c_0_11, t0.c_0_12, t0.c_0_13, t0.c_0_14 FROM t0 WHERE (NOT (false)) GROUP BY t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_9, t0.c_0_10, t0.c_0_11, t0.c_0_12, t0.c_0_13, t0.c_0_14 ORDER BY t0.c_0_13, t0.c_0_6, t0.c_0_13;

mysql> WITH with_t_0 as (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_9, t0.c_0_10, t0.c_0_11, t0.c_0_12, t0.c_0_13, t0.c_0_14 FROM t0 WHERE ((t0.c_0_11) IS NOT NULL)) SELECT COUNT(*) FROM t0, with_t_0 WHERE  ( (SELECT v0.c_0_0 FROM v0 WHERE false)  ) != ( (SELECT v0.c_0_0 FROM v0, t1 WHERE (t1.c_1_7) IN ((SELECT t1.c_1_7 FROM  t1 INNER JOIN (SELECT v0.c_0_0, v0.c_0_1, v0.c_0_2, v0.c_0_3, v0.c_0_4, v0.c_0_5, v0.c_0_6, v0.c_0_7, v0.c_0_9, v0.c_0_10, v0.c_0_11, v0.c_0_12, v0.c_0_13, v0.c_0_14 FROM v0) subv0 ON t1.c_1_7 >= subv0.c_0_5 AND ((t1.c_1_5) IS NULL) = subv0.c_0_5 WHERE false) ) )  ) ;
ERROR 1064 (HY000): Unknown error

```

```
fe.log:
2022-04-13 15:26:56,859 WARN (starrocks-mysql-nio-pool-23|1135) [StmtExecutor.execute():473] execute Exception, sql WITH with_t_0 as (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_9, t0.c_0_10, t0.c_0_11, t0.c_0_12, t0.c_0_13, t0.c_0_14 FROM t0 WHERE ((t0.c_0_11) IS NOT NULL)) SELECT COUNT(*) FROM t0, with_t_0 WHERE  ( (SELECT v0.c_0_0 FROM v0 WHERE false)  ) != ( (SELECT v0.c_0_0 FROM v0, t1 WHERE (t1.c_1_7) IN ((SELECT t1.c_1_7 FROM  t1 INNER JOIN (SELECT v0.c_0_0, v0.c_0_1, v0.c_0_2, v0.c_0_3, v0.c_0_4, v0.c_0_5, v0.c_0_6, v0.c_0_7, v0.c_0_9, v0.c_0_10, v0.c_0_11, v0.c_0_12, v0.c_0_13, v0.c_0_14 FROM v0) subv0 ON t1.c_1_7 >= subv0.c_0_5 AND ((t1.c_1_5) IS NULL) = subv0.c_0_5 WHERE false) ) )  )
java.lang.NullPointerException: null
	at com.starrocks.sql.optimizer.rule.transformation.SemiReorderRule.transform(SemiReorderRule.java:81) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.ApplyRuleTask.execute(ApplyRuleTask.java:62) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.task.SeriallyTaskScheduler.executeTasks(SeriallyTaskScheduler.java:42) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.memoOptimize(Optimizer.java:129) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.optimizer.Optimizer.optimize(Optimizer.java:92) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.createQueryPlan(StatementPlanner.java:84) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.StatementPlanner.plan(StatementPlanner.java:54) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:312) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:283) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:430) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:666) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$459(ReadListener.java:55) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.2 Release
 - mysql> select current_version();
+---------------------------------+
| current_version()               |
+---------------------------------+
| SQLANCER_01_RELEASE 145a79c |
+---------------------------------+

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5041

## Problem Summary(Required) ：

Currently, there is a Project on each Join, but the PushDownAssertOneRowProjectRule may push the AssertOneRow Node down to the Project, which leads to Join loss of Project used for column prune.

### CODE REVIEW

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by HangyuanLiu** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/PushDownAssertOneRowProjectRule.java|1|1|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAssertOneRowProjectRule.java [hunk 1]
```diff
@@ -14,7 +14,7 @@
 public class PushDownAssertOneRowProjectRule extends TransformationRule {
     public PushDownAssertOneRowProjectRule() {
         super(RuleType.TF_PUSH_DOWN_ASSERT_ONE_ROW_PROJECT, Pattern.create(OperatorType.LOGICAL_ASSERT_ONE_ROW)
-                .addChildren(Pattern.create(OperatorType.LOGICAL_PROJECT, OperatorType.PATTERN_LEAF)));
+                .addChildren(Pattern.create(OperatorType.LOGICAL_PROJECT, OperatorType.LOGICAL_AGGR)));
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAssertOneRowProjectRule.java:17]: why could only be LOGICAL_AGGR?

Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/PushDownAssertOneRowProjectRule.java:17]: Because one of the main optimizations of AssertOneRow is that when AssertOneRow is on an aggregate node, AssertOneRow may be optimized away. The specific optimization rules are in PruneAssertOneRowRule. In other cases, there is no need to push down AssertOneRow.

**Review by Seaven — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
