### PR TITLE
[BugFix] Use independent thread to write journals by batch asynchronously

### LINKED ISSUE #4327: The BDB will be stalled in lock
### Steps to reproduce the behavior (Required)
The BDB will be stalled in lock
```
"Thread-38" #87 daemon prio=5 os_prio=0 tid=0x00007f72112d2800 nid=0x7528 runnable [0x00007f70e27ea000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.FileDispatcherImpl.force0(Native Method)
        at sun.nio.ch.FileDispatcherImpl.force(FileDispatcherImpl.java:80)
        at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:388)
        at com.sleepycat.je.log.FileManager$LogEndFileDescriptor.force(FileManager.java:3094)
        at com.sleepycat.je.log.FileManager$LogEndFileDescriptor.access$500(FileManager.java:2760)
        at com.sleepycat.je.log.FileManager.syncLogEnd(FileManager.java:2046)
        at com.sleepycat.je.log.FSyncManager.executeFSync(FSyncManager.java:399)
        at com.sleepycat.je.log.FSyncManager.flushAndSync(FSyncManager.java:349)
        at com.sleepycat.je.log.LogManager.log(LogManager.java:343)
        at com.sleepycat.je.txn.Txn.logCommitEntry(Txn.java:1008)
        at com.sleepycat.je.txn.Txn.commit(Txn.java:767)
        - locked <0x00000005da2c2608> (a com.sleepycat.je.rep.txn.MasterTxn)
        at com.sleepycat.je.txn.Txn.commit(Txn.java:625)
        at com.sleepycat.je.txn.Txn.operationEnd(Txn.java:1803)
        at com.sleepycat.je.Database.put(Database.java:1506)
        at com.sleepycat.je.Database.put(Database.java:1556)
        at com.starrocks.journal.bdbje.CloseSafeDatabase.put(CloseSafeDatabase.java:28)
        at com.starrocks.journal.bdbje.BDBJEJournal.write(BDBJEJournal.java:157)
        - locked <0x0000000637b759c0> (a com.starrocks.journal.bdbje.BDBJEJournal)
        at com.starrocks.persist.EditLog.logEdit(EditLog.java:859)
        - locked <0x0000000637b55a20> (a com.starrocks.persist.EditLog)
        at com.starrocks.persist.EditLog.logUpdateReplica(EditLog.java:1057)
        at com.starrocks.master.ReportHandler.sync(ReportHandler.java:511)
        at com.starrocks.master.ReportHandler.tabletReport(ReportHandler.java:293)
        at com.starrocks.master.ReportHandler.access$300(ReportHandler.java:101)
        at com.starrocks.master.ReportHandler$ReportTask.exec(ReportHandler.java:244)
        at com.starrocks.master.ReportHandler.runOneCycle(ReportHandler.java:1119)
        at com.starrocks.common.util.Daemon.run(Daemon.java:119)

   Locked ownable synchronizers:
        - <0x0000000637be7c38> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        - <0x0000000637dda328> (a java.util.concurrent.locks.ReentrantReadWriteLock$FairSync)
```

### StarRocks version (Required)
 - branch-2.2 f0805b8e084ba625348c5c4d739a8ad4111e13aa

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #4327 

## Problem Summary(Required) ：

We have found some severe performance issues described in #4327.
The main reason is that each thread that writes one journal needs to call EditLog.logEdit(), a synchronized method that holds a global lock. As a result, this function becomes the bottleneck of the journal writing pipeline.
We can use an independent thread called JournalWriter to write journals by batch asynchronously. Each thread that needs to write a log can put the log in a blocking queue, while JournalWriter constantly gets as many logs as possible from the queue and write them all to BDB in one transaction. After committing, JournalWriter will notify the caller thread for consistency.

### CODE REVIEW

**Comment by padmejin** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java [hunk 1]
```diff
@@ -896,63 +908,80 @@ public void rollEditLog() {
...
+     * wait for JournalWriter commit all logs
      */
-    synchronized long getEditLogSize() throws IOException {
-        return editStream.length();
-    }
-
-    public synchronized long getTxId() {
-        return txId;
+    protected void waitLogConsumed(JournalQueueEntity entity) {
+        int cnt = 0;
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:973]: cnt is not added

**Comment by imay** [comment]
@padmejin Have you done some stress test based on this patch.

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java (hunk 1 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:973]: Done.

**Comment by padmejin** [comment]
> @padmejin Have you done some stress test based on this patch.

I have added a unit test to compare the performance between `write` and `writeWithinTxn`. 
As for the whole system, I have run a stress test that run 100 `insert into` in parallel in 100 different databases last week. It turned out that the publishing version part is the bottleneck, not the writing journal part. Besides, there were no metrics for the performance of journal writing, I had to manually add some histograms.
So far the conclusion is that even after this PR, we probably won't find a significant improvement in loading, nor can we explicitly observe the improvement in writing journals because of the lack of such metrics. 
I don't want to compare the performance by hacking, so I am trying different SQLs. I will add the conclusion to the description of this PR once I find a proper scenario to verify the improvement.

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 164 / 189 (86.77%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|42|61|68.85%|
|:large_blue_circle:|com/starrocks/journal/JournalQueueEntity.java|15|16|93.75%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|50|53|94.34%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|38|40|95.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 2]
```diff
@@ -1505,4 +1505,27 @@ public class Config extends ConfigBase {
...
+    @ConfField(mutable = true)
+    public static int journal_queue_size = 1000;
+
+    /**
+     * The maxium size(key+value) of journal entity to write as a batch
+     * Increase this configuration if journal queue is always full
+     * TODO: set default value
+     **/
+    @ConfField(mutable = true)
+    public static int batch_journal_size_mb = 100;
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1522]: Why the default value so large?

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+            while (true) {
+                if (!staggingLogs.isEmpty()) {
+                    entity = logQueue.take();
+                }
+                // 2.1 write(no commit)
+                journal.writeWithinTxn(entity.getOp(), entity.getBuffer());
+                staggingLogs.add(entity);
+
+                // 2.2 check if is an emergency log
+                if (entity.getBetterCommitBeforeTime() > 0) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:59]: How about naming it as `expectedCommitTime`?

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+                if (staggingLogs.size() >= Config.batch_journal_cnt) {
+                    LOG.info("staggging log {} >= {}, will commit now",
+                            staggingLogs.size(), Config.batch_journal_cnt);
+                    break;
+                }
+
+                // 2.4 check uncommitted logs by size
+                uncommitedEstimatedBytes += entity.estimatedSizeByte();
+                if (uncommitedEstimatedBytes >= Config.batch_journal_size_mb * 1024 * 1024) {
+                    LOG.info("uncommited estimated bytes {} >= {}MB, will commit now",
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:78]: why not  log warning?

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java [hunk 5]
```diff
@@ -81,25 +82,36 @@
...
-    private long txId = 0;
+    private final Journal journal;
 
-    private long numTransactions;
-    private long totalTimeTransactions;
+    private BlockingQueue<JournalQueueEntity> logQueue;
 
-    private final Journal journal;
+    /**
+     * for ut only
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:101]: How about annotate with `Visible Test`?

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java [hunk 6]
```diff
@@ -907,63 +919,81 @@ public void rollEditLog() {
...
+         * for historical reasons, logEdit is not allowed to raise Exception, which is really unreasonable to me.
+         * This PR will continue to swallow exception and retry till the end of the world like before.
+         * Hope some day we'll fix it.
+         */
+        // 2. put to queue
+        int cnt = 0;
+        while (true) {
+            try {
+                if (cnt != 0) {
+                    Thread.sleep(1000);
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:966]: Why so many sleep? Why not a condition variable?

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 2 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1522]: It's just temporary set to some number. I'll run some test to check for a proper value.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java (hunk 3 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:59]: I think `expectedCommitTime` can be confusing since commiting before this time is as expected.

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java (hunk 5 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:101]: Good advice. I didn't know this annotation.

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java (hunk 6 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:966]: 1. We only go to this branch when InterruptedException is raised, for example, if this thread is interrupt as `testNoWaitInterrupt()` shows. In this scenerio, a condition variable will also raise a InterruptedException.
2. I actually think that this exception should be raised so that the caller can know it's time to clean up and quit the context. But as I commented above, this function is not allowed to raise Exception for historical reasons. So we can only wait and loop forever as the old implematation did.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java (hunk 4 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:78]: OK

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+                    break;
+                }
+            }
+
+            // 3. commit
+            journal.commitTxn();
+
+            // 4. countdown
+            for (JournalQueueEntity e : staggingLogs) {
+                e.countDown();
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:94]: how about returning a Future
https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:94]: Are you suggesting me to use another thread pool to countdown? I think this operation won't take much time. It's just a conditional variable.

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java [hunk 8]
```diff
@@ -907,63 +919,81 @@ public void rollEditLog() {
...
+                }
+                entity.waitLatch();
+                return;
+            } catch (InterruptedException e) {
+                LOG.warn("failed to put queue, wait and retry {} times..: {}", cnt, e);
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:993]: This is not `put to queue` op.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalQueueEntity.java [hunk 9]
```diff
@@ -0,0 +1,55 @@
...
+        latch.countDown();
+    }
+
+    public long getBetterCommitBeforeTime() {
+        return betterCommitBeforeTime;
+    }
+
+    public long estimatedSizeByte() {
+        // journal id + buffer
+        return Long.SIZE / 8 + buffer.getLength();
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalQueueEntity.java:45]: Where does the padding information come from?

File: fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java (hunk 8 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/persist/EditLog.java:993]: OK

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalQueueEntity.java (hunk 9 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalQueueEntity.java:45]: It's not padding size, it's journal id, the key of bdb.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+                if (!staggingLogs.isEmpty()) {
+                    entity = logQueue.take();
+                }
+                // 2.1 write(no commit)
+                journal.writeWithinTxn(entity.getOp(), entity.getBuffer());
+                staggingLogs.add(entity);
+
+                // 2.2 check if is an emergency log
+                if (entity.getBetterCommitBeforeTime() > 0) {
+                    long delayMillis = System.currentTimeMillis() - entity.getBetterCommitBeforeTime();
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:60]: nanoTime() maybe more precise resolution than currentTimeMillis(), The latter may reach an accuracy of tens of milliseconds.

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 11]
```diff
@@ -0,0 +1,122 @@
...
+        super("JournalWriter", 0L);
+        this.journal = journal;
+        this.logQueue = logQueue;
+    }
+
+    @Override
+    protected void runOneCycle() {
+        try {
+            // 1. waiting if necessary until an element becomes available
+            JournalSubmitTask take = logQueue.take();
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:43]: take => task?

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java [hunk 12]
```diff
@@ -390,6 +409,91 @@ public List<Long> getDatabaseNames() {
...
+        String msg = "write bdb within txn failed. will exit. journalId: " + staggingNextJournalId + ", txnId: " +
+                currentTrasaction.getId() + ", bdb database Name: " + currentJournalDB.getDb().getDatabaseName();
+        LOG.error(msg);
+        Util.stdoutWithTime(msg);
+        System.exit(-1);
+    }
+
+    @Override
+    public void commitTxn() {
+        assert (currentTrasaction != null);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:467]: If commitTxn() failed but writeWithinTxn() succeed, is there necessary to rollbock the BDB?

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 13]
```diff
@@ -0,0 +1,122 @@
...
+                // 2.4 check uncommitted logs by size
+                uncommitedEstimatedBytes += take.estimatedSizeByte();
+                if (uncommitedEstimatedBytes >= Config.batch_journal_size_mb * 1024 * 1024) {
+                    LOG.warn("uncommitted estimated bytes {} >= {}MB, will commit now",
+                            uncommitedEstimatedBytes, Config.batch_journal_size_mb);
+                    break;
+                }
+
+                // 2.5 no more log in queue
+                if (logQueue.peek() == null) {
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:84]: It won't exit. This method is called for every loop.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java (hunk 11 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:43]: Oops.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalSubmitTask.java [hunk 14]
```diff
@@ -0,0 +1,86 @@
...
+import com.starrocks.common.io.DataOutputBuffer;
+import org.jetbrains.annotations.NotNull;
+
+import java.util.concurrent.CountDownLatch;
+import java.util.concurrent.ExecutionException;
+import java.util.concurrent.Future;
+import java.util.concurrent.TimeUnit;
+import java.util.concurrent.TimeoutException;
+
+public class JournalSubmitTask implements Future<Void> {
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalSubmitTask.java:14]: OK

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java (hunk 12 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:467]: No, nothing is written if commit failed.

File: fe/fe-core/src/test/java/com/starrocks/journal/JournalWriterTest.java [hunk 15]
```diff
@@ -0,0 +1,163 @@
+package com.starrocks.journal;
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/test/java/com/starrocks/journal/JournalWriterTest.java:1]: OK. I think we should add a checker for this..

File: fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJEJournalTest.java [hunk 16]
```diff
@@ -0,0 +1,289 @@
+    // This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Limited.
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/test/java/com/starrocks/journal/bdbje/BDBJEJournalTest.java:1]: OK

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 166 / 196 (84.69%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|42|61|68.85%|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|15|21|71.43%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|51|54|94.44%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|36|38|94.74%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|2|100.00%|

**Review by chaoyli — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 17]
```diff
@@ -1505,7 +1505,30 @@ public class Config extends ConfigBase {
...
+
+    /**
+     * The maxium number of journal entity to write as a batch
+     * Increase this configuration if journal queue is always full
+     * TODO: set default value
+     **/
+    @ConfField(mutable = true)
+    public static int batch_journal_cnt = 100;
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1531]: nit: max_bach_journal_cnt

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 2 above)
Comment (DorianZheng) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1523]: nit: max_batch_journal_size_in_mb

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 17 above)
Comment (DorianZheng) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1531]: why restrict the batch count?

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 18]
```diff
@@ -0,0 +1,122 @@
...
+                    break;
+                }
+            }
+
+            // 3. commit
+            journal.commitTxn();
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:90]: Is it possible to call `commitTxn` in another thread, will it introduce any consistent issue or data race?

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 17 above)
Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1531]: We can make our configure name the scope first. like `metadata.journal.max_batch_cnt`. 
Then if we want to find related configuration, we can get it directly.

File: fe/fe-core/src/main/java/com/starrocks/journal/Journal.java [hunk 19]
```diff
@@ -57,4 +59,9 @@ public interface Journal {
     // Get all the dbs' name
     public List<Long> getDatabaseNames();
 
+    // Write a jounal within current transaction
+    public void writeWithinTxn(short op, DataOutputBuffer buffer);
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/Journal.java:63]: This function is very confusing.
Can this journal support multiple transaction. And if write is called after this function, what will happen?
I think we need to make this clearer.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 20]
```diff
@@ -0,0 +1,122 @@
...
+            long uncommitedEstimatedBytes = 0;
+            staggingLogs.clear();
+
+            // 2. batch write
+            while (true) {
+                if (!staggingLogs.isEmpty()) {
+                    task = logQueue.take();
+                }
+                // 2.1 write(no commit)
+                journal.writeWithinTxn(task.getOp(), task.getBuffer());
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:55]: why not write code like 
```
try {
} finally {
     journal.commit()
}
```
This can make sure that the current transaction can be commit or abort

**Review by imay — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java (hunk 18 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:90]: No. The main goal of this PR is to put the write operation on BDB in one thread instead of scattered in every possible thread. You probably raised this question on the assumption that so far we used Journal as some global variable, which I think it's a bad design, and will try to decouple some BDB Classes in later PRs. In the end, BDBJournal will be a private class in JournalWriter so the consistent issue will be grammatically impossible.

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 17 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: Done.

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 242 / 267 (90.64%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|18|24|75.00%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|94|104|90.38%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|67|74|90.54%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|36|38|94.74%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/journal/JournalException.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/CloseSafeDatabase.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 21]
```diff
@@ -1505,7 +1505,30 @@ public class Config extends ConfigBase {
      * In order to avoid unnecessary CLONE, we increase the timeout as much as possible
      */
     @ConfField(mutable = true)
-    public static int quorom_publish_wait_time_ms = 5000;
+    public static int quorom_publish_wait_time_ms = 500;
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1508]: It's a merge accident. I'll fix it right now.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 241 / 266 (90.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|18|24|75.00%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|94|104|90.38%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|67|74|90.54%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|36|38|94.74%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/journal/JournalException.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/CloseSafeDatabase.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 22]
```diff
@@ -1507,6 +1507,29 @@ public class Config extends ConfigBase {
...
+     * Increase this configuration if journal queue is always full
+     * TODO: set default value
+     **/
+    @ConfField(mutable = true)
+    public static int metadata_journal_max_batch_size_mb = 10;
+
+    /**
+     * The maxium number of journal entity to write as a batch
+     * Increase this configuration if journal queue is always full
+     * TODO: set default value
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1528]: what this TODO mean?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:1528]: The default values of these two config need to be evaluated with some performance tests which I will run later. Now I only set them to a larger value to ensure it won't be the bottleneck.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 23]
```diff
@@ -0,0 +1,218 @@
...
+        }
+    }
+
+    /**
+     * We should notify the caller to rollback or report error on abort, like this.
+     *
+     * task.markAbort();
+     *
+     * But now we have to exit for historical reason.
+     * Note that if we exit here, the finally clause(commit current batch) will not be executed.
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:151]: what dose this comment mean? if we do not exit here, will the finally clause be executed again?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:151]: If we do not exit here, the finally clause will be executed, current batch will be committed.
But since we exit here, the finally clause will not be executed, current batch will not be committed.

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:151]: here `exit` means to exit the process by calling `System.exit()`.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/CloseSafeDatabase.java [hunk 24]
```diff
@@ -70,4 +70,11 @@ public String getDatabaseName() {
             return "";
         }
     }
+
+    @Override
+    public String toString() {
+        return "CloseSafeDatabase{" +
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/CloseSafeDatabase.java:76]: Done.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 241 / 266 (90.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|18|24|75.00%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|94|104|90.38%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|67|74|90.54%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|36|38|94.74%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/journal/JournalException.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/CloseSafeDatabase.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java [hunk 25]
```diff
@@ -394,4 +407,141 @@ public BDBEnvironment getBdbEnvironment() {
...
+            throw new JournalException(String.format(
+                    "failed to begin batch write because has running txn = %s", currentTrasaction));
+        }
+
+        JournalException exception = null;
+        for (int i = 0; i < RETRY_TIME; i++) {
+            try {
+                // sleep before retry
+                if (i != 0) {
+                    Thread.sleep(SLEEP_INTERVAL_SEC * 1000);
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:426]: Will the sleep will be too long?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:426]: Since I am lack of online experience, I use the same value as in BDBJEJournal here.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java [hunk 26]
```diff
@@ -0,0 +1,218 @@
...
+        this.nextVisibleJournalId = maxJournalId + 1;
+        this.journal.rollJournal(this.nextVisibleJournalId);
+    }
+
+    public void startDaemon() {
+        // ensure init() is called.
+        assert (nextVisibleJournalId > 0);
+        Daemon d = new Daemon("JournalWriter", 0L) {
+            @Override
+            protected void runOneCycle() {
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/JournalWriter.java:63]: Not sure what you are asking.
1. This Daemon has only one thread that contains an infinity loop, each loop is implemented by the `runOneCycle()`.
2. Only StateListener will call `startDaemon()` and start this JournalWriter Daemon.

**Review by chaoyli — APPROVED** [review]

**Comment by padmejin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 241 / 266 (90.60%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/JournalTask.java|18|24|75.00%|
|:large_blue_circle:|com/starrocks/journal/JournalWriter.java|94|104|90.38%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|67|74|90.54%|
|:large_blue_circle:|com/starrocks/persist/EditLog.java|36|38|94.74%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBEnvironment.java|7|7|100.00%|
|:large_blue_circle:|com/starrocks/journal/JournalException.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/journal/bdbje/CloseSafeDatabase.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/metric/MetricRepo.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|3|100.00%|
