### PR TITLE
[Enhancement] return 1295 when statement is not supported by prepare-statement

### LINKED ISSUE #41757: Return error code "1295" for unsupported command in prepared statement
## Enhancement

We're trying to integrate Hashicorp Vault with StarRocks to generate database credentials using the [database secrets engine](https://developer.hashicorp.com/vault/docs/secrets/databases) and store them securely in Vault. Vault supports various databases and also [MySQL](https://developer.hashicorp.com/vault/docs/secrets/databases/mysql-maria).

After we've successfully connected Vault with StarRocks we stumbled over the problem that `ALTER USER` is an invalid statement type for prepared statements. From your documentation only SELECT statements are supported.
https://docs.starrocks.io/docs/sql-reference/sql-statements/prepared_statement/#prepare

```
2024-02-23 17:05:10,295 WARN (starrocks-mysql-nio-pool-30|9625) [ConnectProcessor.handleQuery():411] Failed to parse SQL: ALTER USER 'root'@'%' IDENTIFIED BY 'top-secret', because.
com.starrocks.common.AnalysisException: prepare statement only support QueryStatement
	at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:378) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:588) ~[starrocks-fe.jar:?]
	at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:872) ~[starrocks-fe.jar:?]
	at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:69) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

Vault has implemented a fallback to run the statement without preparation when the command is not supported but only in case the returned error code is `1295`.
https://github.com/hashicorp/vault/blob/e6d2caaa52c71c6de0df76e183563e09bb0e65d2/plugins/database/mysql/mysql.go#L265-L282

The error code `1295` seems to be the correct one for unsupported commands in MySQL and it would be great if this can be also returned by StarRocks.

## Version

```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| 3.2.3-a40e2f8     |
+-------------------+
1 row in set (0.02 sec)
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## Why I'm doing:
- error code 1295 is defined by MySQL for unsupported prepare-statement

## What I'm doing:

Fixes #41757

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by Seaven — DISMISSED** [review]

**Review by imay — DISMISSED** [review]

**Review by packy92 — DISMISSED** [review]

**Comment by packy92** [comment]
Does some client need this specific error code?

**Review by dirtysalt — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java [hunk 1]
```diff
@@ -91,6 +91,8 @@ public enum ErrorCode {
     ERR_NOT_SUPPORTED_AUTH_MODE(1251, new byte[] {'0', '8', '0', '0', '4'},
             "Client does not support authentication protocol requested by server; consider upgrading MySQL client"),
     ERR_UNKNOWN_STORAGE_ENGINE(1286, new byte[] {'4', '2', '0', '0', '0'}, "Unknown storage engine '%s'"),
+    ERR_UNSUPPORTED_PS(1295, "HY000".getBytes(),
```
Comment (jaogoy) [inline fe/fe-core/src/main/java/com/starrocks/common/ErrorCode.java:94]: Use 0A000 to indicate 'Feature Not Supported'
