### PR TITLE
[BugFix] fix potential heap overflow in snappy slice source

### LINKED ISSUE #15817: [Bug] heap-buffer-overflow on SnappySlicesSource
### Steps to reproduce the behavior (Required)
Build starrocks with AddressSanitizer, meet this problem when run daily testcases.
```
==11888==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x603018503b28 at pc 0x00000e7439f5 bp 0x7f3a69fc7710 sp 0x7f3a69fc7708
READ of size 8 at 0x603018503b28 thread T98 (memtable_flush)
    #0 0xe7439f4 in starrocks::SnappySlicesSource::Skip(unsigned long) (/home/disk1/sr/master_asan/be/lib/starrocks_be+0xe7439f4)
    #1 0x10a98d60 in snappy::Compress(snappy::Source*, snappy::Sink*) /var/local/thirdparty/src/snappy-1.1.8/snappy.cc:1061
    #2 0xe743fae in starrocks::SnappyBlockCompression::compress(std::vector<starrocks::Slice, std::allocator<starrocks::Slice> > const&, starrocks::Slice*, bool, unsigned long, starrocks::faststring*, std::__cxx11::basic_string<char, std::char_traits<char>, starrocks::raw::RawAllocator<char, 0ul, std::allocator<char> > >*) const (/home/disk1/sr/master_asan/be/lib/starrocks_be+0xe743fae)
    #3 0xde24317 in starrocks::PageIO::compress_page_body(starrocks::BlockCompressionCodec const*, double, std::vector<starrocks::Slice, std::allocator<starrocks::Slice> > const&, starrocks::faststring*) /root/starrocks/be/src/storage/rowset/page_io.cpp:73
    #4 0xdcecf35 in starrocks::ScalarColumnWriter::finish_current_page() /root/starrocks/be/src/storage/rowset/column_writer.cpp:518
    #5 0xdcef927 in starrocks::ScalarColumnWriter::append(unsigned char const*, unsigned char const*, unsigned long, bool) /root/starrocks/be/src/storage/rowset/column_writer.cpp:681
```

### StarRocks version (Required)
 MAIN-ASAN ASAN (build d811a3b)
Built on 2022-12-27 08:00:44 by StarRocks@docker

### PR DESCRIPTION
**Pull request by luohaha**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15817 , (Not 100% make sure it can fix this bug, but we can still merge this code, and see if this bug can be fixed or not later)

## Problem Summary(Required) ：

In `SnappySlicesSource` current code, if we already skip all bytes in `SnappySlicesSource`, then call `skip(0)` which satisfy `Available() >= n (0 >= 0)`, but will cause heap overflow in `_slices[_cur_slice]`

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

**Review by decster — DISMISSED** [review]

File: be/src/util/compression/block_compression.cpp [hunk 1]
```diff
@@ -567,7 +567,7 @@ class SnappySlicesSource : public snappy::Source {
     // REQUIRES: Available() >= n
```
Comment (decster) [inline be/src/util/compression/block_compression.cpp:567]: also add a DCHECK(_available >= n) ?

Comment (decster) [inline be/src/util/compression/block_compression.cpp:567]: also add a DCHECK(_available >= n) ?

Comment (decster) [inline be/src/util/compression/block_compression.cpp:567]: also add a DCHECK(_available >= n) ?

Comment (luohaha) [reply be/src/util/compression/block_compression.cpp:567]: Done

**Review by imay — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-2.5

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-2.4

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-2.3

**Comment by luohaha** [comment]
https://github.com/Mergifyio backport branch-2.2
