### PR TITLE
[Bugfix] Fix max src rssid error during update compaction

### LINKED ISSUE #9405: [Primary Key]Tablet state will be error if apply phase has not finished and we restart be
### Steps to reproduce the behavior (Required)
1. load a large dataset
2. restart be before apply finish

actually this was found when i test with condition update, apply will be slow when i need to read many old rows.
in real case we may apply quickly, but i think this is a potential issue

### Expected behavior (Required)
tablet state is normal
### Real behavior (Required)
```
ERROR 1064 (HY000): get_applied_rowsets failed, tablet updates is in error state: tablet:23018 actual row size changed after compaction 12121 -> 4095 tablet:23018 #version:5 [6 7.3@4 7.3] pending: rowsets:1
  568 [seg:2 row:12121 del:8026 bytes:1099563 compaction:36095279]
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by caneGuy**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9405

### CODE REVIEW

File: be/src/storage/tablet_updates.cpp [hunk 1]
```diff
@@ -1319,13 +1319,26 @@ void TabletUpdates::_apply_compaction_commit(const EditVersionInfo& version_info
...
+    for (int i = 0; i < info->inputs.size(); ++i) {
+        uint32_t rowsetid = info->inputs[i];
+        auto itr = _rowsets.find(rowsetid);
+        if (itr == _rowsets.end()) {
+            string msg = Substitute("rowset not found tablet=$0 rowset=$1", _tablet.tablet_id(), rowsetid);
+            DCHECK(false) << msg;
+            LOG(WARNING) << msg;
+            continue;
+        }
+        uint32_t rowset_max_rssid = rowsetid + itr->second->num_segments();
```
Comment (sevev) [inline be/src/storage/tablet_updates.cpp:1332]: maybe `uint32_t rowset_max_rssid = rowsetid + itr->second->num_segments() -1;`

File: be/src/storage/tablet_updates.cpp [hunk 2]
```diff
@@ -1319,13 +1319,29 @@ void TabletUpdates::_apply_compaction_commit(const EditVersionInfo& version_info
...
+        if (itr == _rowsets.end()) {
+            string msg = Substitute("rowset not found tablet=$0 rowset=$1", _tablet.tablet_id(), rowsetid);
+            DCHECK(false) << msg;
+            LOG(WARNING) << msg;
+            continue;
+        }
+        uint32_t rowset_max_rssid = rowsetid + itr->second->num_segments() - 1;
+        max_src_rssid = std::max(max_src_rssid, (int64_t) rowset_max_rssid);
+    }
+
```
Comment (decster) [inline be/src/storage/tablet_updates.cpp:1337]: only need to get rowset of with max rowset id, do not need to get all rowsets

Comment (caneGuy) [reply be/src/storage/tablet_updates.cpp:1337]: There is a scene I don't know if it will appear. we have rowset id 1 and 2, rowset 1 has 3 segments and rowset 2 has 1 segment. then we may get rssid from index cache with value 4 for rowset 1.

Comment (decster) [reply be/src/storage/tablet_updates.cpp:1337]: no, rssid will not overlap

**Comment by decster** [comment]
fix clang format?

File: be/src/storage/tablet_updates.cpp [hunk 3]
```diff
@@ -1319,13 +1319,27 @@ void TabletUpdates::_apply_compaction_commit(const EditVersionInfo& version_info
     size_t total_rows = 0;
     vector<std::pair<uint32_t, DelVectorPtr>> delvecs;
     vector<uint32_t> tmp_deletes;
+
+    // Since value stored in info->inputs of CompactInfo is rowset id
+    // we should get the real max rssid here by segment number
+    uint32_t max_rowsetid = *std::max_element(info->inputs.begin(), info->inputs.end());
+    auto itr = _rowsets.find(max_rowsetid);
```
Comment (decster) [inline be/src/storage/tablet_updates.cpp:1326]: this needs lock held, or just use  `_get_rowset` like in earlier code
```
if (!(st = _compaction_state->load(_get_rowset(rowset_id).get())).ok()) {
```

**Review by decster — APPROVED** [review]

**Comment by decster** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]
