### PR TITLE
[Enhancement] Re-design the behaviour of builtin storage volume

### LINKED ISSUE #26049: [storage volume] fe start failed when s3 info not in congfig file
### Steps to reproduce the behavior (Required)
`2023-06-27 20:40:20,006 ERROR (UNKNOWN 172.26.95.102_9010_1687827465061(-1)|1) [StarMgrServer.initialize():141] The configuration item "aws_s3_path = " is invalid, s3 bucket is empty.`

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-36de4d8`

### PR DESCRIPTION
**Pull request by TszKitLo40**
Fixes #26049 
Add a config `enable_load_volume_from_conf`, the default value is true for backward compatibility. If `enable_load_volume_from_conf` is true, if the storage volume related config in fe.conf is valid, a builtin storage volume will be created. Otherwise FE will fail to start and print a fatal error log. In later version, the default value may be set to false.

## What type of PR is this:
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 1]
```diff
@@ -2030,6 +2030,13 @@ public class Config extends ConfigBase {
...
+
+    /**
+     *  Whether volume can be created from conf. If it is enabled, a builtin storage volume may be created.
+     */
+    @ConfField
+    public static boolean enable_volume_from_conf = true;
+
     // remote storage related configuration
     @ConfField(comment = "storage type for cloud native table. Available options: \"S3\", \"HDFS\", \"AZBLOB\". case-insensitive")
     public static String cloud_native_storage_type = "S3";
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:2042]: shall set this to empty by default.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 54 (90.74%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|5|7|71.43%|[53, 63]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|4|75.00%|[4043]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|35|37|94.59%|[267, 284]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java [hunk 2]
```diff
@@ -238,17 +239,86 @@ public String createOrUpdateBuiltinStorageVolume() throws DdlException, AlreadyE
...
+    public void validateStorageVolumeConfig() throws InvalidConfException {
+        switch (Config.cloud_native_storage_type.toLowerCase()) {
+            case "s3":
+                String[] bucketAndPrefix = getBucketAndPrefix();
+                String bucket = bucketAndPrefix[0];
+                if (bucket.isEmpty()) {
+                    throw new InvalidConfException(
+                            String.format("The configuration item \"aws_s3_path = %s\" is invalid, s3 bucket is empty.",
+                                    Config.aws_s3_path));
+                }
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/server/SharedDataStorageVolumeMgr.java:262]: add endpoint or region check, either should be non-empty but not both.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java [hunk 3]
```diff
@@ -47,11 +47,20 @@ public Void visitCreateStorageVolumeStatement(CreateStorageVolumeStmt statement,
...
+                        StorageVolumeMgr.BUILTIN_STORAGE_VOLUME));
+            }
 
             List<String> locations = statement.getStorageLocations();
             if (locations.isEmpty()) {
                 throw new SemanticException("'storage volume locations' can not be empty");
             }
+            for (String location : locations) {
+                if (location.isEmpty()) {
+                    throw new SemanticException("'location in storage volume' can not be empty");
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java:61]: 'location' field is required to create the storage volume

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java [hunk 4]
```diff
@@ -47,11 +47,20 @@ public Void visitCreateStorageVolumeStatement(CreateStorageVolumeStmt statement,
...
                 throw new SemanticException("'storage volume name' can not be null or empty");
             }
+            if (svName.equals(StorageVolumeMgr.BUILTIN_STORAGE_VOLUME)) {
+                throw new SemanticException(String.format("%s can not be created by SQL",
+                        StorageVolumeMgr.BUILTIN_STORAGE_VOLUME));
+            }
 
             List<String> locations = statement.getStorageLocations();
             if (locations.isEmpty()) {
                 throw new SemanticException("'storage volume locations' can not be empty");
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java:57]: keep the error message consistent.

File: fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java [hunk 5]
```diff
@@ -121,62 +121,6 @@ public void initialize(BDBEnvironment environment, String baseImageDir) throws I
         com.staros.util.Config.STARMGR_IP = FrontendOptions.getLocalHostAddress();
         com.staros.util.Config.STARMGR_RPC_PORT = Config.cloud_native_meta_port;
 
-        // Storage fs type
-        com.staros.util.Config.DEFAULT_FS_TYPE = Config.cloud_native_storage_type;
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/staros/StarMgrServer.java:125]: com.staros.util.Config.DEFAULT_FS_TYPE = ""

force starmgr not creating those `xxx_from_config` in case the default value is not empty.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 57 (85.96%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|6|50.00%|[766, 767, 768]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|34|39|87.18%|[263, 264, 265, 282, 286]|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 6]
```diff
@@ -2030,6 +2030,13 @@ public class Config extends ConfigBase {
      */
     @ConfField
     public static int cloud_native_meta_port = 6090;
+
+    /**
+     *  Whether volume can be created from conf. If it is enabled, a builtin storage volume may be created.
+     */
+    @ConfField
+    public static boolean enable_volume_from_conf = true;
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:2038]: enable_load_volume_from_conf ?

Comment (TszKitLo40) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: > enable_load_volume_from_conf ?

OK

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 51 / 59 (86.44%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|6|50.00%|[766, 767, 768]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|35|40|87.50%|[263, 264, 265, 282, 286]|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 51 / 60 (85.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|3|6|50.00%|[766, 767, 768]|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|5|6|83.33%|[58]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|36|41|87.80%|[267, 268, 269, 286, 290]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 7]
```diff
@@ -4033,7 +4040,7 @@ public MetaContext getMetaContext() {
 
     public void createOrUpdateBuiltinStorageVolume() {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:4041]:
```suggestion
    public void createBuiltinStorageVolume() {
```

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 1 above)
Comment (wyb) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java:2042]: some users may use the default value s3 in 3.0 version, so we should not change the default value.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 52 / 61 (85.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|4|7|57.14%|[766, 767, 768]|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|5|6|83.33%|[58]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|37|42|88.10%|[267, 268, 269, 286, 290]|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

**Review by wyb — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 61 / 68 (89.71%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/SharedNothingStorageVolumeMgr.java|0|1|00.00%|[157]|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|2|5|40.00%|[4041, 4042, 4043]|
|:large_blue_circle:|com/starrocks/sql/analyzer/StorageVolumeAnalyzer.java|5|6|83.33%|[58]|
|:large_blue_circle:|com/starrocks/server/SharedDataStorageVolumeMgr.java|48|50|96.00%|[275, 292]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/staros/StarMgrServer.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/storagevolume/StorageVolume.java|4|4|100.00%|[]|

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
