### PR TITLE
[BugFix] Json loader will lead to BE crash if it reads an error row.

### LINKED ISSUE #6051: stream load for json will lead to BE crash when loading uint64_t::min(-9223372036854775808)
### Steps to reproduce the behavior (Required)
1. create table {
  ....
  a BIGINT;
  ....
}

2. create a json file like the following
{
  a: -9223372036854775808
}

3. use stream load to load the json file into table
curl -v --location-trusted -u xxx: xxx -H "format: json"  -T example.json http://xxx/api/test1/table/_stream_load

### Expected behavior (Required)
succeed to load 
### Real behavior (Required)
BE crash
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
03059fff1f79a7c45d47444ad32686bb0e6369b6

### LINKED ISSUE #6052: stream load for json will lead to be crash when loading number out of range in the strict model.
### Steps to reproduce the behavior (Required)
1. create table {
  ....
  a INT;
  ....
}

2. create a json file like the following
{
  a: -9223372036854775807
}

3. use stream load to load the json file into table
curl -v --location-trusted -u xxx: xxx -H "format: json" -H "strict_model: true" -T example.json http://xxx/api/test1/table/_stream_load

### Expected behavior (Required)
fail to load because -9223372036854775807 is out of range for int
### Real behavior (Required)
BE crash
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
03059fff1f79a7c45d47444ad32686bb0e6369b6

### LINKED ISSUE #6097: BE crash for loading wrong format JSON file
### Steps to reproduce the behavior (Required)
1. create table {
  ....
}

2. create a json file like the following
{"a": -9223372036854775808 "b": 222}
there is no ',' between field a and field b

3. use stream load to load the json file into table
curl -v --location-trusted -u xxx: xxx -H "format: json"  -T example.json http://xxx/api/test1/table/_stream_load

### Expected behavior (Required)
fail to load 
### Real behavior (Required)
BE crash
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
03059fff1f79a7c45d47444ad32686bb0e6369b6

### LINKED ISSUE #6098: BE crash for loading wrong format JSON file
### Steps to reproduce the behavior (Required)
1. create table {
  ....
}

2. create a json file like the following
{"a": "sss" "b": 222}
there is no ',' between field a and field b

3. use stream load to load the json file into table
curl -v --location-trusted -u xxx: xxx -H "format: json"  -T example.json http://xxx/api/test1/table/_stream_load

### Expected behavior (Required)
fail to load 
### Real behavior (Required)
BE crash
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
03059fff1f79a7c45d47444ad32686bb0e6369b6

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #6052
Fixes #6051
Fixes #6098
Fixes #6097
## Problem Summary(Required) ：

Now, the JSON loader will lead to BE crash if it meets an error row.
In the non-strict model, the data(number, string) which cannot be parsed by simdjson will be filled with NULL. However, in the strict model, the data which can not be parsed by simdjson will not be filled with NULL. This will lead to the error column containing one row less than the other columns. In this pr, we will remove the error row before we continue to parse other rows.

Apart from this, there's a bug in simdjson which will recognize -9223372036854775808 as an unsigned number, this pr also adds additional logic to handle this.

### CODE REVIEW

File: be/src/formats/json/numeric_column.cpp [hunk 1]
```diff
@@ -39,10 +39,30 @@ static Status add_column_with_numeric_value(FixedLengthColumn<T>* column, const
     }
 
     case simdjson::ondemand::number_type::unsigned_integer: {
-        uint64_t in = value->get_uint64();
         T out{};
+        // When get_uint64 throws an exception here, we need to recheck it with get_int64.
+        // This is because currently there exists a bug in simdjson, for number <= -9223372036854775808,
+        // simdjson will recognized it as unsigned_integer, and use get_uint64() to parse it, which will
+        // raise an exception here. So here we need to recheck by get_int64().
+        // This bug in simdjson is expected to be solved by the following commit, lator we can remove
```
Comment (rickif) [inline be/src/formats/json/numeric_column.cpp:47]: `lator we can remove` - > `later we can remove`

File: be/src/exec/vectorized/json_scanner.cpp [hunk 2]
```diff
@@ -437,6 +437,15 @@ Status JsonReader::_read_rows(Chunk* chunk, int32_t rows_to_read, int32_t* rows_
                 _state->append_error_msg_to_file(std::string(sv.data(), sv.size()), st.to_string());
                 LOG(WARNING) << "failed to construct row: " << st;
             }
+            if (st.is_data_quality_error() || st.is_invalid_argument()) {
```
Comment (rickif) [inline be/src/exec/vectorized/json_scanner.cpp:440]: It seems that `read_chunk()` at line 405 has handled this but dose not work. Could you please check it and retain one of them?

File: be/src/formats/json/numeric_column.cpp [hunk 3]
```diff
@@ -39,10 +39,30 @@ static Status add_column_with_numeric_value(FixedLengthColumn<T>* column, const
...
+        try {
+            in = value->get_uint64();
+            checked_cast_flag = checked_cast(in, &out);
+        } catch (simdjson::simdjson_error& e) {
+            // only needs to handle int64_t::min here, throw exception for any other number
+            // get_int64() itself may also throw exception
+            if (value->get_int64() == std::numeric_limits<int64_t>::min()) {
+                checked_cast_flag = checked_cast(std::numeric_limits<int64_t>::min(), &out);
+            } else {
+                throw simdjson::simdjson_error(simdjson::error_code::NUMBER_OUT_OF_RANGE);
```
Comment (rickif) [inline be/src/formats/json/numeric_column.cpp:61]: Is it better to return an error instead?

Comment (xiaoyong-z) [reply be/src/formats/json/numeric_column.cpp:61]: In the original code, it should raise an exception here because it can not be parsed by simdjson get_uint64(). 
Here we recheck if it is a std::numeric_limits<int64_t>::min() due to a bug in simdjson. If it is not, i think we should still throw an exception here?

**Review by chaoyli — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

File: be/src/exec/vectorized/json_scanner.cpp [hunk 4]
```diff
@@ -73,9 +73,21 @@ StatusOr<ChunkPtr> JsonScanner::get_next() {
...
     }
-    Status status = _cur_file_reader->read_chunk(src_chunk.get(), _max_chunk_size);
-    if (status.is_end_of_file()) {
-        _cur_file_eof = true;
+
+    Status status;
+    try {
+        status = _cur_file_reader->read_chunk(src_chunk.get(), _max_chunk_size);
+    } catch (simdjson::simdjson_error& e) {
+        auto err_msg = strings::Substitute("The format of the json file may be wrong, stop json loader.");
```
Comment (mofeiatwork) [inline be/src/exec/vectorized/json_scanner.cpp:81]: Unrecognized json format?

**Review by chaoyli — DISMISSED** [review]

File: be/src/exec/vectorized/json_scanner.cpp [hunk 5]
```diff
@@ -73,9 +73,21 @@ StatusOr<ChunkPtr> JsonScanner::get_next() {
...
     }
-    Status status = _cur_file_reader->read_chunk(src_chunk.get(), _max_chunk_size);
-    if (status.is_end_of_file()) {
-        _cur_file_eof = true;
+
+    Status status;
+    try {
+        status = _cur_file_reader->read_chunk(src_chunk.get(), _max_chunk_size);
+    } catch (simdjson::simdjson_error& e) {
+        auto err_msg = strings::Substitute("Unrecognized json format, stop json loader.");
```
Comment (rickif) [inline be/src/exec/vectorized/json_scanner.cpp:81]: `strings::Substitute` is unnecessary here since no format arg is provided.

File: be/src/formats/json/nullable_column.cpp [hunk 6]
```diff
@@ -185,7 +185,7 @@ Status add_nullable_column(Column* column, const TypeDescriptor& type_desc, cons
         }
 
         auto st = add_nullable_column(column, type_desc, name, value);
-        if (st.is_invalid_argument() && invalid_as_null) {
+        if ((st.is_invalid_argument() || st.is_data_quality_error()) && invalid_as_null) {
```
[the remark this answers is not in the document]
Comment (xiaoyong-z) [reply be/src/formats/json/nullable_column.cpp:188]: may be `!st.ok()` ?

**Review by rickif — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
