### PR TITLE
[BugFix] Get pid file lock failed when restart fe

### LINKED ISSUE #5580: FE start failed with error: pid file is already locked
### Steps to reproduce the behavior (Required)
CInVGvKbUb
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - cf45893

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Try to fix #5580

## Problem Summary(Required) ：

Retry 3 times if get file lock failed, and print the fail reson.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java [hunk 1]
```diff
@@ -277,26 +277,34 @@ private static void checkCommandLineOptions(CommandLineOptions cmdLineOpts) {
...
-            if (lock == null) {
-                return false;
-            }
+        for (int i = 0; i < 3; i++) {
+            try (RandomAccessFile file = new RandomAccessFile(pid, "rws")) {
+                FileLock lock = file.getChannel().tryLock();
+                if (lock == null) {
+                    LOG.warn("get pid file lock failed, retried: {}", i);
+                    Thread.sleep(10000L);
+                    continue;
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:288]: why not throw a exception

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:288]: The caller determines whether the lock acquisition was successful based on the return of true/false.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:288]: https://github.com/StarRocks/starrocks/pull/5615/files#diff-4e26971c00c7e12e700dcfb24c434a2c711047605ab45e1407c3a271a13b5c95L81

Comment (imay) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:288]: I want to say is that you throw an exception here, the following catch can handle this exception.

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java [hunk 2]
```diff
@@ -277,26 +277,34 @@ private static void checkCommandLineOptions(CommandLineOptions cmdLineOpts) {
...
-    private static boolean createAndLockPidFile(String pidFilePath) throws IOException {
+    private static boolean createAndLockPidFile(String pidFilePath) {
         File pid = new File(pidFilePath);
-        try (RandomAccessFile file = new RandomAccessFile(pid, "rws")) {
-            FileLock lock = file.getChannel().tryLock();
-            if (lock == null) {
-                return false;
-            }
+        for (int i = 0; i < 3; i++) {
+            try (RandomAccessFile file = new RandomAccessFile(pid, "rws")) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:283]: It's better to find the core problem with the lock held.
Why the exit of FE can not release the lock?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:283]: This problem only occurred in our daily env, but I have not found the root cause. This PR is try to fix this bug, and print more error log if get lock failed.

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java]: done

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java [hunk 3]
```diff
@@ -277,26 +277,34 @@ private static void checkCommandLineOptions(CommandLineOptions cmdLineOpts) {
...
-            return true;
-        } catch (OverlappingFileLockException e) {
-            return false;
-        } catch (IOException e) {
-            throw e;
+                return true;
+            } catch (Throwable t) {
+                try {
+                    LOG.warn("get pid file lock failed, retried: {}", i, t);
+                    Thread.sleep(10000L);
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:299]: I suggest you move `Thread.sleep(1000L)` inside the try-catch scope to avoid empty catch block.

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java (hunk 2 above)
Comment (chaoyli) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:283]: If it's a temporary solution, you can add your PR into a daily environment instead of the main branch.
After finding the root cause, you can make a pull request to address the problem ultimately.

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java (hunk 3 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java]: done

File: fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java (hunk 2 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/StarRocksFE.java:283]: But daily can not run this pr every day. It is not always reproducible.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 15 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/StarRocksFE.java|0|15|00.00%|

**Review by imay — APPROVED** [review]

**Review by padmejin — APPROVED** [review]
LGTM

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
do not merge
