### PR TITLE
[BugFix] fix invalid partition predicate bug

### LINKED ISSUE #19352: partition predicate is invalid
In ssb mv rewrite test, the generated partition predicate is useless and meanless, which is a bug.

### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
create mv one ssb's all tables.
and add foreign constraint and unique constraints on base tables
the fire query Q3.

### Expected behavior (Required)
remove the invalid predicate
### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19352 

## Problem Summary(Required) ：

fix invalid partition predicate bug by removing useless predicates.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 1]
```diff
@@ -1155,7 +1155,13 @@ private PredicateSplit getCompensationPredicates(RewriteContext rewriteContext,
         if (srcPu == null && targetPu != null) {
             // query: empid < 5
             // mv: empid < 5 or salary > 100
-            srcPu = Utils.compoundAnd(compensationEqualPredicate, compensationPr);
+            if (!isQueryAgainstView) {
+                // compensationEqualPredicate and compensationPr is based on query, need to change it to view based
+                srcPu = Utils.compoundAnd(columnRewriter.rewriteQueryToView(compensationEqualPredicate),
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1160]: `columnRewriter.rewriteQueryToView(compensationEqualPredicate)` can be null ?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java [hunk 2]
```diff
@@ -141,6 +142,68 @@ public ScalarOperator simplify(List<ScalarOperator> targets) {
...
+        for (ScalarOperator candidate : columnScalars) {
+            if (!isValidScalarOperator(candidate, validRange)) {
+                continue;
+            }
+            results.add(candidate);
+        }
+        return results;
+    }
+
+    boolean isValidScalarOperator(ScalarOperator scalarOperator, Range<ConstantOperator> validRange) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java:157]: `isRedundantScalarOperator` better?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 3]
```diff
@@ -1178,25 +1184,25 @@ private ScalarOperator getCompensationResidualPredicate(ScalarOperator srcPu,
...
             compensationPu = srcPu;
         } else {
-            ScalarOperator canonizedSrcPu = MvUtils.canonizePredicateForRewrite(srcPu.clone());
-            ScalarOperator canonizedTargetPu = MvUtils.canonizePredicateForRewrite(targetPu.clone());
             ScalarOperator swappedSrcPu;
             ScalarOperator swappedTargetPu;
             if (isQueryAgainstView) {
                 // src is query
-                swappedSrcPu = columnRewriter.rewriteByQueryEc(canonizedSrcPu);
+                swappedSrcPu = columnRewriter.rewriteByQueryEc(srcPu.clone());
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1191]: why clone here ? `rewriteByQueryEc ` can change the input?

**Review by murphyatwork — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1160]: null is ok for compoundAnd

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1191]: to make sure the swappedSrcPu is new object because the following process will change swappedSrcPu and swappedSrcPu may be null.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 56 (87.50%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRewriter.java|1|2|50.00%|[189]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|28|34|82.35%|[168, 170, 172, 190, 193, 202]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|20|20|100.00%|[]|

**Review by LiShuMing — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 4]
```diff
@@ -1155,7 +1155,13 @@ private PredicateSplit getCompensationPredicates(RewriteContext rewriteContext,
         if (srcPu == null && targetPu != null) {
             // query: empid < 5
             // mv: empid < 5 or salary > 100
-            srcPu = Utils.compoundAnd(compensationEqualPredicate, compensationPr);
+            if (!isQueryAgainstView) {
+                // compensationEqualPredicate and compensationPr is based on query, need to change it to view based
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1159]: Why ViewAgainsQuery need to rewrite to view based?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java [hunk 5]
```diff
@@ -141,6 +142,68 @@ public ScalarOperator simplify(List<ScalarOperator> targets) {
...
+        Preconditions.checkState(scalarOperator.getChild(0) instanceof ColumnRefOperator);
+        Preconditions.checkState(scalarOperator.getChild(1) instanceof ConstantOperator);
+        BinaryPredicateOperator binary = scalarOperator.cast();
+        ConstantOperator right = binary.getChild(1).cast();
+
+        if (binary.getBinaryType().equals(BinaryPredicateOperator.BinaryType.LE) && validRange.hasUpperBound()) {
+            if (validRange.upperBoundType() == BoundType.CLOSED
+                    && right.compareTo(validRange.upperEndpoint()) > 0) {
+                // for validRange: [10, 20], scalar: x <= 30, skip it
+                return false;
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java:168]: for skip predicate, return true?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRewriter.java|1|2|50.00%|[189]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|28|34|82.35%|[168, 170, 172, 190, 193, 202]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|8|8|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1159]: because compensationPr is now based on query, but we need predicates based on views as input

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 37 / 44 (84.09%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRewriter.java|1|2|50.00%|[189]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|28|34|82.35%|[168, 170, 172, 190, 193, 202]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|8|8|100.00%|[]|

**Review by Youngwb — DISMISSED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by ABingHuang** [comment]
run starrocks_be_unittest

**Comment by ABingHuang** [comment]
run starrocks_clang-format

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by mofeiatwork** [comment]
run all

**Comment by ABingHuang** [comment]
run starrocks_fe_unittest

**Comment by ABingHuang** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 34 / 35 (97.14%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/ColumnRewriter.java|1|2|50.00%|[189]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/RangeSimplifier.java|25|25|100.00%|[]|
