### PR TITLE
[BugFix] Using json as TxnFinishState serde

### LINKED ISSUE #15248: [Bug] FE start error when upgrading from 2.0 to 2.5
### Real behavior (Required)
```
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
        at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:107) ~[protobuf-java-3.16.3.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawByte(CodedInputStream.java:1242) ~[protobuf-java-3.16.3.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawVarint64SlowPath(CodedInputStream.java:1127) ~[protobuf-java-3.16.3.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawVarint64(CodedInputStream.java:1120) ~[protobuf-java-3.16.3.jar:?]
        at com.google.protobuf.CodedInputStream$ArrayDecoder.readInt64(CodedInputStream.java:763) ~[protobuf-java-3.16.3.jar:?]
        at com.starrocks.proto.TxnFinishStatePB$$JProtoBufClass.readFrom(TxnFinishStatePB$$JProtoBufClass.java:127) ~[?:?]
        at com.starrocks.proto.TxnFinishStatePB$$JProtoBufClass.decode(TxnFinishStatePB$$JProtoBufClass.java:37) ~[?:?]
        at com.starrocks.proto.TxnFinishStatePB$$JProtoBufClass.decode(TxnFinishStatePB$$JProtoBufClass.java:24) ~[?:?]
        at com.starrocks.transaction.TxnFinishState.fromBytes(TxnFinishState.java:50) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.TransactionState.readFields(TransactionState.java:782) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.GlobalTransactionMgr.readFields(GlobalTransactionMgr.java:709) ~[starrocks-fe.jar:?]
        at com.starrocks.transaction.GlobalTransactionMgr.loadTransactionState(GlobalTransactionMgr.java:736) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.loadImage(GlobalStateMgr.java:1266) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:894) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:116) [starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:68) [starrocks-fe.jar:?]

```
### StarRocks version (Required)
2.5, main

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15248

## Problem Summary(Required) ：

Originally, TxnFinishState is serialized using protobuf(baidu jprotobuf) and using the existing field `reason` in TxnState, when upgrading from version before 2.4 to 2.5, TxnFinishState serialized as binary string will be treated as `reason` string in older not upgraded FE, and the serialization of `reason` string will replace illegal chars in the string, which will corrupt TxnFinishState. So serialization using binary format is dangerous, and this PR change serialization format from protobuf to json.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 40 / 55 (72.73%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|11|23|47.83%|[800, 801, 803, 804, 805, 806, 807, 818, 819, 822, 823, 824]|
|:large_blue_circle:|com/starrocks/transaction/TxnFinishState.java|29|32|90.62%|[94, 95, 116]|

**Comment by decster** [comment]
run starrocks_admit_test

File: fe/fe-core/src/main/java/com/starrocks/transaction/TxnFinishState.java [hunk 1]
```diff
@@ -67,4 +74,46 @@ public void fromBytes(byte[] bytes) throws IOException {
             abnormalReplicasWithVersion.put(pb.abnormalReplicasWithVersion.get(i), pb.abnormalReplicasWithVersion.get(i + 1));
         }
     }
+
+    public String toJson() throws IOException {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/transaction/TxnFinishState.java:78]: Why not use GSON? What's the advantage to write json deserialize by hand?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 22 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|9|20|45.00%|[801, 802, 804, 805, 806, 807, 808, 815, 816, 819, 820]|
|:large_blue_circle:|com/starrocks/transaction/TxnFinishState.java|2|2|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/transaction/TxnFinishState.java (hunk 1 above)
Comment (decster) [reply fe/fe-core/src/main/java/com/starrocks/transaction/TxnFinishState.java]: done

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
