### PR TITLE
[Enhancement] Support _META_ scan with tablet() and partition() hints

### LINKED ISSUE #62673: Support `_META_` scan with `tablet()` and `partition()` hints
**Title**: Support `_META_` scan with `tablet()` and `partition()` hints

**Description**:
Currently, StarRocks supports querying internal metadata via `_META_` (meta\_scan). However, `_META_` does not support the `tablet()` or `partition()` hints, which makes it impossible to restrict metadata scan to a specific tablet or partition.

**Example**:

```sql
-- Expected usage with tablet hint
SELECT COUNT(time_us) 
FROM bluesky 
TABLET(1055) 
[_META_];

-- Expected usage with partition hint
SELECT COUNT(time_us) 
FROM bluesky 
PARTITION(p202409) 
[_META_];
```

**Current Behavior**:
The above queries fail because `_META_` does not recognize or push down `tablet()` and `partition()` hints. `_META_` scan always scans all tablets’ metadata, which can be inefficient or even impossible in large clusters.

**Expected Behavior**:

* `_META_` scan should support both `tablet()` and `partition()` hints, just like normal OLAP scan.
* The optimizer should push down these restrictions to `meta_scan`, so that only metadata of the specified tablet or partition is returned.

**Use Cases**:

1. **Diagnostics**: DBAs need to check metadata of a single tablet or partition for debugging.
2. **Performance**: Scanning only the target tablet or partition metadata reduces overhead.
3. **Consistency**: Aligns `_META_` scan with standard scan syntax, making it easier for users to understand and use.

### PR DESCRIPTION
**Pull request by EdwardArchive**
## Why I'm doing:

META scan currently ignores tablet hints, making it impossible to target specific tablets for metadata queries.

## What I'm doing:

Propagate hintsTabletIds from LogicalOlapScanOperator to MetaScanNode through the optimizer pipeline, enabling tablet-level filtering in META scans.

The outcome of this PR is as follows.
image

Fixes #62673

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [ ] 4.0
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3

---

> [!NOTE]
> _META_ scans now respect TABLET(...) hints (and partitions), filtering to specified tablets and showing TabletIds in EXPLAIN; optimizer/planner propagation added with tests and a test helper.
> 
> - **Planner/Execution**:
>   - `MetaScanNode`: accept `hintsTabletIds`, filter tablets by hint set, and append `TabletIds` to EXPLAIN when hints present.
>   - `PlanFragmentBuilder`: pass `hintsTabletIds` from physical operator to `MetaScanNode`.
> - **Optimizer**:
>   - `LogicalMetaScanOperator`/`PhysicalMetaScanOperator`: add `hintsTabletIds`, getters, equals/hash, and builder wiring.
>   - `RelationTransformer`: propagate `node.getTabletIds()` into `LogicalMetaScanOperator` for meta queries.
>   - `RewriteSimpleAggToMetaScanRule`: preserve `hintsTabletIds` when rewriting to `MetaScan`.
> - **Tests/Utils**:
>   - Add META scan tablet-hint tests (`LowCardinalityTest`, SQL R/T cases) validating empty results for invalid hints and EXPLAIN `TabletIds` output.
>   - Test lib: add `set_first_tablet_id()` helper to fetch a tablet id for tests.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 4d9eede2f62a25fff28a7d8306dba86a57d7edf6. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by EdwardArchive** [comment]
Hi @murphyatwork,
Can you check out this PR?
I might be missing some history here, so apologies if this question sounds a bit naive. While implementing tablet hint support for _META_ scan (#62673), I noticed an inconsistency between the equals() and hashCode() methods in several Operator classes.

### LogicalOlapScanOperator - Missing: distributionSpec, partitionNames
fe\fe-core\src\main\java\com\starrocks\sql\optimizer\operator\logical\LogicalOlapScanOperator.java
```java
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (!super.equals(o)) {
            return false;
        }

        LogicalOlapScanOperator that = (LogicalOlapScanOperator) o;
        return selectedIndexId == that.selectedIndexId &&
                gtid == that.gtid &&
                Objects.equals(distributionSpec, that.distributionSpec) &&
                Objects.equals(selectedPartitionId, that.selectedPartitionId) &&
                Objects.equals(partitionNames, that.partitionNames) &&
                Objects.equals(selectedTabletId, that.selectedTabletId) &&
                Objects.equals(sample, that.sample) &&
                Objects.equals(hintsTabletIds, that.hintsTabletIds) &&
                Objects.equals(hintsReplicaIds, that.hintsReplicaIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), selectedIndexId, gtid, selectedPartitionId,
                selectedTabletId, hintsTabletIds, hintsReplicaIds, sample);
    }
```

### LogicalMetaScanOperator - Missing: partitionNames
```java
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        if (!super.equals(o)) {
            return false;
        }
        LogicalMetaScanOperator that = (LogicalMetaScanOperator) o;
        return Objects.equals(aggColumnIdToNames, that.aggColumnIdToNames) &&
                Objects.equals(selectPartitionNames, that.selectPartitionNames) &&
                Objects.equals(hintsTabletIds, that.hintsTabletIds) &&
                selectedIndexId == that.selectedIndexId;
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), aggColumnIdToNames, hintsTabletIds);
    }
````

Was this omission intended to reduce the computation cost of `hashCode()` for complex objects such as `DistributionSpec`?  
For `LogicalMetaScanOperator`, should we add the missing fields (`selectPartitionNames`, `selectedIndexId`) to `hashCode()` to comply with Java’s equals/hashCode contract?

From the history I found:  
- PR #17199: Deleted `hashDistributionSpec` from `hashCode()`  
- PR #52383: Added `selectPartitionNames` to `equals()` but not to `hashCode()`

Thanks.

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: test/sql/test_meta_scan/T/test_meta_scan [hunk 1]
```diff
@@ -246,3 +246,28 @@ SELECT count(*), max(k10), min(k10), count(k10) FROM update_table_with_null_part
...
+    PARTITION p2 VALUES LESS THAN ("2020-02-01"),
+    PARTITION p3 VALUES LESS THAN ("2020-03-01")
+)
+DISTRIBUTED BY HASH(k1) BUCKETS 3
+PROPERTIES ("replication_num" = "1");
+
+INSERT INTO t_tablet_hint VALUES ("2019-12-01", 10), ("2020-01-15", 20), ("2020-02-15", 30);
+
+-- Test: Single tablet hint - EXPLAIN should show TabletIds
+EXPLAIN SELECT min(k2), max(k2) FROM t_tablet_hint TABLET(99999) [_META_];
```
Comment (alvin-phoenix-ai) [inline test/sql/test_meta_scan/T/test_meta_scan]: How do you know the tablet id would be 99999?

File: test/sql/test_meta_scan/T/test_meta_scan [hunk 2]
```diff
@@ -246,3 +246,28 @@ SELECT count(*), max(k10), min(k10), count(k10) FROM update_table_with_null_part
...
+    k2 int
+)
+DUPLICATE KEY(k1)
+PARTITION BY RANGE(k1) (
+    PARTITION p1 VALUES LESS THAN ("2020-01-01"),
+    PARTITION p2 VALUES LESS THAN ("2020-02-01"),
+    PARTITION p3 VALUES LESS THAN ("2020-03-01")
+)
+DISTRIBUTED BY HASH(k1) BUCKETS 3
+PROPERTIES ("replication_num" = "1");
```
Comment (alvin-phoenix-ai) [inline test/sql/test_meta_scan/T/test_meta_scan:258]: We can use the new way to create a table, and partitions can be generated when data is ingested.

File: test/sql/test_meta_scan/T/test_meta_scan (hunk 1 above)
Comment (EdwardArchive) [reply test/sql/test_meta_scan/T/test_meta_scan]: The tablet_id 99999 is just an example — I knows it doesn't need to exist in the table. EXPLAIN queries only generate a logical plan, so they don't actually access or validate physical tablets.

Comment (alvin-phoenix-ai) [reply test/sql/test_meta_scan/T/test_meta_scan]: EXPLAIN doesn't only generate a logical plan, but a plan that applies all partition pruning and tablet pruning. 
If there is no such tablet, the correct message in EXPLAIN should be empty tablets.

Comment (EdwardArchive) [reply test/sql/test_meta_scan/T/test_meta_scan]: Ahh....

Comment (EdwardArchive) [reply test/sql/test_meta_scan/T/test_meta_scan]: than I'll approach like OlapScan way

**Comment by alvin-phoenix-ai** [comment]
@cursor review

File: fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java [hunk 3]
```diff
@@ -213,6 +246,9 @@ protected String getNodeExplainString(String prefix, TExplainLevel detailLevel)
         if (!selectPartitionNames.isEmpty()) {
             output.append(prefix).append("Partitions: ").append(selectPartitionNames).append("\n");
         }
+        if (!hintsTabletIds.isEmpty()) {
+            output.append(prefix).append("TabletIds: ").append(hintsTabletIds).append("\n");
+        }
```
Comment (alvin-phoenix-ai) [inline fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java:248]: I think you should print the tablet IDs which are included in `result`.

File: fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java [hunk 4]
```diff
@@ -87,6 +92,28 @@ public void computeRangeLocations(ComputeResource computeResource) {
...
+                }
+            }
+
+            for (Long hintTabletId : hintsTabletIds) {
+                if (!allValidTabletIds.contains(hintTabletId)) {
+                    throw new StarRocksPlannerException(
+                            "Invalid tablet id: '" + hintTabletId + "'", USER_ERROR);
+                }
+            }
+        }
```
Comment (alvin-phoenix-ai) [inline fe/fe-core/src/main/java/com/starrocks/planner/MetaScanNode.java]: I don't think this check is necessary.
If the given hint tablets are not correct, we can continue with an empty result.

**Comment by EdwardArchive** [comment]
@alvin-celerdata  
Hi, I’ve just finished rebasing and resolved the conflicts.  
I also addressed the review comments.  

My latest changes on this PR can be found here:  
https://github.com/StarRocks/starrocks/pull/66744/changes/4d9eede2f62a25fff28a7d8306dba86a57d7edf6

**Review by murphyatwork — APPROVED** [review]

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by murphyatwork — DISMISSED** [review]

**Comment by EdwardArchive** [comment]
@alvin-celerdata 
Hi alvin, sorry for the commenting at the end of the year.

Could you please guide me on what additional steps are needed to move this PR toward merge?

Thank you! Have a wonderful rest of the year!

**Review by alvin-phoenix-ai — APPROVED** [review]
