### PR TITLE
[BugFix] Fix empty result set

### LINKED ISSUE #7602: [sqlsmith_master_release]:Backend not found. HdfsOrcScanner&HdfsScanner
### Steps to reproduce the behavior (Required)
1. SELECT '...'
```
use sqlsmith;
select
  ref_1.c_last_name as c0,

    sum(
      cast(case when false then cast(null as DOUBLE) else cast(null as DOUBLE) end
         as DOUBLE)) over (partition by ref_1.c_email_address order by ref_1.c_first_name) as c1,
  ref_1.c_current_addr_sk as c2
from
  sqlsmith.hive_ssb_100g_orc_part as ref_0
    inner join sqlsmith.tpcds_100g_customer as ref_1
    on (ref_0.p_color = ref_1.c_customer_id )
where (ref_0.p_color is NULL)
  or (random() > power(
      cast(pi() as DOUBLE),
      cast(e() as DOUBLE)));
```

### Expected behavior (Required)
Successful execution
### Real behavior (Required)
Backend not found. Check if any backend is down or not

### Be stack
```
*** Aborted at 1655816476 (unix time) try "date -d @1655816476" if you are using GNU date ***
PC: @          0x3451277 _ZZN9starrocks10vectorized14HdfsOrcScanner11do_get_nextEPNS_12RuntimeStateEPSt10shared_ptrINS0_5ChunkEEENKUlvE_clEv
*** SIGSEGV (@0x0) received by PID 1586 (TID 0x7f23347a3700) from PID 0; stack trace: ***
    @          0x3f6ead2 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f2365375235 os::Linux::chained_handler()
    @     0x7f236537a031 JVM_handle_linux_signal
    @     0x7f236536d0c8 signalHandler()
    @     0x7f23648245f0 (unknown)
    @          0x3451277 _ZZN9starrocks10vectorized14HdfsOrcScanner11do_get_nextEPNS_12RuntimeStateEPSt10shared_ptrINS0_5ChunkEEENKUlvE_clEv
    @          0x34518b1 starrocks::vectorized::HdfsOrcScanner::do_get_next()
    @          0x344a954 starrocks::vectorized::HdfsScanner::get_next()
    @          0x34022e7 starrocks::connector::HiveDataSource::get_next()
    @          0x28472c4 starrocks::pipeline::ConnectorChunkSource::_read_chunk()
    @          0x2847400 starrocks::pipeline::ConnectorChunkSource::buffer_next_batch_chunks_blocking()
    @          0x2842028 _ZNSt17_Function_handlerIFvvEZN9starrocks8pipeline12ScanOperator18_trigger_next_scanEPNS1_12RuntimeStateEiEUlvE0_E9_M_invokeERKSt9_Any_data
    @          0x1fa30f0 starrocks::PriorityThreadPool::work_thread()
    @          0x3f0a107 thread_proxy
    @     0x7f236481ce65 start_thread
    @     0x7f2363e3788d __clone
    @                0x0 (unknown)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 891d5c4 |
+----------------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by DorianZheng**
Signed-off-by: dorianzheng <xingzhengde72@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/7602

## Problem Summary(Required) ：

The chunk `ck` might be empty if the entire file is skipped

### CODE REVIEW

File: be/src/exec/vectorized/hdfs_scanner_orc.cpp [hunk 1]
```diff
@@ -457,10 +457,14 @@ Status HdfsOrcScanner::do_get_next(RuntimeState* runtime_state, ChunkPtr* chunk)
     // in the chunk according to the order it's stored. This will lead two chunk from different file to
     // different column order, so we need to adjust the column order according to the input chunk to make
     // sure every chunk has same column order
-    auto convert_to_output = [chunk, &ck]() {
+    auto output_result_chunk = [chunk, &ck]() {
```
Comment (imay) [inline be/src/exec/vectorized/hdfs_scanner_orc.cpp:460]: name `chunk` and `ck` is too confusing. Could you give them more distinguished name?

Comment (DorianZheng) [reply be/src/exec/vectorized/hdfs_scanner_orc.cpp]: done

**Review by dirtysalt — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]
