### PR TITLE
[BugFix] Empty kafka message leads data lost in routine load

### LINKED ISSUE #8534: Empty kafka message leads data lost in routine load
### Steps to reproduce the behavior (Required)
1. Create table
```SQL
CREATE TABLE `tbl_simple` ( 
    `key1` int(11) NULL COMMENT "",
    `key2` int(11) NULL COMMENT "" 
) ENGINE=OLAP 
duplicate KEY(`key1`) 
COMMENT "OLAP" 
DISTRIBUTED BY HASH(`key1`) BUCKETS 3 
PROPERTIES (
    "replication_num" = "1", 
    "in_memory" = "false", 
    "storage_format" = "DEFAULT" 
);
```
1. Prepare data
The sample data contains 20 valid json message and a empty message. 
```
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}

{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
{"key1":1,"key2":2}
```
1. Create routine load
```
CREATE ROUTINE LOAD rl_simple ON tbl_simple COLUMNS (key1, key2) PROPERTIES ( "format" = "json", "strip_outer_array"="false", "jsonpaths"="[\"$.key1\", \"$.key2\"]" ) FROM KAFKA ( "kafka_broker_list" = "xxx", "kafka_topic" = "topic_simple", "kafka_partitions" = "0", "kafka_offsets" = "OFFSET_BEGINNING" ); 

```

### Expected behavior (Required)
All messges are inserted.
```
mysql> show routine load for rl_simple\G;
*************************** 1. row ***************************
                  Id: 74032
                Name: rl_simple
          CreateTime: 2022-07-11 16:29:46
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_simple
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"","strict_mode":"false","jsonpaths":"[\"$.key1\", \"$.key2\"]","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"false","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic_blank","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":380,"errorRows":0,"committedTaskNum":1,"loadedRows":20,"loadRowsRate":0,"abortedTaskNum":0,"totalRows":20,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":3009}
            Progress: {"0":"20"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
1 row in set (0.00 sec)

ERROR:
No query specified

mysql> select count(*) from tbl_simple;
+----------+
| count(*) |
+----------+
|       20 |
+----------+
1 row in set (0.00 sec)
```
### Real behavior (Required)
Some messages behind the empty message may be skipped.
```
                  Id: 74024
                Name: rl_simple
          CreateTime: 2022-07-11 16:21:25
           PauseTime: NULL
             EndTime: NULL
              DbName: default_cluster:db0
           TableName: tbl_simple
               State: RUNNING
      DataSourceType: KAFKA
      CurrentTaskNum: 1
       JobProperties: {"partitions":"*","columnToColumnExpr":"key1,key2","maxBatchIntervalS":"10","whereExpr":"*","dataFormat":"json","timezone":"Asia/Shanghai","format":"json","json_root":"","strict_mode":"false","jsonpaths":"[\"$.key1\", \"$.key2\"]","desireTaskConcurrentNum":"5","maxErrorNum":"0","strip_outer_array":"false","currentTaskConcurrentNum":"1","maxBatchRows":"200000"}
DataSourceProperties: {"topic":"topic_blank","currentKafkaPartitions":"0","brokerList":"172.26.92.155:9092"}
    CustomProperties: {}
           Statistic: {"receivedBytes":380,"errorRows":0,"committedTaskNum":1,"loadedRows":10,"loadRowsRate":0,"abortedTaskNum":0,"totalRows":10,"unselectedRows":0,"receivedBytesRate":0,"taskExecuteTimeMs":3002}
            Progress: {"0":"20"}
ReasonOfStateChanged:
        ErrorLogUrls:
            OtherMsg:
2 rows in set (0.01 sec)

ERROR:
No query specified

mysql> select count(*) from tbl_simple;
+----------+
| count(*) |
+----------+
|       10 |
+----------+
1 row in set (0.01 sec)
```
### StarRocks version (Required)
2.0.7

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #8534 

## Problem Summary(Required) ：

This fixes the data lost problem when there's empty kafka message.
The previous implement of `stream_load_pipe` determines the EOF by whether the data length = 0, which is incorrect when there's empty kafka message. As a result, the left message would be abandoned and the data would be lost.

### CODE REVIEW

File: be/src/exec/vectorized/json_scanner.cpp [hunk 1]
```diff
@@ -362,11 +362,13 @@ Status JsonReader::_read_and_parse_json() {
     std::unique_ptr<uint8_t[]> json_binary = nullptr;
     size_t length = 0;
     StreamPipeSequentialFile* stream_file = reinterpret_cast<StreamPipeSequentialFile*>(_file.get());
-    {
+
+    // read until a non-empty message is returned.
+    while (true) {
```
Comment (imay) [inline be/src/exec/vectorized/json_scanner.cpp:367]: do {
} while (length == 0)

**Review by imay — DISMISSED** [review]
LGTM

**Review by chaoyli — DISMISSED** [review]

**Comment by chaoyli** [comment]
run starrocks_be_unittest

**Review by imay — APPROVED** [review]
