### PR TITLE
[BugFix] Add retry for fe thrift rpc

### LINKED ISSUE #3077: The FE sometimes returns `java.net.SocketException: Broken pipe` when `show frontends;`
```
2022-01-25 16:23:46,142 WARN (starrocks-mysql-nio-pool-938|2617) [MasterOpExecutor.forward():152] Forward statement 17891501 to Master TNetworkAddress(hostname:172.26.194.119, port:9820) failed, e
rror type 0
org.apache.thrift.transport.TTransportException: java.net.SocketException: Broken pipe
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:159) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:73) ~[libthrift-0.13.0.jar:0.13.0]
        at org.apache.thrift.TServiceClient.sendBase(TServiceClient.java:62) ~[libthrift-0.13.0.jar:0.13.0]
        at com.starrocks.thrift.FrontendService$Client.send_forward(FrontendService.java:430) ~[starrocks-fe.jar:?]
        at com.starrocks.thrift.FrontendService$Client.forward(FrontendService.java:422) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.forward(MasterOpExecutor.java:149) [starrocks-fe.jar:?]
        at com.starrocks.qe.MasterOpExecutor.execute(MasterOpExecutor.java:76) [starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.forwardToMaster(StmtExecutor.java:553) [starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:317) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:268) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:415) [starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:651) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) [starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener$$Lambda$73/1018985975.run(Unknown Source) [starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_41]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_41]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_41]
Caused by: java.net.SocketException: Broken pipe
        at java.net.SocketOutputStream.socketWrite0(Native Method) ~[?:1.8.0_41]
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[?:1.8.0_41]
        at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[?:1.8.0_41]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_41]
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) ~[?:1.8.0_41]
        at org.apache.thrift.transport.TIOStreamTransport.flush(TIOStreamTransport.java:157) ~[libthrift-0.13.0.jar:0.13.0]
        ... 16 more
```
### Steps to reproduce the behavior (Required)
```
mysql> show frontends;
ERROR 1064 (HY000): java.net.SocketException: Broken pipe
```
### Expected behavior (Required)
return correct result.
### Real behavior (Required)
```
mysql> show frontends;
ERROR 1064 (HY000): java.net.SocketException: Broken pipe
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 2.1

### LINKED ISSUE #5655: Returned 'Socket is closed by peer'  when set fe config.
### Steps to reproduce the behavior (Required)
1. build a cluster with 3 fe (fe1, fe2, fe3).
2. connect to fe1 and execute the command;
```
admin set frontend config ("enable_decimal_v3" = "true");
```
3. restart fe2
4. execute the command again on fe1
```
admin set frontend config ("enable_decimal_v3" = "true");
```

### Expected behavior (Required)
set ok.
### Real behavior (Required)
=>{'status': False, 'msg': (1064, 'set config failed: set config for fe[xxx.xxx.xxx.202] failed: Socket is closed by peer.set config for fe[xxx.xxx.xxx.200] failed: Socket is closed by peer.')}
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5655
Fixes #3077

## Problem Summary(Required) ：

In some cases, such as fe restart, a broken conn will be returned from the connection pool, because there is no validation of the conn before being returned to user. We should reopen the conn and retry the rpc.
But for the timeout exception, it may be a network timeout or the target server may be running slow. We just reopen the conn in this case but do not retry.
Since we do not retry for the timeout exception, there is no need to distinguish between the types of statements that should be retried, so we discard the isQuery param from MasterOpExecutor.

### CODE REVIEW

**Comment by chaoyli** [comment]
Give the description about the bug and the solution in commit message.

File: fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java [hunk 1]
```diff
@@ -29,7 +29,7 @@ public void syncTable(ExternalOlapTable table) {
         authInfo.setPasswd(table.getSourceTablePassword());
         request.setAuth_info(authInfo);
         try {
-            TGetTableMetaResponse response = FrontendServiceProxy.call(addr, 10000,
+            TGetTableMetaResponse response = FrontendServiceProxy.call(addr, 10000, 3,
                     client -> client.getTableMeta(request));
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java:33]: 1. Give the description of the bug and the solution in the commit message.
2. Could the retry can solve the multi-followers' problem about the configuration?

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java:33]: 1. added.
2. yes, the reason of this bug #5655 is that frontendPool returned a broken conn.

Comment (chaoyli) [reply fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java:33]: Under what circumstance, will the broker connection be returned from the connection pool?
Could the broker connection keep-alive to avoid the broken connection?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 40 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/MasterImpl.java|0|6|00.00%|
|:large_blue_circle:|com/starrocks/rpc/FrontendServiceProxy.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|19|00.00%|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/external/starrocks/TableMetaSyncer.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|

File: fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/external/starrocks/TableMetaSyncer.java:33]: I will continue to look for this reason, and make another pr to fix the connection poll bug. But retry is a must when fe restarted or network problem occurred.

File: fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java [hunk 2]
```diff
@@ -142,32 +133,28 @@ private void forward() throws Exception {
...
+                        ctx.getStmtId(), thriftAddress, i, e.getType(), e);
+
+                // END_OF_FILE means server is stopped, only retry on this case
+                if (!isQuery && e.getType() != TTransportException.END_OF_FILE) {
+                    throw e;
+                } else {
+                    if (i == RETRY_TIMES - 1) {
+                        throw e;
+                    } else {
+                        Thread.sleep(10000);
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java:155]: Is this sleep time a bit long?

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 3]
```diff
@@ -6796,7 +6796,7 @@ public Future<TStatus> refreshOtherFesTable(TNetworkAddress thriftAddress, Strin
             request.setTable_name(tableName);
             request.setPartitions(partitions);
             try {
-                TRefreshTableResponse response = FrontendServiceProxy.call(thriftAddress, timeout,
+                TRefreshTableResponse response = FrontendServiceProxy.call(thriftAddress, timeout, 3,
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:6799]: I suggest using a constant integer instead of magic number 3, or even better, make it configurable.

**Review by padmejin — CHANGES_REQUESTED** [review]
I suggest using constant integer instead of magic number 3, or even better, make it configurable.

**Comment by gengjun-git** [comment]
do not merge

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 40 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/MasterImpl.java|0|6|00.00%|
|:large_blue_circle:|com/starrocks/rpc/FrontendServiceProxy.java|0|9|00.00%|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|19|00.00%|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/external/starrocks/TableMetaSyncer.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|0|1|00.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 0 / 18 (00.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/rpc/FrontendServiceProxy.java|0|11|00.00%|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/http/action/SystemAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|

File: fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java [hunk 4]
```diff
@@ -51,24 +49,22 @@ public class MasterOpExecutor {
...
         this.ctx = ctx;
         if (status.isNeedToWaitJournalSync()) {
             this.waitTimeoutMs = ctx.getSessionVariable().getQueryTimeoutS() * 1000;
         } else {
             this.waitTimeoutMs = 0;
         }
-        this.thriftTimeoutMs = ctx.getSessionVariable().getQueryTimeoutS() * 1000;
-        // if isQuery=false, we shouldn't retry twice when catch exception because of Idempotency
-        this.shouldNotRetry = !isQuery;
+        // set thriftTimeoutMs to 2 * query_timeout
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java:65]: The query timeout user may set very short or very long. Therefore, it is best to configure net timeout independently of query timeout and extract it separately. thrift timeout is recommended to be set to query timeout + net timeout.

File: fe/fe-core/src/main/java/com/starrocks/rpc/FrontendServiceProxy.java [hunk 5]
```diff
@@ -5,26 +5,39 @@
...
-            res = callable.invoke(client);
-            returnToPool = true;
+            T t = callable.invoke(client);
+            isConnValid = true;
+            return t;
+        } catch (TTransportException te) {
+            isConnValid = ClientPool.frontendPool.reopen(client);
+            // do not retry for timeout exception
+            if (!(te.getCause() instanceof SocketTimeoutException) && isConnValid) {
+                return callable.invoke(client);
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/rpc/FrontendServiceProxy.java:30]: I suggest you use a for-loop and a definite constant integer like RETRY_TIMES instead of obscurely setting one retry attempt.

File: fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java (hunk 4 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/qe/MasterOpExecutor.java]: done

File: fe/fe-core/src/main/java/com/starrocks/rpc/FrontendServiceProxy.java (hunk 5 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/rpc/FrontendServiceProxy.java]: done

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 6]
```diff
@@ -413,7 +413,7 @@ public class Config extends ConfigBase {
      * some hang up problems in java.net.SocketInputStream.socketRead0
      */
     @ConfField
-    public static int thrift_client_timeout_ms = 0;
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:416]: I  don't think changing a configuration name is appropriate. Perhaps someone has already used that configuration in a production environment. Better reserve the old one for compatibility.

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java (hunk 6 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: done

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Review by padmejin — DISMISSED** [review]

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 3 / 35 (08.57%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/master/MasterImpl.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/rpc/FrontendServiceProxy.java|0|14|00.00%|
|:large_blue_circle:|com/starrocks/qe/MasterOpExecutor.java|0|5|00.00%|
|:large_blue_circle:|com/starrocks/http/action/SystemAction.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/transaction/GlobalTransactionMgr.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/external/starrocks/TableMetaSyncer.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|1|00.00%|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|1|5|20.00%|
|:large_blue_circle:|com/starrocks/common/Config.java|2|2|100.00%|

**Review by Astralidea — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]

**Comment by jxzdoing** [comment]
may i ask which version fixed this bug？
