### PR TITLE
[Bugfix] "SHOW MATERIALIZED VIEW" should return a sql text like "CREATE MATERIALIZED VIEW xxx" for async materialized view

### LINKED ISSUE #9842: [sync materialized view]result error when show materialized view use where
<!-- (At least include the following, feel free to add if you have more content) -->

### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                    `k1` date,
                                    `k2` int,
                                    `k3` int
                                ) ENGINE=OLAP
                                DUPLICATE KEY(`k1`)
                                COMMENT "OLAP"
                                PARTITION BY RANGE (k1) (
                                START ("2020-10-01") END ("2022-03-04") EVERY (INTERVAL 15 day)
                                )
                                DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             PARTITION BY k1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC
                             AS SELECT k1, k2
                             FROM t1;
show materialized view where name = "mv1";
```

### Expected behavior (Required)
```
+-------+------+-----------------------+-------------------------------------------------------------------------------+------+
| id    | name | database_name         | text                                                                          | rows |
+-------+------+-----------------------+-------------------------------------------------------------------------------+------+
| 62700 | mv1  | default_cluster:yn_db | SELECT `yn_db`.`t1`.`k1` AS `k1`, `yn_db`.`t1`.`k2` AS `k2` FROM `yn_db`.`t1` | 0    |
+-------+------+-----------------------+-------------------------------------------------------------------------------+------+
1 row in set (0.00 sec)
```
### Real behavior (Required)
```
+-------+------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| id    | name | database_name | text                                                                                                                                                                                                                                                                                  | rows |
+-------+------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
| 78582 | mv1  | yn_db         | CREATE MATERIALIZED VIEW `mv1`
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`k1`)
DISTRIBUTED BY HASH(`k1`) BUCKETS 10
REFRESH ASYNC
PROPERTIES (
"replication_num" = "3",
"storage_medium" = "HDD"
)
AS SELECT `yn_db`.`t1`.`k1` AS `k1`, `yn_db`.`t1`.`k2` AS `k2` FROM `yn_db`.`t1`; | 0    |
+-------+------+---------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------+
1 row in set (0.04 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE e0e5c98 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by banmoy**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9842

## Problem Summary(Required) ：
  `SHOW MATERIALIZED VIEW` will return sql texts with different styles for  `REFRESH SYNC` and `REFRESH ASYNC` materialized views. And the style for the `ASYNC` materialized view should follow the original style of the `SYNC` mv, which is like  `CREATE MATERIALIZED VIEW xxx`.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 43 / 43 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 43 / 43 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -1814,6 +1814,70 @@ public void replayRecoverPartition(RecoverInfo info) {
         localMetastore.replayRecoverPartition(info);
     }
 
+    public static String getMaterializedViewDdtStmt(MaterializedView mv) {
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1817]: what Ddt mean ? do you mean getMaterializedViewDdlStmt?

Comment (banmoy) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1817]: typo, and should be `Ddl`

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 43 / 43 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 43 / 43 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|42|42|100.00%|[]|
|:large_blue_circle:|com/starrocks/qe/ShowExecutor.java|1|1|100.00%|[]|

**Review by Astralidea — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4
