### PR TITLE
[BugFix ] Fix bad variant access

### LINKED ISSUE #5976: 【window_funnel】be crash when sliding_window is boundary-value
### Steps to reproduce the behavior (Required)
1. 
```
CREATE TABLE `window_funnel_date` (
    `uid` int NOT NULL,
    `event_type` varchar(20) NOT NULL,
    `time` date NOT NULL)
DUPLICATE KEY(`uid`) DISTRIBUTED BY HASH(`uid`) buckets 4
PROPERTIES ("replication_num" = "1");
```
2. 
```
insert into window_funnel_date  values (1, "浏览", "2020-01-02"),
            (1, "点击", "2020-01-03"),
            (1, "下单", "2020-01-04"),
            (1, "支付", "2020-01-05"),
            (1, "浏览", "2020-01-06"),
            (2, "下单", "2020-01-07"),
            (2, "支付", "2020-01-08"),
            (3, "浏览", "2020-01-09"),
            (3, "点击", "2020-01-10"),
            (4, "浏览", "2020-01-11"),
            (4, "点击", "2020-01-12"),
            (5, "浏览", "2020-01-13"),
            (5, "点击", "2020-01-14"),
            (5, "下单", "2020-01-15"),
            (6, "浏览", "2020-01-25"),
            (6, "点击", "2020-01-26"),
            (6, "下单", "2020-01-27")
```
3. 
```
select window_funnel(9223372036854775807,time,0,[event_type="浏览", event_type="点击", event_type="下单", event_type="支付"]) from window_funnel_date;
```

### Expected behavior (Required)
Returns the data that meets the criteria### Real behavior (Required)
```ERROR 1064 (HY000): Backend not found. Check if any backend is down or not```

```
terminate called after throwing an instance of 'std::bad_variant_access'
  what():  std::get: wrong index for variant
*** Aborted at 1652260736 (unix time) try "date -d @1652260736" if you are using GNU date ***
PC: @     0x7f8201f30387 __GI_raise
*** SIGABRT (@0x3f700006958) received by PID 26968 (TID 0x7f81566ab700) from PID 26968; stack trace: ***
    @          0x3ee3d32 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f82029e5630 (unknown)
    @     0x7f8201f30387 __GI_raise
    @     0x7f8201f31a78 __GI_abort
    @          0x181474d _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold
    @          0x58a20c6 __cxxabiv1::__terminate()
    @          0x58a2131 std::terminate()
    @          0x58a2284 __cxa_throw
    @          0x156eec6 std::__throw_bad_variant_access()
    @          0x156eee3 std::__throw_bad_variant_access()
    @          0x1929fe4 starrocks::vectorized::FixedLengthColumnBase<>::append_datum()
    @          0x244be27 starrocks::vectorized::NullableColumn::append_datum()
    @          0x2438390 starrocks::vectorized::ArrayColumn::append_datum()
    @          0x2b33a31 starrocks::vectorized::WindowFunnelAggregateFunction<>::serialize_to_column()
    @          0x2a7e124 starrocks::vectorized::NullableAggregateFunctionBase<>::serialize_to_column()
    @          0x288c60d starrocks::Aggregator::convert_to_chunk_no_groupby()
    @          0x282f8a2 starrocks::pipeline::AggregateBlockingSourceOperator::pull_chunk()
    @          0x281f65a starrocks::pipeline::PipelineDriver::process()
    @          0x28159e8 starrocks::pipeline::GlobalDriverExecutor::_worker_thread()
    @          0x20bcb69 starrocks::ThreadPool::dispatch_thread()
    @          0x20b871a starrocks::Thread::supervise_thread()
    @     0x7f82029ddea5 start_thread
    @     0x7f8201ff88dd __clone
    @                0x0 (unknown)
```
### StarRocks version (Required)
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 9da8e3f |
+----------------------+
```

### PR DESCRIPTION
**Pull request by Pslydhh**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/5976, https://github.com/StarRocks/starrocks/issues/5956, https://github.com/StarRocks/starrocks/issues/5951, https://github.com/StarRocks/starrocks/issues/5935

## Problem Summary(Required) ：

We should use int64_t as array element for all timestampe(date/datetime ). Because date's type is int32_t, so we can't put  it in array, just transfer to int64_t.

### CODE REVIEW

**Review by stdpain — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

File: be/src/exec/vectorized/aggregator.cpp [hunk 1]
```diff
@@ -378,7 +378,7 @@ void Aggregator::compute_single_agg_state(size_t chunk_size) {
             _agg_functions[i]->update_batch_single_state(_agg_fn_ctxs[i], chunk_size, _agg_input_raw_columns[i].data(),
                                                          _single_agg_state + _agg_states_offsets[i]);
         } else {
-            DCHECK_EQ(_agg_intput_columns[i].size(), 1);
+            DCHECK_GE(_agg_intput_columns[i].size(), 1);
             _agg_functions[i]->merge_batch_single_state(_agg_fn_ctxs[i], chunk_size, _agg_intput_columns[i][0].get(),
```
Comment (chaoyli) [inline be/src/exec/vectorized/aggregator.cpp:382]: Please obey the rule of pull request and commit.
