### PR TITLE
[BugFix] Fix column not found after mv rewrite

### LINKED ISSUE #38844: Weird error when using mv rewrite SQL
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by ABingHuang**
Why I'm doing:
query failed after mv rewrite because that column is not found.

What I'm doing:
There are several reasons for this type bug.
1. IsNullPredicate can not be rewritten if mv has this predicate but query do not
2. aggregate has having predicates on grouping key. The keys are not mapped to base tables and not rewritten by query ec, so rewrite failed.
3. aggregate has having predicates on aggregations, The aggregations are not mapped to base tables and not rewritten by query ec, so rewrite failed.

Fix it by:
1. refactor get predicates logics to get only necessary predicates to avoid IsNullPredicate bug
2. mapping keys to based tables and rewrite them by query ec before writing
3. mapping aggregations to based tables and rewrite them by query ec before writing
4. add uts on some tpcds queries

Fixes #38844 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java [hunk 1]
```diff
@@ -217,6 +219,18 @@ protected OptExpression rewriteProjection(RewriteContext rewriteContext,
...
+                ScalarOperator swapped = columnRewriter.rewriteByQueryEc(mapped);
+                ScalarOperator rewritten = rewriteScalarOperator(swapped,
+                        queryExprToMvExprRewriter, rewriteContext.getOutputMapping(),
+                        originalColumnSet, aggregateFunctionRewriter);
+                if (rewritten == null) {
+                    logMVRewrite(mvRewriteContext, "mapping grouping key failed: {}", groupKey.toString());
+                    return null;
+                }
+                queryColumnRefToScalarMap.put(groupKey, rewritten);
+            }
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:233]: So having epxrs can use `group by` keys too?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java [hunk 2]
```diff
@@ -581,6 +583,76 @@ public static boolean isRedundantPredicate(ScalarOperator predicate) {
         return predicate.isPushdown() || predicate.isRedundant();
     }
 
+    public static Set<ScalarOperator> getPredicateForRewrite(OptExpression root) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:586]: This function only extracts predicates from join and scan node which scan node will exclude `IsNullPredicateOperator ` predicates if it's not null and its column ref is in the join's on predicates?

Am I right? may add more docs for this function?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java [hunk 3]
```diff
@@ -196,7 +196,7 @@ private PredicateSplit getQuerySplitPredicate(OptimizerContext optimizerContext,
             return null;
         }
         // only add valid predicates into query split predicate
-        Set<ScalarOperator> queryConjuncts = MvUtils.getAllValidPredicates(queryExpression);
+        Set<ScalarOperator> queryConjuncts = MvUtils.getPredicateForRewrite(queryExpression);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java:199]: Why not exclude original `isRedundantPredicate` predicates?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java [hunk 4]
```diff
@@ -217,6 +219,18 @@ protected OptExpression rewriteProjection(RewriteContext rewriteContext,
                 }
                 queryColumnRefToScalarMap.put(entry.getKey(), rewritten);
             }
+            for (ColumnRefOperator groupKey : queryAggregationOperator.getGroupingKeys()) {
+                ScalarOperator mapped = rewriteContext.getQueryColumnRefRewriter().rewrite(groupKey.clone());
+                ScalarOperator swapped = columnRewriter.rewriteByQueryEc(mapped);
+                ScalarOperator rewritten = rewriteScalarOperator(swapped,
```
Comment (satanson) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:225]: suggest to use Optional<T> to avoid NPE for rewriteScalarOperator

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:586]: yes. for inner join and semi join. I will add it.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java:199]: I filter it by isValidPredicate, already done

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/AggregatedMaterializedViewRewriter.java:225]: yes, good suggestion. But I want to do it in aother pr.

**Review by LiShuMing — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
