### PR TITLE
[BugFix] Backend not found

### LINKED ISSUE #16315: Backend not found
### Steps to reproduce the behavior (Required)
1. Deploy a StarRocks cluster with 6 backends;
2. Stop 5 out of 6 BE processes.
3.  echo "CREATE TABLE `t0` (
  `c0` int(11) NULL COMMENT ""
) DUPLICATE KEY(`c0`)
DISTRIBUTED BY HASH(`c0`) BUCKETS 1
PROPERTIES (
"replication_num" = "1"
);" > create.sql
4. mysqlslap --create=create.sql --concurrency=2 --iterations=10 --query="INSERT INTO t0 VALUES(1),(2),(3),(4)" --host=127.0.0.1 --port=xxx --create-schema=xxx --user=xx

### Expected behavior (Required)
insert success

### Real behavior (Required)
insert failed:
```
mysqlslap: Cannot run query INSERT INTO t0 VALUES(1),(2),(3),(4) ERROR : Backend not found. Check if any backend is down or not. backend: [172.26.92.205 alive: true inBlacklist: false] [172.26.92.205 alive: false inBlacklist: false] [172.26.92.205 alive: false inBlacklist: false] [172.26.92.205 alive: false inBlacklist: false] [172.26.92.205 alive: false inBlacklist: false] [172.26.92.205 alive: false inBlacklist: false]
```

### StarRocks version (Required)
 - dd33427

### PR DESCRIPTION
**Pull request by sduzh**
Fix #16315

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #16315 

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 9 / 17 (52.94%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SimpleScheduler.java|9|17|52.94%|[175, 178, 179, 180, 181, 182, 183, 184]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 24 / 24 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SimpleScheduler.java|24|24|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/qe/SimpleScheduler.java [hunk 1]
```diff
@@ -108,130 +108,61 @@ public static TNetworkAddress getHost(long backendId,
...
-                LOG.debug("candidatebackendId={}", candidatebackendId);
-                ComputeNode candidateBackend = computeNodes.get(candidatebackendId);
-                if (candidateBackend != null && candidateBackend.isAlive()
-                        && !blacklistBackends.containsKey(candidatebackendId)) {
-                    return candidateBackend;
-                }
-                candidateId = nextComputeNodeId.getAndIncrement() % computeNodeSize;
-            }
+        // slow path
+        List<T> aliveNodes = nodes.stream()
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/qe/SimpleScheduler.java:158]: This means every time we will scan all the backends, for the big cluster with 100+ BEs, this may slow the query/load plan. How about first get the nextId from the Atomic nextId to a local variable, and then check the BE status according the local nextId, is not alive, increment the local nextId, and at last add the delta to the Atomic nextId.

Comment (sduzh) [reply fe/fe-core/src/main/java/com/starrocks/qe/SimpleScheduler.java]: updated

**Review by gengjun-git — DISMISSED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SimpleScheduler.java|20|20|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
