### PR TITLE
[BugFix] Be crash when restore primary key table cause by col unique id (#23383)

### LINKED ISSUE #23383: [BugFix] Be crash when restore primary key table cause by col unique id
Problem:
For a primary key table, if the table's col unique id is not not consecutive, be will crash when restore this table cause by the difference between segment file and tablet schema.

Solution:
rebuild tablet schema when doing restore for primary key table

### PR DESCRIPTION
**Pull request by srlch**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #23383

## Problem Summary(Required):
Problem:
For a primary key table, if the table's col unique id is not not consecutive, be will crash when restore this table cause by the difference between segment file and tablet schema.

Solution:
reset tablet schema using schema in snapshot data

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/storage/tablet_manager.cpp [hunk 1]
```diff
@@ -1510,6 +1510,102 @@ Status TabletManager::create_tablet_from_meta_snapshot(DataDir* store, TTabletId
...
+        return Status::NotFound("tablet path not exists");
+    }
+
+    std::unique_lock l(_get_tablets_shard_lock(tablet_id));
+    RETURN_IF_ERROR(meta_store->write_batch(&wb));
+
+    if (!tablet->init().ok()) {
+        LOG(WARNING) << "Fail to init restored tablet " << tablet_id;
+        wb.Clear();
+        RETURN_IF_ERROR(TabletMetaManager::clear_del_vector(store, &wb, tablet_id));
```
Comment (trueeyu) [inline be/src/storage/tablet_manager.cpp:1595]: If clear_del_vector failed, will return error without clear other items such as rowset, delta_column_group ?

File: be/src/storage/tablet_manager.cpp [hunk 2]
```diff
@@ -1510,6 +1510,102 @@ Status TabletManager::create_tablet_from_meta_snapshot(DataDir* store, TTabletId
...
+        set1.insert(rowset_meta_pb.rowset_seg_id());
+    }
+    if (set1.size() != snapshot_meta->rowset_metas().size()) {
+        return Status::InternalError("has duplicate rowset id");
+    }
+    // Set of rowset id collected from tablet meta.
+    std::set<uint32_t> set2;
+    auto& v = snapshot_meta->tablet_meta().updates().versions(0).rowsets();
+    set2.insert(v.begin(), v.end());
+    if (!(set1 == set2)) {
```
Comment (trueeyu) [inline be/src/storage/tablet_manager.cpp:1547]: set1 != set2?

File: be/src/storage/tablet_manager.cpp [hunk 3]
```diff
@@ -1510,6 +1510,102 @@ Status TabletManager::create_tablet_from_meta_snapshot(DataDir* store, TTabletId
...
+    }
+    for (const auto& [segid, dcg] : snapshot_meta->delta_column_groups()) {
+        RETURN_IF_ERROR(TabletMetaManager::put_delta_column_group(store, &wb, tablet_id, segid, dcg));
+    }
+    RETURN_IF_ERROR(TabletMetaManager::put_tablet_meta(store, &wb, snapshot_meta->tablet_meta()));
+
+    auto tablet_meta = std::make_shared<TabletMeta>();
+    tablet_meta->init_from_pb(&snapshot_meta->tablet_meta());
+    if (tablet_meta->tablet_state() == TABLET_SHUTDOWN) {
+        LOG(INFO) << "Fail to load snapshot from " << schema_hash_path << ": tablet has been shutdown";
```
Comment (trueeyu) [inline be/src/storage/tablet_manager.cpp:1573]: LOG(WARN) or Log(INFO)

File: be/src/storage/tablet_manager.cpp [hunk 4]
```diff
@@ -1510,6 +1510,102 @@ Status TabletManager::create_tablet_from_meta_snapshot(DataDir* store, TTabletId
...
+        return Status::InternalError("Fail to create tablet");
+    }
+    // NOTE: do NOT touch snapshot_meta->tablet_meta since here, it has been modified by
+    // `Tablet::create_tablet_from_meta`.
+
+    if (!FileSystem::Default()->path_exists(tablet->schema_hash_path()).ok()) {
+        return Status::NotFound("tablet path not exists");
+    }
+
+    std::unique_lock l(_get_tablets_shard_lock(tablet_id));
```
Comment (trueeyu) [inline be/src/storage/tablet_manager.cpp:1589]: Will it lock for long time?

File: be/src/storage/tablet_manager.cpp [hunk 5]
```diff
@@ -1510,6 +1510,102 @@ Status TabletManager::create_tablet_from_meta_snapshot(DataDir* store, TTabletId
...
+        RETURN_IF_ERROR(TabletMetaManager::clear_del_vector(store, &wb, tablet_id));
+        RETURN_IF_ERROR(TabletMetaManager::clear_delta_column_group(store, &wb, tablet_id));
+        RETURN_IF_ERROR(TabletMetaManager::clear_rowset(store, &wb, tablet_id));
+        RETURN_IF_ERROR(TabletMetaManager::clear_log(store, &wb, tablet_id));
+        RETURN_IF_ERROR(TabletMetaManager::remove_tablet_meta(store, &wb, tablet_id, schema_hash));
+        auto st = meta_store->write_batch(&wb);
+        LOG_IF(WARNING, !st.ok()) << "Fail to clear meta store: " << st;
+        return Status::InternalError("tablet init failed");
+    }
+    auto st = _add_tablet_unlocked(tablet, true, true);
```
Comment (sevev) [inline be/src/storage/tablet_manager.cpp:1604]: Is it enough to hold the tablet_shard lock here?

**Review by trueeyu — APPROVED** [review]

**Review by sevev — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
