### PR TITLE
[BugFix] refresh finishChecker periodically to prevent table/partiton/index change

### LINKED ISSUE #14148: [Bug] Txns stuck in publish process when doing schemachange
### Steps to reproduce the behavior (Required)
* enable new publish
* insert into table continuously
* concurrent alter table continuously

### Expected behavior (Required)
All task normal

### Real behavior (Required)
some txn got stucked in publish process and cannot finish, so database cannot be dropped

### StarRocks version (Required)
main, 2.4, 2.5

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14148

## Problem Summary(Required) ：

When using new publish mechanism and a txn is in the publish process, a DDL/schemachange occurs and the txn related table/partition/index changed, the finishchecker should be refreshed, or tablets in deleted index may still be checked for publish success(which will never happen), and the checker will never succeed. 

This PR fixes this by adding a periodic refresh(recreate actually) for finishchecker, so txn can finish even when DDL/schemachange occurs.

This PR also optimizes some logging issue found when debugging this bug.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 14 / 24 (58.33%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|2|00.00%|[1026, 1027]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|0|2|00.00%|[749, 751]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|2|00.00%|[1512, 1513]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|6|10|60.00%|[938, 939, 940, 941]|
|:large_blue_circle:|com/starrocks/task/PublishVersionTask.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|2|2|100.00%|[]|

File: be/src/agent/publish_version.cpp [hunk 1]
```diff
@@ -27,6 +27,7 @@ struct TabletPublishVersionTask {
     int64_t partition_id{0};
     int64_t tablet_id{0};
     int64_t version{0};
+    int64_t current_version{0};
```
Comment (chaoyli) [inline be/src/agent/publish_version.cpp:30]: What the differenct between version and current_version?

File: fe/fe-core/src/main/java/com/starrocks/task/PublishVersionTask.java [hunk 2]
```diff
@@ -159,14 +159,22 @@ public void updateReplicaVersions(List<TTabletVersionPair> tabletVersions) {
             LOG.warn("db not found dbid={}", dbId);
             return;
         }
+        List<Long> droppedTablets = new ArrayList<>();
+        for (int i = 0; i < tabletVersions.size(); i++) {
+            if (replicas.get(i) == null) {
+                droppedTablets.add(tabletVersions.get(i).tablet_id);
+            }
+        }
+        if (!droppedTablets.isEmpty()) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/task/PublishVersionTask.java:168]: The WARNING log may misunderstand the user. I think the behavior is normal when some tables are dropped before publishing.

File: fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java [hunk 3]
```diff
@@ -901,18 +902,16 @@ public boolean allPublishTasksFinishedOrQuorumWaitTimeout(Set<Long> publishError
...
+            finishChecker = TransactionChecker.create(this, db);
+            checkerCreationTime = System.nanoTime();
         }
     }
 
     public boolean checkCanFinish() {
-        // this may happen if FE restarts
-        if (finishChecker == null) {
+        // finishChecker may be null if FE restarts
+        // finishChecker may require refresh if table/partition is dropped, or index is changed caused by Alter job
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java:913]: During the checker, if the table is dropping, what will happen?

Comment (decster) [reply fe/fe-core/src/main/java/com/starrocks/transaction/TransactionState.java:913]: this round of check will check all the tablets before dropping(and probably won't finish), and after next refresh, it will finish

File: fe/fe-core/src/main/java/com/starrocks/task/PublishVersionTask.java (hunk 2 above)
Comment (decster) [reply fe/fe-core/src/main/java/com/starrocks/task/PublishVersionTask.java:168]: changed

File: be/src/agent/publish_version.cpp (hunk 1 above)
Comment (decster) [reply be/src/agent/publish_version.cpp:30]: version is an input parameter(request publish version), it should not be reused as an output param(tablet's current version). In the original code, this introduced a bug that dropped tablets' current version will be wrongly assigned  to requested publish version.

Comment (decster) [reply be/src/agent/publish_version.cpp:30]: found that max_continuous_version is already for this purpose, but not used in earlier code, so fix it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 12 / 24 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/service/FrontendServiceImpl.java|0|2|00.00%|[1026, 1027]|
|:large_blue_circle:|com/starrocks/catalog/LocalTablet.java|0|2|00.00%|[749, 751]|
|:large_blue_circle:|com/starrocks/qe/StmtExecutor.java|0|2|00.00%|[1512, 1513]|
|:large_blue_circle:|com/starrocks/transaction/TransactionState.java|6|10|60.00%|[938, 939, 940, 941]|
|:large_blue_circle:|com/starrocks/task/PublishVersionTask.java|4|6|66.67%|[165, 169]|
|:large_blue_circle:|com/starrocks/transaction/PublishVersionDaemon.java|2|2|100.00%|[]|

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by decster** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
