### PR TITLE
[BugFix] Fix query queue allocation time and pending timeout

### LINKED ISSUE #65618: Incorrect expiredAllocatedTimeMs,violating the concurrency limit for resource groups
In QueryQueueManager::createSlot(), both expiredPendingTimeMs and expiredAllocatedTimeMs are incorrectly set to the same value using query_queue_pending_timeout_second: QueryQueueManager.java:153-156

This causes BaseSlotTracker::peakExpiredSlots() to incorrectly identify running queries as expired when they exceed the pending timeout (not the query execution timeout): BaseSlotTracker.java:293-303

The slotsOrderByExpiredTime TreeSet is sorted by expiredPendingTimeMs, but isAllocatedExpired() checks against expiredAllocatedTimeMs. Since both have the same value, allocated slots are prematurely considered expired. BaseSlotTracker.java:59-61

### Steps to reproduce the behavior (Required)
SET GLOBAL enable_query_queue_select = true;
SET GLOBAL enable_query_queue_load = true;
set global enable_query_queue_statistic=true;
SET GLOBAL query_queue_max_queued_queries = 30;

    Create a resource group with concurrency_limit = 1
    Enable query queue: SET GLOBAL enable_group_level_query_queue = true
    Set short pending timeout: SET GLOBAL query_queue_pending_timeout_second = 10
    Execute two concurrent queries (e.g., SELECT COUNT(*)) that each take ~40 seconds
    

### Expected behavior (Required)
the 2nd query will query timeout

### Real behavior (Required)
Observe that the 2nd query enter RUNNING state after 10 seconds, violating the concurrency limit

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
4.0

### PR DESCRIPTION
**Pull request by LiShuMing**
## What I'm doing:
- Clear listener after connect finished.
- Ensure expiredAllocatedTimeMs longer than expiredPendingTimeMs.

Fixes https://github.com/StarRocks/starrocks/issues/65618

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.1
  - [x] 4.0
  - [ ] 3.5
  - [ ] 3.4
  - [ ] 3.3

### CODE REVIEW

**Review by ZiheLiu — APPROVED** [review]

File: fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java [hunk 1]
```diff
@@ -96,6 +96,8 @@ public class QueryQueueManagerTest extends SchedulerTestBase {
 
     @BeforeAll
     public static void beforeClass() throws Exception {
+        Config.proc_profile_cpu_enable = false;
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java:99]: Global Config.proc_profile_* flags are modified in @BeforeAll without restoration, which can leak state into other tests running in the same JVM and cause unrelated test behavior changes.

```
private static boolean prevProcProfileCpuEnable;
private static boolean prevProcProfileMemEnable;

@BeforeAll
public static void beforeClass() throws Exception {
    prevProcProfileCpuEnable = Config.proc_profile_cpu_enable;
    prevProcProfileMemEnable = Config.proc_profile_mem_enable;

    Config.proc_profile_cpu_enable = false;
    Config.proc_profile_mem_enable = false;
    SchedulerTestBase.beforeClass();

    MetricRepo.init();
}

@AfterAll
public static void afterClass() {
    Config.proc_profile_cpu_enable = prevProcProfileCpuEnable;
    Config.proc_profile_mem_enable = prevProcProfileMemEnable;
}

```

Comment (LiShuMing) [reply fe/fe-core/src/test/java/com/starrocks/qe/scheduler/QueryQueueManagerTest.java:99]: This should not affect other tests. Since our UT sets `reuseForks` false.

PS: I found this test case cannot run in my IDEA because of aysnc-profiler, so add it this.

```
           <!-->set larger, eg, 3, to reduce the time or running FE unit tests<-->
                    <forkCount>${fe_ut_parallel}</forkCount>
                    <forkNode implementation="org.apache.maven.plugin.surefire.extensions.SurefireForkNodeFactory"/>
                    <!-->not reuse forked jvm, so that each unit test will run in separate jvm. to avoid singleton confict<-->
                    <reuseForks>false</reuseForks>
```

**Review by kangkaisen — APPROVED** [review]

**Comment by stdpain** [comment]
https://github.com/Mergifyio backport branch-3.5

**Comment by huailiu1122** [comment]
@Mergifyio backport branch-3.5

**Comment by huailiu1122** [comment]
https://github.com/Mergifyio backport branch-3.5
