### PR TITLE
[Enhancement] Make the be reboot time display more accurate

### LINKED ISSUE #7561: The `LastStartTime` of `BE` is not updated even though the cluster is updated.
### Steps to reproduce the behavior (Required)
update cluster.
### Expected behavior (Required)
`LastStartTime` updated.
### Real behavior (Required)
The `LastStartTime` of `BE` is not updated even though the cluster is updated.
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - 0eaab02

### PR DESCRIPTION
**Pull request by waittttting**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7561

## Problem Summary(Required) ：

The previous be's restart time is not accurate enough. 
Before that, whether fe updates the lastStartTime of be depends on the alive state of be recorded by fe itself.
When the alive state of be is false and the be heartbeat is received again, fe updates the lastStartTime of be. 
If fe dose not receive be's heartbeat 3 times, fe will set the alive stale of be to false. So if  be reboot quickly, the alive state of be will not be set to false, and the lastStartTime of will not be updated
This PR adds a field reboot time in be,  when be reports a heartbeat, reboot time will be sent to fe to determine if lastStartTime of be needs to be updated. 
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 11 / 14 (78.57%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|2|4|50.00%|[410, 411]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|5|6|83.33%|[89]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|4|4|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|4|4|100.00%|[]|

File: be/src/agent/heartbeat_server.cpp [hunk 1]
```diff
@@ -104,6 +106,10 @@ void HeartbeatServer::heartbeat(THeartbeatResult& heartbeat_result, const TMaste
 #endif
         heartbeat_result.backend_info.__set_version(get_short_version());
         heartbeat_result.backend_info.__set_num_hardware_cores(num_hardware_cores);
+        heartbeat_result.backend_info.__set_is_first_heartbeat(first_heartbeat);
```
Comment (imay) [inline be/src/agent/heartbeat_server.cpp:109]: What happens if fe change mater?

File: fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java [hunk 2]
```diff
@@ -397,13 +397,20 @@ public boolean handleHbResponse(BackendHbResponse hbResponse) {
...
                 LOG.info("{} is alive, last start time: {}", this.toString(), hbResponse.getHbTime());
                 this.isAlive.set(true);
             } else if (this.lastStartTime <= 0) {
                 this.lastStartTime = hbResponse.getHbTime();
             }
 
+            if (hbResponse.isSetFirstHeartbeat() && hbResponse.isFirstHeartbeat()) {
+                this.lastStartTime = hbResponse.getHbTime();
+                isChanged = true;
+            }
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java:412]: Could you add a more detailed description of the problem you are trying to resolve? It seems to me that if the leader of FE changes after a BE reboots, this `lastStartTime` will be inaccurate again.

File: be/src/agent/heartbeat_server.cpp (hunk 1 above)
Comment (waittttting) [reply be/src/agent/heartbeat_server.cpp:109]: isFirstHeartbeat is a property in be, fe change leader has no effect on this pr’s logic

File: fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java (hunk 2 above)
Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java:412]: isFirstHeartbeat is a property in be, fe change leader has no effect on this pr’s logic

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java:412]: Will the new leader go to line 410? If not, then the new leader won't get the accurate BE reboot time.

Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java:412]: done. PTAL

Comment (waittttting) [reply fe/fe-core/src/main/java/com/starrocks/system/ComputeNode.java:412]: use reboot time instead PTAL

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|0|4|00.00%|[402, 409, 410, 411]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|0|4|00.00%|[50, 79, 83, 84]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|4|00.00%|[293, 296, 297, 299]|

File: be/src/agent/heartbeat_server.cpp (hunk 1 above)
Comment (waittttting) [reply be/src/agent/heartbeat_server.cpp]: use reboot time to instead first_heartbeat

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|0|4|00.00%|[402, 409, 410, 411]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|0|4|00.00%|[50, 79, 83, 84]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|4|00.00%|[293, 296, 297, 299]|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by wangruin** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 0 / 12 (00.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|0|4|00.00%|[402, 409, 410, 411]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|0|4|00.00%|[50, 79, 83, 84]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|0|4|00.00%|[293, 296, 297, 299]|

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_fe_unittest

**Comment by waittttting** [comment]
run starrocks_be_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 12 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|1|4|25.00%|[402, 410, 411]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|2|4|50.00%|[83, 84]|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|3|4|75.00%|[297]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|3|4|75.00%|[297]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|4|4|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Review by padmejin — DISMISSED** [review]

**Review by gengjun-git — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by waittttting** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 11 / 12 (91.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/system/HeartbeatMgr.java|3|4|75.00%|[297]|
|:large_blue_circle:|com/starrocks/system/ComputeNode.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/system/BackendHbResponse.java|4|4|100.00%|[]|

**Comment by waittttting** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
