### PR TITLE
[Enhancement]enable fe to list all file in hdfs recursively

### LINKED ISSUE #10238: [Enhancement]When hive table has sub directories, query result returns less rows than real data
### Steps to reproduce the behavior (Required)
1. CREATE table in hive
```
hive> CREATE EXTERNAL TABLE student(
>   name STRING);
OK
Time taken: 0.547 seconds
```
2. CREATE subdirectories in hdfs
```
hive> dfs -ls /user/hive/warehouse/old_test.db/test/yymmdd=1;
Found 1 items
-rw-r--r--   1 qiuzhuodong supergroup          2 2022-08-20 09:44 /user/hive/warehouse/old_test.db/test/yymmdd=1/000000_0
hive> dfs -mkdir /user/hive/warehouse/old_test.db/test/yymmdd=1/1;
hive> dfs -mkdir /user/hive/warehouse/old_test.db/test/yymmdd=1/2;
```
3. CP data file to subdirectories
```
hive> dfs -ls /user/hive/warehouse/old_test.db/test/yymmdd=1/;
Found 3 items
-rw-r--r--   1 qiuzhuodong supergroup          2 2022-08-20 09:44 /user/hive/warehouse/old_test.db/test/yymmdd=1/000000_0
drwxr-xr-x   - qiuzhuodong supergroup          0 2022-08-20 09:46 /user/hive/warehouse/old_test.db/test/yymmdd=1/1
drwxr-xr-x   - qiuzhuodong supergroup          0 2022-08-20 09:46 /user/hive/warehouse/old_test.db/test/yymmdd=1/2
hive> dfs -cp /user/hive/warehouse/old_test.db/test/yymmdd=1/000000_0 /user/hive/warehouse/old_test.db/test/yymmdd=1/1/;
hive> dfs -cp /user/hive/warehouse/old_test.db/test/yymmdd=1/000000_0 /user/hive/warehouse/old_test.db/test/yymmdd=1/2;
```

### Expected behavior (Required)
Return corret rows of result
```
mysql> select * from test;
+------+--------+
| id   | yymmdd |
+------+--------+
|    1 | 1      |
|    1 | 1      |
|    1 | 1      |
+------+--------+
3 rows in set (0.02 sec)
```

### Real behavior (Required)
Return rows of directories at depth of 1, return 1 here
```
mysql> select * from test;
+------+--------+
| id   | yymmdd |
+------+--------+
|    1 | 1      |
+------+--------+
1 rows in set (0.01 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by adzfolc**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10238

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function
If user set `recursive_dir_search_enabled = true` in fe.conf, fe will scan hdfs files recursively; otherwise fe won't change old scan policy.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java [hunk 1]
```diff
@@ -682,7 +682,8 @@ public List<HdfsFileDesc> getHdfsFileDescs(String dirPath, boolean isSplittable,
         // block locations of the files in the given path in one operation.
         // The performance is better than getting status and block location one by one.
         try {
-            RemoteIterator<LocatedFileStatus> blockIterator = fileSystem.listLocatedStatus(new Path(uri.getPath()));
+            // files in hdfs may have multiple directories, so we need to list all files in hdfs recursively here
+            RemoteIterator<LocatedFileStatus> blockIterator = fileSystem.listFiles(new Path(uri.getPath()), true);
```
Comment (DorianZheng) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:686]: this is not a bug, it's a enhancement. this should be configurable.

**Comment by adzfolc** [comment]
Reminder:need to backport to branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 4 / 8 (50.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|1|4|25.00%|[1101, 1105, 1106]|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|3|4|75.00%|[680]|

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java (hunk 1 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java]: > this is not a bug, it's a enhancement. this should be configurable.

After consideration,it's more appropriate to put the para into `fe.conf`.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|3|4|75.00%|[679]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/common/Config.java [hunk 2]
```diff
@@ -1698,4 +1698,7 @@ public class Config extends ConfigBase {
 
     @ConfField(mutable = true)
     public static boolean enable_new_publish_mechanism = false;
+
+    @ConfField(mutable = true)
+    public static boolean recursive_dir_search_enabled = true;
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/common/Config.java:1703]: default value is false

Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/common/Config.java]: > default value is false

changed

**Comment by wangruin** [comment]
run starrocks_clang-tidy

**Comment by adzfolc** [comment]
run starrocks_fe_unittest

**Comment by adzfolc** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|3|4|75.00%|[681]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java [hunk 3]
```diff
@@ -673,7 +673,13 @@ public List<HdfsFileDesc> getHdfsFileDescs(String dirPath, boolean isSplittable,
...
+            // files in hdfs may have multiple directories, so we need to list all files in hdfs recursively here
+            RemoteIterator<LocatedFileStatus> blockIterator = null;
+            if (!Config.recursive_dir_search_enabled) {
+                blockIterator = fileSystem.listLocatedStatus(new Path(uri.getPath()));
+            } else {
+                blockIterator = fileSystem.listFiles(new Path(uri.getPath()), true);
+            }
             while (blockIterator.hasNext()) {
                 LocatedFileStatus locatedFileStatus = blockIterator.next();
                 if (!isValidDataFile(locatedFileStatus)) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:685]: isValidDataFile() will skip the dir, you could check it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|5|7|71.43%|[681, 688]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java (hunk 3 above)
Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:685]: > isValidDataFile() will skip the dir, you could check it.

After check, now hdfs directory will be scanned recursively by call getHdfsFileDescs.

File: fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java [hunk 4]
```diff
@@ -673,11 +673,19 @@ public List<HdfsFileDesc> getHdfsFileDescs(String dirPath, boolean isSplittable,
...
                     continue;
+                } else if (locatedFileStatus.isDirectory() && Config.recursive_dir_search_enabled) {
```
Comment (stephen-shelby) [inline fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:687]: I have checked the listFiles(true)'s behavior. It will return the files and the subDir's files. So I think there is no need to check the isDir?

Comment (adzfolc) [reply fe/fe-core/src/main/java/com/starrocks/external/hive/HiveMetaClient.java:687]: > I have checked the listFiles(true)'s behavior. It will return the files and the subDir's files. So I think there is no need to check the isDir?

As this pr's target, fe should scan hdfs files recursively only when config set `recursive_dir_search_enabled` to true.So,if locatedFileStatus is a dir, and fe enable `recursive_dir_search_enabled`, we check dir here. If recursive_dir_search_enabled is false, fe shouldn't scan sub dir of hdfs.

**Review by stephen-shelby — APPROVED** [review]

**Comment by adzfolc** [comment]
@DorianZheng @caneGuy PTAL

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by dirtysalt — APPROVED** [review]

**Comment by adzfolc** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 6 / 8 (75.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/external/hive/HiveMetaClient.java|5|7|71.43%|[681, 688]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|

**Comment by Smith-Cruise** [comment]
@Mergifyio backport branch-2.4
