### PR TITLE
[BugFix] mysql client automatically reconnect bug

### LINKED ISSUE #11667: mysql client automatically reconnect bug
If we execute a long query, and kill it in the middle process, mysql will automantically start a new session and rerun the query (this bug only trigger will starrocks and mysql client is not in the same LAN, and we add a ssh tunnel to make the mysql client connects to the starrocks)

### PR DESCRIPTION
**Pull request by xiaoyong-z**
If we execute a long query and kill it in the middle process,
MySQL will automatically start a new session and rerun the query
(this bug only triggers will StarRocks and MySQL client is not in the same LAN,
and we add an ssh tunnel to make the MySQL client connects to the StarRocks)

To fix this bug, we need to make sure the cancel operation happens before we
close the session; also, we need to wait for some time until the cancel state is
sent back to the MySQL client.

Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11667

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 4 / 5 (80.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlChannel.java|1|2|50.00%|[98]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|3|3|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 1]
```diff
@@ -520,14 +520,14 @@ public void kill(boolean killConnection) {
 
         if (killConnection) {
             isKilled = true;
+            // Now, cancel running process.
+            StmtExecutor executorRef = executor;
+            if (executorRef != null) {
+                executorRef.cancel();
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:526]: Why not guarantee the cancel() finished before close()?
Wait in the close() sounds not a good idea.

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 2]
```diff
@@ -517,17 +524,27 @@ public void setCurrentCatalog(String currentCatalog) {
...
+        // Now, cancel running process.
+        StmtExecutor executorRef = executor;
+        if (executorRef != null) {
+            executorRef.cancel();
+        }
+        while (closed == false) {
+            // if we don't wait for some time here, mysql client will reconnect
+            // previous session and rerun previous command automatically
+            try {
+                Thread.sleep(10);
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:536]: why slepp so long time?

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 3]
```diff
@@ -517,17 +524,27 @@ public void setCurrentCatalog(String currentCatalog) {
...
+            } catch (InterruptedException e) {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:537]: I suggest you quit the loop when a InterruptedException is caught. This exception is meant to interrupt the process.

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 4]
```diff
@@ -517,17 +524,27 @@ public void setCurrentCatalog(String currentCatalog) {
     public void kill(boolean killConnection) {
         LOG.warn("kill timeout query, {}, kill connection: {}",
                 getMysqlChannel().getRemoteHostPortString(), killConnection);
+        // Now, cancel running process.
+        StmtExecutor executorRef = executor;
+        if (executorRef != null) {
+            executorRef.cancel();
+        }
+        while (closed == false) {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:532]:
```suggestion
        while (!closed) {
```

Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:532]: why check the closed state?

Comment (xiaoyong-z) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java]: to make sure the cancel state is return to the mysql client first

Comment (xiaoyong-z) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java]: Mysql will disable auto reconnect if it receives a cancel message. 
Closed will wait until ReadListener's handleEvent function return from processOnce() and call cleanup, in cleanup function, it will set close to be true.
At the end of processOnce() function, in finalizeCommand(), it will return the cancelled state to mysql.

**Comment by xiaoyong-z** [comment]
@mergify rebase

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 21 / 29 (72.41%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/mysql/nio/NConnectContext.java|2|3|66.67%|[44]|
|:large_blue_circle:|com/starrocks/mysql/nio/NMysqlChannel.java|2|3|66.67%|[94]|
|:large_blue_circle:|com/starrocks/qe/ConnectContext.java|14|19|73.68%|[422, 545, 546, 547, 548]|
|:large_blue_circle:|com/starrocks/mysql/MysqlChannel.java|3|4|75.00%|[122]|

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 5]
```diff
@@ -517,17 +524,33 @@ public void setCurrentCatalog(String currentCatalog) {
...
+                        break;
+                    }
+                } catch (InterruptedException e) {
+                    e.printStackTrace();
+                    LOG.warn("sleep exception, ignore.");
+                    break;
+                }
+            }
+            // Close channel to break connection with client
+            getMysqlChannel().close();
```
Comment (trueeyu) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:552]: If not receive the cleanup from client for 1s, force close the mysql channel?

**Comment by xiaoyong-z** [comment]
procedure: 
1. session A is executing insert into, it will be stuck in coord.join()
2. session B executes kill, it will first cancel out the plan executing insert into, let coordinate.join() exit, after that session B wait for session A to set closed
3. session A, after exiting from coord.join() and finding that it is cancel, will send this message to mysql client (since it is sendAndFlush, I guess it is to ensure that mysql can receive it), then it will enter clien up and set the closed state, in fact, after setting the closed state it will also close the session to close
4. session B is confirming the close, try to close the session, found that the session has been closed, directly exit.
5. If session B tries for 1s and does not find that close is set to true, it will close the session by itself.

**Review by chaoyli — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
run starrocks_admit_test

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.3

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.2
