### PR TITLE
[Enhancement] `files()` `csv.trim_space` error report

### LINKED ISSUE #42800: [table function format:csv] when csv.trim_space=a, query files table function successfully
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
image

### Expected behavior (Required)
report error
### Real behavior (Required)
execute successfully
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

+-------------------+
| current_version() |
+-------------------+
| main-a0223f6      |
+-------------------+
1 row in set (0.00 sec)

### PR DESCRIPTION
**Pull request by rickif**
## Why I'm doing:
The `csv.trim_space` property of `files()` should be in bool type.
Now, the `files()` will not report any error even if we set `csv.trim_space` as any illegal string `a`.
## What I'm doing:
This PR fixes this issue. When an illegal values is set, `Access storage error. Error message: illegal value of csv.trim_space: a, only true/false allowed` will be reported.
Fixes https://github.com/StarRocks/starrocks/issues/42800

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java [hunk 1]
```diff
@@ -294,7 +294,14 @@ private void parseProperties() throws DdlException {
...
 
         if (properties.containsKey(PROPERTY_CSV_TRIM_SPACE)) {
-            csvTrimSpace = Boolean.parseBoolean(properties.get(PROPERTY_CSV_TRIM_SPACE));
+            String property = properties.get(PROPERTY_CSV_TRIM_SPACE);
+            if (property.equalsIgnoreCase("true")) {
+                csvTrimSpace = true;
+            } else if (property.equalsIgnoreCase("false")) {
+                csvTrimSpace = false;
+            } else {
+                throw new DdlException("illegal value of csv.skip_header: " + property + ", only true/false allowed");
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java:303]:
```suggestion
                throw new DdlException("illegal value of csv.trim_space: " + property + ", only true/false allowed");
```

File: fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java [hunk 2]
```diff
@@ -183,4 +183,24 @@ public void parseFile(String path, BrokerDesc brokerDesc, List<TBrokerFileStatus
...
+
+        Map<String, String> properties = newProperties();
+        properties.put("csv.trim_space", "FALSE");
+
+        ExceptionChecker.expectThrowsNoException(() -> new TableFunctionTable(properties));
+
+        properties.put("csv.trim_space", "FALS");
+
+        ExceptionChecker.expectThrowsWithMsg(DdlException.class,
+                "illegal value of csv.skip_header: FALS, only true/false allowed",
```
Comment (wyb) [inline fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java:203]:
```suggestion
                "illegal value of csv.trim_space: FALS, only true/false allowed",
```

**Review by wyb — DISMISSED** [review]

**Review by meegoo — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java [hunk 3]
```diff
@@ -306,7 +306,14 @@ private void parseProperties() throws DdlException {
...
```
Comment (rickif) [inline fe/fe-core/src/main/java/com/starrocks/catalog/TableFunctionTable.java:315]:
```suggestion
                throw new DdlException("illegal value of csv.trim_space: " + property + ", only true/false allowed");
```

**Review by wyb — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
