### PR TITLE
[BugFix] Repair GC logic for shared-data persistent index while multi-disk is used for storage

### LINKED ISSUE #53471: Local persistent index failed to remove old dir while new disk added
### Steps to reproduce the behavior (Required)

1. create PK table with Local persistent index enabled, then continues ingest data to the table.
2. add one or more disks to the CN node

### Expected behavior (Required)

some of the tablets' persistent index dir should shifted to the newly added disk. AND the old persistent index dir should be GC'ed.

### Real behavior (Required)

1. some of the tablets' persistent index dir should shifted to the newly added disk
2. The old tablet persistent index dir will trigger GC but NEVER be removed
3. some odd errors threw while continues ingesting

```sh
W20241126 17:16:36.130760 139819525076736 lake_service.cpp:228] Fail to publish version: Not found: NotFound: 
be/src/storage/tablet_meta_manager.cpp:342 store->get_meta()->get(META_COLUMN_FAMILY_INDEX, key, &value)
be/src/storage/lake/lake_primary_index.cpp:215 TabletMetaManager::get_persistent_index_meta(data_dir, _tablet_id, &index_meta)
be/src/storage/lake/txn_log_applier.cpp:153 _index_entry->value().commit(_metadata, &_builder)
be/src/storage/lake/transactions.cpp:346 log_applier->finish(). tablet_id=92081 txn_ids=txn_id: 13900213
commit_time: 1732612596
combined_txn_log: false
txn_type: TXN_NORMAL
force_publish: false
 version=329556
```

```sh
W20241201 04:02:48.779515 139772657714944 persistent_index.cpp:3347] build persistent index failed because commit failed: Not found: /opt/starrocks/be/storage/disk2/persistent/35505//index.l1.6440.0.tmp: No such file or directory
be/src/storage/persistent_index.cpp:793 FileSystem::Default()->rename_file(_idx_file_path_tmp, _idx_file_path)
be/src/storage/persistent_index.cpp:3531 _merge_compaction()
log_function:persistent_index.cpp:3347]
```

```
Fail to apply staros://35505/log/0000000000008AB1_0000000001493D0A.log: Internal error: prepare_primary_index: load primary index failed: Not found: /opt/starrocks/be/storage/disk2/persistent/35505//index.l1.6440.0.tmp: No such file or directory
be/src/storage/persistent_index.cpp:793 FileSystem::Default()->rename_file(_idx_file_path_tmp, _idx_file_path)
be/src/storage/persistent_index.cpp:3531 _merge_compaction()
be/src/storage/persistent_index.cpp:5274 _build_commit(loader, index_meta)
be/src/storage/lake/txn_log_applier.cpp:203 value_or_err_L203
be/src/storage/lake/txn_log_applier.cpp:214 prepare_primary_index()
be/src/storage/lake/txn_log_applier.cpp:119 check_and_recover([&]() { return apply_write_log(log.op_write(), log.txn_id()); })
```

### StarRocks version (Required)
 - 3.3.x

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

Fixes #53471

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0

### CODE REVIEW

**Comment by sevev** [comment]
Can you describe the specific bug and explain the cause of it?

**Comment by wxl24life** [comment]
> Can you describe the specific bug and explain the cause of it?

done

File: be/src/storage/lake/local_pk_index_manager.cpp [hunk 1]
```diff
@@ -86,10 +90,10 @@ void LocalPkIndexManager::gc(UpdateManager* update_manager, DataDir* data_dir, s
         }
         // judge whether tablet should be in the data_dir or not,
         // for data_dir may change if config:storage_path changed.
-        // just remove if not.
+        // just remove dir if not.
         if (StorageEngine::instance()->get_persistent_index_store(id) != data_dir) {
             dir_changed_tablet_ids.push_back(id);
-            if (clear_persistent_index(id).ok()) {
+            if (remove_local_persistent_index_dir(id, data_dir).ok()) {
```
Comment (kevincai) [inline be/src/storage/lake/local_pk_index_manager.cpp:96]: please try to add UT to cover the scenario.

Comment (wxl24life) [reply be/src/storage/lake/local_pk_index_manager.cpp:96]: there is a trick here, i'm working around with it

**Comment by sevev** [comment]
Maybe it might be better to add a specified `data_dir` in `LakePrimaryIndex`. This is because the result obtained from `get_persistent_index_store` may be inconsistent at different stages, which could lead to an error where the metadata cannot be found during the publish process.

File: be/src/storage/lake/local_pk_index_manager.cpp [hunk 2]
```diff
@@ -86,14 +97,28 @@ void LocalPkIndexManager::gc(UpdateManager* update_manager, DataDir* data_dir, s
...
+                LOG(WARNING) << "Fail to lock pk index, tablet id: " << id;
+                gc_fail_because_lock_fail++;
+                continue;
             }
+            // double check in the lock
+            dir_changed = StorageEngine::instance()->get_persistent_index_store(id) != data_dir;
+            TEST_SYNC_POINT_CALLBACK("LocalPkIndexManager:index_dir_changed:2", &dir_changed);
+            if (dir_changed) {
+                dir_changed_tablet_ids.push_back(id);
+                if (clear_persistent_index_if_dir_changed(id, data_dir).ok()) {
```
Comment (smartlxh) [inline be/src/storage/lake/local_pk_index_manager.cpp:115]: here should call `try_remove_primary_index_cache` to remove index cache first to avoid consistency issues

Comment (wxl24life) [reply be/src/storage/lake/local_pk_index_manager.cpp]: done

File: be/src/storage/lake/local_pk_index_manager.cpp [hunk 3]
```diff
@@ -86,14 +88,36 @@ void LocalPkIndexManager::gc(UpdateManager* update_manager, DataDir* data_dir, s
...
             }
+            // double check in the lock
+            dir_changed = StorageEngine::instance()->get_persistent_index_store(id) != data_dir;
+            TEST_SYNC_POINT_CALLBACK("LocalPkIndexManager:index_dir_changed:2", &dir_changed);
+            if (dir_changed) {
+                dir_changed_tablet_ids.push_back(id);
+                // try to remove pk index cache to avoid continuing to use the index in the cache after deletion.
+                if (update_manager->try_remove_primary_index_cache(id)) {
+                    // clear index from old dir
+                    if (clear_persistent_index(id, data_dir).ok()) {
```
Comment (kevincai) [inline be/src/storage/lake/local_pk_index_manager.cpp:111]: this cleanup may take long time, is it possible to be performed outside the tablet index lock?

File: be/test/storage/lake/local_pk_index_manager_test.cpp [hunk 4]
```diff
@@ -173,6 +173,110 @@ TEST_F(LocalPkIndexManagerTest, test_gc) {
...
+        op_write->mutable_rowset()->add_segments(std::move(f.path));
+    }
+    op_write->mutable_rowset()->set_num_rows(writer->num_rows());
+    op_write->mutable_rowset()->set_data_size(writer->data_size());
+    ASSERT_OK(_tablet_mgr->put_txn_log(txn_log));
+
+    writer->close();
+    // publish again should be successful, persistent index will be reloaded.
+    ASSERT_OK(publish_single_version(_tablet_metadata->id(), 2, txn_id).status());
+}
```
Comment (kevincai) [inline be/test/storage/lake/local_pk_index_manager_test.cpp:278]: looks like the ut doesn't cover the case that multiple data_dirs exists for the same index which is one of the scenario this PR is trying to fix. right?

File: be/src/storage/lake/local_pk_index_manager.cpp (hunk 3 above)
Comment (wxl24life) [reply be/src/storage/lake/local_pk_index_manager.cpp:111]: The lock here is needed for concurrency safety reasons. This logic is same as the following `tablet not on worker` case, both need lock while cleaning index dir.

File: be/test/storage/lake/local_pk_index_manager_test.cpp (hunk 4 above)
Comment (wxl24life) [reply be/test/storage/lake/local_pk_index_manager_test.cpp:278]: used `LocalPkIndexManager:index_dir_changed:2` to mock this case, maybe it can cover partly..

**Review by sevev — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
