### PR TITLE
[BugFix] Fix erase _compaction_candidates bug

### LINKED ISSUE #10237: infinite loop in CompactionManager::pick_candidate
### Real behavior (Required)
The compaction is blocked and not executed any more.
```
W0820 09:46:47.247982 37953 compaction_manager.cpp:71] update candidate failed. status:Service unavailable: Thread pool is at capacity (5/5 tasks running, 100000/100000 tasks queued)
```
Acordding to the error message in be.WARNING, the thread pool of CompactionManager is busy.
 
```
Thread 518 (Thread 0x7ff1531fa700 (LWP 37990)):
#0  0x0000000006008aa7 in std::_Rb_tree_rebalance_for_erase (__z=0x9641530, __header=...) at ../../../.././libstdc++-v3/src/c++98/tree.cc:305
#1  0x0000000001ec1a32 in std::_Rb_tree<starrocks::CompactionCandidate, starrocks::CompactionCandidate, std::_Identity<starrocks::CompactionCandidate>, starrocks::CompactionCandidateComparator, std::allocator<starrocks::CompactionCandidate> >::_M_erase_aux (__position=..., this=0x9641528) at /root/starrocks/be/src/storage/compaction_manager.cpp:62
#2  std::_Rb_tree<starrocks::CompactionCandidate, starrocks::CompactionCandidate, std::_Identity<starrocks::CompactionCandidate>, starrocks::CompactionCandidateComparator, std::allocator<starrocks::CompactionCandidate> >::erase[abi:cxx11](std::_Rb_tree_const_iterator<starrocks::CompactionCandidate>) (__position=..., this=0x9641528) at /usr/include/c++/10.3.0/bits/stl_tree.h:1204
#3  std::set<starrocks::CompactionCandidate, starrocks::CompactionCandidateComparator, std::allocator<starrocks::CompactionCandidate> >::erase[abi:cxx11](std::_Rb_tree_const_iterator<starrocks::CompactionCandidate>) (__position=..., this=0x9641528) at /usr/include/c++/10.3.0/bits/stl_set.h:655
#4  starrocks::CompactionManager::pick_candidate (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#5  0x0000000001ec53b9 in starrocks::CompactionScheduler::_try_get_next_compaction_task (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#6  0x0000000001ec64a9 in starrocks::CompactionScheduler::schedule (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#7  0x0000000001eee97e in operator() (__closure=<optimized out>) at /root/starrocks/be/src/storage/olap_server.cpp:138
#8  std::__invoke_impl<void, starrocks::StorageEngine::start_bg_threads()::<lambda()> > (__f=...) at /usr/include/c++/10.3.0/bits/invoke.h:60
#9  std::__invoke<starrocks::StorageEngine::start_bg_threads()::<lambda()> > (__fn=...) at /usr/include/c++/10.3.0/bits/invoke.h:95
#10 std::thread::_Invoker<std::tuple<starrocks::StorageEngine::start_bg_threads()::<lambda()> > >::_M_invoke<0> (this=<optimized out>) at /usr/include/c++/10.3.0/thread:264
#11 std::thread::_Invoker<std::tuple<starrocks::StorageEngine::start_bg_threads()::<lambda()> > >::operator() (this=<optimized out>) at /usr/include/c++/10.3.0/thread:271
#12 std::thread::_State_impl<std::thread::_Invoker<std::tuple<starrocks::StorageEngine::start_bg_threads()::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /usr/include/c++/10.3.0/thread:215
#13 0x00000000060774e0 in std::execute_native_thread_routine (Python Exception <type 'exceptions.NameError'> Installation error: gdb._execute_unwinders function is missing:
#14 0x00007ff2579f6ea5 in start_thread () from /lib64/libpthread.so.0
#15 0x00007ff257011b0d in clone () from /lib64/libc.so.6
```
From the result of pstack, one of the thread is in infinite loop at https://github.com/StarRocks/starrocks/blob/5898190f00e83f0a22f8b1ffb88bc9996b5a863f/be/src/storage/compaction_manager.cpp#L62, which leads the other thread in the pool waiting for the lock release.

### StarRocks version (Required)
2.4.0-0819-5cd95e7

### PR DESCRIPTION
**Pull request by meegoo**
## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10237

## Problem Summary(Required) ：

1. Using tablet->compaction_score() in comparator is both wrong and inefficient since it can change when rbtree adjusts.
2. update_candidates() erase the old element with the new candidate, which compaction score has changed, it makes set erase an undefined result.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by rickif** [comment]
Does this also resolve https://github.com/StarRocks/starrocks/issues/10081 ?

File: be/src/storage/compaction_manager.cpp [hunk 1]
```diff
@@ -26,18 +26,32 @@ void CompactionManager::init_max_task_num(int32_t num) {
...
+            }
+            if (!has_erase) {
+                iter++;
+            }
+        }
         for (auto& candidate : candidates) {
-            size_t num = _compaction_candidates.erase(candidate);
-            should_notify |= num == 0;
+            candidate.score = candidate.tablet->compaction_score(candidate.type) * 100;
             _compaction_candidates.emplace(std::move(candidate));
```
Comment (rickif) [inline be/src/storage/compaction_manager.cpp:49]: Is it OK to emplace since the score of candidate may have changed ?

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by meegoo** [comment]
run starrocks_admit_test

**Review by chaoyli — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
