### PR TITLE
do not check memory limit when do apply.

### LINKED ISSUE #6596: clone failed: Fail to make snapshot: get_applied_rowsets failed, tablet updates is in error state
firstly, machine 191 memory limit exceed when _apply_compaction_commit，_set_error，then clone from 191, call Tablet::capture_consistent_rowsets -> TabletUpdates::get_applied_rowsets, return when check error state, clone failed
after error gone, did not clear the error state and message, so when check it again, misjudge the present situation.
```
W0514 05:03:34.862161 20746 delta_writer.cpp:87] Primary-key index exceeds the limit. tablet_id: 11363, consumption: 106958369812, limit: 96945436900. Memory stats of top five tablets: 11443(4079M)11379(4079M)11463(4079M)11515(4079M)11371(4079M)
...
W0514 14:54:21.251559 27698 engine_clone_task.cpp:278] Fail to make snapshot from 172.26.34.191: Internal error: get_applied_rowsets failed, tablet updates is in error state: tablet:11463 _apply_compaction_commit error: load primary index failed: Memory limit exceeded: Memory of process exceed limit. read and decompress page Used: 161665088320, Limit: 161575728168. Mem usage has exceed the limit of BE
../src/storage/rowset/page_io.cpp:118 CurrentThread::mem_tracker()->check_mem_limit("read and decompress page")
../src/storage/rowset/scalar_column_iterator.cpp:299 _reader->read_page(_opts, iter.page(), &handle, &page_body, &footer)
../src/storage/rowset/scalar_column_iterator.cpp:101 _read_data_page(_page_iter)
../src/storage/rowset/segment_iterator.cpp:104 iter->seek_to_ordinal(pos)
../src/storage/rowset/segment_iterator.cpp:610 _context->seek_columns(_cur_rowid)
../src/storage/rowset/segment_iterator.cpp:704 _read(chunk, rowid, std::max(chunk_capacity - chunk_start, chunk_capacity / 4)) tablet:11463 #version:17 [154 166@15 166.1] pending: rowsets:129
  16 [seg:1 row:1250690 del:4 bytes:41207634 compaction:-7652547]
  17 [seg:1 row:1249895 del:10 bytes:41180390 compaction:-7624313]
  18 [seg:1 row:1250108 del:9 bytes:41191497 compaction:-7635585]
  19 [seg:1 row:1249558 del:7 bytes:41168110 compaction:-7612528]
  ...
```

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6596

### CODE REVIEW

File: be/src/storage/tablet_updates.cpp [hunk 1]
```diff
@@ -1188,6 +1188,7 @@ Status TabletUpdates::_commit_compaction(std::unique_ptr<CompactionInfo>* pinfo,
 }
 
 void TabletUpdates::_apply_compaction_commit(const EditVersionInfo& version_info) {
+    SCOPED_THREAD_LOCAL_CHECK_MEM_LIMIT_SETTER(false);
```
Comment (trueeyu) [inline be/src/storage/tablet_updates.cpp:1191]: why not set in do_apply() ?

**Review by trueeyu — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by Linkerist** [comment]
@mergify backport branch-2.2
