### PR TITLE
[BugFix] expose the shadowed field in ScanOperator

### LINKED ISSUE #6188: be crash in ScanOperator when work_group turned on
### Steps to reproduce the behavior (Required)
1
`prepare data for tpch 100g`
2
```
select count(*) from (
select
  s_acctbal,
  s_name,
  n_name,
  p_partkey,
  p_mfgr,
  s_address,
  s_phone,
  s_comment
from
  part,
  supplier,
  partsupp,
  nation,
  region
where
  p_partkey = ps_partkey
  and s_suppkey = ps_suppkey
  and p_size = 15
  and p_type like '%BRASS'
  and s_nationkey = n_nationkey
  and n_regionkey = r_regionkey
  and r_name = 'EUROPE'
  and ps_supplycost = ( 
    select
      min(ps_supplycost)
    from
      partsupp,
      supplier,
      nation,
      region
    where
      p_partkey = ps_partkey
      and s_suppkey = ps_suppkey
      and s_nationkey = n_nationkey
      and n_regionkey = r_regionkey
      and r_name = 'EUROPE'
  )
order by
  s_acctbal desc,
  n_name,
  s_name,
  p_partkey
) as t1;
```

### Expected behavior (Required)
`query ok`
### Real behavior (Required)
```
*** Aborted at 1652774152 (unix time) try "date -d @1652774152" if you are using GNU date ***
PC: @          0x27f78ad starrocks::pipeline::ScanOperator::prepare()
*** SIGSEGV (@0x38) received by PID 561 (TID 0x7f85d4e58700) from PID 56; stack trace: ***
    @          0x3ee3d32 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f86aa920630 (unknown)
    @          0x27f78ad starrocks::pipeline::ScanOperator::prepare()
    @          0x2818f2a starrocks::pipeline::PipelineDriver::prepare()
    @          0x27d9c7a starrocks::pipeline::FragmentExecutor::execute()
    @          0x2009cd9 starrocks::PInternalServiceImpl<>::_exec_plan_fragment()
    @          0x200b1b3 starrocks::PInternalServiceImpl<>::exec_plan_fragment()
    @          0x4015a8e brpc::policy::ProcessRpcRequest()
    @          0x400c4f7 brpc::ProcessInputMessage()
    @          0x400d3a3 brpc::InputMessenger::OnNewMessages()
    @          0x40b406e brpc::Socket::ProcessEvent()
    @          0x3fc1fff bthread::TaskGroup::task_runner()
    @          0x414a7e1 bthread_make_fcontext
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 1039f18 |
+----------------------+
```

### LINKED ISSUE #6190: query error when resource_group turn on
### Steps to reproduce the behavior (Required)
```
set enable_pipeline_engine=true;
set enable_resource_group=true;
select current_version();
```

### Expected behavior (Required)
```
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 1039f18 |
+----------------------+
```
### Real behavior (Required)
`ERROR 1064 (HY000): Exceed concurrency limit: 10`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------+
| current_version()    |
+----------------------+
| MAIN-RELEASE 1039f18 |
+----------------------+
```

### PR DESCRIPTION
**Pull request by murphyatwork**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #6188
Fixes #6190

## Problem Summary(Required) ：

The `_workgroup` in `SourceOperator` is shadowed by `ScanOperator`.

### CODE REVIEW

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by silverbullet233 — APPROVED** [review]

File: be/src/exec/pipeline/source_operator.h [hunk 1]
```diff
@@ -79,8 +79,6 @@ class SourceOperator : public Operator {
 
     int64_t _last_scan_rows_num = 0;
     int64_t _last_scan_bytes = 0;
-
-    workgroup::WorkGroupPtr _workgroup = nullptr;
```
Comment (stdpain) [inline be/src/exec/pipeline/source_operator.h:83]: why not reserve _workgroup in Source Operator. it seems JDBC/ES Source Operator will use workgroup later.

Comment (mofeiatwork) [reply be/src/exec/pipeline/source_operator.h:83]: They should inherit the `ScanOperator`.

**Review by satanson — APPROVED** [review]
