### PR TITLE
[BugFix] Fix the error when getting the memory limit in cgroup v2

### LINKED ISSUE #13548: start_be fails when SRs is running in a non-k8s container environment
memory.limit_in_bytes exist on container that is deployed via k8s, but doesn't exist on container that deployed on a local host via docker compose.
It would be more resilient to check the existence of `/sys/fs/cgroup/memory/memory.limit_in_bytes` before `cat`ing it.

This bug is introduced by this  https://github.com/StarRocks/starrocks/pull/11717

```
[root@sr-node-p deploy]# ls /sys/fs/cgroup/memory/memory.limit_in_bytes
/sys/fs/cgroup/memory/memory.limit_in_bytes
[root@sr-node-p deploy]# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
```
### Steps to reproduce the behavior (Required)

```
# ./start_be.sh --daemon
cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory
can't get mem info from /sys/fs/cgroup/memory/memory.limit_in_bytes
There is not /sys/fs/cgroup/memory/memory.limit_in_bytes file for a centos-7 base docker container.
E.g, running this command in a centos-7 based docker container got this error.

# ls /sys/fs/cgroup/memory
```
```
ls: cannot access /sys/fs/cgroup/memory: No such file or directory
Here are all the memory released info I got from centos-7 container

ls  /sys/fs/cgroup/memory.*        
/sys/fs/cgroup/memory.current       /sys/fs/cgroup/memory.low        /sys/fs/cgroup/memory.oom.group     /sys/fs/cgroup/memory.swap.events
/sys/fs/cgroup/memory.events        /sys/fs/cgroup/memory.max        /sys/fs/cgroup/memory.pressure      /sys/fs/cgroup/memory.swap.high
/sys/fs/cgroup/memory.events.local  /sys/fs/cgroup/memory.min        /sys/fs/cgroup/memory.stat          /sys/fs/cgroup/memory.swap.max
/sys/fs/cgroup/memory.high          /sys/fs/cgroup/memory.numa_stat  /sys/fs/cgroup/memory.swap.current
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by chaoyli**
cgroup V1 in Centos7 store memory limit in `/sys/fs/cgroup/memory/memory.limit_in_bytes` cgroup V2 in Ubuntu 22 store memory limit in `/sys/fs/cgroup/memory.max`

StarRocks encounters error when running in docker installed Ubuntu 22.
```
cat: /sys/fs/cgroup/memory/memory.limit_in_bytes: No such file or directory
can't get mem info from /sys/fs/cgroup/memory/memory.limit_in_bytes
There is not /sys/fs/cgroup/memory/memory.limit_in_bytes file for a centos-7 base docker container.
E.g, running this command in a centos-7 based docker container got this error.
```

This pull request figure out a solution by check the version of cgroup. According to the cgroup version, the memory limit will been automatically parsed.

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #13548

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [x] 2.3
  - [x] 2.2

### CODE REVIEW

File: be/src/util/mem_info.cpp [hunk 1]
```diff
@@ -34,39 +34,70 @@
...
 #include "fs/fs_util.h"
 #include "gutil/strings/split.h"
+#include "util/errno.h"
 #include "util/pretty_printer.h"
 #include "util/string_parser.hpp"
 
 namespace starrocks {
 
+#ifndef CGROUP2_SUPER_MAGIC
+#define CGROUP2_SUPER_MAGIC 0x63677270
```
Comment (imay) [inline be/src/util/mem_info.cpp:53]: Should give some comments about this magic number.
And why not introduce this number by include some headers?

File: be/src/util/mem_info.cpp [hunk 2]
```diff
@@ -34,39 +34,70 @@
...
 bool MemInfo::_s_initialized = false;
 int64_t MemInfo::_s_physical_mem = -1;
 
 void MemInfo::init() {
     // check if application is in docker container or not via /.dockerenv file
-    if (fs::path_exist("/.dockerenv")) {
-        // Read from /sys/fs/cgroup/memory/memory.limit_in_bytes
-        std::ifstream memoryLimit("/sys/fs/cgroup/memory/memory.limit_in_bytes");
-        std::string line;
+    while (fs::path_exist("/.dockerenv")) {
```
Comment (imay) [inline be/src/util/mem_info.cpp:61]: Seems this will work even in bare metals. So if we can get memory information from it, we don't need to read `/proc/meminfo`.
And you can extract this into a function, then you don't need `while`

**Review by dengliu — COMMENTED** [review]
shall we update
 https://github.com/StarRocks/starrocks/blob/main/bin/common.sh#L68  ?
this fails the start of BE from a cgroupv2 hosted container.

File: be/src/util/mem_info.cpp (hunk 1 above)
Comment (chaoyli) [reply be/src/util/mem_info.cpp:53]: The lower Linux kernel does not define this magic number. So I copy it from a high Linux version in `linux/magic.h`

File: be/src/util/mem_info.cpp (hunk 2 above)
Comment (chaoyli) [reply be/src/util/mem_info.cpp]: in bare metals, the /sys/fs/cgroup/memory/memory.limit_in_bytes may be int64_t::max(). So still need to get /proc/meminfo.

File: be/src/util/mem_info.cpp [hunk 3]
```diff
@@ -117,4 +112,47 @@ std::string MemInfo::debug_string() {
...
+            // Read from /sys/fs/cgroup/memory/memory.max
+            memoryLimit.open("/sys/fs/cgroup/memory.max");
+            getline(memoryLimit, line);
+
+            if (line == "max") {
+                _s_physical_mem = std::numeric_limits<int64_t>::max();
+            } else {
+                _s_physical_mem = StringParser::string_to_int<int64_t>(line.data(), line.size(), &result);
+            }
+        }
```
Comment (choury) [inline be/src/util/mem_info.cpp:146]: May be add some as this?
```
else {
     result = StringParser::PARSE_FAILURE;
}
```

File: be/src/util/mem_info.cpp [hunk 4]
```diff
@@ -117,4 +112,47 @@ std::string MemInfo::debug_string() {
...
+            getline(memoryLimit, line);
+            _s_physical_mem = StringParser::string_to_int<int64_t>(line.data(), line.size(), &result);
+        } else if (fs.f_type == CGROUP2_SUPER_MAGIC) {
+            // cgroup v2
+            // Read from /sys/fs/cgroup/memory/memory.max
+            memoryLimit.open("/sys/fs/cgroup/memory.max");
+            getline(memoryLimit, line);
+
+            if (line == "max") {
+                _s_physical_mem = std::numeric_limits<int64_t>::max();
```
Comment (dengliu) [inline be/src/util/mem_info.cpp:142]: how will starrocks use `_s_physical_mem`?

I feel like you shall to use `memory.min` and `memory.low` which guarantee the minimal amount of memory that a BE pod can get instead of the maximum amount of memory that it can get.
K8S use `memory.min` and `memory.low` for memory resource request.
check it out here:
https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#how-pods-with-resource-limits-are-run

image

**Review by imay — APPROVED** [review]

**Review by choury — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by dengliu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.3

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.2

File: bin/common.sh [hunk 5]
```diff
@@ -73,6 +74,17 @@ export_mem_limit_from_conf() {
         mem_limit=`expr $mem_limit / 1024`
     fi
 
+    if [ -f /.dockerenv ] && [ "$cgroup_version" == "cgroup2fs" ]; then
+        mem_limit=$(cat /sys/fs/cgroup/memory/memory.max | awk '{printf $1}')
```
Comment (dengliu) [inline bin/common.sh:78]: this is actually `/sys/fs/cgroup/memory.max` in cgroup2

Comment (dengliu) [reply bin/common.sh:78]: when start be I got
```
cat: /sys/fs/cgroup/memory/memory.max: No such file or directory
2022-12-14T03:33:59.839744106Z can't get mem info from /sys/fs/cgroup/memory/memory.max
```
