### PR TITLE
[BugFix] Fix bug create too much dynamic partition.

### LINKED ISSUE #14367: create too much history partition
this pr https://github.com/StarRocks/starrocks/pull/9501 add feature to create history partition.
image

if I set start a small value ， for example -2147483646,  it will create partition from +5775458-11-14, and it is illegal date value, and throw exception as follows 
```
2022-11-30 16:35:01,971 WARN (DynamicPartitionScheduler|43) [DynamicPartitionScheduler.getAddPartitionClause():167] Error in gen addPartitionKeyRange. Error=date literal [+5775458-11-14] is invalid, db: feng, table: xxx
```
then DynamicPartitionScheduler will do it again and again, more important, it always take db lock.

Of course, -2147483646 is not reasonable value, for old version, it is not elegant but ok. so it might cause the problem for upgraded users.

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #14367

## Problem Summary(Required) ：

This fix is due to issues introduced by this PR #9501 and does not fully follow this PR.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java [hunk 1]
```diff
@@ -84,6 +89,10 @@ public DynamicPartitionProperty(Map<String, String> properties) {
             this.buckets = Integer.parseInt(properties.get(BUCKETS));
             this.replicationNum =
                     Integer.parseInt(properties.getOrDefault(REPLICATION_NUM, String.valueOf(NOT_SET_REPLICATION_NUM)));
+            this.createHistoryPartition =
+                    Boolean.parseBoolean(properties.get(CREATE_HISTORY_PARTITION));
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java:93]: CREATE_HISTORY_PARTITION seems unnecessary because the user setting HISTORY_PARTITION_NUM means that he wants to create history partitions.

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/DynamicPartitionProperty.java]: you are right.

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 26 / 32 (81.25%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/util/DynamicPartitionUtil.java|19|25|76.00%|[123, 272, 278, 281, 282, 345]|
|:large_blue_circle:|com/starrocks/common/Config.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/catalog/DynamicPartitionProperty.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/ErrorCode.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/clone/DynamicPartitionScheduler.java|2|2|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
