### PR TITLE
[BugFix] fix outer join and anti join rewrite bug

### LINKED ISSUE #27163: [materialized view optimization] result error left outor join rewrite to full outer join
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
                k1 int,
                k2 int not null
            )
            DUPLICATE KEY(k1);
CREATE TABLE t2 (
                a int,
                b int not null
            )
            DUPLICATE KEY(a);
INSERT INTO t1 VALUES (1,1),(3,2),(null,1);
INSERT INTO t2 VALUES (1,1),(2,2),(null,1);
CREATE MATERIALIZED VIEW mv1 REFRESH MANUAL AS select * from t1 full outer join t2 on k1=a;
REFRESH MATERIALIZED VIEW mv1 with sync mode;
select * from t1 left outer join t2 on k1=a where k1=3;
select * from t1 right outer join t2 on k1=a where b=2;
```
### Expected behavior (Required)
```
mysql> select * from t1 left outer join t2 on k1=a where k1=3;
+------+------+------+------+
| k1   | k2   | a    | b    |
+------+------+------+------+
|    3 |    2 | NULL | NULL |
+------+------+------+------+
1 row in set (0.01 sec)

mysql> select * from t1 right outer join t2 on k1=a where b=2;
+------+------+------+------+
| k1   | k2   | a    | b    |
+------+------+------+------+
| NULL | NULL |    2 |    2 |
+------+------+------+------+
1 row in set (0.01 sec)
```

### Real behavior (Required)
```
mysql> select * from t1 left outer join t2 on k1=a where k1=3;
+------+------+------+------+
| k1   | k2   | a    | b    |
+------+------+------+------+
|    3 |    2 |    3 | NULL |
+------+------+------+------+
1 row in set (0.00 sec)

mysql> select * from t1 right outer join t2 on k1=a where b=2;
+------+------+------+------+
| k1   | k2   | a    | b    |
+------+------+------+------+
| NULL | NULL | NULL |    2 |
+------+------+------+------+
1 row in set (0.01 sec)
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-dca7ca2`

### PR DESCRIPTION
**Pull request by ABingHuang**
Fixes #27163 

The bug has the following causes:
1. The invalid use of equivalence in outer join and anti join, which leads to the invalid use of output columns. The join on predicate A.a = B.b for outer join and anti join can not be used to construct equivalence class.
2. the compatibility check should be more strict for outer and anti join, which should not consider the pushdown predicates derived from equivalence class. eg: the left outer join should make sure that the predicates of right child tree of query and mv should be equal. it means that the compensation predicates should not come from right child of left outer join.
3. when clone equivalence class, should use the same Set<ColumnRefOperator> for the columns in the same ec.

fixed by
1. constructing eq without column equal predicates in outer and anti join
2. add more strict compatibility check for outer and anti join, excluding pushdown ec derived predicates
3. fix equivalence class clone bug.

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 112 / 122 (91.80%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|83|92|90.22%|[301, 310, 319, 324, 334, 478, 479, 1811, 1823]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java|9|10|90.00%|[84]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/EquivalenceClasses.java|4|4|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/JoinDeriveContext.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|1|1|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 147 / 157 (93.63%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java|15|18|83.33%|[67, 85, 87]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|94|101|93.07%|[246, 316, 334, 337, 718, 719, 1844]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/EquivalenceClasses.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/JoinDeriveContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java [hunk 1]
```diff
@@ -37,7 +37,12 @@ public EquivalenceClasses clone() {
         final EquivalenceClasses ec = new EquivalenceClasses();
         for (Map.Entry<ColumnRefOperator, Set<ColumnRefOperator>> entry :
                 this.columnToEquivalenceClass.entrySet()) {
-            ec.columnToEquivalenceClass.put(entry.getKey(), Sets.newLinkedHashSet(entry.getValue()));
+            if (!ec.columnToEquivalenceClass.containsKey(entry.getKey())) {
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java:40]: It's better to put this into the use of `clone` method? `clone` method should deep copy heree?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java [hunk 2]
```diff
@@ -38,6 +38,9 @@ public abstract class ScalarOperator implements Cloneable {
     // from JoinNode.
     protected boolean isRedundant = false;
 
+    // whether the ScalarOperator is pushdown from equivalence derivation
+    protected boolean isPushdown = false;
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java:42]: can we use `isRedundant`, or merge with this?

```
    // Check weather the scalar operator is redundant which will not affect the final
    // if it's not considered. eg, `IsNullPredicateOperator` which is pushed down
    // from JoinNode.
    protected boolean isRedundant = false;
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 3]
```diff
@@ -291,12 +300,60 @@ boolean computeCompatibility(OptExpression queryExpr, OptExpression mvExpr) {
         }
     }
 
+    private boolean checkJoinMatch(JoinOperator joinOperator, OptExpression queryExpr, OptExpression mvExpr) {
+        if (joinOperator.isInnerJoin() || joinOperator.isCrossJoin() || joinOperator.isSemiJoin()) {
+            return true;
+        } else if (joinOperator.isLeftOuterJoin() || joinOperator.isLeftAntiJoin()) {
+            // for left outer/anti join, we should make sure the predicates of right child should be equivalent
+            return checkJoinChildPredicate(queryExpr, mvExpr, 1);
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:308]: Besides on-predicates, we should make sure other predicates are still equivalent?

This is a bit strict?

eg:
MV: a left join b on a.A = b.A where a.x > 10
Query :  a left join b on a.A = b.A where a.x > 20

This can be rewritten or not?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 4]
```diff
@@ -291,12 +300,60 @@ boolean computeCompatibility(OptExpression queryExpr, OptExpression mvExpr) {
...
+                    queryPredicates, mvPredicates, index);
+        }
+        return isEqual;
+    }
+
+    private boolean isAllPredicateEquivalent(
+            Collection<ScalarOperator> queryPredicates, final Collection<ScalarOperator> mvPredicates) {
+        return queryPredicates.size() == mvPredicates.size()
+                && queryPredicates.stream().allMatch(queryPredicate ->
+                mvPredicates.stream().anyMatch(mvPredicate -> mvPredicate.equivalent(queryPredicate)));
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:346]: `equivalent` is not totally safe?
eg:
`a > 10` ? `a >= 9`
`a > 10 and a < 20` ? `a between 10 and 20`

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 5]
```diff
@@ -1720,6 +1810,44 @@ protected EquationRewriter buildEquationRewriter(
...
+        EquivalenceClasses ec = new EquivalenceClasses();
+        if (equalPredicates == null) {
+            return ec;
+        }
+        equalPredicates = MvUtils.canonizePredicateForRewrite(equalPredicates);
+        outerJoinEqualPredicates = MvUtils.canonizePredicateForRewrite(outerJoinEqualPredicates);
+        List<ScalarOperator> outerJoinConjuncts = Utils.extractConjuncts(outerJoinEqualPredicates);
+        for (ScalarOperator equalPredicate : Utils.extractConjuncts(equalPredicates)) {
+            if (outerJoinConjuncts.contains(equalPredicate)) {
+                // outer join on predicates can not be used to construct equivalence class
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1834]: Why ? can you give an example?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:308]: for left outer join, the predicate of right child should be equal. a.x is left table predicate, which can be rewritten

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java:42]: seems not the same purpose, maybe we can discuss it.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java (hunk 1 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/base/EquivalenceClasses.java:40]: no, if you use deep copy here, you may add new column into equivalence class, there will be bug

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:1834]: this is an exmaple, https://github.com/StarRocks/starrocks/issues/27163

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java (hunk 4 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:346]: add normalization here.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 146 / 156 (93.59%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java|15|18|83.33%|[67, 85, 87]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|98|105|93.33%|[246, 316, 338, 341, 722, 723, 1848]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/EquivalenceClasses.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|13|13|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/JoinDeriveContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|1|1|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 151 / 161 (93.79%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java|15|18|83.33%|[67, 85, 87]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java|98|105|93.33%|[246, 316, 338, 341, 722, 723, 1848]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/scalar/ScalarOperator.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/base/EquivalenceClasses.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rewrite/JoinPredicatePushdown.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|18|18|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/mv/JoinDeriveContext.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/rule/BaseMaterializedViewRewriteRule.java|1|1|100.00%|[]|

**Review by LiShuMing — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
