### PR TITLE
[BugFix] Fix create bloom filter index bug

### LINKED ISSUE #4953: create bloom filter index because of materialized view
### Steps to reproduce the behavior (Required)
1. create table client_log

CREATE TABLE `client_log` (
  `event` varchar(100) NULL COMMENT "",
  `device_id` varchar(100) NULL COMMENT "",
  `page_time` bigint(20) NULL COMMENT "",
  `tag` varchar(100) NULL COMMENT "",
  `tag_model` varchar(100) NULL COMMENT "",
  `exposure_id` varchar(100) NULL COMMENT "",
  `exposure_status` varchar(100) NULL COMMENT "",
  `exposure_page_detail` varchar(100) NULL COMMENT "",
  `ad_content` varchar(65533) NULL COMMENT "",
  `nav_id` varchar(100) NULL COMMENT "",
  `user_id` varchar(100) NULL COMMENT "",
  `version` varchar(100) NULL COMMENT "",
  `app_id` varchar(100) NULL COMMENT "",
  `page` varchar(100) NULL COMMENT "",
  `page_detail` varchar(100) NULL COMMENT "",
  `origin` varchar(100) NULL COMMENT "",
  `timestamp` bigint(20) NULL COMMENT "",
  `launch_id` varchar(100) NULL COMMENT "",
  `code` varchar(100) NULL COMMENT "",
  `rec_id` varchar(100) NULL COMMENT "",
  `create_date` date NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`event`)
COMMENT "OLAP"
PARTITION BY RANGE(`create_date`)
(PARTITION p20210809 VALUES [('2021-08-09'), ('2021-08-10')),
PARTITION p20210810 VALUES [('2021-08-10'), ('2021-08-11')),
PARTITION p20210811 VALUES [('2021-08-11'), ('2021-08-12')),
PARTITION p20210812 VALUES [('2021-08-12'), ('2021-08-13')),
PARTITION p20210813 VALUES [('2021-08-13'), ('2021-08-14')))
DISTRIBUTED BY HASH(`tag`) BUCKETS 24
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.time_zone" = "Asia/Shanghai",
"dynamic_partition.start" = "-90",
"dynamic_partition.end" = "3",
"dynamic_partition.prefix" = "p",
"dynamic_partition.buckets" = "24",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);

2. create materialized view

CREATE MATERIALIZED VIEW tag_model_vies AS select create_date,event,tag_model,tag,count(distinct user_id) as uv from client_log group by tag,tag_model,create_date,event
alter table

3. add bloom filter index
alter table client_log set("bloom_filter_columns"="event,origin,tag_model,tag,app_id,version");

### Expected behavior (Required)
success

### Real behavior (Required)
ERROR 1064 (HY000): Can not modify partition column[create_date]. index[tag_model_vies]

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
master

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #4953 

## Problem Summary(Required) ：

Fix create bloom filter index bug by do not check the partition and distribution columns when add bloom filter because it is unnecessary when add bloom filter index.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 1 / 26 (03.85%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|1|26|03.85%|

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java [hunk 1]
```diff
@@ -1096,7 +1137,8 @@ private void createJob(long dbId, OlapTable olapTable, Map<Long, LinkedList<Colu
                     for (Column alterColumn : alterSchema) {
                         if (alterColumn.nameEquals(partitionCol.getName(), true)) {
                             // 2.1 partition column cannot be modified
-                            if (!alterColumn.equals(partitionCol)) {
+                            if (!alterColumn.equals(partitionCol)
+                                    && !checkPartitionColumnChangeAllowed(partitionCol, alterColumn)) {
```
Comment (Astralidea) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java:1141]: some check conditions have already been done in equal, 
so there is no need to check so much?

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java [hunk 2]
```diff
@@ -854,6 +854,47 @@ private void checkAssignedTargetIndexName(String baseIndexName, String targetInd
         }
     }
 
+    private boolean checkPartitionColumnChangeAllowed(Column oldPartitionColumn, Column newPartitionColumn) {
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java:857]: We are better to describe the problem clearly in the commit message. 
Don't make me guess what's the problem.

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java [hunk 3]
```diff
@@ -1096,7 +1137,8 @@ private void createJob(long dbId, OlapTable olapTable, Map<Long, LinkedList<Colu
                     for (Column alterColumn : alterSchema) {
                         if (alterColumn.nameEquals(partitionCol.getName(), true)) {
                             // 2.1 partition column cannot be modified
-                            if (!alterColumn.equals(partitionCol)) {
+                            if (!alterColumn.equals(partitionCol)
```
Comment (chaoyli) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java:1140]: checkPartitionColumnChangeAllowed() is the superset of Column.equals().
You can call Column.equals() in checkPartitionColumnChangeAllowed()
It can reduce some of the duplicate code paths.

**Review by chaoyli — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java [hunk 4]
```diff
@@ -854,6 +854,47 @@ private void checkAssignedTargetIndexName(String baseIndexName, String targetInd
...
+        }
+        if (oldPartitionColumn.getPrecision() != newPartitionColumn.getPrecision()) {
+            return false;
+        }
+        if (oldPartitionColumn.getScale() != newPartitionColumn.getScale()) {
+            return false;
+        }
+        if (oldPartitionColumn.isKey() != newPartitionColumn.isKey()
+                || (oldPartitionColumn.getAggregationType() != newPartitionColumn.getAggregationType())) {
+            // change partition column from key to value is allowed
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/alter/SchemaChangeHandler.java:882]: it think this comment should describe why new partition column could be value with AggregateType.NONE

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 27 / 38 (71.05%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|27|38|71.05%|

**Review by Astralidea — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
