### PR TITLE
[BugFix] Create table failed when deploying shared-data cluster in k8s with CN nodes only

### LINKED ISSUE #41417: Create table failed when deploy shared-data cluster in k8s with CN nodes only
### Steps to reproduce the behavior (Required)

1. deploy a shared-data cluster in k8s
2. create table

### Real behavior (Required)

image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

3.1.5、3.1.7

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

Fixes #41417

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java [hunk 1]
```diff
@@ -817,8 +796,36 @@ public int getAliveComputeNodeNumber() {
     }
 
     public ComputeNode getComputeNodeWithBePort(String host, int bePort) {
-        for (ComputeNode computeNode : idToComputeNodeRef.values()) {
-            if (computeNode.getHost().equals(host) && computeNode.getBePort() == bePort) {
+        return getComputeNodeWithBePortCommon(host, bePort, idToComputeNodeRef);
+    }
+
+    private ComputeNode getComputeNodeWithBePortCommon(String host, int bePort, Map<Long, ? extends ComputeNode> nodeRef) {
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java:802]:
```suggestion
    private <T extends ComputeNode> T getComputeNodeWithBePortCommon(String host, int bePort, Map<Long, T> nodeRef) {
```

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java:802]: Avoid downward casting from ComputeNode to Backend

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java:802]: > Avoid downward casting from ComputeNode to Backend

Seems like still need to cast to `T` when return from `getComputeNodeWithBePortCommon ` . So I will just leave it as it is now

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/system/SystemInfoService.java:802]: T is the element type, no need to cast, the.for loop should use T instead of computeNode

**Review by kevincai — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Comment by wxl24life** [comment]
@HangyuanLiu @imay @nshangyiming PTAL

**Comment by wxl24life** [comment]
@HangyuanLiu @imay @nshangyiming PTAL

**Review by 0xtonyxia — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]
