### PR TITLE
[ISSUE-2721] turn DecimalLiteral into NullLiteral when it overflows

### LINKED ISSUE #2721: Decimal V3 cast overflows bug
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS d2;
CREATE DATABASE d2;
USE d2;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE t0 (c_0_0 DECIMAL(26, 2)  NOT NULL ,c_0_1 DECIMAL128(19, 3)  NOT NULL ,c_0_2 DECIMAL128(4, 3)  NULL ,c_0_3 BOOLEAN NOT NULL ,c_0_4 DECIMAL128(25, 19)  NOT NULL ,c_0_5 BOOLEAN REPLACE NOT NULL ,c_0_6 DECIMAL32(8, 5)  MIN NULL ,c_0_7 BOOLEAN REPLACE NULL ,c_0_8 PERCENTILE PERCENTILE_UNION NULL ,c_0_9 LARGEINT SUM NULL ,c_0_10 PERCENTILE PERCENTILE_UNION NOT NULL ,c_0_11 BITMAP BITMAP_UNION NULL ,c_0_12 HLL HLL_UNION NOT NULL ,c_0_13 DECIMAL(16, 3)  MIN NULL ,c_0_14 DECIMAL128(18, 6)  MAX NOT NULL ) AGGREGATE KEY (c_0_0,c_0_1,c_0_2,c_0_3,c_0_4) DISTRIBUTED BY HASH (c_0_3,c_0_0,c_0_2) properties("replication_num"="1") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 DECIMAL64(9, 9)  NULL ,c_1_1 CHAR(1) NOT NULL ,c_1_2 DECIMAL32(5, 4)  NOT NULL ,c_1_3 DECIMAL32(4, 0)  NOT NULL ,c_1_4 CHAR(11) NOT NULL ,c_1_5 DATE NOT NULL ,c_1_6 DECIMAL128(20, 5)  NULL ) UNIQUE KEY (c_1_0,c_1_1) DISTRIBUTED BY HASH (c_1_0) properties("replication_num"="1") ;
CREATE TABLE t2 (c_2_0 BOOLEAN NULL ) AGGREGATE KEY (c_2_0) DISTRIBUTED BY HASH (c_2_0) properties("replication_num"="1") ;
INSERT INTO t0 VALUES (6378205147408984032880.92, 7048539277116.348, 0.000, false, 5.26653E-14, false, 0.00289, true, percentile_hash("1064797217"), NULL, percentile_hash("-71632349"), bitmap_hash("htg"), hll_hash("f"), 6815337417.396, 829413.367408), (5053913417132953611869.43, 9788064880043.027, 0.005, false, 7.64546E-14, true, 0.00084, false, percentile_hash("1064797217"), 1064797217, percentile_hash("864779358"), bitmap_hash("KBA"), hll_hash("UBN"), 4731929589.649, 105651.423855);
DELETE FROM t0 WHERE c_0_3=false AND c_0_0=2926409103723450755358.14;
INSERT INTO t1 VALUES (2E-9, "", 0.0003, 9050, "0TjL", "1970-01-01", 4694641137.66309), (0E-9, "", 0.0006, 5721, "BN9j3k", "1970-01-01", 5793498088.50641), (4E-9, "", 0.0001, 3248, "", "1970-01-01", NULL);
INSERT INTO t0 VALUES (1454021617839380553925.02, 9812756464485.672, NULL, false, 3.04158E-14, false, 0.00304, false, percentile_hash("1214695759"), 918598135, percentile_hash("171721691"), bitmap_hash("0"), hll_hash("00"), 4868443441.243, 955473.695015);
TRUNCATE TABLE t2;
INSERT INTO t1 VALUES (1E-9, "", 0.0004, 8388, "l4", "1970-01-01", 6735465370.99759), (3E-9, "", 0.0001, 7495, "", "1970-01-01", 349215963.13615);
INSERT INTO t0 VALUES (7879297852428628346863.43, 1920765789296.405, 0.007, false, 4.18406E-14, false, 0.00657, false, percentile_hash("-1644793194"), 918598135, percentile_hash("-71632349"), bitmap_hash("wnboT25"), hll_hash("n"), 3827473239.562, 230976.214694);
INSERT INTO t2 VALUES (false), (false);
2. SELECT DISTINCT subt2.c_2_0 FROM t0,  (SELECT t2.c_2_0 FROM t2 WHERE  (  ( t2.c_2_0 ) = ( true )  ) < ( ((t2.c_2_0) IN (false) )  BETWEEN (t2.c_2_0) AND (t2.c_2_0)  ) ) subt2 FULL JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6 FROM t1 ORDER BY t1.c_1_4, t1.c_1_2) subt1 ON subt2.c_2_0 = subt1.c_1_2 AND (6453) IN (4861, 4302)  < subt1.c_1_2 AND subt2.c_2_0 != subt1.c_1_1 AND subt2.c_2_0 <= subt1.c_1_1 AND subt2.c_2_0 > subt1.c_1_0 AND subt2.c_2_0 = subt1.c_1_0;
-- cardinality: 1
SELECT DISTINCT * FROM (SELECT DISTINCT subt2.c_2_0 FROM t0,  (SELECT t2.c_2_0 FROM t2 WHERE  (  ( t2.c_2_0 ) = ( true )  ) < ( ((t2.c_2_0) IN (false) )  BETWEEN (t2.c_2_0) AND (t2.c_2_0)  ) ) subt2 FULL OUTER JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6 FROM t1 ORDER BY t1.c_1_4, t1.c_1_2) subt1 ON subt2.c_2_0 = subt1.c_1_2 AND (6453) IN (4861, 4302)  < subt1.c_1_2 AND subt2.c_2_0 != subt1.c_1_1 AND subt2.c_2_0 <= subt1.c_1_1 AND subt2.c_2_0 > subt1.c_1_0 AND subt2.c_2_0 = subt1.c_1_0 WHERE (0.00)  BETWEEN (CASE  WHEN (subt1.c_1_5)  BETWEEN (subt1.c_1_5) AND (subt1.c_1_5)  THEN CAST(151971657 AS DECIMAL32 )   WHEN false THEN CASE  WHEN NULL THEN 0.03 ELSE 0.02 END ELSE 0.04 END) AND (0.04)  UNION ALL SELECT DISTINCT subt2.c_2_0 FROM t0,  (SELECT t2.c_2_0 FROM t2 WHERE  (  ( t2.c_2_0 ) = ( true )  ) < ( ((t2.c_2_0) IN (false) )  BETWEEN (t2.c_2_0) AND (t2.c_2_0)  ) ) subt2 FULL OUTER JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6 FROM t1 ORDER BY t1.c_1_4, t1.c_1_2) subt1 ON subt2.c_2_0 = subt1.c_1_2 AND (6453) IN (4861, 4302)  < subt1.c_1_2 AND subt2.c_2_0 != subt1.c_1_1 AND subt2.c_2_0 <= subt1.c_1_1 AND subt2.c_2_0 > subt1.c_1_0 AND subt2.c_2_0 = subt1.c_1_0 WHERE (NOT ((0.00)  BETWEEN (CASE  WHEN (subt1.c_1_5)  BETWEEN (subt1.c_1_5) AND (subt1.c_1_5)  THEN CAST(151971657 AS DECIMAL32 )   WHEN false THEN CASE  WHEN NULL THEN 0.03 ELSE 0.02 END ELSE 0.04 END) AND (0.04) )) UNION ALL SELECT DISTINCT subt2.c_2_0 FROM t0,  (SELECT t2.c_2_0 FROM t2 WHERE  (  ( t2.c_2_0 ) = ( true )  ) < ( ((t2.c_2_0) IN (false) )  BETWEEN (t2.c_2_0) AND (t2.c_2_0)  ) ) subt2 FULL OUTER JOIN (SELECT t1.c_1_0, t1.c_1_1, t1.c_1_2, t1.c_1_3, t1.c_1_4, t1.c_1_5, t1.c_1_6 FROM t1 ORDER BY t1.c_1_4, t1.c_1_2) subt1 ON subt2.c_2_0 = subt1.c_1_2 AND (6453) IN (4861, 4302)  < subt1.c_1_2 AND subt2.c_2_0 != subt1.c_1_1 AND subt2.c_2_0 <= subt1.c_1_1 AND subt2.c_2_0 > subt1.c_1_0 AND subt2.c_2_0 = subt1.c_1_0 WHERE (((0.00)  BETWEEN (CASE  WHEN (subt1.c_1_5)  BETWEEN (subt1.c_1_5) AND (subt1.c_1_5)  THEN CAST(151971657 AS DECIMAL32 )   WHEN false THEN CASE  WHEN NULL THEN 0.03 ELSE 0.02 END ELSE 0.04 END) AND (0.04) ) IS NULL)) t;
-- cardinality: 0

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - main ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_BRANCH_ASAN d92cde3 |
+------------------------------+

### PR DESCRIPTION
**Pull request by satanson**
https://github.com/StarRocks/starrocks/issues/2721

ReduceCastRule behaves incorrectly when it apply to cast(1000000(int) as DECIMAL32(9,9)) <= 0(int), it reduces this binary predicate to 1000000<= 0. because cast(1000000(int) as DECIMAL32(9,9)) overflows and NULL is generated, so the final result should be NULL.

so tryDecimalCastConstant function is added to process BinaryPredicate involves decimal types in ReduceCastRule.

tryDecimalCastConstant is employed by ReduceCastRule to reduce BinaryPredicateOperator involving DecimalV3 ReduceCastRule try to reduce `CAST(Expr<T> as U) BINOP LITERAL<S>` to `EXPR<T> BINOP CAST(LITERAL<S> as T>`, only T->U casting and S->T casting are both legal, then this reduction is legal, so for numerical types, S is not wider than T and T is not wider than U, that is to say, U should is assignable to T, T is assignable to S losslessly.

for examples:
   1. CAST(IntLiteral(100,TINYINT) as DECIMAL32(9,9)) < IntLiteral(0x10000, SMALLINT) cannot be reduced.
   2. CAST(IntLiteral(100,SMALLINT) as DECIMAL64(13,10)) < IntLiteral(101, TINYINT) can be reduced.

### CODE REVIEW

**Review by HangyuanLiu — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java [hunk 1]
```diff
@@ -407,6 +410,7 @@ public Expr visitCall(CallOperator call, FormatterContext context) {
         @Override
         public Expr visitCastOperator(CastOperator operator, FormatterContext context) {
             CastExpr expr = new CastExpr(operator.getType(), buildExecExpression(operator.getChild(0), context));
+            LOG.warn(String.format("[SATANSON] castExpr=%s", expr.toSql()));
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/plan/ScalarOperatorToExpr.java:413]: Remove it

**Comment by satanson** [comment]
run starrocks_clang-format

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java [hunk 2]
```diff
@@ -393,7 +393,7 @@ public ConstantOperator castTo(Type desc) throws Exception {
                     throw new SemanticException("Forbidden cast to decimal(precision=0, scale=0)");
                 }
             } catch (AnalysisException e) {
-                throw new SemanticException(e.getMessage());
+                return ConstantOperator.createNull(desc);
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java:396]: I think returning null is dangerous, FE cast is very weak, some time cast in BE is right but FE can't handle it.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java [hunk 3]
```diff
@@ -429,4 +431,78 @@ public static boolean canOnlyDoBroadcast(PhysicalHashJoinOperator node,
...
+
+    private static boolean isIntegerOrDecimalType(Type t) {
+        return t.isIntegerType() || t.isLargeint() || t.isDecimalV3();
+    }
+
+    // isAssignable means that assigning or casting rhs to lhs never overflows.
+    // only both integer part width and fraction part width of lhs is not narrower than counterparts
+    // of rhs, then rhs can be assigned to lhs. for integer types, integer part width is computed by
+    // calling Type::getPrecision and its scale is 0.
+    private static boolean isAssignable(ScalarType lhs, ScalarType rhs) {
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java:443]:
```suggestion
    private static boolean isAssignable2Decimal(ScalarType lhs, ScalarType rhs) {
```

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java (hunk 2 above)
Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/operator/scalar/ConstantOperator.java:396]: so compute in BE?  but doing so would prevent outer join from converting to a narrower outer join or inner join. outer join containing predicates involving decimals would cost more time.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java (hunk 3 above)
Comment (satanson) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java:443]: ok

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java [hunk 4]
```diff
@@ -429,4 +431,78 @@ public static boolean canOnlyDoBroadcast(PhysicalHashJoinOperator node,
         }
         return Optional.empty();
     }
+
+    private static boolean isIntegerOrDecimalType(Type t) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java:435]:
```suggestion
    private static boolean isFixedNumericType(Type t) {
```

Add this method to Type class

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java [hunk 5]
```diff
@@ -429,4 +431,78 @@ public static boolean canOnlyDoBroadcast(PhysicalHashJoinOperator node,
...
+        return t.isIntegerType() || t.isLargeint() || t.isDecimalV3();
+    }
+
+    // isAssignable means that assigning or casting rhs to lhs never overflows.
+    // only both integer part width and fraction part width of lhs is not narrower than counterparts
+    // of rhs, then rhs can be assigned to lhs. for integer types, integer part width is computed by
+    // calling Type::getPrecision and its scale is 0.
+    private static boolean isAssignable2Decimal(ScalarType lhs, ScalarType rhs) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java:443]: Move this method to ScalarType class

**Review by Seaven — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java (hunk 4 above)
Comment (Seaven) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/Utils.java:435]: There has a samliar method `Type.isExactNumericType()`

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
