### PR TITLE
[BugFix] fix the npe bug when replaying the tablet consistency check data

### LINKED ISSUE #6684: [BUG] fe exits with npe when replaying the consistency check data
### Steps to reproduce the behavior (Required)
Restore a big table at the tablet consistency check time(23:00~04:00, you can change it by set consistency_check_start_time and consistency_check_end_time at fe.conf).

### Expected behavior (Required)
system runs normally

### Real behavior (Required)
fe exists
```
2022-05-26 23:58:04,238 ERROR (stateListener|72) [EditLog.loadJournal():830] Operation Type 29
java.lang.NullPointerException: null
        at com.starrocks.consistency.ConsistencyChecker.replayFinishConsistencyCheck(ConsistencyChecker.java:372) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.loadJournal(EditLog.java:352) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2503) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1244) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:289) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2420) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]

```

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #6684 

## Problem Summary(Required) ：

Only check the OLAP table who is in NORMAL state. Because some tablets of the not NORMAL table may just a temporary presence in memory, if we check those tablets and log FinishConsistencyCheck to bdb, it will throw NullPointerException when replaying the log.

### CODE REVIEW

**Review by padmejin — COMMENTED** [review]
I strongly suggest adding a unit test case for this PR...

**Review by Astralidea — DISMISSED** [review]

**Comment by Astralidea** [comment]
> I strongly suggest adding a unit test case for this PR...

+1

**Comment by gengjun-git** [comment]
> I strongly suggest adding a unit test case for this PR...

I will try

**Comment by chaoyli** [comment]
sh starrocks_fe_unittest

**Review by Astralidea — DISMISSED** [review]

**Comment by gengjun-git** [comment]
> I strongly suggest adding a unit test case for this PR...

done

File: fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java [hunk 1]
```diff
@@ -231,7 +232,7 @@ private int getJobNum() {
      * we use a priority queue to sort db/table/partition/index/tablet by 'lastCheckTime'.
      * chose a tablet which has the smallest 'lastCheckTime'.
      */
-    private List<Long> chooseTablets() {
+    public List<Long> chooseTablets() {
```
Comment (padmejin) [inline fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java:235]: public->protected will be enough

**Review by padmejin — COMMENTED** [review]
BTW, the title has a typo, BubFix -> BugFix

File: fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/consistency/ConsistencyChecker.java]: done

**Review by padmejin — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/consistency/ConsistencyChecker.java|2|2|100.00%|

**Review by Astralidea — APPROVED** [review]

**Review by wyb — APPROVED** [review]
