### PR TITLE
[BugFix] Avoid limit push down of multi-distinct cases

### LINKED ISSUE #11274: Limit is pushed down mistakenly in the scenario of multiple distinct agg functions reusing CTE
### Steps to reproduce the behavior (Required)
prepare data
```
DROP TABLE if exists t0;

CREATE TABLE if not exists t0
(
ts DATETIME NOT NULL,
k0 VARCHAR(10) NOT NULL,
v0 BIGINT NOT NULL,
v1 DECIMAL64(7, 2) NOT NULL
) ENGINE=OLAP
DUPLICATE KEY(`ts`, `k0`, `v0`)
COMMENT "OLAP"
PARTITION BY RANGE(ts) (
  START ("2022-01-01 00:00:00") END ("2022-02-01 00:00:00") EVERY (INTERVAL 1 day)
)
DISTRIBUTED BY HASH(`ts`, `k0`, `v0`) BUCKETS 64
PROPERTIES(
"replication_num" = "1",
"in_memory" = "false",
"storage_format" = "default"
);
INSERT INTO t0
  (ts, k0, v0, v1)
VALUES
  ('2022-01-24 01:18:58', 'x', '-2', '-68098.09'),
  ('2022-01-31 19:31:39', 'IAMA', '-3', '66416.14'),
  ('2022-01-13 19:04:55', 'p', '-165307117929', '8952.25'),
  ('2022-01-09 12:03:49', 'My', '-398594843', '53976.61'),
  ('2022-01-24 10:07:46', 'VFuCTLWLK', '-7472976858', '10524.72'),
  ('2022-01-20 10:23:23', 'HQ4Jp', '6140475120740', '-37293.58'),
  ('2022-01-18 09:02:19', 'HQ4Jp', '64752185315', '-93644.28'),
  ('2022-01-25 07:03:02', 'x4UnqYvOt', '-16492015', '75778.38'),
  ('2022-01-14 14:05:37', 'rK3XUmw5', '-7472976858', '5421.34'),
  ('2022-01-23 14:16:06', 'LTM', '-398594843', '63834.67'),
  ('2022-01-01 03:53:51', 'qWjSJj13', '6140475120740', '-55343.15'),
  ('2022-01-14 18:32:52', 'nTb2rrW', '6140475120740', '43443.60'),
  ('2022-01-21 02:12:31', 'VFuCTLWLK', '1898625731459325159', '86461.87'),
  ('2022-01-26 15:43:14', 'DtzUUl', '-2381241938849338601', '75028.77'),
  ('2022-01-06 04:19:51', 'iD', '64752185315', '-92338.81'),
  ('2022-01-03 10:28:17', 'ZxY', '1898625731459325159', '0.01'),
  ('2022-01-29 01:50:07', 'jLT99K', '-740633217462191', '121.26'),
  ('2022-01-27 19:09:38', 'x', '10299', '75159.20'),
  ('2022-01-21 18:14:45', 'VZu', '-2', '94163.25'),
  ('2022-01-08 08:37:50', 'PmD2H', '10299', '8809.51'),
  ('2022-01-15 21:06:54', 'U9KE', '-740633217462191', '-34999.61'),
  ('2022-01-21 05:40:46', 'fcOWh527k', '-16492015', '48601.34'),
  ('2022-01-24 11:33:12', 'c3E0', '321974', '-97574.53'),
  ('2022-01-05 00:15:47', '2argSOY9w', '321974', '0.54'),
  ('2022-01-22 08:39:11', 'pqM857', '-165307117929', '-15470.38'),
  ('2022-01-31 10:17:05', 'QAgwE', '419554', '28347.44'),
  ('2022-01-13 09:58:30', 'VkvzvDa', '405900030', '27932.60'),
  ('2022-01-11 13:55:40', 'DtzUUl', '64752185315', '45793.47'),
  ('2022-01-04 07:32:16', '7TBcl0j', '10299', '22.46'),
  ('2022-01-11 09:08:35', 'F', '-740633217462191', '48423.21'),
  ('2022-01-22 14:52:23', 'fcOWh527k', '-3', '50663.66'),
  ('2022-01-19 13:23:35', 'e', '1898625731459325159', '-4685.07'),
  ('2022-01-02 06:05:19', 'iD', '-7472976858', '14004.01'),
  ('2022-01-21 07:51:03', 'e', '-740633217462191', '-8697.92'),
  ('2022-01-19 06:14:05', 'x', '-24926502', '-97649.79'),
  ('2022-01-14 22:48:30', 'LWsgcVx', '19362737', '-19811.79'),
  ('2022-01-15 18:17:23', 'LBegd', '-740633217462191', '-62985.55'),
  ('2022-01-18 04:56:30', 'O', '-398594843', '-29269.94'),
  ('2022-01-22 17:12:25', 'x', '-35890853', '-80084.29'),
  ('2022-01-05 21:41:39', 'PiB', '19362737', '13178.26'),
  ('2022-01-30 01:03:14', 'r7iDB', '19362737', '-6454.35'),
  ('2022-01-30 13:29:57', 'ZqwByW', '-7472976858', '-95026.96'),
  ('2022-01-29 23:38:15', 'wwPD3', '6140475120740', '65815.04'),
  ('2022-01-11 23:24:13', 'Y1P', '10299', '-99995.01');
```

Q1
```
select * from (select /*+ SET_VAR (streaming_preaggregation_mode = 'auto',new_planner_agg_stage='3') */ date_trunc('week',ts) as week,k0,(ndv(cast(ts as BIGINT))) as __col_0,(bitmap_count(bitmap_union(bitmap_hash(ts)))) as __col_1,(left(avg(v1),6)) as __col_2,(sum(v1)) as __col_3,(left(variance(v0),6)) as __col_4,(sum(distinct length(k0))) as __col_5,(max(length(k0))) as __col_6,(left(avg(distinct v0),6)) as __col_7 from t0 where ts > '2022-01-01 00:00:00' and ts < '2022-01-10 23:59:59' group by date_trunc('week',ts),k0) as t limit 1;
```

### Expected behavior (Required)
Q1 runs sucessfully and returns only one row exactly
### Real behavior (Required)
Q1 return empty result set.

image

### StarRocks version (Required)
master(a824b9ccf5fa8035f09b0f47a61a47e57c371344)

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11274

## Problem Summary(Required) ：

For multi-distinct cases with group like `select sum(distinct(v1)), avg(distinct(v2)) from t3 group by v3 limit 1`, limit cannot be push down to the aggregate. But for cases without group by, it can.

## Test

And, I'm wondering which plan,with or without cte , is better in the case of limitation.

```sql
-- Q1, with low cardinality group by, without non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem group by L_TAX limit 1;

-- Q2, with high cardinality group by, without non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem group by L_ORDERKEY limit 1;

-- Q3, with low cardinality group by, with non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)), sum(L_LINENUMBER), avg(L_QUANTITY) from lineitem group by L_TAX limit 1;

-- Q4, with high cardinality group by, with non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)), sum(L_LINENUMBER), avg(L_QUANTITY) from lineitem group by L_ORDERKEY limit 1;

-- Q5 without group by, without non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem limit 1;

-- Q6 without group by, with non-distinct agg
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)), sum(L_LINENUMBER), avg(L_QUANTITY) from lineitem limit 1;

-- Q7
select sum(dis_sum), sum(dis_avg) from (
    select sum(distinct(L_LINENUMBER)) as dis_sum , avg(distinct(L_QUANTITY)) as dis_avg from lineitem group by L_TAX
)a

-- Q8
select sum(dis_sum), sum(dis_avg) from (
    select sum(distinct(L_LINENUMBER)) as dis_sum , avg(distinct(L_QUANTITY)) as dis_avg from lineitem group by L_ORDERKEY
)a

-- Q9
select sum(dis_sum), sum(dis_avg) from (
    select sum(distinct(L_ORDERKEY)) as dis_sum , avg(distinct(L_SUPPKEY)) as dis_avg from lineitem group by L_TAX
)a

-- Q10
select sum(dis_sum), sum(dis_avg) from (
    select sum(distinct(L_ORDERKEY)) as dis_sum , avg(distinct(L_SUPPKEY)) as dis_avg from lineitem group by L_ORDERKEY
)a
```

| Query | with cte(withouth limit push down) | without cte |
|:--|:--|:--|
| Q1 | 5.4s | 0.44s |
| Q2 | 17.5s | 0.82s |
| Q3 | 10.0s | 0.45s |
| Q4 | 15.6s | 0.78s |
| Q5 | 4.6s | 0.27s |
| Q6 | 8.8s | 0.31s |
| Q7 | 5.421s | 0.403s |
| Q8 | 18.658s | 3.659s |
| Q9 | 19.580s | 12.149s |
| Q10 | 15.426s | 2.931s |

**So, better to disable cte if multi-distinct-groupby with or without limitation.**

```sql
-- Q11 low cardinality distinct without group by
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem;

-- Q12 high cardinality distinct without group by
select sum(distinct(L_ORDERKEY)), avg(distinct(L_SUPPKEY)) from lineitem;

-- Q13, low cardinality distinct with low distinct group by
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem group by L_TAX;

-- Q14, low cardinality distinct with high distinct group by
select sum(distinct(L_LINENUMBER)), avg(distinct(L_QUANTITY)) from lineitem group by L_ORDERKEY;

-- Q15, high cardinality distinct with low distinct group by
select sum(distinct(L_ORDERKEY)), avg(distinct(L_SUPPKEY)) from lineitem group by L_TAX;

-- Q16, high cardinality distinct with low distinct group by
select sum(distinct(L_ORDERKEY)), avg(distinct(L_SUPPKEY)) from lineitem group by L_ORDERKEY;
```

| Query | with cte | without cte |
|:--|:--|:--|
| Q11 | 4.736s | 0.314s |
| Q12 | 5.746s | 15.055s |
| Q13 | 5.387s | 0.399s |
| Q14 | timeout | timeout |
| Q15 | 21.120s | 22.926s |
| Q16 | timeout | timeout |

**CTE optimization for multi-distinct has bad case when cardinality is low, which is beyond the scope of this pr. And it will be solved in another pr later.**

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 87 / 98 (88.78%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/OperatorStrings.java|82|93|88.17%|[95, 96, 101, 102, 103, 108, 109, 114, 206, 209, 210]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/logical/LogicalTreeAnchor.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/operator/OperatorVisitor.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/OptExpressionVisitor.java|1|1|100.00%|[]|

**Review by Seaven — DISMISSED** [review]
Why move OperatorStrings? It's only used in test

**Comment by liuyehcf** [comment]
> Why move OperatorStrings? It's only used in test

I want to see how logical tree looks like while debugging.

**Comment by Seaven** [comment]
> 



> > Why move OperatorStrings? It's only used in test
> 
> I want to see how logical tree looks like while debugging.

Explain.java is your want?

**Comment by liuyehcf** [comment]
> lain.java is your want



> > 
> 
> > > Why move OperatorStrings? It's only used in test
> > 
> > 
> > I want to see how logical tree looks like while debugging.
> 
> Explain.java is your want?

Yes, indeed, I'll revert my changes

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by packy92** [comment]
Is the test result with limit pushdwon or not ?

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 8 / 8 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|8|8|100.00%|[]|

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java [hunk 1]
```diff
@@ -632,4 +632,36 @@ public void testAllCTEConsumePruned() throws Exception {
...
+                    "     TABLE: t0");
+        }
+        {
+            String sql = "select sum(distinct(v1)), avg(distinct(v2)) from t0 group by v3 limit 1";
+            String plan = getFragmentPlan(sql);
+            assertContains(plan, "  2:Project\n" +
+                    "  |  <slot 4> : 4: sum\n" +
+                    "  |  <slot 5> : CAST(7: multi_distinct_sum AS DOUBLE) / CAST(6: multi_distinct_count AS DOUBLE)\n" +
+                    "  |  \n" +
+                    "  1:AGGREGATE (update finalize)\n" +
```
Comment (kangkaisen) [inline fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java:659]: why no limit?

**Comment by kangkaisen** [comment]
```
So, better to disable cte if multi-distinct with limitation.
```
should be `better to disable cte if multi-distinct with small limit` when limit is large, which means no limit.

File: fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java (hunk 1 above)
Comment (liuyehcf) [reply fe/fe-core/src/test/java/com/starrocks/sql/plan/CTEPlanTest.java:662]: Fixed

**Comment by liuyehcf** [comment]
> Is the test result with limit pushdwon or not ?

cte-without limit pushdown vs. without cte

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 16 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|8|8|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|8|8|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java [hunk 2]
```diff
@@ -147,26 +151,31 @@ public List<OptExpression> transform(OptExpression input, OptimizerContext conte
...
+        List<ColumnRefOperator> groupingKeys = aggregate.getGroupingKeys();
+        boolean hasGroupBy = !groupingKeys.isEmpty();
 
         Map<ColumnRefOperator, ScalarOperator> columnRefMap = Maps.newHashMap();
         LinkedList<OptExpression> allCteConsumes = buildDistinctAggCTEConsume(aggregate, distinctAggList, cteProduce,
                 columnRefFactory, columnRefMap);
+        // For inner join(with group by), distinct aggregate cannot have limitation
+        if (hasGroupBy) {
+            allCteConsumes.forEach(opt -> opt.getOp().setLimit(Operator.DEFAULT_LIMIT));
+        }
```
Comment (packy92) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java:163]: check method ensures no limit in agg. can we delete this line?

Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java:163]: I think better to remain. This can avoid making wrong output if cte reused again later, though this code not works yet.

**Review by packy92 — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java [hunk 3]
```diff
@@ -124,6 +124,10 @@ public boolean check(OptExpression input, OptimizerContext context) {
             return false;
         }
 
+        if (agg.getLimit() >= 0) {
```
Comment (Seaven) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java:127]: don't check none-groupby + limit?

Comment (liuyehcf) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java:127]: in the case of non-groupby, non-cte is faster than cte according to the test results.

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 14 / 14 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctByCTERule.java|6|6|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/RewriteMultiDistinctRule.java|8|8|100.00%|[]|

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by Seaven — DISMISSED** [review]

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Review by kangkaisen — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

**Comment by liuyehcf** [comment]
run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]

**Comment by liuyehcf** [comment]
branch 2.2/2.3/2.4 do not have this problem

**Comment by Seaven** [comment]
@mergify backport branch-2.4
