### PR TITLE
Fix SinkBuffer block problem

### LINKED ISSUE #5222: Be block
### Steps to reproduce the behavior (Required)

* set `pipeline_sink_brpc_dop=1` of `be.conf`
* more than 1 be

Any sql with sort can reproduce this problem, and for simplity, we take TPC-H for example 

```sql
select * from lineitem order by L_ORDERKEY limit 5;
```

### Expected behavior (Required)

return answer

### Real behavior (Required)

block

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 74b31752a |
+-------------------+
```

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5222

## Problem Summary(Required) ：

When `pipeline_sink_brpc_dop` is set to 1, considering the following codes.

* `_request_seqs[instance_id.lo]` is 0, which is init value
* `_max_continuous_acked_seqs[instance_id.lo]` is -1, which is init value
*  so `discontinuous_acked_window_size` is `0 - (-1) = 1`
* `too_much_brpc_process` turns out to be true even we didn't send any packet, then block occurred

```c++
        if (_is_dest_merge) {
            // discontinuous_acked_window_size means that we are not received all the ack
            // with sequence from _max_continuous_acked_seqs[x] to _request_seqs[x]
            // Limit the size of the window to avoid buffering too much out-of-order data at the receiving side
            int64_t discontinuous_acked_window_size =
                    _request_seqs[instance_id.lo] - _max_continuous_acked_seqs[instance_id.lo];
            too_much_brpc_process = discontinuous_acked_window_size >= config::pipeline_sink_brpc_dop;
        }
```

### CODE REVIEW

File: be/test/exprs/vectorized/math_functions_test.cpp [hunk 1]
```diff
@@ -217,21 +217,35 @@ static void testRoundDecimal(const std::vector<std::string>& arg0_values, const
     } else if (c0_const && c1_const) {
         ASSERT_TRUE(res_column->is_constant());
         res_const = true;
-        decimal_res_column =
-                ColumnHelper::cast_to<TYPE_DECIMAL128>(FunctionHelper::get_data_column_of_const(res_column)).get();
+        auto maybe_nullable_res_column = FunctionHelper::get_data_column_of_const(res_column);
```
Comment (mofeiatwork) [inline be/test/exprs/vectorized/math_functions_test.cpp:220]: Has relationship with this PR?

Comment (liuyehcf) [reply be/test/exprs/vectorized/math_functions_test.cpp:220]: No relation. Just add some tests for decimal truncate/round (don't want to open another pr 😵)

Comment (trueeyu) [reply be/test/exprs/vectorized/math_functions_test.cpp:220]: better to create one new PR

**Review by murphyatwork — DISMISSED** [review]

File: be/test/exprs/vectorized/math_functions_test.cpp (hunk 1 above)
Comment (liuyehcf) [reply be/test/exprs/vectorized/math_functions_test.cpp:220]: ok, I'll move tests to another pr

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Review by kangkaisen — DISMISSED** [review]

File: be/src/exec/pipeline/exchange/sink_buffer.cpp [hunk 2]
```diff
@@ -265,7 +264,7 @@ void SinkBuffer::_try_to_send_rpc(const TUniqueId& instance_id) {
         }
 
         *request.params->mutable_finst_id() = _instance_id2finst_id[instance_id.lo];
-        request.params->set_sequence(_request_seqs[instance_id.lo]++);
```
Comment (stdpain) [inline be/src/exec/pipeline/exchange/sink_buffer.cpp:268]: we would better add some comment for `_try_to_send_rpc`. Because we need to get the mutex before calling this function, otherwise we will get a concurrency problem.

Comment (liuyehcf) [reply be/src/exec/pipeline/exchange/sink_buffer.cpp:268]: Ok, I'll add comments

**Review by satanson — DISMISSED** [review]

**Review by satanson — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

File: be/src/exec/pipeline/exchange/sink_buffer.cpp [hunk 3]
```diff
@@ -192,7 +189,10 @@ void SinkBuffer::_process_send_window(const TUniqueId& instance_id, const int64_
     }
 }
 
-void SinkBuffer::_try_to_send_rpc(const TUniqueId& instance_id) {
+void SinkBuffer::_try_to_send_rpc(const TUniqueId& instance_id, std::function<void()> pre_works) {
```
Comment (stdpain) [inline be/src/exec/pipeline/exchange/sink_buffer.cpp:192]: It's better to use lambda expression  instead of std::function

Comment (liuyehcf) [reply be/src/exec/pipeline/exchange/sink_buffer.cpp:192]: I have tried to replace `std::function` with lambda, and I failed because there will be a problem with recursive initialization of template parameters

**Review by kangkaisen — APPROVED** [review]

**Comment by liuyehcf** [comment]
run starrocks_clang-format

**Comment by liuyehcf** [comment]
@Mergifyio backport branch-2.2
