### PR TITLE
Fix wrong plain encoder of boolean column for parquet

### LINKED ISSUE #3073: Query error from iceberg external table after iceberg table insert and update
### Steps to reproduce the behavior (Required)
1. create iceberg table and insert data:
```
create table hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh(
col_boolean boolean,
col_int int,
col_long long,
col_float float,
col_double double,
col_decimal decimal(38,18),
col_date date,
col_timestamp timestamp,
col_string string,
col_binary binary,
col_struct struct<a:string,b:int>,
col_map map<string,int>
) USING iceberg 
PARTITIONED BY (col_date)
TBLPROPERTIES('write.format.default'='parquet','write.parquet.compression-codec'='snappy');
insert into hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh select true,1,1.01,1.001,1.0001,10000000000.0000000001,cast('2020-01-01' as date),cast('2020-01-01 00:00:01' as timestamp),'Top 10 Unsolved Mysteries of Paleontological Dinosaurs, Did You Know?',cast('1110001010101011001001' as binary),null,null;
insert into hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh select false,2,2.02,2.002,2.0002,20000000000.0000000002,cast('2020-02-01' as date),cast('2020-02-01 00:00:02' as timestamp),'Xi Jinping, general secretary of the Communist Party of China Central Committee, called on Tuesday for unrelenting efforts in exercising full and rigorous governance over the Party, saying that the CPC will continue to show zero tolerance for corruption.',cast('1110001010101011001001' as binary),null,null;
```

2. create iceberg external table:
```
create external table ex_iceberg_parquet_refresh (
col_int int,
col_date date,
col_string varchar(200),
col_boolean boolean,
col_float float,
col_double double,
col_long bigint,
col_decimal decimal(38,18))
ENGINE=iceberg
properties (
"resource" = "iceberg_emr_tn",
"table" = "iceberg_par_parquet_snappy_refresh",
"database" = "iceberg_db");
```

3. iceberg table insert into select and update:
```
insert into hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh select * from hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh;
update hive_prod.iceberg_db.iceberg_par_parquet_snappy_refresh set col_string = 'update data';
```

4. select from iceberg external table:
```
mysql> select * from ex_iceberg_parquet_refresh;
ERROR 1064 (HY000): going to read out-of-bounds data, offset=0,count=2,size=1
```

### Expected behavior (Required)
return the right result

### Real behavior (Required)
query error

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| QA_TEST_MASTER d4a0de6 |
+------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by DorianZheng**
Signed-off-by: dorianzheng <xingzhengde72@gmail.com>

## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/3073

## Problem Summary(Required) ：

plain encoding for boolean type is stored as `Bit Packed`, `LSB` first format
more details refer to: https://github.com/apache/parquet-format/blob/master/Encodings.md#PLAIN

### CODE REVIEW

**Review by dirtysalt — DISMISSED** [review]

**Comment by DorianZheng** [comment]
https://sourcegraph.com/github.com/apache/parquet-mr@300200eb72b9f16df36d9a68cf762683234aeb08/-/blob/parquet-column/src/main/java/org/apache/parquet/column/values/plain/BooleanPlainValuesReader.java

File: be/src/exec/parquet/encoding_plain.h [hunk 1]
```diff
@@ -164,6 +191,43 @@ class PlainDecoder<Slice> final : public Decoder {
     size_t _offset = 0;
 };
 
+// plain encoding for boolean type is stored as `Bit Packed`, `LSB` first format
+// more details refer to: https://github.com/apache/parquet-format/blob/master/Encodings.md#PLAIN
+template <>
+class PlainDecoder<bool> final : public Decoder {
```
Comment (caneGuy) [inline be/src/exec/parquet/encoding_plain.h:197]: LGTM since "Run Length Encoding / Bit-Packing Hybrid (RLE = 3)" is not widely used now.
so we do not need to consider this encoding here

File: be/src/exec/parquet/encoding_plain.h [hunk 2]
```diff
@@ -164,6 +191,43 @@ class PlainDecoder<Slice> final : public Decoder {
...
+
+    Status set_data(const Slice& data) override {
+        _batched_bit_reader.reset(reinterpret_cast<const uint8_t*>(data.data), data.size);
+        return Status::OK();
+    }
+
+    Status next_batch(size_t count, ColumnContentType content_type, vectorized::Column* dst) override {
+        dst->resize(count);
+        auto num_unpacked_values =
+                _batched_bit_reader.unpack_batch(kBooleanBitPackedBitWidth, count, dst->mutable_raw_data());
```
Comment (caneGuy) [inline be/src/exec/parquet/encoding_plain.h:210]: will this call cause data loss?

**Comment by DorianZheng** [comment]
https://github.com/apache/impala/blob/b28da054f3595bb92873433211438306fc22fbc7/be/src/exec/parquet/parquet-bool-decoder.h

**Comment by DorianZheng** [comment]
run starrocks_be_unittest

**Comment by caneGuy** [comment]
LGTM

**Review by caneGuy — DISMISSED** [review]

**Review by dirtysalt — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

File: be/src/exec/parquet/encoding_plain.h [hunk 3]
```diff
@@ -53,6 +56,30 @@ class PlainEncoder<Slice> final : public Encoder {
     faststring _buffer;
 };
 
+template <>
+class PlainEncoder<bool> final : public Encoder {
```
Comment (chaoyli) [inline be/src/exec/parquet/encoding_plain.h:60]: Does the problem is boolean type in parquet, StarRocks do not support it?
I can not get the point from the title and commit message.
