### PR TITLE
[Enhancement] Check user identity for `show grants` & support string literal role name for `create role` and `drop role`

### LINKED ISSUE #5389: incomplete support for role management
Currently starrocks's role management has some obvious bugs or bad designs.

### Steps to reproduce the behavior (Required)
1. CREATE ROLE 'somerole'
2. DROP ROLE 'somerole'
3. SHOW GRANTS FOR 'somerole'

### Expected behavior (Required)
1. Create role successfully.
2. Drop role successfully.
3. Report an error with message suggesting user does not exist.

### Real behavior (Required)
1. Create failed, role name must come without quote.
```sql
mysql> create role 'somerole';
ERROR 1064 (HY000): Syntax error in line 1:
create role 'somerole'
            ^
Encountered: STRING LITERAL
Expected: IDENTIFIER

mysql> create role somerole;
Query OK, 0 rows affected (0.03 sec)
```
2. Drop failed, role name must come without quote.
```
mysql> drop role 'somerole';
ERROR 1064 (HY000): Syntax error in line 1:
drop role 'somerole'
          ^
Encountered: STRING LITERAL
Expected: IDENTIFIER

mysql> drop role somerole;
Query OK, 0 rows affected (0.01 sec)
```
3. Report no error yet show an empty table.
```
mysql> show grants for 'somerole';
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
| UserIdentity                   | Password | AuthPlugin | UserForAuthPlugin | GlobalPrivs | DatabasePrivs | TablePrivs | ResourcePrivs |
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
| 'default_cluster:somerole'@'%' | NULL     | NULL       | NULL              | NULL        | NULL          | NULL       | NULL          |
+--------------------------------+----------+------------+-------------------+-------------+---------------+------------+---------------+
1 row in set (0.00 sec)
```

### StarRocks version (Required)
main

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #5389

## Problem Summary(Required) ：

1. So far, using `show grants` for a non-existent user will show a table with all cells 'null'. Fix it by raising an exception in this scenario.
2. Allow usage of `create role 'role_name'` by changing role CUP type from ident to ident_or_text.

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/analysis/ShowGrantsStmtTest.java [hunk 1]
```diff
@@ -0,0 +1,113 @@
+// This file is made available under Elastic License 2.0.
```
Comment (imay) [inline fe/fe-core/src/test/java/com/starrocks/analysis/ShowGrantsStmtTest.java:1]: new files should use the following license header.
```
// This file is licensed under the Elastic License 2.0. Copyright 2021-present, StarRocks Limited.
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 2 / 2 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/analysis/ShowGrantsStmt.java|2|2|100.00%|

**Review by imay — APPROVED** [review]
LGTM

**Review by chaoyli — APPROVED** [review]
