### PR TITLE
Fix: bitmap_count(null) returns 0 instead of null

### LINKED ISSUE #3247: Query result error
### Steps to reproduce the behavior (Required)
1. DROP DATABASE IF EXISTS g0;
CREATE DATABASE g0;
USE g0;
admin set frontend config ("enable_decimal_v3" = "true");
CREATE TABLE IF NOT EXISTS t0 (c_0_0 CHAR(41) NOT NULL ,c_0_1 DATETIME NOT NULL ,c_0_2 LARGEINT NULL ,c_0_3 DECIMAL(28, 2)  NULL ,c_0_4 DECIMAL(29, 10)  NULL ,c_0_5 SMALLINT NULL ,c_0_6 DATE NOT NULL ,c_0_7 DOUBLE NOT NULL ,c_0_8 INT NOT NULL ,c_0_9 BIGINT NOT NULL ,c_0_10 DATE NULL ,c_0_11 VARCHAR(11) NOT NULL ) UNIQUE KEY (c_0_0,c_0_1,c_0_2) DISTRIBUTED BY HASH (c_0_0) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t1 (c_1_0 CHAR(11) NOT NULL ,c_1_1 DATE NULL ,c_1_2 DATETIME NOT NULL ,c_1_3 DATETIME NULL ,c_1_4 DATE NULL ,c_1_5 DATE NOT NULL ,c_1_6 DATETIME NULL ,c_1_7 DATETIME NOT NULL ,c_1_8 LARGEINT SUM NULL ,c_1_9 HLL HLL_UNION NULL ) AGGREGATE KEY (c_1_0,c_1_1,c_1_2,c_1_3,c_1_4,c_1_5,c_1_6,c_1_7) DISTRIBUTED BY HASH (c_1_4,c_1_6,c_1_3,c_1_7,c_1_1) properties("replication_num"="3") ;
CREATE TABLE IF NOT EXISTS t2 (c_2_0 BOOLEAN NULL ,c_2_1 BOOLEAN NOT NULL ,c_2_2 DECIMAL(23, 9)  NOT NULL ,c_2_3 BIGINT NULL ,c_2_4 DATE NULL ,c_2_5 VARCHAR(11) NOT NULL ,c_2_6 LARGEINT NULL ,c_2_7 DECIMAL(7, 3)  MIN NULL ,c_2_8 BOOLEAN REPLACE NULL ,c_2_9 DOUBLE REPLACE_IF_NOT_NULL NOT NULL ,c_2_10 HLL HLL_UNION NULL ,c_2_11 HLL HLL_UNION NOT NULL ,c_2_12 FLOAT MAX NOT NULL ) AGGREGATE KEY (c_2_0,c_2_1,c_2_2,c_2_3,c_2_4,c_2_5,c_2_6) DISTRIBUTED BY HASH (c_2_0,c_2_1,c_2_4,c_2_2,c_2_6) properties("replication_num"="3") ;
INSERT INTO t0 VALUES ("", "1970-01-01 08:00:00", -1192052474, 925919433356898524678513.24, 758130157.2263510155, 8, "1970-01-01", 0.6710555766692743, 13, -1739838693, "1970-01-01", "e2gz3SdD");
INSERT INTO t0 VALUES ("X800", "1970-01-01 08:00:00", -349491474, 449771835643989748021454.03, 986018163.3255054939, NULL, "1970-01-01", 0.4113274190495131, 7, -749446286, NULL, "");
INSERT INTO t2 VALUES (true, false, 94247.413241829, -354510635, "1970-01-01", "C0idSj", 572149012, 7.287, false, 0.6665657655050011, hll_hash("GO"), hll_hash("EI4"), 0.3261775726052979), (false, true, 68440.119884518, 275462241, "1970-01-01", "8nq", 277111639, 2.669, false, 0.06682286516837044, hll_hash("f"), hll_hash("a5l"), 0.8685588239591661);
INSERT INTO t2 VALUES (false, false, 24549.229094824, -1902265719, "1970-01-01", "", -261490012, 5.469, false, -1.100799166E9, hll_hash("Sb"), hll_hash("GLlhV7N"), 0.6681021323178268), (true, true, 65036.054511351, 420154344, "1970-01-01", "", NULL, 1.485, false, 0.12117700995157443, hll_hash(""), hll_hash("LTxaIyuWE"), 0.43085108278984463);
INSERT INTO t2 VALUES (true, false, 24791.098135884, NULL, "1970-01-01", "", -542477973, 5.291, true, 0.1465146010168472, hll_hash("D0GP"), hll_hash(""), 0.19703321730850665);
INSERT INTO t1 VALUES ("s", "1970-01-01", "1970-01-01 08:00:00", NULL, "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", 809384906, hll_hash("AKrWi")), ("X", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", 2103121518, hll_hash("mpd"));
INSERT INTO t2 VALUES (true, true, 48267.768140856, 1665650822, "1970-01-01", "", 1242206771, 7.457, false, -1.122587773E9, hll_hash("1K"), hll_hash("E35A"), 0.07852733699578607);
INSERT INTO t0 VALUES ("d", "1970-01-01 08:00:00", -1744835077, 583791988196473932148933.27, 564822011.4332145102, NULL, "1970-01-01", 0.8025813402299016, 4, 1437056382, "1970-01-01", ""), ("L", "1970-01-01 08:00:00", -179379605, 432477871796739909981965.92, 970846460.8581972884, NULL, "1970-01-01", 0.8100937453491575, 21, -174811394, "1970-01-01", "");
INSERT INTO t2 VALUES (NULL, false, 5389.299944250, 1082867998, "1970-01-01", "", -550357317, 4.439, true, 0.050524806664801414, hll_hash("2t"), hll_hash("7kljvIEKk"), 0.7924291155734305), (false, true, 82333.432522725, -121929976, "1970-01-01", "Kpzu", -1432139767, 8.591, NULL, 0.14713565551829688, hll_hash("S9a"), hll_hash("fsC8"), 0.5778472211980579);
INSERT INTO t1 VALUES ("", NULL, "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", 1180907591, hll_hash("XPF00"));
TRUNCATE TABLE t0;
INSERT INTO t2 VALUES (true, true, 25350.268134152, 1380780168, NULL, "Q", NULL, 2.762, NULL, 0.24789921849025331, hll_hash("eK"), hll_hash("T"), 0.15685307027509265), (true, true, 62458.496828428, 1739578444, "1970-01-01", "6", 1598730142, 9.906, NULL, 0.09222632472316428, hll_hash("VzT7dj0G5"), hll_hash("2fuyXMxOW"), 1.200674878E9), (NULL, true, 52379.904469395, 1705116318, NULL, "z", -1599665631, 8.369, NULL, 0.08058998525310523, hll_hash("M"), hll_hash("j"), 0.623768213821309);
DELETE FROM t0 WHERE c_0_1="1969-12-27 04:43:29" AND c_0_2=72544935;
INSERT INTO t2 VALUES (false, true, 57972.557231010, 1661753400, "1970-01-01", "uyp", NULL, 8.642, false, 0.13839846653167276, hll_hash("sM35"), hll_hash(""), 0.04032431010663773), (false, false, 71835.919955928, -9223372036854775808, "1970-01-01", "z90R", 1692127326, 7.047, true, 0.8383903517205931, hll_hash(""), hll_hash("C"), 0.433239454163877), (true, false, 16870.749540571, -1477277137, NULL, "", -1953894900, 0.684, false, NULL, hll_hash(""), hll_hash("H"), 0.38420277360743205);
INSERT INTO t2 VALUES (false, false, 70170.660318682, 443494045, "1970-01-01", "", -1192052474, 3.904, true, 0.3790319537241599, hll_hash("92vQ"), hll_hash(""), 0.9732411452874585), (true, true, 62057.210873643, -240868039, "1970-01-01", "T", -1693880208, 2.303, false, 0.8710489414959178, hll_hash("W"), hll_hash("0T"), 0.2670505088426153), (false, false, 15992.735510838, -681491961, "1970-01-01", "", -1747392956, 9.459, false, -2.084171034E9, hll_hash("AN"), hll_hash("Zx"), 0.35271126729159263);
INSERT INTO t1 VALUES ("js", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", 871048462, hll_hash("tcR8nNC")), ("9", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", -678450987, hll_hash("")), ("", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", -736053051, hll_hash("lebJK"));
INSERT INTO t0 VALUES ("N9", "1970-01-01 08:00:00", 1533937106, 142998769258282587557573.64, 432248034.6920503299, 15, "1970-01-01", 0.6325466926194969, 18, -1192052474, "1970-01-01", "tLNtPlEc"), ("", "1970-01-01 08:00:00", 143085409, 284796128848855184983790.42, 380642322.8467869263, 12, "1970-01-01", 0.37707792888196157, 28, -9223372036854775808, "1970-01-01", "29z");
INSERT INTO t1 VALUES ("sV", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", NULL, "1970-01-01 08:00:00", 277111639, hll_hash("TWA")), ("l", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", -652396129, hll_hash("")), ("El7pqXM", "1970-01-01", "1970-01-01 08:00:00", NULL, "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", -967441919, hll_hash("Knlot"));
INSERT INTO t1 VALUES ("K", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", "1970-01-01", "1970-01-01", "1970-01-01 08:00:00", "1970-01-01 08:00:00", 897414914, hll_hash("W"));
INSERT INTO t0 VALUES ("N", "1970-01-01 08:00:00", -367565372, NULL, 379509373.2665489092, NULL, "1970-01-01", -1.122587773E9, 4, 1751530727, "1970-01-01", "c"), ("2l", "1970-01-01 08:00:00", 32711386, 393727754659510820189893.85, 957040248.1103308787, 1, "1970-01-01", 0.4530215895207784, 2, 213760671, "1970-01-01", "eCcsD"), ("LilofTlYo", "1970-01-01 08:00:00", -1337205585, 525562814361000052443273.56, 484034170.6585306449, 3, "1970-01-01", 0.797108999731679, 13, 1368754050, "1970-01-01", "P"), ("8", "1970-01-01 08:00:00", 1724933363, 488373459236534879224223.00, 994912244.4472903118, 13, "1970-01-01", -1.192052474E9, 29, 718166292, "1970-01-01", "");
-- SELECT subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8, t0.c_0_9, t0.c_0_10, t0.c_0_11 FROM t0 ORDER BY t0.c_0_7, t0.c_0_1) subt0 FULL JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_12 FROM t2 WHERE false) subt2 ON subt0.c_0_10 = subt2.c_2_0 AND subt0.c_0_10 >= subt2.c_2_0 AND subt0.c_0_6 != subt2.c_2_2 AND DAYS_ADD("1970-01-08 00:46:02", 1764293942)  < 81179.807425927 GROUP BY subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0;
-- cardinality: 6
-- SELECT subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8, t0.c_0_9, t0.c_0_10, t0.c_0_11 FROM t0 ORDER BY t0.c_0_7, t0.c_0_1) subt0 FULL OUTER JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_12 FROM t2 WHERE false) subt2 ON subt0.c_0_10 = subt2.c_2_0 AND subt0.c_0_10 >= subt2.c_2_0 AND subt0.c_0_6 != subt2.c_2_2 AND DAYS_ADD("1970-01-08 00:46:02", 1764293942)  < 81179.807425927 WHERE CAST(BITMAP_COUNT(CASE  WHEN (subt2.c_2_6) IN (-1100799166)  THEN bitmap_hash("NU71mS1y9")  WHEN (subt2.c_2_8) IN (NULL)  THEN TO_BITMAP(-497787005)  END)  AS BOOLEAN )  GROUP BY subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 UNION SELECT subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8, t0.c_0_9, t0.c_0_10, t0.c_0_11 FROM t0 ORDER BY t0.c_0_7, t0.c_0_1) subt0 FULL OUTER JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_12 FROM t2 WHERE false) subt2 ON subt0.c_0_10 = subt2.c_2_0 AND subt0.c_0_10 >= subt2.c_2_0 AND subt0.c_0_6 != subt2.c_2_2 AND DAYS_ADD("1970-01-08 00:46:02", 1764293942)  < 81179.807425927 WHERE (NOT (CAST(BITMAP_COUNT(CASE  WHEN (subt2.c_2_6) IN (-1100799166)  THEN bitmap_hash("NU71mS1y9")  WHEN (subt2.c_2_8) IN (NULL)  THEN TO_BITMAP(-497787005)  END)  AS BOOLEAN ) )) GROUP BY subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 UNION SELECT subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0 FROM  (SELECT t0.c_0_0, t0.c_0_1, t0.c_0_2, t0.c_0_3, t0.c_0_4, t0.c_0_5, t0.c_0_6, t0.c_0_7, t0.c_0_8, t0.c_0_9, t0.c_0_10, t0.c_0_11 FROM t0 ORDER BY t0.c_0_7, t0.c_0_1) subt0 FULL OUTER JOIN (SELECT t2.c_2_0, t2.c_2_1, t2.c_2_2, t2.c_2_3, t2.c_2_4, t2.c_2_5, t2.c_2_6, t2.c_2_7, t2.c_2_8, t2.c_2_9, t2.c_2_12 FROM t2 WHERE false) subt2 ON subt0.c_0_10 = subt2.c_2_0 AND subt0.c_0_10 >= subt2.c_2_0 AND subt0.c_0_6 != subt2.c_2_2 AND DAYS_ADD("1970-01-08 00:46:02", 1764293942)  < 81179.807425927 WHERE ((CAST(BITMAP_COUNT(CASE  WHEN (subt2.c_2_6) IN (-1100799166)  THEN bitmap_hash("NU71mS1y9")  WHEN (subt2.c_2_8) IN (NULL)  THEN TO_BITMAP(-497787005)  END)  AS BOOLEAN ) ) IS NULL) GROUP BY subt2.c_2_2, subt0.c_0_3, subt2.c_2_1, subt2.c_2_8, subt0.c_0_7, subt0.c_0_0;
-- cardinality: 0

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - branch-2.1 ASAN
 - mysql> select current_version();
+------------------------------+
| current_version()            |
+------------------------------+
| SQLANCER_MASTER_ASAN cee9fdd |
+------------------------------+

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fix #3247.

## Problem Summary：

`BITMAP_COUNT(NULL)` should return `0` not `NULL`, because this function is non-nullable.
However, `ScalarOperatorEvaluator` rewrites the result of function to `NULL`, if the function isn't in `NonNullResultWithNullParamFunctions`, which doesn't consider the function may be non-nullable.

### CODE REVIEW

**Comment by wangruin** [comment]
run starrocks_be_unittest

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java [hunk 1]
```diff
@@ -102,10 +102,12 @@ public ScalarOperator evaluation(CallOperator root) {
         }
 
         // return Null directly iff:
-        // 1. Not UDF
+        // 1. The function is nullable
         // 2. Not in NonNullResultWithNullParamFunctions
         // 3. Has null parameter
-        if (!Catalog.getCurrentCatalog().isNonNullResultWithNullParamFunction(fn.getFunctionName().getFunction())
```
Comment (HangyuanLiu) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java:108]: Why not add this function to isNonNullResultWithNullParamFunction? The judgment here seems to be designed to be controlled according to this variable

**Review by Seaven — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java (hunk 1 above)
Comment (ZiheLiu) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ScalarOperatorEvaluator.java]: OK.

**Review by kangkaisen — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java [hunk 2]
```diff
@@ -172,7 +172,7 @@
     private final Map<String, List<Function>> vectorizedFunctions;
     // This does not contain any user defined functions. All UDFs handle null values by themselves.
     private final ImmutableSet<String> nonNullResultWithNullParamFunctions = ImmutableSet.of("if", "hll_hash",
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java:174]: should merge this set to `alwaysReturnNonNullableFunctions`

**Review by kangkaisen — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java (hunk 2 above)
Comment (ZiheLiu) [reply fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java]: The function `"if", "concat_ws", "ifnull", "nullif", "null_or_empty", "coalesce"` don't always return non-nullable result, while `hll_hash`, `bitmap_count`, and `md5sum` return non-nullable result.
Therefore, I rename `nonNullResultWithNullParamFunctions` to `nonNullResultWithNullParamNullFunctions`, remove `hll_hash`, `bitmap_count`, and `md5sum` from `nonNullResultWithNullParamNullFunctions`, and modify `isNonNullResultWithNullParamFunctions()` as follows:
```C++
    public boolean isNonNullResultWithNullParamFunctions(String funcName) {
        return nonNullResultWithNullParamNullFunctions.contains(funcName)
                || alwaysReturnNonNullableFunctions.contains(funcName);
    }
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java [hunk 3]
```diff
@@ -170,9 +171,10 @@
      * to row function when init.
      */
     private final Map<String, List<Function>> vectorizedFunctions;
+    // This contains the nullable functions, which cannot return NULL result directly for the NULL parameter.
     // This does not contain any user defined functions. All UDFs handle null values by themselves.
-    private final ImmutableSet<String> nonNullResultWithNullParamFunctions = ImmutableSet.of("if", "hll_hash",
-            "concat_ws", "ifnull", "nullif", "null_or_empty", "coalesce", "md5sum");
+    private final ImmutableSet<String> nonNullResultWithNullParamNullFunctions = ImmutableSet.of("if",
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java:176]: NotAlwaysNullResultWithNullParamFunctions ?

File: fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java [hunk 4]
```diff
@@ -285,7 +288,8 @@ public void init() {
     }
 
     public boolean isNonNullResultWithNullParamFunctions(String funcName) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/FunctionSet.java:290]: isNotAlwaysNullResultWithNullParamFunction？

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Comment by ZiheLiu** [comment]
run starrocks_fe_unittest

**Comment by ZiheLiu** [comment]
run run starrocks_fe_unittest

**Review by HangyuanLiu — APPROVED** [review]
