### PR TITLE
[BugFix] Fix bug of BrokerDesc can not restore from metadb

### LINKED ISSUE #59730: [BUG] BrokerLoad Job can not restore from new leader when the old leader crash
### Steps to reproduce the behavior (Required)
1. create BrokerLoad Job and run it 
2. make the leader node crash
3. watch the brokerload job state is or not restored from new leader

### Expected behavior (Required)
1. the brokerload job can restore from the meta and run successful

### Real behavior (Required)
1. the brokerLoad job crash

Image

Image

### StarRocks version (Required)
 - Starrocks 3.3.11

### PR DESCRIPTION
**Pull request by Yao-MR**
## Why I'm doing:
To make the field hasBroker in BrokerLoadJob to be Serialized

## What I'm doing:
To make the field hasBroker can restore from metadb

Fixes #59730

[BUG] BrokerLoad Job can not restore from new leader when the old leader crash #59730

## What type of PR is this:

- [X] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [X] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [X] I have added test cases for my bug fix or my new feature
- [] This pr needs user documentation (for new or modified features or behaviors)
  - [] I have added documentation for my new feature or new function
- [] This is a backport pr

## Bugfix cherry-pick branch check:
- [X] I have checked the version labels which the pr will be auto-backported to the target branch
  - [X] 3.5
  - [X] 3.4
  - [X] 3.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java [hunk 1]
```diff
@@ -43,6 +43,7 @@ public class BrokerDesc implements ParseNode, Writable {
     private String name;
     @SerializedName("p")
     private Map<String, String> properties;
+    @SerializedName("h")
     private boolean hasBroker;
```
Comment (alvin-phoenix-ai) [inline fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java]: I'm wondering if the bug can be fixed by implementing hasBroker() with `!Strings.isNullOrEmpty(name)`.
In this way, we can remove the hasBroker member.

Comment (Yao-MR) [reply fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java]: maybe, just to serialize the value and make the same pattern with other field, and the code will be easy to read

Comment (alvin-phoenix-ai) [reply fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java]: `hasBroker` is redundant, let's remove it.

Comment (Yao-MR) [reply fe/fe-core/src/main/java/com/starrocks/analysis/BrokerDesc.java]: > `hasBroker` is redundant, let's remove it.

done,just add the logic to judge the broker is available rather than serialize the value

**Review by alvin-phoenix-ai — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

**Comment by alvin-phoenix-ai** [comment]
@Yao-MR you need to sign the CLA could you sign it?

**Comment by Yao-MR** [comment]
> @Yao-MR you need to sign the CLA could you sign it?

sure, can you give some reference doc

**Comment by Yao-MR** [comment]
> @Yao-MR you need to sign the CLA could you sign it?

done

**Comment by alvin-phoenix-ai** [comment]
@mergify rebase
