### PR TITLE
[Enhancement] Added a message that spark load does not support automatic partitioning

### LINKED ISSUE #19565: [load auto create part] spark load failed
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
```
create database auto_set_bucket_b1532466_c313_11ed_a8a9_00163e0e550b
use auto_set_bucket_b1532466_c313_11ed_a8a9_00163e0e550b
CREATE EXTERNAL RESOURCE "test_spark_resource_b15665e0_c313_11ed_a8a9_00163e0e550b" PROPERTIES ("type" = "spark","spark.master" = "yarn","spark.submit.deployMode" = "cluster","spark.hadoop.yarn.resourcemanager.address" = "xxx.xxx.xxx.xxx:8032","spark.hadoop.fs.defaultFS" = "hdfs://xxx.xxx.xxx.xxx:9000","working_dir" = "hdfs://xxx.xxx.xxx.xxx:9000/tmp/starrocks","broker" = "hdfs_broker")
CREATE TABLE `aggregate_table_with_null` (`k1` date,`k2` datetime, `k3` char(20),`k4` varchar(20),`k5` boolean,`v1` bigint sum,`v2` bigint sum,`v3` bigint sum, `v4` bigint max,`v5` largeint max,`v6` float min,`v7` double min,`v8` decimal(27,9) sum)  AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`) COMMENT "OLAP" PARTITION BY date_trunc('year', k1) DISTRIBUTED BY HASH(`k1`, `k2`, `k3`, `k4`, `k5`) PROPERTIES ( "replication_num" = "3", "storage_format" = "v2")
LOAD LABEL auto_set_bucket_b1532466_c313_11ed_a8a9_00163e0e550b.load_b156f028_c313_11ed_a8a9_00163e0e550b (DATA INFILE("hdfs://xxx.xxx.xxx.xxx:9000/starrocks_test_data/system_data/hdfs_data/nose-ut-data/data") INTO TABLE `aggregate_table_with_null` (k1,k2,k3,k4,k5,v1,v2,v3,v4,v5,v6,v7,v8) ) WITH RESOURCE test_spark_resource_b15665e0_c313_11ed_a8a9_00163e0e550b  PROPERTIES("timeout"="300","max_filter_ratio"="0.5")
```
image

### Expected behavior (Required)
load successfuly
### Real behavior (Required)
load failed
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-3.0-RELEASE cbc57d0 |
+----------------------------+
1 row in set (0.01 sec)

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #19565

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Review by ABingHuang — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/LoadStmtAnalyzer.java [hunk 1]
```diff
@@ -127,6 +131,25 @@ private void analyzeDataDescriptions(LoadStmt statement) {
...
 
+                String database = ConnectContext.get().getDatabase();
+                if (etlJobType == EtlJobType.SPARK && database != null) {
+                    for (DataDescription dataDescription : dataDescriptions) {
+                        String tableName = dataDescription.getTableName();
+                        Database db = GlobalStateMgr.getCurrentState().getDb(database);
+                        if (db == null) {
+                            continue;
+                        }
+                        Table table = db.getTable(tableName);
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/LoadStmtAnalyzer.java:142]: lock

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/LoadStmtAnalyzer.java [hunk 2]
```diff
@@ -127,6 +131,25 @@ private void analyzeDataDescriptions(LoadStmt statement) {
...
+                        if (table instanceof OlapTable) {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/LoadStmtAnalyzer.java:143]: if (table.isNativeTable()) {

**Review by gengjun-git — DISMISSED** [review]

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
