### PR TITLE
[BugFix] fix pk lake table key range scan

### LINKED ISSUE #18386: [StarOS] result error after broker load with op into primary table
### Steps to reproduce the behavior (Required)
````sql
CREATE TABLE primary_20cols_3rep
(k0 TINYINT NOT NULL, k1 DATE NOT NULL, k2 INT NOT NULL, k3 DATETIME NOT NULL, k4 BIGINT NOT NULL, v0 LARGEINT NULL,
v1 BOOLEAN NULL, v2 SMALLINT NULL, v3 VARCHAR(21) NULL, v4 STRING NULL, v5 DECIMAL(18,4) NULL,
v6 STRING NULL, v7 CHAR(126) NULL, v8 INT NULL, v9 DECIMAL(4,2) NULL, v10 DATETIME NULL, v11 DATETIME NULL, v12 STRING NULL,
v13 CHAR(40) NULL, v14 VARCHAR(165) NULL)
PRIMARY KEY(k0,k1,k2,k3,k4)
DISTRIBUTED BY HASH(k0,k1,k2,k3,k4) BUCKETS 5 PROPERTIES ("replication_num" = "3");

LOAD LABEL tn_test.broker_load_bb85c9ca_b355_11ed_8f95_00163e0e550b (DATA INFILE( "hdfs://172.26.194.238:9000/starrocks_test_data/system_data/hdfs_data/primary_test_parquet/primary_20cols_3rep_parquet_0/000000_0") INTO TABLE `primary_20cols_3rep` FORMAT AS "parquet" (k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10) SET (k0=k0,k1=k1,k2=k2,k3=k3,k4=k4,__op=v10) )  WITH BROKER hdfs_broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="259200");
select count(*) from primary_20cols_3rep;
select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;

LOAD LABEL tn_test.broker_load_be831f92_b355_11ed_8f95_00163e0e550b (DATA INFILE( "hdfs://172.26.194.238:9000/starrocks_test_data/system_data/hdfs_data/primary_test_parquet/primary_20cols_3rep_parquet_0/000001_0") INTO TABLE `primary_20cols_3rep` FORMAT AS "parquet" (k0,k1,k2,k3,k4,k5,k6,k7,k8,k9,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10) SET (k0=k0,k1=k1,k2=k2,k3=k3,k4=k4,__op=v10) )  WITH BROKER hdfs_broker ("username"="sr","password"="sr@test") PROPERTIES("timeout"="259200");

select count(*) from primary_20cols_3rep;
select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;
````

### Expected behavior (Required)
olap table in main:
```
mysql> select count(*) from primary_20cols_3rep;
+----------+
| count(*) |
+----------+
|   345578 |
+----------+
1 row in set (0.03 sec)

mysql> select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14';
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.02 sec)
```

### Real behavior (Required)
lake table in StarOS:
```
mysql> select count(*) from primary_20cols_3rep;
+----------+
| count(*) |
+----------+
|   345578 |
+----------+
1 row in set (0.02 sec)

mysql> select count(*) from primary_20cols_3rep where k0=-7 and k1='1999-07-14' and k2=1007088263 and k3='1975-11-25 08:23:14' and k4=6698990814679959142;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.02 sec)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 800b5477f |
+-------------------+
1 row in set (0.00 sec)
```

### PR DESCRIPTION
**Pull request by luohaha**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18386

## Problem Summary(Required) ：
In primary lake table, scan table by key range will return error result. This bug happen when compaction happen, build incorrect ordinal index, which key in ordinal index isn't in order. So when we use key to range scan table, error ordinal index will lead to error result.

The error ordinal index is generated because the rowsets been compacted isn't in order.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/storage/lake/horizontal_compaction_task.cpp [hunk 1]
```diff
@@ -58,6 +58,9 @@ Status HorizontalCompactionTask::execute(Stats* stats) {
     reader_params.chunk_size = chunk_size;
     reader_params.profile = nullptr;
     reader_params.use_page_cache = false;
+    if (keys_type == PRIMARY_KEYS) {
+        reader_params.sorted_by_keys_per_tablet = true;
```
Comment (sduzh) [inline be/src/storage/lake/horizontal_compaction_task.cpp:62]: Try to handle primary key and duplicate key in the same way at the same place:
https://github.com/StarRocks/starrocks/blob/af7d5632703ef2887dc6114b359112fa20a4152b/be/src/storage/lake/tablet_reader.cpp#L250

Comment (luohaha) [reply be/src/storage/lake/horizontal_compaction_task.cpp]: Done

**Review by decster — DISMISSED** [review]

**Review by sduzh — DISMISSED** [review]

**Review by decster — APPROVED** [review]

**Review by sduzh — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by luohaha** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
