### PR TITLE
[BugFix] Fix mv partition prune failed when partition column predicate with function

### LINKED ISSUE #46785: mv partition prune failed when partition column predicate with function
`DATE_FORMAT(pt,'%Y%m%d') BETWEEN '20230307' AND '20230307';`  mv partition prune failed 

  `id` int(11) NULL COMMENT "id",
  `pt` date NOT NULL COMMENT "",
  `gmv` int(11) NULL COMMENT "gmv"
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT "OLAP"
PARTITION BY date_trunc('day', pt)
DISTRIBUTED BY HASH(`pt`)
PROPERTIES (
"compression" = "LZ4",
"datacache.enable" = "true",
"enable_async_write_back" = "false",
"replication_num" = "1",
"storage_volume" = "builtin_storage_volume"
);

> insert into test_pt values(1,20240309,10);
insert into test_pt values(2,20240308,20);
insert into test_pt values(1,20240307,10);

> CREATE MATERIALIZED VIEW `test_pt_mv` (`pt`, `id`, `sum_gmv`)
COMMENT "MATERIALIZED_VIEW"
PARTITION BY (`pt`)
DISTRIBUTED BY RANDOM
REFRESH ASYNC START("2024-03-08 03:00:00") EVERY(INTERVAL 1 MINUTE)
PROPERTIES (
"replicated_storage" = "true",
"partition_refresh_number" = "1",
"replication_num" = "1",
"datacache.enable" = "true",
"enable_async_write_back" = "false",
"storage_volume" = "builtin_storage_volume",
"warehouse" = "default_warehouse"
)
AS SELECT `test_pt`.`pt`, `test_pt`.`id`, sum(`test_pt`.`gmv`) AS `sum_gmv`
FROM `test`.`test_pt`
GROUP BY `test_pt`.`pt`, `test_pt`.`id`;

>  explain
SELECT sum(gmv)
FROM test_pt a
WHERE DATE_FORMAT(pt,'%Y%m%d') BETWEEN '20230307' AND '20230307';

### Expected behavior (Required)
expected:  partitions=1/3 

> |   0:OlapScanNode                                           |
|      TABLE: test_pt_mv                                     |
|      PREAGGREGATION: ON                                    |
|      PREDICATES: date_format(5: pt, '%Y%m%d') = '20230307' |
|      partitions=1/3                                        |
|      rollup: test_pt_mv
### Real behavior (Required)

partitions=3/3 

### StarRocks version (Required)
 3.3

### PR DESCRIPTION
**Pull request by kaijianding**
## What I'm doing:

Fixes #46785 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java [hunk 1]
```diff
@@ -408,6 +409,8 @@ private static boolean isNeedFurtherPrune(List<Long> candidatePartitions, Logica
                 return (FunctionSet.DATE_TRUNC.equalsIgnoreCase(functionName)
                         || FunctionSet.TIME_SLICE.equalsIgnoreCase(functionName))
                         && !exprPartitionInfo.getIdToRange(true).containsKey(candidatePartitions.get(0));
+            } else if (partitionExpr.size() == 1 && partitionExpr.get(0) instanceof SlotRef) {
+                return !exprPartitionInfo.getIdToRange(true).containsKey(candidatePartitions.get(0));
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java:413]: Can we handle all partition exprs? eg: date_trunc/str2date/cast?

Comment (kaijianding) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java:413]: This pr is to make partition prune behavior consisitent to base table and mv, eg: `date_format` can be used to prune partition to base table, but not to mv.

Currently, it's consistent for base table and mv on these 3 functions: 
1. `date_trunc` can apply partition prune to base table and mv
2. `str2date` can't apply partition prune to base table and mv
3. `cast` can't apply partition prune to base table and mv

We can add partition prune support to `str2date/cast ` in another pr.

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/OptOlapPartitionPruner.java:413]: I got your meaning. So this pr only to optimize partition pruning with `slot ref` partitions.

**Review by LiShuMing — APPROVED** [review]

**Review by packy92 — APPROVED** [review]
