### PR TITLE
Fix predicates pushdown in external tables

### LINKED ISSUE #2811: 1064 - mysql query failed. Err: FUNCTION t6.get_json_string does not exist, Time: 0.208000s
**DESC**:  
    I create mysql outside table data_analysis.ods_mysql_vms_metadata_content  ;the table in mysql is in t6 database.
    run the sql `SELECT  id
          FROM  data_analysis.ods_mysql_vms_metadata_content
          WHERE get_json_string(content, '$.content_column_3') IS NOT NULL`   then get the error msg like title；
  but if i change the sql like this `        SELECT  id
          FROM  data_analysis.ods_mysql_vms_metadata_content
          WHERE get_json_string(content, '$.content_column_3') != NULL`   is run success.

**analyze**：
    the first sql by optimized and `WHERE get_json_string(content, '$.content_column_3') IS NOT NULL` predicate push down in mysql running to return smaller data to starRocks, but mysql not have get_json_string function so it`s running error。however  use 
`WHERE get_json_string(content, '$.content_column_3') != NULL` it`s running in starRocks so it`s surccess.

**result**
    some mysql don`t have function not should predicate push down to mysql。

thanks，my first issue.

### PR DESCRIPTION
**Pull request by silverbullet233**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Fixes #2811

## Problem Summary(Required) ：

Because the external table may not support the functions in StarRocks, we cannot push down all predicates to the external table. 

In this PR, I took a conservative strategy, only pushing down simple binary predicates and partial functions to the external table by introducing a new `PushDownPredicateToExternalTableScanRule`.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+        }
+        if (canPushdown(op)) {
+            pushedPredicates.add(op);
+        } else {
+            reservedPredicates.add(op);
+        }
+    }
+
+    // check whether a predicate can be pushed down as a whole
+    public boolean canPushdown(ScalarOperator op) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java:83]: you could use visitor like IsSimpleStrictPredicateVisitor

Comment (silverbullet233) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java]: > you could use visitor like IsSimpleStrictPredicateVisitor

fixed by using `CanFullyPushDownVisitor ` instead of `canPushdown`, and also enable `IN` predicate push down

**Review by liuyehcf — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+
+    public ScalarOperator getReservePredicate() {
+        return Utils.compoundAnd(reservedPredicates);
+    }
+
+    public void extract(ScalarOperator op) {
+        pushedPredicates.clear();
+        reservedPredicates.clear();
+
+        if (op.getOpType().equals(OperatorType.COMPOUND)) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java:41]: CanFullyPushDownVisitor and here both deal with CompoundPredicate， it's looks like have some problems, if predicate like ((canPush) and (can not Push)) and canPush, it will lose one canPush predicate?

Comment (silverbullet233) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java:41]: > CanFullyPushDownVisitor and here both deal with CompoundPredicate， it's looks like have some problems, if predicate like ((canPush) and (can not Push)) and canPush, it will lose one canPush predicate?

@Youngwb  yes…but before using this rule，all `AND` predicates should have been flattened into a CompoundAndPredicate? This is an important assumption.

Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java:41]: No, it have not been  flattened

Comment (silverbullet233) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rewrite/ExternalTablePredicateExtractor.java:41]: > No, it have not been flattened

@Youngwb fixed

**Review by kangkaisen — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by Youngwb — APPROVED** [review]

**Comment by silverbullet233** [comment]
@Mergifyio backport branch-2.1
