### PR TITLE
[BugFix] Fix issue where range partition expr parameters were not checked

### LINKED ISSUE #48141: In special cases, using non-VARCHAR type parameters to call substring will cause BE to crash.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE t (
day datetime
) ENGINE=OLAP
PRIMARY KEY(day)
PARTITION BY RANGE(cast(substr(day, 1, 10) as datetime))
(
PARTITION p201704 VALUES LESS THAN ("20170501"),
PARTITION p201705 VALUES LESS THAN ("20170601"),
PARTITION p201706 VALUES LESS THAN ("20170701")
)
DISTRIBUTED BY HASH(day) BUCKETS 10
PROPERTIES (
"replication_num"="1",
"in_memory" = "false",
"storage_format" = "DEFAULT"
);
2. INSERT INTO t VALUES("20170601");

### Expected behavior (Required)
Returns an error when calling the substr function with the wrong argument type.

### Real behavior (Required)
BE service process crashes.

### StarRocks version (Required)
2.5
3.0
3.1
3.2
3.3

### PR DESCRIPTION
**Pull request by chenminghua8**
## Why I'm doing:
The parameters of the range partition expression are not type-checked, and users can use expressions with incorrect types to create tables. This will cause be to crash when loading (see https://github.com/StarRocks/starrocks/issues/48141)

## What I'm doing:
Added parameter type verification for range partition expressions to prevent users from creating incorrect partition tables.

Fixes #48141

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [x] Yes, this PR will result in a change in behavior.
- [ ] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [x] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java [hunk 1]
```diff
@@ -1760,6 +1760,73 @@ public void testCreatePartitionByExprTable() {
                                 "\"storage_format\" = \"DEFAULT\"\n" +
                                 ");"
                 ));
+
+        ExceptionChecker.expectThrowsWithMsg(AnalysisException.class,
+                "Getting analyzing error from line 5, column 24 to line 5, column 41. Detail message: " +
```
Comment (Astralidea) [inline fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java:1765]: This line can be removed because it may change dynamically.

File: fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java [hunk 2]
```diff
@@ -1760,6 +1760,73 @@ public void testCreatePartitionByExprTable() {
...
+                                "DISTRIBUTED BY HASH(`bill_code`) BUCKETS 10 \n" +
+                                "PROPERTIES (\n" +
+                                "\"replication_num\" = \"1\",\n" +
+                                "\"in_memory\" = \"false\",\n" +
+                                "\"storage_format\" = \"DEFAULT\"\n" +
+                                ");"
+                ));
+
+        ExceptionChecker.expectThrowsWithMsg(AnalysisException.class,
+                "Getting analyzing error from line 5, column 24 to line 5, column 49. Detail message: " +
```
Comment (Astralidea) [inline fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java:1808]: ditto

File: fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java (hunk 1 above)
Comment (chenminghua8) [reply fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java:1765]: If don't do this, is there any way to test that it really checks out the wrong table statement?

File: fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java (hunk 2 above)
Comment (chenminghua8) [reply fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java:1808]: OK, I'll fix it.

File: fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java (hunk 1 above)
Comment (chenminghua8) [reply fe/fe-core/src/test/java/com/starrocks/catalog/CreateTableTest.java:1765]: OK, I'll fix it.

**Review by Astralidea — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
