### PR TITLE
increase make_snapshot rpc timeout

### LINKED ISSUE #5505: Clone failed caused by make_snapshot rpc timeout
### Real behavior (Required)
```
I0425 14:09:01.954985 29620 task_worker_pool.cpp:945] get clone task. signature:103426
I0425 14:09:01.955004 29620 engine_clone_task.cpp:135] Creating a new replica of tablet 103426 by clone. committed_version=18248 signature=103426
I0425 14:09:01.955034 29620 storage_engine.cpp:907] Obtained shard path=/bigdata/be-0014bc09-bf70-44e4-a1e4-014df7f152f5/data/6
W0425 14:09:06.978302 29620 thrift_rpc_helper.cpp:65] retrying call frontend service after 100 ms, address=TNetworkAddress(hostname=172.16.136.199, port=9060), reason=THRIFT_EAGAIN (timed out)
W0425 14:09:12.098285 29620 thrift_rpc_helper.cpp:76] call frontend service failed, address=TNetworkAddress(hostname=172.16.136.199, port=9060), reason=THRIFT_EAGAIN (timed out)
W0425 14:09:12.298710 29620 engine_clone_task.cpp:261] Fail to make snapshot from 172.16.136.199: Rpc error: failed to call frontend service
/root/starrocks/be/src/storage/task/engine_clone_task.cpp:323 ThriftRpcHelper::rpc<BackendServiceClient>( ip, port, [&request, &result](BackendServiceConnection& client) { client->make_snapshot(result, request); })
W0425 14:09:12.298768 29620 task_worker_pool.cpp:999] clone failed. signature: 103426


I0425 14:09:01.955408 3552395 snapshot_manager.cpp:73] Received a snapshot request: TSnapshotRequest {
  01: tablet_id (i64) = 103426,
  02: schema_hash (i32) = 193902312,
  05: timeout (i64) = 180,
  09: preferred_snapshot_format (i32) = 4,
}
I0425 14:09:08.470357 3552395 agent_server.cpp:228] success to make_snapshot. tablet_id=103426, schema_hash=193902312, snapshot_path: /data/be-88a3aaf4-e084-4205-a0b6-9d16dd5555ea/snapshot/20220425140901.228.180

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by decster**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] others

## Which issues of this PR fixes ：

Partially fixes #5505

## Problem Summary(Required) ：

`make_snapshot` will hard link all required rowsets' segment files, the number of files may be very large(>1000),
so it may take some time to process `make_snapshot` rpc, this PR increases rpc timeout from 5s to 20s to reduce the chance
of timeout, we may need a smart way to estimate the time of make_snapshot in the future so we can set a more proper timeout value.

### CODE REVIEW

File: be/src/storage/task/engine_clone_task.cpp [hunk 1]
```diff
@@ -340,9 +340,12 @@ Status EngineCloneTask::_make_snapshot(const std::string& ip, int port, TTableId
...
 
     TAgentResult result;
+    // snapshot will hard link all required rowsets' segment files, the number of files may be very large(>1000),
+    // so it may take some time to process this rpc, so we increase rpc timeout from 5s to 20s to reduce the chance
+    // of timeout for now, we may need a smart way to estimate the time of make_snapshot in future
     RETURN_IF_ERROR(ThriftRpcHelper::rpc<BackendServiceClient>(
-            ip, port,
-            [&request, &result](BackendServiceConnection& client) { client->make_snapshot(result, request); }));
+            ip, port, [&request, &result](BackendServiceConnection& client) { client->make_snapshot(result, request); },
+            20000));
```
Comment (imay) [inline be/src/storage/task/engine_clone_task.cpp:348]: Why not make this a config?

Comment (decster) [reply be/src/storage/task/engine_clone_task.cpp]: ok, add a config

**Review by Astralidea — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]
