### PR TITLE
[Enhancement] trino dialect support select offset

### LINKED ISSUE #42951: Incorrect `OFFSET` behavior in Trino sql dialect
### Steps to reproduce the behavior (Required)
```sql
SELECT conversation_id
FROM test_analytics AS test
WHERE test.account_id = 'TEST_ACCOUNT_ID'
ORDER BY test.start_datetime desc 
OFFSET 10
LIMIT 1
```
offset is ignored in this case, here is the result of explain
image

### Expected behavior (Required)

Offset should apply and give the 10th result instead of the first one.

`OFFSET` preceding `LIMIT` is the proper syntax documented by Trino: https://trino.io/docs/current/sql/select.html#offset-clause
image

### Real behavior (Required)

Offset is not applied the first record in the `ORDER BY` is returned.

Our current workaround is to put the `OFFSET` after `LIMIT` then it works.

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

```sql
+-------------------+
| current_version() |
+-------------------+
| 3.2.2-269e832     |
+-------------------+
```

This was also validated on the `main` branch by @mofeiatwork

### PR DESCRIPTION
**Pull request by DorianZheng**
## What I'm doing:

Fixes https://github.com/StarRocks/starrocks/issues/42951

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
Since this PR adds small new feature and I'm not going to fix UT for v3.1 and below version, I will only CP to v3.2. If anyone require this in v3.1, I will consider to CP it.
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java [hunk 1]
```diff
@@ -532,6 +542,12 @@ protected ParseNode visitSortItem(SortItem node, ParseTreeContext context) {
                 getNullOrderingType(isAsc, node.getNullOrdering()));
     }
 
+    @Override
+    protected ParseNode visitOffset(Offset node, ParseTreeContext context) {
+        long offset = ((LiteralExpr) visit(node.getRowCount(), context)).getLongValue();
+        return new LimitElement(offset, 0);
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java:548]: I think use limit default value -1 is better

Comment (Youngwb) [reply fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java:548]: and plz add some test to cover these

Comment (DorianZheng) [reply fe/fe-core/src/main/java/com/starrocks/connector/parser/trino/AstBuilder.java]: done

**Review by murphyatwork — APPROVED** [review]

**Review by stephen-shelby — APPROVED** [review]
