### PR TITLE
[BugFix] trim quote in get_json_string

### LINKED ISSUE #7471: Daily test failure in `test_condition_functions.TestConditionFunction.test_json_function`
### Real behavior (Required)
```
Daily Test Failed
test_condition_functions.TestConditionFunction.test_json_function (from nosetests)

Error Message
(('v1',),) != (('"v1"',),)
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.6/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.6/unittest/case.py", line 622, in run
    testMethod()
  File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/disk1/jenkins/workspace/master_release/StarRocksTest/case/system_case/test_dql/test_vectorized/test_condition_functions.py", line 253, in test_json_function
    eq_((("v1",),), self._exec_dml("""select get_json_string('{"k1":"v1", "k2":"v2"}', "$.k1")"""))
  File "/usr/local/lib/python3.6/site-packages/nose/tools/trivial.py", line 29, in eq_
    raise AssertionError(msg or "%r != %r" % (a, b))
AssertionError: (('v1',),) != (('"v1"',),)
Standard Output
select connection_id()
create database test_bitmap_457845a8_eda5_11ec_a89b_00163e0e489a
use test_bitmap_457845a8_eda5_11ec_a89b_00163e0e489a
select get_json_int('{"k1":1, "k2":"2"}', "$.k1")
select get_json_int('{"k1":"v1", "my.key":[1, 2, 3]}', '$."my.key"[1]')
select get_json_double('{"k1":1.3, "k2":"2"}', "$.k1")
select get_json_double('{"k1":"v1", "my.key":[1.1, 2.2, 3.3]}', '$."my.key"[2]')
select get_json_double('{"k1.key":{"k2":[3.4, 2.2]}}', '$."k1.key".k2[0]')
select get_json_string('{"k1":"v1", "k2":"v2"}', "$.k1")
drop database test_bitmap_457845a8_eda5_11ec_a89b_00163e0e489a
```

### StarRocks version (Required)
branch-2.3@bba404
main@680d0e

### PR DESCRIPTION
**Pull request by rickif**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7471 

## Problem Summary(Required) ：

This PR trim the quotes of the result returned by `get_json_string`.

### CODE REVIEW

File: be/src/exprs/vectorized/json_functions.cpp [hunk 1]
```diff
@@ -221,7 +221,9 @@ ColumnPtr JsonFunctions::get_json_string(FunctionContext* context, const Columns
     auto paths = columns[1];
 
     jsons = json_query(context, Columns{jsons, paths});
-    return json_string(context, Columns{jsons});
+    auto strs = json_string(context, Columns{jsons});
+
+    return _unquote_string(context, Columns{strs});
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/json_functions.cpp:226]: what if the JSON string contains a valid quote ?

**Comment by rickif** [comment]
run starrocks_clang-format

File: be/src/exprs/vectorized/json_functions.cpp (hunk 1 above)
Comment (rickif) [reply be/src/exprs/vectorized/json_functions.cpp]: This would only trim the first/last quote of string. So the valid quote in the middle of string would remain.

Comment (rickif) [reply be/src/exprs/vectorized/json_functions.cpp]: https://github.com/StarRocks/starrocks/blob/6758cc72b5461851ebe79b4dc40a2b7b8226a3e2/be/test/exprs/vectorized/json_functions_test.cpp#L141
A corresponding test case is added here.

File: be/src/exprs/vectorized/json_functions.cpp [hunk 2]
```diff
@@ -327,6 +331,32 @@ ColumnPtr JsonFunctions::_string_json(FunctionContext* context, const Columns& c
     return result.build(ColumnHelper::is_all_const(columns));
 }
 
+ColumnPtr JsonFunctions::_unescape_and_unquote_string(FunctionContext* context, const Columns& columns) {
```
Comment (mofeiatwork) [inline be/src/exprs/vectorized/json_functions.cpp:334]: In this way the column needs to be copied, could you embed the `unescape` procedure into the `json_string` directly to eliminate this overhead?

Comment (rickif) [reply be/src/exprs/vectorized/json_functions.cpp:334]: Maybe I think it's better to add a function with name `_json_string_unescaped` and not to change the behaviour of `json_string`.

File: be/src/util/json.cpp [hunk 3]
```diff
@@ -101,6 +101,23 @@ StatusOr<std::string> JsonValue::to_string() const {
     });
 }
 
+// NOTE: JsonValue must be a valid JSON, which means to_string should not fail
+StatusOr<std::string> JsonValue::dump() const {
```
[the remark this answers is not in the document]
Comment (rickif) [reply be/src/util/json.cpp]: Sorry. These are unused codes. I've deleted them.

**Review by murphyatwork — DISMISSED** [review]

**Comment by rickif** [comment]
@mergifyio backport branch-2.3

**Comment by rickif** [comment]
@megifyio backport branch-2.2

**Comment by rickif** [comment]
@Mergifyio backport branch-2.2
