### PR TITLE
[Enhancement] optimize colocate balancing when replication_num is 1

### LINKED ISSUE #10619: [Enhancement] Improve the colocate table balance strategy
### Steps to reproduce the behavior (Required)
1. Create a colocate table with replication_num = 1 in a cluster with 3 be node.
2. Restart one be.

### Expected behavior (Required)
The colcoate table should be stable.

### Real behavior (Required)
Colocate table become unstable. 

### StarRocks version (Required)
 - All

### PR DESCRIPTION
**Pull request by nshangyiming**
## What type of PR is this：
- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #10619

## Problem Summary(Required) ：

If there is unavailable bucketId to relocate, but the number of replica is one, we can do
nothing but wait for the dead BE to come alive, in this case we shouldn't change the bucket
sequence which will cause a lot of wasted colocate relocation work and further more make the
colocate group unstable for longer time, but we can still do the balance work.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|10|10|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 10 / 10 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|10|10|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java [hunk 1]
```diff
@@ -357,38 +357,44 @@ private boolean relocateAndBalance(GroupId groupId, Set<Long> unavailableBeIds,
...
+                // There is not enough replicas for us to do relocation or balance, because in this case we
+                // can not choose a valid backend to migrate replica to, end the outer loop.
                 break;
             }
 
             int leftBound;
-            if (hasUnavailableBe) {
-                leftBound = -1;
-            } else {
+            if (!hasUnavailableBe || replicationNum == 1) {
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:372]: Unavailable BE means: 1. stopped, 2. decommissioned.  For the decommissioned case, we should migrate the bucketId on that BE, or the decommission will be blocked.

Comment (nshangyiming) [reply fe/fe-core/src/main/java/com/starrocks/clone/ColocateTableBalancer.java:372]: Yes, i should consider this situation, let me fix that.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|20|20|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

**Review by chaoyli — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 20 / 20 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/clone/ColocateTableBalancer.java|20|20|100.00%|[]|

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Comment by nshangyiming** [comment]
run starrocks_admit_test

**Review by gengjun-git — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]
