### PR TITLE
[BugFix] Fix bug DescribeTable not standard

### LINKED ISSUE #17662: Superset does not recognize MV column type
### Expected behavior (Required)
image

### Real behavior (Required)
image

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
2.5.1

### PR DESCRIPTION
**Pull request by Astralidea**
Signed-off-by: Astralidea <astralidea@163.com>

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #17662

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [x] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/IndexSchemaProcNode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|4|4|100.00%|[]|

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/common/proc/IndexSchemaProcNode.java [hunk 1]
```diff
@@ -89,8 +89,8 @@ public ProcResult fetchResult() throws AnalysisException {
             String extraStr = StringUtils.join(extras, ",");
 
             List<String> rowList = Arrays.asList(column.getName(),
-                    column.getType().canonicalName(),
-                    column.isAllowNull() ? "Yes" : "No",
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/common/proc/IndexSchemaProcNode.java:93]: Could you add a note that this must keep uppercase to avoid someone else change it back.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 6 / 6 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/common/proc/IndexSchemaProcNode.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/ShowStmtAnalyzer.java|4|4|100.00%|[]|

**Review by gengjun-git — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by wyb — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
