### PR TITLE
[Enhancement] Support writing parquet json type when unloading data using FILES()

### LINKED ISSUE #53897: Unload data using INSERT INTO FILES ,Doesn't support to write JSON type data
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `tj` (
    `id` INT(11) NOT NULL COMMENT "",
    `j`  JSON NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`id`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`id`)
PROPERTIES (
    "replication_num" = "3",
    "storage_format" = "DEFAULT"
);
2. INSERT INTO tj (id, j) VALUES (1, parse_json('{"a": 1, "b": true}'));
INSERT INTO tj (id, j) VALUES (2, parse_json('{"a": 2, "b": false}'));
INSERT INTO tj (id, j) VALUES (3, parse_json('{"a": 3, "b": true}'));
INSERT INTO tj (id, j) VALUES (4, json_object('a', 4, 'b', false)); 

3. INSERT INTO 
FILES(
    "path" = "oss://test_bucket/unload/ComplexJSON",
    "format" = "parquet",
    "compression" = "zstd",
    "single" = "true"
) select * from tj;

### Real behavior (Required)
ERROR 1064 (HY000): Doesn't support to write JSON type data backend [id=293662]
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
3.2.12-5f81e3e

### PR DESCRIPTION
**Pull request by wyb**
## What I'm doing:

support writing json type in parquet format when unloading data using `insert into files()`

Fixes #53897

## What type of PR is this:

- [ ] BugFix
- [ ] Feature
- [x] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by trueeyu — APPROVED** [review]

**Review by meegoo — APPROVED** [review]

File: be/src/formats/parquet/level_builder.cpp [hunk 1]
```diff
@@ -599,6 +602,41 @@ Status LevelBuilder::_write_struct_column_chunk(const LevelBuilderContext& ctx,
...
+    // Use the rep_levels in the context from caller since node is primitive.
+    auto& rep_levels = ctx._rep_levels;
+    auto def_levels = _make_def_levels(ctx, node, null_col, col->size());
+    auto null_bitset = _make_null_bitset(ctx, null_col, col->size());
+
+    auto values = new ::parquet::ByteArray[col->size()];
+    DeferOp defer([&] { delete[] values; });
+
+    std::vector<std::string> datas;
+    datas.reserve(col->size());
```
Comment (trueeyu) [inline be/src/formats/parquet/level_builder.cpp:620]: Why alloc one array, only tmp use?

File: be/src/formats/parquet/level_builder.cpp [hunk 2]
```diff
@@ -599,6 +602,41 @@ Status LevelBuilder::_write_struct_column_chunk(const LevelBuilderContext& ctx,
...
+
+    // Use the rep_levels in the context from caller since node is primitive.
+    auto& rep_levels = ctx._rep_levels;
+    auto def_levels = _make_def_levels(ctx, node, null_col, col->size());
+    auto null_bitset = _make_null_bitset(ctx, null_col, col->size());
+
+    auto values = new ::parquet::ByteArray[col->size()];
+    DeferOp defer([&] { delete[] values; });
+
+    std::vector<std::string> datas;
```
Comment (trueeyu) [inline be/src/formats/parquet/level_builder.cpp:619]: Using std::string is not friendly to the memory allocator.

Comment (wyb) [reply be/src/formats/parquet/level_builder.cpp:619]: the buffer total length cannot be determined.
optimize later if there are performance issues.
