### PR TITLE
[BugFix] fix query stuck issue in spill restore phase

### LINKED ISSUE #47673: query may get stuck after many runs
### Steps to reproduce the behavior (Required)

data set: TPCH-1TB

run query09 with the following settings
```sql
set pipeline_dop=4;
set enable_spill=true;
set spill_mode='force';
select
  nation,
  o_year,
  sum(amount) as sum_profit
from
  (
    select
      n_name as nation,
      extract(year from o_orderdate) as o_year,
      l_extendedprice * (1 - l_discount) - ps_supplycost * l_quantity as amount
    from
      part,
      supplier,
      lineitem,
      partsupp,
      orders,
      nation
    where
      s_suppkey = l_suppkey
      and ps_suppkey = l_suppkey
      and ps_partkey = l_partkey
      and p_partkey = l_partkey
      and o_orderkey = l_orderkey
      and s_nationkey = n_nationkey
      and p_name like '%green%'
  ) as profit
group by
  nation,
  o_year
order by
  nation,
  o_year desc;

```
### Expected behavior (Required)

query can run successfully every time
### Real behavior (Required)

query may get stuck if run many times

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

3.3.0-rc02

### PR DESCRIPTION
**Pull request by silverbullet233**
## What I'm doing:

Fixes #47673

### Root Cause

The spill restore task supports a yield mechanism, and if a task runs for more than a time slice, it will actively trigger a yield.

In order to avoid an excessive number of IO tasks, the restore phase will control the number of simultaneously submitted restore tasks to not exceed a certain threshold.
image

_running_restore_tasks will only be updated at the beginning and end of IO tasks, and will not be updated if yield occurs.

In the implementation of YieldRestoreTask:: do_read, there is a possibility that `yield_point==total_yield_point_cnt` triggers yield at the same time. (suppose total_yield_point_cnt = 1 and the first time runs for more than a time slice.)

image

At this point, yield_ctx.need_yield=true, the defer defined in L226 will not be executed, and _running_restore_tasks will never decrease.

In the hash join probe stage, if a partition has no output and no restore task in progress, a restore task will be submitted to retrieve the data. In some cases, the above bug can cause the restore task to never actually execute, resulting in the query getting stuck.

But I couldn't find a stable way to reproduce this problem. In my environment, tpch q09 may get stuck once after running dozens of times. After this change, I executed it more than a hundred times without any problems.

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by satanson — DISMISSED** [review]

File: be/src/exec/workgroup/scan_executor.cpp [hunk 1]
```diff
@@ -80,7 +80,11 @@ void ScanExecutor::worker_thread() {
 
         // task
         if (!task.is_finished()) {
-            _task_queue->force_put(std::move(task));
+            if (task.has_yield_function()) {
```
Comment (stdpain) [inline be/src/exec/workgroup/scan_executor.cpp:83]: why change the code here

**Comment by stdpain** [comment]
> At this point, yield_ctx.need_yield=true, the defer defined in L226 will not be executed, and _running_restore_tasks will never decrease.

in next schedule turn _running_restore_tasks will be decreased.

> In the hash join probe stage, if a partition has no output and no restore task in progress, a restore task will be submitted to retrieve the data. In some cases, the above bug can cause the restore task to never actually execute, resulting in the query getting stuck.
```
 _stream->is_ready() && _running_restore_tasks >= config::io_tasks_per_scan_operator
```
The is_ready in stream will be checked firstly. It probably wasn't caused by that.

File: be/src/exec/spill/input_stream.cpp [hunk 2]
```diff
@@ -59,6 +59,9 @@ Status YieldableRestoreTask::do_read(workgroup::YieldContext& yield_ctx, SerdeCo
 
         BREAK_IF_YIELD(wg, &yield_ctx.need_yield, yield_ctx.time_spent_ns);
     }
+    if (yield_ctx.is_finished()) {
```
Comment (stdpain) [inline be/src/exec/spill/input_stream.cpp:62]:
```patch
diff --git a/be/src/exec/spill/spiller.hpp b/be/src/exec/spill/spiller.hpp
index 0f0010e632..0f6a431ae4 100644
--- a/be/src/exec/spill/spiller.hpp
+++ b/be/src/exec/spill/spiller.hpp
index 0f0010e632..0f6a431ae4 100644
--- a/be/src/exec/spill/spiller.hpp
+++ b/be/src/exec/spill/spiller.hpp
@@ -340,7 +340,7 @@ Status PartitionedSpillerWriter::flush(RuntimeState* state, bool is_final_flush,
         _spiller->update_spilled_task_status(
                 yieldable_flush_task(yield_ctx, splitting_partitions, spilling_partitions));

-        if (yield_ctx.need_yield) {
+        if (yield_ctx.need_yield && !yield_ctx.is_finished()) {
             COUNTER_UPDATE(_spiller->metrics().flush_task_yield_times, 1);
             defer.cancel();
         }
```
prefer change yield task

**Review by stdpain — APPROVED** [review]

**Review by satanson — APPROVED** [review]
