### PR TITLE
[BugFix] JournalCursor retry on bdb exception

### LINKED ISSUE #7459: FE follower fails easily on high IO
During the stability test, the IO load can be very high, causing bdb read fails. FE did not catch the exception and exit.

```
2022-04-10 21:15:44,191 WARN (replayer|78) [BDBJournalCursor.next():148] Catch an exception when get next JournalEntity. key:2970500
com.sleepycat.je.LockTimeoutException: (JE 7.3.7) Lock expired. Locker 1962490634 -1_replayer_ReplicaThreadLocker: waited for lock on database=2968388 LockAddr:276769085 LSN=0xcd/0xd6f69 type=READ grant=WAIT_NEW timeoutMillis=1000 startTime=1649596543191 endTime=1649596544191
Owners: [<LockInfo locker="<ReplayTxn id="-3222017">950837196 -3222017_ReplayThread_ReplayTxn" type="WRITE"/>]
Waiters: [<LockInfo locker="1962490634 -1_replayer_ReplicaThreadLocker" type="READ"/>]

        at com.sleepycat.je.txn.LockManager.makeTimeoutException(LockManager.java:1117) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:606) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockManager.lock(LockManager.java:345) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.BasicLocker.lockInternal(BasicLocker.java:124) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.ReplicaThreadLocker.lockInternal(ReplicaThreadLocker.java:63) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Locker.lock(Locker.java:499) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3585) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3316) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.lockLNAndCheckDefunct(CursorImpl.java:2138) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.CursorImpl.searchExact(CursorImpl.java:1950) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchExact(Cursor.java:4194) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.searchNoDups(Cursor.java:4055) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.search(Cursor.java:3857) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Cursor.getInternal(Cursor.java:1284) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1271) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Database.get(Database.java:1330) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.CloseSafeDatabase.get(CloseSafeDatabase.java:47) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJournalCursor.next(BDBJournalCursor.java:108) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.replayJournal(Catalog.java:2533) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$3.runOneCycle(Catalog.java:2322) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
```

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7459

## Problem Summary(Required) ：

This PR improves the exception handling mechanism for the `BDBJournalCursor` class, so that corner cases such as read failure can be handled and retried properly.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 61 / 76 (80.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|56|65|86.15%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 61 / 76 (80.26%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|56|65|86.15%|

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalCursor.java [hunk 1]
```diff
@@ -21,7 +21,7 @@
 public interface JournalCursor {
 
     // Return the next journal. return null when there is no more journals
-    public JournalEntity next();
+    public JournalEntity next() throws InterruptedException, JournalException;
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalCursor.java:24]: Better to modify this comment to explain when the Exception will be thown.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java [hunk 2]
```diff
@@ -79,54 +78,109 @@ private BDBJournalCursor(BDBEnvironment env, long fromKey, long toKey) throws Ex
...
+    }
+
+    protected void openDatabaseIfNecessary() throws InterruptedException, JournalException {
+        if (!shouldOpenDatabase()) {
+            return;
+        }
+
+        String dbName = Long.toString(dbNames.get(nextDbPositionIndex));
+        JournalException exception = null;
+        for (int i = 0; i != RETRY_TIME; ++ i) {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:104]: I think it is safer to use i < RETRY_TIME

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java [hunk 3]
```diff
@@ -79,54 +78,109 @@ private BDBJournalCursor(BDBEnvironment env, long fromKey, long toKey) throws Ex
...
+                exception = new JournalException(errMsg);
+                exception.initCause(e);
+            }
+        }
+
+        // failed after retry
+        throw exception;
+    }
+
+    protected JournalEntity serializedData(DatabaseEntry data) throws JournalException {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:134]: I think what this function do is deserialize rather than serialize

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java (hunk 2 above)
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java]: Done

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 64 / 76 (84.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|59|65|90.77%|

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java [hunk 4]
```diff
@@ -79,54 +78,109 @@ private BDBJournalCursor(BDBEnvironment env, long fromKey, long toKey) throws Ex
...
+                exception = new JournalException(errMsg);
+                exception.initCause(e);
+            }
+        }
+
+        // failed after retry
+        throw exception;
+    }
+
+    protected JournalEntity deserializedData(DatabaseEntry data) throws JournalException {
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:134]:
```suggestion
    protected JournalEntity deserializeData(DatabaseEntry data) throws JournalException {
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 64 / 76 (84.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|59|65|90.77%|

**Review by imay — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 75 / 87 (86.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|68|74|91.89%|
|:large_blue_circle:|com/starrocks/journal/JournalInconsistentException.java|2|2|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java [hunk 5]
```diff
@@ -79,54 +80,112 @@ private BDBJournalCursor(BDBEnvironment env, long fromKey, long toKey) throws Ex
                 break;
             }
         }
+        nextDbPositionIndex -= 1;
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:83]: In the old implementation, databases are opened in the constructor method as well as the `next()` method. This brings some side effects.

1. In the `next()` method, we have to open a new database only after a failed attempt to read the current database, which leads to some very confusing if-else statements.
2. The constructor would have to deal with the BDB environment, which is against intuition.

As a result, I now shrink the operation of opening a database only in the `next()` function. 

You may think that the name of `nextDbPositionIndex` is confusing in the constructor's scope, but I think the value is reasonable since it's only an initialized value, and it indeed represents the next index of database that we are going to open in the `next()` method.

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java [hunk 6]
```diff
@@ -79,54 +80,112 @@ private BDBJournalCursor(BDBEnvironment env, long fromKey, long toKey) throws Ex
...
+            throw exception;
         }
-        this.database = env.openDatabase(dbName);
+        return ret;
     }
 
     @Override
-    public JournalEntity next() {
-        JournalEntity ret = null;
+    public JournalEntity next() throws InterruptedException, JournalException, JournalInconsistentException {
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:157]: InterruptedException is thrown when the current thread was interrupted, for example, when other thread is calling cancel. At this point, current thread should exit. Now we always ignore this exception and simply retry, which I think it's a bad practice. The natural way is to catch this exception in the main loop and exit gracefully.

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 7]
```diff
@@ -1678,19 +1672,32 @@ public synchronized boolean replayJournal(long toJournalId) {
...
 
         long startTime = System.currentTimeMillis();
         boolean hasLog = false;
         while (true) {
-            JournalEntity entity = cursor.next();
+            JournalEntity entity = null;
+            try {
+                entity = cursor.next();
+            } catch (InterruptedException | JournalException | JournalInconsistentException e) {
+                LOG.warn("got exception will get next, will quit, ", e);
```
[the remark this answers is not in the document]
Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1690]: done

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJournalCursor.java:83]: Cool.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 75 / 87 (86.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|68|74|91.89%|
|:large_blue_circle:|com/starrocks/journal/JournalInconsistentException.java|2|2|100.00%|

**Review by chaoyli — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 75 / 87 (86.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/GlobalStateMgr.java|5|11|45.45%|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJournalCursor.java|68|74|91.89%|
|:large_blue_circle:|com/starrocks/journal/JournalInconsistentException.java|2|2|100.00%|
