### PR TITLE
[MaterializedView] Partition based on non-existing table throws NPE when creating mv (#7733)

### LINKED ISSUE #7733: [MaterializedView] Partition based on non-existing table throws NPE when creating mv
to https://github.com/StarRocks/starrocks/issues/3680

### Steps to reproduce the behavior (Required)
1. create table tbl1
2. create materialized view partition by tbl2.k1

### Expected behavior (Required)
create mv success
### Real behavior (Required)
throw NPE
### StarRocks version (Required)
main branch

### PR DESCRIPTION
**Pull request by blackstar-baba**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7733 

## Problem Summary(Required) ：

1. Fix `npe` Which cause by partition by clause related with base table column.
2. Fix mv period task no scheduling after restart fe.
3. Fix mv task no sync partitions in first time.
4. Fix partition no pruned if output column in query statement has alias.
5. Fix mv can't use after `fe` restarted.
6. Fix `insert overwrite` multi-tables failed in mv sync task.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 46 / 46 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|12|12|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|34|34|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java [hunk 1]
```diff
@@ -101,18 +104,22 @@ public void processTaskRun(TaskRunContext context) throws Exception {
...
         Map<Long, OlapTable> olapTables = Maps.newHashMap();
+        List<SlotRef> slotRefs = Lists.newArrayList();
+        partitionExpr.collect(SlotRef.class, slotRefs);
+        // if partitionExpr is FunctionCallExpr, get first SlotRef
+        Preconditions.checkState(slotRefs.size() == 1);
+        SlotRef slotRef = slotRefs.get(0);
+        QueryStatement queryStatement = ((QueryStatement) SqlParser.parse(
+                materializedView.getViewDefineSql(), context.getCtx().getSessionVariable().getSqlMode()).get(0));
+        Analyzer.analyze(queryStatement, context.getCtx());
+        Map<TableName, Table> tableNameTableMap = AnalyzerUtils.collectAllTableAndViewWithAlias(queryStatement);
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/scheduler/MvTaskRunProcessor.java:115]: could do this work earlier.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 2]
```diff
@@ -209,27 +209,45 @@ private void genColumnAndSetIntoStmt(CreateMaterializedViewStatement statement,
...
-                    // check exp with ref expr which in columnExprMap
-                    checkExpWithRefExpr(expressionPartitionDesc, refExpr);
-                    break;
+            QueryStatement queryStatement = statement.getQueryStatement();
+            SlotRef exprSlotRef = expressionPartitionDesc.getSlotRef();
+            TableName exprTableName = exprSlotRef.getTblNameWithoutAnalyzed();
+            Expr refExpr = null;
+            if (exprTableName == null) {
+                for (Column column : columns) {
+                    if (exprSlotRef.getColumnName().equals(column.getName())) {
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:222]: need equalsIgnoreCase?

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 55 / 56 (98.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|10|11|90.91%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Database.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|37|37|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 55 / 56 (98.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|10|11|90.91%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Database.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|37|37|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 55 / 56 (98.21%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|10|11|90.91%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/catalog/Database.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|37|37|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 3]
```diff
@@ -159,8 +159,9 @@ public void setLastRefreshTime(long lastRefreshTime) {
     @SerializedName(value = "refreshScheme")
     private MvRefreshScheme refreshScheme;
 
-    @SerializedName(value = "baseTableIds")
-    private Set<Long> baseTableIds;
+    // if table has alias, use alias instead name
+    @SerializedName(value = "baseTableIdNames")
+    private Map<Long, String> baseTableIdNames;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:164]: why we need to store base table alias in MV definition？

Comment (blackstar-baba) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:164]: I used  it to get  the table which partitions mapped with mv partitions in class `MvTaskRunProcessor` 
 ```
OlapTable partitionTable = null;
for (Long tableId : baseTableIdNames.keySet()) {
    OlapTable olapTable = (OlapTable) database.getTable(tableId);
    if (slotRef.getTblNameWithoutAnalyzed().getTbl().equals(baseTableIdNames.get(tableId))) {
        partitionTable = olapTable;
    }
    olapTables.put(olapTable.getId(), olapTable);
}
```

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 56 / 56 (100.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|2|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|43|43|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:heart_eyes: **pass** : 77 / 81 (95.06%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|6|7|85.71%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|15|15|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|48|48|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 94 / 146 (64.38%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|8|37.50%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|24|62|38.71%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|17|64.71%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 95 / 151 (62.91%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|0|3|00.00%|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|3|10|30.00%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|25|65|38.46%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|17|64.71%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 4]
```diff
@@ -355,7 +377,17 @@ public MaterializedView selectiveCopy(Collection<String> reservedPartitions, boo
     @Override
     public void gsonPostProcess() throws IOException {
         super.gsonPostProcess();
+    }
 
+    @Override
+    public void write(DataOutput out) throws IOException {
+        // write type first
+        Text.writeString(out, type.name());
```
[the remark this answers is not in the document]
Comment (blackstar-baba) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:385]: Because read type first when reading table：
```
// Table 229
public static Table read(DataInput in) throws IOException {
        Table table = null;
        TableType type = TableType.valueOf(Text.readString(in));
```

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 108 / 165 (65.45%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|9|22.22%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|25|65|38.46%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|17|64.71%|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|14|18|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 5]
```diff
@@ -112,18 +96,25 @@ public Void visitCreateMaterializedViewStatement(CreateMaterializedViewStatement
...
+            Database db = context.getGlobalStateMgr().getDb(statement.getTableName().getDb());
+            if (db == null) {
+                throw new SemanticException("Can not find database:" + statement.getTableName().getDb());
+            }
             tableNameTableMap.forEach((tableName, table) -> {
-                if (!tableName.getDb().equals(statement.getTableName().getDb())) {
+                if (db.getTable(table.getId()) == null) {
                     throw new SemanticException(
-                            "Materialized view do not support table which is in other database:" + tableName.getDb());
+                            "Materialized view do not support table: " + table.getName() +
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:111]: table.getName + " do not exist in database: " + db..getName.

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 6]
```diff
@@ -112,18 +96,25 @@ public Void visitCreateMaterializedViewStatement(CreateMaterializedViewStatement
...
+                                    " which is in other database");
                 }
                 if (!(table instanceof OlapTable)) {
                     throw new SemanticException(
-                            "Materialized view only support olap table:" + tableName.getTbl() + " type:" +
-                                    table.getType().name());
+                            "Materialized view only support olap table:" + table.getName() +
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:116]:
```suggestion
                            "Materialized view only supports olap table. But the type of table " + table.getName() + " is:" + table.getType().name()
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java [hunk 7]
```diff
@@ -40,7 +41,9 @@ public class CreateMaterializedViewStatement extends DdlStmt {
     // for create column in mv
     private List<Column> mvColumnItems = Lists.newArrayList();
     private Set<Long> baseTableIds;
-    private Column basePartitionColumn;
+    private Column partitionColumn;
+    // record expression which related with partition by clause
+    private Expr partitionRefTableExprs;
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java:46]:
```suggestion
    private Expr partitionRefTableExpr;
```

File: fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java [hunk 8]
```diff
@@ -152,12 +155,20 @@ public void setBaseTableIds(Set<Long> baseTableIds) {
...
+        return partitionColumn;
     }
 
-    public void setBasePartitionColumn(Column basePartitionColumn) {
-        this.basePartitionColumn = basePartitionColumn;
+    public void setPartitionColumn(Column partitionColumn) {
+        this.partitionColumn = partitionColumn;
+    }
+
+    public Expr getPartitionRefTableExprs() {
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/ast/CreateMaterializedViewStatement.java:166]:
```suggestion
    public Expr getPartitionRefTableExpr() {
```

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 9]
```diff
@@ -215,42 +202,52 @@ private void checkExpInColumn(CreateMaterializedViewStatement statement,
...
         }
 
-        private void checkExpWithRefExpr(ExpressionPartitionDesc expressionPartitionDesc, Expr refExpr) {
+        private void checkExpWithRefExpr(CreateMaterializedViewStatement statement,
+                                         Map<Column, Expr> columnExprMap) {
+            ExpressionPartitionDesc expressionPartitionDesc = statement.getPartitionExpDesc();
+            Column partitionColumn = statement.getPartitionColumn();
+            Expr refExpr = columnExprMap.get(partitionColumn);
             if (expressionPartitionDesc.isFunction()) {
+                // e.g. partition by date_trunc(ss)
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:229]:
```suggestion
                // e.g. partition by date_trunc("month", ss)
```

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 10]
```diff
@@ -215,42 +202,52 @@ private void checkExpInColumn(CreateMaterializedViewStatement statement,
...
                 if (!(refExpr instanceof SlotRef)) {
                     throw new SemanticException("Materialized view partition function " +
                             functionCallExpr.getFnName().getFunction() +
                             " must related with column");
                 }
-                ArrayList<Expr> children = functionCallExpr.getChildren();
+                SlotRef slotRef = getSlotRef(functionCallExpr);
+                slotRef.setType(partitionColumn.getType());
+                // copy function and set it into partitionRefTableExprs
+                Expr partitionRefTableExprs = functionCallExpr.clone();
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:239]:
```suggestion
                Expr partitionRefTableExpr = functionCallExpr.clone();
```

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 11]
```diff
@@ -215,42 +202,52 @@ private void checkExpInColumn(CreateMaterializedViewStatement statement,
...
+                        partitionRefTableExprs.setChild(i, refExpr);
                     }
                 }
-                // analyze function, must after update child
-                FunctionAnalyzer.analyze(functionCallExpr);
+                statement.setPartitionRefTableExprs(partitionRefTableExprs);
             } else {
+                // e.g. partition by date_trunc('day',ss) or partition by ss
                 if (refExpr instanceof FunctionCallExpr || refExpr instanceof SlotRef) {
-                    expressionPartitionDesc.setExpr(refExpr);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:253]: why there is refExpr instanceof FunctionCallExpr here?

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java [hunk 12]
```diff
@@ -308,6 +303,28 @@ private void checkPartitionColumnWithBaseTable(CreateMaterializedViewStatement s
...
+                expr.collect(SlotRef.class, slotRefs);
+                Preconditions.checkState(slotRefs.size() == 1);
+                return slotRefs.get(0);
+            }
+        }
+
+        private void replaceTableAlias(SlotRef slotRef,
+                                       CreateMaterializedViewStatement statement,
+                                       Map<TableName, Table> tableNameTableMap) {
+            if (slotRef.getTblNameWithoutAnalyzed().getDb() == null) {
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:323]: why should replay table name for this case? please add some comment and cases.

**Review by ABingHuang — CHANGES_REQUESTED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 112 / 167 (67.07%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|9|22.22%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|24|61|39.34%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|18|61.11%|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|14|18|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/common/ExpressionPartitionUtil.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/common/util/RangeUtils.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java (hunk 12 above)
Comment (blackstar-baba) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java:323]: Because table may have alias . if TableName replace it with table name , we can use TableName to get table

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 112 / 167 (67.07%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|9|22.22%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|24|61|39.34%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|18|61.11%|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|14|18|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/common/ExpressionPartitionUtil.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/common/util/RangeUtils.java|4|4|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 111 / 166 (66.87%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|9|22.22%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|24|61|39.34%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|18|61.11%|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|14|18|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/common/ExpressionPartitionUtil.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/common/util/RangeUtils.java|3|3|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

**Comment by blackstar-baba** [comment]
run starrocks_fe_unittest

**Review by Astralidea — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 109 / 166 (65.66%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|2|11|18.18%|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|24|61|39.34%|
|:large_blue_circle:|com/starrocks/scheduler/MvTaskRunProcessor.java|11|18|61.11%|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|14|18|77.78%|
|:large_blue_circle:|com/starrocks/sql/analyzer/ViewDefBuilder.java|9|9|100.00%|
|:large_blue_circle:|com/starrocks/sql/common/ExpressionPartitionUtil.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/ast/CreateMaterializedViewStatement.java|5|5|100.00%|
|:large_blue_circle:|com/starrocks/common/util/RangeUtils.java|1|1|100.00%|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|42|42|100.00%|

**Review by Astralidea — APPROVED** [review]

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by kangkaisen — APPROVED** [review]
