### PR TITLE
[BugFix] Fix mv memory leak bug in QeProcessorImpl

### LINKED ISSUE #15700: [BUG] FE Leader node memory grows continuously when there are new MVs in the cluster.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - 2.4 2.5

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #15700

## Problem Summary(Required) ：

executor.handleDMLStmt() registers the queryInfo into QeProcessorImpl. But there is no place to unregister it in PartitionBasedMaterializedViewRefreshProcessor. 

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 2.5
  - [x] 2.4
  - [ ] 2.3
  - [ ] 2.2

### CODE REVIEW

**Review by Astralidea — APPROVED** [review]

**Review by nshangyiming — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java [hunk 1]
```diff
@@ -737,6 +738,7 @@ public void refreshMaterializedView(MvTaskRunContext mvContext, ExecPlan execPla
         try {
             executor.handleDMLStmt(execPlan, insertStmt);
         } finally {
+            QeProcessorImpl.INSTANCE.unregisterQuery(ctx.getExecutionId());
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java:741]: can we add ut for it

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 1 / 1 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java (hunk 1 above)
Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/scheduler/PartitionBasedMaterializedViewRefreshProcessor.java:741]: Sure.

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4
