### PR TITLE
[BugFix] add check for join type mismatch in view delta mv rewrite

### LINKED ISSUE #20965: mv rewrite should failed for join type mismatch in view delta join rewrite
### Steps to reproduce the behavior (Required)
1. CREATE TABLE with ssb test
2. create materialized view like following:
CREATE MATERIALIZED VIEW lineorder_flat_mv
DISTRIBUTED BY HASH(LO_ORDERDATE, LO_ORDERKEY) BUCKETS 48
REFRESH manual
PROPERTIES (
    "replication_num" = "1"
)
AS SELECT
       l.LO_ORDERKEY AS LO_ORDERKEY,
       l.LO_LINENUMBER AS LO_LINENUMBER,
       l.LO_CUSTKEY AS LO_CUSTKEY,
       l.LO_PARTKEY AS LO_PARTKEY,
       l.LO_SUPPKEY AS LO_SUPPKEY,
       l.LO_ORDERDATE AS LO_ORDERDATE,
       l.LO_ORDERPRIORITY AS LO_ORDERPRIORITY,
       l.LO_SHIPPRIORITY AS LO_SHIPPRIORITY,
       l.LO_QUANTITY AS LO_QUANTITY,
       l.LO_EXTENDEDPRICE AS LO_EXTENDEDPRICE,
       l.LO_ORDTOTALPRICE AS LO_ORDTOTALPRICE,
       l.LO_DISCOUNT AS LO_DISCOUNT,
       l.LO_REVENUE AS LO_REVENUE,
       l.LO_SUPPLYCOST AS LO_SUPPLYCOST,
       l.LO_TAX AS LO_TAX,
       l.LO_COMMITDATE AS LO_COMMITDATE,
       l.LO_SHIPMODE AS LO_SHIPMODE,
       c.C_NAME AS C_NAME,
       c.C_ADDRESS AS C_ADDRESS,
       c.C_CITY AS C_CITY,
       c.C_NATION AS C_NATION,
       c.C_REGION AS C_REGION,
       c.C_PHONE AS C_PHONE,
       c.C_MKTSEGMENT AS C_MKTSEGMENT,
       s.S_NAME AS S_NAME,
       s.S_ADDRESS AS S_ADDRESS,
       s.S_CITY AS S_CITY,
       s.S_NATION AS S_NATION,
       s.S_REGION AS S_REGION,
       s.S_PHONE AS S_PHONE,
       p.P_NAME AS P_NAME,
       p.P_MFGR AS P_MFGR,
       p.P_CATEGORY AS P_CATEGORY,
       p.P_BRAND AS P_BRAND,
       p.P_COLOR AS P_COLOR,
       p.P_TYPE AS P_TYPE,
       p.P_SIZE AS P_SIZE,
       p.P_CONTAINER AS P_CONTAINER,
       d.d_date AS d_date,
       d.d_dayofweek AS d_dayofweek,
       d.d_month AS d_month,
       d.d_year AS d_year,
       d.d_yearmonthnum AS d_yearmonthnum,
       d.d_yearmonth AS d_yearmonth,
       d.d_daynuminweek AS d_daynuminweek,
       d.d_daynuminmonth AS d_daynuminmonth,
       d.d_daynuminyear AS d_daynuminyear,
       d.d_monthnuminyear AS d_monthnuminyear,
       d.d_weeknuminyear AS d_weeknuminyear,
       d.d_sellingseason AS d_sellingseason,
       d.d_lastdayinweekfl AS d_lastdayinweekfl,
       d.d_lastdayinmonthfl AS d_lastdayinmonthfl,
       d.d_holidayfl AS d_holidayfl,
       d.d_weekdayfl AS d_weekdayfl
   FROM lineorder AS l
            INNER JOIN customer AS c ON c.C_CUSTKEY = l.LO_CUSTKEY
            INNER JOIN supplier AS s ON s.S_SUPPKEY = l.LO_SUPPKEY
            INNER JOIN part AS p ON p.P_PARTKEY = l.LO_PARTKEY
            INNER JOIN dates AS d ON l.lo_orderdate = d.d_datekey;

3. query
select sum(lo_linenumber) from `lineorder`
 LEFT OUTER JOIN `dates`
 ON `lineorder`.`lo_orderdate` = `dates`.`d_datekey` WHERE `lineorder`.`lo_orderdate` = 19961001

### Expected behavior (Required)
the query is not rewritten by lineorder_flat_mv
### Real behavior (Required)
the query is rewritten by lineorder_flat_mv
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
main

### PR DESCRIPTION
**Pull request by ABingHuang**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #20965 

## Problem Summary(Required) ：

add check for join type mismatch in view delta mv rewrite to fix issue-20965 bug.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [ ] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java [hunk 1]
```diff
@@ -132,6 +132,19 @@ private boolean isMVApplicable(OptExpression mvExpression,
                     joinOperator.isLeftOuterJoin() || joinOperator.isInnerJoin())) {
                 return false;
             }
+            List<TableScanDesc> queryTableScanDescs = MvUtils.getTableScanDescs(queryExpression);
+            List<TableScanDesc> mvTableScanDescs = MvUtils.getTableScanDescs(mvExpression);
+            // there should be at least one same join type in mv scan descs for every query scan desc.
+            // to forbid rewrite for:
+            // query: a left outer join b
+            // mv: a inner join b inner join c
```
Comment (LiShuMing) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:140]: What about this?
```
MV      : a left outer b left outer c
Query :  b left outer a left outer c
```

Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MaterializedViewRewriter.java:140]: fixed

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java [hunk 2]
```diff
@@ -174,22 +174,23 @@ public Void visitLogicalTableScan(OptExpression optExpression, TableScanContext
...
+                for (int i = 0; i < optExpression.getInputs().size(); i++) {
+                    OptExpression child = optExpression.inputAt(i);
                     if (child.getOp() instanceof LogicalScanOperator) {
                         LogicalScanOperator scanOperator = (LogicalScanOperator) child.getOp();
                         Table table = scanOperator.getTable();
                         Integer id = scanContext.getTableIdMap().computeIfAbsent(table, t -> 0);
                         LogicalJoinOperator joinOperator = optExpression.getOp().cast();
                         TableScanDesc tableScanDesc =
-                                new TableScanDesc(table, id, scanOperator, joinOperator.getJoinType());
+                                new TableScanDesc(table, id, scanOperator, joinOperator.getJoinType(), i == 0);
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:193]: why i is zero means isLeft

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java [hunk 3]
```diff
@@ -28,12 +28,16 @@ public class TableScanDesc {
     private final LogicalScanOperator scanOperator;
     // join type of LogicalJoinOperator above scan operator
     private final JoinOperator parentJoinType;
+    private final boolean isLeft;
```
Comment (kangkaisen) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java:31]: what about full outer join

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java (hunk 2 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:193]: join has two children. input 0 means left?

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java (hunk 3 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java:31]: full outer join is not supported in view delta join rewrite.
I fix it in inner join case.

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java [hunk 4]
```diff
@@ -56,6 +60,14 @@ public LogicalScanOperator getScanOperator() {
         return scanOperator;
     }
 
+    public boolean isMatch(TableScanDesc other) {
+        boolean matched =  table.equals(other.table) && parentJoinType.equals(other.parentJoinType);
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java:64]: This will not work for external table....

**Review by Youngwb — DISMISSED** [review]

**Review by kangkaisen — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java [hunk 5]
```diff
@@ -56,6 +60,30 @@ public LogicalScanOperator getScanOperator() {
...
+    public boolean isMatch(TableScanDesc other) {
+        boolean matched =  table.equals(other.table);
+        if (!matched) {
+            return false;
+        }
+
+        // for
+        // query: a left join c
+        // mv: a inner join b left join c
+        if (parentJoinType.isInnerJoin()) {
```
Comment (Youngwb) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java:72]: query: a left join c
mv: a inner join b inner join c
It looks like will match, is it right?

**Review by kangkaisen — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java (hunk 5 above)
Comment (ABingHuang) [reply fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/TableScanDesc.java:72]: c will not match.

**Review by Youngwb — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
