### PR TITLE
[BugFix] Fix NPE while missing setting globalStateMgr in `ConnectContext`

### LINKED ISSUE #60879: NPE while setting warehouse id in creating partition process
### Real behavior (Required)
```sh
2025-07-08 11:56:53.003+08:00 WARN (thrift-server-pool-762446|12501644) [FrontendServiceImpl.createPartitionProcess():2298] failed to cancel alter operation
java.lang.NullPointerException: null
	at com.starrocks.qe.ConnectContext.setCurrentWarehouseId(ConnectContext.java:865) ~[starrocks-fe.jar:?]
	at com.starrocks.service.FrontendServiceImpl.createPartitionProcess(FrontendServiceImpl.java:2289) ~[starrocks-fe.jar:?]
	at com.starrocks.service.FrontendServiceImpl.createPartition(FrontendServiceImpl.java:2166) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$createPartition.getResult(FrontendService.java:5497) ~[starrocks-fe.jar:?]
	at com.starrocks.thrift.FrontendService$Processor$createPartition.getResult(FrontendService.java:5474) ~[starrocks-fe.jar:?]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:40) ~[libthrift-0.20.0.jar:0.20.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:40) ~[libthrift-0.20.0.jar:0.20.0]
	at com.starrocks.common.SRTThreadPoolServer$WorkerProcess.run(SRTThreadPoolServer.java:311) ~[starrocks-fe.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### StarRocks version (Required)
 - > 3.3.8

### PR DESCRIPTION
**Pull request by wxl24life**
## Why I'm doing:

`ConnectContext` with current implementation is easily miss used. An example to produce NPE is as following:

1. Someone needs to use `ConnectContext`, but it has no aware of wether he should set that `globalStateMgr`first (In fact, he's right, he shouldn't care about this)
```java
        ConnectContext connectContext = ConnectContext.get();
        if (connectContext == null) {
            connectContext = new ConnectContext();
            // not set globalStateMgr property
            connectContext.setThreadLocalInfo();
        }
```

2. But after that, in some other place within same thread, code like following will produce NPE:
```java
ConnectContext.get().setCurrentWarehouseId(xxx);
```

Because `setCurrentWarehouseId()`'s implementation depends on `globalStateMgr` property in `ConnectConext`

## What I'm doing:

Make sure `globalStateMgr` is set in constructor of `ConnectConext` class, as many method in `ConnectConext` now depends on it.

Fixes #60879 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java [hunk 1]
```diff
@@ -59,6 +59,7 @@
 import org.junit.jupiter.api.Assertions;
 import org.junit.jupiter.api.BeforeEach;
 import org.junit.jupiter.api.Test;
+import org.wildfly.common.Assert;
```
Comment (kevincai) [inline fe/fe-core/src/test/java/com/starrocks/qe/ConnectContextTest.java]: wrong assert imported

**Comment by kevincai** [comment]
```
    // GlobalStateMgr: put globalStateMgr here is convenient for unit test,
    // because globalStateMgr is singleton, hard to mock
    protected GlobalStateMgr globalStateMgr;
```

If this is the case, should make a few changes to make the ConnectContext self-sustainable.
1. always set globalStateMgr during constructing
2. remove all `GlobalStateMgr.getCurrentState()` call in other places inside ConnectContext, turn to `globalStateMgr` instead.
3. Fix the comment, it is not just for unit test any more.

File: fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java [hunk 2]
```diff
@@ -350,13 +348,15 @@ public ConnectContext() {
     }
 
     public ConnectContext(StreamConnection connection) {
+        // `globalStateMgr` is used in many cases, so we should explicitly make sure it is not null
+        globalStateMgr = GlobalStateMgr.getCurrentState();
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:353]: one more change: add preconditioncheck to setGlobalStateMgr() ensure it is not null.

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:353]: > one more change: add preconditioncheck to setGlobalStateMgr() ensure it is not null.

maybe we can just remove `set` method?

Comment (kevincai) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:353]: the set interface should be used by unit test, you can have a check.

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/qe/ConnectContext.java:353]: it's used in many many places, to keep things simple, i added a precondition check.

**Review by kevincai — DISMISSED** [review]

**Review by caneGuy — APPROVED** [review]

**Review by caneGuy — DISMISSED** [review]

**Comment by kevincai** [comment]
@Mergifyio rebase

**Review by kevincai — APPROVED** [review]

**Review by wyb — APPROVED** [review]
