### PR TITLE
[BugFix] Lake compaction scheduler might trigger redundant transaction which can cause CN crash

### LINKED ISSUE #56260: CN crash while leader FE restarted
### Steps to reproduce the behavior (Required)

build a cluster with multiple FE

1. continually load data and trigger compaction
2. restart leader FE and leader transferred to some other FE
3. FE compaction scheduler should block compaction transaction from start while some transaction already waited to publish

### Real behavior (Required)

```sh
tart time: Mon Feb 24 19:16:57 CST 2025, server uptime:  19:16:57 up 0 min,  0 users,  load average: 1.62, 0.37, 0.12
Ignored unknown config: emr_serverless_full_domain
Duplicate assignment to config 'storage_root_path', previous assignment will be ignored
Duplicate assignment to config 'sys_log_roll_num', previous assignment will be ignored
Duplicate assignment to config 'update_compaction_size_threshold', previous assignment will be ignored
3.3.8-1.88-202502202124 RELEASE (build 4254b9d)
query_id:00000000-0000-0000-0000-000000000000, fragment_instance:00000000-0000-0000-0000-000000000000
tracker:process consumption: 2885197616
tracker:jemalloc_metadata consumption: 74516576
tracker:query_pool consumption: 407653840
tracker:query_pool/connector_scan consumption: 0
tracker:load consumption: 0
tracker:metadata consumption: 777270
tracker:tablet_metadata consumption: 9695
tracker:rowset_metadata consumption: 0
tracker:segment_metadata consumption: 74911
tracker:column_metadata consumption: 692664
tracker:tablet_schema consumption: 9695
tracker:segment_zonemap consumption: 40240
tracker:short_key_index consumption: 0
tracker:column_zonemap_index consumption: 74592
tracker:ordinal_index consumption: 290312
tracker:bitmap_index consumption: 0
tracker:bloom_filter_index consumption: 0
tracker:compaction consumption: 0
tracker:schema_change consumption: 0
tracker:column_pool consumption: 0
tracker:page_cache consumption: 473898080
tracker:jit_cache consumption: 0
tracker:update consumption: 130034965
tracker:chunk_allocator consumption: 0
tracker:passthrough consumption: 0
tracker:clone consumption: 0
tracker:consistency consumption: 0
tracker:datacache consumption: 916753410
tracker:replication consumption: 0
*** Aborted at 1740395896 (unix time) try "date -d @1740395896" if you are using GNU date ***
PC: @          0x804b6d0 (/opt/starrocks/be/lib/starrocks_be+0x804b6cf)
*** SIGSEGV (@0x0) received by PID 8 (TID 0x7fb62f064700) from PID 0; stack trace: ***
    @     0x7fb8e0e0620b __pthread_once_slow
    @          0x7c863c0 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x7fb8e0e0f630 (/usr/lib64/libpthread-2.17.so+0xf62f)
    @          0x804b6d0 (/opt/starrocks/be/lib/starrocks_be+0x804b6cf)
    @          0x6348145 starrocks::lake::UpdateManager::publish_primary_compaction(starrocks::TxnLogPB_OpCompaction const&, long, starrocks::TabletMetadataPB const&, starrocks::lake::Tablet const&, starro
cks::DynamicCache<unsigned long, starrocks::lake::LakePrimaryIndex>::Entry*<C6><E8>^R
    @          0x63883af std::_Function_handler<starrocks::Status (), starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)::{lambda()#2}>::_M_invoke(std::_Any_data const&)
    @          0x6388ce5 starrocks::lake::PrimaryKeyTxnLogApplier::check_and_recover(std::function<starrocks::Status ()> const&)
    @          0x638b694 starrocks::lake::PrimaryKeyTxnLogApplier::apply(starrocks::TxnLogPB const&)
    @          0x6334f12 starrocks::lake::publish_version(starrocks::lake::TabletManager*, long, long, long, std::span<starrocks::TxnInfoPB const, 18446744073709551615ul>)
    @          0x37dac2b starrocks::LakeServiceImpl::publish_version(google::protobuf::RpcController*, starrocks::PublishVersionRequest const*, starrocks::PublishVersionResponse*, google::protobuf::Closure
*)::{lambda()#1}::operator()() const
    @          0x37ddb0a std::_Function_handler<void (), starrocks::ConcurrencyLimitedThreadPoolToken::submit_func(std::function<void ()>, std::chrono::time_point<std::chrono::_V2::system_clock, std::chron
```

### StarRocks version (Required)
 - build from main branch

### PR DESCRIPTION
**Pull request by wxl24life**
## Why I'm doing:

1. PR #54881 tried to optimize lake compaction scheduler, we wanted to minimize the affect of unfinished compaction transaction blocking compaction scheduler from scheduling
2. We maintained a `active txn id` to `table id` Map in that PR, and the Map was built  on each startup time of FE
3. The lake compaction scheduler would block new compaction scheduling on tables in the Map only, which was our target for that optimization
4. However, we missed to rebuild the Map while leader role transferred to a new FE and the new leader FE doesn't restart. With new leader FE, all tables' compaction scheduling were not blocked, which could introduce duplicate compaction transactions on the same Partition/Tablet, and it can lead BE/CN crash

## What I'm doing:

Fixes #56260

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by kevincai — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java [hunk 1]
```diff
@@ -1441,6 +1441,8 @@ private void startAllNodeTypeDaemonThreads() {
         domainResolver.start();
         if (RunMode.isSharedDataMode()) {
             compactionMgr.start();
+            // For lake compaction scheduler, should trigger rebuilding before GlobalStateMgr is ready
+            compactionMgr.rebuildActiveCompactionTransactionMapOnRestart();
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1445]: is the function call in `CompactionMgr.load()` necessary if `rebuildActiveCompactionTransactionMapOnRestart` is used here?

Comment (wyb) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1445]: why transfer to NonLeader also need rebuild?

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1445]: > is the function call in `CompactionMgr.load()` necessary if `rebuildActiveCompactionTransactionMapOnRestart` is used here?

Yes, in my new commit, I will remove it.

Comment (wxl24life) [reply fe/fe-core/src/main/java/com/starrocks/server/GlobalStateMgr.java:1445]: > why transfer to NonLeader also need rebuild?

yes, compaction mgr should only start on leader

**Review by kevincai — DISMISSED** [review]

**Review by starrocks-xupeng — APPROVED** [review]

**Review by wyb — APPROVED** [review]

**Review by kevincai — APPROVED** [review]
