### PR TITLE
[BugFix] Fix the issue of reading paimon table on S3

### LINKED ISSUE #28403: Error reported when using Paimon Catalog
### Steps to reproduce the behavior (Required)
1.CREATE EXTERNAL CATALOG paimon_catalog
PROPERTIES
(
    "type" = "paimon",
    "paimon.catalog.type" = "filesystem",
    "paimon.catalog.warehouse" = "s3://paimon/warehouse",
    "aws.s3.enable_ssl" = "false",
    "aws.s3.enable_path_style_access" = "true",
    "aws.s3.endpoint" = "http://XXX:9000/",
    "aws.s3.access_key" = "XXX",
    "aws.s3.secret_key" = "XXX"
);
2.set catalog paimon_catalog;
3.show databases;

### Expected behavior (Required)

show databases list.

### Real behavior (Required)

Error:
java.nio.file.AccessDeniedException: s3://paimon/warehouse: org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by TemporaryAWSCredentialsProvider SimpleAWSCredentialsProvider EnvironmentVariableCredentialsProvider IAMInstanceCredentialsProvider : com.amazonaws.SdkClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))

### StarRocks version (Required)
 - 3.1.0 RC02

### PR DESCRIPTION
**Pull request by miomiocat**
Fixes #28403 

follow #28456, fix the exception in BE

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 15 (06.67%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfiguration.java|0|2|00.00%|[45, 53]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|0|2|00.00%|[119, 123]|
|:large_blue_circle:|com/starrocks/connector/paimon/PaimonConnector.java|1|11|09.09%|[80, 81, 82, 83, 84, 85, 87, 88, 90, 91]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 16 / 17 (94.12%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/connector/paimon/PaimonConnector.java|12|13|92.31%|[102]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudConfiguration.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/credential/aws/AWSCloudCredential.java|2|2|100.00%|[]|

**Review by stephen-shelby — APPROVED** [review]

**Review by caneGuy — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

File: fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonConnector.java [hunk 1]
```diff
@@ -76,20 +76,30 @@ public PaimonConnector(ConnectorContext context) {
...
+            AWSCloudCredential awsCloudCredential = awsCloudConfiguration.getAWSCloudCredential();
+            if (!awsCloudCredential.getEndpoint().isEmpty()) {
+                paimonOptions.set("s3.endpoint", awsCloudCredential.getEndpoint());
+            }
+            if (!awsCloudCredential.getAccessKey().isEmpty()) {
+                paimonOptions.set("s3.access-key", awsCloudCredential.getAccessKey());
+            }
+            if (!awsCloudCredential.getSecretKey().isEmpty()) {
+                paimonOptions.set("s3.secret-key", awsCloudCredential.getSecretKey());
             }
```
Comment (0akarma) [inline fe/fe-core/src/main/java/com/starrocks/connector/paimon/PaimonConnector.java:92]: I have reached an error `Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool.` when querying from a paimon table which has large amount of file, So I wonder if it is possible to add `fs.s3a.connection.maximum` option in `paimonOptions` for pushing down to paimon? 
Or maybe there is another way to avoid this error?
