### PR TITLE
[BugFix] Fix `insert into files` statement not support delimiter convert

### LINKED ISSUE #57125: INSERT INTO FILES fail to parse row/column delimiter like '0x11'
### Steps to reproduce the behavior (Required)
```sql
create database unload;
USE unload;
-- SELECT * FROM sales_records;
CREATE TABLE sales_records(
    record_id     BIGINT,
    seller        STRING,
    store_id      INT,
    sales_time    DATETIME,
    sales_amt     DOUBLE
)
DUPLICATE KEY(record_id)
PARTITION BY date_trunc('day', sales_time)
DISTRIBUTED BY HASH(record_id);

INSERT INTO sales_records
VALUES
    (220313001,"Amy",1,"2022-03-13 12:00:00",8573.25),
    (220314002,"Bob",2,"2022-03-14 12:00:00",6948.99),
    (220314003,"Amy",1,"2022-03-14 12:00:00",4319.01),
    (220315004,"Carl",3,"2022-03-15 12:00:00",8734.26),
    (220316005,"Carl",3,"2022-03-16 12:00:00",4212.69),
    (220317006,"Bob",2,"2022-03-17 12:00:00",9515.88);


INSERT INTO FILES(
    "path" = "oss://cdp-hangzhou/unload/test_03/",
    "format" = "CSV",
    'csv.column_separator' = '0X11'
    -- 'csv.row_delimiter' = '\\X12'
) 
SELECT * FROM unload.sales_records;
```

### Expected behavior (Required)

Image

### Real behavior (Required)

Image

### StarRocks version (Required)
 - main branch

### PR DESCRIPTION
**Pull request by wxl24life**
## What I'm doing:

Fixes #57125

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java [hunk 1]
```diff
@@ -272,4 +272,38 @@ public void testFilesCredentialDesensitization() {
                 "FROM FILES(\"aws.s3.access_key\" = \"***\", \"aws.s3.region\" = \"us-west-1\", " +
                 "\"aws.s3.secret_key\" = \"***\", \"format\" = \"parquet\", \"path\" = \"s3://xxx/zzz\")", desensitizationSql);
     }
+
+    @Test
+    public void testCSVDelimiterConverterForUnload() {
+        Map<String, String> properties = new HashMap<>();
+        properties.put("path", "file://test_dir");
+        properties.put("format", "csv");
+        properties.put("csv.column_separator", "0x11");
```
Comment (kevincai) [inline fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java:281]: add the case to cover \X format, and it should be also working.

Comment (wxl24life) [reply fe/fe-core/src/test/java/com/starrocks/catalog/TableFunctionTableTest.java]: done

**Review by kevincai — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]

**Comment by wangsimo0** [comment]
ignore backport check: 3.3.13
