### PR TITLE
[Bugfix] Refactor alter refresh MaterializedView

### LINKED ISSUE #10015: [sync materialized view]alter mv failed when INTERVAL with "SECOND"
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                            `k1` date,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH ASYNC
                             PROPERTIES('replication_num' = '1')
                             AS SELECT k1,k2 from t1;
ALTER MATERIALIZED VIEW mv1 REFRESH ASYNC EVERY(INTERVAL 100 SECOND);
```

### Expected behavior (Required)
`Query OK, 0 rows affected`
### Real behavior (Required)
`ERROR 1064 (HY000): Unsupported interval unit: SECOND, only timeunit [YEAR, MONTH, DAY, HOUR, MINUTE] are supported.`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 9744f36 |
+----------------------------+
```

### LINKED ISSUE #10017: [sync materialized view]display error in information_schema.tasks
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                            `k1` date,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH MANUAL
                             PROPERTIES('replication_num' = '1')
                             AS SELECT k1,k2 from t1;
SELECT SCHEDULE FROM INFORMATION_SCHEMA.tasks;
```

### Expected behavior (Required)
`MANUAL`
### Real behavior (Required)
`EVENT_TRIGGERED`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 9744f36 |
+----------------------------+
```

### LINKED ISSUE #10018: [sync materialized view]alter mv failed
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                            `k1` date,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH MANUAL
                             PROPERTIES('replication_num' = '1')
                             AS SELECT k1,k2 from t1;
ALTER MATERIALIZED VIEW mv1 REFRESH ASYNC EVERY(INTERVAL 1 minute);
```

### Expected behavior (Required)
`Query OK, 0 rows affected`
### Real behavior (Required)
`ERROR 1064 (HY000): Task [mv-268922] already exists`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 9744f36 |
+----------------------------+
```

### LINKED ISSUE #10020: [sync materialized view]alter mv refresh type to async failed
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                            `k1` date,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH MANUAL
                             PROPERTIES('replication_num' = '1')
                             AS SELECT k1,k2 from t1;
ALTER MATERIALIZED VIEW mv1 REFRESH ASYNC;
```

### Expected behavior (Required)
`Query OK, 0 rows affected`
### Real behavior (Required)
`ERROR 1064 (HY000): Unexpected exception: null`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 9744f36 |
+----------------------------+
```

### LINKED ISSUE #10021: [sync materialized view]mv does not refreshed after modify refresh type to async
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `t1` (
                                            `k1` date,
                                            `k2` int,
                                            `k3` int
                                        ) ENGINE=OLAP
                                        DUPLICATE KEY(`k1`)
                                        COMMENT "OLAP"
                                        DISTRIBUTED BY HASH(`k1`) BUCKETS 3;
CREATE MATERIALIZED VIEW mv1
                             DISTRIBUTED BY HASH(k1) BUCKETS 10
                             REFRESH MANUAL
                             PROPERTIES('replication_num' = '1')
                             AS SELECT k1,k2 from t1;
ALTER MATERIALIZED VIEW mv1 REFRESH ASYNC START('2022-08-15 21:15:00') EVERY(INTERVAL 1 minute);
SELECT * FROM INFORMATION_SCHEMA.task_runs;
```

### Expected behavior (Required)
`The task is scheduled to trigger`
### Real behavior (Required)
`task not triggered`
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.4-RELEASE 9744f36 |
+----------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10021
Fixes #10020
Fixes #10018
Fixes #10017
Fixes #10015

## Problem Summary(Required) ：

the main reason is processChangeRefreshScheme and createMaterializedView implementation is wrong.
## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by Astralidea** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 66 / 70 (94.29%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|3|33.33%|[334, 335]|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|2|3|66.67%|[130]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|34|35|97.14%|[279]|
|:large_blue_circle:|com/starrocks/sql/ast/AsyncRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|22|22|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ManualRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RefreshSchemeDesc.java|1|1|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java [hunk 1]
```diff
@@ -256,54 +257,59 @@ public void processAlterMaterializedView(AlterMaterializedViewStatement stmt)
...
-                    asyncRefreshSchemeDesc.getIntervalLiteral().getUnitIdentifier().getDescription());
-        }
-        MaterializedView.RefreshType oldRefreshType = refreshScheme.getType();
-        final String refreshType = refreshSchemeDesc.getType().name();
-        final MaterializedView.RefreshType newRefreshType = MaterializedView.RefreshType.valueOf(refreshType);
-        refreshScheme.setType(newRefreshType);
+        MaterializedView.RefreshType newRefreshType = refreshSchemeDesc.getType();
+        MaterializedView.RefreshType oldRefreshType = materializedView.getRefreshScheme().getType();
 
+        // TODO: The exact same refresh type does not need to drop and rebuild the task
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:263]: Is it easy to achieve this?

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java [hunk 2]
```diff
@@ -256,54 +257,59 @@ public void processAlterMaterializedView(AlterMaterializedViewStatement stmt)
...
-            // newRefreshType = MaterializedView.RefreshType.MANUAL
-            // for now SYNC is not supported
-            Task task = TaskBuilder.buildMvTask(materializedView, dbName);
-            task.setType(Constants.TaskType.EVENT_TRIGGERED);
-            taskManager.createTask(task, false);
+        }
+
+        taskManager.createTask(task, false);
+        // for event triggered type, run task
+        if (newRefreshType == MaterializedView.RefreshType.ASYNC &&
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:293]: remove newRefreshType == MaterializedView.RefreshType.ASYNC

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java [hunk 3]
```diff
@@ -256,54 +257,59 @@ public void processAlterMaterializedView(AlterMaterializedViewStatement stmt)
...
+                task.getType() == Constants.TaskType.EVENT_TRIGGERED) {
             taskManager.executeTask(task.getName());
         }
 
+        final MaterializedView.MvRefreshScheme refreshScheme = materializedView.getRefreshScheme();
+        if (refreshSchemeDesc instanceof AsyncRefreshSchemeDesc) {
+            AsyncRefreshSchemeDesc asyncRefreshSchemeDesc = (AsyncRefreshSchemeDesc) refreshSchemeDesc;
+            IntervalLiteral intervalLiteral = asyncRefreshSchemeDesc.getIntervalLiteral();
+            if (intervalLiteral != null) {
+                final IntLiteral step = (IntLiteral) asyncRefreshSchemeDesc.getIntervalLiteral().getValue();
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:303]:
```suggestion
                final IntLiteral step = (IntLiteral) intervalLiteral.getValue();
```

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java [hunk 4]
```diff
@@ -256,54 +257,59 @@ public void processAlterMaterializedView(AlterMaterializedViewStatement stmt)
...
+                final MaterializedView.AsyncRefreshContext asyncRefreshContext = refreshScheme.getAsyncRefreshContext();
+                asyncRefreshContext.setStartTime(Utils.getLongFromDateTime(asyncRefreshSchemeDesc.getStartTime()));
+                asyncRefreshContext.setStep(step.getLongValue());
+                asyncRefreshContext.setTimeUnit(
+                        asyncRefreshSchemeDesc.getIntervalLiteral().getUnitIdentifier().getDescription());
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:308]:
```suggestion
                        intervalLiteral.getUnitIdentifier().getDescription());
```

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java [hunk 5]
```diff
@@ -256,54 +257,59 @@ public void processAlterMaterializedView(AlterMaterializedViewStatement stmt)
...
+            }
+        }
+        refreshScheme.setType(newRefreshType);
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:311]: move it to line 299

File: fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java [hunk 6]
```diff
@@ -3270,30 +3269,39 @@ public void createMaterializedView(CreateMaterializedViewStatement stmt)
...
                 taskProperties.putAll(optHints);
             }
+
             TaskManager taskManager = GlobalStateMgr.getCurrentState().getTaskManager();
             taskManager.createTask(task, false);
-            // for async type, run task
-            if (materializedView.getRefreshScheme().getType() == MaterializedView.RefreshType.ASYNC &&
-                    task.getType() != Constants.TaskType.PERIODICAL) {
+            // for event triggered type, run task
+            if (refreshType == MaterializedView.RefreshType.ASYNC &&
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/server/LocalMetastore.java:3303]: remove refreshType == MaterializedView.RefreshType.ASYNC

**Review by ABingHuang — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/alter/Alter.java (hunk 1 above)
Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/alter/Alter.java:263]: It is not easy, because manual and asynchronous tasks can be reused, and periodically it is necessary to compare specific units to decide whether to drop and then create.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 64 / 68 (94.12%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|1|3|33.33%|[334, 335]|
|:large_blue_circle:|com/starrocks/scheduler/TaskManager.java|2|3|66.67%|[130]|
|:large_blue_circle:|com/starrocks/alter/Alter.java|33|34|97.06%|[279]|
|:large_blue_circle:|com/starrocks/sql/ast/AsyncRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/SyncRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/server/LocalMetastore.java|21|21|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/ManualRefreshSchemeDesc.java|1|1|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/analyzer/MaterializedViewAnalyzer.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/ast/RefreshSchemeDesc.java|1|1|100.00%|[]|

**Review by ABingHuang — APPROVED** [review]
LGTM

**Review by gengjun-git — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Review by meegoo — APPROVED** [review]

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
run starrocks_admit_test

**Comment by Astralidea** [comment]
@Mergifyio backport branch-2.4
