### PR TITLE
[BugFix] Fixed the bug that clusterid cannot be parsed when using --helper during upgrade

### LINKED ISSUE #48168: When I upgrade follower node to 3.3, got unrecongized "clusterId" error
### Steps to reproduce the behavior (Required)

 - upgrade follower node ( one of three frontend nodes)
 - 3.2.7 to 3.3.0
 
### Expected behavior (Required)
frontend start successful

### Real behavior (Required)
frontend start failed
```
2024-07-10 13:18:14.992Z INFO (main|1) [StarRocksFE.start():122] StarRocks FE starting, version: 3.3.0-19a3f66
2024-07-10 13:18:15.000Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():165] Get FQDN from local host by default, FQDN: my-node001-dc1.tossdata.bz, ip: 111.111.111.111, v6: false
2024-07-10 13:18:15.001Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():190] Try to match addr in fqdn mode, ip: 172.17.0.1, FQDN: 172.17.0.1
2024-07-10 13:18:15.002Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():190] Try to match addr in fqdn mode, ip: 111.111.111.111, FQDN: my-node001-dc1.tossdata.bz
2024-07-10 13:18:15.003Z INFO (main|1) [FrontendOptions.initAddrUseFqdn():200] Using FQDN from local host by default, FQDN: my-node001-dc1.tossdata.bz, ip: 111.111.111.111, v6: false
2024-07-10 13:18:15.132Z INFO (main|1) [ConsistencyChecker.initWorkTime():119] parsed startDate: 1970-01-01T23:00:00.000+0000, endDate: 1970-01-01T04:00:00.000+0000
2024-07-10 13:18:15.448Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role root[-1]
2024-07-10 13:18:15.455Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role db_admin[-2]
2024-07-10 13:18:15.455Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role cluster_admin[-3]
2024-07-10 13:18:15.456Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role user_admin[-4]
2024-07-10 13:18:15.456Z INFO (main|1) [AuthorizationMgr.initBuiltinRoleUnlocked():301] create built-in role public[-5]
2024-07-10 13:18:15.968Z INFO (main|1) [NodeMgr.getHelperNodes():619] get helper nodes: [my-node003-dc1.tossdata.bz:8784]
2024-07-10 13:18:16.019Z INFO (main|1) [NodeMgr.getFeNodeTypeAndNameFromHelpers():526] get fe node type FOLLOWER, name my-node001-dc1.tossdata.bz_8784_1711512966162 from my-node003-dc1.tossdata.bz:8781
2024-07-10 13:18:16.061Z INFO (main|1) [NodeMgr.getVersionFileFromHelper():673] Downloading version file from http://my-node003-dc1.tossdata.bz:8781/version
2024-07-10 13:18:16.390Z WARN (main|1) [NodeMgr.removeMetaFileIfExist():230] Deleted file /opt/starrocks/fe/meta/image/ROLE, maybe because the firstly startup failed.
2024-07-10 13:18:16.391Z WARN (main|1) [NodeMgr.removeMetaFileIfExist():230] Deleted file /opt/starrocks/fe/meta/image/VERSION, maybe because the firstly startup failed.
2024-07-10 13:18:16.391Z ERROR (main|1) [StarRocksFE.start():185] StarRocksFE start failed
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "clusterID" (class com.starrocks.persist.StorageInfo), not marked as ignorable (one known property: "imageJournalId"])
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 15] (through reference chain: com.starrocks.persist.StorageInfo["clusterID"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1138) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2224) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1709) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1687) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:320) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3809) ~[jackson-databind-2.15.2.jar:2.15.2]
        at com.starrocks.server.NodeMgr.getStorageInfo(NodeMgr.java:568) ~[starrocks-fe.jar:?]
        at com.starrocks.server.NodeMgr.getNewImageOnStartup(NodeMgr.java:699) ~[starrocks-fe.jar:?]
        at com.starrocks.server.NodeMgr.getClusterIdAndRoleOnStartup(NodeMgr.java:435) ~[starrocks-fe.jar:?]
        at com.starrocks.server.GlobalStateMgr.initialize(GlobalStateMgr.java:1055) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.start(StarRocksFE.java:128) ~[starrocks-fe.jar:?]
        at com.starrocks.StarRocksFE.main(StarRocksFE.java:83) ~[starrocks-fe.jar:?]
```
### StarRocks version (Required)
 - 3.3.0

### PR DESCRIPTION
**Pull request by HangyuanLiu**
## Why I'm doing:
Because clusterid was deleted in 3.3, but storageInfo sent in 3.2 still contains clusterid information, which causes Jackson to be unable to parse and report an error.
## What I'm doing:
Use GSON parsing directly instead (because our later codes all use GSON)
Fixes #48168

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.3
  - [ ] 3.2
  - [ ] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

**Review by gengjun-git — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/http/meta/MetaService.java:1]: not necessary change to this bug fix?

File: fe/fe-core/src/main/java/com/starrocks/persist/StorageInfo.java [hunk 1]
```diff
@@ -34,11 +34,14 @@
...
 package com.starrocks.persist;
 
+import com.google.gson.annotations.SerializedName;
+
 /**
  * This class is designed for sending storage information from master to standby master.
  * StorageInfo is easier to serialize to a Json String than class Storage
  */
 public class StorageInfo {
+    @SerializedName("imageJournalId")
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/persist/StorageInfo.java:44]: does this mean, the change should apply to 3.2.x in order to make it work to upgrade to v3.3?

Comment (HangyuanLiu) [reply fe/fe-core/src/main/java/com/starrocks/persist/StorageInfo.java:44]: Gson can ignore field in class in default

**Review by nshangyiming — APPROVED** [review]
