### PR TITLE
[pipeline] fix: make ResultSinkOperators share the same BufferControlBlock

### LINKED ISSUE #1099: [pipeline] ResultSinkOperator maybe lost some result chunks
### Steps to reproduce the behavior (Required)
```sql
set enable_pipeline_engine=true;
set pipeline_dop = 0;

create database test_array_1636350653726;
use test_array_1636350653726;
create table t0(c0 INT, c1 array<varchar(65533)>) duplicate key(c0) distributed by hash(c0) buckets 1 properties('replication_num'='1');
insert into t0 values(0, null),(1, ['x']),(1,['x']),(2, ['y']),(2, ['y'])
            
select
  ifnull(1,100),
  ifnull(null,100),
  ifnull([1,null,3][1],100),
  ifnull([1,null,3][2],100),
  ifnull([[1],[null],[3]][1][1],100),
  ifnull([[1],[null],[3]][2][1],100),
  ifnull(array_length([1,null,3]),100),
  ifnull(array_contains([1,null,3],null),100),
  ifnull(array_append([1,null,3],4)[4],100);
```

### Expected behavior (Required)

```
+----------------+-------------------+----------------------------+----------------------------+------------------------------------------------------+------------------------------------------------------+---------------------------------------+-----------------------------------------------+---------------------------------------------+
| ifnull(1, 100) | ifnull(NULL, 100) | ifnull([1,NULL,3][1], 100) | ifnull([1,NULL,3][2], 100) | ifnull([[1],ARRAY<tinyint(4)>[NULL],[3]][1][1], 100) | ifnull([[1],ARRAY<tinyint(4)>[NULL],[3]][2][1], 100) | ifnull(array_length([1,NULL,3]), 100) | ifnull(array_contains([1,NULL,3], NULL), 100) | ifnull(array_append([1,NULL,3], 4)[4], 100) |
+----------------+-------------------+----------------------------+----------------------------+------------------------------------------------------+------------------------------------------------------+---------------------------------------+-----------------------------------------------+---------------------------------------------+
|              1 |               100 |                          1 |                        100 |                                                    1 |                                                  100 |                                     3 |                                             1 |                                           4 |
+----------------+-------------------+----------------------------+----------------------------+------------------------------------------------------+------------------------------------------------------+---------------------------------------+-----------------------------------------------+---------------------------------------------+
1 row in set
```

### Real behavior (Required)
```
Empty set
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
The latest commit in the main branch.
```
+-------------------+
| current_version() |
+-------------------+
| UNKNOWN 4f3f82d   |
+-------------------+
```

### Reason
A `fragment_instance_id` can only have **ONE** sender, because `result_mgr` saves the mapping from `fragment_instance_id` to sender.  Therefore, all the `ResultSinkOperator` instances should share a same sander instead of using different senders themselves.

### PR DESCRIPTION
**Pull request by ZiheLiu**
A `fragment_instance_id` can only have **ONE** sender, because `result_mgr` saves the mapping from `fragment_instance_id` to sender. 
Therefore, sender is created in the same `ResultSinkOperatorFactory` and shared by all the `ResultSinkOperator` instances.

Fix #1099.

### CODE REVIEW

**Comment by ZiheLiu** [comment]
run starrocks_be_unittest

**Review by liuyehcf — DISMISSED** [review]

File: be/src/exec/pipeline/result_sink_operator.h [hunk 1]
```diff
@@ -61,7 +78,9 @@ class ResultSinkOperatorFactory final : public OperatorFactory {
     ~ResultSinkOperatorFactory() override = default;
 
     OperatorPtr create(int32_t degree_of_parallelism, int32_t driver_sequence) override {
-        return std::make_shared<ResultSinkOperator>(_id, _plan_node_id, _sink_type, _output_expr_ctxs);
+        ++_result_sinks_num;
```
Comment (satanson) [inline be/src/exec/pipeline/result_sink_operator.h:81]: _num_result_sinkers ++

File: be/src/exec/pipeline/result_sink_operator.cpp [hunk 2]
```diff
@@ -38,18 +35,19 @@ Status ResultSinkOperator::close(RuntimeState* state) {
...
         st = _writer->close();
+        _written_rows_num.fetch_add(_writer->get_written_rows(), std::memory_order_release);
     }
 
-    // Close sender
-    if (_sender != nullptr) {
-        if (_writer != nullptr) {
-            _sender->update_num_written_rows(_writer->get_written_rows());
+    // Close the shared sender when the last result sink operator is closing.
+    if (1 + _closed_result_sinks_num.fetch_add(1, std::memory_order_release) == _result_sinks_num) {
```
Comment (satanson) [inline be/src/exec/pipeline/result_sink_operator.cpp:42]: ```1 + _closed_result_sinks_num.fetch_add(1, std::memory_order_release) == _result_sinks_num```
is changed to 
```
1 == _num_result_sinkers-- 
```

**Review by satanson — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]
