### PR TITLE
[BugFix] Fix cancel alter table failed when table is not stable

### LINKED ISSUE #12529: [BUG] Cancel alter job failed when table is unstable
### Steps to reproduce the behavior (Required)
1. Create a cluster with 3 BE.
2. Create a table with replication_num = 3.
3. Stop a BE.
4. Add a column on the table.
5. Cancel the alter job.

### Expected behavior (Required)
Cancel can be done.

### Real behavior (Required)
Cancel failed with error:
```
Table xxx is not under SCHEMA_CHANGE.
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by gengjun-git**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #12529

## Problem Summary(Required) ：

If the table is unstable, its state will be changed to WAITING_STABLE. The cancel op will fail because it only checks the SCHEMA_CHANGE/ROLLUP state. To fix it, we should allow cancel op if table is in WAITING_STABLE state.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 4 (25.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|0|2|00.00%|[1408, 1409]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|2|50.00%|[1063]|

**Review by Astralidea — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java [hunk 1]
```diff
@@ -1059,7 +1059,8 @@ public void cancel(CancelStmt stmt) throws DdlException {
                 ErrorReport.reportDdlException(ErrorCode.ERR_NOT_OLAP_TABLE, tableName);
             }
             OlapTable olapTable = (OlapTable) table;
-            if (olapTable.getState() != OlapTableState.ROLLUP) {
+            if (olapTable.getState() != OlapTableState.ROLLUP
+                    && olapTable.getState() != OlapTableState.WAITING_STABLE) {
                 throw new DdlException("Table[" + tableName + "] is not under ROLLUP. "
```
Comment (nshangyiming) [inline fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java:1064]: we also need to update the message.

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/alter/MaterializedViewHandler.java]: done

**Comment by wanpengfei-git** [comment]
starrocks_be_unittest succeeded.

**Review by nshangyiming — APPROVED** [review]

**Review by Astralidea — APPROVED** [review]

**Comment by gengjun-git** [comment]
run starrocks_admit_test

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by gengjun-git** [comment]
run starrocks_fe_unittest

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 1 / 5 (20.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/SchemaChangeHandler.java|0|2|00.00%|[1409, 1410]|
|:large_blue_circle:|com/starrocks/alter/MaterializedViewHandler.java|1|3|33.33%|[1063, 1064]|

**Review by meegoo — APPROVED** [review]

**Comment by gengjun-git** [comment]
@mergify backport branch-2.2 branch-2.3 branch-2.4
