### PR TITLE
[BugFix] fix bug of null type to boolean type

### LINKED ISSUE #39346: COALESCE(timestampArray,[]) FAILS
### Steps to reproduce the behavior (Required)
```
CREATE TABLE `test_1` (
  `c1` bigint(20) NULL COMMENT "",
  `c2` array<datetime> NULL COMMENT ""
) ENGINE=OLAP
DUPLICATE KEY(`c1`)
DISTRIBUTED BY HASH(`c1`) BUCKETS 1
PROPERTIES (
"replication_num" = "3",
"in_memory" = "false",
"enable_persistent_index" = "false",
"replicated_storage" = "true",
"compression" = "LZ4"
);

insert into test_1 values(1, ["2024-01-01 01:00:00", "2024-01-01 02:00:00"]);
insert into test_1 values(2, ["2024-01-02 01:00:00", "2024-01-02 02:00:00"]);
insert into test_1 values(3, ["2024-01-03 01:00:00", "2024-01-03 02:00:00"]);

select coalesce(c2, []) from test_1;
```

### Expected behavior (Required)
It should return results

### Real behavior (Required)
```
Getting analyzing error. Detail message: types ARRAY<DATETIME> and ARRAY<BOOLEAN> cannot be matched.
```
### StarRocks version (Required)
3.1-cs branch

### PR DESCRIPTION
**Pull request by before-Sunrise**
Why I'm doing:
[] will be translated into array[boolean] from NULL_TYPE in FE because BE don't know anything NULL_TYPE, but when use some function like coalesce, we need calculate coalesce's arguments' common super type and cast arguments into common super type, but array[boolean] don't have common super type with many types like array[datetime] , but array[null_type] have common super type with array[datetime]

What I'm doing:
1.change null into array[null]/map{null,null}/struct(null)
2.find common super type
3.change ervery null type into boolean type

Fixes #issue
fix https://github.com/StarRocks/starrocks/issues/39346

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
- [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java [hunk 1]
```diff
@@ -209,8 +211,14 @@ private static Function resolveByDeducingReturnType(Function fn, Type[] inputArg
         if (deduce == null) {
             return null;
         }
-        Type[] resolvedArgTypes = resolveArgTypes(fn, inputArgTypes);
+        // Apply deduce logic first,then replace null to boolean
+        // because null type can have common super type with all types but boolean can't
+        Type[] resolvedArgTypes = Arrays.copyOf(inputArgTypes, inputArgTypes.length);
         Type newRetType = deduce.apply(resolvedArgTypes);
```
Comment (liuyehcf) [inline fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java:217]: Could these logic be put inside the function `resolveArgTypes`?

Comment (before-Sunrise) [reply fe/fe-core/src/main/java/com/starrocks/sql/analyzer/PolymorphicFunctionAnalyzer.java:217]: > Could these logic be put inside the function `resolveArgTypes`?

make resolveArgTypes' logic more clear

**Review by fzhedu — APPROVED** [review]

**Review by Seaven — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]
