### PR TITLE
[BugFix] Adding '-j' to run build.sh causes the compilation run on empty

### LINKED ISSUE #11597: [Build] Adding '-j' to run build.sh causes the compilation run on empty
### Steps to reproduce the behavior (Required)
1. Checkout to branch main, and run `sh build.sh -j 4`.
2. We can see `Successfully build StarRocks`, but it's not actually compiled, `BE`, `FE`, and `SPARK_DPP` are not compiled at all. As shown in the figure below：
sr

### StarRocks version (Required)
The latest version.

### PR DESCRIPTION
**Pull request by tomscut**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #11597

## Problem Summary(Required) ：
Adding '-j' to run build.sh causes the compilation run on empty. `BE`, `FE`, and `SPARK_DPP` are not compiled at all. See the issue #11597.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: build.sh [hunk 1]
```diff
@@ -145,7 +145,7 @@ else
             -h) HELP=1; shift ;;
             --help) HELP=1; shift ;;
             -j) PARALLEL=$2; shift 2 ;;
-            --) shift ;  break ;;
+            --) BUILD_BE=1 BUILD_FE=1 BUILD_SPARK_DPP=1 shift ;  break ;;
```
Comment (kangkaisen) [inline build.sh:148]: why build BE,FE,SPARK dpp all here?

Comment (tomscut) [reply build.sh]: Thanks for your comment. I updated it.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: build.sh [hunk 2]
```diff
@@ -119,7 +119,7 @@ fi
 USE_JEMALLOC=ON
 
 HELP=0
-if [ $# == 1 ] ; then
+if [[ $OPTS =~ "-j" ]] && [ $# == 3 ] || [ $# == 1 ] ; then
```
Comment (kangkaisen) [inline build.sh:122]: Don't get why we need the regex here.

Comment (tomscut) [reply build.sh:122]: Thanks for your comment. This make sure that the OPTS array contains `-j`.

**Review by satanson — APPROVED** [review]

File: build.sh (hunk 2 above)
Comment (satanson) [reply build.sh:122]: it is not required to add these code.
Please run 
```
 bash -x ./build.sh -j 12 --clean --be
```
you will see output as follows:
```
time make -j 12
```
this means that -j opt is handled correctly.

Comment (tomscut) [reply build.sh:122]: But when we run sh build.sh -j 12, without other params, will cause the compilation run on empty. We can see this [issue](https://github.com/StarRocks/starrocks/issues/11597).

**Review by kangkaisen — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test
