### PR TITLE
Fix colocate checker concurrent modify exception

### LINKED ISSUE #2088: colocate info can't deleted after drop database
### Steps to reproduce the behavior (Required)
Create lots of tables  with colocate group and drop database without force concurrently
### Expected behavior (Required)
group info are deleted
### Real behavior (Required)
group info can't deleted
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
d57d156

### PR DESCRIPTION
**Pull request by gengjun-git**
Make a copy set of groupIds to avoid ConcurrentModificationException

### CODE REVIEW

**Review by imay — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java [hunk 1]
```diff
@@ -312,7 +312,8 @@ public GroupId getGroup(long tableId) {
     public Set<GroupId> getAllGroupIds() {
         readLock();
         try {
-            return group2Tables.keySet();
+            // make a copy set to avoid ConcurrentModificationException
+            return new HashSet<>(group2Tables.keySet());
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:316]:
```suggestion
            return Sets.newHashSet(group2Tables.keySet());
```

Comment (gengjun-git) [reply fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:316]: Why we must use the google api? Sets.newHashSet has an additional layer of judgment inside.

**Comment by wyb** [comment]
run starrocks_fe_unittest

File: fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java (hunk 1 above)
Comment (wyb) [reply fe/fe-core/src/main/java/com/starrocks/catalog/ColocateTableIndex.java:316]: It's not necessary.

**Review by wyb — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]
