### PR TITLE
[StarRocks On ES] Wrong _id type causes table creation to fail

### LINKED ISSUE #7490: [StarRocks On ES] BE crashed when `_id` is  int or bigint
### Steps to reproduce the behavior (Required)
1.  create ES external table，and set `int` type for `_id`

```
CREATE EXTERNAL TABLE `test` (
  `_id` int(20),
  `k1` bigint(20) NULL COMMENT "",
  `k2` varchar(20) NULL COMMENT "",
  `k3` varchar(20) NULL COMMENT ""
) ENGINE=ELASTICSEARCH 
COMMENT "ELASTICSEARCH"
PROPERTIES (
"hosts" = "http://172.0.0.1:9200",
"user" = "",
"password" = "",
"index" = "test",
"type" = "_doc"
); 
```

2.  执行查询

```
     select * from test;
```

3. BE crashed

```
ERROR 1064 (HY000): Backend not found. Check if any backend is down or not
```

### Expected behavior (Required)
return null value for id column

### Real behavior (Required)
BE crashed

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by RowenWoo**
## What type of PR is this：
- [x] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes  https://github.com/StarRocks/starrocks/issues/7490

## Problem Summary(Required) ：

Some users want to get _id, but set the wrong type, resulting in some unexpected errors.  
Therefore, it may be necessary for us to add verification when creating the table

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 2 / 4 (50.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/catalog/EsTable.java|2|4|50.00%|

**Comment by imay** [comment]
@RowenWoo could you add an issue to track this problem?

**Comment by RowenWoo** [comment]
> @RowenWoo could you add an issue to track this problem?

done

**Review by caneGuy — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java [hunk 1]
```diff
@@ -261,6 +261,11 @@ private void validate(Map<String, String> properties) throws DdlException {
                 sslEnabled = false;
             }
         }
+        Column idColumn = getColumn("_id");
+        if (idColumn != null && !(idColumn.getPrimitiveType() == PrimitiveType.VARCHAR
+                || idColumn.getPrimitiveType() == PrimitiveType.CHAR)) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:266]: Is the code indent  correct ?

Comment (RowenWoo) [reply fe/fe-core/src/main/java/com/starrocks/catalog/EsTable.java:266]: I think maybe correct? it can pass the fe-checkstyle

**Review by murphyatwork — APPROVED** [review]

**Comment by mofeiatwork** [comment]
@RowenWoo which branch do you need to backport?

**Comment by RowenWoo** [comment]
@[mofeiatwork](https://github.com/mofeiatwork)  maybe need to backport branch-2.0  branch-2.1  branch-2.2  branch-2.3

**Review by imay — APPROVED** [review]
