### PR TITLE
[BugFix] Fix CN crash when scanning empty tablet with physical split enabled

### LINKED ISSUE #70280: [Bug] CN crash when scanning empty tablet with physical split enabled
### Steps to reproduce the behavior (Required)
1. Have a shared-data SR cluster
2. When a tablet has no rowsets (empty tablet) but PhysicalSplitMorselQueue
is created with need_split=true, accessing _tablet_rowsets[_tablet_idx][_rowset_idx]
in _cur_rowset() causes array out-of-bounds access, resulting in SIGSEGV.

### Expected behavior (Required)
Normal end query

### Real behavior (Required)
Cn crash with Stack:
```text
query_id:b3957b5a-1f62-11f1-9da9-fa163efd6e7f, fragment_instance:b3957b5a-1f62-11f1-9da9-fa163efd6ead, plan_node_id:16
*** Aborted at 1773464421 (unix time) try "date -d @1773464421" if you are using GNU date ***
PC: @          0x533e3e0 starrocks::pipeline::PhysicalSplitMorselQueue::_try_get_split_from_single_tablet()
*** SIGSEGV (@0x8) received by PID 10429 (TID 0x14ebd6aaa700) LWP(11134) from PID 8; stack trace: ***
    @     0x14ec2e932e67 __pthread_once_slow
    @          0xbe289d4 google::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)
    @     0x14ec2e935dd0 (/usr/lib64/libpthread-2.28.so+0x12dcf)
    @          0x533e3e0 starrocks::pipeline::PhysicalSplitMorselQueue::_try_get_split_from_single_tablet()
    @          0x533ed1c starrocks::pipeline::PhysicalSplitMorselQueue::try_get()
    @          0x7c45828 starrocks::lake::TabletReader::open(starrocks::TabletReaderParams const&)
    @          0x886b7ec starrocks::connector::LakeDataSource::init_tablet_reader(starrocks::RuntimeState*)
    @          0x886c144 starrocks::connector::LakeDataSource::open(starrocks::RuntimeState*)
    @          0x536243e starrocks::pipeline::ConnectorChunkSource::_open_data_source(starrocks::RuntimeState*, bool*)
    @          0x536284d starrocks::pipeline::ConnectorChunkSource::_read_chunk(starrocks::RuntimeState*, std::shared_ptr<starrocks::Chunk>*)
    @          0x58671f0 starrocks::pipeline::ChunkSource::buffer_next_batch_chunks_blocking(starrocks::RuntimeState*, unsigned long, starrocks::workgroup::WorkGroup const*)
    @          0x534fb3d auto starrocks::pipeline::ScanOperator::_trigger_next_scan(starrocks::RuntimeState*, int)::{lambda(auto:1&)#1}::operator()<starrocks::workgroup::YieldContext>(starrocks::workgroup::YieldContext&) const [clone .isra.0]
    @          0x54968bf starrocks::workgroup::ScanExecutor::worker_thread()
    @          0x45d3e57 starrocks::ThreadPool::dispatch_thread()
    @          0x45cac30 starrocks::Thread::supervise_thread(void*)
    @     0x14ec2e92b2de start_thread
    @     0x14ec2c4e7e83 __GI___clone

```

### StarRocks version (Required)
3.5.11

### PR DESCRIPTION
**Pull request by sfwang218**
## Why I'm doing:

Fixes #70280 

## What I'm doing:

When a tablet has no rowsets (empty tablet) but PhysicalSplitMorselQueue
is created with need_split=true, accessing _tablet_rowsets[_tablet_idx][_rowset_idx]
in _cur_rowset() causes array out-of-bounds access, resulting in SIGSEGV.
 
This fix adds:
1. Boundary checks in _cur_rowset() and related functions to handle empty
   inner vectors gracefully
2. Early return in TabletReader::open() when _rowsets is empty to prevent
   creating PhysicalSplitMorselQueue with empty rowsets
3. Unit test for empty tablet scenario with split enabled

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
  - [ ] This pr needs auto generate documentation
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 4.1
  - [x] 4.0
  - [x] 3.5
  - [ ] 3.4

### CODE REVIEW

**Comment by CelerData-Reviewer** [comment]
@codex review

File: be/test/storage/lake/tablet_reader_test.cpp [hunk 1]
```diff
@@ -1131,4 +1133,71 @@ TEST_F(LakeDuplicateTablet10kColumnReaderTest, DISABLED_test_bench_5kcolumn_init
...
+    // Should return end of file immediately for empty tablet
+    ASSERT_TRUE(reader->get_next(read_chunk_ptr.get()).is_end_of_file());
+
+    reader->close();
+}
+
+// Test case for issue: PhysicalSplitMorselQueue crashes when tablet has no rowsets
+// This test directly verifies the boundary checks in PhysicalSplitMorselQueue methods:
+// _cur_rowset, _cur_segment, _is_last_split_of_current_morsel, _next_segment, _init_segment
+TEST_F(LakeDuplicateTabletReaderTest, test_physical_split_morsel_queue_with_empty_rowset) {
```
Comment (kevincai) [inline be/test/storage/lake/tablet_reader_test.cpp]: shall pull this UT out of this LakeTabletReaderTest, make it in separate PhysicalSplitMorselQueue and test the empty rowset code path.

Comment (sfwang218) [reply be/test/storage/lake/tablet_reader_test.cpp]: OK, done

**Review by kevincai — DISMISSED** [review]

**Review by kevincai — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]
