### PR TITLE
[BugFix] fix incorrect scan metrics in FE

### LINKED ISSUE #27786: table_scan_rows/table_scan_bytes never update in pipeline engine
FE has some scan-related metrics, such as table_scan_rows and table_scan_bytes, we can find out hotspots according to them.

but in pipeline engine, these metrics are never updated.

you can get them by the following command, and the values are always be 0
```shell
curl -u ${user}:${passwd}   'http://${fe_ip}:${fe_http_port}/metrics?type=json&with_table_metrics=all' | grep table_scan_
```

the reason is that we didn't pass stats_item in query_statistics.
image

### StarRocks version (Required)
main 5777c3735b1d6489c5ab4e6370e48ed86fa9f16d

### PR DESCRIPTION
**Pull request by silverbullet233**
Fixes #27786 #27952
1. for issue 27786,  maintain table-level scan stats and pass them to FE
2. for issue 27952
   1. make sure scan statistics must be updated in time after OlapScanOperator finished
   2. if an eos request contains valid query statistics in ExchangeSink, we should not skip it

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5
  - [x] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by murphyatwork — DISMISSED** [review]

**Review by nshangyiming — DISMISSED** [review]

**Review by liuyehcf — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/exec/pipeline/query_context.h [hunk 1]
```diff
@@ -213,6 +217,20 @@ class QueryContext : public std::enable_shared_from_this<QueryContext> {
     std::atomic<int64_t> _delta_cpu_cost_ns = 0;
     std::atomic<int64_t> _delta_scan_rows_num = 0;
     std::atomic<int64_t> _delta_scan_bytes = 0;
+
+    struct ScanStats {
+        std::atomic<int64_t> total_scan_rows_num = 0;
+        std::atomic<int64_t> total_scan_bytes = 0;
```
Comment (kangkaisen) [inline be/src/exec/pipeline/query_context.h:223]: why need total_scan_rows_num and delta_scan_rows_num both?

File: be/src/exec/pipeline/query_context.cpp [hunk 2]
```diff
@@ -179,24 +179,61 @@ std::shared_ptr<QueryStatistics> QueryContext::intermediate_query_statistic() {
...
 
 std::shared_ptr<QueryStatistics> QueryContext::final_query_statistic() {
     DCHECK(_is_result_sink) << "must be the result sink";
     auto res = std::make_shared<QueryStatistics>();
-    res->add_scan_stats(_total_scan_rows_num, _total_scan_bytes);
     res->add_cpu_costs(cpu_cost());
     res->add_mem_costs(mem_cost_bytes());
 
+    {
+        std::lock_guard l(_scan_stats_lock);
```
Comment (kangkaisen) [inline be/src/exec/pipeline/query_context.cpp:206]: if we do this work in FE, then we needn't lock, needn't maintain the tablet id map

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/exec/pipeline/exchange/sink_buffer.cpp [hunk 3]
```diff
@@ -295,7 +295,30 @@ Status SinkBuffer::_try_to_send_rpc(const TUniqueId& instance_id, const std::fun
...
+                            for (int i = 0; i < query_statistics.stats_items_size(); ++i) {
+                                const auto& stats_item = query_statistics.stats_items(i);
+                                if (stats_item.scan_rows() > 0 || stats_item.scan_bytes() > 0) {
+                                    should_skip = false;
+                                    break;
+                                }
+                            }
+                        }
+                        if (!should_skip) {
+                            request.params->set_eos(false);
```
Comment (ZiheLiu) [inline be/src/exec/pipeline/exchange/sink_buffer.cpp:316]: Could we just merge all the statistics of non-last EOS empty packages to the last EOS package, to avoid send too many packages, especially for the large pipeline_dop?

Comment (silverbullet233) [reply be/src/exec/pipeline/exchange/sink_buffer.cpp:316]: > Could we just merge all the statistics of non-last EOS empty packages to the last EOS package, to avoid send too many packages, especially for the large pipeline_dop?

good idea…I will try to optimize it

Comment (liuyehcf) [reply be/src/exec/pipeline/exchange/sink_buffer.cpp:316]: And maybe put these logic into a separate function for code clarity.

File: be/src/exec/pipeline/scan/olap_scan_operator.cpp [hunk 4]
```diff
@@ -31,6 +31,12 @@ OlapScanOperatorFactory::OlapScanOperatorFactory(int32_t id, ScanNode* scan_node
         : ScanOperatorFactory(id, scan_node), _ctx_factory(std::move(ctx_factory)) {}
 
 Status OlapScanOperatorFactory::do_prepare(RuntimeState* state) {
+    auto olap_scan_node = dynamic_cast<OlapScanNode*>(_scan_node);
+    DCHECK(olap_scan_node != nullptr);
+    const TOlapScanNode& thrift_olap_scan_node = olap_scan_node->thrift_olap_scan_node();
+    const TupleDescriptor* tuple_desc = state->desc_tbl().get_tuple_descriptor(thrift_olap_scan_node.tuple_id);
+    DCHECK(tuple_desc != nullptr);
+    _ctx_factory->set_scan_table_id(tuple_desc->table_desc()->table_id());
```
[the remark this answers is not in the document]
Comment (ZiheLiu) [reply be/src/exec/pipeline/scan/olap_scan_operator.cpp:39]: Could we make all the table ids ready when preparing `query_ctx`? Then we needn't lock any more.
But getting all the ids is a little bit trick and I don't know whether it proper, since we need some complex and low-maintenance processes:
1. traverse on `state->desc_tbl()::get_tuple_descs` 
2. check each `tuple_desc::table_desc` is non-null and instance of `OlapTableDescriptor`
3. get table id from `tuple_desc::table_desc`.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ZiheLiu — DISMISSED** [review]

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

File: be/src/exec/pipeline/scan/olap_scan_operator.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (silverbullet233) [reply be/src/exec/pipeline/scan/olap_scan_operator.cpp:39]: > Could we make all the table ids ready when preparing `query_ctx`? Then we needn't lock any more. But getting all the ids is a little bit trick and I don't know whether it proper, since we need some complex and low-maintenance processes:
> 
> 1. traverse on `state->desc_tbl()::get_tuple_descs`
> 2. check each `tuple_desc::table_desc` is non-null and instance of `OlapTableDescriptor`
> 3. get table id from `tuple_desc::table_desc`.

this a little trick, after upgrading phmap, we can use parallel_flat_hash_map directly and the lock will be removed

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]


:heart_eyes: **pass** : 0 / 0 (0%)

**Review by ZiheLiu — APPROVED** [review]

**Review by liuyehcf — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.4

**Comment by silverbullet233** [comment]
@mergify backport branch-2.3
