### PR TITLE
[BugFix] Fix the bug that can't get the variable when connect the Mar…

### LINKED ISSUE #9105: mariadb connector error
### Real behavior (Required)
```
java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=localhost)(port=9030)(type=master) : (conn=0) could not load system variables

	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:197)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1394)
	at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
	at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
	at org.mariadb.jdbc.Driver.connect(Driver.java:89)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.starrocks.pseudocluster.PseudoClusterTest.testCreateTabletAndInsert(PseudoClusterTest.java:34)
Caused by: java.sql.SQLNonTransientConnectionException: (conn=0) could not load system variables
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:188)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.requestSessionDataWithShow(AbstractConnectProtocol.java:1114)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.additionalData(AbstractConnectProtocol.java:1127)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.postConnectionQueries(AbstractConnectProtocol.java:895)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:600)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1389)
	... 6 more
Caused by: java.sql.SQLNonTransientConnectionException: (conn=0) could not load system variables. socket connected: true
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:184)
	at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.requestSessionDataWithShow(AbstractConnectProtocol.java:1107)
	... 10 more

possibly we should support these SQL statements:

  private static final byte[] SESSION_QUERY =
      ("SELECT @@max_allowed_packet,"
              + "@@system_time_zone,"
              + "@@time_zone,"
              + "@@auto_increment_increment")
          .getBytes(StandardCharsets.UTF_8);
  private static final byte[] IS_MASTER_QUERY =
      "select @@innodb_read_only".getBytes(StandardCharsets.UTF_8);

          "SHOW VARIABLES WHERE Variable_name in ("
              + "'max_allowed_packet',"
              + "'system_time_zone',"
              + "'time_zone',"
              + "'auto_increment_increment')");
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by kingpluspk**
…iaDB(#9105)

## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #9105 

## Problem Summary(Required) ：

In the MySQL client, run the following command, can't get the variable of 'innodb_read_only'. Fix it and make the default value of 'innodb_read_only' is true.
mysql> SELECT @@max_allowed_packet,@@system_time_zone,@@time_zone,@@auto_increment_increment;
+------------------------------+----------------------------+---------------------+------------------------------------+
| @@SESSION.max_allowed_packet | @@SESSION.system_time_zone | @@SESSION.time_zone | @@SESSION.auto_increment_increment |
+------------------------------+----------------------------+---------------------+------------------------------------+
| 1048576 | Asia/Shanghai | Asia/Shanghai | 1 |
+------------------------------+----------------------------+---------------------+------------------------------------+
1 row in set (0.03 sec)

mysql> SELECT @@innodb_read_only;
+----------------------------+
| @@SESSION.innodb_read_only |
+----------------------------+
| 1 |
+----------------------------+
1 row in set (0.08 sec)

mysql> set @@innodb_read_only = false;
Query OK, 0 rows affected (0.06 sec)

mysql> SELECT @@innodb_read_only;
+----------------------------+
| @@SESSION.innodb_read_only |
+----------------------------+
| 0 |
+----------------------------+
1 row in set (0.03 sec)
## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java [hunk 1]
```diff
@@ -1294,6 +1306,7 @@ public void readFields(DataInput in) throws IOException {
             netBufferLength = in.readInt();
             sqlSafeUpdates = in.readInt();
             timeZone = Text.readString(in);
+            innodbReadOnly = in.readBoolean();
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:1309]: This modification is not needed now.

Comment (kingpluspk) [reply fe/fe-core/src/main/java/com/starrocks/qe/SessionVariable.java:1309]: Got it

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 5 / 5 (100.00%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/qe/SessionVariable.java|5|5|100.00%|[]|

**Review by decster — APPROVED** [review]

**Review by imay — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by Johnsonginati** [comment]
@kingpluspk Thank you for your contribution！
