### PR TITLE
[BugFix] Redefine mv's staleness to make it more clear

### LINKED ISSUE #27371: [materialized view optimization] mv_rewrite_staleness_second parameter invalid
### Steps to reproduce the behavior (Required)
```
CREATE TABLE t1 (
    k1 int,
    k2 int
)
DUPLICATE KEY(k1);
INSERT INTO t1 VALUES (1,1),(1,2);
CREATE MATERIALIZED VIEW mv1 REFRESH MANUAL PROPERTIES ("mv_rewrite_staleness_second"="5") AS SELECT k1,sum(k2) FROM t1 group by k1;

REFRESH MATERIALIZED VIEW mv1 with sync mode;
INSERT INTO t1 VALUES (2,2);
SELECT k1,sum(k2) FROM t1 group by k1 order by 1;
select sleep(5);
REFRESH MATERIALIZED VIEW mv1 with sync mode;
INSERT INTO t1 VALUES (2,2);
SELECT k1,sum(k2) FROM t1 group by k1 order by 1;
```

### Expected behavior (Required)
```
+------+---------+
| k1   | sum(k2) |
+------+---------+
|    1 |       3 |
|    2 |       2 |
+------+---------+
```
### Real behavior (Required)
```
+------+---------+
| k1   | sum(k2) |
+------+---------+
|    1 |       3 |
|    2 |       4 |
+------+---------+
```
### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
`branch-3.1-0f690e6`

### PR DESCRIPTION
**Pull request by LiShuMing**
Fixes #27371 

Define1:  Table' LastRrefshTime =  max(partitions' OlapTable's getVisibleVersionTime)
Define2:  MV's LastRrefshTime = max(base tables' LastRrefshTime)  
Define3:  MV's Staleness =  max(BaseTable' LastRrefshTime) at query time - MV's LastRrefshTime at query time

Check MV's Staleness is satisfied:
- Check the MV is satisfied for its staleness.
- If it is MV on MVs, check all its sub MVs are valid and satisfied for its staleness

staleness

## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Checklist:
- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5
  - [ ] 2.4

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 40 / 46 (86.96%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[641, 642, 643]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|35|38|92.11%|[618, 641, 656]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 49 / 59 (83.05%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[641, 642, 643]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|36|43|83.72%|[621, 622, 623, 629, 640, 644, 668]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|6|6|100.00%|[]|

File: fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java [hunk 1]
```diff
@@ -884,4 +886,18 @@ public static String toString(Object o) {
...
         return o.toString();
     }
+    
+    /**
+     * Return the max refresh timestamp of all partition infos.
+     */
+    public static long  getMaxTablePartitionInfoRefreshTime(
+            Collection<Map<String, MaterializedView.BasePartitionInfo>> partitionInfos) {
+        return partitionInfos.stream()
+                .map(x -> x.values().stream().map(
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java:896]: .flatMap( x -> return Optional )

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 2]
```diff
@@ -548,18 +551,17 @@ public Expr getFirstPartitionRefTableExpr() {
     }
 
     public Set<String> getUpdatedPartitionNamesOfOlapTable(OlapTable baseTable) {
+        // Ignore partitions when mv 's last refreshed time period is less than `maxMVRewriteStaleness`
+        if (isStalenessSatisfy()) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:555]: `isStalenessSatisfied` , or `satisfyStaleness` ?

Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:555]: if (!satisfyStaleness) { return empty } ?

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 3]
```diff
@@ -594,14 +596,77 @@ public Set<String> getUpdatedPartitionNamesOfOlapTable(OlapTable baseTable) {
...
+     * @return Return max timestamp of all table's max refresh timestamp
+     *          which is computed by checking all its partitions' modified time.
+     */
+    public Optional<Long> maxBaseTableRefreshTimestamp() {
+        long maxRefreshTimestamp = -1;
+        for (BaseTableInfo baseTableInfo : baseTableInfos) {
+            Table baseTable = baseTableInfo.getTable();
+            if (baseTable instanceof OlapTable) {
+                OlapTable olapTable = (OlapTable) baseTable;
+                if (olapTable instanceof MaterializedView) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:609]: if (table is MV) 
if (table is Olap) 
if (table is externa) ?

Comment (mofeiatwork) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:609]: what if it's a view

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 4]
```diff
@@ -594,14 +596,77 @@ public Set<String> getUpdatedPartitionNamesOfOlapTable(OlapTable baseTable) {
...
-    private boolean isLessThanMVRewriteStaleness() {
+    /**
+     * @return Return max timestamp of all table's max refresh timestamp
+     *          which is computed by checking all its partitions' modified time.
+     */
+    public Optional<Long> maxBaseTableRefreshTimestamp() {
+        long maxRefreshTimestamp = -1;
+        for (BaseTableInfo baseTableInfo : baseTableInfos) {
+            Table baseTable = baseTableInfo.getTable();
+            if (baseTable instanceof OlapTable) {
```
Comment (mofeiatwork) [inline fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:607]: we have many if-else branch for the `BaseTableInfo`. 

we should refactor the `BaseTableInfo` into the Inheritance style, with `OlapBaseTableInfo extends BaseTableInfo`, `HiveBaseTableInfo extends BaseTableInfo`

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java (hunk 2 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:555]: > if (!satisfyStaleness) { return empty } ?

`getUpdatedPartitionNamesOfOlapTable ` needs updated partitions' names, just return empty if staleness is satisfied and no need check anymore.

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java (hunk 3 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:609]: > what if it's a view
Good. Ignore view because we can get refresh timestamp from base tables. Other types' base table info will return directly.

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java (hunk 4 above)
Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:607]: Before we can only support olapTable and HiveTable's base table infos.
Later we may support more and more Tables as BaseTable, it may be a big change, Maybe we can do it later.

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:heart_eyes: **pass** : 47 / 55 (85.45%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[641, 642, 643]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|42|47|89.36%|[618, 641, 656, 676, 716]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|3|3|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage Check]

:disappointed: **fail** : 52 / 67 (77.61%)




#### file detail

|   |path|covered_line|new_line|coverage|not_covered_line_detail|
|----|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/alter/AlterJobMgr.java|0|3|00.00%|[642, 643, 644]|
|:large_blue_circle:|com/starrocks/catalog/MaterializedView.java|39|51|76.47%|[619, 620, 621, 623, 624, 625, 626, 628, 634, 645, 651, 675]|
|:large_blue_circle:|com/starrocks/scheduler/PartitionBasedMvRefreshProcessor.java|5|5|100.00%|[]|
|:large_blue_circle:|com/starrocks/common/util/DateUtils.java|2|2|100.00%|[]|
|:large_blue_circle:|com/starrocks/sql/optimizer/rule/transformation/materialization/MvUtils.java|6|6|100.00%|[]|

**Review by murphyatwork — APPROVED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java [hunk 5]
```diff
@@ -605,14 +607,84 @@ public Set<String> getUpdatedPartitionNamesOfOlapTable(OlapTable baseTable) {
...
+                Optional<Long> maxPartitionRefreshTimestamp =
+                        partitionNameWithPartition.values().stream().map(com.starrocks.connector.PartitionInfo::getModifiedTime)
+                                .max(Long::compareTo);
+                if (!maxPartitionRefreshTimestamp.isPresent()) {
+                    return Optional.empty();
+                }
+                maxRefreshTimestamp = Math.max(maxPartitionRefreshTimestamp.get(), maxRefreshTimestamp);
+            } else if (baseTable instanceof View) {
+                // continue
+            } else {
```
Comment (ABingHuang) [inline fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:650]: what if iceberg and hudi table?

Comment (LiShuMing) [reply fe/fe-core/src/main/java/com/starrocks/catalog/MaterializedView.java:650]: Good question. 
To be more safe, now We don't support it for staleness. We can support it later?

**Review by ABingHuang — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.1
