### PR TITLE
[BugFix] properly handle orc reader decompress error

### LINKED ISSUE #61453: [BE][ORC] handle decompress failure error properly
### Steps to reproduce the behavior (Required)

`./be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd` is an zstd corrupted orc file, orc column reader doesn't detect the corruption and continue process it with corrupted data.

```
$ java -jar ~/bin/orc-tools-2.2.0-uber.jar data -n 6000 ./be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd >/dev/null
Processing data file be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd [length: 76791]
Unable to dump data for file: ./be/test/exec/test_data/orc_scanner/tpch_10k.orc.zstd
com.github.luben.zstd.ZstdException: Restored data doesn't match checksum
	at com.github.luben.zstd.ZstdDecompressCtx.decompressByteArray(ZstdDecompressCtx.java:227)
	at com.github.luben.zstd.Zstd.decompressByteArray(Zstd.java:447)
	at org.apache.orc.impl.ZstdCodec.decompress(ZstdCodec.java:240)
	at org.apache.orc.impl.InStream$CompressedStream.readHeader(InStream.java:521)
	at org.apache.orc.impl.InStream$CompressedStream.ensureUncompressed(InStream.java:548)
	at org.apache.orc.impl.InStream$CompressedStream.read(InStream.java:527)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.readValues(RunLengthIntegerReaderV2.java:57)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.next(RunLengthIntegerReaderV2.java:329)
	at org.apache.orc.impl.RunLengthIntegerReaderV2.nextVector(RunLengthIntegerReaderV2.java:379)
	at org.apache.orc.impl.TreeReaderFactory$IntTreeReader.nextVector(TreeReaderFactory.java:676)
	at org.apache.orc.impl.reader.tree.StructBatchReader.readBatchColumn(StructBatchReader.java:65)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatchForLevel(StructBatchReader.java:100)
	at org.apache.orc.impl.reader.tree.StructBatchReader.nextBatch(StructBatchReader.java:77)
	at org.apache.orc.impl.RecordReaderImpl.nextBatch(RecordReaderImpl.java:1439)
	at org.apache.orc.tools.PrintData.printJsonData(PrintData.java:208)
	at org.apache.orc.tools.PrintData.main(PrintData.java:289)
	at org.apache.orc.tools.Driver.main(Driver.java:124)

```

### Expected behavior (Required)

SR be able to detect the corruption and report error

### Real behavior (Required)

SR silent the error and produces corrupted data.

### StarRocks version (Required)
 - 3.5, main

### PR DESCRIPTION
**Pull request by kevincai**
* handle zstd decompress failure, throw runtime_error exception
* fix orc_scanner tpch_10k.orc.zstd, it's corrupted. Replace it with correct test file and update the related test cases.

## What I'm doing:

Fixes #61453

```
W20250731 14:03:36.155932 140689866881216 stack_util.cpp:437] 2025-07-31 14:03:35.735335, query_id=00000000-0000-0000-0000-000000000000, fragment_instance_id=00000000-0000-0000-0000-000000000000 throws exception: std::runtime_error, trace:
     @         0x1efc90b8  starrocks::get_stack_trace[abi:cxx11]()
    @         0x1efcbc08  __wrap___cxa_throw
    @         0x240c320d  orc::ZSTDDecompressionStream::decompress(char const*, unsigned long, char*, unsigned long)
    @         0x240c2737  orc::BlockDecompressionStream::NextDecompress(void const**, int*, unsigned long)
    @         0x240c1348  orc::DecompressionStream::Next(void const**, int*)
    @         0x240d04c3  orc::RleDecoderV2::readByte()
    @         0x240cf28e  orc::RleDecoderV2::next(long*, unsigned long, char const*)
    @         0x240aea6e  orc::IntegerColumnReader::next(orc::ColumnVectorBatch&, unsigned long, char*)
    @         0x240b6887  void orc::StructColumnReader::nextInternal<false, false>(std::vector<std::unique_ptr<orc::ColumnReader, std::default_delete<orc::ColumnReader> >, std::allocator<std::unique_ptr<orc::ColumnReader, std::default_delete<orc::ColumnReader> > > > const&, std::ve
    @         0x240b29ab  orc::StructColumnReader::next(orc::ColumnVectorBatch&, unsigned long, char*)
    @         0x24094ed6  orc::RowReaderImpl::next(orc::ColumnVectorBatch&, orc::RowReader::ReadPosition*)
    @         0x1d0aa657  starrocks::OrcChunkReader::read_next(orc::RowReader::ReadPosition*)
    @         0x164b1031  starrocks::OrcChunkReaderTest_CorruptedZstdOrcFile_Test::TestBody()
    @         0x25290a34  void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
    @         0x2528325e  testing::Test::Run()
    @         0x252833be  testing::TestInfo::Run()
    @         0x252834a7  testing::TestSuite::Run()
    @         0x25283a04  testing::internal::UnitTestImpl::RunAllTests()
    @         0x25283c14  testing::UnitTest::Run()
    @         0x1843c8b1  RUN_ALL_TESTS()
    @         0x1843a2f3  starrocks::init_test_env(int, char**)
    @         0x1843a692  main
    @     0x7ff4e9c1ed90  (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    @     0x7ff4e9c1ee40  __libc_start_main
    @         0x14a17025  _start
 
W20250731 14:03:36.156131 140689866881216 orc_chunk_reader.cpp:458]     @         0x1efc90b8  starrocks::get_stack_trace[abi:cxx11]()
    @         0x1d0aa712  starrocks::OrcChunkReader::read_next(orc::RowReader::ReadPosition*)
    @         0x164b1031  starrocks::OrcChunkReaderTest_CorruptedZstdOrcFile_Test::TestBody()
    @         0x25290a34  void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)
    @         0x2528325e  testing::Test::Run()
    @         0x252833be  testing::TestInfo::Run()
    @         0x252834a7  testing::TestSuite::Run()
    @         0x25283a04  testing::internal::UnitTestImpl::RunAllTests()
    @         0x25283c14  testing::UnitTest::Run()
    @         0x1843c8b1  RUN_ALL_TESTS()
    @         0x1843a2f3  starrocks::init_test_env(int, char**)
    @         0x1843a692  main
    @     0x7ff4e9c1ed90  (/usr/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    @     0x7ff4e9c1ee40  __libc_start_main
    @         0x14a17025  _start
W20250731 14:03:36.350251 140689866881216 orc_chunk_reader.cpp:460] ORC reader read file  failed. Reason is Error while calling ZSTD_decompressDCtx for zstd. error:Corrupted block detected.
```

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

File: be/src/formats/orc/apache-orc/c++/src/Compression.cc [hunk 1]
```diff
@@ -1086,7 +1086,12 @@ class ZSTDDecompressionStream : public BlockDecompressionStream {
 
 uint64_t ZSTDDecompressionStream::decompress(const char* inputPtr, uint64_t length, char* output,
                                              size_t maxOutputLength) {
-    return static_cast<uint64_t>(ZSTD_decompressDCtx(dctx, output, maxOutputLength, inputPtr, length));
+    auto ret = ZSTD_decompressDCtx(dctx, output, maxOutputLength, inputPtr, length);
+    if (ZSTD_isError(ret)) {
+        throw std::runtime_error(std::string("Error while calling ZSTD_decompressDCtx for zstd. error:") +
```
Comment (wyb) [inline be/src/formats/orc/apache-orc/c++/src/Compression.cc]:
```suggestion
        throw std::runtime_error(std::string("Error while calling ZSTD_decompressDCtx for zstd. error: ") +
```

**Review by wyb — DISMISSED** [review]

File: be/src/formats/orc/apache-orc/c++/src/Compression.cc (hunk 1 above)
Comment (kevincai) [reply be/src/formats/orc/apache-orc/c++/src/Compression.cc]: done

**Comment by alvin-phoenix-ai** [comment]
@cursor review

**Review by dirtysalt — APPROVED** [review]

**Review by alvin-phoenix-ai — APPROVED** [review]
