### PR TITLE
Optimize the scenario of adding/deleting a large number of tables

### LINKED ISSUE #2358: Frequent high concurrency create&delete db or table failure, report failed to acquire catalog lock.
### Steps to reproduce the behavior (Required)
```
fe.log:
2021-12-22 11:21:40,370 ERROR (colocate group clone checker|95) [Daemon.run():121] daemon thread got exception. name: colocate group clone checker
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_252]
        at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_252]
        at com.google.common.collect.AbstractMapBasedMultimap$KeySet$1.next(AbstractMapBasedMultimap.java:929) ~[spark-dpp-1.0.0.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.relocateAndBalanceGroup(ColocateTableBalancer.java:142) ~[starrocks-fe.jar:?]
        at com.starrocks.clone.ColocateTableBalancer.runAfterCatalogReady(ColocateTableBalancer.java:89) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:61) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
2021-12-22 11:21:44,205 WARN (starrocks-mysql-nio-pool-36|298) [StmtExecutor.execute():451] execute Exception, sql SELECT ALL * FROM tab2 AS cor0 LEFT OUTER JOIN tab1 AS cor1 ON 
NULL IS NULL
java.lang.NullPointerException: null
2021-12-22 11:21:55,022 WARN (Thread-43|103) [ReportHandler$ReportTask.exec():234] out of date report version 16401410827811 from backend[10004]. current report version[164014108
27815]
2021-12-22 11:22:06,089 WARN (starrocks-mysql-nio-pool-40|302) [StmtExecutor.handleDdlStmt():908] DDL statement(CREATE TABLE t_9885 (
                                `id` int(18),
                                `value` varchar(20)
                            )
                            ENGINE=OLAP
                            DUPLICATE KEY(`id`)
                            COMMENT "OLAP"
                            DISTRIBUTED BY HASH(`id`) BUCKETS 3
                            PROPERTIES (
                                "replication_num" = "1",
                                "storage_format" = "v2",
                                "colocate_with" = "group_9885"
                            );) process failed.
com.starrocks.common.DdlException: Failed to acquire catalog lock. Try again
        at com.starrocks.catalog.Catalog.createOlapTable(Catalog.java:4088) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.createTable(Catalog.java:3037) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.DdlExecutor.execute(DdlExecutor.java:115) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:900) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.StmtExecutor.execute(StmtExecutor.java:420) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:265) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.dispatch(ConnectProcessor.java:412) ~[starrocks-fe.jar:?]
        at com.starrocks.qe.ConnectProcessor.processOnce(ConnectProcessor.java:648) ~[starrocks-fe.jar:?]
        at com.starrocks.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:55) ~[starrocks-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - master release
```
mysql> select current_version();
+------------------------+
| current_version()      |
+------------------------+
| MASTER_RELEASE 2d0fcb9 |
+------------------------+
```

### PR DESCRIPTION
**Pull request by Astralidea**
Fix #2358 
in this scenario, drop a large number of tables will move to CatalogRecycleBin.
then when he actually deletes the table, he will record a log
this log will take 10ms per table and hold lock for a long time
this PR optimize write log once to reduce the time consumed by this operation.

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java [hunk 1]
```diff
@@ -190,6 +190,7 @@
     public static final short OP_SWAP_TABLE = 10001;
     public static final short OP_ADD_PARTITIONS = 10002;
     public static final short OP_FINISH_MULTI_DELETE = 10003;
+    public static final short OP_MULTI_ERASE_TABLE = 10004;
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/persist/OperationType.java:193]:
```suggestion
    public static final short OP_ERASE_MULTI_TABLES = 10004;
```

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java [hunk 2]
```diff
@@ -263,12 +264,15 @@ private synchronized void eraseTable(long currentTimeMs) {
                 // erase table
                 tableIter.remove();
                 idToRecycleTime.remove(tableId);
-
+                tableIdList.add(tableId);
                 // log
-                Catalog.getCurrentCatalog().getEditLog().logEraseTable(tableId);
-                LOG.info("erase table[{}-{}] finished", tableId, table.getName());
+                LOG.info("erase table[{}-{}] in memory finished", tableId, table.getName());
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:269]: Is it necessary? can we remove this log? Or print log outside the critical block?

Comment (Astralidea) [reply fe/fe-core/src/main/java/com/starrocks/catalog/CatalogRecycleBin.java:269]: it is better to log which table is real  deleted, so we can know if it can be restored.
print log outside the critical block needs to put the table name in the Map and pass it to the outside.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java [hunk 3]
```diff
@@ -152,6 +153,11 @@ public void readFields(DataInput in) throws IOException {
                 isRead = true;
                 break;
             }
+            case OperationType.OP_ERASE_MULTI_TABLES: {
```
Comment (wyb) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java:156]: Better to put it under the drop table operation.

**Comment by wyb** [comment]
The scenario of adding/deleting a large number of databases or partitions also need to be optimized?

**Comment by Astralidea** [comment]
> The scenario of adding/deleting a large number of databases or partitions also need to be optimized?

this will optimize it later near future if encounter this.

File: fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java [hunk 4]
```diff
@@ -184,6 +185,11 @@ public void readFields(DataInput in) throws IOException {
...
```
Comment (gengjun-git) [inline fe/fe-core/src/main/java/com/starrocks/journal/JournalEntity.java:188]: Better to remove the OP_ERASE_TABLE writing function. And comment OP_ERASE_TABLE to deprecated.

**Review by wyb — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
