### PR TITLE
[BugFix] Fix wrong implementation of first_value/last_value/lead/lag with ignore nulls

### LINKED ISSUE #18509: LAG/LEAD IGNORE NULLS have incorrect behavior
**UPDATE**: ignore this first example; there's a better example in my commentt below.

### Steps to reproduce the behavior (Required)
```
CREATE DATABASE TEST1;

CREATE TABLE `TEST1`.`A` (`a` BIGINT, `b` BIGINT, `val` BIGINT)  DISTRIBUTED BY HASH (`a`) PROPERTIES("replication_num" = "1");
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(1,1,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,2,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,3,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(2,4,1);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(3,5,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(3,6,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(4,7,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(4,8,2);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(5,9,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,10,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(200,11,3);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,12,3);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(13,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,14,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,16,4);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(6,17,5);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(201,19,5);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(20,5);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(21,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(22,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(23,6);
INSERT INTO `TEST1`.`A`(`a`,`b`) VALUES(24,6);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(10,25,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(20,26,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(30,27,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(40,28,7);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(10,29,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(20,30,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(30,31,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(40,32,8);
INSERT INTO `TEST1`.`A`(`val`,`a`,`b`) VALUES(50,33,8);


  SELECT
    `A`,
    `VAL`,
    LAG(`VAL` IGNORE NULLS, 2) over (
      order by
        `A` DESC
    ) AS `LAG`
  FROM
    `TEST1`.`A` ORDER BY A DESC;
```
### Expected behavior (Required)
```
"33","50","NULL"
"32","40","NULL"
"31","30","50"
"30","20","40"
"29","10","30"
"28","40","20"
"27","30","10"
"26","20","40"
"25","10","30"
"24","NULL","20"
"23","NULL","20"
"22","NULL","20"
"21","NULL","20"
"20","NULL","20"
"19","201","20"
"17","6","10"
"16","201","201"
"14","6","6"
"13","NULL","201"
"12","201","201"
"11","200","6"
"10","6","201"
"9","5","200"
"8","4","6"
"7","4","5"
"6","3","4"
"5","3","4"
"4","2","3"
"3","2","3"
"2","2","2"
"1","1","2"
```

### Real behavior (Required)
```
A	VAL	LAG
33	50	NULL
32	40	NULL
31	30	50
30	20	40
29	10	30
28	40	20
27	30	10
26	20	40
25	10	30
24	NULL	20
23	NULL	10
22	NULL	10
21	NULL	10
20	NULL	10
19	201	10
17	6	10
16	201	201
14	6	6
13	NULL	201
12	201	6
11	200	6
10	6	201
9	5	200
8	4	6
7	4	5
6	3	4
5	3	4
4	2	3
3	2	3
2	2	2
1	1	2
```

### StarRocks version (Required)
3.0

### LINKED ISSUE #18682: `first value ignore nulls` does not work in window.
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

```sql
create table t(grp int, bal  int, block_height int)ENGINE=OLAP DISTRIBUTED BY HASH(grp) BUCKETS 3 PROPERTIES( "replication_num" = "1");

insert into t values(1, 10, 10), (1, null, 20), (1, null, 5), (2, 10, 10), (2, null, 20), (2, null, 5);

select grp, block_height, bal, first_value(bal ignore nulls) over (partition by grp order by block_height) from t;
```

### Expected behavior (Required)
```
+------+--------------+------+-------------------------------------------+
| grp  | block_height | bal  | first_value(bal) OVER (PARTITION BY grp ) |
+------+--------------+------+-------------------------------------------+
|    1 |            5 | NULL |                                        10 |
|    1 |           20 | NULL |                                        10 |
|    1 |           10 |   10 |                                        10 |
|    2 |            5 | NULL |                                        10 |
|    2 |           20 | NULL |                                        10 |
|    2 |           10 |   10 |                                        10 |
+------+--------------+------+-------------------------------------------+
```
### Real behavior (Required)

```
+------+--------------+------+---------------------------------------------------------------------+
| grp  | block_height | bal  | first_value(bal) OVER (PARTITION BY grp ORDER BY block_height ASC ) |
+------+--------------+------+---------------------------------------------------------------------+
|    2 |            5 | NULL |                                                                NULL |
|    2 |           10 |   10 |                                                                  10 |
|    2 |           20 | NULL |                                                                NULL |
|    1 |            5 | NULL |                                                                NULL |
|    1 |           10 |   10 |                                                                  10 |
|    1 |           20 | NULL |                                                                NULL |
+------+--------------+------+---------------------------------------------------------------------+
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by liuyehcf**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes #18509
Fixes #18682

## lead/lag

Before this pr, this is how `ignore null` being implemented
* `lead(v1 ignore nulls, 2)`, for each row, check if `v[i+2]` is null, if so, keep going forward until find the first non-null value
* `lag(v1 ignore nulls, 2)`, for each row, check if `v[i-2]` is null, if so, keep going backward until find the first non-null value

This is wrong, because we only check if `v[i + offset]` is null, but withouth taking care of `v[i+1], v[i+2], ..., v[i + offset-1]`. So this pr has changed the process
* `lead(v1 ignore nulls, 2)`, for each row, find 2nd non-null value in the forward direction.
* `lag(v1 ignore nulls, 2)`, for each row, find 2nd non-null value in the backword direction.

## first/value

Fix wrong condition.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by liuyehcf** [comment]
run starrocks_be_unittest

**Comment by liuyehcf** [comment]
run starrocks_admit_test

File: be/src/exprs/agg/window.h [hunk 1]
```diff
@@ -440,24 +464,53 @@ class LeadLagWindowFunction final : public ValueWindowFunction<LT, LeadLagState<
...
-        } else {
-            if (!ignoreNulls) {
-                this->data(state).is_null = true;
-                return;
+        // for lead/lag, [peer_group_start, peer_group_end] equals to [partition_start, partition_end]
+        // when lead/lag called, the whole partitoin's data has already been here, so we can just check all the way to the begining or the end
+        if (ignoreNulls) {
+            // lead(v1 ignore nulls, <offset>) has window `ROWS BETWEEN UNBOUNDED PRECEDING AND <offset> FOLLOWING`
+            //      frame_start = partition_start
+            //      frame_end = current_row + <offset> + 1
```
Comment (LiShuMing) [inline be/src/exprs/agg/window.h:472]: Why `frame_end ` depends `current_row ` ? `frame_end ` is partition/window's end?

Comment (liuyehcf) [reply be/src/exprs/agg/window.h:472]: frame_end means window'end, and peer_group_end means partition_end

**Review by satanson — APPROVED** [review]

File: be/src/exprs/agg/window.h [hunk 2]
```diff
@@ -412,9 +422,23 @@ template <LogicalType LT, bool ignoreNulls, bool isLag, typename T = RunTimeCppT
 class LeadLagWindowFunction final : public ValueWindowFunction<LT, LeadLagState<LT>, T> {
     using InputColumnType = typename ValueWindowFunction<LT, FirstValueState<LT>, T>::InputColumnType;
 
+    mutable int64_t offset = 0;
```
Comment (ZiheLiu) [inline be/src/exprs/agg/window.h:425]: Could `offset` stored be in `LeadLagState` instead of a field of `LeadLagWindowFunction`

**Comment by fzhedu** [comment]
add more ut?

File: be/src/exprs/agg/window.h (hunk 2 above)
Comment (liuyehcf) [reply be/src/exprs/agg/window.h:425]: Yes, but unnecessary, it will take more space.

**Comment by liuyehcf** [comment]
> add more ut?

I have added integration tests, please refer to https://github.com/StarRocks/StarRocksTest/pull/1969

**Review by ZiheLiu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
@mergify backport branch-2.5

**Comment by dirtysalt** [comment]
I'll help you to backport that.

**Comment by dirtysalt** [comment]
@Mergify backport branch-3.0
