### PR TITLE
[BugFix] Fix alter job conflicts with partition creation.

### LINKED ISSUE #60895: alter job conflicts with partition creation
Transaction 7060297 killed alter job, but partition p20282_8 already existed.
```
2025-07-14 10:11:20.696+08:00 INFO (thrift-server-pool-53023|2847690) [FrontendServiceImpl.createPartition():2180] Receive create partition: TCreatePartitionRequest(txn_id:7060297, db_id:602275, table_id:5903527, partition_values:[[20282, 8]])
2025-07-14 10:11:20.697+08:00 INFO (thrift-server-pool-53023|2847690) [FrontendServiceImpl.createPartitionProcess():2321] cancel schema change for automatic create partition txn_id=7060297
```
```
2025-07-14 00:01:02.350+08:00 INFO (thrift-server-pool-47994|2593146) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:07.925+08:00 INFO (thrift-server-pool-47993|2593145) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:08.621+08:00 INFO (thrift-server-pool-47686|2565114) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:08.702+08:00 INFO (thrift-server-pool-47047|2517002) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:08.726+08:00 INFO (thrift-server-pool-47351|2538079) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:10.065+08:00 INFO (thrift-server-pool-47978|2593108) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:12.737+08:00 INFO (thrift-server-pool-47232|2531486) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:15.353+08:00 INFO (thrift-server-pool-47690|2565120) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:16.729+08:00 INFO (thrift-server-pool-47353|2538081) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:17.042+08:00 INFO (thrift-server-pool-47997|2593149) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:17.668+08:00 INFO (thrift-server-pool-47989|2593140) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:18.116+08:00 INFO (thrift-server-pool-47423|2542386) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:18.435+08:00 INFO (thrift-server-pool-47346|2538073) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:20.920+08:00 INFO (thrift-server-pool-47250|2531526) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:25.322+08:00 INFO (thrift-server-pool-47679|2565107) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:25.544+08:00 INFO (thrift-server-pool-47340|2538067) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:27.327+08:00 INFO (thrift-server-pool-47972|2593102) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:27.375+08:00 INFO (thrift-server-pool-47681|2565109) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:28.316+08:00 INFO (thrift-server-pool-47988|2593139) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:01:30.976+08:00 INFO (thrift-server-pool-47417|2542380) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:05.421+08:00 INFO (thrift-server-pool-47351|2538079) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:10.290+08:00 INFO (thrift-server-pool-47436|2542399) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:15.318+08:00 INFO (thrift-server-pool-47181|2527292) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:15.347+08:00 INFO (thrift-server-pool-47350|2538078) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:15.623+08:00 INFO (thrift-server-pool-47976|2593106) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:16.108+08:00 INFO (thrift-server-pool-47977|2593107) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:16.283+08:00 INFO (thrift-server-pool-47979|2593109) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:16.683+08:00 INFO (thrift-server-pool-47800|2575706) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
2025-07-14 00:06:16.806+08:00 INFO (thrift-server-pool-46645|2483462) [LocalMetastore.addPartitions():1254] add partition[p20282_8] which already exists
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by zhangheihei**
## Why I'm doing:
Partitions that already exist will still affect the alter job, causing the job to be canceled.
## What I'm doing:

Fixes #60895 

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [x] 3.3

### CODE REVIEW

**Review by meegoo — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 1]
```diff
@@ -2308,20 +2308,25 @@ private static TCreatePartitionResult createPartitionProcess(TCreatePartitionReq
...
+                    CatalogUtils.checkPartitionNameExistForCreatingPartitionNames(olapTable, creatingPartitionNames);
+
             // ingestion is top priority, if schema change or rollup is running, cancel it
             try {
                 String errMsg = "Alter job conflicts with partition creation, for more details please check "
                         + "https://docs.starrocks.io/docs/faq/Others#how-can-i-prevent-expression-partition-conflicts"
                         + "-caused-by-concurrent-execution-of-loading-tasks-and-partition-creation-tasks";
-                if (olapTable.getState() == OlapTable.OlapTableState.ROLLUP) {
+                if (olapTable.getState() == OlapTable.OlapTableState.ROLLUP &&
+                        !creatingPartitionNames.equals(checkExistPartitionName)) {
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java]:
```suggestion
                        creatingPartitionNames.size() != checkExistPartitionName.size()
```

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 2]
```diff
@@ -2308,20 +2308,25 @@ private static TCreatePartitionResult createPartitionProcess(TCreatePartitionReq
...
                     LOG.info("cancel rollup for automatic create partition txn_id={}", request.getTxn_id());
                     state.getLocalMetastore().cancelAlter(
                             new CancelAlterTableStmt(
                                     ShowAlterStmt.AlterType.ROLLUP,
                                     new TableName(db.getFullName(), olapTable.getName())), errMsg);
                 }
 
-                if (olapTable.getState() == OlapTable.OlapTableState.SCHEMA_CHANGE) {
+                if (olapTable.getState() == OlapTable.OlapTableState.SCHEMA_CHANGE &&
```
Comment (banmoy) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java]: dito

**Comment by banmoy** [comment]
could you add a test?

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java (hunk 1 above)
Comment (zhangheihei) [reply fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java]: Using equals() is more defensive than using size().

**Review by banmoy — APPROVED** [review]

**Review by gengjun-git — DISMISSED** [review]

File: fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java [hunk 3]
```diff
@@ -95,6 +95,17 @@ public static Set<String> checkPartitionNameExistForAddPartitions(OlapTable olap
         return existPartitionNameSet;
     }
 
+    public static Set<String> checkPartitionNameExistForCreatingPartitionNames(OlapTable olapTable,
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/catalog/CatalogUtils.java]:
```suggestion
    public static Set<String> getExistingPartitionNames(OlapTable olapTable,
```

File: fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java [hunk 4]
```diff
@@ -2308,20 +2308,25 @@ private static TCreatePartitionResult createPartitionProcess(TCreatePartitionReq
                         " already create partition failed");
             }
 
+            Set<String> checkExistPartitionName =
+                    CatalogUtils.checkPartitionNameExistForCreatingPartitionNames(olapTable, creatingPartitionNames);
+
```
Comment (kevincai) [inline fe/fe-core/src/main/java/com/starrocks/service/FrontendServiceImpl.java:2313]: actually here just need to check if there is any partition name that need to be created in subsequent workflow. So it should be

```
boolean willCreateNewPartition = CatalogUtils.checkIfNewPartitionExists(olapTable, creatingPartitionsNames);
```

the interface `checkIfNewPartitionExists()` can be early return if found any item that needs to be created which should be true in most cases. No need to check every items in the set.

and later in the condition can be changed as the follows

```
if (olapTable.getState() == OlapTable.OlapTableState.ROLLUP &&
                        willCreateNewPartition) {
```

**Review by kevincai — CHANGES_REQUESTED** [review]
please check the review comment.

**Review by kevincai — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
