### PR TITLE
[BugFix] write file repeat close bug

### LINKED ISSUE #10926: Repeat Close File bug
In current implementation, if we fail to close a hdfs/file, we will not set _closed to be true.
Actually the file handler is released, and when the destructor of WritableFile is called,
we will close the file again, close a released file handler in libhdfs will lead to BE crash

### PR DESCRIPTION
**Pull request by xiaoyong-z**
Signed-off-by: xyz <a997647204@gmail.com>

## What type of PR is this：
- [x] bugfix
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #10926

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

In the current implementation, if we fail to close a hdfs/file, we will not set _closed to be true.
The file handler is released, and when the destructor of WritableFile is called,
we will close the file again, close a released file handler in libhdfs will lead to BE crash.

### CODE REVIEW

**Review by imay — APPROVED** [review]

**Review by trueeyu — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

File: be/src/fs/fs_hdfs.cpp [hunk 1]
```diff
@@ -191,9 +191,7 @@ Status HDFSWritableFile::close() {
     });
     Status st = ret->get_future().get();
     PLOG_IF(ERROR, !st.ok()) << "close " << _path << " failed";
-    if (st.ok()) {
-        _closed = true;
-    }
+    _closed = true;
```
Comment (chaoyli) [inline be/src/fs/fs_hdfs.cpp:194]: I think you have to consider the returned error. If the close failed, we could retry to close it and maybe succeed. If you set _closed to be true. It will lead file descriptor leak.

Comment (xiaoyong-z) [reply be/src/fs/fs_hdfs.cpp:194]: https://stackoverflow.com/questions/33114152/what-to-do-if-a-posix-close-call-fails

File: be/src/fs/fs_posix.cpp [hunk 2]
```diff
@@ -230,13 +230,12 @@ class PosixWritableFile : public WritableFile {
...
         int ret;
         RETRY_ON_EINTR(ret, ::close(_fd));
+        _closed = true;
         if (ret < 0) {
             if (s.ok()) {
                 s = io_error(_filename, errno);
             }
         }
-
-        _closed = true;
```
Comment (chaoyli) [inline be/src/fs/fs_posix.cpp:239]: This is right. No necessity to change.

**Review by chaoyli — APPROVED** [review]

**Review by chaoyli — APPROVED** [review]

**Comment by xiaoyong-z** [comment]
@mergify backport branch-2.4
