### PR TITLE
[BugFix] fix str_to_map function in MV

### LINKED ISSUE #40862: 创建物化视图的查询sql只要包含了str_to_map 函数，就会导致写入物化视图的任务失败，无法写入数据
### Steps to reproduce the behavior (Required)
1. CREATE TABLE `sr_ods_test_table` (
`id`  bigint(20)  NOT NULL  COMMENT '主键id' ,
`name` string COMMENT '名称'
)
ENGINE=OLAP
PRIMARY KEY (`ID`)
DISTRIBUTED BY HASH(`ID`)
;

2. INSERT INTO sr_ods_test_table values (1,'测试demo');
3. SELECT id,name,str_to_map(CONCAT_WS(':',id,name),';',':') as mapvalue FROM  sr_ods_test_table;
4. CREATE MATERIALIZED VIEW sr_dw_test_table
COMMENT '物化视图demo'
DISTRIBUTED BY HASH(`id`)
REFRESH ASYNC 
AS
SELECT id,name,str_to_map(CONCAT_WS(':',id,name),';',':') as mapvalue FROM  sr_ods_test_table;
5、查询任务物化视图任务状态
select * from information_schema.tasks;

select * from information_schema.task_runs where task_name = 'mv-55136';
返回 物化视图任务写入失败 ，原因是 只要创建物化视图的 sql 包含str_to_map 方法，其任务状态必失败，导致数据无法写入物化视图

### Expected behavior (Required)
物化视图数据能够正常写入
### Real behavior (Required)
物化视图数据无法写入，任务状态 写入失败
### StarRocks version (Required)
 - 3.1 版本

### PR DESCRIPTION
**Pull request by murphyatwork**
## Why I'm doing:
- `str_to_map` is converted to `str_to_map(split(..))` in parser, which is not acceptable when parsing the generated SQL
- In FE, the function signature is `str_to_map(string, string, string)`, but in BE the signature is `str_to_map(array<string>, string)`, in which the input `1st string` is converted to `array<string>` via `array<string> split(string, string)` function

## What I'm doing:

Fixes #40862

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [ ] 3.0
  - [ ] 2.5

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java [hunk 1]
```diff
@@ -5861,8 +5861,14 @@ public ParseNode visitSimpleFunctionCall(StarRocksParser.SimpleFunctionCallConte
...
             }
-            FunctionCallExpr split = new FunctionCallExpr(FunctionSet.SPLIT, ImmutableList.of(e0, e1), pos);
-            return new FunctionCallExpr(functionName, ImmutableList.of(split, e2), pos);
+            if (e0.getType().isStringType()) {
+                // str_to_map(e0, e1, e2) -> str_to_map(split(e0, e1), e2)
+                FunctionCallExpr split = new FunctionCallExpr(FunctionSet.SPLIT, ImmutableList.of(e0, e1), pos);
+                return new FunctionCallExpr(functionName, ImmutableList.of(split, e2), pos);
+            } else {
+                // str_to_map(split(...), e1)
+                return new FunctionCallExpr(functionName, ImmutableList.of(e0, e1), pos);
```
Comment (fzhedu) [inline fe/fe-core/src/main/java/com/starrocks/sql/parser/AstBuilder.java:5870]: can you show some examples for such case?

**Review by Seaven — DISMISSED** [review]

**Review by Seaven — DISMISSED** [review]

**Review by fzhedu — DISMISSED** [review]

**Comment by mofeiatwork** [comment]
@Mergify rebase

**Review by kangkaisen — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
