### PR TITLE
[BugFix] fix PRangeCell compareTo.

### LINKED ISSUE #59370: Comparison method violates its general contract.
```
com.starrocks.sql.common.DmlException: Refresh materialized view ads_play_basic_dev_educ_view_week failed after retrying 1 times(try-lock 0 times), error-msg : Comparison method violates its general contract!
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doRefreshMaterializedViewWithRetry(PartitionBasedMvRefreshProcessor.java:395) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doMvRefresh(PartitionBasedMvRefreshProcessor.java:326) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.processTaskRun(PartitionBasedMvRefreshProcessor.java:200) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRun.executeTaskRun(TaskRun.java:257) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.TaskRunExecutor.lambda$executeTaskRun$0(TaskRunExecutor.java:57) ~[starrocks-fe.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
	at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
	at java.util.TimSort.mergeCollapse(TimSort.java:448) ~[?:?]
	at java.util.TimSort.sort(TimSort.java:245) ~[?:?]
	at java.util.Arrays.sort(Arrays.java:1515) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
	at java.util.stream.Sink$ChainedReference.end(Sink.java:258) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.starrocks.sql.common.PRangeCellPlus.toPRangeCellPlus(PRangeCellPlus.java:78) ~[starrocks-fe.jar:?]
	at com.starrocks.sql.common.RangePartitionDiffer.generateBaseRefMap(RangePartitionDiffer.java:464) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.mv.MVPCTRefreshRangePartitioner.syncAddOrDropPartitions(MVPCTRefreshRangePartitioner.java:126) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.syncPartitions(PartitionBasedMvRefreshProcessor.java:876) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doRefreshMaterializedView(PartitionBasedMvRefreshProcessor.java:419) ~[starrocks-fe.jar:?]
	at com.starrocks.scheduler.PartitionBasedMvRefreshProcessor.doRefreshMaterializedViewWithRetry(PartitionBasedMvRefreshProcessor.java:367) ~[starrocks-fe.jar:?]
```

### Steps to reproduce the behavior (Required)

Write an unit tests like below:

```java
@Test
public void testComparison() throws AnalysisException {
    final String partitionName = "p1";
    final PartitionKey key1 = PartitionKey.ofDateTime(LocalDateTime.of(2025, 5, 27, 10, 0, 0));
    final PartitionKey key2 = PartitionKey.ofDateTime(LocalDateTime.of(2025, 5, 27, 11, 0, 0));
    final PartitionKey key3 = PartitionKey.ofDateTime(LocalDateTime.of(2025, 5, 27, 12, 0, 0));
    final PartitionKey key4 = PartitionKey.ofDateTime(LocalDateTime.of(2025, 5, 27, 13, 0, 0));

    Range<PartitionKey> r1 = Range.closed(key1, key2);
    PRangeCellPlus cell1 = new PRangeCellPlus(partitionName, r1);
    Assert.assertEquals(0, cell1.compareTo(cell1));

    Range<PartitionKey> r2 = Range.closed(key2, key3);
    PRangeCellPlus cell2 = new PRangeCellPlus(partitionName, r2);
    Assert.assertEquals(-1, cell1.compareTo(cell2));
    Assert.assertEquals(1, cell2.compareTo(cell1));

    Range<PartitionKey> r3 = Range.closed(key3, key4);
    PRangeCellPlus cell3 = new PRangeCellPlus(partitionName, r3);
    Assert.assertEquals(-1, cell2.compareTo(cell3));
    Assert.assertEquals(1, cell3.compareTo(cell2));
    Assert.assertEquals(-1, cell1.compareTo(cell3));
    Assert.assertEquals(1, cell3.compareTo(cell1));

    Range<PartitionKey> r4 = Range.closed(key1, key4);
    PRangeCellPlus cell4 = new PRangeCellPlus(partitionName, r4);
    PRangeCellPlus cell5 = new PRangeCellPlus(partitionName, r3);
    PRangeCellPlus cell6 = new PRangeCellPlus(partitionName, r1);
    Assert.assertEquals(0, cell4.compareTo(cell5));
    Assert.assertEquals(0, cell4.compareTo(cell6));
    Assert.assertEquals(0, cell5.compareTo(cell6));
}
```

It's easy to get a result like below:

```bash
[ERROR] testComparison  Time elapsed: 0.553 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
        at com.starrocks.sql.common.PRangeCellPlusTest.testComparison(PRangeCellPlusTest.java:56)

```

### Expected behavior (Required)

For comparison, we must ensure that when c1 is equal to c2 and c2 is equal to c3, c1 must be equal to c3.

### Real behavior (Required)

Currently, when c1 is equal to c2 and c2 is equal to c3, c1 might be not equal to c3.

### StarRocks version (Required)
 - 3.3.2

### PR DESCRIPTION
**Pull request by wuxueyang96**
## What I'm doing:

Fixes #59370

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.5
  - [x] 3.4
  - [ ] 3.3

### CODE REVIEW

File: fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java [hunk 1]
```diff
@@ -51,10 +51,11 @@ public Range<PartitionKey> getRange() {
      */
     @Override
     public int compareTo(PRangeCell o) {
-        if (isIntersected(o)) {
-            return 0;
+        int res = this.range.lowerEndpoint().compareTo(o.range.lowerEndpoint());
```
Comment (meegoo) [inline fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java:54]: Thank you for your PR. The implementation of the compareTo function does have issues, but it was designed that way for a specific purpose. Directly modifying it to a correct implementation would cause the partition mapping functionality to fail. We will refactor this part of the logic based on your PR.

**Review by meegoo — CHANGES_REQUESTED** [review]

File: fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java (hunk 1 above)
Comment (wuxueyang96) [reply fe/fe-core/src/main/java/com/starrocks/sql/common/PRangeCell.java:54]: Yes, and I have modified all the related code paths. Could you take a look for this?

**Review by LiShuMing — APPROVED** [review]
Well Done. We may update `SyncPartitionBench.java` benchmark result later.

**Review by meegoo — APPROVED** [review]

**Review by HangyuanLiu — APPROVED** [review]
