### PR TITLE
[BugFix] Fix persistent index too large when using a string column in the key definition

### LINKED ISSUE #19475: primary key table index is very large when using a string column in the key definition
### Steps to reproduce the behavior (Required)
create a primary key table with a string in the key
enable persistent index
insert data into the table and look at the size on disk of index.*

### Expected behavior (Required)

In our test example we saw tablet data size 50 MB, index size 900 MB
when removing string column from primary key size of index was reduced to 50 MB
The max length of the string column was 44 bytes.
The total rows in the tablet was 1 million.

### Real behavior (Required)

Index size should be less than 100 MB.

### StarRocks version (Required)
3.0

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes ：

Fixes https://github.com/StarRocks/starrocks/issues/19475

## Problem Summary(Required) ：

In merge compaction of persistent index, we will first estimate the shard num and page num according to the kv data size and kv nums for each key length which will determine the file size of l1. The estimated file size will be slightly larger than the real kv data size generally, but the pr(https://github.com/StarRocks/starrocks/pull/15729) use total kv size to estimate the shard num and page num for each key length. So when the key length takes more values, the size of the l1 file will be bigger and the more disk space is wasted.

This pr add the data size and size of each key length in persistent index so we can estimate the reasonable file size.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [x] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

**Comment by sevev** [comment]
run starrocks_clang-format

**Comment by sevev** [comment]
run starrocks_fe_unittest

**Comment by sevev** [comment]
run starrocks_clang-format

File: be/src/storage/persistent_index.cpp [hunk 1]
```diff
@@ -2382,6 +2396,47 @@ Status PersistentIndex::_load(const PersistentIndexMetaPB& index_meta) {
         _l1_merged_num.emplace_back(-1);
         _has_l1 = true;
     }
+    // if reload, don't update _usage_and_size_by_key_size
```
Comment (chaoyli) [inline be/src/storage/persistent_index.cpp:2399]: It's better to use size and nums

Comment (sevev) [reply be/src/storage/persistent_index.cpp]: > It's better to use size and nums

I check the code and there are too many places in the code where `usage` is used.  I will not change it in this pr to avoid adding burden of this pr review and i will refactor them in a new pr in the future。

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-2.5
