### PR TITLE
[BugFix] fix mv with sql_select_limit

### LINKED ISSUE #38792: MV Rewrite doesn't work well with sql_select_limit variable
### Steps to reproduce the behavior (Required)

1. The `sql_select_limit` is an implicit `LIMIT` for all select statement fired by SQL editors
2. When creating and planning MV, this variable should be ignored, since it's not a select
3. Otherwise, the MV rewrite doesn't work 

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
 - all versions

### PR DESCRIPTION
**Pull request by murphyatwork**
Why I'm doing:

What I'm doing:
1. fix the issue when planning mv with `sql_select_limit`
2. clarify the error message when no valid mv plan for query

Fixes #38792

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.2
  - [x] 3.1
  - [x] 3.0
  - [x] 2.5

### CODE REVIEW

File: fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java [hunk 1]
```diff
@@ -1777,6 +1777,21 @@ public void testPlanCache() throws Exception {
...
+        createAndRefreshMv("CREATE MATERIALIZED VIEW mv_with_select_limit " +
+                " distributed by hash(empid) " +
+                "AS " +
+                "SELECT /*+set_var(sql_select_limit=1000)*/ empid, sum(salary) as total " +
+                "FROM emps " +
+                "GROUP BY empid");
+        starRocksAssert.query("SELECT empid, sum(salary) as total " +
+                "FROM emps " +
+                "GROUP BY empid").explainContains("mv_with_select_limit");
+        starRocksAssert.getCtx().getSessionVariable().setSqlSelectLimit(SessionVariable.DEFAULT_SELECT_LIMIT);
```
Comment (LiShuMing) [inline fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java:1792]: What if query with `sql_select_limit`? can it be rewritten by mv?

"SELECT /*+set_var(sql_select_limit=1000)*/ empid, sum(salary) as total " +
                "FROM emps " +
                "GROUP BY empid"

Comment (mofeiatwork) [reply fe/fe-core/src/test/java/com/starrocks/sql/optimizer/rule/transformation/materialization/MvRewriteTest.java:1792]: 1. the query could contains limit, but MV cannot, which would generate an LimitOperator
2. right now MV planning would ignore this variable, no matter whether you set it or not

**Review by LiShuMing — APPROVED** [review]

**Review by Seaven — APPROVED** [review]
