### PR TITLE
[BugFix]: Unexpected errors from primary table using persistent index

### LINKED ISSUE #7298: row count from primary table with enable_persistent_index true is unstable
### Steps to reproduce the behavior (Required)
1. CREATE TABLE :
```
 CREATE TABLE `pri_tbl_persistent_idx` (
 `k1` date NOT NULL,
 `k2` datetime NOT NULL,
 `k3` varchar(20) NOT NULL,
 `k4` varchar(20) NOT NULL,
 `k5` boolean NOT NULL,
 `v1` tinyint null,
 `v3` int NULL,
 `v2` smallint null,
 `v4` bigint NULL,
 `v5` largeint NULL,
 `v6` float NULL,
 `v7` double NULL,
 `v8` decimal(27,9) NULL
 ) ENGINE=OLAP
 PRIMARY KEY(`k1`, `k2`)
 COMMENT "OLAP"
 DISTRIBUTED BY HASH(`k1`, `k2`) BUCKETS 3
 PROPERTIES (
 "replication_num" = "1",
 "enable_persistent_index" = "true",
 "storage_format" = "v2"
 );
```

2. stream load:
```
[tiannan@starrocks-sandbox04 tn_StarRocksTest]$ curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/tn_StarRocksTest/lib/../common/data/basic_types_data_value_null -XPUT -H label:stream_load_1655296391002 -H "columns:__op='upsert'" http://***.***.***.***:8434/api/pri_test/pri_tbl_persistent_idx/_stream_load
{
    "TxnId": 399202,
    "Label": "stream_load_1655296391002",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 65546,
    "NumberLoadedRows": 65546,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 8791205,
    "LoadTimeMs": 218,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 2,
    "ReadDataTimeMs": 8,
    "WriteDataTimeMs": 178,
    "CommitAndPublishTimeMs": 36
}
```

3. SELECT  :
```
mysql> select count(*) from pri_tbl_persistent_idx;
+----------+
| count(*) |
+----------+
|    36881 |
+----------+
1 row in set (0.04 sec)
```

### Expected behavior (Required)
create table with enable_persistent_index = false:
```
CREATE TABLE `pri_tbl` (
 `k1` date NOT NULL,
 `k2` datetime NOT NULL,
 `k3` varchar(20) NOT NULL,
 `k4` varchar(20) NOT NULL,
 `k5` boolean NOT NULL,
 `v1` tinyint null,
 `v3` int NULL,
 `v2` smallint null,
 `v4` bigint NULL,
 `v5` largeint NULL,
 `v6` float NULL,
 `v7` double NULL,
 `v8` decimal(27,9) NULL
 ) ENGINE=OLAP
 PRIMARY KEY(`k1`, `k2`)
 COMMENT "OLAP"
 DISTRIBUTED BY HASH(`k1`, `k2`) BUCKETS 3
 PROPERTIES (
 "replication_num" = "1",
 "enable_persistent_index" = "false",
 "storage_format" = "v2"
 );
```

stream load the same data:
```
[tiannan@starrocks-sandbox04 tn_StarRocksTest]$ curl --location-trusted -u root: -T /home/disk5/tiannan/sr_cases/tn_StarRocksTest/lib/../common/data/basic_types_data_value_null -XUT -H label:stream_load_1655296391000 -H "columns:__op='upsert'" http://***.***.***.***:8434/api/pri_test/pri_tbl/_stream_load
{
    "TxnId": 399200,
    "Label": "stream_load_1655296391000",
    "Status": "Success",
    "Message": "OK",
    "NumberTotalRows": 65546,
    "NumberLoadedRows": 65546,
    "NumberFilteredRows": 0,
    "NumberUnselectedRows": 0,
    "LoadBytes": 8791205,
    "LoadTimeMs": 164,
    "BeginTxnTimeMs": 0,
    "StreamLoadPutTimeMs": 2,
    "ReadDataTimeMs": 2,
    "WriteDataTimeMs": 142,
    "CommitAndPublishTimeMs": 20
}
```

```
mysql> select count(*) from pri_tbl;
+----------+
| count(*) |
+----------+
|    65536 |
+----------+
1 row in set (0.02 sec)
```

### Real behavior (Required)
row count from primary table with enable_persistent_index true is unstable

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
```
mysql> select current_version();
+----------------------------+
| current_version()          |
+----------------------------+
| BRANCH-2.3-RELEASE 24d9520 |
+----------------------------+
1 row in set (0.01 sec)
```

### PR DESCRIPTION
**Pull request by sevev**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #7298

## Problem Summary(Required) ：

 
If `enable_persistent_index` of primary table is true, and `encoded_key_column` is `BinaryColumn`.  The function `raw_data()` will return a vector of slice as `keys` of PersistentIndex .

However, PersistentIndex required the `keys` is real data because PersistentIndex will read data from `keys` directly. So we will get unexpected error when `encoded_key_column` is `BinaryColumn`

### CODE REVIEW

**Review by chaoyli — APPROVED** [review]

**Comment by sevev** [comment]
run starrocks_be_unittest

**Comment by sevev** [comment]
run all

**Comment by sevev** [comment]
run starrocks_be_unittest

File: be/src/storage/primary_index.cpp [hunk 1]
```diff
@@ -1053,7 +1053,7 @@ Status PrimaryIndex::_insert_into_persistent_index(uint32_t rssid, const vector<
     std::vector<uint64_t> values;
     values.reserve(pks.size());
     _build_persistent_values(rssid, rowids[0], pks, 0, pks.size(), &values);
```
Comment (decster) [inline be/src/storage/primary_index.cpp:1055]: only use rowids[0]?  what if values in `rowids` is not continuous

**Review by decster — APPROVED** [review]
