### PR TITLE
[Bugfix] Exit if BDB failed to open after retried

### LINKED ISSUE #4909: FE transmission to the master fails and does not recover automatically.
### Real behavior (Required)
```text
2022-04-08 10:51:38,748 INFO (stateListener|78) [Catalog$4.runOneCycle():2420] begin to transfer FE type from UNKNOWN to MASTER

2022-04-08 10:51:49,820 WARN (stateListener|78) [BDBEnvironment.openDatabase():293] catch an exception when open database 2936958
com.sleepycat.je.rep.InsufficientReplicasException: (JE 7.3.7) Commit policy: SIMPLE_MAJORITY required 2 replicas. But none were active with this master.
        at com.sleepycat.je.rep.impl.node.DurabilityQuorum.ensureReplicasForCommit(DurabilityQuorum.java:116) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.txnBeginHook(RepImpl.java:1161) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.txnBeginHook(MasterTxn.java:193) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.initTxn(Txn.java:377) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:286) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:265) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.<init>(MasterTxn.java:144) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn$1.create(MasterTxn.java:115) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.create(MasterTxn.java:433) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.createRepUserTxn(RepImpl.java:1135) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.createAutoTxn(Txn.java:332) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockerFactory.getWritableLocker(LockerFactory.java:79) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:800) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:652) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.openDatabase(BDBEnvironment.java:290) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:304) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:834) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1247) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:288) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2455) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]

2022-04-08 10:51:59,821 WARN (stateListener|78) [BDBEnvironment.openDatabase():293] catch an exception when open database 2936958
com.sleepycat.je.rep.InsufficientReplicasException: (JE 7.3.7) Commit policy: SIMPLE_MAJORITY required 2 replicas. But none were active with this master.
        at com.sleepycat.je.rep.impl.node.DurabilityQuorum.ensureReplicasForCommit(DurabilityQuorum.java:116) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.txnBeginHook(RepImpl.java:1161) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.txnBeginHook(MasterTxn.java:193) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.initTxn(Txn.java:377) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:286) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:265) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.<init>(MasterTxn.java:144) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn$1.create(MasterTxn.java:115) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.txn.MasterTxn.create(MasterTxn.java:433) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.createRepUserTxn(RepImpl.java:1135) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.Txn.createAutoTxn(Txn.java:332) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.txn.LockerFactory.getWritableLocker(LockerFactory.java:79) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.setupDatabase(Environment.java:800) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.openDatabase(Environment.java:652) ~[je-7.3.7.jar:7.3.7]
        at com.starrocks.journal.bdbje.BDBEnvironment.openDatabase(BDBEnvironment.java:290) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:226) [starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:308) [starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:834) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1247) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:288) [starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2455) [starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]
2022-04-08 10:51:59,822 ERROR (stateListener|78) [Daemon.run():121] daemon thread got exception. name: stateListener
java.lang.NullPointerException: null
        at com.starrocks.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:226) ~[starrocks-fe.jar:?]
        at com.starrocks.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:308) ~[starrocks-fe.jar:?]
        at com.starrocks.persist.EditLog.open(EditLog.java:834) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.transferToMaster(Catalog.java:1247) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog.access$800(Catalog.java:288) ~[starrocks-fe.jar:?]
        at com.starrocks.catalog.Catalog$4.runOneCycle(Catalog.java:2455) ~[starrocks-fe.jar:?]
        at com.starrocks.common.util.Daemon.run(Daemon.java:119) [starrocks-fe.jar:?]

### StarRocks version (Required)
 - all

### PR DESCRIPTION
**Pull request by padmejin**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #4909

## Problem Summary(Required) ：

Check if open database succeed, if not, will retry several times and then exit.

### CODE REVIEW

**Comment by wanpengfei-git** [comment]
#### [FE PR Coverage check]

:disappointed: **fail** : 6 / 10 (60.00%)




#### file detail

|   |path|covered line|new line|coverage|
|----|----|----|----|----|
|:large_blue_circle:|com/starrocks/journal/bdbje/BDBJEJournal.java|6|10|60.00%|

File: fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java [hunk 1]
```diff
@@ -286,30 +285,35 @@ public synchronized void open() {
...
                 } else {
                     // get last database as current journal database
-                    currentJournalDB = bdbEnvironment.openDatabase(dbNames.get(dbNames.size() - 1).toString());
+                    dbName = dbNames.get(dbNames.size() - 1).toString();
+                }
+
+                currentJournalDB = bdbEnvironment.openDatabase(dbName);
+                if (currentJournalDB == null) {
+                    LOG.warn("fail to open database {}. retried {} times", dbName, i);
+                    continue;
```
Comment (imay) [inline fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:311]: will it be better to sleep 1 second?

Comment (padmejin) [reply fe/fe-core/src/main/java/com/starrocks/journal/bdbje/BDBJEJournal.java:311]: See line 284, sleep on every retry

**Review by imay — APPROVED** [review]

**Review by gengjun-git — APPROVED** [review]
