### PR TITLE
[BugFix] Preserve the order of the producer in the passthrough queue of Adaptive DOP

### LINKED ISSUE #22826: Query result is wrong for ORDER BY and adaptive dop
### Steps to reproduce the behavior (Required)
```sql
set global enable_parallel_merge = true;
```

```
nosetests-3.4 -s --with-xunit --xunit-file=./result/test_adaptive_dop_others_py_TestAdaptiveDopOthers_test_adaptive_dop_others.xml --verbose case/system_case/test_dql/test_adaptive_dop/test_adaptive_dop_others.py:TestAdaptiveDopOthers.test_adaptive_dop_others --nologcapture
```

### Expected behavior (Required)
Pass this test case.

### Real behavior (Required)
Cannot pass it sometimes.

### PR DESCRIPTION
**Pull request by ZiheLiu**
## What type of PR is this:
- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

## Which issues of this PR fixes:

Fixes #22826.

## Problem Summary(Required):

`PassthroughState::_in_chunk_queue` uses `moodycamel::ConcurrentQueue`, which doesn't preserve the order of the input by default.
We must hold the `producer_token` when enqueueing chunks.

## Checklist:

- [x] I have added test cases for my bug fix or my new feature
- [ ] This pr will affect users' behaviors
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto backported to target branch
  - [x] 3.0
  - [ ] 2.5
  - [ ] 2.4
  - [ ] 2.3

### CODE REVIEW

File: be/src/exec/pipeline/adaptive/collect_stats_context.cpp [hunk 1]
```diff
@@ -88,11 +88,12 @@ PassthroughState::PassthroughState(CollectStatsContext* const ctx)
...
 
 bool PassthroughState::need_input(int32_t driver_seq) const {
-    return _in_chunk_queue_per_driver_seq[driver_seq].size_approx() < MAX_PASSTHROUGH_CHUNKS_PER_DRIVER_SEQ;
+    return _in_chunk_queue_per_driver_seq[driver_seq].queue.size_approx() < MAX_PASSTHROUGH_CHUNKS_PER_DRIVER_SEQ;
 }
 
 Status PassthroughState::push_chunk(int32_t driver_seq, ChunkPtr chunk) {
-    _in_chunk_queue_per_driver_seq[driver_seq].enqueue(std::move(chunk));
+    auto& [chunk_queue, token] = _in_chunk_queue_per_driver_seq[driver_seq];
+    chunk_queue.enqueue(token, std::move(chunk));
```
Comment (stdpain) [inline be/src/exec/pipeline/adaptive/collect_stats_context.cpp:96]: maybe we need check the return status from enqueue?

**Review by liuyehcf — DISMISSED** [review]

File: be/src/exec/pipeline/adaptive/collect_stats_context.cpp (hunk 1 above)
Comment (ZiheLiu) [reply be/src/exec/pipeline/adaptive/collect_stats_context.cpp]: Yes. Fixed.

**Review by stdpain — DISMISSED** [review]

**Review by liuyehcf — APPROVED** [review]

**Review by stdpain — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
@Mergifyio backport branch-3.0
