### PR TITLE
[BugFix] The time interval is too short to compaction in TabletUpdatesTest.compaction_with_empty_rowset, need wait for its version.

### LINKED ISSUE #9677: [Bug] TabletUpdatesTest.compaction_with_empty_rowset failed
```
16:54:10 [ RUN      ] TabletUpdatesTest.compaction_with_empty_rowset
16:54:10 *** Aborted at 1659776059 (unix time) try "date -d @1659776059" if you are using GNU date ***
16:54:19 PC: @          0xdb1e6d9 starrocks::TabletUpdates::_apply_compaction_commit()
16:54:19 *** SIGSEGV (@0x0) received by PID 11117 (TID 0x7fb0c431e700) from PID 0; stack trace: ***
16:54:19     @          0xff0c1b2 google::(anonymous namespace)::FailureSignalHandler()
16:54:19     @     0x7fb28a46b630 (unknown)
16:54:19     @          0xdb1e6d9 starrocks::TabletUpdates::_apply_compaction_commit()
16:54:19     @          0xdb0a80c starrocks::TabletUpdates::do_apply()
16:54:19     @          0xdb55b5e starrocks::ApplyCommitTask::run()
16:54:19     @          0xea7a15a starrocks::ThreadPool::dispatch_thread()
16:54:19     @          0xea978cc std::__invoke_impl<>()
16:54:19     @          0xea97225 std::__invoke<>()
16:54:19     @          0xea9661c _ZNSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
16:54:19     @          0xea94f7e std::_Bind<>::operator()<>()
16:54:19     @          0xea91fe2 std::__invoke_impl<>()
16:54:19     @          0xea8f946 _ZSt10__invoke_rIvRSt5_BindIFMN9starrocks10ThreadPoolEFvvEPS2_EEJEENSt9enable_ifIX16is_invocable_r_vIT_T0_DpT1_EESA_E4typeEOSB_DpOSC_
16:54:19     @          0xea8b57d std::_Function_handler<>::_M_invoke()
16:54:19     @          0x6cd7de4 std::function<>::operator()()
16:54:19     @          0xea65b69 starrocks::Thread::supervise_thread()
16:54:19     @     0x7fb28a463ea5 start_thread
16:54:19     @     0x7fb289a7eb0d __clone
16:54:19     @                0x0 (unknown)
16:54:19 run-ut.sh: line 235: 11117 Segmentation fault      ${GTEST_PARALLEL} ${STARROCKS_TEST_BINARY_DIR}/starrocks_test --gtest_filter=${TEST_FILTER} --serialize_test_cases ${GTEST_PARALLEL_OPTIONS}
16:54:19 Build step 'Execute shell' marked build as failure
16:54:19 Finished: FAILURE
```

### PR DESCRIPTION
**Pull request by Linkerist**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9677

## Problem Summary(Required) ：

When number of keys is large or machine is high load, this time interval too short to compaction, the inputs vector is empty, cause the _apply_compaction_rowset crash on this line
https://github.com/StarRocks/starrocks/blob/866275b05e89a5cb7e5cd778753798cbbed002f4/be/src/storage/tablet_updates.cpp#L1325
so wait for its version.

### CODE REVIEW

File: be/test/storage/tablet_updates_test.cpp [hunk 1]
```diff
@@ -1213,7 +1213,11 @@ void TabletUpdatesTest::test_compaction_with_empty_rowset(bool enable_persistent
         keys5.push_back(i * 3 + 2);
     }
     ASSERT_TRUE(_tablet->rowset_commit(5, create_rowset(_tablet, keys5)).ok());
-    std::this_thread::sleep_for(std::chrono::milliseconds(200));
+    {
+        // used for wait merely
```
Comment (chaoyli) [inline be/test/storage/tablet_updates_test.cpp:1217]: Could the compaction wait for the completion?

Comment (Linkerist) [reply be/test/storage/tablet_updates_test.cpp:1217]: in real world procedure, the internal do wait for the completion properly, but this UT call compaction directly, did not walk through the wait logic.

**Review by decster — DISMISSED** [review]

**Review by decster — DISMISSED** [review]

File: be/test/storage/tablet_updates_test.cpp (hunk 1 above)
Comment (chaoyli) [reply be/test/storage/tablet_updates_test.cpp:1217]: I think call the wait may be a better way to handle the exception.

Comment (Linkerist) [reply be/test/storage/tablet_updates_test.cpp:1217]: this is the wait definitely, the _wait_for_version is a private function, this get_applied_rowsets is a wrapper for it, it will call _wait_for_version.

**Review by chaoyli — APPROVED** [review]

**Review by decster — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by sevev** [comment]
@mergify backport branch-2.4

**Comment by sevev** [comment]
@mergify backport branch-2.3
