### PR TITLE
[BugFix] fix ObjectColumn::max_one_element_serialize_size

### LINKED ISSUE #56917: select minus causes BE crash if there is a json column in projection
### Steps to reproduce the behavior (Required)
1. CREATE TABLE '...'
2. INSERT INTO '....'
3. SELECT  '....'

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

### PR DESCRIPTION
**Pull request by silverbullet233**
## What I'm doing:

Fixes #56917

Root Cause:

when building ExceptHashSet, we will allocate serialize buffer memory based on the result of `_get_max_serialize_size` which will invoke `Column::max_one_element_serialize_size`.
But we didn't implement this interface for ObjectColumn and the default return result is 16, which is incorrect for JsonColumn.
This will lead to illegal memory access later, and the allocation of oversized memory is due to this.

image

## What type of PR is this:

- [x] BugFix
- [ ] Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] UT
- [ ] Doc
- [ ] Tool

Does this PR entail a change in behavior?

- [ ] Yes, this PR will result in a change in behavior.
- [x] No, this PR will not result in a change in behavior.

If yes, please specify the type of change:

- [ ] Interface/UI changes: syntax, type conversion, expression evaluation, display information
- [ ] Parameter changes: default values, similar parameters but with different default values
- [ ] Policy changes: use new policy to replace old one, functionality automatically enabled
- [ ] Feature removed
- [ ] Miscellaneous: upgrade & downgrade compatibility, etc.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] This pr needs user documentation (for new or modified features or behaviors)
  - [ ] I have added documentation for my new feature or new function
- [ ] This is a backport pr

## Bugfix cherry-pick branch check:
- [x] I have checked the version labels which the pr will be auto-backported to the target branch
  - [x] 3.4
  - [x] 3.3
  - [x] 3.2
  - [ ] 3.1
  - [ ] 3.0

### CODE REVIEW

**Review by kevincai — DISMISSED** [review]

File: be/src/exec/except_hash_set.cpp [hunk 1]
```diff
@@ -103,8 +104,10 @@ void ExceptHashSet<HashSet>::deserialize_to_columns(KeyVector& keys, Columns& ke
             }
         }
 
-        key_column->deserialize_and_append_batch(keys, chunk_size);
+        TRY_CATCH_BAD_ALLOC(key_column->deserialize_and_append_batch(keys, chunk_size));
```
Comment (trueeyu) [inline be/src/exec/except_hash_set.cpp:107]: Is it possible to expand the scope of the Try-Catch block? The `update_if_overflow` maybe also allocate a large amount of memory.

Comment (silverbullet233) [reply be/src/exec/except_hash_set.cpp]: fixed

**Review by kevincai — DISMISSED** [review]

File: be/src/column/binary_column.cpp [hunk 2]
```diff
@@ -569,8 +569,11 @@ const uint8_t* BinaryColumnBase<T>::deserialize_and_append(const uint8_t* pos) {
 template <typename T>
 void BinaryColumnBase<T>::deserialize_and_append_batch(Buffer<Slice>& srcs, size_t chunk_size) {
     // max size of one string is 2^32, so use uint32_t not T
-    uint32_t string_size = *((uint32_t*)srcs[0].data);
-    _bytes.reserve(chunk_size * string_size * 2);
+    T string_size = 0;
+    for (size_t i = 0; i < chunk_size; i++) {
```
Comment (trueeyu) [inline be/src/column/binary_column.cpp:573]: Performance maybe poor compared with previous implementation.
?

File: be/src/exec/except_hash_set.cpp [hunk 3]
```diff
@@ -104,7 +106,10 @@ void ExceptHashSet<HashSet>::deserialize_to_columns(KeyVector& keys, Columns& ke
         }
 
         key_column->deserialize_and_append_batch(keys, chunk_size);
+        ASSIGN_OR_RETURN(key_column, key_column->upgrade_if_overflow());
```
Comment (trueeyu) [inline be/src/exec/except_hash_set.cpp:109]: Can the caller process `LargeBinaryColumn`?

**Review by satanson — DISMISSED** [review]

**Review by kevincai — APPROVED** [review]

**Review by satanson — APPROVED** [review]
