### PR TITLE
[BugFix] fix intialization of empty global runtime filter

### LINKED ISSUE #9816: Wrong result of tpcds-query01 (iceberg table/with global runtime filter/non-pipeline mode)
### Steps to reproduce the behavior (Required)

to create table

```
SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,PIPES_AS_CONCAT';
create external catalog iceberg_catalog_7c391986_17f4_11ed_b50b_00163e0e489a 
        PROPERTIES("type"="iceberg",
        "iceberg.catalog.type"="hive",
        "iceberg.catalog.hive.metastore.uris"="thrift://172.26.195.10:9083");
use iceberg_catalog_7c391986_17f4_11ed_b50b_00163e0e489a.iceberg_tpcds_1g_orc_gzip;

SET GLOBAL parallel_fragment_exec_instance_num = 8;
set enable_pipeline_engine = false;
set enable_global_runtime_filter = true;
```

query 

> with customer_total_return as (select sr_customer_sk as ctr_customer_sk ,sr_store_sk as ctr_store_sk ,sum(SR_RETURN_AMT) as ctr_total_return from store_returns ,date_dim where sr_returned_date_sk = d_date_sk and d_year =2000 group by sr_customer_sk ,sr_store_sk)  select  c_customer_id from customer_total_return ctr1 ,store ,customer where ctr1.ctr_total_return > (select avg(ctr_total_return)*1.2 from customer_total_return ctr2 where ctr1.ctr_store_sk = ctr2.ctr_store_sk) and s_store_sk = ctr1.ctr_store_sk and s_state = 'TN' and ctr1.ctr_customer_sk = c_customer_sk order by c_customer_id limit 10;

### Expected behavior (Required)

+------------------+
| c_customer_id    |
+------------------+
| AAAAAAAAAAABBAAA |
| AAAAAAAAAAADBAAA |
| AAAAAAAAAAADBAAA |
| AAAAAAAAAAAKAAAA |
| AAAAAAAAAABDAAAA |
| AAAAAAAAAABHBAAA |
| AAAAAAAAAABLAAAA |
| AAAAAAAAAABMAAAA |
| AAAAAAAAAACHAAAA |
| AAAAAAAAAACMAAAA |
+------------------+

### Real behavior (Required)

> MySQL [iceberg_catalog_219b51e8_1857_11ed_aae2_00163e0a8624.iceberg_tpcds_1g_orc_gzip]> with customer_total_return as (select sr_customer_sk as ctr_customer_sk ,sr_store_sk as ctr_store_sk ,sum(SR_RETURN_AMT) as ctr_total_return from store_returns ,date_dim where sr_returned_date_sk = d_date_sk and d_year =2000 group by sr_customer_sk ,sr_store_sk)  select  c_customer_id from customer_total_return ctr1 ,store ,customer where ctr1.ctr_total_return > (select avg(ctr_total_return)*1.2 from customer_total_return ctr2 where ctr1.ctr_store_sk = ctr2.ctr_store_sk) and s_store_sk = ctr1.ctr_store_sk and s_state = 'TN' and ctr1.ctr_customer_sk = c_customer_sk order by c_customer_id limit 10;
Empty set (0.37 sec)

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`

commit id = 420e762

---

```
MySQL [iceberg_catalog_219b51e8_1857_11ed_aae2_00163e0a8624.iceberg_tpcds_1g_orc_gzip]>  select count(*) from store_returns  join [shuffle]  store on sr_store_sk = s_store_sk where s_state = 'TN';
+----------+
| count(*) |
+----------+
|    92374 |
+----------+
1 row in set (0.10 sec)

MySQL [iceberg_catalog_219b51e8_1857_11ed_aae2_00163e0a8624.iceberg_tpcds_1g_orc_gzip]> select count(*) from store_returns  join store on sr_store_sk = s_store_sk where s_state = 'TN';
+----------+
| count(*) |
+----------+
|   277452 |
+----------+
1 row in set (0.09 sec)
```

### PR DESCRIPTION
**Pull request by dirtysalt**
## What type of PR is this：
- [x] bug
- [ ] feature
- [ ] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #9816

## Problem Summary(Required) ：

If we don't call `p->init(0)`, the min/max values are not initialized. 

And for runtime filter who has no min/max value, we can not use generate min/max preidcate from it.

## Checklist:

- [ ] I have added test cases for my bug fix or my new feature
- [ ] I have added user document for my new feature or new function

### CODE REVIEW

**Comment by dirtysalt** [comment]
run starrocks_be_unittest

**Review by DorianZheng — DISMISSED** [review]
LGTM

**Comment by kangkaisen** [comment]
```
And for runtime filter who has no min/max value, we can use generate min/max preidcate from it.
```
what's the meaning?

File: be/src/exprs/vectorized/runtime_filter.h [hunk 1]
```diff
@@ -254,7 +254,11 @@ class RuntimeBloomFilter final : public JoinRuntimeFilter {
     RuntimeBloomFilter() = default;
     ~RuntimeBloomFilter() override = default;
 
-    RuntimeBloomFilter* create_empty(ObjectPool* pool) override { return pool->add(new RuntimeBloomFilter()); };
+    RuntimeBloomFilter* create_empty(ObjectPool* pool) override {
+        auto* p = pool->add(new RuntimeBloomFilter());
+        p->init(0);
```
Comment (kangkaisen) [inline be/src/exprs/vectorized/runtime_filter.h:259]: I think we don't need to init zero.

File: be/src/formats/orc/orc_chunk_reader.cpp [hunk 2]
```diff
@@ -1842,7 +1842,7 @@ void OrcChunkReader::_add_conjunct(const Expr* conjunct, std::unique_ptr<orc::Se
 #define ADD_RF_INT_TYPE(type)                                          \
     case type: {                                                       \
         auto* xrf = dynamic_cast<const RuntimeBloomFilter<type>*>(rf); \
-        if (xrf == nullptr) return false;                              \
+        if (xrf == nullptr || !xrf->has_min_max()) return false;       \
```
Comment (kangkaisen) [inline be/src/formats/orc/orc_chunk_reader.cpp:1845]: `!xrf->has_min_max()`   this check is strange.

File: be/src/exprs/vectorized/runtime_filter.h (hunk 1 above)
Comment (dirtysalt) [reply be/src/exprs/vectorized/runtime_filter.h:259]: it's because in `init`, we have to initialize min/max

```
    void init(size_t hash_table_size) override {
        init_bloom_filter(hash_table_size);
        init_min_max();
    }
```

File: be/src/formats/orc/orc_chunk_reader.cpp (hunk 2 above)
Comment (dirtysalt) [reply be/src/formats/orc/orc_chunk_reader.cpp:1845]: Why? If this runtime filter is empty, possibliy there is no min/max value. It's a defensive programming action.

**Comment by dirtysalt** [comment]
> ```
> And for runtime filter who has no min/max value, we can use generate min/max preidcate from it.
> ```
> 
> what's the meaning?

Sorry, I mean `we can not use that to generate min/max predicate`.

File: be/src/exprs/vectorized/runtime_filter.h (hunk 1 above)
Comment (dirtysalt) [reply be/src/exprs/vectorized/runtime_filter.h:259]: It's critical when merging runtime filters. think this case:

in global runtime filter, we create a (int) empty runtime filter first `p`, min/max value is not initialized, so min/max value is 0

and when we merge runtime filters like
- a [10, 20]
- b [5, 12]
then we have min/max value like [0, 20]. But right range should be [5,20]

**Comment by dirtysalt** [comment]
run starrocks_be_unittest

File: be/src/exprs/vectorized/runtime_filter.h (hunk 1 above)
Comment (kangkaisen) [reply be/src/exprs/vectorized/runtime_filter.h]: if so, I think we should move the init_min_max to constructor， then 1. the _has_min_max is always true, and we needn't _has_min_max field and we needn't check has_min_max also.

Comment (dirtysalt) [reply be/src/exprs/vectorized/runtime_filter.h]: OK.

Comment (dirtysalt) [reply be/src/exprs/vectorized/runtime_filter.h]: For some types, it's very hard to construct min/max value.

**Review by kangkaisen — APPROVED** [review]

**Review by satanson — APPROVED** [review]

**Comment by wanpengfei-git** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
run starrocks_admit_test

**Comment by dirtysalt** [comment]
run starrocks_admit_test
