### PR TITLE
[ISSUE-2319] Bugfix: concurrent assignments of shared_ptr Expr::_constant_column

### LINKED ISSUE #2319: Bug: concurrent assignments of shared_ptr Expr::_constant_column in pipeline engine
### Steps to reproduce the behavior (Required)
1. create table:
ssb tables with 1G data;

2. execute the following sql query which was generated by sqlsmith:
```
select
  subq_0.c2 as c0,
  case when subq_0.c0 >= subq_0.c4 then random() else random() end
     as c1
from
  (select
        pi() as c0,
        ref_0.s_city as c1,
        ref_0.s_suppkey as c2,
        ref_0.s_region as c3,

          sum(
            cast(cast(null as DOUBLE) as DOUBLE)) over (partition by ref_0.s_address,ref_0.s_region order by ref_0.s_address,ref_0.s_name) as c4
      from
        ssb_1g.supplier as ref_0
      where true
      limit 77) as subq_0
where (pi() is NULL)
  and (subq_0.c4 > subq_0.c0)
limit 34;
```

### Expected behavior (Required)
query returns the right result

### Real behavior (Required)
BE crash randomly，no matter the cbo_enable_low_cardinality_optimize is true or false:
```
Core was generated by `/home/disk1/dorisdb/qa_test_master/be/lib/starrocks_be'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f79ee86499c in __memset_sse2 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 elfutils-libelf-0.176-2.el7.x86_64 elfutils-libs-0.176-2.el7.x86_64 glibc-2.17-307.el7.1.x86_64 java-1.8.0-openjdk-headless-1.8.0.262.b10-0.el7_8.x86_64 libattr-2.4.46-13.el7.x86_64 libcap-2.22-10.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 systemd-libs-219-67.el7_7.4.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007f79ee86499c in __memset_sse2 () from /lib64/libc.so.6
#1  0x000000000182f3ad in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, unsigned long> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::rehash(unsigned long) ()
#2  0x000000000182f55f in starrocks::vectorized::ChunkIterator::init_encoded_schema(phmap::flat_hash_map<unsigned int, phmap::flat_hash_map<starrocks::Slice, int, starrocks::vectorized::SliceHashWithSeed<(starrocks::vectorized::PhmapSeed)0>, starrocks::vectorized::SliceEqual, std::allocator<std::pair<starrocks::Slice const, int> > >*, phmap::Hash<unsigned int>, phmap::EqualTo<unsigned int>, std::allocator<std::pair<unsigned int const, phmap::flat_hash_map<starrocks::Slice, int, starrocks::vectorized::SliceHashWithSeed<(starrocks::vectorized::PhmapSeed)0>, starrocks::vectorized::SliceEqual, std::allocator<std::pair<starrocks::Slice const, int> > >*> > >&) ()
#3  0x00000000023f2801 in starrocks::pipeline::OlapChunkSource::_init_olap_reader(starrocks::RuntimeState*) ()
#4  0x00000000023f2f61 in starrocks::pipeline::OlapChunkSource::prepare(starrocks::RuntimeState*) ()
#5  0x00000000022badf2 in starrocks::pipeline::ScanOperator::_pickup_morsel(starrocks::RuntimeState*)
    ()
#6  0x00000000022bb01c in starrocks::pipeline::ScanOperator::pull_chunk(starrocks::RuntimeState*) ()
#7  0x00000000022d34c5 in starrocks::pipeline::PipelineDriver::process(starrocks::RuntimeState*) ()
#8  0x00000000022cb970 in starrocks::pipeline::GlobalDriverDispatcher::run() ()
#9  0x0000000001c89859 in starrocks::ThreadPool::dispatch_thread() ()
#10 0x0000000001c97e85 in starrocks::Thread::supervise_thread(void*) ()
---Type <return> to continue, or q <return> to quit---
#11 0x00007f79ef4ceea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f79ee8d38dd in clone () from /lib64/libc.so.6
(gdb)
```

### StarRocks version (Required)
 - You can get the StarRocks version by executing SQL `select current_version()`
commit id :55df928

### PR DESCRIPTION
**Pull request by satanson**

### CODE REVIEW

File: be/src/exprs/expr.cpp [hunk 1]
```diff
@@ -588,12 +588,18 @@ ColumnPtr Expr::evaluate_const(ExprContext* context) {
...
         return nullptr;
     }
-    if (_constant_column != nullptr) {
-        return _constant_column;
+    // TODO(by satanson):  std::atomic_load(shared_ptr<T>) deprecated in C++20
+    auto old_col = std::atomic_load(&_constant_column);
+    if (old_col) {
+        return old_col;
+    }
+    auto new_col = context->evaluate(this, nullptr);
```
Comment (kangkaisen) [inline be/src/exprs/expr.cpp:596]: evaluate once is enough?

Comment (satanson) [reply be/src/exprs/expr.cpp]: use std::once_flag instead

**Review by ZiheLiu — APPROVED** [review]

**Review by kangkaisen — APPROVED** [review]

**Review by Pslydhh — APPROVED** [review]

**Review by dirtysalt — APPROVED** [review]
